### ISSUE TITLE
Vue.use(VueRouter) raises Uncaught TypeError

### ISSUE THREAD

**Issue by dmarko484** [vuejs/vue-router#10]
Trying to use vue-router with latest vue 0.12beta5 . Almost very first command Vue.use(VueRouter) raises Uncaught TypeError: Cannot read property 'push' of undefined ... Is it compatible with latest vue012@beta5 ?

**Comment by dmarko484** [comment]
Hmm, I got it working simply by using vue-router.js instead of vue-router.min.js. Min version raises the error I mentioned ...

**Comment by yyx990803** [comment]
I don't check in built files during development, so both files are most likely out of date...
