### ISSUE TITLE
Authentication pattern

### ISSUE THREAD

**Issue by holic** [vuejs/vue-router#100]
Any suggestions on how we should structure an application which requires authentication for some routes?

My thought was to use each route component's `canActivate` hook to check against an authentication "service" and, if not authenticated, redirect to the sign in route via `transition.redirect(...)`.

Then I thought since I have a few routes that use this pattern, I might put it into a mixin, but found that I can't use a `route` mixin alongside a `route` config object inside the contructor, e.g.

```js
{
  mixins: [requireAuth],
  route: { ... }
}
```

Another option I thought might work is defining something within each route in `route.map` that I can check for in `router.beforeEach`, then authenticate and redirect if necessary. But it seems there's no way to define extra data on a route (either within the `route.map` object or in a route component's `route` config) that I can check for.

**Comment by yyx990803** [comment]
Both good points. The mixins should definitely be fixed. As for extra properties on route config objects - that's something I had in mind but haven't got time to implement (focusing on 1.0.0-alpha atm)

**Comment by yyx990803** [comment]
See update in 0.6.0: https://github.com/vuejs/vue-router/releases/tag/v0.6.0

**Comment by Clunt** [comment]
minin功能在子路径（subRoutes）中不能很好的merge，只有在顶级路径才可以同methods的行为表现一致，子路径的minin只能简单的覆盖
