### ISSUE TITLE
Char '+' in url encodeURI -ed to '%20' instead of '%2B'

### ISSUE THREAD

**Issue by taxi666** [vuejs/vue-router#1002]
Char '+' in url encodeURI -ed to '%20' instead of '%2B'
then it will be decodeURICompent -ed to ' '

**Comment by fnlctrl** [comment]
Hi, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Thanks!
