### ISSUE TITLE
符号'+'被错误地编码成%20，而不是%2B

### ISSUE THREAD

**Issue by taxi666** [vuejs/vue-router#1003]
<Vue.js & vue-router.js version

2.1.1

Steps to reproduce

后端程序返回的链接里面带有如下的query

userId=UImUwZXM4RE/JI4Vh++NQL4fr5xZA=，会被vue-router编码成userId=UImUwZXM4RE%2FJI4Vh%20%20NQL4fr5xZA%3D
但是应用decodeURIComponent解码却为userId=UImUwZXM4RE/JI4Vh  NQL4fr5xZA=
'+'符号被错误地编码成%20，而不是%2B。

What is Expected?

符号'+'被正确地编码为 %2B

**Comment by fnlctrl** [comment]
根据[HTML标准](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1)，query里的加号表示空格。所以`+`被vue-router正确地替换成了` `(空格)，然后被encodeURIComponent变成了`%20`。

详细解释见 http://stackoverflow.com/questions/2678551/when-to-encode-space-to-plus-or-20

**Comment by eadio** [comment]
所以你最终是怎么解决呢？@taxi666
