### ISSUE TITLE
如何通过this.$router来给每一个route动态设置meta

### ISSUE THREAD

**Issue by chao-hua** [vuejs/vue-router#1006]
### Vue.js / vue-router versions
2.1.2 / 2.1.1

### What is actually happening?
我的需求是：
登录后获取用户资源信息，如xx菜单
我的想法是，获取到信息后，给相应的route来设置meta，然后在router.beforeEach中判断to.meta

但是我给this.$router.options.routes[i]来设置meta，却不能改变this.route.meta
    var appRouter = this.$router.options.routes;
    appRouter[0].meta = {
         auth: true
     }

请问怎么才能动态设置route.meta，而不是在routes中静态定义好，
新手，求解答，感谢。

**Comment by posva** [comment]
Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
