### ISSUE TITLE
Suggest `router.history.length`

### ISSUE THREAD

**Issue by xqyww123** [vuejs/vue-router#1010]
I'm working on a login page which should return to last page if exists or home page, when login success.  `router.go` is a good way but it always return `undefined` whenever success or not. So that I wonder a way to detect whether last page existed in history, or some thing about length of history. `window.history.length` is an available approach currently ( ONLY tested in `hash` mode ), but I'm expecting a formal API.

**Comment by LinusBorg** [comment]
I think your request is a duplicate of #883 - can you verify?

I think this would be a useful feature and I think we will implement it.

**Comment by LinusBorg** [comment]
Will close this as a duplicate - please comment if you think I was wrong.
