### ISSUE TITLE
Allow custom class support in router-link component

### ISSUE THREAD

**Issue by dcgauld** [vuejs/vue-router#1011]
It'd be nice to allow custom classes to be passed through to a `<router-link>` component. I often have a set of button styles that I use, and it'd be awesome if I had a little more control over the styling of any internal links. These classes could then get merged with the active class when the current link was set to "active".

**Comment by posva** [comment]
You can already do that:

```vue
<router-link class="btn btn-success" tag="button"></router-link>
```

As for the active class: http://router.vuejs.org/en/api/options.html#linkactiveclass

**Comment by dcgauld** [comment]
Ah, thanks. Is there any documentation for this? Couldn't seem to find it online. Happy to help write some if not.

**Comment by posva** [comment]
Did you open a feature request issue without even trying if it was possible?

**Comment by dcgauld** [comment]
I just didn't think to even try putting it directly on the component. I presumed (wrongly) that the documented props were the only ones supported.
