### ISSUE TITLE
Transition on Parameter Change

### ISSUE THREAD

**Issue by smyth64** [vuejs/vue-router#1013]
Hey awesome vue people! :D
We are just wondering, how can we actually trigger a transition on params change?

So this is working for something like /home to /post
```
      <transition :name="transitionName">
        <router-view class="child-view"></router-view>
      </transition>
```

But when I try this: /post/123 to /post/323
I have no transition =/

Is there a (global) solution to transition also the param changes?

Thank you so much!

**Comment by simplesmiler** [comment]
Hello!

This is a usage question, and we encourage you to ask it on [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). We try to use the issue tracker for bug reports and feature requests.

As for the question, you can do that with `<router-view :key="$route.params.<your_param>">`.
