### ISSUE TITLE
在使用嵌套路由之后，刷新页面，应用的「上下文」就随之改变，导致相对路劲应用的资源报错！

### ISSUE THREAD

**Issue by Jiiiiiin** [vuejs/vue-router#1015]
我使用的requirejs加载应用资源，在使用了一个嵌套路由地址之后，应用的上下文就随之改变了，在刷新嵌套路径浏览器地址的时候：

使用的是: history模式
```js
 {
                name: 'order',
                path: '/order',
                component: function (resolve) {
                    require(['order/tmpl'], resolve)
                },
                children: [
                    {
                        name: 'orderList',
                        path: 'list',
                        component: function (resolve) {
                            require(['order/list'], resolve)
                        }
                    }
                ]
            },
```

刷新页面之后：
GET http://localhost:7000/order/css/index.css 
list:30 GET http://localhost:7000/order/js/lib/temp-files/assets/js/modernizr.min.js 
list:64 GET http://localhost:7000/order/js/bower_components/requirejs/require.js 

应用的上下文就多了一个【order】，嵌套路由的父级path；

请问这样怎么解决？

**Comment by posva** [comment]
Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behaviour you described.

**Comment by fnlctrl** [comment]
跟vue-router无关，请修正你的requirejs配置。

**Comment by Jiiiiiin** [comment]
@fnlctrl 那看来只能搞一个上下文配置了。谢谢
