### ISSUE TITLE
In wechat browser, i use iphone 3D touch to back to the last page, the history is wrong

### ISSUE THREAD

**Issue by w2819** [vuejs/vue-router#1017]
It works well when use the browser back button.
As the title,when i use 3D touch back to the last page, it will go index first,then flash, then go the last page.
And i use it again, it will sign out off the WeChat Subscripti.
ios version: 10.1.1
wechat version: 6.5.1
vue version: 1.0.28
vue-router version: v0.7.13

**Comment by posva** [comment]
Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behaviour you described.

**Comment by w2819** [comment]
https://vux.li/?x-page=oschina#!/
This project has this problem yet,in wechat browser you can reproduce it.

**Comment by posva** [comment]
I doubt it's enough to test it. I cannot test it myself because I don't have wechat. @fnlctrl Is the version of wechat too old or something? Is this something we can even fix?

**Comment by fnlctrl** [comment]
I don't have an iphone 😂 And I don't think it's something we can fix (since the browser back button works fine). Closing now, as it seems to be wechat-related.

**Comment by w2819** [comment]
The customer raised this question,so i found this.
