### ISSUE TITLE
About documentation

### ISSUE THREAD

**Issue by kazupon** [vuejs/vue-router#102]
What does `we are already breaking our application into components` mean ?
https://github.com/vuejs/vue-router/blame/dev/docs/basic.md#L3

I translate vue-router documentation for japanese users now. (WIP)
https://github.com/kazupon/vue-router/commits/translate_docs_ja

Would you tell me that detail ?

Thanks for your great plugin !! :smiley:

**Comment by yyx990803** [comment]
It's more like "dividing" instead "breaking". "分割"です。

**Comment by kazupon** [comment]
I see.
Thanks !!
