### ISSUE TITLE
Commas don't need to be encoded in query component

### ISSUE THREAD

**Issue by robertkern** [vuejs/vue-router#1027]
### Vue.js / vue-router versions
2.1.5 / 2.1.1

### Steps to reproduce
```
router.push({path: 'foo', query: {
  bar: '1,2'
}})
```

### What is happening and what is expected?
Currently the router will redirect to `foo?bar=1%2C2` which is fine and works. Using comma as a sub-delimiter is very common these days and it's much nicer to see `foo?bar=1,2`

According to http://stackoverflow.com/questions/2366260/whats-valid-and-whats-not-in-a-uri-query rfc3986 allows unencoded commas as sub-delimiters in the query component.

I think the default could/should stay as encoding the full query string but an option to allow unencoded commas (or whatever the sub-delimiter is) would be really useful.

**Comment by fnlctrl** [comment]
Looks like it's caused by `encodeURIComponent`:
> encodeURIComponent(',')
> "%2C"

Maybe we should do something like `encodeURIComponent(queryValue).replace(/%2C/, ',')`?

**Comment by posva** [comment]
@fnlctrl Yes, there may be more characters that can be replaced back 😞 
Let's start with the commas I guess

**Comment by posva** [comment]
I investigated a bit more and I think that:

- we should keep the default behaviour the way it is because it's safer
- add a prop/option for the `router-link` and the `router.push` method to: _not encode/encode only some/use your own encode method_

@fnlctrl @yyx990803 WDYT?

**Comment by fnlctrl** [comment]
@posva  Yeah, an option to disable the default behavior of calling `encodeURIComponent` on query params should do.
