### ISSUE TITLE
router-link's in a v-for not rendering?

### ISSUE THREAD

**Issue by dflock** [vuejs/vue-router#1028]
### Vue.js / vue-router versions
2.1.6 / 2.1.1

### Reproduction Link
https://jsfiddle.net/duncanlock/pbb7swvr/1/

### Steps to reproduce

Look at the fiddle and look at the HTML. This is the part that outputs the links in the result:

```
<ul>
  <li><router-link to="/">/</router-link></li>
  <li><router-link to="/other">/other</router-link></li>
  <hr />
  <li v-for="route in this.$router.options.routes">
    <router-link :to="route.path" />
  </li>
</ul>
```

### What is Expected?

I was expecting to see two links, an `<hr />` then two more links.

### What is actually happening?

I get two links, an `<hr>` then two empty `<li>`'s.

The `router-link`s in the `v-for` don't seem to render any output. When I do this locally, with similar code, I can see all four `<RouterLink>` elements in the Vue dev tools, but only the first two (the "hard coded" ones), render a link on the page. All four `<RouterLink>` elements in the Vue dev tools have the expected properties and look like they should all work?

I'm new to `vue-router` so I'm sure I'm probably doing something silly here, but I'm not sure why this doesn't work?

What I'm actually trying to do is have a sidebar component that outputs the links from the Apps `router.options.routes`, rather than repeating/hard coding them.

**Comment by dflock** [comment]
If I do it like this instead, it works:

```
<li v-for="route in this.$router.options.routes">
  <a :href="'#' + route.path">{{ route.name }}</a>
</li>
```

... but then I'm not using `router-link`, contrary to the advice [here](https://router.vuejs.org/en/api/router-link.html).

**Comment by dflock** [comment]
Hmm, this seems to do what I wanted & works as expected:

```
<ul>
  <router-link v-for="route in this.$router.options.routes" tag="li" :to="route.path">
    <a>{{ route.name }}</a>
  </router-link>
</ul>
```

Found that at the bottom of [this page](https://router.vuejs.org/en/api/router-link.html), while trying to figure out getting active classes to work with the previous 'solution'.

I still think the initial behaviour was weird - creating the `RouterLink` objects in dev tools, but not rendering anything?

**Comment by fnlctrl** [comment]
https://jsfiddle.net/oenbobop/

You didn't put any content inside `<router-link>` so it won't show anything in the page. But if you inspect it with Chrome devtools you would see the `<a>` tags rendered correctly.
