### ISSUE TITLE
Instance bug

### ISSUE THREAD

**Issue by lucifercd** [vuejs/vue-router#1029]
document bug：
const app = new Vue({
  router
}).$mount('#app')

is't work

must be:
const app = new Vue({
  router,
  render: h => h(App)
}).$mount('#app')

### Vue.js / vue-router versions
2.1.2 / 2.1.1

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. Questions should be posted on the [forum](https://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

**Comment by LinusBorg** [comment]
@lucifercd The part you see as a "bug" is actually used eactly like this in the jsfiddle that is linked to directly  below the code example - and it works:

http://jsfiddle.net/yyx990803/xgrjzsup/

**Comment by lucifercd** [comment]
@LinusBorg main.js in the vue-cli must add `render: h => h(App)`,then is works. I think there is many pepole don't understand it，so I think is a problem : )

`// The Vue build version to load with the `import` command
// (runtime-only or standalone) has been set in webpack.base.conf with an alias.
import Vue from 'vue'
import App from './App'

import VueRouter from 'vue-router'

Vue.use(VueRouter)

/* eslint-disable no-new */



const Foo = { template: '<div>foo</div>' }
const Bar = { template: '<div>bar</div>' }

const routes = [
  { path: '/foo', component: Foo },
  { path: '/bar', component: Bar },
  { path: '/hello', component: require('./components/Hello.vue')}
]


const router = new VueRouter({
  routes // （缩写）相当于 routes: routes
})


const app = new Vue({
  router,
  render: h => h(App)
}).$mount('#app')`
