### ISSUE TITLE
How to set component to nested router-view?

### ISSUE THREAD

**Issue by bissolli** [vuejs/vue-router#1030]
Hey guys!

I have the following router-view structure:
 - router-view:default
       - router-view:tab (it's nested on my default router-view)
 - router-view:modal

So I would like to do my router to Open my modal but I would like to choose what is opening behind it!

```
{
        name: 'leads.show.quotations.create',
        path: '/leads/:id/quotations/create',
        components: {
            default: Show,
            'default.tab': Quotations,
            modal: Add
        },
        meta: { requiresAuth: true }
}
```
The code above does not work! I have tried replace 'default.tab' for only tab and it does work neither!

Any ideias? I just want to keep my modals controlled my VueRouted and that's was my solution!

When there is no sub component it works great! But when there is those sub components it breaks!

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only, and we encourage you to use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions or for discussion. Thanks!
