### ISSUE TITLE
Use the function abort() to prevent history.back() more than twice,then history.back() can't go last page.

### ISSUE THREAD

**Issue by w2819** [vuejs/vue-router#1031]
version:  "vue-router": "^0.7.13","vue": "^1.0.28"

browser history: index -> list-> detail->buy

buy.vue:
`<a @click="back">back</a>`
`back:()=>history.back()`

I confirm user when click the back button
i do this in router because i want prevent the browser's back button too
`router.beforeEach(({to, from, next, abort}) => {`
`let confirm = window.confirm('are you sure to leave this page?')`
  `if(confirm){`
    `abort()`
  `}else{`
    `next()`
  `}`
`})`

I click the back button first time, and abort,do it again.
then i click it the third time,do next,it go index but not detail...

**Comment by fnlctrl** [comment]
Hi, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Thanks!

**Comment by fnlctrl** [comment]
Seems to be the same issue of which was addressed by https://github.com/vuejs/vue-router/pull/894. Though it's not fixed for 0.7

**Comment by 327326724** [comment]
thank you

**Comment by w2819** [comment]
thank you , can you fix it?

**Comment by w2819** [comment]
is there anybody to fix this?

**Comment by Jialufeng** [comment]
```
new Vue({
    el: '#vueApp',
    data: {
        debug: true,
        users: [],
        xhr_request:[]
    },
    beforeDestroy:function() {
        for (var i = 0; i < this.xhr_request.length; i++) {
            this.xhr_request.shift().abort();
        }
    },
    methods: {
        loadUsers: function() {
            this.$http.get('https://jsonplaceholder.typicode.com/users', 
                 function(data, status, request) {
                     if(status == 200) { 
                          this.users = data;
                 }
            },
             { beforeSend: function(xhr) { 
                     this.xhr_request.push(xhr);
           }
      });
            console.log(this.$http());
}
}
});

当还有在执行的ajax时候，取消ajax
```
