### ISSUE TITLE
Routes match issue

### ISSUE THREAD

**Issue by rwu823** [vuejs/vue-router#1032]
### Vue.js / vue-router versions
2.1.6 / 2.1.1

### Reproduction Link
https://jsfiddle.net/huv1yc2y/5/

### Steps to reproduce
Click the each link and looks the result.

### What is Expected?
If link to `/foobar`, the path `/foo` shouldn't be matched.

### What is actually happening?
If the routes begin with a same word it'll be matched both.

**Comment by fnlctrl** [comment]
http://router.vuejs.org/en/api/router-link.html

> exact
> type: boolean
> default: false
> The default active class matching behavior is inclusive match. For example, <router-link to="/a"> will get this class applied as long as the current path starts with /a.
> One consequence of this is that <router-link to="/"> will be active for every route! To force the link into "exact match mode", use the exact prop:
>
> ```html
> 
> <router-link to="/" exact>
> ```
