### ISSUE TITLE
this.$route for the parent component takes the value of the child component.

### ISSUE THREAD

**Issue by fenixphp** [vuejs/vue-router#1033]
### Vue.js / vue-router versions
2.1.2 / 2.1.1

### Reproduction Link
https://jsfiddle.net/9r6xhqbp/4/

**Comment by fnlctrl** [comment]
http://router.vuejs.org/en/advanced/meta.html

>First, each route object in the routes configuration is called a route record. Route records may be nested. Therefore when a route is matched, it can potentially match more than one route record.

>For example, with the above route config, the URL /foo/bar will match both the parent route record and the child route record.

>All route records matched by a route are exposed on the $route object (and also route objects in navigation guards) as the $route.matched Array. Therefore, we will need to iterate over $route.matched to check for meta fields in route records.
