### ISSUE TITLE
Could you add an example covering a more complex setup? (webpack template)

### ISSUE THREAD

**Issue by gplusdotgr** [vuejs/vue-router#1035]
The documentation explains how to setup a "one file" app, but what happens when we're using for example the webpack-template? (I know that there's a decision to keep the template simple)
Could we have a more detailed example, especially using .Vue templates and 1-2 components/pages?

**Comment by LinusBorg** [comment]
Could you explain a bit what you are missing?

To me (and I may be blind to this as I'm too close), the only thing different when using this in e.g. the webpack template, is that you can put the components in their own modules and import them (as well as the routes object, if you want to). The rest can just stay the same as in the examples, right in main.js.

But I don't think it i is (nor should be) the router doc's job to teach people about `import` & `export`. You need to know about that anyway if you want to use the webpack template.

So it seems that I missing something. What would help you to fell more secure in what you are trying to achieve?

**Comment by gplusdotgr** [comment]
You're of course partly right. In the end I did manage to integrate vue-router to my setup, and yes it's a matter of "imports/exports" as you said. But I feel there could be, alongside with the simple example, one a bit more advanced showing what the proper architecture could be for app with a couple more available components. 
Just feel there's a gap in the documentation there, it could even just be a link towards /examples/ of the repo, and not a full inline code block.

**Comment by posva** [comment]
Vue doesn't (and will probably never) force you to use a specific architecture. You should use what you and your team are more comfortable with.

I think this is what you're looking for: https://github.com/vuejs/vue-hackernews-2.0

In that example, components are in a component folder. You can then create subfolders relating to the business logic.
For instance, you could do it differently:

```
Posts /
  > views/
    > MyPosts.vue
  > components/
    > Post.vue
    > Comment.vue
Profile/
  > views/
    MyProfile.vue
    PublicProfile.vue
  > components/
    Profile.vue
```

**Comment by gplusdotgr** [comment]
Thanks.
