### ISSUE TITLE
Custom (non-mouse) events do not work on router-link

### ISSUE THREAD

**Issue by TremayneChrist** [vuejs/vue-router#1036]
Only mouse events seem to work on `router-link` due to `guardEvent`
```
if (e.button !== 0) return
``` 
The `button` property is only available in `MouseEvent` I believe. Therefore, using `CustomEvent` is a no go. For example, using a tap event on mobile devices.

https://jsfiddle.net/qaj7xyx9/1/

**Comment by fnlctrl** [comment]
Good catch, thanks!
