### ISSUE TITLE
When page redirect to the same component with another alias, the created hook only invoked once

### ISSUE THREAD

**Issue by lifeforfun** [vuejs/vue-router#1038]
### Vue.js / vue-router versions
2.1.3 / 2.1.1

### Reproduction Link
Demo: [here](http://codepen.io/HugeWorld/pen/XNQjeW)

### Steps to reproduce
1. Create a route route with path **/a**, which although has an alias **/b**
2. Navigate to **/a** then to **/b**

### What is Expected?
Although two page point to the same component, the **beforeRouteEnter** hook and **created** hook should be invoked twice.
At lease the **created** hook should be invoked twice, because some initial operation would be bind to **this**(component's context)

### What is actually happening?
Those hooks only invoked once.

**Comment by posva** [comment]
That's an expected behaviour: it's the same route, there's no navigation and therefore the same component is kept

**Comment by lifeforfun** [comment]
But does the **beforeRouteEnter** hook should be invoked at least?

**Comment by posva** [comment]
No, there's no navigation. You should watch the $route property if you need to reach to a change
