### ISSUE TITLE
It's a bug?

### ISSUE THREAD

**Issue by spivet** [vuejs/vue-router#1039]
```html
<router-link to="/report/quiz" active-class="report__item_acitve"></router-link>  
<router-link to="/report/quizSummary" active-class="report__item_acitve"></router-link>  
```
```javascript
      { path: 'quiz', component: Quiz },
      { path: 'quizSummary', component: QuizSummary }
```
When I click the button `quizSummary`, the button `quiz` also be activated

**Comment by fnlctrl** [comment]
Hi, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Thanks!
