### ISSUE TITLE
编程式的导航，怎么打开一个新窗口

### ISSUE THREAD

**Issue by AaronChen2012** [vuejs/vue-router#1040]
编程式的导航，怎么打开一个新窗口

**Comment by fnlctrl** [comment]
你好，请使用[论坛](http://forum.vuejs.org/)或[gitter](https://gitter.im/vuejs/vue)提问，issue列表只用于提交bug和feature request，谢谢！

**Comment by PleaseTryAgain** [comment]
我也有这个问题，该怎么实现？
