### ISSUE TITLE
router.afterEach guard is not called when another route is cancelled with next(false)

### ISSUE THREAD

**Issue by gholol** [vuejs/vue-router#1048]
The router.afterEach() hook is not called when I cancel the route with next(false) inside beforeRouteEnter()
https://jsfiddle.net/zxfs1x7s/

Is this a bug or a feature? I want to stop the progressbar that runs beforeEach and stops afterEach route.

**Comment by LinusBorg** [comment]
Well, afterEach() is supposed to run when a route transition finishes. Since you canceled, there was no transition to finish, so I would not consider this to be a bug.

**Comment by posva** [comment]
what @LinusBorg said

**Comment by jasonbodily** [comment]
@gholol - What'd you do to stop the progress bar? Is there a 'route cancelled' mechanism?

**Comment by naifen00** [comment]
since v2.4.0+
i do so [https://jsfiddle.net/74ak9w5e/](https://jsfiddle.net/74ak9w5e/)

**Comment by kimini507** [comment]
Hi guys, how do you handle back then resolving to same route through redirect?

let's say this:

login => home => browser back button => login guard activates that redirects it to home

in this case, afterEach is not called
