### ISSUE TITLE
Need an example of making an ajax call to a backend API

### ISSUE THREAD

**Issue by ralyodio** [vuejs/vue-router#1049]
The example in the docs shows this:

      // replace getPost with your data fetching util / API wrapper
      getPost(this.$route.params.id, (err, post) => {
        this.loading = false
        if (err) {
          this.error = err.toString()
        } else {
          this.post = post
        }
      })

...but I don't have any idea what `getPost()` should be doing. I tried just using `fetch(url).then(handleData)` but I get `fetch is undefined`

I've looked around and saw examples using `this.$http.get(url)` but I get `$http is undefined` on that example too.

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. Questions should be posted on the [forum](https://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

The getPost is in another file: https://github.com/vuejs/vue-router/blob/dev/examples/data-fetching/api.js

Fetch may not be available in your browser http://caniuse.com/#search=fetch

**Comment by ralyodio** [comment]
You should add how to make an http call to the docs. This is pretty basic stuff for a client side framework that is not mentioned.

I found I can do use axios
``` js

import axios from 'axios'
Vue.prototype.$http = axios

...

this.$http.get(url)
.then(data => {
   this.items = data
});

```
....for anyone else who is wondering.
