### ISSUE TITLE
Router-link with slot and conditional component fails

### ISSUE THREAD

**Issue by johnleider** [vuejs/vue-router#1051]
### Vue.js / vue-router versions
2.1.7 / 2.1.1

### Reproduction Link
https://jsfiddle.net/fpyuz7f8/

### Steps to reproduce
Create a two components. One should contain a router-link with a conditional on the first component and a slot.

### What is Expected?
Render router-link with slot and conditional component

### What is actually happening?
Uncaught TypeError: Cannot read property 'context' of undefined

### Additional
I encountered this while working on my framework. When upgrading to Vue@2.1.7 I would get an error during render. An example of my component is [here](https://github.com/vuetifyjs/vuetify/blob/master/src/components/sidebar/SidebarItem.vue). This can be fixed by removing the conditional, placing the component as a child, and putting the conditional on the new parent, example:

```html
<router-link>
  <div v-if="active">
    <component></component>
  </div>
  <slot></slot>
</router-link>
```

**Comment by fnlctrl** [comment]
Seems to be fixed with vue 2.1.8 (the original fiddle doesn't give warnings anymore since unpkg serves vue@2.1.8 now by default), please reopen if otherwise.
