### ISSUE TITLE
Doc: Named Views JSFiddle demo has extra <div id="app">

### ISSUE THREAD

**Issue by anishkny** [vuejs/vue-router#1054]
### Vue.js / vue-router versions
2.1.2 / 2.1.1

### Reproduction Link
https://router.vuejs.org/en/essentials/named-views.html#

### Steps to reproduce
Click on link in "A working demo of this example can be found here." (https://jsfiddle.net/posva/6du90epg/)

### What is Expected?
HTML in demo should not have unnecessary extra div element.

### What is actually happening?
HTML has unnecessary extra div element:

`<div id="app">`

@posva

**Comment by posva** [comment]
Hey, thanks for pointing that out!
It's now fixed
