### ISSUE TITLE
Multiple router-link-active when route match pattern

### ISSUE THREAD

**Issue by billyshena** [vuejs/vue-router#1055]
Hello everyone ! I am currently facing a strange issue using Vue js 2.0 and router (2.1.1)
Given the route "/user/:id", whenever I have /user/1 or /user/1* (it will append router-link-active class)
Ex: /user/11, /user/111, /user/1111 etc. all router-links that have this path will be set as active, causing multiple links to have the active class.
I guess it is a bug with Vue router itself, any ideas ?

Best,

**Comment by kazupon** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
Thanks!

**Comment by Yawenina** [comment]
Maybe `exact` prop can help you out.

See: http://router.vuejs.org/en/api/router-link.html

**Comment by dulerong** [comment]
@yamanoku Thank you so much!
