### ISSUE TITLE
Using $route.go update query, but the component dose not rerender

### ISSUE THREAD

**Issue by luxueyan** [vuejs/vue-router#1056]
### Vue.js / vue-router versions
2.1.6 / 2.1.1

### Steps to reproduce

 A component which init data rely on the $route.query. When the query update but the component dose not rerender.
### What is Expected?
The query changed and the component rerender the same!
### What is actually happening?
The component dose not rerender!

ps: I expect the router query can be setted  for the children view, and the query  is watched automatically! When the query changes, the child view will rerender!   Angular ui-router has this feature

**Comment by fnlctrl** [comment]
https://router.vuejs.org/en/advanced/data-fetching.html
You need to set a watcher on `$route` to react to query changes.

**Comment by simplesmiler** [comment]
Also note, that in 2.x `router.go` was replaced with `router.push`.

**Comment by luxueyan** [comment]
@fnlctrl   I did so, but i think it is not a good experience ，i must set watcher everywhere when a component needed. If it can be watched automatically by setting in router, will be nice!

**Comment by posva** [comment]
@luxueyan It's better to watch the route when needed than having the whole view rerendered even when the route is the same.

**Comment by luxueyan** [comment]
@posva Yes ，If consider the performance, it may be better .
