### ISSUE TITLE
old sumsang  and huawei oppo the vue router is no work

### ISSUE THREAD

**Issue by ckken** [vuejs/vue-router#1057]
many app or framework is no work in old sumsang android 4.4 or android 6
http://elemefe.github.io/mint-ui/#/action-sheet
http://shinygang.coding.me/#/list
but nuxt is work
https://custom-routes.nuxtjs.org/

**Comment by posva** [comment]
Those phones are probably using a very outdated browser that is not supported by Vue.
Otherwise, everything works fine on android 6.
@ckken  Can you give more details about the phones, please? I couldn't find the models you were talking about. Oppo seems to have a lot of versions. I suppose you mean samsung and not sumsang

**Comment by ckken** [comment]
@posva 
```
{
    "battery":{
        "onlevelchange":null,
        "ondischargingtimechange":null,
        "onchargingtimechange":null,
        "onchargingchange":null,
        "level":0.77,
        "dischargingTime":0,
        "chargingTime":null,
        "charging":false
    },
    "geolocation":{

    },
    "control":{

    },
    "browserLanguage":"zh-CN",
    "onLine":true,
    "cookieEnabled":true,
    "vendorSub":"",
    "vendor":"UCWEB",
    "productSub":"20030107",
    "product":"Gecko",
    "mimeTypes":{
        "length":0
    },
    "plugins":{
        "length":0
    },
    "platform":"Linux armv7l",
    "userAgent":"HUAWEI_MT7-TL10_TD/6.0 Android/6.0 (Linux; U; Android 6.0; zh-cn) Release/01.18.2014 Browser/WAP2.0 (AppleWebKit/537.36) Mobile Safari/537.36",
    "language":"zh-CN",
    "appVersion":"6.0 Android/6.0 (Linux; U; Android 6.0; zh-cn) Release/01.18.2014 Browser/WAP2.0 (AppleWebKit/537.36) Mobile Safari/537.36",
    "appName":"Netscape",
    "appCodeName":"Mozilla"
}
```

**Comment by ckken** [comment]
@posva the navigator , im sorry , i mean samsung

**Comment by ckken** [comment]
wechat x5 core is ok, all wechat webview is ok

**Comment by ckken** [comment]
```
{
    "geolocation":{

    },
    "doNotTrack":null,
    "webkitPersistentStorage":{

    },
    "webkitTemporaryStorage":{

    },
    "onLine":true,
    "cookieEnabled":true,
    "vendorSub":"",
    "vendor":"Google Inc.",
    "productSub":"20030107",
    "product":"Gecko",
    "mimeTypes":{
        "length":0
    },
    "plugins":{
        "length":0
    },
    "platform":"Linux armv7l",
    "userAgent":"Mozilla/5.0 (Linux; Android 4.3; zh-cn; SAMSUNG SM-N7506V Build/JLS36C) AppleWebKit/537.36 (KHTML, like Gecko) Version/1.5 Chrome/28.0.1500.94 Mobile Safari/537.36",
    "language":"zh-CN",
    "appVersion":"5.0 (Linux; Android 4.3; zh-cn; SAMSUNG SM-N7506V Build/JLS36C) AppleWebKit/537.36 (KHTML, like Gecko) Version/1.5 Chrome/28.0.1500.94 Mobile Safari/537.36",
    "appName":"Netscape",
    "appCodeName":"Mozilla"
}
```

**Comment by posva** [comment]
Well, chrome 28 is pretty old. I don't even know how your phone still has that. But Vue should work just fine on that browser. I guess the browsers have been modified or something.
Unfortunately, there's nothing we help you with apart from recommending you to update the browser 😄

**Comment by ckken** [comment]
im sorry to hear that,but many people in china use hua wei oppo , and vue router v1 is surpport, I hope it can fixed it in next version

**Comment by ckken** [comment]
@yyx990803

**Comment by ckken** [comment]
i find the problem in system.import or require.ensure([], () => r(require('./Foo.vue')), 'group-foo') is n o work in webpack1

**Comment by ckken** [comment]
fixed it! oh yeah

**Comment by XuXiaoGH** [comment]
@ckken 
Will solve this problem is to join the above configuration? If yes, where is it? looking forward to your reply.
Thank you!!!

**Comment by sabakugaara** [comment]
+1

**Comment by adophp** [comment]
兼容这里有解决方法：
http://blog.csdn.net/qq_16559905/article/details/70238583

**Comment by AutumnDeSea** [comment]
Can you post your code? @ckken

**Comment by NemoAlex** [comment]
Add
```
import 'babel-polyfill'
```
Before
```
import Vue from 'vue'
```
WORKS!

**Comment by ckken** [comment]
Add

import 'babel-polyfill'
Before

import Vue from 'vue'
WORKS!
