### ISSUE TITLE
Vue router redirect: to is called multiple times

### ISSUE THREAD

**Issue by spezzino** [vuejs/vue-router#1059]
### Vue.js / vue-router versions
2.1.8 / 2.1.1

### Reproduction Link
https://jsfiddle.net/spezzino/9ngtrn90/

### Steps to reproduce
- Open developer console
- Click through menu buttons

### What is Expected?
`redirect: to` callback called only once and on path match

### What is actually happening?
`redirect: to` callback is called multiple times and in every path.
Check console to see a timestamp every time it is called

**Comment by spezzino** [comment]
I think the problem is here

https://github.com/vuejs/vue-router/blob/dev/dist/vue-router.common.js#L1253

No matter what happens, if a route has `redirect` it will get executed immediately even if the path is different from the current path

**Comment by yyx990803** [comment]
This is not a bug, the redirect function is called as part of `match`, and each instance of `<router-link>` needs to call `match` to determine whether it is the current active route.
