### ISSUE TITLE
 "router-link-active" was added to wrong element when two elements have same prefix

### ISSUE THREAD

**Issue by AlexLi88** [vuejs/vue-router#1062]
**Vue.js / vue-router versions**

2.1.6 / 2.1.1

**Reproduction Link**

https://jsfiddle.net/k34ybLc2/3/

**Steps to reproduce**

Click the links on the fiddle, when you click helloworld link, the both router-link elements will be added 'router-link-active' class

**Comment by LinusBorg** [comment]
See the `exact` option:
http://router.vuejs.org/en/api/router-link.html

 Discussion on a new feature about this here: #1014
