### ISSUE TITLE
在开启router-view中的keep-alive后，无法在一个固定的路由地址且每次进入都可能需要刷新数据的组件上更新此组件

### ISSUE THREAD

**Issue by shusiwei** [vuejs/vue-router#1063]
如题：在开启router-view中的keep-alive后，无法在一个固定的路由地址且每次进入都可能需要刷新数据的组件上更新此组件

**Comment by fnlctrl** [comment]
需要给$route加一个watcher来刷新数据，详见https://router.vuejs.org/en/advanced/data-fetching.html
