### ISSUE TITLE
subpath app redirect bugs in the version 0.7

### ISSUE THREAD

**Issue by ccqgithub** [vuejs/vue-router#1064]
### Vue.js / vue-router versions
1.0.28 / 0.7.13

### What is actually happening?
my app has two language,  `http://127.0.0.1/en/` and `http://127.0.0.1/zh-cn/`.
now, if my path is `http://127.0.0.1/en/`, it will redirect to `http://127.0.0.1/#!/`, the right url is `http://127.0.0.1/en/#!/`
and this bug is also with `transition.abort()` of beforeEach hook ...

**Comment by justlstn** [comment]
You can add this in your index.js file:

`import Vue from 'vue'`
`Vue.use(VueRouter)`
`const router = new VueRouter({`
    `    history: true,`
    `    hashbang: false`
`})`
`configRouter(router)`

 [Route Options](https://github.com/vuejs/vue-router/blob/1.0/docs/en/options.md)

**Comment by ccqgithub** [comment]
@Fanciervm i just want to use hash mode, i found just change `location.replace(formattedPath);` to `location.replace(location.pathname + formattedPath);`

and, i found this issue maybe has solved in the version 2, but not add to version 0.7, i copy the source file and edit it to use for myself now……

**Comment by posva** [comment]
Sorry for the late reply 😓 
If you activate history mode, using `root: '/en/'` should work. I couldn't test it though.
Yes, it's doable in v2 with the `base` option
