### ISSUE TITLE
在QQ和微信中，history模式下，在某个动态路由的页面下，有个<a>标签，当我点击这个a标签的时候我希望打开一个新的页面，然后实际上是跳转到了我错误的页面中

### ISSUE THREAD

**Issue by webKity** [vuejs/vue-router#1068]
在QQ和微信中，history模式下，在某个动态路由的页面下，有个<a>标签，当我点击这个a标签的时候我希望打开一个新的页面，然后实际上是跳转到了我错误的页面中，即：假如我有一个页面：/download/1234，download是下载页面，1234是我在这个页面需要的参数，然后在这个页面中有一个超链接，点击跳转到第三方的下载页面。但是实际的效果是路由器帮我定向到了我自己项目中的404页面

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. Questions should be posted on the [forum](https://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

From what I understood, you can add normal links `<a href="https://google.com"></a>`. You shouldn't use `router-link` for that (if that's what you're doing)
