### ISSUE TITLE
vue-router2.0 在安卓机的物理返回键要如何维护好SPA的路由呀～

### ISSUE THREAD

**Issue by Sapphire2k** [vuejs/vue-router#1069]
栗子：
APage 
--A1 Page
--A2 Page
业务需求：从A-->A1 是带有一些数据的需要在A1上显示，并且可以被修改的。返回A 的时候带上A1 最新的数据 在A上展示，A2 一样的需求

在自主维护的导航栏上是没有这个问题的。
但是在安卓机上就跪了。。一个返回按钮 就把A1数据清空了，A页面就会报错 数据不存在

想请教各位大大 vue-router 在安卓返回键上该如何操作

**Comment by fnlctrl** [comment]
你好，请使用[论坛](http://forum.vuejs.org/)或[gitter](https://gitter.im/vuejs/vue)提问，issue列表只用于提交bug和feature request，谢谢！

--------------------

跨路由共享数据(状态)推荐使用vuex。
