### ISSUE TITLE
Vue js redirect

### ISSUE THREAD

**Issue by Theodory** [vuejs/vue-router#1071]
heey there am new to vue js and currently I want to make page redirect with no page refresh, how can I archive this am using Laravel for my back end stuffs

**Comment by alexvanzyl** [comment]
@Theodory Don't really think this is the right place for this :/

Given you are using vue-router, you could simply use router.push('home') https://router.vuejs.org/en/essentials/navigation.html

**Comment by simplesmiler** [comment]
Hello!

This is a usage question, and we encourage you to ask it on [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). We try to use the issue tracker for bug reports and feature requests.

**Comment by Lakshmanan-narayanan** [comment]
@alexvanzyl  If i want to go back to previous screen, In this case how can i use router.push() ?
