### ISSUE TITLE
Route to a new page

### ISSUE THREAD

**Issue by raphcadiz** [vuejs/vue-router#1075]
I was wondering if there a way to complete route to a whole new page with whole new layout.
I have a login page that is completely different to the regular views but vue-router always go the default index.html
`
const routes = [
  { path: '/login', component: resolve => require(['./views/Login.vue'], resolve) },
  { path: '/', component: resolve => require(['./views/Dashboard.vue'], resolve) },
  { path: '/create-client', component: resolve => require(['./views/CreateClient.vue'], resolve) },
  { path: '*', component: resolve => require(['./views/404.vue'], resolve) }
]
`

**Comment by yuchang01** [comment]
```javascript
 //this not always work. In particular, there are `children` sub-routing. bug?
component: resolve => require(['./Foo.vue'], resolve) 
```

try one of:
```javascript
component: resolve => {
    // require.ensure is Webpack's special syntax for a code-split point.
    require.ensure(['./Foo.vue'], () => {
       resolve(require('./Foo.vue'))
    })
}
```
or
```javascript
component: require('./Foo.vue')
```
or
```javascript
component: Foo
```
hope to help you.

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. Questions should be posted on the [forum](https://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

You should create a component for each route. There's only one index.html in an spa
