### ISSUE TITLE
Transitioning from two completely independant routes keeps previous route params in new route params

### ISSUE THREAD

**Issue by maxKimoby** [vuejs/vue-router#1077]
This does not seem to be a common bug. I could not reproduce it in JS Fiddle.

An image is worth 1000 words, the first object is the 'to' parameter from the route change, the second object is the 'from' parameter :

![screen shot 2017-01-05 at 5 44 58 pm](https://cloud.githubusercontent.com/assets/12074525/21700794/2e6c32de-d370-11e6-9863-d14f4892f5da.png)

So I have two routes, conversations-index and appointments-index. 

    const routes = [
	{
		name: 'conversations-index',
		path: '/conversations/:email',
		component: ConversationsIndex
	},
	{
		name: 'appointments-index',
		path: '/appointments/:date',
		component: AppointmentsIndex
	}
    ]

When transitioning to appointments-index from conversations-index, the :email parameter stays in the params object even though it isn't even in the matching path.

What am I missing? Every params set by a previous routes is kept in the new route's params when they aren't visible anywhere in the url.

**Comment by posva** [comment]
Can you check further, please? There may be some hook messing up things. I couldn't tell by just looking at the pictures

---

> An image is worth 1000 words

A repro is worth 1000 images 😛

**Comment by maxKimoby** [comment]
Yesterday night I shut down my Mac with this bug still on. I turned it on this morning and the sticky  params disappeared. I guess something was going on with my server/bundle cache or something.

Closed.
