### ISSUE TITLE
the old url cannot be matched after migration to vue2

### ISSUE THREAD

**Issue by petrelselina** [vuejs/vue-router#1078]
the old vue-router use the "#!/path" and now is "#/path", so how can it work correctly when user visit the old url? I seems that no solution in the migration document.

**Comment by posva** [comment]
The shebang (`#!`) is now deprecated (https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html). If you have old links that you want to keep working, the best thing to do it at your server level.
If you're using Nginx, a [rewrite](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#rewrite) or [try_files](http://nginx.org/en/docs/http/ngx_http_core_module.html#try_files) rule will do it
Of course, you can do it with Apache too.

Another dirty solution is to keep using the shebang, although, I discourage you from doing so:

```js
new VueRouter({
  mode: 'history',
  base: '/#!/',
  ...
})
```
And [adapt your server](https://router.vuejs.org/en/essentials/history-mode.html)
