### ISSUE TITLE
Nested Routes in Named Views

### ISSUE THREAD

**Issue by Vwings** [vuejs/vue-router#1079]
Is there an example about nested routes in named views?
I am thinking of writing something like this :   
<pre>const router = new VueRouter({
    routes: [
    {
      path: '/',
      components: {
        default: Foo,
        a: Bar,
        b: Baz
      }
      children : [
        {
          name : 'default.c'
          path: 'c'
          component : C
        },
        {
          name : 'default.d'
          path: 'd'
          component : D
        }
      ]
    }
  ]
})</pre>

**Comment by fnlctrl** [comment]
Hi, thanks for filing this issue, however the issue tracker is reserved for bug reports and feature requests only, please use  [gitter](https://gitter.im/vuejs/vue) or [forum](https://forum.vuejs.org/) or [stackoverflow](https://stackoverflow.com)to ask questions. Thanks!
