### ISSUE TITLE
Adhoc Routing: add route dynamically 

### ISSUE THREAD

**Issue by li3p** [vuejs/vue-router#1083]
Hi, All. By digging into the document and examples of 2.x version. I found I have to determine every route before `router = new VueRouter(routes)`.  I have a situation that some routes need to be added according to some ajax request's result. Can `vue-router` add a function to support this feature (in some Vue components method):

```js
...
this.$router.on(url, component)
...
```

**Comment by znck** [comment]
What do you need dynamic routes for?

**Comment by li3p** [comment]
Well, It is a document collaboration SPA, a number of people may editing a different pages of one document simultaneously.  Each page is a node of the tree control in sidebar on every pages in editing.  I need when someone added pages or changed the page title,  each tree control on other pages can be updated simultaneously, and bind to  a <router-link> dynamically.

**Comment by znck** [comment]
I think something like `/pages/:page` can work. If you need different component for different values of `page` then use a [functional component](https://vuejs.org/v2/guide/render-function.html#Functional-Components).

Does this solve your issue?

**Comment by nkostadinov** [comment]
I have the same problem with ajax response which "needs" to modify routes #888 and #954

**Comment by posva** [comment]
Closed in favour of #888
