### ISSUE TITLE
Should I use vue-cli to use data into a template?

### ISSUE THREAD

**Issue by Taewa** [vuejs/vue-router#1089]
Hello.
I am a newbie of vueJs and Vue-router.
Even though I have checked several article, video and official website, still I can't find a solution for my issue.

[Here is example](https://jsfiddle.net/hadeath03/z98nq70a/)

Basically what I want is passing the `data` through `const app`.
In the example, you will find `xxx` variable which I want to use in template. And I expect to see `yyy` string when I click Go to Foo link but, no luck.

I could find many examples that use vue-cli with webpack.
However, for some reason I want to avoid that way.

Is it possible to resolve my problem without using vue-cli and webpack?

Thank you.

**Comment by fnlctrl** [comment]
Hi, thanks for filing this issue. 
As for your problem, in short: please finish reading [the official guide about components](https://vuejs.org/v2/guide/components.html) first, before trying out vue-router.
As for your question about webpack/vue-cli, yes, they're not required to solve your problem.

For more questions, please use [gitter](https://gitter.im/vuejs/vue) or [forum](https://forum.vuejs.org/) or [stackoverflow](https://stackoverflow.com), as this issue tracker is reserved for bug reports and feature requests only, Thanks!

**Comment by qwexvf** [comment]
you can have `data` for each templates. check out the vue component docs
if you want to use data storage, you should use vuex.

**Comment by Taewa** [comment]
@fnlctrl @qwexvf 
Thanks for the answer.
I have read the official guide about components carefully again, but I could not find an answer.

However, I could resolve my issue, I am not sure if this is a correct way but in any case people who have the same issue, [I leave my code](https://jsfiddle.net/hadeath03/z98nq70a/1/).

As you can see the my code, component can be either `Vue.extend()` or just `object {}`. (Foo is Vue.extend and Bar is just an object). That's is a point that I didn't know.

But the official document about component is not saying about it. Just showing `Vue.component(...` way.
If I missed something it would be grateful to let me know.

Thanks again!

**Comment by chandmk** [comment]
You are trying to access root elements data property from child component that was loaded through router.  There are ways to pass props in to the router.  And there are ways to fetch the data independently from the component.  

Here is a way to get what you are doing.  Not sure if this is idiomatic or not. 

{this.$root.xxx}}
