### ISSUE TITLE
replace option is missing when use beforeEach hook

### ISSUE THREAD

**Issue by viclm** [vuejs/vue-router#1090]
The route object doesnot contain any replace imformation,  so if i call `router.replace()` or enable replace in `<view-link replace>`,  then use next(path) always invoke `history.push`

**Comment by fnlctrl** [comment]
It's added in 2.1.0 https://github.com/vuejs/vue-router/releases/tag/v2.1.0
```
router.beforeEach((to, from, next) => {
  if (to.path === '/foo') {
    next({
      path: '/bar',
      replace: true
    })
  }
})
```

**Comment by viclm** [comment]
You are not get it, I do not know the navigation which invoke beforeEach hook is push or replace

**Comment by fnlctrl** [comment]
Yes, there's currently no information about whether beforeEach was invoked by push/replace.
Can you explain why you need it?

**Comment by viclm** [comment]
I need every route contain the same query info, but do not want to copy it in every navigation, in beforeEach hook, just add it if not provided, so i need the next(path) in the hook keep the same behavior

**Comment by fnlctrl** [comment]
In this case where you want to enforce query params, simply call `next` again with replace: true
```js
router.beforeEach((to, from, next) => {
    next()
    next({
        query: {
            foo: 'bar'
        },
        replace: true
    });
});
```

**Comment by BoltDoggy** [comment]
I need the same help. Please open this.

**Comment by BoltDoggy** [comment]
#1620

**Comment by wanyaxing** [comment]
+1 for this feature.

I want to hook the router in each page in ddtalk app, to add parameter dd_nav_bgcolor, but I found all the links in next are set as router.push...

```
router.beforeEach ((to, from, next)=> {
    if (to && to.query && !to.query.dd_nav_bgcolor)
    {
        to.query.dd_nav_bgcolor = 'FF08B2F2';
        next(to);
    }
    else
    {
        next();
    }
  });
```

**Comment by Alphmega** [comment]
I need this feature, too

**Comment by carolirod** [comment]
+1

**Comment by sl-nancy** [comment]
+1

**Comment by SSSStone** [comment]
The same question!
```
router.beforeEach((to, from, next) => {
  if (to.query.r) {
    next()
  } else {
    next({
      // replace: true,
      path: to.path,
      query: Object.assign(to.query, { r: Math.random() })
    });
  }
})
```

**Comment by mathk** [comment]
+1

**Comment by posva** [comment]
the `query` is not modifiable, create a new object:

```js
query: Object.assign({}, to.query, { r: Math.random() })
// or
query: { ...to.query, r: Math.random() }
```

 ---

Closing to prevent noise from questions
