### ISSUE TITLE
DOM mismatch with beforeRouteEnter in combination with prefetching/SSR

### ISSUE THREAD

**Issue by jvandenaardweg** [vuejs/vue-router#1092]
Alright. So i have this situation:

I use beforeRouteEnter to fetch some data before routing to that page/component. This works perfect in the client. I used it as [described in the docs](https://router.vuejs.org/en/advanced/data-fetching.html).

However, in combination with server side rendering this goes a little bit wrong with also preFetching data on the server.

### Vue.js / vue-router versions
2.1.8 / 2.1.0

### Reproduction Link
I've forked the latest version of the Hackernews 2.0 example and added [2 changes](https://github.com/jvandenaardweg/vue-hackernews-2.0/commits/master) to showcase the problem:
https://github.com/jvandenaardweg/vue-hackernews-2.0

### Steps to reproduce
1. Use the example above
2. Run it with `npm run dev`
3. Navigate to a user
4. Refresh the page
5. The error shows in the console

### What is Expected?
No errors.

### What is actually happening?
Vue throws an error saying: 
```
The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render. 
```

I think this has something to do with the active class being set on the router-link for the user page. Because that one is only set after beforeRouteEnter completes. So, making the server rendered HTML and client rendered HTML different. Because in the client's DOM that active class is not (yet) present. That's the only thing i can think of now.

I kinda guess this is not expected behaviour, though the error makes sense. It actually means you cannot use beforeRouteEnter in combination with prefetching data on the server? 
Or am i missing something here?

**Comment by yyx990803** [comment]
This is a known issue - basically SSR doesn't play very well with asynchronous route hooks. We plan to improve this in the next feature release.

**Comment by jvandenaardweg** [comment]
I worked around this problem. The fix for an other problem i had also seems to work here. http://stackoverflow.com/a/41621807/3194288

If `from.name` is `null` (i name all my routes) and it loads in the client, it means we don't need to do an API call again. So we can leave the server rendered HTML as is. So no need to do data fetching in beforeRouteEnter when that's the case. Because we've already done the `preFetch` when it loads from the server, and that's enough.

```javascript
beforeRouteEnter (to, from, next) { 
    if (from.name && process.env.VUE_ENV === 'client') {
      preFetchData(store).then(data => {
        next(vm => {
          // do something
        })
      })
    } else {
      next()
    }
  }
```

**Comment by yyx990803** [comment]
With 2.2, using `router.onReady` on both server and client will ensure consistent render results on both sides.

**Comment by atinux** [comment]
@yyx990803 is there any way to know if the router could not load the async routes?

For example, I have a route `pages/index.vue` for the `/` route:
```vue
<template>
  <p>Hello</p>
</template>

<script>
console.log(window)
</script>
```

Actually I have this warning in the console:
```
[vue-router] Failed to resolve async component default: ReferenceError: window is not defined
```

And `router.onReady` is never fired on the server-side.

**Comment by jvandenaardweg** [comment]
"window" is not available on the server, that's why you get that error. Your app should have some checks to check when you are on the server, or not, if you want to use something like "window" (which will only do something in the browser)

https://vuejs.org/v2/api/#vm-isServer

**Comment by atinux** [comment]
I know @jvandenaardweg, I created the error myself so I can display this error when loading the page to help the user to debug. The problem is from [vue-router] which does not give me a callback if they cannot load the component.

I found a workaround to `router.onReady` if you guys are interested to see: https://github.com/nuxt/nuxt.js/commit/cfd6b197c4009274c43ea6a82dec82a9fdd128a7
