### ISSUE TITLE
Feature request: route with empty name still should show default component

### ISSUE THREAD

**Issue by DonPrus** [vuejs/vue-router#1093]
latest version vue, latest version vue-router.

Here I want to have several view for one route, I use named view:
https://jsfiddle.net/k7ce2zcw/
But if `name=''` it don’t show default.
How could I fix it without making two different names?

This is working well: https://jsfiddle.net/k7ce2zcw/1/
But I just want to use default. When I don’t use `name` at all it shows default, but if name is even empty string it shows nothing.

**Comment by znck** [comment]
Set `name` to `''`.

``` js
{
  path: '/',
  components: {
    '': Default,
    default: Default,
    login: Login
  }
}
```

**Comment by posva** [comment]
I agree with @znck , you should set the corresponding entry to Default to make it explicit. You can also set the name to `'default'` instead of `''`.
