### ISSUE TITLE
Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by fengxinming** [vuejs/vue-router#1094]
component: resolve => require(['vues/index.vue'], resolve),

在路由文件里面异步加载路由组件，用chrome浏览器访问时有时候会报错 Cannot read property 'call' of undefined，用10台机器上的chrome浏览器测试，有5台会必现该问题

**Comment by fnlctrl** [comment]
如果是用webpack 2.x的话 请用System.import() / import()，不要用require(.., resolve)，详见https://github.com/vuejs/vue-router/pull/862

如果不是的话，请阅读[Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines)然后提供重现。
