### ISSUE TITLE
[question] how to create crossfade transition

### ISSUE THREAD

**Issue by beebase** [vuejs/vue-router#1095]
When switching views, I'd like to fadeOut the old page/fadeIn the new page at the same time.
Are there any examples somewhere? There's a lot of documentation around about transitions but I haven't found anything specifically on cross fading.

**Comment by fnlctrl** [comment]
Hi, thanks for filing this issue, however the issue tracker is reserved for bug reports and feature requests only, please use  [gitter](https://gitter.im/vuejs/vue) or [forum](https://forum.vuejs.org/) or [stackoverflow](https://stackoverflow.com)to ask questions. Thanks!

---------------------

Simply define a crossfade transition and use it with router-view:

```
<transition name="crossfade">
  <router-view></router-view>
</transition>
```

**Comment by jerearaujo03** [comment]
Did you achieved it? I don't like I can't mix two routes view to crossfade smoothly, instead I'm getting view A fade to opacity 0, and then view B opacity to 1, but it's not crossfade, it's fade to white and then fade from white.

**Comment by kalnode** [comment]
> Simply define a crossfade transition and use it with router-view:

I'm confused by this answer, and it getting thumbs up. Is there an actual "crossfade" feature in `vue-router` (I find no evidence of it)... or is the suggestion to simply name a custom animation as "crossfade" and pretend that it's cross-fading ?
