### ISSUE TITLE
programmatic navigation with params only works for named route?

### ISSUE THREAD

**Issue by reverland** [vuejs/vue-router#1098]
### Vue.js / vue-router versions
2.1.8 / 2.1.1

### Reproduction Link

https://jsfiddle.net/6du90epg/176/

### Steps to reproduce
1. click `/a`, it do get params
2. but click '/b', params is lost

### What is Expected?

click '/b' and it shows 'bar another'

### What is actually happening?

click '/b' and it shows 'bar'

**Comment by fnlctrl** [comment]
This is working as intended. If you want to use `$route.push` with `params` option to another route, the target route must be named.
