### ISSUE TITLE
v-if and v-show with router-view(v-else)

### ISSUE THREAD

**Issue by ibyteyou** [vuejs/vue-router#1099]
hI!
i require components into vuex/vue-router file
and use v-if/v-else for consistent progress down the route.
this construction perfectly work, but when i use v-if and v-show together - component not showed inside router-view =(.

vue@2.1.8 vue-router@2.1.1 pug

```
transition(mode="out-in" enter-active-class="animated fadeIn" enter-leave-class="animated fadeOut" appear)
  ul.columns.is-multiline(v-if="$route.meta.panel" v-show="!loading")
    user-card(v-for="i in list", :i="i", @changed="getList()")
    user-card-add(v-if="!loading")
  router-view(v-else, @changed="getList()")
```

**Comment by yyx990803** [comment]
You are not supposed to be using `v-if` and `v-show` on the same node, especially when they both try to trigger transitions.

Use `v-if` on the outer transition component instead.
