### ISSUE TITLE
There is no `lib/index.js` file

### ISSUE THREAD

**Issue by djyde** [vuejs/vue-router#110]
The main file is `lib/index.js` configured in `package.json`, but there is no `lib` folder in the package after `$ npm install vue-router`.

https://github.com/vuejs/vue-router/blob/dev/package.json#L5

So my temporary solution is replacing `lib/index.js` to `dist/vue-router.js`.

Is there anything wrong?

**Comment by yyx990803** [comment]
`lib` is auto built before publishing to npm so it's not checked into git.

I just tested install from npm and it is there. Are you using the latest version?

**Comment by djyde** [comment]
Oops, I just tested again and it is there, too. Maybe it is something wrong with npm
