### ISSUE TITLE
target="_blank" attr unusable

### ISSUE THREAD

**Issue by Etheryte** [vuejs/vue-router#1100]
### Vue.js / vue-router versions
2.1.9 / 2.1.1

### Reproduction Link
https://jsfiddle.net/q46wrr7x/

### Steps to reproduce

Specify the `target` attribute on any an `a` or a `router-link`. After the app is mounted, the attributes are missing. In the Fiddle, links with the `target` attribute present have a green background, all other links have a red background.  
What is more, the issue also affects links that are outside the actual application mounting node (see Fiddle).

As covered in [#827](https://github.com/vuejs/vue-router/issues/827), using the `target` attribute should be fixed, at least on `a` tags. It seems it is completely unusable at the moment.

**Comment by fnlctrl** [comment]
It's working fine here.. Can you tell us about the OS/browser you're using?
![image](https://cloud.githubusercontent.com/assets/5557143/22025849/fbf24804-dd09-11e6-9d89-ea56d0fa6831.png)

**Comment by Etheryte** [comment]
@fnlctrl I'm running macOS 10.12 with the latest Chrome. It seems to be an issue only when I have [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en) enabled.  
The app gets mounted (the router links work), but all target attributes are missing.  
I've closed this issue as the actual problem seems to lie somewhere else entirely.

![http://i.imgur.com/7y7RCRa.png](http://i.imgur.com/7y7RCRa.png)

**Comment by agm1984** [comment]
This still occurs with uBlock Origin. Just disabled it on my localhost and target="_blank" started working.
