### ISSUE TITLE
data of app.vue changes in router is not effect

### ISSUE THREAD

**Issue by marsprince** [vuejs/vue-router#1107]
### Vue.js / vue-router versions
2.1.2 / 2.1.1

### Reproduction Link

```javascript
router.beforeEach((to,from,next)=>{
router.app.test='a'
})

In app.vue

data () {
    return {
        test:'init',
    }
  }
```
### Steps to reproduce
can't change app.test,it's always init
### What is Expected?
app.test='a'
### What is actually happening?
How can I change data of app.vue in vue-router?

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. Questions should be posted on the [forum](https://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

app probably points to the `new Vue({ router: el: '#app', ...})` and not the the App.vue.
Maybe a ref helps
``` js
new Vue({
   el: '#app',
   router,
   render: h => h(App, { ref: 'app' })
```

and then you can do `router.app.$refs.app.test = 'a'`
