### ISSUE TITLE
The beforeRouteEnter and beforeRouteLeave component hooks aren't called on query change

### ISSUE THREAD

**Issue by ryancharlesking** [vuejs/vue-router#1109]
### Vue.js / vue-router versions
2.1.10 / 2.1.1

### Reproduction Link
https://jsfiddle.net/9r6xhqbp/12/

### Steps to reproduce
Using the fiddle above
* Open up the developer tools to see the console statements
* Click the /home link
* Click the /foo link
* Click the /foo?query link

### What is Expected?
The `beforeRouteEnter` and `beforeRouteLeave` hooks are called when switching from `/foo` to `/foo?query` to maintain consistency with the `beforeEach` global hook.
### What is actually happening?
Only the `beforeEach` global hook is being called when switching between `/foo` and `/foo?query`.

### Additional Insight
We are working on iteratively replacing an existing code base with Vue and the existing system would do component cleanup on query changes, and needs the ability to prevent a query change for dirty form handling. 

Eventually, we plan on removing that and changing the URL structure to be less reliant on query data and more reliant on dynamic paths, but for now we must maintain backwards compatibility.

Using the `beforeEach` global guard is working, but it is forcing cleanup logic for a specific component to exist in a global function which isn't an ideal design.

The behavior is also slightly inconsistent between the global and the local guards.

**Comment by fnlctrl** [comment]
Hi, thanks for filing this issue. There will be a new hook `beforeRouteUpdate` for this, you can check out https://github.com/vuejs/vue-router/issues/938.

**Comment by ryancharlesking** [comment]
Awesome, thanks! I tried searching, but apparently my queries weren't good enough. Implementation makes sense as well.
