### ISSUE TITLE
How can I detect the browser back button with Vue 2 a vue-router?

### ISSUE THREAD

**Issue by wuzi1975** [vuejs/vue-router#1110]
In main.js

```
router.back = (target) => {
  console.log('back---')
  ...
}
```

It doesn't work

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. Questions should be posted on the [forum](https://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

This is actually unrelated to Vue. `window.onpopstate` or similar should do it

**Comment by wizardnet972** [comment]
hi @posva , the `window.onpopstate` happens after the `router.beforeEach`.
