### ISSUE TITLE
How to add different layouts to vue router？

### ISSUE THREAD

**Issue by KeyHui** [vuejs/vue-router#1112]
I found vue router just add components ，but layout is same. Dose it have layout manager or other method for layout ？

**Comment by phanan** [comment]
Hello! Please use our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) for questions like this. The repo issue list is strictly for bug reports and feature requests, as stated in the [contributing guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md). Thanks.
