### ISSUE TITLE
Routing separator can be custom?

### ISSUE THREAD

**Issue by liuzesen** [vuejs/vue-router#1113]
I want to custom the routing separator,
like '#/home', i want it become '#-home'

**Comment by phanan** [comment]
Hello! Please use our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) for questions like this. The repo issue list is strictly for bug reports and feature requests, as stated in the [contributing guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md). Thanks.
