### ISSUE TITLE
[Russian translation] Неверная вложенность списков

### ISSUE THREAD

**Issue by chimit** [vuejs/vue-router#1114]
На странице https://router.vuejs.org/ru/api/router-link.html в блоке "Входные параметры", начиная с `replace` и до `active-class` включительно, сбилась вложенность списков: тип и значение по умолчанию на одном уровне с самим названием параметра.

![2017-01-23 18 58 36](https://cloud.githubusercontent.com/assets/839349/22201312/f8fc4fa8-e19d-11e6-9c5b-d3401be1f98e.png)

Глянул в markdown-исходник - никаких ошибок не нашел, но факт остается фактом. Может кто найдет причину проблемы.

**Comment by simplesmiler** [comment]
Случается и в [англоязычной версии](https://router.vuejs.org/en/api/router-link.html), но на локально сгенерированных доках я не могу воспроизвести проблему, так что скорее всего проблема при деплое. Попинговал нужных людей.

**Comment by simplesmiler** [comment]
Редеплой исправил проблему.

:+1: to @chrisvfritz

**Comment by chrisvfritz** [comment]
пожалуйста! :smile:
