### ISSUE TITLE
router-link error when used from child view components and global vue scripts

### ISSUE THREAD

**Issue by chandmk** [vuejs/vue-router#1116]
Bug

Using latest view and view-router.

This error is not present if I use  global scripts and no .vue files 
This error is not present if I use npm to load Vue and Vuerouter compnents.

index.html has references to global scripts (had to do this as we have a hybrid spa app)

    <script src="https://unpkg.com/vue/dist/vue.js"></script>
    <script src="https://unpkg.com/vue-router/dist/vue-router.js"></script>

One of the child .vue file has the following markup
```
<template>
  <div id="foo">
     <h1>{{ msg }}</h1>   
    <router-link tag="button" :to="'/'">back to home</router-link>
  </div>
</template>

<script>
export default {
  data () {
    return {
      msg: 'Welcome to Foo vue'
    }
  }
};
</script>
```

```
When navigating to the child link getting the following error
[Vue warn]: Unknown custom element: <router-link> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in anonymous component at C:\Work\hello\src\Foo.vue)
```

**Comment by posva** [comment]
Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behaviour you described.

---

Using scripts should automatically do `Vue.use(VueRouter)` but you may need to manually use it

PS: view and view-router? Please, tell me it was autocorrected 😄

**Comment by chandmk** [comment]
I am not sure if it is possible to have  jsfiddle to reproduce this issue.  As this is only a problem when I use .Vue files and build them into a single script.

I am not importing vue or vue-router.  I don't have the statement, Vue.use(VueRouter) in main.js.  And router-view component in main.js is working without errors.

I tried to use Vue.use(VueRouter) in the foo.vue component file, but that doesn't seem to have any affect.

Yes vue and vue-router :)

**Comment by posva** [comment]
That's strange. You can provide a minimal repro in a repo instead, then. But, please, make sure to boil down the issue as much as possible. We'd really appreciate that 🙂

**Comment by chandmk** [comment]
Source for the issue
[vue-router-issue-#1116](https://github.com/chandmk/vue-router-issue)

**Comment by LinusBorg** [comment]
You're missing `Vue.use(VueRouter)`

https://github.com/chandmk/vue-router-issue/blob/master/src/main.js#L3

**Comment by LinusBorg** [comment]
* You haven't defined Vue and Vue-Router as externals in your webpack config.
* Therefore, webpack is bundling another copy of Vue & vue-router with your bundle.js
* These are used inside your app, not the global ones.
* and finally, since VueRouter only auto-registers itself with Vue in the global scope, not in a bundle, the copy inside your app still needs a `Vue.use(VueRouter)`

....or, better: define Vue and VueRouter as externals so they don't get bundled. Keeps you from bundling Vue 2 times and the various other bugs you would experience from this.

https://webpack.js.org/configuration/externals/

**Comment by yyx990803** [comment]
If you use `.vue` files, then Vue is assumed to be loaded as an npm dependency in your bundle. This is necessary for hot-reload to work properly.

Maybe we can check for presence of global Vue in the hot-reload code. However this is not really a vue-router issue.

Or, use externals as suggested by @LinusBorg

**Comment by chandmk** [comment]
Thank you!!!
 
externals: {
    vue: 'Vue',
    "vue-router": 'Vue-Router'
  },

**Comment by chandmk** [comment]
externals also is not completely working... 

If I use externals I must use both vue and vue-router in externals.  If I keep just the vue in externals I get the following error.

I updated the solution to show the problem

[vue-router-issue-#1116](https://github.com/chandmk/vue-router-issue)
```
Uncaught TypeError: Cannot read property 'matched' of undefined
    at render (eval at <anonymous> (build.js:1310), <anonymous>:63:24)
    at J (vue.min.js:6)
    at V (vue.min.js:6)
    at le (vue.min.js:6)
    at ue (vue.min.js:6)
    at e._c (vue.min.js:6)
    at a.render (eval at <anonymous> (build.js:1291), <anonymous>:6:64)
    at a.n._render (vue.min.js:6)
    at a.<anonymous> (vue.min.js:6)
    at no.get (vue.min.js:7)
```

**Comment by LinusBorg** [comment]
Well, did you call Vue.use(VueRouter)?

**Comment by LinusBorg** [comment]
Please ask further questions on forum.vuejs.org.
