### ISSUE TITLE
Routes with aliases and named child routes cause warnings

### ISSUE THREAD

**Issue by Dadibom** [vuejs/vue-router#1119]
### Vue.js / vue-router versions
\>= 2.1.2

### Reproduction Link
https://jsbin.com/satalijiga/edit?js,console

### Steps to reproduce
Give a child route a name, add an alias to the parent

### What is actually happening?
The console is blasted with warnings about duplicate named route definitions. This happened at 2.1.2
> "[vue-router] Duplicate named routes definition: { name: \"test.subpage\", path: \"/subpage\" }"

**Comment by SuperAL** [comment]
Updated to vue-router@2.3.0，this problem still exists.
`[vue-router] Duplicate named routes definition: { name: "monitor", path: "index.html/monitor" }`

**Comment by posva** [comment]
Create a new issue with a repro. The one provided before doesn't produce any warning now. You can use this template: http://jsfiddle.net/posva/9r6xhqbp/

**Comment by samayo** [comment]
@yyx990803 Why is this closed? I have the same issue. At least it should be answered or referenced

**Comment by trollepierre** [comment]
Evan closed it because the issue was fixed in the commit https://github.com/vuejs/vue-router/commit/67307680c2a0a70d47d6a11697ec27e6876917e2
