### ISSUE TITLE
2.1.2版本开始, SSR时, 源代码的链接全部会被加上src/router

### ISSUE THREAD

**Issue by lincenying** [vuejs/vue-router#1120]
![image](https://cloud.githubusercontent.com/assets/10840991/22369316/176dcc20-e4c6-11e6-8e50-e1514e946a77.png)
如上图所示, 经过浏览器渲染后, 链接是正常的, 包括最新的 2.2.0 也有此问题, 退回 2.1.1 版本问题消失

vue 版本 2.1.10
vuex 版本 2.1.1
系统 mac/win7
浏览器 chrome55

**Comment by fnlctrl** [comment]
请检查new VueRouter(...)的配置对象里是否有
```
base: __dirname
```

**Comment by lincenying** [comment]
https://github.com/vuejs/vue-router/pull/1045/commits/ad0f036ef8ca528079e06f468024212dbc70b7e3
目测是base的原因了, 2.1.2改动了这个...
