### ISSUE TITLE
beforeRouteEnter 访问vuex中的数据很麻烦

### ISSUE THREAD

**Issue by shusiwei** [vuejs/vue-router#1134]
beforeRouteEnter 访问vuex中的数据很麻烦，建议提供比较便捷的方法

**Comment by posva** [comment]
Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You can access to getters, mutations or actions in the hook
```js
beforeRouteEnter (to, from, next) {
  next(vm => {
    // access to component instance via `vm`
  })
}
```

**Comment by fantasybei** [comment]
Indeed, try to load data using vuex before navigation is difficult
