### ISSUE TITLE
.v-link-active seems to be added to routes that match a given pattern, sometimes incorrect

### ISSUE THREAD

**Issue by xsbeats** [vuejs/vue-router#114]
I believe this is an issue, but could be incorrect.  Given `v-link`s with paths `foo` and `foobar`, when `foobar` is visited `foo` is still considered active.

https://jsbin.com/zukinud/edit?html,css,js,output

**Comment by yyx990803** [comment]
Yeah, that's a bug.

**Comment by JosephSilber** [comment]
BTW, can the class name handling be abstracted into a separate directive?

I find myself wanting to highlight certain elements when a route is matched, but they're not links.

**Comment by yyx990803** [comment]
@JosephSilber I'll keep that in mind, for now something like `v-class="active: isActive('/a/b/c')"` would probably work? (you need to implement `isActive` yourself)

**Comment by rrrhys** [comment]
@JosephSilber 

I found a workaround for this without custom code - attach v-link to the parent element too, and it will attach the active class without any hyperlink properties.

                    <li v-link="{name: 'foo', activeClass: 'active'}">
                        <a v-link="{name: 'foo'}">Foo</a>
                    </li>

Correctly attaches .active to <li>

**Comment by oguzhanaslan** [comment]
@rrrhys 
This solutions, redirect to the homepage. Links are not working. 
vue version: 0.12.16
vue-router version: 0.7.7

**Comment by jekinney** [comment]
Had the same issue until I added exact: true. Works great now

**Comment by altafhussain10** [comment]
Why do so much repeated work, just add a little css and change the li.active > a css to be applied on li > a.active. It works great with too much changes required repeatedly.
