### ISSUE TITLE
Handle page not found with many router-view

### ISSUE THREAD

**Issue by lephuhai** [vuejs/vue-router#1141]
I have a question for handle many page not found in layout.

I declare routers like this:

```javascript
const router = new VueRouter({
  history: true,
  mode: 'history',
  scrollBehavior,
  routes: [
    {
      path: '/',
      components: {root: Publisher},
      meta: {requiresAuth: true},
      children: [
        {path: '*', components: {content: ContentNotFound}} // **Router run it**
      ]
    },
    {path: '/sign-in', name: 'SIGNIN', components: {root: SignIn}, meta: {scrollToTop: true}},
    {
     path: '/sign-out',
      name: 'SIGNOUT',
      redirect: to => {
        return '/sign-in'
      }
    },
    {path: '/sign-up', components: {root: SignUp}, meta: {scrollToTop: true}},
    {path: '*', components: {root: NotFound}}
  ]
})
```

When I access to: */sign-out* then  **ContentNotFound** handle, i want to using **NotFound** for handle this.

I hope you give me correct mindset or example in this case. Thanks so much.

**Comment by posva** [comment]
Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). The issues are for bugs and feature requests only.

---

You can probably do something like `$router.push()` inside of the ContentNotFound
