### ISSUE TITLE
URL are not same for the same path between vue-router 0.7.x and 2.x when using hash mode

### ISSUE THREAD

**Issue by oliverzy** [vuejs/vue-router#1146]
### Vue.js / vue-router versions
2.1.9 / 2.1.1

### Issue Description
The url are different between Vue Router 2.x and 0.7.x when using hashbang mode.
In 0.7.x, the router path will be appended after '#!', however, in 2.x, the router path will be appended after '#'.

We are migrating our Vue 1.x app to Vue 2.x. We are noticing this difference which make original url invalid if vue router is used.

### What is Expected?
Can keep url same between vue-router 0.7.x and 2.x when using hashbang mode

**Comment by posva** [comment]
Hi, thanks for your interest in Vue!

The hashbang was removed on purpose in the first beta: https://github.com/vuejs/vue-router/releases/tag/v2.0.0-beta.1. So I'd recommend you to migrate your paths to `#`. You can hack your way around by using the [base](https://router.vuejs.org/en/api/options.html#base) option, but you should really adapt your application to simply use a hash

**Comment by oliverzy** [comment]
Is it possible to still provide the hashbang option, but the default value is false.
Since the url is public and impossible to use server redirect because of hash.

**Comment by fnlctrl** [comment]
@oliverzy  You can simply add support for legacy #! urls by adding something like
```js
if (location.href.indexOf('#!') > -1) {
  router.replace(location.href.split('#!')[1])
}
```
Since it's trivially easy to implement in userland, it's not likely to be added back to vue-router.
