### ISSUE TITLE
Баг в активных ссылках

### ISSUE THREAD

**Issue by wormen** [vuejs/vue-router#1148]
на скрине видна суть проблемы

![09-02-2017 16-23-34](https://cloud.githubusercontent.com/assets/8462339/22773304/b7edf1b6-eee4-11e6-8043-cbdcf1f38efc.jpg)

версия роутера, самая последняя

**Comment by simplesmiler** [comment]
Это ожидаемое поведение. В таких случаях нужно делать `<router-link to="/dashboard" exact>`.
