### ISSUE TITLE
relative child router-link ignores params

### ISSUE THREAD

**Issue by kedemd** [vuejs/vue-router#1151]
Vue 2.1.8
Vue Router 2.1.1

When creating children route with relative paths, params are ignored by the router link.

Example route:
```
const router = new VueRouter({
    routes: [
        {
            path: '/user/:id',
            component: {
                template: '<div><router-link to="profile"></router-link><router-view></router-view></div>'
            },
            children: [
                {
                    path: 'profile',
                    component: {
                        template: '<div>{{ $route.params.id}}</div>'
                    }
                }
            ]
        }
    ]
}}
```
Expected:
page: /user/test will have link to /user/test/profile
page: /user/test/profile will work as expected and display 'test'

Actual:
page: /user/test has link to /user/profile
page: /user/profile doesn't work as expected and displays: 'undefined'

Fix / Hack:
Use full path instead of relative path on `<router-link>`. for example:
`<router-link :to="'/user/' + id + '/profile'">...`

I know I can use full paths on the routes themselves but I want to use relative paths because I am reusing routes and they should behave differently based on the location in the route tree. (I don't want to do: /user/:id/profile on the child route path).

**Comment by kedemd** [comment]
Note:
Redirect route will redirect correctly and will pass the param. This means that the behavior is inconsistent.

For example:
```
const router = new VueRouter({
    routes: [
        {
            path: '/user/:id',
            component: {
                template: '<div><router-link to="profile"></router-link><router-view></router-view></div>'
            },
            children: [
                { path: '', redirect: 'profile'},
                {
                    path: 'profile',
                    component: {
                        template: '<div>{{ $route.params.id}}</div>'
                    }
                }
            ]
        }
    ]
}}
```

Accessing the /user/test will redirect to /user/test/profile (as expected)

**Comment by yyx990803** [comment]
Cannot reproduce in vue-router 2.2.0. If issue persists please open new one with proper reproduction (a jsfiddle link)
