### ISSUE TITLE
About set the document.title problem with router.afterEach 

### ISSUE THREAD

**Issue by lmasdata** [vuejs/vue-router#1152]
when I use router.afterEach set document.title, In ios(version:10.0.0.1) devices cannot be properly set the title.Only when I refresh can display properly.

router.afterEach((route) => {
  document.title = `${route.meta.title !== undefined ? route.meta.title : '标题'}`;
});

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. According to your description it's likely an ios bug. Please check if directly calling `document.title = 'foo'` works, if not, then there's nothing we can do to help.

**Comment by lmasdata** [comment]
Thank you, I have solved the problem,It needs to do some fit for WeChat browsers.

**Comment by ZhihaoLau** [comment]
@lmasdata Hi, I got the same issue, can you tell us how you solved it? What fit need to be done?

**Comment by lmasdata** [comment]
@ZhihaoLau 
![image](https://cloud.githubusercontent.com/assets/8501594/22916103/3d90b5d0-f2b7-11e6-9038-74af28abefdd.png)

**Comment by ZhihaoLau** [comment]
@lmasdata thanks, totally saved in gist
