### ISSUE TITLE
router-link has 300ms deley in mobile

### ISSUE THREAD

**Issue by lmh2072005** [vuejs/vue-router#1153]
### Vue.js / vue-router versions
2.1.2 / 2.1.1

### What is actually happening?

I use the router-link ,but it has 300ms deley in mobile ,it is a bug ?

**Comment by fnlctrl** [comment]
No, it's added by browser to any click event listener. You need to setup a `<meta>` tag. Please refer to: https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away
