### ISSUE TITLE
Transition-delay on component children crashes Chrome tab

### ISSUE THREAD

**Issue by germania** [vuejs/vue-router#1154]
### Vue.js / vue-router versions
2.1.10 / 2.2.0
Chrome 56 (tested on W10, MacOS 10.12, Linux, Android)

### Reproduction Link
http://codepen.io/bclarke/pen/egPPEZ (Chrome only - open in FF/Edge to see it working)

### Steps to reproduce
1) Set up a minimal vue-router with a component at /
2) Wrap router-view in transition appear
3) Give the component parent element a perspective CSS property (eg, perspective: 800px)
4) Add several child elements to the component parent, and set transform: translate3d(0, 0, 800px) on them
5) stagger them on .v-enter with transition-delay
6) Observe

### What is Expected?
The child elements stagger into the scene using the 3D transform

### What is actually happening?
The Chrome tab stops rendering, needs closing (console remains responsive, keyboard shortcuts to navigate change address bar, but the tab no longer gets rendered)

**Comment by yyx990803** [comment]
I believe this is a bug of Chrome itself, because it is working properly in Chrome Canary (58).

**Comment by germania** [comment]
If anybody runs into this until Chrome 58 drops, add `transform-style: preserve-3d`.  This seems to work around the bug in all cases I've seen.
