### ISSUE TITLE
Accessing root instance on initial router load.

### ISSUE THREAD

**Issue by Aferz** [vuejs/vue-router#1160]
Hi,

I've been seaching for info about this problem and I didn't find a solution, so here it goes:

When I try to access to root instance data/methods in `beforeEach` middleware in the very first router initial loading I get `undefined`. Once the route component is mounted, next calls to router middleware `beforeEach` have the root instance completely ready.

I wanna say that I can understand why root instance is not mounted on initial loading. I guess is because it doesn't mount without a child component (I didn't see the core code, just guessing). I just wanna know if this is intended behaviour (Official doc doesn't clarify this point).

I provide a JSbin for better clarification:

https://jsbin.com/pemoxeyuki/edit?html,js,console

Thanks !

**Comment by posva** [comment]
Yes, it's intended. The transition takes places when the router is initialised and that happens in a `beforeCreate` hook. Therefore the data hasn't yet been called: https://github.com/vuejs/vue-router/blob/dev/src/install.js#L20-L28

Not sure if something can be added to the docs.
Can you summarise what you're trying to do in the `beforeEach` hook?

**Comment by Aferz** [comment]
Of course @posva,

I'm trying to access a property in the root instance that check if the user is authenticated or not.

```javascript
router.beforeEach((to, from, next) => {
    const { requiresAuth } = to.meta
    const { isAuth } = router.app

    if (! isAuth) {
      next({ name: 'auth.login' })
    } else {
      next()
    }
})
```

`isAuth` is allways `undefined` the first time the has loaded, so I can't use this implementation to check if there is already an user authenticated.

I know this can be resolved with Vuex, but I don't need a full state management for my app and I was tinkering with the idea of the root instance.

With ES6 modules I can access `isAuth` data importing my little "store", but I just wanted to do it the Vue way.

Any idea?

Thanks !

**Comment by posva** [comment]
> I know this can be resolved with Vuex, but I don't need a full state management for my app and I was tinkering with the idea of the root instance

Exactly. The isAuth is some piece of global state, so it really belongs to some place like Vuex. You should try it out, it's great 🙂 
There's also probably a way of initialising the auth data out of Vue so it's ready the first time, and you can later on use it outside of it. Another easy way would be to use `nextTick`

Cheers

**Comment by Aferz** [comment]
Thanks for your help @posva .

**Comment by marcusamargi** [comment]
@Aferz I am struggling with this now too. What approach did you settle on?

**Comment by Aferz** [comment]
@pymarco I finished using a Vuex Instance. There's no other solutions so far. Technicaly is the best approach and the most clean solution.

Hope It helps.
