### ISSUE TITLE
How to set route's component dynamically depending on params?

### ISSUE THREAD

**Issue by konradkalemba** [vuejs/vue-router#1166]
Hi, my goal is to create website with pages downloaded from API. I ended up with idea to create one route and showing different components depending on passed params in URL: 
`{ path: '/:lang/:page?/:subpage?', component: () => components.get(params) }`

It doesn't work unfortunately. Any ideas?

**Comment by fnlctrl** [comment]
Hi, thanks for filing this issue, however the issue tracker is reserved for bug reports and feature requests only, and we encourage you to use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions or for discussion. Thanks!

-------------------------------------------

A straightforward solution:
bind `/:lang/:page?/:subpage?` to a static component, and then use `<component :is="dynamicComponent"/>` in its template,
where `dynamicComponent` is binded to the result of `components.get(params)` (as data or computed property)
