### ISSUE TITLE
[bug] wrong condition of `current.matched` in src/util/location.js#27

### ISSUE THREAD

**Issue by puxxustc** [vuejs/vue-router#1169]
This line https://github.com/vuejs/vue-router/blob/dev/src/util/location.js#L27

```javascript
    } else if (current.matched) {
```

`current.matched` is an Array, so this condition should be

```javascript
    } else if (current.matched.length === 0) {
```

**Comment by fnlctrl** [comment]
It's perfectly fine to put an array inside `if`, to check for its existence.

**Comment by puxxustc** [comment]
current.matched can be []

**Comment by fnlctrl** [comment]
It's guaranteed to be not emtpy. Please provide an actual reproduction if you believe there's a bug.

**Comment by posva** [comment]
@fnlctrl There's probably something wrong with that check, it may be unnecessary because in the flow types it's always an array, it cannot be absent. So we're probably missing a little improvement either in the types or in the codition there

**Comment by puxxustc** [comment]
Here is a stacktrace recorded by sentry:

vue@2.1.10, vue-loader@11.0.0, vue-router@2.2.1, vuex@2.1.2, vuex-router-sync@4.1.2, webpack@2.2.1

![image](https://cloud.githubusercontent.com/assets/4092563/23055987/fdf19a92-f523-11e6-8e62-d779fd3f53cc.png)

**Comment by fnlctrl** [comment]
Again, please provide a reproduction, thanks!

**Comment by IncSW** [comment]
Has same error with nuxt when url not matched by router.
If change to `current.matched.length && current.matched.length` works fine and throw 404.
