### ISSUE TITLE
Vue-router can not work properly in the typescript2.0 environment

### ISSUE THREAD

**Issue by ulivz** [vuejs/vue-router#1170]
I use vue2.0 and typescript2.0, as well as vue-router2.0 as my development technology stack, which is my project template —— [template](https://github.com/toxichl/vue-typescript-template-ui)，You run this project (`npm run dev`), you will find the error as follows:

`vue-typescript-template-ui\node_modules\vue-router\types\router.d.ts`
`(2,10): error TS2305: Module '"vue"' has no exported member 'ComponentOptions'.`
`.......`

Does it have a problem with the type declaration file of vue-router2.0 ？

**Comment by posva** [comment]
@ktsn @kazupon Can you chime in, please 😁?

**Comment by ktsn** [comment]
I guess `@types/vue-resource` still use Vue v1.x typings, so it conflict with Vue v2.x typings. 😞

**Comment by posva** [comment]
@ktsn Thanks for looking it!
In that case, @toxichl  you should file an issue on the vue-resource repo.
Since there's nothing to do on vue-router, I'll close this 🙂

**Comment by ulivz** [comment]
No, I modify the vue-router's source code to solve this problem, not vue-resource types have problems. 😞@ktsn @posva

**Comment by posva** [comment]
Can you submit a PR in that case?

**Comment by ulivz** [comment]
I have submitted a PR in [click here](https://github.com/vuejs/vue-router/pull/1171)， you can reproduce the bug with the demo project I have given and fix my bug based on my PR. @posva
