### ISSUE TITLE
Link to child route prepends parent route on transition

### ISSUE THREAD

**Issue by awitherow** [vuejs/vue-router#1172]
Hello vuejs!

I have a project I am building using vue at the moment, and have started to read into the vue-router documentation for nested routes.

I have created a view for a parent component with links to children view within an array of objects in my data.

```vue
<template>
  <div id="refugees" class="container">
    <ul>
      <li v-for="section in sections">
        <router-link :to="section.to">{{ section.text }}</router-link>
      </li>
    </ul>
    <router-view></router-view>
  </div>
</template>

<script>
export default {
  name: 'refugees',
  data () {
    return {
      sections: [
        {
          text: this.$t('views.refugees.links.local'),
          to: 'refugees/local'
        },
        {
          text: this.$t('views.refugees.links.online'),
          to: 'refugees/online'
        },
        {
          text: this.$t('views.refugees.links.help'),
          to: 'refugees/help'
        }
      ]
    }
  }
}
</script>
```

When I navigate to `../refugees`, the home path loads fine. When I click on the first link (local, for example), it routes properly to `../refugees/local`. When I click a second link (online, for example), it routes to `../refugees/refugees/online`.

Is this due to the logic I am using to iterate over the sections/links in the data structure, or am I doing something else completely wrong?

The pull request I have everything in can be found here: https://github.com/awitherow/openrefuge/pull/4/files

Thank you!

**Comment by posva** [comment]
Hello, it is working as expected: you're using relatives links that depend on the current route.
You should use named routes instead, they're explicit and absolut 🙂 

Please, next time, ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Issues are for bug reports and feature requests only

**Comment by awitherow** [comment]
Thanks for the help @posva but it is not clear how a child route should be named according to the documentation. Only a single tier route is shown.

Would I name the route, for example, `refugees/home`?

Perhaps the documentation could be updated to reflect the correct implementation?

**Comment by awitherow** [comment]
@posva ah I see, it does not matter, as long as it links to that name, which serves similar to an 'id'. Got it! Thanks.
