### ISSUE TITLE
Path as regex instead of strings

### ISSUE THREAD

**Issue by Dadibom** [vuejs/vue-router#1177]
### Vue.js / vue-router versions
2.1.10 / 2.2.1

Trying to add a route with a negative lookahead regex, `path: '/(?!PathThatShouldNotBeMatched)'`, however the exclamation mark is automagically escaped before passed to the regex tester.

**Comment by posva** [comment]
Paths are not regexes, they're transformed to regexes.
We could maybe allow the user to use his own regexes.
Why would you need to use a custom regex in a path?

**Comment by Dadibom** [comment]
I don't really need to use custom regex, though it would make the path system more flexible. I just want a way to match everything BUT something specific. This is an alternate solution to my problem caused by https://github.com/vuejs/vue-router/issues/1176 , meaning that my wildcard route could have exceptions for the routes i add dynamically.

**Comment by Dadibom** [comment]
Or maybe, replace the wildcard route with something that always matches anything unmatched, that is always checked last

**Comment by Dadibom** [comment]
Like routes: [{...}], notFound: {...}

**Comment by fnlctrl** [comment]
Since the current route matching is completely done by [path-to-regexp](https://github.com/pillarjs/path-to-regexp), it's very unlikely to add such feature in vue-router. @Dadibom can you check out [path-to-regexp](https://github.com/pillarjs/path-to-regexp)'s docs and see if it's features can work for your use case?

**Comment by posva** [comment]
I should have referenced this when I saw it 😄  https://github.com/pillarjs/path-to-regexp/issues/99

Anyway, I don't think we need to add anything. We should look at #1176 instead

**Comment by LinusBorg** [comment]
So can we agree to close this because we are committed to path2regexp?

@posva @fnlctrl @Dadibom

**Comment by posva** [comment]
Yes, we should close this because the real issue is #1176
Thanks for the reminder 🙂
