### ISSUE TITLE
Dynamic loading of components

### ISSUE THREAD

**Issue by gapipro** [vuejs/vue-router#118]
So right now if I inspected docs and examples correctly you can't dynamically load components, but they must be all loaded (with require) when defining initial router mapping. 

When developing large applications it would be cool to have then loaded on demand. So when mapping component you would just specify where to get component it self and when appropriate url is hit you require that component and build it. 

Also components it self in most cases have sub routes (ex: item list/edit/create). Could this sub routes be defined as component options that are then inserted into main router at component compile time?

**Comment by azamat-sharapov** [comment]
Did you check [Async Components](http://vuejs.org/guide/components.html#Async_Components)?

**Comment by gapipro** [comment]
Somehow I missed this feature in 0.12 release. Thank you.

**Comment by ifyio** [comment]
How does one actually make use of async components along with `vue-router`? Is there an example?
