### ISSUE TITLE
npm run dev Errors

### ISSUE THREAD

**Issue by zhangxueru** [vuejs/vue-router#1180]
Errors！！！
What's up？
Windows environment

E:\vue-router-dev\examples>npm run dev
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path E:\vue-router-dev\examples\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'E:\vue-router-dev\examp
les\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'E:\vue-router-dev\examp
les\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     E:\vue-router-dev\examples\npm-debug.log

**Comment by fnlctrl** [comment]
Hi, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Thanks!
