### ISSUE TITLE
keep-alive nests a named view,but the named view can't be rendered

### ISSUE THREAD

**Issue by ghost** [vuejs/vue-router#1186]
part of the code is as follows:  
```
    <view-box ref="viewBox">
      <router-view></router-view>
      <keep-alive>
        <router-view name="footer" slot="bottom"></router-view>
      </keep-alive>
    </view-box>
```

maybe I can't do it this way

**Comment by LinusBorg** [comment]
Hello @olymk,

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted.


Thank you.

**Comment by ghost** [comment]
https://jsfiddle.net/48sft446/

i think when keep-alive tag exist, the named view also can be rendered
when I annotate keep-alive tag，it's work

i'm so sorry, my englist is poor

**Comment by posva** [comment]
You have to put the `slot` attr in the outer element like so:

```html
<keep-alive slot="footer">
            <router-view name="foot"></router-view>
        </keep-alive>
```

**Comment by ghost** [comment]
thanks!

**Comment by ghost** [comment]
my god,so stupid,I thought keep-alive is functional element and can't add any attr
