### ISSUE TITLE
Add Per-Route beforeLeave and beforeUpdate guard

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs/vue-router#1195]
Is there any reason why this guard is not supported on per route configuration? While there is component `beforeRouteLeave` hook.

**Comment by posva** [comment]
I remember it is because it has access to `this` and therefore makes more sense to be declared at a component level

**Comment by miljan-aleksic** [comment]
Not really needing it, but make sense to have both, if for example want to and can afford to keep the route logic out of the component one.

**Comment by posva** [comment]
Adding a note from #1577 :
`beforeEnter` on routes allows you to have generic guards that do not depend on the component while component guards are specific to that component.

**Comment by mitar** [comment]
I really think this is needed to handle cases when one uses `props` set to `true` on the route to pass route to the component as props. Then you do not want component to handle invalid values being passed, but you want and need route to check that every time props change, to decide if to pass the new prop value to the component or do something else.

**Comment by econic** [comment]
And something else could also be dispatching a store action necessary to get the component's data

**Comment by patricio-ezequiel-hondagneu-roig** [comment]
This would be a nice feature to have, and it would also make it feel more consistent with component guards.

**Comment by mjarosch** [comment]
I could really use a beforeUpdate to validate params before passing them to the component. I took a stab at adding them in. This is my first time working with the vue-router code, so I am probably missing things. Any chance this could be pulled in as a feature?

[Commit](https://github.com/mjarosch/vue-router/commit/b1326de599c463aa554337f0c7e19435472708cc)

**Comment by MaheshCasiraghi** [comment]
I solved this by adding per-route guards as meta fields.
In (all) routes:

```
        beforeEnter (to, from, next) {
            console.log("Entering route (only called once)");
            // next();
        },
        meta: { 
            beforeUpdate (to, from, next) {
                console.log("updating route");
                // next();
            },
            afterLeave (to, from) {
                console.log("leaving route");
            },
        },
```

In router (only once):
```
    router.beforeEach((to, from, next) => {
        to.meta.beforeUpdate(to, from, next);
    })

    router.afterEach((to, from) => {
        to.meta.afterLeave(to, from);
    })
```

**Comment by Rziedreo145** [comment]
@MaheshCasiraghi I was pretty excited about your simple workaround, but found that it doesn't support guards on parent routes. I'm going to take a crack at extending your work around to that end.

**Comment by T0RAT0RA** [comment]
Here is an updated version of @MaheshCasiraghi's workaround, that works with nested routes:

```
router.afterEach((to, from) => {
  if (!to.matched.some(r => r.name === from.name)) {
    from.matched.forEach(f => f.meta?.afterLeave?.(to, from));
  }
}
```

Edit: I updated the code to execut afterLeave from each matching route that have one

**Comment by posva** [comment]
As this can be implemented with `meta` fields (and so do `beforeEnter`), we think it's better to drop this for the moment

**Comment by mitar** [comment]
@posva Should this be documented [here](https://router.vuejs.org/guide/advanced/navigation-guards.html#the-full-navigation-resolution-flow) then?

**Comment by posva** [comment]
Rather document the example in `meta` and maybe link to it from the navigation guards docs. Open for PR!
