### ISSUE TITLE
A typo in Passing Props to Route Components documentation page

### ISSUE THREAD

**Issue by gamtiq** [vuejs/vue-router#1198]
There is the following typo in [Passing Props to Route Components](http://router.vuejs.org/en/essentials/passing-props.html) documentation page:
> This allows you *to to* cast the parameter

**Comment by znck** [comment]
Please send a PR for this change.

**Comment by gamtiq** [comment]
Which branch should I use to make changes from?

**Comment by znck** [comment]
To `dev`
