### ISSUE TITLE
Compatibility issue with Microsoft Edge Browser

### ISSUE THREAD

**Issue by sibowilldo** [vuejs/vue-router#1200]
Hi Gitters

I'm not sure if this has been logged yet, but as I working on a small project using Vue 2.1.10 and Vue Router v2.2.1 (along with Laravel 5.4 but not the issue here), I noticed that Vue Router tags (router-link, router-view) are not being compiled/parsed/rendered in MS Edge (with latest Windows 10 updates)

### Steps to reproduce
I have <router-link to="/" tag="li"><a>Home</a></router-link> on my navigation 
and 
<router-view></router-view> on my main
Both are wrapped with in div#app

### What is Expected?
It works 100% on Chrome, Firefox and IE11, except MS Edge. As expected they should be rendered and appear as <li></li> and <div class="container">...</div> respectively  

### What is actually happening?
but both those tags on MS Edge show as they are when inspecting elements.

Please help, or is it just me... I'll understand if this log is giving a very low priority, cause I mean, who uses MS Edge anyway😅.

**Comment by posva** [comment]
Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a **minimal** JSFiddle or Github repository containing a set of reproducible steps that can lead to the behaviour you described. Make sure to boil down the problem as much as possible. Thanks!

**Comment by sibowilldo** [comment]
False alarm please accept my sincere apologies. Apparently the problem is with my MS Edge, specifically on this computer I'm using, VueRouter works 100% on my other computer with the same version of MS Edge
