### ISSUE TITLE
How it work in this case? $router.push

### ISSUE THREAD

**Issue by lephuhai** [vuejs/vue-router#1201]
When I assign `this = vm` and using `vm.$router.push({/})`. It's not working :(

Can you help me to finds solutions in this case?

```js
methods: {
      onSignInSuccess (googleUser) {
        if (googleUser.getBasicProfile().U3.slice(5) === '@example.com') {
          this.$auth.setToken(googleUser.getAuthResponse().id_token, (60 * 60 * 1000) + Date.now())
          this.logging = false
          this.$router.push({path: '/'}) // It's works!!
        } else {
          this.$router.push({path: '/sign-in'})
        }
      }
    }
```

But in this case, not working when using `vm.$router.push`
```js
methods: {
      onSignInSuccess (googleUser) {
        if (googleUser.getBasicProfile().U3.slice(5) === '@example.com') {
          var vm = this
          axios.get('http://example/v1/token.json', {
            headers: {
              'Authorization': `Bearer ${googleUser.getAuthResponse().id_token}`
            }
          }).then(function (response) {
            if (response.data.status_code === 200) {
              vm.logging = false
              vm.$router.push({path: '/'}) // NOT WORKING???
            } else {
              vm.$router.push({path: '/sign-in'})
            }
          })
        }
      }
    }
```

**Comment by fnlctrl** [comment]
Hi, thanks for filing this issue, however the issue tracker is reserved for bug reports and feature requests only, and we encourage you to use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions or for discussion. Thanks!

**Comment by lephuhai** [comment]
@fnlctrl I mean, this is issues to use. Can you help me to fix this or certain solutions ?

**Comment by YouSour** [comment]
i got a problem with $router.push like this too , any solutions ?

**Comment by alvirtuoso** [comment]
Same problem here. Mine only happens in component that's auth guard protected 
In my router array:
`              { path: 'dash', component: Dashboard, meta: { requiresAuth: true } }, 
                { path: 'login', component: Login },
`
In my Dashboard component:
`        signOut: function(){
            this.$router.push({path: '/'})
            console.log('im getting executed but router.push does nothing. no error')
          }
`

**Comment by jsgv** [comment]
~~Any solution/feedback? 
I am having the same issue of `$router.push({ name: '', params: {}})` not working nor doing anything.~~

My mistake, I had a navigation guard in my component on which I forgot to add call `next()` 

```js
beforeRouteLeave (to, from, next) {
  // do stuff
  // call next() when done
  next()
}
```
