### ISSUE TITLE
Vue router reloading to '/' when used with webpack-hot-middleware

### ISSUE THREAD

**Issue by chopfitzroy** [vuejs/vue-router#1206]
### Vue.js / vue-router versions
2.1.2 / 2.1.1

### Reproduction Link
https://github.com/CrashyBang/vue-router-reload-bug

### Steps to reproduce
1) Once repo is set up run `npm run src:dev` and `npm run app:dev` and then in the app click on the **Test One** link.

2) Now navigate back to the code base and modify `src/logic/views/TestOne.html` or `src/logic/views/TestOne.js` now instead of inserting the new code it just `vue-router` is resetting to `/`.

3) This project was largely inspired by [vuepack](https://github.com/egoist/vuepack) so there are a lot of code similarities expect in [vuepack](https://github.com/egoist/vuepack) the live reloading works. It could be because I am not using the `vue-loader` (just vanilla JS)?

### What is Expected?
Live reloading should insert new code into page and not do full reload to `/`

### What is actually happening?
When code is modified `vue-router` is resetting to `/`

**Comment by posva** [comment]
> t could be because I am not using the vue-loader (just vanilla JS)

Yes, more specifically vue-loader uses https://github.com/vuejs/vue-hot-reload-api which uses what allows that
