### ISSUE TITLE
scrollBehavior ( to, from, savedPosition )   console.log(to) == console.log(from) ;    //true

### ISSUE THREAD

**Issue by junjieit** [vuejs/vue-router#1207]
## Vue.js / vue-router versions

2.2.0

## Reproduction Link

https://jsfiddle.net/wjunjie/fg0eu4ey/

## Steps to reproduce

Click link: 
`
scrollBehavior ( to, from, savedPosition ) { 
     console.log(to) == console.log(from) ;    //true
}
`

## What is Expected?

**to**: Route: the target Route Object being navigated to.

**from**: Route: the current route being navigated away from.

## What is actually happening?

**to**: Route: the target Route Object being navigated to.

**from**: Route: the target Route Object being navigated to.

//  英文不好，希望回复中文，谢谢。

**Comment by posva** [comment]
I'd say this is intended to make it possible to recognise the same router view is being reused. It also happen with params btw.
wdyt @fnlctrl

**Comment by fnlctrl** [comment]
But `to` is always equal to `from`  :joy: :joy: :joy: https://jsfiddle.net/dus1anxL/... 
Creating a PR to fix this..

**Comment by exah** [comment]
Hi, is there any workaround until next release?

**Comment by jazoom** [comment]
Yes, that's a good question. I was bitten by this yesterday. I'm not sure if there is a reasonable workaround.

**Comment by yyx990803** [comment]
Just released 2.3.1 for this fix.
