### ISSUE TITLE
Equivalent to replaceState(null, null, path) ?

### ISSUE THREAD

**Issue by plauclair** [vuejs/vue-router#1211]
I was not able to find a way to just replace the URL natively from vue-router **without triggering navigation**. I'm trying to emulate window.history.replaceState(null, null, '/the-path');.

My use case is the following:

In one of our views, we have a component that loads another dynamically. When loading the latter component (imagine the different lines on Netflix and the block that opens below when you click one, it's pretty much the same thing), we must set the url but not trigger any navigation. This way, if the person wanted to share the page, upon loading, the URL will be correct and route to a full-blown direct-access view.

Currently I just use window.history.replaceState directly but it would be pretty nice if I could use the path building options vue-router provides in $router.push and $router.replace.

I was not able to reproduce this behavior, and if it is indeed not possible, consider this a feature request. Cheers!

**Comment by posva** [comment]
Hi, please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You talked about it but I think you're looking for `router.replace` https://router.vuejs.org/en/essentials/navigation.html

**Comment by plauclair** [comment]
The problem with router.replace is that it will trigger navigation. This is not what I intend to do. I'll ask again on the forums but I doesn't seem to have the required functionality in my case.

**Comment by plauclair** [comment]
[Forum discussion URL](https://forum.vuejs.org/t/vue-router-equivalent-to-replacestate-null-null-path/7195)

**Comment by posva** [comment]
If by navigation you mean the before and after hooks, I'd say that's by design. Why wouldn't you want to trigger them? Are you giving access to the user to something he shouldn't see?

**Comment by plauclair** [comment]
By navigation I mean that router.replace will load the router view associated with it. 

We're not giving access to something the user shouldn't see. We have embedded views that need to have their paths exposed so if the user reloads or shares what he/she sees, people going to that route will be taken to a view that shows the same thing but in a "standalone" kind of way (see the Netflix-like use-case described in the first message). We can't faithfully just put it back in place, because the context might not exist at that time (each users view is customized, so the place the original user came from might not exist anymore on a different view, or it could be there multiple times, which means resolving context is impossible). 

Imagine thumbnail "cards" on Youtube but opening inline/in-place on the home page. You have multiple rows, sometimes you have the same thumbnail cards appearing on different rows. When you would open that view in-place, you would see the video, but not be navigating to a full-blown page for the video. When that happens, you have a problem: the URL isn't what you want, you're still on the home, it can't be shared (this is especially troublesome for mobile sharing) or accessed at a later time.

The way I'd see implementation would be to have `router.replaceUrl(args)` which takes the same argument as replace() or push() (a path or object), but doesn't trigger anything in the router itself, just changes the displayed url. That way we're still in the vue-router way of doing things with all the niceties you provide (url building) without having to handle each of these cases manually with resolve() and managing browsers differences where they might exist.

**Comment by posva** [comment]
Oh, I see. Then, this is a dup of #703 

Sorry, I don't have netflix so the first example didn't make any sense to me 😄
