### ISSUE TITLE
When file extension is present in URL, cannot get page

### ISSUE THREAD

**Issue by MaestroJurko** [vuejs/vue-router#1216]
how would someone set the path of a view, that is dynamic and can include file extensions:

```
/storage/folder1/folder2/file.py
```

Now I get:

```
Cannot get /storage/folder1/folder2/file.py
```

Path conf now:

```
path: ‘storage/*'
```

**Comment by kazupon** [comment]
Thanks for filing the issue! Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behavior you described.

**Comment by MaestroJurko** [comment]
Ok will provide a jsfiddle, but is there a fix for this?

**Comment by fnlctrl** [comment]
There couldn't be a fix if there were no bugs in the first place.

Judging from the error message it seems your web server treated the url as a file, and there's nothing we can do about that. Please configure your web server's url rewrites.

For example, if you're using `webpack-dev-server`, use the `historyApiFallback` option:
```js
historyApiFallback: {
    rewrites: [
        {
            from: /.*/,
            to:  'index.html'
        }
    ]
}
```
