### ISSUE TITLE
router hook not worked in children router's component

### ISSUE THREAD

**Issue by superchangme** [vuejs/vue-router#1217]
I have  router map ,such as /news/add, /news/ is a root router, /news/add is its sub router.
I write the router hook in /news/add template:
~~~
   watch: {
           '$route' (to, from) {
               console.log('come in sub')
           }
       },
        beforeRouteEneter(){
       console.log('come in sub')
        },
~~~
But the code can’t work.
It's a bug or not support in sub router?

**Comment by LinusBorg** [comment]
Hello @superchangme,

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted. ([Why is this necessary?](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff))


Thank you.

**Comment by imac8t** [comment]
+1 the same ask

**Comment by superchangme** [comment]
This bug is fixed when i use vue-cli webpack 
May be the bug only appear in vue-cli browserify's env

**Comment by LinusBorg** [comment]
If that's the case, then this is the wrong repository. Also, no reproduction was provided, so this will be closed now.
