### ISSUE TITLE
how to redirect undefined route name?

### ISSUE THREAD

**Issue by alphaelf** [vuejs/vue-router#1220]
hi, i use version 2.0
with `path` i can use:
```javascript
{
    path: '*',
    redirect: '/404'
}
```
and `<router-link to="/some-unmatch-route">Some</router-link>`  and works fine.
but if call routes by name like `this.$router.push({name: 'some-unmatch-route'})` it's get error:

> [vue-router] Route with name 'some-unmatch-route' does not exist

 my suggest is define a property `unmatchRoute: { redirect: '/404'}` in root option and it manage both path and name unmatching issue.

**Comment by posva** [comment]
It doesn't make sense to use a name of a non-existing route in your app. The error is there so you can add it. Would you mind sharing a brief explanation of why you need that?

**Comment by fnlctrl** [comment]
Yeah... using a non-existent name doesn't make sense. Arbitrary paths can be visited by users, so it's necessary to set up a catch-all route and redirect to 404 if a path doesn't exist. Names are only defined by developers and cannot be arbitrary, so this error exists to protect developers from typos.

When you can already simply do `this.$router.push('/404')`, it doesn't make sense to do `this.$router.push({name: 'some-unmatch-route'})` to make the router redirect to `/404`.

**Comment by alphaelf** [comment]
@posva it's because my menu item grabbed from php and i may have some wrong route name.
never mind it's just make my code trace a little hard.
tanks 4 reply
