### ISSUE TITLE
router-link will add a parent route path

### ISSUE THREAD

**Issue by JackFGreen** [vuejs/vue-router#1222]
The ```<route-link>``` tag will add a parent route path after clicked, but the ```<a>``` tag will not.

![2017-03-05_230258](https://cloud.githubusercontent.com/assets/23187848/23588574/4bf3ca8e-01fa-11e7-9015-c3db191b949c.png)
![2017-03-05_230217](https://cloud.githubusercontent.com/assets/23187848/23588575/4dae1eb0-01fa-11e7-8497-cf79ff9294fe.png)

## before click
![2017-03-05_230555](https://cloud.githubusercontent.com/assets/23187848/23588577/50f2e394-01fa-11e7-8d38-df3c159319bc.png)

## after click
![2017-03-05_232206](https://cloud.githubusercontent.com/assets/23187848/23588587/9f226558-01fa-11e7-8c1f-b03d4bc7efe3.png)

**Comment by posva** [comment]
Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
