### ISSUE TITLE
Access 'this' on beforeRouteUpdate

### ISSUE THREAD

**Issue by rfberaldo** [vuejs/vue-router#1225]
Maybe it's a really dumb question, but why when I do this:

```
beforeRouteUpdate(to, from, next) {
  console.log(this)
  next()
}
```

I have access to the component instance, but when I do this:

```
beforeRouteUpdate: (to, from, next) => {
  console.log(this)
  next()
}
```

it returns a regular obj?
![capture](https://cloud.githubusercontent.com/assets/18370605/23658241/79904a90-0320-11e7-99e8-d6d66d7e80a3.PNG)

Shouldn't return the same component obj?

**Comment by fnlctrl** [comment]
Arrow functions don't have `this`.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

**Comment by rfberaldo** [comment]
Sorry about that, new to ES6.
