### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by VyaWave** [vuejs/vue-router#1229]
Uncaught TypeError: Cannot read property '_recognizer' of undefined ,
on console i see this error ,why do this ? vue-router 1.0

**Comment by kazupon** [comment]
Thanks for filing the issue! Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behavior you described.
