### ISSUE TITLE
base option not working

### ISSUE THREAD

**Issue by mimani** [vuejs/vue-router#1230]
### Vue.js / vue-router versions
2.1.2 / 2.1.1

### Reproduction Link

http://jsfiddle.net/xgrjzsup/1352/
http://stackoverflow.com/questions/42664712/how-base-option-works-in-vue-router
### Steps to reproduce
add base in route:

```
const router = new VueRouter({
  base: "/app/",
  routes
})
```

### What is Expected?

It should had added `/app/` in all the routes when hitting from the browsers.

### What is actually happening?

When I do `/app/foo` in the browser, it is not going to corresponding route of `/foo`.

**Comment by posva** [comment]
As they told you on the SO post, the base doesn't have to be part of the link
