### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by any86** [vuejs/vue-router#1231]
如果:  $router.push({query: {a:[1,2]}} })
那么url:  xxx?a=1&a=2
这时: $route.query.a = [1,2]

=========但是============

如果:  $router.push({query: {a:[1]}} })
那么url:  xxx?a=1
这时: $route.query.a = 1

$route.query.a数据类型变了
vue2.1.4
vue-router  @2.2

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
Thanks!
