### ISSUE TITLE
on tab use on route?

### ISSUE THREAD

**Issue by finnome** [vuejs/vue-router#1244]
how to use router for single tab, like this?
[http://7xsm7t.com1.z0.glb.clouddn.com/WechatIMG1.jpeg](url)

**Comment by fnlctrl** [comment]
Hi, thanks for filing this issue, however the issue tracker is reserved for bug reports and feature requests only,  please use  [gitter](https://gitter.im/vuejs/vue) or [forum](https://forum.vuejs.org/) or [stackoverflow](https://stackoverflow.com) to ask questions. Thanks!
