### ISSUE TITLE
gh-pages is missing CNAME file

### ISSUE THREAD

**Issue by ifraixedes** [vuejs/vue-router#1245]
I've just realized that the docs pages don't work, GH is reporting 404 and after I checked the `gh-page` branch I've seen that the current version is missing the _CNAME_ file.

**Comment by fnlctrl** [comment]
I was fixing the docs and run `update-docs.sh` before realizing it requires a globally installed `gitbook-cli` which I haven't installed 😂  It should be fixed now.
