### ISSUE TITLE
请问vue-router2，webpack2,vue2写的组件懒加载webpack的配置文件怎么写呢

### ISSUE THREAD

**Issue by hrpc** [vuejs/vue-router#1247]
主要是webpack生成的组件单独的js文件加载不了，我npm run dev是可以正常运行的，npm run dev就不行了。    我用的是webpack－simple

我用的是System.import在router文件中引入组件的。我估计错误是在webpack配置文件中。

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
Thanks!
