### ISSUE TITLE
ios9.0 9.1 uiwebview vue-router 有问题

### ISSUE THREAD

**Issue by ustbhuangyi** [vuejs/vue-router#1248]
ios9.0 和 9.1 这俩个操作系统下的 uiwebview，当设置 location.hash = 'xxxx' 的时候，vue-router 源码中的 getHash() 方法并不能取到这个 hash（setTimeout 20ms 才能取到），导致后面 hash 比对的逻辑都不对了。目测是 uiwebview 内核的 bug，同样的 wkwebview 就没有此 bug。考虑到这部分内核的微信、支付宝还有一定量级的用户，vue-router 官方能否修复这个问题？

**Comment by fnlctrl** [comment]
原因是旧版UIWebview中location.hash的写入不是同步的。 https://bugs.webkit.org/show_bug.cgi?id=149415
很遗憾，浏览器的bug，应用库没有办法修。不过ios7.1起就已经支持history api了，可以考虑使用vue-router的history模式。

**Comment by wangxiao** [comment]
history 模式需要服务器支持，往往前端部分会直接部署到 CDN 服务器上面，不可能调整 CDN 服务器的支持。

**Comment by wjhcc2018** [comment]
@fnlctrl 微信 ios版，不支持history，视图能正常切换，但是浏览器的地址 不切换，这样导致复制链接，分享，在Safari中打开等等功能，拿到的链接都是首页的链接，这个问题有什么解决方案吗

**Comment by ustbhuangyi** [comment]
@Say-Hello 当时自己 fork 了一个 vue-router 改了一下，感觉解决方案略 hack 就没有给官方提 pr 了，不过滴滴这么大用户量应该也验证了没有什么问题。可以参考：https://github.com/ustbhuangyi/vue-router/commit/a97de5d2129500055eea9180d5a1d168b98bb209
