### ISSUE TITLE
Support parent container for scroll behavior

### ISSUE THREAD

**Issue by erguotou520** [vuejs/vue-router#1249]
Feature request?

`VueRouter` use `window.scrollTo` to do scroll, but in some case, the scroll container may be not the body, is that possible to support custom scroll parent like:
```
scrollBehavior () {
  return { container: 'container-selector', x: 0, y: 0 }
}
```
For realization, update `window.scrollTo` to `$container.scrollTop = position.y; $container.scrollLeft = position.x`

**Comment by posva** [comment]
dup of #1187
