### ISSUE TITLE
Wildcard redirects and .addRoute()

### ISSUE THREAD

**Issue by nickforddev** [vuejs/vue-router#1250]
The concept of wildcard redirects is somewhat incompatible with the `.addRoute` method. If I want to add routes dynamically, or even better, asynchronously, I cannot have a wildcard route in routes. Of course, one could add all of the other routes prior to adding a wildcard route, but then you are unable to take advantage of the wildcard route before loading the async routes.

Anybody have any thoughts about this? Is it unreasonable to want both options?

**Comment by posva** [comment]
dup of #1176
