### ISSUE TITLE
Cannot get /...

### ISSUE THREAD

**Issue by awitherow** [vuejs/vue-router#1254]
Regardless of what page I attempt to go to, if I try to go there directly and not through the home page, it gives me, for example:

`Cannot GET /take-action`

How can I navigate to these pages directly?

My router file looks like

```javascript
import Vue from 'vue'
import Router from 'vue-router'

Vue.use(Router)

export default new Router({
  mode: 'history',
  routes: [
    {
      path: '/',
      name: 'hello',
      component: require('components/views/Hello')
    },
    {
      path: '/find-help',
      name: 'find-help',
      component: require('components/views/Find')
    },
    {
      path: '/take-action',
      name: 'take-action',
      component: require('components/views/Action')
    },
    {
      path: '/about',
      name: 'About',
      component: require('components/views/About')
    },
    {
      path: '*',
      name: '404',
      component: require('components/views/Hello')
    }
  ]
})
```

**Comment by awitherow** [comment]
Duh there is a section about it... closing.

**Comment by a21y** [comment]
For those wondering, this is the section: https://router.vuejs.org/en/essentials/history-mode.html

**Comment by kofimokome** [comment]
https://router.vuejs.org/en/essentials/history-mode.html does not solve the problem
I recentlyy deployed my vue js app to heroku and I have the same problem

**Comment by awitherow** [comment]
@kofimokome can you please post your router file?

**Comment by kofimokome** [comment]
`
import Vue from "vue"
import VueRouter from "vue-router"
import Index from "./components/index.vue"
import OfflineDemo from "./components/demo/offline.vue"
import OnlineDemo from "./components/demo/online.vue"
import Login from "./components/authentication/login.vue"
import Register from "./components/authentication/register.vue"
import Profile from "./components/user/profile.vue"
import Game from "./components/user/game.vue"
import Welcome from "./components/demo/notice.vue"

Vue.use(VueRouter)

const router = new VueRouter({
routes: [

    {
      path: "/",
      component: Index,
      meta: {
        title: "Kofi: Tic Tac Toe",
        forVisitors: true
      }
    },

    {
      path: "/demo",
      component: Welcome,
      meta: {
        title: "Welcome",
        forVisitors: true
      }
    },
    {
      path: "/register",
      component: Register,
      meta: {
        title: "Register",
        forVisitors: true
      }
    },
    {
      path: "/login",
      component: Login,
      meta: {
        title: "Login",
        forVisitors: true
      }
    },
    {
      path: "/demo/offline",
      component: OfflineDemo,
      meta: {
        title: "Offline Demo",
        forVisitors:true
      }
    },
    {
      path: "/demo/online",
      component: OnlineDemo,
      meta: {
        title: "Online Demo",
        forVisitors:true
      }
    },
    {
      path: "/dashboard",
      component: Profile,
      meta: {
        title: "Dashboard",
        forAuth:true
      }
    },
    {
      path: "/game",
      component: Game,
      meta: {
        title: "Game",
        forAuth:true
      }
    }
   ],
  mode: "history"
})

export default router

`

**Comment by kofimokome** [comment]
All the code can't fit into the block. Thanks

**Comment by awitherow** [comment]
I can't help you too much @kofimokome as I am not really active with vue anymore... but check out my project, it is working: 

https://github.com/openrefuge/openrefuge/blob/master/src/router/index.js
https://github.com/openrefuge/openrefuge/blob/master/src/main.js

Good luck and let me/us know if you've gotten it fixed 👍

**Comment by kofimokome** [comment]
Thanks @awitherow .<br> I noticed that my `dist ` folder has just one file (`build.js`). I do not know if it is OK or normal because I took a look at yours and I saw other files inside?

**Comment by kofimokome** [comment]
I've seen the solution. I was using webpack simple. So, I switched to webpack and everything is working fine  https://kofitictactoe.herokuapp.com ( still under development so the app is not user friendly)
Thanks for your help @awitherow

**Comment by awitherow** [comment]
Nice @kofimokome glad you figured it out! Sorry I couldn't be of more help m8. Good luck with your project! Would be cool to see it turn into a nice progressive web app 👍 

https://github.com/vuejs-templates/pwa

**Comment by jezperp** [comment]
If anyone stumbles upon this problem, you can just add:
`historyApiFallback: true`
to your webpack.config file

read more:
[https://webpack.js.org/configuration/dev-server/#devserver-historyapifallback](https://webpack.js.org/configuration/dev-server/#devserver-historyapifallback)

**Comment by samayo** [comment]
@awitherow Can you be more civil about your 'help' next time?

**Comment by LinusBorg** [comment]
The comment you are referring to is more than a year old, more recent comments are fine, plus the author is not active anymore - so I think this is a bit unnecessary

**Comment by samayo** [comment]
The comment was made on Mar 15, 2017 so, it's not more than a year old by any calendar. Also, I just encountered this error and came to see a solution, but saw his comment go without being reprimand so I had to say something. 

Its fine if you want to take sides, but my comment wasn't unnecessary

**Comment by gaussianblurs** [comment]
I activated history mode and followed these steps: https://router.vuejs.org/en/essentials/history-mode.html and configured nginx as indicated, now everything works fine except for one route (api-feed), where I get the same error message (Cannot GET /api-feed/whatever) upon refreshing the page or accessing it directly from the adress bar.

Here is my router file:


```
import Vue from 'vue'
import Router from 'vue-router'
import NProgress from 'nprogress'
import Home from '@/components/Home'
import Categories from '@/components/Categories'
import Products from '@/components/Products'
import Product from '@/components/Product'
import About from '@/components/About'
import Page from '@/components/Page'
import APIFeed from '@/components/APIFeed'

Vue.use(Router)

const router = new Router({
    mode: 'history',
    routes: [
        {
            path: '/',
            name: 'home',
            component: Home
        },
        {
            path: '/categories',
            name: 'categories',
            component: Categories
        },
        {
            path: '/categorie/:key_name',
            name: 'products',
            component: Products,
            props: true
        },
        {
            path: '/produit/:id-:key_name',
            name: 'product',
            component: Product,
            props: true
        },
        {
            path: '/a-propos',
            name: 'about',
            component: About
        },
        {
            path: '/api-feed/:feed',
            name: 'api-feed',
            component: APIFeed,
            props: true
        }
    ]
})

router.beforeResolve((to, from, next) => {
    // If this isn't an initial page load.
    if (to.name) {
        // Start the route progress bar.
        NProgress.start()
    }
    next()
})

router.afterEach((to, from) => {
    // Complete the animation of the route progress bar.
    NProgress.done()
})

export default router


```

**Comment by alzmob** [comment]
How can I add historyApiFallback: true ?
I cannot find webpack.js file in my source code.

**Comment by posva** [comment]
Remember we have the [forum](http://forum.vuejs.org/) and the [Discord chat](https://vue-land.js.org/) to ask quick questions!
