### ISSUE TITLE
router.go(n) 是否可以支持类似于 router.push(location) 的 location 参数？

### ISSUE THREAD

**Issue by wynn719** [vuejs/vue-router#1257]
某些场景下需要在调用`router.go(n)`之后去滚动到指定的位置上，`router.go(n)`跟 History 的 `window.history.go(n)`一样，只接受一个向前或者后退多少步的参数，想知道能够让`router.go(n)`能够支持像`router.push(location)`的部分参数吗？

demo：
```
router.go({ hash: 'comment', query: { key: 'test' } })
```

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
Thanks!
