### ISSUE TITLE
Is named view supported for nested routes ?

### ISSUE THREAD

**Issue by albert-kam** [vuejs/vue-router#1258]
I tried this, but doesnt seem to work:

```
{ path: '/modules', children: [
       { path: 'todos', components: {
           selection: TodoSelection,
           content: TodoContent
       } }
     ]
 }

```
But this one without nested routes works out fine:

> { path: '/modules/todos', components: { selection: TodoSelection, content: TodoContent } }

So i assume the children entry doesnt support 'components' yet, only 'component'.

The reason i want use nested model is so that it's easy to mental model paths in hierarchy. Or maybe im using nested route feature wrongly ?

**Comment by posva** [comment]
Yes, it does: http://jsfiddle.net/3cpufcdc/
Next time, please ask the question on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) and share some code so people can help you 🙂

**Comment by albert-kam** [comment]
Thanks you. And sorry for asking it here, i'll go to the forum next, aside from vuejs gitter.
