### ISSUE TITLE
Reload to current route or go(currentroute)

### ISSUE THREAD

**Issue by antivir88** [vuejs/vue-router#1261]
Hello, i used VueJs in cordova app. If app user change lang, where reload page in new locale.

If widnow.location.reload() where current page rendered twice...

Please fix or add reload() method..

**Comment by znck** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. **The issue list only accepts bug reports and feature requests.**
