### ISSUE TITLE
Issue with transition and link anchor

### ISSUE THREAD

**Issue by stefanodotit** [vuejs/vue-router#1262]
I've some problem with router-view and transition, if I remove the tag <transition> from <router-view> it work perfectly, but if I insert a animation the link anchor doesn't work. 
It seem the anchor tag don't "wait" a transition delay  
Link to jsfiddle to test it => http://jsfiddle.net/qw4hbgek/

**Comment by posva** [comment]
Hi! Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You'll probably have to do the jump yourself. You could setup a beforeEach hook and add a query parameter to handle the jump. Something similar what docute does: https://github.com/egoist/docute/blob/master/src/utils/jump.js but without Vuex

**Comment by posva** [comment]
On second thought, I think this could be improved vue-router's side, I'll open a new issue for it
