### ISSUE TITLE
Recursive inclusion of page when use vue-router into iframe.

### ISSUE THREAD

**Issue by rjurado01** [vuejs/vue-router#1264]
I have this code that is a simplification of my code to reproduce the bug:

```html
<!-- index.html -->
<html>
  <head>
  </head>
  <body>
    <iframe srcdoc="<div id='app'></div><script src='https://cdnjs.cloudflare.com/ajax/libs/vue/2.1.10/vue.js'></script><script src='https://cdnjs.cloudflare.com/ajax/libs/vue-router/2.3.0/vue-router.js'></script><script>new VueRouter({});</script>" width="100%" height="600"i></iframe>
  </body>
</html>
```

When I open this file with browser and `new VueRouter({})` is called all the page is including inside iframe and it occurs recursively to infinity:

![vue-router](https://cloud.githubusercontent.com/assets/1703608/24038140/7691b1ca-0b00-11e7-9030-31d25cf88278.png)

Some help?

**Comment by posva** [comment]
Use `mode: 'abstract'` in the router creation.

**Comment by rjurado01** [comment]
@posva Thanks it works!!
