### ISSUE TITLE
Query parser doesn't support nested objects

### ISSUE THREAD

**Issue by danderozier** [vuejs/vue-router#1268]
### Vue.js / vue-router versions
2.1.10 / 2.2.1

### Reproduction Link
https://jsfiddle.net/danderozier/jhcbu84y/1/

### Steps to reproduce
In your vue-router enabled vue app, push a nested object as the router query. For example, take the following statement: 
```
this.$router.push({ query: { order: { name: 'asc' } } })
```

### What is Expected?
One would expect the query string to be built correctly. For the example above, this would be: 
```
?order[name]=asc  // url decoded for legibility
```

### What is actually happening?
Because nested objects aren't supported, the example above results in the query string 
```
?order=[object Object]  // url decoded for legibility
```

Somewhat related: in #1259 someone suggests using qs or a similar library as a querystring parser, which has object support built in.

**Comment by posva** [comment]
Maybe we should use qs to parse query strings, it's only 2kb gzipped

**Comment by trikadin** [comment]
@danderozier 
Small clarification: I don't suggest to change query lib, but to add ability to use any custom stringifier/parser (JSON, for example).

**Comment by posva** [comment]
@danderozier Yes, I know 😄 , and we're probably going to do that. That way people will be able to use anything they want

**Comment by posva** [comment]
Closing in favour of #1259

**Comment by danderozier** [comment]
Looking forward to it—qs would be perfect for me in this particular case. Cheers!
