### ISSUE TITLE
I've got an TypeError from Template by BeforeRouteEnter hooks

### ISSUE THREAD

**Issue by cssxn** [vuejs/vue-router#1270]
```
export default {
  data () {
    return {
      post: null,
      error: null
    }
  },
  beforeRouteEnter (to, from, next) {
    getPost(to.params.id, (err, post) => 
      if (err) {
        // display some global error message
        next(false)
      } else {
        next(vm => {
          vm.post = post
        })
      }
    })
  },
}
```

This example from VueRouter

**if I have  a variable in my template like this:**

```
<div>{{post.auther.name}}<div>
```
I'd got anTypeError I know that  caused by read a inexistent variable from a undefine variable of Object

I suppose that caused by life circle of  BeforeRouteEnter hooks

**Comment by posva** [comment]
The post is unavailable the first time it renders. You should do `{{ post && post.author.name }}`. There're other open issues than are meant to improve that

**Comment by cssxn** [comment]
@posva  

Before The router completed, Render is running?

**Comment by posva** [comment]
The cb passed to `next` is ran after one tick in the view component

**Comment by cssxn** [comment]
@posva  Is there another way to solve it? I mean sth like  resolve of angular's ui-router that could get the depth data before render run.

**Comment by posva** [comment]
Using v-if. Please, refer to the docs: https://router.vuejs.org/en/advanced/data-fetching.html

**Comment by cssxn** [comment]
@posva  Thanks for answer！

**Comment by shaunc869** [comment]
What are the other open issues so I can subscribe to them? Thanks!
