### ISSUE TITLE
Component's lifecycle broken when it is used for multiple routes

### ISSUE THREAD

**Issue by sqal** [vuejs/vue-router#1272]
### Vue.js / vue-router versions
Vue 2.2.4 / Vue-rouer 2.2.1

### Reproduction Link
https://jsfiddle.net/sqal/jexLybm9/

### Steps to reproduce
1. Open reproduction link and observe console logs
2.  Click on /edit (1) link - component's create hook is called
3. Click on /edit (2) link - beforeRouteUpdate is correctly called because the same component is reused
3. Click on /create link - two logs appeared beforeRouteLeave and beforeRouteEnter but there is a bug, where are logs from created hook ( with `mode: 'create' }` and destroyed ( with `{ id: 2, mode: 'edit' }` )
4. Go to /edit (1) - same thing happens, seems like the same component is reused for different routes
5. Let's fix things. In clCreate rotue replace `Editor` component with its cloned version `EditorCreate`. Now repeat steps 1-4, but this time everything works as it should be

### What is actually happening?
Component's lifecycle is broken when it is used for multiple routes.

Same issue as https://github.com/vuejs/vue-router/issues/1212 ?

**Comment by posva** [comment]
Hey, it's working as expected, it's better to reuse the component because it's the same one. If you need to rerun the created hook but still want to use the same component, then you should `key` the component with the route name `:key="$route.name"`.
The other issue is a bit different, it has to deal with keep-alive routes

**Comment by sqal** [comment]
@posva hmm, yeah you're right :) Thank you. I had to add :key on the root router-view component because I don't use it in Editor component. Quick follow up question. If some of my rotues don't have declared name, then :key value will be undefined in some cases, won't this be a problem? Should i use name for every route?

**Comment by posva** [comment]
Yes, it will. I'll personally try `$route.name || $route.path` as a fallback (or something similar). But if you can, add names to every route 🙂
