### ISSUE TITLE
page refresh lost the data of route param 

### ISSUE THREAD

**Issue by jagasan** [vuejs/vue-router#1274]
### Vue.js / vue-router versions
2.1.2 / 2.1.1

### Reproduction Link

http://192.168.2.102:8080/

### Steps to reproduce
1. i added router-link with prams and path of the components
2. when i clicked the images it will render to another page with the value of the product
3. here i refresh the page then data is loss 
### What is Expected?
i don't want to loss the route.prams data in the page when i refresh the page
### What is actually happening?
hi everyone ,
i am pass the object through route one page to another page and  i got value through route.prams but problem is when i am refresh the page data is lost please help 
thanks,

**Comment by posva** [comment]
Hi, please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Make sure to declare the params on the path of the route definition. Cheers
