### ISSUE TITLE
<router-link> don't support e.preventDefault()

### ISSUE THREAD

**Issue by cloudyan** [vuejs/vue-router#1275]
`<router-link>` don't support @click 

include @click.prevent 

Unable to prevent default event（ preventDefault() ）

Render is expected to become  `<a>` tag, the ability to call the click event, and the internal support for `e.preventDefault ()`,

or let `@click.prevent` into effect

http://codepen.io/xiaohan1219/pen/zZjERr?editors=1010

**Comment by znck** [comment]
To listen DOM events on components you've to use `.native` modifier. [Follow docs](https://vuejs.org/v2/guide/components.html#Binding-Native-Events-to-Components).

**Comment by cloudyan** [comment]
@znck has a little question

use `@click.native="handleClick($event)"`

```
handelClick(e) {
  e.preventDefault()
  // use .native support run click,
  // but can't stop default event, router-link as <a> tag, still jump to next router
  console.log('click work')
},
```

**Comment by znck** [comment]
You've to do that in router navigation guards. 

Better use [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue).

Thanks.

**Comment by cloudyan** [comment]
https://codepen.io/xiaohan1219/pen/zZjERr?editors=1012

maybe OK,but is not good,如果是按需加载，每个组件都去实现，太坑了

应该可以路由上统一设置
https://stackoverflow.com/questions/43450663/validate-routes-in-vue

比如在router.beforeEach中设置，已经测试，可以通过配置对应组件，实现 beforeEach 中判断条件是否返回 next(false)

example:
```
router.beforeEach((to, from, next) => {
  const {
    meta = {},
  } = to
  // 约定 status===-1 不允许跳转加载
  if (meta.status === -1) {
    return next(false)
  }

  next()
})
```

**Comment by tarunmangukiya** [comment]
@znck I think that providing is functionality in Vue-link itself will be more reliable as we've to cancel the event. Plus there might be a case in which we are using 10s-100s of links in a page, in this scenario, it becomes difficult to manage them all in navigation guard.

**Comment by RMiguelRivero** [comment]
@cloudyan  This is what I've done to achieve exactly this: 
- Capture the click at a parent level.
- Do the redirect via `$router`.

I understand that this solution would not require the use of `router-link` but it gives you the extra functionality of the `active-class` which is really nice.

```html
<template lang="pug">
    ul
        li(
            v-for="link in links"
            @click.capture="click"
        )
            router-link.link(
                active-class="is-active"
                :to="link.url"
                :title="link.name"
            ) {{link.name}}
</template>

<script>
	export default {
		name: 'my-links'
		props: {
			links: Array
		},
		methods: {
			click($event) {
				// 
				// DO YOUR STUFF HERE
				// 
				this.$router.push({path: $event.target.pathname});
                                 // or just skip the redirect. whatever suits your use case
			}
		}
	}
</script>
```
