### ISSUE TITLE
Feature Request: Switching route with its children by using naming routes

### ISSUE THREAD

**Issue by zheeeng** [vuejs/vue-router#1276]
For example: 

```
routes: [
  { path: '/playground', name: 'playground', component: Playground },
  { path: '/dormitory', name: 'dormitory', redirect: 'Dormitory',
    children: [
      {path: 'g/:id', name: 'girl-dorm', component: GirlDormitory }, 
      {path: 'b/:id', name: 'boy-dorm', component: BoyDormitory },
    ]
  }
]
```
First I switched to '/dormitory/b/123' then I switched to '/playground' by name 'playground'. I expect to switch back to '/dormitory/b/123' by just link to naming route 'dormitory'.

For this purpose, a solution is recording the last route path of each top route:

```
const RouteStackTop = {
  playground: '',
  dormitory: '',
}

const redirectTo = (routeName) => {
  return (dest, src, next) => {
    if (RouteStackTop[routeName] === dest.path) return next()
    RouteStackTop[routeName] = RouteStackTop[routeName] || dest.path
    return next(RouteStackTop[routeName])
  }
}

const routes = [
  { 
    path: '/playground', name: 'playground', component: Playground,
    beforeEnter: redirectTo('playground')
  },
  { 
    path: '/dormitory', name: 'dormitory', redirect: 'Dormitory',
    beforeEnter: redirectTo('dormitory'),  // redirect to /dormitory/b/123
    children: [
      {path: 'g/:id', name: 'girl-dorm', component: GirlDormitory }, 
      {path: 'b/:id', name: 'boy-dorm', component: BoyDormitory },
    ]
  }
]

```

When we simulate a iOS app with tabbar, it is a common situation that bottom tabbar-item link to '/favorites', '/recents', '/contacts', '/keypad', when we first switch to '/recents/missed' then switch to '/favorites', if we next touch 'recents', the app will show the 'missed' page, not the 'all' page. We can also be redirected to '/contacts/jhon' if the the path of last view of 'contacts' is '/contacts/jhon'

The route tree looks like:
```
/favorites
/recents
    /all
    /missed
/contacts
    /:name
/keypad
```

**Comment by posva** [comment]
I may not be getting what you mean because the explanation of the problem being solved is simply too short but we cannot make that because a `{ name: 'dormitory' }` is meant to go to the `dormitory` route. If we implicitly keep previous parameters, that'd lead to unpredictable behaviour as well as a breaking change

**Comment by zheeeng** [comment]
@posva Yeah, I want to switch to a route with the latest parameters of it. Maybe vue-router can provide a way to retrieval the path history (not the windows.history api), e.g. add a 'tracing' array contains the visited routes' path and name infos, user can easily check the tracing info.

**Comment by posva** [comment]
In that case, you should save those parameters in a global state upon entering the route, and reuse them when necessary.
