### ISSUE TITLE
Default child route disappear if immediately revisitting

### ISSUE THREAD

**Issue by posva** [vuejs/vue-router#1281]
> from #1273 @hworld

### Vue.js / vue-router versions
2.1.2 / 2.1.1

### Reproduction Link

http://jsfiddle.net/L7hscd8h/934/

### Steps to reproduce
Click on  /users/foo twice

### What is Expected?

The default child route Home should either not appear at first, or (better) stay there

### What is actually happening?
The child route is hidden when clicking the second time on the link

**Comment by tiagojpdias** [comment]
According to the warning at the console

`[vue-router] Named Route 'user' has a default child route. When navigating to this named route (:to="{name: 'user'"), the default child route will not be rendered. Remove the name from this route and use the name of the default child route for named links instead.`

And making those changes

@template
`<router-link :to="{ name: 'user.home', params: { id: 'foo' } }">/user/foo</router-link>`

@routes
`{ path: '/user/:id', component: User,`

After these changes I cannot reproduce your bug, so it seems fixed.

http://jsfiddle.net/L7hscd8h/1016/

**Comment by posva** [comment]
I'm marking this as an improvement because even though the behaviour is unexpected it's happening in a warned use case. Also, I don't know about a real use case when you may want to go to the parent route without displaying the default (`path: ''`) child.
