### ISSUE TITLE
beforeRouteEnter 

### ISSUE THREAD

**Issue by weifeiyue** [vuejs/vue-router#1282]
### Vue.js / vue-router versions
2.2.5 / 2.3.0

### What is Expected?
beforeRouteEnter 应该执行一次
### What is actually happening?
beforeRouteEnter 执行了两次

**Comment by posva** [comment]
Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
