### ISSUE TITLE
`from` and `to` values the same in `scrollBehaviour`

### ISSUE THREAD

**Issue by jazoom** [vuejs/vue-router#1284]
### Vue.js / vue-router versions
2.2.6 / 2.3.0

### Steps to reproduce
```
scrollBehavior (to, from, savedPosition) {
    console.log('to: ' + to.path);
    console.log('from: ' + from.path);
    return { x: 0, y: 0 };
}
```

### What is Expected?
`from` should be the route object of the route before navigation

### What is actually happening?
`from` appears to be the same as `to`

**Comment by posva** [comment]
Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or Github repository containing a set of reproducible steps that can lead to the behaviour you described. Make sure to boil down the problem as much as possible. Thanks!

**Comment by jazoom** [comment]
I'd be surprised if you can't just put that function into your router in any app and get the behaviour I'm describing. Do you not see this behaviour?

I boiled it down to 1 function. That's pretty well boiled down I thought.

**Comment by posva** [comment]
If I tried to reproduce every issue people open without a link, I'll spend my days doing that 🙂

**Comment by jazoom** [comment]
It's just one function. I'm just reporting the value that the router provides to scrollBehavior.

Do you have an already set-up JSFiddle that I can plug this function into?

**Comment by posva** [comment]
Oh god... I knew this was fixed already, that's why I was asking for the repro. Turns out it hasn't been released yet.
The link of the repro is on the new issue template. Next time collaborate a bit, and take the time to make the repro. For this specific issue it literally took me 30 seconds to do so, so you really have no excuses.

You may want to give this a read: https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff

**Comment by jazoom** [comment]
Sorry, I wasn't being lazy. Actually, you might remember a few days ago I provided a reproduction for a serious memory leak issue that I reported. I don't usually use JSFiddle so I'd have to spend a bit of time learning it first, which I thought would be silly seeing as this is such a basic and obvious issue. <-- the excuse

Ah, thanks. I didn't notice the JSFiddle link in the new issue thing.

**Comment by posva** [comment]
I couldn't remember because of the github avatar 😄 
Don't worry, jsfiddle is super straightforward 🙂

**Comment by jazoom** [comment]
Yes, I should probably get around to adding a proper avatar.

Now that I know about the already set-up jsfiddle it should be pretty easy and I'll have, as you said, no excuse. 😀
