### ISSUE TITLE
If router-link pass undefined should it render element a without href attribute

### ISSUE THREAD

**Issue by ausir0726** [vuejs/vue-router#1289]
I have a menu list , one of them don't have href data 
when I pass undefined to router-link , it can't show correct on screen .

https://jsfiddle.net/9r6xhqbp/19/

If I pass a undefined to router-link , should it give me a element without href and click binding ? 

because I don't want click event ( I can use e.preventDefault ) , and without href attribute , because with SSR will have a weird href ....

I checked w3c , a don't have href is valid . ( I think so )

thanks .

**Comment by fnlctrl** [comment]
Hi, thanks for filing this issue. You can simply use an `<a>` tag with v-if: https://jsfiddle.net/8xzqu3f9/
as `<router-link>` is only meant for in-app navigation.

**Comment by ausir0726** [comment]
@fnlctrl  thanks, your suggest is same with my current  solution .
but , now you need maintain two same value variable in template .

jsfiddle just a simple example , when in production it more complex , maybe with a submenu or  dropdown , that will be more problem with maintain period .

If give a empty string or give undefined , just return `<a>` without `href` and `click event` will not be easy understand or looking better or easier maintain ? 

anyway , grateful to this great framework .

**Comment by fnlctrl** [comment]
Well, the current behavior is to protect developers from typos or errors, as you can see an error when passing an invalid `to` prop:
```
[Vue warn]: Invalid prop: type check failed for prop "to". Expected String, Object, got Undefined. 
(found in <RouterLink>)
```


For complex templates, I think it would be better to create a component to decide whether to render a `<router-link>` or a plain `<a>` tag: https://jsfiddle.net/cfc9t3oa/

**Comment by ausir0726** [comment]
@fnlctrl  I think you're right.
protect developers error is also important .
I will following to do a component outside router-link let it easier maintain .

thank you .
