### ISSUE TITLE
alwaysRefresh option for route definition

### ISSUE THREAD

**Issue by kwronski** [vuejs/vue-router#129]
Hi,

There was an option "alwaysRefresh" on route definitions which forced component to be reloaded when switch between two routes using the same component.
How can I handle this functionality in current router version ?

**Comment by azamat-sharapov** [comment]
I think [`canReuse`](http://router.vuejs.org/en/pipeline/can-reuse.html) is what you need.

**Comment by kwronski** [comment]
Thank you, it works!
