### ISSUE TITLE
Use an array for path matching?

### ISSUE THREAD

**Issue by Fohlen** [vuejs/vue-router#1292]
I was unsure wether to file this as an issue or a feature request. Currently the `API` proposes that the `path` attribute must be a `String` object. This is quiet hindering, when you think of the following case:

```
    { path: '/participant', component: ParticipantFilter, name: 'participant' },
    { path: '/participant/(.*)', component: ParticipantFilter, name: 'participant' },
```

1. This does produce a lot of `DRY` code
2. Named routes are bugging this way

It would be more elegant with:
```
    { path: ['/participant', '/participant/(.*)'], component: ParticipantFilter, name: 'participant' },
```

Are there any plans to bring `Array` path attributes?

**Comment by LinusBorg** [comment]
Can you explain the use case for this, in comparison to an alias?

**Comment by posva** [comment]
Just use an alias (it also supports arrays)
