### ISSUE TITLE
懒加载的时候，模板报错 Property or method "count" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.  (found in <Anonymous> - use the "name" option for better debugging messages.)

### ISSUE THREAD

**Issue by GreatBoy** [vuejs/vue-router#1293]
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by fnlctrl** [comment]
Hi, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Thanks!

**Comment by GreatBoy** [comment]
sorry, i have miss image, but i resoved!
