### ISSUE TITLE
网址出现"."路由解析问题

### ISSUE THREAD

**Issue by nevergiveup-j** [vuejs/vue-router#1298]
路由地址中有"."提示Cannot GET /1/7.1
127.0.0.1:8080/1/7.1.1

以下是代码
```
export default [
    {
        path: '/',
        component: Root,
        children: [
            {
                path: '/:device/:version',
                component: ShareComment
            }
        ]
    }
]

```

versions:
Vue.js 2.1.0
vue-router 2.1.1

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
Thanks!

---

You probably need to check this: http://router.vuejs.org/en/essentials/history-mode.html
