### ISSUE TITLE
npm run unit prompt '[Vue warn]: Error in render function: (found in <RouterLink>)'

### ISSUE THREAD

**Issue by jomyhuang** [vuejs/vue-router#1299]
I've project created by Vue-cli and apply vue-router 2.2 fixed Hello.vue:
 <router-link to="/myapp">Link</router-link>

my package.json:
  "dependencies": {
    "vue": "^2.2.1",
    "vue-router": "^2.2.0",
    "vuex": "^2.2.1"
  },

it's work okay, but run "npm run unit", always prompt some warning each unit test:

ERROR LOG: '[Vue warn]: Error in render function:
(found in <RouterLink>)'
ERROR LOG: TypeError{stack: 'render@http://localhost:9876/base/index.js?73dd11bb4cb5ba65a68430f337de29bfaa5d4c05:46874:21
_render@http://localhost:9876/base/index.js?73dd11bb4cb5ba65a68430f337de29bfaa5d4c05:5963:26
updateComponent@http://localhost:9876/base/index.js?73dd11bb4cb5ba65a68430f337de29bfaa5d4c05:4512:28
get@http://localhost:9876/base/index.js?73dd11bb4cb5ba65a68430f337de29bfaa5d4c05:4823:29
Watcher@http://localhost:9876/base/index.js?73dd11bb4cb5ba65a68430f337de29bfaa5d4c05:4806:15
mountComponent@http://localhost:9876/base/index.js?73dd11bb4cb5ba65a68430f337de29bfaa5d4c05:4516:28
$mount@http://localhost:9876/base/index.js?73dd11bb4cb5ba65a68430f337de29bfaa5d4c05:9606:24
$mount@http://localhost:9876/base/index.js?73dd11bb4cb5ba65a68430f337de29bfaa5d4c05:11655:20
init@http://localhost:9876/base/index.js?73dd11bb4cb5ba65a68430f337de29bfaa5d4c05:5285:19
createComponent@http://localhost:9876/base/index.js?73dd11bb4cb5ba65a68430f337de29bfaa5d4c05:7010:10
createElm@http://localhost:9876/base/index.js?73dd11bb4cb5ba65a68430f337de29bfaa5d4c05:6953:24
createChildren@http://localhost:9876/base/index.js?73dd11bb4cb5ba65a68430f337de29bfaa5d4c05:7078:18
createElm@http://localhost:9876/base/index.js?73dd11bb4cb5ba65a68430f337de29bfaa5d4c05:6986:23
patch@http://localhost:9876/base/index.js?73dd11bb4cb5ba65a68430f337de29bfaa5d4c05:7409:16
_update@http://localhost:9876/base/index.js?73dd11bb4cb5ba65a68430f337de29bfaa5d4c05:4389:28
updateComponent@http://localhost:9876/base/index.js?73dd11bb4cb5ba65a68430f337de29bfaa5d4c05:4512:17
get@http://localhost:9876/base/index.js?73dd11bb4cb5ba65a68430f337de29bfaa5d4c05:4823:29
Watcher@http://localhost:9876/base/index.js?73dd11bb4cb5ba65a68430f337de29bfaa5d4c05:4806:15
mountComponent@http://localhost:9876/base/index.js?73dd11bb4cb5ba65a68430f337de29bfaa5d4c05:4516:28
$mount@http://localhost:9876/base/index.js?73dd11bb4cb5ba65a68430f337de29bfaa5d4c05:9606:24
$mount@http://localhost:9876/base/index.js?73dd11bb4cb5ba65a68430f337de29bfaa5d4c05:11655:20
http://localhost:9876/base/index.js?73dd11bb4cb5ba65a68430f337de29bfaa5d4c05:61927:38
callFn@http://localhost:9876/absolute/Users/jomyhuang/Desktop/dev/vueapp01/node_modules/.3.2.0@mocha/mocha.js?0491afff0b566ea45cd04c9164a355dba705689e:4447:25
run@http://localhost:9876/absolute/Users/jomyhuang/Desktop/dev/vueapp01/node_modules/.3.2.0@mocha/mocha.js?0491afff0b566ea45cd04c9164a355dba705689e:4439:13
runTest@http://localhost:9876/absolute/Users/jomyhuang/Desktop/dev/vueapp01/node_modules/.3.2.0@mocha/mocha.js?0491afff0b566ea45cd04c9164a355dba705689e:4936:13
http://localhost:9876/absolute/Users/jomyhuang/Desktop/dev/vueapp01/node_modules/.3.2.0@mocha/mocha.js?0491afff0b566ea45cd04c9164a355dba705689e:5042:19
next@http://localhost:9876/absolute/Users/jomyhuang/Desktop/dev/vueapp01/node_modules/.3.2.0@mocha/mocha.js?0491afff0b566ea45cd04c9164a355dba705689e:4853:16
http://localhost:9876/absolute/Users/jomyhuang/Desktop/dev/vueapp01/node_modules/.3.2.0@mocha/mocha.js?0491afff0b566ea45cd04c9164a355dba705689e:4863:11
next@http://localhost:9876/absolute/Users/jomyhuang/Desktop/dev/vueapp01/node_modules/.3.2.0@mocha/mocha.js?0491afff0b566ea45cd04c9164a355dba705689e:4787:16
http://localhost:9876/absolute/Users/jomyhuang/Desktop/dev/vueapp01/node_modules/.3.2.0@mocha/mocha.js?0491afff0b566ea45cd04c9164a355dba705689e:4831:9
timeslice@http://localhost:9876/absolute/Users/jomyhuang/Desktop/dev/vueapp01/node_modules/.3.2.0@mocha/mocha.js?0491afff0b566ea45cd04c9164a355dba705689e:82:27', line: 46874, sourceURL: 'http://localhost:9876/base/index.js?73dd11bb4cb5ba65a68430f337de29bfaa5d4c05'}

thank your help!

**Comment by posva** [comment]
Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks!

**Comment by jomyhuang** [comment]
got it thank you

**Comment by buildAll** [comment]
@jomyhuang I got the similar error when execute npm run unit. How did you fix this error?

====================================

UPDATE:

I find the root cause of this error.  There is some error in the .vue file. In my case, I forget to add $t method in the unit test's index.js file, and when the unit test be executed, it can not find the $t method. 

The solution is simply import 'vue-i18n' in the unit test entry file and then Vue.use(Vuei18n).

**Comment by jomyhuang** [comment]
got it! thank you!
