### ISSUE TITLE
vue-router has an object containing 'default'

### ISSUE THREAD

**Issue by ghost** [vuejs/vue-router#1301]
This isn't a major issue but finding a fix for this would certainly be helpful.

I can import Vue like this: `window.Vue = require('vue');` which is great.
I can't import vue-router the same. I have to do: `window.VueRouter = require('vue-router').default;`

The sample applies to `import Vue from 'vue'; import VueRouter from 'vue-router';` the latter is an object containing default.

Both libraries seem to export themselves the same, so why is the behavior different?

Babel 6 changed the behavior of export default, and from my understanding, ditched commonJS exporting. There is a plugin called "add-module-exports" which doesn't seem to fix it. Probably because babel doesn't touch node_modules.

My `.babelrc`:

```
{
    "presets": [
        ["es2015", { "modules": false }],
        ["stage-3"],
        ["env"]
    ],
    "plugins": [
        "add-module-exports"
    ]
}
```

Is there any explanation to this behavior and is there a way around it?

**Comment by posva** [comment]
Well, that's weird because both, vue and vue-router have an esm and a commonjs file, and, both main/module entries in their respective package.json files are pointing to the right one. Are you sure you haven't defined an alias?

I tested by running `vue build main.js` with

```js
// main.js
import Router from 'vue-router'
import Vue from 'vue'

console.log(Vue)
console.log(Router)
```

and it works fine

**Comment by ghost** [comment]
I am absolutely sure. It was a fresh Laravel project so there isn't much JavaScript to work with. The need to have `.default` has been a thing since 2015: http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default I just can't find a way around it.

Here are my dev dependencies. I've removed dependencies that are not related (such as jQuery and Lodash):

```
{
  "devDependencies": {
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-polyfill": "^6.23.0",
    "babel-preset-env": "^1.1.8",
    "babel-preset-stage-3": "^6.17.0",
    "cross-env": "^3.2.3",
    "laravel-elixir": "^6.0.0-15",
    "laravel-elixir-vue-2": "^0.3.0",
    "laravel-elixir-webpack-official": "^1.0.10",
    "laravel-mix": "^0.8.3",
    "vue": "^2.1.10",
    "vue-router": "^2.3.1"
  }
}
```

I don't use `cross-env` and `laravel-mix` but I know that `laravel-mix` has some babel dependencies.

I'm not saying that Vue Router has an issue itself but something is going on with my set up that seems to treat Vue Router differently to Vue. I'm certain that Vue Router is unlikely to be the only library that behaves like this so I'd like to get to the bottom of why and how to fix it.

**Comment by ghost** [comment]
When you evaluate a `import VueRouter from 'vue-router'` using babel with es2015 preset you will get the following:

```js
'use strict';

var _vueRouter = require('vue-router');

var _vueRouter2 = _interopRequireDefault(_vueRouter);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```

We can see that if Vue Router does not have `_esModule` (not sure where it comes from or what it does) then the imported Vue Router will be an object containing a default key.

Further inspection in my code (webpack + babel) reveals this: `exports["default"] = VueRouter;` which would explain why I can only access VueRouter via `.default`. Yet if I look at how Vue is exported, I see this `module.exports = Vue$3;`. I'm failing to see why they are different.

Furthermore, running `export default { }` using babel with es2015 preset you will get the following:

```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = {};
```

This makes me think that Vue is using `module.exports = ...` as shown above but VueRouter is using `export default = ...` which in turn converts into `exports["default"] = ...` but... why?

**Comment by posva** [comment]
There's probably something wrong in the webpack config. Make sure to be using the `vue-router.esm.js` in the import. You can try `import Router from 'vue-router/dist/vue-router.esm.js'`. That one only works with es2015 imports. If that doesn't work, try again with the `vue-router.common.js`. This can be setup with alias in the webpack config so you can just import `vue-router`. 

Closing this since your issue lies with the tooling. If you need further help, I encourage you to ask the question on the [forum](http://forum.vuejs.org/) but I think you should be able to take care of it with the advice below 🙂
