### ISSUE TITLE
Component instances are destroyed before a transition leave done callback is called

### ISSUE THREAD

**Issue by jesse-mm** [vuejs/vue-router#1302]
### Vue.js / vue-router versions
2.2.6 / 2.3.1

### Reproduction Link
[https://jsfiddle.net/pyh4uzxb/3/](https://jsfiddle.net/pyh4uzxb/3/)

### Steps to reproduce
1) Wrap a transition component around the router-view with an attribute ```leave="leaveFn"```
2) Call the done method after a few seconds
3) Observe that the DOM with components is still rendered but the component instances are already destroyed.

### What is Expected?
The component would still be instantiated.

### What is actually happening?
The component is still rendered in the DOM but the component instances are already destroyed.

**Comment by posva** [comment]
This is actually how Vue works (it happens without vue-router), the DOM element is still there for the transition but it's not reactive anymore since there's no Vue instance anymore
