### ISSUE TITLE
target="_blank" doesn't trigger if <router-link> contains child elements (e.g. <span>)

### ISSUE THREAD

**Issue by bradbeattie** [vuejs/vue-router#1303]
I've confirmed that this happens in the most recent version of vue and vue-router.

    const target = e.currentTarget.getAttribute('target')
    if (/\b_blank\b/i.test(target)) return

The problem is that this block of code isn't necessarily testing the generated <a> tag due to the use of "currentTarget".

**Comment by posva** [comment]
Hey,the most recent version of vue-router doesn't include that fix yet but it was fixed in #1290
