### ISSUE TITLE
Root link is always getting active class applied. 

### ISSUE THREAD

**Issue by vanderlin** [vuejs/vue-router#1305]
The root link `/` is always getting the active class. 
![image](https://cloud.githubusercontent.com/assets/149997/24663992/7497557a-1927-11e7-80df-8637f739033a.png)

![image](https://cloud.githubusercontent.com/assets/149997/24664008/81df0cc8-1927-11e7-9d94-44200c5beb74.png)

**Comment by sqal** [comment]
You should add exact prop to the first link:

https://router.vuejs.org/en/api/router-link.html

**Comment by patforg** [comment]
Had same issue and adding exact worked for me.

**Comment by posva** [comment]
Pretty much what was said 🙂 
Please, next time, ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) first
