### ISSUE TITLE
页面(路由)之间如何通信了？

### ISSUE THREAD

**Issue by striverx** [vuejs/vue-router#131]
第一次使用这个库，感觉非常好用，但现在遇到个问题，相关的路由之间怎么传递数据了？比如我要在A路由对应的页面里输入一些数据，验证成功后带上数据跳转到B路由对应的页面。是不是可以在切换钩子函数的 transition 参数上实现？

**Comment by yyx990803** [comment]
通常建议做一个 store 层来存放多个组件共享的全局数据。

**Comment by striverx** [comment]
好的，谢谢指点。

**Comment by guhongjie** [comment]
@yyx990803 有更优雅的解决方案吗？

**Comment by fnlctrl** [comment]
@guhongjie 使用vuex

**Comment by qinzitong** [comment]
用vuex怎么搞？
