### ISSUE TITLE
Missing TS definition for router push

### ISSUE THREAD

**Issue by druppy** [vuejs/vue-router#1312]
### Version
2.3.0

### Reproduction link
[https://jsfiddle.net/7syt1bdu/](https://jsfiddle.net/7syt1bdu/)

### Steps to reproduce
When writing `router.push({name: 'xx', params: {id: 2}}` TS will complain about the type is not right.

### What is expected?
Problem free TS compilation :-)

### What is actually happening?
TS error 

---
adding this to `types/router.d.ts`, fix the issue :

``` typescript
export interface LocationObject {
    name?: string,
    path?: string,
    params?: Object
    query?: Object
}
export type RawLocation = string | Location | LocationObject;
```

**Comment by posva** [comment]
A PR would be even better 🙂

**Comment by druppy** [comment]
Ok, i make the PR danse 😁

**Comment by druppy** [comment]
Location `params` and `query` may only hold string values, and I passed along a number. Sorry, move on ... nothing to see :-)
