### ISSUE TITLE
Support setting the active-class attribute for <router-link> to an empty string to prevent setting a class.

### ISSUE THREAD

**Issue by lehni** [vuejs/vue-router#1314]
### What problem does this feature solve?
I would like to prevent the setting of the class attribute on a router-link component. Setting it to an empty string has no effect, I have to set it to `" "` currently to prevent the class being set.

### What does the proposed API look like?
e.g.:
```html
<router-link tag="button" to=".." active-class="" append>Cancel</router-link>
```

**Comment by posva** [comment]
why do you need this? You could set it to an unused class if it's about styling purposes

**Comment by lehni** [comment]
In the example I am creating a `<button>`, and I thought it was strange that it would receive the same styling that I had already defined for the other router-link elements, so I tried to deactivate it. It's not a big deal, I'm using `a.router-link-active` for the other styling now so it does not clash any longer, but I was a bit surprised that this wouldn't work.
