### ISSUE TITLE
Function or bug ?

### ISSUE THREAD

**Issue by sciooga** [vuejs/vue-router#1315]
### Version
2.3.0

### Reproduction link
[https://jsfiddle.net/sciooga/rahhqu0o/](https://jsfiddle.net/sciooga/rahhqu0o/)

### Steps to reproduce
click navigate1 and navigate2 button

### What is expected?
change query every times

### What is actually happening?
navigate1 return a str and just change once

**Comment by yyx990803** [comment]
`$route.query` is considered immutable. The router compares the new query against the old query - however because you mutated the old query and passed it to `router.push`, the comparison is basically comparing the same object to itself.

Cloning is the correct way to do it.

**Comment by huysh3** [comment]
@sciooga 
`let query = JSON.parse(JSON.stringify(this.$route.query))`
Not pretty, but effective.
