### ISSUE TITLE
When using router.replace() or router.push() in the ios wechat 6.5.7 browser page changed but URl did not change

### ISSUE THREAD

**Issue by webKity** [vuejs/vue-router#1316]
### Version
2.4.0

### Reproduction link
[http://testwx.jiaozula.cn/shareMore](http://testwx.jiaozula.cn/shareMore)

### Steps to reproduce
1. open http://testwx.jiaozula.cn/shareMore in ios wechat 6.5.7
2. click the '活动细则 >' link
3. copy the url by wechat
4. see the url remain http://testwx.jiaozula.cn/shareMore 

### What is expected?
at the fourth step the url should be http://testwx.jiaozula.cn/shareHelp

### What is actually happening?
at the fourth step the url is http://testwx.jiaozula.cn/shareMore

**Comment by posva** [comment]
Can you provide an editable fiddle, please. You can use this as a base http://jsfiddle.net/posva/9r6xhqbp/

**Comment by webKity** [comment]
```javascript
<div id="app">
  <router-link to="/">/home</router-link>
  <router-link to="/foo">/foo</router-link>
  <router-view></router-view>
</div>
<script src="https://unpkg.com/vue/dist/vue.js"></script>
<script src="https://unpkg.com/vue-router/dist/vue-router.js"></script>
<script>
  const Home = { template: '<div>I am Home: but the url is demo.html in ios wechat 6.5.7</div>' }
  const Foo = { template: '<div>I am Foo: but the url is demo.html in ios wechat 6.5.7</div>' }			
  const router = new VueRouter({
    mode: 'history',
    routes: [
    { path: '/', component: Home },
    { path: '/foo', component: Foo }
  ]
})			
new Vue({
  router,
  el: '#app'
})
</script>
```

1. new a .html file and open this file in ios weChat 6.5.7 (you need a server)
2. click the link 
3. see the url, and the url is not change

**Comment by James-dai** [comment]
@webKity

i also have this bug

first page: www.demo.html?#!/

this.$router.push('/b')

but on the wechat is not  www.demo.html?#!/b

still www.demo.html?#!/

when i refresh current page on the wechat , it has been changed www.demo.html?#!/b

**Comment by James-dai** [comment]
@webKity
hi webKity,
Do you resolve this question?

**Comment by wjhcc2018** [comment]
i also have this question，did you resolve this？

**Comment by webKity** [comment]
no

**Comment by wjhcc2018** [comment]
我查了查api，应该是微信浏览器那边的问题，微信浏览器只会记住你第一次进来的地址，有那么3种解决方案：
1、修改路由模式为hash，
2、你用history的时候，把router-link换成a标签跳转
3、如果遇到分享的问题，就每次请求签名...
看看这个https://github.com/vuejs/vue-router/issues/481

**Comment by callumacrae** [comment]
If I recall correctly, this is because the wechat browser doesn't support the HTML5 history mode.

**Comment by posva** [comment]
@callumacrae  If you have a website where I can lookup that information, I would be grateful to get the link
Installing a strange pkg from a torrent on my phone is something I'm reluctant to do...

**Comment by callumacrae** [comment]
@posva i have no idea, I can only find stuff in chinese 😬  but I'm pretty sure I've heard this a few times

**Comment by posva** [comment]
The version looks recent, though (April 2017)

**Comment by Lidingkorol** [comment]
i also have this problem , who can reslove this problem

**Comment by wjhcc2018** [comment]
@Lidingkorol  我改成hash模式了

**Comment by willsky7** [comment]
@Say-Hello 改成hash模式 但是还是没有生效,请问还有别的解决办法吗？

**Comment by willsky7** [comment]
@webKity  Did you solve the problem at last？

**Comment by buzhou9** [comment]
我也遇见了类似的问题，push以后，路由没有改变，并且同样的代码，同样的手机设备，同样的webview，在网络环境不同的时候表现不一致，当我链接wifi的时候，push以后正常跳转下一个页面，使用4g网络的时候，push以后无法跳转下一个页面，路由信息也没有改变

**Comment by posva** [comment]
Completely forgot to close this for inactivity 😅

**Comment by hellojavaer** [comment]
使用下面这种方式可以解决，不过有一点不完美的地方是如果分享在微信中显示的url还是第一次进来的，不过点击链接打开的页面还是正确的。

`
router.beforeEach((to, from, next) => {
  setTimeout(function () {
    window.location = window.location;
  }, 500);
});

`

**Comment by 565784135** [comment]
有个最笨的方法，手动跳转  location.href = '/#/login'
