### ISSUE TITLE
beforeRouteEnter not triggered when component is reused

### ISSUE THREAD

**Issue by nirazul** [vuejs/vue-router#1322]
### Version
2.4.0

### Reproduction link
[http://jsfiddle.net/yj21tp09/](http://jsfiddle.net/yj21tp09/)

### Steps to reproduce
1. Open the fiddle
2. Switch between routes (should work)
3. Change version to 2.4.0
4. Switch between routes (doesn't work)

### What is expected?
In older versions I was able to reuse a component with different paths. The `beforeRouteEnter` hook was triggered nonetheless.

### What is actually happening?
In 2.4.0 this behaviour is broken. The hook isn't called anymore.

---
This seems to be a direct consequence of https://github.com/vuejs/vue-router/issues/750 as `match.instances` is empty for the route changes that don't work.

**Comment by posva** [comment]
BTW you can provide versions when using unpkg.com: http://jsfiddle.net/posva/xjoojctq/

**Comment by nirazul** [comment]
@posva I'm not sure what you mean, I've included the script like that to switch between two vue-router versions within one fiddle.

**Comment by posva** [comment]
Sorry, it wasn't clear, I meant that you don't need to make it complicated, you can just pass the version in the script tag, it'll be enough to check 🙂
Also make sure to use unpkg and not npmcdn (it got renamed)

**Comment by nirazul** [comment]
Ah, I understand. Thanks for clearing things up.

**Comment by francoisromain** [comment]
It looks like it's not only the `beforeRouteEnter` hook which doesn't work, but any router method when a component is reused. (p.e.: `$router.replace`, `router-link :to`, etc.)

**Comment by xxRockOnxx** [comment]
but if `beforeRouteEnter` does not work how come `next()` gets called? But even then, my data are not updating even if it's called.
