### ISSUE TITLE
Global active-class overwrites local active-class

### ISSUE THREAD

**Issue by cspeer** [vuejs/vue-router#1323]
### Version
2.4.0

### Reproduction link
[https://jsfiddle.net/2p7jph02/3/](https://jsfiddle.net/2p7jph02/3/)

### Steps to reproduce
1. Define global `linkActiveClass`
2. Define local `active-class` on `router-link`

### What is expected?
The local `active-class` should overwrite the global `linkActiveClass` definition.

### What is actually happening?
The global `linkActiveClass` definition overwrites local `active-class`

**Comment by posva** [comment]
Thanks, I'll take a look

**Comment by cspeer** [comment]
It may be related to #1314 ?

**Comment by posva** [comment]
Yes, it is, the fix there caused it
