### ISSUE TITLE
Offer a configurable parameter to remove /#/ when the link is '/' in hash-mode.

### ISSUE THREAD

**Issue by ghost** [vuejs/vue-router#1327]
### What problem does this feature solve?
when I use vue-router in hash-mode, the index link is replaced with '/#/', it is ugly usually, I think the home page url does not need to append the '/#/'.I know use history-mode can remove '#', but in my project the most page render by server side.

before:
  http://router.vuejs.org/#/
  http://router.vuejs.org/#/api
  http://router.vuejs.org/#/document

after:
  http://router.vuejs.org
  http://router.vuejs.org/#/api
  http://router.vuejs.org/#/document

I modify the vue-router code.

```
function replaceHash (path) {
  var i = window.location.href.indexOf('#');
  if (i === -1) {
    return; <--- importance
  }
  window.location.replace(
    window.location.href.slice(0, i >= 0 ? i : 0)   '#'   path
  );
}
```

It can resolve my problem, but I prefer it has a configurable parameter.

### What does the proposed API look like?
indexHash: false

**Comment by posva** [comment]
If you don't want to have an empty path you can make `/` redirect to something like `/home` so you always have something after the `#/`
Having the ending hash is intended to be more consistent with all the other paths and changing it can suppose a problem to other people relying on that path, so unfortunately, we are not likely to change that.
You can still change the location on a navigation guard to make it look _pretty_. It should work 🙂
