### ISSUE TITLE
Suggestion: v-link change to `link` with optional `bind-` or `:=` to use an expression

### ISSUE THREAD

**Issue by cheapsteak** [vuejs/vue-router#133]
The majority use case for using v-link is with a literal, don't want to wrap all of their values in quotes  

Also `.=""` literally looks like a typo

**Comment by yyx990803** [comment]
So with the latest discussion for the new binding syntax, we are moving away from un-prefixed custom attributes. The new literal syntax is `v-link#="/a/b/c"`.
