### ISSUE TITLE
router-link triggers navigation with no user interaction

### ISSUE THREAD

**Issue by ghost** [vuejs/vue-router#1330]
### Version
2.4.0

### Reproduction link
[https://jsfiddle.net/addyjj/e2Ltj7h6/](https://jsfiddle.net/addyjj/e2Ltj7h6/)

### Steps to reproduce
1. Create a route that redirects to 'google.com'.
2. Add a route-link that points to route created in step 1.
3. On page load, the redirect code is executed even though the link was never clicked on.

### What is expected?
Redirect code shouldn't execute unless user clicks on link.

### What is actually happening?
Redirect code of router-link is executed on page load.

---
I used chrome. If you run the fiddle with console open you can see the redirect code is being executed without clicking on the link.

**Comment by posva** [comment]
I thought there was an open issue about this but I couldn't find it 😆

**Comment by javoski** [comment]
The redirect function need to be called to render ```router-link```.

**Comment by posva** [comment]
Yeah, that's true, it allows to resolve the actual link to be displayed on the `a` element
Thanks for tuning in 😄 

I think a note should be added to the notes, just under the function example at http://router.vuejs.org/en/essentials/redirect-and-alias.html

**Comment by ghost** [comment]
Thanks for the explanation. I guess what I was really trying to do was navigate to an external link, but I wanted to hide the ugly external login URL behind a clean looking "/login" URL.

```javascript
    {
      path: '/login',
      name: 'login',
      redirect: to => {
        window.location = store.getters['auth/loginUrl']
        return '/'
      }
    }
```

Maybe the following request is what I am looking for:
#1280 (Feature request: enable some way of handling external links by router.)

Thanks for your time!

**Comment by lbineau** [comment]
It is a common case to have some links that have been removed and you want to act like a 301 redirection. 
We add a htaccess file but we also need to handle it for the links in Vue app.

**Comment by LinusBorg** [comment]
@lbineau If you talk about routes links being removed, you can simply change the routes deifnition to redirect to an error page, right?

@jeremy-addy Yes, you usecase would be solved with #1280

**Comment by lbineau** [comment]
@LinusBorg In my case I talk about pages that have moved from my website to another one (not even a vuejs website). So I needed a way to keep them in the routes object because I use <router-link> in templates and redirect them to the proper external url.
That's why I was talking about "301 redirection" in issue (that will solve my problem too I think) https://github.com/vuejs/vue-router/issues/1280

**Comment by posva** [comment]
Closing as this is outdated and there's no actionable thing to do

for a redirection, adding a meta option to the record that needs to be redirected and then handling the logic in a beforeEach should work
