### ISSUE TITLE
IE 11 Promise Not Defined

### ISSUE THREAD

**Issue by AngelMunoz** [vuejs/vue-router#1333]
### Version
2.4.0

### Reproduction link
[https://buefy.github.io/#/](https://buefy.github.io/#/)

### Steps to reproduce
1. enter to https://buefy.github.io/#/ with Internet Explorer 11
2. open devtools
3. refresh (yet nothing will be loaded)

----
to reproduce a actual vue-router warning:
1. clone the buefy source
2. npm install
3. npm run dev
4. visit http://localhost:8080
5. open devtools
6. page won't load and vue-router warning will be logged

### What is expected?
load the website

### What is actually happening?
an error (production mode, warning in dev mode) *promise is not defined* is thrown

---
for additional context/info check https://github.com/rafaelpimpa/buefy/issues/6#issuecomment-294071776
I kind of worked around it adding bluebird locally in the cloned repo but i'm not sure I should be adding bluebird to prevent this issue

**Comment by lancelot-lewis** [comment]
@AngelMunoz Have the same quesion

**Comment by fnlctrl** [comment]
Promise is not available in IE11, please use a polyfill.
http://caniuse.com/#search=promise
