### ISSUE TITLE
transition.next() raising error.

### ISSUE THREAD

**Issue by crswll** [vuejs/vue-router#134]
I'm using `data` and I'm getting the error `Uncaught TypeError: Cannot convert undefined or null to object` when doing `transition.next()`. However, `transition.next({})` works.

```
route: {
  data: function (transition) {
    transition.next();
  }
}
```

vue 0.12.13
vue-router 0.6.0

**Comment by yyx990803** [comment]
Data expects you to... return some data?

**Comment by crswll** [comment]
You know what.

I did it for testing and I don't know what I was thinking. Maybe I thought it was activate or something. Plus it's late. Thanks.
