### ISSUE TITLE
I hope that you can dynamically addRoutes appendRoutes repacleRoutes deleteRoutes But Must be before the Wildcard

### ISSUE THREAD

**Issue by codedart2018** [vuejs/vue-router#1342]
### Version
2.4.0

### Reproduction link
[https://github.com/myxingke/vueManage.git](https://github.com/myxingke/vueManage.git)

### Steps to reproduce
addRoutes 
It is it          `[{xxxx}, {xxxx}, {xxxx},{new router},{new router},{'path': '*'}]`
Not it         ` [{xxxx}, {xxxx}, {xxxx},{'path': '*'},{new router},{new router}]`

### What is expected?
`
[{xxxx}, {xxxx}, {xxxx},{new router},{new router},{'path': '*'}]
`

### What is actually happening?
**But that's it**
`
[{xxxx}, {xxxx}, {xxxx},{'path': '*'},{new router},{new router}]
`

---
I hope that you can dynamically addRoutes appendRoutes repacleRoutes deleteRoutes But Must be before the Wildcard. Because it is necessary to do dynamic rights management routing。。。。

This problem is resolved after version 2.4?
link: https://github.com/vuejs/vue-router/issues/1176

**Comment by LinusBorg** [comment]
I just closed your previous issue, and told you there that this was fixed for the next release (**not** the current 2.4)

Please stop opening new issues for the same topic.
