### ISSUE TITLE
路由无法使用

### ISSUE THREAD

**Issue by iScript** [vuejs/vue-router#135]
![9a611df0-d24d-412c-b1b0-f3b979dae3aa](https://cloud.githubusercontent.com/assets/2595251/9807859/b8785a22-588b-11e5-81a3-53216718c6fb.png)
![0a46e6c6-f4ee-439b-b4ce-46acb69a515a](https://cloud.githubusercontent.com/assets/2595251/9807862/be619a16-588b-11e5-890e-ac5aa426669a.png)

按照文档上的内容写了段代码，无法运行， 然后直接下载官方example,运行basic.html还是报错。。

**Comment by byr-gdp** [comment]
我也遇到同样的问题，用webpack来构建的。

代码：https://github.com/byr-gdp/vue-router-example

**Comment by byr-gdp** [comment]
![image](https://ooo.0o0.ooo/2015/09/11/55f2bf571752a.png)

**Comment by yyx990803** [comment]
0.6.0 v-link API 有变化，中文文档还没更新，以英文版为准。

**Comment by iScript** [comment]
github上的demo ， example/basic.html也无法运行， 代码也没更新吗。

**Comment by yyx990803** [comment]
@iScript `example/basic.html` 更新过了
