### ISSUE TITLE
`route-link`能否生成无默认行为的空超链接a标签

### ISSUE THREAD

**Issue by xjchenhao** [vuejs/vue-router#1352]
### What problem does this feature solve?
类似`<a href="#"></a>`或者`<a href="javascript:;"></a>`，如果我配置了`<router-link :to="#">`,在`localhost:3000` 这样的url打开，它会生成`<a href="/#"></a>`这样的链接，在`localhost:3000/tables` 这样的url打开，它会生成`<a href="/tables#"></a>`这样的链接。

我的需求场景是根据join动态生成导航条，包含子菜单的父级菜单项需要用空超链接替代。现在每次点击都会触发路由的跳转。

### What does the proposed API look like?
`<router-link :to="#"></router-link>`判断`#`号表示这是空链接

**Comment by posva** [comment]
dup of #1280
