### ISSUE TITLE
Using `params` in programmatic Navigation requires named route

### ISSUE THREAD

**Issue by karlpokus** [vuejs/vue-router#1356]
### Version
2.4.0

### Reproduction link
[http://jsfiddle.net/2rm2e0z4/4/](http://jsfiddle.net/2rm2e0z4/4/)

### Steps to reproduce
```
const router = new VueRouter({
  routes: [
    { path: '/user/:id', name: 'user'}
  ]
})
```

`this.$router.push({ path:'user', params: { id: 'bar' } })` inside a method returns the value `user` for `param.id`

### What is expected?
Not sure. The docs does not state explicitly that using params requires a named route.

### What is actually happening?
The string `user` is returned when setting `param.id` to `bar`

---
https://forum.vuejs.org/t/using-params-in-vue-router-requires-named-routes/9883

**Comment by posva** [comment]
That is expected: once you provide the path, it's up to you to properly pass any param. You can actually just push params to update current route params with `this.$router.push({ params: { id: 'bar' } })` in the user route in your example. The name is required when navigating to another route and if you want to pass params with the object syntax, which is usually better than interpolating them yourself in the path

if you have some improvement proposals to the docs, we'll happily look at a PR 🙂

**Comment by karlpokus** [comment]
> The name is required when navigating to another route

But this is only when also setting `param` right? Not for `query`? That's where the docs had me confused.

**Comment by posva** [comment]
It's better to use query the same way but it's true that since the query is not part of the declaration of the path, you can don't need named routes with queries. But, you should name all routes you navigate to, it's an extra information and makes it easy to update the path if you ever need to

**Comment by karlpokus** [comment]
> you should name all routes you navigate to

Agreed.

> if you have some improvement proposals to the docs, we'll happily look at a PR

Cool. How do I do this? This issue tracker does not allow it it seems.

**Comment by posva** [comment]
You can create a pull request with a proposal to improve that parts of the docs 😄 
You can found more info about how to run the project locally on the readme or the contribution guidelines. Checking the package.json may even be enough 🙂

**Comment by karlpokus** [comment]
Great! I'll do a PR. I think I should add a link to this issue to provide some context.

**Comment by posva** [comment]
Yeah, you can add that in the description later 🙂
