### ISSUE TITLE
beforeRouteEnter does not set data on 2nd visit

### ISSUE THREAD

**Issue by xxRockOnxx** [vuejs/vue-router#1357]
### Version
2.4.0

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
A bit hassle to do in a Bin. Minimal reproduction I can give is only this code and steps below:

```
beforeRouteEnter(to, from, next) {
  next(vm => vm.someData = 'data')
}
```
- Have a component with that nav guard code
- Load the page. (Data is set)
- Press back button then press forward (Or visit other routes and visit the problem route again)
- Page loads, data is not set.

### What is expected?
`someData` is equal to `data`

### What is actually happening?
`someData` is empty

**Comment by posva** [comment]
you're probably looking for `beforeRouteUpdate`

**Comment by xxRockOnxx** [comment]
@posva if following the description of it from here

> For example, for a route with dynamic params /foo/:id, when we
> navigate between /foo/1 and /foo/2, the same Foo component instance
> will be reused

well then, no.

Any route I go to, when I get back to that one it doesn't update the data.

I tried to isolate everything already to the point only `router` and that component only remains.

Currently still talking about it on gitter somehow.

doing `console.log()` on `next(vm => console.log() .... code....)` and on `created`, and `mounted`

only mounted and created has the same output. they both have the same `_uid` and same everything. but the output from `next()`'s console.log is still the same.

**Comment by posva** [comment]
it may be #1322

**Comment by pulekies** [comment]
For anyone blocked by this issue, you may be able to get around it by observing $route and doing whatever updates you had planned in beforeRouteUpdate's next callback there.
