### ISSUE TITLE
throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);

### ISSUE THREAD

**Issue by zhuyuanwen** [vuejs/vue-router#1362]
### Version
2.4.0

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
npm run dev, the error happens

### What is expected?
npm run dev without error

### What is actually happening?
npm run dev, the error happens

---
The error in server.js at "app.use(webpackDevMiddleware(webpack(WebpackConfig), {". 
It seems the webpack can't do webpack() function. And if I use webpack@2.1.0-beta.21, it will not has this error. But it will have another error...it can't handle the .vue files

Details:

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be one of these:
   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function
   The entry point(s) of the compilation.
   Details:
    * configuration.entry should NOT have less than 1 properties ({
        "keyword": "minProperties",
        "dataPath": ".entry",
        "schemaPath": "#/oneOf/0/minProperties",
        "params": {
          "limit": 1
        },
        "message": "should NOT have less than 1 properties",
        "schema": 1,
        "parentSchema": {
          "minProperties": 1,
          "additionalProperties": {
            "oneOf": [
              {
                "description": "The string is resolved to a module which is loaded upon startup.",
                "minLength": 1,
                "type": "string"
              },
              {
                "description": "All modules are loaded upon startup. The last one is exported.",
                "$ref": "#/definitions/common.nonEmptyArrayOfUniqueStringValues"
              }
            ]
          },
          "description": "Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.",
          "type": "object"
        },
        "data": {}
      }).
      object { <key>: non-empty string | [non-empty string] }
      Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.
    * configuration.entry should be a string.
    * configuration.entry should be an array:
      [non-empty string]
    * configuration.entry should be an instance of function
      function returning an entry object or a promise..
    at webpack

**Comment by yyx990803** [comment]
This is completely unrelated to vue-router and your repro link is invalid.

**Comment by zhuyuanwen** [comment]
@yyx990803  yeah, it seems something wrong with webpack. I'm just curious that how could your vue-router don't get the error. I got this error when I used your package.json, server.js and webpack.config.js in an empty project. (same directory with you)

Sorry, I don't know how to show you in the repro link.

**Comment by posva** [comment]
@zhuyuanwen You should ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Github issues are for bug reports and feature requests only 🙂

**Comment by zhuyuanwen** [comment]
OK. Thanks.
