### ISSUE TITLE
query serialization & deserialization

### ISSUE THREAD

**Issue by cherry-geqi** [vuejs/vue-router#1375]
### What problem does this feature solve?
provide a consistent query object between programmatic navigation and navigation through url

### What does the proposed API look like?
When I navigate programmatically using:

```js
this.$router.push({ name: 'foo', query: { bar: { baz: 'blablabla' } } });
```

The url becomes `#/foo?bar=%5Bobject%20Object%5D`, and I get `{ bar: { baz: 'blablabla' } }` as query object on the next `foo` page.

If I reload this page, then I get `{ bar: "[object Object]"}`.

**Comment by posva** [comment]
Closing in favour of #1259
