### ISSUE TITLE
I can not get the meta param in VueRouter instance 

### ISSUE THREAD

**Issue by taoyingsong** [vuejs/vue-router#1378]
### Version
2.5.2

### Reproduction link
[http://jsfiddle.net/fanaticism1/wtpuevc6/72/](http://jsfiddle.net/fanaticism1/wtpuevc6/72/)

### Steps to reproduce
When the route is switched, the page judgment 【v-if="$route.meta.keepAlive"】 does not take effect

### What is expected?
switch correctly

### What is actually happening?
can not switch correctly

**Comment by posva** [comment]
I think you wanted to do this: http://jsfiddle.net/ygjg5znx/
(v-if then v-else)
