### ISSUE TITLE
When switching between child routes, beforeDestroy is called after beforeMount

### ISSUE THREAD

**Issue by nicolas-t** [vuejs/vue-router#1380]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/3xu0o52g/8/](https://jsfiddle.net/3xu0o52g/8/)

### Steps to reproduce
Go to the jsfiddle : https://jsfiddle.net/3xu0o52g/8/  
Open the console  
Click Foo then click Bar

console outpout is : 

```
beforeMount Foo  
beforeMount Bar  
beforeDestroy Foo  
```

### What is expected?
I expected `beforeDestroy` to be called before `beforeMount`

like this: 

```
beforeMount Foo  
beforeDestroy Foo  
beforeMount Bar  
```

### What is actually happening?
`beforeDestroy` is called after `beforeMount`  
```
beforeMount Foo  
beforeMount Bar  
beforeDestroy Foo  
```

**Comment by marioacc** [comment]
I will start working on it

**Comment by posva** [comment]
This is actually expected. If you really need the other way, you can use a transition with `mode="out-in"`: http://jsfiddle.net/01t7wdus/

**Comment by nicolas-t** [comment]
Oh thanks !

For those interested, relevant doc is here (pretty detailed and interesting) : 
https://vuejs.org/v2/guide/transitions.html#Transition-Modes
