### ISSUE TITLE
append prop should append to route, where it his parent component was matched

### ISSUE THREAD

**Issue by trailskr** [vuejs/vue-router#1385]
### Version
2.5.2

### Reproduction link
[http://jsfiddle.net/L7hscd8h/1211/](http://jsfiddle.net/L7hscd8h/1211/)

### Steps to reproduce
click one of base links.
then one of child links

### What is expected?
expected child links will be appended to the base route, as before child route transition.
subchild will be as in example

### What is actually happening?
childs links in base component transforms to more nested routes: base1/child1/child1.
subchild link appends properly: base1/child1/subchild

---
replacing child routes with absolute routes solves problem, but it is now absolute =(
http://jsfiddle.net/L7hscd8h/1212/

**Comment by posva** [comment]
That is intended, `child1` could have child with a `child1` path 😛 
It's better to use named routes

**Comment by trailskr** [comment]
WAT!? could, but should not! It is anyway illogical behavior. No real use cases.

**Comment by trailskr** [comment]
@posva I don't understand how named routes can save situation.
All base routes have same children routes, if give them a name, routes will match only as base1 child routes, not from base2 (http://jsfiddle.net/L7hscd8h/1233/)
It is easier to reduplicate every child route to every of it's base routes.
But then why do we need "append" If it doesn't fit its purpose?

**Comment by posva** [comment]
It's actually logical:
An appended route path depends on where you currently are. The same thing happens with an `a`. The current behaviour is made to be consistent with `a` behaviour.

About how to do it with named routes: create a function to generate the array of children and prepend a string to the name. This way, you use the same component in different children:

```js
function generateChildren (name) {
  return [
    { name: `${name}-child1`, component: child1, path: 'child1' }
  ]
}

// a route
{ path: '/base1', component: 'base1', children: generateChildren('base1') }
``` 
Hope it helps 🙂

**Comment by trailskr** [comment]
@posva this is the case. An appended route path depends on where you currently are - it is wrong and mainly not suitable behavior. It should depends on where component currently matched, not application at all. That logic not breaks previous "append to current" logic in which it works.
Your solution will not work, because children also links to each other, and links should have one name, regardless of it's parent. That's why it only possible with sibling path routing like in working example http://jsfiddle.net/L7hscd8h/1212/
In my opinion, it would be best having mechanisms for moving through the chain like in file system: './sibling', '../onother-parent', '..' - back to parent and so on

**Comment by posva** [comment]
My solution may not work in your case because I haven't adapted it to it.
If you really need or want to generalise the component, you can pass down a prop as well (https://router.vuejs.org/en/essentials/passing-props.html).

It's how `a` behaves...

I like the idea of relative paths like in a system folder, you can open a new issue for that and reference this from that one. But make sure to give a real world use case about when these complex nesting with relative paths can not be solved already with the method above
