### ISSUE TITLE
Missing named routes throw TypeErrors

### ISSUE THREAD

**Issue by Xcelled** [vuejs/vue-router#1386]
### Version
2.5.2

### Reproduction link
[http://jsfiddle.net/qkco53b9/1/](http://jsfiddle.net/qkco53b9/1/)

### Steps to reproduce
Run the example. Look at the console.

### What is expected?
Inserting a router link to a named route that doesn't exist should warn.

### What is actually happening?
The console spews both warnings about the missing named routes and errors about not being able to access the `regex` property of a route.

---
I'm building an SPA and inserting placeholder links to pages I haven't built yet.

It looks like the problem might be here: https://github.com/vuejs/vue-router/blob/4de549a45cc38975d6ce343ecdea007972891b4f/src/create-matcher.js#L39. Seems the matcher still tries to proceed even if there's no record.

**Comment by posva** [comment]
I added that label too fast, I was sure there was already a warning 😛 

```
vue-router.js:22 [vue-router] Route with name 'foo' does not exist
```

**Comment by Xcelled** [comment]
No, you misunderstand @posva. This is a bug, not an improvement. The warning *is* printed, this is fine. But there is **also** an error thrown:

![image](https://cloud.githubusercontent.com/assets/5599341/25566583/a9009f1a-2da9-11e7-8114-811bc67815d6.png)

This issue is about that error, not the warning.

**Comment by posva** [comment]
The error happens because the link is pointing to a non-existent route, that's expected. The warning is there to help you out find the real problem

**Comment by Xcelled** [comment]
That seems unintuitive. I would expect it to warn only (then abort), or at the very least fail gracefully with a specific error message. Instead the error message makes me think there's, well, a bug in the router.

**Comment by posva** [comment]
That's right, I'll create a pr for that. Thanks!

**Comment by akoidan** [comment]
Maybe we should consider altering behavior a bit? 
For example, when using vue-loader, it could throw compile time error, or at least compile-time warning. 

IMHO using named routes should prevent regression in big projects. Atm warnings only pop up if user visits a page with invalid route link. I'm not sure if `vue-router` has information when it receives RouterConfiguration about all vue components, so maybe it's impossible implement this w/o bundles as webpack.

**Comment by posva** [comment]
You could implement a webpack plugin for it but I think the current behaviour is already easy to detect because of the warnings/errors
