### ISSUE TITLE
How to set Component as String

### ISSUE THREAD

**Issue by kvdmolen** [vuejs/vue-router#139]
When using vueify, my components are defined in `app.vue`.

I would like to set the `component` in a route to the name (string) of the component.

in app.vue:
```js
module.exports = {
    components: {
        "foo": require("./pages/foo.vue"),
        "bar": require("./pages/bar.vue")
    }
}
```

Initialising the router: 

```js
router.map({
    '/foo': {
        component: "foo"
    },
    '/bar': {
        component: "bar"
    }
})

router.start(require("./app.vue"), "#app")
```
But I get the error: 
```
[vue-router] invalid component for route "undefined"
```

Alternatively, you could also NOT give the `component` parameter, then you can handle the component yourself:

```html
<component is="{{$route.mycomponent}}"></component>
```

**Comment by yyx990803** [comment]
This is no longer supported. Just require the components directly in the router config - it's actually more straightforward.

**Comment by kvdmolen** [comment]
This is true, thanks.

Though, it assumes one component for one route. In my application I use two components per route, a `template.vue` and **within** this component another component e.g. `content.vue`

This means a combination of the use of:
```html
<component is="{{$route.template}}"></component>
```
in the main `app.vue` and
```html
<router-view></router-view>
```
in the `template.vue`.

Works fine, but for flexibility perhaps it would be good to allow `component` to be not defined in the route. Just an idea.

Thanks!

**Comment by yyx990803** [comment]
Allowing multiple components at the same route actually would complicate the problem when you are dealing with hooks like `canActivate`, `canDeactivate` - what can be handled in one place now needs to be split in two! In comparison, handling your own sub-views eliminates this problem altogether.
