### ISSUE TITLE
IE9-IE11 how to support

### ISSUE THREAD

**Issue by linxq** [vuejs/vue-router#1391]
### Version
2.5.3

### Reproduction link
[https://github.com](https://github.com)

### Steps to reproduce
what I need to add for ie9  can make my project run with vue-router2.0

### What is expected?
what I need to add for ie9  can make my project run with vue-router2.0

### What is actually happening?
what I need to add for ie9  can make my project run with vue-router2.0

---
what I need to add for ie9  can make my project run with vue-router2.0

**Comment by nickmessing** [comment]
@linxq, this is not a place to ask, please use [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue) for that

**Comment by fnlctrl** [comment]
Please don't abuse the issue helper to ask questions.
