### ISSUE TITLE
How to replace history when I use router.back()

### ISSUE THREAD

**Issue by lainlee** [vuejs/vue-router#1394]
### What problem does this feature solve?
Hello everyone

I am a Chinese developer and developing a product using Vue and Vue-router

And ... something in trouble in the scence as follows

when someone want to order some goods, he needs to jump into 'signIn' page at first, and after sign in successfully, he will back to the previous page, here I use router.back() to make it, but the problem is when he uses forward button in chrome or other browser, he can jump to the 'signIn' page again which I don't want him to

So is there any way or method can replace the 'signIn' page when I want to back, I find whole doc and don't find method suitablely

My English is weak, so if I explain not clearly, point to me and I will correct it, thank you

### What does the proposed API look like?
Maybe we can add an object that we can get 'from-route' or a hook 'afterRouteEnter' in component

**Comment by posva** [comment]
Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
