### ISSUE TITLE
beforeRouteEnter not called on first load when defined in global mixin for single file component 

### ISSUE THREAD

**Issue by zsalzbank** [vuejs/vue-router#1395]
### Version
2.5.3

### Reproduction link
[https://github.com/zsalzbank/vue-router-before-route-enter-mixin-single-file-component](https://github.com/zsalzbank/vue-router-before-route-enter-mixin-single-file-component)

### Steps to reproduce
1. Load the minimal reproduction in the browser and open the developer console.
2. Notice that there is no message with `bre` or `bre next`. (There will be one with `be`.)
3. Click the `World` link.
4. Notice that there is no message with `bre` or `bre next`. (There will be one with `be`.)
5. Click the `Hello` link.
6. Notice that the console logged `bre` and `bre next`. (There will be one with `be` too.)
7. Click the `World` link.
8. Notice that the console logged `bre` and `bre next`. (There will be one with `be` too.)

### What is expected?
The `bre` and `bre next` messages are shown when the page loads initially. They should also be shown when navigating to the `World` link for the first time.

### What is actually happening?
The messages are not shown.

---
This does work when the component is not a single file component. An example of this can be found here: http://jsfiddle.net/wq4kftpa/5/

**Comment by defcc** [comment]
Thanks @zsalzbank ,  this seems not to be a bug. 

The mixin should be loaded earlier, so that each Vue instance could be applied.

I'll update the demo.

**Comment by defcc** [comment]
@zsalzbank  I opened a PR to your repository, you could take a look the change. https://github.com/zsalzbank/vue-router-before-route-enter-mixin-single-file-component/pull/1/files

**Comment by zsalzbank** [comment]
Thanks!

Can't believe I made the same mistake in my reproduction too. I feel silly.

Thanks again!

**Comment by zsalzbank** [comment]
Finally got around to testing this out. For some reason, it makes a difference whether or not the mixin is in a separate file or not. I've updated my repo with the two possibilities. Any idea why one would work and the other wouldn't? I would expect them to be functionally equivalent.

**Comment by zsalzbank** [comment]
https://github.com/zsalzbank/vue-router-before-route-enter-mixin-single-file-component/commit/11707059f90a4ed0ea1aa895729702efacb2e340
