### ISSUE TITLE
[FEATURE] PushState with url changing BUT without rendering the associated component

### ISSUE THREAD

**Issue by darkylmnx** [vuejs/vue-router#1397]
### What problem does this feature solve?
The use-case is pretty simple : 
- i am on a home page with a feed of posts
- i click on a post to see it's details
- because i'm on the feed, the post shows within a modal but the url changed with a state pushed to history
- i reload the page with this same url, i'm on the page of the post, not a modal because my previous state does not exist so a modal over nothing woun't be accurate.

the url changes and a state is pushed to history without removing the current component

Why ? Because the user can perfom actions without leaving the main page he browses (it's an UX use case) but i guess there are many cases where you want an url change without the current component changing (modals mainly)

and of course you want a history so when back button is pressed you can lose the modal while having the good url for the route you are in

- facebook does this for video posts
- instagram does this on their web app on the explore page
- smaller website : dribbble.com does this on all their feeds

same url, two different behaviours.

### What does the proposed API look like?
i would suggest a simple api for the next func, something like :

```
// in the next func
function next(to, rollback_url) {
  if (to === false) {
    if (rollback_url) return

    // here do anything to rollback url
  }
}
```

so i could do something like

```
beforeRouteEnter(to, from, next) {
    if (something) {
      next(false, false) // browser URL was changed, nothing else happens
      // next(false) : browser URL was changed and will be reset to that of the from route.
    } else {
      next() // browser url was changed, component is rendered
    }
  }
```

**Comment by posva** [comment]
dup of #703
