### ISSUE TITLE
Allow specifying different transitions for navigation and popstate

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vue-router#14]
Sometimes different page transitions are needed when clicking a link vs. clicking the back button.

**Comment by altitudems** [comment]
Does this mean we can have transitions that go back and forth between pages in a single page app?

I would be happy to see that. Maybe we could eventually get to do something like this?
http://www.appcoda.com/wp-content/uploads/2015/03/vid08.gif

**Comment by limichange** [comment]
+1

**Comment by amirrustam** [comment]
+1

**Comment by whtsky** [comment]
+1

**Comment by lesion** [comment]
+1
I would love a way to specify to vue-router that transitions has to be done in reverse order

**Comment by shenlq** [comment]
+1

**Comment by wjy4124** [comment]
+1

**Comment by nbagonet** [comment]
+1

**Comment by vwxyutarooo** [comment]
Is there any updated?

**Comment by james-brndwgn** [comment]
+1 - Looking for a way to control the "direction" of a transition depending on if the browser back button is clicked. Eg. If back is clicked the transition would play in reverse.

**Comment by chasebank** [comment]
+1

**Comment by ccqgithub** [comment]
How about this feature now ?

**Comment by james-brndwgn** [comment]
+1

**Comment by chasebank** [comment]
Until this get's an official solution, the method I've settled for is setting a "depth" meta property for each route. Then when the route changes, check whether the new route depth is higher or lower than the previous. If it's higher, transition from right, if it's lower (going back) transition from left.

Not ideal and could be a nightmare to maintain, but get's the job done for simple implementations.

```
  { 
    name: 'categories',
    path: '/categories',
    component: categories,
    meta: { depth: 1 },
  },
  { 
    name: 'category',
    path: '/categories/:category/',
    component: category,
    meta: { depth: 2 },
  }
```
```
<transition :name="transitionDirection">
  <router-view></router-view>
</transition>
```
```
data() {
  return {
    transitionDirection: 'slide-left',
  }
},
watch: {
  '$route' (to, from) {
    const toDepth = to.meta.depth
    const fromDepth = from.meta.depth
    this.transitionDirection = toDepth < fromDepth ? 'slide-right' : 'slide-left';
  }
}
```
```
.slide-left-enter,
.slide-right-leave-active {
  transform: translate3d(100%, 0, 0);
  opacity: 0;
}

.slide-right-enter,
.slide-left-leave-active {
  transform: translate3d(-100%, 0, 0);
  opacity: 0;
}
```

Or, if it's a super simple application, rather than set the depth manually, you can rely on the "depth" of the route path. `app/categories` < `app/categories/:category` < `app/categories/:category/:post`
```
watch: {
  '$route' (to, from) {
    const toDepth = to.path.split('/').length
    const fromDepth = from.path.split('/').length
    this.transitionDirection = toDepth < fromDepth ? 'slide-right' : 'slide-left'
  }
}
```

**Comment by jasonhibbs** [comment]
Transitions are extremely clumsy when using the swipe back gesture on iOS because they fire after the user has already reached the destination. 

Being able to disable transitions when a forward/back button or browser gesture is used would be _very_ helpful.

**Comment by valgeirb** [comment]
> Transitions are extremely clumsy when using the swipe back gesture on iOS because they fire after the user has already reached the destination.
> 
> Being able to disable transitions when a forward/back button or browser gesture is used would be _very_ helpful.

Have you found a work-around? I'm really struggling with transitions and swipe back gestures on iOS.

**Comment by jasonhibbs** [comment]
> Have you found a work-around? I'm really struggling with transitions and swipe back gestures on iOS.

I never found a workaround, just this issue

**Comment by posva** [comment]
Closing in favor of https://github.com/vuejs/vue-router/issues/3453 which would effectively allow this by using `$route.navigation.type` or similar
