### ISSUE TITLE
Add delegate functionality to v-link

### ISSUE THREAD

**Issue by lepture** [vuejs/vue-router#140]
An example for delegating `v-link-delegate`:

```html
<div v-html="aVar" v-link-delegate></div>
```

`aVar` is a HTML variable that contains inner links, e.g.

```html
<!-- aVar -->
<a href="/foo">go to foo</a>
```

We can't add `v-link` directive to this link since it is in a variable. My solution is adding a `v-link-delegate` directive to listen for link redirection.

page.js can handle the links very well since it captures every link redirection.

I am not sure whether it should be added to vue-router.

**Comment by yyx990803** [comment]
Sounds like a decent solution. I'd take a pull request.

**Comment by lepture** [comment]
@yyx990803 It seems we can merge `v-link` and `v-link-delegate` together.

```html
<div v-link></div>
```

`v-link` on `div` is a delegate obviously.

**Comment by yyx990803** [comment]
@lepture hmm, good idea!

**Comment by lepture** [comment]
I'm going to implement it.

**Comment by yyx990803** [comment]
:+1:

**Comment by lepture** [comment]
@yyx990803 Not sure how to implement the test case. The `click` function seems not working properly.

**Comment by yyx990803** [comment]
You can manually dispatch a fake `click` event:

``` js
function trigger (el, event) {
  var e = document.createEvent('HTMLEvents')
  e.initEvent(event, true, true)
  el.dispatchEvent(e)
}
```
