### ISSUE TITLE
in hash mode , manual modify #hash and in the router.beforeEach ,  redirect to a different location , the different location will not  trigger afterEach

### ISSUE THREAD

**Issue by PanJiaChen** [vuejs/vue-router#1406]
### Version
2.5.3

### Reproduction link
[http://panjiachen.github.io/vue-router-demo/#/bar](http://panjiachen.github.io/vue-router-demo/#/bar)

### Steps to reproduce
detail code  https://github.com/PanJiaChen/PanJiaChen.github.io/blob/master/vue-router-demo/index.html#L32

1.open the page
2.change the hash (just remove bar)

### What is expected?
manual change the hash (just remove /bar) will trigger router.afterEach

### What is actually happening?
manual change the hash (just remove /bar) not trigger router.afterEach

---
when in the hash mode, manual modify #hash and in the router.beforeEach , l  redirect to a different location,the different location will not  trigger afterEach.

but in the history mode is ok.

**Comment by posva** [comment]
It's the same behaviour in history mode: http://jsfiddle.net/4jx38y09/
If you prevent the navigation by staying on the same route, there will be no `after*` hook called
