### ISSUE TITLE
Disclosure JSON result after reload page

### ISSUE THREAD

**Issue by weehong-1** [vuejs/vue-router#1409]
### Version
2.5.3

### Steps to reproduce
Reload the page once with www.example.com/catalog

### What is expected?
Reload the entire page

### What is actually happening?
Disclosure JSON result

---
Using Laravel 5.4 and AXIOS

**Comment by simplesmiler** [comment]
This is not enough information to triage your issue.

If you are having problems making HTML5 History Mode work, please make sure your server is configured properly: http://router.vuejs.org/en/essentials/history-mode.html#example-server-configurations

**Comment by weehong-1** [comment]
Hi @simplesmiler 

I uploaded a GIF to Imgur for your better understanding.

![vue router](https://cloud.githubusercontent.com/assets/6753022/26024816/7cdee032-380c-11e7-82ce-85300f9993b6.gif)

**Comment by posva** [comment]
Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
