### ISSUE TITLE
Warn if no routes are provided in the Router constructor options

### ISSUE THREAD

**Issue by iDhruv22** [vuejs/vue-router#1411]
### Version
2.5.3

### Reproduction link
[https://codepen.io/iDhruv22/pen/MmGXee?editors=1010](https://codepen.io/iDhruv22/pen/MmGXee?editors=1010)

### Steps to reproduce
```js
const Routes = [{
  path: '',
  component: Home
}, {
  path: 'users',
  component: User
}];

const router = new VueRouter({
  routes: Routes
});
```

This is current, but now if I mistakenly write below code

```js
const router = new VueRouter({
  Routes // Means Routes: Routes
});
```

So I don't get anything in browser, importantly not even a warning message(something like, routes key is required)

### What is expected?
There should be a warning message if one does not pass routes key.

### What is actually happening?
Currently, there is no warning message.

**Comment by LinusBorg** [comment]
Seems like a good idea to me.

**Comment by posva** [comment]
Can be useful, we can take a pr for that 🙂 
BTW, it's better to use Uppercase variables for Classes (or libs), it's a convention. When you see a variable name like `Routes`, you want to do `new Routes()`

**Comment by posva** [comment]
See https://github.com/vuejs/vue-router/pull/1526#issuecomment-312094775
