### ISSUE TITLE
export {supportsPushState} from vue-router

### ISSUE THREAD

**Issue by daggerjames** [vuejs/vue-router#1417]
### What problem does this feature solve?
I need set 'base' due to whether the mode has been fallback to 'hash', for example, in IE 9. however, router.fallback could only be accessed after I init it.

### What does the proposed API look like?
in es6, I could use 

`import { supportsPushState } from 'vue-router'`

and use it as a consistent way to check whether we were in fallback mode

**Comment by posva** [comment]
just do

```js
if (history.pushState) {
  // supported.
}
```
http://stackoverflow.com/questions/6824991/how-to-find-if-a-browser-supports-history-pushstate-or-not

**Comment by daggerjames** [comment]
but I look deeply into vue-router code, and find that some ua were filtered specifically.

see [here](https://github.com/vuejs/vue-router/blob/dev/src/util/push-state.js#L10)

**Comment by posva** [comment]
Oh, right. Well you can already import it then 😄

**Comment by daggerjames** [comment]
It was my first attempt, until I found that simply `import {supportsPushState} from 'vue-router/src/util/push-state'` have issues related to dependencies, such as `Date` is unknown type. Thus, I formally handle this request to see if it could be officially supported. ☺️

**Comment by posva** [comment]
Given this is a very specific use case and that this feature has shown no demand, we are closing it
