### ISSUE TITLE
The route object is too simple！

### ISSUE THREAD

**Issue by baijunjie** [vuejs/vue-router#1418]
### What problem does this feature solve?
希望当前路由对象（this.$route）能携带一些自定义数据。
Hope that the current route objects (this.$route) can carry some custom data.

在嵌套路由中，目前的路由对象无法追踪到它的父级路由。
At present, the embedded in routines by route objects cannot be traced to its parent routing.

这对于开发面包屑导航功能尤为重要。
This is especially important for development of bread crumbs navigation function.

在中文开发中，我无法知道当前路由的中文名称。
In the Chinese development, I can't know the Chinese name of the current routing.

### What does the proposed API look like?
**Example**

current path: `Home/Foo/Bar`

Tracking the parent:
```js
this.$route.self    //=> this.$router.options.routes[{Home route}].children[{Foo route}].children[{Bar route}]
this.$route.parent    //=> this.$router.options.routes[{Home route}].children[{Foo route}]
this.$route.parent.parent //=> this.$router.options.routes[{Home route}]
```

**Comment by posva** [comment]
You can already carry custom data with `meta`
You should be able to build the full path for a breadcrumb using the `matched` object of the `$route`. Have you given that a try?

**Comment by baijunjie** [comment]
Yes, ` meta ` are useful.
But, The contents of the `$route.matched` very confusion, Can't reflect the real father-son relationship.
[demo](http://jsfiddle.net/L7hscd8h/1383/)
![0b8f2150-a469-4894-90e1-1c83573bab08](https://cloud.githubusercontent.com/assets/7956480/26110471/097f617c-3a85-11e7-807a-7b4c11a89b83.png)


`vue-router` whether can provide a routing tree, help us more convenient to get its parent?

**Comment by posva** [comment]
the array shows it. if it's not clear maybe we can improve the documentation
But as you can see, you have, in order `/`, then `/foo` and then `/foo/` (default child), and you have access to the name, so building a breadcrumb should be a matter of `map` on the matched object

**Comment by baijunjie** [comment]
Thank you for your answer, I do some packing again on this foundation, can satisfy my needs.

**Comment by posva** [comment]
The redirect work the other way around ☺️
Switch the values for path and redirect
