### ISSUE TITLE
support component name in routes

### ISSUE THREAD

**Issue by BigSully** [vuejs/vue-router#1419]
### What problem does this feature solve?
I wonder why the value of routes[i].component can not accept a component name string instead of the component object itself? If so, I can register router with pure string, like:
```
const router = new VueRouter({
  routes: [
    //{ path: '/user/:id', component: User }  // original syntax
    { path: '/user/:id', component: name }  // expected syntax,  the name was decided at run time
  ]
})
```

### What does the proposed API look like?
```
const routes = [];

_.each(arr, , function(obj, i){
    var node = {  //造结点
        path: obj.pathString,
        component: obj.componentString  // 1st syntax
        //component: someFunction(obj.componentString)  // or 2nd syntax
    };
	routes.push(node);
});
const router = new VueRouter({
    routes
})
```

**Comment by posva** [comment]
What prevent you from importing the components? That way it's explicit and the router instance can be read.
If you want to refer global components, you can already do it by passing `Vue.component(name)` to the component option 🙂
