### ISSUE TITLE
 this.$router.addRoutes(routes)

### ISSUE THREAD

**Issue by jason65** [vuejs/vue-router#1423]
routes是要添加的对象 
console.log(this.$router)
this.$router.addRoutes(routes)
console.log(this.$router)
为什么两次log的结果是一样的

**Comment by dagedan** [comment]
我也遇到了，可以正常跳转，但是this.$router 内容并没有增加，请问您是怎么解决的@jason65

**Comment by pi-ka-qiu** [comment]
@dagedan  手动改$router.options.routes
