### ISSUE TITLE
Cannot use alias on / route

### ISSUE THREAD

**Issue by TynesideGroup** [vuejs/vue-router#1427]
### Version
2.5.3

### Reproduction link
[http://jsfiddle.net/9r6xhqbp/31/](http://jsfiddle.net/9r6xhqbp/31/)

### Steps to reproduce
* Use an alias on base `/` route (alias does not work)
* Add a child to the aliased `/` route (alias child does not work)
* Give the aliased child route a `name` (throws "Duplicate named routes definition" warnings)

### What is expected?
* Alias on base `/` route should work as expected
* Child routes on aliased `/` route should work as expected
* No "Duplicate named routes definition" warnings should be thrown on aliased base `/` child routes that have a `name`

### What is actually happening?
* Alias on base `/` route does not work
* Children on aliased base `/` route do not work
* "Duplicate named route definition" warning is thrown for aliased base `/` child routes that have a `name`

**Comment by posva** [comment]
As a workaround, you can set the path as `/home` and use `/` as the alias instead
But this looks like a bug, thanks!

**Comment by TynesideGroup** [comment]
Thanks @posva. ~~Unfortunately the workaround doesn't solve the issue of the "Duplicate named routes definition" warning in the console when using named child routes, but I can live with that for now!~~

Thanks for confirming it is indeed a bug - look forward to seeing a solution soon 👍

**Comment by posva** [comment]
The warning does gets suppressed on the fiddle

**Comment by TynesideGroup** [comment]
Yep, my bad - my Console was retaining history.

Would be nice to be able to declare `/` as the root path and alias it to something else rather than vice-versa though - at first glance to another developer it could appear my codebase doesn't have a base `/` route.
