### ISSUE TITLE
Router push programmatically with default params as null

### ISSUE THREAD

**Issue by ruchernchong** [vuejs/vue-router#1429]
### Version
2.5.3

https://codepen.io/ruchern/pen/jmvWra

### Steps to reproduce
Using the following code and assigning params to null does not route correctly.

```javascript
methods: {
    navigate(route, params = null) {
        this.$router.push(route, {
            params: params
        }
    }
}
```

### What is expected?
Expects the route to navigate properly even when the param is null.

### What is actually happening?
Router is throwing the errror message:
`Uncaught TypeError: Cannot use 'in' operator to search for 'id' in null`

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue next time. The reproduction is mandatory...

---

Params must be an object, it can be empty though 🙂

**Comment by ruchernchong** [comment]
@posva I was editing my codepen, so temporarily removed the link. However, I guess your reply might have solved my problem. Thank you.
