### ISSUE TITLE
[FEATURE] A url generation method that returns the compiled url for the given named route populated with the given params.

### ISSUE THREAD

**Issue by mutumarieru** [vuejs/vue-router#1430]
### What problem does this feature solve?
This feature will solve a simple problem, having urls in translations. 
Today if i have a translation text that has anchors linking to some part of the website, i can't generate a url based on a named route.

"But you can just inject the url hardcoded" - well yes, but where's the point of having named routes if i can't generate my own url at some point to just have the "text value" of my url ?

Other use-case : a user has referral url he wants to share ton somebody, well i can't output the url to the user to copy / paste.

### What does the proposed API look like?
```
@param Object options (the route options as for $router.push())
@param Boolean prependHostName (wether to prepend or not hostname)
@return String the url of the named route

this.$router.href([options], prependHostName)
```

e.g :
```
 this.$router.href({name: 'pages.policies'}) => /policies
 this.$router.href({name: 'pages.policies'}, true) => www.yourhostname.com/policies
```

**Comment by posva** [comment]
You already have router.resolve: https://router.vuejs.org/en/api/router-instance.html
Isn't that what you're looking for?

**Comment by mutumarieru** [comment]
@posva seems to be it 

(the name wasn't so clear IMHO resolve looks more like word used to resolve data in this lib, maybe rename to resolveUrl ?)

could you tell what current?, append? params are for since it's not said on the docs

**Comment by mutumarieru** [comment]
**beforeResolve** this method for example entertains the confusion on the **router.resolve** method lol

**Comment by posva** [comment]
I agree that it's quite confusing, the resolve word is used a bit too much
I added a PR with the detail of those arguments, in short, you probably don't need them 😄

**Comment by mutumarieru** [comment]
thanks !
