### ISSUE TITLE
Forward to wrong url when using google cache

### ISSUE THREAD

**Issue by yuyi** [vuejs/vue-router#1437]
### Version
2.5.3

### Reproduction link
[http://webcache.googleusercontent.com/search?q=cache%3Ahttps%3A%2F%2Fvue-hn.now.sh%2Ftop&oq=cache%3Ahttps%3A%2F%2Fvue-hn.now.sh%2Ftop&aqs=chrome..69i57j69i58.3167j0j4&sourceid=chrome&ie=UTF-8](http://webcache.googleusercontent.com/search?q=cache%3Ahttps%3A%2F%2Fvue-hn.now.sh%2Ftop&oq=cache%3Ahttps%3A%2F%2Fvue-hn.now.sh%2Ftop&aqs=chrome..69i57j69i58.3167j0j4&sourceid=chrome&ie=UTF-8)

### Steps to reproduce
1. Google "vue-hn.now.sh"
2. Click "Cached" at the first result
3. Will be forwarded to "https://vue-hn.now.sh/https:/vue-hn.now.sh/"

### What is expected?
A Cached Page

### What is actually happening?
Forwarding to "https://vue-hn.now.sh/https:/vue-hn.now.sh/"

**Comment by posva** [comment]
Dup of #1426
