### ISSUE TITLE
Add a note about $route being read only in programmatic navigation

### ISSUE THREAD

**Issue by awei01** [vuejs/vue-router#1439]
### Version
2.5.3

### Reproduction link
[https://jsfiddle.net/awei01/aftmo7kt/](https://jsfiddle.net/awei01/aftmo7kt/)

### Steps to reproduce
* Open up fiddle
* Click the two different buttons. Notice how the `$route.push()` works with one implementation and not with the other implementation.
* Scratch your head

### What is expected?
Manipulating the `$route.query` object should probably not alter the actual `query` object attached to `router.currentRoute`

### What is actually happening?
the `$route.query` object should be cloned so that any manipulation on it doesn't affect the current route query. It's currently a referenced object that is likely stored somewhere on the `router` instance. So, when you manipulate it, the `currentRoute.query` is also being manipulated. The new query route will never be detected. 

---
I'm thinking that this is probably a bug. But, if it's not a bug and the intended behavior, then it should be clearly documented that the `query` object should be cloned before altered. I'm also suspecting that the same would be true for `params`, but I haven't tested that out.

**Comment by posva** [comment]
It's actually documented: http://router.vuejs.org/en/api/component-injections.html
the `$route` object is is read only

But I agree another note could be added at http://router.vuejs.org/en/essentials/navigation.html
We could take a PR for this 🙂

**Comment by awei01** [comment]
Ah, ok. You're right. Sorry, I missed that. 

Maybe do an `Object.freeze` on `query`?

**Comment by posva** [comment]
Yeah, that will throw an error when attempting to modify it

**Comment by posva** [comment]
After further investigation, applying Object.freeze to nested properties could conflict with custom query parsing/stringifying functions. Ultimately, the fact that `$route` is readonly should be said as soon as it is introduced
