### ISSUE TITLE
Has any way to match path to *.vue filename automaticly?

### ISSUE THREAD

**Issue by luozhihua** [vuejs/vue-router#1444]
### What problem does this feature solve?
Usually，we write rorters like this:

```javascript
const routers = [{
    path: '/settings',
    component: resolve => { resolve(await import(`./views/settings/index.vue`)) }
}, {
    path:'/settings/profile',
    component: resolve => { resolve(await import(`./views/settings/profile.vue`)) }
}
// more path...
]
```

It's posibled to support like this:

```javascript
const routers = [{
    path: '*',
    component: function (resolve) {
        const PATH = "How to get the path of current router?" // At this point, `new VueRouter().router.currentRoute` is always be `/`

        resolve(await import(`./views/${PATH}.vue`))
    }
}];
```

### What does the proposed API look like?
```javascript
const routers = [{
    path: '*',
    component: function (resolve) {
        const PATH = "How to get the really path of current route?"  

        resolve(await import(`./views/${PATH}.vue`))
    }
}];
```

**Comment by posva** [comment]
You can use `addRoutes` to add routes dynamically.
BTW, you should write the resolve as follows:

```js
component: resolve => import('...').then(resolve)
```

You can have a look at the different results if you use babel: http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&debug=false&code=const%20Foo%20%3D%20resolve%20%3D%3E%20import('Foo').then(resolve)%0A%0A%2F%2F%20bad%20version%0Aconst%20Bar%20%3D%20async%20resolve%20%3D%3E%20resolve(await%20import('Bar'))
