### ISSUE TITLE
vue-router addRoutes() refresh after not work

### ISSUE THREAD

**Issue by 953133667** [vuejs/vue-router#1450]
### Version
2.5.3

### Reproduction link
[https://jsfiddle.net/a953133667/1dnhk7op/1/](https://jsfiddle.net/a953133667/1dnhk7op/1/)

### Steps to reproduce
- step1: addRoutes()
- step2: refresh page (press the 'F5' key).
- step3: dynamically add routes not work.

### What is expected?
Routes normal work

### What is actually happening?
Routes not work

---
### My project need use "Access control":

For example:

- User '1' can access to the page a and page b, can't access the page c and page d.

- User '2' can access to the page c and page d, can't access the page a and page b.

I can use the vue-router `addRoutes` method ,I think.

In the file "login.vue", show me the code:

    // more code

    // User login success
    sessionStorage.setItem('user', JSON.stringify(user));

    // From server get the routes data
    getRoutes().then(data => {

      // Routes data save in to sessionStorage
      sessionStorage.setItem('routes', JSON.stringify(data.routes));

      // Format data && created vue Router object
      let routes = this.routeCreater(data.routes);

      // addRoutes
      this.$router.addRoutes(routes);

      this.$router.push({ path: '/Index' });
    })

    // more code

Routes normal work.But  if i refresh this page(press the 'F5' key). use `addRoutes()` dynamic add routes not work. 

Please help me  Thx!

**Comment by posva** [comment]
That's normal, all the local data is lost upon reload. You'll need to save them using localstorage or a similar solution and load them up again at startup (router.onReady)

**Comment by SWTHongbin** [comment]
solve? @953133667

**Comment by printjs** [comment]
@posva localstorage is wrong . component function lost when `localstorage.setItem` call it.

**Comment by EvanBurbidge** [comment]
@posva when trying to store vue router in localStorage there are errors when trying to set it to a JSON string as it is a "circular structure". Has there been any progress in a method which could sync this to session/localStorage? 
```
vue.common.js?49d2:593 [Vue warn]: Error in created hook: "SyntaxError: Unexpected token o in JSON at position 1"

vue.common.js?49d2:1743 SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at VueComponent.created (index.vue?6ced:15)
    at callHook (vue.common.js?49d2:2923)
    at VueComponent.Vue._init (vue.common.js?49d2:4632)
    at new VueComponent (vue.common.js?49d2:4800)
    at createComponentInstanceForVnode (vue.common.js?49d2:4312)
    at init (vue.common.js?49d2:4133)
    at createComponent (vue.common.js?49d2:5610)
    at createElm (vue.common.js?49d2:5557)
    at createChildren (vue.common.js?49d2:5684)
```

**Comment by EvanBurbidge** [comment]
@posva while addRoutes works the issue of it not persisting through a page refresh, or the router not trying to trace down to the path with the component is still quite frustrating behaviour. You can see in routers such as Angular and react-router that while in a child route you can trace down to the required component.
