### ISSUE TITLE
Router使用history 模式，页面刷新后，需要两次返回才能返回上级页面

### ISSUE THREAD

**Issue by EvynXu** [vuejs/vue-router#1453]
### Version
2.1.1

### Steps to reproduce
Router使用history 模式，A页面跳转B页面，然后在B页面执行刷新操作，然后点击返回按钮

Router uses the history mode, the A page jumps to the B page, then performs a refresh operation on the B page, and then clicks the return button

### What is expected?
返回到A页面

Go back to the A page

### What is actually happening?
点击第一次没有任何反应，点击第二次才能正常返回到A页面。点击次数取决于刷新的次数

Click on for the first time without any response and click second times to return to the A page. The number of clicks depends on the number of times you refreshed

---
问题原因应该是刷新后Router内部又再一次执行了 history.pushState方法。

The problem should be that after the refresh, the Router executes the history.pushState method again. But I don't know how to solve it

**Comment by posva** [comment]
Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or Github repository containing a set of reproducible steps that can lead to the behaviour you described. Make sure to boil down the problem as much as possible. Thanks!

**Comment by EvynXu** [comment]
run this repository
https://github.com/vuejs/vue-hackernews-2.0

step1. running http://localhost:8080/
step2. I clicked on the 'New' at the top
step3. Refresh the 'New' page 
setp4. click the browser Back button，The page does not switch
step5. click again，The page switched

**Comment by posva** [comment]
I tested with a simple page and a with a nuxt project (ssr) and while it's true it happens with the vue hackernews website, I'd still like to see a minimal repro. I'm passing the message and closing this. I'll reopen if someone came up with more information or with a minimal reproduction
