### ISSUE TITLE
重大bug，IOS safari浏览器中，使用了vue-router的单页点击返回发生错误

### ISSUE THREAD

**Issue by Lyfme** [vuejs/vue-router#1455]
IOS safari浏览器中， a页面跳到b页面，b页面直接重定向到使用了vue-router的单页应用c，在c中进行内部的切换，点击返回，应该有的效果是在c中正常返回上一个内部页面，但是，实际却直接返回页面b，经测试，只有在手机safari浏览器中才如此，希望你们留意一下

**Comment by cinry** [comment]
vue-router在IOS safar浏览器中，不能使用。审查元素发现连标签<router-view>都没有被编译。直接拿官方文档的例子测试，结果也是一样的

**Comment by fly2017313** [comment]
很遗憾，我也遇到了这样的问题，根据我们的大量打点统计和监控分析，确实会有因vue-router，导致在moutend里获取url参数，获取不到的bug。
我们尝试2种获取参数都有失败的可能
1、原生直接获取location.href
2、用vue提供的方式获取 ，例如：this.$route.params.recruitId
都出现了获取不到参数的问题。
我们不得不改成多页面跳转。
出现的userAgent：

`Mozilla/5.0 (Linux; Android 5.1.1; OPPO A33 Build/LMY47V; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/42.0.2311.138 Mobile Safari/537.36 wkbrowser 4.2.91
Mozilla/5.0 (Linux; Android 6.0; M5 Note Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.146 Mobile Safari/537.36 wkbrowser 4.2.56
Mozilla/5.0 (Linux; Android 5.0.2; vivo Y37A Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/37.0.0.0 Mobile Safari/537.36 wkbrowser 4.2.90
Mozilla/5.0 (Linux; Android 4.4.4; vivo X5V Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36 wkbrowser 4.2.88
`
@vue-issue-bot ，请重视，谢谢。 我在通过 Issue Help里已提交。
https://github.com/vuejs/vue-router/issues/2283
