### ISSUE TITLE
SSR compatibility with IE9

### ISSUE THREAD

**Issue by JounQin** [vuejs/vue-router#1456]
### Version
2.5.3

### Reproduction link
[https://vue-hn.now.sh/top](https://vue-hn.now.sh/top)

### Steps to reproduce
open [Vue HN 2.0](https://vue-hn.now.sh/) in IE9

### What is expected?
Keep the original link

### What is actually happening?
The url will change to https://vue-hn.now.sh/#/top automatically

---
Is there anyway to force enable 'history' mode in IE9 or just don't change url and treat it like IE9-?

**Comment by vvenv** [comment]
http://www.caniuse.com/#search=pushstate
IE9 doesn't support history.pushState, history.replaceState, ...

**Comment by JounQin** [comment]
I know that, I'm just saying to force 'history' mode like opening the page in IE8,etc. It should be optional otherwise when I refresh https://vue-hn.now.sh/#/new then it will be redirected to https://vue-hn.now.sh/#/top in IE9.

What makes SSR to be a not very good solution for IE9 specially.

**Comment by posva** [comment]
I'm not sure to understand here, vue hn redirects to `/top` by default, it happens on other browsers as well. Is it because it fallbacks to hash mode instead of history mode?

**Comment by JounQin** [comment]
@posva I know `vue hn redirects to /top by default`, but the behavior of fallbacking to hash mode in IE9 makes SSR failure when we refresh the page. So maybe there should be an option to avoid fallbacking to hash mode in IE9.

**Comment by posva** [comment]
history mode doesn't work on IE9, as @crossjs said, that's why it fallbacks to hash mode. It wouldn't work otherwise. My recommendation is to setup your server reverse proxy to redirect routes from `foo.com/#/top` to `foo.com/top`, so the server handles them correctly. You can also handle the alternative routes from the server app.

**Comment by JounQin** [comment]
@posva In SSR, there is no need to support pushState or replaceState for IE9, because we can handle the links as new requests(like we open the pages on IE8 or below).

And we can not get hash in server.
https://stackoverflow.com/questions/12066621/how-to-get-variables-in-window-location-hash-in-node-js

**Comment by posva** [comment]
ah, right, the hash being deleted makes it troublesome for IE9. But, at the same time, reloading the page each link is not a good user experience at all

**Comment by JounQin** [comment]
But at least it's *correct*.

For now, when we open a link on IE9 and then share the newest link to another, we will get a wrong page. It seems not a good idea.

So I really think we should have an option to avoid this.

**Comment by posva** [comment]
Why would it be better to reload the page every time you change the path instead of not having SSR in IE 9. Honestly, I prefer having the later and a much smoother experience.

**Comment by JounQin** [comment]
Because the url on IE9 is absolutely wrong, and we can not return the correct url after sharing the wrong the url from IE9. Or maybe we need do a redirect in other browsers when we find there is hash part in location.

**Comment by posva** [comment]
In that case, you may want to use the hash mode everywhere

**Comment by JounQin** [comment]
I really do not want that, we are discussing about SSR, there should be no hash mode, please.

**Comment by posva** [comment]
you don't have a choice if you want to support ie9... You cannot use history mode with that

**Comment by JounQin** [comment]
I'm not asking for supporting history mode on IE9 but disabling fallbacking to hash mode for SSR and treating `router-link`s as new requests.

@yyx990803 Any idea about SSR solution for IE9?

The key point is that in a lot of use cases the url will be shared to another but url on IE9 is absolutely wrong, so current behavior is not so good for me.

**Comment by simplesmiler** [comment]
Ability to make `router-link`s "static" (reloading the page instead of pushing to the history) sounds like a reasonable feature to me.

**Comment by posva** [comment]
IMO it's much better for the user to take a tiny bit more time the first time than taking some extra time **every** click. Also, it'd be a feature for IE9 only...

**Comment by JounQin** [comment]
Maybe current behavior has better performance for user, but it's not friendly to developers, and fallbacking to hash mode is also a feature for IE9 only, isn't it?

Please notice that we're not asking for better performance but just *marking url correct*, and it *should* be able to be controlled by developers.

**Comment by posva** [comment]
> Maybe current behavior has better performance for user, but it's not friendly to developers

It's quite the opposite for the dev: you need to add an option to make it worse for the user. Fallback in ie9 is **necessary** and transparent, not an explicit option we have to add.
I'm not talking about performance, I'm talking about user experience, which is something usually quite important, that's what is confusing me the most...

Have you tested removing the fallback in index.js? (search `fallback`). To see if that is enough to make it work on IE9 for you?

**Comment by JounQin** [comment]
Not exactly.

I've mentioned several times that users will share urls from IE9 to others, then the later user will open a wrong page, so we have to judge if there's a part of hash in location then redirect to the correct page, otherwise the users will complain to us why they can't open links correctly.

And also, we've generated some static HTML files for some urls, and we've tested it on IE8, so I believe no fallbacking is much better to ourselves.

Actually we don't care about IE9- a lot, but the shared links _affects other users_.

**Comment by yyx990803** [comment]
Just... don't mount the app if IE9 is detected?

**Comment by JounQin** [comment]
Don't care about IE9 a lot doesn't means dropping support totally. And it's only related to `vue-router` not `vue`, why not mount it as possible.

**Comment by yyx990803** [comment]
So the only thing needed is disabling route navigations on IE9?

**Comment by JounQin** [comment]
Yes, that's all.

**Comment by posva** [comment]
are you sure that forcing history mode in ie9 is enough? If that's the case, exposing the `fallback` option in the router constructor should be enough (+ handling it)

**Comment by JounQin** [comment]
This has been shipped in https://github.com/vuejs/vue-router/commit/05a5f085fd7e230d4b51862f7a6086fec4378bc6 .

**Comment by clevergod** [comment]
> This has been shipped in [05a5f08](https://github.com/vuejs/vue-router/commit/05a5f085fd7e230d4b51862f7a6086fec4378bc6) .

你好，ie9服务端渲染，设置fallback: false后, 通过编程式导航的话router.push()页面不会跳转（刷新）,router-link是可以的
