### ISSUE TITLE
route.params has properties that don't match dynamic url segments

### ISSUE THREAD

**Issue by psalaets** [vuejs/vue-router#1458]
### Version

2.5.3 (with vue 2.3.3)

### Reproduction link
[https://jsfiddle.net/bhurtqpj/9/](https://jsfiddle.net/bhurtqpj/9/)

### Steps to reproduce
1. Navigate to a route (e.g. `router.push(...)`) passing more params than what the destination route has in its path
2. After navigation, inspect `route.params`

### What is expected?
`route.params` only has properties that match a dynamic segment in destination route's path.

### What is actually happening?
`route.params` has all params that were used during navigation

---
The observed behavior seems wrong based on what I read at:

- https://router.vuejs.org/en/essentials/dynamic-matching.html
- https://router.vuejs.org/en/api/route-object.html

I found [issue 444](https://github.com/vuejs/vue-router/issues/444) and it looks like someone requested this type of thing but it was rejected.

**Comment by posva** [comment]
Yeah, it was rejected because it's a piece of application state that is not on the url, and params are meant to host that application state that is reflected on the url.
So using the params to pass on additional data is a non-supported and discouraged pattern. I hope you're not basing your application on that 😅 
Maybe we should add a note to the docs. I'm open to suggestions

**Comment by psalaets** [comment]
To be clear, I'm not advocating for using the router to pass non-url state around.  

I stumbled upon this because I was navigating with a params object with extra properties that didn't match up with dynamic url segments. The extra properties caused a props function in my route config object to break.

I filed this issue to ask if the param passing should be more strict, i.e. filtering out params that don't match with segments in the destination path.

**Comment by posva** [comment]
Don't worry, I got that.

I think it's the responsibility of the user to be strict when passing params. If it breaks, vue router should be clear about errors

**Comment by LinusBorg** [comment]
> The extra properties caused a props function in my route config object to break.

In what way, can you share an example?

**Comment by psalaets** [comment]
I had two routes `/records/new` and `/records/:id`, both going to the same component. The component had two props: `{ id: Number, new: Boolean }`. If `new` was false, it loads the record for `id` and displays it. If `new` was true it displays an empty record for user to fill in.

The props function I used in both route configs looks like

```js
props(route) {
  if ('id' in route.params) {
    return {
      id: parseInt(route.params.id, 10),
      new: false
    };
  } else {
    return {
      new: true
    };
  }
}
```

When rendering a `router-link` to go to the `/records/new` route I was passing a non-empty object as params (which came out of vuex state, some properties were initialized to null instead of just not existing). I thought it wouldn't matter because none of the null properties would match anything in url, and therefore not be in `route.params`.

This ended up with my component trying to load a record for id `NaN`.

I changed my props function

```diff
props(route) {
-  if ('id' in route.params) {
+  if (route.params.id != null) {
    return {
      id: parseInt(route.params.id, 10),
      new: false
    };
  } else {
    return {
      new: true
    };
  }
}
```

and it's okay now.

Thanks for reading.

**Comment by posva** [comment]
I forgot to look at this. Glad you found the culprit 🙂

**Comment by psalaets** [comment]
Ok so tldr of this is:

Q: `route.params` isn't "strict", should it be?
A: no

**Comment by YevheniiHerasymchuk** [comment]
As I understand, right now the problem can be solved with 
https://router.vuejs.org/en/advanced/meta.html
