### ISSUE TITLE
请问有没有方法可以在路由切换之前做ajax请求。

### ISSUE THREAD

**Issue by chairuosen** [vuejs/vue-router#146]
我翻了vue-router和vue-resource的文档貌似没找到。
类似Angualr 路由里的resolve项。
可以在本页依赖的异步数据资加载完后才切换路由。
谢谢。

**Comment by BrainBuzzer** [comment]
What? Can you please type it in english

**Comment by chairuosen** [comment]
@BrainBuzzer ....ok.thanks. my question is :
Can i do some ajax request before route changes?
like the "resolve" in angular's router config.

**Comment by BrainBuzzer** [comment]
Well I do not think so that this functionality is added still. But let's wait for @yyx990803 reply. If it is not then I will soon have a pull request as this seems interesting.

**Comment by chairuosen** [comment]
well I suddenly found the solution..........
Maybe I could do ajax in async components' callback.

**Comment by chairuosen** [comment]
Well.....finally i found this 
http://vuejs.github.io/vue-router/zh-cn/pipeline/data.html
