### ISSUE TITLE
Alias for '/' not worked in nested routes

### ISSUE THREAD

**Issue by zh-impact** [vuejs/vue-router#1461]
### Version
2.5.3

### Reproduction link
[https://jsfiddle.net/x4storm/qmjw452y/](https://jsfiddle.net/x4storm/qmjw452y/)

### Steps to reproduce
click `/` and `/bar` in Route Alias section, it will same result
click `/` and `/home/foo` in Route nested Alias section, the `/` alias not work

### What is expected?
nested route alias for `/` just like the flat alias.

### What is actually happening?
alias for `/` not worked in nested routes

**Comment by yyx990803** [comment]
This is fixed by 8e30c34
