### ISSUE TITLE
child components route view back to parent component route view

### ISSUE THREAD

**Issue by cdllqos** [vuejs/vue-router#1462]
### What problem does this feature solve?
Sometime,I use child modal component to save,delete or update something, when I have done it, and back to parent component, and then I just want to update my data by ajax. And I use this.$router.go(-1) == this.$router.back() or this.$router.push() to make it, but it can't work. I just think it want to use data for performance...

### What does the proposed API look like?
this.$router.update(-1)

**Comment by LinusBorg** [comment]
What isn't working with `$router.go(-1)` or `$router.back()` ? It sounds like those do exactly what you want...

**Comment by cdllqos** [comment]
@LinusBorg $router.go(-1) or $router.back(), It can work and back my last page, but It can't execute created  method again, I just want to use it to update my new data.

**Comment by LinusBorg** [comment]
in that case, use 
``` javascript
watch: {
  '$route' function (newRoute) {
    // update data here
  }
}
```

or use the `beforeRouteUpdate` Navigation guard as explained here:

https://router.vuejs.org/en/advanced/navigation-guards.html

We don't need a new API for this.

**Comment by cdllqos** [comment]
@LinusBorg It can work, thank u

**Comment by zhe-he** [comment]
when I use 
`watch: {
  '$route' function (newRoute) {
    // update data here
  }
}`  +   webpack  Hot Module Replacement API.

When I modify the code, the route event is executed more than once.
You must manually refresh the page once to work properly.
