### ISSUE TITLE
Allowing Vue Router to allow a path url arguments

### ISSUE THREAD

**Issue by derryspann** [vuejs/vue-router#1474]
### What problem does this feature solve?
Vue Router currently only supports single path arguments i.e:

```js
{ path: '/admin/:pagename/:pageid', component: pageview} 
```
given the following url
'http://domain.com/admin/foo/99'

will return param.pagename as 'foo' and param.pageid as 99

This approach isn't very dynamic to me. 
Allowing declarative path types in Vue Router will allow better support for isometric apps when communicating with a back-end systems.

### What does the proposed API look like?
Vue Router could allow path argument types that will render a specific parameter based on a declared type. Here is my proposed solution

```js
{ path: '/admin/<path:pagename><int:pageid>', component: pageview}
```
When provided the following url
'http://domain.com/admin/long/generic/path/99'

param.pagename will render '/long/generic/path' 
and 
param.pageid will render '99'

VueJS Router would search the route path property declared for path `<types>` arguments  variable. 
Types could include:
<string: propname> ==> 'Single string path argument'
<path: propname> ==> 'Path string arguments'
<int: propname> ==> 'Single integer path argument'

I'm new to using Vue Router and not entirely certain if this feature already exists. Please provide best practice on achieving the above feature.

thanks

**Comment by posva** [comment]
Hi, thanks for the fr. Unfortunately, vue-router uses https://github.com/pillarjs/path-to-regexp to parses paths and convert them to regexp. There's no notion of types when doing so but this is ok because an url is a string by default. To do some type checking you can use the props option when declaring a route. That way you can cast props to other types: http://jsfiddle.net/posva/0937bqx9/

**Comment by derryspann** [comment]
Thanks @posva apparently this was mentioned in the docs at the very end.

The link to pillarjs contained information on how to pass wildcard path arguments using `:path*`

https://github.com/pillarjs/path-to-regexp#zero-or-more

Here is an update fiddle that works as intended. 
http://jsfiddle.net/6yfuz6Lb/1/
