### ISSUE TITLE
it can not response to a search parameter change

### ISSUE THREAD

**Issue by zzzgit** [vuejs/vue-router#1480]
### What problem does this feature solve?
`<router-link to="./?foo=bar">Home</router-link>`

after I click on the link,the `mounted` method of the current component will not been called.
so,how could make the program listen to the change of the search parameters?

### What does the proposed API look like?
nothing

**Comment by posva** [comment]
Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
