### ISSUE TITLE
computed properties don't work with $route.query

### ISSUE THREAD

**Issue by DanielWLam** [vuejs/vue-router#1486]
### Version
2.4.0

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
computed () {
  test: function() {
    return this.$route.query.test || 'hello'    // varaible test is not responsive
  }
}

### What is expected?
test variable can be calculated by $route.query

### What is actually happening?
not reponse

**Comment by posva** [comment]
That's not a valid repro... It should work: http://jsfiddle.net/zwhdtk3g/
I encourage you to ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) if you need specific help
