### ISSUE TITLE
Invalid prop: type check failed for prop "to". Expected String, Object, got Undefined.

### ISSUE THREAD

**Issue by FQZhang** [vuejs/vue-router#1495]
### Version
2.5.3

### Reproduction link
[http://localhost](http://localhost)

### Steps to reproduce
run `yarn run dev`

### What is expected?
no error message in console

### What is actually happening?
app.js:34844 [Vue warn]: Invalid prop: type check failed for prop "to". Expected String, Object, got Undefined.

found in

---> <RouterLink>
       <AncMenu> at /resources/assets/js/components/Menu.vue
         <Root>

---
in Menu.vue
<template>
    <div>
        <ul class="nav nav-pills">
            <li role="presentation" v-for="item in menu">
                <router-link :to="item.url"  @click.native="selected = item.id">{{item.title}}</router-link>
            </li>
        </ul>
    </div>
</template>
<script>
    export default{
        data(){
            return{
                selected: 0,
                menu: [
                    {id: 1, title: "client", status: true, path:'/'}
                ]
            }
        },
        methods: {
            btnClass(id) {
                return this.selected == id ? 'btn-primary' : 'btn-default';
            }
        }
    }
</script>

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Expected String, Object, got Undefined -> `item.url` is undefined
