### ISSUE TITLE
Have the router behave relative to URL the root app is mounted from

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/vue-router#1497]
### What problem does this feature solve?
Right now, if you don't specify a base option, the router will overwrite whatever URL you're on.

Example: 'www.foo.com/bar/baz' is where the app is mounted, the router's '/' path goes to 'www.foo.com', instead of 'www.foo.com/bar/baz'.

This is problematic for when an app (or component) should be reusable on different pages (e.g. `/foo/bar` and `/foo/baz`).

A workaround is to supply the basepath in some way (like through a data attribute), but this is far from elegant:
```js
const router = new VueRouter({
  mode: 'history',
  base: document.querySelector('#app').getAttribute('data-path') || '/',
  routes
})
```

### What does the proposed API look like?
Add a `relative` Boolean option in the router config (or something similar).

```js
const router = new VueRouter({
  mode: 'history',
  relative: true,
  routes
})
```

**Comment by LinusBorg** [comment]
Wouldn't this be enough?
```javascript
const router = new VueRouter({
  mode: 'history',
  base: window.location.pathName,
  routes
})
```

**Comment by LinusBorg** [comment]
Also, this would be problematic with history mode when used with a server that's re-reouting every route to `index.html`

The app could be started from `/` just as well as `/some/other/route`, and making the base dependent on the current path will break your app everytime that it's booting from a subroute.

**Comment by TheDutchCoder** [comment]
@LinusBorg Unfortunately that would indeed result in problems when started from a sub route, that's why it would be great if the router had something built-in for this.

Isn't the Vue router instance aware of it's root path it got created in?

The server should be handling the redirect to the root, the router should behave relatively to that i my opinion, but maybe I'm over simplifying this?

**Comment by LinusBorg** [comment]
> Unfortunately that would indeed result in problems when started from a sub route, that's why it would be great if the router had something built-in for this.

...but a built-in functionality would suffer from the same problem:

> Isn't the Vue router instance aware of it's root path it got created in?

No. From the router's perspective, the "*root path it got created in*" is. e.g. `/yourRoot/users/TheDutchCoder` when you visit the website directly at `www.site.com/yourRoot/users/TheDutchCoder`.

The fact that your nginx frontend served `/yourRoot/index.html` for that route is happening without the client being able to tell. It's totally decoupled.

Something that might help is #1426, if it gets implemented.

**Comment by TheDutchCoder** [comment]
Gotcha.

Well I guess it's just the hacky way then ;)

**Comment by vjoao** [comment]
I'm facing the same issue. I serve 2 apps on different paths:
`/panel` and `/`.

The problem is that when serving the `admin panel` app, history mode replaces whe whole URL to:

`/overview` and `/account` instead of replacing it to `/panel/overview` and `/panel/account`.

How can I hack it?

**Comment by LinusBorg** [comment]
Please use forum.vuejs.org or chat.vuejs.org for questions.
