### ISSUE TITLE
Feature: Populate $route.params before resolving async components

### ISSUE THREAD

**Issue by Avinm** [vuejs/vue-router#1499]
### What problem does this feature solve?
Currently the params are populated after the component resolution is triggered. This makes the value of the various route params unavailable to the loader. Populating the params before can greatly simplify loading of templates and/or data (or even parallel loading of both) which is dependent on the route params.

### What does the proposed API look like?
```javascript
function x()
{
return loadTemplateAsync(app.$route.params.id) // this is currently undefined
}
const routes = [
    { path: '/X/:id', component: x },
];
````

**Comment by posva** [comment]
Including routing logic in the async resolution of view components feels wrong to me. Why do you need to do it that way. I would create different routes for that purpose

**Comment by Avinm** [comment]
This is the only way one could parallelize template loading and data fetching. Why should one wait for template to finish loading before attempting to retrieve data? For example:
```javascript
function x()
{
return LoadDataAndTemplate(app.$route.params.id); // Load Data and template in parallel
// Also, at this point, the navigation has already happened as window.location.href 
//  contains "id/value" so it makes no sense to have $route.params.id undefined. 
}
const routes = [
    { path: '/X/:id', component: x },
];
```

**Comment by posva** [comment]
But why do you include routing logic in the async resolution of view components?

**Comment by Avinm** [comment]
How else do you propose I can parallelize template loading and data fetching? And sometimes you might need to load dynamic templates like an svg which depends on the route params. Is there another approach I am missing?

**Comment by posva** [comment]
You can fetch the data before doing the navigation with a custom router-link component, or a click event or in a before route hook

**Comment by Avinm** [comment]
You mean like `beforeRouteEnter`? I just checked and saw that even `beforeRouteEnter `is executed after component resolution. So still one will have to wait idly till the template is loaded. For people who want to mix their routing logic with component resolution, it is already possible to do so by directly obtaining the value from window.location. And for people who would want to keep it separate, this feature would not impact them in any way. I'd say that the library should offer the freedom for people to choose, as this might make sense in some scenarios and may not in others.

**Comment by posva** [comment]
I mean like `beforeEnter` in config: http://jsfiddle.net/posva/9wzxgmvs/
Look at the end of https://router.vuejs.org/en/advanced/navigation-guards.html

**Comment by Avinm** [comment]
That works, but seems hacky as one would have to write the data fetching logic of a component outside the component, but again this is just my opinion. Feel free to close the issue if you like, then.

**Comment by posva** [comment]
> as one would have to write the data fetching logic of a component outside the component

That's pretty much what you're doing 😛 . Also, you have no choice if you want to split the parallelize component and data fetching
