### ISSUE TITLE
Setting params from v-link isn't working

### ISSUE THREAD

**Issue by OEvgeny** [vuejs/vue-router#150]
I'm trying to put parameters with ``v-link`` as described [here](http://vuejs.github.io/vue-router/en/link.html):
```js
<!-- named route -->
<a v-link="{ name: 'user', params: { userId: 123 }}">User</a>
```
But it not works correctly. See fiddle: http://jsfiddle.net/bz3vdcze/1/

**Comment by adam12** [comment]
Missing route name and param key inside route definition.

See my fork: http://jsfiddle.net/j00ox1zt/

**Comment by yyx990803** [comment]
You are using `path` instead of `name` in your `v-link`.

**Comment by OEvgeny** [comment]
Ah, thanks! It was unclear. It looks like object, why need I specify ``name``? Can't find it in docs.

**Comment by yyx990803** [comment]
http://router.vuejs.org/en/named.html

**Comment by OEvgeny** [comment]
Thanks Evan.
