### ISSUE TITLE
"Fetching Before Navigation" example does not work

### ISSUE THREAD

**Issue by philipithomas** [vuejs/vue-router#1502]
### Version
2.5.3

### Reproduction link
[https://github.com/vuejs/vue-router/issues/1144](https://github.com/vuejs/vue-router/issues/1144)

### Steps to reproduce
The previously closed issue #1144 was opened because the documentation is incorrect. The message from maintainers on that issue states that the method used on the "Fetching Before Navigation" example for the vue-router docs does not work: https://router.vuejs.org/en/advanced/data-fetching.html

### What is expected?
this.post to be set

### What is actually happening?
this.post is null (see issue #1144)

**Comment by posva** [comment]
The example does work: http://jsfiddle.net/onve61xt/
But I understand this is confusing because you shouldn't see an error. See #1499 
I never said the example doesn't work....

---

Next time, make sure to include a reproduction, please
