### ISSUE TITLE
A页面跳转到login的时候我在beforeEnter里面判断了本地是否有token，如果有的话，就next到from.fullPath，但是这样做NProgress就卡在了

### ISSUE THREAD

**Issue by acodercat** [vuejs/vue-router#1505]
`  path: '/login',
    name: 'login',
    component: login,
    beforeEnter(to, from, next) {
      if (localStorage.getItem('token')) {
        next(from.fullPath)
      } else {
        next()
      }
    }`
`router.beforeEach((to, from, next) => {
  NProgress.start()
  next()
})
router.afterEach(() => {
  NProgress.done()
})`

**Comment by aeolusheath** [comment]
afterEach 没有被调用？ 我也遇到了？ @acodercat  你怎么解决的最后
