### ISSUE TITLE
Object in query string parameters does not trigger "route change" if its properties changes

### ISSUE THREAD

**Issue by ppdeassis** [vuejs/vue-router#1509]
### Version
2.5.3

### Reproduction link
[http://jsfiddle.net/6znsr5wd/3/](http://jsfiddle.net/6znsr5wd/3/)

### Steps to reproduce
1. Access fiddle and click on `Access Home`
2. Enter any value on the `input` 
  - it will be the object property used on query string
3. Click on `Update route` button 
  - it will `replace` the route, using the object on query string
  - the query string will be rendered in the `<code>` tag
4. Change the value on the `input` and click on `Update route` again

### What is expected?
The _query string_ is updated with the new value on the object property.

### What is actually happening?
The _query string_ remains the same, ignoring the change on object's property.

---
After some digging in the code, I think I found the [object comparison method](https://github.com/vuejs/vue-router/blob/dev/src/util/route.js#L76) used in [`confirmTransition`](https://github.com/vuejs/vue-router/blob/dev/src/history/base.js#L82) method (which uses [`isSameRoute`](https://github.com/vuejs/vue-router/blob/dev/src/util/route.js#L53)), and it does a simple "non-deep" comparison of properties on query string. Since it's using an Object on the query string, it should do a _deep_ (recursive) comparison of Object properties.

**Comment by posva** [comment]
dup of #1421 
FYI, vue-router does not support nested queries by default, but you can use a lib like qs: http://jsfiddle.net/posva/y5boz2jf/1/
There's already a PR for this at #1425

**Comment by ppdeassis** [comment]
Thanks, @posva.
