### ISSUE TITLE
returned to N times and vue-router BUG

### ISSUE THREAD

**Issue by andylei18** [vuejs/vue-router#1511]
### Version
2.4.0

### Reproduction link
[Https://vue-hn.now.sh/top](Https://vue-hn.now.sh/top)

### Steps to reproduce
Https://vue-hn.now.sh/top

Jump page 2 times after the return is also returned to 2 times to return

### What is expected?
1 time

### What is actually happening?
2 times

---
that is vue-router bug

**Comment by posva** [comment]
I'm sorry, I don't understand what do you mean and the repro is not valid. Can you create a repro using this: http://jsfiddle.net/posva/9r6xhqbp/ Thanks

**Comment by yyx990803** [comment]
This is already addressed and will be fixed in next router release.

**Comment by andylei18** [comment]
What time is the next version?
