### ISSUE TITLE
VueRouter link change

### ISSUE THREAD

**Issue by qianthinkover** [vuejs/vue-router#1515]
### Version
2.5.3

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
when router mode is hash,http://localhost:8082/#/home/products this link is ok for router to next ,but if link change to like this http://localhost:8082/?code=3333&state=scope#/home/products, this router will not work well. Is that a bug for vue-router? how to fix it?

### What is expected?
no demo code

### What is actually happening?
no demo code

---
when router mode is hash,http://localhost:8082/#/home/products this link is ok for router to next ,but if link change to like this http://localhost:8082/?code=3333&state=scope#/home/products, this router will not work well. Is that a bug for vue-router? how to fix it?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
