### ISSUE TITLE
Active Classes for alias routes

### ISSUE THREAD

**Issue by lukepolo** [vuejs/vue-router#1516]
### Version
2.5.3

### Steps to reproduce
Setup 2 routes 
```

path: '/site/:site_id', component: SiteArea,
        children: [
           {
                alias: 'setup',
                path: 'setup/repository',
                name: 'site_repository',
                components: {
                    default: SiteRepository,
                    nav: SiteNav,
                    subNav: SiteSetupNav
                }
            },
            {
                path: 'setup/workflow',
                name: 'site_workflow',
                components: {
                    default: SiteWorkflow,
                    nav: SiteNav,
                    subNav: SiteSetupNav
                }
            },
}

```

This will not allow for site_workflow to be highlighted cause the alias doesn't get a match

### What is expected?
setup/workflow should activate /setup 

### What is actually happening?
setup is not activated 

---
Im sure this is intended but would like to see if we would like to switch , dont think a repo is needed in this case but let me know if im wrong

**Comment by posva** [comment]
yes, please, a repro is always necessary
