### ISSUE TITLE
uncaught error during unit test

### ISSUE THREAD

**Issue by narwajea** [vuejs/vue-router#1525]
### Version
2.6.0

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
- create a new project with vue-cli & webpack template
- add routing conf
- execute "Hello" unit test

### What is expected?
Successful test   no error log.

  Hello.vue
    √ should render correct contents

### What is actually happening?
Successful test   error log:

WARN LOG: '[vue-router] uncaught error during route navigation:'
ERROR LOG: TypeError{line: 69180, sourceURL: 'http://localhost:9876/base/index.js?1847356d1dc613813fe25b2
fceaf98b48711837b', stack: 'http://localhost:9876/base/index.js?1847356d1dc613813fe25b2fceaf98b48711837b:
69180:21
iterator@http://localhost:9876/base/index.js?1847356d1dc613813fe25b2fceaf98b48711837b:221329:11
step@http://localhost:9876/base/index.js?1847356d1dc613813fe25b2fceaf98b48711837b:221212:11
runQueue@http://localhost:9876/base/index.js?1847356d1dc613813fe25b2fceaf98b48711837b:221220:7
confirmTransition@http://localhost:9876/base/index.js?1847356d1dc613813fe25b2fceaf98b48711837b:221358:11
transitionTo@http://localhost:9876/base/index.js?1847356d1dc613813fe25b2fceaf98b48711837b:221260:25
http://localhost:9876/base/index.js?1847356d1dc613813fe25b2fceaf98b48711837b:221637:26'}

  Hello.vue
    √ should render correct contents

---
I don't even understand why a navigation occurs.. BTW it navigates from '/' to '/error', based on the following route configuration:

`{
  path: '*',
  redirect: {
    name: 'error'
  }
}`

Sorry for the reproduction link, I actually can't reproduce that issue on JSFiddle / JSBin / CodePen..

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

I don't know if this is the issue but the asterisk path must be at the end of the routes array

**Comment by narwajea** [comment]
Thanks for your reply, I will post it on the forum. So an issue can only be created with a valid reproduction link, is that it ?

As for the asterisk path, it is indeed at the last position of the routes array. My app is working fine in dev & build modes, it's just the unit test that prints annoyings logs..

**Comment by posva** [comment]
issues are for bug reports and feature requests only and bug reports must include a repro, yes 🙂
