### ISSUE TITLE
Vue-router route name in $route

### ISSUE THREAD

**Issue by infomiho** [vuejs/vue-router#153]
Follow up from this: http://forum.vuejs.org/topic/26/vue-router-named-routes/2

The `$route` object should have the `name` property which is set in the router. I think there are a lot use cases, primarily this would enabled a developer not to depend on a dynamic path but on a single name.

**Comment by airtonix** [comment]
Seems that while this is working if you `console log(this.$route);` it's not showing up in context/scope displayed by the vue-devtools.
