### ISSUE TITLE
Export both View and Link component

### ISSUE THREAD

**Issue by segfaultmedaddy** [vuejs/vue-router#1534]
### What problem does this feature solve?
It discovers the way to developers to define additional features on top of existing router's component. For example, that way I can create something like next's prefetch feature on top of router's router-link component, and then simply override the default one with mine, without introducing a new component.

### What does the proposed API look like?
```js
export default Router;
export RouterLink;
export RouterView;
```

**Comment by posva** [comment]
I'd say `RouterView` instead of `View` 😛 
ATM you can get them by doing `Vue.component('router-link')`

**Comment by VitorLuizC** [comment]
That would be awesome to libs where RouterView and RouterLink are used in custom components and don`t need to install vue-router

**Comment by posva** [comment]
I forgot to say this is not possible in v3 as it is a breaking change (https://github.com/vuejs/vue-router/issues/1976#issuecomment-356736572) but has been implemented in v4 (vue-router@next)
