### ISSUE TITLE
active class css modules

### ISSUE THREAD

**Issue by mmase** [vuejs/vue-router#1535]
### What problem does this feature solve?
Currently, the only built in way to style an active router link is with plain CSS and becomes impossible if using CSS modules

**Comment by LinusBorg** [comment]
Shouldn't this work?
```scss
// someStyles.css

.active-link {
  // our styles here
}
```
```javascript
import Styles from './someStyles.css' // properly config webpack to use CSS modules.
import VueRouter from 'vue-router'

new new VueRouter({
  activeLinkClass: Styles['active-link']
})
```

**Comment by posva** [comment]
You can pass in the class name you want locally and globally

**Comment by mmase** [comment]
Thanks guys! Sorry for the noise

**Comment by mmase** [comment]
But what if your styles are in your `.vue` component? AFAIK there is no way to add an active class with css modules this way

**Comment by LinusBorg** [comment]
It's generally not a good idea to keep styles in a .vue file that should be used outside of that file's component as well.
