### ISSUE TITLE
src props to <router-link>

### ISSUE THREAD

**Issue by jofftiquez** [vuejs/vue-router#1538]
### What problem does this feature solve?
I think it would be nice to have a `src` props to the `<router-link></router-link>` component.

Like : `<router-link :src="pathToImage"></router-link>`

### What does the proposed API look like?
If the src props is present the component should show img with link instead of an `a` tag.

**Comment by javoski** [comment]
I'm not sure what you really want, but you can pass a tag prop to display an image.
```html
<router-link tag="img" :src="imageUrl" to="compName"></router-link>
```

**Comment by jofftiquez** [comment]
Whoah! Thanks @javoski
