### ISSUE TITLE
router params can't be void string

### ISSUE THREAD

**Issue by gd602546628** [vuejs/vue-router#1539]
### Version
2.6.0

### Reproduction link
[http://localhost:8080/#/couponSearch/](http://localhost:8080/#/couponSearch/)

### Steps to reproduce
 ```javascript

{ 
      path: '/couponSearch/:keyword',
      name: 'couponSearch',
      component: couponSearch,
    }



this.$router.push({
            name: 'couponSearch',
            params: {keyword: keyword}
          })
```
if keyword is void string,this router can't be matched

### What is expected?
go to  'couponSearch/'  ，and params.keyword is  void string 

### What is actually happening?
this router can't be matched

**Comment by nirazul** [comment]
Apparently you can make params optional by using a `?`: `/couponSearch/:keyword?`

I haven't found any documentation about this in the `vue-router` docs, not even a mention of `path-to-regexp`. This should really be improved.

**Comment by gd602546628** [comment]
thanks a lot!
  I try this , ```  params.keyword ``` still can't be void string ,but can be ```null```,that was enough

**Comment by nirazul** [comment]
@gd602546628 
Can you leave this issue open? I think the docs really need improvement on this topic.

**Comment by posva** [comment]
It's actually said at https://router.vuejs.org/en/essentials/dynamic-matching.html
Contributions to improve documentations are always welcome 🙂

**Comment by nirazul** [comment]
Totally missed that 😅
