### ISSUE TITLE
Merge strategy is not applied for already registered global components

### ISSUE THREAD

**Issue by nirazul** [vuejs/vue-router#1543]
### Version
2.6.0

### Reproduction link
[http://jsfiddle.net/737m4jwp/10/](http://jsfiddle.net/737m4jwp/10/)

### Steps to reproduce
1. Click on first link
2. Click on second link

### What is expected?
The hook merging works already on the first link.

Option 1: Warn when components are already registered when VueRouter is initialized.

Option 2: Reinitialize components that are already registered.

### What is actually happening?
The hook merging works only after the second link.

The fist hook merging fails because vue-router is late-initialized when global components were already registered. 

---
This was a tough one to figure out...

VueRouter seems to require initialization before any components are registered. It's not obvious why the merge doesn't work at first, but only after the second navigation. 
I would expect / welcome some sort of notification that VueRouter needs to be initialized before registering any global components.

**Comment by posva** [comment]
Thanks for reportingn this. I'm not sure if it's expected, but it's weird that globally registered components do not benefit from later on registered merge strategies.
It's easy to fix from the user perspective though, by moving the `Vue.use` to the top. Why would you lazy load the router?

**Comment by nirazul** [comment]
@posva 
Yes you're right, it's easily fixable and what you suggested, was exatcly what I ended up with to solve the problem. However, as I stated, it wasn't obvious to me that I need to register all plugins before registering global components.

We have a registry function that uses webpack to register all components within a folder to make them easily available without any local imports. We also load our route definitions from a server-provided json file and map component names to their globally registered components.

I've written a [medium article](https://blog.dreipol.ch/how-we-used-vue-js-to-create-a-single-page-application-with-django-cms-95f3d874f354) about this, if you want to dive into details.

**Comment by yyx990803** [comment]
Global component registrations are eager, i.e. they are turned into a constructor the moment they are registered., so you definitely **should** register plugins before registering global components. I'd consider that a best practice.

We might want to document this in docs, but this doesn't seem to be a vue-router issue anyway.

**Comment by nirazul** [comment]
@yyx990803 Should I open a issue about better documenting this in the vuejs repo?

**Comment by posva** [comment]
No please, there's a repo for docs, it's vuejs/vuejs.org
Even better than an issue, create a pull request with your suggestion ☺️
That way, things will go faster

**Comment by nirazul** [comment]
@posva Alright, I'll see what I can do :)
