### ISSUE TITLE
router里的isObjectEqual方法，当对象属性的值为null时，会报错

### ISSUE THREAD

**Issue by tomatoo1** [vuejs/vue-router#1552]
### Version
2.7.0

### Reproduction link
[https://jsfiddle.net/50wL7mdz/43712/](https://jsfiddle.net/50wL7mdz/43712/)

### Steps to reproduce
isObjectEquals方法没写好

### What is expected?
不报错

### What is actually happening?
报nullpointer

---
router里的isObjectEqual方法，当对象属性的值为null时，会报错

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. That repro is only doing `alert(typeof null)`
Thanks!

**Comment by tomatoo1** [comment]
Hi,
the bug is very simple. In the latest release of vue router. A method named isObjectEqual has bug. It use typeof to judge if an variable is object. But when the variable is null, typeof will return object! This will cause  nullpointer exception.

**Comment by posva** [comment]
well, in that case please point out where the problem or a jsfiddle showcasing the problem

**Comment by anhzhi** [comment]
assert isObjectEqual( {q: "", from: null, to: null},  {q: "", from: null, to: null})===true

please add this test Case 

 i wish that vue-router supports url like "http://host:port/dashboards?q=&from&to" 

i get a work around way: 
isObjectEqual( {q: "", from: undefined, to: undefined},  {q: "", from: undefined, to: undefined})
while the url  looks like  http://192.168.10.40:8221/dashboards?q=&from&to

**Comment by CzBiX** [comment]
I just create a new issue about this problem, please see #1566.
