### ISSUE TITLE
iOS UIWebView delegate 'shouldStartLoadWithRequest' can not intercept every url from vue router

### ISSUE THREAD

**Issue by csjlengxiang** [vuejs/vue-router#1561]
for every UIWebview in iOS app. I can not use UIWebView delegate method 'shouldStartLoadWithRequest' intercept url request. 
'shouldStartLoadWithRequest' method will intercept every request from h5. if code return NO. this request will invalid.
When I use vue-router 1.x that 'shouldStartLoadWithRequest' return NO. url request will not work. this as expected.
But when I update vue-router 2.x. I find shouldStartLoadWithRequest return NO can not intercept url request

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
