### ISSUE TITLE
How does a static HTML file use vue-router?

### ISSUE THREAD

**Issue by aisin** [vuejs/vue-router#1562]
### What problem does this feature solve?
I'm using Vue to develop a PC APP, and try to open a static HTML instead of server-link-access, but the router does not work. How should I solve it?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Using hash mode should work
