### ISSUE TITLE
`isObjectEqual` will throw exception when object contains null value

### ISSUE THREAD

**Issue by CzBiX** [vuejs/vue-router#1566]
### Version
2.7.0

### Reproduction link
[https://jsfiddle.net/t8gpt9mk/](https://jsfiddle.net/t8gpt9mk/)

### Steps to reproduce
Click router link in page.

### What is expected?
Query in url changed.

### What is actually happening?
Throw TypeError.

---
This code works well on vue-router 2.5.3, and bug introduce by pull request #1425.

**Comment by posva** [comment]
Thanks for a more comprehensive bug report! 😄

**Comment by BboyAwey** [comment]
这个方法使用 `=== void 0` 来判断是否为对象，结果碰到`null`就GG了...快点修复吧~
![vue-router-bug](https://user-images.githubusercontent.com/15099804/28156970-75cb5630-67e7-11e7-856c-02e2964543df.png)

**Comment by tebaly** [comment]
May be omit query parameter if is Null, like axios?
