### ISSUE TITLE
Override v-link `-exact` class

### ISSUE THREAD

**Issue by Morgul** [vuejs/vue-router#157]
I'm using Bootstrap, and my routes are setup as follows:

* `/` - The main landing page of the app when not logged in.
* `/dashboard` - The main landing page of the app when logged in.

However, when I set `linkActiveClass` to be `'active'` (the class Bootstrap is expecting), both links appear active on `/dashboard`, and neither on `/` . When I inspect, what's going on appears clear; `'active-exact'` is the class that is correctly depicting which one is active, while all matching routes are getting `'active'`. That's awesome if I was doing a breadcrumb bar, however, it doesn't work well with how bootstrap expects things.

Now, I can simple set `'v-link-active-exact'` to have the correct styling, and it works well enough, but it would be really awesome if I could set two completely different classes for `linkActiveClass` and the `-exact` variant.

**Comment by yyx990803** [comment]
fb3e727

**Comment by Morgul** [comment]
@yyx990803 Awesome! Thanks for adding this.
