### ISSUE TITLE
希望vue-router能支持跳转站外链接

### ISSUE THREAD

**Issue by hhhuaang** [vuejs/vue-router#1571]
### What problem does this feature solve?
在实际开发过程中，有时会动态指定按钮跳转的页面，这个地址是有用户发布信息的时候指定的，有可能是站内的页面，也可能是站外的链接

### What does the proposed API look like?
我也不知道该怎么设计

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
