### ISSUE TITLE
history 模式下刷新页面 hash 会丢失

### ISSUE THREAD

**Issue by lianer** [vuejs/vue-router#1575]
### What problem does this feature solve?
保留 hash

### What does the proposed API look like?
无

![](http://olhzdi73f.bkt.clouddn.com/vue-router-history-hash.gif)

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. You need to provide a repro when reporting bugs.
Thanks!
