### ISSUE TITLE
v-link active handling option

### ISSUE THREAD

**Issue by rpkilby** [vuejs/vue-router#158]
Hey. Just a suggestion in relation to #157.

Would it make sense to provide a v-link option for handling the application of the `linkActiveClass` class? As @Morgul mentioned, the current implementation makes sense for breadcrumbing, but can run into issues in other contexts such as navigation bars. For example,
```html
<div class="navbar thing">
    <a v-link="{ path: '/' }">Dashboard</a>
    <a v-link="{ path: '/widgets' }">Widgets</a>
    <a v-link="{ path: '/frobs' }">Frobs</a>
</div>
```

You may want `/frobs` to continue matching on `/frobs/1/quirks`, but the Dashboard link should only ever be active when visiting `/`.

Behavior could look something like:
- The `linkActiveExactClass` class is *always* applied to the link on an exact route match with the URL.
- By default, the `linkActiveClass` class is applied when the route has a startswith match on the URL.
- The behavior for `linkActiveClass` can configured with either `'exact'` or `'match'`. Possible syntax:
```html
    <a v-link="{ path: '/', active: 'exact' }">Dashboard</a>
```

**Comment by Morgul** [comment]
I'm actually completely for this suggestion! It would give a much finer-grained control over the way the classes are applied, and certainly fits my use cases. :)

**Comment by yyx990803** [comment]
Looks like the main issue here is just the index path. It seems making `/` always match exact would solve the issue? I just don't want to add an extra option that has only one use case.

**Comment by yyx990803** [comment]
See 65009d0f468391370c894139ade3ee45851a55d4

It should fix the home route matching problem. (also addresses #157)

**Comment by rpkilby** [comment]
> It seems making / always match exact would solve the issue? 

I'm not sure its entirely correct.

- Wouldn't this break the breadcrumbing scenario? 
- `/` was just an example, no reason the routes couldn't be based off of `/foo`. That said, nested routes might work? ie, 
```
{'/foo': {
    '/': {},
    '/bar': {},
    '/bar/:id': {}
}}
```

**Comment by yyx990803** [comment]
Good point. yeah the extra option may just be necessary.

**Comment by yyx990803** [comment]
How about we just get rid of `linkActiveExactClass` and configure the matching behavior inline (default behavior is inclusive match):

``` html
<a v-link="{ path: '/', exact: true }"></a>
```

In addition the active class should be configurable inline too:

``` html
<a v-link="{ path: '/some/path', activeClass: 'active' }"></a>
```

**Comment by yyx990803** [comment]
4f42085

**Comment by rpkilby** [comment]
Sounds good to me.
