### ISSUE TITLE
In hash mode, hash value should be encoded to be a valid URL

### ISSUE THREAD

**Issue by nkovacs** [vuejs/vue-router#1581]
### Version
2.7.0

### Reproduction link
[http://fiddle.jshell.net/nkovacs/wajqos5L/](http://fiddle.jshell.net/nkovacs/wajqos5L/)

### Steps to reproduce
1. use hash mode in vue-router
2. navigate to a page with a hash: router.push({ path: "/foo", hash: "somehash" })
3. look at window.location.href

In the reproduction, click the "Navigate to hash with router" button, then look at the console.

### What is expected?
The second hash in window.location.href should be encoded, e.g. `https://fiddle.jshell.net/_display/#/foo%23somehash`

### What is actually happening?
The second hash is not encoded, e.g.
`https://fiddle.jshell.net/_display/#/foo#somehash`

---
The fragment should not contain a number sign: https://tools.ietf.org/html/rfc3986#section-3.5
Browsers are less strict about this, so it works.

Parsing the encoded number sign also doesn't work. I ran into this bug because I'm generating an url on the server, and the second hash is encoded correctly by the server-side code, but vue-router was unable to parse it.
I can't show this on jsfiddle though.

**Comment by posva** [comment]
Tested on firefox, safari and chrome and works as expected. BTW, it's not changing anything but you forgot to include the router: http://fiddle.jshell.net/wajqos5L/1/
for the second _bug_ you can send an html file as a repro

**Comment by nkovacs** [comment]
What do you mean it works as expected? Is the second hash encoded as `%23`? It's not for me on Chrome.

The two bugs are related. If vue-router generates urls with an encoded hash, it needs to be able to properly parse them too.

**Comment by nkovacs** [comment]
Here's a github pages version where you can see and change the url:
https://nkovacs.github.io/vue-router-bug/index.html#/foo#somehash
And this doesn't work:
https://nkovacs.github.io/vue-router-bug/index.html#/foo%23somehash

**Comment by posva** [comment]
Sorry it wasn't clear, I meant that I couldn't reproduce it because the hash doesn't get escaped

**Comment by nkovacs** [comment]
But that's the problem. It should be escaped.

**Comment by posva** [comment]
Oh man, sorry. Now I see why that conversation didn't make sense 😆 
If you pass the hash using `hash`, it won't be escaped, that's intended. Are you using hashes for something in particular?

**Comment by nkovacs** [comment]
My problem is that I'm generating a redirect url on the backend, and it's generated with the second hash escaped, and vue-router can't parse that.
Here's a simple example in go: it can parse the url with the unescaped hash, but it generates an escaped hash: https://play.golang.org/p/_ROUG8dYVU

Why is this the intended behavior? The url that vue-router generates, `https://nkovacs.github.io/vue-router-bug/index.html#/foo#somehash`, is not valid according to RFC3986. It should be `https://nkovacs.github.io/vue-router-bug/index.html#/foo%23somehash` (which should be equivalent to `https://nkovacs.github.io/vue-router-bug/index.html/foo#somehash` if you turn on html5 history mode).

**Comment by posva** [comment]
Aaah, now I see. I didn't get it because of _number sign_; I didn't understand it was referring to the hash character.
I wonder if this may affect other people. It's technically a breaking change, even if it's for the best

**Comment by nkovacs** [comment]
Go generates urls according to the rfc, so non-ascii character also get encoded: https://play.golang.org/p/wlXtWZ_NBa
However, the [URL constructor](https://developer.mozilla.org/en-US/docs/Web/API/URL) doesn't do that (neither in chrome nor in firefox), and it doesn't even escape the second number sign: `var u = new URL("https://nkovacs.github.io/vue-router-bug/index.html#/föű#somehash")`.
The funny thing is, if you try `u.href` in chrome's dev tools after that, chrome doesn't correctly autolink the url, it breaks at the accented letters.

If I'm reading [the spec](https://url.spec.whatwg.org/#fragment-state) right, a number sign in the fragment part is supposed to be a validation error, but utf8 characters are allowed. Yet both firefox and chrome allow and even generate urls with a number sign in the fragment.

So given these and that the url looks better without all that encoding and that it would break backwards compatibility, I'll close this, and I'll deal with it on my backend.

Thanks.

**Comment by posva** [comment]
Ok, glad you can work around it. I'm still keeping an eye on this and what is the impact when using hashes on hash mode
