### ISSUE TITLE
Support selective SSR routes

### ISSUE THREAD

**Issue by liamwang** [vuejs/vue-router#1584]
### What problem does this feature solve?
Use SSR on specific routes. 

### What does the proposed API look like?
Actually, I have no idea right now.  It maybe something that works together with `vue-server-renderer` . 

BTW, is there any workaround for this feature?

**Comment by callumacrae** [comment]
What problem does this feature solve? You haven't said a problem, just the feature.

How would this be useful? :)

**Comment by JounQin** [comment]
Why not just implement it in your own server code?

IMO, you only need do several tiny things:

1. generate a normal `index.html` for non-ssr requests (you may need to read it from memory file system on development, or just rewrite the url to `index.html`)
2. add some judgment statements for non-ssr urls which will return `index.html` immediately
3. do not wait router ready on `entry-client.js` for non-ssr `index.html`

Here is the example:
https://github.com/JounQin/vue-ssr/blob/master/server/index.js#L72
https://github.com/JounQin/vue-ssr/blob/master/src/entry-client.js#L68

**Comment by posva** [comment]
This is something you should do in your server code. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js) if you need help 🙂

**Comment by liamwang** [comment]
@JounQin  谢谢。能否加你的QQ或微信交流一下？或者你加我QQ或微信（同号）：262359372

**Comment by liamwang** [comment]
@callumacrae @posva 

Sorry for the problem is not clearly described.

### What problem does this feature solve?

1. Reduce server stress. For user-specific web pages SSR is not required, such as pages like "My Account". For the PC web site especially, we use SSR only to make SEO friendly in most scenarios.

2. Many third-party plugins do not support SSR, and one solution is to disable SSR from pages that refer those plugins, such as Quill a wysiwyg editor (for purely editing pages SSR is not required).

谢谢 @JounQin 给的解决方案。
