### ISSUE TITLE
can't import RoteLink from 'vue-router' when i use vue render function with jsx

### ISSUE THREAD

**Issue by zrain** [vuejs/vue-router#1587]
### Version
2.7.0

### Steps to reproduce
none

### What is expected?
none

### What is actually happening?
none

---
none

**Comment by callumacrae** [comment]
can you post some code? otherwise this issue will just get closed when someone on the team sees it 😄

**Comment by zrain** [comment]
![image](https://user-images.githubusercontent.com/6274220/28113302-a04d157e-672e-11e7-8d8e-a7f370ac18ce.png)


import RouteLink from 'vue-route' ? ? ? ?

how can i import routeLink individually ?

vue-route does not support to import RouteLink individually!

this is vue-router install.js
![image](https://user-images.githubusercontent.com/6274220/28113448-22225ec4-672f-11e7-9788-52c6b49c12a9.png)

```javascript
export default {
  render (h) {
    let path = '/test'
    return <Routelink to={path}/>
  }
}
```

![image](https://user-images.githubusercontent.com/6274220/28113509-70f6fc58-672f-11e7-9d06-571ad194cc13.png)

**Comment by fnlctrl** [comment]
Simply use `<router-link>` inside jsx, as it's a global component registered by vue-router during install. No need for manual imports.
```jsx
export default {
  render (h) {
    let path = '/test'
    return <router-link to={path}/>
  }
}
```

**Comment by callumacrae** [comment]
Try using `<RouterLink>` (or `<router-link>` - haven't used JSX before) instead of `<Routelink>` - you've spelled it wrong.

EDIT: @fnlctrl beat me!
