### ISSUE TITLE
add params to the router.back()

### ISSUE THREAD

**Issue by lxholding** [vuejs/vue-router#1594]
### What problem does this feature solve?
This features is very userful!

I have a common page to receive user input，any other page call the page to receive the user input.
Now I cant`t pass the user input to the router.back()...
 

### What does the proposed API look like?
page1 page2

page2.router.back({data:'xxx'})

page1.routeBackReceive((data) => {
     console.log(data) //console log:{data:'xxx'}
})

**Comment by posva** [comment]
use `push` instead to _set data_ (using params and queries) because it's like doing a new navigation
