### ISSUE TITLE
in hash mode, programmatic navigation with query navigate to incorrect url

### ISSUE THREAD

**Issue by wuhaosky** [vuejs/vue-router#1601]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/wuhaosky/k59fkmhc/6/](https://jsfiddle.net/wuhaosky/k59fkmhc/6/)

### Steps to reproduce
1.click "click me" button

### What is expected?
origin url is https://fiddle.jshell.net/_display/#/ ,
in hash mode, I want to use this.$router.push({ path: 'bar', query: { plan: 'private' }}) to nativage to https://fiddle.jshell.net/_display/?plan=private#/bar

### What is actually happening?
real nativagation url is https://fiddle.jshell.net/_display/#/bar?plan=private

**Comment by wuhaosky** [comment]
@yyx990803

**Comment by wuhaosky** [comment]
@yyx990803

**Comment by posva** [comment]
That's working as expected, queries go after path. I recommend you checking the docs at https://router.vuejs.org/

**Comment by wuhaosky** [comment]
@posva  I know queries go after path, but actually go after hash in "hash" mode.

**how to reproduce:**
location.href = "https://fiddle.jshell.net/_display/#/bar?plan=private";
location.pathname
"/_display/"
location.search
""
location.hash
"#/bar?plan=private"

**Comment by posva** [comment]
they go after the hash in hash mode because they must be after the path
