### ISSUE TITLE
Component name is not shown in Vue devtools

### ISSUE THREAD

**Issue by mitar** [vuejs/vue-router#1604]
### Version
2.7.0

### Reproduction link
[https://codepen.io/anon/pen/vZMEXP](https://codepen.io/anon/pen/vZMEXP)

### Steps to reproduce
1. Have some components with names defined. 
2. Use such component as route's component.
3. Get router to render the route/component.
4. Inspect the Vue components tree in Vue devtools. Observe that component is not named by its name, but it is anonymous component. This makes debugging harder.

### What is expected?
![screen shot 2017-07-15 at 2 33 29 pm](https://user-images.githubusercontent.com/585279/28242804-9a022766-696a-11e7-8493-2d5ac92cdc03.png)

### What is actually happening?
![screen shot 2017-07-15 at 2 31 08 pm](https://user-images.githubusercontent.com/585279/28242792-43a9308a-696a-11e7-812b-1fa4e3020e96.png)

**Comment by Akryum** [comment]
You defined names on the routes instead of the components in your repro.

**Comment by posva** [comment]
When using `vue` files, names are auto injected but otherwise you need to add them yourself

**Comment by mitar** [comment]
> You defined names on the routes instead of the components in your repro.

Oh, that was a mistake in the reproduction. Thanks for catching that. Then I do not know why https://github.com/meteor-vue/todomvc/issues/1 does not work. :-( I have it in a `vue` filename there.

**Comment by haysmike** [comment]
I'm actually seeing this issue with `.vue` files that don't explicitly declare a `name` after a hot-reload in DevTools... Works fine after a full reload.

Update: created https://github.com/vuejs/devtools/issues/1992
