### ISSUE TITLE
Nested routes breaks the static path

### ISSUE THREAD

**Issue by KakarN** [vuejs/vue-router#1606]
### Version
2.7.0

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
My css is placed inside the static directory.

html:

```
<html>
  <head>
    <link rel="stylesheet" href="static/font-awesome/css/font-awesome.min.css">
  </head>
  <body>
    <div id="app"></div>
  </body>
</html>```
And I have nested routes

```
const routes = [
    {
        path: '/user/:id', component: Profile,
        children: [
            {
                path: 'feeds',
                component: ProfileFeeds
            },
            {
                path: 'photos',
                component: ProfilePhotos
            },
        ]
    },
    ... some other routes... ,
];
```

When I am outside of the nested route, the static file is found. But, when I navigate to `user/user_21/feeds`, Vue can't find the css.

The working css:

`http://localhost:8080/static/font-awesome/css/font-awesome.min.css`

Turns into a wrong static path:

`http://localhost:8080/user/static/font-awesome/css/font-awesome.min.css`

How can I solve this?

### What is expected?
The path to the static file should remain constant.

### What is actually happening?
The path to the static file is changed.

<!-- generated by vue-issues. DO NOT REMOVE -->

**Comment by posva** [comment]
The static path is unrelated to vue-router...

Please, ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by vbgm** [comment]
and yet the problem persists.. :-/ 
@KakarN did yo solve it?

**Comment by KakarN** [comment]
@vblagomir  Please see the answer that I have posted in [Stackoverflow](https://stackoverflow.com/questions/45133669/nested-routes-breaks-the-static-path).
