### ISSUE TITLE
meta object empty

### ISSUE THREAD

**Issue by gabifromkorea** [vuejs/vue-router#1618]
### Version
2.2.0

### Reproduction link
[https://github.com/gomonk3037/vue-chalkack](https://github.com/gomonk3037/vue-chalkack)

### Steps to reproduce

**Before**
```javascript
export default [
  {
    path: '/home',
    meta: { requiresAuth: true },
    name: 'UserPage',
    component: UserPage,
  },
];
```

**Current**
```javascript
export default [
  {
    path: '/home',
    meta: { requiresAuth: true },
    component: UserPage,
    children: [
      {
        path: '',
        name: 'UserPage',
        component: MainPage,
      },
    ],
  },
];
```

### What is expected?
Children inherit meta value of the parent router object

### What is actually happening?
meta object empty in '/home' route & children route

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Sharing your whole project as the repo is just too much... If you manage to boil it down in a jsfiddle, I can take a look

**Comment by gabifromkorea** [comment]
@posva 
I'm sorry I uploaded the wrong issue because I did not know it was really a bug.
> '/foo' click => console log shows that the meta object for the route object is empty
https://jsfiddle.net/jm84numq/2/

**Comment by callumacrae** [comment]
I think this is by design, not a bug - although a way to access the parent route from beforeEach would be really nice.

**Comment by posva** [comment]
Yeah, it's by design. Inheriting meta fields can be problematic. To get access to the meta fields of the parent, you have to look at the `matched` property
