### ISSUE TITLE
High priority for children route from parent

### ISSUE THREAD

**Issue by achen224** [vuejs/vue-router#1621]
### What problem does this feature solve?
I want render component  to different router-view( root or inside component ) depends on where route come from

http://jsfiddle.net/djalexxx/zc19p580/3/

case1 from /home : /item/123 will render in root's router-view

case2 from /item : /item/123 will render in itemList's router-view

### What does the proposed API look like?
maybe add property for router to set priority type like:

new VueRouter({

  type: 'expaned(default:order by route define) | nested(children route from parent first)'

})

**Comment by posva** [comment]
This is not possible and I don't think it's a good practice because a route should always show the same view no matter where the navigation comes from

edit: It's actually possible by listening to the history api but I really discourage from doing so...

**Comment by achen224** [comment]
yes,I totally agree

I just try to show same view but in different position like lightbox

for example :
[500px](https://500px.com/popular) will show picture detail in lightbox when you come from list
but when user refresh page it will show picture detail directly 

I'll try to find better way to do that
thx

**Comment by simplesmiler** [comment]
Related to https://github.com/vuejs/vue-router/issues/703
