### ISSUE TITLE
不断来回切换路由页面就可以看到内存不断增长直到浏览器崩溃

### ISSUE THREAD

**Issue by paygle** [vuejs/vue-router#1622]
### Version
2.7.0

### Reproduction link
[https://github.com/paygle/vue2ElementTest.git](https://github.com/paygle/vue2ElementTest.git)

### Steps to reproduce
1. 下载源码
2. 完成安装（源码内有操作步骤）
3. 运行工程后在“性能测试”菜单下，来回切换下面的子菜单就可以看到内存增长的情况（IE最突出）。

### What is expected?
我们的项目属于大型表单应用，这个源码样例的处理和展现能力还不到我们实际应用的1/3，希望解决路由在不断切换页面后内存无限增长的问题，尤其是IE浏览器最为严重。实现生产中IE浏览器也是用得最多的。

### What is actually happening?
IE9、IE11下面，多次单页面路由切换，在本机上监控浏览器占用内存，发现IE所占内存没有上限，一直会占用到1.6-1.7G左右的内存，然后浏览器崩溃。

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Please, don't share you whole project to report an issue, I cannot use that to test

**Comment by ghost** [comment]
大佬 同样遇到这样的问题 请问有什么好的解决办法吗
