### ISSUE TITLE
vue-router cant get query value without '#/'

### ISSUE THREAD

**Issue by nbwsc** [vuejs/vue-router#1624]
### Version
2.7.0

### Reproduction link
[http://jsfiddle.net/nbwsc/vav8yg63/](http://jsfiddle.net/nbwsc/vav8yg63/)

### Steps to reproduce
make your url as `http://ip:port/path/page/#/?query=value` and you can get the query value using `$route.query` but if you remove the `#/`(like `http://ip:port/path/page?query=value` )and refresh the page . It will get undefined .
I meet some trouble with this using nginx static file server to deploy my Vue app.
So I get the query value using my own parser
is that a bug?

### What is expected?
it should work I hope

### What is actually happening?
but it gives me undefined

**Comment by posva** [comment]
You have to change the `mode` option when creating the router. See https://router.vuejs.org/en/essentials/history-mode.html
