### ISSUE TITLE
beforeRouteLeave and other guards to be called when a property in a route is changed

### ISSUE THREAD

**Issue by silverbackdan** [vuejs/vue-router#1629]
### What problem does this feature solve?
When changing between the same route, but with an updated property/slug the beforeRouteLeave and other guard functions should be called. Currently I have a number of pages using the same route which have a common template and components. When adding a CMS bar (which shows to a user when content has been changed and gives them the option of saving changes), I'd like to warn a user that their changes will not be saved if they continue to another page. But the guard is not called and I'm not sure if I can prevent the route changing just by watching $route

I couldn't see an issue which addresses this currently.

### What does the proposed API look like?
I think this could be implemented as standard as it seems more intuitive. Perhaps to enable/disable this feature one could add a simple boolean option on the route like `guardExact` or similar.

**Comment by posva** [comment]
You can use `beforeRouteUpdate`

**Comment by silverbackdan** [comment]
Thanks @posva - sorry for raising this!

**Comment by silverbackdan** [comment]
I wanted to check before raising another issue if it's OK @posva - It seems that `beforeRouteUpdate` reloads the current page if I return `next(false)` - it seems like the data has already changed by the time it is called. Is this intentional behaviour? It's possible that it may be related to NuxtJS

**Comment by posva** [comment]
It seems to work: http://jsfiddle.net/8ugmabnt/
You may need some help, you can ask for it in discord or the forums 🙂

**Comment by silverbackdan** [comment]
Ah cool, thanks again for this, very helpful!
