### ISSUE TITLE
Pages setup with dynamic imports won't load when used via router.replace

### ISSUE THREAD

**Issue by LanFeusT23** [vuejs/vue-router#1630]
### Version
2.7.0

### Reproduction link
[https://github.com/LanFeusT23/dynamic-import-vue-router-issue](https://github.com/LanFeusT23/dynamic-import-vue-router-issue)

### Steps to reproduce
1. Setup routes with dynamically imported components
2. Setup a manual `<a>` link that will link to a route that redirects to the new one (do not use router-link, this is a "fake" link as if it came from another site)

### What is expected?
The new route should load.

### What is actually happening?
The default route loads.

---
We recently converted one of our tool to Vue. However we need to have backwards compatibility with the urls.

They used to be something like such: `/?view=thisPage&key=123`

We decided that on app start in `main.js` we could simply check the URL for `view` and `key` query strings and simply use vue-router to `router.replace` to the new route.

The old links come from emails which we cannot update, and while we updated the template for new emails, old ones still need to work.

This works perfectly fine when the new route's component is not dynamically loaded. However, once we update the component to dynamic it no longer works, and simply does not load the page, nor the chunk file.

Current solution is not ideal, we simply do not dynamically load that page, and instead have the component itself check for the `key` prop and dynamically load it's internal components and data when that prop is set.

**Comment by LanFeusT23** [comment]
A better solution is actually to move our redirect code AFTER the `new Vue()` instance is created.

However that first loads the default route and then the new route, which means that if the default route has any data loaded it will cause a delay.

**Comment by posva** [comment]
You need to wrap that code in the `onReady` method of the router: https://router.vuejs.org/en/api/router-instance.html#methods

```js
router.onReady(() => {
 var oldPage = getQueryStringValue("view");
 var oldKey = getQueryStringValue("key");

if (!_.isEmpty(oldPage) && !_.isEmpty(oldKey)) {
         router.replace({ name: 'viewPage', params: { someKey: oldKey } });
     }
 }
})
```

**Comment by LanFeusT23** [comment]
Thanks that makes sense. Although that still loads the landing page before redirecting. I was hoping for it not to do that.

**Comment by posva** [comment]
you can add that on a `beforeEnter` hook to make it smoother
