### ISSUE TITLE
How to access $router in common js module?

### ISSUE THREAD

**Issue by onlyfew** [vuejs/vue-router#1632]
I have a common js "fetch.js" to request data from server. when get a special code like -1, I want to redirect to /login. But I don't know how to access $router in fetch.js file.
Thanks.

**Comment by dima74** [comment]
[Here is](https://stackoverflow.com/a/43562210/5812238) the solution, first add import:

    import router from '@/path/to/router.js';

and then just use router.

(`router.js` is file with code `export default new Router({ ...`)

**Comment by onlyfew** [comment]
@dima74 Thank you very much.
