### ISSUE TITLE
How to access $router in common js module?

### ISSUE THREAD

**Issue by onlyfew** [vuejs/vue-router#1633]
### What problem does this feature solve?
I have a common js "fetch.js" to request data from server. when get a special code like -1, I want to redirect to /login. But I don't know how to access $router in fetch.js file.
Thanks.

### What does the proposed API look like?
thanks.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You may need to pass it as an argument to the function, but it really depends on your use case
