### ISSUE TITLE
vue-demo error:template or render function not defined

### ISSUE THREAD

**Issue by yueswing07** [vuejs/vue-router#1638]
### Version
2.7.0

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Steps to reproduce
when use vue scaffolding addr:https://github.com/vuejs/vue-cli webpack demo, edit src/router/index.js
line 12 from component: Hello to component: {Hello} 

### What is expected?
no error 

### What is actually happening?
there is an error Failed to mount component: template or render function not defined.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by yueswing07** [comment]
@posva  i am not sure   it is a bug
