### ISSUE TITLE
Problem updating view data when using v-link

### ISSUE THREAD

**Issue by elcontraption** [vuejs/vue-router#164]
I am trying to link between components using `v-link`. When a link is clicked, the URL is updated, but the view data does not update unless the page is manually refreshed.

Some context for this example: a Tour has many Tour Objects, and Tour Objects need to link to previous/next Tour Objects.

Here's the route that represents a Tour Object:
```js
'/tours/:tourId/objects/:objectId': {
    name: 'tourObject',
    component: tourObjectComponent
}
```

I didn't want to represent Tour Objects using a nested route (they're more of their own view), but maybe that's where I went wrong?

[Here is a JsFiddle example](http://jsfiddle.net/elcontraption/crrk3mhe/34/)

**Comment by zenozeng** [comment]
@elcontraption I guess maybe you component is reused. By default, vue-router will reuse current component unless you setup YouComponent.route.canReuse. See also: http://vuejs.github.io/vue-router/en/pipeline/can-reuse.html

**Comment by zenozeng** [comment]
@elcontraption using route.data may be an better option: http://vuejs.github.io/vue-router/en/pipeline/data.html

**Comment by elcontraption** [comment]
Thank you @zenozeng, I will look into both of those options.

Having just realized that there is a new Vue forum, I am closing this issue and have posted the topic there.
