### ISSUE TITLE
Going to another not spa page then hitting back button returns JSON response

### ISSUE THREAD

**Issue by jericopulvera** [vuejs/vue-router#1643]
### Version
2.7.0

### Reproduction link
[https://github.com/jericopulvera/test-app](https://github.com/jericopulvera/test-app)

### Steps to reproduce
1. I searched something from my search bar then router.push('search', query)

2. Search returns a result

3. Then I go to a login page that is not an SPA.

4. I click back button from the browser.

5. I get a JSON response instead of vue-router page.

### What is expected?
return vue router page.

### What is actually happening?
returning a json response.

**Comment by callumacrae** [comment]
that's a pretty big repo! are you able to provide a minimal case?

**Comment by LinusBorg** [comment]
If you see the JSON response from the server in the browser window, then that's an issue with your server, vue-router (running on the client) has nothting to do with it.

I assume you are using vue-router in history mode? You must configure your server accordingly to this:

https://router.vuejs.org/en/essentials/history-mode.html
