### ISSUE TITLE
There is no class 'router-link-active' on the link that references alias

### ISSUE THREAD

**Issue by Sociopacific** [vuejs/vue-router#1649]
### Version
2.7.0

### Reproduction link
[https://jsfiddle.net/omt23qs1/3/](https://jsfiddle.net/omt23qs1/3/)

### Steps to reproduce
Check class on second link

### What is expected?
The second link should have the class 'router-link-active'

### What is actually happening?
On the second link there is no class 'router-link-active'

**Comment by posva** [comment]
Dup of #419
