### ISSUE TITLE
children component disappear when router-link navigates to a exactly same named dynamic route with object type "to" props

### ISSUE THREAD

**Issue by imageslr** [vuejs/vue-router#1651]
### Version
2.7.0

### Reproduction link
[http://jsfiddle.net/zhukaihao/eo9a14ck/4/](http://jsfiddle.net/zhukaihao/eo9a14ck/4/)

### Steps to reproduce
点击`/user/foo`，子组件创建；
再次点击`/user/foo`，子组件消失，`vue-devtools`显示该子组件未被创建；

Click `/user/foo`, subcomponent is created;
Click `/user/foo` again, the subcomponent disappears, `vue-devtools` shows that the subcomponent is not created.

### What is expected?
点击`/user/foo`多次，子组件始终存在。

Click `/user/foo` repeatedly, subcomponent always exists.

### What is actually happening?
点击`/user/foo`第二次，子组件消失，`vue-devtools`显示该子组件未被创建；

Click `/user/foo` again, the subcomponent disappears, `vue-devtools` shows that the subcomponent is not created.

---
`/user/foo`的`to`属性是一个对象，`/user/bar`的`to`是一个字符串。点击`/user/bar`多次，子组件始终存在。

The prop `to` of `/user/foo` is an object, yet the prop of `/user/bar` is a string. Click `/user/bar` repeatedly, subcomponent always exists;

**Comment by LinusBorg** [comment]
Please look at the console:

> Named Route 'user' has a default child route. When navigating to this named route (:to="{name: 'user'"), the default child route will not be rendered. Remove the name from this route and use the name of the default child route for named links instead.

In essence, that means:

* **Bad**: `this.$router.push({name: 'user'})`
* **Good**: `this.$router.push({name: 'userHome'})`

http://jsfiddle.net/Linusborg/eo9a14ck/5/

This is a bit inconsistent behaviour, but hard to change with the current way of things in the source.

Using the child route's name solves this.

**Comment by imageslr** [comment]
Thank you！
