### ISSUE TITLE
Russian docs is not up-to-date with repo translated version

### ISSUE THREAD

**Issue by totalamd** [vuejs/vue-router#1653]
### Version
2.7.0

### Reproduction link
[https://router.vuejs.org/ru/api/options.html](https://router.vuejs.org/ru/api/options.html)

### Steps to reproduce
https://router.vuejs.org/ru/api/options.html doesn't have 'fallback' section though it is in https://github.com/vuejs/vue-router/edit/dev/docs/ru/api/options.md

https://router.vuejs.org/ru/advanced/scroll-behavior.html doesn't have "2.6.0 " version mention either unlikely https://github.com/vuejs/vue-router/edit/dev/docs/ru/advanced/scroll-behavior.md

### What is expected?
'fallback' section

2.6.0  feature mention

### What is actually happening?
no 'fallback' section

no 2.6.0  feature mention

**Comment by Alex-Sokolov** [comment]
It seems that there was no publication after pull-request

**Comment by posva** [comment]
It should be now
