### ISSUE TITLE
Dynamic route with v-for

### ISSUE THREAD

**Issue by hiejulia** [vuejs/vue-router#1655]
### Version
2.7.0

### Reproduction link
[https://paste.ubuntu.com/25206858/](https://paste.ubuntu.com/25206858/)

### Steps to reproduce
I need to go the this page like this
https://paste.ubuntu.com/25206858/
How I can get the dynamic syntax to get the route params equal p.id?

### What is expected?
Route syntax with v-for

### What is actually happening?
I do not know how to do it

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

```
:to="`product/${p.id}``"
```
