### ISSUE TITLE
How to get a correct href right away [router.afterEach]

### ISSUE THREAD

**Issue by yingyuk** [vuejs/vue-router#1656]
### Version
2.7.0

### Reproduction link
[https://jsfiddle.net/6rzLab69/1/](https://jsfiddle.net/6rzLab69/1/)

### Steps to reproduce
click button

### What is expected?
after first click,
window.location.href is `https://fiddle.jshell.net/home?index=1`;

### What is actually happening?
after first click
but window.location.href is `https://fiddle.jshell.net/home`;

---
after first click   
router.query == { index: 1 };   
but window.location.href is `https://fiddle.jshell.net/home`;   
setTimeout output is `https://fiddle.jshell.net/home?index=1`   
Promise.resolve output is `https://fiddle.jshell.net/home?index=1`

**Comment by posva** [comment]
Dup of #1197

**Comment by sojuker** [comment]
meeting the same condition
