### ISSUE TITLE
What's the differences between components and component

### ISSUE THREAD

**Issue by Gcaufy** [vuejs/vue-router#1660]
### Version
2.7.0

### Reproduction link
[https://github.com/vuejs/vue-router/blob/dev/src/create-route-map.js#L74](https://github.com/vuejs/vue-router/blob/dev/src/create-route-map.js#L74)

### Steps to reproduce
I see the code here and I don't understand why we need components hehe. any reason for that?

### What is expected?
nothing

### What is actually happening?
nothing

**Comment by posva** [comment]
[named views](https://router.vuejs.org/en/essentials/named-views.html)

Please, next time ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
