### ISSUE TITLE
Router Object By Directory Structure

### ISSUE THREAD

**Issue by kardeepak** [vuejs/vue-router#1664]
### What problem does this feature solve?
Router creation according to directory structure.

### What does the proposed API look like?
We can create a utility that will create the router file according to the directory structure of our pages directory just like in Nuxt.Js but this will be for client-side rendering. This will make routing easy and we can also add custom routes if we want just like in Nuxt.Js.

**Comment by posva** [comment]
This is intentionally left out of vue-router so people can implement them as they want. You can use webpack to automatically require every view and create necessary route records for them
