### ISSUE TITLE
trouble passing data to prop in route with vue-cli setup

### ISSUE THREAD

**Issue by chancesmith** [vuejs/vue-router#1665]
### Version
2.7.0

### Reproduction link
[https://jsfiddle.net/chancesmith/vj3n55vs/3/](https://jsfiddle.net/chancesmith/vj3n55vs/3/)

### Steps to reproduce
Look at jsfiddle.

### What is expected?
Trying to pass root Vue instance data to route prop.

### What is actually happening?
Getting error that contact info is not in scope.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

`this` is just `window` there. In that very specific case, you can refer to `routerApp.contactInfo`
