### ISSUE TITLE
Navigating back should retain the scroll position.

### ISSUE THREAD

**Issue by krestaino** [vuejs/vue-router#1669]
### Version
2.7.0

### Reproduction link
[https://github.com/krestaino/nuepress](https://github.com/krestaino/nuepress)

### Steps to reproduce

1. Go to http://localhost:3000/
2. Scroll down and click on a post
3. After the new page loads, use the browser's back button
4. Scroll position goes to the top rather than where it was

### What is expected?
Navigating back should retain the scroll position.

### What is actually happening?
Navigating back does not retain the scroll position.

### Related Issues
https://github.com/nuxt/nuxt.js/issues/1036
https://github.com/vuejs/vue-router/issues/1373

https://github.com/nuxt/nuxt.js/issues/1182 (this issue on [nuxt/nuxt.js](https://github.com/nuxt/nuxt.js/issues/1182))

---
Is this a vue-router or Nuxt.js issue?

One thing I noticed, if I set the height of the HTML element to something like `html { min-height: 10000px }`, the issue goes away. Is this happening because the post list is being rendered dynamically using `v-for`?

**Comment by posva** [comment]
Please, check if this hasn't been reported already. It looks related to #1263
Next time, please make sure to provide a minimal repro using the fiddle of the vue issue helper, otherwise I won't be able to check it

**Comment by krestaino** [comment]
Yeah sorry, I figured out the issue is with Nuxt.js and it has nothing to do with vue-router. I've reported it over there.

I'll make sure to isolate the issue next time and apologizes for the inconvenience.
