### ISSUE TITLE
Spam v-link with transition-mode="out-in".

### ISSUE THREAD

**Issue by hellbeast92** [vuejs/vue-router#167]
Hello, i noticed if we start spam at different v-link links then sometimes <router-view> stop changed content, without error. Occurs only with transition-mode="out-in".

P.S. sry for my bad english.

**Comment by yyx990803** [comment]
This should be addressed by a fix in Vue core: https://github.com/yyx990803/vue/commit/c7cfd59aad80a3e539f89ad81590871dedf8d70e

It will be shipped soon in the next 1.0 alpha/beta release.

**Comment by AStaroverov** [comment]
It still repeats if i use vue transition system :(
No errors, but router view stays with *-leave class.

Vue@1.0.8, vue-router@0.7.6
