### ISSUE TITLE
missing param for named route "mysearchpackage": Expected "query" to be defined

### ISSUE THREAD

**Issue by bookc-man** [vuejs/vue-router#1671]
missing param for named route "mysearchpackage": Expected "query" to be defined

**Comment by bookc-man** [comment]
The meaning of this sentence is that in the use of "mysearchpackage" when the "query" this parameter assignment, the global search "mysearchpackage" this route to see if the use of the route when the parameter "query" assignment.

**Comment by MartinX3** [comment]
did you solve this issue?
