### ISSUE TITLE
v-on:click.native='doStuff' event fired before/after router $route watch event depending on browser

### ISSUE THREAD

**Issue by AndrewCocks** [vuejs/vue-router#1674]
### Version
2.7.0

### Reproduction link
[https://jsfiddle.net/yh65uhey/6/](https://jsfiddle.net/yh65uhey/6/)

### Steps to reproduce
1.  Create a router with watch to capture events and an onclick handler to do something.
2.  Click on the routes and observe different event sequence between browsers (Chrome, Edge vs Firefox, IE)

### What is expected?
All browsers fire events in same sequence (either route event first and then on-click event or vice-versa)

### What is actually happening?
on:click.native event fired after route event (Edge, Chrome)
on:click.native event fired before route event (Firefox, IE11)

---
Workaround available for Edge/Chrome to control route/on-click event sequence.  Unable to find similar for Firefox/IE - they always fire the click event first.

**Comment by posva** [comment]
I'm unsure if there's something we can do because browser behaviour around scheduling is what leads to this inconsistency.

Isn't `afterRouteLeave` what you actually need?

**Comment by AndrewCocks** [comment]
I have a viable workaround using SPAN as I need the click before the route changes, I was hoping the framework would insulate me from browser differences.  It is possible that someone else would require afterRouteLeave.  Could the framework take the on-click action during compilation and push it into beforeRouteLeave or afterRouteLeave and generate consistent cross-browser behavior?

**Comment by posva** [comment]
> Could the framework take the on-click action during compilation and push it into beforeRouteLeave or afterRouteLeave and generate consistent cross-browser behavior?

Unfortunately, that's would rather be a hack, more than a fix 😅 

> I was hoping the framework would insulate me from browser differences

We try to, but sometimes the complication of the codebase is too much for something that can already be handled in another way or is simply not possible at all 😞

**Comment by posva** [comment]
Closing since it's related to browser inconsistency and this would be really hard to fix in vue-router code
If you're relying on click order to do things, better do everything in the click by calling `$router.push()` and not using a router-link (but you loose href attribute) or use a different mouse event that always fires before or after click
