### ISSUE TITLE
Unify `next()` for `beforeRouteUpdate ` and `beforeRouteEnter `

### ISSUE THREAD

**Issue by zatziky** [vuejs/vue-router#1676]
### What problem does this feature solve?
Hi there,

it would make our code base simpler if we received `vm` in `beforeRouteUpdate` too even though this method already has access to `this`. Then if the same logic applies for `beforeRouteUpdate` and `beforeRouteEnter`  it could be handled uniformly in one method only:

```
beforeRouteUpdate(to, from, next){
   handleRouteChange(to, from, next)
},

beforeRouteEnter(to, from, next){
   handleRouteChange(to, from, next)
}
```

Yes, sometimes you need to handle both the methods in a different way but if not this is a nice short cut. Is it possible to do it in Vue.js or not?

Kind regards,

Nobo

**Comment by posva** [comment]
dup of #1582

**Comment by LinusBorg** [comment]
Reopening for further discussion following https://github.com/vuejs/vue-router/issues/1582#issuecomment-325031283
