### ISSUE TITLE
Support for inheriting attrs in router-link tag

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs/vue-router#1678]
### What problem does this feature solve?
router-link can render a specified tag which could happen to be a component. This component could have its own props but currently there is no way to pass them down. Eg.

```
// the primary prop will not be passed down to my-button
<router-link tag="my-button" primary></router-link>
```

Unless I am missing something I would like to request a way to solve this situation.

**Comment by yyx990803** [comment]
Implemented in 2.8+

**Comment by maksnester** [comment]
It doesn't work in 3.0.1. Component seems to be rendered but props isn't passed to it. Props are applied to target html element, but it's not the same as pass it to component before render.

**Comment by miljan-aleksic** [comment]
It should be definitely solved once https://github.com/vuejs/vue-router/pull/2029 is merged.
