### ISSUE TITLE
Allow v-link to not redirect

### ISSUE THREAD

**Issue by fnlctrl** [vuejs/vue-router#168]
Consider this:
```html
<foo v-if="redirect" v-link="{{ theLink }}"></foo>
<foo v-if="!redirect"></foo>
```

Wouldn't it be better if we can write something like:
```js
computed: {
  theLink: function() {
     if (this.redirect) {
       return {path:'somepath'}
     } else {
       return false
     }
  }
}
```
and when v-link="false" it will not redirect?

**Comment by yyx990803** [comment]
`<foo v-link="redirect ? link : null">`

**Comment by fnlctrl** [comment]
Using 0.6.2,
If v-link is set to null, this will happen:

Uncaught TypeError: Cannot read property 'replace' of null
update	@	bundle.js:22328

 update: function update(path) {
	      var router = this.vm.$route.router;
	      this.replace = typeof path === 'object' ? path~~.replace : false;~~
                                                                                        ^

**Comment by fnlctrl** [comment]
opened a new issue in  #172
