### ISSUE TITLE
router-link does not show href tags

### ISSUE THREAD

**Issue by samayo** [vuejs/vue-router#1683]
### Version
2.7.0

### Reproduction link
[https://jsfiddle.net/zysj2meg/2/](https://jsfiddle.net/zysj2meg/2/)

### Steps to reproduce
install vue via vue-cli

### What is expected?
vue init webpack-simple vue
cd vue
npm install
npm install --save vue-router
npm run dev
-- create routes, and add router-link inside html

### What is actually happening?
The routes show but without anchor tag (a)

**Comment by posva** [comment]
You used `tag="li"` to change the tag purposely, so it's normal that you get `li` instead with no href.
