### ISSUE TITLE
Dynamic components

### ISSUE THREAD

**Issue by tremendus** [vuejs/vue-router#169]
In vue-router, url drives the view with drives component selection at some level in the routes map. 

However, I haven't seen a way to **dynamically** specify the component using the route params. 

```
'contacts/:tab': {
    component: require('components/contacts/tabs/' + <tab> + '.vue') 
```

.. where the tab is a route param, but then is used within the route map to set the component dynamically. 

Has this been considered or discussed?

**Comment by yyx990803** [comment]
There's no support for this, but you can just use a container component to do that:

``` html
<div>
  <component :is="$route.params.tab"></component>
</div>
```

**Comment by tremendus** [comment]
Ok, but it's not the same ... follow me here if you will. 

As you suggest, consider: 

```
// routes.js
module.exports = {
	'vue/:subvue': {
		name: 'vue/subvue',
		component: require('../development/vues/vue.vue')
	}
}
```
```
// vue.vue
<script>
module.exports = {
	components: {
		'subvue1': require('./subvue1.vue')
	},
	route: {
		data: function () {
			console.log('vue:data()') // outputs as expected
		}
	}
}
</script>

<template lang="jade">
#vue-vue
	h1 vue.vue
	component(is="{{$route.params.subvue}}")
	debug(debug="{{$route.params}}", label="params")
</template>
```
```
// subvue1.vue
<script>
console.log('subvue1.vue')
module.exports = {
	route: {
		data: function () {
			console.log('subvue1:data()') // nothing output, hook not called
		}
	}
}
</script>

<template lang="jade">
#vue-subvue
	h2 subvue1.vue
</template>
```
The dynamic component displays (eg h2 present) but it's data hook isn't called, nothing in console for that statement. 

So either you have to pass the data from the parents routed component (therefore coupling it) or you have to retrieve data from alternate hook (eg compiled()), making that inconsistent method of getting data, depending on whether that component is routed or not. 

Perhaps there is a reason for not calling the data hook on a non-routed component (performance?) I'm not sure. But what's your suggestion Evan for handling use case such as this?

**Comment by yyx990803** [comment]
You should pass the data down with props. The coupling is inevitable, the child component needs **some way** to get the data anyway.
