### ISSUE TITLE
router.push() doesn't update query when provided name route doesn't change

### ISSUE THREAD

**Issue by posva** [vuejs/vue-router#1690]
> from #1182 @kvdmolen

### Version
2.7.0

### Reproduction link
[http://jsfiddle.net/ub9e33fm/12](http://jsfiddle.net/ub9e33fm/12)

### Steps to reproduce
1. Click first link (?q=foo)
2. Click second link (?=foo,bar)

### What is expected?
$route.query should update

### What is actually happening?
It only updates after another navigation

**Comment by anishdcruz** [comment]
I can confirm this issue. Is there any hack to fix this issue?

**Comment by lbineau** [comment]
Same here, it is annoying because I would want to use query to filter an array.

**Comment by Ashishdce** [comment]
Same issue, can't update query dynamically for the same route. Query object is getting updated, but it's not showing up in the route.

**Comment by fnlctrl** [comment]
Quick workaround: Use a fresh array (`this.arr.slice()`) when using `.push()`
http://jsfiddle.net/ydwmmum6/

**Comment by anishdcruz** [comment]
@fnlctrl Here is the example issue.

### Version

"vue": "^2.4.2",
"vue-router": "^2.7.0"

### Reproduction link

https://jsfiddle.net/ydwmmum6/2/

### Steps to reproduce

1. type random text in input field and hit search

### What is expected?

$route.query should update

### What is actually happening?

input field gets the value from the previous $route.query

**Comment by posva** [comment]
Actually, I don't know why I marked this as a bug... If the array is the same, it's normal for the router not being able to tell it's a different location. To fix it we could compare the JSON representation (which could be very slow) or copy the arrays in queries which can also be slow.
