### ISSUE TITLE
"router-link-active" class is unfriendly with navbar

### ISSUE THREAD

**Issue by fy0** [vuejs/vue-router#1691]
### What problem does this feature solve?
There are many question about home link \(\<router-link to="/">\) always had the "router-link-active" css class.

And the answer always is use exact.

But think about that situation: we have a "topics" nav button, and two paths with one link
```
/
/page/1
```

```html
<router-link :to="{ path: '/' }" >Topics</router-link>
```

Now "router-link-active" will be always actived, looks bad. OK, use the model answer "exact".

```html
<router-link :to="{ path: '/' }" exact>Topics</router-link>
```

It works fine when path is "/", but not work with path "/page/1"

### What does the proposed API look like?
Actually we can use some trick to avoid show wrong highlight style, but I prefer to see vue-router itself works better on it.

BTW: redirect "/" is a solution, but not prefect.

**I think add active class with name is a solution:**
```html
<router-link :to="{ name: 'topics' }" >Topics</router-link>
```
Seems active determined by the route's path, whether the route active or not. (version 2.5.3).

**Another way is add a new prop, for example:**
```html
<router-link :to="{ name: 'topics' }" show-active-if-match="/(^\/$)|(\/page\/(\d+))/">Topics</router-link>
```
Developers use a regex to match url if they want to handle the class.

**The third way (the best i thought):**
```html
<router-link :to="{ name: 'topics' }" :active-when="['topic-list', 'topic']">Topics</router-link>
```

```js
for (let i of active_when) {
    if ($route.name == i) return true;
}
```

**Comment by LinusBorg** [comment]
I don't understand your problem description. 

Why should a link to '/' match both '/' and '/page/1'?

**Comment by fy0** [comment]
@LinusBorg  The problem is  "router-link-active" class are unfriendly with navbar.
<img width="459" alt="snipaste_20170820_235214" src="https://user-images.githubusercontent.com/1579850/29496344-40d861c2-8603-11e7-8c79-dc14b53bfc5a.png">
<img width="459" alt="snipaste_20170820_235232" src="https://user-images.githubusercontent.com/1579850/29496345-410cb850-8603-11e7-9f5f-42026315a07a.png">

The link match one path, add "router-link-active" css class when match the [route](https://router.vuejs.org/en/api/options.html#routes) name (now it acitved if match the path of RouteConfig)

http://jsfiddle.net/xgrjzsup/3276/
It means text change to red only if $route.name equals to the name inside <router-link> element.

The second suggestion is that vue-router add "router-link-active" when $route.name match one of several names.

**Comment by posva** [comment]
The problem isn't clear to me either. If you could provide a simple jsfiddle showcasing the thing that bothers you, that would help
BTW, you can always manually bind the active class using your own condition

**Comment by fy0** [comment]
@posva  
There is current behavior:
http://jsfiddle.net/xgrjzsup/3277/

Here is what I want:
http://jsfiddle.net/xgrjzsup/3279/

Well, I can manually bind active classes regardless of css classes auto added by vue-router.
But I prefer to use \<route-link\> element to do that if i could.
Don't you think usage of "router-link-active" is very limited now?

**Comment by posva** [comment]
Using `exact` for the first `router-link` yields the same result you want (`<router-link :to="{name :'topic_list'}" exact>TopicList</router-link>`).

If what you want is to have both `/`  highlighted when on `/topics/1` but not on `/other-page`, you'll have to do something custom...

**Comment by fy0** [comment]
@posva 
This example is about why not use exact.
http://jsfiddle.net/k11c8wsc/1/

The problem is "router-link-active" usually need to be replaced by custom code.
I don't know the origin purpose of "router-link-active", but I think it's not very useful now.
So I ask for adding a \<router-link> attr/directive(or using name match instead of path match) to improve this situation.

**Comment by posva** [comment]
Usually, you have some kind of prefix for that kind of routes: `/items/:id`, and in that case, you won't need `exact`. I haven't analyzed your path `/:p(p)?/:page(\\d+)?` but TopicList should be highlighted when using `exact`

**Comment by fy0** [comment]
@posva 
The path looks strange because I want to make ```/``` and ```/p/1``` show the same page and use same RouteConfig, but it's not the point.

You can noticed in this case, *Topics* hightlighted when path is ```/```, ```/p/1``` or ```/topic/1```. Actually two routes named **topic_list** and **topic**.
Just like both ```/vuejs/vue-router/pull/1687``` and ```/vuejs/vue-router/pulls``` highlights the *Pull requests* button.
http://jsfiddle.net/xgrjzsup/3279/

**Comment by battlePlaze** [comment]
maybe  you say because of the version problem 1.0 and 2.0

**Comment by autobrain-stanley** [comment]
Seems that `/` matches all routes and setting the active class. When maybe it should be `*` that matches all. `/` matching all routes is frustrating when your integrating in to another backend that uses the root for a specific view. One other problem is that the search query is also taken in to consideration for matches which can be annoying if you want to persist a query string to another route but might not always be provided. 

https://codesandbox.io/s/kwl495v077
However I was able to circumvent the problems with `/` matching all routes by using redirects in the config to ensure nothing is on the root path.

**Comment by SavkaTaras** [comment]
> Using `exact` for the first `router-link` yields the same result you want (`<router-link :to="{name :'topic_list'}" exact>TopicList</router-link>`).
> 
> If what you want is to have both `/` highlighted when on `/topics/1` but not on `/other-page`, you'll have to do something custom...

Adding "exact at the end of router-link" fixed my issue!

<router-link :to="{name: 'home'}" exact>
Thanks a lot!

**Comment by fy0** [comment]
Emmmmmmmm, I remembered this issue was closed. The problem was solved to me for a long time.
