### ISSUE TITLE
Nested Named Views doesn't resolve

### ISSUE THREAD

**Issue by remoe** [vuejs/vue-router#1693]
### Version
2.7.0

### Reproduction link
[https://jsfiddle.net/3dman/j1oubLkL/](https://jsfiddle.net/3dman/j1oubLkL/)

### Steps to reproduce
Click the "click" link.

### What is expected?
It should display "baz"

### What is actually happening?
it doesn't display "baz"

---
I'm not sure it's a bug. When not, it's a feature request.

**Comment by posva** [comment]
Nested named views already work, but in your fiddle you're not nesting any route. The `components` option should be added in a child route
