### ISSUE TITLE
<router-link>dose not parse link with http

### ISSUE THREAD

**Issue by dongnaebi** [vuejs/vue-router#1694]
### What problem does this feature solve?
I want to jump a full link like 'https://www.a.com/b' (maybe it's an AD link),and '/b' is in my router,if I use `<a>` in history mode,the browser will be refresh,and if I use `<router-link>`

`<router-link to="https://www.a.com/b"></router-link>`

the render result is

 `<a href="/https://www.a.com/b"></a>`

why not inspect if link include 'http',don't parse it,that we can write a filter to resolve the full link:

if the link in same domain,filter it to path,e.g. https://www.a.com/b -> /b

if the link in different domain,don't filter it,e.g. https://www.b.com/b -> https://www.b.com/b

### What does the proposed API look like?
`<router-link to="https://www.a.com/b"></router-link>`

render to

`<a href="https://www.a.com/b"></a>`

**Comment by posva** [comment]
dup of #1280
