### ISSUE TITLE
why vue-router 2.7 - samsung mobile phones(Galaxy S III) in enforcing the hash pattern

### ISSUE THREAD

**Issue by toddywang** [vuejs/vue-router#1697]
### What problem does this feature solve?
my code is use histoty mode.
<-----
 let router = new Router({
    mode: 'history',
    routes: [
----->
but i think you use that some ua were filtered specifically?

Google Mobile Simulator
Mozilla/5.0 (Linux; U; Android 4.1; en-us; GT-N7100 Build/JRO03C) 
AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30

### What does the proposed API look like?
I want to use history mode in enforing.

**Comment by yyx990803** [comment]
If it falls back to hash mode it means the browser does not support history mode.

**Comment by pokkur** [comment]
How can I do swap router mode by the UA?
I want to use history mode on default.
but, only unsupported browser use hash mode.
