### ISSUE TITLE
vue-router how to fixed the third part add '&' in the end

### ISSUE THREAD

**Issue by dukegod** [vuejs/vue-router#1698]
### Version
2.3.0

### Reproduction link
[https://github.com/dukegod/vue-router/blob/dev/examples/route-matching/app.js](https://github.com/dukegod/vue-router/blob/dev/examples/route-matching/app.js)

### Steps to reproduce
open browser

### What is expected?
/optional?token=8989&wife=88&

i want to reserve the last "&" .

how to set my router

### What is actually happening?
in browser it wil render like 

/optional?token=8989&wife=88

**Comment by LinusBorg** [comment]
Why?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

I can't understand why either, but if what you wnat is the actual _&_ character, you can escape it with `encodeURIComponent` which gives you `%26` for `&`
