### ISSUE TITLE
Multiple view-router outlets

### ISSUE THREAD

**Issue by tremendus** [vuejs/vue-router#170]
Originally in an early release I thought I saw code and docs for multiple outlets. Has this been deprecated in favor of nested (only) structure? If not, has it been considered?

**Comment by yyx990803** [comment]
Yes, it's been deprecated because it makes it difficult to reason about route hooks. Imagine resolving the hooks for multiple components for the same route - it's pretty confusing. Similar to #169 , just use a container component.
