### ISSUE TITLE
BeforeRouteUpdate hook is not called again on navigation to original route

### ISSUE THREAD

**Issue by timvanoostrom** [vuejs/vue-router#1701]
### Version
2.7.0

### Reproduction link
[http://jsfiddle.net/uLg4qmpf/2/](http://jsfiddle.net/uLg4qmpf/2/)

### Steps to reproduce
1. Enter route with /app/1
2. Navigate to /app/2 (beforeRouteUpdate is called with id: 2)
3. Navigate to /app/3 (beforeRouteUpdate is called with id: 3)
4. Click browser back button (beforeRouteUpdate is called with id: 2)
5. Click browser back button (beforeRouteUpdate is not called when navigating to route we've entered the app on)

### What is expected?
beforeRouteUpdate is always called when the params change

### What is actually happening?
beforeRouteUpdate is not called when navigating to original route

---
Maybe it's designed like this, I don't know.

**Comment by posva** [comment]
This is working as expected. Keep in mind the app start at a different route not at `/app/1`, so when going back, at that point it will get go to a **different** route

**Comment by timvanoostrom** [comment]
I don't understand you. Why can't my app start at /app/1 ? Maybe in the fiddle it doesn't start at /app/1 but in a real world scenario I can definitely share a URL with these params

**Comment by timvanoostrom** [comment]
So if I understand correctly the vue-router only considers something an update when it's different from the original state, not different from the updated state* (e.g a new url param) ?

* state being the url here

**Comment by LinusBorg** [comment]
No, your real problem is that you pass a callback to `next` in `beforeRouteUpdate`, but that only works in `beforeRouteEnter`.

in beforeRouteUpdate, you have access to this, so that callback "workaround" we have to use in `beforeRouteEnter` is not necessary.

I am however a bit shocked about the lack of options.

**Comment by timvanoostrom** [comment]
Argh, I've mentioned the wrong fiddle damnit... this is the one I meant to post here: http://jsfiddle.net/uLg4qmpf/2/ @posva please recheck

**Comment by LinusBorg** [comment]
Works well for me.

![image](https://user-images.githubusercontent.com/1444526/29672028-6c1af85a-88eb-11e7-91e0-fc68bf763920.png)

**Comment by timvanoostrom** [comment]
@LinusBorg did you enter the fiddle with /#/app/1 in the url? I can't figure out how that works with jsFiddle.

This: http://jsfiddle.net/uLg4qmpf/2/#/app/1 doesn't work but it's needed for the scenario.

**Comment by LinusBorg** [comment]
then we need a small respository to clone

**Comment by timvanoostrom** [comment]
Nvm, I've discovered the flaw in my app code. I wasn't calling ```next()``` in the ```beforeRouteUpdate``` hook. The URL changed however but not calling ```next()``` didn't reflect the url state in my app, effectively making the router out of sync
