### ISSUE TITLE
Push query or params cannot change the URL

### ISSUE THREAD

**Issue by shabai517** [vuejs/vue-router#1703]
## About push query:

1.  The current URL is "/foo?a=1"
2. This.$router.push({path: '/foo', query: { a: 2}});
3. The data will be changed in the "beforeRouteUpdate", but the URL does not change. (The proper URL should be "/foo?a=2", but it is still "/foo?a=1")

## Replace params in nested router
1. In the nested router: (The current URL is  '/foo/:a/b/:c')
```js
{
      path:'/foo/:a',
      name: 'foo',
      component: foo,
      children:[
          {
            path:'b/:c',
            component: foo,
          }
      ]
},
```
2. No matter we use any method to push router, the URL will not change. For example:
this.$router.push("/foo/a/b/d"); The URL is still "/foo/a/b/c"

I think these two problems are the same bugs: the nested params or query in the URL not changes when push to the CURRENT URL . 

_But the pushed data can be fetched in the "beforeRouteUpdate", the only problem is the URL does not changed._

- The non-nested params works fine and we can use the "beforeRouteUpdate" to fetch the new params
- If we push to another URL, it will work fine

**Comment by LinusBorg** [comment]
You likely just forgot to call `next()` in `beforeRouteUpdate`

**Comment by shabai517** [comment]
Wow...I am so careless and spend a lot of time doing test...Thank you so so much! @LinusBorg

**Comment by Invizible** [comment]
@LinusBorg, Big thanks from 2018 ! :)

**Comment by poulerik-dk** [comment]
@LinusBorg, Big thanks from 2019 ! :)

**Comment by nicodevs** [comment]
@LinusBorg You're the man :smile:
