### ISSUE TITLE
$route.fullPath does return path without the hash in hash mode

### ISSUE THREAD

**Issue by apollo7321** [vuejs/vue-router#1708]
### Version
2.7.0

### Reproduction link
[https://codepen.io/Ctwx/pen/xLypva?editors=1010#](https://codepen.io/Ctwx/pen/xLypva?editors=1010#)

### Steps to reproduce
For some reason it does not fills $router.hash with the # sign, although I am using the default mode.

### What is expected?
To print the full url with hash and query string', according to https://router.vuejs.org/en/api/route-object.html

### What is actually happening?
It just prints '/'

**Comment by posva** [comment]
Adding `router.push('/#sign')` in your code does yield `'/#sign'`
I suggest you to seek help on the [forum](http://forum.vuejs.org/) or on the [Discord server](https://vue-land.js.org/). Come back if you find out there's actually a bug and provide a repro
