### ISSUE TITLE
Skip component destruction on route change

### ISSUE THREAD

**Issue by vhmolinar** [vuejs/vue-router#1712]
### What problem does this feature solve?
Vue-router is taking too much time to change the route after leaving a page with a huge set of components loaded and rendered.
In fact, I realized that vue-router waits for the component(current page) destruction before calling the next route's component.

### What does the proposed API look like?
I need to skip component destruction on route change, because in case I have a huge set of components loaded and rendered in a specific route I wouldnt want to wait until next page is finally opened.

**Comment by posva** [comment]
This is more likely to come from your page/components than vue-router. A component destruction shouldn't take much time, so I'd suggest you to ask for help on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

You could also use `keep-alive` to prevent the component from being destroyed and created when it gets out of view
