### ISSUE TITLE
TS2345 Error with RouterOptions

### ISSUE THREAD

**Issue by gring2** [vuejs/vue-router#1714]
### Version
2.7.0

### Reproduction link
[https://github.com/gring2/followingegghead.io](https://github.com/gring2/followingegghead.io)

### Steps to reproduce
my tsc version is 2.3 and vue-router via npm

### What is expected?
```
import Vue, { ComponentOptions } from 'vue'
import Router from 'vue-router'
import Hello from '@/components/Hello.vue'

Vue.use(Router)

export default new Router({
  routes: [
    {
      path: '/',
      name: 'Hello',
      component: Hello
    }
  ]
})
```

-------Hello.vue--------
```
<script lang="ts">
  import Parent from './Parent'
  import Component from 'vue-class-component'

  @Component
  export default class Hello extends Parent {
//    message:string = 'hello Vue'
    created(){
      console.log('child created')
    }


    clicked() {
      console.log('clicked')
    }

    beforeRouteEnter(to, from, next){
      console.log('Enter')
      next()
    }
  }
```

### What is actually happening?
TS2345 Error ... is not assignable to parameter of type 'RouterOptions'

---
i am following egghead.io but unlike the video my code make TS2345 error on vue-router

**Comment by ktsn** [comment]
Looks like the same problem as https://github.com/vuejs/vue-class-component/issues/123
`vue-shim.d.ts` is needed to update like following in the latest TS compiler (remove typeof):

```ts
declare module "*.vue" {
  import Vue from 'vue';
  export default Vue;
}
```

Would you mind report to egghead (or the template author) to update `vue-shim.d.ts`?

**Comment by gring2** [comment]
thank you for your help!! i will report this issue to egghead.io
