### ISSUE TITLE
IE9 history mode jump wrong url 

### ISSUE THREAD

**Issue by wjhcc2018** [vuejs/vue-router#1715]
### Version
2.7.0
### Steps to reproduce
use history mode,open the url in chrome,you can open the website well,but copy the url to the IE9 browser,it's jump a wrong url,and you can't open the website

### What is expected?
i expected that it's can  change to the hash mode currectly,and jump a right url

### What is actually happening?
i have a url like this：
in history mode: https://e.qianfan578.com/wxm/toLogin
but ,copy this url to ie9,it's jump to https://e.qianfan578.com/#/wxm/toLogin
and it's does't open，
but use hash mode  in ie9,it's jump to https://e.qianfan578.com/wxm/toLogin/#/wxm/toLogin（right）

**Comment by posva** [comment]
IE9 doesn't support HTML5 history mode, so you should use hash mode if you want to support IE9

**Comment by wjhcc2018** [comment]
@posva thanks for  answer my question and i konw that IE9 doesn't support HTML5 history mode and i can see if i use history mode in IE9,it's can change to the hash mode by it's self,but why the url different with i use the hash mode

**Comment by JounQin** [comment]
As I know, it is as expected.

When it fallback to hash mode on IE9, it will change url according to `base` option which is default as `/`.
https://github.com/vuejs/vue-router/blob/dev/src/history/hash.js#L61-L69

Besides, you should provide a reproduction at least.

**Comment by wjhcc2018** [comment]
@JounQin  thank you very much i need  to  check my route config again
