### ISSUE TITLE
Nested routes JS Fiddle example doesn't work in Safari (docs)

### ISSUE THREAD

**Issue by bsaf** [vuejs/vue-router#1716]
### Version
2.7.0

### Reproduction link
[http://jsfiddle.net/yyx990803/L7hscd8h/](http://jsfiddle.net/yyx990803/L7hscd8h/)

### Steps to reproduce
1. Visit [this page](https://router.vuejs.org/en/essentials/nested-routes.html) of the docs using **Safari 10**
2. Click the link to the JS Fiddle at the bottom of the page

### What is expected?
Demo router links should be active and clickable

### What is actually happening?
They are not active. There is a console error "Can't create duplicate variable that shadows a global property"

---
This is due to [this webkit bug](https://bugs.webkit.org/show_bug.cgi?id=159270) and can be worked around by changing the final `const app = ` declaration to `var app =`.

**Comment by posva** [comment]
Thanks for reporting it, it looks like the fiddle demo works if we just use Javascript instead of babel + jsx as well
@yyx990803 Could you update the fiddle by either removing the `const app =` or changing the `const` into a `var` to make it work on Safari

**Comment by posva** [comment]
Since this was fixed I think it's fine to keep the example like that
