### ISSUE TITLE
v-link issue on 0.6.2

### ISSUE THREAD

**Issue by fnlctrl** [vuejs/vue-router#172]
1.When v-link's value is truly `null`, for example v-link="true ? null : null"
It will cause:
```
Uncaught TypeError: Cannot read property 'replace' of null
```
source code that caused error:
```javascript
update: function update(path) {
var router = this.vm.$route.router;
this.replace = typeof path === 'object' ? path.replace : false;
```

2.When v-link="null", it will redirect to /undefined

**Comment by yyx990803** [comment]
Thanks, this is already fixed in `dev`, will be out in next release.
