### ISSUE TITLE
One of queries is undefined and watch $route will fire twice

### ISSUE THREAD

**Issue by webrsb** [vuejs/vue-router#1722]
### Version
2.0.1  or higher

### Reproduction link
[http://jsfiddle.net/xvs5euab/2/](http://jsfiddle.net/xvs5euab/2/)

### Steps to reproduce
Click first link (foo_undefined)

### What is expected?
Same as next link "foo_bar", just show alarm only one time

### What is actually happening?
It show alarm two times

**Comment by posva** [comment]
Once #1568 is merged, you can use null, but I really think you shouldn't use `undefined` as your query values. For the moment, you can delete them or simply not include them. I'm marking this as an improvement but I really recommend you to not include query's parameters that are undefined, it better to remove them

**Comment by webrsb** [comment]
Thanks for providing advice. In some case,  query's parameters may be removed by user from URL that I can't prevent it.

**Comment by webrsb** [comment]
Thanks for providing advice. In some case,  query's parameters may be removed by user from URL that I can't prevent it.

**Comment by posva** [comment]
If the property is not in the query it won't trigger the watcher twice. The reason it happens twice right now is because the query gets normalized

**Comment by leeci** [comment]
You're correct 👍 . It only trigger once if manual remove from URL.

**Comment by posva** [comment]
Note: Would be good to prevent normalization from triggering the navigation twice
