### ISSUE TITLE
if router query have null or undefined value, will throw error

### ISSUE THREAD

**Issue by svkd9** [vuejs/vue-router#1725]
### Version
2.7.0

### Reproduction link
[https://github.com/vuejs/vue-router/blob/v2.7.0/src/util/route.js#L86](https://github.com/vuejs/vue-router/blob/v2.7.0/src/util/route.js#L86)

### Steps to reproduce
const routerQuery =  {
    a:  null,
    b:  undefined
}
this.$router.push({name: 'routerName', query: routerQuery})

### What is expected?
no error 

### What is actually happening?
throw error 'Cannot convert undefined or null to object'

---
i think the problem maybe in https://github.com/vuejs/vue-router/blob/v2.7.0/src/util/route.js#L86

typeof aVal === 'object'   ====>  Object.prototype.toString.call(aVal) === '[object Object]'

**Comment by posva** [comment]
Dup of some other issue, PR to fix this at #1568
