### ISSUE TITLE
Scroll to top on route change issue on iOS

### ISSUE THREAD

**Issue by oleynikd** [vuejs/vue-router#173]
I'm building web app with Vue and have some strong behavior on iOS (Safari).
When route changes Safari won't scroll to top of the page (everything's fine on other platforms/browsers)

Has someone faced such problems?

Thanks.

**Comment by yyx990803** [comment]
The router doesn't automatically scroll to top when the route changes. You can do that in a global before hook though:

``` js
router.beforeEach(function (transition) {
  window.scrollTo(0, 0)
  transition.next()
})
```

**Comment by wonderbeyond** [comment]
Any elegant way to solve this problem?

**Comment by oleynikd** [comment]
Solution @yyx990803 proposed is pretty elegant... Why you don't like it?

**Comment by wonderbeyond** [comment]
Just first impression, I think it's OK now 😀
Thanks for your post.

**Comment by dung13890** [comment]
thanks! @yyx990803, i also have this problem.

**Comment by asantibanez** [comment]
Is this available in vue-router@next?

I managed to use this per component

``` javascript
export default{
        data(){
            return {}
        },

        created() {
            //Scrolls to top when view is displayed
            window.scrollTo(0, 0);
        }
    }
```

But wondering if it is a router configuration

**Comment by fnlctrl** [comment]
@asantibanez Checkout scrollBehavior https://github.com/vuejs/vue-router/releases

**Comment by pajtai** [comment]
Looks like the arguments for `beforeEach` are now `to, from, next` instead of just `transition`. 

https://router.vuejs.org/en/advanced/navigation-guards.html#global-guards

@yyx990803's example would now be:

```
router.beforeEach(function (to, from, next) {
  window.scrollTo(0, 0)
  next();
})
```

**Comment by panayotoff** [comment]
Setting global `scrollBehavior` to the router works fine for me, but is there any elegant solution to animate the scrolling of the window **within** vue-router. I can set my animation in **router.beforeEach** function, but was just wondering...

**Comment by lukepolo** [comment]
@panayotov  

Use this 

```
        scrollToTop: function (scrollDuration) {
                var cosParameter = window.scrollY / 2,
                    scrollCount = 0,
                    oldTimestamp = performance.now();

                function step(newTimestamp) {
                    scrollCount += Math.PI / (scrollDuration / (newTimestamp - oldTimestamp));
                    if (scrollCount >= Math.PI) window.scrollTo(0, 0);
                    if (window.scrollY === 0) return;
                    window.scrollTo(0, Math.round(cosParameter + cosParameter * Math.cos(scrollCount)));
                    oldTimestamp = newTimestamp;
                    window.requestAnimationFrame(step);
                }

                window.requestAnimationFrame(step);
            }
```

https://stackoverflow.com/questions/21474678/scrolltop-animation-without-jquery

**Comment by jesong** [comment]
The fix would scroll current page to top then do the route. That's not what people want if they have route animation.

**Comment by lukepolo** [comment]
@jesong you can do it with your http client it you can add interceptors, while not pretty its doable. 

```
axios.interceptors.response.use(function (response) {
    // Do something with response data
    return response;
  }, function (error) {
    // Do something with response error
    return Promise.reject(error);
  });
```

**Comment by crobertsbmw** [comment]
@pajtai - Stupid question here. Where do I add that customization? I have a webpack application with my main.js as : 

```import Vue from 'vue'
import Vuetify from 'vuetify'
import App from './App'
import router from './router'

Vue.use(Vuetify)
Vue.config.productionTip = false

new Vue({
  el: '#app',
  router,
  render: h => h(App)
})
```
I tried inserting into my main.js before the `new Vue` bit, but it didn't work.

**Comment by kallebornemark** [comment]
Just wanted to piggyback @jesong's comment and (re?)highlight this problem. Using beforeEach to scroll causes the page to scroll before any route animation is made, which doesn't look too good.

**Comment by iamaaron** [comment]
For those that want to apply the animation after the route has changed, or doesn't want that odd flicker of the view when using the `scrollTop` in a `beforeEach`. You are always welcome to use the `afterEach` hook provided by the router.

```
router.afterEach(() => {
  window.scrollTo(0, 0);
});
```

Reference: https://router.vuejs.org/en/api/router-instance.html

**Comment by edarioq** [comment]
This is better (scrollBehavior):

```
export default new Router({
  scrollBehavior() {
    return { x: 0, y: 0 };
  },
  routes: [
    {
      path: '/',
      name: 'Home',
      component: Home
    }
  ],
  mode: 'history'
});
```

See https://router.vuejs.org/guide/advanced/scroll-behavior.html#async-scrolling

**Comment by IamCharmaineJoy** [comment]
@yyx990803 thanks it worked for me.

**Comment by IsmoPismo** [comment]
@edarioq 
I had an ugly jump to the top of the current page before leaving.
I put the window.scrollTo(x, y) in the beforeCreate() hook and it worked

**Comment by ImSandeepMishra** [comment]
> This is better (scrollBehavior):
> 
> ```
> export default new Router({
>   scrollBehavior() {
>     return { x: 0, y: 0 };
>   },
>   routes: [
>     {
>       path: '/',
>       name: 'Home',
>       component: Home
>     }
>   ],
>   mode: 'history'
> });
> ```
> 
> See https://router.vuejs.org/guide/advanced/scroll-behavior.html#async-scrolling

Thank you for the solution. This is working for my project.
