### ISSUE TITLE
this.$route.fullPath etc not set on async route refresh

### ISSUE THREAD

**Issue by benperiton** [vuejs/vue-router#1730]
### Version
2.7.0

### Reproduction link
[https://github.com/benperiton/vue-router-issue](https://github.com/benperiton/vue-router-issue)

### Steps to reproduce
Clone the repo listed and install, then run yarn run dev.

Click to navigate to the users page.
Refresh the page and observe the console log.

Click the 'update' button and see that the correct values are set.

### What is expected?
That the this.$route.path and this.$route.fullPath properties are populated correctly

### What is actually happening?
They are set to '/' until the component requesting them is updated.

---
It seems that the route must be known for it to know which component to load, so populating the path details should be available from the beginning.

**Comment by Doeke** [comment]
Tested in beforeEach handler, initial `from` always has fullPath "/" regardless of url, so it matches the incorrect route. This also breaks my social logins.

Version 2.7.0, history mode on (code was working before I upgraded)

**Comment by Juli0GT** [comment]
I'm having the same issue!

**Comment by Doeke** [comment]
Downgrading vue-router to 2.6, 2.5.3, does not seem to fix it for me...

Could it be caused by a change in the way Vue.js initiates vue-router?
I'm using Vue 2.4.2. I will have to continue investigating some other time.

**Comment by Doeke** [comment]
Changing vue-router version didn't work (?) so I'm using a work-around for now.

```
router.beforeEach(async (to, from, next) => {
  let actualPath = location.pathname + location.search + location.hash;
  if (actualPath != from.fullPath && actualPath != to.fullPath) {
    return next(actualPath)
  }
  next()
})
```

**Comment by posva** [comment]
See #1784 comment for explanation and reliable solution
@Doeke That could be another issue, would you mind sharing it using this fiddle as a base: http://jsfiddle.net/posva/9r6xhqbp/ (you can simulate async with a simple promise)

**Comment by Doeke** [comment]
@posva, forgot to mention, my issue turned out to be caused by vuex-router-sync, removing it fixed my problem.
