### ISSUE TITLE
Bug. Using path aliases with pathToRegexpOptions

### ISSUE THREAD

**Issue by o-alexandrov** [vuejs/vue-router#1736]
### Version
2.7.0

### Reproduction link
[https://github.com/OlzhasAlexandrov/vue-router-bug-aliases](https://github.com/OlzhasAlexandrov/vue-router-bug-aliases)

### Steps to reproduce
1. run `npm run dev`

### What is expected?
2. you are now able to check that the following will all load the `First` component:
  - `localhost:8080/some/cat/`
  - `localhost:8080/some/cat/cat/`
  - `localhost:8080/some/cat/cat/cat/`
3. whereas the following will load the `Second` component:
  - `localhost:8080/some/cat/second`
  - `localhost:8080/some/cat/cat/second`
  - `localhost:8080/some/cat/cat/cat/second`

### What is actually happening?
4. Everything is great and `pathToRegexpOptions` seems to work properly, **however, when using aliases** setting it above the First Component with a strict option in `pathToRegexpOptions` to let the routes with the forward slash at the end to slip to the `First` component, it **now gives an error, see below:**

**Uncomment the prepared code in `router/index.js` to see that it stops working as intended after the first alias:**
  - `localhost:8080/some/cat/`
  - `localhost:8080/some/cat/cat/`
  - `localhost:8080/some/cat/cat/cat/` => **now it loads the SECOND component whereas it is supposed to load the First**

**Comment by posva** [comment]
Can you please move it to the fiddle: http://jsfiddle.net/posva/9r6xhqbp/ and simplify (two routes would be perfect 😄 ) it a bit and adding clickable links, I tried moving it to a fiddle but it shows warnings about duplicated routes so I wonder if that's the problem. Thanks!

**Comment by o-alexandrov** [comment]
@posva Thank you, but the problem occurs only when using < 2 routes deep.
For this particular case, I have decided to follow the guide and instead of setting `aliases` for the routes that require the same component, I explicitly [write down the `children` option](https://router.vuejs.org/en/essentials/nested-routes.html).

**Comment by posva** [comment]
Ok, glad you found a solution
