### ISSUE TITLE
[SSR]history mode use base option get 404

### ISSUE THREAD

**Issue by falstack** [vuejs/vue-router#1739]
### Version
2.7.0

### Reproduction link
[https://github.com/vuejs/vue-hackernews-2.0](https://github.com/vuejs/vue-hackernews-2.0)

### Steps to reproduce
1：clone `vue-hackernews-2.0` repo

2：npm install & npm run dev

3：add `base: '/anyPath'` to router/index.js

4：refresh browser

### What is expected?
show page

### What is actually happening?
404 | Page Not Found

**Comment by posva** [comment]
Add a route with a path value of `'*'`

**Comment by tengmaoqing** [comment]
@falstack  Has this problem been solved now？

**Comment by falstack** [comment]
@tengmaoqing sorry, it's a long time ago, i forgot it...

but, it's not a big deal, if you have some question, please show your route.js

this is my route.js, maybe resolve this bug

![image](https://user-images.githubusercontent.com/16357724/43770221-50616cf8-9a6e-11e8-9cbe-eadcbef23cef.png)

**Comment by tengmaoqing** [comment]
@falstack  ok，这种办法并不能很好的替代 options.base 的功能，比如push的时候，或者router-link 的to参数。而我的项目需要这些都很灵活， base 这个值可能会改变的。

**Comment by aiyadingya** [comment]
Why not fix this ?
