### ISSUE TITLE
$router.replace() don't replases History.replaceState()

### ISSUE THREAD

**Issue by evgencode** [vuejs/vue-router#1742]
### Version
2.7.0

### Reproduction link
[### Version
2.7.0

### Version
2.7.0

### Reproduction link
[https://github.com/evgencode/routerbug](https://github.com/evgencode/routerbug)

### Steps to reproduce
I have a component:
```
const Request = () =>  import('../components/request');
```
And router:
```
const router = new VueRouter({
    { path: '/request/edit/:id', name: 'requestEdit', component: Request }
})
```
in component:
```
created : function() {
    this.init(this.$route);
    setTimeout(() => {
        // go to other router page after 2 sec.
        this.$router.replace('/request/edit/'   200);
    }, 2000);
},
beforeRouteUpdate : function(to, from, next) {
    this.init(to);
},
```
I'm trying to run site.com/request/edit/100.

### What is expected?
Will mount component with id=100, after 2 second it will mount again with id=200
**_And url have to change to a new: /request/edit/200._**

### What is actually happening?
But this does not happen, the previos url  (/request/edit/100) remains in ULR bar.
I suspect that the function History.replaceState() does not execute in this case.

---
Why url doesn't change?
If i'm using

`<router-link to="/request/edit/200">...</router-link>`

 in Request component the URL also does not change. Do I have to execute history.replaceState() by hands?

**Comment by evgencode** [comment]
the history of references within the same component works wrong

**Comment by Dadibom** [comment]
you've got a syntax error.
this.$router.replace('/request/edit/'   200);
you need a plus between the string and 200

**Comment by posva** [comment]
I didn't even saw this issue when it came 😅 
The repro doesn't even exist now
