### ISSUE TITLE
Async components and TypeScript

### ISSUE THREAD

**Issue by rhyek** [vuejs/vue-router#1745]
### Version
2.7.0

### Reproduction link
[https://github.com/rhyek/aspnetmvccore-vuejs-boilerplate/blob/master/clients/web/src/router/index.ts#L13](https://github.com/rhyek/aspnetmvccore-vuejs-boilerplate/blob/master/clients/web/src/router/index.ts#L13)

### Steps to reproduce
Scaffolded a new project using `vue-cli` and the webpack template. I'm trying to convert it to TypeScript following https://github.com/vuejs/vue-class-component/tree/master/example. Finally, I'm trying to assign an async component (written using `vue-class-component`) to a route config definition.

### What is expected?
TypeScript should understand what I'm trying to do.

### What is actually happening?
TypeScript complains with the following:

```
[ts]
Argument of type '{ mode: "history"; routes: { path: string; component: () => Promise<typeof "*.vue">; }[]; }' is not assignable to parameter of type 'RouterOptions | undefined'.
  Type '{ mode: "history"; routes: { path: string; component: () => Promise<typeof "*.vue">; }[]; }' is not assignable to type 'RouterOptions'.
    Types of property 'routes' are incompatible.
      Type '{ path: string; component: () => Promise<typeof "*.vue">; }[]' is not assignable to type 'RouteConfig[] | undefined'.
        Type '{ path: string; component: () => Promise<typeof "*.vue">; }[]' is not assignable to type 'RouteConfig[]'.
          Type '{ path: string; component: () => Promise<typeof "*.vue">; }' is not assignable to type 'RouteConfig'.
            Types of property 'component' are incompatible.
              Type '() => Promise<typeof "*.vue">' is not assignable to type 'typeof Vue | ComponentOptions<Vue> | undefined'.
                Type '() => Promise<typeof "*.vue">' has no properties in common with type 'ComponentOptions<Vue>'.
```

**Comment by rhyek** [comment]
I can see the [`dev`](https://github.com/vuejs/vue-router/blob/dev/types/router.d.ts#L4) branch now defines `Component` as accepting `AsyncComponent` which is already included in `vue` 2.4.4.

When is this expected to be published?

Also, is that `sfc` definition ok? The error mentions `Promise<typeof "*.vue">` which seems like it would be a problem anyways.

**Comment by posva** [comment]
We will release it soon, don't worry, but please don't open issues to ask this kind of questions...
There's a PRs being worked on by @ktsn if you want to take a look

**Comment by rhyek** [comment]
Ok, sure. Any possibilities of publishing an interim release with just:
```js
import { ComponentOptions, PluginFunction, AsyncComponent } from "vue";

type Component = ComponentOptions<Vue> | typeof Vue | AsyncComponent;
```
The absence of this prevents use of documented functionality that is stable without TypeScript.

If this is not possible, then no worries. I am using a fork in the meantime.
