### ISSUE TITLE
Losing params open in new tab

### ISSUE THREAD

**Issue by SnooHD** [vuejs/vue-router#1746]
### Version
2.7.0

### Reproduction link
codepen / jsfiddle don't support open in new tab. But for the idea:
http://jsfiddle.net/yo62z2o5/

### Steps to reproduce
`ctrl   click` on a `router-link` with params.
or right click -> open in tab / open in window.

### What is expected?
The route opens in a new tab containing the params.

### What is actually happening?
the params are empty.

**Comment by posva** [comment]
You need to specify the param on the route defiintion `{ path: '/foo/:foo', name: 'foo', component: Foo }`

**Comment by SnooHD** [comment]
In my case i don't want to use url parameters.
The data being loaded on the page is private, and only accessible by the logged in user.
So because Vue creates a new instance when you open a new tab, to only way out for me seems to use localStorage.
