### ISSUE TITLE
how to add global query string to every route path

### ISSUE THREAD

**Issue by philoyou11** [vuejs/vue-router#1748]
### What problem does this feature solve?
I need a param to add on every route path， added after the "?". In the current vue-router version, I can not find a method to add the param, would you like to think about how to solve this kind of issue 

### What does the proposed API look like?
add to router instance config

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
