### ISSUE TITLE
Async components are only evaluated one time

### ISSUE THREAD

**Issue by genu** [vuejs/vue-router#1749]
### Version
2.7.0

### Reproduction link
[https://github.com/genu/vue-router-bug](https://github.com/genu/vue-router-bug)

### Steps to reproduce
Using the attached repo

1. Open Console
2. Click "Foo"
3. Console reads "Async loading component" and we see "Hello Foo"
4. Click "Bar"
5. We still still see "Hello Foo", but not console output

The steps can be reproduced by clicking "Bar" first with similar results

### What is expected?
I should see "Hello Bar" and another console output reading "Async loading component"

### What is actually happening?
The first async component that gets loaded gets loaded all the time for that route going forward. 

The component function is only called one time

**Comment by posva** [comment]
That's how it works, it calls the function only once and then caches the result. It wouldn't be very cool of it fetched the component every time, would it? 😌

**Comment by genu** [comment]
@posva Well, in the use case above, it would be cool if the component is fetched every time (Since its a different component every time).

Perhaps this is more of a feature request then? That is, to add an option to disable component caching for use cases as this.

**Comment by posva** [comment]
A route should always yield the same component. Fetching something should also always yield the same result. If you need different behaviour for some reason, it should be **inside** of the route component

**Comment by WhereJuly** [comment]
Let us take a well-spread use case for a general web site - a universal popup window component: header, main text, footer, close button. The constant here is the structure of the component. Hence constant markup. The variable part is the content of these parts.

Important notice: as this is a popoup, something that is not needed to be loaded at the site start I like even the markup of it beind AXAJ-loaded on demand i.e. when the user press the button, invoking the markup.

It is not needed to be loaded at the page sta

The component is the same: the component's markup returned from the server i
