### ISSUE TITLE
beforeRouteUpdate fire twice when query contain empty array []

### ISSUE THREAD

**Issue by newbeea** [vuejs/vue-router#1754]
### Version
2.7.0

### Reproduction link
[http://jsfiddle.net/a9v43732/](http://jsfiddle.net/a9v43732/)

### Steps to reproduce
go to foo
then click 'beforeRouteUpdate' button
beforeRouteUpdate fire twice when query contain empty array []

eg.
this.$router.push({query: {a: Math.random(), b: []}})
beforeRouteUpdate fire twice

this.$router.push({query: {a: Math.random(), b: [1]}})
beforeRouteUpdate fire once

### What is expected?
this.$router.push({query: {a: Math.random(), b: []}})
beforeRouteUpdate shoud fire once

### What is actually happening?
this.$router.push({query: {a: Math.random(), b: []}})
beforeRouteUpdate fire twice

**Comment by posva** [comment]
This is probably related to #1722 
The route object gets normalized and the array is stripped off, making the route change fire twice.
As a temporary workaround, you can remove empty arrays from query objects

**Comment by ghost** [comment]
@posva This also happens without sending any route parameters. Should i open new issue with example?

**Comment by posva** [comment]
if there isn't an open issue about it and you provide a boiled down repro, yes please!
