### ISSUE TITLE
Cannot use v-link from component as of 1.0.0-beta.4

### ISSUE THREAD

**Issue by scottbedard** [vuejs/vue-router#176]
As of Vue 1.0.0-beta.4, I cannot use v-link from a child component. I've set up a demonstration at [this repo](https://github.com/scottbedard/vue-router-break/blob/master/index.html)

`util.js:35 [vue-router] v-link can only be used inside a router-enabled app..`
`link.js:63 Uncaught TypeError: Cannot read property 'router' of undefined`

**Comment by jakobrosenberg** [comment]
Same issue here. <router-view></router-view> isn't working either.

**Comment by yyx990803** [comment]
This is a known issue, beta 4 compat release will be out later today.

**Comment by scottbedard** [comment]
@yyx990803 awesome, thanks for the quick response!

**Comment by yyx990803** [comment]
Should be fixed in 1.0.0-beta.4.

**Comment by mediafreakch** [comment]
It seems that it doesn't. I created the following jsFiddle and not only get problems resolving v-link, but also <router-view> itself: http://jsfiddle.net/9x3mxvj0/3/ (using vue 1.0.0-beta.4 & vue-router 0.7.0)

**Comment by mediafreakch** [comment]
I confirm that it works with 1.0.0-beta.4 and 0.7.0. Just make sure you register the router in Vue before you define any component with ```<router-view>``` in it. A jsFiddle to help: http://jsfiddle.net/9x3mxvj0/4/
