### ISSUE TITLE
Why replace '+' with space in query param?

### ISSUE THREAD

**Issue by 66beta** [vuejs/vue-router#1760]
### Version
2.7.0

### Reproduction link
[https://github.com/vuejs/vue-router/blob/dev/src/util/query.js#L48](https://github.com/vuejs/vue-router/blob/dev/src/util/query.js#L48)

### Steps to reproduce
http://******/***/?p=xxx+yyy

### What is expected?
```
route.query.p => 'xxx+yyy'
```

### What is actually happening?
```
route.query.p => 'xxx yyy'
```

---
Does this necessary？
src/util/query.js
line: 48
```
var parts = param.replace(/\ /g, ' ').split('=');
```

**Comment by callumacrae** [comment]
Your what is expected and what is actually happening sections both contain the same thing 🤔

**Comment by posva** [comment]
Because URL encoding normally replaces spaces with a plus sign or with `%20`

**Comment by eadio** [comment]
@66beta
Have you finally solved it? I have the same problem.

**Comment by callumacrae** [comment]
@eadio see @posva's comment above: it's intentional, not a bug

**Comment by mortenege** [comment]
If you would really like a '+' in the query string use %2B which will encode to '+' 
```eg. http://xxx/yyy?q=m%2Bu``` will be ```route.query.q => 'm+u'```

**Comment by yuniit** [comment]
I run to the same issue, Has anyone solved it yet?

**Comment by ebouchard91** [comment]
I run into the same issue too, are you sure it's a feature and not a bug ?
I was under the impression that it should work the other way around, as @posva said, URL encoding normally replaces spaces with a plus sign or %20, but URL encoding doesn't usually replace plus signs by space (I think it wouldn't make sense given it does precisely the opposite).
Am I missing something else here that would explain why this feature exists ?
