### ISSUE TITLE
beforeRouteEnter not always triggering next();

### ISSUE THREAD

**Issue by SnooHD** [vuejs/vue-router#1765]
### Version
2.7.0

### Reproduction
http://jsfiddle.net/mx0gLa80/

### Steps to reproduce
When using the `beforeRouteEnter` i call next() after my data is loaded.
This works fine on initial run, but when using history back/forward, the next() function sometimes doesn't run.

```
beforeRouteEnter (to, from, next) {
   console.log(next); //always called
   next(); //not always called
}
```

### What is expected?
next() call triggered, and new route is loaded

### What is actually happening?
new route never loads

**Comment by posva** [comment]
Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or Github repository containing a set of reproducible steps that can lead to the behaviour you described. Make sure to boil down the problem as much as possible. Thanks!

(you can use this http://jsfiddle.net/posva/9r6xhqbp/)

**Comment by SnooHD** [comment]
Yes ofcourse, sorry for that.
here it is:
http://jsfiddle.net/mx0gLa80/

**Comment by SnooHD** [comment]
I apologize, this is not a problem with `vue-router` but rather with the `WebFont` loader im using in the reproduction.
I doesnt re-trigger the `active` event if the fonts are already loaded.

I have fixed my issue by keeping track of the already loaded fonts and only recall `WebFont` if im reloading the component with new fonts.

Thanks for your time anyways :)<3
