### ISSUE TITLE
router.push & router.replace to return promise if callbacks are not provided

### ISSUE THREAD

**Issue by charles-mathieus-jomedia** [vuejs/vue-router#1769]
### What problem does this feature solve?
It would help preventing callback hell... Would be more consistent with vue js api... 

### What does the proposed API look like?
router.push('/new/url').then(() => doSomeCoolStuff())

**Comment by belmarca** [comment]
This seems to work fine if for example your component is expecting an event.

```
methods: {
  asyncRouterPush (route) {
    return new Promise(resolve => {
      resolve(this.$router.push({ path: route }))
    })
  },
  doSomething (myVar) {
    this.asyncRouterPush(myVar)
      .then(() => {
        this.$root.$emit('someEvent')
      })
  }
}
```

**Comment by adamreisnz** [comment]
Any progress on this? Seems a bit backwards in 2019 that we still have to use a callback API, and can't simply `await router.push()`.

**Comment by adamreisnz** [comment]
Here's a simple helper function in the mean time...

```js
/**
 * Async push method
 */
router.pushAsync = function(route) {
  return new Promise((resolve, reject) => {
    router.push(route, resolve, reject);
  });
};
```

**Comment by Mighty683** [comment]
I will try implement this issue.

**Comment by Mighty683** [comment]
The problem is `UnhandledPromiseRejectionWarning` if we dont implement `catch` for previous implementations.

`router.push` should throw error on route abort? Or should resolve with `undefined` on route abort?

https://github.com/vuejs/vue/blob/dev/src/core/util/next-tick.js should I implement this similar to `nextTick`?

**Comment by posva** [comment]
Yes, it's similar to nextTick. It must work when Promises are not supported. The behavior only changes when no callback is passed and there is support for Promises
