### ISSUE TITLE
Can't bind this context to imported routes array

### ISSUE THREAD

**Issue by plauclair** [vuejs/vue-router#1770]
### Version
2.7.0

### Reproduction link
[https://pastebin.com/nWxRA8kD](https://pastebin.com/nWxRA8kD)

### Steps to reproduce
See PasteBin for sample code.

I've tried defining routes as a function too to bind context, but when I do this it tries to call forEach on it and it's of course not working..

### What is expected?
Have a way to bind so "this" is accessible from the imported array.

### What is actually happening?
I don't see a way how to do that..

**Comment by LinusBorg** [comment]
> I've tried defining routes as a function too to bind context, but when I do this it tries to call forEach on it and it's of course not working..

Your code doesn't show any attempt to do this so I have a hard time understanding what you are trying to do.

> Have a way to bind so "this" is accessible from the imported array.

Bind to what? 

The component doesn't exist yet when that hook runs.


---

This sounds more like a usage question that a proper bug report, please consider asking your question on forum.vuejs.org or chat.vuejs.org

If you think this really think this is a bug, provide more information and a proper, runnable reproduction

**Comment by posva** [comment]
As @LinusBorg said, this sounds like a usage question, please use the discord or forum for that and come back if you find out there's actually a bug
