### ISSUE TITLE
A way to pass arbitrary data to navigation guards

### ISSUE THREAD

**Issue by andrei-zhidkov** [vuejs/vue-router#1775]
### What problem does this feature solve?
When using vue-router together with vuex, currently the only option to use the store inside `beforeRouteEnter()` guard is via direct import. While this might be okay in number of cases, I think there's a bunch of problems that may potentially arise, like testing difficulties and circular imports. Besides, the user ends up having both `$store` that's injected and the store that was imported, which makes the usage a bit inconsistent and confusing.
I think this kind of tight coupling can be avoided.

I understand that vue-router shouldn't know anything about vuex (or about any other state management), so we can't handle the store injection. But I guess we might have a generic way to pass arbitrary data to `beforeRouteEnter` (and, maybe, to other guards as well (?)). Then, the customer code (or wiring libraries like vuex-router-sync) could use that way to pass necessary data to the guard.

I would love to work on this myself, but I want to make sure that I'm doing the right thing conceptually, so prior to opening a PR I'm creating this issue.

### What does the proposed API look like?
I propose to add a method `registerGuardOption(name: string, data: any)` on the Router instance, as well as changing the signature of `beforeRouteEnter` from `beforeRouteEnter(to, from, next)` to `beforeRouteEnter(to, from, next, options)`.

Calling `router.registerGuardOption('store', storeInstance)` should result in `{ store: storeInstance }` being passed to `beforeRouteEnter` as an `options` parameter.

**Comment by posva** [comment]
You can already achieve it by either importing the store in the relevant component or using a function to inject it:

```js
import store from './store'

function storeInjector (fn) {
    return (...args) => {
        fn(...args, store)
    }
}
```

```js
beforeRouteEnter: storeInjector((to, from, next, store) => {     
     // your code
})
```

**Comment by andrei-zhidkov** [comment]
Sorry for bringing the closed issue up, but the proposed solution is exactly the thing I'd like to avoid.

Either proposed solution (both importing the store or importing the decorator that imports the store) results in the store and the component becoming tightly coupled, which (in my opinion, of course) is not good. My intention was to avoid importing a store instance into a component at all, and instead make the router responsible for passing the desired data.

**Comment by posva** [comment]
imo it's better this way because we can easily mock injections (because they're explicit), while the other way we cannot
