### ISSUE TITLE
Adding "resume" lifecycle event

### ISSUE THREAD

**Issue by mapodev** [vuejs/vue-router#1778]
### What problem does this feature solve?
Just a thought: Would it not be nice to have a "resume" lifecycle in vue-router? So adding an event callback by jumping back to a visited component?

### What does the proposed API look like?
Just like "mounted" or "created".

**Comment by posva** [comment]
You can already achieve this by using `beforeRouteEnter`, `beforeRouteUpdate` and the other hooks
