### ISSUE TITLE
[Suggestion] Proper merging strategy for transition hooks

### ISSUE THREAD

**Issue by OEvgeny** [vuejs/vue-router#178]
Now when using `route` transition hooks in mixin they can be redefined by component.

Just look at this [demo](http://jsfiddle.net/pnwtq6r0/). Click to "Go to Foo" to see what only component `data` hook is called. To check that mixin works click to "Go to Bar" you will see that mixin `data` hook is called.

I think it will be good to achieve Vue hooks merging strategy also for transition hooks.

**Comment by yyx990803** [comment]
This has been implemented for `data`, `activate` and `deactivate` in 0.7.3.

**Comment by OEvgeny** [comment]
@yyx990803 thanks. Works great with v1.0.0-rc.1! http://jsfiddle.net/pnwtq6r0/1/
