### ISSUE TITLE
link routes to wrong view from conditionally rendered nav

### ISSUE THREAD

**Issue by tedmoyses** [vuejs/vue-router#1783]
### Version
2.7.0

### Reproduction link
[https://ppxx14835q.codesandbox.io/](https://ppxx14835q.codesandbox.io/)

### Steps to reproduce
For some reason the bootstrap drop down doesn't work on codesandbox so the nav is pinned at display:block but navigate to login, click login, menu changes to logged in menu, click either profile or organisations and the wrong view is displayed - it takes you to login or register.

Note if you hover or inspect the correct link element is being displayed but incorrect view is shown

It's almost as if the previous nav list is being used

### What is expected?
clicking profile should show the profile view

### What is actually happening?
clicking profile shows the login view

---
apologies if this is vue related and not vue-router. Using static links instead in the conditional nav lists works as expected

**Comment by LinusBorg** [comment]
It would be helpful to see the code of this sandbox ...

But If I had to guess you probably should key your elements in the menu properly:

https://vuejs.org/v2/guide/conditional.html#Controlling-Reusable-Elements-with-key

**Comment by tedmoyses** [comment]
https://codesandbox.io/s/ppxx14835q is the source

I have added keys and this appears to fix the problem - thank you!

Apologies for this issue as I suppose it's not a bug, I did see about keying in the docs but did not make the connection. I will apply the fix to this project when I am back on tonight and pending success I will close the issue.

Thanks again, in advance

**Comment by tedmoyses** [comment]
Hi - I can confirm this does indeed solve the problem for my project. Thanks for the quick response and suggested resolution
