### ISSUE TITLE
When initial route to non root route with lazy loading, this.$route not initialized in created and mounted events of root instance (App.vue)

### ISSUE THREAD

**Issue by Zysce** [vuejs/vue-router#1784]
### Version
2.7.0

### Reproduction link
[https://github.com/Zysce/VueRouterRouteIssue](https://github.com/Zysce/VueRouterRouteIssue)

### Steps to reproduce
* get project [https://github.com/Zysce/VueRouterRouteIssue](https://github.com/Zysce/VueRouterRouteIssue)
* npm install
* npm run dev
* Navigate to link Hello (lazy loaded)
* Refresh browser 
* Look to data displayed on page

- When initial routing to root route (no params, no path), no problem
- When initial routing to route not lazy loaded, no problem
- When initial routing to route with lazy loading, this.$route not initialized in created and mounted of App.vue

### What is expected?
this.$route initialized to route (name, params, ...)  on created and mounted of vue instance

### What is actually happening?
this.$route not initialized on created and mounted of vue instance

---
I need url params in the mounted event.
Before adding lazy loading, no problem to access to data.
After setting up lazy loading, couldnt access to url params since this.$route is not initialized.
N.B : The initial routing needs to be a non root url with params.

**Comment by posva** [comment]
This is working as expected: vue-router waits for the component to be loaded before doing the navigation. It doesn't work with `/` either, it's just that it's the initial default route.

You can come around this by using a before hook which relies on the actual navigation
