### ISSUE TITLE
If you have a empty data() {} in the component, it crashes vue when routing. 

### ISSUE THREAD

**Issue by ChadTaljaardt** [vuejs/vue-router#1785]
### Version
2.7.0

### Reproduction link
[http://jsfiddle.net/o5q632d0/](http://jsfiddle.net/o5q632d0/)

### Steps to reproduce
Put a data() {} in your component, when navigating between routes you will get a error which will completly crash vue and the only way to fix it that ive found is to refresh the browser. 

The error looks like this: 
```
TypeError: Cannot read property '__ob__' of undefined
    at VueComponent.Vue.$destroy (npmcdn.com/vue@2.4.4/dist/vue.js:2511)
    at destroy (npmcdn.com/vue@2.4.4/dist/vue.js:3606)
    at invokeDestroyHook (npmcdn.com/vue@2.4.4/dist/vue.js:5330)
    at removeVnodes (npmcdn.com/vue@2.4.4/dist/vue.js:5346)
    at updateChildren (npmcdn.com/vue@2.4.4/dist/vue.js:5454)
    at patchVnode (npmcdn.com/vue@2.4.4/dist/vue.js:5508)
    at Vue$3.patch [as __patch__] (npmcdn.com/vue@2.4.4/dist/vue.js:5657)
    at Vue$3.Vue._update (npmcdn.com/vue@2.4.4/dist/vue.js:2464)
    at Vue$3.updateComponent (npmcdn.com/vue@2.4.4/dist/vue.js:2578)
    at Watcher.get (npmcdn.com/vue@2.4.4/dist/vue.js:2919)
handleError @ npmcdn.com/vue@2.4.4/dist/vue.js:569
10:20:25.621 
```

Related to https://github.com/vuejs/vue-router/issues/1728

### What is expected?
Navigation should continue and discard the component. 

### What is actually happening?
The component crashes upon discarding and crashes vue as a result. 

---
This might not be a bug, but its really bad for the component to crash if the data is empty, it took me a very long time to find this error's cause.

**Comment by LinusBorg** [comment]
Well, the `data` function is supposed to return an object. Not returning one is simply wrong usage.

**Comment by bmustiata** [comment]
Then `vue-router` should report that in a sane way.

**Comment by LinusBorg** [comment]
That it something that would have to be fixed in Vue, not vue-router.

But it already is:

![image](https://user-images.githubusercontent.com/1444526/33255150-7ce342cc-d34c-11e7-8a8e-873ba228a5ac.png)

**Comment by bmustiata** [comment]
This message only appears if the development mode is set.

**Comment by LinusBorg** [comment]
That's right. 

I would assume that such a bug would be easy enough to be catched in development that it can't happen in production.

So while the error message in production could be more helpful, it's not a "necessary" improvement because it should not happen in production in the first place.

We'll see what we can do....

**Comment by Wisdom132** [comment]
I'm also experiencing this issue...it gives me a blank page..but when i reload the component it then loads the component properly

**Comment by posva** [comment]
You just need to return an empty object or remove the `data` property altogether. It is also unrelated to vue-router. Locking as the thread has been resolved and it's old
