### ISSUE TITLE
router.match(location) not return query object from url like this.$route

### ISSUE THREAD

**Issue by davidgaroro** [vuejs/vue-router#1786]
### Version
2.7.0

### Reproduction link
[https://github.com/BlackCode7/vue-router-bug](https://github.com/BlackCode7/vue-router-bug)

### Steps to reproduce
1. git clone https://github.com/BlackCode7/vue-router-bug
2. npm install
3. npm run dev
4. open console
5. click on the "Get console.log" button
6. Look at both objects, they should be the same but "router.match(location)" loses query parameters

### What is expected?
Objects returned by "this.$route" and "router.match(location)" should be the same

### What is actually happening?
The object returned by "router.match(location)", contains an empty query object inside when there are query in the url

---
Documentation: https://router.vuejs.org/en/api/route-object.html

**Comment by posva** [comment]
You have to pass `location.href` not the Location object

**Comment by davidgaroro** [comment]
Thank you so much Posva!
