### ISSUE TITLE
Component reloaded

### ISSUE THREAD

**Issue by andrew-vdb** [vuejs/vue-router#1787]
### Version
2.7.0

### Reproduction link
[https://jsfiddle.net/yyx990803/xgrjzsup/](https://jsfiddle.net/yyx990803/xgrjzsup/)

### Steps to reproduce
1. Change Foo Template
const Foo = { template: '<div><input>foo</div>' }

2. Click Go To Foo, type something in the input

3. Click Go To Bar

4. Click Go To Foo

### What is expected?
What I type in input inside component "Foo" still exists

### What is actually happening?
What I type in input is gone, it feels like the component being reloaded

**Comment by andrew-vdb** [comment]
![image](https://user-images.githubusercontent.com/12871379/31299936-40b6467e-aaf1-11e7-8a76-24a17b37025b.png)

**Comment by andrew-vdb** [comment]
Click Go to Bar
![image](https://user-images.githubusercontent.com/12871379/31299945-517beeaa-aaf1-11e7-8d94-1887b0ca13ed.png)

**Comment by andrew-vdb** [comment]
Click Go to Foo
![image](https://user-images.githubusercontent.com/12871379/31299959-5d774f38-aaf1-11e7-95f7-ad6cf9751ab1.png)

What I type is gone....

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

That's normal, it's as if you switched pages. Depending on what you want to do, there're different solutions, one is to set up a variable on the parent and pass it down as a prop

**Comment by andrew-vdb** [comment]
Well when I read forum, the expected behavior is to have it keep-alive by default.
I hope it will be putted in "Getting Started" documentation as it took me some serious "google vue" to finally find this option

For anyone else who may read this in future,
If you don't use "keep-alive", every time you change routes, component's "mounted" will be called.
Usually we put initialization code within "mounted", thus it will looks like "reset" the component
```
<keep-alive>
                <router-view></router-view>
</keep-alive>
```
There is also include/exclude option for keep-alive which you may want to have when you want some components to be always mounted.
