### ISSUE TITLE
Add a new history mode to allow parallel <router-view> components to work independently

### ISSUE THREAD

**Issue by vberlier** [vuejs/vue-router#1788]
### What problem does this feature solve?
The problem occurs when building applications/tools inside of which you need to let your users reorganize their workspace. Users with different needs will configure their workspace to only show what they care about.

Let's say I have an application made of 4 different modules:

- Module A
- Module B
- Module C
- Module D

A user interested in modules A, B and C might configure his workspace like this:

```
 ----------------------- ------------ 
| Module A              | Module B   |
|                       |            |
|                       |            |
|                        ------------ 
|                       | Module C   |
|                       |            |
|                       |            |
|                       |            |
|                       |            |
 ----------------------- ------------ 
```

Another user, interested in modules A, B and D will configure his workspace differently:

```
 ----------------------- ------------ 
| Module D              | Module B   |
|                       |            |
|                       |            |
|                        ------------ 
|                       | Module A   |
|                       |            |
|                       |            |
|                       |            |
|                       |            |
 ----------------------- ------------ 
```

Here the three sections of the page are independent. They all have their own navigation stack, their own "Back" button. This means that to be able to use a `<router-view>` in each section to switch between modules, we would need a history mode completely decoupled from the URL of the page. This is very different from named views, it's about allowing multiple virtual navigation roots per application instead of a single one (the URL).

The "virtual" history mode would keep track of the parallel navigation branches internally instead of modifying the URL.

### What does the proposed API look like?
Using the "virtual" history mode would simply require the user to set `mode` to `'virtual'` inside of the router.

```js
const router = new VueRouter({
  mode: 'virtual',
  route: [
	// Define routes
	{ path: '/module-a', name: 'a', component: ModuleA },
	{ path: '/module-b', name: 'b', component: ModuleB },
	...
  ]
})
```

In templates, parallel `<router-view>` components will now work independently on their own virtual navigation branch instead of being tied to the URL of the page. Setting the root of a `<router-view>` component could then be done using either a `string` or a `Location` object, just like the `to` prop on the `<router-link>` component.

```html
<div class="section-1">
  <router-view root="a"></router-view>  <!-- Using the route name -->
</div>

<div class="section-2">
  <router-view :root="{ path: 'module-b' }"></router-view>  <!-- Using the path -->
</div>

...
```

**Comment by posva** [comment]
Thanks for your suggestion but this is way too specific to an use case and introduces too much complexity to be implemented.
In any case, there's only one url, so this would be easier to customise by your side and maybe represent the state of the current layout in the url somehow.

You should also be able to create multiple `new Vue` on your page (instead of one) to achieve what you want

**Comment by vberlier** [comment]
Alright, thanks for your feedback. I will work on an independent solution.
