### ISSUE TITLE
beforeEnter logout localStorage.clear() no use

### ISSUE THREAD

**Issue by willin** [vuejs/vue-router#1794]
### What problem does this feature solve?
```js
{
      path: '/logout',
      redirect: '/login',
      beforeEnter: (to, from, next) => {
        localStorage.clear();
        next();
      }
    }
```

### What does the proposed API look like?
localStorage should be clear.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
