### ISSUE TITLE
Issue #862 solution without webpack 2

### ISSUE THREAD

**Issue by cobrAJ** [vuejs/vue-router#1799]
### What problem does this feature solve?
Issue #862 fix a problem on lazy load with webpack 2 ,
but I just use the RequireJS  VueJs 2.0   ES5 .
How can I fix this problem ?
Did this has any other solutions ?
(PS: Problem description the same as Issue #1074)

### What does the proposed API look like?
I hope the problem doesn't just be fix on the Third plugin .
I wish it be fixed in vue-router .
That's all thanks .

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

I'm sorry, I haven't used requirejs in a very long time, but it sholud work as long as you return a promise, check https://router.vuejs.org/en/advanced/lazy-loading.html
