### ISSUE TITLE
Option for preserving scroll position

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vue-router#18]

**Comment by zdz1993** [comment]
我在 ready里面调用window.scrollTo 为什么会不起作用呢？？`<script>
import XHeader from '../common/x-header/' 

export default {
	ready () {
		alert('aa')
		window.scrollTo( 0, 1000);
	
	},
    data () {
        return {
          
        }
    },
    components: {
        XHeader
    },
    methods: {
    	scroll:function(){
    		window.scrollTo( 0, 100);
    	}
    }
    
	}
</script>`

**Comment by zdz1993** [comment]
`<script>
import XHeader from '../common/x-header/' 

export default {
	ready () {
		alert('aa')
		window.scrollTo( 0, 1000);
	
	},
    data () {
        return {
          
        }
    },
    components: {
        XHeader
    },
    methods: {
    	scroll:function(){
    		window.scrollTo( 0, 100);
    	}
    }
    
	}
</script>`

**Comment by zdz1993** [comment]
<script>
import XHeader from '../common/x-header/' 

export default {
	ready () {
		alert('aa')
		window.scrollTo( 0, 1000);
	
	},
    data () {
        return {
          
        }
    },
    components: {
        XHeader
    },
    methods: {
    	scroll:function(){
    		window.scrollTo( 0, 100);
    	}
    }
    
	}
</script>

**Comment by briangonzalez** [comment]
If anyone comes across this issue, this is already implemented:

``` js
const router = new VueRouter({
  saveScrollPosition: true,
});
```

**Comment by liu-dongyu** [comment]
@briangonzalez  `saveScrollPosition: true` only work when setting `history: true`.  How to preserving scroll position with `history: false` ? 
@yyx990803 Any ideas to do that ?

**Comment by fwon** [comment]
@liu-dongyu  Here i have a solution(with vuex or not).
1. save position before each router jump, in main.js
```javascript
router.beforeEach((to, from, next) => {
	store.commit('setPosition', {
		name: from.name,
		pos: window.scrollY
	})
	next();
});
```
2. create a mixins global function in position.js
```javascript
export default {
	activated() {
		const pos = this.$store.state.pagePosition;
		const name = this.$route.name;
		window.scrollTo(0, pos[name]);
	}
}
```
3. so in every vue page component, you can add mixins into it
```javascript
import Position from 'position.js'
export default {
	mixins: [Position],
        ...
}
```

**Comment by woshi82** [comment]
@yyx990803 @fwon 
But when press the back button in browser (`window.history.go(-1)`), scroll to the savedPosition is the browsers‘s default behaviour。
I just confused why when i change route in my SPA, the browsers not scroll to the savedPosition, but when i refresh my SPA ,  the browsers scroll to the savedPosition? why ? 
is it the problem of `vue-router`?


"vue": "2.1.10"
 "vue-router": "2.2.1"

**Comment by Wang-Kai** [comment]
@fwon 思想倒是很不错，对 js、vue 都了解的蛮透彻，但SPA项目多数都是包裹在一个大的 div 里面，记录 window 对象的滚动位置，并不能解决多数问题。

**Comment by fwon** [comment]
@Wang-Kai, The example just showing my thought but not forced to use "window".
Please think it deeply，not every router need a "position jump" feature. So maybe we can just put a router hook into a mixin function (like beforeRouteLeave), but not as global.

Mixin file Position.js

```javascript
activated() {
	const pos = this.$store.state.pagePosition;
	const name = this.$route.name;
	if (this.scroller) {
		this.scroller.scrollTop = pos[name];
	} else {
		window.scrollTo(0, pos[name]);	
	}
},
mounted() {
	if (this.$refs.scrollpage) {
		this.scroller = this.$refs.scrollpage; 
	}
},
methods: {
	//beforeRouteLeave can not be directly insert into vue prototype, so put in methods
	beforeRouteLeave (to, from, next) {
		const self = this;
		this.$store.commit('setPosition', {
			name: from.name,
			pos: self.scroller.scrollTop || window.scrollY
		})
		next();
	}
}
```

Then in jumping page, include the mixin to record the position.

```html
<div class="scroll-container" ref="scrollpage"></div>
```
```javascript
mixins: [Position],
beforeRouteLeave (to, from, next) {
	this.beforeRouteLeave(to, from, next);
}
```
