### ISSUE TITLE
instant call method go()

### ISSUE THREAD

**Issue by AStaroverov** [vuejs/vue-router#180]
Hello, I have some problem with router view.
If I call method go({ path: '/some/path' }) in time created vue instance in router, then ```<router-view>``` becomes empty. After all v-links work normally.

```
let instance = Vue.extend({
  created() {
     this.$route.router.go({ path:  '/some/path' });
  }
})

let router = new VueRouter({
  history: true
});

router.map({
  '/some/path': {
    component: require('someComponent')
  }
})

router.start(instance, '#app');
```

if i use 
```
router.beforeEach(function (transition) {
  setTimeout(transition.next, 0);
})
```
Then all work correct, but first component for ```<router-view>``` displayed with transition.
(<router-view> have transition class and transition mode 'out-in')

this reproduce at 0.6.(1|2) and 0.7.0 releases

**Comment by yyx990803** [comment]
Why not use [redirect](http://router.vuejs.org/en/api/redirect.html) instead?

**Comment by hellbeast92** [comment]
It case not for redirect.
I need pick url in the dependence some varible.

**Comment by yyx990803** [comment]
Try doing this in the ready hook instead.

**Comment by AStaroverov** [comment]
it doesn't work.

**Comment by yyx990803** [comment]
Just tested with 0.7.5 and seems to work correctly.
