### ISSUE TITLE
2.8 & 3.0 router-view props bug

### ISSUE THREAD

**Issue by Yusoo** [vuejs/vue-router#1800]
### Version
2.8.0

### Reproduction link
[http://jsfiddle.net/9r6xhqbp/38/](http://jsfiddle.net/9r6xhqbp/38/)

### Steps to reproduce
click /foo, msg is undefined

### What is expected?
before 2.8.0, msg == 123

### What is actually happening?
msg is undefined

**Comment by alexsasharegan** [comment]
I'm also having this issue using route params. My route param will be initially passed, but then updated as an empty string.

```js
const routes = {
  {
    name: "cluster-select",
    path: "/uploadconfigure/clusters/select/cluster/:slugName?",
    props: true,
    component: HdClusterViz,
    beforeEnter: (to, from, next) => {
      const selectedCluster = store.getters["clusters/clustersBySlugName"][to.params.slugName]
      if (selectedCluster) {
        store.dispatch("clusters/selectCluster", selectedCluster)
      } else {
        store.dispatch("clusters/deselectCluster")
      }
      next()
    }
  }
}
```

Reverting to 2.7.x fixed this for me.

**Comment by yyikaka** [comment]
+1

**Comment by amirrustam** [comment]
I'm also experiencing this issue. Tested with both 2.8.0 and 3.0.0. I get a missing prop error for a `router-view` that accepts a prop. I also had to revert to 2.7.0 to get things back to normal.

**Comment by tri-chandra** [comment]
If you are navigating programmatically, in $router.push() you could pass the props there. However, this is a painful solution, reverting to 2.7.0 is better.

**Comment by andrei-markeev** [comment]
Same here, had to revert to 2.7.0. Would be great if it is fixed!
