### ISSUE TITLE
VueRouter with children and named routes. Components won't load

### ISSUE THREAD

**Issue by MadReal** [vuejs/vue-router#1806]
### Version
3.0.0

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
I can't make the children's components work, no matter what I do they won't load anything. As you can see in my router file I in fact am currently trying 2 different setup for the component import but nothing works.

I also tried not having components at all in the main path and only load them from the children, still wasn't working.

This is my current setup

router.js

    {
        path: '/beats',
        components: {
            navbar: Navbar,
        },
        children: [{
                path: 'catalog',
                name: 'BeatsCatalog',
                component: BeatsCatalog,

            },
            {
                path: 'upload',
                name: 'BeatsUpload',
                components: {
                    default: () => import ('@/views/BeatsUpload'),
                },
            },
        ]
    },

App.vue

    <template lang="pug">
    #app
    	modal-manager
    	router-view(name="navbar")
    	router-view
    </template>

What I'm trying to do is have the navbar by default in all my children, and inside the children just load the main component for the view.

I've tried any type variation and I can't make it work. What am I doing wrong? 

### What is expected?
Vue router to load the components inside the children

### What is actually happening?
They are not being loaded and no error is shown

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
