### ISSUE TITLE
MVC ASP.NET vue-router Error after refresh.

### ISSUE THREAD

**Issue by Ethan0007** [vuejs/vue-router#1808]
Hi, i just want to ask something when i refresh the link it will give me some kind of HTTP 404.0 - Not Found
i already installed the UrlReWrite , and change the port in dev-server and also added the said web.config in the project.

![image](https://user-images.githubusercontent.com/12542052/31544020-7f847934-b04b-11e7-82b7-fa13cfa705e2.png)

please be guided.

Thanks

**Comment by callumacrae** [comment]
You need to get it to serve index.html on any HTML request it doesn't recognise

**Comment by Ethan0007** [comment]
@callumacrae sir, the issue is already resolved by adding proxy in webpack in index.js.

My bad, late reply.
