### ISSUE TITLE
Url params in child route undefined

### ISSUE THREAD

**Issue by dimensi** [vuejs/vue-router#1809]
### Version
2.8.0 & 3.0.0

### Reproduction link
[http://jsfiddle.net/xfmcLgjd/4/](http://jsfiddle.net/xfmcLgjd/4/)

### Steps to reproduce
1. Create route with optional param
2. Create in route, child route with optional param

### What is expected?
```js
id === 10  
mode === 'test'  
modeId === 1  
```

### What is actually happening?
```js
id === 10
mode === undefined
modeId === undefined

```
---
With problem only from 2.8.0 and only with child.

**Comment by posva** [comment]
The version that you provided works. Can you check it please?

**Comment by edDimensi** [comment]
If i change version on 2.7.0, i get
![image](https://user-images.githubusercontent.com/11390039/31546233-153371fe-b02b-11e7-8334-1a823644fe71.png)

**Comment by posva** [comment]
I still get the good result (last screenshot) what browser are you using?

**Comment by edDimensi** [comment]
chrome.

**Comment by posva** [comment]
Oh, my bad, I was looking at `$route.params`

**Comment by edDimensi** [comment]
![image](https://user-images.githubusercontent.com/11390039/31547652-dadc7824-b030-11e7-807b-300813d17b79.png)
on url https://kmpv5k402o.codesandbox.io/foo/10/active/test/1
i get 
```
id:"10"
mode:undefined
modeId:undefined
```

**Comment by posva** [comment]
For some reason, declaring the props `mode` and `modeId` on the parent route view fixes the issue
edit: I cleared out the conversation because it was my bad, sorry 😆

**Comment by yyx990803** [comment]
Duplicate of #1800
