### ISSUE TITLE
v-link="null" still not fixed in 0.7.0

### ISSUE THREAD

**Issue by fnlctrl** [vuejs/vue-router#181]
```html
v-link="true ? null : null"
```
causes 
"Uncaught TypeError: Cannot read property 'name' of null"

Source code that caused error:
```javascript
value: function _stringifyPath(path) {
	      if (typeof path === 'object') {
	        if (path.name) {
```

It is obvious that `null` is an object....
~~please allow me to do a facepalm...~~

**Comment by yyx990803** [comment]
Facepalm instead of a PR? ~~please allow me to do a facepalm...~~

**Comment by azamat-sharapov** [comment]
haha, I wish I could upvote comments here
