### ISSUE TITLE
Nested routers do not produce external urls and are not navigable to without clicking

### ISSUE THREAD

**Issue by rjwittams** [vuejs/vue-router#1816]
### Version
3.0.1

### Reproduction link
[https://github.com/vuejs/vue-router/tree/dev/examples/nested-router](https://github.com/vuejs/vue-router/tree/dev/examples/nested-router)

### Steps to reproduce
In a clone of vue-router:
- npm run dev
- open http://localhost:8080/nested-router/
- Click nested-router
- Hover over the nested foo link
- Copy that link and try it in a new browser window
- Click the nested foo link and look at the browser address bar - it does not change.

### What is expected?
The url for the nested foo should be 
http://localhost:8080/nested-router/nested-router/bar

This should work in a new browser. 

### What is actually happening?
The url for the nested foo is actually
http://localhost:8080/bar, which is in the parent directory of the example.

This obviously does not work in a new browser.

---
This appears externally just like changing a component based on internal data, even though the route mechanism is used.
I thought this would be useful for modularity of components. It appears only a global flat list of routes works well currently.

**Comment by posva** [comment]
This is intended, a nested router in abstract mode doesn't change the URL. You can use history mode to make it change the URL but that would complexify too much the application routing. It was originally made to allow embedding demos of vue-router but it should always be used with abstract mode
