### ISSUE TITLE
router.beforeEach with alias '/' is wrong matching in to.matched 

### ISSUE THREAD

**Issue by tjunussov** [vuejs/vue-router#1817]
### Version
2.7.0

### Reproduction link
[http://jsfiddle.net/tjunussov/n8hbzauv/1/](http://jsfiddle.net/tjunussov/n8hbzauv/1/)

### Steps to reproduce
```
routes: [
    {
      path: '/tasks',
      alias: '/',
      component: TaskList,
      children: [
        {
          path: ':taskId',
          component: TaskForm
        },
        {
          path: '',
          component: TaskDashboard
        }
      ]
    },
    {
      path: '/login',
      component: WelcomeLogin,
      meta: { isPublic: true }
    },
    { path: '*', redirect: '/' }
  ]
```
and in beforeEach

```
router.beforeEach((to, from, next) => {
  console.log('beforeEach',to.matched);
  next('/login')
})
```

### What is expected?
If we navigate to `/login` in `router.beforeEach` `to.matched` parameter should contain { /login , WelcomeLogin  } 

### What is actually happening?
but it matched default alias and children of alias
{ TaskList, taskForm }

---
I saw this issue, https://github.com/vuejs/vue-router/issues/1427 but it looks like it still persist in 2.7.0 router

**Comment by posva** [comment]
By using alias: /, you're matching `/login` onto `/:taskId`
Just move the login route to the top

**Comment by tjunussov** [comment]
Thanks, it solves issue, but maybe we could update docs to warn users ?
