### ISSUE TITLE
Store navigation state for multiple independent widgets/components on one page

### ISSUE THREAD

**Issue by im4LF** [vuejs/vue-router#1819]
### What problem does this feature solve?
I need to organize the following page behavior - one page, several components, the state of which is reflected in the address bar (for ex hash)

#component1:/current/state/of/c1;component2:/current/state/of/c2

### What does the proposed API look like?
May be for hash based navigation pass "segment"
```
<router-link to="/current/state/of/c1" segment="component1"></router-link>
```

**Comment by posva** [comment]
Use a `query` for that
