### ISSUE TITLE
v-link is not accessible if component is imported

### ISSUE THREAD

**Issue by wonderfulll** [vuejs/vue-router#182]
Hi,
Is there any reason why `v-link` could not be accessible if component is imported?

Console:
```
[Vue warn]: Failed to resolve directive: link
```

app.js:
```es6
import Vue from 'vue';
import VueRouter from 'vue-router';
import Page3 from './page3';

Vue.use(VueRouter);

const Page2 = Vue.extend({
  template: '<page3></page3><br/><a v-link="{ path: \'/my-path\' }">Working link</a>',
  components: {
    'page3': Page3,
  },
});

const Page1 = Vue.extend({
  template: '<page2></page2><br/><a v-link="{ path: \'/my-path\' }">Working link</a>',
  components: {
    'page2': Page2,
  },
});

const router = new VueRouter({});

router.map({
  '/': {
    name: 'page1',
    component: Page1,
  },
});

const App = Vue.extend({});
router.start(App, '#app');
```

page3.js (Failed to resolve directive: link):
```es6
import Vue from 'vue';

export default Vue.extend({
  template: '<a v-link="{ path: \'/my-path\' }">Not working link</a>',
});
```

app.html:
```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title></title>
</head>

<body>
    <div class="ui container" id="app">
        <router-view></router-view>
    </div>
    <script type="text/javascript" src="/build/app.js"></script>
</body>

</html>
```

P.S.: is there any service like jsfiddle with browserify support? 

Vue.js 1.0.0-beta.4, vue-router: 0.7.1

**Comment by yyx990803** [comment]
This is because for Page3, `Vue.extend` is called **before** `Vue.use(VueRouter)`.
`Vue.use(VueRouter)` injects the necessary hooks for components to pick up the `$route` context.

The simple solution for now is to just export objects in your component modules. There's no need to call `Vue.extend` there anyway.

This is still somewhat confusing behavior, so I'll fix it in a later release.

**Comment by wonderfulll** [comment]
The simplest solutions is to change order, but note if you are using babel you will have to use `require` as imports are hoisted (see https://github.com/babel/babel/issues/1371 for details).

```
import Vue from 'vue';
import VueRouter from 'vue-router';
import Page3 from './page3';

Vue.use(VueRouter);

const Page3 = require('./page3';);
```
