### ISSUE TITLE
vue-router异步嵌套路由不生效，url有变化，子页面不显示

### ISSUE THREAD

**Issue by lmm1990** [vuejs/vue-router#1828]
### Version
3.0.1

### Reproduction link
[http://jsfiddle.net/7g61npzo/1/](http://jsfiddle.net/7g61npzo/1/)

### Steps to reproduce
点击 child page，url有变化，子页面内容没显示

### What is expected?
应该显示子页面内容

### What is actually happening?
url发生了变化，子页面内容没显示

---
文件附件：https://github.com/vuejs/vue-router/files/1393861/src.zip

**Comment by JounQin** [comment]
You need also add `<router-view></router-view>` into your home template to show your child view.

**Comment by lmm1990** [comment]
谢谢，已经解决了
