### ISSUE TITLE
v-link exact option and trailing slash behavior

### ISSUE THREAD

**Issue by rpkilby** [vuejs/vue-router#183]
If there is a route `/foobar` and a user visits `/foobar/`, the active class is not applied under `exact` matching. I could see arguments for both as to whether or not the matching is trailing-slash agnostic.

**Comment by yyx990803** [comment]
Hmm, looks like a trailing slash should be allowed, because `/foobar/` does match a route with path `/foobar`.

**Comment by rpkilby** [comment]
That would make sense to me. Either way, it's not an incredibly pressing issue since `v-link`ing to a named route will generate a path of `/foobar`.
