### ISSUE TITLE
Dynamic import component in router definition fails

### ISSUE THREAD

**Issue by Inndy** [vuejs/vue-router#1830]
### Version
3.0.1

### Reproduction link
[https://github.com/Inndy/vue-bugs/tree/vue-router-dynamic-import](https://github.com/Inndy/vue-bugs/tree/vue-router-dynamic-import)

### Steps to reproduce

`vue init webpack vue-router-fails`

```import Vue from 'vue'
import Router from 'vue-router'

Vue.use(Router)

export default new Router({
  routes: [
    {
      path: '/',
      name: 'Hello',
      component: import('@/components/HelloWorld')
    }
  ]
})```

### What is expected?
Route component should appear

### What is actually happening?
It doesn't work

<!-- generated by vue-issues. DO NOT REMOVE -->

**Comment by JounQin** [comment]
Async component in router options should be a function which returns a Promise: `component: () => import('@/components/HelloWorld')`.

https://router.vuejs.org/en/advanced/lazy-loading.html

**Comment by Inndy** [comment]
@JounQin thanks!
