### ISSUE TITLE
scroll.js: replaceState() is not supported in IE9

### ISSUE THREAD

**Issue by FranckFreiburger** [vuejs/vue-router#1834]
### Version
3.0.1

### What is actually happening?
IE9 throw the following error: `Object doesn't support this property or method "replaceState"`.
This was introduced here:
commit: https://github.com/vuejs/vue-router/commit/c166822cdc6cadd9f3c01085b877c86d74362b95
related issue: https://github.com/vuejs/vue-router/issues/1585

**Comment by yyx990803** [comment]
Are you using `fallback: false`?

**Comment by FranckFreiburger** [comment]
yes, mode 'history' and fallback false
