### ISSUE TITLE
Appear Transition

### ISSUE THREAD

**Issue by Twinpix** [vuejs/vue-router#1839]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/Twinpix/hgs7w26f/2/](https://jsfiddle.net/Twinpix/hgs7w26f/2/)

### Steps to reproduce
When changing to route A or Route B, Router should fire appear hook of Component on the first time and but enter hook is fired instead.

### What is expected?
I want to get a different transition/animation on the first load of components by vue-router, so I want to use appear hooks for this purpose.

### What is actually happening?
But it seems that appear hook can only fired on the first component that is loaded in <router-view>, even if appear hooks are defined at component level and not around  <router-view>.

**Comment by posva** [comment]
> But it seems that appear hook can only fired on the first component that is loaded in , even if appear hooks are defined at component level and not around .

Yes, the view not being there right from the start, the `appear` event is not triggered. However, you will get the event if it's the initial view (try changign the component for the route `/`)

More about appear at https://vuejs.org/v2/guide/transitions.html#Transitions-on-Initial-Render
