### ISSUE TITLE
在ts中路由定义时无法使用import()定义异步子组件

### ISSUE THREAD

**Issue by yangdan8** [vuejs/vue-router#1847]
### Version
3.0.1

### Reproduction link
[https://router.vuejs.org/zh-cn/advanced/lazy-loading.html#](https://router.vuejs.org/zh-cn/advanced/lazy-loading.html#)

### Steps to reproduce
无法使用import()定义异步子组件

### What is expected?
无法使用import()定义异步子组件

### What is actually happening?
无法使用import()定义异步子组件

---
无法使用import()定义异步子组件

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

I'm not very familiar with ts but it looks like it should work (https://github.com/Microsoft/TypeScript/issues/12364). Anyways, as long as it returns a Promise, vue-router should be able to handle it, if it doesn't work, then you can open an issue with a repro
