### ISSUE TITLE
Routing to Async Component fails 

### ISSUE THREAD

**Issue by blake-newman** [vuejs/vue-router#1855]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/rd0whfxd/](https://jsfiddle.net/rd0whfxd/)

### Steps to reproduce
Add a Async route, try to navigate via router-link. 

### What is expected?
To load route component

### What is actually happening?
Nothing

**Comment by LinusBorg** [comment]
This may only apply to your jsfiddle example, but:
```
 { path: 'profile', component: () => UserProfile }
```
The above is simply invalid usage of the lazy option. You have to either:
* return a promise, or
* call resolve

**Promise**: https://jsfiddle.net/Linusborg/rd0whfxd/1/

**Resolve**: https://jsfiddle.net/Linusborg/rd0whfxd/2/

**Comment by posva** [comment]
@LinusBorg is right, you need to return a promise with `Promise.resolve` 😛
