### ISSUE TITLE
add routes by addRoutes  will not show in $router.options.routes

### ISSUE THREAD

**Issue by PanJiaChen** [vuejs/vue-router#1859]
### Version
3.0.1

when l add routes by addRoutes  ,but $router.options.routes is not update

**Comment by posva** [comment]
That is normal, options is the object passed to the vuerouter constructor. It's not modified afterwards.

**Comment by tadada** [comment]
After ‘addRoutes’, the routers added can accessable, but can not be found in this.$router object. So how can I get added routers? Or save a copy instead?

**Comment by fayt81** [comment]
It's ok that options.routes are those passed during initialization, but then we need a method to get also routes added with addRoutes. What about exposing an array with all routes such as this.$router.routes?

**Comment by shaqueoneal** [comment]
how can you close this issue without solving the practical problem？@posva @yyx990803

**Comment by jinweijie** [comment]
@posva it's reasonable that $router.options.routes not modified afterwards, but is there any method available to retrieve the current routes? for me, after addRoutes succeeded there should be a way to get the current routes which are available. Thanks!

**Comment by posva** [comment]
right now you need to keep a copy of current routes as you add them. This is because vue-router is designed about static routes, so there are things not quite possible regarding full dynamic routing and we don't want to rush all features

**Comment by jinweijie** [comment]
@posva Thank you for the reply, sure, please take your time.

**Comment by fayt81** [comment]
Hi @posva, as suggested, I am currently storing an array with the routes added dynamically, so that it can later be used by the rest of my code. However, since all the routes (including dynamically added ones) should be already stored somewhere to get the routing working, why not just exposing the variable where they are actually stored? Could you kindly explain what is critical in exposing it?

**Comment by milost1982** [comment]
@posva any updates on requests in this thread asked by the community?

**Comment by erg** [comment]
Maybe rename it to vue-static-router

**Comment by posva** [comment]
See https://github.com/vuejs/rfcs/pull/122 `getRoutes`
