### ISSUE TITLE
route data hook generates warnings about setting non-existent paths

### ISSUE THREAD

**Issue by rpkilby** [vuejs/vue-router#186]
I have a router and route component that look roughly like the following:
```js
const bar = Vue.extend({
    route: {
        data: function(transition) {
            return {someKey: 'some data'};
        },
    },
})

router.map({
    '/foo': {
        component: {template: '<router-view></router-view>'},
        subRoutes: {
            '/bar': {component: bar},
        },
    },
})
```

This results in the following warning every time I navigate to the component:
```
You are setting a non-existent path "someKey" on a vm instance. Consider pre-initializing the property with the "data" option for more reliable reactivity and better performance.
```
I tried adding a data function to the component, but this didn't seem to fix the warnings.

I don't think that the subRoutes has anything to do with it. Tried using `bar` as a top-level route's component, and the same errors cropped up.

**Comment by yyx990803** [comment]
Did you try this?

``` js
const bar = Vue.extend({
    data: function () {
      return {
        someKey: 'default value'
      }
    },
    route: {
        data: function(transition) {
            return {someKey: 'some data'};
        }
    }
})
```

**Comment by rpkilby** [comment]
That works, although I must have made a mistake earlier as it didn't work.

Either way, should this be the expected behavior?

**Comment by yyx990803** [comment]
Yes. this is expected behavior.

**Comment by rpkilby** [comment]
right - because the route data is asynchronous, hence $loadingRouteData.
