### ISSUE TITLE
Router document `Scroll Behavior - scroll to anchor` section

### ISSUE THREAD

**Issue by wxsms** [vuejs/vue-router#1861]
### Version
3.0.1

### Reproduction link
[https://codepen.io/wxsm/pen/EbKXoz](https://codepen.io/wxsm/pen/EbKXoz)

### Steps to reproduce
Using the document code:

```javascript
scrollBehavior (to, from, savedPosition) {
  if (to.hash) {
    return {
      selector: to.hash
      // , offset: { x: 0, y: 10 }
    }
  }
}
```

to scroll between anchors such as '#1', '#2'

### What is expected?
scroll properly without error.

### What is actually happening?
CAN'T scroll properly & WITH error like:

Fail to execute 'querySelector': '#1' is not a valid selector.

See minimal reproduction link on codepen, click the `go to foo` link, then check console.

---
This is because `querySelector` dose not support such id selector. There is a better way to do this:

```javascript
if (to.hash) {
  return {
    selector: `[id='${to.hash.slice(1)}']`
  }
}
```

This will cause no error.

I think the document should update to this for better helping people. I can PR this if needed. thanks.

**Comment by posva** [comment]
This is actually unrelated to vue-router, it's a browser specific error. It looks like you cannot make an id start with a number.

**Comment by wxsms** [comment]
@posva  

**All browsers indeed**, and not only number-leading ids, but also something like '#-1' or others. 

Since the document mention it, then I think you want people to achive this easier. So why not in a better way?

**Comment by posva** [comment]
Where does the mention says to use `#1`. If it does we should change it

**Comment by wxsms** [comment]
No it doesn't. Just making me confuse for a while. cause some anchors are auto-generated, and those not start with alphabet will lead to this problem.

 Thanks for your time and good luck.
