### ISSUE TITLE
router-link with query won't be active if url has no query

### ISSUE THREAD

**Issue by SidKwok** [vuejs/vue-router#1871]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/xgrjzsup/4169/](https://jsfiddle.net/xgrjzsup/4169/)

### Steps to reproduce
```vue
<router-link :to="{name: 'Foo', query: {a: 1}}">Go to Foo With Query</router-link>
```

```css
.router-link-active {
  color: red;
}
```
the url is `/foo`

### What is expected?
Both `/foo` and `/foo?a=1` can make the link active.

### What is actually happening?
Only `/foo?a=1` can.

---
Both `/foo` and `/foo?a=1` can make the link active in vue-router 0.7

**Comment by LinusBorg** [comment]
This is expected behaviour in since vue-router 2.0 onwards. if you want this behaviour, create it yourself with a simple class binding.
