### ISSUE TITLE
dynamic path assembly by route name

### ISSUE THREAD

**Issue by newbie78** [vuejs/vue-router#1876]
### What problem does this feature solve?
if we have nested routes like this for example:
```
export let routes = [
  {
    path: '/:lang',
    name: 'Main',
    component: Main,
    children: [
      {
        path: '/cabinet',
        name: 'Cabinet',
        component: Cabinet
      }
    ]
  }
]
```
in the template, we must call:
```
<router-link :to="{ path:`/${$route.params.lang}/cabinet`}">Cabinet</router-link>
```
### What does the proposed API look like?
why we can not specify for this simply named route like this:
```
<router-link :to="{ name: 'Cabinet'}">Cabinet</router-link>
```
maybe I'm wrong it cook?

**Comment by posva** [comment]
You need to specify the param `lang` to make it work. But you also may want to specify the child path as `cabinet` and not `/cabinet` http://jsfiddle.net/jjf21uph/

Please, next time use the forum or discord chat for questions 🙂

**Comment by newbie78** [comment]
thanks for the answer!
I meant the substitution of the current language, and not some specific as in your example

**Comment by posva** [comment]
Ahh, you need to use the `append` prop on a router-link: http://jsfiddle.net/m5237fsu/
