### ISSUE TITLE
Question: Placeholder for scripts per route

### ISSUE THREAD

**Issue by kfirba** [vuejs/vue-router#188]
Hello.

I was trying to figure out a way to have a placeholder element which may contain js scripts that are relevant to the current viewed route.

At the moment I have some markup which has a div with the id `#app` and then I mount the router on it. 

The way I currently "control" my layouts is by using sub-routes. I have a `<default-template>` component which I want to use for most of my pages. Now I have in my `routes.js`:

``` js
router.map({
            '/': {
                component: require('./pages/home.js')
            },

            '/auth': {
                component: require('./components/auth.js'),
                subRoutes: {
                    '/login': {
                        component: require('./pages/login.js')
                    },
                    '/register': {
                        component: require('./pages/register')
                    }
                }
            }

        })
```

Let's take a look at the `/auth` route tree. the `/auth` component is simply a template that utilises the `<default-template>`:

``` js
module.exports = {
    template: '<default-template><router-view></router-view></default-template>'
}
```

Now my sub-routes are simply defining the `content` area.

`<default-template>`:

```
<nav-component></nav-component>
    
    <slot></slot>

<footer-component></footer-component>
```

So essentially the `<router-view></router-view>` is being injected in the `<slot></slot>` which let me just have the content area without repeating the template.

The issue is that I can't really have some placeholder for some scripts that I want to be applicable only on certain pages.

Currently the way I'm trying to do this is to have my scripts in the `ready()` method on my components. I really don't like this idea since it feels messy.

Is there some hook that I can attach to some global component that is always being called on any route change which I can maybe put all of the scripts loading logic in there?

**Comment by yyx990803** [comment]
Why is the script in `ready` messy? I don't get it.

**Comment by kfirba** [comment]
@yyx990803 the `ready` method isn't messy, yet.. I'm just afraid that if I will need to load many scripts in a view the `ready` method will get bloated. I just thought that it will be very nice to have some dedicated spot to include all of our view specific scripts and "un-load" them when we de-activate the view so prevent collisions.

**Comment by amirrustam** [comment]
@kfirba I'm not fully understanding what you are trying to accomplish, but to generally answer you last question, yes there are two global hooks that are are called for all transitions:

- [`router.beforeEach`](http://vuejs.github.io/vue-router/en/api/before-each.html)
- [`router.afterEach`](http://vuejs.github.io/vue-router/en/api/after-each.html)

**Comment by amirrustam** [comment]
@kfirba If you are still having troubles with this, I suggest clearly asking your question within the [forums](http://forum.vuejs.org) where the community will be glad to help you out. Please close out this issue, since it does not conform to the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines). Thanks.
