### ISSUE TITLE
nested parameters in route resolve doesn't work

### ISSUE THREAD

**Issue by wendt88** [vuejs/vue-router#1880]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/wendt88/50wL7mdz/76097/](https://jsfiddle.net/wendt88/50wL7mdz/76097/)

### Steps to reproduce
router.resolve() passing parameters does not set parameters of its parent route (only if it is the default child route)

### What is expected?
in that example the routerlink of 'subroute' should contain the language parameter

### What is actually happening?
missing language parameter in 'subroute'-router-link

**Comment by posva** [comment]
if you want the language parameter to appear in the route is to use a relative path: `subroute` instead of `/subroute`

**Comment by wendt88** [comment]
how can I realize it? I solved it like: 

`<router-link :to="$router.resolve({ ... }).location.path.replace(/^\//, '')">...</router-link>`

but so I get no route match.

**Comment by posva** [comment]
I'm sorry I don't get what you mean. I hope you find this useful: https://jsfiddle.net/m6kozswu/
