### ISSUE TITLE
the method of router.back() won't working on <a href="#"> of iphone6s

### ISSUE THREAD

**Issue by seancy** [vuejs/vue-router#1881]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/cysean/xgrjzsup/4211/](https://jsfiddle.net/cysean/xgrjzsup/4211/)

### Steps to reproduce
1、click link "Go to Foo"

2、click link "Go to Bar"

3、click link "bar back to prev."

### What is expected?
we can write $router.back() in a callback of click event of  <a href="#"></a> on any platform.

### What is actually happening?
The method of $router.back() is not execute.

**Comment by posva** [comment]
Can you try with `@click.prevent`? I don't have an iPhone 6 to test it

**Comment by seancy** [comment]
I have changed the href attribute to href='javascript:;', then it works well.

**Comment by seancy** [comment]
when I append prevent modifier after click, like this:@click.prevent="goBack" , the router.back() works. thanks Posva.

**Comment by posva** [comment]
Ok, closing then, it looks like something specific to iPhone 6 browser
