### ISSUE TITLE
why I change router, but the url do not change?

### ISSUE THREAD

**Issue by Pasoul** [vuejs/vue-router#1883]
### Version
3.0.1

### Reproduction link
[https://mtest.xuetucn.com/index.html](https://mtest.xuetucn.com/index.html)

### Steps to reproduce
it happened in WeChat browser， and I use hash mode， for example: 
1、click banner, then go to the news page 
2、copy the location url

### What is expected?
the normal url is https://xxx.com/index.html#/news

### What is actually happening?
the url do not change, no matter what pages I enter, it is still https://xxx.com/index.html

---
wechat version is 6.5.19,
android version is 6.0.1,
vue version is 2.4.4,
vue-router version is 2.4.0

**Comment by Pasoul** [comment]
i find the problem will happen in https://mtest.xuetucn.com/index.html,but will not happen in https://mtest.xuetucn.com/index.html#/home

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
