### ISSUE TITLE
Hydration from SSR rendered code fails when using lazy-loaded route components

### ISSUE THREAD

**Issue by MrSlide** [vuejs/vue-router#1886]
### Version
3.0.1

### Reproduction link
[https://github.com/MrSlide/vue-ssr-lazy-load-hydration-issue](https://github.com/MrSlide/vue-ssr-lazy-load-hydration-issue)

### Steps to reproduce
- Clone repository
- Install dependencies using `npm install`
- Install Gulp globally using `npm install -g gulp`
- Get the project running using `gulp`, this should get a server started and open the app in the browser
- Check the browser console when loading the initial page, the warning `[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.` should appear

### What is expected?
Vue should wait for the async route component to finish loading before diffing the tree of the SSR content and the virtual DOM tree on the client side

### What is actually happening?
The SSR content has the async route component fully rendered, but on the client side when the app is mounted the async route component is not rendered yet, causing the virtual DOM tree to be different and throwing a warning

---
This works fine

```
// src/js/router/routes.js

import HomeView from '../views/index.js'

export default [
  {
    path: '/',
    name: 'home',
    component: HomeView
  }
]
```

This causes issues

```
// src/js/router/routes.js

export default [
  {
    path: '/',
    name: 'home',
    component: function () {
      return import('../views/index.js')
    }
  }
]
```

**Comment by posva** [comment]
Could you please provide a boiled down repro. You can follow the docs [here](https://ssr.vuejs.org) if you need some help. Thanks!

**Comment by MrSlide** [comment]
I simplified the reproduction repo, now it should be much easier to see how it's set up:
https://github.com/MrSlide/vue-ssr-lazy-load-hydration-issue

**Comment by posva** [comment]
Sorry, but by boiled down, I also mean no gulp, no webpack and no unnecessary features (for example no vuex). You should be able to create one using the docs in my previous comment

**Comment by MrSlide** [comment]
Ok I simplified it further. Gulp, Babel transpiling and other unnecessary features are removed. I didn't really see a way of getting rid of Webpack though, the Vue SSR documentation also refers using Webpack to get bundles for the client and the server.

https://github.com/MrSlide/vue-ssr-lazy-load-hydration-issue

**Comment by posva** [comment]
Check https://ssr.vuejs.org/en/routing.html#code-splitting
You need to wait for the router to be ready on the client side as well 🙂 

```js
const { app, router } = createApp();

router.onReady(function() {
  app.$mount('#app');
});
```

**Comment by MrSlide** [comment]
That makes sense. I feel a bit silly now.
Thanks for the help ;)
