### ISSUE TITLE
Typescript integration fails on beforeRoute* guards implemented on the class

### ISSUE THREAD

**Issue by silkentrance** [vuejs/vue-router#1888]
### Version
3.0.1

### Reproduction link
[https://gist.github.com/silkentrance/9caa45481329f6ef911bd5eae5dbb7c3](https://gist.github.com/silkentrance/9caa45481329f6ef911bd5eae5dbb7c3)

### Steps to reproduce
Just npm install vue-router, vue, and vue-class-component or integrate the gist into an existing project, adjusting the import paths where necessary.

Then run the server and navigate to root '/'.

In the console log there should now be multiple entries, with the outputs from beforeRouteEnter/beforeRouteUpdate missing. 

### What is expected?
The guards implemented on the class as methods must be called.

### What is actually happening?
The guards implemented on the class are never called.

---

Registering the beforeRouteEnter and beforeRouteUpdate and beforeRouteLeave hooks with Component.registerHooks() and then implementing these hooks on the class will not work as expected as vue-router still tries to access these guards directly from def.options, see below

https://github.com/vuejs/vue-router/blob/d539788df8394efe41c1534e1e9d1555aa2edbe2/src/history/base.js#L262

The solution will be to also query the methods property of these options and return the available guards from there, e.g.

```
  if (def.options[key]) {
    return def.options[key];
  }
  return def.options.methods ? def.options.methods[key] : null;
```

I can prepare a PR for this, if you like.

**Comment by silkentrance** [comment]
Darn, so much work. Yet, the error lies in vue-class-component.
Closing.

**Comment by babielmam** [comment]
I ran into the same issue and ask to reopen the issue, so it can be fixed.

**Comment by silkentrance** [comment]
@babielmam I issued this over at https://github.com/vuejs/vue-class-component/issues/193

The solution is to register the hooks in a separate file, see the updated gist.

https://gist.github.com/silkentrance/9caa45481329f6ef911bd5eae5dbb7c3
