### ISSUE TITLE
Make "component" a required property for a route

### ISSUE THREAD

**Issue by danidee10** [vuejs/vue-router#1892]
### What problem does this feature solve?
It improves the developer experience. Currently if a developer omits or misspells the component key of a route object `({ path: '/foo', Component: FooComponent })` Notice the Capital letter in Component.

No warning is shown (A blank page would be rendered since the path has no Component defined on it), There's already a warning if a developer tries to use a String as a Component. I believe this would also be useful as there's no point having a route that doesn't point to any Component.

### What does the proposed API look like?
There's no change to the API.

**Comment by posva** [comment]
Unfortuntaely, this is actually not possible because you can redirect in the `beforeRouteEnter` to somewhere else, therefore, `component` (or components or redirect) is not required 🙁
