### ISSUE TITLE
API for handling events from routed components

### ISSUE THREAD

**Issue by chriscasola** [vuejs/vue-router#1895]
### What problem does this feature solve?
The [documentation](https://router.vuejs.org/en/essentials/passing-props.html) already recommends avoiding using `$route` in routed components because it couples the component to the route.

There is API to avoid the coupling when passing params in from the route, but there is no API for handling events emitted by the routed component.

My use case is I'd like to use a component in one place where an interaction should cause a route change, and in another place where the same interaction needs to be handled without changing the route.

### What does the proposed API look like?
I think I'd like some way to add a handler for the component events in the route definition, similar to how you can pass a `props` argument, maybe there could be an `events` property?

I was thinking something like this:

```javascript
const router = new VueRouter({
  routes: [
    {
      path: '/promotion/from-newsletter',
      component: Promotion,
      props: { newsletterPopup: false },
      events: {
        promotionAccepted: function() {
          router.push('/promotion/accepted');
        }
    }
  ]
})
```

**Comment by posva** [comment]
> There is API to avoid the coupling when passing params in from the route, but there is no API for handling events emitted by the routed component.

I'm sorry, but I don't get this. You can already listen to events in the `router-view` component.
It looks to me that you want to move a userland abstraction layer to the router, which is something is better to prevent to leave vue-router as agnostic as possible

**Comment by chriscasola** [comment]
I don't think listening to events in the `router-view` component really solves my problem either, because then I'll just end up with a bunch of `v-on` bindings on the main `router-view` in my app. The route config is where all of the logic about what views to show when is located, so it seems like that would be the place to also locate changes to the current route.

Maybe [this jsfiddle](https://jsfiddle.net/fjLufwLz/1/) clarifies my issue more?

**Comment by posva** [comment]
Listening to events on the router view is fine, but you have more alternatives like dispatching actions with vuex or wrapping the component that emits with a view component, so you can `$router.push` in the view component.
As I said, it's better to leave this kind of abstractions out of vue-router since they're already doable in user land

**Comment by chriscasola** [comment]
A wrapper component could also be used to pass props into a component, which would negate the need for the already existing router API to pass params into a component.

I still think there is value in a way to receive events from a routed component. Being able to see the inputs to a routed component, and the outputs, where the route is defined avoids needing to scan through the component itself or the vuex state to figure out how the routed component proceeds to the next route.

Is there any chance of this issue being considered further?

**Comment by posva** [comment]
To be clear, I see the value on this, but I'm super skeptical. I do think it plays nicely with the props feature but it can be done [on userland](https://jsfiddle.net/fjLufwLz/2/):

```js
function wrapView(component, { events }) {
  return {
    functional: true,
    render: (h, { data, children }) => h(component, {
      on: events,
      ...data
    }, children)
  }
}
{
      component: wrapView(Login, {
        events: {
          login: () => router.push('/welcome')
        }
      }),
      path: '/login',
}
```
(it ~~should be~~ is possible to adapt this [to props](https://jsfiddle.net/fjLufwLz/5/) btw)

I do think it's worth thinking a bit more about it though because it would make testing view components much easier.

**Comment by posva** [comment]
Closing as this hasn't received enough interest
