### ISSUE TITLE
[feature request] Could i use 'append' in $router

### ISSUE THREAD

**Issue by yoyo837** [vuejs/vue-router#1899]
### What problem does this feature solve?
`/order/123`
`this.$router.append('cancel')`
`/order/123/cancel`

### What does the proposed API look like?
append current path

#911

**Comment by posva** [comment]
Do `router.push({ path: 'foo', append: true })`

**Comment by melunar** [comment]
thks

**Comment by thebrownfox** [comment]
This should be a part of the docs.
