### ISSUE TITLE
在部分浏览器中会自动过滤参数中的中文

### ISSUE THREAD

**Issue by changexbc** [vuejs/vue-router#190]
在osx 10.11safari和ios 9.0.2的safari浏览器中会自动过滤参数中的中文，需要encodeURI()和decodeURI来解决
```
<a class="card-item" v-link="{
	name:'car-edit',
	params:{
	    license:encodeURI(car.carLicense)
	}
}">
```

**Comment by yyx990803** [comment]
请确保你的页面有 `<meta charset="utf-8">`。

**Comment by changexbc** [comment]
@yyx990803 
jsfiddle上的meta是utf-8的，我把vue-router基本用法中在线实例稍微改了一下，传递了一个中文的参数，在safari下就无法显示中文了
http://jsfiddle.net/zhangjia/eacvd2tj/1/
