### ISSUE TITLE
beforeEach() hook not called 2nd time when next() redirects to origin

### ISSUE THREAD

**Issue by fjelsted** [vuejs/vue-router#1900]
### Version
3.0.1

### Reproduction link
[https://codepen.io/fjelsted/pen/WXJvKa](https://codepen.io/fjelsted/pen/WXJvKa)

### Steps to reproduce
Press the shown links in the following order: A -> B -> B

### What is expected?
The letter C to be green

### What is actually happening?
The letter C turns red

---
In the beforeEach() hook I am determining whether to show the navbar based on the route path's meta properties. The visibility-boolean is kept in a Vuex store.

If the user attempts to access "/settings" (with visible navbar) while unauthorized, they will be redirected to "/sign-in" (hidden navbar). Pressing the browsers back button will result in staying on "/sign-in" but with a visible navbar.

Still very much a noob at Vue, at Javascript, at life in general... is this a dumb way of doing it? Anyways, this is not the place. Just in case I had missed something glaringly obvious. :)

I'm pretty sure the bug happens because the origin and destination paths match, therefore no beforeEach() hook is called a second time.

**Comment by fjelsted** [comment]
On second thought, is it bad practice to change the state in the beforeEach hook? If so, perhaps this is expected behavior and not a bug?

**Comment by posva** [comment]
Check the guard `beforeRouteUpdate` in docs, that's what you're looking for 🙂 

---
Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first.

**Comment by fjelsted** [comment]
Apologies, but I believe you are mistaken. I have made the change and used `beforeRouteUpdate`: https://codepen.io/fjelsted/pen/BmxzXa

The same problem occurs. This is the console output on the sequence A-B-B:
> "from: /A" "to: /B" "goRed" "redirect: /C"
"from: /A" "to: /C" "goGreen"
"from: /C" "to: /B" "goRed" "redirect: /C"

`beforeRouteUpdate`, and other hooks for that matter, seems to only be called when the paths of origin and destination differ. From the docs:
> beforeRouteUpdate (to, from, next) {
    // called when **the route** that renders this component **has changed**,
(...)

Perhaps this will make it more clear. Same sequence, A-B-B:
- *press link A*
- Go to `/A` from `/`; call router hooks
- Render `/A`
- *press link B*
- Go to `/B` from `/A`; call router hooks
- Unauthorized; redirect to `/C`
- Go to `/C` from `/A`; call router hooks
- Render `/C`
- *press link B*
- Go to `/B` from `/C`; call router hooks
- Unauthorized; redirect to `/C`
- Go to `/C` from `/C`; **no change, thus no hooks called**

Now, this is a matter of opinion. Should the hooks be called at the final step? I'd say yes because even though you don't see it, behind the scenes the router goes: `/C` -> `/B` -> `/C`. Shouldn't the hooks reflect the actual routing? However, if you actually went `/C` -> `/C`, then no hooks should be called.

At least that's what I think. :)

**Comment by posva** [comment]
Oh, sorry I did misunderstand what you were trying to say. It's working as expected because there's no hook executed if you don't change the url. In your case, you cannot go to /C because you're already on /C

**Comment by fjelsted** [comment]
I found a solution and I feel pretty dumb now. :) For anyone else who might stumble upon this, simply add a conditional to check `from.path` before redirecting (https://codepen.io/fjelsted/pen/eerMZN):
```javascript
router.beforeEach((to, from, next) => {
  if (to.path === '/B') {
    if (from.path !== '/C') {
      store.commit('goRed')
      next({ path: '/C' })
    } else {
      next(false)
    }
  } else {
    store.commit('goGreen')
    next()
  }
})
```
Generally don't change the state if you call `next(false)`

Thanks for the clarification, @posva 👍
