### ISSUE TITLE
Pass props via router-link

### ISSUE THREAD

**Issue by MartinMuzatko** [vuejs/vue-router#1901]
### What problem does this feature solve?
It is possible to pass props via the defined routes. Unfortunately, I can't get the complete object passed to the `to` attribute from the route props function.

routes:
```js
routes: {
    {
        path: '/device/:id',
        component: load('device/DeviceView'),
        props: (route) => { console.log(route) // does not contain route.props }
    }
}
```

template
```html
<router-link :to="{path: `device/${device.UniqueID}`, props: {device: device}}">show device</router-link>
```

### What does the proposed API look like?
Same as above. I would like to pass the props via `router-link`:
```html
<router-link :to="{path: `device/${device.UniqueID}`, props: {device: device}}">show device</router-link>
```

**Comment by posva** [comment]
Hi!
Sorry, but we intentionally leave _hidden_ state out of vue-router. In other words, if it's not in the url, it should be stored somewhere else, like in a vuex store. 

For you specific scenario, you could inject the `device` by using the unique id in the props function

**Comment by FullStackAlex** [comment]
@posva 
> if it's not in the url, it should be stored somewhere else, like in a vuex store.

But what if I have 100 router-links on a page and I need on a click related data which is only available at the time of looping through the links at the HTML / template level ? A @click listener doesn't work on router-links. Currently I would have to build custom, complicated mapping functionality and custom route listener to be able to send data via vuex store . Makes absolutely no sense to me. 

So what is actually the intention by not allowing to append data to router-link?

**Comment by FullStackAlex** [comment]
just found this here! [https://github.com/vuejs/vue-router/issues/800](https://github.com/vuejs/vue-router/issues/800)  🎉😁
So now I can use vuex store to transmit the data. 

But would still love to find out the reason why exactly it's not possible to send data with router-link for example as a data property: $router.data
