### ISSUE TITLE
Using router-link in v-for, children are treated as root path

### ISSUE THREAD

**Issue by launchriot** [vuejs/vue-router#1905]
### Version
3.0.1

### Reproduction link
[http://jsfiddle.net/avizuber/c1mo5371/8/](http://jsfiddle.net/avizuber/c1mo5371/8/)

### Steps to reproduce
Click on "Home", "Foo", "Projects". These are all root paths. Then click (or just hover over to see url in bottom-left of browser) "Web" and "Mobile".

### What is expected?
Per the docs, children without a slash, e.g. path: 'foo', should be rendered as '/parent/foo'

### What is actually happening?
Children are being treated as root paths. Instead of  '/projects/web', it is '/web'.

---
Could be "solved" be manually setting path to '/parent/child' in the path of each child. Seems to conflict with docs.

**Comment by posva** [comment]
Use `append` on router-link that need to append a url. For your example is better to compute the actual path of the link beforehand though.

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by launchriot** [comment]
Thanks! I thought it was a bug because it's not working as described in the documentation.
On this page https://router.vuejs.org/en/essentials/nested-routes.html, it offers this syntax
```
const router = new VueRouter({
  routes: [
    { path: '/user/:id', component: User,
      children: [
        {
          // UserProfile will be rendered inside User's <router-view>
          // when /user/:id/profile is matched
          path: 'profile',
          component: UserProfile
        },
        {
          // UserPosts will be rendered inside User's <router-view>
          // when /user/:id/posts is matched
          path: 'posts',
          component: UserPosts
        }
      ]
    }
  ]
})
```
which is what I modeled my routes after:

```
const router = new VueRouter({
  mode: 'history',
  routes: [
    { path: '/',component: Home },
    { path: '/foo',component: Foo },
    { path: '/projects',
      component: Projects,
      children: [
        {
          path: 'web',
          component: WebProjects
        },
        {
          path: 'mobile',
          component: MobileProjects
        }
      ]
    }
  ]
})
```
The docs then say "**Note that nested paths that start with / will be treated as a root path. This allows you to leverage the component nesting without having to use a nested URL.**", which to me infers that nested paths that **do not** start with / will **not** be treated as a root path.

I'll check out the forum and whatnot (thanks for including those links), but I do think the docs are a little confusing.

FWIW, `append` didn't work in this instance.

**Comment by posva** [comment]
yeah, you got what the docs say... I don't see the matter here, sorry. Good luck in the forums 🙂

**Comment by posva** [comment]
I'm interested if you have suggestions on how to improve the docs because I don't see what confused you

**Comment by launchriot** [comment]
The docs seems to say that children did not require a "/", but when I wrote
my code I needed to include the "/". I also missed the part that said child
routes needed a different <router-view/> within the parent. As of now my
children still need a funky path to work:

      children: [
        {
          path: '*/projects/*web',
          name: 'Web Projects',
          component: WebProjects,
          meta: {appLayout: true, theme: 'default', parent: 'projects'}
        },

**Comment by posva** [comment]
Using just `projects/web` will lead to `/users/:id/projects/web`
