### ISSUE TITLE
The route parsing behavior of `redirect` in configuration is different from `push()` method

### ISSUE THREAD

**Issue by caikan** [vuejs/vue-router#1910]
### Version
3.0.1

### Reproduction link
[https://jsbin.com/cikacabasa/1/edit?html,js,output](https://jsbin.com/cikacabasa/1/edit?html,js,output)

### Steps to reproduce
click the link: `/redirect`.

### What is expected?
show `id: 222`, like using `push()` method.

### What is actually happening?
show `id: default id`.
the `params` property in prototype has been ignored.

**Comment by posva** [comment]
The location you redirect to should be a plain object:

```js
let loc = {name: 'target', params: {id: 222}};
```

**Comment by caikan** [comment]
@posva
But why can the `push()` method accept `params` from prototype?
I think the behavior of parsing location should be consistent.

**Comment by posva** [comment]
It's just a coincidence but it was not meant to be used like that
