### ISSUE TITLE
Dynamic import splits code but doesn't lazy load

### ISSUE THREAD

**Issue by folmert** [vuejs/vue-router#1915]
### Version
3.0.1

### Reproduction link
[https://github.com/folmert/vue-lazy-loading](https://github.com/folmert/vue-lazy-loading)

### Steps to reproduce
1. `npm install`
2. `npm run start`
3. open app with Network tab in Chrome, refresh if requests are not there
4. all bundles are loaded up front (moin.bundle.js, hello.bundle.js, bye.bundle.js) while only 1 is needed

### What is expected?
Lazy loaded bundles (moin.bundle.js and bye.bundle.js) shouldn't be loaded on initial page load.

### What is actually happening?
Bundles which were supposed to be lazy loaded are loaded up front on initial page load (moin.bundle.js and bye.bundle.js).

---
Following guide was used for introducing lazy loading into router:
https://router.vuejs.org/en/advanced/lazy-loading.html

**Comment by posva** [comment]
That is because you're using the PWA template that does precaching, it's actually a good thing
