### ISSUE TITLE
在route上面增加isEventChange属性判断是否是事件改变的路由还是调用方法改变的路由

### ISSUE THREAD

**Issue by agileago** [vuejs/vue-router#1916]
### What problem does this feature solve?
有时候需要知道是否是用户主动调用方法改变的路由还是点击导航栏或者左滑返回改变的路由，以处理动画效果，比如ios上面用户左滑返回上一个路由，需要在beforeEach里面判断是调用方法触发的还是 `hashchange`或者 `popstate`事件触发的，来处理要不要拥有返回动画，如果是左滑返回的话就不用做动画效果了

### What does the proposed API look like?
```javascript
router.beforeEach((to, from, next) => {
  if (to.isEventChange) {
    // 不处理动画 
  } else {
    // 处理返回动画
  }
})
```

**Comment by posva** [comment]
Are you asking for a way to know if the action came from a user action or not?

**Comment by agileago** [comment]
yes

**Comment by posva** [comment]
Sorry, I meant if the action came from clicking somewhere.
What may be possible is to add some flag if the navigation is called from a `push` or similar but I'm unsure of this being very reliable because using `next` should remove this flag but some people may be expecting to have it.
For the moment it's still doable in userland because as the dev, you know best where the action came from

**Comment by agileago** [comment]
only browser trigger router change should add this prop. because the vue-router handle the router event. i think it should be apply on `vue-router`

**Comment by posva** [comment]
Can you give some examples to better understand, please 🙂 ?

**Comment by agileago** [comment]
### IOS left slide back
when you do a transition in router-view. you should judge the behavior is `back` or `forward`. like this 
```vue
<template>
  <div>
    <h2>transition router-view</h2>
    <transition :name="viewTransition" :css="!isEventChange">
       <router-view />
    </transition>
  </div>
</template>


<script>
  export default {
    data () {
      return {
        viewTransition: 'forward',
        isEventChange: false
      }
    }
  }
</script>
```

when you click the browser back navigator. you should do a back transition. but when you do left slide back using hand. you don't want to do transition in `router-view`. so far. we use overwrite the router methods to hack this.  but it is not a perfect solution.

see example
https://vux.li/demos/v2/?x-page=v2-doc-home#/

the code solution
https://github.com/airyland/vux/blob/v2/src/main.js#L147

**Comment by posva** [comment]
So, you only need to know if `popstate` was used to navigate? (#14)

**Comment by agileago** [comment]
almost. i don't need know the direction. just want to know the router change is the `event change` or `user change (by click or js)`. but `hachchange` should also handle the same behavior

**Comment by posva** [comment]
But vue-router cannot guess if the action comes from a user action or not 🙁

**Comment by agileago** [comment]
of course vue-router can do it. wait a time. i will do a pr.

**Comment by posva** [comment]
If it's patching `push` and other methods, that's not enough.
Functionally speaking, what is the feature you want to achieve?

**Comment by agileago** [comment]
I just know the router change is by the user click browser navigator(include ios swipe back) or by router method execute (push, go, forward, back, replace, include router-link)

**Comment by h330894169** [comment]
这个问题有新进展了吗？@ @agileago

**Comment by cqgsm** [comment]
同问，这个问题有进展了吗？

**Comment by luckymore** [comment]
Why not add the `isEventChange` prop by yourself?

**Comment by icefee** [comment]
同问，这个问题有进展了吗？

**Comment by posva** [comment]
knowing if the action came from a user action or not is not doable in vue-router. Not even sure if it's possible in userland as well for all cases, but should be possible in specific scenarios
