### ISSUE TITLE
make the params can be use in object mode

### ISSUE THREAD

**Issue by lasthrun** [vuejs/vue-router#1925]
### What problem does this feature solve?
you can use params in the object mode, that will make the object mode be more powerful and flexable.

### What does the proposed API look like?
path: ':id'
props: {
  id: $params.id, //or
  id: $id, //or
  id, //auto check the params by name
  check: true
}

**Comment by JounQin** [comment]
So where can we get the reference of your `$params`?

Just use a function, it is so easy to do that.

**Comment by lasthrun** [comment]
First, these types of descriptions will be more flexible and make sense. you are right, function is easy to do that. but it doesn't meet the user first mind.
secondary, if object mode does not support to get the params, It will be too restrictions. it just only for the static case.

**Comment by posva** [comment]
You can add this yourself very easily 🙂:

```js
Object.defineProperty(Vue.prototype, '$params', {
  get () { return this._routerRoot._route.params }
})
```

(this is also how `$route` and `$router` are defined).
For vue-router is easier to just have `$route` and let user access anything from there

**Comment by lasthrun** [comment]
sad :(
i will try to do it by myself. can you lead me which file should i work on?

**Comment by posva** [comment]
you don't need to add it to the original vue-router code, just add it in your `main.js` file after installing vue-router 😉
