### ISSUE TITLE
this.$router in setTimeout doesn't work

### ISSUE THREAD

**Issue by tonywangcn** [vuejs/vue-router#1927]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/mu6f7zj6/](https://jsfiddle.net/mu6f7zj6/)

### Steps to reproduce
click Go to Foo , and console said Cannot read property 'push' of undefined.

### What is expected?
1s after clicked Go to Foo should redirect to '/' (home), and 'foo' should disapear

### What is actually happening?
Cannot read property 'push' of undefined.

**Comment by JounQin** [comment]
There's nothing related to Vue, that's because you're using wrong `this` context is `setTimeout` callback.

You should learn more about pure js before using Vue.

**Comment by tonywangcn** [comment]
solved by add "var self = this, self.$router.push()"

**Comment by al-hassan-cse** [comment]
"tonywangcn"  Good Job
