### ISSUE TITLE
用<a href='#'>封装的button组件，点击时路由在ie9上表现与ie>=10以及chrome上表现不一致

### ISSUE THREAD

**Issue by mygaochunming** [vuejs/vue-router#1929]
### Version
3.0.1

### Reproduction link
[https://github.com/mygaochunming/vue-router-bug](https://github.com/mygaochunming/vue-router-bug)

### Steps to reproduce
运行“重现链接”中的“项目”，
1、点击“/foo”,下面显示/foo；
2、点击“/bar”，下面显示/bar;
3、点击“href="#"”,下面还是显示/bar(chrome,ie>=10),下面为“空”(ie=9)

### What is expected?
在ie9下也显示/bar

### What is actually happening?
显示为空

---
在项目中button组件是用\<a href=\"#\" \>封装的。项目在chrome或者ie>=10上表现没有问题，但在ie9上，每当点击button组件时，路由就会重定向到path: “/”而清空router-view组件中的内容。

**Comment by posva** [comment]
Adding an anchor to the page should not change the route. You may want to check #1911

**Comment by mygaochunming** [comment]
@posva I come back to say thanks!
