### ISSUE TITLE
Loading with Browserify

### ISSUE THREAD

**Issue by Ben52** [vuejs/vue-router#193]
I installed with `npm install vue-router --save`. However when I attempt to use the package using CommonJS and Browserify, I get an error that the module could not be found. Looking in the package.json, it sets `"main": "lib/index.js"`, which doesn't exist after a simple npm install. What would be the best way to load the module with Browserify?

**Comment by Ben52** [comment]
For a temporary solution I am inserting into my package.json
```
  "browser": {
  	"vue-router": "./node_modules/vue-router/dist/vue-router.js"
  }
```

**Comment by yyx990803** [comment]
Sounds like your npm didn't install correctly. Just tried a fresh install and `lib` is there.

**Comment by Ben52** [comment]
I see what the problem is. I had installed with `npm install vuejs/vue-router#devnpm install vuejs/vue-router#dev --save`
That install does not come with a lib directory.
