### ISSUE TITLE
Why is route.props updated with a delay?

### ISSUE THREAD

**Issue by dimensi** [vuejs/vue-router#1934]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/k6qxo3z3](https://codesandbox.io/s/k6qxo3z3)

### Steps to reproduce
set to route `props: route => ({ ..route.query })`
try change props via router.push()

### What is expected?
I expect to see that if the query changes, then the props will change immediately.

### What is actually happening?
First, the query changes, and then the route props changes after nextTick

**Comment by posva** [comment]
Because props need to be propagated. Here's an example without vue-router: http://jsfiddle.net/posva/xcLov89k/

**Comment by dimensi** [comment]
@posva hm, i not understand, why this happing?

**Comment by posva** [comment]
The navigation is synchronous (eg you can remove the existing `await`) but vue will propagate props modification and re render dom asynchronously. Basically, this is in Vue by design

**Comment by dimensi** [comment]
if navigation is sync, why we can add callback on complete?

**Comment by posva** [comment]
Sorry, I meant in your case it is, it can be async if there's a transition or a before* hook

**Comment by dimensi** [comment]
@posva thx for answers. I use vue for 7 months and for the first time met such a problem.
