### ISSUE TITLE
Cant redirect continuously when the path is dynamic

### ISSUE THREAD

**Issue by wangyi7099** [vuejs/vue-router#1938]
### Version
3.0.1

### Reproduction link
[https://codepen.io/wangyi7099/pen/JMdRYq](https://codepen.io/wangyi7099/pen/JMdRYq)

### Steps to reproduce
As I want to set the default render component when the parent component was rendered. so I use redirect  to redirect to the component I want to render for the default. But it seems not to work, when I want to redirect component  continuously when the path is dynamic.And the console shows the warning:" [vue-router] missing param for redirect route with path "/:bigCata/smallCata": Expected "bigCata" to be defined"

### What is expected?
The default components can be rendered.
When I click the ```<a href="/index"></a>``` -> redirect to the path:"/index/bigCata/smallCata"
### What is actually happening?
It doesn't redirect to the smallCata..

**Comment by posva** [comment]
Use named routes (add a `name`) when using object navigation with params. For you last redirect, you need to specify `bigCata` param as well
