### ISSUE TITLE
next in beforeRouteEnter support to return a Promise

### ISSUE THREAD

**Issue by leaves4j** [vuejs/vue-router#1939]
### What problem does this feature solve?
Avoid callback

### What does the proposed API look like?
```js
async beforeRouteEnter(to, from, next) {
  //do something
  const vm =  await next();
  //do something with vm
}
```

**Comment by posva** [comment]
Given the only benefit of this would be to avoid using a callback in a method (`beforeRouteEnter()`) that is only used sometimes and the very little activity in it, we don't think this should be added. If you still think it's worth adding, you should follow the RFC process in the vuejs/rfcs repository
