### ISSUE TITLE
userService.get(userId)  这里的userService是如何实现的  ？？

### ISSUE THREAD

**Issue by xiaolongyuan** [vuejs/vue-router#194]
route: {
  data: function (transition) {
    var userId = transition.to.params.userId
    return {
      user: userService.get(userId),
      post: postsService.getForUser(userId)
    }
  }
}

userService.get(userId)  这里的userService是如何实现的  ？？

 data: function(transition){
                                // GET request
                                return {
                       profile:this.$http.get('/api/profile/'+new Date().getTime())
                                    }

vue-resource 里面难道没有实现？

 component: {
                        template: '<p>This is bar/,value is {{profile.token}}</p>',
                        route: {
                            data: function(transition){
                                // GET request
                                return this.$http.get('/api/profile/'+new Date().getTime())
                                    .success(function(data, status, request) {
                                        // set data on vm
                                        this.$set('profile', data)
                                    })                                
                            }
                        }
                    },

如何简化？

**Comment by yyx990803** [comment]
1. 请用 markdown 格式化代码。
2. 提问请条理清楚一些，我看不懂你想问什么。
