### ISSUE TITLE
Router transition hooks aren't being fired on top-level Vue instance that the router is mounted on

### ISSUE THREAD

**Issue by kfirba** [vuejs/vue-router#195]
Hello.

I have an SPA built with Vue-router. The main component which the router is mounted on isn't triggering the route transition events such as `activate` and `data`.

My router start code looks something like:

```js
const App = require('./app')
router.start(App, '#app')
```

Now in my `app.js` I handle my application state and check if the user is logged with a token and everything. My `app.js` template is a simple `<vue-router></vue-router>`. 

I tried adding this to my `app.js`:

```js
route: {
        activate: function (transition) {
            console.log('activate hook')
            transition.next()
        },

        data: function (transition) {
            console.log('data hook')
            transition.next()
        },

        canActivate: function (transition) {
            console.log('can activate hook')
            transition.next()
        }
    },
```

The above doesn't seem to work as there is no output at all in the console.

Why is that happening? I want to use the `activate` hook in order to check if I have a token in my local storage and if there is, fetch the user from the server. As it currently stands, I try to do this from my `ready` Vue lifecycle hook,  but since the fetching is returning a promise it doesn't wait for the promise to resolve and continues compiling the route which leads to errors in console that the `$root.user` is null.

**Comment by yyx990803** [comment]
The root instance is always there no matter what route you are at, why do you need route hooks for it? Just use its own component lifecycle hooks.

**Comment by kfirba** [comment]
Another disturbing finding:

I tried to move the logics of when to retrieve the user profile if the user is already logged in to the root URL for my logged in users. In my case it's the `/account` root as defined in my `routes.js`:

```js
'/account': {
                auth: true,
                component: require('./pages/account'),
                subRoutes: {
                    'collections': {
                        component: require('./pages/collections/all')
                    }
                }
            }
```

So basically the `account.js` component has to get rendered before all other sub-routes.

In my `account.js` file I added some code to the `activate` hook:

```js
route: {
        activate: function (transition) {

            var token = localStorage.getItem('jwt-token')
            try {
                var id = jwtDecode(localStorage.getItem('jwt-token')).sub
            } catch (e) {
                this.$dispatch('userHasLoggedOut')
                return
            }

            return this.$http.get('users/'+ id + '?include=profile', function (data) {
                this.$dispatch('userHasLoggedIn', data.data)
            }).error(function () {
                // nope, our token got denied, let's make sure we logout
                this.$dispatch('userHasLoggedOut')
            })

        }
    }
```

Since the activate returns a promise AND accepts a transition argument, it should be asynchronously but when I view the result, it seems like the route I'm navigating to is already trying to access properties that I'm trying to fetch. The only difference now is that the view it self isn't being shown before I fetch the user properly but I do get the warnings in the console.

Just so I make sense, here are some of the files:

account.html
```html
<account-template>
    <router-view></router-view>
</account-
```

account-template.html:
```html
<account-nav></account-nav>

<slot></slot>
```

account-nav**.html** (the culprit section of the file):
```html
<!-- ... more -->
<a href="#">
    <i class="fa fa-user account-nav-icon"></i>
     <div class="account-nav-text">{{ fullName }}</div>
</a>
<!-- ... more -->
```

account-nav**.js**:

```js
module.exports = {

    template: require('./account-nav.html'),

    computed: {
        fullName: function () {
            // this line of code produce an error at initial rendering
            return this.$root.user.profile.data.first_name + ' ' + this.$root.user.profile.data.last_name
        },
    }

}
```

Just to make it clear, the flow is as follows:

1. The user is already logged in and there is a token in storage
2. The user access any sub-route of `/account/*` which requires authentication which is set to true if there is a token present in localStorage
3. Since all of these views needs the user's profile, the "master" `account.js` component is trying to fetch it in the `activate` hook and returns a promise
4. for some odd reason, I get warnings in console about trying to access property of null coming from `account-nav.js` computed property -- which simply means that the promised hasn't yet been resolved
5. The promise is being resolved and I can only then actually see the view with the proper data instead of a blank page (blank page is displayed until we resolve the promise)

It just seems like the `account.html` template is being compiled in parallel to the transition hooks of `account.js` which is odd.

**Comment by kfirba** [comment]
@yyx990803 I also tried any lifecycle hook for that. It just doesn't work. Since I'm sending a sync HTTP request it doesn't wait for the promise to resolve and starts compiling the current route. If it helps, take a look at my previous comment please.

**Comment by yyx990803** [comment]
It's hard to grok your issue without seeing a live repro, but auth validations should be done in the `canActivate` hook instead of the `activate` hook.

**Comment by kfirba** [comment]
@yyx990803 I will try to make a repo here so you can inspect it. Meanwhile, while trying to add my user fetching to the `canActivate` hook it seems like that the `this` keyword is `null` so I can't make the requests to return a promise for some reason.

**Comment by kfirba** [comment]
@yyx990803  I've created a repo which you can look at. If you feel like something is missing, feel free to ask for it: https://github.com/kfirba/vue-router-issue-repo

**Comment by kfirba** [comment]
@yyx990803 I got a VERY messy solution which I'm really not proud of and don't want to use it in production. I altered the `canActivate` hook in `account.js`:

```js
canActivate: function (transition) {
    var that = transition.to.router.app

    var token = localStorage.getItem('jwt-token')

    try {
        var id = jwtDecode(token).sub
        } catch (e) {
            that.dispatch('userHasLoggedOut')
            return false
        }

    return Vue.http.get('users/'+ id + '?include=profile', function (data) {
        that.$dispatch('userHasLoggedIn', data.data)
    }).error(function () {
        // nope, our token got denied, let's make sure we logout
        that.$dispatch('userHasLoggedOut')
    })
}
```

This is really nasty. I mentioned above that there is no access to `this` in `canActivate` hook for some reason. it just returns `null`.

Note that I had to get some Vue component so I could dispatch an event with `transition.to.router.app` and also I had to use the `Vue.http` global. I also couldn't extract any method because if I tried to call it it would return an error as `this` is `null`.

Even though it works, it just feels messy and I don't want to rely on this.

**Comment by aidistan** [comment]
@yyx990803 

> The root instance is always there no matter what route you are at, why do you need route hooks for it? Just use its own component lifecycle hooks.

The `data` hook provided by `vue-router` is great for loading data asynchronously. However the root component won't trigger this hook when we try to load some app-level data, and its lifecycle hooks are all synchronous which don't fit our need.

@kfirba 

I suggest you to use a before hook instead:

```js
router.beforeEach((transition) => {
  if (!router.app.initialized) {
    router.app.loadData(transition.next)
  } else {
    transition.next()
  }
})
```

**Comment by lkiarest** [comment]
@yyx990803 I have tried to use the component lifecycle hooks "activate(done){}", but it didn't tigger either.
