### ISSUE TITLE
URL&Router not changed when use route params

### ISSUE THREAD

**Issue by qdechochen** [vuejs/vue-router#1950]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/qdechochen/L7hscd8h/3310/](https://jsfiddle.net/qdechochen/L7hscd8h/3310/)

### Steps to reproduce
1. click /user/foo/profile1 OK
2. click /user/foo/profile2 : content changed, but URL not changed if you run this directly in a browser.
3. click /user/foo/profile1:  nothing happend
4. click /user/foo OK
5. click /user/foo/profile2 OK
6. click /user/foo/profile1:  content changed, but URL not changed if you run this directly in a browser.
7. click /user/foo/profile2:  nothing happend

### What is expected?
1. In step 2, URL should be changed to /user/foo/profile2
2. in step 3, beforeRouteUpdate should be called.

For step 6 & 7, same thing.

### What is actually happening?
Maybe it's because the URL not change in step 2, beforeRouteUpdate is not called?

**Comment by posva** [comment]
You forgot to call `next` in beforeRouteUpdate
