### ISSUE TITLE
the beforeRouteLeave event of vue's first component is not trigger

### ISSUE THREAD

**Issue by francecil** [vuejs/vue-router#1951]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/gahing/c61ng9of/7/](https://jsfiddle.net/gahing/c61ng9of/7/)

### Steps to reproduce
（1）open https://jsfiddle.net/gahing/c61ng9of/7/ 

（2）Press the back button of the browser immediately

（3）Or wait for 2S ,browser will alert('main beforeRouteLeave happened')

my english is poor , that is chinese version as follows:

(1)打开该网址

(2)立刻按浏览器的后退按钮

(3)或者等待2s 出现alert弹框('main beforeRouteLeave happened')

### What is expected?
When 'Main' component is mounted，and the function of setTimeout is not happened,Press the back button of the browser immediately. I
 wish that the beforeRouteLeave event is triggered.

### What is actually happening?
It is not happen。bug when the code "this.$router.push('/user')" run, will trigger beforeRouteLeave

---
now, my solution is add component named 'BeforeMain' before Main component.
when BeforeMain'mounted trigger,run  "this.$router.push({name:'main'})"
Add 'beforeEach':
router.beforeEach((to, from, next) => {
  // gameview的
  if (to.name === 'beforemain' && from.name === 'main') {
    router.go(-1)
    next(false)
  } else {
    next()
  }
})
Thus,while current component is 'Main' ,you press back button of brower, you can trigger 'beforeRouteLeave'
But , it 's so trouble

Chinese version:
将第一个组件前再增加一个beforemain组件，做一次push跳转。这样main可以正常触发beforeRouteLeave

**Comment by posva** [comment]
The setTimeout still happens even though you go back, there nothing wrong here

**Comment by francecil** [comment]
setTimeout can happen,but the back evnet of browser can't happen
