### ISSUE TITLE
<router-link> scroll issue

### ISSUE THREAD

**Issue by anonim2214** [vuejs/vue-router#1954]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/u8egqj0q/](https://jsfiddle.net/u8egqj0q/)

### Steps to reproduce
Click to "router-link to Thirteen"

### What is expected?
The same behavior as when clicking <a href>(scroll to element, change window.location)

### What is actually happening?
Only App.$route changed

**Comment by MaximeAubry** [comment]
I have the same problem

**Comment by posva** [comment]
Hey, sorry for the delay, you need to setup scrollBehavior. BTW, you were not calling `next` in your beforeEach, making no navigation at all: https://jsfiddle.net/jp05wy9q/1/

Navigating on the same route doesn't work thought (see #1668)
