### ISSUE TITLE
Vuejs ssr check user is authenticated for each request

### ISSUE THREAD

**Issue by mymtw** [vuejs/vue-router#1956]
I’m using this ssr boilerplate for my app, https://github.com/vuejs/vue-hackernews-2.0

I don’t know how to implement logic for checking is user authenticated for each user’s page request, I’m using cookies for storing user's token

I looked that router can handle request before render component:
```
router.beforeEach((to, from, next) => {
    if (to.matched.some(record => record.meta.requiresAuth)) {
      // this route requires auth, check if logged in
      // if not, redirect to login page.
      // isLoggedIn()
      //   .then(response => response.json())
      //   .then(json => {
      //     console.log(json[0])
      //     next()
      //   })
      //   .catch(error => {
      //     console.log(error)
      //     next()
      //   })

      const x = true

      if (!x) {
        next({
          path: '/signin',
          query: { redirect: to.fullPath }
        })
      } else {
        next()
      }
    } else {
      next() // make sure to always call next()!
    }
  })

  return router
}
```

Here is problem, router starting to use this code in client-side and in server-side, which in my case a little bit incorrect.

How to send request for is user authenticated only once, or in client-side or in server-side?

**Comment by JounQin** [comment]
You should enable `beforeEach` hook first on server but wait for router ready on client, so that it will not call `beforeEach` hook again on client.

Here is an example.

https://github.com/JounQin/Rubick/blob/master/src/app.ts#L22
https://github.com/JounQin/Rubick/blob/master/src/entry-client.ts#L92

**Comment by mymtw** [comment]
@JounQin yes, thank you. But I already made something similar on your example, anyway thanks
I wrote check user middleware as below and it works, what is very cool: 
```
export function createRouter (cookies) {
  const router = new Router({ ... })

  router.beforeEach((to, from, next) => {
    // this route requires auth, check if logged in
    // if not, redirect to login page.
    if (to.matched.some(record => record.meta.requiresAuth)) {
      if (router.app.$store) {
        router.app.$store
          .dispatch('FETCH_CURRENT_USER', cookies)
          .then(() => {
            next()
          })
          .catch(() => {
            next('/signin')
          })
      } else {
        next()
      }
    } else {
      next()
    }
```
