### ISSUE TITLE
Issue in nested vue-route when refresh 

### ISSUE THREAD

**Issue by ksankumar** [vuejs/vue-router#1959]
### Version
3.0.1

### Reproduction link
[https://codepen.io/ksankumar/pen/rpwxNv](https://codepen.io/ksankumar/pen/rpwxNv)

### Steps to reproduce
Need a help in nested vue-route
Jan 01, 2018 12:57
I have more page.
By landing i wanna show either login or dashboard page.

In dashboard page i have some navigation menus. When i click items in menu, i want to show menu content in dashboard page.

### What is expected?
/dashboard ->dashboard page with menu
/menu1 -> menu content in dashbaord page with same menus

when i refresh /menu1 that menu and menu content should be persist

### What is actually happening?
in refresh menus got destroyed

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by ksankumar** [comment]
@posva I hope this is Bug or feature
