### ISSUE TITLE
router a-link方式切换正常 浏览器回退可导致未名bug

### ISSUE THREAD

**Issue by lazyhero** [vuejs/vue-router#196]
BUG demo
https://github.com/lazyhero/vue-spa-demo
说明图
![vue-router-bug-demo](http://7jpswm.com1.z0.glb.clouddn.com/bugrouter-bug-1.gif)

1.  通过v-link=“{path:'/routerName'}” 可以跳转 但通过具名路由形式v-link={name:‘routerName’} 一般在第二次重复切换时会发生异常

2.  通过页面上的v-link 进行路由间的B-->D-->D.A-->B 再通过页面链接到D-->D.A这是正常的

但是通过B-->D-->D.A-->B-->浏览器回退按钮-->D.A 无效

**Comment by lazyhero** [comment]
今晚在调试时 页面div复杂的子路由页面 也会出现地址栏更改 但是 视图未渲染的问题 但是会报错 报错函数是blockOp 报错信息为current.nextSibling undefined

**Comment by yyx990803** [comment]
更新到 0.7.4 了吗？

**Comment by lazyhero** [comment]
@yyx990803 是0.7.4 昨晚进行更新的

**Comment by lazyhero** [comment]
@yyx990803 转成了gh-page 直接可以看

**Comment by yyx990803** [comment]
看来是 `keep-alive` 的问题，暂时去掉就 ok 了。待我 debug 一下

**Comment by lazyhero** [comment]
@yyx990803  好滴~~ ^_^

**Comment by yyx990803** [comment]
发现不是 router 本身的问题，是 vue 对于 fragment instance 的移除有 bug。等 1.0.0-rc.2 吧，这里先关了
