### ISSUE TITLE
ie9&fallback=false has a error: 对象不支持“replaceState”属性或方法 

### ISSUE THREAD

**Issue by gaoyuan123** [vuejs/vue-router#1960]
### Version
3.0.1

### Reproduction link
[https://hello-world.nuxtjs.org/](https://hello-world.nuxtjs.org/)

### Steps to reproduce
1.vue init nuxt-community/starter-template test
2.cd test
3.npm install
4.open http://localhost:3000/ in ie9

f12 open console has a error

### What is expected?
no error

### What is actually happening?
[nuxt] Error while initializing appTypeError: 对象不支持“replaceState”属性或方法 

---
vue ssr 在ie下必须将fallback设置为false,跳转时刷新页面才能正确渲染
但是fallback设置为false的情况下HTML5History没有做容错处理:

    var expectScroll = router.options.scrollBehavior;

    if (expectScroll) {
      setupScroll();
    }

当配置了scrollBehavior的时候会调用setupScroll方法,导致报错

**Comment by clevergod** [comment]
@gaoyuan123 所以怎么处理呢 老哥
