### ISSUE TITLE
vue-router 无论是hash模式还是history模式在ios微信浏览器中无论进入哪个页面复制链接或选择safari打开都是第一次进入的那个页面

### ISSUE THREAD

**Issue by inmWang** [vuejs/vue-router#1962]
在ios微信浏览器中，vue+vue-router的项目无论点击哪个页面跳转到其他路由，选择复制链接或是用safari打开都是第一次访问的页面。之前的issues提到可以每次进入url用jssdk重新获取签名，实践发现：
1. ios每次访问变化的url，用该url调wx.config报错：invalid signature。
2.只在页面首次打开config一次也并不能解决。
3.每次打开变化的url，用第一次打开的url去调wx.config不会报签名无效的错误，但是复制链接依然是第一次打开的url。

**Comment by SeongBrave** [comment]
@inmWang 您好，您的问题解决了吗？我也遇到同样的问题了
