### ISSUE TITLE
How to create a separate file which consist of common modules shared between multiple routes?

### ISSUE THREAD

**Issue by SunshowerC** [vuejs/vue-router#1969]
### Version
3.0.1

### Steps to reproduce
We all know CommonsChunkPlugin can create a separate file which consist of common modules shared between multiple entry points.
But how to create a separate file which consist of common modules shared between multiple routes(`.vue` file)?

### What is expected?
Like CommonsChunkPlugin , common `.js` in multiple routes entry should be separated from routes' bundles ?

### What is actually happening?
Some common `.js` modules is duplicated in the output file.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You may find help in webpack docs: https://webpack.js.org/guides/code-splitting/
