### ISSUE TITLE
ios10&ios11Safari中从一个动态获取数据的列表页面点击列表项进入详情页后再返回，页面出现一个白色的遮罩

### ISSUE THREAD

**Issue by CrazyHuiLiang** [vuejs/vue-router#1978]
### Version
3.0.1

### Reproduction link
[https://crazyhuiliang.github.io/#/](https://crazyhuiliang.github.io/#/)

### Steps to reproduce
需要在ios10 / ios11 的 Safari/微信中测试

1. 打开一个异步获取列表数据（数据量需要至少两页）的列表页面
2. 向下滚动列表到至少第2页以下
3. 点击列表项进入详情页
4. 点击浏览器返回/页面中自己写的返回按钮返回列表页，等待列表页加载出列表后就可以看到，页面出现一个白色的遮罩，页面点击事件会失效，页面滚动一下遮罩会消失

我已经写好了demo，列表页数据是通过一个1秒的延时来构造的，详情页有一个返回
demo：https://crazyhuiliang.github.io/#/

源码在这里：https://github.com/CrazyHuiLiang/my-vue-webpack

### What is expected?
我已经做了很久的尝试，仍然没有办法，如果是vue的bug希望能在新版本中修复，如果是什么地方使用不当，希望能给予指出，十分感谢

### What is actually happening?
出现bug后页面点击事件会失效，页面滚动一下遮罩又会消失

**Comment by posva** [comment]
If you fetch the data asynchronously, it's up to you to scroll to the content

**Comment by CrazyHuiLiang** [comment]
The problem is not about scroll, The problem is when i go back to a list page witch asynchronously data, There is a white layer on my screen when the data rendered. This white layer will bother i click my views.

Have you seen the phenomenon on ios ?

**Comment by posva** [comment]
I couldn't check on ios. Can you post some screenshots or video. I do not manage to picture what you say

**Comment by CrazyHuiLiang** [comment]
I captured a video, https://crazyhuiliang.github.io/video.mp4

1.  first i refresh this page
2. when this page loaded，This page would fetch the list data dynamically
3. When the data rendered，
4. I swipe down 1 or 2 page ( this step is important, but the point is not scroll)
5. I clicked an item to jump to a detail page, This page has a go back button(click me to go back)
6. Clicked go back, and the window backed to the list page.
7. when the list page loaded, the page will fetch list data, but this time, when the data is rendered there is a white layer appear on the screen.

The white layer will bother i click this page, but i can swipe the layer, just swipe a little, the layer will disappear. So the problem is when i do up 7 step, There will be  an white layer appear to bother me.

This problem only appear on ios 10 & ios 11. It's oddly.This code is  also very simple, You can see the code here:

https://github.com/CrazyHuiLiang/my-vue-webpack/tree/master/src

**Comment by CrazyHuiLiang** [comment]
Hello, Have you noticed the problem ?
