### ISSUE TITLE
vue-router 可以支持类似angular router的参数templateUrl吗？

### ISSUE THREAD

**Issue by zjzcn** [vuejs/vue-router#198]
以前一直用angularjs，现在想尝试vuejs，vue-router 可以支持类似angular router的参数templateUrl吗？

**Comment by shinygang** [comment]
@zjzcn  不是可以直接用require吗，组件的方式直接引用呗，
```
'/logon':{
      name:'logon',   
      component:require('./views/login/logon.vue')
},
```

**Comment by chairuosen** [comment]
你要是想同步加载就全都同步，要是异步加载就整个component全异步，没必要只有html异步

**Comment by yyx990803** [comment]
基本上就是 @chairuosen 所说的。异步组件用 webpack 实现非常简单：http://rc.vuejs.org/guide/components.html#Async_Components
