### ISSUE TITLE
take full advantage of Pushstate to support history.go

### ISSUE THREAD

**Issue by willin** [vuejs/vue-router#1983]
### What problem does this feature solve?
Issue codes at:

https://github.com/vuejs/vue-router/blob/dev/src/util/push-state.js#L40-L55

ref: https://stackoverflow.com/a/20544601

although there is a feature called `keep-alive` in vue but its performance is so scaring.

cause our fe developers never call `destroy` method, and https://github.com/vuejs/vue/issues/3269 not so useful in vast situations

### What does the proposed API look like?
no idea, perhaps user may specific state keys to store

**Comment by posva** [comment]
I don't see what this have to deal with keep alive or destroy but, regarding storing state in the pushState, it's not something we will add for the moment, as we prefer people to use a state management library like Vuex
