### ISSUE TITLE
nginx docs config doesn't work

### ISSUE THREAD

**Issue by lengziyu** [vuejs/vue-router#1986]
### Version
3.0.1

### Reproduction link
[https://router.vuejs.org/zh-cn/essentials/history-mode.html](https://router.vuejs.org/zh-cn/essentials/history-mode.html)

### Steps to reproduce
vue-router 设置为mode: 'history'，nginx配置根据官网的设置：
```
location / {
  try_files $uri $uri/ /index.html;
}
```
报错如下：
```
Uncaught SyntaxError: Unexpected token <
vendor.bb79a4c4fbca2d59f921.js:1 Uncaught SyntaxError: Unexpected token <
app.51feaf429d12ada477d3.js:1 Uncaught SyntaxError: Unexpected token <
```
网上搜遇到同样问题的原因是：因为配置服务器的时候把js资源重定向到了index.html，但是没有解决方法。谢谢~

### What is expected?
能正常访问

### What is actually happening?
无法访问

**Comment by posva** [comment]
I changed the title to English in case someone wants to contribute with a proper solution

**Comment by lengziyu** [comment]
thanks! I asked my colleague that he had forwarded it with nginx, which is accessible in tomcat.

**Comment by HuangXiZhou** [comment]
@lengziyu Hi, can you please provide your Nginx version ? I also encountered the same problem :(

**Comment by nzljay** [comment]
@lengziyu 
你好，这个问题解决了吗？我也遇到了同样的问题

**Comment by useryechen** [comment]
楼主您好，请问这个问题解决了吗？ 我也遇到了这个问题
