### ISSUE TITLE
[Vue warn]: Error in created hook: "ReferenceError: config is not defined"

### ISSUE THREAD

**Issue by kjhatis** [vuejs/vue-router#1989]
` ``
[Vue warn]: Error in created hook: "ReferenceError: config is not defined"

found in

---> <School> at resources\assets\js\components\Users\User.vue
       <Root>
app.js:6457:7
ReferenceError
columnNumber: 7
fileName: "http://localhost/mytestproject/public/js/app.js"
lineNumber: 72155
message: "config is not defined"
stack: "fetchAllSchools@http://localhost/mytestproject/public/js/app.js:72155:7\nboundFn@http://localhost/mytestproject/public/js/app.js:6070:9\ncreated@http://localhost/mytestproject/public/js/app.js:72147:5\ncallHook@http://localhost/learninggps/public/js/app.js:8772:9\ninitMixin/Vue.prototype._init@http://localhost/learninggps/public/js/app.js:10437:5\nVueComponent@http://localhost/learninggps/public/js/app.js:10605:7\ncreateComponentInstanceForVnode@http://localhost/learninggps/public/js/app.js:10119:10\ninit@http://localhost/learninggps/public/js/app.js:9936:45\ncreateComponent@http://localhost/learninggps/public/js/app.js:11389:9\ncreateElm@http://localhost/learninggps/public/js/app.js:11337:9\nupdateChildren@http://localhost/learninggps/public/js/app.js:11626:11\npatchVnode@http://localhost/learninggps/public/js/app.js:11717:29\npatch@http://localhost/learninggps/public/js/app.js:11877:9\nlifecycleMixin/Vue.prototype._update@http://localhost/learninggps/public/js/app.js:8524:16\nupdateComponent@http://localhost/learninggps/public/js/app.js:8642:7\nget@http://localhost/learninggps/public/js/app.js:8992:13\nrun@http://localhost/learninggps/public/js/app.js:9069:17\nflushSchedulerQueue@http://localhost/learninggps/public/js/app.js:8831:5\nnextTick/<@http://localhost/learninggps/public/js/app.js:7690:9\nflushCallbacks@http://localhost/learninggps/public/js/app.js:7611:5\n"
__proto__: {…}

`` `

I am using vue inside Laravel,  not sure what is causing this error.

**Comment by Austio** [comment]
Please post to forum.  Will probably get help.

**Comment by kjhatis** [comment]
thank you
