### ISSUE TITLE
Route hook API change

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vue-router#199]
Currently, route transition hooks are nested under the `route` option. One thing that is a bit awkward is that we have `data` and `activate` which overlap with plain component option names:

``` js
module.exports = {
  data: function () {
    // ...
  },
  route: {
    data: function () {
      // ...
    },
    activate: function () {
    }
  }
}
```

A lot of times we also have components that have only the `data` hook, which makes the nesting unnecessary.

I'm thinking about switching to a flatter structure:

``` js
module.exports = {
  data: function () {
    // ...
  },
  routeData: function () {
    // ...
  },
  routeActivate: function () {
    // ...
  }
}
```

This makes the code look cleaner (less nesting), and make the function names more distinct and descriptive. Thoughts?

**Comment by allanfreitas** [comment]
:smiley::+1: Approved, I think It's much better this way.
The code looks cleaner.

**Comment by JosephSilber** [comment]
I like the current way _much_ more.

1. I just love method names that are composed of single words (laravel excels at this).
2. I actually like that all route related stuff is nicely grouped in a single object.

**Comment by jonagoldman** [comment]
Like the current way. Nesten and single word.

**Comment by hfalucas** [comment]
I am 100% with @JosephSilber.

**Comment by dmail** [comment]
+1 on nested

**Comment by auvipy** [comment]
+1 for new way

**Comment by federicodionisi** [comment]
+1 on nested as well

**Comment by stefanosandes** [comment]
+1 in nested. The organization becomes more clear.

**Comment by oleynikd** [comment]
+1 for nested

**Comment by remoe** [comment]
same as @JosephSilber. Nested.

**Comment by matteocontrini** [comment]
Nested but you could accept both syntaxes in some way

**Comment by yyx990803** [comment]
Ok, sticking with nested...
