### ISSUE TITLE
docs: typo in named-views.md

### ISSUE THREAD

**Issue by cdump** [vuejs/vue-router#1996]
### Version
3.0.1

### Reproduction link
[https://router.vuejs.org/en/essentials/named-views.html](https://router.vuejs.org/en/essentials/named-views.html)

### Steps to reproduce
open the link

### What is expected?
> the view **component**

### What is actually happening?
> the view **comopnent**

**Comment by posva** [comment]
Thanks! No need to create issues for typos next time! Firing the PR is enough 🙂 
Waiting for the PR btw

**Comment by cdump** [comment]
Ok :)
Should I not refer ticket/pr number in commit message in that case? Will it be added during pr review/merge?

**Comment by posva** [comment]
no need to refer the issue if there is no issue 😄 
It's just easier since typos are very small changes
