### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vue-router#20]
- [x] matching views
- [x] matching nested views
- [x] route context
  -  [x] path
  -  [x] params
  -  [x] query
  -  [x] presence in non-router-view components
- [x] `router.go()`
-  [x] `v-link`
  - [x] navigation
  - [x] setting correct href
  - [x] dynamic link
  - [x] active CSS classes (with `linkActiveClass` option)
  - [x] relative query string
-  [x] redirect
  -  [x] simple
  -  [x] with params
- [x] alias
  - [x] simple
  - [x] with params
- [x] not found
- [x] global before hook (test reject)
- [x] `saveScrollPosition` option
- [x] `transitionOnLoad` option
- [x] respect `<base>` tag
- [x] html5 history
  -  [x] `root` option
- [x] hash history
  - [x] `hashbang` option
- [x] component route activation lifecycle
  - [x] full pipeline
  - [x] canDeactivate
  - [x] canActivate
  - [x] deactivate
  - [x] activate
  - [x] canReuse
    - [x] boolean
    - [x] function
  - [x] data
    - [x] waitForData
    - [x] reload on reuse

**Comment by yyx990803** [comment]
Awwwww yeah

**Comment by JosephSilber** [comment]
Congrats :heart_eyes: 

:+1: :+1:  :+1:  :+1:  :+1:  :+1:  :+1:  :+1:  :+1:  :+1:  :+1:  :+1:  :+1:  :+1:

**Comment by simplesmiler** [comment]
Does it mean that soon we'll see an 0.1.0 release?

**Comment by kazupon** [comment]
:+1:
