### ISSUE TITLE
Router-link via <component> lost href after first change path.

### ISSUE THREAD

**Issue by dimensi** [vuejs/vue-router#2005]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/qz0m332p8w](https://codesandbox.io/s/qz0m332p8w)

### Steps to reproduce
Generate router-link from array by v-for using `<component>`
Click on router-link.
![vokoscreen-2018-01-15_17-45-03](https://user-images.githubusercontent.com/11390039/34947672-def17f2e-fa1b-11e7-89a4-8f8a0cafaf63.gif)

### What is expected?
Not lost href attribute

### What is actually happening?
href attribute disapper

**Comment by posva** [comment]
Please provide a boiled down repro and make sure your repro runs before submitting an issue. You can use jsfiddle btw: http://jsfiddle.net/posva/9r6xhqbp/

You don't need to use `href` on router-link as it creates it for you. That, or you don't want to use a `router-link` component

**Comment by dimensi** [comment]
@posva I fixed my repro and you not understand my problem! I have dynamic component if i pass href i get `<a>` if i pass name i get `router-link`. But `router-link` generate href attibute from route object!

**Comment by dimensi** [comment]
Or i must not set `:href=undefined` if it's router-link?

**Comment by posva** [comment]
You have to remove the `href` binding for router-link or it will override `router-link` generated value

**Comment by chatzipan** [comment]
Seriously you closed this issue?

So you are telling me in Vue its not possible to create a custom button component the can render either a `button` or an `a` or a `router-link` like that, just because the existence of the `:href` binding, even if `href` is `null`?

```
  <component
    v-ripple
    :is="to ? 'router-link' : href ? 'a' : 'button'"
    :class="buttonClasses"
    :href="href"
    :to="to"
    :type="(!href && !to) && type"
    :disabled="(!href && !to) && disabled"
    @click="handleTap"
  >
```

**Comment by posva** [comment]
Vue will override properties bound on the component on the root of the element rendered because they are more specific, this is a feature. This is not Vue Router specific and happens with any property on any custom component. It can be disabled with `inheritAttrs: true` but  that would disallow **every** attribute inheritance.

On top of that, using `null` will **unset** an attribute while using `undefined` will be ignored, so **in your case, you just want to use `undefined`** for `href` when using a `router-link`

**Comment by scottbedard** [comment]
For anyone else running into this, this worked for me...

```vue
<template>
    <component v-bind="attrs" :is="is" :to="to">
        <slot />
    </component>
</template>

<script>
export default {
    computed: {
        attrs() {
            const attrs = {};

            if (this.href) {
                attrs.href = this.href;
            }

            return attrs;
        },
        is() {
            if (this.href) {
                return 'a';
            }

            if (this.to) {
                return 'router-link';
            }

            return 'button';
        },
    },
    props: ['href', 'to'],
};
</script>
```
