### ISSUE TITLE
The KeepAlive of A/B pages are true, scrollTop is error when B back to A.

### ISSUE THREAD

**Issue by raybest** [vuejs/vue-router#2009]
1. Vue + Vue-router + Vuex
2. The A/B pages's KeepAlive all are true.
3. When A link to B, i save dom's scrollTop into store in the beforeRouteLeave.
4. When B back to A, update dom's scrollTop from store, but dom's scrollTop always is 0.
5. If C page is not keepalive and C back to A, dom's scrollTop will get value from store's value.
so i have not solution for the question, i need you help. 
thanks.

**Comment by raybest** [comment]
A page scroll dom is "<div data-v-6f770f6e="" data-v-ac685cc4="" class="scroll ui-scroll">"
B page scroll dom is "<div data-v-6f770f6e="" data-v-490930f3="" class="scroll">"

**Comment by raybest** [comment]
```
console.log(this.$refs) 
\\ this.$refs.scroll.$el.clientHeight : 667
console.log(this.$refs.scroll.$el.clientHeight)
\\ 4000(B),667(C)
```
why?

**Comment by raybest** [comment]
I set value after change nextTick to setTimeout and waiting 200ms.
Now scrollTop to store's value.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
