### ISSUE TITLE
相同路径下跳转怎么处理

### ISSUE THREAD

**Issue by shinygang** [vuejs/vue-router#201]
@yyx990803 ，你好，请问一下touter的那么相同的情况怎么做跳转呢，我用router.go不起作用：

```
'/order-detail/:orderId':{
     name:'order-detail',
     component:require('./views/profile/order-detail.vue')
},
```
这是我定义的路由，

我当前页面访问地址是http://localhost:9090/order-detail/1115,我想跳转到http://localhost:9090/order-detail/11，
```
that.$route.router.go({
       name:"order-detail",
        params:{
               orderId:11
        }
})
```
代码这样写没效果，

**Comment by shinygang** [comment]
找到解决方案了，我这里描述一下:
我之前是在ready或者created里面获取ajax数据的，在组件重用的时候会有问题，最后又看了一遍官方文档，里面http://router.vuejs.org/zh-cn/pipeline/data.html讲的很清楚。哈哈，解决方案用下面的方式取数据：
```
route: {
  data: function (transition) {
    setTimeout(function () {
      transition.next({
        message: 'data fetched!'
      })
    }, 1000)
  }
}
```

**Comment by Yunkou** [comment]
好好  `看文档`  `看文档` `看文档`
