### ISSUE TITLE
Add a way to catch a route cancel

### ISSUE THREAD

**Issue by ghost** [vuejs/vue-router#2011]
There are occasions where a route should be handled everytime it’s considered. For example, I’ve seen it suggested that VueRouter could be used to show a loading indicator by doing the following:

```
router.beforeEach((to, from, next) => {
    LoadIndicator.show();
    next();
});
router.afterEach((to, from) => {
    LoadIndicator.hide();
});
```
A route can be cancelled in a component’s `beforeRouteEnter` method with `next(false)`, but `AfterEach` won’t fire since the route never actually loaded and the loading indicatior is stuck.  

Something like that would be great: 

```
router.cancel((to, from) => {
    LoadIndicator.hide();
});
```

**Comment by posva** [comment]
Use `router.onError` in combination with `next(err)` (https://router.vuejs.org/en/api/router-instance.html#methods). It also allows you turn the bar red and similar things

**Comment by JounQin** [comment]
This also occurs on trying to go to another route but which redirects to itself.

**Comment by posva** [comment]
@JounQin mhh, that may be different though. Let me give it a second look

**Comment by ghost** [comment]
@JounQin wrote:
> This also occurs on trying to go to another route but which redirects to itself

Second this... there's no way to catch redirect to itself

**Comment by posva** [comment]
Closing in favour of #2012
if you have a use case about hooking on redirects, I'll like to hear it there 🙂
