### ISSUE TITLE
router-link integration with custom components

### ISSUE THREAD

**Issue by Leopoldthecoder** [vuejs/vue-router#2021]
### Version
3.0.1

### Reproduction link
[http://jsfiddle.net/leopoldthecuber/forzLu80/38/](http://jsfiddle.net/leopoldthecuber/forzLu80/38/)

### Steps to reproduce
Run the demo. In the demo I mainly did two things:
- a custom component `my-button`, it has a prop `content` and a named slot `icon`
- a `router-link` with its tag set to `my-button`

### What is expected?
Props and named slots can be passed to custom component.

### What is actually happening?
Props and named slots don't work

---
- https://github.com/vuejs/vue-router/issues/1678 says props can be passed down since 2.8, but it still doesn't work
- Default slots work fine, while named slots don't

**Comment by QingWei-Li** [comment]
If `router-link` is a functional component, this feature will be supported. Then I did that, and all the tests passed.
But I am not sure if this is correct. 😂

**Comment by miljan-aleksic** [comment]
I assumed this was working and just tested now on a new project confirming it does not. If there is anyway we can help to push this forward, let us know.

**Comment by posva** [comment]
Yes, it should be. We wanted to make router link functional components for a while but never took the time to actually do it. So if you want to open a pr for 5yat,that would be great :smile: (since you have already coded it)

**Comment by 0m4r** [comment]
is there any chance #1678 gets fixed? or any idea if it will ever be and when?

**Comment by posva** [comment]
The recommended approach is to use the v-slot api of router-link. Making router-link functional would be a breaking change and thus isn't possible
