### ISSUE TITLE
add default match path to <router-view>

### ISSUE THREAD

**Issue by yozman** [vuejs/vue-router#2022]
### What problem does this feature solve?
```javascript
...
routes: [
  { // /dashboard
    path: '/dashboard',
    component: {
      render: h => h('router-view'),
    },
    children: [
      { // /dashboard/analysis
        path: 'analysis',
        component: analysis,
      }
    ],
  },
]
...
```

if I want `/dashboard/analysis` to render `analysis`,
I should change the `path` for `analysis` to `''`,
it's sometime werid,
I need a natural way to keep `analysis` and do it at `<router-view/>`

### What does the proposed API look like?
```javascript
...
routes: [
  { // /dashboard
    path: '/dashboard',
    component: {
      template: `<router-view default="analysis"/>`
    },
    children: [
      { // /dashboard/analysis
        path: 'analysis',
        component: analysis,
      }
    ],
  },
]
...
```

**Comment by posva** [comment]
Use an alias or redirect to achieve that.
Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by yozman** [comment]
@posva 
this is not a bug,
it's a **feature request**

**Comment by posva** [comment]
Yes, I know, but it already exists as alias/redirect, that's why I asked you to ask if you couldn't find a way of doing it 🙂

**Comment by yozman** [comment]
@posva
I know there is one way to resolve it,
but as I already said, it's sometimes let me feels werid,
there should has some more way to adapt more scenes
