### ISSUE TITLE
not defined vuerouter

### ISSUE THREAD

**Issue by newprogrammeram** [vuejs/vue-router#2027]
### Version
3.0.1

### Reproduction link
[https://cdn.rawgit.com/vuejs/vue-router/dev/dist/vue-router.min.js](https://cdn.rawgit.com/vuejs/vue-router/dev/dist/vue-router.min.js)

### Steps to reproduce
<pre>
var notFound = Vue.extend({
   // You can use also use template path (Thanks to @jcerdan)
   // path : '/path/to/component.html'
   template: '<h1>Not Found</h1>'
})

// For dashboard. This is our root page
var dashboardComponent = Vue.extend({
    template: 
            '<div class="jumbotron">hi all</div><router-view></router-view>'
})
//********* this line give error*********//
Vue.use(VueRouter) 
var App = Vue.extend()
// Router options
var router = new VueRouter({
  history: false,
   root: '/',
    routes: [
    { path: '/', component: dashboardComponent }
  ],
})
`</pre>`

### What is actually happening?
not defined vuerouter

**Comment by LinusBorg** [comment]
Please follow the issue rules.
