### ISSUE TITLE
error :not defined vuerouter

### ISSUE THREAD

**Issue by newprogrammeram** [vuejs/vue-router#2028]
### Version
3.0.1

### Reproduction link
[https://cdn.rawgit.com/vuejs/vue-router/dev/dist/vue-router.min.js](https://cdn.rawgit.com/vuejs/vue-router/dev/dist/vue-router.min.js)

### Steps to reproduce
not defined vuerouter

### What is expected?
var notFound = Vue.extend({
   // You can use also use template path (Thanks to @jcerdan)
   // path : '/path/to/component.html'
   template: '<h1>Not Found</h1>'
})

// For dashboard. This is our root page
var dashboardComponent = Vue.extend({
    template: 
            '<div class="jumbotron">hi all</div><router-view></router-view>'
})
//********* this line give error*********//
Vue.use(VueRouter) 
var App = Vue.extend()
// Router options
var router = new VueRouter({
  history: false,
   root: '/',
    routes: [
    { path: '/', component: dashboardComponent }
  ],
})

### What is actually happening?
not defined vuerouter

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You have to import the Router to use it. Take a look at the docs: https://router.vuejs.org/

**Comment by newprogrammeram** [comment]
![vrouter](https://user-images.githubusercontent.com/22255338/35506562-ed7ba626-04fe-11e8-8474-5427e6d92248.png)

this is link 
http://mehdibashirinejad.ir/bve

**Comment by posva** [comment]
you're using an extremely old version of vue. Use the latest version: `https://unpkg.com/vue`

**Comment by newprogrammeram** [comment]
i change that to last 
`<script src='https://unpkg.com/vue'></script>
<script src='https://unpkg.com/vue-router'></script>`
but it tell map is not defined 
and i remove that line and 
it tell  
start no defined  and i think router dont have any method
 
can u give me a example link without node js?

**Comment by leopiccionia** [comment]
If you're using VueRouter 3.0+, that requires Vue 2.5+, and vice-versa. For info about migrating to a newer VueRouter version, [see here](https://vuejs.org/v2/guide/migration-vue-router.html).
