### ISSUE TITLE
Pushing a route with query parameters clones complex objects incorrectly

### ISSUE THREAD

**Issue by ferk6a** [vuejs/vue-router#2032]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/f5y29tjp/3/](https://jsfiddle.net/f5y29tjp/3/)

### Steps to reproduce
* When `whichTest` is `push`, a `Date` is pushed as a query parameter.
* When `whichTest` is `path`, the hash location is changed to a string representation of `Date`.
* When `whichTest` is `pushAndUpdateURL`, a `Date` is pushed as a query parameter, and after that, the hash location is set again with a new parameter.

### What is expected?
That when a `Date` object is pushed by a query parameter, it should end up in `$state.query` the same way as if the page was loaded with that query parameter.

### What is actually happening?
It's being cloned by a function that copies only simple object properties, which transforms the `Date` into a simple unusable `{}` object.

---
I believe the correct way to approach this, while wasteful, is to clone by doing `stringifyQuery` and then `parseQuery` instead of using a problematic `clone` function. This makes the behavior more consistent, and allows developers to implement these functions as they please.

**Comment by posva** [comment]
Keep in mind the url is just a string, so you have to make sure your stringify function does the job correctly and that you have the according `parseQuery` to retrieve back the original values.
In your case, it is much simpler to transform the date to a string (which is what you do in the other cases) without any custom `stringifyQuery`: https://jsfiddle.net/Lqa9eek6/

You may be also interested in qs for advanced query handling: https://github.com/ljharb/qs

**Comment by ferk6a** [comment]
Yes, this is my current solution atm (and I don't need a custom `parseQuery`, I want the query as string, currently). I just think that if you complicate your `stringifyQuery` function enough (say you have complicated business objects which are encoded in a specific way), it would be nice if vue-router used it when passing the arguments back to another route.

I also think we could save on shipping the `clone` function entirely by doing this.

**Comment by posva** [comment]
can you elaborate on

> I also think we could save on shipping the clone function entirely by doing this.

I don't quite understand what you're referring to by _the clone function_ nor by _this_

**Comment by ferk6a** [comment]
Sure thing!

The clone function is the one called here, which is only used here:
https://github.com/vuejs/vue-router/blob/effb1143db10376c4ed553aec9a909dd1430ef66/src/util/route.js#L18

This thing:
https://github.com/vuejs/vue-router/blob/effb1143db10376c4ed553aec9a909dd1430ef66/src/util/route.js#L37-L49

By doing "this", I mean doing:
```javascript
query = parseQuery(stringifyQuery(query))
```

Instead of the line in the first snippet above.

---

It should be noted that `parseQuery` and `stringifyQuery` in this context aren't necessarily the original functions, they come from the options having the default ones as default.

```javascript
const _parseQuery = route.opts.parseQuery || parseQuery
const _stringifyQuery = route.opts.stringifyQuery || stringifyQuery

query = _parseQuery(_stringifyQuery(query))
```
And so on. I'm not sure how it fits within the current code style.

**Comment by posva** [comment]
Thanks! That's interesting. Indeed, a simple clone may not be enough for more complex stringify/parse. I think there's a bit refactoring to do around there to make sure we ensure the type of query all around but using `parseQuery(stringifyQuery(query))` if both are available may be an option. I'll test some things and open a separate issue.
That being said I'm not quite convinced by having non-plain js objects as query objects. Do you have any use case beyond Dates?

**Comment by ferk6a** [comment]
Yes, quite. I can see use cases for:

* Decimal types like https://mikemcl.github.io/decimal.js/
* Date types coming from different libraries such as https://js-joda.github.io/js-joda/ and http://moment.github.io/luxon/index.html
* Colors, for example http://gka.github.io/chroma.js/, where you will need to call `hex` to get a real color back.

In all of these cases, you end up with:
* **`clone`:** Results in an object which loses all its prototype properties and dump all the functions, while being inconsistent with what you would get from a query parameter (a string).
* **`valueOf` or `toJSON`:** Results in a string which can be then parsed again on the next route.

Component authors are free to write components which have a v-model of one of those "complex" objects, and it becomes easy to pass them around if the interface is uniform, string in, string out. In `stringifyQuery` you would convert each into their own string versions and in `parseQuery` if you were so inclined, you could convert them back, the key here is just consistency.

We are being inconsistent by giving whoever accesses `query` a different object if the object was passed via the programmatic interface or via query string.
