### ISSUE TITLE
发现一个2.x中文文档的错别字

### ISSUE THREAD

**Issue by 542154968** [vuejs/vue-router#2034]
### Version
3.0.1

### Reproduction link
https://router.vuejs.org/zh-cn/essentials/getting-started.html

### Steps to reproduce
通过注入路由，我们可以用 this.$router 来访问它，就像在任何组件里用 this.$router 访问当前  **路有**  一样。

### What is expected?
错别字

### What is actually happening?
错别字

**Comment by javoski** [comment]
这个已经修复([https://github.com/vuejs/vue-router/commit/75f2c1e64596b4c3dde46b9ff79dba2539f2eb0f](https://github.com/vuejs/vue-router/commit/75f2c1e64596b4c3dde46b9ff79dba2539f2eb0f))了，只是还没发布。
