### ISSUE TITLE
Add route attribute to template tag to simplify route config

### ISSUE THREAD

**Issue by jarrettv** [vuejs/vue-router#2039]
### What problem does this feature solve?
This suggestion is in honor of single file components (which are awesome) and would simplify route config and reduce code.

### What does the proposed API look like?

**./pages/Dashboard.vue**
`<template route="/"></template>`

**./pages/UserDetail.vue**
`<template route="/users/:id"></template>`

**Comment by posva** [comment]
This is unfortunately not something that needs to be handled on vue-router, but rather on a webpack-loader to extract it somewhere else.
Regardless of that, I think using plain html attributes lacks the feature of a programming language (functions for example).

Another option is to declare routes in a component fashion, but that can be achieved in user land as well
