### ISSUE TITLE
In history mode, pushing/replacing query params to the same path does nothing

### ISSUE THREAD

**Issue by Malabarba** [vuejs/vue-router#2047]
### Version
3.0.1

### Reproduction link
[http://jsfiddle.net/83fogkav/3/](http://jsfiddle.net/83fogkav/3/)

### Steps to reproduce

In the linked jsfiddle:
Click the `/home` link, then click the `/home?iam=home`. Notice how the query params don't change according to `document.location.search` (it does change according to `this.$route.query`).
If you click on the `/foo` link and **then** click the `/home?iam=home` link then it works. I.e., changing the query params only works if you change the path as well.

Note that the same problem happens if you try to push/replace routes via javascript code. For instance, none of the following 4 lines have any effect on the browser's urlbar.

    this.$router.push({query: {x: 5}})
    this.$router.push({path: document.location.pathname, query: {x: 5}})
    this.$router.replace({query: {x: 5}})
    this.$router.replace({path: document.location.pathname, query: {x: 5}})

### What is expected?
The query string should always be appended to the url.

### What is actually happening?
Nothing. No error is signaled and the URL doesn't change.

---
If you remove `mode: 'history'`, you get the expected behaviour.
Also, if you change the `path` to something different from the current path, you get the correct behaviour as well.

Also, even though `$route.query` gets updated, it's important for the browser's urlbar to update as well.

**Comment by posva** [comment]
What browser are you using, it does work on my end. Maybe you're trying to access `document.location.search` too early (in the computed). Could you try checking in the console instead?

**Comment by Malabarba** [comment]
I've tested on chromium 64 and firefox 58, both running on arch linux.
If I evaluate `document.location.search` on the console I get the same behaviour displayed in the jsfiddle I linked. It's always an empty string, both before or after I click the link that should change the query params.

To be honest, I don't really care about `document.location.search`. 
The real issue I have here is that the url doesn't change on the browser's location bar (I only used `document.location.search` because that's how I managed to expose the problem in the fiddle).
No matter what I do, I can't seem to add query params to the url unless I also change to a different path.

**Comment by Malabarba** [comment]
Hold on. Suddenly the behaviour has become inconsistent. I'll see if I can narrow it down.

**Comment by posva** [comment]
`document.location` shows what is seen on the URL bar 😉 
Closing for the moment, will reopen if there's indeed a bug

**Comment by Malabarba** [comment]
Hey there, I've found the cause of my issue so I wanted to provide an update. This is more or less what I'm doing:

    <router-link :to="{query: q}">Search</router-link>

Where `q` is initialized in the data object as `q: this.$route.query` and different attributes of `q` are modified by user interaction with form elements. 
Apparently, some nasty issue happens there. If I inspect the link in the browser, the `href` attribute correcly shows everything inside `q`, but when I click the link nothing happens.
By now, I've learned that this is completely fixed by replacing the initialization with `q: {...this.$route.query}`.

However, back when I was debugging this issue I ran into a number of other stuff that kept pushing further and further away from the cause. :-)
For instance, I eventually tried a router-link as simple as `:to="{query: {x: 1}}"`. But I **still** observed the buggy behaviour because by then I had some other code snippets in my file that prevented navigation altogether. Of course, the fact I managed to "reproduce" my issue on a small jsfiddle didn't help either. 

Anyway, thanks for your time. And sorry for the noise.

**Comment by rgpolizeli** [comment]
**Version:** 3.1.3

I have the same problem. With `$router.currentRoute.path == '/articles/'`, this code:

`context.$router.push({path: document.location, query: {s: context.search}});`

Results in the following url (note the symbol **?#**):

`http://localhost:2121/?#/articles/`

And, this code:

`context.$router.push({ path: '/articles/', query: { s: context.search } });`

Results in the following url (note the symbol **?#** again):

`http://localhost:2121/?#/articles/?s=someString`

But in both situations I expected the url:

`http://localhost:2121/#/articles/?s=someString`

In the second situation, when I go back, I go to the url:

`http://localhost:2121/#/articles/?s=someString`

But I expected to go to the url:

`http://localhost:2121/#/articles/`

If `$router.currentRoute.path` is different from the path  specified in `$router.push()` all works as expected.
