### ISSUE TITLE
filter is executed on route change

### ISSUE THREAD

**Issue by nikugogoi** [vuejs/vue-router#2063]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/nikugogoi/mj6ajs9e/](https://jsfiddle.net/nikugogoi/mj6ajs9e/)

### Steps to reproduce
filter is called once at the beginning (detected by alert)
again it is called on route change (alert pop up)

### What is expected?
filter should not be executed on route change?

### What is actually happening?
filter is called on route change

---
is This a normal behaviour?

**Comment by posva** [comment]
Yes, it is, as said in https://github.com/vuejs/vue/issues/7644
You can get around it by wrapping the either, the message with a filter or the router-view in a component or by using a computed property instead of a filter

**Comment by nikugogoi** [comment]
thank you @posva .... it works in the fiddle
But still facing the same problem in my project (the filter is in a different child component) 
@yyx990803 mentioned the reason for this behaviour is that the router-view is a functional component.
I have seen that the router-view is a functional component but if you could provide any kind of documentation for understanding, I would be really thankful

**Comment by nikugogoi** [comment]
just leaving it here if anyone may need it
https://vuejs.org/v2/guide/render-function.html#Functional-Components
