### ISSUE TITLE
Proposal: Link should provide an API to get info about its current state

### ISSUE THREAD

**Issue by getriebesand** [vuejs/vue-router#2066]
### What problem does this feature solve?
With info about Links active state you can trigger animations or something else.

Please see this issue from someone else:
https://github.com/vuejs/vue-router/issues/774
https://forum.vuejs.org/t/get-active-state-of-router-link-using-javascript/1462
and his gist: https://gist.github.com/aplr/b49b74103a5c4adba57379cc7ce932da

My use case is this component from vue-mdc-adapter
https://github.com/stasson/vue-mdc-adapter/blob/master/components/tabs/mdc-tab.vue

It is using https://github.com/material-components/material-components-web for rendering and I need to trigger foundation.setActive() from mdc when the underlying router-link changes to active

### What does the proposed API look like?
An event on active state change and a data var or computed var for active and exactActive

**Comment by posva** [comment]
Hello! Watching the current route or using `afterEach` is the actual solution. Firing an event may work now but it will not work when we move router-link to a functional component.
Your use case is very specific so you'll have to handle it be calling setActive on the right component whenever necessary. But don't worry, using a watcher or `afterEach` should be straightforward, even with an event you still will have to add references or keep track of the elements associated with a route 🙂

**Comment by getriebesand** [comment]
Thank you for your answer :) watching current route is ok. But i don't know how to comparing to path in router-link.
In router-link there are functions isSameRoute and isIncludedRoute. But they seems to be private. Is it possible to get Access to that functions?
But if my use case realy specific I will copy these functions in my code.

**Comment by posva** [comment]
You can use `router.resolve`

**Comment by yfwz100** [comment]
Exposing utilities like `isSameRoute()` and `isIncludedRoute()` is necessary as comparing route is not trivial.

Could you consider exposing those API? @posva
