### ISSUE TITLE
Vue-router to fail gracefully when code-split deps fail to load

### ISSUE THREAD

**Issue by john-ko** [vuejs/vue-router#2067]
### What problem does this feature solve?
When navigating to `https://vue-hn.now.sh/top` and if a specific code-split dependency fails to load, the url is changed to `https://vue-hn.now.sh`

steps to reproduce:
1. navigate to https://vue-hn.now.sh/top
2. developer tools > network tools > block url request 1.js
3. refresh https://vue-hn.now.sh/top
4. url is now https://vue-hn.now.sh

### What does the proposed API look like?
N/A

**Comment by john-ko** [comment]
```
// the starting route that represents the initial state
export const START = createRoute(null, {
  path: '/'
})
```

from what i've looked at, it looks like it defaults to `/`. When code-split dependency fails, the url changes to `/` no matter where the user is currently at

**Comment by posva** [comment]
Just catch the promise to do as you please 🙂

**Comment by john-ko** [comment]
@posva in terms of the vue-hackernews 2.0, does the vue-router provide callback hooks on error or anything that you know of?

**Comment by posva** [comment]
`router.onError`

**Comment by john-ko** [comment]
@posva Thanks!
