### ISSUE TITLE
Question: translate guide to Hebrew

### ISSUE THREAD

**Issue by kfirba** [vuejs/vue-router#207]
Hey.

Would it be helpful if I submitted a PR with the documentation translated to Hebrew? I just believe that the more languages a framework has to offer will eventually invite more people to use it.

If it is indeed something you are willing to accept that, I can start with translating the `Vue-router` documentation and then `Vue` 's documentation.

**Comment by kfirba** [comment]
P.s. I forgot to mention that Hebrew is RTL. Is there a way to denote that in the markup?

**Comment by yyx990803** [comment]
Not being disrespectful for Hebrew speakers - but ideally I only want to include translations for languages that have a known community of developers using Vue. This is mostly to ensure the long-term maintenance responsibility for an additional language is worth it. Note I'm not familiar with Hebrew at all - if you can demonstrate enough community interest in a Hebrew translation, I will gladly accept PRs for it.

**Comment by kfirba** [comment]
@yyx990803 you got a point there. I will do a market research and try to figure out how many Hebrew speakers are using Vue.

**Comment by kfirba** [comment]
@yyx990803 doesn't seem like there is much interest among he Hebrew speakers currently. Hopefully it will change in the future ;)
