### ISSUE TITLE
Unexpected router.replace behaviour

### ISSUE THREAD

**Issue by Dadibom** [vuejs/vue-router#2071]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/e3odg60s/2/](https://jsfiddle.net/e3odg60s/2/)

### Steps to reproduce
Click push next three times
three states should be added (1,2,3)
Now click replace three times. The history list should now look like this:
[1,2,6]

Now use the back button to go back to the start. _First navigation simply does not work._
Then the order is as follows: [5, 4, 2, 1]

It appears that replace actually only _replaces_ on the first call, subsequent calls instead push states.

### What is expected?
Replace should always replace the current state

### What is actually happening?
Replace pushes new states

**Comment by Dadibom** [comment]
You can also try clicking: push, replace, push, replace, push, replace, push, replace
Now every other back navigation does not work. Very weird behaviour.

**Comment by posva** [comment]
You need to `.prevent` on the click event because since it is a link, it will also mess up the history

**Comment by Dadibom** [comment]
I'm facepalming so hard right now. Thanks @posva

**Comment by posva** [comment]
lol, don't worry, it also took me some time to figure it out
