### ISSUE TITLE
"localhost:8080/#/" changed to "localhost:8080/?#/" ?

### ISSUE THREAD

**Issue by chebysheph** [vuejs/vue-router#2073]
### What problem does this feature solve?
For example, in page "localhost:8080/#/temp1" has a input tag, when I modified the input value, and press "enter" button, because I did not add "@keydown.enter" event on the input tag, so the page url become to "localhost:8080/?#/login", but the right result should be "localhost:8080/#/login", so  I would like to know how the "?" add into the url?And what exactly happened when I press "enter" button?

### What does the proposed API look like?
For example, in page "localhost:8080/#/temp1" has a input tag, when I modified the input value, and press "enter" button, because I did not add "@keydown.enter" event on the input tag, so the page url become to "localhost:8080/?#/login", but the right result should be "localhost:8080/#/login", so  I would like to know how the "?" add into the url?And what exactly happened when I press "enter" button?

**Comment by MaksPapirovnyk** [comment]
add to your routes confog 

> mode: 'history'

example:
```
export default new Router({
  mode: 'history',
  routes: [
    {
      path: '/',
      name: 'yourPath',
      component: yourComponent
    }
  ]
})
```
