### ISSUE TITLE
beforeRouteUpdate is not called on change from multiple named views

### ISSUE THREAD

**Issue by oles** [vuejs/vue-router#2077]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/yfj5tmh4/](https://jsfiddle.net/yfj5tmh4/)

### Steps to reproduce
0. Open console
1. Click on /1, then /2
2. Every beforeRouteUpdate is called
3. Click on /2/qux, then click on /1 

### What is expected?
Every beforeRouteUpdate is called, resulting in console messages.

### What is actually happening?
No beforeRouteUpdate is called.

---
Everything works as expected when clicking on /1 if you've clicked on /2 before /2/qux.

It could be that I've miss-understood something, but I'm not 100% sure, and couldn't find any related issues - so here we are :)

**Comment by posva** [comment]
Hello!
`beforeRouteUpdate` only triggers when a param makes the route effectively change but the components in view stay the same. In your case you're changing to a **different route**, that's why it doesn't fire. However, if you use `beforeRouteEnter`, it will fire
