### ISSUE TITLE
Incorrect typehint

### ISSUE THREAD

**Issue by cdekok** [vuejs/vue-router#2078]
### Version
3.0.1

### Reproduction link
[https://github.com/vuejs/vue-router/blob/dev/types/router.d.ts#L27](https://github.com/vuejs/vue-router/blob/dev/types/router.d.ts#L27)

### Steps to reproduce
This should be a string not a number

### What is expected?
a string as typehint

### What is actually happening?
a number as typehint

**Comment by posva** [comment]
It is correct, it's a number `router.go(-1)` 🙂
