### ISSUE TITLE
Update apache-example for history-mode (documentation)

### ISSUE THREAD

**Issue by doppelreim** [vuejs/vue-router#2090]
### What problem does this feature solve?
For HTML5 History Mode, there are some example server-configurations in the documentation.

See https://github.com/vuejs/vue-router/blob/dev/docs/en/essentials/history-mode.md#apache

I think the apache-example could be simplified by using https://httpd.apache.org/docs/2.4/mod/mod_dir.html#fallbackresource instead of `mod_rewrite`?

### What does the proposed API look like?
```
FallbackResource /index.html
```

**Comment by posva** [comment]
Hey, thanks for pointing it out. I don't use Apache `FallbackResource` looks indeed simpler. We are open to PRs for this kind of information but I will also like to have more people review (Will probably post the link to the PR in discord or twitter). Could you please open the PR instead to open up discussion? Thanks!

**Comment by christianmarzian** [comment]
When deploying in subfolders it works for me with an additional '.'
`FallbackResource ./index.html`
