### ISSUE TITLE
Vue Router not working properly in Component when url have some deep

### ISSUE THREAD

**Issue by maki10** [vuejs/vue-router#2093]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/43q4nsx9/2/](https://jsfiddle.net/43q4nsx9/2/)
Go to second home, and click on an image (but you must have some deep's in URL, in order to see the issue) 

### Steps to reproduce
When calling `route-link` form Component, they switch URL bad.
For example:
- My domain is: `example.com/shop/shop-slug/`
- Root Vue make a path: `example.com/shop/shop-slug#/`
- And Bug occurred on `Product` Component when changing the path. Router link adds me: `example.com/#/product/{{ product.id }}`

I try `$router.fullPath` and get `#/product/{{ product.id }}`.
Try to match, replace `router-link` nothing work as I expected?

### What is expected?
To match full URL.

### What is actually happening?
The router doesn't catch good URL

**Comment by maki10** [comment]
Actually, I got now a new issue for this. Because I use `axios` for API call's I just add simple Swiper slider and bug actually start from there.
```js
initialSlider: function() {
	$(window).on('load', function() {
		var swiper = new Swiper('.swiper-container', {
			slidesPerView: 3,
			spaceBetween: 30,
			slidesPerGroup: 3,
			loop: true,
			centeredSlides: true,
			loopFillGroupWithBlank: true,
			pagination: {
				el: '.swiper-pagination',
				clickable: true,
			},
			navigation: {
				nextEl: '.swiper-button-next',
				prevEl: '.swiper-button-prev',
			},
		});
	});	
}

axios.post("api/product/"+this.productId).then((res) => {
	this.product = res.data.data;

	this.initialSlider();
}).catch((error) => {
	this.showErrorMessage(error);
});
```

When removed Swiper, everything works normally.

**Comment by posva** [comment]
Hello, everything is working when I try it. BTW remember to use non-minified versions of vue and router, you had a template with a compilation error (but it wasn't changing anything).
Regarding the second thing, that's something you should ask in the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js)
