### ISSUE TITLE
Setting pushState title

### ISSUE THREAD

**Issue by dotnetCarpenter** [vuejs/vue-router#2099]
### What problem does this feature solve?
Is there any objections against a PR that opens up for setting the `pushState()` title argument in [push-state.js](https://github.com/vuejs/vue-router/blob/dev/src/util/push-state.js#L50).

I'm porting an app to use vue-router and the app had this before. I realise that Firefox ignores the title, but other browsers do not. The app is using vue-router to enable deep linking. The app display PDFs with hundreds of pages. I got the back/forward buttons working pretty easily but the resulting list is completely unreadable, since it is just the `document.title` repeated 10-100 times. I would like to add the page number to each entry.

### What does the proposed API look like?
Not sure... Could be:
```js
this.$router.push({
  meta: { title: `page ${pageCurrent} - foobar` }
})
```
But I don't have any preferences other than the one the vue-router team + community prefer. :)

**Comment by posva** [comment]
Thanks for your interest. This is something I need to think a bit more about before accepting a PR. Browsers ignoring it is indeed a problem. Passing a meta attribute is like passing state around, so careful about that 😅

**Comment by dotnetCarpenter** [comment]
You're right. Instead of misusing a current attribute, we could introduce a new one?

```js
this.$router.push({
  stateTitle: `page ${pageCurrent} - foobar`
})
```

The idea is to reflect the state of the app in the URL, right? Synchronising to the address bar is our public ~API~ state, to enable the user to copy/paste from and send how-ever they want, to whom-ever they want. The `stateTitle` is a meta label of the current URL state, so the browser can display a list of states (URLs) and make them easily recognisable. I guess I'm not getting why it's bad to pass state around..

You mean, be careful as in state management, use vuex, single source of truth, kinda way? I'm using vuex and synchronising the address bar, via `this.$router.push` in actions. I don't use `meta` for anything, so I'm (_blissfully_) unaware of the pitfalls.

**Comment by dotnetCarpenter** [comment]
~I realise that Firefox ignores the title, but other browsers do not.~ I take that back. Even though [their documentation says that it's not supported](https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_pushState()_method), they do indeed display `stateTitle`. I have just tested in Firefox 60.0b1 on macOS.

![screen shot 2018-03-09 at 19 10 55](https://user-images.githubusercontent.com/43763/37222497-9edf421e-23cd-11e8-913a-3f47ae44fbab.png)

**Comment by dotnetCarpenter** [comment]
@posva Where should I add a test, if I wanted to implement this? In `test/unit/specs/api.spec.js` - `'router.push/replace callbacks'` section?

**Comment by posva** [comment]
Given how browsers haven't aligned on the second argument and how it is recommended to pass an empty string `''` (which is what the router does) and that you can still overwrite it yourself after a router navigation like this:


```js
await router.push('/somewhere')
history.replaceState(history.state, 'my title')
```

It's better to drop it. If the spec ever changes about the second parameter we will revisit this through an RFC
