### ISSUE TITLE
Accessing template variables outside of router-view in basic app

### ISSUE THREAD

**Issue by jsantari** [vuejs/vue-router#210]
In the basic example I'd like to put values into the #app template which is the wrapper for <router-view>. For example if I change the heading to this <h1>Hello App! {{name}}</h1> why can't I update it by App.$set('name','Jim') ? What am I missing on how this works?

**Comment by yyx990803** [comment]
`App` is just a component definition. It is **not the app instance**.

The app instance is `router.app`.
