### ISSUE TITLE
In beforeEach hook , call next with a callback is invalid

### ISSUE THREAD

**Issue by viruscamp** [vuejs/vue-router#2104]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/viruscamp/z6j6yozx/3/](https://jsfiddle.net/viruscamp/z6j6yozx/3/)

### Steps to reproduce
Run this jsfiddle, open js console, and click "Go to Foo "

### What is expected?
Js console show:

```
router.beforeEach /foo  
router.beforeEach.next /foo  
routeConfig.beforeEnter /foo  
routeConfig.beforeEnter.next /foo  
router.beforeResolve /foo  
router.beforeResolve.next /foo  
```

### What is actually happening?
Js console show:

```
router.beforeEach /foo  
routeConfig.beforeEnter /foo  
router.beforeResolve /foo  
```

---
As https://github.com/vuejs/vue-router/blob/dev/types/router.d.ts show:  
router.beforeEach, routeConfig.beforeEnter, router.beforeResolve use NavigationGuard  
and next in NavigationGuard receive ((vm: Vue) => any) as argument  
But I cannot use this feature as the code show

**Comment by LinusBorg** [comment]
Passing a callback only works with the In-Component hook `beforeRouteEnter`. Re-read the docs please.

> Note that beforeRouteEnter is the only guard that supports passing a callback to next.

**Comment by viruscamp** [comment]
So It's better to split 'NavigationGuard' as two different types..

**Comment by posva** [comment]
There's an open issue to make this behaviour consistent though 🙂
