### ISSUE TITLE
The router clicked but the url and view not updated follow

### ISSUE THREAD

**Issue by lichenhao** [vuejs/vue-router#2107]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/v3ox6n8xj0](https://codesandbox.io/s/v3ox6n8xj0)

### Steps to reproduce
Run with this code 
`<router-link :to="someroute.path"></route-link>`
and click more 
Sometime the history or hash will not changed.

### What is expected?
The page state should be switched.

### What is actually happening?
Nothing happend

**Comment by posva** [comment]
Sorry but I cannot reproduce
