### ISSUE TITLE
Allow the router to control the history of an iframe

### ISSUE THREAD

**Issue by AndreyVMarkelov** [vuejs/vue-router#2108]
### Version
3.0.1

### Reproduction link
[https://github.com/vuejs/vue-router/blob/dev/src/util/push-state.js#L44](https://github.com/vuejs/vue-router/blob/dev/src/util/push-state.js#L44)

### Steps to reproduce
Run application into iframe

### What is expected?
Please, add the way to setup window.top in VueRouter

### What is actually happening?
const history = window.history
is used 
should be way to use
const history = window.top.history
via some flag

**Comment by AndreyVMarkelov** [comment]
I can add PR shortly if you ready to access this

**Comment by posva** [comment]
I imagine a window property could be added to html history and make it configurable through an option in Router constructor but I wonder if this is going to work everywhere or not and if it introduces any side effet

**Comment by AndreyVMarkelov** [comment]
@posva I expect to add extra flag to push method to specify which history to take

**Comment by posva** [comment]
I don't think that's a good idea because it means the url could come from different places in one single application

**Comment by AndreyVMarkelov** [comment]
Any ideas then how to work inside iframe? If I wanna open by direct links

**Comment by posva** [comment]
What I'm saying is that is that if the window property is set, it should directly be in the Router construcor, for the whole application

**Comment by AndreyVMarkelov** [comment]
I dont see the way to propagate window to router constructor

**Comment by posva** [comment]
Note to myself: maybe through a custom history: https://github.com/vuejs/vue-router/issues/2052

**Comment by posva** [comment]
After some time this hasn't gained enough traction. I think this would be possible through a custom history but maybe it's not enough. If you still want to pursue this idea, please go [through the RFC process](https://github.com/vuejs/rfcs)
