### ISSUE TITLE
Can customize scroll element not just window by using scrollBehavior api.

### ISSUE THREAD

**Issue by wangyi7099** [vuejs/vue-router#2109]
### What problem does this feature solve?
When using scrollBehavior api, it seems that only supports window scroll i.e.
```javascript
const router = new VueRouter({
    routes: [...],
    scrollBehavior(to, from, savedPosition) {
        {
            x: 10,
            y: 10
        }
    }
})

// window triggers scrolling
window.scrollTo({x: 10, y: 10});

```
,  so, I hope add a param into the return object `element`, that the element triggers scrolling, not only window.  

### What does the proposed API look like?
```javascript
const router = new VueRouter({
    routes: [...],
    scrollBehavior(to, from, savedPosition) {
        {
            return {
                element: document.querySelector("#app"),
                x: 10,
                y: 10
            }
        }
    }
})

//
// element triggers scrolling
element.scrollTo({x: 10, y: 10});
```

**Comment by posva** [comment]
you can already do that with `selector`: https://router.vuejs.org/en/advanced/scroll-behavior.html

**Comment by wangyi7099** [comment]
@posva 

But this is not what I want..  FYI, the `selector` only represents that will scroll to its position, not trigger scrolling itself.   The window will still trigger scrolling eventually. 
Like: 
// `window.scrollTo()`
I hope the passed element  trigger scrolling,
 Like:
// `element.scrollTo({x: 10, y: 10});`

**Comment by posva** [comment]
Ah sorry, this is a duplicate of #1187

**Comment by wangyi7099** [comment]
Thanks ! Got it:)
