### ISSUE TITLE
Progress bar possibility

### ISSUE THREAD

**Issue by crispouille** [vuejs/vue-router#211]
Hey,

Keep in mind that i'm pretty new in the front-end dev world. I'm using vuerouter with a full vuejs site, on an express nodejs server. I would love to have a progress bar during the transition of my route components.
Do you have any guide line to have the loading of the route components in a progress bar, to finaly make the transition ?
Think that would only work with the promises ?
Thanks a lot !

**Comment by crispouille** [comment]
For exemple, i've got a video in the template of one of my components. I would love to display a loading state during the time of this video loading.

**Comment by amirrustam** [comment]
@crispouille You can use `$loadingRouteData` to show a progress bar while in a loading state:

```javascript
<div class="view">
  <div v-if="$loadingRouteData">
    <div id="my-progress-bar"></div>
  </div>
  <div v-if="!$loadingRouteData">
    <my-component></my-component>
  </div>
</div>
```
Also as a note for the future, these types are questions are best suited for the community forums or gitter. The issues section is for reporting bugs, enhancements, and providing development feedback. Please review the Issue Reporting Guidelines: https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines

Thanks

**Comment by amirrustam** [comment]
@crispouille if you want follow up on this question please do so in the forums and just link back to this issue for reference. 

@yyx990803 I think this issue can be closed out.

**Comment by weituotian** [comment]
@amirrustam 
`
vue.esm.js?efeb:591 [Vue warn]: Property or method "$loadingRouteData" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
`

```
        <div v-if="$loadingRouteData">
            <h1>loading</h1>
        </div>
```

nothing help?
