### ISSUE TITLE
Configured with routing function to generate lazy loading will not work

### ISSUE THREAD

**Issue by lynzz** [vuejs/vue-router#2112]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/63ljm6z9k](https://codesandbox.io/s/63ljm6z9k)

### Steps to reproduce
1.  Routed to the User, view router-view content
2. Routed to the Log, view router-view content

### What is expected?
1.  Routed to the User, router-view content for the user
2. Routed to the Log, router-view content for the log

### What is actually happening?
1.  Routed to the User, router-view content remains at home
2. Routed to the Log, router-view content remains at home

---
Lazy loading can be defined directly on a home and not using a function to handle, is the import did not permit such treatment

**Comment by posva** [comment]
This is a webpack question, please use the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions.

---

BTW, you probably want to use `item.component` instead of `item.components`
