### ISSUE TITLE
v-link with string in quotes not working

### ISSUE THREAD

**Issue by marcvdm** [vuejs/vue-router#212]
When using ``v-link="'/about'"`` the quotes are taken as literal

so ``v-link="'/about'"`` does not work goes to ``#!/'about'``
and ``v-link.literal="/about"`` does work and goes to ``#!/about``

I have made a fiddle as example.
https://jsfiddle.net/9onh9ph8/

I log the path in the console.

This is with vue 1.0.3 and vue-router v0.7.5

**Comment by lpreterite** [comment]
You use the Vue 1.0.6 to resolve.

**Comment by yyx990803** [comment]
This should have been fixed with latest version of Vue core.
