### ISSUE TITLE
implicit params ({ name: 'sub-route' }) don't update when navigating between nested routes

### ISSUE THREAD

**Issue by mudoo** [vuejs/vue-router#2121]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/67xnq5to/](https://jsfiddle.net/67xnq5to/)

### Steps to reproduce
1. click /foo/1/sub1
2. click /foo/2/sub1
3. click sub2

### What is expected?
id==2

### What is actually happening?
id is 1

like #1255

**Comment by posva** [comment]
Thanks for the short repo, this is something that will disappear once we use the functional router-link version

**Comment by reinhardt1053** [comment]
Any workaround?

**Comment by posva** [comment]
@reinhardt1053 The workaround is explicitly passing the param: 

```js
const FooSub1 = {
  template: '<router-link :to="{name:\'sub2\', params: { id: $route.params.id}}">sub2</router-link>'
}
```

Sorry for the delay 😅

**Comment by jesusfreak3** [comment]
@posva I tried that already, which does not work for me.

Routes

```
{
      path: '/products',
      component: {
        template: `
          <div>
            <router-view></router-view>
          </div>`
      },
      meta: {
        breadcrumb: 'Products'
      },
      children: [
        {
          path: '',
          name: 'products',
          component: Products,
          props: true
        },
        {
          path: ':uid',
          name: 'product',
          component: Product,
          props: (route) => ({ uid: route.params.uid }),
          meta: {
            breadcrumb: 'product'
          }
        }
      ]
    },
```

Then I would generate a list of products with a router link for each

`<router-link :to="{ name: 'product', params: { uid: props.row.uid} }">{{ props.row.title }}</router-link>`

The first click would work, but then the next click on another router link, the uid would stay the same as the first.

![image](https://user-images.githubusercontent.com/863030/42294442-e430fdf2-7fae-11e8-8027-b4f8daca7f5b.png)

The only way i was able to get around it for now was to use a router link with the path parameter and manually creating the path with the prop.

> :to="{ path: '/products/' + props.row.uid }"

then the anchors would render correctly.

**Comment by hlongjuice** [comment]
I have the same issue 

when I use Router-link with Name and Params
<router-link :to={name:'content_category_edit',params:{id:number}}>edit</router-link>
1. id=1
2. id=2 
the first click work well but when I go back two route-link alway have same url 

but  it work if I use like below
<router-link :to="'/content_category/edit/'+item.id">edit</router-link>
<router-link :to="'/content_category/edit/'+item.id">edit</router-link>

**Comment by rlfrahm** [comment]
Checkout this comment which mighttttt be your problem? https://github.com/vuejs/vue-router/issues/1255#issuecomment-416002706

**Comment by econic** [comment]
I just came across the same issue in my app, built an example https://codesandbox.io/s/p5rm135m0 to report the bug and came across this one. Not entirely sure if it's the same issue.
Any updates on the fix?

**Comment by posva** [comment]
yeah, looks like the same
