### ISSUE TITLE
Navigating with anchor tag makes `exact` router-links lost its class

### ISSUE THREAD

**Issue by shirohana** [vuejs/vue-router#2123]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/1340kjpvvl?autoresize=1&initialpath=%2Fa%2F1&module=%2Fsrc%2Fcomponents%2Fview.vue](https://codesandbox.io/s/1340kjpvvl?autoresize=1&initialpath=%2Fa%2F1&module=%2Fsrc%2Fcomponents%2Fview.vue)

### Steps to reproduce
(From demo page)

1. Click `Anchor tags` link, it will append `#anchor` to the href of current page
2. Click `refresh` link, just like sharing a link with a specific paragraph

### What is expected?
The link should still has its active class (but only when `mode: 'history'`)

### What is actually happening?
`vue-router` also compared its `hash`, so it's no longer `exact` and lost its class

---
I think if we're in `history mode`, it is no need to compare `route.hash`

https://github.com/vuejs/vue-router/blob/dev/src/util/route.js#L73-L94

**Comment by posva** [comment]
Let's move the discussion to #2040 (which was originally for queries) but it is the same kind of problem: exact is not flexible enough

**Comment by shirohana** [comment]
I see, thanks :)
