### ISSUE TITLE
query values should be casted into strings

### ISSUE THREAD

**Issue by Astray-git** [vuejs/vue-router#2131]
### Version
3.0.1

### Reproduction link
[http://jsfiddle.net/L7hscd8h/6976/](http://jsfiddle.net/L7hscd8h/6976/)

### Steps to reproduce
click 'a'

query `z` added as Number in `beforeRouteEnter`

`typeof query.z` is Number

### What is expected?
query props should be String

### What is actually happening?
no stringify applied on programmatic navigation (`next`, `this.$router.push` etc.)

**Comment by posva** [comment]
This is something that could break existing application, so we may have to wait for a major release.
For the moment you can add your own https://router.vuejs.org/en/api/options.html#parsequery--stringifyquery to overcome this, although JS handles number -> string casting ok

**Comment by Astray-git** [comment]
😢`parseQuery` is not called on transition query:
https://github.com/vuejs/vue-router/blob/dev/src/util/query.js#L20
`extraQuery` is typed as `{ [key: string]: string }` and assigned directly without type casting.

Maybe we can add a coercion option for extraQuery?

**Comment by posva** [comment]
I have changed my mind regarding not casting (https://github.com/vuejs/vue-router/issues/2131#issuecomment-376957750)
I think we should always cast to string, and regarding ts types, allow strings and numbers for convenience but let users manually cast anything else
