### ISSUE TITLE
IOS Url Schemes not working on safari

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuejs/vue-router#2132]
### Version
3.0.1

### Reproduction link
[prefs://root=General&path=ManagedConfigurationList](prefs://root=General&path=ManagedConfigurationList)

### Steps to reproduce
1. Put pref href prefs://root=General&path=ManagedConfigurationList
2. a href="prefs://root=General&path=ManagedConfigurationList"
3. click anchor tag
4. Safari invalid address 

### What is expected?
Must open configuration manager / settings

### What is actually happening?
Safari invalid address

**Comment by posva** [comment]
Please, provide a repro and more context about this, it is the first time I hear about `prefs://` for Safari. The URL is indeed quite unconventional

**Comment by ralphchristianeclipse** [comment]
@posva https://github.com/phynet/iOS-URL-Schemes

this are the schemes to open ios settings using the url scheme

we are using this on a simple html file and it works but with vue-router in history mode

it doesn't

This only works in IOS Phones

**Comment by ralphchristianeclipse** [comment]
https://codepen.io/anon/pen/oqEvxG

Here is the html version

Vue version with vue router

https://codesandbox.io/s/wnp5vq79yw

right now i can't test this out ( I don't have IPHONE )  **android user** :(

but this is the exact code we are doing

**Comment by posva** [comment]
If you cannot test it how can you say it doesn't work? 😕 
Will give it a try on Simulator

**Comment by posva** [comment]
The raw HTML codepen doesn't work, I'll wait for a working demo

**Comment by ralphchristianeclipse** [comment]
@posva we only tested it in safari

We tested it yesterday and it really doesn't work on vue but works on the html 

As i said Safari is saying invalid address on the url scheme on an IOS phone

**Comment by posva** [comment]
Closing as this doesn't seem to be related to vue router anyway
Will reopen if  repro is provided

**Comment by ralphchristianeclipse** [comment]
@posva This is the example site that we used as a reference (PS: NSFW (not safe for work) xD only 18+ above)

http://c0001.hysfjx.cn/index.html#abs|
please open it on mobile only it will auto redirect to baidu.com if not on mobile mode

here is the js for the site

http://c0001.hysfjx.cn/js/index.js

we just want to open the ios settings on prefs menu
