### ISSUE TITLE
Vue-Router seeks and makes use of the first anchor element inside the component

### ISSUE THREAD

**Issue by pzanitti** [vuejs/vue-router#2134]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/50wL7mdz/250344/](https://jsfiddle.net/50wL7mdz/250344/)

### Steps to reproduce
Make a `router-link` whose `tag` attribute is not `a`, and place an anchor element inside it.

### What is expected?
The click listener should bind to self.

### What is actually happening?
The click listener binds to the first inner anchor element, disregarding self.

---
There are several things at play here:

1. I want the whole card to be user-clickable.
2. I prerender my pages using `prerenderer-spa-plugin` and I want only the title of the card to be an anchor element for SEO reasons.
3. Again for SEO reasons, I don't want the whole card to be an anchor element since it will also contain `Content` and `More content` as anchor text.

Now I understand where this behavior is coming from, it's trying to prevent a child anchor from triggering a full page navigation. Without using `router-link` I can get the best of both worlds by making a clickable div whose event does not propagate and trigger the inner anchor while web crawlers still relate `/route/3` to `I am a good link`:

```
<div class="card" @click.prevent="$router.push({ name: 'MyRoute', params: { id: 3 } })">
  <h2><a href="/route/3">I am a good link</a></h2>
  <p>Content</p>
  <p>More content</p>
</div>
```

These lines are responsible for this behavior:

https://github.com/vuejs/vue-router/blob/9880cbda8dd299315a253abaab69da00eecdf635/src/components/link.js#L86-L99

Note a shortcoming of this implementation: should the user place more than one anchor element inside the `router-link`, only the first one will get enhanced while the other ones will still trigger a full page reload. To me that scenario makes little sense and I have no idea of any real use case, but perhaps it should raise a warning.

Is there any 'official' stance on my workaround?

**Comment by posva** [comment]
this was intended behaviour, so for the moment, you will have to handle the click yourself on the card, using a `.stop` and still use router-link (I know, it's one year later)

For the current version of vue-router, a prop could be enough to apply the click behaviour to the root element instead but I'm thinking we might also need a way to disable the click to trigger navigation on the router-link which relates to https://github.com/vuejs/vue-router/pull/2098

**Comment by posva** [comment]
This can now be solved with the v-slot api of router-link
