### ISSUE TITLE
Default deeply nested route and active-class Prop

### ISSUE THREAD

**Issue by eyad-alshami** [vuejs/vue-router#2136]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/Iyadorf/dy0e4412/](https://jsfiddle.net/Iyadorf/dy0e4412/)

### Steps to reproduce
click on BrowseCommenters

### What is expected?
only dashbord -> commenter -> BrowseCommenters
will have the router-link-active CSS class on them

### What is actually happening?
 dashbord -> commenter -> [BrowseCommenters and NewCommenter]
are all having the router-link-active CSS class on them

**Comment by posva** [comment]
If you don't want that behaviour you have to use the `exact` prop in NewCommenter as you did with DefaultIntent

**Comment by eyad-alshami** [comment]
I am sorry but it didn't work, I put the exact prop in NewCommenter but that didn't solve the problem.
In the vuejs Forum someone has pointed that this might be a bug, here is the url:

https://forum.vuejs.org/t/default-deeply-nested-route-and-active-class-prop/25949/4

**Comment by posva** [comment]
it does: https://jsfiddle.net/juu7L163/

**Comment by eyad-alshami** [comment]
Thank you very much for the prompt reply

when I click on CustomReply
NewCommenter should have the router-link-active CSS class on too, but it does not.

**Comment by posva** [comment]
Ah, about that specific case, you will have to apply custom logic. The matching is about the URL not the routing nesting. 
Maybe you are using nesting while what you need is namespacing which can be achieved with a function (that you can write yourself and simply prepend a path to an array of routes)

**Comment by eyad-alshami** [comment]
Thank you very much, you gave me a nudge in the right direction 👍
