### ISSUE TITLE
Router guard not working when coming from page its supposed to redirect if condition does not match

### ISSUE THREAD

**Issue by iamsayantan** [vuejs/vue-router#2139]
### Version
2.0.1

### Reproduction link
[https://jsfiddle.net/jrfd3x89/](https://jsfiddle.net/jrfd3x89/)

### Steps to reproduce
So I have three components, Secured, NonSecured and Dummy associated to three routes. Secured routes should be accessed only by users who has access. And the router guard checks for that. If the user does not have permission then navigating the user to NonSecured page. 
 if you navigate from Dummy to Secured you would be redirected to NonSecured which is what supposed to happen. but if you navigate from NonSecured to Secured page, then you would be allowed to access. 

### What is expected?
If I have router guard enabled for a route, then the route should not be accessed if the guard logic is not met.

### What is actually happening?
The protected route can be accessed if I navigate to the protected route from the page where it redirects if guard logic is not met.

**Comment by posva** [comment]
You can only call `next` once, in your case you need to return inside of the first if (or return everytime you do next)
