### ISSUE TITLE
Allow paths with trailing slash.

### ISSUE THREAD

**Issue by b-3-n** [vuejs/vue-router#2141]
### What problem does this feature solve?
Right now if I specify a route with "path: '/about/'" and I redirect to it the browser URL will be set to '.../about'.

This creates various issues. For example, Google Analytics will report usage statistics about '/about' and '/about/' (the latter we get if the user arrives on our page at /about as the browser appends a slash). Clearly this should be fixed on our end and I'm sure there are a lot of other cases where this creates problems. 

### What does the proposed API look like?
Disclaimer: I don't know if this breaks something else.

It would be great if "path: '/about/'" would add a trailing slash when redirecting to the route.

**Comment by posva** [comment]
Check `pathToRegexpOptions` in vue-router and use the `strict` option (https://github.com/pillarjs/path-to-regexp/tree/0.1.x)
