### ISSUE TITLE
Enhancement on reusable router view

### ISSUE THREAD

**Issue by lepture** [vuejs/vue-router#2142]
### What problem does this feature solve?
Use a shared router view among different route paths. I'm creating a dashboard dynamically, which only need three views:

1. List View
2. Create View
3. Edit View

Let's create three files: `PageList.vue`, `PageCreate.vue`, `PageEdit.vue`, and use them in routes.

### What does the proposed API look like?
```js
routes = [
   {path: '/users', component: PageList},
   {path: '/users/create', component: PageCreate},
   {path: '/users/:id', component: PageEdit},
   {path: '/posts', component: PageList},
   {path: '/posts/create', component: PageCreate},
   {path: '/posts/:id', component: PageEdit},
]
```

Currently, this won't work properly. Actually, it has a bug, the `poll` function will run infinitely when switching routes.

## Current Bug

If you have such routes, and using navigation guard, the `poll` function will run infinitely when switching routes.

```js
routes = [
   {path: '/users', component: PageList},
   {path: '/posts', component: PageList},
]
```

If you add a `console.log` here https://github.com/vuejs/vue-router/blob/dev/src/history/base.js#L315
it will print log infinitely, because `instances[key]` will always be undefined.

My current solution:

```js
routes = [
   {path: '/users', component: Object.assign({}, PageList)},
   {path: '/posts', component: Object.assign({}, PageList)},
]
```

**Comment by JounQin** [comment]
What you need is nested route children.

https://router.vuejs.org/en/essentials/nested-routes.html

**Comment by lepture** [comment]
@JounQin you haven't understood the issue. They are not children, they are shared views.

**Comment by JounQin** [comment]
Then please provide a minimal reproduction.

**Comment by lepture** [comment]
@JounQin please read "Current Bug" section. This is a feature request rather than bug report, and I will implement it later.

**Comment by sqal** [comment]
This is the same issue i described here https://github.com/vuejs/vue-router/issues/1272 and it's not a bug because you reuse the same component for different routes. @posva explained this with solution (your is also valid i guess)

**Comment by lepture** [comment]
@sqal that `:key="$route.name"` works like a charm. thank you.
