### ISSUE TITLE
Default tab not showing

### ISSUE THREAD

**Issue by quenti77** [vuejs/vue-router#2145]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/L7hscd8h/7987/](https://jsfiddle.net/L7hscd8h/7987/)

### Steps to reproduce
In jsfiddle click on **/user/foo** link
Home component does not appear
But if use path instead of name, component home appear.

### What is expected?
That the home component appear with name property

### What is actually happening?
The home component doesn't appear

**Comment by posva** [comment]
That is intended, you have to refer to the child's name
