### ISSUE TITLE
怎么在hash前面添加一个?

### ISSUE THREAD

**Issue by Pasoul** [vuejs/vue-router#2149]
### What problem does this feature solve?
vue-router使用的是hash模式，
如果页面地址为xxx.com/web#/home，支付目录必须为xxx.com/web/；
如果页面被分享出去了，微信会给url添加参数，xxx.com/web?from=singlemessage&isappinstalled=0#/home，微信会忽略?后面的参数，如果去支付，支付目录必须为xx.com/；
如果在hash前添加?，此时url为xxx.com/web?#/home，由于微信会忽略?后面的参数，那么支付目录可以统一成xx.com

### What does the proposed API look like?
未知

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
