### ISSUE TITLE
 router-view:key="$route.path" hot reload

### ISSUE THREAD

**Issue by ccqgithub** [vuejs/vue-router#2150]
### What problem does this feature solve?
now, if i use router-view with `key` like this:

```
        <div class="sma-mod">
          <transition name="mod">
            <keep-alive>
              <router-view
                :key="$route.path"
                ref="router"
              ></router-view>
            </keep-alive>
          </transition>
        </div>
```
when i modify `js`, the current component disappear, when i modify `template` or `style`, it is right.

want:  can hot reload with `key router-view`

### What does the proposed API look like?
```
        <div class="sma-mod">
          <transition name="mod">
            <keep-alive>
              <router-view
                :key="$route.path"
                ref="router"
              ></router-view>
            </keep-alive>
          </transition>
        </div>
```

**Comment by posva** [comment]
Tested with vue-cli@beta and the problem seems related to the presence of `keep-alive` but happens without the router. Could you report this back to vue-loader?
