### ISSUE TITLE
Extra params should be ignored

### ISSUE THREAD

**Issue by fracz** [vuejs/vue-router#2151]
### What problem does this feature solve?
I have a route defined like this:

```
{path: '/entities/:id', component: () => import("...."), name: 'entity', props: true}
```

Then, I have a loaded `entity` instance in my code, so in order to create a link, I need to write:

```
<router-link :to="{name: 'entity', params: {id: myEntity.id}}">Link</router-link>
```

Being lazy, I was slightly less explicit about params and relying on the fact that `entity` contains an `id` field required by the route, I have created the link in the following way:

```
<router-link :to="{name: 'entity', params: myEntity}">Link</router-link>
```

Glad it worked for quite a long time, until I discovered that all extra parameters are not ignored but added to the `<router-view>` element as html attributes. So, for example, if the `myEntity` contains a `name` property besides the `id`, the `id` prop is properly consumed by the component but all the others are left on HTML element produced by `router-view`.

```
<div name="Name from entity">
```

IMO, all extra parameters (not defined in the route) should be ignored and not passed as `props` to the element.

What do you think?

I know there are at least two solutions: 1. not being lazy and 2. use function mode of the `props` to extract only props that are defined in the route. But I think this should be a default behavior.

Fun fact: I have discovered it when `myEntity` contained a `hidden: true` property and it resulted in `hidden="true"` HTML attribute on the whole `router-view`. You can guess how big WTF I had when debugging it... :-)

### What does the proposed API look like?
API does not change.

**Comment by emanuelmutschlechner** [comment]
I think this is expected behavior of vue. 

Did you try setting `inheritAttrs: false` and `props: ['id']` in your entity page component?
[Link to docs](https://vuejs.org/v2/api/#inheritAttrs)

**Comment by posva** [comment]
Yes, this is expected behaviour because of `props: true` letting params fall through. The good practice would be to provide only necessary props
