### ISSUE TITLE
有一个机制能让过渡动效左右两侧的界面处于不同的滚动状态，这样才能更像APP能达到的功能

### ISSUE THREAD

**Issue by likyh** [vuejs/vue-router#2152]
### What problem does this feature solve?
Vue Router在切换加上动画之后，怎么解决滚动栏的问题？

在页面都处于顶部的时候是正常的，但某一侧页面滚动到一半位置，无论怎么做切换，两侧都会处于同一个滚动位置。
图：https://segmentfault.com/q/1010000013874925

但是如果我要离开的界面和右侧等待进入的页面滚动位置不一样，这该怎么处理呢，我没有发现让左右滚动条处于不同地方的办法。
（如果采用元素内加上scroll-y，不使用全局的滚动条，会造成fixed定位的元素位置错乱，并且在ios上transform切换时，会自动一处fixed和scroll-y的效果。当然也许是我某个细节没实现对，请求指正）

### What does the proposed API look like?
有一个机制能让左右两侧处于不同的滚动状态，这样才能更像APP能达到的功能

**Comment by posva** [comment]
Please follow the issue reporting guidelines. If you have a question use the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js)

**Comment by bolechen** [comment]
碰到同样的问题，楼主解决了吗？

**Comment by likyh** [comment]
@bolechen 并没有解决。

**Comment by bolechen** [comment]
> @bolechen 并没有解决。

好吧，我目前的做法是加了  opacity: 0; 这样跳到顶部的动作不是那么明显
