### ISSUE TITLE
isSameRoute test order

### ISSUE THREAD

**Issue by hlefebvre** [vuejs/vue-router#2155]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/2zlyzp6mm0](https://codesandbox.io/s/2zlyzp6mm0)

### Steps to reproduce
in the sample just click 'launch' and then 'fail'

in general

1. create a route in the router with a name and a component
2. pragmatically change to the component using this.$router.push({ name: xxx, params: yyy })
3. put some link/button inside the component that will call this.$router.push with the same name but different params

### What is expected?
in the sample: the text should update

in general:

The router should update this.$route.params according to the new values given, the "completion" callback should be called

### What is actually happening?
in the sample: the text is not updated

in general:

The router is not loading the new params, the "abort" callback is called

---
in the isSameRoute function there a several cases
when there is a 'path' it is tested before when there is a 'name'
'path' is mandatory, we cannot create routes without path
thus the "name/params" comparison is never triggered and vue-router considers that the page is the same and aborts the navigation

inverting the order of the tests (testing for name before path) will fix this issue but I do not know enough the vue-router internals do be sure it will not break some other functionalities

**Comment by posva** [comment]
You need to add a param named `title` to you route, otherwise, they are indeed, the same route
