### ISSUE TITLE
video cannot resume play when using vue-router

### ISSUE THREAD

**Issue by Litten1106** [vuejs/vue-router#2160]
#### Version
3.0.1

#### Reproduction link
Because this problem happened at a project which is in development so i cannot offer a demo temporarily

#### Steps to reproduce
At first,I use vue-router in my project which has two pages, let me call them page A and page B
then,I put an video which is fullscreen display in page a, and i overlap a button on the video to control the video to play or pause
when i pause the video,the app will jump from page A to pageB,
paegB has also a button used to jump back to pageA，when i click button on pageB i will emit a event to pageA, and use router.back() to back to pageA, when pageA $on get the event emit in PageB,the paused video will resume to play, in my project, the code Running well in anyone Android machine，but in Iphone6s Iphone8 even in IphoneX when i come back from pageA, i cannot find the scene of the video,so i want to you to make sure,is this caused by vue-router or ios system? thanks a lot , i tried my best but cannot fix it

#### What is expected?
when i come back from pageB, i want to resume my video,but now i cannot see the video scene,and use video's official methods such as  play() or pause() seems useless,so i  reload the video and restart to play,but on any Android machine my code running well,so it make me confused

**Comment by LinusBorg** [comment]
Just to stress it: It is impossible to say what's going on without (runnable) code.
