### ISSUE TITLE
Nested routes doesn't mounting after router push named-routes

### ISSUE THREAD

**Issue by shubich** [vuejs/vue-router#2162]
### Version
2.6.0

### Reproduction link
[https://codepen.io/shubich/pen/MGWoMR](https://codepen.io/shubich/pen/MGWoMR)

### Steps to reproduce
click button "work" and "doesn't work"

### What is expected?
Nested routes mounting after router push named-routes

### What is actually happening?
Nested routes doesn't mounting after router push named-routes

**Comment by posva** [comment]
You have to name the child route

**Comment by shubich** [comment]
@posva how?

**Comment by posva** [comment]
add a `name` in the child route as well and use that one in the `push` 🙂 

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first
