### ISSUE TITLE
Scroll behavior: hash that starts with number

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vue-router#2163]
ref: https://github.com/vuejs/vuepress/issues/121

When the selector starts with `/^#\d/`, should use `getElementById` instead.

**Comment by karanisverma** [comment]
Hey @yyx990803 , I would like to work on this Issue. it would be great if you can point me toward right approach.

**Comment by posva** [comment]
@karanisverma It's in `src/history/base.js` line 199

**Comment by karanisverma** [comment]
Thanks @posva :) looking into it!

**Comment by karanisverma** [comment]
Hi @posva, I have looked at the code base not really sure how this can be fixed 😂.. Moreover I am not able to reproduce this issue at my end.
