### ISSUE TITLE
有没有预加载的路由组件

### ISSUE THREAD

**Issue by haizhilin2013** [vuejs/vue-router#2164]
### What problem does this feature solve?
![default](https://user-images.githubusercontent.com/5070345/38925720-036c87b2-4333-11e8-874a-2afde7ac6bed.png)
图上，用vue-router同时打开了好几个页面，因为每个页面有好多接口，有些接口请求比较慢，有没有一种机制是同时打开好多页面的时候，有个优先级，当打开到最后一个页面时先打开，然后依次载之前的数据呢？就好比队列一样的功能。

### What does the proposed API look like?
vue-router api

**Comment by fnlctrl** [comment]
你需要配置webpack的preload，可参阅：
https://medium.com/webpack/link-rel-prefetch-preload-in-webpack-51a52358f84c

预加载本身不是框架相关的，并且也有webpack的实现，因此vue-router不会考虑重复造轮子
