### ISSUE TITLE
router 嵌套路由，二级路径名，按照 文档实例，无效

### ISSUE THREAD

**Issue by xiaoshengkai** [vuejs/vue-router#2166]
{
      path: '/home/:id',
      component: home,
      children: [
        {
          path: '/publishOrder',
          name: 'publishOrder',
          component: publishOrder
        },
        {
          path: '/todayOrder',
          name: 'todayOrder',
          component: todayOrder
        },
        {
          path: '',
          component: publishOrder
        }
      ]
    }

按照文档示例如此，二级路由匹配不到响应的二级路由组件
其中，把二级路由改为 
      {
          path: '/home/publishOrder',
          name: 'publishOrder',
          component: publishOrder
        },
        {
          path: '/home/todayOrder',
          name: 'todayOrder',
          component: todayOrder
        }
成功

**Comment by hasbug** [comment]
二级里面不要带/了
