### ISSUE TITLE
Allow option to adjust url encoding by path-to-regex

### ISSUE THREAD

**Issue by felorhik** [vuejs/vue-router#2168]
### What problem does this feature solve?
If you need to use a permalink system, where your API routes need to use a path to get the response. An example of this is using Vue as a frontend for Wordpress, but allowing wordpress to dictate the url structure.

So for example

would have a route that looks like:
```
{
      name: 'post',
      path: '/:permalink([0-9] [/][0-9] [/][\\S] )',
      component: StandardArticle
}
```
and a page would have a route that looks like:
```
{
     name: 'page',
     path: '/:permalink*',
     component: StandardPage
}
```

This would mean a post url would look like
/2018/04/some-post
and a page would look like
/some-page

The regular expressions work but when you actually try to use them it would look like 
/2018%2F04%2Fsome-post
for the post route, page route would look fine since it does not have a / normally

I see this is an option in path-to-regex but the option is not forwarded to vue-router. This means that if a path would have a / it would be urlencoded by path-to-regex and makes it seemingly impossible to get around (at least I have not found a way around it).

This would have additional benefits of, for instance being able to not urlencode but instead change / with _ or even encode it to base64 or something.

### What does the proposed API look like?
It would just be passing the second parameter of path to regexp's compile function to the route.
```
{
     name: 'post',
     path: '/:permalink([0-9] [/][0-9] [/][\\S] )',
     compile: {
         encode: (value, token) => value
     },
     component: StandardArticle
},
```
https://github.com/pillarjs/path-to-regexp#compile-reverse-path-to-regexp

https://github.com/vuejs/vue-router/blob/dev/src/util/params.js
on line 20 is where it would need to be passed in some way, `{ pretty: true }` is where the encoding can be changed.

**Comment by posva** [comment]
I don't get very well what you are asking for but the example with `/2018/04/some-post`, it works well

**Comment by felorhik** [comment]
The url has the slashes url encoded through right? 

so the url would be `http://example.com/2018%2F04%2Fsome-post`

If you use the post route,and create a link to it, it will route using urlencode. This comes from the default encoding function from `path-to-regex`, you need to override it to prevent it through the second parameter of `path-to-regex` compile return function.

So to reproduce create a router with 
```
{
     name: 'post',
     path: '/:permalink([0-9]+[/|%2f|%2F][0-9]+[/|%2f|%2F][\\S]+)',
     component: StandardArticle
},
```
Then for the link
```
<router-link tag="h4" :to="{ name: 'post', params: { permalink: permalink } }">Test</router-link>
```
In the component
```
data() {
   permalink: '2018/04/some-post'
}
```

In the example I have made it so it will still "route" with it urlencoded, so using `path: '/:permalink([0-9]+[/][0-9]+[/][\\S]+)'` might show it easier

**Comment by posva** [comment]
I tested with the urls you provided so please, provide a repro in a jsfiddle

**Comment by felorhik** [comment]
https://jsfiddle.net/vzeLrjo0/6/

Clicking on the link to go to the "Foo" component will show the current url the browser sees.

**Comment by posva** [comment]
Ah, now I see what you mean.
By the way, you can get around that by using a string value instead of an object (it will actually be the same link from vue-router perspective): `<router-link :to="'/' +permalink">{{ permalink }}</router-link>`

**Comment by felorhik** [comment]
That is interesting, I will try it (works in the jsfiddle witch is cool). I had always liked to be explicit so I never thought it would handle them differently.

I think them being handled differently is a slight concern, but there is a workaround so for me its no longer a complete wall on the project I am working on, so thank you for pointing that out, I would of likely never have thought that.

For this feature request though, I still think its fairly valid, having optional access to the encoder would be good.

**Comment by felorhik** [comment]
Although the solution to use a path instead of an object works, when matching the regular expressions it will sometimes urlencode the string, and sometimes not before matching.

I had used 
```
/:permalink([0-9]+[/|%2f|%2F][0-9]+[/|%2f|%2F][\\S]+)
```

in testing but technically it should be

```
/:permalink([0-9]+[/][0-9]+[/][\\S]+)
```

However the second does not always work. When you initially load the page it does not urlencode the path before checking the router, but when you click a link it will.

Not something hard to get around, but still an interesting issue that can come up. Path in the url remains correct regardless using a string instead of an object for links.

**Comment by Garito** [comment]
+1 on having control of the escape process

My use case is about arbitrary trees so no tricks would work except to control the escape process
The manual path is not a solution either cause I'm going to have several routes and would be not nice to use them manually

**Comment by gertjanwytynck** [comment]
+1 This would be very handy. 

Did someone manage to make it work at this time? To have control on the escape process of that route/named param?

**Edit**: I found a working solution via this issue #1175

**Comment by posva** [comment]
After investing quite a lot of time in understanding encoding and providing a solution that works out of the box in different browsers in v4, I don't think it is a good idea to allow people to customize the encoding. In the specific problem exposed, one should use a path with multiple parameters and can put them together with the `props` option:

```js
{
  path: '/:year(\\d{4})/:month(\\d{2})/:slug',
  props: to => ({ permalink: `${to.params.year}/${to.params.month}/${to.params.slug}` })
}
```

This is to be able to use the slash characters in parameters (since they need to be escaped) without being considered as separators, as by default, a param regex excludes the slash: `[^/]+`.

If there are other use cases that make customizing character encoding a must, they should be discussed using the [RFC proccess](https://github.com/vuejs/rfcs)
