### ISSUE TITLE
Documentation link is down? 

### ISSUE THREAD

**Issue by luchux** [vuejs/vue-router#2171]
### Version
3.0.1

### Reproduction link
[https://router.vuejs.org/](https://router.vuejs.org/)

### Steps to reproduce
Visit links

### What is expected?
https://router.vuejs.org/ should open docs
http://vuejs.github.io/vue-router should open docs

### What is actually happening?
https://router.vuejs.org/ (down) 
http://vuejs.github.io/vue-router (down)

**Comment by posva** [comment]
Both seem to work fine
