### ISSUE TITLE
Route switching increases memory consume

### ISSUE THREAD

**Issue by guarah** [vuejs/vue-router#2177]
### Version
3.0.1

### Reproduction link
[https://github.com/guarah/memory-leak](https://github.com/guarah/memory-leak)

### Steps to reproduce
1 - yarn install
2 - yarn serve
3 - select a main route
4 - switch multiple times between child routes
5 - check the memory consume

### What is expected?
Increasing memory when switching routes

### What is actually happening?
When switching between child routes multiple times, the memory consume increases a lot.

---
In our company we have an app with this basic setup, loading a few cards in kanban placed in child routes.
When switching from one kanban to another, the memory increases and take so long to decrease.
Apparently the route components keeps in cache. Is there some way to destroy theese components?

**Comment by p-adams** [comment]
Have you tried programmatic navigation using router.replace API? According to the docs, replace does not push a new history entry.

**Comment by guarah** [comment]
@p-adams I'll try this. thanks

**Comment by guarah** [comment]
The problems has nothing to do with vue router or vue at all. Sorry.
