### ISSUE TITLE
am unable to use multiple views giving error

### ISSUE THREAD

**Issue by adityarw** [vuejs/vue-router#2179]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/posva/6du90epg/](https://jsfiddle.net/posva/6du90epg/)

### Steps to reproduce
am new to vue please help me..

routing code :

import Vue from 'vue'
import Router from 'vue-router'
import HelloWorld from '@/components/HelloWorld'
import HelloWorlds from '@/components/HelloWorlds'

Vue.use(Router)

export default new Router({
routes: [
{
path: '/',
component: {
default: HelloWorld,
b: HelloWorlds
}
},
{
path: 'nav',
name: 'HelloWorlds',
component: HelloWorlds
}
]
})

Vue component

<script> export default { name: 'App' } </script> <style> #app { font-family: 'Avenir', Helvetica, Arial, sans-serif; -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale; text-align: center; color: #2c3e50; margin-top: 60px; } </style>

### What is expected?
i need to show 2 view one above the other. 

### What is actually happening?
giving error like this
[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Anonymous>
       <App> at src/App.vue
         <Root>

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

it's _component**s**_ not _component_ if you use named views

**Comment by yezongyang** [comment]
I have a same error when using named view, it maybe caused by vue-loader
