### ISSUE TITLE
Vue router push not working on Firefox

### ISSUE THREAD

**Issue by magarrent** [vuejs/vue-router#2181]
### Version
2.8.1

### Reproduction link
[https://jsfiddle.net/50wL7mdz/332372/](https://jsfiddle.net/50wL7mdz/332372/)

### Steps to reproduce
[Firefox - Last version]

Just added a event to a link, add a param to the vuex and then push the step-2 route, and it doens't works on firefox

### What is expected?
Change url

### What is actually happening?
Not working url

**Comment by posva** [comment]
Your repro doesn't even work... From the top of my head the only problem is see is that it should be `to="/some-path2`

**Comment by magarrent** [comment]
@posva Before the page push, I want to put an object to Vuex, and then push the route, and that push doesn't work

**Comment by posva** [comment]
Please use the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions 🙂
