### ISSUE TITLE
Typescript: `Location` interface typing for query should include arrays

### ISSUE THREAD

**Issue by nowy** [vuejs/vue-router#2182]
### Version
3.0.1

### Reproduction link
[https://router.vuejs.org/en/essentials/navigation.html](https://router.vuejs.org/en/essentials/navigation.html)

### Steps to reproduce
When programmatically navigating on vue router, pass through a dictionary with a param as an array. E.g.
``` json
{
  "foo": ["bar"]
}
```

### What is expected?
Types are expected to work

### What is actually happening?
In `router.d.ts`, the typing for `query`, under `Location` is set to:
`Dictionary<string>`.

This should be set to allow arrays too. Potentially numbers as well?

**Comment by posva** [comment]
It is set to string or string[] which is right.
Unless you use a custom query parser those are the only legal values. Docs should indeed be updated to not use a number.
I'm not sure what is the best option to support different syntaxes based on custom query parser

**Comment by nowy** [comment]
@posva Thanks! Just realised it was done here: https://github.com/vuejs/vue-router/pull/2050
Just hasn't been released. Any knowledge on when next release is?

**Comment by rchl** [comment]
Seems like #2050 is merged now. This can be closed?
