### ISSUE TITLE
Configruation for enable/disable ensureSlash() in hash mode 

### ISSUE THREAD

**Issue by sheggi** [vuejs/vue-router#2183]
### What problem does this feature solve?
Use Case:
vue-route is used beside other scripts, where plain anchors are used.
Clicking a link for `#top` we get `#/top` because of ensureSlash() in hash mode. (There is no route defined for `/top`).
Therefore the other script can't complete because the hash with slash is not recognized.

I guess the ensureSlash() is only required for matching the `/` home route or `/any...` any other route.

Is there otherwise a dependency I don't see, where ensureHash() is required?

### What does the proposed API look like?
Having a configuration is preferable for disabling the default behaviour.

```js
router  = new VueRouter({
    ensureHash: false
});
```

**Comment by posva** [comment]
Clicking on an page anchor will replace the url (browser behaviour). You can however use router links: https://jsfiddle.net/Lc5rryg7/

**Comment by sheggi** [comment]
The given example does not cover anchors outside the vue app, where `location.hash` is used instead of `$route.hash`.

https://jsfiddle.net/mnvcvoos/

The only way the "other module" works and resolves to true, is when "vue module" is disabled.
Why does the vue-route always add a `/` as prefix for hashes?
I guess it's used to convert url fragments to paths within vue-route. My point is, this makes other modules unusable, when vue-route is active.

**Comment by shtief** [comment]
Right now it is not possible to use anchor links outside the vue widget and router when the mode "hash" is on.
The Problem is the ensureHash function, I think.
Example:
```html
<body>
<p>Here is a long text and I want to jump to the app with <a href="#app">App</a></p>
<div id="app"></div>
</body>
```
When you click on the "App" Link the hash will be replaced by "#/app"

**Comment by lastlink** [comment]
For a chrome vuejs plugin I ended up writing my own custom router to make hashes optional.

**Comment by posva** [comment]
If you don't have a URL, you can use the abstract mode

When arriving to `/#foo`, vue router will allow that to be the route `/#/foo`. That's intended behavior and cannot be changed for the current version as it will be a breaking change
