### ISSUE TITLE
Ship Flow types

### ISSUE THREAD

**Issue by sobolevn** [vuejs/vue-router#2185]
### What problem does this feature solve?
I am currently working on providing better developer experience for ones using `flow` +  `vue`: https://github.com/sobolevn/vue-flow-typed

I have noticed that you already have pretty much all the needed types in https://github.com/vuejs/vue-router/blob/dev/flow/declarations.js So, maybe it would be better to ship them with the package?

Or if they are not ready for the "production" shipping, is there anything I can help with?
If you are not interested in providing these types for now, I will just create a custom package at https://github.com/sobolevn/vue-flow-typed

Thanks!

### What does the proposed API look like?
-

**Comment by posva** [comment]
Hi, sorry for the delay. Since they are not shipped with vue core, I think it would make more sense to move them to another repo (I think you already published it).
I know it's very inconvenient and I'm not fully convinced. My concern is that if we stop using flow one day, we may not want to maintain the flow typings. What do you think?

**Comment by sobolevn** [comment]
I think that the best place for `flow` types is in the official `flow-typed` repository.
My project is just a temporary work-around.

`vue-router` types seem complete enough for me, after using it in production for almost 3 months now.

So, my opinion is that we can send a PR to `flow-typed` with the types I have here: https://github.com/sobolevn/vue-flow-typed/blob/master/packages/vue-router/definitions/vue-router_v3.x.x.js/vue-router_v3.x.x.js

**Comment by posva** [comment]
okay, thanks for testing it out in production 🙂

**Comment by posva** [comment]
I won't be able to maintain flow types for vue-router and it looks like it makes sense to keep them in `flow-typed`. Thank you!
