### ISSUE TITLE
history模式下，index.html在二级路由下刷新页面无法读取static文件夹中的资源文件

### ISSUE THREAD

**Issue by KnorienChang** [vuejs/vue-router#2187]
### Version
3.0.1

### Reproduction link
[https://xxx.xx.xxx](https://xxx.xx.xxx)

### Steps to reproduce
vue-cli(2.9.3) vue-router 3.0.1 ，在index.html引用static文件夹下的静态资源，当路由的模式为history且为二级路由的时候，刷新页面并不能正确的获取到静态资源的文件。因vue-cli生成的项目，无法提供例子。

### What is expected?
能否在history模式下，刷新的时候也能够正常的读取到static目录下的静态资源文件

### What is actually happening?
在history模式下且在二级路由的时候，刷新页面的时候不能正确的读取到static文件夹下的静态资源文件

**Comment by KnorienChang** [comment]
已将`./static/xx.xx`文件改为`/static/xx.xx`绝对根路径解决了

**Comment by hanz520** [comment]
nice， get it
