### ISSUE TITLE
wrong work history push state

### ISSUE THREAD

**Issue by ilia-aaron** [vuejs/vue-router#2194]
### Version
3.0.1

### Reproduction link
[http://95.213.163.110:3001/user/578f9322f833fde7b4f479f8](http://95.213.163.110:3001/user/578f9322f833fde7b4f479f8)

### Steps to reproduce
click to  Объявления and see browser adreess

### What is expected?
link change to http://95.213.163.110:3001/user/578f9322f833fde7b4f479f8//ads

### What is actually happening?
link change to http://95.213.163.110:3001/user/578f9322f833fde7b4f479f8/ads

---
I'm using a vue-router, and history is fashion. I have references such as `/user/578f9322f833fde7b4f479f8//ads, the link itself is spelled correctly, and the request to the server goes along the correct path, but in the address bar the link changes to /user/578f9322f833fde7b4f479f8/ads, that is, without 1 slash, and naturally the page refreshes an incident.

**Comment by emanuelmutschlechner** [comment]
I don't think `//` can be used in routes. Route urls get sanitized by this function
https://github.com/vuejs/vue-router/blob/721755df5fb7fa0e9db43025d642c12785f5d606/src/util/path.js#L72-L74

**Comment by posva** [comment]
This is not a valid repro anyway

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by ilia-aaron** [comment]
@emanuelmutschlechner 
Why do you think so? This method allows you to do sorting with a complex routing system. Is there any way to disable this sanitizer?
