### ISSUE TITLE
there are some problems with vue-router in a iframe in ie10

### ISSUE THREAD

**Issue by Mageenz** [vuejs/vue-router#2196]
### Version
2.8.1

### Reproduction link
[https://jsfiddle.net/mage1990/pcoucsx6/2/](https://jsfiddle.net/mage1990/pcoucsx6/2/)

### Steps to reproduce
open the link above in ie10,not the ie10 in ie11's or edge's  f12
click the detail button in the list component
click the back button in the detail component
click the detail button again button again
The page turns white

### What is expected?
The page can be displayed normally.

### What is actually happening?
The page turns white

**Comment by posva** [comment]
Hi, sorry for the delay. I do not have access to IE 10 but works correctly on IE9 with latest version of vue-router and since nobody else said anything and the code doesn't look wrong, I will close this
