### ISSUE TITLE
A link to named router is not working with root path of nested routes.

### ISSUE THREAD

**Issue by eunjae-lee** [vuejs/vue-router#2199]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/63b7utzm/19/](https://jsfiddle.net/63b7utzm/19/)

### Steps to reproduce
From the link above, click `/user`.

### What is expected?
It's supposed to render `UserHome` component.

### What is actually happening?
but it's just rendering `User` component.

---
If you try with https://jsfiddle.net/kx7spvh3/1/ , it will work fine.
The only difference is, this one has links with actual path instead of route names.

**Comment by emanuelmutschlechner** [comment]
Did you even check your console logs?

> Named Route 'User' has a default child route. When navigating to this named route (:to="{name: 'User'"), the default child route will not be rendered. Remove the name from this route and use the name of the default child route for named links instead.

Your code does not follow the route config specifications

**Comment by emanuelmutschlechner** [comment]
I fixed your fiddle. BTW I think you should read the docs and ask questions in our [forum](https://forum.vuejs.org/).

https://jsfiddle.net/63b7utzm/20/

**Comment by posva** [comment]
What @emanuelmutschlechner said

**Comment by eunjae-lee** [comment]
@emanuelmutschlechner Sorry about that. I didn't check the log.
And I'll use the forum when it comes to more like q&a like this.
Thanks for your comment and the fiddle!
