### ISSUE TITLE
How to make sure visiting login route while being authenticated doesn't result in 404 but rather redirect to home?

### ISSUE THREAD

**Issue by aligajani** [vuejs/vue-router#2201]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
**Login Route**

```
 {
        path: '/login',
        name: 'login',
        component: Login,
        meta: { auth: false }
    },
```

**404**

```
{
        path: '/404',
        name: 'error-404',
        component: Error404
    },
```

**Home**

```
{
        path: '/',
        name: 'default',
        component: Home,
        meta: { auth: true }
    }
```

### What is expected?
Visiting login route while authenticated should redirect to home

### What is actually happening?
Visiting login router while authenticated redirects to 404 route

**Comment by posva** [comment]
Please follow issue reporting guidelines. This is a question and should be asked in the forum or discord server
