### ISSUE TITLE
Sometimes the feat `Lazy Loading Routes`  has odd build problem.

### ISSUE THREAD

**Issue by korewayume** [vuejs/vue-router#2202]
### Version
3.0.1

### Reproduction link
[https://github.com/korewayume/abc](https://github.com/korewayume/abc)

### Steps to reproduce

run command : `npm run serve`

commit init is generate by @vue/cli 3.0.0-beta.10

commit success write two `.vue` files:  `src/views/a/index.vue` and `src/views/b/index.vue`, they only have one line different. And `src/views/a/index.vue` is not referenced by `vue-router`.

commit error toggle the line `import router from '@/router';` comment status, and now they are same.

The later commit show some odd behavior about `Lazy Loading Routes`,  even throught the `asComponent` func never used.

### What is expected?
`Lazy Loading Routes`  work well

### What is actually happening?
`Lazy Loading Routes` makes odd

**Comment by posva** [comment]
I'm not getting your issue very well (the _makes odd_ thing is not clear) but this is something related to webpack and not to vue-router, so please use another channel of communication like forums, discord or stackoverflow

if you use `return () => import(`./views/${component}`)`, webpack will make that work with every possible file in views
