### ISSUE TITLE
Nginx cases the same content in router page reloading

### ISSUE THREAD

**Issue by SecMao** [vuejs/vue-router#2205]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/8e1ghfme/2/](https://jsfiddle.net/8e1ghfme/2/)

### Steps to reproduce
I have a project in which pages are split to left/middle/right parts. The left and right parts in different routers display different Component. But the middle part keeps unchanged. When I played in my own project, switch the routers, everything goes well. Then I published the project to Production Environment, where we use nginx to redirect request. The problem occurs. When I change route 1 to route 2, the middle part reload too. 

my router config:
new Router({
  mode: 'history',
  routes: [
    {
      path:  '/index',
      components: {
        Left: Left,
        Middle: Middle,
        Right: Right
      }
    },
    {
      path: '/working',
      components: {
        Left: workingLeft,
        Middle: Middle,
        Right: workingRight
      }
    },
    {
      path: '/powermode',
      components: {
        Left: workingLeft,
        Middle: Middle,
        Right: powerRight
      }
    }
  ]
})

### What is expected?
same component in different routers do not reload

### What is actually happening?
same component in different routers do reload

**Comment by posva** [comment]
Please use the forum or discord to ask questions

**Comment by SecMao** [comment]
Fixed this problem by move the unchanged parts before any changing nodes in dom.
