### ISSUE TITLE
Error: Can't resolve 'vue-router'

### ISSUE THREAD

**Issue by davincif** [vuejs/vue-router#2211]
### Version
"vue": "^2.5.11",
"vue-route": "^1.5.1"

### Reproduction link
https://pastebin.com/5nk5U3Fd

### Steps to reproduce
npm install vue-route --save
add the line:
    import VueRouter from 'vue-router';
to the main.js file
npm run dev

### What is expected?
run

### What is actually happening?
crashing

---
error msg:

Failed to compile.

./src/main.js
Module not found: Error: Can't resolve 'vue-router' in '/home/davincif/Documents/projects/pessoal/davincif.com/src'
 @ ./src/main.js 2:0-35
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

**Comment by davincif** [comment]
I had a pretty hard time trying to uninstall this version, 'cause I noticed that that npmjs.org version is the 3.0.1. I don't know why, when I gave ```npm install vue-router``` it installed this outdated version.
In the end I removed the node_module folder, changed the version in package manually and installed again.
It worked =)

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by davincif** [comment]
@posva, I know, sorry. At first I really thought it was a bug, just then I realised the version problem. =/

**Comment by rambhaprasad** [comment]
npm install vue-route --save should have been npm install vue-route**r** --save
