### ISSUE TITLE
[Docs] Broken link on Vue Router homepage

### ISSUE THREAD

**Issue by tristancalderbank** [vuejs/vue-router#2213]
### Version
3.0.1

### Reproduction link
[https://router.vuejs.org/](https://router.vuejs.org/)

### Steps to reproduce
Click the link that says "Get started". This link is pointing to https://router.vuejs.org/essentials/getting-started.html, but page does not exist.

### What is expected?
Should instead be a link to https://router.vuejs.org/guide/

### What is actually happening?
404 Not Found

**Comment by posva** [comment]
Please, send a pr instead of opening an issue for broken links, it's much easier :)

**Comment by tristancalderbank** [comment]
Hi, I'm trying to fix it but I get the same issue as this one from the vuex repo when trying to build the docs:

https://github.com/vuejs/vuex/issues/1275

Should I open an issue for that here?
