### ISSUE TITLE
[Docs]: All links to docs from google search results return 404

### ISSUE THREAD

**Issue by breadadams** [vuejs/vue-router#2214]
### Version
3.0.1

### Reproduction link
http://lmgtfy.com/?q=vue-router+how+to+safeguard

### Steps to reproduce
Visit a link directly to the `router.vuejs.org` docs via Google search results.

**Or**, visit the link that the result is actually linking to directly 😅 https://router.vuejs.org/en/advanced/navigation-guards.html

### What is expected?
Should load the docs page like usual, ie. https://router.vuejs.org/guide/advanced/navigation-guards.html

### What is actually happening?
Being taken to `https://router.vuejs.org/guide/advanced/*/` and seeing a 404

![image](https://user-images.githubusercontent.com/5795227/40509087-55113eb4-5f99-11e8-83b1-99edf0c66452.png)

**Comment by yyz1989** [comment]
anyone got an idea?

**Comment by posva** [comment]
it's pretty much the same documentation, the only breaking change was in typescript. It's something I will try to fix for most scenarios
