### ISSUE TITLE
Decoding a url with &amp; fails

### ISSUE THREAD

**Issue by NathanHolsombeck** [vuejs/vue-router#2216]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/oa2muvbo/2/](https://jsfiddle.net/oa2muvbo/2/)

### Steps to reproduce
This is not reproducible with jsfiddle... I can't really pass query params and it doesn't reproduce when hardcoded as a vuew-router link.
The url http://site.com?a=b&amp;c=d is not properly decoded using the vue router. This only reproduces when coming from outside the application, links from inside the SPA don't have this issue.

The bug is here: vue-router/src/util/query.js Line 46
The url should be decoded before splitting it by '&'.

### What is expected?
The url http://site.com?a=b&amp;c=d should be processed by the vue router and the query params extracted. For instance:
a=b
c=d

### What is actually happening?
Result is:
a=b
amp;c=d

**Comment by posva** [comment]
You need to encode the & (vue router does it for you with links). It's not `&amp`, you should be able to get the good value with encodeuricomponent. After all & has a special meaning in urls

**Comment by fsanano** [comment]
Hi, I had a similar problem when try confirming an invite by a user from email link.
Laravel generates a link in the form:
```
<a href="{{ url('/invite?confirm_hash='. $user-> confirm_hash. '& invite_hash ='. $ userTenant-> invite_hash)}} "> Push here to JOIN !! </a>
```
But in html letter `&` automatically converted to `&amp;`
And I had to get `confirm_hash` and `invite_hash` like
```
const { confirm_hash } = this.$route.query;
const invite_hash = this.$route.query['amp;invite_hash'];
// Instead of
const { confirm_hash, invite_hash } = this.$route.query;
```
I think I not alone with this problem. 
And fixing query decoding url will be great.

**Comment by ssglopes** [comment]
Hi, just run into similar issue between laravel API where email generated with markdown causes ampersands in urls and the useRoute() can't read it correctly. eg an url like:
`?action=password-reset&amp;id=155&amp;expires=1700270466&amp;signature=02f01465a31`
using useRoute() outputs:
```
action
amp;id
amp;expires
amp;signature
```
variables whereas it should be:
```
action
id
expires
signature
```
Fixed it using the below instead:

``` 
const queryString = window.location.search.replaceAll('&amp;', '&')
const urlParams = new URLSearchParams(queryString)
const action = urlParams.get('action') ?? ''
const id = urlParams.get('id') ?? ''
const expires = urlParams.get('expires') ?? ''
const signature = urlParams.get('signature') ?? ''
```
Maybe of use for someone else running into same problem.
