### ISSUE TITLE
[Docs] Changed to Vuepress?

### ISSUE THREAD

**Issue by brunokunace** [vuejs/vue-router#2220]
### Version
3.0.1

### Reproduction link
[https://router.vuejs.org/](https://router.vuejs.org/)

### Steps to reproduce
check on mobile or any small screen and click to hamburger menu

### What is expected?
Open menu and results of search bar

### What is actually happening?
link of menu dont work (dont make anything). Same as search input

---
VuePress is awesome, please fix it!!

**Comment by ulivz** [comment]
Duplicate of https://github.com/vuejs/vuepress/issues/492.

**Comment by posva** [comment]
That's a vuepress issue and I think there's already an issue opened
