### ISSUE TITLE
Search on documentation does not show results or direct to results on enter press

### ISSUE THREAD

**Issue by nchudleigh** [vuejs/vue-router#2222]
### Version
3.0.1

### Reproduction link
[https://router.vuejs.org/](https://router.vuejs.org/)

### Steps to reproduce
Type something into the search box on https://router.vuejs.org/

### What is expected?
I am assuming it is intended to have the same behaviour as the core documentation https://vuejs.org/v2/guide/ 

### What is actually happening?
No results popdown is displayed

---
Ran into this bug when trying to search for something in the documentation.  I checked the issues list on  https://github.com/vuejs/vue-router/issues and did not see anything related to the search on the documentation

Noticed this bug in the console, could be related (though I doubt that)
https://imgur.com/a/kybpG3j

**Comment by posva** [comment]
Cannot reproduce, you may have an ad blocker blocking that content
