### ISSUE TITLE
路由跳转后 params 丢失

### ISSUE THREAD

**Issue by jason-chang** [vuejs/vue-router#2223]
### Version
3.0.1

### Reproduction link
[http://icoding.so](http://icoding.so)

### Steps to reproduce

我的路由配置如下

const routes = [{
  path: '/article',
  // name: 'app.article',
  component: require('../views/Article/Article').default,
  children: [
    {
      path: 'tag/:label',
      name: 'app.article.tag',
      component: require('../views/Article/List').default,
    }
]
}];

router-link 如下

          <router-link v-if="item.name" v-for="item in tags" :key="item.id" :to="{name: 'app.article.tag', params: {label: item.name}}">{{ item.name }}</router-link>

tags 数据如下:
[{"id":1,"name":"sed","created_at":"2016-08-08 22:35:39","updated_at":"2016-08-09 02:47:56","deleted_at":null},{"id":2,"name":"linux","created_at":"2016-08-08 22:35:44","updated_at":"2016-08-09 02:47:56","deleted_at":null},{"id":3,"name":"https","created_at":"2016-08-09 00:54:18","updated_at":"2016-08-09 02:47:56","deleted_at":null},{"id":4,"name":"ssl","created_at":"2016-08-09 02:47:56","updated_at":"2016-08-09 02:47:56","deleted_at":null}]

错误的行为是， 点击其他 tag 的链接后 当前链接 url 变成  #/ . router-link 组件上的 to.params 被清空。

### What is expected?
unknow

### What is actually happening?
错误的行为是， 点击其他 tag 的链接后 当前链接 url 变成  #/ . router-link 组件上的 to.params 被清空。

**Comment by posva** [comment]
That is not a valid repro. Also, please, take the time to write in English, I would appreciate that

**Comment by hasbug** [comment]
使用query 这样才会留在url上面，用params刷新下就没了
