### ISSUE TITLE
favicon request on click a tag

### ISSUE THREAD

**Issue by id1385** [vuejs/vue-router#2226]
i have a submenu when i click on menu it not work

**Comment by id1385** [comment]
![image](https://user-images.githubusercontent.com/28746285/40589312-70e810b8-6200-11e8-9b50-14f639c7535d.png)

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
