### ISSUE TITLE
Request to remove routers feature

### ISSUE THREAD

**Issue by ducle1** [vuejs/vue-router#2227]
### What problem does this feature solve?
Hi there, 

When I develop my app, I only found add routers (https://router.vuejs.org/api/#router-addroutes ) but don't found delete or remove routers. I don't see any docs for this. Can you provide any docs for removing routers or support for this?

Best regards,

### What does the proposed API look like?
router.removeRoutes(routes: Array<RouteConfig>)

**Comment by msouidi309** [comment]
Probably what you're excpecting : https://github.com/vuejs/vue-router/issues/1234

**Comment by posva** [comment]
This is indeed in the road map already
