### ISSUE TITLE
digits in route don't properly match in vue-router but match in path-to-regexp

### ISSUE THREAD

**Issue by mkastner** [vuejs/vue-router#2229]
### Version
3.0.1

### Reproduction link
[https://codepen.io/mikekastner/pen/oyvGPB](https://codepen.io/mikekastner/pen/oyvGPB)

### Steps to reproduce
Create Vue
Create Router with one path using this pattern: '/*-\\d{4}-\\d{2}-\\d{2}'

### What is expected?
router pattern  '/*-\\d{4}-\\d{2}-\\d{2}' should match e.g. /test/name-2016-12-04 or /whatever/item/name-2014-03-02

### What is actually happening?
Route does not match pattern.

It seems like the vue path can't handle the curly brackets for quantifying digits. Which is weird because path-to-regexp can.

**Comment by posva** [comment]
That doesn't seem to work with path-to-regexp v1 either

**Comment by mkastner** [comment]
Yes, it does. Please have a look at the attached screenshot.

I've run this against the very path-to-regexp (which is 1.7.0) version which ships with the latest vue-router version 3.0.1.

![screenshot-path-to-regexp](https://user-images.githubusercontent.com/287486/40642790-66633da6-631e-11e8-8491-01e620484cda.png)
