### ISSUE TITLE
Function isObjectEqual (a, b) can return unexpected result if object a has properties with undefined values

### ISSUE THREAD

**Issue by mburmistrov** [vuejs/vue-router#2233]
### Version
3.0.1

### Reproduction link
[https://codepen.io/mburmistrov/pen/vrYWWR?editors=1112](https://codepen.io/mburmistrov/pen/vrYWWR?editors=1112)

### Steps to reproduce
Look at the codepen snippet.

It contains **isObjectEqual(a, b)** implementation from *vue-router/src/util/route.js* and an example of it's unexpected behaviour.

Console output represents the issue.

### What is expected?
In the codepen **isObjectEqual(a, b)** is used on two objects: 

```a: { foo: true, bar: undefined } ```

```b: { foo: true, baz: 'qux' } ```

What is expected: 
1. **isObjectEqual(a, b)** is expected to return false since **Object b** has 'baz' property with 'qux' value and **Object a**  doesn't have such property at all.

2. **isObjectEqual(b, a)** is expected to return false for the same reason.

3. **isObjectEqual(a, b)** result should be equal to **isObjectEqual (b, a)** result.

### What is actually happening?
What is happening:
1. **isObjectEqual(a, b)** returns true (unexpected).

2. **isObjectEqual(b, a)** returns false (expected).  

3. **isObjectEqual(a, b)** result is not equal to **isObjectEqual(b, a)** result  (unexpected).

Same thing will happen with any **Object a** and **Object b** if conditions below are met:

- **Object a** and **Object b** have the same amount of properties.

- **Object b** must have same properties with same values that are present in **Object a** with values different from undefined.

---
Issue with **isObjectEqual** causes issues with other functions that use it.

For example, **isSameRoute(a, b)** (from *vue-router/src/util/route.js*) can return true for routes with different query objects (if query objects meet conditions listed above).  

I ran into this bug because sometimes programmatic navigation worked in unexpected ways when using **router.push** with a query object.

**Comment by posva** [comment]
I cannot find the duplicate right now but there is even a pr for this already 🙂

**Comment by laomu1988** [comment]
this bug still exists

**Comment by laomu1988** [comment]
@posva  this bug still exists

**Comment by Kyseme** [comment]
it is still exists in  version: 3.4.6 @posva

**Comment by posva** [comment]
Can you open a proper issue with boiled down code using vue router api instead of extracting code from it in a codepen like the original issue? I can't tell anymore what's the actual problem
