### ISSUE TITLE
Regexp path yields error: `TypeError: t.replace is not a function`

### ISSUE THREAD

**Issue by nikwen** [vuejs/vue-router#2234]
### Version
3.0.1

### Reproduction link
[https://codepen.io/anon/pen/Qxwvzr](https://codepen.io/anon/pen/Qxwvzr)

### Steps to reproduce
Set the path property of a route to a RegExp.

### What is expected?
According to the [docs](https://router.vuejs.org/guide/essentials/dynamic-matching.html#advanced-matching-patterns), that RegExp should be used for route matching:

> vue-router uses path-to-regexp as its path matching engine, so it supports [...] even custom regex patterns.

### What is actually happening?
A TypeError is thrown: `TypeError: t.replace is not a function`

---
~I need to use a RegExp here because I need to have a single case-sensitive route.~
Wrong: There is the `caseSensitive` option for routes.

**Comment by Jinjiang** [comment]
Also according to the docs, you should follow this document: https://github.com/pillarjs/path-to-regexp#parameters to [customize](https://github.com/pillarjs/path-to-regexp#custom-matching-parameters) your own. For example: `{ path: '/icon-:foo(\\d+).png' }`

**Comment by nikwen** [comment]
`path-to-regexp` supports RegExps being passed to it: https://github.com/pillarjs/path-to-regexp#usage.

Hence, in combination with the quote from the original comment, I figured "custom regex patterns" would allow passing of custom native RegExp objects.

**Comment by posva** [comment]
I'm not convinced by this to be honest. It looks like it brings flexibility but it can make so many other things so much harder.
You can already use regexes for matching parameters which is where you need the most that flexibility

Do you have any usecase not covered by that?

**Comment by nikwen** [comment]
@posva This wasn't meant as a feature request.

In my opinion the documentation quoted above seems to imply that custom RegExp objects work with vue-router. I thought it was a supported feature but saw it not working. That's why I filed the issue.

As stated in the updated issue text, my usecase was better solved using the `caseSensitive` and `pathToRegexpOptions` route options, which I later found in the API reference.

So in my opinion the tutorials should be improved. My suggestions:

* Remove the phrase "custom regex patterns" and point out that even though `path-to-regexp` supports RegExp objects, vue-router route paths do not.
* Futhermore, it would be great to see the `caseSensitive` and `pathToRegexpOptions` route options referenced in the tutorial somewhere.

**Comment by posva** [comment]
Oh, thanks for the suggestions! The example with the regex is actually there: https://github.com/vuejs/vue-router/blob/dev/examples/route-matching/app.js#L20
caseSensitive and pathToRegexOptions are in the API reference (https://router.vuejs.org/api/#routes)
Will see what I can do to make this better

**Comment by nikwen** [comment]
Thanks! :)
