### ISSUE TITLE
Address bar is flashing with $router.replace()

### ISSUE THREAD

**Issue by pmochine** [vuejs/vue-router#2237]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/j43r89wp43](https://codesandbox.io/s/j43r89wp43)

### Steps to reproduce
So if you go to  https://codesandbox.io/s/j43r89wp43 you will see two navigations left and right. I know it's a bit buggy, but it shows my problem. The URL in the address bar is flashing all the time after going through right steps. I don't know why. It's super weird.

If you don't see it I could give you a slow mo video

### What is expected?
No flashing

### What is actually happening?
it flashes

**Comment by posva** [comment]
That repro is too big. If you boil it down to the minimal I can take a look. Otherwise I recommend you to ask in the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) 🙂
