### ISSUE TITLE
Unclear documentation regarding keep-alive

### ISSUE THREAD

**Issue by robcresswell** [vuejs/vue-router#2238]
### Version
3.0.1

### Reproduction link
[https://router.vuejs.org/api/#router-view](https://router.vuejs.org/api/#router-view)

### Steps to reproduce
Go to https://router.vuejs.org/api/#router-view

### What is expected?
In https://router.vuejs.org/api/#router-view the following is written: 

"Since it's just a component, it works with `<transition>` and `<keep-alive>`. When using the both together, make sure to use `<keep-alive>` inside:"

It's not clear to me "why" I need to use it like this. Is it to stop the router-view component being destroyed following a transition? I think this documentation item could be elaborated on.

### What is actually happening?
n/a

**Comment by robcresswell** [comment]
Sorry for the duplication, but the draconian external issue site wouldn't let me proceed otherwise.

**Comment by posva** [comment]
Because it is made to work that way 😄 
if you put the keep-alive around the transition, it will try to keep alive the transition (which doesn't make sense since the transition is an abstract component as well as keep-alive). See https://vuejs.org/v2/api/#keep-alive

**Comment by robcresswell** [comment]
Ah derp. I read it as meaning that I was required to use keep-alive if I used transition. I got it now.
