### ISSUE TITLE
$route doesn't contain anything on first load in "history" mode on any other path than "/"

### ISSUE THREAD

**Issue by darkylmnx** [vuejs/vue-router#2239]
### Version
3.0.1

### Reproduction link
[https://github.com/darkylmnx/Layout-system-with-vue-and-vue-router](https://github.com/darkylmnx/Layout-system-with-vue-and-vue-router)

### Steps to reproduce
- clone the repo
- cd into it & yarn
- yarn serve
- go to the path "/about-us" or any other route path except the root "/"
- reload the page and check the console

### What is expected?
- I'm expecting to see only one log, the current $route with it's informations

### What is actually happening?
- I see two logs, in the first log the $route contains only null values and only the second one shows the good informations

---
- This doesn't seem to happen on the root path "/"
- This doesn't seem to happen in "hash" mode

**Comment by posva** [comment]
Sorry for the delay! The repro is quite an overkill. I took a look but didn't see what was wrong
