### ISSUE TITLE
Reserved word in closure compiler

### ISSUE THREAD

**Issue by hpmdy** [vuejs/vue-router#224]
Hi, when I try to use closure compiler with SIMPLE_OPTIMIZATIONS option, I have the following errors:
```ShellSession
WARNING - Keywords and reserved words are not allowed as unquoted property names in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option.
          abstract: _historyAbstract2['default'],
          ^

test.js:131: WARNING - Keywords and reserved words are not allowed as unquoted property names in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option.
            var _ref$abstract = _ref.abstract;
                                     ^

test.js:132: ERROR - Parse error. identifier is a reserved word
            var abstract = _ref$abstract === undefined ? false : _ref$abstract;
                ^

test.js:181: ERROR - Parse error. identifier is a reserved word
            this._abstract = abstract;
                             ^

```

For the errors, I just need to replace the "abstract" var and it's ok.

**Comment by amirrustam** [comment]
@hpmdy were you able to resolve the problem?

**Comment by hpmdy** [comment]
@amirrustam No, except by replacing words during the process.

**Comment by amirrustam** [comment]
@hpmdy I think it's best to post your question in the community forums to get a fresh set of eyes on it: http://forum.vuejs.org. If it is concluded within the forums that this is an issue then come back here an open it, but close out this issue for now.

**Comment by hpmdy** [comment]
Ok, for more information: http://forum.vuejs.org/topic/1356/reserved-word-in-closure-compiler/2
