### ISSUE TITLE
External Website and vuejs application URL deletes parameters on load or refresh

### ISSUE THREAD

**Issue by kennCK** [vuejs/vue-router#2240]
I'm using vuejs and vue-router.  I would like to ask why the url parameters deleted during loading or refreshing the page. For example, I have this url http://localhost:8080/#/a/value1/value2 when the page loaded the url will become http://localhost:8080/#/a and deleted the value1 and value2.

Here's my router code.
    path: '/a/:value1/:value2',
    name: 'a',
    component: resolve => require(['modules/home/A.vue'], resolve),
    meta: {
      tokenRequired: false
    }

I want to send verification code to user's email address and get that code using the link
<a href=http://localhost:8080/#/a/value1/value2></a>

Any Idea? Thanks head.

**Comment by Kishanjvaghela** [comment]
I have same issue. Any help?
my url is like this 

https://example.com/verify-email?userid=52&type=2&token=0bb3ad256a50f01fec25f63c218ead0aeadc84c3898733fdf285d69856fa270f

When on load its becomes like this
https://example.com/verify-email/
