### ISSUE TITLE
Redirect old links in docs to new ones in VuePress

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue-router#2241]
Since a lot of courses, books, blog posts, etc still link to pages in the non-VuePress docs I'm thinking some redirects should be set up. Unfortunately, I don't have a complete list of links, but [here's one](https://github.com/vuejs/vuejs.org/issues/1656).

**Comment by posva** [comment]
Yeah, same as https://github.com/vuejs/vue-router/issues/2214
I wanted to make the redirect but saw Evan added it then removed it, so waiting for an answer 😓
