### ISSUE TITLE
Router doesn't render link properly if hash tag is defined

### ISSUE THREAD

**Issue by EugeneHerasymchuk** [vuejs/vue-router#2244]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/5njn5pry4](https://codesandbox.io/s/5njn5pry4)

### Steps to reproduce
There are some cases where I have to render `a` or `router-link` based on some condition. So both `to` and `href` tags want to be applied. In this case, router link doesn't render the link properly. 
Hover mouse over the link and see where you'll be directed.       
`<a href="[object Object]" class="">Link</a>`

### What is expected?
Expected to render A tag properly with the link formed from `to` tag.   This can be achieved by removing `href` tag from `router-link`.     
`<a href="/link/3450" class="">Link</a>`

### What is actually happening?
It renders the `[object Object]` in the place of `href`.

**Comment by rdunk** [comment]
Why don't you just conditionally render an `a` or `router-link`?

If you absolutely have to avoid conditional rendering, then create a component that accepts a `to` prop and renders an `a` tag. Something like: https://codesandbox.io/s/k26125nm67

**Comment by EugeneHerasymchuk** [comment]
Sure, I've fixed in another way. I don't want to have this huge conditional tags, instead, I do it like this:
```
<component
      :is="componentTypeByRoute"
      :to="componentTypeByRoute === 'router-link' ? item.route : undefined" /*it will be rendered if we'll have `routerLink` */ 
      :href="componentTypeByRoute === 'router-link' ? undefined : item.route " /* it will be rendered if we'll have `a` */
    >
```
But, I thought that this case should handled by vue-router, so just to point out.
I'd like to create PR for it in the future.

**Comment by posva** [comment]
You should not set an href attribute on a router link because it may override the one added by the prop to
