### ISSUE TITLE
The page does not display correctly after changing the path

### ISSUE THREAD

**Issue by mangoooooo** [vuejs/vue-router#2245]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/9jr1zry2k4](https://codesandbox.io/s/9jr1zry2k4)

### Steps to reproduce
1. click "to desinger home" then return, and then click "to designer detail"

2. The detail page shows the content of the home page

3. then refresh the detail page, it shows the correct content

![](https://ws1.sinaimg.cn/large/005wMh0ngy1fs1t21tbykg308l0fa4qp.gif)

### What is expected?
 shows the correct content

### What is actually happening?
 shows the wrong content

---
Please forgive me for my poor English

**Comment by posva** [comment]
Put the  star route (*) at the end otherwise it will pick-up every single route

**Comment by mangoooooo** [comment]
@posva  
I have removed the code
`
 {
      path: "*", 
       redirect: "/mall"
     }
`
But there is still a problem

link: [https://codesandbox.io/s/9jr1zry2k4](https://codesandbox.io/s/9jr1zry2k4)

**Comment by z1948296027** [comment]
in my problem, route path changed,but the page did not change

**Comment by Virgil-N** [comment]
I have the same problem. I use history mode. Url is right, but component is not mounted, so my page contains nothing.

**Comment by Virgil-N** [comment]
我找到解决办法了，给嵌套组件添加一个只包含router-view的空父组件，哈哈！

**Comment by mangoooooo** [comment]
更新到最新就没有这个问题了 [#2930](https://github.com/vuejs/vue-router/pull/2930)
