### ISSUE TITLE
`this.router.go(-1)` doesn't work only on Chrome 67

### ISSUE THREAD

**Issue by wpsumsun** [vuejs/vue-router#2246]
### Version
2.6.0

### Reproduction link
[http://jsbin.com/?html,css,js,output;I don't know how to show this question in  editor such as JSBin,  you can try it on you page.](http://jsbin.com/?html,css,js,output;I don't know how to show this question in  editor such as JSBin,  you can try it on you page.)

### Steps to reproduce
use `this.router.go(-1)`   return to previous page

### What is expected?
return to previous page

### What is actually happening?
nothing, it doesn't work. horever, it worked  well on Chrome 66.

**Comment by posva** [comment]
It's probably a regression in chrome then. Make sure it's not a html history issue

**Comment by RicoLiu** [comment]
@wpsumsun Hi, I had met the same issue.

How to fix it? Do U have any idea?
