### ISSUE TITLE
console show error:Uncaught (in promise) Error: [vue-router] TypeError: Cannot read property 'app' of undefined

### ISSUE THREAD

**Issue by libp** [vuejs/vue-router#2249]
### Version
3.0.1

### Reproduction link
[https://github.com/libp/littleweb](https://github.com/libp/littleweb)

### Steps to reproduce
first click is true.when i click subroute to return main route  ,i have the error.
but the error  not make my web bad.
just console has error
the web show is ok

### What is expected?
console not show error

### What is actually happening?
console show error:Uncaught (in promise) Error: [vue-router] TypeError: Cannot read property 'app' of undefined

**Comment by libp** [comment]
selfask  selfanswer，when i delete this code in  route index.js，everything is OK：
`return new Promise(resolve => {
      // check if any matched route config has meta that requires scrolling to top
      if (to.matched.some(m => m.meta.scrollToTop)) {
        // coords will be used if no selector is provided,
        // or if the selector didn't match any element.
        position.x = 0
        position.y = 0
      }

      // wait for the out transition to complete (if necessary)
      this.app.$root.$once('triggerScroll', () => {
        // if the resolved position is falsy or an empty object,
        // will retain current scroll position.
        resolve(position)
      })
    })`

**Comment by nicooprat** [comment]
Just had to check if `savedPosition` is not null. The error was triggered on first load, so it was not set yet. Here's my code ([inspired by this example](https://github.com/vuejs/vue-router/blob/dev/examples/scroll-behavior/app.js)):

```js
scrollBehavior(to, from, savedPosition) {
  // On prev/next browser button
  if (savedPosition && to.name !== from.name) {
    // Wait for AJAX loaded content
    return new Promise(resolve => {
      // Listen to this.$root.$emit('triggerScroll')
      this.app.$root.$once('restoreSavedScroll', () => {
        // Wait for content appended to DOM
        this.app.$root.$nextTick(() => resolve(savedPosition))
      })
    })
  }
}
```
