### ISSUE TITLE
The website https://router.vuejs.org does not work

### ISSUE THREAD

**Issue by aitchnyu** [vuejs/vue-router#2260]
### Version
2.5.1

### Reproduction link
[https://ibb.co/jDXPed](https://ibb.co/jDXPed)

### Steps to reproduce
Not really sure. I use Firefox 60 in Ubuntu 17.10

### What is expected?
The website should download its assets and display a website with design

### What is actually happening?
The website assets all 404 and a barebones site shows up

**Comment by posva** [comment]
You may have a cache issue, the site looks fine on my end

**Comment by aitchnyu** [comment]
I tried Ctrl+F5 and then F5. The second load onwards fails consistently for Firefox on Ubuntu. In the second case the page is transferred from a service worker and the wrong assets are downloaded. I deleted the service worker for the domain and fresh and cached requests work fine. 

I hope this is a rare issue or non-programmers and all kinds of IT staff must learn more things than clearing cache.

I included the requests from "network" tab before I removed the service worker:

Fresh load:
```
https://router.vuejs.org/guide/advanced/navigation-guards.html
https://router.vuejs.org/assets/css/91.styles.2148f177.css
https://router.vuejs.org/assets/js/84.f2f54886.js
https://router.vuejs.org/assets/js/app.b73d8279.js
https://router.vuejs.org/assets/img/search.83621669.svg
```

Cached load:
```
https://router.vuejs.org/guide/advanced/navigation-guards.html
https://router.vuejs.org/assets/css/72.styles.8235416c.css
https://router.vuejs.org/assets/js/65.d4e5ad5e.js
https://router.vuejs.org/assets/js/app.137b6b9c.js
```

**Comment by saleem-git** [comment]
The issue has occurs again, I had to go into Firefox Storage tab and delete the cache as both Ctrl+F5 and then F5 failed to work. This happens only on Firefox and only with https://router.vuejs.org/

**Comment by abrekhov** [comment]
issue is still occurs!
