### ISSUE TITLE
Replace boolean params with string placeholders

### ISSUE THREAD

**Issue by plehnen** [vuejs/vue-router#2261]
### What problem does this feature solve?
Imagine a route path like this: 
`{ path: '/thanks/:polite/:foo?', component: Thanks } `
...with one or more boolean parameters.

The URL would look like this `/thanks/true/true`

it would be nice to be able to substitute the "true" state by a string-placeholder, so the URL would look like this:
`/thanks/polite/foo` or `/thanks/polite` (or even `/thanks/foo/` if "polite" is false)

### What does the proposed API look like?
Syntax could be:
`{ path: '/thanks/:!polite/:!foo?', component: Thanks } `
... if a parameter name starts with "`!`" it is considered to be a boolean value, and its name will be the substitution of the true value or it will be left out if false.

**Comment by posva** [comment]
keep in mind there is no booleans in urls because they're strings.
If you want both parameter to be optional, you can use the `?` on the first parameter. Keep in mind we use path-to-regexp v1 to convert paths to regexes

**Comment by plehnen** [comment]
@posva But how is it possible to use such flags in an URL in a more human-readable way?
Instead of `/path/true/true/false` I want the URL to be `/path/foo/bar/baz` and accessible via `this.$route.params.foo` (as a boolean)
I think this would be very handy. And a useful feature.

**Comment by plehnen** [comment]
It is even worse.
After reading your comment again I was wondering if you really understood the intention of the feature request, because you only replied to the "optionals", but what I want has nothing to do with optional parameters. I just added one optional parameter to the example for the sake of completeness.
But actually optional parameters can be ignored totally.

Nevertheless I just tried to simply substitute my params to the string representatives:

`this.$router.push({
	name: TARGET,
	params: {
		id: '123',
		inProgress: response.data.inProgress ? 'inProgress' : null,
		optin: this.optin ? 'optin' : null,
	},
});`

which matches the following route:
`{
	path: '/target/:id/confirmation/:inProgress?/:optin?',
	name: types.TARGET,
	component: () => import('@/pages/Target'),
},`

Now the URL looks as desired. But if optin is **true**, and inProgress is false, the URL is:
`/target/123/optin`
... as I wanted it to be, but on the target page the values are mixed:

`!!this.$route.params.inProgress is` true, and `!!this.$route.params.optin` is **false**.

**Comment by posva** [comment]
Think about route params as function arguments in js, if one is optional, then all remaining arguments must also be optional. If you want to skip one of those, you will have to do some manual checks. The difference with route params is that they're strings, so you cannot rely on type checking.
Maybe a more appropriate feature for your boolean flags is the _query_ 🙂
