### ISSUE TITLE
Facebook/Instagram like main route

### ISSUE THREAD

**Issue by dawidcyron** [vuejs/vue-router#2263]
### What problem does this feature solve?
Right now, when you want to create Facebook like login system, where both login page and timeline are on the same route, it's really hard or impossible. I think it should be easier to do, as it's a really important feature for many developers.

### What does the proposed API look like?
To be honest, I have no idea. But to make it simple, it should be available as a simple option in vue router

**Comment by posva** [comment]
I'm not sure to get what you're trying to do but based on the login state you can display different components (which turn out to be view components) inside of the view displayed by the _timeline_ route
