### ISSUE TITLE
Problem with beforeRouteUpdate in-Component Guard Test

### ISSUE THREAD

**Issue by BerniWittmann** [vuejs/vue-router#2264]
### Version
3.0.1

### Reproduction link
[https://github.com/BerniWittmann/vue-test-navigation-guard-reproduction](https://github.com/BerniWittmann/vue-test-navigation-guard-reproduction)

### Steps to reproduce
Run the tests with `npm run test:unit`

### What is expected?
The specs in `tests/unit/Home.spec.js` should pass and calling `wrapper.vm.beforeRouteUpdate` should call the component navigation guard `beforeRouteUpdate`

### What is actually happening?
The specs fail, because  `wrapper.vm.beforeRouteUpdate` yiels undefined

---
I already asked a question on [stackoverflow](https://stackoverflow.com/questions/50913421/testing-vue-router-in-component-navigation-guard) (without any solution). After providing the minimal reproduction this appears to be a bug, that only happens with `mocha   chai` (and maybe `karma   jasmine`) , but not with `jest`

**Comment by posva** [comment]
I don't know what may be causing this but I would say it's not on Vue router's side.
If you want to acces the `beforeRouteUpdate` hook, you will need to go through `vm.$options.beforeRouteUpdate`
