### ISSUE TITLE
Useing Lazy Loading when subroute path is empty, match parent route is blocked

### ISSUE THREAD

**Issue by zaoyu63** [vuejs/vue-router#2266]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/50wL7mdz/405076/](https://jsfiddle.net/50wL7mdz/405076/)

### Steps to reproduce
{
path: ‘/’,
component: require(’./components/index.vue’),
children: [
{
path: ‘’,
component: resolve => require([’./components/dashboard.vue’], resolve),
children: []
}
}
use this.$router.push(’/’),  'index.vue' is render until to 'dashboard.vue' is loaded;

### What is expected?
use this.$router.push(’/’),  'index.vue' is render, next  'dashboard.vue' is loading

### What is actually happening?
use this.$router.push(’/’),  'index.vue' is render until to 'dashboard.vue' is loaded;

**Comment by posva** [comment]
This is expected behaviour.
Lazy loading a child route individually would require you to first display the parent view, then the child view. Ideally, this could be done automatically with an option but the current api makes it a bit complicated. I'll come up with something 🤔 

```js
const delay = time => new Promise(r => setTimeout(r, time))

const Home = { template: '<div>Home <router-view/></div>' }
const Foo = () => new Promise(resolve => delay(1000).then(() => resolve({ template: '<div>Foo</div>' })))


const router = new VueRouter({
  mode: 'history',
  routes: [
    { path: '/', name: 'home', component: Home, children: [
    { path: '', component: Foo }
    
    ] },
  ]
})

new Vue({
	router,
  el: '#app'
})

// first navigate to parent
router.push({ name: 'home' })
// then navigate to actual route
/* router.push('/') */
```
