### ISSUE TITLE
Add scrolling transition effect to scrollBehavior

### ISSUE THREAD

**Issue by preese13** [vuejs/vue-router#2270]
### What problem does this feature solve?
My team are currently building a vue based progressive web app.  As such, we have put much effort into creating a user environment that most imitates that of a native app.  Every aspect of the application has been designed to allow for transitions/transforms to make the user experience as smooth as possible.  The only action in our entire application that does not have such effects is our scroll to effect.  As it is the only transition-free state change, it often is jarring to users when it occurs.  Adding a simple scroll effect to the scroll behavior would go a long way to making the user experience for many Vue applications more seamless.

### What does the proposed API look like?
Honestly I have no idea what this would look like as I have only just begun looking into your docs today.  I am a firm believer in keeping the Vue api surface small and straightforward, so I don't think it's a big enough feature to necessitate adding if it is too clunky.  Its just something I wanted to put in front of you, as it could be an easy way to enhance the user experience for users of Vue applications across the globe

**Comment by posva** [comment]
Unfortunately this is beyond router scope. You can however use any scrolling library to trigger the transition. I recall egoist did this in docute. You should check its source code 🙂
