### ISSUE TITLE
History Mode Still Responds to #

### ISSUE THREAD

**Issue by sam-araiza** [vuejs/vue-router#2271]
### What problem does this feature solve?
Currently, using 'history' mode relieves the app of being routed via an anchor tag. Great! However, when an anchor tag is appended to trigger an app behavior (e.g. www.my-vue-spa.com/playlist-1234#fullview), the router pushes this as part of the history so that the back-button undoes the anchor state instead of returning to the previous page.

### What does the proposed API look like?
The proposed solution would be to enforce what the current documentation currently suggests: to not let anchor tags drive routing history. The descriptions for 'hash' mode is "uses the URL hash for routing" and since history mode is not hash mode, the anchor tag would not affect $router.hash.

**Comment by posva** [comment]
Use `replace` if you don't want to save a history entry
