### ISSUE TITLE
route.params are not always strings

### ISSUE THREAD

**Issue by doppelreim** [vuejs/vue-router#2272]
### Version
3.0.1

### Reproduction link
[https://github.com/doppelreim/vue-test-app/tree/test-route-params-type](https://github.com/doppelreim/vue-test-app/tree/test-route-params-type)

### Steps to reproduce
- `$ npm run serve`
- Open the app in a browser, open the dev-tools
- Click the "About"-link (links to /about/3)
- Click the "Take 5"-link (links to /about/5)
- Observe the console output

### What is expected?
```
oldRoute 3 string
newRoute 5 string
```

### What is actually happening?
```
oldRoute 3 number
newRoute 5 string
```

The type of the id-param in the oldRoute is number, instead of string.

---
The signature according to (VSCode) is:
```
(property) Route.params: {
    [key: string]: string;
}
```

The link from the main-page to the about-page is:
```
<router-link :to="{ name: 'about', params: { id: 3 }}">About</router-link>
```
If I pass the `3` not as a number, but as a string instead, then the issue does not occur:
```
<router-link :to="{ name: 'about', params: { id: '3' }}">About</router-link>
```

If I do not use the link, but instead use a deep-link to the about-page, then the issue does not occur.

**Comment by posva** [comment]
Thanks for you concern! This is something we are aware and we have already planned on improving by probably casting or warning the user to force them to use strings as URLs are always strings

**Comment by doppelreim** [comment]
Ok, cool :)

Where can I track the progress? Is there another issue?

**Comment by posva** [comment]
It's on the board (which I'm not sure if it's public). I cannot find the issue right now, but it's clearly on my list of vue router todos, so don't worry 😆
