### ISSUE TITLE
router-link props to add meta object but not extend

### ISSUE THREAD

**Issue by leixu2txtek** [vuejs/vue-router#2274]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/leixu2txtek/kn3f9dsq/31/](https://jsfiddle.net/leixu2txtek/kn3f9dsq/31/)

### Steps to reproduce
open link above , click  tag **foo**

### What is expected?
```javascript
{ title: 'hi', keep: false }     // define in the router-link
```

### What is actually happening?
```javascript
{ "title": "bar" }     // define in the route 
```

**Comment by JounQin** [comment]
`meta` is not available in `to` prop, it can only be used in route definition.

https://router.vuejs.org/api/#to
https://github.com/vuejs/vue-router/blob/dev/types/router.d.ts#L106-L114
