### ISSUE TITLE
生产模式下 在一个 js模块引入 router实例  router.currentRoute 的path 为根路径 而不是当前路径

### ISSUE THREAD

**Issue by qinouz** [vuejs/vue-router#2275]
### Version
3.0.1

### What is expected?
生产环境下 在 ajax 拦截器 console.log  router  实例 从控制台上看 currentRoute 属性的 path 为当前路由
但是 console.log (router.currentRoute)  的路径为 根路径

**Comment by posva** [comment]
Please make sure to follow guidelines before opening issues

**Comment by qqqiangqiang** [comment]
请问解决了吗，也遇到了这个问题..
