### ISSUE TITLE
Vue-router doesn't detect hash changes without leading slash

### ISSUE THREAD

**Issue by T0RAT0RA** [vuejs/vue-router#2276]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/50wL7mdz/445050/](https://jsfiddle.net/50wL7mdz/445050/)

### Steps to reproduce
* In chrome, open the inspector
* Click the link /route3  
 In the console you see:  
    `ROUTE CHANGED / to /route3`  
    `HASH CHANGED`
* Click the link /route4  
 In the console you see:  
    `HASH CHANGED`

### What is expected?
When clicking *route4* you should see in the console:  
`ROUTE CHANGED / to /route4`  
`HASH CHANGED`

### What is actually happening?
Vue-router doesn't see the hashchange for links without leading slash (#/...)

**Comment by posva** [comment]
This is normal, if you don't have that leading slash you are actually setting the hash part of the url
