### ISSUE TITLE
router.addRoutes not updating routes list

### ISSUE THREAD

**Issue by hfsaito** [vuejs/vue-router#2280]
### Version
3.0.1

### Reproduction link
[https://codepen.io/anon/pen/gKNYwO?editors=1010](https://codepen.io/anon/pen/gKNYwO?editors=1010)

### Steps to reproduce
import AnyComponent from './Somewhere';

const router = new VueRouter({ 
  routes: [], 
  mode: 'history'
});

new Vue({ router });

router.addRoutes([{ path:'/example', name: 'example', component: AnyComponent }]);

### What is expected?
console.log(router.options.routes); // [{ path:'/example', name: 'example', component: AnyComponent }]

### What is actually happening?
console.log(router.options.routes); // []

---
Shouldn't update router.options.routes when using router.addRoutes?

**Comment by posva** [comment]
The options object contain the original one. It never changes. Having somewhere the updated routes is under consideration. For the moment you can add them to an array and keep track of it there

**Comment by phil294** [comment]
What is the reason for this design decision? It seems strange to me that when you simply want to iterate over all existing routes, you will have to build a custom array to keep track of

**Comment by FranckFreiburger** [comment]
Since having somewhere the updated routes is under consideration, is there another issue to track this
feature ?

**Comment by posva** [comment]
Not yet because the API won't be modifying options, so something a bit different must be created like `router.getRouteRecords` but it's more likely to come in a form of RFC with dynamic routing as well

**Comment by shiguoqing** [comment]
> 
> ### Version
> 
> 3.0.1
> ### Reproduction link
> 
> https://codepen.io/anon/pen/gKNYwO?editors=1010
> ### Steps to reproduce
> 
> import AnyComponent from './Somewhere';
> 
> const router = new VueRouter({
> routes: [],
> mode: 'history'
> });
> 
> new Vue({ router });
> 
> router.addRoutes([{ path:'/example', name: 'example', component: AnyComponent }]);
> ### What is expected?
> 
> console.log(router.options.routes); // [{ path:'/example', name: 'example', component: AnyComponent }]
> ### What is actually happening?
> 
> console.log(router.options.routes); // []
> 
> Shouldn't update router.options.routes when using router.addRoutes?



I had the same problem.

**Comment by mnts26** [comment]
Is there any solution ?

**Comment by hfsaito** [comment]
@mnts26 
You have to create your own route list with those new routes

**Comment by matrunchyk** [comment]
As a workaround, you can try this code (TypeScript)

```
import Vue from 'vue';
import VueRouter, { RouteConfig } from 'vue-router';

class VueRouterEx extends VueRouter {
  matcher: any;

  public routes: RouteConfig[] = [];

  constructor(options) {
    super(options);
    const { addRoutes } = this.matcher;
    const { routes } = options;

    this.routes = routes;

    this.matcher.addRoutes = (newRoutes) => {
      this.routes.push(...newRoutes);
      addRoutes(newRoutes);
    };
  }
}

Vue.use(VueRouterEx);

const router = new VueRouterEx({
  mode: 'history',
  base: process.env.BASE_URL,
  routes: [],
});

export default router;
```

**Comment by gabrielmendes98** [comment]
> As a workaround, you can try this code (TypeScript)
> 
> ```
> import Vue from 'vue';
> import VueRouter, { RouteConfig } from 'vue-router';
> 
> class VueRouterEx extends VueRouter {
>   matcher: any;
> 
>   public routes: RouteConfig[] = [];
> 
>   constructor(options) {
>     super(options);
>     const { addRoutes } = this.matcher;
>     const { routes } = options;
> 
>     this.routes = routes;
> 
>     this.matcher.addRoutes = (newRoutes) => {
>       this.routes.push(...newRoutes);
>       addRoutes(newRoutes);
>     };
>   }
> }
> 
> Vue.use(VueRouterEx);
> 
> const router = new VueRouterEx({
>   mode: 'history',
>   base: process.env.BASE_URL,
>   routes: [],
> });
> 
> export default router;
> ```

this worked for me, thanks a lot!!!

**Comment by manandre** [comment]
@matrunchyk Thanks for this workaround.
Is there a way to enable `@watch("$routes")` in a Vue component (typically a navigation menu) as we can already do with `$route` (typically in a breadcrumb) ?

**Comment by matrunchyk** [comment]
The first idea came into my mind is using an event bus:
@manandre try this:
```
import eventBus from './eventBus';

class VueRouterEx extends VueRouter {
  matcher: any;

  public routes: RouteConfig[] = [];

  constructor(options) {
    super(options);
    const { addRoutes } = this.matcher;
    const { routes } = options;

    this.routes = routes;

    this.matcher.addRoutes = (newRoutes) => {
      this.routes.push(...newRoutes);
      addRoutes(newRoutes);
      eventBus.$emit('add-routes', newRoutes);
    };
  }
}
```

And in your NavBar/BreadCrumb components:
```
import eventBus from './eventBus';

// ...
created() {
  eventBus.$on('add-routes', (routes) => {
     this.routes = routes;
  });
}
//...
```
