### ISSUE TITLE
vue-router 3.0.1单页面跳转，在某些手机快速切换路由的情况下，会出现获取不到url参数的bug 

### ISSUE THREAD

**Issue by fly2017313** [vuejs/vue-router#2282]
### Version
3.0.1

### Reproduction link
[https://testapi-c.wifi.com/d/changsha](https://testapi-c.wifi.com/d/changsha)

### Steps to reproduce
我们使用的是编程式导航this.$router.push

我们尝试2种获取参数都有失败的可能
1、原生直接获取location.href
2、用vue提供的方式获取 ，例如：this.$route.params.recruitId
都出现了获取不到参数的问题。
我们不得不改成多页面跳转。

### What is expected?
在单页面跳转时，进入组件内部，都应该立即获取到url参数

### What is actually happening?
在某些手机上快速切换路由

---
根据我们报警信息抓取出用户的userAgent如下：

Mozilla/5.0 (Linux; Android 5.1.1; OPPO A33 Build/LMY47V; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/42.0.2311.138 Mobile Safari/537.36 wkbrowser 4.2.91 
Mozilla/5.0 (Linux; Android 6.0; M5 Note Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.146 Mobile Safari/537.36 wkbrowser 4.2.56 
Mozilla/5.0 (Linux; Android 5.0.2; vivo Y37A Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/37.0.0.0 Mobile Safari/537.36 wkbrowser 4.2.90 
Mozilla/5.0 (Linux; Android 4.4.4; vivo X5V Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36 wkbrowser 4.2.88

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only and you didn't provide an editable boiled down repro, which is necessary for us to check if there is actually a bug. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by fly2017313** [comment]
很抱歉，虽然我也很想，但是我无法提供完整的bug测试报告，因为这是概率性的，很难复现。目前给的项目地址依旧还有这样的bug存在，我们将在下周一修复掉，强制改成多页面跳转，可是这样就失去了vuejs的一大优势了。
对了，再补充点信息：
我们的路由采用的是history模式；并且在pc上无法重现，虽然我们尝试了n次。

希望对你们有所帮助。
