### ISSUE TITLE
Mute/Turn off <router-view> reactive rendering programatically

### ISSUE THREAD

**Issue by nandin-borjigin** [vuejs/vue-router#2284]
### What problem does this feature solve?
Suppose an app like `Settings` app in iOS.

We navigate in a path like this: 
Settings -> General -> About This Phone

Then we can navigate in a reversed path by clicking 'back' button on the top left corner.

This "happy path" is easy to implement. But as a nature of web app, user may directly visit any "deep route" via a "deep url" and the "back" button loses its power to navigate through the reverse path:

1. User visits `https://app.example.com/settings/general/about`
2. User clicks back
3. App exits 
*Instead, we want the app to navigate to `/settings/general`*

I have managed to automatically inject the `/settings`, `/settings/general` routes when user directly visits `/settings/general/about`. The problem is these two pages and transitions associated to them show up in this process. 

I need the routing life cycles of auto injected routes, i.e. `/settings`, `/settings/general`,  to be complete to make the later `back` operation possible, but a complete routing life cycle causes the corresponding component to be rendered thus the problem occurred.

If I can mute/turn off the `<router-view>`'s rendering before the automatic injection starts and then turn it on later when the injection ends the problem would be hopefully solved.

### What does the proposed API look like?
```
router.mute()
router.unmute()
```

**Comment by posva** [comment]
What you need is to make your button go to the parent route instead of just going back, that would make the whole thing easier.
Closing as this is a very specific use case that should be solved in userland

**Comment by nandin-borjigin** [comment]
My PM requests a consistency between browser back button and the in-APP back button, thus injecting history seems inevitable
