### ISSUE TITLE
v-link dynamic params

### ISSUE THREAD

**Issue by gcfeng** [vuejs/vue-router#229]
My Vue component's data looks like
```
{
  data: function() {
    return {
       one: 'a'
    }
  }
}
```
in template, I use v-link to dynamic generate my link
```
<a v-link="/home/{{one}}">{{one}}</a>
```
Sadly, this doesn't work. When I try to custom a directive, it warns me 
```
[Vue warn]: v-plink="/one/{{one}}": attribute interpolation is not allowed in Vue.js directives and special attributes.
```

How can I use v-link to generate dynamic link? or there is another way to do this? thanks.

**Comment by zjzcn** [comment]
+1

**Comment by JosephSilber** [comment]
Use regular JavaScript expressions for directives:

```html
<a v-link="'/home/' + one">{{ one }}</a>
````

**Comment by gcfeng** [comment]
Thanks @JosephSilber . I missed the [1.0 binding syntax](https://github.com/vuejs/vue/issues/1325). In 1.0, literal directives are not valid and mustache tags can only appear inside native attributes. 

[A working example](https://jsfiddle.net/9onh9ph8/)

**Comment by raidenz** [comment]
@JosephSilber thanks you save my life
