### ISSUE TITLE
[Docs] Headings in sidebar for API page displayed incorrectly

### ISSUE THREAD

**Issue by Alex-Sokolov** [vuejs/vue-router#2294]
Headings with code blocks for `<router-link>` and `<router-view>` in sidebar displayed incorrectly for API page (https://router.vuejs.org/api/)

<img width="297" alt="2018-07-12 15 47 04" src="https://user-images.githubusercontent.com/4497128/42634150-231a8168-85eb-11e8-80c0-e386c2924686.png">

**Comment by posva** [comment]
Thanks, opened https://github.com/vuejs/vuepress/issues/645
