### ISSUE TITLE
希望router.addRoutes可以给已存在的路由下添加新路由，并且添加删除路由对象的功能

### ISSUE THREAD

**Issue by see311** [vuejs/vue-router#2299]
### What problem does this feature solve?
可以为已经存在的路由对象下添加新路由，删除已经存在的路由对象

### What does the proposed API look like?
```javascript
router.addRoutes(existingRoute,newRoutes)
router.removeRoutes(existingRoutes)
```

**Comment by posva** [comment]
Please check existing issues before creating new ones

**Comment by Xuhengfeng** [comment]
haha
