### ISSUE TITLE
Prevent parent route data reload when sub router changes

### ISSUE THREAD

**Issue by bekite** [vuejs/vue-router#230]
I have the following route definition:

```javascript
  '/users': {
    ....
    subRoutes: {
      '/:userId': {
        ....
      }
    }
```
Parent route and sub route component route object:
```javascript
route: {
  data () { ... }
}
```
Every time the sub route changes  (e.g /users/1 to /users/2 ) the parent data function is called.
Is there a way to prevent the parent data function from getting called when the sub route changes?

Currently I use `activate` instead of `data` in the parent route object. But I think you should use the data function when you want to fetch data.

**Comment by noirbizarre** [comment]
+1 
I have exactly the same issue.
subRoutes should not trigger parent `data()` if the parent doesn't change.

**Comment by yyx990803** [comment]
The point of `data` is that it will always be called when the route changes. If the data you are fetching is not related to the route params then using `activate` is correct.
