### ISSUE TITLE
vue-router without router-link

### ISSUE THREAD

**Issue by pradeepachan** [vuejs/vue-router#2300]
### What problem does this feature solve?
Can I use vue-router without using router-link tag? The use case is,  my HTML is created by designers, using standard components like A HREF="/my-router-link" tag -  so that it is visible as regular HTML. Later,  I enable dynamic nature by attaching routing script by mapping /my-router-link to a custom function.  

For this purpose, I was forced to move to page.js (https://visionmedia.github.io/page.js/) - as a barebone router - just for the above functionality. But it will be ideal, if vue-router can support this natively, and I could switch back to vue-router. 

 

### What does the proposed API look like?
<A HREF="/my-router-link"> 

route('/user/:id', user.load, user.show)

**Comment by posva** [comment]
if you do SSR, you end up with router links rendered as `a` tags.
I don't think there's anything we can do here, this is more of a question of how to integrate the work of your designers into your codebase 😄 

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions 🙂 (you are also more likely to get a lot more feedback)
