### ISSUE TITLE
Allow custom route matching functions

### ISSUE THREAD

**Issue by suau** [vuejs/vue-router#2302]
### What problem does this feature solve?
Allow less hierarchical and shorter urls for nested routes and general wide usecase flexibility.

Due to limitations of simple pattern matching the example from https://router.vuejs.org/guide/essentials/nested-routes.html require hierarchical urls for nesting routes and router-views e.g. `user/:id/profile` and `user/:id/posts`, routes without a common parent-path can't be nested.

Example: Let's say we want a tabbed overview page with different topics like this
```
---------------------------------
|                               |
| **DOGS**     CATS    UNICORNS | 
|                               |
| LIST OF DOGS:                 |
| 1) Woof                       |
| 2) Woof woof                  |
| 3) Woof woof woof             |
|                               |
---------------------------------
```
The routes would look like this
```
routes = [
   {
      path: '/pets',
      component: PetsTabs,
      children: [
         {
            path: 'dogs',
            component: DogsList
          },
         {
            path: 'cats',
            component: CatsList
          },
         {
            path: 'unicorns',
            component: UnicornsList
          }
      ]
   }
]
```
The pattern matching dictates hierarchical urls like above `/pets/dogs`, `/pets/cats`, `/pets/unicorns`.
Shorter urls like `/dogs`, `/cats`, `/unicorns` can't be achieved (while still keeping the overview page with the tabs).
With custom matcher (functions) that would be possible.
This is especially important when migrating from other frameworks, where the url structure can't be changed for SEO and other reasons.

### What does the proposed API look like?
For the example above that could look like this:
```
routes = [
   {
      matcher: (raw: RawLocation, current?: Route, redirectedFrom?: Location) => {
         // I DON'T REALLY NOW HOW RAWLOCATION LOOKS LIKE, THIS IS JUST FOR DEMO PURPOSES
         if (raw.path.startsWith('/dogs') || raw.path.startsWith('/cats') || raw.path.startsWith('/unicorns')) {
            return current;
         } else {
            return null;
         }
      },
      component: PetsTabs,
      children: [
         {
            path: 'dogs',
            component: DogsList
          },
         {
            path: 'cats',
            component: CatsList
          },
         {
            path: 'unicorns',
            component: UnicornsList
          }
      ]
   }
]
```
This is similar to the how Angular handles it:
https://angular.io/api/router/UrlMatcher

**Comment by posva** [comment]
This is achievable with alias (https://router.vuejs.org/guide/essentials/redirect-and-alias.html#redirect) and for more advanced cases, by providing a customised regex https://router.vuejs.org/guide/essentials/dynamic-matching.html#advanced-matching-patterns

**Comment by suau** [comment]
Thanks, these are great tips !

**Comment by rtcpw** [comment]
@posva I think having a custom async function-based route matcher would be beneficial. If I need to call an API to match a dynamic route, it is difficult to do it with the current feature set. Being able to supply arbitrary async function matcher would elegantly solve this issue.

**Comment by posva** [comment]
`router.resolve()` **must** be sync to resolve links. Any validation can be async and can happen in guards. @rtcpw don't necro issues please, ask open questions in vuejs/router discussions without mentioning a person
