### ISSUE TITLE
Vue-router -Is there a function to clear the routes

### ISSUE THREAD

**Issue by shenjianzch** [vuejs/vue-router#2303]
### What problem does this feature solve?
Adding a route has a router.addroutes method but I want to clear how the route I've registered should be successful.

### What does the proposed API look like?
router.clearAll()

**Comment by posva** [comment]
See #1234

**Comment by Tom-Evers** [comment]
#1234 has no clear conclusion and is a veritable sea of comments
Is there or is there not a clearAll function?

**Comment by CreativeWarlock** [comment]
Probably the best approach is to recreate the router:

```
const router = createRouter({
	history: createWebHistory(),
	routes: [
		...newRoutes,
	]
})
```
