### ISSUE TITLE
When using the query to pass parameters, the parameters are deeply nested data, the first jump is no problem, but when manually refreshed, the nested layer data will become "[object Object]"

### ISSUE THREAD

**Issue by liuyangjike** [vuejs/vue-router#2307]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/ovzyk4nl86](https://codesandbox.io/s/ovzyk4nl86)

### Steps to reproduce
1. Download the replay link item because it cannot be manually refreshed above
2. install dependencies, start project
3. click "B"
4. Manual refresh

### What is expected?
Manual refresh is not lost when query passes deep nested data

### What is actually happening?
 the third step : display the data "{ "id": "ee", "obj": { "name": "jike" } }"<br/>
the fourth step: display the data  "{ "id": "ee", "obj": "[object Object]" }"<br/>
"obj"  lose

---
I will encounter this problem when designing to some details page

**Comment by posva** [comment]
Use a custom `parseQuery` and `stringifyQuery` (it's in the docs).
You can use the qs package that support nested objects
