### ISSUE TITLE
TypeError: this._router.init is not a function

### ISSUE THREAD

**Issue by KMPolakowski** [vuejs/vue-router#2308]
### Version
3.0.1

### Reproduction link
[https://github.com/KMPolakowski/BuyCryptos/blob/master/resources/assets/js/app.js](https://github.com/KMPolakowski/BuyCryptos/blob/master/resources/assets/js/app.js)

### Steps to reproduce
go to the '/' route and take a look at the console

### What is expected?
Home template should load and vue router should work.

### What is actually happening?
[Vue warn]: Error in beforeCreate hook: "TypeError: this._router.init is not a function"

(found in <Root>)
warn @ VM506 app.js:14571
logError @ VM506 app.js:15715
globalHandleError @ VM506 app.js:15710
handleError @ VM506 app.js:15699
callHook @ VM506 app.js:16901
Vue._init @ VM506 app.js:18604
Vue @ VM506 app.js:18707
(anonymous) @ VM506 app.js:25157
__webpack_require__ @ VM506 app.js:20
Object.defineProperty.value @ VM506 app.js:25085
__webpack_require__ @ VM506 app.js:20
(anonymous) @ VM506 app.js:63
(anonymous) @ VM506 app.js:66
VM506 app.js:15719 TypeError: this._router.init is not a function
    at Vue.beforeCreate (VM506 app.js:48007)
    at callHook (VM506 app.js:16899)
    at Vue._init (VM506 app.js:18604)
    at new Vue (VM506 app.js:18707)
    at Object.<anonymous> (VM506 app.js:25157)
    at __webpack_require__ (VM506 app.js:20)
    at Object.defineProperty.value (VM506 app.js:25085)
    at __webpack_require__ (VM506 app.js:20)
    at VM506 app.js:63
    at VM506 app.js:66
logError @ VM506 app.js:15719
globalHandleError @ VM506 app.js:15710
handleError @ VM506 app.js:15699
callHook @ VM506 app.js:16901
Vue._init @ VM506 app.js:18604
Vue @ VM506 app.js:18707
(anonymous) @ VM506 app.js:25157
__webpack_require__ @ VM506 app.js:20
Object.defineProperty.value @ VM506 app.js:25085
__webpack_require__ @ VM506 app.js:20
(anonymous) @ VM506 app.js:63
(anonymous) @ VM506 app.js:66
VM506 app.js:14571 [Vue warn]: Error in render: "TypeError: Cannot read property 'matched' of undefined"

(found in <Root>)
warn @ VM506 app.js:14571
logError @ VM506 app.js:15715
globalHandleError @ VM506 app.js:15710
handleError @ VM506 app.js:15699
Vue._render @ VM506 app.js:18524
updateComponent @ VM506 app.js:16766
get @ VM506 app.js:17120
Watcher @ VM506 app.js:17109
mountComponent @ VM506 app.js:16773
Vue.$mount @ VM506 app.js:22518
Vue.$mount @ VM506 app.js:24917
(anonymous) @ VM506 app.js:25159
__webpack_require__ @ VM506 app.js:20
Object.defineProperty.value @ VM506 app.js:25085
__webpack_require__ @ VM506 app.js:20
(anonymous) @ VM506 app.js:63
(anonymous) @ VM506 app.js:66
VM506 app.js:15719 TypeError: Cannot read property 'matched' of undefined
    at render (VM506 app.js:47535)
    at createFunctionalComponent (VM506 app.js:18038)
    at createComponent (VM506 app.js:18228)
    at _createElement (VM506 app.js:18398)
    at createElement (VM506 app.js:18335)
    at Proxy.vm._c (VM506 app.js:18467)
    at Proxy.eval (eval at createFunction (VM506 app.js:24658), <anonymous>:3:1218)
    at Vue._render (VM506 app.js:18522)
    at Vue.updateComponent (VM506 app.js:16766)
    at Watcher.get (VM506 app.js:17120)
logError @ VM506 app.js:15719
globalHandleError @ VM506 app.js:15710
handleError @ VM506 app.js:15699
Vue._render @ VM506 app.js:18524
updateComponent @ VM506 app.js:16766
get @ VM506 app.js:17120
Watcher @ VM506 app.js:17109
mountComponent @ VM506 app.js:16773
Vue.$mount @ VM506 app.js:22518
Vue.$mount @ VM506 app.js:24917
(anonymous) @ VM506 app.js:25159
__webpack_require__ @ VM506 app.js:20
Object.defineProperty.value @ VM506 app.js:25085
__webpack_require__ @ VM506 app.js:20
(anonymous) @ VM506 app.js:63
(anonymous) @ VM506 app.js:66
app.js:48019 Uncaught TypeError: Cannot redefine property: $router
    at Function.defineProperty (<anonymous>)
    at Function.install (VM506 app.js:48019)
    at Function.Vue.use (VM506 app.js:18729)
    at Object.RESOLVED (VM506 app.js:50087)
    at __webpack_require__ (VM506 app.js:20)
    at Object.<anonymous> (VM506 app.js:25097)
    at __webpack_require__ (VM506 app.js:20)
    at Object.defineProperty.value (VM506 app.js:25085)
    at __webpack_require__ (VM506 app.js:20)
    at VM506 app.js:63

---
Worked fine previously, but suddenly started getting this exception.

**Comment by posva** [comment]
We need a boiled down repro for bugs. You can always use the forums or discord server to get help 🙂

**Comment by KMPolakowski** [comment]
![image](https://user-images.githubusercontent.com/41514470/43043000-cfa1f54c-8d89-11e8-8603-dc1aac193974.png)
![image](https://user-images.githubusercontent.com/41514470/43043005-dfd37454-8d89-11e8-99de-1302dc5d54e5.png)
Sorry but your shit doesn't work for whatever reason. Updating, reinstalling vue, vue-router won't help.

**Comment by KMPolakowski** [comment]
Could you at least tell where _router.init should be (Where should it be defined)? Nobody seems to have a clue about this problem.
