### ISSUE TITLE
window.history.pushState({ key } ...) overrides any previous pushState set

### ISSUE THREAD

**Issue by jakeg** [vuejs/vue-router#2309]
### What problem does this feature solve?
In a `beforeDestroy()` hook, do `window.history.replaceState({ foo: 'bar' }, '')`. This data will not be set though (well, only very briefly) as vue-router does its own `window.history.pushState({ key: _key }, '', url)` afterwards.

### What does the proposed API look like?
Not sure.

**Comment by posva** [comment]
Not sure why you're doing push state with Vue router but you shouldn't need this. If it's about adding state to router navigations. This is something  we have rejected already before in favor of store like solutions like vuex
