### ISSUE TITLE
Can someone reopen #2305, please?

### ISSUE THREAD

**Issue by watchduck** [vuejs/vue-router#2310]
I provided a (more) boiled down reproduction, as asked, but the bug remains closed. And I don't have the impression that my commenting there does any good.

https://github.com/vuejs/vue-router/issues/2305

**Comment by posva** [comment]
I haven't gave it up yet. I will look at it when I have time

**Comment by watchduck** [comment]
Nothing wrong with taking your time. I just don't get why this is a reason to close the issue. Maybe someone else would look at an open issue? Anyway, good to know that this is still on your radar.
