### ISSUE TITLE
Router links sometimes lead to wrong pages or don't work

### ISSUE THREAD

**Issue by watchduck** [vuejs/vue-router#2311]
### Version
3.0.1

### Reproduction link
[http://daggy1c.watchduck.net/nodes/9](http://daggy1c.watchduck.net/nodes/9)

### Steps to reproduce
Start on page 9, click parent 2, click parent 1. Link does not work.

Start on page 10, click parent 1, click child 2. Link leads to 13 instead of 2.

### What is expected?
That the links go to the correct pages.

### What is actually happening?
Sometimes these links go to the wrong page or don't work.

---
A detailed description is on Stackoverflow: https://stackoverflow.com/questions/51332783
Full version with console logging: http://daggy1.watchduck.net/nodes/9
Code on GitHub: https://github.com/watchduck/daggy/tree/static-data/front/src

Works without tag="li":
http://daggy1a.watchduck.net/nodes/9
https://github.com/watchduck/daggy/tree/simple-router-links/front/src

This is a duplicate of https://github.com/vuejs/vue-router/issues/2305, which was closed when a team member asked for a smaller reproduction, but not reopened when it was provided. Sorry for the noise, but there seems to be no other way.
https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github
Original reporter should be able to reopen a closed issue: https://github.com/isaacs/github/issues/583

**Comment by posva** [comment]
Please don't do this again. The other issue is already in my todo list j just do not have the time to check it yet.
This creates unnecessary noise for me and other people watching the repository

**Comment by watchduck** [comment]
Hopefully GitHub will introduce a more meaningful status than "closed" for situations like this. A yellow tag saying something like "in progress" would be great. I close this one now.
