### ISSUE TITLE
Transition gap between routes

### ISSUE THREAD

**Issue by chochihim** [vuejs/vue-router#2312]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/yy0ovx9rz](https://codesandbox.io/s/yy0ovx9rz)

### Steps to reproduce
This is the example at https://github.com/vuejs/vue-router/blob/dev/examples/transitions/app.js with some styles changes.
1. In the codesandbox app, navigating between /parent, /parent/foo and /parent/bar
2. There is white gap between the screen components.

### What is expected?
There is no white gap between the screen components.

### What is actually happening?
There is white gap between the screen components.

---
I am creating an mobile application and want to mimic the native screen navigating behaviour. The white gap between screen makes it not really working.

**Comment by sebmor** [comment]
A quick fix is to set the transform to a lower amount, try for example transformX(-70%).

But I'm also curious to know what is causing the white gap.

**Comment by chasebank** [comment]
I believe the issue here was some confusion in the transition classes. There was no active transition during the enter hook.

The transition classes should look something more like

```
.slide-left-enter-active,
.slie-left-leave-active,
.slide-right-enter-active,
.slide-right-leave-active {
  transition: transform 1s, opacity 1s;
}

.slide-left-leave-active,
.slide-right-leave-active {
  position: absolute;
}

.slide-left-enter,
.slide-right-leave-to {
  opacity: 0;
  transform: translate3d(100%,0,0);
}

.slide-right-enter,
.slide-left-leave-to {
  opacity: 0;
  transform: translate3d(-100%,0,0);
}
```

**Comment by truefusion** [comment]
https://github.com/vuejs/vue-router/tree/dev/examples/transitions

Using an example straight from the transitions example still shows a gap when transitioning between / and /parent. Instead of fading simultaneously, it waits till the first fades out completely before starting the next. The only time it doesn't show a gap is when you try transitioning between the parent and one of the children paths: /parent and /parent/foo and /parent/bar.

**Comment by AimForNaN** [comment]
If there is going to be child router views with transitions, the router view element must have a parent element; it cannot be the root element of the component.

In other words, this won't work:
```
<template>
    <transition>
        <router-view class="child-view"/>
    </transition>
</template>
```

Must be something like this:
```
<template>
    <div>
        <transition>
            <router-view class="child-view"/>
        </transition>
    </div>
</template>
```

Though, I think this also holds true for parent router views.

**Comment by posva** [comment]
I completely missed this one, sorry about that. It seems to be a CSS problem rather than a bug coming from the Router
