### ISSUE TITLE
router.beforeEach执行，router.afterEach却不执行问题

### ISSUE THREAD

**Issue by yangjh168** [vuejs/vue-router#2313]
我在router.beforeEach和router.afterEach定义执行了一些JS，但是某种情况下，router.beforeEach执行了，router.afterEach会却不执行，比如在一个home页面，router跳转到page页面，但是在page页面有个局部钩子beforeRouteEnter，在这钩子里执行 next('/home') 重定向回到home页面，这时相当于最终重定向到本身，这时会发现router.beforeEach执行了，但是router.afterEach并没有执行，有没有什么办法更好处理让router.afterEach都执行

**Comment by shichzh** [comment]
@gdmec07150749 遇到同样问题，请问解决了吗？

**Comment by simba88888** [comment]
You can add next() function on router.beforeEach.
