### ISSUE TITLE
Click event bindings do not work after navigating backward (native browser back) in iOS Safari

### ISSUE THREAD

**Issue by daetal-us** [vuejs/vue-router#2316]
### Version
3.0.1

### Reproduction link
[http://jsbin.com/hohewabama/1](http://jsbin.com/hohewabama/1)

### Steps to reproduce
on an iOS device, in Safari:
- Setup a view with an element with a @click event binding
- click element to verify functionality
- navigate away (either via routing or to some other link)
- navigate back (cached view/state loaded by browser?)
- click element and nothing happens

### What is expected?
click behavior should execute

### What is actually happening?
nothing is executed

**Comment by posva** [comment]
The click does work, for some reason `alert` doesn't fire but that is probably a Safari bug, any other instruction works. You should report this bug to webkit 🙂

**Comment by Beautybest** [comment]
在点击safari里面自带返回键的时候，会有点击事件无效的情况，目前不知道是什么原因
