### ISSUE TITLE
vue-router  open a new window

### ISSUE THREAD

**Issue by zhanyi233** [vuejs/vue-router#2318]
vue-router  when you open a new window, refresh the page, why always return to the home page

**Comment by oimmc** [comment]
解决了吗？

**Comment by wghust** [comment]
我也有这个问题，vue-bot把这些issue，全都关了。囧~~~ @wangyajundev

**Comment by Alisazheng12345** [comment]
请问解决了吗

**Comment by Alisazheng12345** [comment]
> 我也有这个问题，vue-bot把这些issue，全都关了。囧~~~ @wangyajundev

解决了？

**Comment by yan919** [comment]
我也遇到这个问题，解决了么

**Comment by zhanyi233** [comment]
http://note.youdao.com/noteshare?id=c0c26dcd6112a5ac9404d74025d4d60d&sub=CAEAEA7A2FC54C178FA835FE044A7475

**Comment by zhanyi233** [comment]
> 解决了吗？

http://note.youdao.com/noteshare?id=c0c26dcd6112a5ac9404d74025d4d60d&sub=CAEAEA7A2FC54C178FA835FE044A7475

**Comment by zhanyi233** [comment]
> 我也遇到这个问题，解决了么

http://note.youdao.com/noteshare?id=c0c26dcd6112a5ac9404d74025d4d60d&sub=CAEAEA7A2FC54C178FA835FE044A7475

**Comment by zhanyi233** [comment]
> 请问解决了吗

http://note.youdao.com/noteshare?id=c0c26dcd6112a5ac9404d74025d4d60d&sub=CAEAEA7A2FC54C178FA835FE044A7475
