### ISSUE TITLE
Vue-router not work properly when the onload event of window not triggered

### ISSUE THREAD

**Issue by zuibunan** [vuejs/vue-router#2320]
### Version
3.0.1

### Reproduction link
[https://github.com/vuejs/vue-router/blob/dev/examples/hash-mode/index.html](https://github.com/vuejs/vue-router/blob/dev/examples/hash-mode/index.html)

### Steps to reproduce
It seems that vue-router back not work when the onload event of window not trigger
I tested on PC Chrome and Android Phones

1. clone vue-router，and flow the Development Setup，
2. modify examples/hash-mode/index.html，add a script which would pending a long time (I use a proxy tool `whistle` emulate reqDelay)
3. visit `http://localhost:8080/hash-mode`，click `/foo`
4. at this time, you can see chrome is still on a loading status
5. click browser back button，vue-router didn't  route to right content

[whistle](http://wproxy.org/whistle/rules/reqDelay.html)

### What is expected?
vue-router should route to the right component when the back button clicked 

### What is actually happening?
vue-router doesn't route to the right component

I

**Comment by zuibunan** [comment]
Figured out by disabling vue-router use popstate, 

I have to modify the source code temporarily, because hashchange doesn't have this problem and vue-router doesn't support force using hashchange event !

https://github.com/vuejs/vue-router/blob/936d99afa14239e652df812d9e478cf2ce23b7a2/src/history/hash.js#L31

**Comment by zuibunan** [comment]
It seems that Webkit based browser has this problem
I tested on window10 Chrome，Firefox，Mac Safari
only Firefox works well

**Comment by LinusBorg** [comment]
Please share an actual runnable reproduction

**Comment by posva** [comment]
closing until a repro is provided

**Comment by xixizhangfe** [comment]
same problem. waiting for solution

**Comment by mice33** [comment]
same problem

**Comment by LinusBorg** [comment]
@ xixizhangfe @mice33 

> closing until a repro is provided

You didn't provide a reproduction -> issue stays closed

**Comment by mice33** [comment]
@LinusBorg 
Demo: https://github.com/mice33/router-demo

Chrome 70

can't from 'h2' page go back 'Hello World' page when the onload event of window not triggered

**Comment by mice33** [comment]
@posva repro https://github.com/mice33/router-demo

**Comment by posva** [comment]
a link is not enough, without repro steps I don't know what to check. FYI you can wait for things to be ready before mounting Vue

**Comment by mice33** [comment]
steps:
1. run dev && visit website
2. click 'go to h2' link
3. click 'go back' link, can't go back now when the onload event of window not triggered

**Comment by mice33** [comment]
@posva @LinusBorg
