### ISSUE TITLE
Fetch data example when route is same

### ISSUE THREAD

**Issue by ibeex** [vuejs/vue-router#2321]
### What problem does this feature solve?
I documentation https://router.vuejs.org/guide/advanced/data-fetching.html#fetching-after-navigation shows how to refresh view in case off url change. 

How to refresh view when url is still same? 

For instance there is router page with one child instance. Main page use form to open child page form input is part off url /parent/child/:something, if user wants to refresh child component resubmitting form on parent view don't trigger watch condition, there is ugly hack using query  and new Date(); 

This is useful for a number of reasons, but most importantly for UX. Users expect to be able to click on a link menu item and have the page content re-initialise. 
 

### What does the proposed API look like?
extend '$route' so it change even on same path.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

you can listen for the click event and check if the current route is the same to trigger your method that fetches data
