### ISSUE TITLE
on route change, in component's beforeDestroy, this.$route is the new route instead of old route. this should be changed

### ISSUE THREAD

**Issue by gillib** [vuejs/vue-router#2323]
### What problem does this feature solve?
I have a component linked to a route path.
in that component there is a  router-link that navigates the user to a different route.
before the component is destroyed, I need to do some cleanup regarding one of the route params.

in the beforeDestroy function I try to access the this.$route
but the values there belong to the new route.

the only solution I found was to bind the route params to the component data in the mounted function. and then I have access to those params in beforeDestroy.

please let me know if i'm doing something wrong. thanks!

thanks

### What does the proposed API look like?
the api will not change

**Comment by posva** [comment]
You are probably looking for beforeRouteLeave
