### ISSUE TITLE
别名无法匹配中文吗？

### ISSUE THREAD

**Issue by jymusic0663** [vuejs/vue-router#2326]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/guyun41/6zmob50e/](https://jsfiddle.net/guyun41/6zmob50e/)

### Steps to reproduce
我在路由里添加一个alias别名，其中想判断，访问类似地址为：`/中`、`/%E9%97%AE`的，但好像匹配不出来。

在 path-to-regexp的表达式在线测试工具测试正常，单独增加路由记录正常，别名无法匹配中文，别名直接用`/:keyword` 就可以匹配

单独正常

```
{
    name: 'searchSingle',
    path: '/:keyword([\u4E00-\uFE4F\u3400-\u4DB5\u3400-\u4DB5\u2F00-\u2FD5\uD800-\uDBFF\uDC00-\uDFFF]{1})',
    component: SearchSingle
}
```

别名，无法匹配中文，但直接用`/:keyword`就可以

```
{
    name: 'search',
    path: '/s/:keyword',
    component: MySearch,
    alias: '/:keyword([\u4E00-\uFE4F\u3400-\u4DB5\u3400-\u4DB5\u2F00-\u2FD5\uD800-\uDBFF\uDC00-\uDFFF]{1}$)' 
}
```

### What is expected?
alias别名匹配

### What is actually happening?
别名无法匹配中文

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Your repro isn't even complete... Maybe you need to escape the `\`: `\\u4E00`
