### ISSUE TITLE
Could you add the new property on Route objects, which can show if the route is replaced or pushed?

### ISSUE THREAD

**Issue by zamhown** [vuejs/vue-router#2327]
### What problem does this feature solve?
I wanted to record the history of router in 'router.beforeEach' method to display the breadcrumbs, but I didn't find any information about if the route will be replaced or pushed. It's easy to make mistakes.

### What does the proposed API look like?
A new boolean property called 'route.replaced'.

**Comment by posva** [comment]
this is already on our roadmap and tracked in a ticket (and maybe even an issue)
