### ISSUE TITLE
Could not fire next() in the cached view when route changes

### ISSUE THREAD

**Issue by icesman** [vuejs/vue-router#2328]
### Version
3.0.1

### Reproduction link
[https://github.com/icesman/bug-demo](https://github.com/icesman/bug-demo)

### Steps to reproduce
1. have two components A and B, a list, and two routes of them, such as 'pathA' for A and 'pathB' for B;
2. and then have a component such as C, when click item in A or B then jump to C, use the same component but with different routes, such as 'pathCForA' and 'pathCForB'
3. component C is cached used by the directive of 'include' via name
4. when click different items in A , items would be updated when redirect to 'pathCForA' , but when back from 'pathCforA' to 'pathA', and then to 'pathB', click the item in C. Now the route is 'pathCForB', but the next function wouldn't trigger.

### What is expected?
the next function of the beforeRouteEnter is fired

### What is actually happening?
the next function of the beforeRouteEnter is not fired

**Comment by LinusBorg** [comment]
Wehen components can be re-used between routes, beforeRouteEnter will not 
be called - that's documented behaviour. 

You should use beforeRouteUpdate instead. 

Alternatively, you could turn C Into its own component with its own name by simply extending he base component

```
Import CosmpA from '. /CompA'

export default {
  name: 'CompC', 
  extends: CompA

}
```

**Comment by icesman** [comment]
@LinusBorg actually the 'beforeRouteEnter' is called but the 'next()' is not fired, which doesn't make the data updated.
I resolved it but I am curious about why the next is no fired.
**Remember that params or query changes won't trigger enter/leave navigation guards**
I know that but for now it is the path change, shouldn't trigger the 'beforeRouteEnter'?
