### ISSUE TITLE
Async components produce hydration error.

### ISSUE THREAD

**Issue by houd1ni** [vuejs/vue-router#2329]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/jnm95moj23](https://codesandbox.io/s/jnm95moj23)

### Steps to reproduce
In my case: 
- make a project with the router.
- i.e. my component is required as import PostEdit from '../com/posts/PostEdit'
and
```
{
        path: '/posts/new/',
        // component: () => import('../com/posts/PostEdit'),
        component: PostEdit,
        name: 'posts_new'
      }
```

All's OK.

- Now uncomment and delete first sync import:

```
{
        path: '/posts/new/',
        component: () => import('../com/posts/PostEdit'),
        name: 'posts_new'
      }
```

Goes with an error: "[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render."

### What is expected?
Console is clear.

### What is actually happening?
I've got the error.

---
What could cause this behavour? I've tried a lot, and for 100% sure that the html output of Node and browser are the same.
I even have tried empty div ```<div></div>``` components! And I DO use router.onReady and so on the server side.

Even if this particular issue is simply cannot be reproduced, what could theoretically cause the problem? Thank you!

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You may be interested in checking https://ssr.vuejs.org/

**Comment by houd1ni** [comment]
Thanks a lot to @LinusBorg  this issue is solved.

Here's how (attention to the **_flow_**): https://forum.vuejs.org/t/issue-async-components-produce-hydration-error/40098

**Comment by LinusBorg** [comment]
Note: his entry-client wasn't set up like explained in the docs

**Comment by houd1ni** [comment]
@LinusBorg It wasn't clear for me what has to be first: it looks like I could do it another way, and the error message gave no clue at all. Maybe, it could be a bit clarified. (I don't say, I did it right way, btw, - just got used to vue doc simplicity :)
