### ISSUE TITLE
$route.meta types

### ISSUE THREAD

**Issue by backbone87** [vuejs/vue-router#2331]
### What problem does this feature solve?
Currently the `meta` field is typed to any. It would be nice, if we could provide a type for it. I tried an ambient module, but couldnt get it to work, so a generic type variable may needs to be introduced.

### What does the proposed API look like?
`interface RouteConfig<M = any> { meta?: M, ... }`

Also the using types may need adjustments.

**Comment by posva** [comment]
The meta object can be different per route, otherwise, its type would end up in making every single field optional, forcing you to check everytime the properties

**Comment by backbone87** [comment]
But we dont even have this decision...

Also some structure like this reduces the checks to a minimum:
```ts
  interface RouteMeta {
    navigation?: RouteNavigation,
    auth?: RouteAuth,
  }
```

The check doesnt change at all, if we want to check RouteAuth in a hook, because i need to check for `route.meta && route.meta.auth` anyway (even when the meta field type is `any`). Same for a navigation that is rendered from the route set.

**Comment by nicky1038** [comment]
@posva I agree with @backbone87. Providing an imperfect but still working ability to declare `meta` field type as a partial interface is way better than leave this field totally untyped. It won't force users to check properties more than how much they do it now, as an object of `any` type should be fully checked too.

The main potential problem I can see there is that the implementation of this feature would not be as easy as it seems to be. Vue-router itself creates ambient type declarations for Vue with `$route` and `$router` properties, so it will be necessary to add a new generic parameter (type of `meta` field) to Vue interface.

**Comment by posva** [comment]
Let's keep the discussion at https://github.com/vuejs/vue-router/issues/3183
