### ISSUE TITLE
Support 2 extra parameters when navigating like with router.push

### ISSUE THREAD

**Issue by xMartin** [vuejs/vue-router#2332]
### Version
3.0.1

### Reproduction link
[https://codepen.io/xMartin/pen/EpLPKr](https://codepen.io/xMartin/pen/EpLPKr)

### Steps to reproduce
1. Open browser console
2. Click on link "Go to Bar"
2. Click on link "Go to Baz (redirect to bar in beforeResolve handler)"

### What is expected?
See "after /bar" as the last entry in the console.

### What is actually happening?
See "redirect to /bar" as the last entry in the console.

---
All works fine if the current route is not the one that is going to be redirected to in `beforeResolve`. It also works fine if the redirect happens in `beforeEach`.

**Comment by posva** [comment]
This is expected as the redirect makes is cancelling the navigation

**Comment by xMartin** [comment]
Thanks for the feedback!

My use-case is showing a loading bar when routing starts and hiding it when routing is done. I'm using `beforeEach` and `afterEach` so far but for this special case the loading bar is never hidden.

Any idea how this can be accomplished?

**Comment by xMartin** [comment]
@posva I understand this behavior is expected but then vue-router might be missing a feature to support my use-case described above.

**Comment by posva** [comment]
Maybe we could support 2 extra parameters like with `router.push`, for onComplete and onAbort. Or maybe it's time for global `onAbort` too

**Comment by xMartin** [comment]
A global `onAbort` makes sense to me.

This edge case of redirecting to the current route is a tough one, because it is not really an explicit abort. As a developer I might expect the same thing (callback and all) to happen as any other route transition.

Anyway, a global `onAbort` would fix my issue :)

**Comment by diaevd** [comment]
Join - it's very necessary for me too

**Comment by xMartin** [comment]
@diaevd Can you describe your use-case?

**Comment by posva** [comment]
I appreciate your interest but it's not really necessary to add more to this thread 🙂

**Comment by posva** [comment]
Closing in favour of https://github.com/vuejs/vue-router/issues/2012

For the moment, the loading bar can be cancelled by using the `router.onError`
