### ISSUE TITLE
框架路由匹配。

### ISSUE THREAD

**Issue by JHeLiu** [vuejs/vue-router#2338]
### What problem does this feature solve?
1、减少没必要的配置代码量，更注重开发业务。
2、当我在多方面分片开发的时候，我不要再去关注路由配置。我只要按照约束进行文件新建就可以了

### What does the proposed API look like?
它能像C# MVC框架路由匹配。

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
