### ISSUE TITLE
since my English is poor , so I use Chinese

### ISSUE THREAD

**Issue by leisclei** [vuejs/vue-router#2339]
### What problem does this feature solve?
请教一下,用keep-alive缓存的页面,打包成的h5 app,这个缓存会不会在手机内存堆积,需不需要清理

### What does the proposed API look like?
请教一下,用keep-alive缓存的页面,打包成的h5 app,这个缓存会不会在手机内存堆积,需不需要清理

**Comment by fnlctrl** [comment]
请使用[论坛](http://forum.vuejs.org/)或[gitter](https://gitter.im/vuejs/vue)提问。

-----------
需要根据实际占用的内存量决定。不放心可以清理。
