### ISSUE TITLE
Prevent following v-link from inside click handler

### ISSUE THREAD

**Issue by ryanwinchester** [vuejs/vue-router#234]
I have a condition to check before following a link, and no matter what I do I can not stop it.

I have tried `e.preventDefault()`, `e.stopPropagation()`, `return false`

```html
<a v-link="'things/'+thing.id" @click="checkLock(thing, $event))">Link</a>
```

```js
checkLock: function (thing, e) {
    if (! thing.is_locked) {
        return true;
    }

    var proceed = confirm("Proceed?");

    if (! proceed) {
        e.preventDefault();
    }
}
```

`console.log` of `e` is a `MouseEvent` and `proceed` is `false`.

Am I missing something simple?

**Comment by ryanwinchester** [comment]
also, this worked in a previous iteration of my app using Vue 0.12

**Comment by yyx990803** [comment]
You can just do a conditional expression in v-link.

**Comment by ryanwinchester** [comment]
I'm not sure how to accomplish that without displaying the pop-up confirmation for each link that appears on the page.

Here is the actual link, in context: https://github.com/flashtag/flashtag/blob/master/app/Admin/resources/assets/js/components/posts/index.vue#L41

It is a list of posts that can be locked by another user and so if you click on a link it checks if it's locked and gives you a warning message if you really want to proceed, at which point you can cancel.

![Open locked post](https://s3-us-west-2.amazonaws.com/ryanwinchester/screenshots/Screenshot+2015-11-13+20.13.35.png)

**Comment by ryanwinchester** [comment]
Okay, I've got it working, but it feels kinda dirty.

```html
<a href="#!/things/{{ thing.id }}" @click.prevent="goToThing(thing)">{{ thing.title }}</a>
```

```js
goToThing: function (thing) {
    if (this.checkLock(thing)) {
        this.$route.router.go({ path: '/things/'+thing.id });
    }
},

checkLock: function (thing) {
    if (! thing.is_locked) {
        return true;
    }

    return confirm("Proceed?");
},
```

Anyone have thoughts on this?

**Comment by azamat-sharapov** [comment]
What Evan means, is: `v-link='isOkay(thing.id) ? 'things/'+thing.id : null"`

**Comment by ryanwinchester** [comment]
@azamat-sharapov The problem is the `isOkay` check requires user input and there could be hundreds of these links in the list. You will get hundreds of confirm popups when the page loads.

**Comment by ryanwinchester** [comment]
It would be nice if there was a way to stop the link from proceeding inside a click handler function.

**Comment by yyx990803** [comment]
If you are trying to prevent navigation away from current route, you should
use the canDeactivate hook...

**Comment by ryanwinchester** [comment]
@yyx990803 Can I pass an object to that hook on a click event?

**Comment by yyx990803** [comment]
@ryanwinchester ah I see, so you need reference to a `v-for` scope alias. Sounds like for your use case you should just perform the navigation inside the click handler using `this.$route.router.go()` instead of using a `v-link` separately.

**Comment by ryanwinchester** [comment]
Thanks, that's what I've done.
