### ISSUE TITLE
增加功能：返回路由的实际地址

### ISSUE THREAD

**Issue by JZLeung** [vuejs/vue-router#2342]
### What problem does this feature solve?
比如要分享，或是在新标签页面打开，则需要获取当前（下一个页面）的真实地址。

### What does the proposed API look like?
使用： `$route.getPath(location)` 函数返回该路由的绝对路径。
如现在有一个路由是这么定义的：
```js
{
  name: 'userInfo',
  path: '/user/:uid',
  component: userComponent
}
```

```js
const url = this.$route.getPath({
  name: 'userInfo',
  params: {
    uid: 2
  }
})
// url : http://example.com/#/user/2
```

**Comment by posva** [comment]
https://router.vuejs.org/api/#router-resolve
