### ISSUE TITLE
Imported router doesn't work, inline declaration of vue-router does.

### ISSUE THREAD

**Issue by lululeon** [vuejs/vue-router#2343]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/3qnxwp6k3p](https://codesandbox.io/s/3qnxwp6k3p)

### Steps to reproduce
https://codesandbox.io/s/3qnxwp6k3p

Summary:
- vue @ 2.5.17
- vue router @ 3.0.1
- create basic app using vue-cli.
- define app routes in separate file, import file into main.js and pass router to Vue instance.

### What is expected?
Routing should work

### What is actually happening?
App cannot load, errors in console.

**Comment by posva** [comment]
it's `export default router` (as said in Discord 😛 )

**Comment by lululeon** [comment]
OMG!!! Shameful.
@posva 🥇 thank you!!!! I gave up too soon on discord; didn't see responses :)
I'll see myself out 😝

**Comment by posva** [comment]
haha, no worries, I definitely answered in discord some hours after you opened the issue
