### ISSUE TITLE
There's a potential collision between state keys

### ISSUE THREAD

**Issue by chatoo2412** [vuejs/vue-router#2349]
### Version
3.0.1

### Reproduction link
[https://github.com/vuejs/vue-router/blob/90cd2690d59c6bd56e5bc12b5b752166a1d35e98/src/util/push-state.js#L22-L30](https://github.com/vuejs/vue-router/blob/90cd2690d59c6bd56e5bc12b5b752166a1d35e98/src/util/push-state.js#L22-L30)

### Steps to reproduce
``` js
console.log(window.history.state.key) // 2078.800

// refresh window and try again
console.log(window.history.state.key) // 1678.300

// refresh window and try again
console.log(window.history.state.key) // 2263.300

// ...repeat

// refresh window and try again
console.log(window.history.state.key) // 1678.300 - collision
```

### What is expected?
unique value

### What is actually happening?
collision

---
Because of Spectre issue, each browser reduced the resolution of `performance.now()`. For example, [FireFox's precision is only 2ms](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now#Reduced_time_precision).

[It doesn't a problem in a single Vue instance lifecycle](https://github.com/vuejs/vue-router/pull/998#issuecomment-265549456).

But there may be multiple Vue instances in the whole session history, and keys between them could collide.

Please replace `performance.now()` with `Date.now()` or [uuid](https://github.com/kelektiv/node-uuid).

**Comment by posva** [comment]
what's the matter about the keys being the same from one session to another? What would prevent it from happening using uuid?
