### ISSUE TITLE
Provide `router-alive` component for better performance

### ISSUE THREAD

**Issue by masquevil** [vuejs/vue-router#2353]
### What problem does this feature solve?
Just like keep-alive.
The only difference is that use `history.state.key` as `vnode.key`.
It will use cache when history popstate, and create new component when click `router-link`.

### What does the proposed API look like?
```
<router-alive>
  <router-view></router-view>
</router-alive>
```

**Comment by posva** [comment]
I do not really see the benefit of this but it can be achieved in userland 🙂
