### ISSUE TITLE
watch '$route.query' is triggering when click in some link fragment/anchor like <a href="#">test</a>

### ISSUE THREAD

**Issue by willjosefi** [vuejs/vue-router#2355]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/willjosefi/4shd27gm/9/](https://jsfiddle.net/willjosefi/4shd27gm/9/)

### Steps to reproduce
Just click in the links and check console or the "logs"

### What is expected?
Not trigger

### What is actually happening?
Triggering when click in some link anchor/fragment that links to the current page

**Comment by posva** [comment]
We create copies of the query object, that's why it triggers again. Reusing the same query object may be a problem. I will need to check further. A more complete repro for myself: https://jsfiddle.net/posva/4shd27gm/17/

**Comment by posva** [comment]
Ideally, one would watch the actual query key they need directly or watch muliple ones by passing a function as the first argument to `$watch`

**Comment by posva** [comment]
This is inherent to how watchers work and is a won't fix.
We can prevent multiple watchers by watching the properties we require like `$route.query.q`
