### ISSUE TITLE
Scrollbehavior does not fire on initial load

### ISSUE THREAD

**Issue by jafri** [vuejs/vue-router#2358]
```
const router = new Router({
  linkActiveClass: 'is-active',
  mode: 'history',
  scrollBehavior (to) {
    console.log(to)
    if (to.hash) {
      return { selector: to.hash }
    } else {
      return { x: 0, y: 0 }
    }
  },
  routes
})
```

Scrollbehavior does not fire on initial load of page, it fires when moving to another page though

**Comment by mgibas** [comment]
Please reopen - this is still existing issue, though cause its a first load + router its quite hard to create any useful repro.

**Version**
3.0.2

**Steps to reproduce**
- Create simple app using vue-cli
- nclude router with scrollBehavior and single route
- Refresh app

**What is expected?**
configured `scrollBehavior` should be called on initial load - ie. to support navigation to anchored headings (#)

**What is actually happening?**
`scrollBehavior` is NOT called on initial load

**Comment by jafri** [comment]
Yes, scrollBehavior is NOT called on initial load

Have had to hack it by using created () on the component wrapping around `<router-view/>`

**Comment by mgibas** [comment]
I just used `created` on app component to workaround this issue. Maybe this is expected behaviour though ?

**Comment by jafri** [comment]
@posva can have a look at this

**Comment by cbeauchesne** [comment]
I confirm it's not fired on initial load. We had to handle hash use-case in component view methods.
