### ISSUE TITLE
Two feature to make history.state more useful

### ISSUE THREAD

**Issue by masquevil** [vuejs/vue-router#2362]
### What problem does this feature solve?
1) Run replaceState when app init
`history.state.key` is a very useful value. But `history.state` is null when app init.
Although manually run `router.replace` when app created is ok, guards like `router.beforeEach` will run twice, which is not expected.

2) Change `history.state.key` when replaceState
Generally, PageA replace to PageB, keep history.state the same key is fine.
But in this case: PageA -> PageB -> replace to PageC -> back to PageA -> replaceTo PageD ----- It's expected that PageD use the same key with PageA, but actually same with PageB & PageC.
A solution is to change `history.state.key` when replaceState. So that all page-jump will generate a new key.

### What does the proposed API look like?
no need

**Comment by posva** [comment]
what do you need the key for?

**Comment by masquevil** [comment]
Our original request (from PM) is:
Refresh page when click a link, do not refresh when history.go(n). Just like origin browser behavior.
The main benefit can be imagined by this case:
Product page, jump to similar product page, use the same component.
We hope to see empty content when click a link, and do not refresh when go back.
Moreover, if some data load from server and some data keeps page status, data reset would be complicated.

After lots try, I thought there should be a manageable route queue. Then I found history.state.key could be used.
Idea is use `history.state.key` take the place of the `key` in component 'keep-alive'. Here is [a code sample](http://jsfiddle.net/3ywx1p2z/1/), the complete code is more complicated.
Then I found these problem. Some problems ( like nested route ) can be solved without changing source code of vue-router, not including those above.

**Comment by posva** [comment]
I still don't understand. Why would you use the history.state.key which is private api.

Does the page refresh when you do `router.go(n)`? if so that's a bug (and I would like to see a repro)

**Comment by masquevil** [comment]
Sorry, not refresh, I mean refetch data.
As the official example of [Data Fetching](https://router.vuejs.org/guide/advanced/data-fetching.html#fetching-after-navigation), the first line of the function 'fetchData' should be data reset (`this.error = this.post = null`). And data reset could be very complicated.
Furthermore, when I go to similar product page, it would be called by `watch: { '$route': 'fetchData' }`. It means when we do `router.go(-1)`, which expected is showing previous data without `fetchData`, but actually not.
I use `history.state.key` because it is the closest way I can find ( take the place of 'keep-alive' cache key ) to solve my problem.

**Comment by posva** [comment]
okay, this is not clear at all. If you need data caching, you can achieve it with Vuex or other methods. You should consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) and come back once you have a more detailed feature request or bug report 🙂
