### ISSUE TITLE
beforeEach causes <failed to convert exception to string> on any next() parameter except false or empty string

### ISSUE THREAD

**Issue by kalreg69** [vuejs/vue-router#2363]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/93jwr2okyy](https://codesandbox.io/s/93jwr2okyy)

### Steps to reproduce
More precise description of problem can be found on Stackoverflow under that link:
https://stackoverflow.com/questions/52011879/vuerouters-beforeeach-causes-error-failed-to-convert-exception-to-string?noredirect=1#comment90975639_52011879

The link to sandbox refers in console "maximum callstack size exceeded" - my console says "failed to convert exception to stirng", however puting next() or next(false) clears the problem. It generates problems only if next has a any string parameter 

### What is expected?
I expect rerouting to specified component on calling next('/registeredComponent').

### What is actually happening?
I get an error 
[vue-router] uncaught error during route navigation:
<failed to convert string to exception>

**Comment by posva** [comment]
`next` has to be called without parameters to confirm navigation, otherwise you will keep triggering the `beforeEach` hook:

```js
router.beforeEach(function(to, from, next) {
  console.log(to.path)
  if (to.path !== '/timer') {
    next("/timer");
  } else {
    next();
  }
});
```

**Comment by sacse2010** [comment]
if (1 === 1) {
    next("/");
}
