### ISSUE TITLE
After build routing does not work in chrome, but works in firefox

### ISSUE THREAD

**Issue by lordenas** [vuejs/vue-router#2366]
### What problem does this feature solve?
After "npm run build" try to run index.html
Everything works in Firefox. But in google chrome when you click the link turns file:///C:/index ..

### What does the proposed API look like?
```
import Vue from 'vue';
import VueRouter from 'vue-router';

Vue.use(VueRouter);

import Login from './pages/login';
import Index from './pages/index';

const routes = [
	{
		path: '',
		redirect: {name: 'Login'}
	},
	{
		name: 'Login',
		path: '/login',
		component: Login,
		props: { name: 'Авторизация' }
	},
	{
		name: 'Index',
		path: '/Index',
		component: Index,
		props: { name: 'Страницы' }
	}
];

export const router = new VueRouter({
	routes,
	mode: 'history'
});

```

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

BTW, you first route should probably be `'/'`

**Comment by neronovtf** [comment]
Hello.
Replace 
`{
	path: '',
	redirect: {name: 'Login'}
}`
with
`{
	path: '*',
	redirect: {name: 'Login'}
}`
