### ISSUE TITLE
Base URL containing query parameters breaks routing

### ISSUE THREAD

**Issue by benjamindavid** [vuejs/vue-router#2367]
### Version
2.5.3

### Reproduction link
[https://codepen.io/benjamindavid/pen/YOWgPr](https://codepen.io/benjamindavid/pen/YOWgPr)

### Steps to reproduce
Go to this URL (containing a test query parameter) https://s.codepen.io/benjamindavid/debug/YOWgPr/mVMbGpDQDqpr?p=test

### What is expected?
The page should show "foo" as the Foo component is defined for the `/` path and the base URL contains the full path, including query parameters: `/benjamindavid/debug/YOWgPr/mVMbGpDQDqpr?p=test`

### What is actually happening?
The `/` route is not matched, the query parameters contained in the base URL don't seem to be properly taken into account.

**Comment by posva** [comment]
a base cannot contain a query as it acts as a prefix
