### ISSUE TITLE
Registering Vue router hooks prevents vue rendering

### ISSUE THREAD

**Issue by Fachher** [vuejs/vue-router#2373]
### Version
3.0.1

### Reproduction link
[https://github.com/Fachher/vuejsschool/tree/bug/vue-router](https://github.com/Fachher/vuejsschool/tree/bug/vue-router)

### Steps to reproduce
git clone example project
yarn run serve
open http://localhost:8080 with your browser
Click on any link => You will see that the content area isn't rendered.

### What is expected?
Clicking on "home" or "about" should render the content 

### What is actually happening?
Content area isn't rendered

---
When registering the hooks in file class-component-hooks.ts everything works as expected but when I add a hook to one of the component, rendering does not work

class-component-hooks.ts .   
Component.registerHooks([
    'beforeRouteEnter',
    'beforeRouteLeave',
    'beforeRouteUpdate'
]);

Home.vue .  
export default class Home extends Vue {
        beforeRouteEnter(to: Route, from: Route, next: Function) {
            console.log('About has been entered');
        }    
}

**Comment by posva** [comment]
you need to call the `next` function to confirm the navigation

**Comment by Fachher** [comment]
Thank you. It wasn't obvious to me. Maybe the author of vue-class-component should update their Readme. https://github.com/vuejs/vue-class-component. Here you can see that they are not calling the next function inside beforeRouteEnter.

**Comment by posva** [comment]
Even better, submit a PR 🙂
