### ISSUE TITLE
Query parameter types change on reload

### ISSUE THREAD

**Issue by michaelfelixmurphy** [vuejs/vue-router#2381]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/vv2rrjm2p7](https://codesandbox.io/s/vv2rrjm2p7)

### Steps to reproduce
It helps to open the inline browser in a new window so you can see the native URL bar.

Click "say hello" or "say goodbye" to go to the respective page with no query param. Number should be blank and the type undefined.

Click the button to switch pages but set the number to 10. The number is set and the type is number.

You can also confirm that the param is being set in the URL bar.

Now reload the page (or copy the URL and load it in a fresh tab). The number will be set and display correctly, but the type will be string. You can confirm this in the Vue devtools.

### What is expected?
On a fresh load or reload, the type of the "number" param should be the same as it was when it was set by Vue. The type should be number.

### What is actually happening?
On reload, the type changes to string.

---
Frankly I don't care which type vue router gives to me. I would prefer the parsing happens automatically, so I get a number, but if I know I'll get a string, I can always call parseInt myself. The important thing is that there is no difference in types between loading from another page vs loading for the first time from a URL. With many more query params of different types it is a pain (and code bloat) to handle the case where any of them can come in as a string or as the expected type.

**Comment by posva** [comment]
When params come from URL, they're always strings, but when passed by a router-link or `push`, they keep their type. This is something that is already tracked but I cannot find the issue, it's maybe just in the board, we may automatically cast params to strings in the future to make it consistent

**Comment by michaelfelixmurphy** [comment]
Thanks for the quick response on this. It would be nice if that issue was somewhere public. I spent quite a while looking for any mention of this online, searching the vue-router issues, and creating a test case for this issue.
