### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by OculusMode** [vuejs/vue-router#2384]
### Version
2.5.0

### Reproduction link
[https://codesandbox.io/s/7wnmv7q9n1](https://codesandbox.io/s/7wnmv7q9n1)

### Steps to reproduce
Simply navigate through tabs again and again

### What is expected?
Memory should be preseved

### What is actually happening?
Memory is increasing by time

**Comment by OculusMode** [comment]
I just found that giving type as email or password was causing it. Still is it expected behaviour of increasing in ram every time?

**Comment by fnlctrl** [comment]
Please provide a minimal reproduction instead of a complex project. Remove anything that doesn't prevent reproducing the issue.

**Comment by posva** [comment]
as @fnlctrl said, this is especially true with memory leak reports. Ideally, an html file is better, so it's easier to see create snapshots.

Closing until an appropriate repro is provided

**Comment by OculusMode** [comment]
@posva @fnlctrl  i have created link with only needed code. 
please check
https://codesandbox.io/s/o9zjqyk8n9

**Comment by posva** [comment]
What is exactly the memory leak you are seeing? 🤨

**Comment by OculusMode** [comment]
@posva thanks for reply. I'm honestly not much deep into js.
So i can be totally wrong.
But in my code (previously given) when i was using input tag with type email and password memory kept increasing(very small amount like 0.2 to 0.5MB).

from new link(with  if you'll navigate again and again you'll see result like this image.)
![screen shot 2018-09-13 at 1 05 56 pm](https://user-images.githubusercontent.com/37273899/45473863-d34de200-b755-11e8-9e73-eee990e9dacd.png)

And if you remove type of input  you'll see result like this image.

![screen shot 2018-09-13 at 1 06 01 pm](https://user-images.githubusercontent.com/37273899/45473875-de087700-b755-11e8-959f-3340532413cd.png)


And im not sure is this the actual 'should be' behaviour?

Thanks for reply :)

**Comment by hohlb** [comment]
I can see the same problem. I noticed this in my "real" application, so I looked if I can reproduce it with an unmodified project created by vue-cli using `vue ui` -> _create new Project_. It seems so, if I am not measuring the wrong things.

**Versions**
_Environment_
Node.js: 10.10.0
@vue/cli: 3.0.3 (to create the repro)

_Project (dependencies)_
vue: 2.5.17
vue-router: 3.0.1

_Project (devDependencies)_
@vue/cli-plugin-babel: 3.0.3
@vue/cli-service: 3.0.3
vue-template-compiler: 2.5.17

**Reproduction link**
https://github.com/hohlb/vue-router-memory-leak
Only the built project: https://github.com/hohlb/vue-router-memory-leak/tree/master/dist

**Steps to reproduce**

Simply navigate between "Home" and "About" routes by clicking them alternatively:
![grafik](https://user-images.githubusercontent.com/35731400/45537357-5168c200-b804-11e8-9c65-10dfd206d721.png)


This is true for the devServer as well as the built site (built using `npm run build --modern`).

In [Chrome's Taskmanager](https://www.wikihow.com/Open-Google-Chrome-Task-Manager), you will see the increase in memory consumption. As @OculusMode described, you also see it in Chrome's DevTools, e.g. by comparing [Heat Snapshots in Chrome](https://developers.google.com/web/tools/chrome-devtools/memory-problems/heap-snapshots#comparison_view).

**Comment by posva** [comment]
I opened #2389 with a boiled down repro. It's really weird that it only happens with input[type=password]

**Comment by GummyDonut** [comment]
Sorry to bother, has there been any progress on this since, we also noticed this memory leak as well and was wondering if there was any work around?

**Comment by egeersoz** [comment]
Same here. Please provide an update.
