### ISSUE TITLE
IE9: Object doesn't support this property or method "replaceState"

### ISSUE THREAD

**Issue by clevergod** [vuejs/vue-router#2386]
### Version
3.0.1

### Reproduction link
[https://github.com/vuejs/vue-router/issues/1834](https://github.com/vuejs/vue-router/issues/1834)

### Steps to reproduce
IE9 throw the following error： Object doesn't support this property or method "replaceState"
I set the options: fallback: false
I saw a similar issue：https://github.com/vuejs/vue-router/issues/1834
Why not do the same treatment here?：
https://github.com/vuejs/vue-router/blob/8dadf9744e5d8431bf3e9148e66b34f4849055b5/dist/vue-router.js#L2149-L2153

### What is expected?
In addition to the judgment support supportPushState processing：https://github.com/vuejs/vue-router/blob/8dadf9744e5d8431bf3e9148e66b34f4849055b5/dist/vue-router.js#L2149-L2153

### What is actually happening?
IE9 throw the following error: Object doesn't support this property or method "replaceState"

**Comment by JounQin** [comment]
It seems that it has been fixed but not published to npm yet.
