### ISSUE TITLE
Params are not passed to the route

### ISSUE THREAD

**Issue by gil0mendes** [vuejs/vue-router#239]
Hey,

I'm trying to pass an id to a specific route, but the param is never passed.

```javascript
'/post/:id': {
    component: require('./components/blog/post.vue')
},
```

```jade
a.btn.btn-link(v-link="{ path: '/post', params: { id: '1' }}") Ler Mais...
```

Anyone can help me, I do not know what to do.

**Comment by azamat-sharapov** [comment]
Can you provide reproduction? (jsfiddle?)

**Comment by gil0mendes** [comment]
Ok... I used the example on the vue-router documentation as base... https://jsfiddle.net/onsg89e1/

**Comment by azamat-sharapov** [comment]
Params make sense together with `name`: https://jsfiddle.net/onsg89e1/1/
You don't need `params` if you are using `path`. If you want to use `path`, just do: `path: '/foo'+1`

**Comment by gil0mendes** [comment]
Ok... Now I understand. I think the documentation is not very clear what comes to this matter.

Tks ;)

**Comment by melanke** [comment]
@azamat-sharapov you jsfiddle is not working neither (at least, not anymore).

The JSON is not visible

**Comment by azamat-sharapov** [comment]
@melanke https://jsfiddle.net/onsg89e1/2/ (`vm.$router` changed into `vm.$route`).
