### ISSUE TITLE
The output component names in vue-router.common.js are not what is defined in the src/components files

### ISSUE THREAD

**Issue by stevenadams** [vuejs/vue-router#2392]
### Version
3.0.1

### Reproduction link
[https://github.com/vuejs/vue-router/blob/dev/dist/vue-router.common.js#L386](https://github.com/vuejs/vue-router/blob/dev/dist/vue-router.common.js#L386)

### Steps to reproduce
Try using `<RouterLink />` instead of `<router-link />`

### What is expected?
I should be able to use `<RouterLink />`

### What is actually happening?
`<routerlink> //content </routerlink>` gets rendered

---
I cloned the repo and ran `npm run build` - got the expected outcome in vue-router.common.js

**Comment by posva** [comment]
It hasn't been released yet. Please be patient

**Comment by stevenadams** [comment]
@posva ah cool, no worries. I thought because the component files were in master it should have been available. My bad, look forward to seeing this launched :)
