### ISSUE TITLE
Expose (store) history state stack

### ISSUE THREAD

**Issue by lakca** [vuejs/vue-router#2393]
### What problem does this feature solve?
As we know,  for security reasons, browsers do not expose visited pages history.
But if in a single page application , it will be very helpful to access the history stack. 
For example, I can clarify if it should directly back to previous or redirect to specific page when logged in.
although I can replace these with other approaches in different scenarios or maintain this by myself.
Appreciate it!

### What does the proposed API look like?
router.history.stack or others are all okay.

**Comment by JounQin** [comment]
Or maybe you can just implement a plugin for it, not everyone needs this feature and should not affect the core library.

**Comment by posva** [comment]
The funny thing is we don't have it in history mode. This should be doable through a plugin though by branching into `router.afterEach`
In abstract mode, you do have access to it

> For example, I can clarify if it should directly back to previous or redirect to specific page when logged in.

You should probably save the redirect url in a query parameter and read it when successfully logged in, then redirect

**Comment by lakca** [comment]
Okay, I see, maybe it's not the attention of vue-router.
Thanks.
