### ISSUE TITLE
有时候会出现不能命中目标路由而直接命中根路由的问题，不是必然，有时候会出现，频率还有点高，在开发阶段没有问题，发布后就会有问题

### ISSUE THREAD

**Issue by Undefined100** [vuejs/vue-router#2399]
### Version
3.0.1

### Reproduction link
[http://47.95.14.230:10003/dist/index.html#/test1](http://47.95.14.230:10003/dist/index.html#/test1)

### Steps to reproduce
一直点 【router-link】点击跳转test3 ，理论上回会命中目标路由，但会出现直接到根路由的情况。

### What is expected?
一直都是命中目标路由

### What is actually happening?
会出现直接到根路由的情况

**Comment by posva** [comment]
Please provide a valid repro using jsfiddle or codesandbox. And I will appreciate you write issues in English, I don't speak Chinese 😉
