### ISSUE TITLE
Why encode '(' to 28%

### ISSUE THREAD

**Issue by dongnaebi** [vuejs/vue-router#2400]
### Version
3.0.1

### Reproduction link
[https://abc.com/search?keyword=iPhone%20XS%20Max(A2104)%20%E5%9B%BD%E8%A1%8C%E7%89%88](https://abc.com/search?keyword=iPhone%20XS%20Max(A2104)%20%E5%9B%BD%E8%A1%8C%E7%89%88)

### Steps to reproduce
I use vue-router in ssr,in entry-server.js,got rejection
```javascript
    const { url } = context
    const { fullPath } = router.resolve(url).route

    if (fullPath !== url) {
      return reject({ url: fullPath })
    }
```
the URL is `/search?keyword=iPhone%20XS%20Max(A2104)%20%E5%9B%BD%E8%A1%8C%E7%89%88`
get fullPath in express by `req.url` is `/search?keyword=iPhone%20XS%20Max(A2104)%20%E5%9B%BD%E8%A1%8C%E7%89%88`
but in vue-router `route.fullPath` get `/search?keyword=iPhone%20XS%20Max%28A2104%29%20%E5%9B%BD%E8%A1%8C%E7%89%88`
the difference is vue-router encode '(' to 28% and ')' to 29%,why do this?

### What is expected?
don't endoce `!， '，(，)，*，-，.，_，~，0-9，a-z，A-Z`

### What is actually happening?
got error in ssr

**Comment by posva** [comment]
It's because they are reserved by the spec: https://github.com/vuejs/vue-router/commit/3f91065e5165d0457ee6295980086b86e107d034
