### ISSUE TITLE
$router not available in function passed as prop (undefined is not an object)

### ISSUE THREAD

**Issue by rothsandro** [vuejs/vue-router#2401]
### Version
3.0.1

### Reproduction link
[https://github.com/rothsandro/vue-router-issue](https://github.com/rothsandro/vue-router-issue)

### Steps to reproduce
1. Clone the repo
2. Go into the repo folder
3. `npm install`
4. `npm run serve`
5. Open the app (http://localhost:8080/)
6. Click on the button

The parent component `HelloWorld` has a property `demo` with a function `run`, passed down to its child component `ChildComponent`. Clicking the button executes the run method in the child component.

The run method triggers four alerts:
1. Alert of a property of the class
2. Alert a property from the Vuex store
3. Alert the $router object using a method in the class
4. Alert using this.$router directly instead of a separate function

### What is expected?
You should see four alerts, number 3 and 4 should show "[object Object]".

### What is actually happening?
Only three alerts will be shown, number four produces the following error:

```
TypeError: undefined is not an object (evaluating 'this._routerRoot._router')
```

The same syntax using this.$store works fine. Therefore I assume the problem is related to Vue Router, not Vue or Typescript.

**Comment by posva** [comment]
There is too much in your repro. Could you reproduce it without Typescript, please? I tried with a js fiddle and it works: https://jsfiddle.net/posva/vLo4xtsk/1/

**Comment by rothsandro** [comment]
I have created a new project without Typescript on a [separate branch](
https://github.com/rothsandro/vue-router-issue/tree/without-typescript) - it works (as your example on jsfiddle). The problem only occurs with Typescript.

**Comment by posva** [comment]
In that case, there is nothing I can do here to help you 😕
You should check if the problem comes from the generators or check what the code generated by typescript looks like
