### ISSUE TITLE
Can i make route with asterisk and exception?

### ISSUE THREAD

**Issue by Drezdenozk** [vuejs/vue-router#2402]
### What problem does this feature solve?
For works need something like
'path': '*(exclude something like /static/)'
Yes, really, root asterisk and exception...

### What does the proposed API look like?
*(regExp)

**Comment by posva** [comment]
Yes, you can do that with a regex. But you should always put the star route at the end :)

**Comment by Drezdenozk** [comment]
```
'path': '/(^((?!(static|public|assets|404)).{0,}))*', not working( 
'path': '/*(^((?!(static|public|assets|404)).{0,}))/*', not working too ( 
'path': '/:page(^((?!(static|public|assets|404)).{0,}))/*', not working too ( 
```

must works for all routes except /static, /public, /asset....
