### ISSUE TITLE
route with iframe changes the iframe then the page when hitting back

### ISSUE THREAD

**Issue by smakinson** [vuejs/vue-router#2403]
### Version
3.0.1

### Reproduction link
[https://codepen.io/smakinson/pen/JaVbGv](https://codepen.io/smakinson/pen/JaVbGv)

### Steps to reproduce
Click the first PRESS ME link to move to the page with an iframe.

Notice the iframe and the VAL.

Click the next PRESS ME link.

Notice the iframe and the VAL.

Press the back button.

Notice the iframe and the VAL.

Press the back button again.

Notice the iframe and the VAL.

### What is expected?
Pressing the browser back button would go back to the previous route on the first press, not first affecting only the iframe.

### What is actually happening?
Pressing back in the browser first affects the iframe, then pressing again affects the route.

---
Reference issue: https://github.com/vuejs/vue-router/issues/1699

I came across this bug recently in a project I am working on that uses an iframe for video. I had only noticed the issue in Chrome initially, but the pen seems to show it happening in Firefox and Safari as well.

**Comment by posva** [comment]
I got the chance to look more at this and it seems to be expected behaviour: the browser adds entries to the history when the `src` of the iframe changes, making the back button go back **only inside the iframe**

There are two solutions: add a `key` attribute to replace the whole iframe everytime src changes or use `iframe.contentDocument.location.replace` instead of `src` to change the url of the iframe

**Comment by smakinson** [comment]
Ok, thank you for checking it out. I'll give those solutions a go and see what works best.

**Comment by posva** [comment]
Sure, please tell me back if you find out this isn't enough

**Comment by tasarsu** [comment]
Hi @posva, I had the same problem here.
In my scenario, I have an iframe that is opened in a modal on the page. I define a src attribute at the beginning and some navigation occur in iframe without my control. So there is no way to do iframe.contentDocument.location.replace.

After some navigation in the iframe, with window.parent.postMessage command from the iframe and I close the modal.

When I return to my page, there still urls of iframe exists in history, even if there is no iframe. So if I want to go back, I have to click back too much times.

Is there a way to solve this?

**Comment by germain-receeve** [comment]
Any update on this?
We're facing the exact same issue :/

**Comment by canvascat** [comment]
@germain-receeve You can try using it with `keep-alive`. 😀

```vue
<template>
  <div>
    <iframe src="" ref="iframeRef" v-show="active"></iframe>
  </div>
</template>

<script>
export default {
  data() {
    return {
      active: true,
    };
  },

  activated() {
    this.active = true;
  },

  deactivated() {
    this.active = false;
  },

  mounted() {
    document.documentElement.appendChild(this.$refs.iframeRef);
  },

  beforeDestroy() {
    document.documentElement.removeChild(this.$refs.iframeRef);
  },
};
</script>

<style scoped>
iframe {
  position: fixed;
  z-index: 99;
}
</style>
```
