### ISSUE TITLE
add runtime type-checking & well understood warnings

### ISSUE THREAD

**Issue by Amorites** [vuejs/vue-router#2406]
### What problem does this feature solve?
If we accidentally set `to` prop of router-link to `null`, an error `TypeError: Cannot read property 'name' of null` will be thrown. 

At this line:
https://github.com/vuejs/vue-router/blob/dev/src/util/location.js#L18

There should be a better error message but not just crash and leave users confused.

### What does the proposed API look like?
warn like react

**Comment by posva** [comment]
There is already a warning if the route is null because `to` is a required prop
