### ISSUE TITLE
Vue router opened with nodejs outpus me an error on router.push

### ISSUE THREAD

**Issue by sarmanulco** [vuejs/vue-router#2412]
### Version
3.0.1

### Reproduction link
[https://gist.github.com/sarmanulco/9feab4fe1ea84626bb6ffbe7b65ec93c](https://gist.github.com/sarmanulco/9feab4fe1ea84626bb6ffbe7b65ec93c)

### Steps to reproduce
create a project like in the package json in the gist on the link I have written and run it with nodejs and not in the browser

### What is expected?
In the output should appear:
```
<div>
   <h1>Hola vuex</h1>
   <h1>Foo</h1>
</div>
```

### What is actually happening?
Outputs the error addressed in the gist github

**Comment by posva** [comment]
maybe this is related to how rollup handles the code splitting. I imagine you are following https://ssr.vuejs.org/guide/routing.html#routing-with-vue-router
I don't understand how to run your code but this is too wide, and belongs to the forum or discord server. Come back if you have something more specific 🙂
