### ISSUE TITLE
[Docs] Clearly show how to keep router reference after ajax callbacks

### ISSUE THREAD

**Issue by graham-sportsmgmt** [vuejs/vue-router#2413]
### What problem does this feature solve?
It is unclear how to maintain a reference to the router once "this" changes inside a callback (such as an ajax request)

### What does the proposed API look like?
Please change the "Programmatic Navigation" documentation to show how to declare a variable outside of the callbacks that keep a reference to the router.

**Comment by posva** [comment]
PRs are welcome to improve that 😀
Not sure of what you mean though. We can use fat arrows too inside components
