### ISSUE TITLE
Give the Router plugin a config option

### ISSUE THREAD

**Issue by longrunningprocess** [vuejs/vue-router#2416]
### What problem does this feature solve?
Right now we are required to send in a "configured router" to the instantiation options of the Vue instance, example:

```
import Vue from 'vue';
import router from './plugins/router';
import App from './App.vue';

new Vue({
  router,
  render: h => h(App)
}).$mount('#app');
```
**AND**

we are also required to "`use`" the plugin, example:
```
import Vue from 'vue';
import Router from 'vue-router';
import homeRoutes from '@/home/routes';
import passwordRoutes from '@/password/routes';
import profileRoutes from '@/profile/routes';

Vue.use(Router);

const configuredRouter = new Router({
  mode: 'history',
  routes: [
    ...homeRoutes,
    ...passwordRoutes,
    ...profileRoutes,
    {
      path: '*',
      component: {
        render: h => h('span', 'page not found')
      }
    }
  ]
});

export default configuredRouter;
```

This feels a little redundant to me.

### What does the proposed API look like?
I'm requesting we be able to configure the Router at time of plugin installation, i.e., `Vue.use(Router, options)`, example:
```
import Vue from 'vue';
import Router from 'vue-router';
import homeRoutes from '@/home/routes';
import passwordRoutes from '@/password/routes';
import profileRoutes from '@/profile/routes';

Vue.use(Router, {
  mode: 'history',
  routes: [
    ...homeRoutes,
    ...passwordRoutes,
    ...profileRoutes,
    {
      path: '*',
      component: {
        render: h => h('span', 'page not found')
      }
    }
  ]
});
```

so the `main.js` could look like this:
```
import Vue from 'vue';
import './plugins/router';
import App from './App.vue';

new Vue({
  render: h => h(App)
}).$mount('#app');
```

Developers could save a step in bootstrapping if this were available and I believe it could be done in a backward compatible way.  Vuetify does it this way and it seems like a cleaner approach to me.

Thanks for consideration.

**Comment by posva** [comment]
Both achieve different things actually. Having a router instance should also make things easier regarding typings.
Only having the options would not allow injecting the router in a specific instance
