### ISSUE TITLE
[Docs] HTML5 History Mode Caveat Clarification

### ISSUE THREAD

**Issue by ataylor32** [vuejs/vue-router#2418]
### Version
3.0.1

### Reproduction link
[https://router.vuejs.org/guide/essentials/history-mode.html#caveat](https://router.vuejs.org/guide/essentials/history-mode.html#caveat)

### Steps to reproduce
The documentation correctly states that using history mode and configuring the server with a catch-all fallback route has the caveat that the server will no longer report 404 errors. It says "To get around the issue, you should implement a catch-all route within your Vue app to show a 404 page". In my opinion, that wording implies that implementing a catch-all route within Vue completely fixes the problem. However, with that approach, if a user goes to an invalid URL, the server will respond with a status code of 200 even though the URL is invalid. On some sites (especially dynamic ones), there is a good chance that a URL that is valid today could be invalid tomorrow. Maybe some search engines are smart enough to recognize that it's a "Page Not Found" page and treat it as such rather than a valid URL, but I'm guessing that not all search engines are that smart. I think it's important for developers to be aware of this, so I think it would be a good addition to the "Essentials > HTML5 History Mode >  Caveat" documentation.

### What is expected?
The documentation should mention that the server will respond with a status code of 200 for invalid URLs.

### What is actually happening?
The documentation does not mention this.

**Comment by posva** [comment]
You are more than welcome to submit a proposal for this :)
