### ISSUE TITLE
使用addrouters动态添加路由，无法懒加载

### ISSUE THREAD

**Issue by hushenao** [vuejs/vue-router#2421]
### What problem does this feature solve?
使用addrouters动态添加路由的时候，在添加路由的时候会把所有的路由信息都加载，导致加载慢，有没有方法可以使用懒加载的方式加载动态路由

### What does the proposed API look like?
最好是可以直接通过webpack或者router配置

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
