### ISSUE TITLE
[Docs] Full text search for vue-router docs. 

### ISSUE THREAD

**Issue by nicedaichi3** [vuejs/vue-router#2439]
### What problem does this feature solve?
Hello :)
I'd like to full text search for vue-router docs.  
beforeRouteLeave and others do not hit in header search.  
> VuePress comes with built-in headers-based search - it automatically builds a simple search index from the title, h2 and h3 headers from all the pages.

Would you like to introduce Algolia like a Vuejs document ?  

If you give Algolia's API key specific to this document, I'll fix the code and commit it.  
https://vuepress.vuejs.org/theme/default-theme-config.html#algolia-search  

You have something to worry about, please let me know.   

Thank you.

**Comment by posva** [comment]
Oh yeah, that's something we could add

**Comment by nicedaichi3** [comment]
Hi @posva 
Could you please give me a hint how to get Algolia API Key for this docs.
Probably I think I should process on this refs: https://github.com/vuejs/vuejs.org/issues/575
