### ISSUE TITLE
Feature/request: Access to instance properties inside transition hooks

### ISSUE THREAD

**Issue by tilleps** [vuejs/vue-router#244]
Disclaimer: I'm new to VueJS so I'm not exactly sure where to put and connect things, so any direction is appreciated.

Not sure if this promotes bad practices, but could we get access to the instance properties inside transition hooks (just like we do with lifecycle hooks)?

```javascript
{
  //
  // Lifecycle hooks
  //
  created: function () {
    // instance properties
    console.log(this.$data);
    console.log(this.$root);
    // etc...
  },
  
  //
  //  Transition Hooks
  //
  route: {
    canActivate: function (transition) {
       console.log(this.$data);  // undefined
       console.log(this === window);  // true

       // Feature/request
       console.log(this.$data);  // make accessible like created(), instead of undefined
       console.log(this.$root);  // make accessible like created(), instead of undefined
    }
  }
}

```

I am currently doing this as a workaround:
```javascript
{
  route: {
    canActivate: function (transition) {
      console.log(transition.to.router.app.$root);
    }
  }
}
```

**Comment by yyx990803** [comment]
`canActivate` is called **before** the instance is even created. So it doesn't really make sense to be able to access the instance in there.

You **can** access the instance in the other hooks though.
