### ISSUE TITLE
<router-view> can't render on TV browsers!!!

### ISSUE THREAD

**Issue by 493843643** [vuejs/vue-router#2440]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
i use vue-cli 2.0  to build my project, is rendered success in computer browsers and mobile browsers.
but ! On Android system TV,<router-view> can't render ！
the tv ua is https://share.weiyun.com/5gEBwHc and https://share.weiyun.com/5bbCqxR,
the console is Error{} ,https://share.weiyun.com/5ftBb7K
the dom is https://share.weiyun.com/5hQfR7u!
thanks  very muck!
thanks  very muck!

### What is expected?
- -!

### What is actually happening?
- -!

---
- -!

**Comment by posva** [comment]
I need a repro to check!!!

You probably want to ask in the forums or suscités chat for help first
