### ISSUE TITLE
Watch $route doesn't work on first route update

### ISSUE THREAD

**Issue by geoidesic** [vuejs/vue-router#2446]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/4xfa2f19/19326/](https://jsfiddle.net/4xfa2f19/19326/)

### Steps to reproduce
Click either link.

### What is expected?
This should trigger the watch (which should trigger an alert).

### What is actually happening?
Watch is not triggering on first click, only on subsequent clicks.

---
I've been trying to get watch $route working in my own app with mixed results. It has been incredibly frustrating because I thought it was working, then I thought it wasn't working. I still can't get it to work at all in my larger app, nor on codesandbox.io (e.g. https://codesandbox.io/s/6jv5mrnk1k). However on this more simple JsFiddle I thought at first that it also wasn't working but then noticed that it works on second and subsequent route updates only.

I followed the docs here to build up the example: https://router.vuejs.org/guide/essentials/dynamic-matching.html#reacting-to-params-changes

**Comment by posva** [comment]
Use the `immediate` option for `watch`
