### ISSUE TITLE
Missing libs in build 0.7.6

### ISSUE THREAD

**Issue by blueshed** [vuejs/vue-router#246]
"GET http://localhost:8888/.../jspm_packages/github/vuejs/vue-router@dev/lib/route-recognizer.js 404 (Not Found)"
I've install vue-router with jspm and I'm using system.js.

This problem occurs with the 0.7.6 build as well - version 0.7.5 works fine. 

I have also been unable to get Star Segments to work. I have not seen any in the tests.

**Comment by yyx990803** [comment]
Should be fixed in 0.7.7.
