### ISSUE TITLE
How can I remove the routers were add to VueRouter by addRoutes method

### ISSUE THREAD

**Issue by connie1992** [vuejs/vue-router#2460]
### What problem does this feature solve?
Recently, I am working on a project developed with vue. I used Vue-Router to manage routers.
When I logout system, I want to clear the routers were add to VueRouter by addRoutes method.
Beacuase the routers are calculated by the logined user ,  all the routers data were sented from api.
So when I logout, I want to clear the Dynamic routers except the public path, like home, 404 page etc.

### What does the proposed API look like?
Sorry, I can't found the proposed API

**Comment by connie1992** [comment]
Sorry , I selected a error issue type.

**Comment by Riant** [comment]
Really need that.
