### ISSUE TITLE
Inconsistent formatting with URL for named child route with no path and query params

### ISSUE THREAD

**Issue by BrianBrenner** [vuejs/vue-router#2463]
### Version
3.0.1

### Reproduction link
[http://jsfiddle.net/u3be49g0/](http://jsfiddle.net/u3be49g0/)

### Steps to reproduce
Open the JSfiddle and click the /user/foo link

### What is expected?
The URL should be /user/foo?test=test_param

### What is actually happening?
The URL is /user/foo/?test=test_param

---
This is a valid URL and the query property of $route still works, but the formatting is inconsistent with how query params are handled with other routes in vue router. This occurs only for named child routes with no path since it will automatically append the trailing slash (see https://github.com/vuejs/vue-router/issues/1273).

Maybe this is intended, but it would be nice if query params were handled the same for all routes.

**Comment by kellym** [comment]
+1 to this. In my case, I'd deem this more of a bug because we _can't_ have the trailing slash or else it conflicts with another part of our code.

**Comment by TheDutchCoder** [comment]
We're facing the same issue and it actually breaks our app, because we don't allow trailing slashes in our routes, resulting in a 404 on a reload.

**Comment by adamreisnz** [comment]
Also unhappy about the trailing slashes. The parent route's path is defined as `'foo'`, and the (default) child route's path is defined as `''` (empty string). As such, I expect the route for the child to be `foo`, not `foo/`.

The parent route is abstract, and it is never expected to navigate to it directly. So differentiating between the parent route and the child route should not be needed.

**Comment by adamreisnz** [comment]
Moreover, the explanation in the other issue that this is done to differentiate the parent route from the child route also doesn't make sense, because both routes with and without trailing slash end up going to the child route. So the router *knows* that even without a slash it should load the child route, so why append the slash when navigating to a named route?

**Comment by posva** [comment]
After further investigation, changing this behavior would be a breaking change for some users so it won't happen on v3. It is however already working for Vue 3 to make trailing slash consistent (good for SEO):

- By default no route has a trailing slash
- Trailing slashes can be manually added and enforced with the `strict` option

in v4 the original issue is also fixed: there is no trailing slash by default while you can still access the parent route using a named navigation (`router.push({ name: 'parent' })`) while navigating through a string (from url or `router.push('/parent')`) will always end up on the empty path child
