### ISSUE TITLE
Router is linking invalid Components

### ISSUE THREAD

**Issue by csigmanek** [vuejs/vue-router#2464]
### Version
3.0.1

### Reproduction link
[https://github.com/csigmanek/cspage](https://github.com/csigmanek/cspage)

### Steps to reproduce
Build the project.
Go to
http://localhost:8080/demos/prime-chain
Open file src/router.ts
Comment out
    import UsefulLinks from './views/UsefulLinks.vue';
and

     {
       path: '/useful-links',
       name: 'Useful Links',
       component: UsefulLinks,
     },

Reload the page

### What is expected?
A route configuration should not influence other routes.

When i specify component PrimeChain to be loaded at the path /demos/prime-chain, I do not expect component UsefulLinks to be loaded.

### What is actually happening?
A wrong component is loaded by the router.
Also, the parent element of "App" is called "Useful Links" which is odd i guess. Other Routes do not rename the root element in the vue inspector.

**Comment by posva** [comment]
If you need help with your project please use the forums or chat. When reporting a bug make sure to provide a boiled down repro

**Comment by csigmanek** [comment]
Well I wanted to give you the opportunity to fix that bug. Help in discord is very poor unless you have some basic questions. Haven't tried the forum yet.

Bug seems to be anywhere between the vue-router and the vue-class-component.

I did further research and importing simply <template> components without 
```
<script lang="ts">
import { Vue } from 'vue-property-decorator';
export default class PrimeChain1 extends Vue {}
</script>
```
works. While the script part breaks them (1 component is loaded for multiple routes).

The example in the repo already is boiled down to an almost empty page. And kicking out the 2 libraries vue-i18n and element-ui doesn't change a bit. The routes worked wonderful in all routes till yesterday. So how am i supposed to reproduce it in a new project where probably everything will work?

**Comment by csigmanek** [comment]
Well, if anyone wonders:
'@Component' is required, even when empty or you will get such errors.
i.e.
```
import { Component, Vue } from 'vue-property-decorator';

@Component({
  components: {
  },
})
export default class PrimeChain1 extends Vue {}
```

There might be a reason for that empty import. But I'd expect vue-router or any other instance to warn me when doing this.
