### ISSUE TITLE
Event window.onpopstate is never fired

### ISSUE THREAD

**Issue by nolimitdev** [vuejs/vue-router#2465]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/bjb8ukb8/](https://jsfiddle.net/bjb8ukb8/)

### Steps to reproduce
Set listener for window.onpopstate and navigate through VUE app using VUE router. Event is never fired. Demo: https://jsfiddle.net/bjb8ukb8/ Event popstate works correctly without VUE. Demo: https://jsfiddle.net/bzo67L32/2/

### What is expected?
Event popstate must be fired.

### What is actually happening?
Event popstate is not fired.

---
So when this event is not working there is no possible way to detect that user used back or forward button in browser. And I think VUE and VUE router do not offer any API to check it.

```
var lastHistoryLength = window.history.length;
window.onpopstate = function() {
  if (window.history.length == lastHistoryLength)
      console.log("User used back button");
  lastHistoryLength = window.history.length;
};
```
This code works well in clean javascript website - you can put it into console at e.g. http://example.com/ and then put `location.hash="foo"` and press back button or use `location.history.back()` and in console you will see "User used back button". But this code does not work in website using vue+vue router.

**Comment by posva** [comment]
This is normal, as router links trigger js navigation and not regular browser navigation. That's why it does appear when clicking the back and forward button (https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onpopstate)
