### ISSUE TITLE
something wrong with router.beforeEach when slide back

### ISSUE THREAD

**Issue by Lyanbin** [vuejs/vue-router#2466]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/50wL7mdz/778919/](https://jsfiddle.net/50wL7mdz/778919/)

### Steps to reproduce

```
router.beforeEach((to, from , next) => {
    setTimeout(() => {
        next();
    }, 2000);
});
```

slide back to old page by gesture

### What is expected?
is this a  known issue？how to avoid

### What is actually happening?
when i slide back to old page by gesture,  the current page will flash in view port. that means you can see [old page => current page => old page].

---
it's hard to be observed on the pc or mac, use iphone.

**Comment by posva** [comment]
The repro doesn't work and the reproduction steps are not clear.
If you are talking about safari displaying the previous page, it's how it works and there is nothing we can do to remove it. Maybe in the future they exposé some kind of api for it
