### ISSUE TITLE
Should the type of $route.query.xx be unified into a String type?

### ISSUE THREAD

**Issue by zhangzhengyi12** [vuejs/vue-router#2471]
### What problem does this feature solve?
If I use 
```
this.$router.push({
      name: 'pageB',
      query: {
        money: 100, // number
      }
 })
```
jump to pageB

now 

```
// pageB
export default {
  mounted(){
     console.log(typeof this.$route.query.money)
     // case1 If the page enters as push, then the output is [number]
     // case2 If this page B is refreshed, then the output is [string]
  }
}
```
Since the requery type cannot be retrieved from the current URL when re-entering the page，
So should the type of the unified parameter always be string to avoid some unnecessary type problems?

using Google Translate Thanks

### What does the proposed API look like?
Uniform parameter type is String

**Comment by posva** [comment]
IMO yes, they should always be casted to strings to make things consistent

**Comment by tesla3327** [comment]
Related to #2131

**Comment by posva** [comment]
Let's close this in favour of #2131 . We should allow numbers and string for convenience but cast things to strings for consistency
