### ISSUE TITLE
TypeError: this._router.init is not a function

### ISSUE THREAD

**Issue by shrinisudi** [vuejs/vue-router#2472]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/w26279rw0l](https://codesandbox.io/s/w26279rw0l)

### Steps to reproduce
Open the code sandbox and inspect the console.

### What is expected?
No errors in the console.

### What is actually happening?
There is an error saying this._router.init is not a function.

---
While the app itself is rendering fine, I am not sure what consequences this might have once the app gets complicated. I just wanted to bring this to your attention.

**Comment by haoqunjiang** [comment]
It's due to the `router` field in your `Home` component… `vue-router` uses this field to inject the `VueRouter` instance, so you are not expected to put any arbitrary data into it.

**Comment by shrinisudi** [comment]
That fixed it. I'll close the issue. Thank you!!

**Comment by nabeeltahir785** [comment]
In router.js file used this 
export default router
