### ISSUE TITLE
$router.options.routes are not reactive

### ISSUE THREAD

**Issue by yene** [vuejs/vue-router#2474]
### Version
3.0.1

### Reproduction link
[http://example.org/](http://example.org/)

### Steps to reproduce
Declare page title inside a route.meta.
```
  {
    path: '/device/:id',
    component: Device,
    meta: {
      title: 'Device',
      sidebar: false,
    }
  },
```

use the page title in template
`{{route.meta.title}}`

update page title in mounted()
`this.$route.meta.title = 'test'`

### What is expected?
that 'test' is rendered

### What is actually happening?
The page title does not change.

**Comment by posva** [comment]
Router options are not reactive. This is on purpose. That being said meta shouldn't be used as a reactive source either
