### ISSUE TITLE
Can Vue accept http Post Request?

### ISSUE THREAD

**Issue by kmshelke** [vuejs/vue-router#2480]
### What problem does this feature solve?
I am using Vue JS application which needs Payment Gateway integration. The Payment Gateway, after processing the payment, will send a post response to the return url of the application. 

I am getting 405 Method not allowed error when the response from the payment gateway returns the control back to the application.

How should I handle the Post Response  for the url path of Vue application.

Thanks & Regards,

Kuldip Shelke

### What does the proposed API look like?
I should be able to access the VueJS application using http Post method.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by marcicocha** [comment]
> 

How did you resolve this? I currently have a similar problem
