### ISSUE TITLE
in windows browser(chrome,ie,edge,firefox), refresh page, then router leave and route to /

### ISSUE THREAD

**Issue by realfly08** [vuejs/vue-router#2482]
I have build a web app by vuejs with vur-router.

my router/index.js is below:
![image](https://user-images.githubusercontent.com/14865594/48602256-7e288980-e9ad-11e8-8bc4-9856bcc059a5.png)

after build the app, it can be run under nginx server well.
**But when I open a page is not '/home' (such as '/myLadings') in any browser in windows platform, then refresh this page , the router will be route to the route path '/', then to '/home'.**

But this will not happen in mac or other linux platform.

**Comment by wghust** [comment]
yeah，I have the same problem in windows system. when open in new window，it will redirect to default page.
