### ISSUE TITLE
【bug】在webpack chunk 配置下Vue  Global Mixins 与 非chunk 配置下表现不一致的问题 

### ISSUE THREAD

**Issue by cys85** [vuejs/vue-router#2487]
### Version
3.0.1

### Reproduction link
[https://github.com/cys85/vue-router-chunk-global-mixin-bug-demo](https://github.com/cys85/vue-router-chunk-global-mixin-bug-demo)

### Steps to reproduce
在 https://github.com/cys85/vue-router-chunk-global-mixin-bug-demo 中可复现
代码采用 vue 3.0 脚手架生成，移除了部分 干扰因素。

依赖：
```
"dependencies": {
    "vue": "^2.5.17",
    "vue-class-component": "^6.0.0",
    "vue-property-decorator": "^7.0.0",
    "vue-router": "^3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.0",
    "@vue/cli-plugin-typescript": "^3.0.0",
    "@vue/cli-service": "^3.0.0",
    "typescript": "^3.0.0",
    "vue-template-compiler": "^2.5.17"
  },
```

### What is expected?
虽然不同配置，最终功能应该表现一直，但是目前表现不一致
我现在不确定两种不一致，哪种是正确的。

### What is actually happening?
在路由懒加载并且对应view有混入的情况下，vue全局 混入 对于当前视图会被多次执行，但是 在非路由懒加载并且对应view有混入的情况下，vue全局 混入 对于当前视图只执行一次。

- 路由懒加载并且对应view有混入的情况：

路由配置：
![image](https://bucket-cys.oss-cn-beijing.aliyuncs.com/images/WX20181119-132525.png?Expires=1542608767&OSSAccessKeyId=TMP.AQFZF6_joozG-K3KzYDOa-anE4U8_ulYisVTmQfP-HGdHYE1Scgf5N7ReGYqAAAwLAIUK4g2Ke5idMTI09B1PGCKU2p4td8CFCI_-6NuarxMW2AJo4deShvKNblQ&Signature=tzyOHKiW%2BZR2xAA5hqta1pETxPY%3D)

视图：
![image](https://bucket-cys.oss-cn-beijing.aliyuncs.com/images/222.png?Expires=1542608903&OSSAccessKeyId=TMP.AQFZF6_joozG-K3KzYDOa-anE4U8_ulYisVTmQfP-HGdHYE1Scgf5N7ReGYqAAAwLAIUK4g2Ke5idMTI09B1PGCKU2p4td8CFCI_-6NuarxMW2AJo4deShvKNblQ&Signature=wGubTp8VnY%2BKIixZ5OwHva2hfXs%3D)

全局混合：
![image](https://bucket-cys.oss-cn-beijing.aliyuncs.com/images/333.png?Expires=1542608964&OSSAccessKeyId=TMP.AQFZF6_joozG-K3KzYDOa-anE4U8_ulYisVTmQfP-HGdHYE1Scgf5N7ReGYqAAAwLAIUK4g2Ke5idMTI09B1PGCKU2p4td8CFCI_-6NuarxMW2AJo4deShvKNblQ&Signature=QQDVqUEKIxTYc9SSYwWn4Z4wA38%3D)

输出
![image](https://bucket-cys.oss-cn-beijing.aliyuncs.com/images/444.png?Expires=1542609221&OSSAccessKeyId=TMP.AQFZF6_joozG-K3KzYDOa-anE4U8_ulYisVTmQfP-HGdHYE1Scgf5N7ReGYqAAAwLAIUK4g2Ke5idMTI09B1PGCKU2p4td8CFCI_-6NuarxMW2AJo4deShvKNblQ&Signature=ucMf8hIAu%2FYJAiEIxUy8%2BoQUCEM%3D)

- 路由非懒加载并且对应view有混入的情况：

路由配置：
![image](https://bucket-cys.oss-cn-beijing.aliyuncs.com/images/555.png?Expires=1542609434&OSSAccessKeyId=TMP.AQFZF6_joozG-K3KzYDOa-anE4U8_ulYisVTmQfP-HGdHYE1Scgf5N7ReGYqAAAwLAIUK4g2Ke5idMTI09B1PGCKU2p4td8CFCI_-6NuarxMW2AJo4deShvKNblQ&Signature=ooMEKfKPK3gMkc6me%2FSB8BMyVfk%3D)

输出：
![image](https://bucket-cys.oss-cn-beijing.aliyuncs.com/images/1542605927774.jpg?Expires=1542609547&OSSAccessKeyId=TMP.AQFZF6_joozG-K3KzYDOa-anE4U8_ulYisVTmQfP-HGdHYE1Scgf5N7ReGYqAAAwLAIUK4g2Ke5idMTI09B1PGCKU2p4td8CFCI_-6NuarxMW2AJo4deShvKNblQ&Signature=L7u9zJ%2BraCVmlsRQeE1zpNcJ3Kg%3D)

---
typescript

**Comment by posva** [comment]
This is too much for a repro. Typescript shouldn't be there. Also, if you manage to boil it down, please, post the issue in English
