### ISSUE TITLE
Add "background-color: white" to router website

### ISSUE THREAD

**Issue by murilobd** [vuejs/vue-router#2489]
### Version
3.0.1

### Reproduction link
[https://screenshots.firefox.com/nTTnRBT96v1QXEH6/router.vuejs.org](https://screenshots.firefox.com/nTTnRBT96v1QXEH6/router.vuejs.org)

### Steps to reproduce
I using OS Fedora 29 with dark theme and, because of the lack of background-color style in body, it's hard to read

### What is expected?
White background in website

### What is actually happening?
Takes the color from OS (black, in my case)

---
Just add a "background-color: white" to the ```<body>``` tag and that's it

**Comment by posva** [comment]
This is related to vuepress not to vue-router. You can open an issue there
