### ISSUE TITLE
问一个问题

### ISSUE THREAD

**Issue by xingyuefa** [vuejs/vue-router#2491]
现在有一个组件 内部实现是可以传入slot参数的，现在把他用在了<router-view/>中去匹配路径，我该怎么做才能把slot传给这个组件，因为直接在<my-component><div slot=''hello">hello</div></my-component>中我可以这样做，但是用在router匹配中，我就不知道该如何做了，请专业人士帮我解答一下这个问题

**Comment by hasbug** [comment]
不是很明白，但除了通过路由的query传参去实现，貌似没有更贴切的答案了。
