### ISSUE TITLE
querystring和锚点位置问题

### ISSUE THREAD

**Issue by nymlc** [vuejs/vue-router#2492]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/lc642539059/eywraw8t/469850/](https://jsfiddle.net/lc642539059/eywraw8t/469850/)

### Steps to reproduce
根据一个已有的带querystring的url eg: http://localhost:8080/process/page/instance/detail?processInstanceId=2429&type=1
因为前端路由配置，
```javascript
routes: [{
        path: '/',
        redirect: '/index'
    },{
            path: '/agree',
            name: 'agree',
            component: () => import('@/views/mobile/agree.vue'),
        }]
```
呈现出来的情况是http://localhost:8080/process/page/instance/detail?processInstanceId=2429&type=1#/index

这时候跳转/agree
```javascript
this.$router.push({
                    path: 'agree',
                    query: {
                        processInstanceId: this.processInstanceId
                    }
                })
```
url变成http://localhost:8080/process/page/instance/detail?processInstanceId=2429&type=1#/agree?processInstanceId=2429
页面无法成功跳转
这种情况怎么办呢

### What is expected?
页面成功跳转

### What is actually happening?
页面无法成功跳转

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
