### ISSUE TITLE
Current route's query unaccessible on the App's created hook when using lazy loaded routes

### ISSUE THREAD

**Issue by ThomasFerro** [vuejs/vue-router#2495]
### Version
3.0.2

### Reproduction link
[https://codesandbox.io/s/7mmqoqz18j](https://codesandbox.io/s/7mmqoqz18j)

### Steps to reproduce
- Start a new vue-cli 3 project with vue-router
- In the App.vue component, add this created hook :

```
created() {
  console.log('created', this.$route.query, this.$route.query && this.$route.query.test);
},
```

- Run the application using the url `http://localhost:8080/#/about?tiers=tezst`

### What is expected?
The query should be present in the `this.$route` object.

### What is actually happening?
It is not.

---
Sorry but I cannot get vue-router working on the online IDEs.

I think this is due to the lazy loading because it does works however when calling the home page `http://localhost:8080/#/?tiers=tezst`.

**Comment by posva** [comment]
Was this working in the previous version? I'm having a hard time reproducing with an older version with code sandbox and I cannot test very well

**Comment by ThomasFerro** [comment]
Hi, I don't know if it worked before but I can send you a minimalist project where the issue is reproduced ?

**Comment by posva** [comment]
no, don't worry. Now that I'm home I can check it on a computer 😄

**Comment by posva** [comment]
What's happening is that because the route is lazy loaded, we need to wait for it and its navigation guards before actually triggering the navigation, so when we land on the `/`, we are still not in the actual `/` route during the created hook, so the `$route` property isn't up to date. If you change the path of the lazy loaded route to something like `/no`, you will see that the `$route` object still contains `/` (this should help visualise what is actually happening)

**Comment by ricardocastanho** [comment]
I'm having this problem. @ThomasFerro how did you workaround this problem?

**Comment by ThomasFerro** [comment]
@ricardocastanho It's been a few years, I cannot remember how we managed to workaround the issue. We may have [watched the `$route`  object](https://router.vuejs.org/guide/essentials/dynamic-matching.html#reacting-to-params-changes).

**Comment by ricardocastanho** [comment]
Funny part is that logging at App.vue doesn't work at all, but logging in the lazy loaded component it works like a charm 😅.

![image](https://github.com/vuejs/vue-router/assets/48383095/21563243-6876-4f40-8ca8-1ed3f3d3d8ff)

My workaround is moving the logic to the route's component.
