### ISSUE TITLE
Pushback for not-root urls does not work

### ISSUE THREAD

**Issue by windows1087** [vuejs/vue-router#25]
I have the following url for my project: `http://localhost:1337/project/public`

If i declare my routes with this schema: 

```js
router.map({
  '/test': {
    component: 'test'
  },

  '/other': {
    component: 'other'
  }
});
```

and my navigation:

```
<a v-link="/test">TEST</a>
<a v-link="/other">OTHER</a>
```

it redirects me to `http://localhost:1337/other`. So, if i change the routes wit `./`, it works with my url, but when i go back in browserhistory, nothing happens in my view:

```js
router.map({
  './test': {
    component: 'test'
  },

  './other': {
    component: 'other'
  }
});
```

```
<a v-link="./test">TEST</a>
<a v-link="./other">OTHER</a>
```

**Comment by yyx990803** [comment]
You can pass in the `root` options:

``` js
var router = new Router({
  root: '/project/public'
})
```
