### ISSUE TITLE
isError only identifies literal errors when extending Error and targeting IE

### ISSUE THREAD

**Issue by michaeldjeffrey** [vuejs/vue-router#2509]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/o8v2plnoz](https://codesandbox.io/s/o8v2plnoz)

### Steps to reproduce
Make a custom error using the class-extends syntax.
Throw error during a route transition.

### What is expected?
Error is caught and sent to Router.onError handler.

### What is actually happening?
Error is being identified as a plain object.

---
Have a custom error to carry notifications with uncaught errors in an application. 
No notifications were showing up in production where we support IE11. 
The custom error correctly identifies as an instanceof Error, but the util/isError function deems it an object.

I'm currently using some snippets from https://github.com/onury/custom-error-test to get the Error prototype on my custom error.

**Comment by posva** [comment]
Codesandbox doesn't work on IE11...
Anyway, I tested using babel: https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEByCmB3AogJ1Qe1deAPALvAHYAmMam2A3gL5A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=

```js
class NewError extends Error {}
```

and our `isError` function works properly to detect errors. Maybe you are not configuring babel correctly

**Comment by michaeldjeffrey** [comment]
You are correct. I updated my babel packages and everything works fine now. 
I must have been in that weird error vortex where I did the same thing on the babeljs website and it wasn't working for me. But today, lo and behold. 

Thanks, and sorry @posva
