### ISSUE TITLE
Ability to execute code "really" `afterEach`

### ISSUE THREAD

**Issue by paulstraw** [vuejs/vue-router#251]
I might be totally missing something here, but it seems like in the following setup, there's no (good) way to "really" find out when each transition has completed (for instance, to have global loading indicators).

``` javascript
var Ajaxy = Vue.extend({
    template: '<div>Some ajaxy things happen in here, supposedly.</div>',
    route: {
        activate: function(transition) {
            return this.$http.get 'a-page', function(res) {
                this.data = res;
            }
        }
    }
});

var router = new VueRouter();

router.map({
    '': {
        component: Foo
    },
    'ajaxy': {
        component: Ajaxy
    }
});

router.beforeEach(function(transition) {
    router.app.loading = true;
    transition.next();
});

router.afterEach(function() {
    // this fires before the component's route `activate` is resolved'
    router.app.loading = false;
});
```

I understand this is the currently expected behavior, but it would be super useful to be able to have a "true" after. I just had a really quick look, but if I'm not mistaken, it should be relatively easy to drop something into [_postTransition](https://github.com/vuejs/vue-router/blob/09af0b297a3b4b4b90d4c91eb635720158d13f27/src/index.js#L507) that works basically the same as when the `_afterEachHooks` are called in `_onTransitionValidated`. This could possibly be exposed as `postEach`? I'd be happy to take care of this and submit a PR, or however you want it handled!

**Comment by zcoding** [comment]
Question: I'd like to scroll window to the top, and i think i should do this after my data hook is resolved because my page shows a large number of data. But i don't know how to do. :joy:
Is my question similar to this issue? :confused:

**Comment by anishdcruz94** [comment]
1+

**Comment by pibo** [comment]
I also would like to have global loading indicators inside my app (dynamically apply the class "loading" to the body, for example). As far as I know, there is no good way of passing the value of $loadingRouteData from a loading component to the root.

**Comment by Chiefo** [comment]
**EDIT**: Nevermind. It's clear vue-router will be updated for Vue 2 and the transition API is being changed.

**Comment by jasonbodily** [comment]
I believe this is still a problem in Vue 2 and VueRouter.
