### ISSUE TITLE
router-link doesn't work correctly when rendered within a functional component

### ISSUE THREAD

**Issue by deepkolos** [vuejs/vue-router#2513]
### Version
3.0.1

### Reproduction link
[https://github.com/deepkolos/vue-router-link-bug-demo](https://github.com/deepkolos/vue-router-link-bug-demo)

### Steps to reproduce
![router-link-bug.gif](https://upload-images.jianshu.io/upload_images/252050-56ab6f579680300d.gif?imageMogr2/auto-orient/strip)

### What is expected?
when come back router-link's classList is "f-link default-link" as it's inital state

### What is actually happening?
router-link's classList become empty

**Comment by posva** [comment]
Could you put that into a code sandbox so I can check please?

**Comment by deepkolos** [comment]
@posva https://codesandbox.io/s/github/deepkolos/vue-router-link-bug-demo

**Comment by posva** [comment]
`class` is a bit different from other `attrs`, set it in `staticClass` when calling `h` instead of adding it to `attrs.class`

```js
staticClass: `f-link ${staticClass}`,
```
