### ISSUE TITLE
Inside guards, get to know current navigating is under router.replace or router.push.

### ISSUE THREAD

**Issue by masquevil** [vuejs/vue-router#2515]
### What problem does this feature solve?
when doing `router.replace('url')`, `next('otherUrl')` will cause this navigation become `router.push`.

when doing `router.push('url')`, `next({..., replace: true})` will cause this navigation become `router.replace`.

want to know current navigating statue inside guards to solve this problem.

### What does the proposed API look like?
```javascript
beforeEach: (to, from, next, infos) => {
  console.log(info.replace)    // true or false
}
```

or:

```javascript
beforeEach: (to, from, next) => {
  console.log(to.replace)    // true or false
}
```

**Comment by posva** [comment]
This is intended and it will propably go under the location params to and from instead of an extra argument.
I cannot search for the issue right now but this has been asked before and it's being tracked so closing as a duplicate

**Comment by GuoQichen** [comment]
Does this have any solution ? @posva

**Comment by iamahuman** [comment]
Duplicate of #1620
