### ISSUE TITLE
beforeRouteEnter next callback cannot return next(false)

### ISSUE THREAD

**Issue by medmin** [vuejs/vue-router#2516]
### Version
3.0.2

### Reproduction link
[https://github.com/whizjs/netlify-identity-demo-vue/blob/master/src/components/Protected.vue#L21](https://github.com/whizjs/netlify-identity-demo-vue/blob/master/src/components/Protected.vue#L21)

### Steps to reproduce
https://github.com/whizjs/netlify-identity-demo-vue/blob/master/src/components/Protected.vue#L21

Change the code on Line 21 to "return next(false);" or "return false;"  the router will proceed even the user is not logged in.

It's very easy to reproduce this bug.

### What is expected?
I need the unauthenticated guest to stay in the current page, not redirect to home or any other page. 

### What is actually happening?
Change the code on Line 21 to "return next(false);" or "return false;"  the router will proceed even the user is not logged in.

**Comment by posva** [comment]
When reporting a bug, please provide a boiled down runnable repro (in a jsfiddle or codesandox). Closing until a valid repro is provided

**Comment by medmin** [comment]
Just git clone the repo and change one single line of it and you can reproduce the bug.

What else do you expect me to provide ?

**Comment by leoyli** [comment]
@medmin, did you read the reply...? he said using jsfiddle or codesandbox, which is easier and safer for people to inspect your code.  Also, your code is problematic, you should read the [doc](https://router.vuejs.org/guide/advanced/navigation-guards.html#global-guards); `next` is not accept a callback function in your use case.
