### ISSUE TITLE
What is the proper way to use router.go in a vue component?

### ISSUE THREAD

**Issue by vedraan** [vuejs/vue-router#252]
This is an example of how most of my components use redirection right now:
```js
var Login = Vue.extend({
    template: require('./template.html'),
    methods: {
        onSubmit: function() {
            // Do some stuff here
            this.$route.router.go('/somewhere-else');
        }
    }
});
```
It works, but is ` this.$route.router.go` the right way to do it?

The documentation lacks an example of how to use it in a component:
http://vuejs.github.io/vue-router/en/api/go.html

It might be a good idea to include an example since I had to dig through the `$route` object to find the `router.go` method.

**Comment by yyx990803** [comment]
Yeah, might be easier to just expose `this.$router` directly in the future.

**Comment by yyx990803** [comment]
`this.$router` will be directly available in next release.

**Comment by GitYong** [comment]
I tried both 'this.$router.router.go' and 'this.$route.router.go', I got undefined error for both methods: 'ManageView.vue?1fff:56 Uncaught TypeError: Cannot read property '$route' of undefined'. Is therr any update on this?

**Comment by azamat-sharapov** [comment]
It's `this.$router.go()`.
But your error is for something else, it says `this` isn't available.

**Comment by GitYong** [comment]
I figured this out. It was the es6 arrow function scope issue.

**Comment by iamhabbeboy** [comment]
Guys help me, am having issue with vue router, i am unable to use selector for template.like
`var home = Vue.extend({
  template: '#homeView'
})`
This is not working but working with
`var home = Vue.extend({
  template: '<div>Home Template</div>'
})`

**Comment by yanlee26** [comment]
need more available examples...

**Comment by liufuyang** [comment]
for vue 2.0 do: `this.$router.push('/about')` instead of using `this.$router.go()`
https://router.vuejs.org/en/essentials/navigation.html

**Comment by kevinreytabada** [comment]
it gives me an error => "Cannot read property '$router' of undefined" @liufuyang

**Comment by kevinreytabada** [comment]
it gives me an error => "Cannot read property '$router' of undefined"

**Comment by felipe-augusto** [comment]
You probably have the wrong `this`, make sure to hold the reference:
```js
mounted() {
  // keep reference
  let self = this

  Service.perform.then(function () {
    // the *this* here refers to the function
    self.$router.push('/about')
  })

  // or use arrow function to keep the same *this*
  Service.perform.then(() => {
    this.$router.push('/about')
  })
}
```

**Comment by zugende** [comment]
@felipe-augusto Thanks, your solution works perfectly fine. 👍

**Comment by webhacking** [comment]
`this.$router` give to me this error

Cannot read property '$router' of undefined

**Comment by webhacking** [comment]
In my case, it's like using an anonymous function.

**Comment by regalstreak** [comment]
```this.$router.go("/somewhere-else")```
changed to 
```this.$router.push("/somewhere-else")```
in recent vue versions

**Comment by Rhyanz46** [comment]
import router in your component 
`import router from '../router'`
and use that like this 
`router.replace('home')`

my full code example : 
<script>
import router from '../router'
export default {
  methods: {
  signIn: function () {
    firebase
    .auth().signInWithEmailAndPassword(this.email, this.password).then(
      function (user) {
        router.replace('home')
      },
      function (err) {
        alert('Sorry, ' + err.message)
      }
    )
  }
 }
}
</script>

**Comment by Rhyanz46** [comment]
import router in your component 
`import router from '../router'`
and use that like this 
`router.replace('home')`

my full code example : 
`<script>`
`import router from '../router'`
`export default {`
`  methods: {`
`  signIn: function () {`
`    firebase`
`    .auth().signInWithEmailAndPassword(this.email, this.password).then(`
`      function (user) {`
`        router.replace('home')`
`      },`
`      function (err) {`
`        alert('Sorry, ' + err.message)`
`      }`
 `   )`
`  }`
 `}`
`}
`</script>`

**Comment by Rhyanz46** [comment]
import router in your component 
`import router from '../router'`
and use that like this 
`router.replace('home')`

more : https://stackoverflow.com/a/52595926/8197537

**Comment by eRendon** [comment]
@Rhyanz46 Thanks, your method solved my error!
