### ISSUE TITLE
keep-alive can not cache two router-view

### ISSUE THREAD

**Issue by spencer17x** [vuejs/vue-router#2523]
### Version
2.5.1

### Reproduction link
[https://github.com/xuzpeng/vue-sell.git](https://github.com/xuzpeng/vue-sell.git)

### Steps to reproduce
The order page and home page switch pages are not cached, or the home page -> find page -> order page -> home page still occurs.

### What is expected?
Order page and home page are cached

### What is actually happening?
not cached

**Comment by LinusBorg** [comment]
Without having run the reproduction, it seems like you should set a `key`.
```html
<keep-alive>
  <router-view v-if="$route.meta.keepAlive" key="A"/>
</keep-alive>
<router-view v-if="!$route.meta.keepAlive" :key="B"/>
```

**Comment by xuzpeng** [comment]
I have tried it, but it has the same question.

**Comment by spencer17x** [comment]
@LinusBorg  I have tried it, but it has the same question.

**Comment by posva** [comment]
Please boil down the repro to the minimal when reporting a bug, this is your whole project. You can use codesandbox or jsfiddle.net to easily share something
