### ISSUE TITLE
Optional dynamic routing parameters in documentation

### ISSUE THREAD

**Issue by innocentdiaz** [vuejs/vue-router#2525]
### What problem does this feature solve?
It aims to solve the lack of documentation on optional parameters when performing dynamic route matching. At the moment, the documentation for dynamic route matching does NOT show that you have the ability to make your params optional with the '?' character. Example:
```
    {
      path: '/blog:id?', // optional parameter. this feature is not shown in the documentation
      name: 'blog',
      component: Blog,
    },
```

### What does the proposed API look like?
https://router.vuejs.org/guide/essentials/dynamic-matching.html#reacting-to-params-changes is updated to show this feature

**Comment by LinusBorg** [comment]
We *do* mention it briefly in the secion where we link people to the docs of pathtoregexp (which is the lib we use for this, and which allows for other advanced stuff as well):

https://router.vuejs.org/guide/essentials/dynamic-matching.html#catch-all-404-not-found-route

An example demonstrating it might be useful though.

**Comment by posva** [comment]
Yeah, that's true, I just marked it as docs because there are a lot of things I want to improve in docs and this way I don't forget about some

**Comment by fourpixels** [comment]
👍

**Comment by posva** [comment]
See https://github.com/vuejs/vue-router/pull/3229#issuecomment-667918861
