### ISSUE TITLE
utility function to update the query

### ISSUE THREAD

**Issue by ppvy** [vuejs/vue-router#2526]
### What problem does this feature solve?
have a search function in my project, implemented with query, and then props in an id query, needs to be updated query.id ，don't need to remove the query for the search

### What does the proposed API look like?
`queryUpdate({id: xxxxxxx})`

Look at the ` iss ` before
```
 let query = Object.assign({}, $route.query)
query.id = xxxxxxxxxx
this.$router.push({ query: query })
```

Using a lot of them in a project can be cumbersome

**Comment by posva** [comment]
This is something I thought about many times. The function should also remove query parameters if they are falsy and this should also be customizable.

The thing is there are multiple possible apis and I'm not sure which one should be used:

```js
updateQuery({ foo: true }) // keeps any existing query ✅
updateQuery({ foo: false }) // removes foo but keep everything else
// same for falsy values 0, null, undefined
// but it could also be remove with null/undefined only
// right now router.push({ query: { foo: null }}) yields ?foo while it removes the parameter if the value is undefined
```

**Comment by yoonasy** [comment]
very thank you @posva

**Comment by iamdhj** [comment]
You could use `router.replace` It acts like `router.push`

**Comment by yoonasy** [comment]
@posva    Whether you can use the second parameter to decide whether to merge or delete

But controlling one of the query parameters is tricky

`updateQuery({foo : false}, { null_delete: true })`

or 

`updateQuery({ foo: false }, { null_delete: ['foo', 'baz'] })`

or

`updateQuery({ foo: false }, { retain_query: ['foo'] })`

It looks a little more complicated and maybe a little easier to use

The default value should be merge

**Comment by posva** [comment]
I think this is something that should be handled in user land because in most scenarios it's only `$router.push({ query: {...$route.query, newThing: value }})`
