### ISSUE TITLE
next() callback is not executed under beforeEnter

### ISSUE THREAD

**Issue by waqas385** [vuejs/vue-router#2529]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/waqas385/pvqz8s6u/](https://jsfiddle.net/waqas385/pvqz8s6u/)

### Steps to reproduce
in beforeEnter(to, from, next) under next-callback i used code:
next(vm => { console.log(vm, 'this line wont be called'));

next callback is not called.

goto link (https://jsfiddle.net/waqas385/pvqz8s6u/)

- Click button "Goto Test"
- Click button "Goto Home"
- See console log

In above example I tried to get 'this' but found an unusual behavior 

### What is expected?
I believe next callback should call and this should be also be available

### What is actually happening?
next callback function will not call

---
Let me know, if I miss-understood beforeEnter

**Comment by posva** [comment]
Only beforeRouteEnter call the callback passed to next

**Comment by waqas385** [comment]
Roger!
