### ISSUE TITLE
Routing to same url should fire event

### ISSUE THREAD

**Issue by plehnen** [vuejs/vue-router#2530]
### What problem does this feature solve?
I need to update the current page (request new data from server) whenever the link in the navigation or breadcrumb is clicked. (like it is implemented on amazon)

Currently the `router-link` will do absolutely nothing when clicked, while already being on the target page.
Neither `beforeRouteUpdate` or `router.beforeEach` are triggered.
But it would be nice to be able to notice a route request to the same route.

### What does the proposed API look like?
Maybe a `beforeRouteReload` hook, which returns `false` per default and does nothing (as it is now), but when it returns `true` the normal events get fired and I can handle them.

Or a global parameter which allows me to enable events even if `from` and `to` are the same. Ideally on route level, individually for each route.

**Comment by posva** [comment]
Closing in favour of #974
