### ISSUE TITLE
Unexpected bahaviour on scrollBehavior

### ISSUE THREAD

**Issue by ashnamuh** [vuejs/vue-router#2533]
### Version
3.0.1

### Reproduction link

```js
export default new Router({
  mode: 'history',
  routes: [
    {
      path: '/bulletins/:id',
      name: 'bulletin',
      component: () => import('@/views/Bulletin.vue')
    },
    {
      path: '/bulletins',
      name: 'bulletins',
      component: () => import('@/views/Bulletins.vue')
    }
  ],
  scrollBehavior (to, from, savedPosition) {
    if (savedPosition) {
      return savedPosition
    } else {
      return { x: 0, y: 0 }
    }
  }
})
```

```js
<router-link :to="`bulletins/${bulletin.id}`" tag="div">
{{bulletin.title}}
</router-link>
```

### Steps to reproduce
click <router-link> in nfinite scroll page.
click browser history back button

### What is expected?
Auto-move to Y position scroll of previous page when i click browser history back button.

### What is actually happening?
Auto-move to wrong Y position scroll

---
I have a infinite scroll pagination site that show bulletins. if i click a bulletin title, it move to bulletin detail page. The bulletin title is made with `<router-link>`. And i click browser history back button in bulletin detail page. But it move to wrong Y position scroll of previous page. What is wrong? Is there any idea? 

And i got one more thing. If i paste the url of detail bulletinpage in the pagination page to browser's url input form and click browser history back button, it work correctly.

**Comment by posva** [comment]
You will have to handle this yourself by delaying the scrollBehaviour scroll until the infinite scroll has charged. You can check https://router.vuejs.org/guide/advanced/scroll-behavior.html#async-scrolling
For infinite scroll, you could also save how many elements where loaded to do a new request, but this should be asked in the proper channels 😉
