### ISSUE TITLE
希望能够在监听路由变化时获取到导致当前路由变化的action

### ISSUE THREAD

**Issue by axel10** [vuejs/vue-router#2535]
### What problem does this feature solve?
在Watch$route变化的时候并没有相应的api来告诉开发者是push、pop还是replace导致当前路由变化，这样会对路由动画组件的制作造成极大不便。

### What does the proposed API look like?
当获取到新的$route对象后，添加action字段：
$route.action = "PUSH"
$route.action = "POP"
$route.action = "REPLACE"

**Comment by posva** [comment]
This is already in our roadmap. Please, do no open issues in Chinese, I don't speak Chinese :)
