### ISSUE TITLE
Router push does not seem to work for dynamically generated query.

### ISSUE THREAD

**Issue by asolopovas** [vuejs/vue-router#2536]
### Version
3.0.2

### Reproduction link
[https://codesandbox.io/s/3131mjz155](https://codesandbox.io/s/3131mjz155)

### Steps to reproduce
In the codesandbox if you click on one of the table title it should add the query to the url, but it doesn't unless the object is hard defined. If you look at the method sort in BaseList.vue you will see the variable query and queryB, they are almost identical appart from that one is hard typed the other one is dynamic.

### What is expected?
 If I execute this.$router.push({query: query}) it doesn't not work

### What is actually happening?
 If I execute this.$router.push({query: queryB}) it does work

---
I tried comparing objects by JSON.stringify and it confirms that both objects seem to be almost identical but for some reason router refuses to push the one which is dynamically generated.

**Comment by posva** [comment]
`$route.query` is readonly, make sure to create copies: `this.$set(this, "queryParams", {...this.$route.query});`

**Comment by asolopovas** [comment]
@posva Thanks for the fix. I understand that it is readonly but why this is a problem? I am not trying to right into it? Whats the reason behind such behaviour?

**Comment by posva** [comment]
Basically your queryParams was also readonly because it was the same object so modifications were not working.

Cheers

**Comment by asolopovas** [comment]
Ok now I understand. Basically by creating a reference from a locked object to my prop on creation I have locked that prop.
