### ISSUE TITLE
application as node_module fails to resolve components or lazy chunks. 

### ISSUE THREAD

**Issue by EvanBurbidge** [vuejs/vue-router#2539]
Version
3.0.2

Steps to reproduce
Create two vue cli applications
In app 2 replace router.js with this const Home = () => import(/* webpackChunkName: 'app2.home '*/'./views/Home.vue');
export default [
  {
    path: '/app2',
    name: 'app2.home',
    component: Home,
  },
];
add an index.js at the top level of the project along side main.js and router.js ` import routes from './router';
export default routes;

4. add this line to package.json ``` "lib": "vue-cli-service build --target lib --name tp2 ./src/index.js"
Install it as a node_module into app 1.
import routes from 'tp2'; ` import routes from 'tp2/dist/tp2.common';
export default new Router({ mode: 'history', base: process.env.BASE_URL, routes: [ { path: '/', name: 'home', component: Home, }, ...routes, ], }); `

What is expected?
When I navigate to /app2 and load in the components from app2, which is an npm package, pre compiled it should lazily load the chunk from node_modules.

What is actually happening?
I write a vuejs library that includes a vue router instance. when I import a component non lazily e.g. import Component from 'views'. It works

When I try to lazy load a component into the router, I get an error saying loading chunk failed.

vue-router.esm.js?8c4f:1897 Error: Loading chunk 0 failed. (missing: http://localhost:8082/tp2.common.app2.home%20.js) at HTMLScriptElement.onScriptComplete (tp2.common.js?9697:115)

If wanting to truly have a standard for using monorepos in enterprise the router should at least allow you to persist routes added with addRoutes on page refresh.

**Comment by pbwei** [comment]
@EvanBurbidge I  have the same issues

**Comment by EvanBurbidge** [comment]
@pbwei what have you tried, its not an issue if you bundle everything into one common.js file, but that defeats the whole purpose of lazy loading files.

**Comment by Kristoffer95** [comment]
I have the same issue
