### ISSUE TITLE
Deprecate beforeEnter guard

### ISSUE THREAD

**Issue by trainiac** [vuejs/vue-router#2540]
### What problem does this feature solve?
By deprecating and eventually removing the `beforeEnter` route guard, the lib can remove the weight and complexity of the feature. Existing features can do the same or better.

Flaws with `beforeEnter`:
 - Encourages devs to add code to the router that can't be code split.
 - Doesn't work well with universal web applications because it is called on server and client side causing redundant work.
 - There is no beforeUpdate so in the case that a route that can be reused (/profile/123/ -> /profile/123/), developers almost always have to share code between the router and the route component to handle the update case.

beforeRouteEnter solves all of these problems.

### What does the proposed API look like?
use beforeRouteEnter or other methods instead of beforeEnter

**Comment by LinusBorg** [comment]
For clarification: Does your Proposal refer to the global `beforeEnter` hook, or the per-component one, or both?

in-component Guards have their own problems, for example:
* When code-splitting them, you can't evaluate these guards until you have loaded the component, so you have to actually load it to decide if the navigation is valid, which essentially means loading a whole lot of code *before* deciding wether or not the navigation is valid, and maybe not even finish it.
* you can't use [this feature](https://vuejs.org/v2/guide/components-dynamic-async.html#Handling-Loading-State) easily

**Comment by trainiac** [comment]
I thought it was `beforeEach` global,` beforeEnter` route, and `beforeRouteEnter` component for the guards.  I'm referring to the `beforeEnter` route guard.

**Comment by LinusBorg** [comment]
Oh, right. ^^

**Comment by trainiac** [comment]
> When code-splitting them, you can't evaluate these guards until you have loaded the component, so you have to actually load it to decide if the navigation is valid, which essentially means loading a whole lot of code before deciding wether or not the navigation is valid, and maybe not even finish it.

- Imagine you have 20 routes that all have `beforeEnter` logic in the router.  That means you will download 20 routes worth of beforeEnter logic when you only need one for the initial payload. 
- How often do you display links to users that they don't have access to?  Sure it happens but the majority of the time if they have the links they can access it so they are gonna download it anyways.
- You can download chunks in the background when the page is loaded, so that can reduce any latency.

> you can't use this feature easily

True, my last point above helps with that.  

The initial payload point to me seems like the bigger problem with regards to performance but I suppose that part is subjective.  This still leaves the universal web app problem and the route update logic and router enter logic having to be split between two files which feels icky to me.

Definitely not convinced  that this needs to be removed but just wanting to start the conversation to maybe even help distill the cases where you would want to use it.

**Comment by LinusBorg** [comment]
> Imagine you have 20 routes that all have beforeEnter logic in the router. That means you will download 20 routes worth of beforeEnter logic when you only need one for the initial payload.

1. You will hardly have totally different rules for each one of those rules - you will probably have 5 hooks that you re-use between routes.
2. You *could* code-split them if you wanted to:
```javascript
beforeEnter(...args) {
  import('./myEnterHook').then( c => {
    c.default(...args)
  })
}
```

a more general helper:
```javascript
const asyncEnterHook = asyncComponent => {
  return function beforeEnter(...args) {
    asyncComponent().then(hook => hook.default(...args))
  }
})
```
```javascript
{
  path: '/a',
  component: A,
  beforeEnter: asyncEnterHook(() => import('./hookForA'))
},

{
  path: '/b',
  component: B,
  beforeEnter: asyncEnterHook(() => import('./hookForB'))
}
```

> Definitely not convinced that this needs to be removed but just wanting to start the conversation to maybe even help distill the cases where you would want to use it.

Apprechiated, and we're definitely always open to such discussions

> How often do you display links to users that they don't have access to? Sure it happens but the majority of the time if they have the links they can access it so they are gonna download it anyways.

Fair point

**Comment by trainiac** [comment]
> You will hardly have totally different rules for each one of those rules - you will probably have 5 hooks that you re-use between routes.

I suppose it depends on the app and how much all of your route's beforeEnter logic adds up to be.

> You could code-split them if you wanted to

But then you either have a request chain problem or the same problem you brought up before.
**Option 1**: convert both beforeEnter and the route component into separate async chunks.
**Result**: user has to wait for beforeEnter chunk, then has to make API calls, then has to download component chunk.  Three synchronous requests is worse than using beforeRouteEnter

**Option 2**: convert beforeEnter and the route component into async chunks but give them the same chunkname.
**Result**: Now you're only down to having to download one chunk, complete any beforeEnter API calls, and the components are already there because it came down with initial chunk.  But then you're hitting the problem of having to download the component code in order to run the beforeEnter logic.  This is the same perf as using beforeRouteEnter and it doesn't work well with universal apps or when your need to also run logic on updating the route.

**Comment by posva** [comment]
Thanks for the proposal, it's the first time someone proposes to remove something 😄 
However, the main point is, as @LinusBorg said, that `beforeEnter` can be executed without fetching fetching the component when doing code splitting. This brings flexibility that we want to keep

Just a few notes: you don't need to and shouldn't code split absolutely everything, specially if it's a function that takes a few bytes. The code that goes in `beforeEnter` isn't related to the component in any way but the code in `beforeRouteEnter` is. `beforeRouteUpdate` only exist in components because you usually want to fetch data and update component data

**Comment by trainiac** [comment]
@posva Anytime 😃.  @LinusBorg @posva  Thank you both for clarity on why one would use `beforeEnter`
- With respect to performance / code splitting, sounds like it depends on the app.
- The universal app question still stands.  The main issue is your router will process beforeEnter and beforeRouteEnter server side and then again client side when initializing the app. Of course you can add an isServer check in that code but it seems ugly to have to repeat that everytime you use those guards.  Any thoughts on configuring Vue Router with a `universal: true` option so that during the first route on the client the beforeEnter and beforeRouteEnter guards don't get run? What cases would you want to run it server and client?

> The code that goes in beforeEnter isn't related to the component in any way but the code in beforeRouteEnter is. beforeRouteUpdate only exist in components because you usually want to fetch data and update component data

- What would be an example of code that goes into `beforeEnter` that is not related to the component?

**Comment by LinusBorg** [comment]
> What cases would you want to run it server and client?

All cases that have an effect on the shape of the output of that route, because  otherwise you will get hydration errors as client- and server side dom may differ. 

> What would be an example of code that goes into beforeEnter that is not related to the component?

BeforeEnter can't manipulate the component instance, beforeRouteEnter can. So code that is supposed to set properties in the component would have to go in the latter. 

I think Posva was referring to that.

**Comment by trainiac** [comment]
> All cases that have an effect on the shape of the output of that route, because otherwise you will get hydration errors as client- and server side dom may differ.

Right but don't you run `store.replaceState(window.__INITIAL_STATE__)` before instantiating your app and router? You already requested the data you needed server side.

> BeforeEnter can't manipulate the component instance, beforeRouteEnter can. So code that is supposed to set properties in the component would have to go in the latter.

beforeRouteEnter can't manipulate the component instance either because the component hasn't been instantiated when it's called, i.e. you don't have access to `this`. If you're referring to the next callback within beforeRouteEnter, then that is a different story. That is not available until the route has already rendered.
