### ISSUE TITLE
router.beforeEach中，对to.query设置参数，组件中可以收到参数，但是没有更新到url上

### ISSUE THREAD

**Issue by imshenshen** [vuejs/vue-router#2541]
### Version
3.0.2

### Reproduction link
[https://jsfiddle.net/50wL7mdz/809324/](https://jsfiddle.net/50wL7mdz/809324/)

### Steps to reproduce
路由跳转

### What is expected?
url符合接收到的参数，同样被更新

### What is actually happening?
URL中没有u_c_n参数

---
基础需求是要保持一个参数在路由间传递，但是URL上没更新，刷新后就丢失了

**Comment by posva** [comment]
That is not a valid repro and please write the issues in English. Thank you

**Comment by posva** [comment]
oh and the locations in general are readonly ($route, to, from)
