### ISSUE TITLE
error when using child routes in a plugin

### ISSUE THREAD

**Issue by mxrlkn** [vuejs/vue-router#2547]
### Version
3.0.2

### Reproduction link
[https://codesandbox.io/s/l2zkww865q](https://codesandbox.io/s/l2zkww865q)

### Steps to reproduce
Open the codesandbox, open the console and click on the page1 link

### What is expected?
page1 route and child route working

### What is actually happening?
freezes and shows:
[Vue warn]: Error in nextTick: "RangeError: Maximum call stack size exceeded"`

In the console

---
I'm making a plugin for internal use that will always need vue-router with some default routes. When I tried to use child routes, I encountered the error.

If you open the vue inspector you'll see that it keeps creating new child routes inside the child routes itself repeatedly.

**Comment by posva** [comment]
The line `Vue.options.render = h => h(app);` shouldn't be there, Vue is the constructor, not the Vue instance at the route. You will need to manually add that line to the main.js. For further questions, please use the appropriate channels like the Forum or discord chat 🙂

**Comment by mxrlkn** [comment]
Ahh thanks. I've added the render function to main.js, but I still get the same error. I've created a forum post for it instead 🙂
https://forum.vuejs.org/t/error-when-using-child-routes-in-a-plugin/52194
