### ISSUE TITLE
Default route and set activeClass for parent element

### ISSUE THREAD

**Issue by tranduyhung** [vuejs/vue-router#255]
activeClass option is only applied to its ```<a>```, what I want to achieve is applying to its parent, in my case is the ```<li>``` which belong to a navigation bar/menu.

```
<ul class="nav nav-list">
	<li>
		<a v-link="{ path: '/', activeClass: 'active' }">Home</a>
	</li>
	<li>
		<a v-link="{ path: '/page-1', activeClass: 'active' }">Page 1</a>
	</li>
	<li>
		<a v-link="{ path: '/page-1', activeClass: 'active' }">Page 2</a>
	</li>
</ul>
```
I can workaround by apply v-link to the ```<li>``` but the Home menu item is always active because its route is "/".

```
<ul class="nav nav-list">
	<li v-link="{ path: '/', activeClass: 'active' }">
		<a v-link="{ path: '/' }">Home</a>
	</li>
	<li v-link="{ path: '/page-1', activeClass: 'active' }">
		<a v-link="{ path: '/page-1' }">Page 1</a>
	</li>
	<li v-link="{ path: '/products', activeClass: 'active' }">
		<a v-link="{ path: '/page-1' }">Page 2</a>
	</li>
</ul>
```

What I want is, when we first access the page, Home menu item is active (class "active" is added to its ```<li>```), when I click other menu item like Page 1, its ```<li>``` is active and Home's ```<li>``` is not active.

I'm new to Vue and Vue Router so I'm not sure how to do this. I really appreciate if you have any suggestion! I hope there is something in Vue could help me achieve this easily, I really don't want to add some lines of jQuery to do it manually.

**Comment by tranduyhung** [comment]
I ended up with this

```
<ul class="nav nav-list">
    <li v-link="{ path: '/home', activeClass: 'active' }">
        <a v-link="{ path: '/home' }">Home</a>
    </li>
    <li v-link="{ path: '/page-1', activeClass: 'active' }">
        <a v-link="{ path: '/page-1' }">Page 1</a>
    </li>
    <li v-link="{ path: '/products', activeClass: 'active' }">
        <a v-link="{ path: '/page-1' }">Page 2</a>
    </li>
</ul>
```

```
	router.redirect({
		'*': '/home'
	})
```

It works but if there is any better solutions, please let me know. Thanks!

**Comment by jonagoldman** [comment]
+1

**Comment by PistachioPlz** [comment]
+1 from me as well.

Having the active class on the parent `<li>` element is so common (e.g bootstrap) it really should be possible to do with a built-in feature.

**Comment by simondubois** [comment]
+1

**Comment by NicolasParada** [comment]
`exact: true`
```js
<ul class="nav nav-list">
    <li>
        <a v-link="{ path: '/', activeClass: 'active', exact: true }">Home</a>
    </li>
    <li>
        <a v-link="{ path: '/page-1', activeClass: 'active' }">Page 1</a>
    </li>
    <li>
        <a v-link="{ path: '/page-2', activeClass: 'active' }">Page 2</a>
    </li>
</ul>
```

**Comment by yyx990803** [comment]
This can now be done with `v-link-active` in 0.7.8.

**Comment by cnicodeme** [comment]
Awesome! Thank you :)

**Comment by bwangel23** [comment]
You has soloved my question. Awesome! Thank you :)

**Comment by paglias** [comment]
@yyx990803 is this feature gone in v2?

**Comment by vetalball** [comment]
@paglias 
Yes, it has been replaced.
According to the [documentation](https://router.vuejs.org/en/api/router-link.html#applying-active-class-to-outer-element) now you can use the following structure:
```
<router-link tag="li" to="/foo">
  <a>/foo</a>
</router-link>
```

**Comment by YavorK** [comment]
Here is THE Solution https://github.com/vuejs/vue-router/issues/762
The router assumes that if you are not using "exact" option you want 
Categories to be ACTIVE when you are in Categories / Phones for example.
So when you are in /x/y, then / is active, and /x is active as well. "exact" option serves to disable this functionality.

**Comment by jdriesen** [comment]
@YavorK : Thanks mate.
Exactly what I was looking for :)

**Comment by leszekhanusz** [comment]
If you arrive on this page from google, note that the correct way to do this with a recent version (>3.1.0) is to use the [v-slot API](https://router.vuejs.org/api/#v-slot-api-3-1-0)

**Comment by posva** [comment]
The name of the property change but it can still be set globally: https://router.vuejs.org/api/#linkactiveclass

the slot api could help with more advanced use cases!
Locking because this thread is very outdated
