### ISSUE TITLE
warn about root paths without a leading slash

### ISSUE THREAD

**Issue by MatiasOlivera** [vuejs/vue-router#2550]
### Version
2.5.3

### Reproduction link
[https://codesandbox.io/s/6zvmx5lorr](https://codesandbox.io/s/6zvmx5lorr)

### Example
```js
import Vue from "vue";
import Router from "vue-router";

import Home from "../src/views/Home.vue";
import Products from "../src/views/Products.vue";

Vue.use(Router);

const routes = [
  { name: "home", path: "/", component: Home },
  {
    name: "products",
    path: "products", // <-- the problem is here
    component: Products
  }
];

export default new Router({
  routes
});
```

### Steps to reproduce
1. Open the reproduction
1. Click on the products link

### What is expected?
I spent some time trying to understand what the problem was, so it would be nice to see a warning message telling that the route is invalid because doesn't have the initial slash.

### What is actually happening?
The router goes to a route that doesn't exist.

**Comment by Zarad1993** [comment]
Can I work on this?

**Comment by thedamon** [comment]
Would be nice to see a note in the docs about how slashes should be used in routes.. or did I miss one?

**Comment by nmfzone** [comment]
Any update on this? I think it's should be mentioned in docs if leading slash (in path) is mandatory.
This will make some confusion for new user..
