### ISSUE TITLE
router.go() does not work in Safari

### ISSUE THREAD

**Issue by Johnsoct** [vuejs/vue-router#2554]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/zljj518k94](https://codesandbox.io/s/zljj518k94)

### Steps to reproduce
Setup `this.$router.go()` (essentially, refresh the page without any data) and try triggering it in Safari.

In code sandbox, using Safari, if you click the button (calls `this.$router.go()`) an error is thrown. If you do the same in Chrome, for example, nothing happens (I assume it's due to being inside their sandbox) but remains error-free.

### What is expected?
Page refresh without data

### What is actually happening?
Nothing at all

---
I'm not experienced with picking source code apart, but I did a bit of digging to see if any recent merges may have caused because I believe the issue to be new as of within one week's time.

**Comment by posva** [comment]
Please check the documentation at https://router.vuejs.org, you should pass the router instance to the mani Vue instance. You are passing The Router constructor

**Comment by Johnsoct** [comment]
@posva I made these updates and it's still not functioning. `this.$router.go()` has zero effect in Safari.

(the application I'm working on is setup correctly. I just rushed the reproduction sandbox)

Here is my exact setup for vue-router:
**main.js**
```
import Vue from 'vue';
import App from './App.vue';
import router from './router';
import store from './store/index';

Vue.config.productionTip = false;

new Vue({
  router,
  store,
  render: h => h(App),
}).$mount('#app');
```
**router.js**
```
// Dependency Imports
import Vue from 'vue';
import Router from 'vue-router';

Vue.use(Router);

export default new Router({...})
```

Again, using `this.$router.go()` anywhere works in Chrome and Firefox, but has zero effect in Safari. Here is a video of the behavior: http://recordit.co/lpKpKQB3XP

**Comment by posva** [comment]
Please, check the docs for the `go` function, you are passing no parameters or anything... Make sure you are not mistakenly using go instead of push.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by Johnsoct** [comment]
Alright, I've already read the documentation quite a few times and I've already tried Discord and used StackOverflow to get to this example. I appreciate your time, but if you could take a second instead of immediately blowing this off, that would be great.

The vue-router docs mention it imitates the browser history API, which for `window.history.go()` if you do not pass a parameter reloads the current page: https://developer.mozilla.org/en-US/docs/Web/API/History.

This is working as expected in Chrome and Firefox, but not in Safari. However, if I put any parameter other than 0 or empty (numbers only), it works in Safari. This is a bug.

**Comment by VictorCazanave** [comment]
I have the same issue with vue-router 3.0.7: `this.$router.go()` works in Chrome, Firefox, IE and Edge but not in Safari.

The result is the same with `window.history.go()`, so I guess it's a bug in Safari but I think it would be great to fix it in vue-router to get a consistent behaviour in all the browsers.

Currently I use `window.location.reload()` as a workaround.

**Comment by gabomasi** [comment]
This is not solved

**Comment by netopolit** [comment]
@Johnsoct  You forgot to prevent default event, either by using event modifier (@click.preven="refresh") or in the handler function. Safari seems not to be forgiving of this, while other browsers you mentioned are.

**Comment by codewithharshad** [comment]
Yes, `router.go()` doesn't work on Safari.
Currently, even I am using `window.location.reload()` as a workaround.

**Comment by 1isten** [comment]
This issue is not solved

**Comment by abuwho** [comment]
For me it's working on first load, I have a button that triggers a route change. After the page renders, the first time the routing works, but after that it does not do anything, is that how it is for you too, guys?
