### ISSUE TITLE
why the redirect function executes twice

### ISSUE THREAD

**Issue by changk99** [vuejs/vue-router#2566]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/changli/38sft2x0/1/](https://jsfiddle.net/changli/38sft2x0/1/)

### Steps to reproduce
1、  click the home     
2、  click the toAbout

### What is expected?
1、 the redirect function  will not be called  
2 、the redirect function will  be called once

### What is actually happening?
1、 the redirect function  will  be called once  
2、 the redirect function will  be called  twice

**Comment by posva** [comment]
`redirect` is executed by router-links to compute the destination. It's not to be used as a hook. Remember you can also redirect in a `beforeEnter` hook by calling the `next` function with a parameter
