### ISSUE TITLE
beforeRouteUpdate is not called on the first navigation when routing to the same component

### ISSUE THREAD

**Issue by salomvary** [vuejs/vue-router#2580]
### Version
3.0.2

### Reproduction link
[https://jsfiddle.net/salomvary/qcfg8xm7/18/](https://jsfiddle.net/salomvary/qcfg8xm7/18/)

### Steps to reproduce
- Open the linked JSFiddle link
- Open the developer console
- Click on "Go to /foo/one"
- Look at the console logs

### What is expected?
'foo:beforeRouteUpdate'  to be logged on the first navigation.

### What is actually happening?
'foo:beforeRouteUpdate'  is not logged on the first navigation.

---
Workaround: watching `$route` seems to work as expected.

**Comment by posva** [comment]
`beforeRouteUpdate` executes when the param changes but we stay on the same route. You start off the home `/` then go to a different route: `/foo/:param`. You use the same component but what matters to the guard is the route
