### ISSUE TITLE
vue-router and axios 拦截器一起使用 出现的异步问题

### ISSUE THREAD

**Issue by ovarte** [vuejs/vue-router#2594]
### Version
2.0.1

### Reproduction link
[https://jsfiddle.net/jwdtae9u/3/](https://jsfiddle.net/jwdtae9u/3/)

### Steps to reproduce
详见JSFiddle。通过后端返回的数据，判断是登录状态或者管理员或者进入维护，或者强制进入公告，但是异步问题，请问怎么解决呢

### What is expected?
通过后端返回的数据，判断是登录状态或者管理员或者进入维护，或者强制进入公告，但是异步问题，axios 里的next()不生效。请问怎么解决呢

### What is actually happening?
通过后端返回的数据，判断是登录状态或者管理员或者进入维护，或者强制进入公告，但是异步问题，axios 里的next()不生效。

---
怎么解决 vue-router和 axios 拦截器 一起使用的问题呢 非常感谢

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
