### ISSUE TITLE
Vue-router not work properly when the onload event of window not triggered

### ISSUE THREAD

**Issue by mice33** [vuejs/vue-router#2596]
### Version
3.0.1

### Reproduction link
[https://github.com/mice33/router-demo](https://github.com/mice33/router-demo)

### Steps to reproduce
1.run dev && visit website  
2.click 'go to h2' link  
3.click 'go back' link, can't go back now when the onload event of window not triggered

### What is expected?
3.click 'go back' link, can go back

### What is actually happening?
3.click 'go back' link, can't go back

Same problem #2320

**Comment by posva** [comment]
The repro works...

**Comment by mice33** [comment]
@posva 
I'm still bad.

only http://1.xxxfgfg.com/test request status is pending, click 'go back' link, can't go back, when http://1.xxxfgfg.com/test request status is connection timeout, can go back

http://1.xxxfgfg.com/test can be replaced with any non-existent request address.
