### ISSUE TITLE
hey guys, I have trouble with dynamic imports in routes

### ISSUE THREAD

**Issue by cybermerlin** [vuejs/vue-router#2597]
### Version
3.0.2

### Reproduction link
[https://github.com/vuejs/vue-router/issues/215#issuecomment-456791509](https://github.com/vuejs/vue-router/issues/215#issuecomment-456791509)

### Steps to reproduce
https://github.com/vuejs/vue-router/issues/215#issuecomment-456791509

pls, watch on the screenshot

### What is expected?
good work

### What is actually happening?
not work

---
https://github.com/vuejs/vue-router/issues/215#issuecomment-456791509

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by cybermerlin** [comment]
@posva hi man, this is not question, this is the trouble

**Comment by cybermerlin** [comment]
give me a few minutes n look this trouble pls

**Comment by posva** [comment]
If it's _trouble_ follow the issue reporting guidelines. It's not the first time you open issues like this. I'm not your personal support
