### ISSUE TITLE
beforeEnter next callback is not called

### ISSUE THREAD

**Issue by rominf** [vuejs/vue-router#2600]
### Version
2.5.22

### Reproduction link
[https://jsfiddle.net/2ykhv8jq/](https://jsfiddle.net/2ykhv8jq/)

### Steps to reproduce
Create a route with `beforeEnter` handler which calls `next` with a callback function.

In jsfiddle.net click the button and check the console.

### What is expected?
"Am i called" and the `vm` should be present. 

### What is actually happening?
Line with "Am i called" is not present.

---
Code borrowed from https://github.com/vuejs/vue-router/issues/737#issuecomment-446565958

**Comment by LinusBorg** [comment]
A callback is only supported in the in-component `beforeRoutEnter` guard.

**Comment by rominf** [comment]
Is there a good reason for this? It's inconvenient!
