### ISSUE TITLE
Keep previous component until next mounted

### ISSUE THREAD

**Issue by avele** [vuejs/vue-router#2601]
### What problem does this feature solve?
I want the ability to change the router-view component only when the next one is mounted. For instance, the next router-view component could be mounted separately with ```display: none```, and after the "mounted" event I would make the new component visible and destroy the previous component.

Currently I can only show a spinner or an overlay while the new component is loading, but I can't keep the previous component on the screen.

My usecase is similar to github repository tabs
![github tabs](https://user-images.githubusercontent.com/34437766/51894559-8f384280-23c1-11e9-9637-3fc10ae17fa4.gif)
I want to mimic the standard, non-SPA browser behavior.

### What does the proposed API look like?
A prop for ```<router-view>,``` perhaps "preload" or "changeOnMounted".

**Comment by posva** [comment]
That's the behaviour right now. You can prefetch data in navigation guards and call `next` once everything is fetched

**Comment by avele** [comment]
No, you did not understand. I want to fully load next component, until mounted event will be triggered (or ideally until I manually tell router view to do it) and then only show it. 
I have a lot of logic in components premount hooks and not only in components router mounts but its child components and so on. If I put all this logic in router it will become overloaded, and components will depend on router too much.
