### ISSUE TITLE
Passing new params to the current route when props=true, doesn't update router-view

### ISSUE THREAD

**Issue by pikax** [vuejs/vue-router#2604]
### Version
3.0.2

### Reproduction link
[https://codesandbox.io/s/k50j5wn8or](https://codesandbox.io/s/k50j5wn8or)

### Steps to reproduce
- set mode to history
- Add a route with `props: true` 
- Add props to that route component
- App.vue beforeMount, add a `router.replace` or `router.push` with a the route `name` and `params` object.
- If the route path is the same as the current route, it won't update the route

### What is expected?
Updating the component props down based on params

### What is actually happening?
route component defaults props

---
Not sure if this is the expected behaviour, even using ` <router-view :key="$route.fullPath"></router-view>` doesn't do much because of the `params` don't affect the path.

Encounter this when sending the app to `Error` page with custom props but when I refreshed was getting the expected values or times no props being passed.

**Comment by posva** [comment]
Params must be declared in the url. Passing state  in params is not supported

**Comment by pikax** [comment]
You mean using query instead of params?
```javascript
const props  ={
text: "text"
};

// use this 
router.replace({
  name: 'test',
  query: props
})

// instead of
router.replace({
  name: 'test',
  params: props
})
```
