### ISSUE TITLE
abstract mode's router.back() fails if there are 2 consecutive same routes in history stack

### ISSUE THREAD

**Issue by rocka** [vuejs/vue-router#2607]
### Version
3.0.2

### Reproduction link
[https://jsfiddle.net/Rocka/bhu5vkn8/3/](https://jsfiddle.net/Rocka/bhu5vkn8/3/)

### Steps to reproduce
1. Click `10. artist`
2. Hit button `togglePlayer`
3. Click `10. artist`
4. Hit button `back` 2 times

### What is expected?
route back to `/search`

### What is actually happening?
nothing happend, route and route-view do not change

---
'cause I didn't figure out how to determine wether the route is going forward or backword, I decided to use `abstract` mode and traverse the router stack to find out which direction the route is going, then hit into this bug. The demo works fine if change router's mode to `hash` or `history`.

**Comment by tarunmangukiya** [comment]
Facing same issue!
