### ISSUE TITLE
Improve function mode props with route-view attributes

### ISSUE THREAD

**Issue by jbmikk** [vuejs/vue-router#2608]
### What problem does this feature solve?
When passing props to the `router-view` all routed components are forced to implement the same interface if they want to use the data provided by the `router-view`.

We usually use the props as a way of avoiding coupling the components to the router. The components simply receive the props and they are not aware they come from the URL.

I think it would be useful if we could decouple the components from the router-view, just the way we decouple them from the URL.
I think being able to map the router-view attributes to the desired component props is more appropriate and lets our components expose the interface they need to expose, rather than the interface imposed by the router-view.

I think the right place for solving this problem is the route's function mode props.

### What does the proposed API look like?
The router view passes down a couple of parameters as usual:

    <router-view :param1="value1" :param2="value2"></router-view>

The function maps the props both from the route's URL and also the `router-view` attributes.
It can also resolve conflict names between URL parameters and view parameters and determine which parameter is more important in each case.

    {
      path: '/test',
      component: Test,
      props: (route, view) => {
        return {
          query: route.query.q
          paramA: view.attrs.param1,
          paramB: view.attrs.param2 || route.query.param2
        }
      }
    } 

I have done some tests with the router's code and it seems to work fine.

I would like to have some feedback from the community. It is a fairly simple change. We should make sure this doesn't have any unwanted side effects, it's backwards compatible and there isn't a better way to do it.

Here's a branch with a test I made and it worked for me: https://github.com/jbmikk/vue-router/commits/view-parameter-for-props

**Comment by posva** [comment]
Thanks for the proposal but if you are passing different props to different views and hoisting them in the App component (or a layout), you are better off putting that in a Store (vuex).

The props passed to the router-view should indeed be adopted my most if not all of view components as they are configuration values. If you need to pass specific values, you can already do that in the function mode of props. If you want reactive values, you are likely passing state which should instead be part of the URL or in the store

**Comment by jbmikk** [comment]
I'm trying to avoid vuex for now, it seems overkill for the app I'm building. 

I have data in the App component that was fetched from an API call, so it can't be part of the URL and it can't be part of the route configuration. 

I think the only option I have right now is coupling all components to the router view, although it makes them awkward to reuse elsewhere. 

I think the Flux architecture is a good idea, but I don't have to use vuex if I don't want to, I can build an app using just functional components with props and events and managing state at the root of the app without vuex.

I don't want to sound pedantic, but I was thinking the vue-router can be more useful and streamlined out of the box without having to install yet another library. And a better integration of the router's own components (routes and views) sounds like the kind of job the router should be doing.
