### ISSUE TITLE
"ChromeDriver installation failed undefined" during npm install.

### ISSUE THREAD

**Issue by jasonlam0619** [vuejs/vue-router#261]
log:

    > chromedriver@2.16.0 install /Users/Jason/Documents/vue-router/node_modules/chromedriver
    > node install.js

    Downloading http://chromedriver.storage.googleapis.com/2.16/chromedriver_mac32.zip
    Saving to /var/folders/_1/4khr45254mbfbn7k7fvmbkk80000gn/T/chromedriver/chromedriver_mac32.zip
    Receiving...
    ChromeDriver installation failed undefined
    npm ERR! Darwin 15.0.0
    npm ERR! argv "/usr/local/Cellar/node/0.12.2_1/bin/node" "/usr/local/bin/npm" "install"
    npm ERR! node v5.0.0
    npm ERR! npm  v3.4.1
    npm ERR! code ELIFECYCLE
    
    npm ERR! chromedriver@2.16.0 install: `node install.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the chromedriver@2.16.0 install script 'node install.js'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the chromedriver package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node install.js
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls chromedriver
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/Jason/Documents/vue-router/npm-debug.log

**Comment by yyx990803** [comment]
Most likely chromedriver is incompatible with Node 5. Try 4.2.2 instead.

**Comment by xiaomao155** [comment]
请问您这个问题是怎么解决的

**Comment by KingMario** [comment]
Most likely the zip file you downloaded is zero byte in length. This happened to me.
storage.googleapis.com could be blocked by the _WALL_

**Comment by ghost** [comment]
@KingMario thanks

**Comment by asktalk** [comment]
Downloading http://npm.taobao.org/mirrors/chromedriver/2.24/chromedriver_win32.zip
Saving to C:\Users\asktalk\AppData\Local\Temp\chromedriver\chromedriver_win32.zip
Receiving...
ChromeDriver installation failed undefined
npm info lifecycle chromedriver@2.24.1~install: Failed to exec install script
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\2.enviroment_domain\2.nodejs.env\node.exe" "D:\2.enviroment_domain\2.nodejs.env\node_modules\npm\bin\npm-cli.js" "install" "chromedriver" "--chromedriver_cdnurl=http://cdn.npm.taobao.org/dist/chromedriver" "-g"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.24.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromedriver@2.24.1 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.

**Comment by guwenbin1991** [comment]
@KingMario 
### it does work for me

**Comment by KingMario** [comment]
@yangjie6020 @guwenbin1991
I'm glad it helps. If you want to show your thanks, buy me a cup of coffee:
![image](https://cloud.githubusercontent.com/assets/3956876/21517623/6df82ed6-cd1b-11e6-818d-525a50fd10e6.png)

Or notice me if only it doesn't work.

**Comment by tomaszczechowski** [comment]
Hi, 

The topic is already closed, however, I want to share with you steps I did to resolve this issue. Hope it helps someone whos still struggling with it.

1. Download chrome driver from here (I used 2.20 version): `https://chromedriver.storage.googleapis.com/2.20/chromedriver_win32.zip`
2. Unpack it somewhere in your project dir.
3. Using NPM install package from local files system: 
`npm install chromedriver --chromedriver_filepath=/path/to/chromedriver.zip`
4. Update .npmrc file with this line: `chromedriver_filepath=/path/to/chromedriver.zip` **(optional)**
5. In protractor.conf.js file indicate new source of chrome driver adding a line: 
`chromeDriver: './node_modules/chromedriver/lib/chromedriver/chromedriver.exe'`

Work at least on my end 😄

**Comment by chenyiqi** [comment]
npm install chromedriver --chromedriver_cdnurl=http://cdn.npm.taobao.org/dist/chromedriver

**Comment by muzishuiji** [comment]
@tomaszczechowski can you tell me where is the   .npmsrc file?

**Comment by tomaszczechowski** [comment]
if you don't have it, just create it in the same flles level as a `package.json` is.

**Comment by muzishuiji** [comment]
ok, thank you! i have resolved this problem. but i still have a question.when i write 
""chromedriver_filepath=C:/Users/user/AppData/Local/Temp/chromedriver/chromedriver_win32.zip"" in the  .npmrc file,then next time , if you run npm install chromedriver , it will find this module in "C:/Users/user/AppData/Local/Temp/chromedriver/chromedriver_win32.zip" this place, right?? but it doesn't work, it still downloads from "https://chromedriver.storage.googleapis.com/2.35/chromedriver_win32.zip" this url,i feel confused.

**Comment by Django-annotate9** [comment]
> 请问您这个问题是怎么解决的





https://stackdev.space/questions/struggling-with-setting-up-vuejs
