### ISSUE TITLE
Dynamic route doesn't work if route parameter contains a dot followed by text.

### ISSUE THREAD

**Issue by CarlosOnline** [vuejs/vue-router#2610]
### Version
2.5.1

### Reproduction link
[https://github.com/CarlosOnline/VueRouterBug.git](https://github.com/CarlosOnline/VueRouterBug.git)

### Steps to reproduce
Create a route with dynamic route parameter **:lab**

* Start app
* Navigate to MyView/**Foo** which works
* Navigate to MyVew/**Number.1234** does not work

```
{
    path: '/MyView/:lab',
    component: MyView,
    display: 'MyView',
    meta: { title: 'MyView' }
},
```

### What is expected?
Navigate to route with dynamic parameter when no 

### What is actually happening?
Route is not found

**Comment by CarlosOnline** [comment]
Never mind upgrading vue js versions fixed the issue.

**Comment by CarlosOnline** [comment]
Upgrading vue js versions fixed the issue.

**Comment by mbsimonovic** [comment]
which version solved the problem?

**Comment by smilingkylan** [comment]
Still having issue in vue-router v4.1.5

**Comment by cabeaulac** [comment]
Still having issue in vue-router 4.2.1 also

**Comment by arminebner** [comment]
same in 4.2.2
using vite and i stumbled upon this plugin that worked for me:
https://www.npmjs.com/package/vite-plugin-rewrite-all
