### ISSUE TITLE
// makes route invalid

### ISSUE THREAD

**Issue by GHakopian** [vuejs/vue-router#2613]
### Version
3.0.2

### Reproduction link
[https://codesandbox.io/s/jzr5nojn39](https://codesandbox.io/s/jzr5nojn39)

### Steps to reproduce
when in history mode with a basePath setup,
navigating to server:123/basePath/subPath navigates to the right component
but if you add an extra / after server:234, 
navigating to server:123//basePath/subPath returns 404 

### What is expected?
navigating to server//basePath/subPathnavigates to configured component

### What is actually happening?
navigating to server:123//basePath/subPath returns 404 

---
Is this a bug? i think the extra / should not change the end route, this is an issue in my case as my legacy backend application can redirect with an extra / at random. if this is intended can we then add something like "*/basePath" to only consider the path starting from basePath.

**Comment by posva** [comment]
please provide a minimal repro and clearer repro steps: click here, there, see url, etc
