### ISSUE TITLE
https://router.vuejs.org/   can't open 

### ISSUE THREAD

**Issue by hwlv** [vuejs/vue-router#2615]
### Version
2.6.0

### Reproduction link
[https://router.vuejs.org/ ](https://router.vuejs.org/ )

### Steps to reproduce
https://router.vuejs.org/   can't open 

### What is expected?
Web page display normally

### What is actually happening?
Web page display exception

---
Please repair it as soon as possible.  It's seriously

**Comment by posva** [comment]
it works. It must be something on your end blocking it
