### ISSUE TITLE
dynamic routing support

### ISSUE THREAD

**Issue by wangjingf** [vuejs/vue-router#2616]
### What problem does this feature solve?
dynamic routing like react-router-v4

### What does the proposed API look like?
Are there plans to upgrade vue-router to dynamic routing (like react-router-v4)

**Comment by posva** [comment]
Please check existing issues for addRoutes, replaceroutes, etc
To be clear, dynamic routing is not an upgrade, it's a different way of working with its own disadvantages and advantages
