### ISSUE TITLE
The addRoutes  method need to suport  adding dynamic routes as children to an existing route

### ISSUE THREAD

**Issue by hzsrc** [vuejs/vue-router#2622]
### What problem does this feature solve?
The addRoutes method currently only suport add new routes to root routes.  But if can not add routes as children to an existing route.

### What does the proposed API look like?
router.addRoutes(routes: Array<RouteConfig>, parent ? : Location)

Like:
router.addRoutes([...childRoutes],  '/main')

**Comment by posva** [comment]
Duplicate of #1156
