### ISSUE TITLE
希望vue-router能支持查询跳转后的地址

### ISSUE THREAD

**Issue by zhuxianbin** [vuejs/vue-router#2627]
### What problem does this feature solve?
router 通过 与 push 一样的方式 不进行跳转而获取一个预跳转地址,与push的地址保持一致性;
可解决用于hybrid 开发模式中,A页面打开新窗口到B页面的代码书写不优雅问题;

### What does the proposed API look like?
const url  =  this.$router.query({name:"namespace.one.two",params:{id:1001,type:"default"}})
or
const url  =  this.$router.push({},{prevent:true}) // Options

**Comment by posva** [comment]
I tried translating but I don't understand, sorry. If you want to update the query you can `push({ query: newQuery })`

**Comment by zhuxianbin** [comment]
sorry,My English is very poor.
i think.
router.query({name:"xxx",params:{a:1}})  // router  path: "/xxx/:a" ,  get  "/xxx/1"
return me  a string , example "/xxx/1"

In the process of mixed development with app, sometimes there is such a demand that a new window is opened instead of " router.push".
 At this time, if you use path splicing, the code is not elegant enough. if " router" provides a method to query the path, it can ensure the correctness of the path

**Comment by posva** [comment]
if you want to open a new window use a regular link. I still don't understand well what you mean... I think you should ask for help in the chinese forum
