### ISSUE TITLE
Components for child routes doesn't show

### ISSUE THREAD

**Issue by Ihor-Shevtsov** [vuejs/vue-router#2629]
### Version
3.0.2

### Reproduction link
[https://codepen.io/ih-shevtsov/pen/ywNVEe](https://codepen.io/ih-shevtsov/pen/ywNVEe)

### Steps to reproduce
1. Click on "Go to nested route 1" -> route changed to  /home/nested-route-1
2. Click on "Go to nested route 2" -> route changed to  /home/nested-route-2

### What is expected?
Components for specific child route must be shown. 

### What is actually happening?
Components for child routes doesn't show. It is works only for "parent" route.

---
I tried to research this issue in router's code. Seems like incorrect router depth for any reason (https://github.com/vuejs/vue-router/blob/v3.0.2/dist/vue-router.esm.js#L58-L69)

**Comment by posva** [comment]
This is working as expected, when using children you must nest `router-view` in your route components and name those accordingly
