### ISSUE TITLE
Could you add a config option?

### ISSUE THREAD

**Issue by yozman** [vuejs/vue-router#263]
@yyx990803 
continue from here:
https://github.com/vuejs/vue-loader/issues/91#issuecomment-161318918

now the page use `vue-router` is 2D,
only `x` and `y`, I need to add `z`,
like `window.alert`, `window.confirm`,
but I don't want to control `dom`,
what should I do?

**Comment by amirrustam** [comment]
@yozman Your question is not clear and well defined. Please provide some code to demonstrate what you are trying to accomplish.
