### ISSUE TITLE
关于router用query传参时的格式问题

### ISSUE THREAD

**Issue by ctrlv-git** [vuejs/vue-router#2630]
### Version
3.0.1

### Reproduction link
[https://jsbin.com/yujepuwamo/edit?html](https://jsbin.com/yujepuwamo/edit?html)

### Steps to reproduce
当使用 如下方法传递参数时
 this.$router.push({
        path: "/xxx",
        query: {
          id: “yyy”
        }
      });

### What is expected?
按照URL的标准格式 将会跳转至如下格式
scheme://host:port/path?id=yyy/#/xxx

### What is actually happening?
然而生成路径时是如下格式
scheme://host:port/path/#/xxx?id=yyy

---
这样的结果是在URL不符合路径传参的规则，当然这不影响用 this.$route.query的方法拿到所要传递的参数。但是当用window.location.search的方法时会发现参数被存放在hash的内容了。是否能统一格式呢？

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
