### ISSUE TITLE
Multiple named views in single vue file

### ISSUE THREAD

**Issue by ferndot** [vuejs/vue-router#2633]
### What problem does this feature solve?
It would be great if I could specify multiple named views in a single .vue file. This would make it easier and more centralized to manage applications that require multiple views for each route. By having all the code in one file, it would also make it easy to update both components simultaneously.

### What does the proposed API look like?
For instance, if I had header and content views:
```html
<!-- Named slot -->
<template slot="header">
  <div>
    Header content
  </div>
</template>

<!-- Default slot -->
<template>
  <div>
    Body content
  </div>
</template>
```

**Comment by posva** [comment]
Thanks for the proposal. Unfortunately, I think this goes against Vue rule of having one file per component and it brings a problem when creating the `script` and `style` counterpart as the user would be required to specify a name (you called that slot) too

This is however something you could achieve with a custom webpack loader
