### ISSUE TITLE
Tests failing on lazy loading

### ISSUE THREAD

**Issue by eugenweissbart** [vuejs/vue-router#2635]
### Version
3.0.2

### Reproduction link
[https://github.com/vuejs/vue-router](https://github.com/vuejs/vue-router)

### Steps to reproduce
- Clone a vue-loader git repo and checkout to 3.0.2
- Run `npm install`
- Run `npm test`

### What is expected?
All tests run smoothly

### What is actually happening?
```ERROR in ./lazy-loading/app.js 32:9
Module parse failed: Unexpected token (32:9)
You may need an appropriate loader to handle this file type.
|   // a Promise.
| };var Foo = function Foo() {
>   return import('./Foo.vue');
| };
|
 @ multi es6-promise/auto ./lazy-loading/app.js lazy-loading[1]```

The corresponding test fails afterwards

<!-- generated by vue-issues. DO NOT REMOVE -->

**Comment by posva** [comment]
I think you missed the repo

**Comment by eugenweissbart** [comment]
No

**Comment by eugenweissbart** [comment]
@posva reopen pls

**Comment by posva** [comment]
You pointed to vue-loader, I see you 😉 
I remember the error. Use `yarn` for development, it will fix it and that's what we use anyway
Otherwise, you have to do this:

```js
rm -rf node_modules package-lock.json
# you may or may not need to do a full npm cache clean - I did in my case
npm cache clean --force
npm install webpack@4.28.4 --save-dev --save-exact
npm install acorn-dynamic-import@4.0.0 --save-dev
npm install acorn@6.0.5 --save-dev
npm i
npm update acorn --depth 20
npm dedupe
```

The problem comes from webpack, not from the repo

**Comment by eugenweissbart** [comment]
Yeah, the wrong repo link was my mistake.

Thanks will try yarn instead!
Maybe this should be mentioned in README.md for the newcomers?
