### ISSUE TITLE
Accessibility keyboard shortcuts

### ISSUE THREAD

**Issue by joelworsham** [vuejs/vue-router#2637]
### What problem does this feature solve?
When tabbing over router links, pressing the space or enter key does not trigger navigation. Although I can add this layer of logic myself, it seems that this should be natively supported.

### What does the proposed API look like?
To the public, nothing would change, the links would just work on keyboard navigation.

**Comment by posva** [comment]
This already works, if it doesn't provide a boiled down repro please

**Comment by joelworsham** [comment]
@posva You are right, and this issue may have been opened preemptively. However, we have identified the cause is that, somehow, the `href` is being stripped from the generated links, thus not becoming keyboard accessible. This could very well be a bug in our system, and we're looking into it, but it certainly is strange.

**Comment by karatekaneen** [comment]
We encountered a problem similar to this but we can only reproduce it in Firefox (v79, no extensions) and Safari running on Mac, other browsers and OS did not have any issues. 

I first assumed this was an issue with Vuetify but after further investigation we learned that the router-links (without any button) did not focus either when navigating with tab.

https://codepen.io/karatekaneen/pen/QWNpZmy?editors=1111
