### ISSUE TITLE
Special character + is automatically removed from query string

### ISSUE THREAD

**Issue by mrksbnch** [vuejs/vue-router#2642]
### Version
3.0.2

### Reproduction link
[https://codesandbox.io/s/zkl0jwwk43](https://codesandbox.io/s/zkl0jwwk43)

### Steps to reproduce
Add a query string with the special character "+" to the URL in Codesandbox, e.g. add "?email=test+test@test.com" to the end of the URL: https://zkl0jwwk43.codesandbox.io/?email=test+test@test.com

### What is expected?
I can access the query parameter "test" with `this.$route.query.test` to get the value "test+test@test.com".

### What is actually happening?
When I try to get the value of the query parameter "test" I only get "test test@test.com" (space instead of "+").

**Comment by posva** [comment]
This is expected `+` produces spaces, you have to encode it with encodeURIComponent which yields `%2B`

**Comment by mrksbnch** [comment]
@posva Thanks for checking. Does only "+" produce spaces or any other special character as well? 

I'm also not sure why it's expected that "+" produces spaces. If I e.g. try to go to https://vuejs.org/?parameter=test+test@test.com and type `window.location.search` in the console, I get the expected string "?parameter=test+test@test.com" and not "?parameter=test test@test.com". Any reason why Vue Router behaves differently?

**Comment by posva** [comment]
A bit long to explain but this does it pretty well: https://stackoverflow.com/questions/1211229/in-a-url-should-spaces-be-encoded-using-20-or

**Comment by quannt** [comment]
Saving future readers a click

https://www.w3.org/Addressing/URL/uri-spec.html

> Within the query string, the plus sign is reserved as shorthand notation for a space. Therefore, real plus signs must be encoded. This method was used to make query URIs easier to pass in systems which did not allow spaces.
