### ISSUE TITLE
Route params not passed when staying on same page

### ISSUE THREAD

**Issue by rderimay** [vuejs/vue-router#2644]
### Version
3.0.2

### Reproduction link
[https://jsfiddle.net/1946Leau/4/](https://jsfiddle.net/1946Leau/4/)

### Steps to reproduce
When defining routes which do not contain a parameter which is passed in the route params, the component params are updated only when coming from another route. In short, when the route url does not change, nothing is updated.

If you call `$router.push({ name:'a', params: { foo: 1 } })` and `$router.push({ name:'a', params: { foo: 2 } })` alternatively, the value of `foo` passed to the component will be updated only if `:foo` is included in the route url (Example B in Fiddle) or if you force an update by using a random query str (Example C in Fiddle)

### What is expected?
I will expect to have `foo` passed also in the case it is not included in the route url.
At least, having a way to force the update without the trick with the query string would be nice.

### What is actually happening?
`foo` is updated only the first time

**Comment by posva** [comment]
params must be defined in the route in order to work: `/route/:foo`

**Comment by rderimay** [comment]
Yes of course. But.
1. It works already without being defined in the route, if you come from another route
2. It would be a nice enhancement and nice way to pass additional parameters you dont want to get reflected in the route ?
