### ISSUE TITLE
Buggy Chromium altKey persistence in touch events prevents router-link to act properly

### ISSUE THREAD

**Issue by epaterlini** [vuejs/vue-router#2649]
### Version
3.0.2

### Reproduction link
[http://link-not-needed](http://link-not-needed)

### Steps to reproduce
On Kubuntu 18.04, using Chromium 72, do the following:
- setup a simple vue-router view and some links
- open that page with Chromium and try the links with touch events, it works
- then press Alt-Tab to switch to another application and switch back to Chromium

### What is expected?
Router links should work as expected

### What is actually happening?
Router links are working if triggered with mouse events.
If triggered via touch events, Chromium incorrectly sets "altKey" to true in the original DOM event and that prevents router-link to complete (due to this first line in guardEvent function:
if (e.metaKey || e.altKey || e.ctrlKey || e.shiftKey) { return } )

---
Don't know also if this affects other users, for my use case for now I have commented out the modifier keys check in "guardEvent"
(vue-router.esm.js)

I built a custom PC equipped with Linux and a touchscreen and encountered this "behaviour" while testing the app.
I know that this may not be related with vue-router, just asking if my workaround is feasible and can be introduced eventually in the codebase.
I do not test it with other versions of Chrome or other browsers.

**Comment by posva** [comment]
this seems more like a bug with the browser or os but touch events are simulated in desktop anyway.

BTW repros are always needed
