### ISSUE TITLE
Hash router remove initial slash not working

### ISSUE THREAD

**Issue by ghost** [vuejs/vue-router#2651]
### Version
3.0.1

### Reproduction link
[https://github.com/kingofdelphi/vue-realworld-example-app/blob/master/src/router/index.js](https://github.com/kingofdelphi/vue-realworld-example-app/blob/master/src/router/index.js)

### Steps to reproduce
1. yarn install
2. yarn serve

### What is expected?
Clicking on links should change the address bar properly.
Typing the address on address bar should route to the proper page.
Browser refresh should not change url i.e. url must stay same on browser refresh / reload.

### What is actually happening?
Clicking on links is changing the address bar properly with proper route(this is expected behavior)
Typing the address on address bar doesn't route to the proper page.
Browser refresh should not convert /#url to /#/url ie do not add slash automatically. 

---
I had successfully used react-router to solve the problems listed above, but I can't seem to get it to work with vue-router.

**Comment by posva** [comment]
You need to put an initial path in your routes `path: '/'`

**Comment by ghost** [comment]
> You need to put an initial path in your routes `path: '/'`

Hi, actually, I want to remove the / after /#. For example /#/user should be /#user

**Comment by posva** [comment]
that's not possible, that would be the actual hash of the route, we need that slash to make the difference

**Comment by ghost** [comment]
> that's not possible, that would be the actual hash of the route, we need that slash to make the difference

I've actually done this with react router. So, I know its possible.

**Comment by Snehasish-Konger** [comment]
Can I remove the "/#/" thing to "/"? is this possible in HashRouter?
