### ISSUE TITLE
通过url和通过导航传递的query类型不统一

### ISSUE THREAD

**Issue by zx06** [vuejs/vue-router#2658]
### What problem does this feature solve?
通过url访问时，路由接收到的query为string。
但是通过vue-router进行导航时，接收到的query却是传递的参数实际类型。
![image](https://user-images.githubusercontent.com/12474586/54586550-609d2680-4a58-11e9-8640-d38fd5c7df7d.png)
![image](https://user-images.githubusercontent.com/12474586/54586621-93471f00-4a58-11e9-9ac3-418b837782a9.png)

### What does the proposed API look like?
希望通过这两种方式传递的query类型一致

**Comment by posva** [comment]
The only one that will be handled by default are numbers, this is already being tracked
