### ISSUE TITLE
SSR app with async components, 500s when using component styles

### ISSUE THREAD

**Issue by OliverJEvans** [vuejs/vue-router#2660]
### Version
3.0.1

### Reproduction link
[https://github.com/OliverJEvans/vue-ssr-issue](https://github.com/OliverJEvans/vue-ssr-issue)

### Steps to reproduce
After cloning, run commands in terminal ... `npm install`, `npm run build` then `npm run start`. 

Open browser at http://localhost:8080/ and observe 500 error.

Server console shows `[vue-router] Failed to resolve async component default: ReferenceError: document is not defined`

In file Hero.vue, remove styles on lines 7-10 and re-run `npm run build` and `npm run start`. 

Server runs correctly

### What is expected?
I expect hero component to have green background and allow nested components to have styles.

### What is actually happening?
Server 500s with `document is
 not defined` error message

---
When non-lazy loading the views in router.js, everything works fine. Something to do with lazy loading those chunks in breaks nested component styles. 

This issue might not be specific to vue-router but as it is the one throwing the error, I thought I'd start here for assistance. Thank you

**Comment by Nettsentrisk** [comment]
This is most likely not a problem with vue-router, but some code trying to load the stylesheet via document-methods on the server-side, such as Mini CSS Extract Plugin or similar.
