### ISSUE TITLE
$router Optional query parameters

### ISSUE THREAD

**Issue by baturali** [vuejs/vue-router#2661]
### What problem does this feature solve?
The main problem I am experiencing is the unnecessary query parameters inside `$router.replace()`. Now, assuming I am inserting multiple parameters or a JSON object inside the `query:`, some of the paramters might have null, undefined or empty values. It would be great if we had an option to simply avoid showing these parameters in the URL if they are not wanted.

### What does the proposed API look like?
As an example I have the below `replace()`
```
const hasBrandQuery = 'brandIds: 5'
const hasProductQuery = null
this.$router.replace({
  query: {
    hasBrandQuery,
    hasProductQuery
  }
})
```
The problem I have with the code above is that I don't want `hasProductQuery` to be shown in my URL, simply because it has no specific value and it should only show `hasBrandQuery`.
I think this would be a good feature if we had an option to enable such a thing.

**Comment by posva** [comment]
you can customize the stringifyquery function but right now, to remove a parameter, you have to either delete it from the object or use undefined

**Comment by baturali** [comment]
Well then, thank you...
