### ISSUE TITLE
Translate docs to PT-BR

### ISSUE THREAD

**Issue by thayannevls** [vuejs/vue-router#2670]
### What problem does this feature solve?
https://vuejs.org/ and https://vuex.vuejs.org/ docs already are translated to PT-BR, would be interesting to Vue-Router be translated to Brazil Portuguese too.

### What does the proposed API look like?
I want to start translating, can I make a fork and start working on this? I can start translating the `docs/README.md`, `docs/installation.md` and the `docs/api/README.md`

**Comment by posva** [comment]
The translated effort for docs is at https://github.com/vuejs-br/vue-router
