### ISSUE TITLE
vue-router not working when accessed directly on URL address of the browser

### ISSUE THREAD

**Issue by lightzane** [vuejs/vue-router#2671]
### Version
3.0.2

### Reproduction link
[https://github.com/vuejs/vue-router/issues/2668](https://github.com/vuejs/vue-router/issues/2668)
Also logged issue on [https://github.com/zeit/serve/issues/515](https://github.com/zeit/serve/issues/515)
because I do not know where the root cause of issue is (either on ```npm run build``` or ```serve -s```). But it seems working when running on ```npm run serve```.

### Steps to reproduce
1. npm run build
2. npm install -g serve
3. serve dist
4. visit localhost:5000
5. click the router-link to /route/to/login = component correctly displayed
6. access the route directly in URL address (or just refresh the page) localhost:5000/route/to/login = this shows issue, 404 page is displayed

### What is expected?
Access the route directly in the URL (localhost:5000/route/to/login) to display the Login component

### What is actually happening?
404 page is displayed.
**Important to read notes below for more understanding of the issue.**

---
# Important Notes

Compare:
When clicking on a ```<router-link to="/route/to/login">Login</router-link>```
The Login component is displayed

**BUT** when refreshing the page **OR**
When accessing the URL directly in the browser (localhost:5000/route/to/login)
404 page is displayed. (**Note** that this is working on ```npm run serve``` but not on ```serve``` at dist folder)

See issue #2668 for more details of the code.

**Comment by posva** [comment]
You have to preperly configure your server to use history mode. This is in the docs

**Comment by lightzane** [comment]
> You have to preperly configure your server to use history mode. This is in the docs

@posva please need help on configuring the serve to use history mode.

Are you talking about the ```serve.json``` ? Because I'm running it only using ```serve``` (```npm install -g serve```)

It still won't work. Please I need some help.
I already tried the following:
```serve -s```

with and without:

In ```serve.json``` 
```
{
	"renderSingle": true,
	"rewrites": [
		{
			"source": "/route/to/login",
			"destination": "/index.html"
		}
	]
}
```

**Comment by chris-dura** [comment]
@timelights -- did you figure this out?

**Comment by nezlicodes** [comment]
@chris-dura did YOU figure this out yourself? I am facing the same problem.

**Comment by arifikhsan** [comment]
how did you guys solve this problem?

**Comment by chris-dura** [comment]
@nezlicodes @arifikhsan -- This was such a long time ago, I'm not sure precisely what I was seeing... however, in some quick testing, I _think_ everything is working for me now...

So, just as an FYI...

- I'm using `serve@^11.2.0`
- And run it with the `--single` flag: `serve --single --listen 5000 dist`

My `vue-router` setup is pretty much what comes with `@vue/cli@4.x`...

```
// src/router/index.ts

import Vue from 'vue';
import VueRouter from 'vue-router';
import Home from '../views/Home.vue';
import NotFound from '../views/404.vue';

Vue.use(VueRouter);

const routes = [
  { path: '/', name: 'home', component: Home },
  { path: '/', name: 'about', component: About },
  ...
  // Separated into two routes so that you can also programmatically
  // direct the user to the /404 if missing some data, etc.
  { path: '/404', component: NotFound },
  { path: '*', redirect: '/404' }
];

const router = new VueRouter({
  mode: 'history',
  base: process.env.BASE_URL,
  routes
});

export default router;
```

**Comment by Mexko** [comment]
https://router.vuejs.org/guide/essentials/history-mode.html

**Comment by Funminiyi-debug** [comment]
Why not try to update your component to watch the route params

**Comment by giocarmine** [comment]
Did anyone have this problem in an ASP.NET Core project? 
What i managed to do there was to catch every request and redirect to the home page.. but this is not ideal, as i would like have the vue router to process it..

**Comment by zohojayesh** [comment]
how to make it work in case when you are hosting the production build on a godady hosting ?

**Comment by engrnasir** [comment]
I am getting same issue, while using vue3 + vite 
`const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes,
});`

This is the code for router 
I deployed the app on vercel and hostinger but still have same issue
anyone can help me?

**Comment by Glass109** [comment]
This problem should be resolved with a redirect on the server configuration, check your hosting provider documentation for configuring Client-Side routing
Example: https://docs.render.com/deploy-vue-js#using-client-side-routing
Another "solution " would be changing the WebHistory mode to Hash
https://router.vuejs.org/guide/essentials/history-mode.html

**Comment by liudonghua123** [comment]
I have encountered the similar issue on github-pages (https://liudonghua123.github.io/it-tools/), when I search and goto `"base64 file converter"`, the url is changed to https://liudonghua123.github.io/it-tools/base64-file-converter and the UI is normal. But when I share this link to friends, they couldn't open directly. They also need to navigate from the root page/url.

Is this a limit of [html5-mode](https://router.vuejs.org/guide/essentials/history-mode.html) of vue-router. So I need to change to hash-mode?

**Comment by liudonghua123** [comment]
> I have encountered the similar issue on github-pages (https://liudonghua123.github.io/it-tools/), when I search and goto `"base64 file converter"`, the url is changed to https://liudonghua123.github.io/it-tools/base64-file-converter and the UI is normal. But when I share this link to friends, they couldn't open directly. They also need to navigate from the root page/url.
> 
> Is this a limit of [html5-mode](https://router.vuejs.org/guide/essentials/history-mode.html) of vue-router. So I need to change to hash-mode?

I changed history mode of vue-router from html5-mode to hash-mode, see the [changes](https://github.com/liudonghua123/it-tools/commit/26bca1f2ec7d0b643bd4ad9fb5316d01481cf2e5), and it worked now, the link I can share changed to https://liudonghua123.github.io/it-tools/#/base64-file-converter.
