### ISSUE TITLE
SSR cannot get matched component (router.getMatchedComponents())

### ISSUE THREAD

**Issue by perezpz** [vuejs/vue-router#2675]
### Version
3.0.2

### Reproduction link
[https://jsbin.com/qiduticizu/edit?html,js,output](https://jsbin.com/qiduticizu/edit?html,js,output)

### Steps to reproduce
SSR gets matched component  is function when I use router redirect.

(by router.getMatchedComponents())

### What is expected?
The matched is a component,  and component.asyncData isn't undefined when asyncData was set in logic components.

### What is actually happening?
matched components is function and  asyncData is undefined.

function is:
```
function VueComponent (options) {
      this._init(options);
    }
```

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

when reporting bugs, a boiled down runable repro (can be a simple js file) is necessary

**Comment by perezpz** [comment]
@posva I think it's a bug.

**Comment by Madd0g** [comment]
This is happening with version 3.1.3
in `router.onReady`, I'm calling `router.getMatchedComponents` and getting back `[null]` (so all the examples that check `.length` fail because there's a null there.

I'm using SSR and also vue-class-component, not sure if it's relevant

**Comment by jsonleex** [comment]
I get the similar problem, is there a solution?
