### ISSUE TITLE
Page refresh after addRoutes method fails to load the new route

### ISSUE THREAD

**Issue by EvanBurbidge** [vuejs/vue-router#2677]
### Version
3.0.1

### Reproduction link
[https://github.com/EvanBurbidge/vue-router-tester](https://github.com/EvanBurbidge/vue-router-tester)

### Steps to reproduce
- Clone the project
- Install dependencies
- Run the project
- Navigate to /testing
- reload the page
- then navigate to the about page
- navigate to the foo link
- reload the page

### What is expected?
When I reload the page the tester component is fetched for the /testing route. Or when I navigate to the foo component and reload the page I should see the same component load. 

### What is actually happening?
When we reload the page I expect the component assigned to that route to be present, however it does not load on page refresh, the router is setup within a parent component and on page refresh this data is lost. Looking at the router.options.routes I can see that it is not modified with a new route when we call the addRoutes method. When trying to store the configuration in localStorage / sessionStorage we lose the import part of the component.

---
While this method is handy for adding new routes to the router, you will never know when a user is going to reload their browser, if some data goes wrong or something like that, therefore we should probably ensure that this method allows us to easily add new routes that will persist through a page refresh, if I am 2/ 3 child levels deep into a set of components then when I refresh I should see those components not a blank screen.

**Comment by posva** [comment]
addRoutes is dynamic and therefore lost on reload. In your case it looks like you may not need it

Also, router.options is read only and static

**Comment by EvanBurbidge** [comment]
@posva that was just to showcase the route being lost, in the main application I am working on in my day job we are trying to introduce it but the loss of routes is proving difficult. We have an instance where we have a monorepo with some parent applications and child applications which contain their own routing configurations, at the moment we're registering the routes on the consuming applications by hand e.g. import { childAppRoutes } from 'childApp' and then using a spread across the main router instance, would be nicer if there was someway to automatically register these new routes that would persist. 

Is there anything in the pipeline that could lead to this?

**Comment by posva** [comment]
Persisting dynamically added routes is something you will have to implement on your own like saving the config in local storage or similar then read them and add them after creating the router but before mounting the root instance.
