### ISSUE TITLE
Error on decoding ISO-8859-1 words

### ISSUE THREAD

**Issue by claudiolcastro** [vuejs/vue-router#2679]
### Version
3.0.1

### Reproduction link
[https://codepen.io/anon/pen/ZPdOxa?editors=1010](https://codepen.io/anon/pen/ZPdOxa?editors=1010)

### Steps to reproduce
First click on the "Test Ok" link and see the route populate the $this.route.query.q. Then, click on the "Test fail" and see the route chash and not populate the $this.route.query.q.

### What is expected?
It was expected that the router converted the "test%E9" to "testé" and populate the this.$route.query.q. 

### What is actually happening?
Vue-router is failing to populate the this.$route.query.q.

---
By debugging the code,  I realized  that the `decodeURIComponent` does not work properly with  ISO-8859-1 words. In other hand, the `unescape` method works well.

Example below:

```
text = 'test%E9'
> "test%E9"

decodeURIComponent(text)
> VM568:1 Uncaught URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at <anonymous>:1:1

unescape(text)
> "testé"
```

**Comment by posva** [comment]
Yeah, the correct encoding of `é` is `%C3%A9`. You can check that with the encodeURI/decodeURI function. As the error says, that's a malformed URI and is not allowed (by the browser)

**Comment by claudiolcastro** [comment]
Hey @posva  thanks for answer. I'm working with Vuejs on a old legacy project that's use latin-1 encode (ISO-8859-1), so, unfortunately, I couldn't use the correct encoding.

For those who might have the same problem: By searching on the docs I discovered how to pass a  `parseQuery` property on the route file that receives a function, so that a I  could "override" the original `decodeURIComponent`. I don't know if it's the best way to do it, but it's worked for me. =)

Here is my code as an example:

```
parseQuery: (query) => {
    const res = {};
    query = query.trim().replace(/^(\?|#|&)/, '');
    if (!query) {
      return res;
    }
    query.split('&').forEach((param) => {
      const parts = param.replace(/\+/g, ' ').split('=');

      const key = decodeURIComponent(parts.shift());

      let val = '';
      if (parts.length > 0) {
        try {
          val = decodeURIComponent(parts.join('='));
        } catch (e) {
          val = unescape(parts.join('='));
        }
      } else {
        val = null;
      }

      if (res[key] === undefined) {
        res[key] = val;
      } else if (Array.isArray(res[key])) {
        res[key].push(val);
      } else {
        res[key] = [res[key], val];
      }
    });

    return res;
  },
```

**Comment by ORCohen-il** [comment]
fdsbxcbxc
