### ISSUE TITLE
Multiple guards on one route

### ISSUE THREAD

**Issue by GoGurtPrime** [vuejs/vue-router#2687]
### What problem does this feature solve?
My application contains routes that require multiple layers of validation to run before proceeding to them. Some of my routes must have an 'Organization' selected. If a user attempts to hit the route without having an organization selected, they are redirected to another route to set up an organization. All of my routes require that a user is authenticated, or else they are redirected to my auth server.

I understand that it is possible to nest each of my guards in one single guard; however, I have unique combinations of guards per route (not all routes have the same guards), which makes it difficult to express the requirements of a route without writing a guard to contain each guard the route requires (versus something easier and more expressive, such as an array).

In my opinion, this is clearly a responsibility of the framework to support this. I have heard the arguments that you can write one guard that contains each guard inside of it, but is that really a solution when we have multiple people asking for this feature? If many consumers of Vue require this feature, and they're all writing their own implementations to support this functionality, it should be absorbed into the framework.

The problem is common enough to justify given the strong support demonstrated by Issue #721

### What does the proposed API look like?
```
let router = new VueRouter({
    routes: [
        {
            path: '/dashboard',
            name: 'dashboard',
            component: ...,
            beforeEach: [guard1, guard2],    // Each guard is a function accepting (to, from, next)
        }
});
```

**Comment by posva** [comment]
Don't worry I will create the issue myself. It's something already intended

**Comment by GoGurtPrime** [comment]
Thanks for your help, there is an issue with posting feature requests at the moment using the Issue Helper. I'm not sure why it wasn't working, but it wasn't autofilling the details passed to Githubs create issue page in the query params of the url.
