### ISSUE TITLE
Expose a way to get route string from a router object.

### ISSUE THREAD

**Issue by trandaison** [vuejs/vue-router#2690]
### What problem does this feature solve?
I think it would be nice if there is a helper function that parse an object to an URL based on matched route from routers list. 

Currently, we have to use `<router-link>` and bind that object to `:to`, but what if I want to bind a `<a :href="">`?

```html
<a :href="`/video/${video.id}`?t=${video.t}`">
```
This is ok. However, sometimes, the route path changes (for example: `/videos` instead of `/video`), in that case we have to find all the `<a>` and replace with the new path, I don't think it's a good idea.

But if we use the route name instead of the path, it will work despite of changing route path.

### What does the proposed API look like?
```js
this.$router.parseURL({ name: 'Video', params: { id: 'funny-video' }, query: { t: 200 } })

// /video/funny-video?t=200
```

**Comment by posva** [comment]
Use the resolve method
