### ISSUE TITLE
How can I use multiple, or parameterized baseurl?

### ISSUE THREAD

**Issue by sarkiroka** [vuejs/vue-router#2693]
### What problem does this feature solve?
I have a page with many many (near 100) routes, and every route depends on a parameter. So my router config something like that:

base: '/static'
...
path: '/:productId/x' -> for module x
path: '/:productId/y' -> for module y
...
Can I use the base for store parameter?
For example something like this:

base: '/static/:productId'
...
path: '/x' -> for module x
path: '/y' -> for module y
...
Because less code less errors :)

### What does the proposed API look like?
```
{
...
base: '/static/:productId'
...
}
```

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You can have a parent route with children and set it's component option to a component that just renders it children

```js
{ path: '/:param', component: { render: h => h('RouterView') }, children: [] }
```
