### ISSUE TITLE
I cant use ':,;' this characters

### ISSUE THREAD

**Issue by ademyalcin27** [vuejs/vue-router#2696]
### Version
3.0.1

### Steps to reproduce
I want to use ';:' characters in my URL but it's updating after the query  push URL;
is there any way how to fix it ?

### What is expected?
http://localhost:8080/balbal?checkin=2019-04-24&checkout=2019-04-30&pax=2&filters=konaklama_tipi:ultra-hersey-dahil,kahvalti-ingiliz-tarz;tesis_tipi:su-parki

### What is actually happening?
http://localhost:8080/antalya-bolge-kemer-otelleri?checkin=2019-04-24&checkout=2019-04-30&pax=2&filters=konaklama_tipi%3Aultra-hersey-dahil,kahvalti-ingiliz-tarzi%3Btesis_tipi%3Asu-parki

is there any way how to fix it ?

**Comment by posva** [comment]
Those characters are encoded

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by ademyalcin27** [comment]
> Those characters are encoded
> 
> Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

Actually I checked some forms but I didnt found. Thank you I will check again.

**Comment by LinusBorg** [comment]
> Actually I checked some forms but I didnt found.

You can ask questions on the forum. That's what it's for
