### ISSUE TITLE
[Docs/zh] 导航守卫解析流程的语义描述问题

### ISSUE THREAD

**Issue by pot-code** [vuejs/vue-router#2697]
### Version
3.0.3

### Reproduction link
[https://router.vuejs.org/zh/guide/advanced/navigation-guards.html#%E5%AE%8C%E6%95%B4%E7%9A%84%E5%AF%BC%E8%88%AA%E8%A7%A3%E6%9E%90%E6%B5%81%E7%A8%8B](https://router.vuejs.org/zh/guide/advanced/navigation-guards.html#%E5%AE%8C%E6%95%B4%E7%9A%84%E5%AF%BC%E8%88%AA%E8%A7%A3%E6%9E%90%E6%B5%81%E7%A8%8B)

### Steps to reproduce
None

### What is expected?
12. 调用 beforeRouteEnter 守卫中传给 next 的回调函数，用创建好的组件实例作为回调函数的参数传入

### What is actually happening?
12. 用创建好的实例调用 beforeRouteEnter 守卫中传给 next 的回调函数。

---
这里的“用创建好的实例”，是个很有歧义的描述，是创建好的组件实例，还是路由实例？

**Comment by posva** [comment]
If you have a suggestion to the docs, please open a pull request
