### ISSUE TITLE
multiple & named router-views

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vue-router#27]
``` js
router.on('/route', {
  namedViews: {
    a: { component: 'view-a' },
    b: { component:  'view-b' }
  }
})
```

``` html
<router-view name="a"></router-view>
<router-view name="b"></router-view>
```

**Comment by AStaroverov** [comment]
It isn`t implemented?

**Comment by juukie** [comment]
Is this stil a feature? It would be nice to be able to target a specific router-view like in angularjs routing.

**Comment by iamjstates** [comment]
This does not work yet correct - it would be nice to have this feature like in angularjs and emberjs. :/
