### ISSUE TITLE
Array from query

### ISSUE THREAD

**Issue by afabros** [vuejs/vue-router#2701]
### Version
3.0.3

### Steps to reproduce
https//www.websitename.com?x%5B%5D=1&x%5B%5D=2

### What is expected?
this.$route.query.x[]
should return an array.

### What is actually happening?
correctly inspected by browser:   x[]: Array[2] 0: “1” 1: “2”
but when getting this array, this line is not compiled: this.$route.query.x[]
ERROR: Unexpected token 

---
Is it possible to get array from this.$route.query

**Comment by afabros** [comment]
closing this issue. %5B%5D is added when name of the input is x[], but if the name of the input is only x, the vue parse the array correctly.

**Comment by afabros** [comment]
reopening this issue. but without the  %5B%5D , the server cannot recognize the server request as an array.

what is happening:
https//www.websitename.com?x[]=1&x[]=2 
or
https//www.websitename.com?x%5B%5D=1&x%5B%5D=2
is seen by this.$route.query.x as undefined
but seen by server processing $_GET correctly, x is an array

while:
https//www.websitename.com?x=1&x=2 
is correctly seen by this.$route.query.x as an array
but not the server processing $_GET.

**Comment by posva** [comment]
that's because in PHP arrays in queries are handled differently than in browsers. You can use a custom querystringify and queryparse to adapt it to your needs (https://router.vuejs.org/api/#parsequery-stringifyquery). You can use packages like qs or query-string

**Comment by afabros** [comment]
what's confusing is that the array is correctly being recognized by the vue inspector on the browser, but not this.$route.query.x[] .
<img width="223" alt="Screen Shot 2019-04-10 at 9 30 13 PM" src="https://user-images.githubusercontent.com/805713/55878783-1848d280-5bd8-11e9-846b-d1e810651cb3.png">

**Comment by YSavir** [comment]
@posva Related to the above, I'm noticing this behavior:

When visiting the URL: `https//www.websitename.com?x[]=1&x[]=2`, `this.$route.query['x[]']` is an array with `['1', '2']`.

However, when visiting the URL `https//www.websitename.com?x[]=1`, `this.$route.query['x[]']` is the string `'1'`.

Is this variation in data type intentional? I would expect that search params ending in `[]` would always be an array, even if only one entry is provided.

**Comment by posva** [comment]
yes, that's intentional. There is no special meaning in the names of the variables like having `[]` at the end
