### ISSUE TITLE
router-link-active class is removed if the route is not exact

### ISSUE THREAD

**Issue by madmoizo** [vuejs/vue-router#2707]
### Version
3.0.3

### Reproduction link
[https://codesandbox.io/embed/zrjv12l0rp](https://codesandbox.io/embed/zrjv12l0rp)

### Steps to reproduce
- Click on Home
- Click on Nested 2

### What is expected?
Home should have `router-link-active` class

### What is actually happening?
`router-link-active` is removed from Home on route change

**Comment by posva** [comment]
this is working as expected, the `exact` prop is what adds that behaviour

**Comment by madmoizo** [comment]
@posva the repro was wrong, I fixed it, the issue is a bit more complex.
It seems related to redirect

**Comment by madmoizo** [comment]
@posva may you give it an other try ?

**Comment by posva** [comment]
Do the redirect in a child instead, that makes more sense 🙂 

```js
children: [
        {
          path: "home",
          name: "home",
          component: HomePage,
          children: [
            { path: '',  redirect: {
              name: "page-1"
            }},
            {
              path: "page-1",
              name: "page-1",
              component: Page1
            },
            {
              path: "page-2",
              name: "page-2",
              component: Page2
            }
          ]
        }
      ]
```

**Comment by madmoizo** [comment]
It means `router-link-active` works only in some cases since v3.0.3 and it's expected ?

**Comment by madmoizo** [comment]
Glad to see that an issue is considered an issue after 3 reports https://github.com/vuejs/vue-router/issues/2724
