### ISSUE TITLE
push to route with async component before create root vue instance will fail

### ISSUE THREAD

**Issue by noe132** [vuejs/vue-router#2712]
### Version
3.0.3

### Reproduction link
[https://jsfiddle.net/qLz5ew9t/](https://jsfiddle.net/qLz5ew9t/)

### Steps to reproduce
1. create a vue-router instance
2. call `router.push` to some async-component-route
3. create the root vue instance

### What is expected?
`router.push` success

### What is actually happening?
`router.push` was aborted

---
If we change step2 to push to some sync-component-route, then the push would be success.  
Or, exchange step2 with step3, call `router.push` after create the vue instance, `router.push` will also success  
Is this intended or a bug or not allowed use cases?

**Comment by posva** [comment]
I'm reverting this because the fix introduces some regressions.
The asyncPush should be wrapped in a `router.onReady`. I feel that this often bites people so I'm labelling this as a doc issue
