### ISSUE TITLE
nested 的路由回退问题？

### ISSUE THREAD

**Issue by hojas** [vuejs/vue-router#2714]
### Version
3.0.3

### Reproduction link
[http://sample.com](http://sample.com)

### Steps to reproduce
路由跳转：`/jobs/` -> `/posts/` -> `/posts/1/` ，然后点击浏览器的返回按钮，页面会返回到 `/jobs/` 而不是 `/posts/`。好像返回时，nested 的路由会被直接跳过？

### What is expected?
期望是返回到 `/posts/` 页面

### What is actually happening?
返回到了 `/jobs/` 页面

**Comment by posva** [comment]
That's not a valid repro. Also please, write the issue in English.
Before opening a new issue, make sure to check  existing  issues as well :)
