### ISSUE TITLE
Make forward slash optional on v-link

### ISSUE THREAD

**Issue by belisarh** [vuejs/vue-router#272]
Well, I couldn't come up with a better title for this so here we go:

Let the route map be:

```JS
let routes = {
  '/auth': {
    component: { template: '<router-view></router-view>' },
    subRoutes: {
      '/login': { component: login },
      '/register': { component: register },
      '/reset': { component: reset }
    }
  }
};
```
Let '#loginSubRoute' be an anchor element in the root Vue instance pointing to login as so:

```HTML
<a v-link="{ path: 'auth/login }" id="loginSubRoute"></a>
```
Let dummy.dom be the domain. Clicking once on on loginSubRoute we get to:

```
http://dummy.dom/auth/login
```
Clicking another time we get:
```
http://dummy.dom/auth/auth/login
```
For every time you click another 'auth' will be added to the path.
Trying to avoid this behavior by setting the append flag to false, does not help.
Setting the links with the forward slash on v-link fixes it.

Would it make sense to resolve the path with or without the forward slash, thus making it optional in the v-link directive or is the syntax tied to some core functionality?

**Comment by yyx990803** [comment]
You should either use absolute path, or ensure that a relative path is always called at the same location. Calling relative paths at different location is obviously going to result in different destinations.

Another choice is using a named route instead.
