### ISSUE TITLE
vue-router 3.0.5 router onComplete no longer executed

### ISSUE THREAD

**Issue by twickstrom** [vuejs/vue-router#2721]
### Version
3.0.5

### Reproduction link
[https://codesandbox.io/embed/74y8ok1kpj](https://codesandbox.io/embed/74y8ok1kpj)

### Steps to reproduce
In a vuex action I have a simple block of code:

In my action.js file for my auth module I have the following block of code:

```
import Vue from 'vue'

login ({ commit }, data) {
  Vue.router.push({
    name: 'dashboard'
  }, () => {
    store.dispatch('app/loaded')
  })
}

```
### What is expected?
The onComplete callback of the router.push call should be executed.

### What is actually happening?
The onComplete callback of the router.push call should be executed.

---
I rolled back to 3.0.4 and this issue went away. This is code that I have not touched in 6 months and has had many vue-router upgrades without issue.

The reproduction link is a very simplified version simply click on "Click me for callback failure" you should get an alert showing the click event was executed. The route will change too: /#/foo but the callback of alert('callback') is never executed.

**Comment by LinusBorg** [comment]
Works fine here in FF and Chrome.
![grafik](https://user-images.githubusercontent.com/1444526/56267172-5a00de00-60ee-11e9-9296-a8ce80a49b17.png)

**Comment by posva** [comment]
thanks, it's probably related to the fix introduced in #2712

**Comment by posva** [comment]
the callback wasn't passed correctly as the second argument:

```js
this.$router.push({ name: 'foo' }, function () {
        // This will never execute
        alert('callback');
      })
```

it was passed like this:

```js
this.$router.push({ name: 'foo', function () {
        // This will never execute
        alert('callback');
      }})
```

**Comment by twickstrom** [comment]
@posva 

Not according to the documentation:
`router.push(location, onComplete?, onAbort?)`

https://router.vuejs.org/api/#router-push

Further, in my own codebase this was working fine for over a year until I upgraded to 3.0.5. Rolling back to 3.0.4 "fixed" my issue.

```
import Vue from 'vue'

login ({ commit }, data) {
  Vue.router.push({
    name: 'dashboard'
  }, () => {
    store.dispatch('app/loaded')
  })
}
```

**Comment by twickstrom** [comment]
@posva,

Sorry about the type in my example. It's weird that did sem to resolve the simplified version. In my code base however this problem persists but only in 3.0.5. I will dig deeper to see why.

**Comment by lukeajtodd** [comment]
I'm also having a similar issue, tried it with 3.0.3 and 3.0.6. May be something specific to the codebase I'm working on but I'll try and get an example of it happening up later.

To sum it up though. The callback doesn't seem to fire for any reason and as far as I can see my routes will always eventually resolve so I don't think it's an issue with the guards.

**Comment by AlexanderBredun** [comment]
@posva it still doesnt work, event if you change here https://codesandbox.io/embed/74y8ok1kpj to this
`this.$router.push({ name: 'foo' }, function () {
        // This will never execute
        alert('callback');
      })`
it doesnt work
