### ISSUE TITLE
Possible bug in beforeRouteEnter

### ISSUE THREAD

**Issue by hraynaud** [vuejs/vue-router#2727]
### Version
3.0.2

### Reproduction link
[https://github.com/hraynaud/vue-beforeenter](https://github.com/hraynaud/vue-beforeenter)

### Steps to reproduce
Build the project.
Open the project homepage at localhost:8080
Open chrome dev tools
Open the sources tab and type Command -P to get source list
Search for vue.runtime.esm.js
select the webpack:///./node_modules/vue/dist/vue.runtime.esm.js?2b0e file (Note your query has will probably be different)
Set a breakpoint in the for loop of the flushCallbacks method (in my distribution the line number is 1906
One the app login page click the projects link next to the login button
Step through the app

### What is expected?
The next([NEW ROUTE]) call of the routeBeforeEnter should abort the the clicked upon route (projects) and not render the component, at all as per the docs.

### What is actually happening?
The component is rendered and then a route redirect occurs rendering the route specified in the next call.

---
I'm new to vue js and I'm experimenting with how best to structure and  implement  routing.

**Comment by posva** [comment]
What you described in the readme:

> Basically calling `next((vm) => {vm.$router.push("/error")});`
>
> in the beforeRouteEnter hook. doesn't seem to abort the route but temporarily diplays it and then redirects to the desired route.

Is normal behaviour. You confirm the navigation and then push to a new location

To abort a navigation you need to call `next('/some-route')`
