### ISSUE TITLE
'redirect' to support async function 

### ISSUE THREAD

**Issue by JinboMa** [vuejs/vue-router#2729]
### What problem does this feature solve?
when i add the permission to router
i need get the permissionList in redirect function
so i need redirect function to support async.

### What does the proposed API look like?
```js
{
  // RouteConfig
  redirect async (to, next) {
    const routerConfig = await getRouterConfig()
    return routerConfig
  }
}
```

**Comment by posva** [comment]
The redirect is there to establish sync redirects, pretty much like a config. If you need an asynchronous redirect, you should do it in a guard like `beforeEach` or `beforeEnter`

**Comment by JinboMa** [comment]
> The redirect is there to establish sync redirects, pretty much like a config. If you need an asynchronous redirect, you should do it in a guard like `beforeEach` or `beforeEnter`

now, i have such a demand:

```js
const routerConfig = {
  path: '/a',
  component: A,
  children: [
    {
      path: 'b',
      name: 'B',
      component: B,
      permission: 'b'
    },
    {
      path: 'c',
      name: 'C',
      component: C,
      permission: 'c'
    }
  ]
}

function createPermissionRouter (router) {
  let { children = [] } = router
  let redirect = async (to, next) => {
    const permissionList = await getPermissionList()
    const redirectRouter = children.find(({ permission }) => permissionList.includes(permission))
    // Find the first child with permission，auto redirect.
    next(redirectRouter)
  }
  return {
    ...router,
    redirect,
    children.map(item => createPermissionRouter(item))
  }
}

new VueRouter({
  routes: createPermissionRouter(routerConfig)
})
```

why not `beforeEach` ?

because `redirect` before `beforeEach`, and I want automatic ‘redirect’,

so i want to 'redirect' support async function.

**Comment by AHIMOTU** [comment]
Is there a solution? I have the same problem.

**Comment by darkbasic** [comment]
I have a problem with the suggested solution: `beforeEnter` gets called only the first time you access a route. If you're inside a children route and you try to access the parent you won't be redirected because `beforeEnter` doesn't get called a second time.
