### ISSUE TITLE
Circular dependency in 'src\util\push-state.js'

### ISSUE THREAD

**Issue by aosnow** [vuejs/vue-router#2730]
### Version
3.0.3

### Reproduction link
[https://github.com/vuejs/vue-router/blob/dev/src/util/push-state.js](https://github.com/vuejs/vue-router/blob/dev/src/util/push-state.js)

### Steps to reproduce
https://github.com/vuejs/vue-router/blob/dev/src/util/push-state.js 
import { saveScrollPosition } from './scroll'

https://github.com/vuejs/vue-router/blob/dev/src/util/scroll.js
import { getStateKey, setStateKey } from './push-state'

### What is expected?
Can it be repaired?

### What is actually happening?
At compile time, there may be insufficient memory

---
please repaired it, thanks

**Comment by posva** [comment]
Thank you for your concern. I'm aware of the warning. Currently it doesn't cause a problem
