### ISSUE TITLE
beforeEach() not firing.

### ISSUE THREAD

**Issue by RemiKalbe** [vuejs/vue-router#2731]
### Version
2.6.0

### Reproduction link
[https://github.com/RemiKalbe/vue-router-issue](https://github.com/RemiKalbe/vue-router-issue)

### Steps to reproduce
Click on "Login" on the top.

### What is expected?
Same loading animation as when you click on the big blue login button. 
And you should see a console.log("Hello?").

### What is actually happening?
Nothing.

---
In router.js, beforeEach() is not firing. And I have no idea why.

I can't use CodeSandbox because it just don't work with stylus.

**Comment by posva** [comment]
Hey, sorry but that's too much for a repro. I can take a look if you update to latest vue router and provide a boiled down repro. You don't need stylus for the repro BTW :)

**Comment by RemiKalbe** [comment]
Here you are : https://codesandbox.io/s/7zp0q6y390
See, when you click on the login button, there is a loading bar on top, but if you click on the Login text on top, it just change the page, when it is supposed to also console.log("Hello?") and display the loading bar.

**Comment by RemiKalbe** [comment]
Also, you need to go on the page /Login or /Signup

**Comment by posva** [comment]
That's just the same code in codesandbox. A repro is the minimal code to show a repro. I wouldn't expect to see any of the extra components there for example

**Comment by RemiKalbe** [comment]
It's done, you can check it on https://codesandbox.io/s/1q7487mzlj
