### ISSUE TITLE
是否可以在跳转路由时可以把参数带到 url 以外的地方？

### ISSUE THREAD

**Issue by jamieYou** [vuejs/vue-router#2736]
### What problem does this feature solve?
react router 跳转路由时，除了可以把参数带到 url 上，还可以放在 state 里

参考 https://reacttraining.com/react-router/web/api/location

这种参数的特征是即使刷新网页，依然有效，即使它不是在 url 上的。
但是当 url 被分享时，这个参数是不会被带上的。
这样的参数只有在当前的会话才是有用的。

### What does the proposed API look like?
类似这样
```
push({
   path: '',
   query: {},
   params: {},
   state: {},
})
```

**Comment by posva** [comment]
Hey, I don't speak Chinese, can you open the issue in English? Thanks!
The issue doesn't seem to follow the issue reporting guidelines either. Could you please take a moment to read them before opening a new issue?
