### ISSUE TITLE
Is it possible to bring parameters outside the url when jumping routes?

### ISSUE THREAD

**Issue by jamieYou** [vuejs/vue-router#2737]
### What problem does this feature solve?
When the react router jumps the route, in addition to taking the parameter to the url, it can also be placed in the state.

Reference https://reacttraining.com/react-router/web/api/location

The characteristic of this parameter is that even if the page is refreshed, it still works, even if it is not on the url.
But when the url is shared, this parameter will not be taken.
Such parameters are only useful in the current session.

### What does the proposed API look like?
like this

```
push({
   path: '',
   query: {},
   params: {},
   state: {},
})
```

**Comment by posva** [comment]
As I suspected, this is a usage question, please use the forum or discord chat next time. There isn't such thing as a state in navigation. You will have to save the state in a store or at the root of the app
