### ISSUE TITLE
Child `router-view` shouldn't cause update when parent route isn't matched.

### ISSUE THREAD

**Issue by franciscolourenco** [vuejs/vue-router#2741]
### Version
3.0.3

### Reproduction link
[https://codesandbox.io/s/6lpo2oxo4z](https://codesandbox.io/s/6lpo2oxo4z)

### Steps to reproduce
1. Open the console
2. Click on link "Items"
3. Click on link "Page B"
4. Click on link "Page C"

### What is expected?
The router-view inside of Items, should not cause Items to update, when the Items route isn't matched.

### What is actually happening?
Notice that going from page B to page C caused an update in Items.

---
This happens if there is a nested `router-view` inside a another `router-view   keepalive`.

**Comment by posva** [comment]
This is expected, Items is rendering because the nested router-view is changing

**Comment by franciscolourenco** [comment]
The point isn't that the component shouldn't update. Is that router-view shouldn't change because the parent route isn't matched.

**Comment by posva** [comment]
Ah, I see. It's the same as #2739: the component is kept alive and re renders because `router-view` does (because it's a functional component)

**Comment by franciscolourenco** [comment]
Does it have to be a functional component? Can this be optimized?
