### ISSUE TITLE
Param 0 har been renamed pathMatch but must be provided in router object

### ISSUE THREAD

**Issue by mikaelkarlsson-se** [vuejs/vue-router#2742]
### Version
3.0.5

### Reproduction link
[https://codesandbox.io/s/k0jxq926jr?fontsize=14](https://codesandbox.io/s/k0jxq926jr?fontsize=14)

### Steps to reproduce
1. Click on "Navigate to one", router should work.
1. Click on "Navigate to two", "missing param for named route "myRoute": Expected "0" to be defined" will be displayed in the console

### What is expected?
Providing the property pathMatch in $router.push object should be equal to providing '0' or really work instead of 0, as 0 has been renamed to pathMatch (issue #1994).

### What is actually happening?
The routing breaks because of a missing property for the wildcard (0) in the route regexp.

---
I'm using v3.0.5 but it was not possible to chose in the list.

**Comment by LinusBorg** [comment]
Works fine when I change this:
```javascript
{
  myParam: route.params.param,
}
```
to this:
```javascript
{
  myParam: route.params.myParam,
}
```

in the route definition.

**Comment by posva** [comment]
I took a look, the path should start with `/` in the route config. I found some inconsistencies but, it makes sense to provide `pathMatch`, using 0 was never documented

**Comment by mikaelkarlsson-se** [comment]
@LinusBorg So it should be, but the "expected 0" error occurs when navigating with the second button.
@posva True with the /, seems to work anyway though but that's maybe more of a coincidence?

Anyway, in case the demo is a bit unclear. The trouble for me in my real case, is that I want to change one parameter out of three (incl 0/pathMatch) and that's really convenient to do with `...this.$route.params, myParam: 'something'` but "0" isn't present as it's been renamed to pathMatch. This leads to the error or that I need to provide to "0" property manually `'0': pathMatch`.

Thanks for taking your time guys and have a nice weekend! :)

**Comment by adi-zz** [comment]
@mikaelkarlsson-se Take a look at https://github.com/vuejs/vue-router/issues/3062, I think it's the same issue. Unfortunately, based on pasva'a answer, it seems `$router.push` is not that flexible as we would like it (and as it would be nice) to be.

**Comment by mikaelkarlsson-se** [comment]
@adi-zz Thanks for the info. If that's the case it should be documented and this issue can be closed.

**Comment by posva** [comment]
Closing in favour of https://github.com/vuejs/vue-router/issues/3072
