### ISSUE TITLE
Redirect with query string not loading child route

### ISSUE THREAD

**Issue by GreggOD** [vuejs/vue-router#2743]
### Reproduction link
[https://codesandbox.io/s/3xxrojp771](https://codesandbox.io/s/3xxrojp771)

### Steps to reproduce
If in the router.js we redirect to a route without parameters, its fine. if we redirect to a route with parameters the router doesnt pick it up.

https://codesandbox.io/s/3xxrojp771

### What is expected?
Redirects to work with parameters

### What is actually happening?
nothing gets loaded, the route is ignored

---
See code sandbox

**Comment by posva** [comment]
The child route path is conflicting with the root one. Maybe you meant path:'' instead of '/'

**Comment by GreggOD** [comment]
Thanks! I didnt know i could do blank path '' . I will try this out.
