### ISSUE TITLE
./del, that dumb support style

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [vuejs/vue-router#2745]
./del

**Comment by shelru** [comment]
this.$router.replace(this.$router.currentRoute); // doesn't work
this.$router.push(this.$router.currentRoute); //doesn't work
this.$router.go(this.$router.currentRoute); // work's well

**Comment by shelru** [comment]
@posva

**Comment by posva** [comment]
Hey, please ask question on forums and discord 
Also make sure to read the documentation for those methods

**Comment by shelru** [comment]
They all work's perfect with '/' path, ex. this.$router.replace('/'), there no info in doc's about current path replace restriction's.
![image](https://user-images.githubusercontent.com/9306996/56758426-b081b280-67a7-11e9-970c-cbf7f799eecd.png)

Why i should ask at forum's if this is potential bug? Add some var's to router config's which gonna allow to replace work's with current path.

**Comment by afwn90cj93201nixr2e1re** [comment]
@LinusBorg this too. Close.
