### ISSUE TITLE
Is path-to-regexp fully supported by vue-router?

### ISSUE THREAD

**Issue by maximelebreton** [vuejs/vue-router#2747]
### Version
3.0.3

### Reproduction link
[https://codesandbox.io/s/3qzr50oo46](https://codesandbox.io/s/3qzr50oo46)

### Steps to reproduce
Click on each link, and see that is redirect to the 'not found' route instead the 'hello' route.

### What is expected?
This path-to-regexp `/@(:lng,:lat,:zoom z)?(/p/:parcels)?(/c/:cart)?` works on [express-route-tester](https://forbeslindesay.github.io/express-route-tester/) for these paths:

`/@43.21,5.67,9z/p/12345/c/9876`  
`/@43.21,5.67,9z/p/12345`  
`/@43.21,5.67,9z`  
`/@/p/12345/c/9876`  
`/@/p/12345`  
`/@/c/9876`  
`/@`  

So it should works on `vue-router`.

### What is actually happening?
`vue-router` doesn't understand it...

---
Hello, 

I've write this quite complex **path-to-regexp**:
```
/@(:lng,:lat,:zoom z)?(/p/:parcels)?(/c/:cart)?
```

Because I need a component who support all these routes:
`/@43.21,5.67,9z/p/12345/c/9876`  
`/@43.21,5.67,9z/p/12345`  
`/@43.21,5.67,9z`  
`/@/p/12345/c/9876`  
`/@/p/12345`  
`/@/c/9876`  
`/@`  

To get (`lng`, `lat`, `zoom`), `parcels` and `cart` params individually

I've tested my regex an all these paths on the **route-tester** recommended by [path-to-regexp](https://github.com/pillarjs/path-to-regexp), and everything works as excepted:
https://forbeslindesay.github.io/express-route-tester/

But on `vue-router`, it doesn't work at all...

And I can't find any explanation on [vue-router docs](https://router.vuejs.org/guide/essentials/dynamic-matching.html#advanced-matching-patterns)

**Here is a codesandbox to reproduce the case:**
https://3qzr50oo46.codesandbox.io/home

Thanks for your help!

**Comment by posva** [comment]
Make sure you are testing against the same version used by vue router which is v1.
It does support any syntax supported by that version 
Upgrading the package requires some extra changes that we cannot afford without breaking things

**Comment by maximelebreton** [comment]
Thank you @posva , maybe it should be warned on `vue-router` docs? https://router.vuejs.org/guide/essentials/dynamic-matching.html#advanced-matching-patterns

**Comment by posva** [comment]
Sure, open for a PR for a short message about the version using between parenthesis (a warning would be too much here) 🙂
