### ISSUE TITLE
Default child-path doesn't work

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [vuejs/vue-router#2748]

**Comment by afwn90cj93201nixr2e1re** [comment]
```[vue-router] Named Route 'abcd' has a default child route. When navigating to this named route (:to="{name: 'abcd'"), the default child route will not be rendered. Remove the name from this route and use the name of the default child route for named links instead.```

http://jsfiddle.net/m3sqyuxc/19/

When removing `name:'abcd'`, also nothing rendering. (http://jsfiddle.net/m3sqyuxc/20/)


```js
/* const router = new VueRouter({
  routes: [
    { 
      path: '/user/',  name: 'user.home', component: UserProfile       
    },
    {
      path: '/user/:id', name:'user.id', component: UserId, 
    }
]
}) */
```

works

Don't say anything 'bout stackoverflow or doc's, there no examples. I think it's bug too.

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/vuejs/vue-router/issues/2745 review too.

**Comment by afwn90cj93201nixr2e1re** [comment]
@posva @LinusBorg

**Comment by afwn90cj93201nixr2e1re** [comment]
http://jsfiddle.net/3dkb29nm/5/
doesn't work too

**Comment by zrh122** [comment]
> http://jsfiddle.net/3dkb29nm/5/
> doesn't work too

@shelru, change to this can work.
http://jsfiddle.net/26ov5ces/

**Comment by afwn90cj93201nixr2e1re** [comment]
Thank's, but it's not what i need at all.

https://codepen.io/anon/pen/PgVYKE?editors=1010
I need something like this.
Without params - show 1 component, with params show another.

**Comment by zrh122** [comment]
> Thank's, but it's not what i need at all.
> 
> https://codepen.io/anon/pen/PgVYKE?editors=1010
> I need something like this.
> Without params - show 1 component, with params show another.

@shelru,  change to this.
https://codepen.io/anon/pen/oOmvpY?editors=1010

**Comment by LinusBorg** [comment]
This is not following issue guidelines and looks like a usage question.

Use forum.vuejs.org or chat.vuejs.org, as our issue guidelines require.
