### ISSUE TITLE
apache .htaccess not working with lazy-loaded routes

### ISSUE THREAD

**Issue by xseignard** [vuejs/vue-router#2753]
### Version
3.0.3

### Reproduction link
[https://beta.pow.cool/members](https://beta.pow.cool/members)

### Steps to reproduce
- Create a new app
- Add a lazy loaded route named 'myRoute'
- Build it
- Check that you have a `myRoute.js` file in your build folder
- Deploy it to an apache server after following the `.htaccess` recommandation in the vue-router docs
- Check that your browser shows the content of the `myRoute.js` file instead of serving the `index.html` file when browsing `http://mysite.com/myRoute`

### What is expected?
The browser shoud display the index.html at the given route.

### What is actually happening?
The browser displays the js content of the javascript file.

---
It works as expected with the following conf (taken from create-react-app):
```
Options -MultiViews
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.html [QSA,L]
```

**Comment by posva** [comment]
I see, can you submit a Pull request with the configuration provided. I don't use Apache, so I will need someone to validate it though

**Comment by posva** [comment]
we have the apache tomcat one
