### ISSUE TITLE
vue-router without webpack is not able to load javascript as imports

### ISSUE THREAD

**Issue by oksw** [vuejs/vue-router#2757]
### Version
3.0.3

### Reproduction link
[https://jsfiddle.net/posva/4Lm5Lpgz/](https://jsfiddle.net/posva/4Lm5Lpgz/)

### Steps to reproduce
1. use vue , vue-router without webpack
2. create route 
ex : [     { path: '/a/b' , component: () => import('/a/b/1')  }  ]

3. import javascripts like :

import  'https://cdn.jsdelivr.net/npm/vue-multiselect@2.1.6/dist/vue-multiselect.min.js'
//doesn't work
//since the call  in !function(t,e){ .. from above url is undefined

exports default{..}

### What is expected?

import VueMultiselect from  'https://cdn.jsdelivr.net/npm/vue-multiselect@2.1.6/dist/vue-multiselect.min.js'
var multii = Vue.component('vue-multiselect', VueMultiselect.default);

exports default{..}

### What is actually happening?
when 'https://cdn.jsdelivr.net/npm/vue-multiselect@2.1.6/dist/vue-multiselect.min.js'
is loaded 

t is undefined in 
 !function(t,e){ .

causing failure to load module import

**Comment by posva** [comment]
Hey, this is just how js works. You should be able to search about it by using javascript module keywords
