### ISSUE TITLE
Support for configuring global navigation guards inside router construction options?

### ISSUE THREAD

**Issue by kid1412621** [vuejs/vue-router#2759]
### What problem does this feature solve?
Configure global navigation guards inside router construction options like `scrollBehavior` to keep code more concise.

### What does the proposed API look like?
```javascript
export default new Router({
  beforeEach: (to, from, next) => {
      // ...
   },
})
```

**Comment by posva** [comment]
Thanks for your proposal but this is why we have local guards. Use meta fields to handle specific behaviors attached to global handlers like guards and scrollbehavior

**Comment by kid1412621** [comment]
It’s not conflicting. Local guard is in each route.
