### ISSUE TITLE
beforeRouteEnter callbacks trigger in opposite order for nested routes

### ISSUE THREAD

**Issue by posva** [vuejs/vue-router#2761]
### Version
3.0.3

### Reproduction link
[https://jsfiddle.net/posva/jr8wgc4u/](https://jsfiddle.net/posva/jr8wgc4u/)

### Steps to reproduce
- click on the last link /foo/a/d/c
- check logs

### What is expected?
beforeEnter order to be the same as beforeRouteEnter, from parent to child: Foo, NestedOne, NestedTwo

### What is actually happening?
The order in beforeRouteEnter is backwards

---
I should also check if the same happens outside of the callback

**Comment by zrh122** [comment]
@posva, i think #2738 fixes it.

**Comment by posva** [comment]
Thanks for pointing out, I didn't check, but I didn't want to forget about this
