### ISSUE TITLE
beforeRouteUpdate not prevent back/forward browser navigation

### ISSUE THREAD

**Issue by gianlucaiannelli** [vuejs/vue-router#2764]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/4qj8n6x7lw](https://codesandbox.io/s/4qj8n6x7lw)

### Steps to reproduce
1. Click on 'Increment' button and wait for route update to 'c=1'.
2. Click on 'Increment' button and wait for route update to 'c=2'.
3. Click back browser button.

### What is expected?
On back browser button click route update wait for 2 seconds.

### What is actually happening?
Route update immediate.

---
With use 'next(false)' on beforeRouteUpdate method work fine.
I need to pass 'next' as a parameter of other method.

**Comment by posva** [comment]
this is working as expected, the back button of the browser changes the url and we revert it back when cancelling

**Comment by gianlucaiannelli** [comment]
Sorry but I was not clear enough.
When I click back browser button I expect the url to be change after 2 seconds but it change immediately.
Thanks.

**Comment by posva** [comment]
No, it was clear. That's normal behaviour, we only change it back once the navigation is cancelled. The browser changes the url and it's only then we get to react
