### ISSUE TITLE
Parent link loses active class

### ISSUE THREAD

**Issue by abellion** [vuejs/vue-router#2765]
### Version
3.0.3

### Reproduction link
[https://jsfiddle.net/ve3cwk0h/3/](https://jsfiddle.net/ve3cwk0h/3/)

### Steps to reproduce
I havent' been able to reproduce the issue, but I noticed it appears from V3.0.3 (everything works in V3.0.2). So it must have appeared in one of these commits :
- https://github.com/vuejs/vue-router/commit/e224637
- https://github.com/vuejs/vue-router/commit/53cce99
- https://github.com/vuejs/vue-router/commit/7ff4de4
- https://github.com/vuejs/vue-router/commit/ca30a75

### What is expected?
Giving two routes, `/a` and `/a/b`, the `/a` link should have the active class when navigating on `/a/b`.

### What is actually happening?
It doesn't happen for all the links but only some of them, for example if I have a parent `/a` and two children `/a/1` and `/a/2`, the parent has the active class on `/a/1`  but loses it when navigating on `/a/2`.

**Comment by posva** [comment]
If you cannot reproduce it, I cannot take a look at it...

**Comment by abellion** [comment]
Hey @posva, I've finally been able to reproduce the issue : https://codesandbox.io/embed/54lv0m251k

There is three links :
- __Settings__ `/settings`
- __Modules__ `/settings/modules`
- __Onboarding__ `/settings/onboarding`

__Settings__ should be highlighted when navigating on __Onboarding__ but that's not the case. Works well on __Modules__.

**Comment by posva** [comment]
See https://github.com/vuejs/vue-router/issues/2717 and https://github.com/vuejs/vue-router/issues/2724
