### ISSUE TITLE
$router.push aborted for unknown reason

### ISSUE THREAD

**Issue by KKSzymanowski** [vuejs/vue-router#2767]
### Version
3.0.6

### Reproduction link
[https://jsfiddle.net/72rkon0v/](https://jsfiddle.net/72rkon0v/)

### Steps to reproduce
1. Click the "Redirect 1" button. The redirect does not happen and "redirect1 aborted" is logged in the console
2. **Important**: Rerun the fiddle
3. Click the "Redirect 2" button. The redirect does happen and "redirect2 completed" is logged in the console
4. Then click "Redirect 1" button. The redirect once again does not happen and "redirect1 aborted" is logged in the console.
5. If you now click "Redirect 2" again(which worked previously) it won't work now without rerunning the fiddle.

### What is expected?
Clicking the "Redirect 1" button should redirect to `/foo?page=2`

### What is actually happening?
Clicking the "Redirect 1" button does nothing

**Comment by posva** [comment]
`$route.query` is read only, so you are not creating a different query. You need to do 
```js
const query = Object.assign({},
      	this.$route.query,
        {page: 2}
      );
```

the navigation then fails because you are navigating to the exact same location

**Comment by KKSzymanowski** [comment]
Thanks!
