### ISSUE TITLE
Autoscroll to fragment

### ISSUE THREAD

**Issue by innovate-invent** [vuejs/vue-router#2776]
### What problem does this feature solve?
Currently there is no way to navigate to a page fragment. I propose an autoscroll feature that can be specified in the router config to navigate to a page anchor.
It would also be good to support XPath references and the ability to automatically assign a class attribute to the target.

### What does the proposed API look like?
extend the routes path to allow a octothorpe:
```javascript
const router = new VueRouter({
    routes: [
      { path: '/about#staff', component: MyComponent, name: "About", target_class="page_target"},
```

**Comment by posva** [comment]
This is something that has to be implemented in userland through a combination of scrollBehaviour, hooks and meta field. It has been done in Vuepress, docute and other website generators that use the router

**Comment by sgpinkus** [comment]
> This is something that has to be implemented in userland through a combination of scrollBehaviour, hooks and meta field.

Seems complicated. Is there a way to just make vue-router do nothing if the path has a fragment, possibly only if certain other conditions are met like path matching something ..?
