### ISSUE TITLE
路由切换到同一个页面，生命周期不发生变化，不重新渲染

### ISSUE THREAD

**Issue by shupan123** [vuejs/vue-router#278]
路由从 /search/abc 跳转到 /search/ab,  用的是同一个组件

**Comment by yyx990803** [comment]
同一个组件默认复用。http://router.vuejs.org/zh-cn/pipeline/can-reuse.html

**Comment by jie** [comment]
有没有强制重新渲染的方法，下面这样设置不起作用
`        
route() {
            canReuse: false;
        }
`

**Comment by virusdefender** [comment]
同上，设置不管用。不知道怎么解决的呢？

**Comment by ccqgithub** [comment]
canResuse 好像是没作用
