### ISSUE TITLE
Alias does't allow additional route param

### ISSUE THREAD

**Issue by farin** [vuejs/vue-router#2784]
### Version
3.0.6

### Reproduction link
[https://jsfiddle.net/ovk93q5e/](https://jsfiddle.net/ovk93q5e/)

### Steps to reproduce
When alias contains additional params
```
{
   path: "/:foo/explore/,
   alias: ["/:foo/explore/:extra/bar"],
}
```
route is matched on both urls, but extra parameter remains unset in `$route.params`

When decalared in reversed order
```
{
   path: "/:foo/explore/:extra/bar",
   alias: ["/:foo/explore/"],
}
```
Route is matched only by path and not by alias

### What is expected?
Route params should contains values according to matched route.

### What is actually happening?
Described in steps to reproduce.

**Comment by posva** [comment]
A path and an alias should contain the same amount of params. Otherwise set another route with a redirect. That will allow you to provide a default param

**Comment by farin** [comment]
@posva redirect is not solution in my case. I am going to declare another route pointing to same component. (but such solution requires much more effort especially together with Nuxt, alias with different params would be much much easier)
