### ISSUE TITLE
URI malformed with dynamic route 

### ISSUE THREAD

**Issue by yaniv51** [vuejs/vue-router#2786]
### Version
3.0.3

### Reproduction link
[https://codesandbox.io/s/mw8di](https://codesandbox.io/s/mw8di)

### Steps to reproduce
Open:
https://mw8di.codesandbox.io/#/test/error/100%

### What is expected?
Page with 'Error' text

### What is actually happening?
URI malformed error page

---
I found this error while using Nuxt.js, related bug:
https://github.com/nuxt/nuxt.js/issues/5827

**Comment by posva** [comment]
`mw8di.codesandbox.io/#/test/error/100%` is not a legal URL, the `%` character must be encoded (it's `%25`, try encodeURI), this is a browser spec

**Comment by yaniv51** [comment]
Did you checked the related issue?
https://quzpq.sse.codesandbox.io/90%25
The request is fully encoded but still there is an exception in vue-router.

The only way I think it might be is that there is an issue with Nuxt.js and while handle request, nuxt is decode path (-> instead of 90%25 we get 90%) and the vue-router try to decode it again -> the exception raised.

**Comment by posva** [comment]
Please, see https://github.com/vuejs/vue-router/issues/2725
