### ISSUE TITLE
Javascript hooks failed to be called on per route transitions

### ISSUE THREAD

**Issue by jasonlav** [vuejs/vue-router#2787]
### Version
3.0.3

### Reproduction link
[https://codesandbox.io/s/sparkling-leftpad-t2one](https://codesandbox.io/s/sparkling-leftpad-t2one)

### Steps to reproduce
Vue-router documentation outlines approach for per route transitions (https://router.vuejs.org/guide/advanced/transitions.html#per-route-transition). In the minimal reproduction, Javascript callbacks are not called when transitioning between routes.

Note that using a transition `name` to animate with CSS does work.

### What is expected?
Javascript transition hooks should be called.

### What is actually happening?
Javascript transition hooks are not being called.

**Comment by posva** [comment]
This is not related to the router. You need the `appear` prop to trigger transitions on appear
Also, please, next time take the time to complete the reproduction: it was missing the router instance 🙂
