### ISSUE TITLE
Problems opening a link in a new TAB with ctrl   click

### ISSUE THREAD

**Issue by andresparrav** [vuejs/vue-router#2789]
### Version
3.0.2

### Reproduction link
[https://www.loom.com/share/39015e27f2e1406e8f6c2c3ed251da09](https://www.loom.com/share/39015e27f2e1406e8f6c2c3ed251da09)

### Steps to reproduce
Ctrl   Click on the link

### What is expected?
requested page opened in a new tab with ctrl   click

### What is actually happening?
We are having problems with the Vue-router component, when you try to open a link with ctrl   click, open the page but not the selected option, but the same where the page is open.

**Comment by posva** [comment]
Hey, please provide a boiled down editable repro when reporting bugs, thanks!

**Comment by jpmckinney** [comment]
Same as #2788
