### ISSUE TITLE
Typescript   commonjs   import (lazy route) does not work

### ISSUE THREAD

**Issue by mustafaekim** [vuejs/vue-router#2795]
### Version
3.0.3

### Steps to reproduce
Create a Vuejs   Typescript project. 
Set the module property in tsconfig as "commonjs".
Setup a lazy-route

### What is expected?
I would expect the route to be lazy loaded

### What is actually happening?
The route is not lazy-loaded. Route is included in the bundle

---
I've made a big research in internet - some people recommend using "esnext" as the module in tsconfig but that does not work for me. I have to use commonjs.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). This is related to Typescript, dynamic imports, and webpack or any bundler you are using
