### ISSUE TITLE
Detect back/forward (expose popstate event)

### ISSUE THREAD

**Issue by heidarv** [vuejs/vue-router#2796]
### What problem does this feature solve?
The need to know when back button is pressed without using popstate event.
For example to return to global search popup dialog from search results.

### What does the proposed API look like?
router.popstate((to, from, next) => {
})

**Comment by posva** [comment]
Hey, those two things are quite different. The direction of navigation is in already in the roadmap for next Vue Router. Once I come up with a proper API I will be able to adapt it to current version. Exposing a popstate event is not something we want to do, you can listen to navigation with navigation guards.

Keep in mind the popstate event does not contain information about the navigation direction

**Comment by vesper8** [comment]
is there a workaround currently?

I have some logic that currently aborts navigation if a modal is open and instead closes the modal, but I only want this to happen if the back button has been pushed, if going forward, for example as a result of using push(), then I don't want to abort navigation even if a modal is open

**Comment by Rusinas** [comment]
@posva any updates on this? :)

**Comment by fheft** [comment]
Also interested in this. Having a hard time distinguishing between programmatic navigation (`router.push` etc) and browser navigation (back/forward).
