### ISSUE TITLE
Change Component in current Route?

### ISSUE THREAD

**Issue by kvdmolen** [vuejs/vue-router#280]
I am trying to **change the current component**, but without succes.

Reason: after an asynchronous call, I want to be able to set the global component to "not-found", but **without** re-routing. So I can't use `this.$route.router.go({name: "not-found"})`

So the URL will remain `example.com/article/123`, but the page will render "not found"

Would it be possible to do this for example?

```js
this.$route.router.component = "not-found"
```

**Comment by yyx990803** [comment]
I don't think this makes sense... you better bet is handling this inside your `article` component.
