### ISSUE TITLE
Can you add attributes to the $route to identify which of the replace, push, or go methods are used for the current jump?

### ISSUE THREAD

**Issue by wukaikailive** [vuejs/vue-router#2801]
### What problem does this feature solve?
I have a component that monitors the $route. When the URL changes, whether using the replace or push method, it will display the route history at the top of the page. But if I just want to replace the current url, I will still add a new record at the top of the page. I have to use vuex to mark the current jump so that it is not added to the record. If the Route object can add an attribute. The method used to mark the jump, which I can judge when using the replace method, will be very concise.

### What does the proposed API look like?
The Route object adds a "method" attribute with values: link, replace, push, go. When the page is not using the vue-router api, the value is "link", which is consistent with the method name used in other cases.

**Comment by posva** [comment]
Please check https://github.com/vuejs/vue-router/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22group%5Bcurrent+route+information%5D%22
