### ISSUE TITLE
next() in beforeEach doesn't work without return

### ISSUE THREAD

**Issue by ashnamuh** [vuejs/vue-router#2805]
### Version
3.0.3

### Reproduction link
[https://codesandbox.io/embed/vue-template-kr8qp](https://codesandbox.io/embed/vue-template-kr8qp)

### Steps to reproduce
Click Add link. Then it will be redirected to `/login` route.
Click Add link again. Then it will be redirected to `/book/new` ignoring authentication on beforeEach.
But if i write `return` on next line of `next()`, it work well.

### What is expected?
even work without `return`

### What is actually happening?
doesn't work

---
I want to know why is it happen. Should i always write `return` with `next()`?

**Comment by posva** [comment]
Because `next` must be called only once
