### ISSUE TITLE
Make up your mind: Suffix OR Trailing Slash

### ISSUE THREAD

**Issue by isaakengineer** [vuejs/vue-router#2809]
### What problem does this feature solve?
In my understanding, the general perception of browser is that it is being displayed either a "file" or a "directory" and as, generally speaking, VueJS apps return an HTML file, hence, Vue-Router should by default add `.html` at the end of the routes it creates. I have seen this feature-request be dismissed a while ago, but back then the default behavior was to add a ​trailing slash, now that this has been pushed to an additional option: `pathToRegexpOptions: { strict: true } `, it is finally time to adopt the suffix feature.

### What does the proposed API look like?
Browser displaying: `https://myapp.com/log/post-n.html`

so, when the log post number n contains multiple images, videos, or audios, the plain text of the post n does not need to take into account from which URL structure the page is being accessed.

For example, the author can simply write: `<img src="my-image.jpg">` and the image will be displayed properly regardless of the URL structure. However, when the trailing slash and the suffix are neither available by default, the image will be loaded from the previous component of the path, in this example: the current default behavior looks like this: `https://myapp.com/log/post-n` and the web browser will request the image like this: `https://myapp.com/log/my-image.jpg` which is actually a bug!

**Comment by posva** [comment]
> the web browser will request the image like this: https://myapp.com/log/my-image.jpg which is actually a bug

it's how browsers work, add a `/` at the beginning to request a link at the root of the domain but this is completely unrelated to vue or vue router

If you want to add a suffix like `.html` which I don't think serve any purpose (definitely they change nothing for SEO), you can already do so by adding it to the url's paths but It's not something I would recommend because the page without the extension looks better

**Comment by isaakengineer** [comment]
Nobody is talking about SEO. I began the text with describing "how browsers work" and exactly that's the reason why Vue-Router has to respect how the browsers are designed to work.

What I'm talking about is that the content is stored somewhere, written by some guy (creative author) who has no idea about HTML, or browser, or anything, while the structure of the app is designed by a web developer: Most contents contain non-text material which are embedded via an HTML-element and a `src` attribute that is not designed to take into account the app's architecture!

The point is to maintain the same standard as the web was based on, instead of trying to make the URL look nice. Because most end-users don't ever look at the URL but how the URL ends have implication both: 
- how the browser renders the page
- how other applications interact with the URL when sending requesting based on that URL

Here is how a real-life example looks like: https://galacticvisions.xyz/log/103/ the content of this post has multiple video elements, most are embedded from Youtube, while one is hosted on the same server and the correct request depends on what the URL, from the browser's perspective, looks like.

In more obscure cases, you have the example when others are referencing the link to your application in their text which can look like this: `https://website.com/essays/author/xzy.` and the dot at the end is part of the "referencing manual" (Harvard Style, MLA, etc) but when copy-pasted into the browser, it can cause break! Which again if there it was like `https://website.com/essays/author/xzy.html.` most browser would ignore the final "dot".
