### ISSUE TITLE
$route properties not reactive

### ISSUE THREAD

**Issue by y-nk** [vuejs/vue-router#2810]
### Version
3.0.3

### Reproduction link
[https://jsfiddle.net/y_nk/d07bxk86/](https://jsfiddle.net/y_nk/d07bxk86/)

### Steps to reproduce
1. try to v-model into an object of `$route`

### What is expected?
objects of route to be reactive

### What is actually happening?
they are not

---
example based on @posva 's codebase https://jsfiddle.net/posva/chyLjpv0/
i'm mixed feeling either this is a bug or a feature request, but it's surely something saving a lot of code in many projects.

**Comment by posva** [comment]
$route is a read only property. Triggering navigations  should go through router.push
Making it reactive is a bad api imo because of the many edge cases that you can face by modifying one thing. Using router.push is straightforward and is always atomic

**Comment by y-nk** [comment]
I'm not really sure to get a difference on the prefered way (from your example) and having a reactive behavior but, i get your point on the atomic part.

What about dynamic getters and setters in $route.query which would automate your original idea ?
I mean that, it would probably possible to imagine a (sortof) Proxy of query route which does exactly this : 

```
this.$router.replace({
  query: {
    ...this.$route.query,
    [this.name]: target.value
  }
})
```

**Comment by y-nk** [comment]
I mean that, the effort and possibility is already there if you use a [watcher](https://jsfiddle.net/y_nk/ge3a1boh/) or even a [computed](https://jsfiddle.net/y_nk/ge3a1boh/1/) as a proxy... my point is that it just feels like a hack to use those in order to achieve it, and it's probably a tiny addition to "not feel like having to hack a library constantly to use it with convenience"

**Comment by posva** [comment]
Yes, a proxy would be possible but I prefer to keep one single way of doing things than having an incomplete alternative to push
