### ISSUE TITLE
router.go(-1) 无法返回上一个页面，扔停留在当前页面（tag v3.0.6）

### ISSUE THREAD

**Issue by William-WFC** [vuejs/vue-router#2812]
### Version
3.0.3

### Reproduction link
[http://wenti.com](http://wenti.com)

### Steps to reproduce
偶现

### What is expected?
正常返回上一个页面

### What is actually happening?
停留在当前页面

---
vue-router(v3.0.6)构建成生产代码后，偶尔出现
vue-router(v3.0.5)开发时，必现

**Comment by posva** [comment]
Please of you found a regression, open a proper issue with a boiled down editable repro and not just a website. Also please, write in English so I can read it

**Comment by 60late** [comment]
老哥后来怎么解决的
