### ISSUE TITLE
Pass props to router view

### ISSUE THREAD

**Issue by mittalyashu** [vuejs/vue-router#2813]
### What problem does this feature solve?
Passing the props to `<router-view data="fetchData" />` should pass the props to it's all child components or views depending upon the way we have defined the configuration in `router.js`

```html
<router-view :data="[4, 5]" />
```

I have tried using parms & query, but it doesn't fulfill the use-case.

### What does the proposed API look like?
_Not sure_

**Comment by posva** [comment]
Passing props should work, only one level though (same as regular props). If that doesn't work, please provide a repro

**Comment by mittalyashu** [comment]
> Passing props should work, only one level though

What do you mean by one level?

As you mention that it works till one level, will it be changed to all it's child component in the future?

---

I am using the `<router-view data="fetchData" />` in `App.vue` and pass some props too.

**router.js**

```
{
		path: "/1",
		component: require("../pages/1").default,
		children: [
			{
				path: "2",
				name: "secondPage",
				component: require("../pages/repository/2").default
			}
		]
	}
```

I am trying to access the props in the secondPage

**Comment by posva** [comment]
Props won't be passed implicitly, you will have to handle that explicitly as regular props

**Comment by hopeswiller** [comment]
> Props won't be passed implicitly, you will have to handle that explicitly as regular props

This actually solved my issue thanks
