### ISSUE TITLE
Allow for custom element anchors

### ISSUE THREAD

**Issue by kamituel** [vuejs/vue-router#2815]
### What problem does this feature solve?
`<router-link>` will set a `href` attribute on its child only if this child has an `<a>` tag name (see [`findAnchor()`](https://github.com/vuejs/vue-router/blob/dev/src/components/link.js#L124)). However, this won't work in case an anchor is wrapped in a custom element.

### What does the proposed API look like?
Maybe something like this?

```
<router-link to="..." anchorTag="custom-anchor">
   <custom-anchor>Click Me!</custom-anchor>
</router-link>
```

**Comment by posva** [comment]
See https://github.com/vuejs/rfcs/pull/34
