### ISSUE TITLE
vue-cli3  路由重定向可以使用，但是别名无效

### ISSUE THREAD

**Issue by warmup413** [vuejs/vue-router#2817]
vue-cli3  路由重定向可以使用，但是别名alias无效

**Comment by MuLoo** [comment]
> vue-cli3 路由重定向可以使用，但是别名alias无效

alias: '/test'   需要以/开头的哦

**Comment by warmup413** [comment]
亲测无效，我特地创建了一个新的项目测试依然无效，但是重定向却可以使用
