### ISSUE TITLE
Can't route to the path "/element53" , and so on

### ISSUE THREAD

**Issue by 0415wangyibo** [vuejs/vue-router#2823]
### Version
3.0.2

### Reproduction link
[https://github.com/0415wangyibo/webLearning/tree/master/vueweb](https://github.com/0415wangyibo/webLearning/tree/master/vueweb)

### Steps to reproduce
npm install
npm run dev
Open a browser and enter the URL "http://localhost:8080/#/element53"

### What is expected?
It can route to the component which named "element53"

### What is actually happening?
"vue-router" can't route to the path "/element53", and it routes to the default path.

---
It can't route to the path "/element53","/element54","/element55",and so on. But it can route to the path "/element52","element51","element50",and so on.

**Comment by posva** [comment]
Hey, please report boiled down repros when reporting a bug, that's your whole testing project with ElementUI and many components. If the problem comes from having too many routes, then focus on that aspect for the repro and leave everything else out. You can use Codesandbox as well
