### ISSUE TITLE
Vue-router points to wrong component when using browser navigation and two routes have same path

### ISSUE THREAD

**Issue by ahochel** [vuejs/vue-router#2824]
### Version
3.0.6

### Reproduction link
[https://codesandbox.io/s/vue-template-6fm9z](https://codesandbox.io/s/vue-template-6fm9z)

### Steps to reproduce
1. You start at the homepage.
2. Click "B" link. It shows that B component is mounted and slug is "test-b".
2. Click "A" link. It shows that A component is mounted and slug is "test-a".
3. Click back button in an iframe. It shows that A component is mounted and slug is "test-b".

### What is expected?
On last step, it should mount component "B", because when you have been on that route before it pointed to route "b".

### What is actually happening?
URL changes correctly, slug (which is route param) also changes correctly, but the wrong component is mounted.

---
This happens when you have two (or more) routes with different names and different components, but with the same path and when you navigate through "go back" / "go forward" buttons in your browser.

```
{ name: "a", path: "/:slug.html", component: A },
{ name: "b", path: "/:slug.html", component: B }
```

**Comment by posva** [comment]
Two routes cannot have the same path because only one will be matched. Otherwise, if the user copies the url to share it, the other person may end up in the wrong url

**Comment by ahochel** [comment]
@posva I take care of it on the server side, I just want front-end to work correctly, it should know what route it was before (store it somewhere in the history) and do not make matching again, because it is not necessary.

**Comment by posva** [comment]
It's literally impossible to make the difference between two identical strings: if user goes to `/slug-1`, it will always be `/slug-1`. It's impossible to know which route the user wants if both are identical, that's why having two routes with the same path is not supported
