### ISSUE TITLE
errorHandler can't catch the error thrown in navigation guards

### ISSUE THREAD

**Issue by maroon1** [vuejs/vue-router#2825]
### What problem does this feature solve?
目前 Navigation Guards 中的异常直接被 vue-router 内部处理掉，无法被 errorHandler 处理，导致需要在 Navigation Guards 单独处理，或者转换为 Promise 异常再通过 unhandledrejection 事件处理

### What does the proposed API look like?
希望可以提供与 Vue 统一的异常传播行为

**Comment by posva** [comment]
Hey can you open the issue in English please? Thank you :)

**Comment by maroon1** [comment]
Current router catch all error thrown in navigation guard(route guard or component guard), thus errorHandler can't handle the error. We have to handle error in every navigation guard or instead reject a promise then use unhandledrejection event listener to handle these common errors at one place. Is there some way to throw these error out, and then caught by errorHandler or errorCaptured @posva

**Comment by posva** [comment]
Please provide a boiled down repro for bug reports. You can use Codesandbox, codepen or other platforms. Thanks

**Comment by maroon1** [comment]
https://codesandbox.io/s/vue-template-s3dk4

it seems that unhandledrejection listener can't handle rejection in sandbox, but you can find errorHander can't handle the error thrown from navigation guard

**Comment by posva** [comment]
You have to call `next(new Error("HelloWord.vue navigation guard: beforeRouteEnter"))`

**Comment by maroon1** [comment]
Is there a way to pass the error to vue rather than handled by router(via onError)? Because i put some code in errorCaptured lifecycle to process auth failed.

**Comment by posva** [comment]
Now I get what you meant by the async errors, I'm opening https://github.com/vuejs/vue-router/issues/2825 to track that
Since the error comes from the router, it makes sense for it to be tracked by the router, it cancels navigations so, in the beforeRouteEnter, you won't have access to the component anyway, en `beforeRouteUpdate` and `beforeRouteLeave`, you can however access `this` and can propagate the error manually through `this.$options.errorCaptured`. I will think about if this should and can be done automatically for the next version though

**Comment by 9-lives** [comment]
This is significant for me.

**Comment by 9-lives** [comment]
> Now I get what you meant by the async errors, I'm opening #2825 to track that
> Since the error comes from the router, it makes sense for it to be tracked by the router, it cancels navigations so, in the beforeRouteEnter, you won't have access to the component anyway, en `beforeRouteUpdate` and `beforeRouteLeave`, you can however access `this` and can propagate the error manually through `this.$options.errorCaptured`. I will think about if this should and can be done automatically for the next version though

you're totaly a genius.It's relly helpful.

**Comment by 9-lives** [comment]
> Now I get what you meant by the async errors, I'm opening #2825 to track that
> Since the error comes from the router, it makes sense for it to be tracked by the router, it cancels navigations so, in the beforeRouteEnter, you won't have access to the component anyway, en `beforeRouteUpdate` and `beforeRouteLeave`, you can however access `this` and can propagate the error manually through `this.$options.errorCaptured`. I will think about if this should and can be done automatically for the next version though

you're totally a genius.It's relly helpful.
