### ISSUE TITLE
maybe getMatchedComponents type is missed

### ISSUE THREAD

**Issue by kahirokunn** [vuejs/vue-router#2827]
### Version
3.0.3

### Reproduction link
[https://github.com/vuejs/vue-router/blob/732c8258258608c2e29268cbda2a4ed957d884d4/types/router.d.ts#L31](https://github.com/vuejs/vue-router/blob/732c8258258608c2e29268cbda2a4ed957d884d4/types/router.d.ts#L31)

### Steps to reproduce
Maybe this `getMatchedComponents` type is incorrect.
https://github.com/vuejs/vue-router/blob/732c8258258608c2e29268cbda2a4ed957d884d4/types/router.d.ts#L31

### What is expected?
I expected correct `getMatchedComponents` type

### What is actually happening?
I try to read vue-router code.
But code is too long.
So I don't have a much confidence.
I'm sorry if the point is wrong.

I read this source code.

https://github.com/vuejs/vue-router/blob/732c8258258608c2e29268cbda2a4ed957d884d4/src/util/resolve-components.js#L13

there has this sentence.

> we want to halt the navigation until the incoming component has been resolved.

And I read some code.
I guess `getMatchedComponents` function never return asyncComponent.

https://github.com/vuejs/vue-router/blob/732c8258258608c2e29268cbda2a4ed957d884d4/src/index.js#L173

So I think this `getMatchedComponents` type is incorrect.
https://github.com/vuejs/vue-router/blob/732c8258258608c2e29268cbda2a4ed957d884d4/types/router.d.ts#L31

**Comment by kahirokunn** [comment]
Is anyone here? (´；ω；｀)

**Comment by posva** [comment]
See https://github.com/vuejs/vue-router/pull/2828#issuecomment-507022544
