### ISSUE TITLE
 use history mode,history.length is wrong

### ISSUE THREAD

**Issue by stavid** [vuejs/vue-router#2832]
### Version
2.7.0

### Reproduction link
[https://github.com/vuejs/vue-router/issues/2831](https://github.com/vuejs/vue-router/issues/2831)

### Steps to reproduce
export default new Router({
mode: 'history',
routes: [

	{
		path: '/A',
		name: 'A',
                   component: resolve => require(['../components/files/

A.vue'], resolve),
meta: {
title: 'A'
}
},
open A page ,print history.length in beforeEach method , the message is：

beforeEach:history.size:32to:/A,from:/
beforeEach:history.size:33to:/A,from:/

I hope beforeEach work ,but not twice.How can i do?

### What is expected?
history.length add 1

### What is actually happening?
history.length add 2

**Comment by posva** [comment]
The history length is not directly controlled by the router, it grows as new entries are added to the navigation.

I'm not sure what you are trying to use it for but it's not very reliable as it can grow by clicking on links and reloads.

Remember you can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask quick questions! Also, please don't open bug request with fake reproductions, it must be a boiled down, editable working reproduction as stated in the issue helper. Thanks!
