### ISSUE TITLE
base是否能当成params参数来配置？

### ISSUE THREAD

**Issue by liubin595338764** [vuejs/vue-router#2835]
### Version
3.0.3

### Reproduction link
[https://www](https://www)

### Steps to reproduce
现在`base`只能写死为一个固定的字符串`string`

### What is expected?
希望在history模式的时候可以把`base`当成`params`来处理，

对于多公司访问通一个应用的时候，这样的链接比较好看，

比如：
```js
export default new Router({
    mode: 'history',
    base: '/:company',
    routes: routes
})
```

### What is actually happening?
现在`base`只能写死为一个固定的字符串`string`

---
希望能尽快支持哦

**Comment by posva** [comment]
If you want a dynamic base use a route:

```js
routes: [
  { path: '/:lang',
    component: { render: h => h('router-view') },
    children: [
      {
        path: 'profile',
        component: UserProfile
      },
      {
        path: 'posts',
        component: UserPosts
      }
    ]
  }
]
```
