### ISSUE TITLE
External JavaScript working when changing route

### ISSUE THREAD

**Issue by ghost** [vuejs/vue-router#2837]
### What problem does this feature solve?
I am currently facing an issue with the external javascipt stopping when changing routes.

For example, when I start from / (root page), then click /shop, then click back / (root page), the external javascript stop working (Eg. plugin.js stop).

I tried to use a plugin called vue-plugin-load-script. In order to dynamically load external javascript in main.js but the result is still the same, external javascript stops working when changing routes.

this feature should allow the javascript works when changing routes. 

### What does the proposed API look like?
The external javascript is place in index.html

index.html
```

<html>

<body>

...

</body>

<script src="<%= BASE_URL %>js/plugins.js"></script>

</html>
```

route.js
```

{

path: '/',

name: 'home',

component: Home

},

{

path: '/shop',

name: 'shop',

component: Shop

},
```

App.vue
```

<template>

<div id="app">

<router-view />

</div>

</template>
```

External javascript is provided globally, so each page can be used. I wish to request a feature that the same external javascript works in different paths.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
