### ISSUE TITLE
Color active state on link does not return to color

### ISSUE THREAD

**Issue by juanescarraga** [vuejs/vue-router#2839]
### Version
3.0.2

### Reproduction link
[https://codesandbox.io/embed/vue-template-lgn63](https://codesandbox.io/embed/vue-template-lgn63)

### Steps to reproduce
Open the project in the browser.
The link with the name Say Hello appears in the browser.
The default color is green of the Say Hello link is green, when hovering or clicking on the link the color changes from green to gray.
The gray color remains in the Say Hello link, the expected behavior is that once you click and refresh the page the color returns to the original which is green.
In tests carried out in development environments, low resolutions are being presented with smart phone views.

### What is expected?
Fix the original color state bug, if the mouse cursor is positioned or the link is touched change color and return to its original state.

### What is actually happening?
The color of the link in desktop resolutions works correctly when you hover over the link or click. In low resolutions and smart phones when touching the link changes the active state color and does not return to the original color of the normal state.

**Comment by posva** [comment]
The link being focused is a browser mechanism, completely unrelated to Vue router
