### ISSUE TITLE
How to extract only components RouterView and RouterLink?

### ISSUE THREAD

**Issue by fgr-araujo** [vuejs/vue-router#2843]
### What problem does this feature solve?
Load only the *router-view* and *router-link* will give me the ability to use external VueRouter instance.

I'm working with web-components and I have an AppShell with VueRouter and I'm using a web-component inside them with another VueRouter.
Everything inside the web-component are working fine but my AppShell can't load the router components.

### What does the proposed API look like?
I think something like **const { RouterView, RouterLink } = VueRouter** can help

**Comment by posva** [comment]
The thing is even if there is something like `const { RouterView, RouterLink } = VueRouter`, we still need to import the router. Having named exports would be a breaking change for CommonJS users so we cannot do that. This is what you need to do:

```js
import Router from 'vue-router'
import Vue from 'vue'

const localVue = Vue.extend({})
localVue.use(Router)
const RouterView = localVue.component('RouterView')
const RouterLink = localVue.component('RouterLink')

export { RouterView, RouterLink }
```

Ideally, there would also be a way to teardown listeners added by the router
