### ISSUE TITLE
typescript error Property 'matcher' does not exist on type 'VueRouter'.

### ISSUE THREAD

**Issue by lk8888** [vuejs/vue-router#2844]
this is my code:
const router = createRouter();

export function resetRouter() {
  const newRouter = createRouter();
  router.matcher = newRouter.matcher; // reset router
}
the error:
TS2339: Property 'matcher' does not exist on type 'VueRouter'.

**Comment by posva** [comment]
That is normal as the `matcher` is not part of the public API. You will have to use a `// @ts-ignore` before that line

**Comment by lk8888** [comment]
> That is normal as the `matcher` is not part of the public API. You will have to use a `// @ts-ignore` before that line

Oh, thank you. This problem is solved
