### ISSUE TITLE
createHref 方法能否变成公共方法

### ISSUE THREAD

**Issue by zhengxs2018** [vuejs/vue-router#2848]
### What problem does this feature solve?
**场景一：**

我的商城 base 是 /h5/shop/:shopId ( node 路由 )

My mall 'base' is 'h5/shop/: shopId' (node routing)

点击购物车需要跳转到登录页，但是 fullPath 拿到的 path 不包含 base 的内容

Click on the shopping cart to jump to the login page, but the 'path' of 'fullPath' does not contain the content of 'base'.

每次都手动拼接，希望能变成一个公共方法，（ps: 应用有多个，目前左右一个函数在使用）

Hope to make this method public

**场景二：**

购买成功页需要生成海报，海报的地址指向商品详情页，需要生成 url 地址

Business needs to generate URLs for other pages

### What does the proposed API look like?
```javascript
/**
 * url join
 *
 * @param {String|Object} location
 * @param {Object} [options=null]
 * @param {Boolean} [options.base=false]
 *
 * @returns {String|Null}
 */
router.url(location, options?)

// -> /home
router.url('home')

// -> /h5/shop/3/home
router.url('home', {
  base: true
})

// -> /h5/shop/3/home
router.url({ path: 'home' }, {
  base: true
})

// -> /h5/shop/3/member/123
router.url({ name: 'member', params: { memberId: '123' } }, {
  base: true
})

// -> /h5/shop/3/products?sort=date
router.url({ path: 'products', query: { sort: 'date' } }, {
  base: true
})
```

```javascript
// 或者 route 添加 href 字段
route.href = '/h5/shop/1/shopping-cart'
```

**Comment by posva** [comment]
Use `router.resolve`
