### ISSUE TITLE
在iphone浏览器下hash路由问题

### ISSUE THREAD

**Issue by chenguzhen87** [vuejs/vue-router#2850]
### Version
3.0.1

### Reproduction link
[http://www.lulutopic.com/web/#/login](http://www.lulutopic.com/web/#/login)

### Steps to reproduce
1、设置hash路由
2、在iphone下打开带hash路由
3、点击浏览器‘复制’按纽
4、粘贴地址

### What is expected?
粘贴地址带上hash部分

### What is actually happening?
hash地址丢失

**Comment by posva** [comment]
Copying the url is a browser interaction so this is likely to not be related to vue-router
That's not a valid repro anyway (it is explained in the issue helper)
