### ISSUE TITLE
Why does vue.js report 404 route in production, but not development?

### ISSUE THREAD

**Issue by atrueresistance** [vuejs/vue-router#2854]
### Version
3.0.3

### Reproduction link
[https://stackoverflow.com/questions/57013982/why-does-vue-js-report-404-route-in-production-but-not-development](https://stackoverflow.com/questions/57013982/why-does-vue-js-report-404-route-in-production-but-not-development)

### Steps to reproduce
Running npm run serve I can visit auth/login, but after npm run build the server returns a 404 on auth/login.

I get a 404 when going to https://example.com/auth/login but navigating to https://example.com/address-records works just fine. It seems as if only something that is more than a single / deep returns a 404.

Here is the router code

```
let router = new Router({
  mode: "history",
  base: process.env.BASE_URL,
  routes: [
    {
      path: "/",
      name: "home",
      component: Home
    },
    {
      path: "/auth/login",
      name: "Login",
      component: Login
    },
    {
      path: "/address-records",
      name: "Address",
      component: Address
    }
  ]
});
```

Is there something special I need to be doing with Nginx? I have it setup with similar searched questions.

```
 location / {
        try_files $uri $uri/ /index.html;
 }
 location @rewrites {
         rewrite ^(. )$ /index.html last;
      }

 location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
         # Some basic cache-control for static files to be sent to the browser
         expires max;
         add_header Pragma public;
         add_header Cache-Control "public, must-revalidate, proxy-revalidate";
  }
```

### What is expected?
200 status code from auth/login in production

### What is actually happening?
404 status code from auth/login in production

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

We have some configurations listed at https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations
