### ISSUE TITLE
路由切换添加scrollBehavior会出现横向滚动条

### ISSUE THREAD

**Issue by wakaka378** [vuejs/vue-router#2861]
### What problem does this feature solve?
在添加scrollBehavior后，路由切换的时候底部会出现一个横向滚动条(我加了路由动画)一闪而过。

### What does the proposed API look like?
不要横向的滚动条

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. This is a styling question. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
