### ISSUE TITLE
Improve history mode server configuration documentation to include non-root publicPath

### ISSUE THREAD

**Issue by philBrown** [vuejs/vue-router#2863]
### What problem does this feature solve?
The documentation for [HTML5 History Mode - Example Server Configurations](https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations) assumes all apps are running at the document root (ie `/`). Apps using a non-root [`publicPath`](https://cli.vuejs.org/config/#publicpath) are going to struggle with these config examples.

### What does the proposed API look like?
Update the examples to include `<publicPath>` placeholders, eg

nginx
```
location <publicPath> {
  try_files $uri $uri/ <publicPath>/index.html;
}
```

**Comment by posva** [comment]
I think we can add a small paragraph at the beginning, before all examples, saying that they are targeting deployments at root `/` and then point out about the publicPath option in CLI and relate it to `base` in router options
