### ISSUE TITLE
Make automatically added trailing slash in base optional

### ISSUE THREAD

**Issue by tychenjiajun** [vuejs/vue-router#2865]
### What problem does this feature solve?
We use the following base config
```js
base: /page/index.html
```

what we want in href generated by <router-link>

```html
<a href="/page/index.html#/foo"/></a>
```

what we have now
```html
<a href="/page/index.html/#/foo"/></a>
```

### What does the proposed API look like?
```js
base: {
    url: '/page/index.html'
    trailingSlash: false
}
```

**Comment by posva** [comment]
What is the use case for that?

**Comment by tychenjiajun** [comment]
@posva Our backend only allow us to use index.html to be the only entry to the SPA.

**Comment by posva** [comment]
Initial navigation should still work as the router will still recognize `index.html#/users/:id`. But, the base should be `/page/` without the index.html, that way the server can probably also answer correctly

**Comment by tychenjiajun** [comment]
@posva No, the server response 404 on `/page/` and fail to answer the CSS and js files if request URL is `/page/index.html/#/`. I was told to only use `/page/index.html` to be the only entry.

`<router-link>` works well when clicked. For example, `<router-link to="/foo">` can navigate us from `/page/index.html#/` to  `/page/index.html#/foo`, but its rendered href is `<a href="/page/index.html/#/foo">`, which makes us unable to right click it and open in a new tab.

And here is an example: https://codesandbox.io/s/vue-template-v7qmf

**Comment by posva** [comment]
I forgot about this but with Hash mode, there should be no `base` specified. It's picked up automatically from the URL
