### ISSUE TITLE
清除浏览器缓存，通过vue-router新开一个窗口，新窗口的路由会被重定向到 / 目录

### ISSUE THREAD

**Issue by yan919** [vuejs/vue-router#2866]
### Version
3.0.7

### What is expected?
跳转到正确的路由

### What is actually happening?
 

---

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
Thanks!
