### ISSUE TITLE
Pushing query keeps existing ones

### ISSUE THREAD

**Issue by TheInvoker** [vuejs/vue-router#2874]
### Version
3.1.1

### Reproduction link
[http://www.google.ca](http://www.google.ca)

### Steps to reproduce
I use this code to push a new link

                this.$router.push({path:item.path, query: { 
                    language : this.$route.query.language, 
                    dark : this.$route.query.dark, 
                    rtl : this.$route.query.rtl
                }}).catch(err => {});

but the problem is, if the link had other params in the URL, they persist. How can I use this code, but specify it to discard other params?

### What is expected?
other params get discarded.

### What is actually happening?
Other params persist.

**Comment by posva** [comment]
Tested locally and it works well: the query params that are kept are only the ones provided to push.

Please, next time take the time to provide a boiled down repro, it can be a jsfiddle or codesanbox too: https://jsfiddle.net/posva/9r6xhqbp/
