### ISSUE TITLE
Getting NavigationDuplicated errors since 3.1.0 - but for now everything works

### ISSUE THREAD

**Issue by samydoesit** [vuejs/vue-router#2878]
### Version
3.1.1

### Reproduction link
[https://github.com/samydoesit/vueTestError](https://github.com/samydoesit/vueTestError)

### Steps to reproduce
* cd vueTestError/actualSite
* npm run serve
* Console shows uncatched Error (NavigationDuplicated)

### What is expected?
No errors

### What is actually happening?
Everything works fine just this error is showing up

---
I've been searching for my mistake for a while now but i dont know what im doing wrong.

**Comment by posva** [comment]
See https://github.com/vuejs/vue-router/issues/2872#issuecomment-519073998 and https://github.com/vuejs/vue-router/issues/2873#issuecomment-519406818
