### ISSUE TITLE
No stacktrace on NavigationDuplicated error

### ISSUE THREAD

**Issue by rchl** [vuejs/vue-router#2880]
When `NavigationDuplicated` error is thrown, there is no stack trace in the error itself so when error is reported through error reporting service like `Sentry`, there is absolutely no context to go with the error and so it's hard to figure out where that error originated.

Transpiled code for the `NavigationDuplicated` class looks like this:
https://github.com/vuejs/vue-router/blob/5141def3a21da479c2858c0d70db3cb438c3b7d0/dist/vue-router.common.js#L1935-L1946

which is problematic because instantiating such function won't create a stacktrace. It would work fine with non-transpiled code (although I'm not suggesting to not transpile it): https://github.com/vuejs/vue-router/blob/44c63a963f05ede229d8658a45b2388e244ce00b/src/history/errors.js#L1

One possible solution would be to manually set stack trace with:
```js
this.stack = (new Error()).stack;
```
but I'm not sure how that would be done if transpilation is done by webpack/babel...

There is also one extra bug in that code. The line that instantiates error passes a route object to the error:
https://github.com/vuejs/vue-router/blob/fc42d9cf8e1d381b885c9af37003198dce6f1161/src/history/base.js#L125
but error doesn't do anything with it:
https://github.com/vuejs/vue-router/blob/44c63a963f05ede229d8658a45b2388e244ce00b/src/history/errors.js#L2

Saving route properties on the error object would also help in deciphering source of the error.

**Comment by a3246995** [comment]
有两种解决办法:
1. 是回退上一个版本;
2. 在main.js 中加入这个:

import Router from 'vue-router'

const originalPush = Router.prototype.push
Router.prototype.push = function push(location) {
  return originalPush.call(this, location).catch(err => err)
}
