### ISSUE TITLE
I can't get params normally when I use alias

### ISSUE THREAD

**Issue by funyaliga** [vuejs/vue-router#2882]
### Version
3.1.0

### Reproduction link
[https://codesandbox.io/s/codesandbox-nuxt-fvf98](https://codesandbox.io/s/codesandbox-nuxt-fvf98)

### Steps to reproduce
My project uses nuxt.
The project directory is:

-pages
   - post
     - _id

In routes:
```js
{
     name: 'post-id',
     path: '/post/:id?',
     component: 'project/pages/post/_id/index.vue',
     chunkName: 'pages/post/_id/index',
     alias: '/post/:id?.html'
}
```
I added alias, (because my project must be accessed with the html suffix).

When I visit http://localhost/post/181.html,
```js
console.log( this.$route.params.id );  // 181
```

For me, everything is normal.

but after I updated the Npm package for the project today,
```js
console.log( this.$route.params.id ); // 181.html
```
There is more '.html' after the id.
I found that the problem occurred after the vue-router version was upgraded to v3.1.0.

### What is expected?
I want to filter the alias of .html when I use this.$route.params.id

**Comment by posva** [comment]
Because `/posts/:id` also matches `/posts/2.html`, your alias is never used. Inverse them to match first `/posts/:id?.html`, so the html extensions is ignored:

```js
{
     name: 'post-id',
     path: '/post/:id?.html',
     component: 'project/pages/post/_id/index.vue',
     chunkName: 'pages/post/_id/index',
     alias: '/post/:id?'
}
```
