### ISSUE TITLE
NavigationDuplicated on navigating to the same page with different params

### ISSUE THREAD

**Issue by masoud-deh** [vuejs/vue-router#2884]
Hi.
I have a page with '/user/2' URL. I want to change to a different user from the page with 'this.$router.push' 

I tried
`this.$router.push({ path: '/user/3' })`

and

`this.$router.push({ path: 'user', params: { userId: 3 } })`

but both of them throw NavigationDuplicated error event though the params are defrrent

**Comment by xmsz** [comment]
> Hi.
> I have a page with '/user/2' URL. I want to change to a different user from the page with 'this.$router.push'
> 
> I tried
> `this.$router.push({ path: '/user/3' })`
> 
> and
> 
> `this.$router.push({ path: 'user', params: { userId: 3 } })`
> 
> but both of them throw NavigationDuplicated error event though the params are defrrent

Same issue . any update?

**Comment by posva** [comment]
https://github.com/vuejs/vue-router/issues/2872#issuecomment-542555350
