### ISSUE TITLE
[vue-router] Duplicate named routes definition

### ISSUE THREAD

**Issue by cosoc** [vuejs/vue-router#2886]

**Comment by posva** [comment]
Please check open issues for dynamic routing: https://github.com/vuejs/vue-router/issues?utf8=✓&q=is%3Aissue+is%3Aopen+label%3A%22group%5Bdynamic+routing%5D%22+

**Comment by cosoc** [comment]
解决方法
```js
router.$addRoutes = (params) => {
  router.matcher = new VueRouter({
    mode: 'history'
  }).matcher
  router.addRoutes(params)
}
```

**Comment by shwull** [comment]
antdv  router的index.js中加了
router.$addRoutes = (params) => {
  router.matcher = new Router({
    mode: 'hash'
  }).matcher
  router.addRoutes(params)
}
原来的addRoutes改为$addRoutes  发现报错
Uncaught (in promise) InternalError: too much recursion 
matchRoute vue-router.esm.js:1502
match vue-router.esm.js:1384
。。。。。
