### ISSUE TITLE
Vue remove # from url

### ISSUE THREAD

**Issue by BonBonSlick** [vuejs/vue-router#2894]
### Version
3.0.1

### Reproduction link
[https://new-issue.vuejs.org/?repo=vuejs/vue-router](https://new-issue.vuejs.org/?repo=vuejs/vue-router)

### Steps to reproduce
https://new-issue.vuejs.org/?repo=vuejs/vue-router

### What is expected?
remove # from url

### What is actually happening?
whole site is broken

https://github.com/vuejs/vue-router/issues/new

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

if you want to have a url without a `#`, you can use the `mode: 'history'` when creating the router

**Comment by BonBonSlick** [comment]
@posva  most of people do not know Chinese, forum posts like this does not help https://forum.vuejs.org/t/mode-history/24612
google translation can not translate such texts

**Comment by BonBonSlick** [comment]
@posva  This is very strange, these are required for history mod work correctly.
```
I think docs should be updated

    output: {
        filename: 'main.js', // required for nginx
        publicPath: '/', // required for nginx
    },

```
