### ISSUE TITLE
Location.params and Route.params  should not be Dictionary<string> in router.d.ts

### ISSUE THREAD

**Issue by tttxiaowei** [vuejs/vue-router#2895]
### Version
3.1.2

### Reproduction link
[https://github.com/tttxiaowei/vue-typescript-example](https://github.com/tttxiaowei/vue-typescript-example)

### Steps to reproduce
1. git clone https://github.com/tttxiaowei/vue-typescript-example.git
2. npm install
3. open project in webstorm
4. open src/components/aaa.vue  src/components/bbb.vue
5. you can see the TS error

1. Location.params: 

            this.$router.push({
                name: 'aaa',
                params: {
                    data: {
                        x: 1,
                    },
                },
            })

In this case, I have to write <any> to avoid this TS error：
Error:(414, 31) TS2345: Argument of type '{ name: string; params: { data: { x: number; }; }; }' is not assignable to parameter of type 'RawLocation'.
  Type '{ name: string; params: { data: { x: number; }; }; }' is not assignable to type 'Location'.
  Types of property 'params' are incompatible.
  Type '{ data: { x: number; }; }' is not assignable to type 'Dictionary<string>'.
  Property 'data' is incompatible with index signature.
  Type '{ x: number; }' is not assignable to type 'string'.
  
            this.$router.push(<any>{
                name: 'aaa',
                params: {
                    data: {
                        x: 1,
                    },
                },
            })
  
2. Route.params:

			interface Data {
				x: number
			}
			let d:Data = this.$route.params.data

In this case, I have to write <any> to avoid this TS error：
Error:(339, 17) TS2322: Type 'string' is not assignable to type 'Data'.

			interface Data {
				x: number
			}
			let d:Data = <any> this.$route.params.data

### What is expected?
Change Location.params and Route.params to any 

### What is actually happening?
1. Location.params: 
When I use this.$router.push({params: {data:{}}}) to pass object data between pages, TS will report an error. Currently, every push writes any to solve the problem.

2. Route.params:
When I use this.$route.params.data to get the data passed by other pages, and the assigned variable has a custom type, TS will report an error, which can only be solved by <any>.

**Comment by posva** [comment]
Only strings are allowed as params as they must appear in the url. Number may be added in the future as said in https://github.com/vuejs/vue-router/issues/2662

**Comment by tttxiaowei** [comment]
> Only strings are allowed as params as they must appear in the url. Number may be added in the future as said in #2662

But sometimes we really need to pass data through params, can we realize that the parameters configured in the route can only be string and number, while other parameters are not verified.

**Comment by jsamayoap** [comment]
> Only strings are allowed as params as they must appear in the url. Number may be added in the future as said in #2662

Booleans? please

**Comment by Thaval** [comment]
What? Why are strings represented in the url? 
I am passing params right now and they are not represented in the url but the query string is! Just like I would imagine. However, I changed 
```
params?: Dictionary<string> 
```

to
```
params?: Dictionary<any> 
```

and it's working just fine. Accessing the object via $route.params is working like a charme. Please, change that officially. Params should be passed under the hood while the query could still be represented in the url.

Sorry, but everything else doesn't make sense. Just imagine selecting some entries in a table and you want to pass the selected items as an array to a routed view. No one wants to use a store for such a simple thing.
