### ISSUE TITLE
beforeEach navigation guard throws error when passing object, false or string to next()

### ISSUE THREAD

**Issue by kagagnon** [vuejs/vue-router#2897]
### Version
3.1.2

### Reproduction link
[https://codesandbox.io/s/vue-template-334c1](https://codesandbox.io/s/vue-template-334c1)

### Steps to reproduce
Click on a `router-link` to change page. When entering the `beforeEach` callback, an error will be thrown but will work accordingly. If clicking on the current page link, there's also an error being thrown.

### What is expected?
To work without error.

### What is actually happening?
It works with an error

---
This error happens only when using a compiler, could not make it happens in a JSFiddle.

Upon inspection, the error happens since version 3.1.0. The breaking change is the use of `Promise` in the `VueRouter.prototype.push` callback. The problem might be located in the file [`vue-router@3.1.2 history/base.js#87`](https://github.com/vuejs/vue-router/blob/v3.1.2/src/history/base.js#L87):

```
if (onAbort) {
  onAbort(err)
}
```

Here, `onAbort` is equal to the `reject` function of the Promise. `err` can be equal to many things depending on what is being passed to `next()`, but there's no way that I know of to catch the error thrown.

Downgrading to version 3.0.7 solves the issue.

**Comment by posva** [comment]
Clicking on links no longer errors, that was fixed and released already.
Calling `push` or `replace` however must be caught if you don't care about the promise result, everything related is explained [here](https://github.com/vuejs/vue-router/issues/2881#issuecomment-520554378). A navigation guard aborting the navigation will reject the push/replace promise as the navigation is not fulfilled. We are working on improving the errors (only NavigationDuplicated have been changed so far)
