### ISSUE TITLE
Vue-router fails to initialize with latest CDN versions

### ISSUE THREAD

**Issue by denniskempin** [vuejs/vue-router#290]
Using vue 1.0.11 and vue-router 0.7.7 new Vue() will fail with the following error:
**'Cannot read property '_parent' of undefined'**
in t._init	@	vue-router.min.js:6

See: https://jsfiddle.net/vLjson03/

**Comment by Vorror** [comment]
Still happens with vue 1.0.12

**Comment by yyx990803** [comment]
This is fixed with https://github.com/vuejs/vue-router/pull/292 and will be fixed with next release of vue-router
