### ISSUE TITLE
add ability to provide http response code (301 permanent redirect) for the purpose of SEO

### ISSUE THREAD

**Issue by vesper8** [vuejs/vue-router#2901]
### What problem does this feature solve?
I am upgrading an old website with 10s of thousands of links to a vue pwa. I have new sitemaps generated with all the new link structure and I have a set of redirect routes/components that correctly handle all the redirects from the old links to the new ones

I'm not using SSR. I'm using vue-router history mode

I would like those redirects (Even though they are pwa redirects) to "teach" the search engines that these links have moved to a new link. Normally you do that by issuing a 301 permanent redirect.

I'm not sure how I can go about doing this with a pwa or if it's even possible

Would love to know : ) thanks

### What does the proposed API look like?
The ability to I guess something like this
```
router.push({ path: redirectUrl, code: 301 })
```

Or something of the likes

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

A redirect must be setup on the server, so it completely depends on what you are using, for example Netlify allows creating a _redirects file. But it's not something that can be added on a client-side library

**Comment by vesper8** [comment]
@posva adding the ability to provide the http response code (301 permanent redirect)

how is this not a feature request?
