### ISSUE TITLE
Sub-component not re-rendering unless route is changed

### ISSUE THREAD

**Issue by nvrnight** [vuejs/vue-router#2909]
### Version
3.1.2

### Reproduction link
[https://jsfiddle.net/buot0hpe/2/](https://jsfiddle.net/buot0hpe/2/)

### Steps to reproduce
Click on Foo to activate the /foo route. Click on the button however many times as you want to, then click on bar, then click on foo again.

### What is expected?
Button counter to re-render the correct number when clicked

### What is actually happening?
Button is not being re-rendered until the route changes

---
I suspect I'm probably doing something wrong here, but I've been trying to figure it out for a long time now and haven't gotten anywhere far. The jist of the scenario I'm trying for is that my routing components will represent pages which will be utilizing other components in its own template that I've built. This approach works fine without the routing involved: https://jsfiddle.net/472hxfz6/ and as a subcomponent: https://jsfiddle.net/7mhz348n/

**Comment by posva** [comment]
The `props` option in a route record is static data, it cannot be modified, it's not observed either. You could for example pass a key that is stored somewhere else like a Vuex store but, the `props` option is not meant to hold state

**Comment by nvrnight** [comment]
Thanks for the info, that makes a lot of sense after thinking it through in the context of a route, which led me to a solution of storing my model privately on my route's component and using data() to return it and the beforeRouteEnter/beforeRouteUpdate hooks to initialize it, then was able to bind properties on the model to sub-components in the template as needed.
