### ISSUE TITLE
It would be nice to have an abstract parent route

### ISSUE THREAD

**Issue by rwaltenberg** [vuejs/vue-router#2912]
### What problem does this feature solve?
It will allow to have a parent route that cannot be accessed directly. It will serve only as a nest do child routes that share the same structure with different content (like a config page with many config category tabs)

### What does the proposed API look like?
By adding an `abstract` property to the route config, that route would not be accessible directly. Instead, it would redirect to a children with (maybe) a `default` property set.

e.g
```javascript
export const configs = [
  {
    name: 'Config',
    path: '/config',
    component: ConfigWrapper,
    abstract: true,
    children: [
      {
        name: 'GeneralConfig',
        path: 'general',
        component: GeneralConfig,
        default: true
      },
      {
        name: 'MerchantConfig',
        path: 'merchant',
        component: MerchantConfig
      },
      {
        name: 'AddressConfig',
        path: 'address',
        component: AddressConfig
      },
      {
        name: 'SocialConfig',
        path: 'social',
        component: SocialConfig
      }
    ]
  }
]
```

**Comment by posva** [comment]
Thank you for the proposal but this can be achieved by adding a redirect record to the children:


```js
{ path: '', redirect: 'general' }
```
