### ISSUE TITLE
<router-link> not working with named route and hash

### ISSUE THREAD

**Issue by matthieudou** [vuejs/vue-router#2914]
### Version
3.1.2

### Reproduction link
[https://codesandbox.io/s/vue-routing-example-bcy1y](https://codesandbox.io/s/vue-routing-example-bcy1y)

### Steps to reproduce
switch between pages and check the hash and the url

### What is expected?
`:to="{name: 'hello', hash: 'test'}" => /hello#test`

### What is actually happening?
`:to="{name: 'hello', hash: 'test'}" => /hellotest`

---
Hash is working fine when using path so it's definitely not a major or blocking problem but I personally use named route whenever I can and also with nuxt-i18n and the hash is just appended without the # to the route.

Thanks for the awesome work.

**Comment by posva** [comment]
It's weird it works with the path, the hash option needs a `#` as the first character, so it should be `hash: '#test'` in both cases

**Comment by matthieudou** [comment]
Thanks for the reply. It works as expected now that i add the hash 😄 I first tried without hash so I thought it was a bug.

**Comment by fawadahmad** [comment]
`<router-link :to="{ name: 'home', hash: '#contact-us' }">Contact Us</router-link>`
The link becomes `/home#contact-us`
When clicked, the URL changes, but the pages doesn't scroll.
Also there is an error in the console: `Uncaught Error: Syntax error, unrecognized expression: /home#contact-us`

**Comment by Gbahdeyboh** [comment]
The exact same problem @fawadahmad is having brought me here.

@fawadahmad , have you been able to find a fix? Can anyone help clarify this issue?

**Comment by domoran** [comment]
Same problem here, please reopen this issue.

<router-link :to="{ name: 'home', hash: '#contact-us' }">Contact Us</router-link>
The link becomes /home#contact-us
When clicked, the URL changes, but the pages doesn't scroll.

Although I got not even an error in the console. 

I found a workaround to this behaviour - if you insert this (found on the router documentation) in your router configuration 
```
  scrollBehavior (to, from, savedPosition) {
      if (to.hash) {
         return { selector: to.hash }
      }
  }
```

then scrolling works as expected after page navigation. Still I think this should be a default behaviour.

**Comment by Glogo** [comment]
In vue-router 4 the `selector` property was renamed to `el`:
```
  scrollBehavior(to, from, savedPosition) {
    if (to.hash) {
      return {
        el: to.hash,
      };
    }
  },
```
See: https://router.vuejs.org/guide/advanced/scroll-behavior.html

**Comment by Novacation** [comment]
Is there any way to remove the "#" from urls after clicking a router-link?

![image](https://user-images.githubusercontent.com/47398013/222961819-b771ed7a-71df-46c8-9b0a-dc856ce1ce87.png)

![image](https://user-images.githubusercontent.com/47398013/222961856-7e69bc4f-2334-4331-be52-ddf5a9147ff0.png)

![image](https://user-images.githubusercontent.com/47398013/222961881-09e445c2-360e-4fb6-9eab-8c35c782c5dd.png)
