### ISSUE TITLE
Switching to a nested route is automatically running the last commit event from parent’s store

### ISSUE THREAD

**Issue by farazshuja** [vuejs/vue-router#2915]
### Version
3.1.0

### Reproduction link
[https://codesandbox.io/s/vue-template-c2gtb](https://codesandbox.io/s/vue-template-c2gtb)

### Steps to reproduce
1. Open https://codesandbox.io/s/vue-template-c2gtb
2. Click on ‘Go to Page with nested router’ link
3. Click on ‘commit event’, it will show an alert box
4. Now change the nested route by clicking ‘change nested route to reporting’

### What is expected?
Route changed to reporting without showing the ‘hello’ alert box.

### What is actually happening?
Its showing the ‘hello’ alert box again.

**Comment by posva** [comment]
Hey, this is a question so please, use the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for it. I checked it up and it seems that the Vuex module registration is triggering the alert, so some check in your store code must be triggering it
