### ISSUE TITLE
Error at redirecting throught beforeEach

### ISSUE THREAD

**Issue by JFGHT** [vuejs/vue-router#2916]
### Version
3.1.3

### Reproduction link
[https://github.com/JFGHT/vue-router-error-repro](https://github.com/JFGHT/vue-router-error-repro)

### Steps to reproduce
1.- Push to any route (`this.$router.push('/test');`).
2.- Redirect to same router but with extra param.
```js
if (to.fullPath === '/test') {
  next('/en/test');
}
```

route:
```js
{
  path: '/:lang?/test',
  name: 'test',
  component: () => import(/* webpackChunkName: "test" */ './views/Test.vue'),
},
```

### What is expected?
Correct redirect.

### What is actually happening?
It's redirecting but it's displaying an error:
`vue-router.esm.js?8c4f:2051 Uncaught (in promise) undefined`

**Comment by posva** [comment]
See https://github.com/vuejs/vue-router/issues/2873#issuecomment-519274203
