### ISSUE TITLE
registerModule and beforeRouteEnter fetching data need an example

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [vuejs/vue-router#2917]
As we know, **next inside beforeRouteEnter gonna call after mounted**, but if we wanna use mapActions or mapState and other stuff like that, we should initialize module before.

So, i can't find any workaround for this, that's why im writing here.
So, i have beforeRouterEnter guard, where im fetching some data.

```javascript
import { mapActions, mapState } from 'vuex';
computed: {
            ...mapState('test', ['abcd','abcd123'])
},
async beforeRouteEnter (to, from, next) {
            console.log("before router enter");
            try{
                let resp = await FetchingSomeData();
                console.log(resp);
                
                next(vm => {
                    console.log("next(vm => { called");
                    vm.$store.registerModule('test', {state:resp.object,...},{devtools_getStateDirectly:true});
                });
            }
            catch(e){
                next(vm => {vm.isEmpty = true;console.log("next(vm => {vm.isEmpty = true;");});
            }
        },
```
```javascript
        beforeDestroy() {
            if(this.$store.state.test)this.$store.unregisterModule('test');
        }
```
As you can see i wanna register module only if there any response, but it should be registered before component created, but we can't set some variable to true, for making it inside created/beforeCreated(we can use only some global var, but it's crappy way).

**Comment by afwn90cj93201nixr2e1re** [comment]
@posva any suggestions? I didn't found any issues like that.


https://git.rubansoft.com/chenying/vue-demo/blob/b3b03c684c3cc770df3fe4ae22dd86fadcd60dff/src/views/nav2/increment.vue
as you can see some one also tried to do that, but ended with nothing, lol.

https://github.com/vuejs/vue-router/issues/1144#issuecomment-449070382


If we already have mounted post call(next) on beforeRouterEnter, why you can't add something like
```javascript
next_beforeCreated(vm...);
next_afterCreated(vm...);
next_beforeMounted(vm...);
next_afterMounted(vm...);
```
it seems like not a breakble change at all. Why we can't just provide some info before/after created hook?

Also the reason why im here, it's coz i can use async on created/beforeCreated, but as we know created/beforeCreated is also sync, but functions inside can be async.

So, i really **didn't found a workaround** for this one, can you provide an real example in this case, with register/unregister store modules.

**Comment by afwn90cj93201nixr2e1re** [comment]
https://git.rubansoft.com/chenying/vue-demo/blob/b3b03c684c3cc770df3fe4ae22dd86fadcd60dff/src/views/nav2/increment.vue
as you can see some one also tried to do that, but ended with nothing, lol.

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/vuejs/vue-router/issues/1144#issuecomment-449070382


If we already have mounted post call(next) on beforeRouterEnter, why you can't add something like
```javascript
next_beforeCreated(vm...);
next_afterCreated(vm...);
next_beforeMounted(vm...);
next_afterMounted(vm...);
```
it seems like not a breakble change at all. Why we can't just provide some info before/after created hook?

**Comment by afwn90cj93201nixr2e1re** [comment]
xD, should i use this shitty workaround?

```javascript
mounted(){console.log("mounted");},
        created(){
            console.log("created");
        },
        beforeCreate(){

            if(this.$route.params.isNewList){
                this.$store.registerModule('test', STestModule,{devtools_getStateDirectly:true});//stay new list from vuex module directly
            }
            else if(this.$route.params.anyPayload){

                this.$store.registerModule('test', 
                   {
                      namespaced:STestModule.namespaced,
                      state:this.$route.params.anyPayload,
                      //  First question: how i should avoid potential memory leak here, does vuerouter gonna clear params each time?
                      //  Second question: should i use Object.assign({},this.$route.params.anyPayload) or keep as is?
                      actions:STestModule.actions,
                      mutations:STestModule.mutations
                     }
                                        ,{devtools_getStateDirectly:true});//load state from api fetch
                console.log(JSON.stringify(this.$store.state.test));
            }
            console.log("beforeCreated end sync")
        },
        async beforeRouteEnter (to, from, next) {
            if(isNaN(to.params.id-0)||!(to.params.id-0)){
                to.params.isNewList = true;
                next();
                return;
            }
            try{
                to.params.anyPayload = await GetTestInfo({id:1});
                next();
            }
            catch(e){
            }
        },
        beforeDestroy() {
            // this.$store.commit("test/m_ClearState");
            this.$store.unregisterModule('test')
            this.$store.commit("auth/m_TestMutation");
        }
```
Also **can you answer** to this two questions inside code?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

In your code I would rather register the store before calling `next` in `beforeRouteEnter`. This requires you to import the store as well

**Comment by afwn90cj93201nixr2e1re** [comment]
@posva we doesn't have any context in beforeRouteEnter, how we must register store, lol.
There no `this` and so on. Also i don't wanna import store exports in this module, that's not nice at all.
Also forum is not place for asking spec. architecture updating questions like this.
