### ISSUE TITLE
Allow add query in beforeEach or some new API?

### ISSUE THREAD

**Issue by hezhongfeng** [vuejs/vue-router#2918]
### What problem does this feature solve?
code like this
```
function getKey(src) {
    return src.replace(/[xy]/g, function (c) {
        let r = (Math.random() * 16) | 0;
        let v = c === 'x' ? r : (r & 0x3) | 0x8;
        return v.toString(16);
    });
}
router.beforeEach((to, from, next) => {
    if (!to.query['test']) {
        to.query['test'] = getKey('xxxxxxxx');
        next({
            path: to.path,
            query: to.query
        });
    } else {
       // here will console `Uncaught (in promise) undefined`
        next();
    }
});
```
I want to add some query in beforeEach, but the query is read only in beforeEach ,So I must push the same path twice，`vue-router(3.1.x)` will appear Uncaught (in promise)  in console.

### What does the proposed API look like?
Some interceptors could operate query before beforeEach?

**Comment by posva** [comment]
This is not a feature request. I already gave you indications about the uncaught promise rejection in https://github.com/vuejs/vue-router/issues/2911

Please do not use the issue tracker to ask questions
