### ISSUE TITLE
keep-alive deeply nested router-views display the last visited component component

### ISSUE THREAD

**Issue by lxcuso4** [vuejs/vue-router#2923]
### Version
3.1.3

### Reproduction link
[https://jsfiddle.net/lxcuso4/cu6keqw2/28](https://jsfiddle.net/lxcuso4/cu6keqw2/28)

### Steps to reproduce
Click on childA
Click on index
Click on childB

### What is expected?
we want to show B page

### What is actually happening?
but actually A page dispaly

---
This behavior happens when we use keep-alive and have three layers of nested routing

**Comment by posva** [comment]
Similar to https://github.com/vuejs/vue-router/issues/2552 if anybody wants to try fixing this

**Comment by santiaomaojin** [comment]
I tested that the following code works in src/component/view.js
    var matched = route.matched[depth];
  // render empty node if no matched route
  if (!matched) {
    cache[name] = null;
    return h()
  }
  // render previous view if the tree is inactive and kept-alive
  if (inactive && (cache[name] === matched.components[name])) {
    return h(cache[name], data, children)
  }

**Comment by songpeng0501** [comment]
> I tested that the following code works in src/component/view.js
> 
> ```js
>     var matched = route.matched[depth];
>   // render empty node if no matched route
>   if (!matched) {
>     cache[name] = null;
>     return h()
>   }
>   // render previous view if the tree is inactive and kept-alive
>   if (inactive && (cache[name] === matched.components[name])) {
>     return h(cache[name], data, children)
>   }
> ```

you are right
