### ISSUE TITLE
When using beforeRouteEnter，maybe only one next() can be invoked is better

### ISSUE THREAD

**Issue by starstaysky** [vuejs/vue-router#2934]
### Version
3.0.1

### Reproduction link
[https://router.vuejs.org/zh/guide/advanced/navigation-guards.html#%E7%BB%84%E4%BB%B6%E5%86%85%E7%9A%84%E5%AE%88%E5%8D%AB](https://router.vuejs.org/zh/guide/advanced/navigation-guards.html#%E7%BB%84%E4%BB%B6%E5%86%85%E7%9A%84%E5%AE%88%E5%8D%AB)

### Steps to reproduce
1 beforeRouteEnter(to, from, next) {

      next('/home')

      next((vm) => {
        next('/index')
        }
    }
  }

2 current route  " /home "

beforeRouteEnter(to, from, next) {

      next('/home')
  }

### What is expected?
1 only one next() was in work
2 not in work when next() called to itself

### What is actually happening?

1 when called next('/path'), it seemed to run api window.location.href, if any other next() after it ,should not be in work.

2 when i was at page home and inovked next(/home), it entered in endless loop.

**Comment by posva** [comment]
You are indeed supposed to call `next` only once per guard

**Comment by starstaysky** [comment]
that's right, but boundary condition tips or relative documentation maybe better.becasue in some case, we may write the following codes:
beforeRouteEnter(to, from, next) {
if(status === 1){
  next('/home')(thought it worked as window.location.href, so "else" is not present here)
}
   next('/index')
}
