### ISSUE TITLE
<router-link> component is mutating a prop

### ISSUE THREAD

**Issue by guillaumeduliscouet** [vuejs/vue-router#2938]
### Version
2.6.0

### Reproduction link
[https://codesandbox.io/embed/vue-template-hf9hq](https://codesandbox.io/embed/vue-template-hf9hq)

### Steps to reproduce
- Click on 'route' link
- Look at the console

### What is expected?
In `components/Parent.vue` the object `childRoute`, that is passed as the `to` prop of `<router-link>`, should not be mutated.

### What is actually happening?
It is mutated (the key `parent` is added to `childRoute.params`)

**Comment by posva** [comment]
I haven't checked but there is a chance that the problem comes from `router.resolve` or a normalization function

**Comment by zrh122** [comment]
Maybe PR #2802 can fix it, but the test code in the PR is not for this issue. @posva 

I have found this issue when i try to fix #2800, and this [comment](https://github.com/vuejs/vue-router/issues/2800#issuecomment-499038948) mention it. But i didn't  add new issuse for it.

**Comment by posva** [comment]
I completely forgot about that PR, thank you @zrh122 ! I will take another look

**Comment by posva** [comment]
Closed in #2802
