### ISSUE TITLE
提供一个方法来释放router实例。

### ISSUE THREAD

**Issue by liuyang0826** [vuejs/vue-router#2942]
### What problem does this feature solve?
当vue和single-spa这种微应用框架一起使用的时候，页面可能会有多个router实例，并且存在router实例需要被释放的场景。目前vue实例是可以正确的释放，但是router以及router创建的时候添加事件监听就不能得到释放，造成路由切换页面不响应和内存泄漏的问题。

### What does the proposed API look like?
router.$destory() 类似这种即可。

**Comment by aMiing** [comment]
> ### What problem does this feature solve?
> 当vue和single-spa这种微应用框架一起使用的时候，页面可能会有多个router实例，并且存在router实例需要被释放的场景。目前vue实例是可以正确的释放，但是router以及router创建的时候添加事件监听就不能得到释放，造成路由切换页面不响应和内存泄漏的问题。
> 
> ### What does the proposed API look like?
> router.$destory() 类似这种即可。

有销毁的方法了吗？我看被关掉了
