### ISSUE TITLE
Update navigation hooks to include which "action" triggered it

### ISSUE THREAD

**Issue by wrosa-pariveda** [vuejs/vue-router#2943]
### What problem does this feature solve?
Currently it is not possible to use the navigation hooks in order to react to specific directions a user is using in the application.

For example, I cannot use the hooks to react to when users  go to the next screen ( using router.push ), but do nothing if they are navigating back ( using router.back )

### What does the proposed API look like?
Currently the NavigationGuard signature is such, as defined by vue-router's TypeScript definitions:
```
type NavigationGuard < V extends Vue = Vue > = (
  to: Route,
  from: Route,
  next: (to?: RawLocation | false | ((vm: V) => any) | void) => void
) => any
```

the proposed change would simply add a new parameter to the callback to tell which "action" was the cause of the callback invocation.

```
type NavigationGuard < V extends Vue = Vue > = (
  to: Route,
  from: Route,
  next: (to?: RawLocation | false | ((vm: V) => any) | void) => void,
  action: "go" | "push" | "back" | "replace"
) => any
```

**Comment by posva** [comment]
Please see https://github.com/vuejs/vue-router/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22group%5Bcurrent+route+information%5D%22

It won't be possible to detect direction consistently in all cases but we will likely add something that allows to know if it was a `pop` from the browser or `push` from code
