### ISSUE TITLE
[Feature] Fire transition hooks on child components that can suspend the transition

### ISSUE THREAD

**Issue by weotch** [vuejs/vue-router#295]
A new behavior I would like to see is that when a route component is `deactivate`-ing or `activate`-ing, it would trigger all of it's children's transitions.  Furthermore, the route component transition phase would be paused until all children resolve that phase. 

For instance, a child's `beforeLeave` would need to resolve before the route component's `leave` hook gets called on itself and its children.

**Comment by amirrustam** [comment]
@weotch by "suspend" do you mean pause or stop? I'm assuming you mean stop, and if I understand correctly, can't this by accomplished by `transition.abort()`: http://vuejs.github.io/vue-router/en/pipeline/hooks.html

**Comment by weotch** [comment]
No, I do mean pause.  For instance, say you have a router component (the one referenced in `router.map`) and it has a child and both have Vue transitions defined on them.  What I'm proposing is that when the router component deactivates, it would trigger the transition `beforeLeave` on the router component and its child.  If the child transition takes 1s to finish and the router component transition takes .5s, it would take 1s until the `leave` transition hook fires on both router component and child.

**Comment by yyx990803** [comment]
I'm not sure if I understand your original post. Are you describing the feature you want or describing the problem that leads to this feature?

**Comment by weotch** [comment]
I saw what you meant, I just tried to clean up my original post.  I was describing a feature I want; hopefully it makes more sense now.

**Comment by homerjam** [comment]
If I understand the desired behaviour correctly couldn't this be done already using `transition-delay`? ie. delay the child components when activating and delay the parent components when deactivating. Or perhaps use `animation` rather than `transition` and specify precise offsets using percentages.
