### ISSUE TITLE
Routing to the wrong component when refreshing the page

### ISSUE THREAD

**Issue by maiajhonathan** [vuejs/vue-router#2950]
### Version
3.1.3

### Reproduction link
[https://github.com/maiajhonathan/vue-event-list](https://github.com/maiajhonathan/vue-event-list)

### Steps to reproduce
Create a "router.js" with the following structure:

import Vue from 'vue'
import Router from 'vue-router'
import EventList from './views/EventList.vue'
import EventShow from './views/EventShow.vue'
import EventCreate from './views/EventCreate.vue'

Vue.use(Router)

export default new Router({
  mode: 'history',
  routes: [
    {
      path: '/',
      name: 'event-list',
      component: EventList
    },
    {
      path: '/event/:id',
      name: 'event-show',
      component: EventShow,
      props: true
    },
    {
      path: '/event/create',
      name: 'event-create',
      component: EventCreate
    }
  ]
})

ATTENTION: Notice the order of routers, specially name: 'event-show' and name: 'event-create'.

When running npm run serve application starts properly. The first time you click at the "Create" link, the page will display correctly with url: http://localhost:8080/event/create, but if you refresh the page even though the url remains the same vue try to load the "event-show" component instead.

### What is expected?
Reloading the page does not change the component.

### What is actually happening?
When page is reloaded the url: http://localhost:8080/event/create tries to load "event-show" component instead of its own component "event-create".

---
A solution to the problem is simply changing the router's order like so:

routes: [
    {
      path: '/',
      name: 'event-list',
      component: EventList
    },
{
      path: '/event/create',
      name: 'event-create',
      component: EventCreate
    },
    {
      path: '/event/:id',
      name: 'event-show',
      component: EventShow,
      props: true
    }
  ]
Then it works perfectly fine. Not sure why vue-router gets confused when you have a router that receives a parameter above the one you're trying to access.

Could it be recognizing the "/create" as being a prop/parameter?

**Comment by posva** [comment]
The order matters for vue-router as of v3.1. You can also use a custom regex: `path: '/event/:id(\\d+)'`. This won't be a problem on future versions
