### ISSUE TITLE
Add config option for slashes within route params

### ISSUE THREAD

**Issue by FullStackAlex** [vuejs/vue-router#2953]
### What problem does this feature solve?
It would allow within the Vue app a controlled routing of flexible / unpredictable, nested hierarchical categories e.g.: "post-type/post-category/sub-category/sub-sub-category/post-name"
Currently this is not possible due to encoding of the params by encodeURIComponent within vue-router, which leads to slashes being encoded as %2F.

### What does the proposed API look like?
Kind of:
```
<router-link :to={name: "CustomPost", params:{category: "post-category/sub-category/sub-sub-category", post:"post-name"}, encodeURIcomponent: false}></router-link>
```

**Comment by posva** [comment]
Slashes are separators in routes, so they have to be encoded when used in params. You can directly provide a `path` or a string version to control the escaping but note you will also have to provide a custom regexp to the param: ` path: '/:p(.*)'`.

I think the best way for your case would be to use a repeated param: `'/:p+'` and then provide an array of params: `{ params: { p: ['one', 'two'] }}`

**Comment by FullStackAlex** [comment]
Hmm, ok. Thank you for the repeated param idea. I'll try it out.
