### ISSUE TITLE
Add a switch for open/close 'hashchange' and 'statepop' event

### ISSUE THREAD

**Issue by alreadytaken1990** [vuejs/vue-router#2965]
### What problem does this feature solve?
we want anlysis user behivour PV/UV out of vue project, like a static js by add event listener

### What does the proposed API look like?
router = {
    mode: 'history'
    routes: [],
    openEvents: ['statpop','hashchange']
}

**Comment by posva** [comment]
Can you provide more information about this please? It really isn't clear what this is meant for

**Comment by alreadytaken1990** [comment]
After vue project release, we want to add some code to anlysis Page View, but I cant catch 
popstate or hashchange event by add window listners.

**Comment by posva** [comment]
I see. Use navigation guards like after hooks for that

**Comment by alreadytaken1990** [comment]
i mean after release vue project without inject vue life circle
