### ISSUE TITLE
How to handle multiple dynamic nested routes?

### ISSUE THREAD

**Issue by gplusdotgr** [vuejs/vue-router#2966]
### What problem does this feature solve?
Having something like /properties/:id/:tab and redirecting all /properties/:id to a default :tab

Example:
```js
  { path: '/real-properties/:id', redirect: '/real-properties/:id/gateways-table', name: 'real-property' },
  { path: '/real-properties/:id/:activeTab?', component: RealProperty, name: 'real-property-tab' },
```
the above doesn't work correctly : routes that match `/real-properties/:id/:activeTab` don't redirect to an other :id .. .
### What does the proposed API look like?
Having something like /properties/:id/:tab and redirecting all /properties/:id to a default :tab

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

The only thing I see that could be missing in your route list is that `redirect` should be a function to pass the param again: `redirect: from => ({ name: 'real-property-tab', params: { ...from.params, activeTab: 'gateways-table' }})`

**Comment by gplusdotgr** [comment]
Thank you for the response! It might not be the best place to post this, but with the hope core members @yyx990803  @chrisvfritz might listen as well. : 

Before posting here I did seek help in both Vue Forums and the Discord server. I understand all OSS support and development happens on a exclusively (for the most part, unless you're hired by Facebook or Google to work on OSS) volunteer basis but talking from not only my personal experience but also from other frontend devs who like VueJS, it seems to us that there's growing discontent with the ability to get some quality support. 

Comparisons are maybe a bit lame but the React community seems so much more responsive. (in the help channels I mean). Usually the analogy of questions vs answers in the Discord server is 10 to 1 and when we move to more advanced topics more like 100 to 1. 

Blocking the Issue trackers (in all /vuejs/ org repos) from support questions means we have no chance to get quality answers from the actual maintainers of the library - the people who actually master it. There should be some criteria on allowing support questions if they're not answered to the documentation. For example, I'm having a hard time routing from a nested dynamic route to another - this probably won't help many people in the chat rooms who are in the 99% usage scenario, but it might be a good pointer for a missing documentation part or a new feature or even a bug.
