### ISSUE TITLE
addRoutes后，我换一个账号登录权限不一样了，怎么删除之前添加的的路由？

### ISSUE THREAD

**Issue by hankun8645** [vuejs/vue-router#2997]
### Version
2.6.0

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
目前是判断权限生成可访问的路由后addRoutes进去。但是退出登录后换一个账号登录，然后又重新生成一次，之后addRoutes。
问题1：控制台会警告提示[vue-router] Duplicate named routes，就是有重复的路由add进去了。
问题2：可能存在，直接输入地址栏跳转到前一账号可访问的路由（目前是在输地址栏后跳转，整个单页应用会重新init一次，根据当前缓存的账号权限重新生成routes，此问题暂时好像不需要解决）

会不会有方法去删除已经添加的routes？我看过vue-router的文档没有写这个方法。

### What is expected?
解决问题

### What is actually happening?
问题没有解决

---
matcher方法并不生效

**Comment by hankun8645** [comment]
我的微信1005922744

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/vue-router/issues/1234

**Comment by lishihong** [comment]
> 我的微信1005922744

兄弟，怎么解决的，这个问题，matcher我这里也不生效。。。

**Comment by shwull** [comment]
兄弟，怎么解决的

**Comment by WHBLeer** [comment]
题主您好 这个问题解决了吗

**Comment by ItsNikkiZeng** [comment]
> 题主您好 这个问题解决了吗
参考 https://github.com/vuejs/vue-router/issues/1234 中coxy的回答
