### ISSUE TITLE
Add vue-router docs favicon?

### ISSUE THREAD

**Issue by BARNZ** [vuejs/vue-router#3001]
### What problem does this feature solve?
I notice the vue-router docs does not have any favicon. Can one be added?

### What does the proposed API look like?
favicon.ico

Just helps to identify it when users have the tab pinned like me:

![image](https://user-images.githubusercontent.com/2202345/67121366-d2845b00-f247-11e9-8aa1-2504c9fc6457.png)

**Comment by posva** [comment]
It would be the Vue icon though

**Comment by BARNZ** [comment]
Yeah saw that with the vue docs and vuex docs

![image](https://user-images.githubusercontent.com/2202345/67121739-b59c5780-f248-11e9-847d-e41a124c2de5.png)

Could do a slight little variant to distinguish them :)

**Comment by posva** [comment]
for anybody doing the PR, no variation is needed (https://github.com/vuejs/vue/issues/6305)

**Comment by BARNZ** [comment]
Added via https://github.com/vuejs/vue-router/pull/3002

**Comment by cnschwarz** [comment]
this one misses the label **hasPR** see @BARNZ 's comment
