### ISSUE TITLE
Vue router's link active class naming convention (BEM)

### ISSUE THREAD

**Issue by avxkim** [vuejs/vue-router#3007]
### What problem does this feature solve?
Right now, we can override a class name for an active router link menu, but it doesn't solve a problem, if we have, for example, 2 different navbar's across our web application. I am using BEM (https://en.bem.info/methodology/), so let's say if i override an active class name to "navbar__link_active" in the first navbar (parent is "navbar" class), then i would get the same class name in my 2nd navbar, though i have a different parent class on it "footer-menu", so it should have "footer-menu__link_active" class ideally.

code example:

```
// i overrided an active class to "navbar__link_active"
<ul class="navbar">
  <router-link class="navbar__link navbar__link_active">Menu 1 is active</router-link>
  <router-link class="navbar__link">Menu 2</router-link>
  <router-link class="navbar__link">Menu 3</router-link>
</ul>

// 2nd navbar
<ul class="footer-navbar">
  <router-link class="footer-navbar navbar__link_active">Menu 1 is active</router-link>
  <router-link class="footer-navbar">Menu 2</router-link>
  <router-link class="footer-navbar">Menu 3</router-link>
</ul>
// notice here, an active class would be the same, as for the 1st navbar, that's not what i wanted, instead it should be "footer-navbar__link_active"
```

### What does the proposed API look like?
There should be a setting in a router instance config, to set an active class for specific menus or something like that.

**Comment by posva** [comment]
use the active-class prop if you need to change the active class of a link. Choosing BEM or any other css _framework_ doesn't affect the router, you apply classes the same way
