### ISSUE TITLE
[Feature] $loadingRoute or A way to handle/listen to transition.abort

### ISSUE THREAD

**Issue by tilleps** [vuejs/vue-router#301]
### Feature Request

Support for `$loadingRoute` like `$loadingRouteData` (but for the route instead of data) would be helpful.
### Handling `transition.abort()`

From the documentation:  http://vuejs.github.io/vue-router/en/pipeline/hooks.html

Transitions can be cancelled with:

``` javascript
transition.abort([reason])
```

Question: Where does the `[reason]` go?  Is there an event that I can listen do that gets emitted after a failed/cancelled transition?

I have tried using `router.beforeEach`/`router.afterEach` but `router.afterEach` does not appear to be called if the transition is aborted.

**Comment by amirrustam** [comment]
@tilleps you asked a lot of different stuff in this one issue, so lets address them one by one. In the future, please make issue posts that focus on one thing. Also the community [forum](http://forum.vuejs.org) is a great place to get general questions answered.

- I'm not sure if `[reason]` does anything. If you look at the [source](https://github.com/vuejs/vue-router/blob/f6ebb67283a424364368f827558bc40d94221380/dist/vue-router.js#L1345), it doesn't take in an argument. @yyx990803 can you clarify this?

- `router.afterEach` will only get called if the route transition **successfully enters the activation phase**. This is the documented behavior, so it is expected for it to not get called when the transition is aborted.

- I'm not particular certain that is useful to have an event for aborted transitions. If you need to do handle something that went wrong within the pipeline, then it is best to handle it within the pipeline hooks. Maybe you can **provide a use case** that would justify the adoption of such an event.

- Please **elaborate on your proposal** for a `$loadingRoute`. What use case will it fulfill? I'm actually not fully understanding what it would actually do. It is always helpful and necessary to be specific when proposing new features.

Thanks

**Comment by tilleps** [comment]
My apologies for the ambiguousness and not providing a use case scenario.  This request/issue was mainly about handling async component/routes.  

I was looking for a way to handle cases that occur before and prevent `$loadingRouteData` from happening.  The pipeline/lifecycle hooks wouldn't work because the route/component has not loaded yet to read component's hooks, meaning `activate`/activation never occurs, neither does `router.afterEach`.

Not sure if this is related or needs a mention in #321

**Comment by amirrustam** [comment]
Issue #321 is not really relevant. I suggest **closing this issue**, and **making a new one** that focuses on a **proposal for an event that is triggered upon transition abort**. Please give the issue a specific and descriptive title, and please **elaborate a detailed use case** within issue post. 

If you would like seek alternatives solutions, then please post your question within the community forum, and the discussion can continue there. Thanks.
