### ISSUE TITLE
update docs for standalone

### ISSUE THREAD

**Issue by yurii-github** [vuejs/vue-router#3011]
### Version
3.1.3

### Reproduction link
[https://router.vuejs.org/guide/#javascript](https://router.vuejs.org/guide/#javascript)

### Steps to reproduce
1. read docs https://router.vuejs.org/guide/#javascript
2. try with vue-loader with single-file component approach (by moving each page component to its file)
3. see error "Failed to mount component: template or render function not defined."
4. make ES6 fixes by adding "**.default**"
profit
```
## index.js

import Vue from 'vue'
import VueRouter from 'vue-router'
import App from './App.vue'

Vue.use(VueRouter)

const router = new VueRouter({
  routes: [
    {path: '/', component: require('./pages/Index.vue').default},
    {path: '/about', component: require('./pages/About.vue').default}
  ]
})

window.app =  new Vue({
  router,
  render: h => h(App)
}).$mount('#app')
```

### What is expected?
docs must have solution for standalone approach when vue compiler IS NOT bundled to webbrowser

### What is actually happening?
you don't have such docs, instead you have ton of closed unresolved issues from clients, example:

https://github.com/vuejs/vue-router/issues/824

https://github.com/vuejs/vue-cli/issues/1875

https://github.com/vuejs/vue-router/issues/794

https://github.com/vuejs/vue-router/issues/713

and so on. internet is flooded with this stuff

**Comment by posva** [comment]
Impactful contributions to docs are welcomed. In this case though, having to use `.default` is unrelated to vue, vue-router, or vue's compiler, it's part of the bundler being used and the way the component is exported (`module.exports` vs `export default`)
