### ISSUE TITLE
Trailing slash causing routes to be nested

### ISSUE THREAD

**Issue by tettoffensive** [vuejs/vue-router#3014]
### Version
3.0.7

### Reproduction link
[https://codesandbox.io/embed/vue-router-trailing-slash-bug-rwsbj](https://codesandbox.io/embed/vue-router-trailing-slash-bug-rwsbj)

### Steps to reproduce
1. Have 2 routes specified like '/services' and '/guide'
2. Click on a link that routes to services. (address bar should say http://localhost:8081/services)
3. Refresh the page (used Brave browser)  and you should see a trailing slash added in the address bar (e.g., http://localhost:8081/services/)
3b. In CodeSandbox it is necessary add trailing slash manually
4. Click on a link that goes to '/guide'
5. Address bar now shows http://localhost:8081/services/guide instead of http://localhost:8081/guide

### What is expected?
Route should go to http://localhost:8081/guide

### What is actually happening?
Route is going to http://localhost:8081/services/guide which does not exist.

---
I've noticed an issue with 'vue-router' where if there's an extra '/' on the end of my current url, the other sibling routes think they're nested inside.

I  have 2 routes with paths '/services' and '/guide' Normally, when the address bar says 'http://localhost:8081/services', the other link takes me to http://localhost:8081/guides', BUT if it says 'http://localhost:8081/services/' (which seems to happen when i refresh), then it takes me to http://localhost:8081/services/guides'

Anyone know what might cause this?

**Comment by posva** [comment]
This is because you are using a relative path:

```vue
<router-link to="guide">Guide</router-link>
```

You need to put the leading slash:

```vue
<router-link to="/guide">Guide</router-link>
```
