### ISSUE TITLE
Vue-router 3.1.x breaking change

### ISSUE THREAD

**Issue by bigreddale** [vuejs/vue-router#3016]
### Version
3.1.3

### Reproduction link
[https://jsfiddle.net/u7vwcaLm/7/](https://jsfiddle.net/u7vwcaLm/7/)

### Steps to reproduce
Create a router-link with a to attribute that is a static string and wrap it around a child element (or elements) instead of using v-html

### What is expected?
The router-link should render as an a tag with a correct href attribute and clicking the link should navigate through the router to the desired route.  

Eg. Same code using router v3.0.7
https://jsfiddle.net/u7vwcaLm/8/

### What is actually happening?
The child elements are being rendered without the wrapping a tag.  Note that About is not a link.  In the example with router 3.0.7 About is correctly wrapped in an a tag that routes correctly on click.

---
I love the additional power added in the 3.1.0  update but please fix this breaking change.

**Comment by bigreddale** [comment]
I THINK this can be resolved with an additional check at https://github.com/vuejs/vue-router/blob/dev/src/components/link.js#L92

Adding:
this['v-slot'] &&

Would verify that the developer is attempting to leverage the new scoped slot functionality.

Otherwise the example above evaluates as a scoped slot and falls into
https://github.com/vuejs/vue-router/blob/dev/src/components/link.js#L104 and is simply returned without a link around it.

**Comment by posva** [comment]
You are using an outdated version of vue, you should updated it alongside vue-router. There were quite a few v-slot related fixes between 2.6.6 and 2.6.9 (that version makes it work)
