### ISSUE TITLE
Navigating to current location (the query parameter has changed) is not allowed

### ISSUE THREAD

**Issue by xyqiao** [vuejs/vue-router#3018]
keyWordsChange() {
        const { keywords } = this
        const query: Query = get(this, '$route.query')
        if (keywords) {
            query.keywords = keywords
        } else {
            delete query.keywords
        }
        this.$router.replace({
            ...this.$route,
            query,
        })
    }
![image](https://user-images.githubusercontent.com/15622228/68204395-d6173080-0002-11ea-9316-3de300665519.png)

**Comment by posva** [comment]
Tye route object is read-only. Make sure to create a copy instead of deleting from query

**Comment by itibbers** [comment]
```js
let query  = Object.assign({}, this.$route.query)
// ...
this.$router.push({ query })
```
