### ISSUE TITLE
should I use multi router

### ISSUE THREAD

**Issue by yozman** [vuejs/vue-router#302]
I have two tabs at a page,
how could I make sense with `<router-view>`?
does it support multi router or what should I do,
could u help me?

**Comment by b12k** [comment]
Well you can use nested routing.
```html
<view-router>
    <view-router></view-router>
</view-router>
```
So the root component has a router tag, and the component loaded into that tag may have own router tag, and so on...

http://vuejs.github.io/vue-router/en/nested.html

**Comment by yozman** [comment]
@b12k 
thanks for the answer but not I want,
My cases there is two tab groups in `router-view`
like
```javascript
<router-view>
    <router-view name="tabs1"></router-view>
    <router-view name="tabs2"></router-view>
</router-view>
```

**Comment by tilleps** [comment]
@yozman That is probably the wrong usage for `<router-view>`, because if route changes then how would you determine which `router-view` changes?

You can use nested routing like @b12k said, and/or the `component` element which would probably better fit your needs:  http://vuejs.org/api/#component

**Comment by yozman** [comment]
@tilleps
yeah, so I think there should be some keys for
witch the `router-view` match and the match scope use RegEx

**Comment by amirrustam** [comment]
@yozman I think you should review the jsFiddle provided at the beginning of vue-router docs: http://jsfiddle.net/yyx990803/xyu276sa/

You can think of each of those links as one of your tabs. Does this answer your question?

**Comment by yyx990803** [comment]
This sounds like a duplicate feature request for #213
