### ISSUE TITLE
Abstract mode starts with a negative history index

### ISSUE THREAD

**Issue by wrosa-pariveda** [vuejs/vue-router#3020]
### Version
3.1.3

### Reproduction link
[https://jsfiddle.net/s0kag18p/2/](https://jsfiddle.net/s0kag18p/2/)

### Steps to reproduce
Create a new Vue Router in Abstract Mode

`const router = new Router({ mode: 'abstract', routes: [{path: '/', component: {render: function(h){return h('div', 'Hello World!')}}}]})`

### What is expected?
Expect `router.history.index` to be 0

### What is actually happening?
`router.history.index` is -1

---
The main issue this is causing me is that the first `router.push()` call will increase the index to 0 when it should be increased to 1. What this means is that `router.back()` does nothing until the *second* navigation, when `router.history.index` is set to 1, when it should be 2.

This basically makes it impossible to navigate back until my stack has 3 or more navigated routes.

*F.Y.I.* For some reason JSFiddle doesn't work with Vue Router in abstract mode, but the code is correct. (Comment out the mode and you'll see)

**Comment by posva** [comment]
This is normal since abstract mode starts in a _nowhere_ state and doing that initial `push` is necessary to start the router. Differently from other histories, abstract do not have access to the url to start the history automatically
