### ISSUE TITLE
how to send query in children router , not working

### ISSUE THREAD

**Issue by davedat** [vuejs/vue-router#3025]
### Version
3.1.3

### Reproduction link
[http://127.0.0.1:8080/#/user](http://127.0.0.1:8080/#/user)

### Steps to reproduce
``` 
const routes = [
  {
    path: '/',
    name: 'home',
    component: Home,
    children: [
      { path: 'user', name:'user', component: User },
```

```
this.$router.push({ name:'user', query:{kw: "abc"} });
```

### What is expected?
i want 
http://127.0.0.1:8080/#/user?kw=abc

### What is actually happening?
it go to  
http://127.0.0.1:8080/#/user

**Comment by posva** [comment]
Please provide a reproduction when reporting a bug: https://jsfiddle.net/16zpdw79/
