### ISSUE TITLE
Vue-router installation broken

### ISSUE THREAD

**Issue by tilleps** [vuejs/vue-router#303]
http://vuejs.github.io/vue-router/en/installation.html

```bash
npm install vue-router
# dev branch
npm install vuejs/vue-router#dev
```

The `package.json` main is pointing to non-existing `dist/vue-router.common.js` file.

Unable to build it either as `npm run build` fails because the `build/*` directory is not included

**Comment by yyx990803** [comment]
You will have to clone from github directly:

``` bash
git clone https://github.com/vuejs/vue-router.git node_modules/vue-router
```

**Comment by tilleps** [comment]
Is there any particular reason why `dist/vue-router.common.js` isn't included in the dist?  It would increase usability for Node users.  It feels like such a hurdle just to be able to do this:
```javascript
var VueRouter = require('vue-router');
```
The way it is now, I can't just `npm install`/`npm update` my vue/vue-router dependencies without having to `npm install`/`npm update` those dependencies and building again.

**Comment by yyx990803** [comment]
Actual released versions have it. It's just the latest dev code you have to
build yourself.

**Comment by tilleps** [comment]
How bizarre.  `npm install vue-router` wouldn't give me the `dist/vue-router.common.js` file, even after a number of uninstall/reinstalls.  Not sure if it was because of npm version 3+ or if it's because of one of my `npm link` dependencies.   Removing all symlinked/`npm link` dependencies and doing a fresh `npm install` seems to have fixed the issue.  Thanks for the quick response.
