### ISSUE TITLE
[docs] improvement / for uncaught exception on duplicated Routes (since v. 3.1.0)

### ISSUE THREAD

**Issue by ibrainventures** [vuejs/vue-router#3034]
### What problem does this feature solve?
Hi,

would be great to have updated examples for the programmatic routing:

https://router.vuejs.org/guide/essentials/navigation.html

for :

router.push('/location', () => {})

and/or have a link ( on the https://github.com/vuejs/vue-router/issues/2881#issuecomment-520554378 )

Would be great.

### What does the proposed API look like?
It would help to prevent or solve this log warnings.

**Comment by posva** [comment]
This is now covered by https://router.vuejs.org/guide/advanced/navigation-failures.html
