### ISSUE TITLE
Vue 路由刷新在谷歌浏览器下回偶尔跳转到主页 

### ISSUE THREAD

**Issue by dj835638078** [vuejs/vue-router#3036]
### Version
3.0.1

### Reproduction link
[http://139.159.149.124:38081/#/examine/commentExamine](http://139.159.149.124:38081/#/examine/commentExamine)

### Steps to reproduce
用的是hash，在当前页刷新页面， 一般会停留在当前页， 但是有的电脑会跳回主路由。跳回主路由时beforeEach里面检测的是to直接变成了home的信息

### What is expected?
希望页面刷新后所有电脑都能停留在当前页面
如http://139.159.149.124:38081/#/examine/commentExamine链接按F5刷新，页面跳转到了http://139.159.149.124:38081/#/index

### What is actually happening?
希望页面刷新后有的电脑跳转到了首页

**Comment by posva** [comment]
Please provide a boiled down editable repro like explained in the issue helper instructions. Open a new issue in English with it and I will take a look
