### ISSUE TITLE
If the third parameter is omitted in router.push(), will cause unhandledRejectionError on SSR

### ISSUE THREAD

**Issue by lmf** [vuejs/vue-router#3037]
### Version
3.1.3

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
1、router.js use beforeEnter in path
```javascript
{
    path: '/index',
    component: Index,
    beforeEnter: (to, from, next) => {
        next({ path: '/' })
    }
```
2. when SSR, this will:   router.push('/index')   =>  history.confirmTransition =>  abort() 

### What is expected?
Don't make unhandledRejectionError

### What is actually happening?
unhandledRejectionError

**Comment by posva** [comment]
Please see related issues and https://github.com/vuejs/vue-router/issues/2881#issuecomment-520554378
