### ISSUE TITLE
Export NavigationDuplicated class

### ISSUE THREAD

**Issue by LEW21** [vuejs/vue-router#3039]
### What problem does this feature solve?
I want to do:

```javascript
try {
	await router.push(...)
} catch (e) {
	if (e instanceof NavigationDuplicated) {}
	else {throw e}
}
```

Unfortunately I can't, because NavigationDuplicated is not exported.

### What does the proposed API look like?
export NavigationDuplicated

**Comment by jonatahr** [comment]
@LEW21 It seems that it was fixed in version 3.1.3. What version are you using?

https://github.com/vuejs/vue-router/commit/5ef5d73

**Comment by FranckFreiburger** [comment]
Please export this, it is quite annoying to compare to the error name.

**Comment by jonatahr** [comment]
@LEW21 and @FranckFreiburger, take a look:
https://github.com/vuejs/vue-router/pull/3047

You will be able to check the error type by property **_type**. This information must be documented.

**Comment by posva** [comment]
I'm closing this in favour of https://github.com/vuejs/vue-router/pull/3047

It's not final API as we want to align it with vue-router-next as much as possible to reduce breaking changes. It will probably be available through an additional property on the error instance to support every browser
