### ISSUE TITLE
Possible to cache the component templates instead of destroying them?

### ISSUE THREAD

**Issue by roblav96** [vuejs/vue-router#304]
I have a basic app here. Has some contacts, reads some info from the database.

I've noticed that each time I switch from my database page to my contacts page, they need to re-render every visit. If I have 250+ contacts with images for each, the page load is unbearable (~2000).

**Can I append the DOM elements elsewhere and re-apply them?**

**Comment by yyx990803** [comment]
Use keep-alive on router-view

**Comment by roblav96** [comment]
ah, that's what that means. I saw that in the docs but didn't put the two together. thank you!!!

**Comment by roblav96** [comment]
So I'm reading through the source and I see two options.

Use as an attribute:
```html
<router-view keep-alive></router-view>
```

Or use as a property when defining the route?
```javascript
'/public': {
	component: require( './routes/public/tabs/tabs.js' ),
	subRoutes: {
		'/login': {
			component: require( './routes/public/login/login.js' ),
			name: 'public.login',
			keepAlive: true
		}
	}
}
```

Is this correct?

**Comment by amirrustam** [comment]
@roblav96 The first option is correct. `keep-alive` is an attribute on dynamic component elements as documented in the main Vue.js docs (http://vuejs.org/guide/components.html#Dynamic_Components) and in the vue-router docs (http://vuejs.github.io/vue-router/en/view.html).

If that answers your question, then I think it's safe for @yyx990803 to close out this issue.
