### ISSUE TITLE
When I use '()' in path regex of router config, it doesn't work

### ISSUE THREAD

**Issue by doubleKGe** [vuejs/vue-router#3040]
### Version
3.1.3

### Reproduction link
[https://codesandbox.io/s/vue-template-nq4gk](https://codesandbox.io/s/vue-template-nq4gk)

### Steps to reproduce
I came across a scenario that required custom matching named parameter rules,so I tried it:
```js
const routes: RouteConfig[] = [
    {
        path: '',
        component: load('main/layout'),
        children: [
            { path: ':a((a)?bc)?', component: load('main/content') }
        ]
    },
    { path: '*', component: load('Error404') }
]
```
but it doesn't work
so I went to ask  the author of path-to-regexp: https://github.com/pillarjs/path-to-regexp/issues/211
And I did it his way:
```js
const routes: RouteConfig[] = [
    {
        path: '',
        component: load('main/layout'),
        children: [
            { path: ':a((?:a)?bc)?', component: load('main/content') }
        ]
    },
    { path: '*', component: load('Error404') }
]
```
but it still bad ,and throw an error
```
Invalid regular expression: /^\/((?:[^\/] ?))\((?:((?:?\:a)))?bc\)(?:\/(?=$))?$/: Nothing to repeat
```
I know it works without '()' of 'a', but this is just a simple example, I need use '()' in my actual work, how do I solve it . Thanks!

### What is expected?
I want the route to match '/' or '/abc' or '/bc'

### What is actually happening?
It doesn't match, and it's an error

**Comment by doubleKGe** [comment]
I tried the second way in path-to-regexp alone, and it worked, but vue-router didn't parse properly

**Comment by posva** [comment]
It seems like this problem was fixed in later versions of path-to-regexp but not in the one used by vue-router. It won't be a problem on future versions of vue-router as they use a newer version of the package but this one doesn't as upgrading implies a few breaking changes. This will be a wontfix for vue-router 3

A workaround is to use the `|` to create multiple possibilities: `/foo/:a(abc|bc)`
