### ISSUE TITLE
Modal Dialogs: router-vue get a default component and keeps old component unless new one is set

### ISSUE THREAD

**Issue by osasson** [vuejs/vue-router#3041]
### What problem does this feature solve?
I think many developers come to a stage where they want to show modal dialogs, regardless of the previous route they were in, and without using some data model.

As far as I have seen, we have no ability doing so while using the history.

One problem might arise when no default view is given, in which case another property could be added as the default component instead of an empty node.

It is not a breaking change and the complexity of its implementation is hopefully very minor.

### What does the proposed API look like?
router-vue becomes 2 more props:
```javascript
preserve: {
  type: Boolean,
  default: false
},
default: {
  type: Function,
  default: null
}
```

and instead of setting the cache directly to the component or rendering an empty node:
```typescript
// render previous view if the tree is inactive and kept-alive
if (inactive) {
  return h(cache[name], data, children)
}

const matched = route.matched[depth]
// render empty node if no matched route
if (!matched) {
  cache[name] = null
  return h()
}

const component = cache[name] = matched.components[name]
```

use something like

```typescript

const renderCachedComponent = () => h(cache[name], data, children)

// render previous view if the tree is inactive and kept-alive
if (inactive) {
  return renderCachedComponent()
}

const matched = route.matched[depth]
// render default or empty node if no matched route
if (!matched) {
  cache[name] = props.default
  return cache[name] ? renderCachedComponent() : h()
}

let component = matched.components[name]
if (!component) {
  if (props.preserve && cache[name])
    return renderCachedComponent()
  component = props.default;
}
cache[name] = component;
```

Its usage would then be:

```html
<template>
  <modal v-if="$route.meta.dialog">
    <router-view name="dialog"/>
  </modal>
  <router-view :default="Home" :preserve="true"/>
</template>
```

**Comment by posva** [comment]
Thank you looking into it but if you want to display a different component or an extra one based on a condition **without changing** the route, that's something you will have to handle in your code by setting flags on `meta` and a similar `v-if` to what you showed. From the router perspective the displayed view must be connected to the current location

**Comment by osasson** [comment]
@posva Thanks, I guess my example was not thorough enough, so I think you misunderstood me, I actually want to change the route but not change the content of the other views. I hope this example will make it clearer. As you can see, I do not need to define all views for each route, which makes the flow easier in this case, which IMO is not that seldom.

router.ts
```ts
const router = new Router({
  mode: 'history',
  base: process.env.BASE_URL,
  routes: [
    { path: '/', component: Home, },
    { path: '/news', component: News, },
    ...
    { path: '/contact', components: { dialog: Contact }, meta: { dialog: true }},
  ],
});
```

App.Vue
```html
<template>
  <modal v-if="$route.meta.dialog">
    <router-view name="dialog"/>
  </modal>
  ...
  <router-view :default="Home" :preserve="true"/>
  ...
  <footer>
    <router-link to="/contact">Contact</router-link>
  <footer>
</template>
```

**Comment by posva** [comment]
See #703
