### ISSUE TITLE
Routing to named parent does not load child component to child router view

### ISSUE THREAD

**Issue by luckylooke** [vuejs/vue-router#3043]
### Version
3.1.3

### Reproduction link
[https://jsfiddle.net/luckylooke/b0xvae8g/2/](https://jsfiddle.net/luckylooke/b0xvae8g/2/)

### Steps to reproduce
 - click router link labeled "name user"

### What is expected?
default component UserHome to be loaded to child router view

### What is actually happening?
default component UserHome content will disappear from child router view

**Comment by luckylooke** [comment]
Thank you for great open source software! 👍 
And I did like the idea with custom issue creator https://new-issue.vuejs.org/, very clever 👏 🙂

**Comment by posva** [comment]
Thanks for the kind words!
This is expected, you even have a warning in the console telling you about it :)

**Comment by luckylooke** [comment]
ahaa.. sorry I did not check console correctly, I just check there is no error :D My bad, I have ignored warnings. But is there a discussion or something so I can understand why is this wanted behavior? Thanks
