### ISSUE TITLE
Navigation guards being triggered on unused router on history back/forward.

### ISSUE THREAD

**Issue by trafium** [vuejs/vue-router#3046]
### Version
2.6.0

### Reproduction link
[https://jsfiddle.net/7n5jkgv9/2/](https://jsfiddle.net/7n5jkgv9/2/)

### Steps to reproduce
Click both Foo and Bar links, then try to go back and forward in browser history.

### What is expected?
Unused by any Vue app VueRouter's navigation guard should not be triggered.

### What is actually happening?
Unused by any Vue app VueRouter's navigation guard is being triggered.

**Comment by posva** [comment]
This is normal, both routers are connected to the same address bar. You are not supposed to have more than one router connected to the address bar. You can use an abstract one if you need it
