### ISSUE TITLE
colon literal in Vue router

### ISSUE THREAD

**Issue by begueradj** [vuejs/vue-router#3050]
### Version
3.1.3

### Reproduction link
[https://github.com/begueradj/nuxt-extend-routes-bug](https://github.com/begueradj/nuxt-extend-routes-bug)

### Steps to reproduce
My URLs have double colon on them.

I push a path to Nuxt router which has **:** as a part of it.

      export default {
      router: {
        extendRoutes (routes, resolve) {
          routes.push({
            name: 'custom',
            path: 'towns'   '(:[0-9].*)?/',
            component: resolve(__dirname, 'pages/404.vue')
          })
        }
      }
    }

### What is expected?

When I point to http://localhost:3000/towns:3 , I must see my 404.vue page without any error

### What is actually happening?

When I point to http://localhost:3000/towns:3 , for example, the **:** is translated as `%3A`on the URL leading to this error message:

    Expected "1" to match ":[0-9].*", but received "%3A2"

**Comment by posva** [comment]
We need a boiled down repro with vue-router. You can use this sandbox: https://codesandbox.io/s/vue-router-template-dzhtz

Please open a new issue with the repro if you manage to reproduce it without Nuxt
