### ISSUE TITLE
it is unnecessary to make the NavigationDuplicated as an error

### ISSUE THREAD

**Issue by midcu** [vuejs/vue-router#3052]
### What problem does this feature solve?
for this. we need to add the following code anywhere.
`
if (n !== this.$route.name) { this.$router.push({ name: n }) }
`

### What does the proposed API look like?
delete the NavigationDuplicatedError

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
