### ISSUE TITLE
Allow greater control over order of routes

### ISSUE THREAD

**Issue by enjibby** [vuejs/vue-router#3053]
### What problem does this feature solve?
Currently, Dynamic Matching Priority https://router.vuejs.org/guide/essentials/dynamic-matching.html#matching-priority states that the first route to be added to the list will take precedence over other routes that are added after.

If I were to define a catch-all/404-style route at the end of my route list, then it will cause no problem to the previous routes. But if I decide to create an additional route afterwards, this would not be available as the catch-all route would take priority.

For example, I want to allow administrator users to press an "Add content to this URL" button when they land on a URL that doesn't exist in the route list. In order to achieve this, I would need to create a new route for the non-existent URL *before* the catch-all route. The only alternative I can currently see is to completely refresh the page using a POST request to add the URL or to dismantle and recreate the Vue.$router object.

### What does the proposed API look like?
For my specific use-case, I expect the desired behaviour could be achieved by adding an optional "before" parameter to the addRoutes function e.g. `router.addRoutes([ { path:"/new-page" } ], catchAllRoute)`. But I see a greater benefit in general if the route list could be accessed and updated in a more dynamic way.

**Comment by posva** [comment]
Current router matcher doesn't allow this but  path ranking is already supported on the next version and it avoids the issue by correctly ordering the records
