### ISSUE TITLE
Path as token

### ISSUE THREAD

**Issue by ghost** [vuejs/vue-router#3055]
### Question!
I have read the path-to-regexp library. And i saw a method that i need. 
`pathToRegexp.parse()`
I could not find in sources. Does vue-router exposes this or something similar? 

![Screen Shot 2019-12-07 at 00 06 20](https://user-images.githubusercontent.com/1254613/70356687-fba78c00-1885-11ea-9689-48d81d38b3bd.png)

**Comment by posva** [comment]
No it doesn't expose it.

---

Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
