### ISSUE TITLE
nested routes & missing param for named route

### ISSUE THREAD

**Issue by newbie78** [vuejs/vue-router#3057]
### Version
3.1.3

### Reproduction link
[https://github.com/newbie78/routerbug](https://github.com/newbie78/routerbug)

### Steps to reproduce
mkdir ./routerbug && cd ./routerbug
git clone git@github.com:newbie78/routerbug.git .
yarn install
yarn serve
open project in browser and see to console

### What is expected?
child route without param
router-link :to="{ name: 'about' }" generates without warning in console

### What is actually happening?
got the warnings

---
aniway all worked but why the warning adds to console?
![image](https://user-images.githubusercontent.com/28735/70391298-96b67800-19e4-11ea-8f96-e41ebde673f5.png)

**Comment by ghost** [comment]
Hello @newbie78 ,
As I see it, your routes `home` and `about` declared as children to `/:lang` parent
```
export default [
  {
    path: '/:lang',
    component: {
      render(c) { return c('router-view'); },
    },
    children: [
      {
        path: '',
        name: 'home',
        component: loadComponent('Home'),
      },
      {
        path: 'about',
        name: 'about',
        component: loadComponent('About'),
      },
    ],
  },
  ...
];
```
So to avoid warnings you should either use your `<router-link>`s in the nested `<router-view>` or explicitly provide `:lang` value.
Please take a look at the example in the official docs: [Nested Routes](https://router.vuejs.org/guide/essentials/nested-routes.html)

**Comment by newbie78** [comment]
Hi @hrmn-dvlpr, thanx for you interesting )

yes, but i'm use two router-view:

![image](https://user-images.githubusercontent.com/28735/70435747-b6a77380-1a98-11ea-9a76-78e2406e0627.png)
![image](https://user-images.githubusercontent.com/28735/70435791-d2127e80-1a98-11ea-9255-0664850fe354.png)

or im must place router-link's inside second view?

**Comment by newbie78** [comment]
![image](https://user-images.githubusercontent.com/28735/70439099-4bfa3600-1aa0-11ea-963f-736dad9bab22.png)

im change components structure and warnings is lost. tanx

according to the first embodiment. why is there are warnings and everything works correctly? what could go wrong?

**Comment by ghost** [comment]
it worked because your default route redirecting to the `/en` path which fulfills `/:lang` parameter, but if you, for example, will try to use these `<router-link>`s without explicit :lang parameter in another top level component, it will not put `href` value correctly and links will send you to `/`

**Comment by posva** [comment]
This is because the links render a first time before the initial navigation happens which cause them to be invalid but after the redirect they implicitly get the param from the current location. You can use an immediate watcher on `$route` to see that it initially has a different value
