### ISSUE TITLE
NavigationDuplicated when deleting a query parameter

### ISSUE THREAD

**Issue by vallemar** [vuejs/vue-router#3061]
### Version
3.1.3

### Reproduction link
[https://jsfiddle.net/vallemar/rfwo5m3v/36/](https://jsfiddle.net/vallemar/rfwo5m3v/36/)

### Steps to reproduce
To reproduce the problem just click on the button. The function that calls what it does is add or remove a query in the router url. To see the errors you have to see the console with F12.

### What is expected?
By removing the parameter from the query the url would change and not give an exception. Also delete the query from the browser url without waiting for the next .push

### What is actually happening?
When making the exception (which should not be given since the query is different) the parameter of the deleted query is not removed from the physical url until the next .push or .replace

**Comment by posva** [comment]
`$route` is readonly, if you reuse its query, duplicate the object. `query`

```js
methods: {
  	changeURL: function(){
      let route = this.$route
      if (Object.keys(route.query).includes(this.query)) {
          this.queryPush = {...route.query}
          delete this.queryPush[this.query]
          this.$router.push({ path: '/', query: this.queryPush })
      }else{
      		this.queryPush = {[this.query] : this.value }
          this.$router.push({ path: '/', query:  this.queryPush })
      }
    }
  }
```

**Comment by WebKieth** [comment]
This is not a real reason of this error.
this.$router.replace({ query: {} })
Always, in 100% cases calls this error
