### ISSUE TITLE
Catch all route (asterisk route) error when matched path is empty string

### ISSUE THREAD

**Issue by adi-zz** [vuejs/vue-router#3062]
### Version
3.1.3

### Reproduction link
[https://codesandbox.io/s/vue-template-c3dox](https://codesandbox.io/s/vue-template-c3dox)

### Steps to reproduce
Go to https://codesandbox.io/s/vue-template-c3dox

Click on link `go to /anything/123 `.
Click on button `go to [current url]?foo=bar`.
You get to page `/anything/123?foo=bar` - as expected.

Now, click on link `go to /anything/ `.
Click on button `go to [current url]?foo=bar`.
You get to page `/?foo=bar`.

### What is expected?
You should get to page `/anything/?foo=bar`.

### What is actually happening?
You get to `/?foo=bar`.
And console says: "[vue-router] missing param for named route "catchAllRoute": Expected "0" to be defined".

**Comment by posva** [comment]
Copying the normalized route and passing that to push isn't really valid. Use this instead

```js
const newRoute = {
        path: this.$route.path,
        query: { foo: "bar" }
      }; 
````

**Comment by adi-zz** [comment]
@posva 

[Documentation](https://router.vuejs.org/guide/essentials/navigation.html#router-push-location-oncomplete-onabort) says you can use "named route" when calling `router.push`. Is it fair to say that a remark should be added in the doc saying "named route" + `router.push` is not supported when the named route is a catch all route?

Because:
```
this.$router.push({
  name: "catchAllRoute",
  params: { pathMatch: "" }
});
// => [vue-router] missing param for named route "catchAllRoute": Expected "0" to be defined
```

Although:
```
this.$router.push({
  name: "catchAllRoute",
  params: { pathMatch: "bla" }
});
// => works as expected, but what if
//       I need to redirect to a path with `pathMatch` being the empty string?

this.$router.push({
  name: "catchAllRoute",
  params: { 0: "" }
});
// => works as expected, by as I understand `0` should not be used
//       https://github.com/vuejs/vue-router/issues/2742#issuecomment-487026392
```

Needless to say, I would prefer "named route" + `router.push` to do work for catch all routes.

**Comment by adi-zz** [comment]
So @posva isn't this a bug?
cc @LinusBorg
