### ISSUE TITLE
why not create a new navigation guard called like “firstLoading”

### ISSUE THREAD

**Issue by duyefeng** [vuejs/vue-router#3064]
### What problem does this feature solve?
sometimes we need a navigation guard just for ”router first loading“ , so why not create a new
navigation guard to distinguish between ”first loading“ and ”each update（beforeEach）“，sorry，i am Chinese，English is not very fluent。
有的时候我们需要首次加载路由的导航守卫，所以为什么不创造一个新的导航守卫用来区分首次加载路由和每次路由更新呢

### What does the proposed API look like?
router.firstLoading

**Comment by posva** [comment]
because you can add it and remove it the first time it's used:

```js
const removeGuard = router.beforeEach((to, from, next) => {
  next()
  removeGuard()
})

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by duyefeng** [comment]
Thank you for your answer, next time i will consider in [StackOverflow]🙂
