### ISSUE TITLE
router.go and its implementations doesn't mark n as optional

### ISSUE THREAD

**Issue by FyiurAmron** [vuejs/vue-router#3065]
### Version
3.1.3

### Reproduction link
read [https://developer.mozilla.org/en-US/docs/Web/API/History/go#Parameters](https://developer.mozilla.org/en-US/docs/Web/API/History/go#Parameters)

### Steps to reproduce
verify the source code vs the spec

### What is expected?
router.go and its history implementations should mark the delta param as optional (also, if possible, the param should be named more descriptively, e.g. "delta" as in spec)

### What is actually happening?
router.go and its history implementations are marking "n" as required, although it actually isn't, and should default to 0 to maintain POLA

### Source code links

https://github.com/vuejs/vue-router/blob/479510b2bf6342cf083299da28334c6925ae465a/src/index.js#L175

also https://github.com/vuejs/vue-router/blame/479510b2bf6342cf083299da28334c6925ae465a/src/history/html5.js#L40 etc. (all https://github.com/vuejs/vue-router/tree/479510b2bf6342cf083299da28334c6925ae465a/src/history implementations are affected)

**Comment by posva** [comment]
This is intended as there is no _reload_ in the router

**Comment by FyiurAmron** [comment]
@posva there *was* a `reload` method, but AFAIK it was removed some time ago - if it *is* there, please link me to it, and consider https://stackoverflow.com/questions/41301099/do-we-have-router-reload-in-vue-router/47005895#47005895 , https://github.com/vuejs/vue-router/pull/442 & https://router.vuejs.org/api/#router-instance-methods in the meantime, instead of arbitrarily closing the issue.

Also, regardless of the existence/absence of `reload`, you didn't address the fact that current behaviour fails POLA vs current HTML/JS WebAPI spec. Not substantiating your POV on this matter makes you reply a "meh" by itself, which is something that evokes a feeling of severe disrespect. I'm aware it's possible this happened due to your young age, but please don't do that in the future.
