### ISSUE TITLE
Want to refresh page with same path but different query parameters.

### ISSUE THREAD

**Issue by lamiru** [vuejs/vue-router#3071]
### Version
3.0.1

### Reproduction link
[http://jsfiddle.net/erdo58mc/](http://jsfiddle.net/erdo58mc/)

### Steps to reproduce
Current url is

/?type=1

I want to use router.push on this page.

this.$router.push('/?type=2');

But this gives NavigationDuplicated error.

I don't want to use params like

/:type

### What is expected?
page refresh

### What is actually happening?
nothing

**Comment by posva** [comment]
Always provide a runnable repro when reporting a bug, please.

---

Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
