### ISSUE TITLE
Named catch-all route warns if `pathMatch` is empty

### ISSUE THREAD

**Issue by posva** [vuejs/vue-router#3072]
### Version
3.1.3

### Reproduction link
[http://jsfiddle.net/yza5k02v/](http://jsfiddle.net/yza5k02v/)

### Steps to reproduce
- click on /nope
- click on button

### What is expected?
no warn

### What is actually happening?
there is a warn

---
maybe the param should be marked as optional to prevent this warning from ever happening

**Comment by yinm** [comment]
Can I work on this?

**Comment by kazupon** [comment]
@yinm 
You can contribute to it!
