### ISSUE TITLE
asterisk without root slash fails to match routes

### ISSUE THREAD

**Issue by wlnirvana** [vuejs/vue-router#3074]
### Version
3.1.3

### Reproduction link
[https://jsfiddle.net/c7hvumdn/](https://jsfiddle.net/c7hvumdn/)

### Steps to reproduce
Clicking any of the three links (` Go to Bar`, `Go to /B/a/z`, `Go to /b/a/b/c/d/e/f`), the Foo component does not show up, which means the catch-all route fails.

### What is expected?
all routes should be catched by the wildcard match and only Foo  be displayed

### What is actually happening?
Foo, Bar, Baz all can show up.

**Comment by posva** [comment]
The asterisk route has a special treatment and is put at the end precisely to prevent this mistake of including it before other routes and ending up catching too much

**Comment by wlnirvana** [comment]
@wlnirvana So a single `*` route has to be in the end to take effect, but "mixed wildcard" like `/user-*` does not necessarily come in the end. Right?
