### ISSUE TITLE
Update documentation to explain the return values of Navigation Guards

### ISSUE THREAD

**Issue by ggedde** [vuejs/vue-router#3077]
### What problem does this feature solve?
Currently the Guide Documentation doesn't explain the return values of the Navigation Guards. It is listed in the API Reference, but it is just a single line and very difficult to find.  I honestly never found it in the Documentation when I was looking and instead found some Vue Issues with users explaining it, but never listing any documentation to it.  I only found it in the API Reference by doing site find on page search for "remove".

### What does the proposed API look like?
I feel that this should be shown with examples and listed in the Sidebar in its own section for "Removing Registered Guards", etc and listed in the Guide with a link to it in the API Reference.

Thanks

**Comment by posva** [comment]
I think that because removing guards is something most people won't need until they meet advanced use cases, it's better placed in the API section as it is now

**Comment by ggedde** [comment]
@posva That's fine, but I still think it could use some examples and should be listed in the sidebar as its own section in the API Reference to help others.
