### ISSUE TITLE
Advanced Matching Patterns not working properly

### ISSUE THREAD

**Issue by thierri** [vuejs/vue-router#3078]
### Version
3.1.3

### Reproduction link
[https://codepen.io/thierri-oliveira/pen/wvBeBzV](https://codepen.io/thierri-oliveira/pen/wvBeBzV)

### Steps to reproduce
Just click on the first link (test-one) 

### What is expected?
The route show match with the definition and the param id_one should be captured.

### What is actually happening?
The route don't match and the param id_one its not captured.

---
If you test exactly the same path and regex on the express route tester (http://forbeslindesay.github.io/express-route-tester/) provided by path-to-regexp package, everything works fine.

**Comment by posva** [comment]
It only works on 0.1.7 but we are using 1.7.x where it doesn't work

Here is a version that works: `{ path: '/test-dos/:id_one([a-z]+)-:dos([a-z]+)' },`. It is then possible to use the `props` option to reshape that property into a single one
