### ISSUE TITLE
页面 replace('/404') 跳转时 报错Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by apprat** [vuejs/vue-router#3080]
### Version
3.1.3

### Reproduction link
[https://vdapk.com](https://vdapk.com)

### Steps to reproduce
/ a路由路由到404了（）通配符，然后整个页面渲染404然后浏览器报TypeError：无法读取null的属性“ classList”，看字面意思应该是路由变化时会给对应的router-link添加类时页面重渲染了该a标签也不在了所以出现这个错误，但奇怪的是，页面上也没有router-link to =“ ”是通配符的，这个报错也不是每次都会触发

### What is expected?
修复

### What is actually happening?
错误

**Comment by apprat** [comment]
无论是replace还是push都会报同样的错

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
When reporting a bug, provide a runnable boiled down repro as specified in the issue helper
