### ISSUE TITLE
Url is not correct in ie9 use window.open

### ISSUE THREAD

**Issue by kanbekotori** [vuejs/vue-router#3083]
### Version
3.0.1

### Reproduction link
[https://github.com/kanbekotori/vue-router-ie9/tree/master](https://github.com/kanbekotori/vue-router-ie9/tree/master)

### Steps to reproduce
- Run `npm install` to install dependencies.
- Write a html file to open a new window to load vue project.
- Use IE9 to open the html file and click the button.

```
<html>
	<head>
	</head>
	
	<body>
		<button id="test">Click</button>
	</body>
	
	<script type="text/javascript">
		var url = 'http://localhost:9059/#/page1';
		function openDialog() {
			var winWidth = 1200
			var winHeight = 700
			window.open(
			  url,
			  '_blank',
			  'toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=no, copyhistory=no, width='   winWidth   ', height='   winHeight
			)

		}
		document.getElementById('test').onclick = function () {
			openDialog();
		}
	</script>
</html>
```

### What is expected?
window.open will load `http://localhost:9059/#/page1` and show `page01` message.

### What is actually happening?
window.open load `http://localhost:9059/#/` and show `home` message.

**Comment by posva** [comment]
I couldn't reproduce the problem but this shouldn't be related to vue-router as it's using a JS method to open a new browsing context
