### ISSUE TITLE
已处理

### ISSUE THREAD

**Issue by killer99999** [vuejs/vue-router#3085]
已处理

**Comment by killer99999** [comment]
![image](https://user-images.githubusercontent.com/46144321/71658006-33b6c780-2d7d-11ea-9b1e-3d9525d27af8.png)

![image](https://user-images.githubusercontent.com/46144321/71658023-48935b00-2d7d-11ea-9ef2-8270291db723.png)

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
