### ISSUE TITLE
<router-link> throws an error if multiple child elements provided with v-slot API.

### ISSUE THREAD

**Issue by theharshin** [vuejs/vue-router#3091]
### Version
3.1.3

### Reproduction link
[https://codesandbox.io/s/condescending-yalow-gn5fz?fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.vue&theme=dark](https://codesandbox.io/s/condescending-yalow-gn5fz?fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.vue&theme=dark)

### Steps to reproduce
Create a router-link component with v-slot API and provide multiple child elements.

### What is expected?
According to the docs here: https://router.vuejs.org/api/#v-slot-api-3-1-0
The content should be automatically wrapped with <span> and router-link should work fine.

### What is actually happening?
The rendering of a component fails and throws an error with the following message: "TypeError: this.props is undefined"

**Comment by theharshin** [comment]
It looks like when Vue tries to show a warning for a single child but fails because `this.props` is undefined.
![image](https://user-images.githubusercontent.com/7118937/71971039-c6e57680-322f-11ea-8228-3ab86802a89c.png)

**Comment by LinusBorg** [comment]
should be `this.$props.to`

https://github.com/vuejs/vue-router/blob/927f0c9013141c95df77a82b84acb7cc77c238c5/src/components/link.js#L110
