### ISSUE TITLE
How to use vue router to redirect to a file

### ISSUE THREAD

**Issue by MatteoGauthier** [vuejs/vue-router#3092]
How to use vue router to redirect to a file.
I want to redirect the user to a pdf file from the '/cv' location. I've tried 
```
extendRoutes(routes, resolve) {
      routes.push({
        path: "/CV.pdf",
        name:'cv',
      });
    },
```

Can somebody help me ?

**Comment by LinusBorg** [comment]
just use a plain anchor tag ?

**Comment by MatteoGauthier** [comment]
@linusborg Yes I can do this but if my visitors wants to directly be redirected to my resume..

**Comment by LinusBorg** [comment]
Then programmatically set `window.location`.

The router's job is to route between frontend components on the client side. It doesn't and shouldn't care about links to any kind of asset located on the server side.
