### ISSUE TITLE
disable v-link on null value?

### ISSUE THREAD

**Issue by SeoFood** [vuejs/vue-router#31]
```html
<a v-link="{{ previousStep }}" v-class="disabled: ! previousStep">Link</a>
```

If previousStep is null I get an error: 
> Uncaught TypeError: Cannot read property 'replace' of null

It should be something like that:
```javascript
if (e.button === 0) {
          e.preventDefault()
          if (value !== null)
              vm.route._router.go(self.destination)
}
```

**Comment by yyx990803** [comment]
Closed via 8b3c35ea2e53f9e182cec73e43de4500f0554dc9 & 0d4469be5e45c44c35b66057f06b054c58ca0b7d
