### ISSUE TITLE
Reloading route

### ISSUE THREAD

**Issue by socieboy** [vuejs/vue-router#310]
Sorry I know this is not the place to ask this question but the forum and the chat takes a while to get some feedback. Any way...

I have a router defined like that
```
'page/:slug': {
                        name: 'page',
                        component: require('./components/pages/pages')
                    },
```
Where I show dynamic pages,
when I load the page I do a ajax request to pull the page from the database, title and content of the page.
the pull request make a request tu the URL when the component it's created
```
created: function(){
        this.$http.get('api/pages/'+ this.$route.params.slug, function(page){
            this.$set('page', page)
            this.loading = false;
        });
    },
```
So here is my issue, when im in page htttp://app.dev/pages/page-1 and y do click to other page htttp://app.dev/pages/page-2 the URL change but seems like it doesn't reload the component, where I should put the code to update the page variable?

**Comment by fnlctrl** [comment]
Because the component is reused, so the created hook never got fired again.
You can either: 
1. Set `component.route.canReuse` to `false`, which is most straightforward but not recommended;
2. Recommended: use component.route.data, read the [docs](http://vuejs.github.io/vue-router/en/pipeline/data.html) about it.

**Comment by socieboy** [comment]
Thank you! I will go for the second one!

**Comment by socieboy** [comment]
Sorry to ask again but I have another issue and I can't resolve.

I have a master component that have this code
```
    route: {
        waitForData: true,
        data: function (transition) {
            this.$http.get('/api/me').then(function(response){
                this.$set('user', response.data);
                transition.next();
            });
        }
    },
```
It's a get request to the server, and this master component have a <view-router> tag in the template to show other sub components, each time a change the internal route the master component is like rendered again, and made another get request to the server I don't need that how can i use render the internal routes?
