### ISSUE TITLE
Router link active class not applied with non ascii params

### ISSUE THREAD

**Issue by vkaelin** [vuejs/vue-router#3103]
### Version
3.1.3

### Reproduction link
[https://codesandbox.io/s/romantic-browser-xvj0m](https://codesandbox.io/s/romantic-browser-xvj0m)

### Steps to reproduce

* Refresh page at https://xvj0m.csb.app/user/t%C3%A9st : the active class is not applied.

### What is expected?
Active class on the router link

### What is actually happening?
No active class is applied

---

Finally, the active class is applied when you click on router links, even with non ASCII char. The only problem is at the first load of the page.

**Comment by yonicb** [comment]
### I have the same problem ! 💥
