### ISSUE TITLE
push to named star route with empty pathMatch fails

### ISSUE THREAD

**Issue by adi-zz** [vuejs/vue-router#3106]
### Version
3.1.3

### Reproduction link
[https://codesandbox.io/s/vue-template-7k3sv](https://codesandbox.io/s/vue-template-7k3sv)

### Steps to reproduce
1. Open https://codesandbox.io/s/vue-template-7k3sv
1. Click [button 1]. Note you get to `https://7k3sv.csb.app/anything/123` - which is ok.
1. Click [button 2].

### What is expected?
You should get to `https://7k3sv.csb.app/anything/`.

### What is actually happening?
You get to `https://7k3sv.csb.app/`.

---
I checked a couple of vue-router issues in the past, and I noticed posva has his own particular way of assessing bugs, so I know he will say this is not a bug. But is there anyone in vue-router team willing to acknowledge this is a bug? (cc @yyx990803, @kazupon)

I used the latest vue-router available on npm (3.1.5). My current issue report says I used 3.1.3 because new-issue.vuejs.org does not let me choose 3.1.5. Guys, if you force me using new-issue.vuejs.org when reporting an issue, it would be nice to keep it up-to-date.

**Comment by posva** [comment]
The workaround for this is using a named param with a custom regexp, which will be the preferred way in the next major version:

```js
{
      name: "catchAllRoute",
      path: "/anything/:pathMatch(.*)"
    }
```
