### ISSUE TITLE
Set $route meta data dynamically.

### ISSUE THREAD

**Issue by pavinthan** [vuejs/vue-router#3108]
### What problem does this feature solve?
For SEO / Layout purpose good to have ```$route.setMeta``` method to update current route's meta information because if we view an artical, I'll fetch artical title using route param first, then We can set the page title.

please advice me.

### What does the proposed API look like?
To update current route meta data
```
this.$route.setMeta({
    title: "Example title from service."
})
```

Then we can have separete hook for route modifed like
```
router.onUpdate((route) => {
    // do something here
    document.title = route.meta.title;
})
```

**Comment by posva** [comment]
The metadata is intentionally not dynamic, that would be like a state. You can already store different metadata in each record and read it in hooks to change the title.

For SEO purposes you might find yourself using https://github.com/nuxt/vue-meta

**Comment by pavinthan** [comment]
@posva Thanks for your explanation, 

but still I'm still unclear about this usecase
I have a question to leave
1. How dynamic route like `posts/:postId` contains static meta data?

anyway thanks for your effort guys 🙏 `vue-router` is awesome.

**Comment by posva** [comment]
Use the meta fields: https://router.vuejs.org/guide/advanced/meta.html#route-meta-fields

**Comment by jhicksrowmark** [comment]
@posva your answer is not a solution. Here's a practical example: you are loading product data from your API and want to show the product title as the document title. Are you telling me the only option in Vue is to hard-code your entire catalog in the route config? That's ridiculous. Please provide a solution or reopen this for feature consideration.

**Comment by cayoub88** [comment]
This is slightly tricky to do... Using meta fields doesn't fix the problem as I cannot seem to pass a function to return a dynamic string... Something like vue-meta doesn't help me, as I'm trying to set dynamic breadcrumbs, which are different than titles...

**Comment by cayoub88** [comment]
@jhicksrowmark - in your case you would be able to set the meta data on the view making the API call (using the vue-meta plugin mentioned above - it supports async operations).

My issue is related to this ticket but has to do with updating a `breadcrumb` property. I wanted to base my breadcrumbs on my routes, but some routes (or breadcrumbs) need to be dynamic. And unfortunately the page title cannot be used, because a page title and a breadcrumb are not necessarily always the same thing...

**Comment by charbs-io** [comment]
@jhicksrowmark  - in your case you would be able to set the meta data on the view making the API call (using the vue-meta plugin mentioned above - it supports async operations).

My issue is related to this ticket but has to do with updating a `breadcrumb` property. I wanted to base my breadcrumbs on my routes, but some routes (or breadcrumbs) need to be dynamic. And unfortunately the page title cannot be used, because a page title and a breadcrumb are not necessarily always the same thing...

Doing something like this (referenced on the vue forums) does not work...
```
meta: {
  breadcrumb: route => `${route.params.month}`
}
```

**Comment by posva** [comment]
@cayoub88 I don't know the post you are referring to but I imagine that can be combined with an `afterEach` hook:

```js
router.afterEach(to => {
  updateBreadcrumb(to.meta.breadcrumb(to))
})
```

Note you might need to go through the `matched` array depending on how it used (see https://router.vuejs.org/guide/advanced/meta.html#route-meta-fields). In v4 `meta` is merged from parent to child on `to.meta`, so it won't require that loop

**Comment by charbs-io** [comment]
@posva - fantastic, i hadn't thought about invoking `to.meta.breadcrumb(to)`! Thanks for replying!

**Comment by fuoridallarete** [comment]
> @posva - fantastic, i hadn't thought about invoking `to.meta.breadcrumb(to)`! Thanks for replying!

Sorry @cayoub88, I didn't get how you used it.
In my code ```updateBreadcrumb``` is not defined, how do you set it in the breadcrumb title?
```
{
          path: '/dayDetail/:id',
          name: 'dayDetail',
          component: () => import('./views/DayDetail.vue'),
          meta: {
            breadcrumb: [
              { title: 'Storico', url: '/history' },
              { title: 'Storico', url: '/history' },
              { title: route => `${route.params.startDate}`, active: true }, // make this title dynamic
            ],
            parent: 'history',
         },
 },
```
Thanks for the help

**Comment by JustineMiko** [comment]
Hi @fuoridallarete,
Did you find a solution for this issue about making your breadcrumb title dynamic inside metafields ?

**Comment by aesdotjs** [comment]
I know its an old issue but If you ever need to have dynamic meta fields : 

```
meta: {
              layout: 'view-layout',
              parent: { title: 'Projets' },
              section: (route) => ({
                title: route.params.projectType === ProjectTypes.Casp ? 'CASPs' : 'EICs',
                icon: 'pi-cog',
              }),
              path: (route) => ({
                title: route.params.projectType === ProjectTypes.Casp ? 'Création d\'une CASP' : 'Création d\'un Portail EIC',
              }),
              requireRoles: (route) => {
                if (route.params.projectType === ProjectTypes.Casp) {
                  return [SuperviseurCasp'];
                }
                if (route.params.projectType === ProjectTypes.PortailEic) {
                  return [SuperviseurPortailEic'];
                }
                return [];
              },
            },
```
            
          And then overcharge meta fields using : 
          
        ```  router.beforeEach((to) => {
              const { meta } = to;
              Object.keys(meta).forEach((key) => {
                if (typeof meta[key] === 'function') {
                  meta[key] = meta[key](to);
                }
              });
            });
```
