### ISSUE TITLE
Aborting navigation throws `undefined`

### ISSUE THREAD

**Issue by diachedelic** [vuejs/vue-router#3122]
### Version
3.1.3

### Reproduction link
[https://jsfiddle.net/0ukqxgho/1/](https://jsfiddle.net/0ukqxgho/1/)

### Steps to reproduce
Click the `/foo` button, check the browser console for errors

### What is expected?
An `Error` be thrown.

### What is actually happening?
`undefined` is thrown.

---
The [docs](https://router.vuejs.org/guide/essentials/navigation.html#router-push-location-oncomplete-onabort) specify that if a navigation is aborted, then the promise returned by `$router.push` is rejected. This was causing me grief because I was trying to track down where an `Uncaught (in promise) undefined` error was being thrown - would have been helpful to have been able to narrow down the error faster.

**Comment by posva** [comment]
See https://github.com/vuejs/vue-router/pull/3047
