### ISSUE TITLE
$route incorrect for view when inactive (in combination with keep-alive)

### ISSUE THREAD

**Issue by tafelnl** [vuejs/vue-router#3126]
### Version
3.1.3
(and up to 3.1.5 as well)

### Reproduction link
[https://jsfiddle.net/mdvL4276/29](https://jsfiddle.net/mdvL4276/29)

### Steps to reproduce
1. Open the JsFiddle
2. Click 'navigate to random'

### What is expected?
The list that shows all children of the App.vue should all have their own correct id. The id is a computed property that is computed the following:
`return this.$route.params.id`

In the JsFiddle I also implemented a workaround myself. This is done as follows:
```
  data() {
    return {
      'routeFixed': this.$route
    }
  },
```
This way the `routeFixed` property will always have the correct `$route` info available.

### What is actually happening?
The $route param changes when the view becomes inactive. In my opinion it should remained fixed as it is linked to that specific view. 

---
This can cause all sorts of problems and issues. For example, I have a computed property based on one of the $route.params variables. If I then make a watcher on that computed property, it will actually execute the code within that watcher's handler (because it changed from some value to undefined). Of course this can be worked around by adding a check to see if the variable is undefined, but I don't think that should be necessary. Besides that it can cause problems when you use that computed property in a Vue plugin that does not check for undefined for example.

**Comment by posva** [comment]
See https://github.com/vuejs/vue/issues/5477

**Comment by tafelnl** [comment]
@posva Okay, it might be the same problem indeed. But the workaround given there is not viable (see the problem I mentioned above). Also the disadvantage of the workaround given by myself is not reactive of course. So both are not desirable.

Do you agree this is a bug in vue-router in the first place? Or is this expected behaviour?

**Comment by posva** [comment]
The right workaround is the one highlighted by Evan, not the one after that is attaching properties to the route (which is not supported). The workaround is something like this (applied to your example):

```js
const Foo = {
data() {
    return {
      'routeFixed': this.$route,
      isActive: true
    }
  },
  watch: {
    $route() {
      if (isActive) this.routeFixed = this.$route
    }
  },
  activated() { this.isActive = true },
  deactivated() { this.isActive = false },
}
```

**Comment by tafelnl** [comment]
Thanks a lot, that workaround seems pretty solid. But do you expect this problem to be addressed anytime soon? Because this is not very ideal. I now have to implement this method in about 60 different views 😅

**Comment by posva** [comment]
The behavior won't change because as Evan said it's part of how kept alive components work
You can definitely refactor this using a mixin or composition api
