### ISSUE TITLE
beforeRouteLeave don't prevent router.back()

### ISSUE THREAD

**Issue by alphatr** [vuejs/vue-router#3128]
### Version
3.1.5

### Reproduction link
[https://jsfiddle.net/alphatr/eawpdvb6/](https://jsfiddle.net/AlphaTr/eawpdvb6/)

### Steps to reproduce
open https://jsfiddle.net/alphatr/eawpdvb6/ and click `Go to Page` then click `back`;

### What is expected?
Neither `location.hash` nor `$route` change

### What is actually happening?
location.hash is changed

---
if beforeRouteLeave used next in synchronize, the location.hash is not change;

**Comment by posva** [comment]
This is expected because `router.back` triggers `history.go(-1)` which triggers popstate and hash change listeners

**Comment by alphatr** [comment]
> This is expected because `router.back` triggers `history.go(-1)` which triggers popstate and hash change listeners

@posva but I use `beforeRouteLeave` prevent the call and $route state also not change

`window.history.go(-1)` should not be called

**Comment by alexsasharegan** [comment]
So `beforeRouteLeave` does not capture the route change of `router.back()`? This is a big surprise, and if it isn't going to change, it probably is worth documenting.

Maybe I'm just getting stuck on this: https://github.com/vuejs/vue-router/issues/764

_Update: Subcomponent guards did prove to be my mistake._
