### ISSUE TITLE
Router options not working

### ISSUE THREAD

**Issue by ansarizafar** [vuejs/vue-router#313]
@yyx990803 I am configuring router options when creating a router instance. Like this

    Vue.use(Router)
    var router = new Router({
      histroy: true,
      root: '/',
      transitionOnLoad: true
    })

Router options are not taking effect. Is it a bug?

**Comment by altitudems** [comment]
Looks like you have a typo. histroy should be history?

**Comment by ansarizafar** [comment]
Oh! Embarrassing mistake. Sorry
