### ISSUE TITLE
router.go() will not free previous page data causing memory leak issue

### ISSUE THREAD

**Issue by zhouyanggodking** [vuejs/vue-router#3130]
### Version
3.1.3

### Reproduction link
[https://codesandbox.io/s/heuristic-poitras-nt2f2?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/heuristic-poitras-nt2f2?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1.  first land on /home page, then navigate to /about page.    (at this page, it produces a large array)
2. on about page, click back button (calling router.go(-1))
3. at the memory panel of chrome devtool,  click "garbage collect" button to force garbage collection.
4. take a snapshot

you can see the created array is not freed.

### What is expected?
Array created on about page should be freed.

### What is actually happening?
Array created on about page stays in memory

![image](https://user-images.githubusercontent.com/6425541/75094433-fd9c0400-55c5-11ea-9a7b-9ac17321bdd9.png)

Note:  if I click the back button of chrome browser, no issue at all. Weird
You can also monitor the memory usage of each page. (Please remember to force garbage collection before you look at the stats)

**Comment by posva** [comment]
> Note: if I click the back button of chrome browser, no issue at all. Weird

This might be a browser bug then as router.back calls window.history.back()

Can you reproduce it on a single html page instead of code sandbox please

**Comment by zhouyanggodking** [comment]
Thanks for reply, @posva .
I tested it again in the latest Firefox browser (the same steps as what I did in chrome), and no issue at all.  It can work as expected.  So I think it's a bug of chrome.

![image](https://user-images.githubusercontent.com/6425541/75102897-3f609500-562e-11ea-8ff5-594c1b17e1ce.png)

**Comment by zhouyanggodking** [comment]
I also did a similar test in my real application, router.go(-1)  causes massive memory leak in both chrome and firefox which confusing me so much (browser's back button did not).

**Comment by zhouyanggodking** [comment]
I also did a similar test in my real application, router.go(-1) causes massive memory leak in both chrome and firefox which confusing me so much (browser's back button did not).

**Comment by posva** [comment]
Okay, thanks for the feedback. In that case you should report the leak on Chromium side. Let me know if you manage to boil down a browser-consistent leak!
