### ISSUE TITLE
Nested named route with parameter is redirected to the route name on refresh

### ISSUE THREAD

**Issue by namoosalishah** [vuejs/vue-router#3132]
Hi,

I am having this issue with the nested routes having parameter, when I refresh the page, the route loses the parameter and redirects to the route name instead. Please check the following code.
Before refreshing the page
http://localhost:8080/pos/tickets/1
and after refreshing
http://localhost:8080/pos/ticketDetail
<pre>
{
   path: "/pos",
   name: "pos",
   component: Pos,
   meta: {
      requiresAuth: true
   },
   children: [
      ...... other child routes,
     {
       path: "tickets/:ticket_id",
       name: "ticketDetail",
       component: TicketDetail
      }
   ]
}
</pre>
"vue": "^2.6.8",
"vue-router": "^3.0.1"

Please advise?

**Comment by namoosalishah** [comment]
Any reason for closing this issue without any reasonable answer?

**Comment by LinusBorg** [comment]
As the bot explained: You didn't follow the issue guidelines which were laid you it the issue template. You chose to delete them and not follow them.

We get a lot of issues so we auto-close issues that don't include the minimum requirements we need to actually process them.

You are free to re-open with a properly filled out issue including a runnable reproduction of the presumed bug.
