### ISSUE TITLE
Redirection away from and back to route fails to cancel navigation

### ISSUE THREAD

**Issue by luxaritas** [vuejs/vue-router#3133]
### Version
3.1.3

### Reproduction link
[https://codepen.io/luxaritas/pen/WNvRagw?editors=1010](https://codepen.io/luxaritas/pen/WNvRagw?editors=1010)

### Steps to reproduce
* Run a long async function within a route guard
* Start at route A, navigate to route B, and then back to A again before the guard for B resolves

### What is expected?
Navigation to route B is cancelled, or at least completed and re-routed to route A

### What is actually happening?
NavigationDuplicated is thrown, and the page navigates to and stays on route B

**Comment by posva** [comment]
This could be technically a breaking change but I don't see a reason to not cancel ongoing navigation when trying to navigate to the same location
