### ISSUE TITLE
Change router params to a generic/any type instead of Dictionary<string>

### ISSUE THREAD

**Issue by jsamayoap** [vuejs/vue-router#3134]
Expected behavior, to push params of any type, like:

this.$router.push({
                name: 'piloto',
                params: {
                    id: item.id.toString(),
                    isThisTrue: (this.opN === 1),
                    isThisFalse: (this.opN === 2)
                }
            })

Currently this code on typescript would produce the following error:
No overload matches this call

https://github.com/vuejs/vue-router/blob/39d46b254bd8130464626539e7b73b4cc760241b/types/router.d.ts#L140

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/vue-router/issues/2895
