### ISSUE TITLE
Option to merge meta with parent route meta

### ISSUE THREAD

**Issue by davNazaryan** [vuejs/vue-router#3137]
### What problem does this feature solve?
Add an option `mergeParentMeta: [Boolean]` to give the ability to merge route meta with its parent route meta directly in routes.js
`mergeParentMeta`-s default value is `false`. The priority of the child must be higher than the parent.

### What does the proposed API look like?
```js
{
        path: '/report',
        name: 'report',
        redirect: { name: 'report/workspace' },
        component: { render(c) { return c('router-view'); } },
        meta: {
          breadcrumbs: {
            name: 'Reports',
          },
          layout: {
            headerMenu: true,
          },
          menuItems: [
            { name: 'Banners', to: 'report/banner' },
            { name: 'Campaigns', to: 'report/campaign' },
            { name: 'Workspaces', to: 'report/workspace' },
          ],
        },
        children: [
          {
            path: '/report/workspace',
            ...component('report/list/List', 'report/workspace'),
            mergeParentMeta: true,
            meta: {
              breadcrumbs: {
                crumbs: [
                  { name: 'Reports', route: 'report', title: 'Reports' },
                ],
                name: 'Workspaces',
              },
            },
          },
          {
            path: '/report/campaign',
            ...component('report/list/List', 'report/campaign'),
            mergeParentMeta: true,
            meta: {
              breadcrumbs: {
                crumbs: [
                  { name: 'Reports', route: 'report', title: 'Reports' },
                ],
                name: 'Campaigns',
              },
            },
          },
        ],
      },
```

In this case, the `menuItems` meta can be used inside `report\workspace` and `report\campaign` routes.

**Comment by posva** [comment]
The truth is I have an RFC almost ready about **always** (I don't think it should be an option) merging the meta from parent to child. Like Nuxt does, I believe
I don't think it should go through an option, it should be a default. But all of this will be on the RFC I will publish next week :)

**Comment by mahammad-sixberries** [comment]
@posva is this published or not? and in which version?

**Comment by posva** [comment]
There is an RFC on the RFCs repository and this is fixed in v4 because it's technically a breaking change
