### ISSUE TITLE
Double decoding of url params

### ISSUE THREAD

**Issue by lyaskovec** [vuejs/vue-router#3138]
### Version
3.1.6

### Reproduction link
[https://lyaskovec.github.io/tests/](https://lyaskovec.github.io/tests/)

### Steps to reproduce
There are two cases where you can see issue with double decoding of URL:
case 1:
- Go to the example page
- Click on link  /%25
- Click on link /home
- Try to use browsers navigation buttons

case2:
- Go to the example page
- Click on link  /%25
- reload the browser page

### What is expected?
It should show a correct page

### What is actually happening?
I got "URIError: URI malformed" error

**Comment by aradjdi** [comment]
I opened a PR to fix that issue. Can you check it please ? #3213

**Comment by souldzin** [comment]
Friendly heads up that we're running into this issue over here in GitLab.

https://gitlab.com/gitlab-org/gitlab/-/issues/233878#note_401932109

Removing `decodeURI` from `getLocation` [fixes it](https://gitlab.com/gitlab-org/gitlab/-/issues/233878#note_401945422), but this function seems to be used in a lot of places, so I'm not sure what the consequences of this is 🤔

```patch
--- node_modules/vue-router/dist/vue-router.esm.orig.js	2020-08-25 13:49:56.000000000 -0500
+++ node_modules/vue-router/dist/vue-router.esm.js	2020-08-25 13:46:16.000000000 -0500
@@ -2207,7 +2207,7 @@
 }(History));
 
 function getLocation (base) {
-  var path = decodeURI(window.location.pathname);
+  var path = window.location.pathname;
   if (base && path.indexOf(base) === 0) {
     path = path.slice(base.length);
   }

```
