### ISSUE TITLE
Overwrite Props to Route Components does not work

### ISSUE THREAD

**Issue by vallemar** [vuejs/vue-router#3140]
### Version
3.1.6

### Reproduction link
[https://jsfiddle.net/vallemar/rfwo5m3v/74/](https://jsfiddle.net/vallemar/rfwo5m3v/74/)

### Steps to reproduce
Click on the text.

### What is expected?
I hope that the properties that are passed to the view are the ones that I have configured in my data link with <router-link>.

### What is actually happening?
The property that is passed is the default that is put on the router and is not overwritten by the one that is passed at that time from the <router-link>.

**Comment by posva** [comment]
Params must be defined in the `path` like `/users/:urlAPI`(https://router.vuejs.org/guide/essentials/dynamic-matching.html). Then you can use `props: true` to pass that to the view component (https://router.vuejs.org/guide/essentials/passing-props.html#passing-props-to-route-components)
