### ISSUE TITLE
Async child components are created after App.vue mounted() on client but not on SSR

### ISSUE THREAD

**Issue by Evertvdw** [vuejs/vue-router#3142]
### Version
3.1.6

### Reproduction link
[https://codesandbox.io/s/fervent-dream-5upjy](https://codesandbox.io/s/fervent-dream-5upjy)

### Steps to reproduce
Run the code and check the console output of the SSR and the Client hydration.

### What is expected?
I'm using Quasar with SSR mode, but we have trouble there with async components. We run into some errors because at the SSR side some components are created, which on the client side are created after the initial mount. This in turn causes hydration errors. In the provided example I have a MainLayout (which is async loaded in the router), which in turn  loads (also async) an EssentialLink component. In order to solve our issue this EssentialLink component should be created on the client side before the App.vue mounted hook. 

### What is actually happening?
Currently only the component loaded async in the route itself is created before App.vue mounted(). Child components that are also async are created after the App.vue mounted() hook which causes issues for us. 

---
Server and client side are waiting for router.onReady() which in the documentation says that async components are resolved before this hook is called: https://router.vuejs.org/api/#router-onready. 

It seems to me that the router.onReady() should only be fired when all async child components are also resolved and created.

**Comment by posva** [comment]
When reporting a bug we need a boiled down repro to check (only vue and vue router).

---

> Currently only the component loaded async in the route itself is created before App.vue mounted(). Child components that are also async are created after the App.vue mounted() hook

The `onReady` hook resolves after the initial navigation, which means after async **route** components have resolved. Other async component will resolve later, upon mounting. The explanation regarding hydration at https://ssr.vuejs.org/guide/routing.html#code-splitting should make more sense

**Comment by Evertvdw** [comment]
Ok, is it impossible to make it wait for other async components or is it a design choice? In our case hydration errors occur because of this, and I'm just trying to get a clear picture where we need to be to fix this.
