### ISSUE TITLE
Home view created twice

### ISSUE THREAD

**Issue by deefeloper** [vuejs/vue-router#3146]
### Version
3.0.1

### Reproduction link
[https://none.needed](https://none.needed)

### Steps to reproduce
Create a boilerplate vue app, add console.log() in created() in Home.

### What is expected?
Only one log

### What is actually happening?
two logs

---
Only the Home view is created twice on initial load & refresh, all other views are fine. I double checked that the mount div is not in there twice

**Comment by posva** [comment]
A boiled down reproduction is always needed. You can use CodeSandbox. Ping me or open a new issue when you have it

**Comment by deefeloper** [comment]
@posva I cannot for the life of me get it to misbehave on codesandbox, however it will do it when i use vue ui to create a new app with vue-router
