### ISSUE TITLE
路由切换报错

### ISSUE THREAD

**Issue by txw2018** [vuejs/vue-router#3147]
Identifier 'pleaseLetJsLoaded' has already been declared
![image](https://user-images.githubusercontent.com/37097875/76918253-ddc7d980-6900-11ea-88aa-5b4c4ce02803.png)

**Comment by chenpenghai** [comment]
> Identifier 'pleaseLetJsLoaded' has already been declared
> ![image](https://user-images.githubusercontent.com/37097875/76918253-ddc7d980-6900-11ea-88aa-5b4c4ce02803.png)
兄弟，问题解决了吗？我也遇到了

**Comment by Zhuzi-orz** [comment]
我也遇到了,紧急 滴滴,求助求助HELP

**Comment by lemoyuan** [comment]
mee too

**Comment by txw2018** [comment]
> 我也遇到了,紧急 滴滴,求助求助HELP

因为开了谷歌插件fehelper的原因，关了就行

**Comment by txw2018** [comment]
> mee too

关闭谷歌插件fehelper就行了

**Comment by txw2018** [comment]
> > Identifier 'pleaseLetJsLoaded' has already been declared
> > ![image](https://user-images.githubusercontent.com/37097875/76918253-ddc7d980-6900-11ea-88aa-5b4c4ce02803.png)
> > 兄弟，问题解决了吗？我也遇到了

因为开了谷歌插件fehelper的原因，关了就行

**Comment by Zhuzi-orz** [comment]
> > 我也遇到了,紧急 滴滴,求助求助HELP
> 
> 因为开了谷歌插件fehelper的原因，关了就行

谢谢了兄弟, 这个白浪费我之前那么长时间了.
