### ISSUE TITLE
Cannot get symbol type value in params

### ISSUE THREAD

**Issue by M0j1** [vuejs/vue-router#3148]
### Version
3.1.6

### Reproduction link
[https://codesandbox.io/s/wandering-shape-utn95](https://codesandbox.io/s/wandering-shape-utn95)

### Steps to reproduce
Jumping from the HOME page to the User page, the params carry a value of symbol type key, but the params obtained on the user page do not contain a value of type symbol

### What is expected?
I can get the key of symbol type and use it

### What is actually happening?
In the params passed, the symbol type key cannot be obtained, and the Google console cannot see it

---
v3.1.3 can get it.

**Comment by posva** [comment]
`params` can only contain declared properties in the `path`. In your case, `id` is the only param that can be used in `/users/:id`
