### ISSUE TITLE
router.afterEach doesnot trigger after refreshing page

### ISSUE THREAD

**Issue by airyland** [vuejs/vue-router#315]
Is it a feature or a bug?

**Comment by amirrustam** [comment]
@airyland can you please provide to some code that reproduces the issue?

**Comment by amirrustam** [comment]
@airyland If you are still having problems with this, then please explain the problem, possibly with a jsFiddle reproduction, within the forums: http://forum.vuejs.org

This issue can be closed out.
Thanks

**Comment by airyland** [comment]
Sorry. 

http://jsfiddle.net/airyland/s1kyqxs1/6/

if I use `history:true`, it failed to exec afterEach callback.
 
````javascript
var router = new VueRouter({
	history:true
});


router.afterEach(function (transition) {
  console.log('current' + transition.to.path)
});
````

**Comment by amirrustam** [comment]
I just ran the jsFiddle you linked to within Safari 9.0.2 and it's working. What browser are you using?

**Comment by airyland** [comment]
Did you see the alert "current /" when entered the demo page?

**Comment by airyland** [comment]
if I use `history:false`, it seems to be ok.

http://jsfiddle.net/airyland/s1kyqxs1/7/

**Comment by amirrustam** [comment]
I get alerts for `current/bar` and `current/foo`. There is no route defined for `/`, so there is no route for the initial loading of the root page. You need to define that route:

```javascript
router.map({
    '/': {
    	component: { template: "<p>This is root</p>" }
    },
    '/foo': {
        component: Foo
    },
    '/bar': {
        component: Bar
    }
})
```

History works with the actual browser history, so you need to define all the routes so the router can push the state into history. This is expected behavior and not a bug. 

You can see it working now with `history: false`: http://jsfiddle.net/s1kyqxs1/8/

If you feel like your question was answered, then please close out this issue. Thanks.

**Comment by airyland** [comment]
I mean it doesn't work when using `history:true` even with the route '/'.

http://jsfiddle.net/airyland/s1kyqxs1/10/

**Comment by amirrustam** [comment]
Ok, I see. @yyx990803 does this look like bug to you or is there something missing in that Fiddle.

**Comment by anishdcruz94** [comment]
Hi, @airyland 

You have to place `afterEach` before the `router.start`

`router.start` should be the last line of code.


```
router.afterEach(function (transition) {
  alert('current' + transition.to.path)
});

// Now we can start the app!
// The router will create an instance of App and mount to
// the element matching the selector #app.
router.start(App, '#app')
```

**Comment by anishdcruz** [comment]
Hi, @airyland 

You have to place the `afterEach` statement before the `router.start`

`router.start` should be the last line of code.

This worked for me.

```
router.afterEach(function (transition) {
  alert('current' + transition.to.path)
});
// Now we can start the app!
// The router will create an instance of App and mount to
// the element matching the selector #app.
router.start(App, '#app')
```

**Comment by amirrustam** [comment]
@airyland is right. It's always the simple stuff. But I did notice something, the template for `'/'` does not load with `history: true` http://jsfiddle.net/s1kyqxs1/13/

**Comment by yyx990803** [comment]
The root thing is unrelated - it's because the iframe has a non-root url that interferes with `history` based matching.

**Comment by airyland** [comment]
@anishdcruz @amirrustam  thx
