### ISSUE TITLE
router back not work when loading

### ISSUE THREAD

**Issue by snowtreetree** [vuejs/vue-router#3150]
### Version
3.1.6

### Reproduction link
[https://github.com/snowtreetree/router-back](https://github.com/snowtreetree/router-back)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/30932683/77144357-a142dc00-6ac0-11ea-8740-ef99a6b34770.png)

### What is expected?
router back immediately.

### What is actually happening?
when something is loading，i want to let router go back, but the page does not change immediately,  when browser loading end,  the page show correctly.

---
In my app , I need to do something in router change(log my page path, title), but when the internet speed is slow,  use the function of back or go(-1), I can not back 🤷‍♀️。

**Comment by posva** [comment]
> when something is loading，i want to let router go back, but the page does not change immediately, when browser loading end, the page show correctly.


The Router needs to wait for the js that is necessary to render your page before navigating there. This needs to happen with both normal navigation and history-based navigation (back and forward buttons)

Note: please, next time, provide explicit written steps in reproductions steps, not a screenshot, it will be much clearer

**Comment by snowtreetree** [comment]
but why forward is ok? @posva , in  [app](https://github.com/snowtreetree/router-back), you can change network to slow3g，**when browser top left show loading**,  click `to button`, the page show correctly,  then click browser back, the router params have changed, but the page show no change.

**Comment by snowtreetree** [comment]
https://www.youtube.com/watch?v=dxpUgt-fCSo
@posva I upload my video to youtube , you can watch it.
