### ISSUE TITLE
Types: Missing options on instance.$router

### ISSUE THREAD

**Issue by Mister-Hope** [vuejs/vue-router#3151]
### Version
3.1.6

### Steps to reproduce
```
this.$router.options // should be the options that user passed to vue-rotuer
```

## Solution

I think we should change 

```ts
declare module 'vue/types/vue' {
  interface Vue {
    $router: VueRouter
    $route: Route
  }
}
```
to 

```ts
import { RouterOptions } from './router'

declare module 'vue/types/vue' {
  interface Vue {
    $router: VueRouter & { options: RouterOptions }
    $route: Route
  }
}
```

**Comment by posva** [comment]
As said in https://github.com/vuejs/vue-router/issues/2051, it's a private API. What do you need to read from `$options`?

**Comment by Mister-Hope** [comment]
routes.

I am making a plugin, so I am not expecting that the user provides me his options.

**Comment by posva** [comment]
I see. Retrieving the routes is the only thing I've seen so far and it will be covered by https://github.com/vuejs/rfcs/pull/122. While dynamic routing won't added to vue router 3, it's possible to add the `getRoutes` function here to retrieve the list of records once that RFC reaches a final comments state. It will also have routes dynamically added by the user in a normalised format, which is not the case for `router.options`

**Comment by Mister-Hope** [comment]
> I see. Retrieving the routes is the only thing I've seen so far and it will be covered by [vuejs/rfcs#122](https://github.com/vuejs/rfcs/pull/122). While dynamic routing won't added to vue router 3, it's possible to add the `getRoutes` function here to retrieve the list of records once that RFC reaches a final comments state. It will also have routes dynamically added by the user in a normalised format, which is not the case for `router.options`

Wow, getRoutes function is pretty cool
