### ISSUE TITLE
router back not work when loading

### ISSUE THREAD

**Issue by snowtreetree** [vuejs/vue-router#3153]
### Version
3.1.6

### Reproduction link
[https://github.com/snowtreetree/router-back](https://github.com/snowtreetree/router-back)

**[youtube video](https://www.youtube.com/watch?v=dxpUgt-fCSo) ,  I upload my video to youtube , you can watch it in 15 second.**

### Description
**It's not js, just image**
** in my  [app](https://github.com/snowtreetree/router-back), you can change network to slow3g，**when browser top left conrner show loading**,  click `to button`, the page show correctly,  then click browser back, the router params have changed, but the page show no change.**

### Steps to reproduce
![image](https://user-images.githubusercontent.com/30932683/77144357-a142dc00-6ac0-11ea-8740-ef99a6b34770.png)

### What is expected?
router back immediately.

### What is actually happening?
when something is loading，i want to let router go back, but the page does not change immediately,  when browser loading end,  the page show correctly.

---
In my app , I need to do something in router change(log my page path, title), but when the internet speed is slow,  use the function of back or go(-1), I can not back 🤷‍♀️。

**Comment by posva** [comment]
The browser doesn't emit the `popstate` event until it's ready, meaning Vue Router **cannot** detect the navigation done by the back button. The event is emitted later on and that's when the router detects the navigation.
