### ISSUE TITLE
Using Router with Office.js: router tries using push state even tho it's reset manually by the office js script

### ISSUE THREAD

**Issue by Mafii** [vuejs/vue-router#3154]
### What problem does this feature solve?
When using Microsofts Offic.js (e.g. in Word: https://docs.microsoft.com/en-us/javascript/api/word?view=word-js-preview), and using Vue with vue router, the router tries using push state, but the office js script deletes the push state since the excel web pane is not supporting the push state. The check in push state wheter push state can be used, checks for `window.history && 'pushState' in window.history`, but office.js resets the fields on window.history, not window.history itself (see https://stackoverflow.com/a/42703406/). I propose we check if Office.js is available in the context, and if so, we disable the push state.

### What does the proposed API look like?
We would add a check at this position:

https://github.com/vuejs/vue-router/blob/c0d3376f4e3527bd761bd325873366ed74f5736b/src/util/push-state.js#L17

The additional check could look like this:

```const officeJsLoaded = window.Office && window.Office.context;```

so the whole function might look like this:

```
export const supportsPushState =
  inBrowser &&
  (function () {
    const ua = window.navigator.userAgent
    const officeJsLoaded = window.Office && window.Office.context

    if (
      officeJsLoaded ||
      ((ua.indexOf('Android 2.') !== -1 || ua.indexOf('Android 4.0') !== -1) &&
      ua.indexOf('Mobile Safari') !== -1 &&
      ua.indexOf('Chrome') === -1 &&
      ua.indexOf('Windows Phone') === -1)
    ) {
      return false
    }

    return window.history && 'pushState' in window.history
  })()
```

Alternatively, we could check if `window.history.pushState` is null, but I am not sure of the implications of this. Maybe someone who knows the expected state in the browsers can shed a light wheter that would make sense.

This would result in this return statement, the rest of the function not being changed:
```
return window.history && 'pushState' in window.history && window.history.pushState !== null
```

**Comment by posva** [comment]
I think checking for history.pushState to be a function should be enough

**Comment by Mafii** [comment]
I found a workaround so vue router doesn't have to be changed:

Before importing vue router, add the following lines:

```
delete window.history.pushState; // workaround to make sure vue router doesn't try using pushState
delete window.history.replaceState; // workaround to make sure vue router doesn't try using replaceState
```

Then, import vue router and init it, before initializing office.js.
Seems to work for me.

**Comment by hengchengfei** [comment]
@Mafii 
![1](https://github.com/vuejs/vue-router/assets/3182964/dfd331f7-4a48-4d23-92d5-8075d0cd90cd)

**Comment by Mafii** [comment]
@hengchengfei I have no clue and have not worked on any of this in years, but what about replacing the second line's `pushState` with `replaceState`?

Anyways, your error is purely a typescript error, so you could just disable typescript checks on this (using `as any`?) if the types don't work with it? And, it should be fixed anyways (see the closing commit), so maybe just comment out the lines and see if everything works?

**Comment by points-unknown** [comment]
Forgive me for digging up an old thread, but I don't understand how to _" import vue router and init it, before initializing office.js."_

Here is my **main.js** code:

```
import { createApp } from "vue";
import App from "./App.vue";

delete window.history.pushState; // workaround to make sure vue router doesn't try using pushState
delete window.history.replaceState; // workaround to make sure vue router doesn't try using replaceState
import router from "./router";

const app = createApp(App);
app.use(router);
window.Office.onReady(() => {
  app.mount("#app");
});
```

and I call the office.js script in **index.html**:

```
<head>
    <script src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js"></script>
</head>
```

Doing this does not work. If I don't load office.js and I don't use Office.onReady() I can get the page to at least show up. But any mention of office.js or Office.onReady and it loops with errors.

Is there a special order to calling or defining these elements to make the work-around function as intended?

**Comment by Mafii** [comment]
@points-unknown as mentioned before, you should not have to use this workaround! Take a look at the closing commit :)

If that doesn't work, also take a look at https://stackoverflow.com/a/53662709 to help you understand the context. It is possible the way you import officejs in the head is problematic. Sorry I can't help more!

**Comment by points-unknown** [comment]
Thank you so much for your help with this. I understand that I shouldn't of had to use the workaround, but vue router wasn't working at all with office.js so I had to do something. Your guidance led me to a solution that worked for me. For those that come here in the future looking for help - here is what I ended up doing that worked:

My router.js file looks like this:
```
import { createRouter, createMemoryHistory } from "vue-router";

const routes = [
  {
    path: "/",
    name: "home",
    component: Home,
    alias: ["/taskpane", "/taskpane.html"],
  },
     //etc.  go through all of the routes and views
];

const router = createRouter({
  history: createMemoryHistory(),
  routes,
});

export default router;
```
the key was to change the history to **'createMemoryHistory()'** that's what ended up working.

And then for completeness this is what my main.js file looks like:
```
import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";

delete window.history.pushState; // workaround to make sure vue router doesn't try using pushState
delete window.history.replaceState; // workaround to make sure vue router doesn't try using replaceState

const app = createApp(App);

app.use(router);

window.Office.onReady(() => {
  app.mount("#app");
});
```
I am not sure if I still needed to delete the pushState and replaceState parameters, but it hasn't hurt me yet, so I've left them in.

**Comment by abc245** [comment]
I've spent 8 hours today trying to resolve this, thank you @points-unknown!

**Comment by gierschv** [comment]
Thanks @points-unknown! I can reproduce the issue with the latest vue-router on an old MacOS/Safari that the Office team uses to review apps, but doesn't happen with a recent MacOS/Safari.

It crashes [around this function call](https://github.com/vuejs/router/blob/main/packages/router/src/history/html5.ts#L231). I tried to reproduce it in a router unit test by setting the 2 functions `pushState` & `replaceState` to null, but jsdom crashes an error instead when detecting the feature is not available.
I guess that could be reproduced in a e2e test, but I haven't used nightwatch yet.
