### ISSUE TITLE
beforeRouteLeave

### ISSUE THREAD

**Issue by anihCevol** [vuejs/vue-router#3159]
### Version
3.1.5

### Reproduction link
[https://router.vuejs.org/zh/guide/advanced/navigation-guards.html#%E7%BB%84%E4%BB%B6%E5%86%85%E7%9A%84%E5%AE%88%E5%8D%AB](https://router.vuejs.org/zh/guide/advanced/navigation-guards.html#%E7%BB%84%E4%BB%B6%E5%86%85%E7%9A%84%E5%AE%88%E5%8D%AB)

### Steps to reproduce
B页面：
```
export default {
  beforeRouteLeave (to, from, next) {
    next(false)
  }
}
```
假如A页面高度300，A页面滑动到底部，然后路由跳转到B页面，假如B页面高度400，在B页面点击浏览器返回键， 虽然阻止了页面返回，但是页面滚动到了300的位置。

### What is expected?
页面位置不变

### What is actually happening?
页面位置滚动上一个页面位置高度

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
