### ISSUE TITLE
Debugging Fragment Instance warnings?

### ISSUE THREAD

**Issue by radicaled** [vuejs/vue-router#316]
I have three templates (using `vue-loader`, sparing the JS bits for brevity).

`blog-post.vue`
```html
<template>
  <div class="post">
     {{ post.content }}
     <hr>
     <comment-thread v-bind:comments="post.comments"
     ></comment-thread>
   </div>
</template>
```

`comment-thread.vue`:
```html
<template>
  <div class="comment-thread">
    <comment v-for="comment in comments"
      v-bind:comment="comment"
      v-bind:parent-comment="parentComment"
    ></comment>    
    </div>
  </div>
</template>
```

`comment.vue`:
```html
<template>
  <div class="comment">
    {{ comment.content }}
    <comment-thread
      v-bind:comments="comment.comments"
      v-bind:parent-comment="comment"
    ></comment-thread>    
    </div>
  </div>
</template>
```

Inside of `blog-post.vue`, the `<comment-thread />` element renders normally. However, once nesting starts to occur inside of `<comment />`, I get fragment instance warnings:
```shell
[Vue warn]: Attributes "v-bind:comments", "v-bind:parent-comment" are ignored on component <comment-thread> because the component is a fragment instance
```

Since my markup doesn't appear to be violating any of the rules located http://vuejs.org/guide/components.html#Fragment_Instance , how can I determine what's causing the fragment instance error?

**Comment by yyx990803** [comment]
You comment-thread.vue has an extra `</div>` closing tag.

**Comment by radicaled** [comment]
Sorry, the extra div is a red herring -- my templates are in Jade but I didn't want to assume any knowledge of that, so have translated to HTML. Jade is a whitespace based compile-to-html language that automatically adds coding tags.

The extra div closing tag doesn't exist in the rendered output.

If nothing else immediately jumps out I'll try to reproduce in a jsfiddle.

**Comment by yyx990803** [comment]
Yes please, a jsfiddle would be great :)

**Comment by radicaled** [comment]
I think this might have something to do with the way I'm using `vue-loader` and the `.vue` files. Closing for now.

**Comment by thgh** [comment]
Were you able to solve the issue? I'm having trouble debugging the same nested structure of components. Also using vue-loader.

First it loads the structure on the left and after a hot-reload of some unrelated change it gets the expected structure (right)

before-> ![fragment1](https://cloud.githubusercontent.com/assets/1109982/13906127/66e24094-eecf-11e5-8245-51fd847dfd1a.PNG) after-> ![fragment-trouble](https://cloud.githubusercontent.com/assets/1109982/13906126/66df0d52-eecf-11e5-9bc6-51961f3fb610.PNG)

**Comment by radicaled** [comment]
> Were you able to solve the issue?

Nope. At the time I triple-checked my HTML component structure, questioned my sanity, then stepped through the vue.js source code. I didn't get far enough into it to discover the root cause, and the project pivoted before I could fully debug it, but at the time I discovered that internally vue.js was transforming a particular component's `<div />` element into a document fragment for some reason. I think it occurred during the data passing or binding step, can't remember.

I was using vue-hot-reload-api, webpack, vue components, etc, so in the end I just assumed that the interactions between one component and another introduced the problem.

**Comment by thgh** [comment]
Same conclusions here. But I just found a solution! Register the component globally in the entry file. 

Reported here: https://github.com/vuejs/vue-loader/issues/180
