### ISSUE TITLE
getMatchedComponents 在base 模式下没有返回正确路由

### ISSUE THREAD

**Issue by evont** [vuejs/vue-router#3161]
### Version
3.1.6

### Reproduction link
[https://github.com/evont/vue-multi-ssr](https://github.com/evont/vue-multi-ssr)

### Steps to reproduce
SSR 下，如果使用了base 选项，比如： { routes: [{ path: '/page1', component: Page1 }], base: '/test' }，访问/pc2/page1, getMatchedComponents 将不会匹配到Page1，会抛出not found

### What is expected?
getMatchedComponents 在base 模式下能够正确匹配到组件

### What is actually happening?
getMatchedComponents 会直接使用routes中的path 去和fullPath 比对，导致无法获得正确路由组件

---
在尝试修改源码，在addRouteRecord 添加base 到 normalizedPath，即record.path 加上了base 之后，运行正常，但由于对源码改动比较大，且不确定这一问题是否为正常行为，希望解答或修复，感谢

**Comment by posva** [comment]
This is way too much for a reproduction, please include the bare minimum for reproductions. You can find instructions here: https://ssr.vuejs.org
Also please, write the issue in English so I can read it

**Comment by evont** [comment]
Forget about the code, in SSR mode, **getMatchedComponents**  use the route's path to match with the fullpath, ignore the base option, then get a 404 when visiting this router, I tried to add base to **record.path** in **addRouteRecord** method and it works, I want to know if this is a bug or is on purpose, if is a bug, I hope it could be fixed, if is on purpose, please tell me why, thanks a lot

**Comment by posva** [comment]
When `pushing` with the `router`, the base shouldn't be there. It is only stripped during client navigation. Route record must not include the `base` either and a RouteLocation object does not include the `base` attribute in `path` nor `fullPath`
