### ISSUE TITLE
Is there the possibility of coexisting with hash mode and history mode in one program

### ISSUE THREAD

**Issue by hengyizhangcn** [vuejs/vue-router#3165]
### What problem does this feature solve?
Is there the possibility of coexisting with hash mode and history mode in one program

### What does the proposed API look like?
Is there the possibility of coexisting with hash mode and history mode in one program

**Comment by posva** [comment]
No, that's not possible, only one history can manipulate the url

**Comment by hengyizhangcn** [comment]
In the official document, in the `devServer` section. It says:
```
Some values like publicPath and historyApiFallback should not be modified as they need to be synchronized with publicPath for the dev server to function properly.
```
Then I found the solution of this question.
In the devServer, you can add the config like:
```
historyApiFallback: {
      verbose: true,
      rewrites: [
        { from: /^\/history\/.*$/, to: '/history.html' }
      ]
    }

# Please note that, the rewrites configuration is local for debug. The same configuration (like nginx) must be applied in the server when the program released online.
```


Then, in the routes, the path must be configured like: 
```
let routes = [
  {
    path: '/history/qualityAlliance',
    name: 'qualityAlliance',
    component: () => import('views/qualityAlliance/index')
  }
]
# the path can't be replaced with '/qualityAlliance' in this situation
```

In the pages, you can do like this:
```
pages: {
    main: {
      ....
      // hash mode
    },
    routerHistory: {
      // history mode
      entry: 'src/entry/history.js', // another entery
      template: 'public/history.html', // another template
      filename: 'history.html',
      title: ''
    }
  },
```

Then I type 'http://localhost:8080/history/qualityAlliance' (the history mode) into the web browser, and it works without add '#/' in the suffix automatically!
Then I type 'http://localhost:8080/#/history/qualityAlliance' (the hash mode), it works normally!
