### ISSUE TITLE
Vue Router Dynamic Class Issue

### ISSUE THREAD

**Issue by michaelmyc** [vuejs/vue-router#3169]
### Version
3.1.6

### Reproduction link
[https://jsfiddle.net/zhoLsm6b/11/](https://jsfiddle.net/zhoLsm6b/11/)

### Steps to reproduce
When a router-view tries to dynamically add classes to the router-links, some changes are overridden. 

### What is expected?
Dynamically added classes are preserved. 

### What is actually happening?
When vue-router sees it needs to modify the classes, it does not preserve the previous classes. 

---
I need to add another class for CSS modifications on the navigation bar for my 404 page. This requires me to reactively add a class to the router-links. 

Maybe rather than create a new classList, we can simply use `classList.add` or `classList.remove` so the user-added classes can be preserved when vue-router updates the elements?

Or is this configurable in the router setup?

**Comment by posva** [comment]
This is expected behavior in Vue. Handle the dynamic classes with Vue instead of manually changing them
