### ISSUE TITLE
Getting NavigationDuplicated when pushing new query params to router

### ISSUE THREAD

**Issue by jousi592** [vuejs/vue-router#3173]
### Version
3.1.6

### Reproduction link
[https://codesandbox.io/s/flamboyant-fermat-lhb7u](https://codesandbox.io/s/flamboyant-fermat-lhb7u)

### Steps to reproduce
Install and configure Vue-router,  in any component try to add a query parametr with: `this.$router.push({ query: { test: 'test' } })` in `mounted` hook for example.

### What is expected?
The query parameter gets added without errors.

### What is actually happening?
A uncaught error "NavigationDuplicated" gets thrown and blocks further js execution (when developer tools open)

---
I thought this has been fixed before, but it doesnt seem like it has and adding `.catch(() => {});` doesnt work 100% of the time.

**Comment by posva** [comment]
This is weird but it seems to be an error on Codesandbox or vue-loader: the `mounted` hook is triggered twice (it should be triggered only once), that is why you get the error, the second time the navigation is duplicated. What I don't know if this is intended (maybe for hot reload), I don't think it is so if you have a reproduction with vue-loader you should file an issue there, if not, file an issue on codesandbox

**Comment by jousi592** [comment]
Well I have this happening whenever I try it and I think the double trigger is happening somewhere within the `push` function. I am using it in multiple places in my application and each time it executes, I get the error.
