### ISSUE TITLE
Documentation: Clarify how to navigate to current page, while avoiding NavigationDuplicated

### ISSUE THREAD

**Issue by ajmas** [vuejs/vue-router#3179]
### What problem does this feature solve?
Suggestion to provide an example and counter example on how to navigate to current page with updated query parameters. To be added  https://router.vuejs.org/guide/essentials/navigation.html

This is partly to counter outdated examples I have found on the internet and provide a 'supported' approach and also some knowledge that is currently only in the issues tracker.

Initially I was dealing with code that looks like:

```
        const query = this.$route.query;
        query.page = page;
        query.limit = rowsPerPage;
        await this.$router.push({ query }); 
```

and resolved with:

```
        const query = Object.assign({}, this.$route.query);
        query.page = page;
        query.limit = rowsPerPage;
        await this.$router.push({ query }); 
```

### What does the proposed API look like?
This is a documentation update suggestion. I can make it if the idea is approved.

**Comment by posva** [comment]
Thank you for the suggestion but a navigation should be to a different location. We cannot really document a hack

**Comment by ajmas** [comment]
It is not hack, if you are reflecting a parameter change such as from:

`/abc?x=z&page=1&limit=10` to `/abc?x=z&page=2&limit=10`

then if you are essentially calling the same page with different parameters. The documentation does not make it clear how to achieve this. If it does, it would be good to see where in the documentation it is explained, otherwise it will keep cropping up as issue tickets and stackexchange entries.
