### ISSUE TITLE
two nested router-view exist memory leak

### ISSUE THREAD

**Issue by muzi131313** [vuejs/vue-router#3181]
### Version
3.1.6

### Reproduction link
[https://github.com/muzi131313/vue-drag-slider/tree/master/example](https://github.com/muzi131313/vue-drag-slider/tree/master/example)

### Steps to reproduce
- 1.run the project
```
git clone https://github.com/muzi131313/vue-drag-slider/tree/master/example
npm install
npm run serve
```

- 2.open chrome browser, input: http://localhost:8080
- 2.open chrome devtool, and select memory
- 3.more tools, select **Performance monitor**, notice **DOM Nodes** and **JS event listeners**
- 4.click button 【go images】, then entry images page
- 5.click button 【back】, back to the home page
- 6.at 【memory】 tab, click 【collect garbage】
- 7.then you will see 【JS event listeners】number was down, but 【DOM Nodes】and 【JS heap size】stay high
- 8.repeat 4~7

### What is expected?
【DOM Nodes】and 【JS heap size】was down

### What is actually happening?
【DOM Nodes】and 【JS heap size】stay high

**Comment by posva** [comment]
Hi, thank you for reporting a memory leak but I cannot do anything with a whole library. I would need a boiled down reproduction with no external dependencies (besides) Vue in a simple HTML file. Also, please make sure the bug does come from vue-router by checking other Vue issues: https://github.com/vuejs/vue/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+leak. Open a new issue once you have done those

**Comment by muzi131313** [comment]
Hi, sorry for that not used vue-router example to test this question, This memory leak surely not the vue-router question, I will try other ways to find what problem was.
This was the vue-router [test example](https://github.com/muzi131313/memory-leak), test it by below step:
1.run the project
```
npm install
npm run dev
```

2.repeat 4~7

**Comment by muzi131313** [comment]
I hava submited a [issue](https://github.com/vuejs/vue/issues/11350) to vue repository
