### ISSUE TITLE
Question: navigate back the previous page when logon succeeded

### ISSUE THREAD

**Issue by DarkLite1** [vuejs/vue-router#3182]
### Version
3.1.6

### Reproduction link
[https://github.com/posva/rfcs/blob/router/navigation-failures/active-rfcs/0000-router-navigation-failures.md](https://github.com/posva/rfcs/blob/router/navigation-failures/active-rfcs/0000-router-navigation-failures.md)

### Steps to reproduce
I've implemented the `beforeEach` guard from the example:

```javascript
router.beforeEach((to, from, next) => {
  // redirect to the login page if the target location requires authentication
  if (to.meta.requiresAuth && !isAuthenticated) next('/login')
  else next()
})
```

This works perfectly fine and redirects the user to the login page when he is not authenticated. When I then try to implement the navigation back to the original requested page as in the example it fails:

```javascript
// user is not authenticated
await router.push('/profile/dashboard')

// `redirectedFrom` is a RouteLocationNormalized, like `currentRoute` but we are omitting
// most properties to make the example readable
router.currentRoute // { path: '/login', redirectedFrom: { path: '/profile/dashboard' } }
```
Thank you for shining a little bit of light on this subject. Sorry if this is the wrong place to ask but the official example doesn't show something like this.

### What is expected?
After  successful logon the user should be navigated to the page he requested in the first place.

### What is actually happening?
Don't understand how to get that functionality in the app. 

---
Thank you for your help.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

One way is to keep the original address in the query when redirecting the user to `/login` and then use it once the user is logged in.

**Comment by dietergeerts** [comment]
I'm encountering a similar issue. When the user navigates to lets say `/portal/studies`, we check if they are authenticated. If not, we do `next` in the hook to the `/portal/login` page. In that view, we have a login button which we want to use the original URL in, so we can have our auth provider redirect to that URL once the login is finished. Now, the `redirectedFrom` should return this original URL according to the docs, but that's not the case. I can see that it's empty. So I believe this is still a bug in the library to this day. We are using v3 and this might have been solved in v4, but we aren't in the possibility to move to v4 in the very short term. Can this be solved, or is there a workaround for this bug?
