### ISSUE TITLE
Add mixin option to Vue Router

### ISSUE THREAD

**Issue by nrgsourcecode** [vuejs/vue-router#3186]
### What problem does this feature solve?
I need to be able to add a mixin only for components which are directly instantiated inside the <vue-router>, not their children.

At this time, it seems to me that I have to go inside each of those components and add a mixin manually, which I would like to avoid.

What I've done is to create a global mixin with a beforeCreate lifecycle event, but it's triggered for every component that's loaded, which I also would like to avoid.

### What does the proposed API look like?
import mixin from 'mixin';

interface RouteConfig = {
 ...
  mixins?: any // Mixin to be applied when instantiating a component
}

**Comment by posva** [comment]
This belongs to the user land: it can be achieved with a function rewriting the `routes` array before passing it to the router or, as you said, manually passing the mixin to the different view components.

**Comment by nrgsourcecode** [comment]
Hello and thank you for your response, but I'm not sure that I follow.


`// routerMixin.js
export default {
    beforeCreate() {
        console.log('beforeCreate');
    }
};

// router.js
import routerMixin from '../util/routerMixin';

const routes = [
    {
      path: '/login',
      name: 'Login',
      component: () => import(/* webpackChunkName: "login" */ '../views/Login.vue'),
      mixins: [routerMixin]
    }]`

And nothing happens, mixin is not executed, and it's not accessible from the loaded component
