### ISSUE TITLE
Child relative links lose parameter when child path is empty

### ISSUE THREAD

**Issue by atmatthewat** [vuejs/vue-router#3187]
### Version
3.1.6

### Reproduction link
[https://jsfiddle.net/eu7vbq9h/2/](https://jsfiddle.net/eu7vbq9h/2/)

### Steps to reproduce
See jsfiddle https://jsfiddle.net/eu7vbq9h/2/
<router-link to="posts"> inside /user/foo/profile (UserProfile component child path 'profile') links to /user/foo/posts, but
<router-link to="posts"> inside /user/foo (UserHome component child path '') links to /user/posts instead of /user/foo/posts

### What is expected?
Child path is rendered properly with parameter even if the child path is ''

### What is actually happening?
Child path is rendered missing parameter if the child path is ''

**Comment by posva** [comment]
That's how relatives URLs work. You need to use `<router-link to="/user/foo/">/user/foo/</router-link>` with a trailing `/` for those relative links to work

**Comment by atmatthewat** [comment]
> That's how relatives URLs work. You need to use `<router-link to="/user/foo/">/user/foo/</router-link>` with a trailing `/` for those relative links to work

That's not a relative link. That's an absolute link. 

For my application I need actual relative links that preserve the parameter part.

**Comment by posva** [comment]
Right now you have `<router-link to="/user/foo">/user/foo</router-link>`, add the trailing slash to that link so that other relative links appear after the last slash. That's what I'm saying.

**Comment by atmatthewat** [comment]
That's not feasible if a user visits "/user/foo" all on their own, of course. But I see that relative links are generally broken for all the child cases anyway, so off to find an alternative design.
