### ISSUE TITLE
在全局前置守卫中如果手动跳转到一个不同的地址，会导致replace跳转方式失效

### ISSUE THREAD

**Issue by hooray** [vuejs/vue-router#3190]
### Version
3.1.6

### Reproduction link
none

### Steps to reproduce
假设有ABC三个页面，先从A页面通过push方式跳到B页面，然后B页面再通过replace跳转到C页面，这时候前置守卫中做了一些处理，通过 `next({ path: 'D页面' })` 跳转到了D页面，这时候在D页面通过 `history.go(-1)` 会回到B页面

### What is expected?
希望是能回到A页面

### What is actually happening?
回到了B页面

---
虽然我可以通过 `next({ path: 'D页面', replace: true })` 的方式实现，但我更希望 `next()` 方法能自动根据当前导航的跳转方式自动区分是 push 还是 replace

**Comment by posva** [comment]
Please open a new issue in English **and with a boiled down reproduction with clear reproduction steps**, I can't tell what you are saying with a translator
