### ISSUE TITLE
Navigation guards don't work on nested routes

### ISSUE THREAD

**Issue by wojtiku** [vuejs/vue-router#3191]
### Version
3.1.6

### Reproduction link
[https://codesandbox.io/s/upbeat-panini-cy8r4](https://codesandbox.io/s/upbeat-panini-cy8r4)

### Steps to reproduce
1. Go to the example code and notice how the same component is attached both as a root route and a nested route with a different prop: https://codesandbox.io/s/upbeat-panini-cy8r4?file=/src/router.js
2. Switch between menu items in the app, especially "nested" and "nested as root".

### What is expected?
Browser confirmation dialog is shown both when trying to navigate out of 'nested' and out of 'nested as root'.

### What is actually happening?
Browser confirmation dialog is shown only when trying to navigate out of 'nested as root'. It doesn't work for 'nested'.

**Comment by posva** [comment]
There are a few things that need to be pointed out:

- it's `children` not `nested`
- Two routes cannot have the same name
- the nested route should not have a leading `/` if you want to produce a nested path. Otherwise it would produce an absolute path

The reason it looks like it's not working is that your nested link navigates to nowhere and there is no leave guard attached

This is what you probably wanted to do:

```js
{
      path: "/users/:id",
      name: "users",
      component: User,
      props: true,
      children: [
        {
          path: "nested",
          name: "nested",
          component: Nested,
          props: { msg: "AS NESTED" }
        }
      ]
    },
    {
      path: "/nested",
      name: "absolute-nested",
      component: Nested,
      props: { msg: "AS ROOT" }
    }
```

**Comment by wojtiku** [comment]
Thanks for a quick response @posva !
The reproduction was indeed unfortunate. But with that aside it still doesn't work in my app in the same case.

I will keep looking for differences (e.g. we load views lazily so this could be the case it doesn't work for me) and update the issue if I locate them (or not update if it is on my side).

**Comment by wojtiku** [comment]
Turns out our project was using this pattern from Chris to lay-load route components: https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/master/src/router/routes.js but I missed that fact and the original note about component route guards got removed at some point.

Would be great to have a good UX this pattern provides and component route guards at the same time one day (at least the before update and before leave as before enter may be hard to do with lazy loading :)).
