### ISSUE TITLE
在百度APP中，router-link在进入下一页面后点击浏览器自带返回或者Android物理返回都不能返回上一页面

### ISSUE THREAD

**Issue by showtan001** [vuejs/vue-router#3194]
### Version
3.1.6

### Reproduction link
[https://gitee.com/showtan/h5.git](https://gitee.com/showtan/h5.git)

### Steps to reproduce
在百度APP中，使用router-link在进入下一页面后点击浏览器自带返回或者Android物理返回都不能返回上一页面，效果是直接退出程序（a标签可以返回上一页面）。但是我把router-link渲染成a标签也不能返回，然后我监听“popstate”，使用$router.back()，在百度浏览器中可以返回，然而在百度APP还是不能返回，它直接退出H5了。

### What is expected?
在进入下一页后点击浏览器自带返回或者Android物理返回或者侧滑返回能返回上一页面。

### What is actually happening?
直接退出程序。

**Comment by posva** [comment]
This is a whole project. Please provide a boiled down reproduction with only the minimal code to show the problem and clear reproduction steps inside the application of how to reproduce as well as the device needed.
Also please open the issue in English, I don't speak Chinese

**Comment by showtan001** [comment]
No chinese? Forget it, you foreigners don’t even need Baidu APP!

**Comment by TinChak** [comment]
same issue

**Comment by Clare29** [comment]
same issue,happened in uc-browser and quark-browser too
