### ISSUE TITLE
Change query, the address bar will not change

### ISSUE THREAD

**Issue by lang1427** [vuejs/vue-router#3198]
### Version
3.1.3

### Reproduction link
[https://github.com/lang1427/vue-typescript-music/blob/master/src/views/test.vue](https://github.com/lang1427/vue-typescript-music/blob/master/src/views/test.vue)

### Steps to reproduce
When there is query in the route and the attribute is name value XXX, you want to change the value of name,

The following code:
```
this.$route.query.name = '更新数据'
```

### What is expected?
Change the value of name in the address bar while changing the value of name

### What is actually happening?
The name value has changed, but the name value in the address bar has not changed. What can I do?

**Comment by posva** [comment]
you need to push:

```js
this.$router.push({ query: { ...this.$route.query, name: 'the name' }})
```

make sure to copy the query object because it's readonly (as noted in the docs)

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
