### ISSUE TITLE
v-link: opening new window should set hash

### ISSUE THREAD

**Issue by lafka** [vuejs/vue-router#32]
When using v-link like `<a v-link="/dash">Dash</a>` will generate the html `<a href="/dash">Dash</a>`.
Since the directive binds `click` it will work when clicking with that window, however when opening in a new window it will use the href as the path instead of as the hash.

Possible fix https://github.com/lafka/vue-router/commit/42370f74a24124d916f9460df7c10078198dc9e6 but i want feedback before i create a pull request.

In general not prefixing with the hash will also break when doing refreshes (unless your server is specifically configured to always load the index)

Should the app avoid `pushState` and have vue-router accept a configuration, or should one always use hashes?

**Comment by azamat-sharapov** [comment]
I think purpose of `v-link` is exactly for paths like `/dash` without hashbang, because it preventsDefault and changes URL on click. If you need hashbang, why not just use `href` attribute? For direct links like `/dash`, I personally make server handle it (configure multiple or all paths to load index file).

**Comment by lafka** [comment]
I'm missing something here, by changing the `example/example.js` to include `hashbang: true`  in router opts and changing example/index.html to use `<a href="#!..` instead of v-link then none of the routes match.

I think there is an issue in the check https://github.com/vuejs/vue-router/blob/293c96762ea617102635ca911978b3ffa1e7ef92/src/api.js#L82 where `/^#!?/` is not replaced if history is enabled, causing the `_match` to fail.

Has anyone defined how `v-link` and href should work? I would assume when the `hashbang` option is enable everything will be rewritten

**Comment by Lidbetter** [comment]
To echo @lafka s point, it would be nice if hashbangs are enabled, the href created also includes the hashbang.

That way if one decides to change from including hashbang to not; in the future no templates need to be changed

**Comment by yyx990803** [comment]
Fixed, `v-link` should now work in both modes.

**Comment by yyx990803** [comment]
Closing, feel free to reopen if the latest commits do not resolve your issue.
