### ISSUE TITLE
Impossible to build vue-router

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [vuejs/vue-router#320]
I want to try solving #245, but I'm not able to build `vue-router`

I get : `[ReferenceError: [BABEL] /home/guillaume/dev/static-front-end/node_modules/vue-router/src/index.js: Unknown option: /home/guillaume/dev/static-front-end/.babelrc.presets]`

Any Idea on this ?

**Comment by yyx990803** [comment]
`vue-router` is built with Babel 5, not 6.

**Comment by GuillaumeLeclerc** [comment]
I already checked before I made the issue.

`require('babel-core').version' outputs `'5.8.34'`

when I run it in the the vue-router directory

**Comment by yyx990803** [comment]
Your `.babelrc` is in 6.0 format though, presets is a Babel 6 only concept.

**Comment by GuillaumeLeclerc** [comment]
Why is it ready my personal `.babelrc` ? and not using the project configuration instead. That means I have to delete my configuration file ?

**Comment by yyx990803** [comment]
Because the project itself doesn't have a `.babelrc` :/
You can probably fix this by placing an empty `.babelrc` in the project root.

**Comment by GuillaumeLeclerc** [comment]
Thank you for the hint. I'll try it !
