### ISSUE TITLE
onError does not capture errors thrown in redirect callback

### ISSUE THREAD

**Issue by trainiac** [vuejs/vue-router#3201]
### Version
3.1.6

### Reproduction link
[https://codepen.io/trainiac/pen/rNOZvRO?editors=1112](https://codepen.io/trainiac/pen/rNOZvRO?editors=1112)

### Steps to reproduce
1. create route config like

```ts  
{
    path: '/oldpath/:part',
    redirect: (to: Route) => {
      if(to.ooopsmistake.part) {
        return `/newpath/${to.params.part}`
      }
      return '/newpath/'
    },
  }
```

### What is expected?
When router.push('/oldpath/test'). an error is throw becuase there is no oopsmistake property on the to route.  This should be caught in router.onError.

### What is actually happening?
It's only caught in router.push('/oldpath/test').catch(err is here)

**Comment by posva** [comment]
FYI, the error will still be thrown/rejecetd by `router.push` even if it's sent to `onError`

**Comment by trainiac** [comment]
Makes sense. The issue is now, for ssr, if you just want to use onError to manager errors and add a push().catch(noop) to swallow rejections, a thrown error in the redirect callbacks leaves you hanging.

**Comment by raulcabello** [comment]
I'm also interested in this. Would you accept a pull request for this feature?

**Comment by posva** [comment]
yes, go ahead
