### ISSUE TITLE
Vue Router not works on Firefox, Works perfect on Chrome and Safari

### ISSUE THREAD

**Issue by phpexpert00784** [vuejs/vue-router#3207]
### Version
3.2.0

### Steps to reproduce
I just setup the Laravel 7 with Latest Vuejs. I Just setup simple sampleComponent.Vue

### What is expected?
import Vue from 'vue'
import VueRouter from 'vue-router'

Vue.use(VueRouter)

const routes = [
	{
		path : '/example',
		component : require('./components/ExampleComponent.vue').default
	}
];

const router = new VueRouter({
	routes
});

const app = new Vue({
    el: '#app',
    router : router
});

That is my code. What is wrong in that

### What is actually happening?
[Vue warn]: Unknown custom element: <router-link> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>) 

[Vue warn]: Unknown custom element: <router-view> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>)

In firefox, It will me that error.

---
Please ignore mimimal reprodoction link

**Comment by posva** [comment]
We need a boiled down reproduction to check. Open a new issue I you manage to reproduce

**Comment by wontone18** [comment]
same issue with me also. Scroll behaviour not working in firefox.
