### ISSUE TITLE
Pass components into slots in router config

### ISSUE THREAD

**Issue by nicky1038** [vuejs/vue-router#3208]
### What problem does this feature solve?
At present users are able to pass props into components inside router config via [props](https://router.vuejs.org/api/#routes) property. But there is also another kind of input information that components accept as well: slots.

It would be cool if users could configure passing something into slots in router config. The simpliest and the most intuitive idea is to specify components to be displayed instead of slots.

This feature can **incredibly** _reduce code coupling_ and _raise configuration flexibility_.

To be honest, I was sure this feature already exists, and was very surprised when I didn't find it in the documentation.

### What does the proposed API look like?
This could be done with the new `slots` variable that does the thing, for example:

```javascript
{
  path: '/foo',
  component: Foo,
  slots: { // object of slot names to slot configs
    default: { // default slot of Foo
      component: Bar, // a component to display instead of the default slot of Foo
      props: { // props to pass into Bar component
        a: 1,
        b: 'hey'
      }
      // maybe allow passing slots into Bar component via nested 'slots' property here?
    },
    customSlotName: Baz // only component can be specified is no props are needed to be passed
  }
}
```

**Comment by posva** [comment]
Why is the actual use case for this ? I don't see why you would pass a slot to a view component. It complicates the api a lot

**Comment by nicky1038** [comment]
I can totally understand that any proposal of such a scale is very hard to be included into such a wide-spreaded library, and only the most useful ones are.

Let me explain what is my actual case:

There are several pages with almost the same content. Every page has its own route config, and the same Vue component is used for every page. Each page displays one list of entities, and all data is being passed into these pages via `props` property of their router configuration. Everything was perfect, but now I have a need to add "actions" panel to the pages, and it should be different for all pages.

The existing solutions are:
* For N panels create N more new components that just pass panels into the existing common component, and use these components inside router config. Looks too boilerplate and dirty for me :( 
* Pass panel components to the common component via a prop `componentFromProp` and use it for `<component :is="componentFromProp">`. Is it normal to do this? + If `componentFromProp` had its own props, we'd have to write boilerplate code again - OK, this is not my case yet, but it seems to be more than real.
* Higher-order components? Is it possible to create a HOC that just passes components into all slots of given component? If so, this way is the best one, though everyone who runs into the same issue will have to reinvent this method and implement the same routine HOC. Basically, it would be an acceptable solution to make an npm package with this HOC and write about this solution in the documentation. 

I'm facing this problem in the first considerable web application I deal with, and it does not seem very specific, so I think the solution would be useful for others as well. My API proposal seems to be a pretty, the simpliest and the cleanest one.

I will be very glad if there are also other simple and clean solutions I haven't thought about yet.

**Comment by posva** [comment]
Thanks for the explanation, it's clearer now. Given the existing solutions and this not being a common scenario (most application won't need to pass any slot to view component), this makes sense as an external library (similar to HOC). It could be a function that take these options to generate the appropriate component, but the api is up to you.

**Comment by nicky1038** [comment]
It's a good news that such a function **can** be created.
Here is an example: **https://jsfiddle.net/mcugfjdp/**

This function (it is called `withSlotContentHoc` in the example) generates the required component from some source component and "slot names to components" options object. I haven't experimented with passing props to that components yet but it seems it's possible too.

However, HOC creation in Vue is not the easiest thing in programming :D
I hope I'll have time to make an npm package in the nearest future.
