### ISSUE TITLE
Modify the beforeRouteUpdate parameter to be optional

### ISSUE THREAD

**Issue by pikadun** [vuejs/vue-router#3209]
### What problem does this feature solve?
The `to`,`from`  is unnecessary in `Navigation Guards`,  so consider making them optional parameters

### What does the proposed API look like?
export type NavigationGuard<V extends Vue = Vue> = (
  next: (to?: RawLocation | false | ((vm: V) => any) | void) => void, 
  to?: Route,
  from?: Route
) => any

**Comment by posva** [comment]
Thank you but this is a breaking change. Al guards Jae he same signature and you use to and from moreoften than not
