### ISSUE TITLE
Simplify transition hooks

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vue-router#321]
Here's what I think of the current API:
- The current list of hooks is a bit overwhelming. Do we actually need `canActivate` and `canDeactivate`? It seems `activate` and `deactivate` can already handle most use cases with `transition.abort()` and `transition.redirect()`.
- The `data` hook name is not that self-explanatory.
- The way we determine the async-ness of these hooks is convoluted. Sync, Promises, callbacks... we should try to simplify it.
### Idea

Some potential breaking changes for 0.8.0:
- Remove `canActivate` and `canDeactivate`.
- (Maybe?) Remove `canReuse`. The same component is always reusable. Handle route change in `onChange`.
- Rename hooks, now we have just 3 of them:
  - `onEnter`: what `activate` used to be.
  - `onLeave`: what `deactivate` used to be.
  - `onChange`: what `data` used to be. The new name better explains when it is called (on every route change when the current component is active)
- In addition: allow specifying `onEnter` and `onLeave` in the route config as well.
- Open to suggestion: how do we simplify hook async-ness?

**Comment by chenkie** [comment]
I think one of the nice things about hooks like canActivate is that intent is expressed nicely in the hook name. An example of this is checking authentication status. I think being explicit like this has some value for readability.

**Comment by amirrustam** [comment]
@chenkie as a general rule of thumb explicit naming is useful and a good practice, though I think in this context @yyx990803's proposal is a good start. 

One of the things that attracted myself and others to Vue was how its simple API is small enough for you to keep a mental model of it in your mind. A minimized set of transition hooks with more intuitive names will help maintain this trait of Vue. For example, I found the Vue instance [lifecycle hooks](http://vuejs.org/guide/instance.html#Instance_Lifecycle) to be very self-explanatory and along with the provided diagram I was able to have mental model of how everything worked.

When first reading through the docs, I found the name of the `data` hook odd, and I know an issue I responded to the other day was posted due to the confusion around this hook. 

Now, having more hooks does provide more granular control within the transition pipeline, though I don't particularly see a loss of functionality with the proposed 3 hooks. So a +1 for the proposed hook names.

Have to do some thinking about the async stuff.

**Comment by benseitz** [comment]
:+1:  I like the simplification!

**Comment by moe-szyslak** [comment]
I like that the hooks are *EXPLICIT*. There are only 6 hooks to get started with, each one with clear intent & meaning (maybe not so on `data`)

+1 for the hook renames, they seem more explicit (at least for me)

**Comment by yyx990803** [comment]
The reason why I think `canActivate` and `canDeactivate` are redundant: Simply returning `false` in `canActivate` is almost useless, because the user will just be puzzled why the navigation didn't work. In most cases, we want to **do something when the navigation should be prevented**, for example, redirect the user to the login page:

``` js
canActivate (transition) {
  if (!loggedIn) {
    transition.redirect('/login')
  } else {
    transition.next()
  }
}
```

Now, doing the same thing in `activate` (or the new `onEnter`) achieves the same goal. To me it sounds like a good tradeoff to halve the hooks API surface vs. the little explicitness of a dedicated hook.

**Comment by amirrustam** [comment]
Are there any **common** use cases that would **require** the need for `canActivate` or `canDeactivate`? 

If no, then there is sufficient reason to adopt the proposal. I think it's a good goal to enhance the surface API to accommodate the 99% of use cases.

**Comment by thelinuxlich** [comment]
love the proposal!

**Comment by sylvainpolletvillard** [comment]
`onEnter`, `onLeave`, `onChange` : certainly much more intuitive names :+1:
Also I agree with @yyx990803 arguments concerning `canActivate` and `canDeactivate`

**Comment by blikblum** [comment]
> (Maybe?) Remove canReuse. The same component is always reusable. Handle route change in onChange.

There's at least one use case that i can think for reuse: when you need to prevent deactivate changing to/from a same route with different params

See the example below. It prevents to change route when Person is dirty. Removing `canReuse: false` i can change from Person 1 to Person 2 regardless of dirty

http://codepen.io/blikblum/pen/EPepaG

**Comment by rpkilby** [comment]
How drastic are the changes to the underlying code? Would it be possible to provide deprecation warnings for the old hooks before completely removing them? 
- Not everyone reads the issue tracker, so are unable to weigh in on this discussion. 
- Deprecation warnings would provide backwards compatibility and give users a chance to try to migrate to just onEnter instead of canActivate & activate. 
- If it turns out that canActivate really is necessary, then maybe re-add as canEnter?

**Comment by yyx990803** [comment]
@blikblum yeah, keeping `canReuse` seems fine to me if there are valid use cases.

@rpkilby we sure can do that, although as a `0.x` release I'm not sure if it's worth it to start doing fully backwards compatible releases. Per semver, if you have `^0.7.1` in your `package.json` you will never get `0.8` unless you explicitly upgrade. And if you are doing so, you should be reading the release notes.

**Comment by blikblum** [comment]
@yyx990803 Fine. 
BTW. Is there another way of implementing the use case i cited without `canReuse`?

**Comment by rpkilby** [comment]
@yyx990803 that's a fair statement about compatibility guarantees. In this case, it's more about prompting the community for feedback before the changes are finalized. Users would still be able to use 0.8.x while discussing whether or not there are any use cases that justify keeping around the canActivate/canDeactivate hooks.

**Comment by pensacola1989** [comment]
I got a problem, how to get components data when hooking deactive?(I need to check some data,then deactivate or not ) 
``js
canDeactivate: (transition) => {
            console.log(this);// undefined
            // console.log('hook-example deactivated!')
            return false;
            // transition.next();
        }
``

**Comment by azamat-sharapov** [comment]
@pensacola1989 please don't ask questions here, there is forum and gitter channel.
Try removing `=>`.

**Comment by bartlomieju** [comment]
Merging `canActivate` with `activate` and `canDeactivate` with `deactivate` make great sense to me. I found it really hard to figure out how to handle situation where user asks for some resource and gets `403`. It either required making two requests, or setting `suppressTransitionError` to true. It would be nice to be able to handle Promise errors in these hooks. Or maybe there's a better way to do it?

**Comment by hartmut-co-uk** [comment]
Hi, regarding the `canReuse` topic, there's another use case (https://github.com/vuejs/vue-router/issues/474)

Or taking this even further (than the fade in/out effect) - in my case I was experimenting with dynamic routes, e.g. picture a CMS where a user can add new pages with custom slugs.
The routes could look like _/content/page1_, _/content/page2_, _/content/that-is-a-slug_, ...
(well same with /product/:id ...)
Now you have a 'content' component requesting your data from the backend to fetch content by slug / redirect to 404 if not found.. 

To go with one request only I fetch my data within `activate` hook, store content to component prop, redirect if not found.. 

...so without `canReuse: false` => `activate` is never called and I can't redirect on 404... 
(...and I won't have transition effects)

**Comment by posva** [comment]
Closing as this is now outdated and most things are implemented with a different naming.
