### ISSUE TITLE
NavigationDuplicated Error after addRoute

### ISSUE THREAD

**Issue by cropr** [vuejs/vue-router#3216]
### Version
3.3.2

### Reproduction link
[https://jsfiddle.net/cropr/86vnLj4k/](https://jsfiddle.net/cropr/86vnLj4k/)

### Steps to reproduce
Following scenario fails with NavigationDuplicated
 1. Have a router wildcard and navigating to an non existing url e.g. /aroute
 2. Doing a addRoute in the handling component of the wildcard, resulting in an updated  routing table with a matching /aroute 
 3. Trying to navigate to new /aroute either via  $router.push or $router.replace

While the url does not change, the Navigation changes and thus the NavigationDuplicated error is incorrect

### What is expected?
The router is changed to the new component matching /aroute

### What is actually happening?
NavigationDuplicated error raised

**Comment by posva** [comment]
please complete the reproduction
