### ISSUE TITLE
$router.go(-1) Not Working In Android Webview

### ISSUE THREAD

**Issue by RicoLiu** [vuejs/vue-router#3223]
### Version
3.0.1

### Reproduction link
[https://codepen.io/RicoLiu/pen/VweepGq](https://codepen.io/RicoLiu/pen/VweepGq)

### Steps to reproduce
路由模式为 Hash
本地开发环境一切正常
打包编译后，集成到 app webview 容器中。进入二级页面后，发现 $router.go(-1) 会失效

### What is expected?
正常返回到一级页面

### What is actually happening?
无法返回 二级页面

**Comment by posva** [comment]
That's not a valid reproduction.

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by 60late** [comment]
老哥后来怎么解决 的？

**Comment by nauyniq** [comment]
> 老哥后来怎么解决 的？

都咋解决的啊？我也遇到这样的问题了

**Comment by 60late** [comment]
> > 老哥后来怎么解决 的？
> 
> 都咋解决的啊？我也遇到这样的问题了

后来直接把跳转链接写死了，没用.go()了

**Comment by nauyniq** [comment]
> > > 老哥后来怎么解决 的？
> > 
> > 
> > 都咋解决的啊？我也遇到这样的问题了
> 
> 后来直接把跳转链接写死了，没用.go()了

我上一个页面还用了keep-alive，直接写死的话估计就没效果了
唉 头疼 不知道咋处理

**Comment by RicoLiu** [comment]
android webview 的版本是多少？可能版本太低了

**Comment by nauyniq** [comment]
> android webview 的版本是多少？可能版本太低了

我的不是 android ，我的是嵌入在企业微信里面的 h5 页面，只是在iphone XR机型上有这个问题

**Comment by nauyniq** [comment]
> > android webview 的版本是多少？可能版本太低了
> 
> 我的不是 android ，我的是嵌入在企业微信里面的 h5 页面，只是在iphone XR机型上有这个问题

我的问题找到了 ，是因为我的页面外被 iframe 包裹着，被 iframe 包裹的 vue 页面好像就是有路由的问题，也算是终于定位到问题了吧
