### ISSUE TITLE
Why do you need the judgment statement of issue #1287

### ISSUE THREAD

**Issue by yyTopfine** [vuejs/vue-router#3227]
### Version
3.3.2

### Reproduction link
[https://github.com/vuejs/vue-router/pull/1287](https://github.com/vuejs/vue-router/pull/1287)

### Steps to reproduce
I think the parsePath method has removed the ‘#’ and ‘?’ in the path.

### What is expected?
Want to know the intention of the judgment sentence

### What is actually happening?
I think the parsePath method has removed the ‘#’ and ‘?’ in the path.

**Comment by posva** [comment]
I'm sorry, I don't completely get what you are saying but it is also not a valid issue. If you found a bug, please open an issue with a reproduction
