### ISSUE TITLE
How can I get pending route's info

### ISSUE THREAD

**Issue by xmsz** [vuejs/vue-router#3235]
### What problem does this feature solve?
```
VueRouter = {
  ...
  history: {
    pending: {}
  }
}
```

I need the pending route' info，The TS types do not support to get this info(maybe It's wrong ). 

case:
onRouterBeforeEnter the currentRoute is not equal to pending route's info

### What does the proposed API look like?
```
router.pendingRoute
```

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You could save the pending location in a `beforeEach` hook if you need it
