### ISSUE TITLE
vue-router duplicates router-view contents when using prerender-spa-plugin

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [vuejs/vue-router#3237]
### Version
3.2.0

### Reproduction link
[https://github.com/RudolfVonKrugstein/vue-prerender-test](https://github.com/RudolfVonKrugstein/vue-prerender-test)

### Steps to reproduce
I am reporting this for vue-router, but I am not sure if it is really a problem with the vue-router component or some other tool in the toolchain I am using.

1. Check out the provided git repository, which has been created the following way
  * A new project has been created with `vue create pre-render-test` and setup with typescript and vue-router
  * Vuetify has been added using `vue add vuetify`
  * [prerender-spa-plugin](https://github.com/chrisvfritz/prerender-spa-plugin) has been added and configured (see [vue.config.js](https://github.com/RudolfVonKrugstein/vue-prerender-test/blob/master/vue.config.js))
2. Build for production using `yarn build`
3. Run a simple http server, for example like this:
    cd dist
    python3 -m http.server
4. go to localhost:8000/about

### What is expected?
The about page, just showing

```
This is an about page
```

### What is actually happening?
The about page is duplicated:

```
This is an about page
This is an about page
```

---
Looking at the DOM I can see, that not the whole app is duplicated but only the contents of `router-view`.
It also seems that some unrelated changes to the project (like adding a toolbar) makes the problem disappear, or re-appear.
Maybe it is some sort of race condition?

**Comment by posva** [comment]
> I am reporting this for vue-router, but I am not sure if it is really a problem with the vue-router component or some other tool in the toolchain I am using.

For vue router bug reports we need boiled down reproductions (no TS, no vuetify). It could indeed come from something else, so please make sure it doesn't come from something else.

From vue-router perspective, `router-view` only renders one component, so it sounds more like something is rendering `router-view` twice

**Comment by RudolfVonKrugstein** [comment]
Is there any hint on how I could debug this? The `router-view` is not rendered twice, because it is in the 'static' main template. And I cannot reproduce it without vuetify/ts.

**Comment by valentinoli** [comment]
I'm experiencing a similar bug with the prerender plugin and `<router-view>` inside a `<v-main>` Vuetify component. When I remove `<v-main>` then everything works fine. 

It seems like the bug has something to do with `<v-main>` (and corresponding deprecated `<v-content>` that you used in the demo). I don't know why this is causing the bug.

I solved the issue by moving `<v-main>` into the view component as the root element. You can do the same for `<v-content>` in your example and see if that works:

In your App.vue remove `<v-content>`:

```
<template>
  <v-app>
    <router-view/>
  </v-app>
</template>
```

In your view components add `<v-content>` as the root element.

**Comment by zerjioang** [comment]
@valentinoli @posva @RudolfVonKrugstein did you try replacing `<router-view/>` with `<router-view></router-view>` and checking if the problem persist when rendering static content with spa-renderer?

**Comment by gbrian** [comment]
Hi, in my case there was an error rendering the new view. After fixing the issues the duplication has gone.
Check console for errors rendering the new view
