### ISSUE TITLE
Push current with empty query isn't work

### ISSUE THREAD

**Issue by Dsartok** [vuejs/vue-router#3238]
### Version
3.3.2

### Reproduction link
[https://codepen.io/dsartok/pen/abdBxoM?editors=1111](https://codepen.io/dsartok/pen/abdBxoM?editors=1111)

### Steps to reproduce
If push from
**'someLocation?someQuery'**
to
**'someLocation'**
via
**router.push({path: 'someLocation', query: {} })**
it takes old query and throw NavigationDuplicated error.

### What is expected?
That it will be replaced to current page with empty query

### What is actually happening?
It get previous query

---
P.S.
fixed this with
router.push({path: 'someLocation', query: { someStub: 'some' } })

**Comment by posva** [comment]
your reproduction shows the expected behavior...
