### ISSUE TITLE
vue.mixin triggers twice when loading or refreshing the page

### ISSUE THREAD

**Issue by airyland** [vuejs/vue-router#324]
http://jsfiddle.net/airyland/zjqbxou3/2/

````javascript
Vue.mixin({
	created:function(){
  	alert('g created '+this.$route.path); // will trigger twice
  }
});
````

**Comment by amirrustam** [comment]
@airyland you are creating a global mixin which will get triggered every time a component is created. It is getting triggered twice, once for the root Vue component for the router and then second time for the component within the `/` route. If the behavior of global mixins is not what you want then utilize option merging with mixins as documented: http://vuejs.org/guide/mixins.html#Option_Merging

**Comment by airyland** [comment]
I see. Thx~

**Comment by airyland** [comment]
One more problem, I want to create a common `created` handler and `beforeDestroy` handler for each router component, is there a easy way to do that?

**Comment by amirrustam** [comment]
@airyland myself and many others would love to help you out, but please ask these types of questions within community forums.

**Comment by airyland** [comment]
Sorry. I think the maintainers may help me more professionally and quickly, So I ask the question.

**Comment by amirrustam** [comment]
The project maintainer has outlined an Issue Reporting Guideline which designates these types of questions for the forums or project gitter chat. The maintainer also monitors the forum to assist whenever possible. Please review the guidelines here: https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines
