### ISSUE TITLE
next() in router.beforeEach() not send params

### ISSUE THREAD

**Issue by smoothdvd** [vuejs/vue-router#3242]
### Version
3.1.1

## Steps to reproduce
```
next({
        path: to.path,
        params: to.params,
        query: {
          referer, token, code, userid, trackid, devicetype,
        },
      });
```

In Vue tools, there is no params received

### What is expected?
receive params

### What is actually happening?
no params

**Comment by posva** [comment]
Please de provide a repro when reporting a bug.

If you are referring to the `to: to.params,`, there is no such option. Remember that you cannot pass `path` and `params` at the same time (https://router.vuejs.org/guide/essentials/navigation.html)
