### ISSUE TITLE
Navigation bug in vue-router >= 3.3.0

### ISSUE THREAD

**Issue by sqal** [vuejs/vue-router#3245]
### Version
3.3.4 (but it exists since 3.3.0)

### Reproduction link
[https://github.com/sqal/vue-router-navigation-bug](https://github.com/sqal/vue-router-navigation-bug)

### Steps to reproduce
1. Clone my repository, run `npm i && npm run serve`
2. Click on the following links

- Go to /users
- Go to /users/1

3. Go back to the previous page. At this point, you can notice that navigation is broken, because instead of users page Vue still renders the user page and clicking back again doesn't work, it still renders the last visited route.

### What is expected?
vue-router should display correct route

### What is actually happening?
To understand why this bug occurs you need to look at [this line of code](https://github.com/sqal/vue-router-navigation-bug/blob/master/src/router/index.js#L16l).  Even though I've added some comments there I'll try and explain what this code does. I added noop beforeEach hook there because I want to prevent a resolution of the initial route meaning I don't want to show dashboard or login page before the authentication check is resolved. Only after the user is authenticated (or not) I am calling `resolveRoute` function and redirecting the user to the correct page. This worked great with vue-router <= 3.2.0, but something has changed in the newer version and I can't figure out how to fix it in my code or if it has to be fixed inside a vue-router. Anyway, I would appreciate any help you could provide. Thanks

**Comment by posva** [comment]
Make sure to always call `next` inside of a guard

```js
const authGuard = router.beforeEach((to, from, next) => {
  next(false)
})
```

The initial navigation never finished so the popstate listeners were never added

**Comment by sqal** [comment]
@posva Thank you so much, for the help, it indeed fixes this issue. Why it previously worked though? 😂

**Comment by posva** [comment]
because the history listeners were setup independently of the initial navigation, but now they are set after the initial navigation. So the back and forward button were not working but regular navigation were
