### ISSUE TITLE
Clear query in beforeEnter route interface

### ISSUE THREAD

**Issue by dsfcoll** [vuejs/vue-router#3247]
### What problem does this feature solve?
If you want to clear query from route, i can't do it from beforeEnter callback.

That looks like you prevent `next`, if they point to the same route
```js
{
  path: '/',
  beforeEnter (to, from, next) {
    if (!localStorage.getItem('referral')) {
      localStorage.setItem('referral', to.query.r)
      next({ path: '/', query: { } })
    }
  }
}
```

### What does the proposed API look like?
^

**Comment by posva** [comment]
You need to always call `next`:

```js
if (Object.keys(to.query) === 0) next()
else next({ query: {} })
```

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
