### ISSUE TITLE
无法为异步路由组件新增loading状态及error状态

### ISSUE THREAD

**Issue by PakTo** [vuejs/vue-router#3249]
### Version
3.3.4

### Reproduction link
[https://gitee.com/chawpakto/VueAsyncLoadRouteDemo](https://gitee.com/chawpakto/VueAsyncLoadRouteDemo)

### Steps to reproduce
在Vue官方文档中的 [异步组件 - 处理加载状态](https://cn.vuejs.org/v2/guide/components-dynamic-async.html#%E5%A4%84%E7%90%86%E5%8A%A0%E8%BD%BD%E7%8A%B6%E6%80%81) 的案例，为异步组件添加Loading过渡组件及Error错误组件

### What is expected?
Loading组件及Error组件能正常为异步路由组件进行加载过渡及错误处理显示

### What is actually happening?
在实际生成的页面中，Loading及Error组件无法正常作用于异步组件的加载过渡及错误处理

**Comment by posva** [comment]
See https://github.com/vuejs/vue-router/pull/2140
I would avoid using the async factory with vue router because it won't display while the router is waiting for navigation guards. It will only wait after the navigation is confirmed, to fetch the chunk of the page
