### ISSUE TITLE
Abstract history mode doesn't fire `afterEach` hooks when using `router.go()`

### ISSUE THREAD

**Issue by sirlancelot** [vuejs/vue-router#3250]
### Version
3.3.4

### Reproduction link
[https://codepen.io/sirlancelot/pen/wvMPeZj?editors=1011](https://codepen.io/sirlancelot/pen/wvMPeZj?editors=1011)

### Steps to reproduce
1. Open Reproduction (Ensure CodePen's Console is open)
1. In the Output Window, click the "One" link
1. Observe that the `afterEach` hook fires ("Navigate / -> /one" is emitted in the Console)
1. In the Output Window, click the "Back" link

### What is expected?
* The `afterEach` hooks should fire when `router.go()` is used.
* "Navigate /one -> /" should be emitted in the Console.

### What is actually happening?
`afterEach` hooks are not firing. Nothing is emitted in the Console.

**Comment by posva** [comment]
This was introduced in 3.3.0 and could be from this change: https://github.com/vuejs/vue-router/pull/2292
It should also be a good first issue. If anybody wants to submit a PR and there isn't one yet, please do
