### ISSUE TITLE
Vue crashes when using history.state.key as the key of <Router-view> Wrapped in <Keep-alive>

### ISSUE THREAD

**Issue by soulsands** [vuejs/vue-router#3254]
### Version
3.3.4

### Reproduction link
[https://jsfiddle.net/soulsands/zhykod58/3](https://jsfiddle.net/soulsands/zhykod58/3)

### Steps to reproduce
click about

### What is expected?
show the about instance and the page stay normal 

### What is actually happening?
the about instance doesn't show  and the app crashes that  it  doesn't show page again no matter which router link you click. 

---
the reason is that router.replace use the same key while the keep-alive uses the key of  a vnode to track the caches. 
when I click the About link, the key of About Vnode is the same as Home's. so the keep-alive use the cache of home to render the About vnode.
```js
// keep-alive's render method
if (cache[key]) {
          vnode.componentInstance = cache[key].componentInstance;
          // make current key freshest
          remove(keys, key);
          keys.push(key);
        } 
```
I hijacked the go\back\replace methods of router setting a flag when I use those methods and manually set a new key to Router-view. 

this strategy is quite useful, at least for me. it's quite similar to browser's bfcache. Keep-alive only hits cache when user click back or forward button of browser and use a new page otherwise.

but I still think the key should be corresponding to the change of the routes. I think it represents the identifier of a URL or a page. when you replace a page with a new page, the key should be a new key too. 

and maybe router should use a new key too when using webpack hot reloads.

looks it's compatible if the replace methord use a new key since Router just use these keys to support the scroll-behavior feature, 

By the way, I found some inconsistent behavior about the key in history when loading a page.

say the app is running at  http://localhost:8080/

-  open a new tab and fill with  http://localhost:8080/ , the key is a number. reload the page then the key is the same number
-  open a new tab and fill with  http://localhost:8080/#/ , the key is null.  reload the page then the key is null.

all above are loading a page, but the keys are totally different. 

I think it's a good idea to provide a method to get the current key Router maintained  and it's also a good idea to provide a built-in mechanism to support bfcache in vue app

**Comment by posva** [comment]
The key stored in the state isn't public api and one shouldn't rely on it for this kind of things. If you want to implement something similar to [bfcache](https://developer.mozilla.org/en-US/docs/Archive/Misc_top_level/Working_with_BFCache), you will have to create your own incrementing key and save it in history state. Note you should also use HTML5 history for that. If you need hash history you will have to store the key somewhere else
