### ISSUE TITLE
Use vue router on a single HTML file

### ISSUE THREAD

**Issue by kaihendry** [vuejs/vue-router#3255]
### Version
3.3.4

### Reproduction link
[https://myce7qa3h8.execute-api.ap-southeast-1.amazonaws.com/staging/study.html](https://myce7qa3h8.execute-api.ap-southeast-1.amazonaws.com/staging/study.html)

### Steps to reproduce
I'm trying to get https://github.com/vuejs/vue-router/blob/dev/examples/route-props/app.js working on a static HTML page without a build chain.

### What is expected?
Working demo

### What is actually happening?
Cannot use import statement outside a module
/
Uncaught SyntaxError: import declarations may only appear at top level of a module

---
Looking for a demo of https://unpkg.com/vue & https://cdn.jsdelivr.net/npm/vue-router@3.0.6/dist/vue-router.min.js for function mode https://stackoverflow.com/a/62859896/4534

**Comment by posva** [comment]
Make sure to use the hash mode and if you want to use the import syntax, to use type=module on the script tag.
Closing since this is a question and should be posted in the appropriate channels
