### ISSUE TITLE
Update path-to-regexp

### ISSUE THREAD

**Issue by aleksandargosevski** [vuejs/vue-router#3256]
### What problem does this feature solve?
Is there any chance of updating path-to-regexp to a newer version? Right now, the version is 1.8.0, and path-to-regexp is on 6.1.0.

Bunch of things changed and path-to-regexp is a much better module now.

### What does the proposed API look like?
Update path-to-regexp to 6.1.0

**Comment by posva** [comment]
There were a few breaking changes so we cannot upgrade without releasing a new version. In v4 we have our own library for that anyway
