### ISSUE TITLE
vue-router能实现渲染出带域名的链接吗，而不是一个相对路径

### ISSUE THREAD

**Issue by Tianyazz** [vuejs/vue-router#3258]
### What problem does this feature solve?
我在用nuxt.js的时候，seo同事要求源码能渲染出全域名的链接。nuxt-link无法实现渲染出带域名的源代码链接，列如
`<Nuxt-link to="/name">链接</Nuxt-link>`渲染成`<a href="http://www.yuming.com/name">链接<a>`
我看了vue-router的相关文档，貌似没有这样的配置（如果有希望能给出一个实现的例子）。之前用nextjs的时候，next link的as属性，可以实现。

### What does the proposed API look like?
`<router-link to="/name">链接</router-link>`渲染出来的是`<a href="/name">链接</a>`
期待
`<router-link to="/name">链接</router-link>`渲染出来的是`<a href="http://www.yuming.com/name">链接</a>`
类似nextjs里的`<Link as="http://www.yuming.com/name" href="/name">链接<Link>`

**Comment by posva** [comment]
I don't see a difference in having an absolute url instead of a relative one. You can still build this by creating a custom Nuxt Link component that prepends the domain to the href using the v-slot api https://router.vuejs.org/api/#v-slot-api-3-1-0
