### ISSUE TITLE
Select Close to throw a redirect error

### ISSUE THREAD

**Issue by tangdaohai** [vuejs/vue-router#3260]
### What problem does this feature solve?

when router has redirect I got this error: `Redirected when going from "/a" to "/b" via a navigation guard.`

I found this line of code(**199-200**):

[https://github.com/vuejs/vue-router/blob/b0ef4974aa4a8a6a4865717f1fad50954379800a/src/history/base.js#L194-L209](https://github.com/vuejs/vue-router/blob/b0ef4974aa4a8a6a4865717f1fad50954379800a/src/history/base.js#L194-L209)

Redirection is a commonly used function, I think that this error should not be thrown frequently or provide a function to choose whether to throw an error.

By the way, why should this exception be thrown, and what is its purpose?

> I use Google Translate, which may cause difficulty in understanding...

### What does the proposed API look like?
```
// like this
interface NavigationGuardOptions {
  throwError: boolean
}
export type NavigationGuardNext<V extends Vue = Vue> = (
  to?: RawLocation | false | ((vm: V) => any) | void,
  options: NavigationGuardOptions
) => void
```

**Comment by posva** [comment]
This has been extensively explained at https://github.com/vuejs/vue-router/issues/2881#issuecomment-520554378 where it explains how to adapt the behavior. There is also an upcoming PR https://github.com/vuejs/vue-router/pull/3220 to add the necessary API to handle this correctly

To make it short, it always was considered an error before, so with Promises, it had to be a rejection (see example using 3.0.0 https://jsfiddle.net/zoh1dj6w/). This is no longer the case in v4, where navigation failures are not promise rejections anymore and a redirection is considered a successful navigation but changing it on v3 would be a breaking change so it only changed on v4

**Comment by tangdaohai** [comment]
> This has been extensively explained at [#2881 (comment)](https://github.com/vuejs/vue-router/issues/2881#issuecomment-520554378)
> 
> To make it short, it always was considered an error before, so with Promises, it had to be a rejection (see example using 3.0.0 https://jsfiddle.net/zoh1dj6w/). This is no longer the case in v4, where navigation failures are not promise rejections anymore and a redirection is considered a successful navigation

thanks.
