### ISSUE TITLE
Add tags.json and attributes.json files for Vetur

### ISSUE THREAD

**Issue by posva** [vuejs/vue-router#3263]
See https://github.com/vuejs/vetur/issues/2046

I think it makes sense to add a folder `vetur` and add the file paths to the `package.json` file like mentioned at https://vuejs.github.io/vetur/framework.html

cc @octref

**Comment by octref** [comment]
Seems this can be closed.

**Comment by posva** [comment]
Yes, it was added at ea03de16e18218c55203ba497365ad470ebd8e29
