### ISSUE TITLE
Named and dynamic routes

### ISSUE THREAD

**Issue by markwbrown** [vuejs/vue-router#3264]
### What problem does this feature solve?
This allows for a named route to take priority over a dynamic route. Useful in getting some otherwise rather messy logic out of the templates.
i.e. a blog route with an archive page

The end user experience is likely to be better as developers will have more time to work on other things and not coming up with hacky ways to parse a param. 

### What does the proposed API look like?
{path: '/blog/archive/:date(.*)', component: blogArchivePage},
{path: '/blog/category/:categoryName', component: blogCategoryPage},
{path: '/blog/:postName', component: blogPost},
{path: '/products/ourAmazingFlagshipProduct', component: amazingProduct},
{path: '/products/:theRestLessExcitingProducts', component: lessAmazingProducts}

**Comment by posva** [comment]
Named routes already have the priority
Dynamic routing is only supported on v4, so make sure to correctly order your routes in the current version: v3

**Comment by markwbrown** [comment]
@posva I think you missed the intent here. A named route + dynamic prop would be better handled at the router level than putting logic into the component. Please take note of the routes `/blog/:postName` and `/blog/archive/:date` pointing to different components and the order in which they are defined above.
