### ISSUE TITLE
Clicking Back button in Chrome affects my Vue app in cross-origin iframe instead of parent webpage

### ISSUE THREAD

**Issue by markon1** [vuejs/vue-router#3265]
### Version
3.3.4

### Steps to reproduce
So basically I append an iframe with my Vue app to mail.google.com page, and I do all of the routing inside my Vue app with vue-router.
Strange thing is, when I click the Back button in my browser (Chrome), it takes my Vue app in iframe one page back instead of doing that with parent page (mail.google.com).
How can I make it that clicking browser’s back button affect only parent page (mail.google.com) and not my Vue app in appended iframe?

### What is expected?
Clicking on Chrome's  Back button should navigate parent webpage one step backwards.

### What is actually happening?
Clicking on Chrome's  Back button navigates my iframe with vue-router app instead.

**Comment by posva** [comment]
This is simply how it works and cannot be controlled.
