### ISSUE TITLE
Failed: Redirected when going from "/blank" to "/private" via a navigation guard.

### ISSUE THREAD

**Issue by alexey2baranov** [vuejs/vue-router#3266]
### Version
3.3.4

### Reproduction link
[https://github.com/alexey2baranov/vue-test-utils-getting-started/tree/vue-router](https://github.com/alexey2baranov/vue-test-utils-getting-started/tree/vue-router)

### Steps to reproduce
```
git clone https://github.com/alexey2baranov/vue-test-utils-getting-started vue-router-issue
cd vue-router-issue
git checkout vue-router
npm install
npm test
```

### What is expected?
Test should be done

### What is actually happening?
Failed: Redirected when going from "/blank" to "/private" via a navigation guard.
Error: Redirected when going from "/blank" to "/private" via a navigation guard.

---
please don't forget to checkout "vue-router" branch from git repo

**Comment by posva** [comment]
This isn't a bug, this is the navigation failure introduced with the promise api. Please search existing issues for more details

FYI: it's better to mock the router with spies when doing unit or integration tests

**Comment by alexey2baranov** [comment]
Thank you for reply. If i understand you there is new API and any redirect rejects router.push() promise now. is it correct?
