### ISSUE TITLE
Cannot get the 'split' property in navigation guard, which is an undefined or null reference.

### ISSUE THREAD

**Issue by markers16123** [vuejs/vue-router#3273]
[ie에서의 vue router 오류.pdf](https://github.com/vuejs/vue-router/files/5019994/ie.vue.router.pdf)
### Version
3.3.1

### Reproduction link
[https://codesandbox.io/s/pensive-ishizaka-xfsuq?file=/src/router.js](https://codesandbox.io/s/pensive-ishizaka-xfsuq?file=/src/router.js)

### Steps to reproduce
The following error is output in the **IE 11 browser** console.

> You cannot get the 'split' property, which is an undefined or null reference.

 

This error occurs when there is code that redirects from the navigation guard to the login page.

```typescript
// router.js
router.beforeEach((to, from, next) => {
    if (
        !to.path.startsWith('/account/login') &&
        !store.state.localization.supports
    ) {
        store
            .dispatch(types.GLOBAL_INIT, {})
            .then((result) => {
                if (result?.type === 'redirect') {
                    next(result.data); // <== Error!!
                } else {
                    next();
                }
            })
            .catch((err) => {
                console.error('navigation guard', err);
            });
    } else {
        next();
    }
});

export default router;
```

The `createRouterError` function in the `vue-router.esm.js` file inside the router causes an `undefined` error. The code that produces the error is `var newStack = error.stack.split('\n');`. `error.stack` is `undefined`.

```js
function createRouterError (from, to, type, message) {
  var error = new Error(message);
  error._isRouter = true;
  error.from = from;
  error.to = to;
  error.type = type;

  var newStack = error.stack.split('\n');
  newStack.splice(1, 2); // remove 2 last useless calls
  error.stack = newStack.join('\n');
  return error
}
```

In chrome, it has the value of the stack property.
 

In IE, the stack property is undefined.
 

In the following reference documentation, the stack property is called a non-standard property.

Error.prototype.stack (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stack)

> **Non-standard**
> This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.
 

When handling the stack in the createRouterError function, it seems that you need to handle the exception for null or undefined.

 

Any other ideas?

### What is expected?
When handling the stack in the createRouterError function, it seems that you need to handle the exception for null or undefined.

### What is actually happening?
The following error is output in the **IE 11 browser** console.

> You cannot get the 'split' property, which is an undefined or null reference.

This error occurs when there is code that redirects from the navigation guard to the login page.

**Comment by posva** [comment]
Upgrade your vue-router version, this was fixed a while ago 🙂
