### ISSUE TITLE
Vue test utils -router.push - UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by gfrileux** [vuejs/vue-router#3275]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/vue-router-bug-2jvks](https://codesandbox.io/s/vue-router-bug-2jvks)

### Steps to reproduce
Set up a component using router-link , and then create a unit test for that component.
As part of the unit test, we set up a router, and use router.push. the output from `nom run test` issues an UnhandledPromiseRejectionWarning

Please see the sandbox for the component and test set up. Basically, we do this:
```
import { mount, createLocalVue } from '@vue/test-utils';
import VueRouter from 'vue-router';
import { routerParams } from '../../../src/router';
import MenuLink from '../../../src/components/menu/MenuLink.vue';

const localVue = createLocalVue();
localVue.use(VueRouter);

describe('components - MenuLink', () => {
  test('renders as active if route matches to prop without query string', async () => {
    const router = new VueRouter(routerParams);
    const wrapper = mount(MenuLink, {
      localVue,
      router,
      propsData: {
        icon: '',
        label: 'Coupons',
        to: '/coupons',
      },
    });
    expect(wrapper.vm.$route.path).toBe('/blank'); // initial route the router gets mounted with in test
    expect(wrapper.find('a').classes().length).toBe(1);
    expect(wrapper.find('a').classes()[0]).toBe('Vlt-sidemenu__link');

    router.push('/coupons');
    await wrapper.vm.$nextTick();
    await wrapper.vm.$nextTick();

    expect(wrapper.vm.$route.path).toBe('/coupons');
    expect(wrapper.element).toMatchSnapshot();
    expect(wrapper.find('a').classes().length).toBe(2);
    expect(wrapper.find('a').classes()[0]).toBe('Vlt-sidemenu__link');
    expect(wrapper.find('a').classes()[1]).toBe('Vlt-sidemenu__link_active');
  });
});

```

### What is expected?
I would expect no such output from Jest

### What is actually happening?
This output is generated:
```
(node:47299) UnhandledPromiseRejectionWarning
(node:47299) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**Comment by posva** [comment]
FYI it's better to mock the router when testing things involving it. The test you are writing _renders as active if route matches to prop without query string_ seems to be testing Vue Router. The only thing I can see in your code is that you want to `await router.push(...)`. It might give you more information as well.
Closing because this is a question.

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by gfrileux** [comment]
Adding `await` did give me a better error message, linked to how the router was initialised. I fixed  some router params and the test works great. It was not possible to stub vueRouter because of the v-slot that I'm using. Because this is our menu I wanted a test that was as clause to reality as possible. All fixed now - thanks !
