### ISSUE TITLE
Undefined value in router query now become undefined string

### ISSUE THREAD

**Issue by lephuongbg** [vuejs/vue-router#3276]
### Version
3.4.0

### Reproduction link
[https://jsfiddle.net/herophuong/97bq4vmh/](https://jsfiddle.net/herophuong/97bq4vmh/)

### Steps to reproduce
1. Call `$router.push({path: '/', query: {q: undefined}})`

### What is expected?
URL should be `/`

### What is actually happening?
URL is now `/?q=undefined`

---
Possibly due to fixing this issue: https://github.com/vuejs/vue-router/issues/2131

**Comment by pfdgithub** [comment]
This problem is introduced from 3.0.3
https://github.com/vuejs/vue-router/releases/tag/v3.0.3

undefined should be ignored

**Comment by posva** [comment]
FYI this has been fixed and released. Undefined query Params are removed from the string representation
