### ISSUE TITLE
路由切换后，状态保持问题

### ISSUE THREAD

**Issue by LayGit** [vuejs/vue-router#328]
在 ready () 中 异步加载数据，路由跳转之后再回来，会重新调用 ready () 方法加载数据。
如何能够让 页面状态 保持，只在第一次渲染的时候调用 ready () 方法？

**Comment by yyx990803** [comment]
`<router-view keep-alive></router-view>`

**Comment by huysh3** [comment]
在加上keep-alive后，
除了去监听hashchange来强制执行ready外
是否还有其他可以使【每次显示该.vue(包括点击返回后显示该页面)ready都会被执行】的钩子？

**Comment by renjian93** [comment]
@huysh3 可以用路由的data钩子

**Comment by fnlctrl** [comment]
@huysh3 可以用attached和detached钩子。
@renjian93 data在2.0被移除了，请避免使用。

**Comment by renjian93** [comment]
@fnlctrl 谢谢提醒，2.0的新改动还没仔细看.

**Comment by kaysonli** [comment]
可以只针对特定路由使用keep-alive 吗？

**Comment by yanlee26** [comment]
@yyx990803,路由切换，闪退问题：二级路由间切换页面内容闪一下没了，只有再切换到一级路由然后再到二级路由某项才能正常显示，这是哪里的问题？？
```
//router.js
{path:'/science',component:science,
			children:[
				{path:'',component:sc0},
				{path:'sc1',component:sc1},
				{path:'sc2',component:sc2},
			]
		},
//template
 <article>
      <keep-alive>
        <transition name="slide-fade">       
            <router-view ></router-view>       
        </transition> 
      </keep-alive>     
    </article>
```

**Comment by asionius** [comment]
@huysh3 你问的问题你解决了吗

**Comment by huysh3** [comment]
@asionius 
只给部分组件加上keep-alive就可以了
在vue-router的meta属性上设置
然后在根组件app.vue里去判断

**Comment by lisleyang** [comment]
@huysh3 有例子么，想看一下具体的实现

**Comment by huysh3** [comment]
@lisleyang  @asionius 
https://www.zhihu.com/question/37480475/answer/137739230?group_id=815948549488545792

**Comment by aa-ziyi** [comment]
<router-view keep-alive></router-view>   路由有切换状态保持，但当我不同路由指向同一组件时如何保留状态，如用户的编辑和创建指向同一个组件，如何实现切换这两个路由同时数据都保留

**Comment by sysuxw** [comment]
@Demon2 我也遇到这个问题了，请问解决了吗

**Comment by hellwen** [comment]
@Demon2 我们是在做全局tabs控制的时候有这样的问题，你也是吗？

**Comment by aa-ziyi** [comment]
目前我的解决方案是只能是一个路由对应一个组件，编辑和创建代码一致就统一封装成一个组件。编辑和创建的页面中分别去调用这个组件；

**Comment by solzhang777** [comment]
能不能用结合vuex来保持状态， 需要保持的组件匹配vuex下的一个data
