### ISSUE TITLE
beforeRouter遇到confirm再next的问题

### ISSUE THREAD

**Issue by MMhui** [vuejs/vue-router#3280]
### Version
3.0.6

### Steps to reproduce
情景一：
```
beforeRouteLeave (to, from, next) {
  const answer = window.confirm('Do you really want to leave? you have unsaved changes!')
  if (answer) {
    next()
  } else {
    next(false)
  }
}
```

连续多次触发物理返回键的时候，history会改变，最终显示的页面依旧是当前页面，但是接下来如果next()的话跳的不是上一页。

情景二：
```
beforeRouteLeave (to, from, next) {
  next(false)
  const answer = window.confirm('Do you really want to leave? you have unsaved changes!')
  if (answer) {
    next()
  } else {
    next(false)
  }
}
```
这种写法可以解决上面情景一的问题，但是会导致上一个页面需要返回两次，上一页第一次触发物理返回键的时候没有任何反应，第二次才能真正的返回。

### What is expected?
beforeRouterLeave中如何使用异步函数判断next，并且还不影响到history

### What is actually happening?
next不能卸载异步函数中，会有不好的事情发生

**Comment by posva** [comment]
Using interface blocking API like confirm is the way to prevent multiple click on back. Call next only once though

Please do not open bug reports without reproduction and not in English

**Comment by MMhui** [comment]
The user's behavior of operating the physical return key is uncontrollable. When the physical return key is clicked, the next (false) command is not received, and the history has been changed. If the return is triggered directly next, the direct return is not the previous page.（用户操作物理返回键的行为是不可控制的，物理返回键被点击的那一刻并没有拿到next(false)的命令，history已经被改变了，接下来直接触发返回的话，直接返回的就不是上一页了。）
Whether the browser address should be changed when the next function is executed and the parameters of the next function are obtained. （Whether the browser address should be changed when the next function is executed and the parameters of the next function are obtained.）

**Comment by MMhui** [comment]
The user's behavior of operating the physical return key is uncontrollable. When the physical return key is clicked, the next (false) command is not received, and the history has been changed. If the return is triggered directly next, the direct return is not the previous page.（用户操作物理返回键的行为是不可控制的，物理返回键被点击的那一刻并没有拿到next(false)的命令，history已经被改变了，接下来直接触发返回的话，直接返回的就不是上一页了。）
Whether the browser address should be changed when the next function is executed and the parameters of the next function are obtained. （浏览器地址的改变是否应该是在执行了next函数拿到了next函数的参数的情况下。）
