### ISSUE TITLE
There's no way to global handle for onAbort in vue router (Check onError). Implement global onAbort router lifecycle hook.

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [vuejs/vue-router#3286]

**Comment by afwn90cj93201nixr2e1re** [comment]
### Version
3.3.4

### Reproduction link
[https://1.1](https://1.1)


### Steps to reproduce
1

### What is expected?
Add new **global** VUE ROUTER **onAbort** **HANDLE**

### What is actually happening?
nothing

---

https://github.com/vuejs/vue-router/issues/2956#issuecomment-539049720

As i said, just check the code, you missed onError callback calling here: https://github.com/vuejs/vue-router/blob/dev/src/history/base.js#L107 , but checking for false here: https://github.com/vuejs/vue-router/blob/dev/src/history/base.js#L153

simple code:
beforeRouteEnter(to, from, next){
if(1){next(new Error('This gonna call onError global route Hook');return;}
if(1){next(false);return;}//but that's not, this call only onAbort local route link.
}

i know, thats expected coz that's onError which mean calback should be called only on Error, but how we should operate/hook on false next on global level, which also stop routing?

I think you should add ||error===false
or create new global hook for router which called onCancel.

You really need repo for this?

**Comment by afwn90cj93201nixr2e1re** [comment]
Right now i should everytime patch vue router just for getting this functionality, coz i need to stop progress bars/loading bars on any page Aborts, but i cant, coz it's not implemented yet.

@posva

**Comment by posva** [comment]
Use `afterEach` and `onError`. Also see https://router.vuejs.org/guide/advanced/navigation-failures.html. Don't open issues without following the template

**Comment by afwn90cj93201nixr2e1re** [comment]
> issues without following the template 

What else do you need? I provide simple example code, what else i should provide?

> Use afterEach and onError 

Im not fucking stupid person which create issues just for fool.

https://github.com/vuejs/vue-router/blob/5c4221adf0d3dae41708f9b70b2d39e711f852b5/src/history/base.js#L138-L154

Pls stop being too angry. Before closing issue without any valid reason just try to investigate.
If you can't just open ur code and checkout that OnError **not** called on **false** condition then idk why are u still maintaining this one.
![изображение](https://user-images.githubusercontent.com/9306996/89718734-d210a880-d9b0-11ea-8eb9-bba2b8761a86.png)

I think that you should read it before sending it to me, i have read it in 2019 october. But u still dont wanna just look up inside code.

> As i said, just check the code, you missed onError callback calling here: https://github.com/vuejs/vue-router/blob/dev/src/history/base.js#L107 , but checking for false here: https://github.com/vuejs/vue-router/blob/dev/src/history/base.js#L153
**simple code:**
```
beforeRouteEnter(to, from, next){
   if(1){next(new Error('This gonna call onError global route Hook');return;}
   if(1){next(false);return;}//but that's not, this call only onAbort local route link.
}
```

https://hastebin.com/ezotiwuqas.coffeescript

read 29 line description
