### ISSUE TITLE
The "mounted" hook of the cached parent component is called a second time after the child component mounted in the nested router-view

### ISSUE THREAD

**Issue by stovberpv** [vuejs/vue-router#3292]
### Version
3.3.4

### Reproduction link
[https://codesandbox.io/s/oribo](https://codesandbox.io/s/oribo)

### Steps to reproduce
1. Open console.
2. Go to Parent.
3. Go to ChildA.
4. Go to ChildB.
5. Go to ChildC.

### What is expected?
`keep-alive` Parent component mounted once.

### What is actually happening?
The already mounted parent component mounted a second time after mounting the child component in the nested router-view.

**Comment by posva** [comment]
this is normal because you are passing a `key` to the root instead of the nested `router-view`

**Comment by stovberpv** [comment]
I understand that the parent component needs to be mounted in order for the route to appear in the child view. But is it ok for the parent component to be mounted twice? It's already mounted and cached, why are we doing it again? It would be more logical to call an activated hook in the parent.

**Comment by posva** [comment]
by setting the `key` to path **you are forcing its mounting**. As said add the `key` to the nested `router-view` instead if you don't want that
