### ISSUE TITLE
Type definition does not contain enumeration for NavigationFailureType

### ISSUE THREAD

**Issue by amjmhs** [vuejs/vue-router#3293]
### Version
3.4.2

### Reproduction link
[https://jsfiddle.net/dmop5w9b/](https://jsfiddle.net/dmop5w9b/)

### Steps to reproduce
I want to check for navigation-errors of a certain type. So there is the new `VueRouter.isNavigationFailure` function which takes a type as second parameter. But because of the missing type definition for this type, I can not call this function without typescript-errors.

```
if (VueRouter.isNavigationFailure(err, VueRouter.NavigationFailureType.duplicated)) {
 ...
}
```
Typescript error is: `Property 'duplicated' does not exist on type 'NavigationFailureTypeE'.ts(2339)`

I provided a fiddle with the code, but did not get the errors there... Those errors just appear in VSCode.

### What is expected?
No typescript errors

### What is actually happening?
Typescript errors

**Comment by posva** [comment]
Thanks!

**Comment by loeffel-io** [comment]
Still not possible to use `NavigationFailureType` or `isNavigationFailure` 

https://router.vuejs.org/guide/advanced/navigation-failures.html#detecting-navigation-failures is not working (typescript)

**Comment by amjmhs** [comment]
```typescript
import VueRouter from 'vue-router';

if (VueRouter.isNavigationFailure(err)) {
          switch (err.type) {
            case VueRouter.NavigationFailureType.duplicated: {
....
```
this was working for me.
