### ISSUE TITLE
Reset history.current on destroy app

### ISSUE THREAD

**Issue by nightnei** [vuejs/vue-router#3294]
### Version
3.3.4

### Reproduction link
[https://jsfiddle.net/NightNei/5bv7co0u/10/](https://jsfiddle.net/NightNei/5bv7co0u/10/)

### Steps to reproduce
**1)** Open "Reproduction link" -> OK - beforeResolve handler is run
**2)** Click "foo" btn -> OK - beforeResolve handler is run
**3)** Click "home" btn -> OK - beforeResolve handler is run
**4)** Click "destroy" btn -> OK - app destroyed
**5)** Click "start" btn -> FAIL - app started, but beforeResolve handler isn't run

### What is expected?
`beforeResolve` is always run on start app

### What is actually happening?
`beforeResolve` isn't run on restarting app

---
I am a maintainer of "Isomorphic Layout Composer" - Micro-frontends library( https://github.com/namecheap/ilc ).  
And we have faced the problem of remounting Vue apps - when we render the same app second time, it will ignore running of `beforeHooks`.  

Since on restart app `history.current.matched` contains last instance of route component so this condition: https://github.com/vuejs/vue-router/blob/dfc289202703319cf7beb38d03c9258c806c4d62/src/history/base.js#L159 returns `true` and `router.beforeHooks` are ignored.
On Destroy app we should reset `history.current` to default value(`START`).

**Comment by posva** [comment]
I remember @joeldenning proposing something similar but I might be wrong. This seems reasonable to do when the last app is destroyed (set the location to START)

**Comment by internettrans** [comment]
I agree - [my recent pr](https://github.com/vuejs/vue-router/pull/3172) changed things so that the `popstate` and `hashchange` listeners are cleaned up when the last vue app is destroyed, but it didn't change it so that the history entries would be cleaned up.
