### ISSUE TITLE
named views not working with webpack

### ISSUE THREAD

**Issue by puschie286** [vuejs/vue-router#3299]
### Version
2.6.1

### Reproduction link
[https://drive.google.com/file/d/1xOYi2SfIJTo0g8lFFKlutuvUCxxJKWtz/view?usp=sharing](https://drive.google.com/file/d/1xOYi2SfIJTo0g8lFFKlutuvUCxxJKWtz/view?usp=sharing)

### Steps to reproduce
open project
yarn install
npm serve
-> check console

### What is expected?
named views works

### What is actually happening?
named views throw error:
[Vue warn]: Failed to mount component: template or render function not defined.

**Comment by posva** [comment]
Please open a new issue with a reproduction hosted on GitHub or jsfiddle. Thank you
