### ISSUE TITLE
Require component not working with global registration

### ISSUE THREAD

**Issue by swannknani** [vuejs/vue-router#33]
Following your example, the following code is not working when register a global component like so:

// Registration (file ->inbox/index.js)

``` module.exports = Vue.component('my-component, {}); ```

// Require inside ```router.map``` function :

```
'/inbox': {
    component: require('./inbox/index.js')
}
 ```

**Comment by yyx990803** [comment]
`Vue.component` doesn't return the component constructor, `Vue.extend` does. Read the paragraph right above "Data Flow": http://vuejs.org/guide/components.html

**Comment by swannknani** [comment]
Ok so it should work like so ?

```
export default Vue.extend({

	data: function() {

		return {
			hello: 'world'
		};
	}
});

```
