### ISSUE TITLE
error

### ISSUE THREAD

**Issue by puschie286** [vuejs/vue-router#3301]
### Version
2.6.0

### Reproduction link
[https://github.com/puschie286/vueroutererror](https://github.com/puschie286/vueroutererror)

### Steps to reproduce
open project
yarn install
npm serve
-> check console

### What is expected?
named views works

### What is actually happening?
named views throw error:
[Vue warn]: Failed to mount component: template or render function not defined.

Please open a new issue with a reproduction hosted on GitHub or jsfiddle. Thank you

_Originally posted by @posva in https://github.com/vuejs/vue-router/issues/3299#issuecomment-678514737_

**Comment by posva** [comment]
Named views are put under the option `components`, not `component`

**Comment by puschie286** [comment]
No, that doesnt fix it - have you tried it ? the error is gone but it doesnt work

**Comment by puschie286** [comment]
stop closing reported issues without testing

**Comment by posva** [comment]
It turns out you were also missing the `name` on RouterView. Please read the docs (https://router.vuejs.org/guide/essentials/named-views.html) before opening issues. Also remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by puschie286** [comment]
what do you mean with "missing the name on routerview"
the router view in app has no name to use "default" as name like in the documentation
the router view in Home has the name "test"
so where is the name missing ?
edit: updated the repo with to use components instead of components - still the second routerview is not showing the content

**Comment by posva** [comment]
Look at the documentation page I sent you, named views are adjacent, not nested, move it from Home to App.vue. Your reproduction is working as expected. Please, use the chat or forum for further questions.
