### ISSUE TITLE
Completely standalone routers on same Vue app

### ISSUE THREAD

**Issue by Vanojx1** [vuejs/vue-router#3304]
### What problem does this feature solve?
Im implementing a Vue app that has a main column with his router and a sidebar with his own router too, the first router route depends on the current url and the sidebar router depends on an abstract history. Right now this cannot be done so i've forked the vue-router repo and implemented in my own way, you can find it here https://github.com/Vanojx1/vue-router. I hope that this feature will be implemented in the future as it may be very usefull.

### What does the proposed API look like?
Here an example of the implementation: 

```
import Vue from 'vue'
import VueRouter from 'vue-router'

Vue.use(VueRouter)

const Foo = { template: `<div class="foo"><h1>foo</h1></div>` }
const Bar = {
  template: `
    <div class="bar">
      <h1>bar</h1>
      <router-link standalone router-name="testRouter" to="/buz">TOBUZ</router-link>
    </div>`
}
const Buz = {
  template: `
    <div class="buz">
      <h1>buz</h1>
      <router-link standalone router-name="testRouter" to="/">TOBAR</router-link>
    </div>`
}

const router = new VueRouter({
  mode: 'history',
  base: __dirname,
  routes: [
    { path: '/', component: Foo }
  ]
})

const testRouter = new VueRouter({
  mode: 'abstract',
  base: __dirname,
  routes: [
    { path: '/', component: Bar },
    { path: '/buz', component: Buz }
  ]
})

new Vue({
  router,
  template: `
    <div id="app">
      <router-view />
      <router-view :standalone="$options.testRouter" router-name="testRouter" />
    </div>
  `,
  testRouter
}).$mount('#app')
```

**Comment by posva** [comment]
Thanks for the proposal, this should be covered with the RouterView's `route` prop that was added on vue router v4 and will likely be backported. It allows specifying what route to render.

However, I can see how different expectations exist based on passing a router instance to a router view, and I don't think it's an idea worth pursuing. If you feel differently, feel free to open an RFC that goes into the details of all the different interactions.

I also think you don't need a router to implement an independent view
