### ISSUE TITLE
Prevent Component From Re-rendering when navigating from empty route to "/"

### ISSUE THREAD

**Issue by martinmckenna** [vuejs/vue-router#3305]
### What problem does this feature solve?
This solves a redundant re-render because your homepage component should be rendering on both `hello.com` and `hello.com/?query=hello`

### What does the proposed API look like?
`router.push({ name: from.name, query: { something: 'example' }})` should be smart enough to not re-render the component if the path hasn't changed

**Comment by martinmckenna** [comment]
Just updated to `v3.4.3` and still getting the same issue too

**Comment by posva** [comment]
Vue router doesn't control re render of components. Maybe you have a `key` attribute on the `router-view` component. In any case, when reporting a bug, please provide a reproduction.

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
