### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Redirected when going from "/" to "/en" via a navigation guard.

### ISSUE THREAD

**Issue by n4an** [vuejs/vue-router#3307]
### Version
3.4.3

### Reproduction link
[https://github.com/vuejs/vue-hackernews-2.0](https://github.com/vuejs/vue-hackernews-2.0)

### Steps to reproduce
install last packages and webpack 4

### What is expected?
Why in this code is wrote that it redirect only // next('/') or next({ path: '/' }) -> redirect 
if it redirect all next( something)?
And I can't use it 

`
router.beforeEach((to, from, next) => {
  if (to.meta.auth && !store.getters.isLoggedIn) {
    next({
      path: '/login'
    })
  }
  else {
    next()
  }
`

because get error always if next paramenter is present ('/home' or {name: 'home'} for example)

`

    } else if (
          typeof to === 'string' ||
          (typeof to === 'object' &&
            (typeof to.path === 'string' || typeof to.name === 'string'))
        ) {
          // next('/') or next({ path: '/' }) -> redirect
          abort(createNavigationRedirectedError(current, route));
          if (typeof to === 'object' && to.replace) {
            this$1.replace(to);
          } else {
            this$1.push(to);
          }
        } else {
`

### What is actually happening?
error

UnhandledPromiseRejectionWarning: Error: Redirected when going from "/" to "/en" via a navigation guard.

**Comment by posva** [comment]
Please see https://router.vuejs.org/guide/advanced/navigation-failures.html

**Comment by n4an** [comment]
It's worked well with 3.0.0.
After downgrade to 3.2.X, 3.0.0 and back to 3.4.3 and some changes in router it seems to work well!
Or is miraje?
Lost one day to fix.

Work without Navigation Failures.
I try before you answer the router.push(context.url).catch() but not helped ( withut: if (isNavigationFailure(failure, NavigationFailureType.redirected)) ...).

I not understand tha this was, but was terrible

**Comment by phlegx** [comment]
I get the same error @Mitch-i @posva with SSR on server side!

```js
router.beforeEach((to, from, next) => {
  // ...

  // EXAMPLE 1:
  if (to.matched.some((record) => record.meta.requiresAuth && !isAuthenticated()) {
    return next({ name: 'login', params: { locale: locale } }) // Error raised on this line, but only on SSR server side.
  }
  next({ params: { locale: locale } })

  // EXAMPLE 2: Also this variant don't work.

  if (to.matched.some((record) => record.meta.requiresAuth && !isAuthenticated()) {
    next({ name: 'login', params: { locale: locale } }) // Error raised on this line, but only on SSR server side.
  } else {
    next({ params: { locale: locale } })
  }
})
```

### Error

```
UnhandledPromiseRejectionWarning: Error: Redirected when going from "/" to "/en/" via a navigation guard.
    at createRouterError (/app/node_modules/vue-router/dist/vue-router.common.js:1961:15)
```

**vue-router:** 3.4.5
