### ISSUE TITLE
vnode passed to directive missing data.on handlers for router-link

### ISSUE THREAD

**Issue by brianpmaher** [vuejs/vue-router#3308]
### Version
3.4.3

### Reproduction link
[https://jsfiddle.net/5fr2Luha/8/](https://jsfiddle.net/5fr2Luha/8/)

### Steps to reproduce
1. Create a custom directive
2. Use custom directive on router-link with tag button
3. Note the vnode parameter passed to the directive bind hook

### What is expected?
since an on.click handler is being added in vue-router to the element, I'd expect to see that when the directive is bound to the element.

### What is actually happening?
There are no click events in the vnode passed to the directive bind event.

---
Not sure if this is an issue with vue router or vue, but figured I'd start here.

**Comment by posva** [comment]
Closed in favor of https://github.com/vuejs/vue/issues/11635
