### ISSUE TITLE
Question: How to pass data from one component to other

### ISSUE THREAD

**Issue by luis-conor** [vuejs/vue-router#331]
Hi,
I have a component loaded and want to do .go('/other-component'), and on the 'other-component' want  to receive an object from the first. 

What is the correct way to do this?

Thanks in advance!

**Comment by amirrustam** [comment]
Hi, @luis-conor welcome to Vue.js. The "Issues" section of the project repo is reserved for bug reports, feature requests, and project enhancement discussions. You can always ask your questions within the [community forums](http://forum.vuejs.org) or on [Gitter - project chat](https://gitter.im/vuejs/vue), where a the community will be glad to help you out. To learn more about what you should post in the Issues section please review the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines).

Please close out this issue, and ask this question within the places linked above. Thanks.

**Comment by luis-conor** [comment]
Hey thanks for the reply - sorry I didn't realise there were those strict rules.
