### ISSUE TITLE
Documentation request: How to import router.push() error types

### ISSUE THREAD

**Issue by alexey2baranov** [vuejs/vue-router#3312]
### What problem does this feature solve?
After https://github.com/vuejs/vue-router/issues/2881 we have new promise api which rejects pushes with errors which are differed by `error.type` field. But documentation doesn't cover those type's values. Those type's values are very important inside tests. But i don't see how to import them hire https://router.vuejs.org/guide/essentials/navigation.html#router-push-location-oncomplete-onabort

### What does the proposed API look like?
I suggest to append documentation with simple scetch example which
1. does router.push()
2. catch and compare thrown error **with imported constant**

Have a nice day..

**Comment by posva** [comment]
See https://router.vuejs.org/guide/advanced/navigation-failures.html#detecting-navigation-failures
