### ISSUE TITLE
Error Redirected 

### ISSUE THREAD

**Issue by ppvy** [vuejs/vue-router#3316]
### Version
3.4.3

### Reproduction link
[http://xxx.xxx](http://xxx.xxx)

### Steps to reproduce
`vue.runtime.esm.js?2b0e:1888 Error: Redirected when going from "/home" to "/product" via a navigation guard.`

### home.vue
`this.$router.push('/product')`

## a router guard `permission.js`
```
async function initRouter (router) {
  router.beforeEach(async (to, from, next) => {
    NProgress.done(true)
    NProgress.remove()
    NProgress.start()

    const token = store.state.user.token
    const info = store.state.user.info

    if (to.meta.requireAuth && !token) {
      return next({ // Here is an error，Multiple redirection？
        path: '/login',
        query: { redirect: to.fullPath },
      })
    } else if (to.path === '/login' && token) {
      return next({ path: '/home' })
    }

    if (token && !info) {
      await store.dispatch('user/getInfo')
    }

    store.commit('user/SET_INIT', true)

    next()
  })

  router.afterEach(() => {
    NProgress.done()
  })
}
```

### What is expected?
When redirecting, modify the redirect

### What is actually happening?
error

**Comment by posva** [comment]
https://router.vuejs.org/guide/advanced/navigation-failures.html

---

Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by ppvy** [comment]
Thank you very much. @posva 

yi，You changed avatar。
