### ISSUE TITLE
"Loading chunk failed" error causes unwanted redirect

### ISSUE THREAD

**Issue by AeonFr** [vuejs/vue-router#3318]
### Version
3.4.3

### Reproduction link
[https://codesandbox.io/s/vue-router-example-forked-74fsg?file=/router/index.js](https://codesandbox.io/s/vue-router-example-forked-74fsg?file=/router/index.js)

### Steps to reproduce

0. Download the project from CodeSandbox or use any project that has async components in routes
1. Compile the application
2. Delete the compiled async chunks (e.g. with a command like this one:
```
find ./public/assets/chunks -type f -name '[0-9]*.[0-9a-zA-Z]*.js' -delete
```
)

3. Try to navigate to a route whose component is async

### What is expected?
If a chunk fails to load or there is another navigation error, no redirect should happen, or it should be a way to prevent it.

The `onError` should be used by the user to control the behaviour

### What is actually happening?
Whenever a chunk fails to load, the router redirects to whatever `router.options.base` is defined to.

This redirect can't be prevented even if the `onError` catch is used.

---
I would like to show an error screen and suggest the users to reload the page if the navigation fails.

But since the route is overwritten, reloading the page would make users end up in a totally different place from where they wanted to go.

This is an example code to give context on what I'm trying to achieve

```
router.onError((error) => {
  const pattern = /Loading chunk (\d)  failed/g;
  const isChunkLoadFailed = error.message.match(pattern);
  const targetPath = router.history.pending.fullPath;
  if (isChunkLoadFailed) {
    // Here it would be nice to show the user a button to try refreshing the page,
    // But A few milliseconds after this code is executed, a redirection to "/" happens
    // Therefore refreshing the page takes you to another page
```

For anyone encountering this error, I found out you can use `history.replaceState` to go back to the current path. But I find it weird to have to do this in the first place.

```
// Handle missing chunks
router.onError((error) => {
  const pattern = /Loading chunk (\d)  failed/g;
  const isChunkLoadFailed = error.message.match(pattern);
  const targetPath = router.history.pending.fullPath;

  if (isChunkLoadFailed) {
    console.error(error);

    modals.showError();

    history.replaceState("", "", targetPath);
  } else {
    throw error;
  }
});
```

**Comment by posva** [comment]
Please provide a boiled down repro: only Vue router and Vue (no vue fire or other libs)

**Comment by AeonFr** [comment]
i tried to create a simple repo to test this with Vue cli, but the webpack setup was different and I was unable to load components asynchronously. I'll keep this issue closed and come back to this on friday to try and achieve a proper repository to reproduce this.
