### ISSUE TITLE
Comments after wrapper in router-view child component causes fragment instance

### ISSUE THREAD

**Issue by dargue3** [vuejs/vue-router#332]
Note: I'm using laravel-elixir-vuefiy to compile my .vue files down.

Say in the component.vue child of your `<router-view></router-view>` you had the following:
```javascript
<template>
  <div id="wrapper">

    <p>This works!</p>

  </div>
</template>

<script>
...
```

But if you had that same code with some sort of comment after the wrapper div, this component is considered a fragment instance.
```javascript
<template>
  <div id="wrapper">

    <p>This is a fragmented instance!</p>

  </div> <!-- end of the template -->
</template>

<script>
...
```

Not saying this is necessarily a bug, mainly because I'm not smart enough to know if this is just caused by the vueify process not handling HTML comments. Figured I would just post this here, as I pulled my hair out for 2 hours before finally finding the issue.

The one difference I've noted is that this is NOT the case in components that are children of other components. It seems to be an intricacy of the router-view component

**Comment by GuillaumeLeclerc** [comment]
Any news on this on ? This is quite annoying because we don't have any animations on components with comments in it.

**Comment by dargue3** [comment]
No you can still have comments inside your template, just don't put them outside of the "wrapper" div that encapsulates your whole template. 

Just to really make sure you understand: to avoid a component being a fragment instance, you must have everything inside the template also wrapped in a single element, in my example it is the ``` <div id="wrapper"> ```. The fact that I had a comment on the outside of that wrapper was the reason I was getting a fragment instance.

My post here is merely to address whether or not this is a bug or expected behavior.

**Comment by yyx990803** [comment]
Also, this issue is better moved to `vue-loader` and `vueify` since it's not `vue-router` related.

**Comment by GuillaumeLeclerc** [comment]
@yyx990803 wouldn't be better to put it into vue itself since I suppose it would be the case in the template of a component too ?

**Comment by yyx990803** [comment]
@GuillaumeLeclerc good point - although stripping them out at compile time is more efficient. (Otherwise Vue would have to check for comments in every template at runtime)

**Comment by GuillaumeLeclerc** [comment]
Make sense. But some people don't use vueify. In other hand I doubt they will add inline comments.

**Comment by altitudems** [comment]
It took me a while to figure this out. Often I will add a comment indicating what a closing div tag is related to so that I can easily and quickly move things around with breaking tag nesting.

Simple enough to remember not to do this on root elements, but still annoying.

```
<template>
  <div class="component">
    ...
  </div><!-- /.component -->
</template>

**Comment by yyx990803** [comment]
This has been fixed in Vue.js core and will be out in next release.

**Comment by GuillaumeLeclerc** [comment]
Thank you very much !
