### ISSUE TITLE
[Request] Remove Redundant Navigation Errors 

### ISSUE THREAD

**Issue by martinmckenna** [vuejs/vue-router#3320]
### What problem does this feature solve?
These console errors are unnecessary. Vue Router knows itself whether or not something is redundant, so why not just silently return early with no error? Seems like a pointless error

Especially annoying when you have error reporting like Sentry (and even more annoying when you're paying for it) and getting thousands of reports and having to intentionally ignore them

### What does the proposed API look like?
No console logging

**Comment by martinmckenna** [comment]
and yes I realize I can just `router.push.catch(e => e)`, but what's the point?

**Comment by posva** [comment]
See https://router.vuejs.org/guide/advanced/navigation-failures.html

This would be a breaking change but it already changed for v4

**Comment by targetlucked69** [comment]
What about handling errors with the `next` callback in `beforeEach` hooks? Im getting flooded by navigation guard errors in sentry
