### ISSUE TITLE
When using abstract router, <router-view> doesn't match the default component on initial render (within iframe/Cypress)

### ISSUE THREAD

**Issue by JessicaSachs** [vuejs/vue-router#3324]
### Version
3.4.3

### Reproduction link
[https://github.com/JessicaSachs/cypress-abstract-router/](https://github.com/JessicaSachs/cypress-abstract-router/)

### Steps to reproduce
We're trying to use abstract router to make components using Router testable within Cypress. It's almost working. The initial mount fails to match the default `Home` component, and so the `<router-view>` is empty.

Subsequent clicks on `<router-link>` cause `<router-view>` to render fine.

1. Clone repo & yarn install
2. `npm run test:components`
3. open `App.spec.js`

### What is expected?
Initial mount of App component should render the `<router-view>`

### What is actually happening?
Nothing is being mounted inside of `<router-view>`

If you manually interact with the About & Home links, the `<router-view>` will properly find the components for About & Home. It's only the initial render that isn't working correctly.

**Comment by JessicaSachs** [comment]
If I do `router.push('/')` before mounting the App component in my spec, everything is great :-). As a testing framework, I would likely make this the default behavior.

**Comment by JessicaSachs** [comment]
I don't think there's anything for vue-router lib to do about this. Perhaps @lmiller1990 and I can have a discussion about the router testing strategy in general.

**Comment by lmiller1990** [comment]
Should the strategy just be to do a `router.push` before the tests run? We could add something into cypress to do this automatically, potentially.

One thing to be aware of for Vue Router 4 is, if you are using a real router to test, you also may need to do `await router.isReady()` before mounting the component. Detailed explanation [here](https://github.com/vuejs/vue-test-utils-next-docs/pull/43/files).

**Comment by JessicaSachs** [comment]
I think so, and yeah that was my though exactly. Within mount we can detect
if there’s a router passed in and call push before we mount the component.

We could also await isReady there too.
