### ISSUE TITLE
Add amazon web service s3 redirect rules in the docs

### ISSUE THREAD

**Issue by lewandy** [vuejs/vue-router#3328]
### What problem does this feature solve?
Hi dudes!,

I am configuring an aws s3 bucket with a vue app using vue router in history mode and the docs does not have the example explaining it, would be great that it appear an example about it.

### What does the proposed API look like?
On bucket configuration in the section "Properties/static web hosting" in the field "Redirection rules"

``` 
<RoutingRules>
  <RoutingRule>
    <Condition>
      <HttpErrorCodeReturnedEquals>404</HttpErrorCodeReturnedEquals>
    </Condition>
    <Redirect>
      <ReplaceKeyWith></ReplaceKeyWith>
    </Redirect>
  </RoutingRule>
</RoutingRules>
```

**Comment by posva** [comment]
Thank you for the proposal, I don't think its sustainable to add anymore configs, they should live outside somewhere
