### ISSUE TITLE
Allow Suppressing (Redirect) Errors in Programmatic Navigation / Navigation Guards

### ISSUE THREAD

**Issue by j0Shi82** [vuejs/vue-router#3329]
### What problem does this feature solve?
On SSR applications there's currently a scenario in which `onReady` is called too early and either the wrong route is rendered, or worse a server error is thrown (depending on your SSR code).

Here's the scenario:

- User navigates to route A
- route A has navigation guards that at some point call next('/routeB') to redirect
- onReady fires (https://github.com/vuejs/vue-router/issues/3225), telling the SSR to render route A, the redirect never completes

This comes with multiple issues. I have not tested it, but since route A is rendered on the server and route B is rendered on the client, you might run into hydration issues. More than that, in case route A does not match any component, the SSR might unnecessarily return an error based on how you handle routes with no matched components.

You can circumvent this issue by using the `router.push` API, but I guess this is not the intended way to navigate within navigation guards?

### What does the proposed API look like?
```js
next({
  path: '/routeB',
  ignoreRedirectErrors: true
});
```

**Comment by posva** [comment]
Can you provide a boiled down reproduction (https://ssr.vuejs.org/ should help) so I can check if this is a problem

**Comment by posva** [comment]
Nevermind, it reproduces by adding a test to https://github.com/vuejs/vue-router/commit/4d484bf81d733769d54091455a4a6e5dbafd62a1#diff-c044368ddb9969465784dfa4ebfa75cd with the path of the current route

**Comment by posva** [comment]
I was actually testing on the wring test and this seems to work on the latest version as the `currentRoute` is valid inside `onReady`. It might be related to some other code you have in your application. If you manage to boil it down, please open a new issue with the reproduction so I can take a look!
