### ISSUE TITLE
How to route into a page directly from browser

### ISSUE THREAD

**Issue by greenpdx** [vuejs/vue-router#3332]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/haoqtnsc/](https://jsfiddle.net/haoqtnsc/)

### Steps to reproduce
I have a verification page after signup. /validate?token=XXXX .  Now I get a 404  as stated in API history-mode server configs. I would like to go to that page directly.  It worked in development using "npm run serve" but not on live site.  /validate is a single static page.

### What is expected?
The API states the that /user/id where id is some value, does not work.  I can understand that. but a single page with no extra route on the end, I think should work.

### What is actually happening?
404

---
Is there a way to jump to a static page in the app?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You need to configure your server to handle the redirection. We have a few examples in the documentation for well known servers

**Comment by greenpdx** [comment]
I looked at the server redirection, but that only redirects to index.html, not the validate page.
