### ISSUE TITLE
路由丢失

### ISSUE THREAD

**Issue by yuhonyon** [vuejs/vue-router#3334]
### Version
3.4.6

### Reproduction link
[https://vux.li/demos/v2/?x-page=github#/component/alert](https://vux.li/demos/v2/?x-page=github#/component/alert)

### Steps to reproduce
A页面 地址是xxx.com#/a  按需加载a.chunk.js
如果a.chunk.js加载失败, vue-router会把地址重置成xxx.com#/
接下来用户刷新网页就会去到错误的页面

真实场景:
打开地址https://vux.li/demos/v2/#/component/alert?x-page=github
断点静态资源108.de037dbd118e6ee543e8.js
刷新页面,地址会变成https://vux.li/demos/v2/#/
取消断点刷新页面 页面跳转到了首页

### What is expected?
资源加载失败 不要修改页面地址

### What is actually happening?
资源加载失败 , hook方式里判断isError(to)===ture 则调用ensureURL修改了页面地址

---
不理解为什么这么设计, 弱网就非常容易导致页面跳转错误或者参数丢失, 多次导致严重的线上故障

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

That's not a valid reproduction, but if you manage to boil down the problem and think it's a bug, open a new issue in English so I can read

**Comment by xuehanyu** [comment]
想问这个问题解决了么？我们最近也遇到这个问题
