### ISSUE TITLE
Wrong component insertion

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [vuejs/vue-router#334]
Hello,

I have a quite deep `vue-router` project and I'm facing a very anoying problem.

Let's suppose I have some components and I'm in the current state:

A -> B -> C -> D

then I transition to A. Do B, C and D are deactivated.

now I want to transition to. A -> B -> C -> E.

I did step by step debugging and this is what happen : 

E is inserted, then C is inserted and then B is inserted. (it seems they are inserted on the same anchor, I don't know why). The component inserted are the good one though.

The problem is B still contain  "C -> D" inside. So when B is inserted (in the last step). and we end up with : 

A -> B -> C -> D

Sadly I was not able to reproduce this bug in a small amount of code but I may have some explanation: 

Do you think it might come from the fact that some component is a fragment instance and has a wrong anchor ?. If it is the case it might come from #332 it seems we are affected. I need to dig a little bit.

**Comment by amirrustam** [comment]
It's really hard to ascertain what is actually happening without seeing code. Please try to provide some.

**Comment by GuillaumeLeclerc** [comment]
I know you would like to have the code but this is a huge beast with more than 50 components. It might take a whole day to shrink it to a reasonable size in order to analyze it. I'm starting now.

**Comment by GuillaumeLeclerc** [comment]
I did some investigation and, the bug was present in two different places in our application.

but the commit 95558dc solved one of them. Can anyone explain what's exactly the purpose of this commit? It might help me solving the second one.

**Comment by GuillaumeLeclerc** [comment]
I found the bug and a hotfix.

[Here](https://github.com/vuejs/vue-router/blob/dev/src/pipeline.js#L167), the cached object is used even if this is not the correct one to display. 

In my example the component D is is cached inside the component C. When I want to display component E, C reuse D, therefore E is never displayed from now we are never able to display any other component than D as a child of C.

A simple, yet very efficient is just to disable keep alive on any `router-view` components. I tried to fix it but I don't know when I can use the cached component or not.

I hope it helps you fixing this.

**Comment by yyx990803** [comment]
Unfortunately I cannot reproduce the issue. This is basically what you described: https://jsfiddle.net/z85cLv7h/ However it seems to be working correctly. Can't really help without an actual repro of the issue :/

**Comment by GuillaumeLeclerc** [comment]
I'm really trying to edit your fiddle to be as close as our code base. I added transitions but still can't reproduce it.

I'll ping you when I have something

**Comment by GuillaumeLeclerc** [comment]
```javascript
 // handle keep-alive.
      // cache the child view on the kept-alive child vm.
      if (view.keepAlive && view.childVM && view.childView) {
        view.childVM._keepAliveRouterView = view.childView;
      }

      // build the new component. this will also create the
      // direct child view of the current one. it will register
      // itself as view.childView.
      component = view.build({
        _meta: {
          $loadingRouteData: loading
        },
        created: function created() {
          this._routerView = view;
        }
      });

      // handle keep-alive.
      // when a kept-alive child vm is restored, we need to
      // add its cached child views into the router's view list,
      // and also properly update current view's child view.
      if (view.keepAlive) {
        component.$loadingRouteData = loading;
        var cachedChildView = component._keepAliveRouterView;
        if (cachedChildView) {
          view.childView = cachedChildView;
          component._keepAliveRouterView = null;
        }
      }
```

As I said the problem comes from `view.childView = cachedChildView;` so I tried to to create a fiddle that execute this line of code (yours don't that's why the bug is not visible). 

It seems strange to me because it looks like it's impossible to reach this line of code. to reach this we need `cachedChildView` to be defined. then `component._keepAliveRouterView` must be defined, therefore  ` view.childView` must be defined, which is only defined on line I'm trying to reach. It looks like circular condition that can't be met.

**Comment by GuillaumeLeclerc** [comment]
I tried with the latest release v0.7.9 and it is still present

**Comment by yyx990803** [comment]
@GuillaumeLeclerc I did find a related bug in the keep-alive handling logic, although not exactly what you've described, but it's most likely related. Can you try building the latest dev and see if it resolves your issue?

**Comment by GuillaumeLeclerc** [comment]
I'm on it

**Comment by GuillaumeLeclerc** [comment]
It works ! thank you.
