### ISSUE TITLE
iOS history mode triggers page refresh

### ISSUE THREAD

**Issue by adamprocter** [vuejs/vue-router#3346]
### Version
2.8.1

### Reproduction link
[http://jsfiddle.net/vehbg57t/](http://jsfiddle.net/vehbg57t/)

### Steps to reproduce
This issue is back. iOS 14.0.1
I managed to stop it happening all the time but no reason I can fathom. Visit on iOS device (iPad / iPhone), must be actual device. https://alpha.nodenogg.in

Tap my lists
Give you self a name (lowercase no spaces)
Tap store
Create a microcosm (lowercase no spaces)
Two Join

Now without creating a node
Tap to another view such as cards
Screen will hit refresh problem. 

Now a workaround seems to be to create a node on that view first. 

Doesnt effect Android or desktop

### What is expected?
Should load page 

### What is actually happening?
Goes black / keep trying to refresh 

---
Looks like this previous issue - https://github.com/vuejs/vue-router/issues/890

**Comment by posva** [comment]
I can reproduce on your website but not on the reproduction you provided. There was a bug introduced recently that seems similar so I released a new patch version. Let me know if that fixes your problem. If not, please, open a new issue **with a boiled down reproduction** so I can actually take a look

**Comment by adamprocter** [comment]
Thanks - Yeah I was trying to get boiler plate to work needed to do some tweaks rushing about and trying to test fiddle on iOS is a nightmare. Will check for patch and update on here.

**Comment by adamprocter** [comment]
I updated and didnt help... am trying to fix the simplified example but at the moment that doesn't break. https://codepen.io/adamprocter/full/QWENKNB  - But I think it has something to do with the reuse of components across views.
