### ISSUE TITLE
Hash模式中location.search和location.hash的位置顺序使用有误

### ISSUE THREAD

**Issue by FIGHTING-TOP** [vuejs/vue-router#3347]
### Version
3.4.7

### Reproduction link
[https://codesandbox.io/s/naughty-sky-vj71h?file=/src/components/HelloWorld.vue](https://codesandbox.io/s/naughty-sky-vj71h?file=/src/components/HelloWorld.vue)

### Steps to reproduce
使用vue-router的Hash模式
使用vm.$route.query获取url中location.search参数在以下情况获取不到，
eg:  http://www.example.com:80/path/to/myfile.html?key1=value1&key2=value2#SomewhereInTheDocument

### What is expected?
应该是：location.search 应该是排在 location.hash 前面时可以用vm.$route.query来获取location.search参数

### What is actually happening?
规范的url中，location.search 应该是排在 location.hash 前面的，但是在实际上，我们使用 vue-router却是在hash排在search之前时才能获取到

---
此外 $router.push() 和 $router.replace() 具有同样的问题

**Comment by posva** [comment]
This is intended because the query is part of the URL sent to the server while the hash isn't. In hash history, othe search has to be included after the hash for vue-router to pick it up
