### ISSUE TITLE
vue-router.esm-bundler.js?6c02:1031 Uncaught Error: Route paths should start with a "/": "**" should be "/**".

### ISSUE THREAD

**Issue by wxwzl** [vuejs/vue-router#3349]
vue-router  4.0.0-beta.13

vue-router.esm-bundler.js?6c02:1031 Uncaught Error: Route paths should start with a "/": "**" should be "/**".

**Comment by posva** [comment]
See https://next.router.vuejs.org/guide/migration/#removed-star-or-catch-all-routes
