### ISSUE TITLE
{ history: false } adding hash to links.

### ISSUE THREAD

**Issue by crswll** [vuejs/vue-router#335]
`history: false` is behaving differently in `0.7.8` than it has in the past.

Here's the setup:

    var router = new VueRouter({
      history: true
    })

    router.map({
        '/': {
            component: Home,
            name: 'home'
        },
        '/about': {
            component: About,
            name: 'about'
        }
    })

The links are being created using `v-link="{ name: 'about' }"`.

The link created in `0.7.8` is **/about#about** (https://jsfiddle.net/x1o95z9u/5/)
The link created in `0.7.7` is **/about** (https://jsfiddle.net/x1o95z9u/6/)

**Comment by GuillaumeLeclerc** [comment]
It seems we are impacted too. Is it the bug you told me about yesterday @aaronjpitts ?

**Comment by azamat-sharapov** [comment]
I also thought this was bug, but later thought it's [feature](https://github.com/vuejs/vue-router/commit/5fbaffe91d91061abe0aa63b060f55e77a1463f2#diff-16238ab3cc86d6b0cea95cfa157dec00R122) :)

**Comment by aaronjpitts** [comment]
I cannot see how this is an improved feature, because now if someone right clicks on the link and opens it in a new tab it doesn't work and the route is incorrect???

**Comment by yyx990803** [comment]
I added this when trying to deal with generating URLs for named paths with missing params, but obviously did it wrong.

fixed via #337 and ad575fca1cd85562e703f71dc4b2ba8bde7f6f26
