### ISSUE TITLE
Error when opening with a encoded hash title

### ISSUE THREAD

**Issue by SCWR** [vuejs/vue-router#3354]
### Version
3.4.7

### Reproduction link
[https://github.com/vuejs/vuepress/issues/2599](https://github.com/vuejs/vuepress/issues/2599)

### Steps to reproduce
The final wrong position is

https://github.com/vuepress/vuepress-plugin-smooth-scroll/blob/master/src/enhanceApp.ts#L16

vuepress-plugin-smooth-scroll

This document is used here.

https://router.vuejs.org/guide/advanced/scroll-behavior.html#async-scrolling

There was no problem before because the to.hash returned by vue-router was call decodeURIComponent.

Since version 3.4.3, the uncoded hash has been returned directly.

### What is expected?
The scroll was successful.

### What is actually happening?
Scrolling failed.

**Comment by posva** [comment]
Please open a new issue once you boil down the reproduction to only vue router to make sure it comes from vue router
