### ISSUE TITLE
Error at new NavigationDuplicated

### ISSUE THREAD

**Issue by xd-luke** [vuejs/vue-router#3359]
### Version
3.4.7

### Reproduction link
[https://stackoverflow.com/questions/57837758/navigationduplicated-navigating-to-current-location-search-is-not-allowed](https://stackoverflow.com/questions/57837758/navigationduplicated-navigating-to-current-location-search-is-not-allowed)

### Steps to reproduce
Navigate to the route you are already on causes an false error. 

### What is expected?
No error message should be displayed for attempting to navigate to the route that the user is already on.  perhaps a warning could be displayed... But, certainly this is not an error, as the nothing wrong has actually happened.  

### What is actually happening?
The system making developers have to deal with errors that aren't actually errors. 

---
Please don't ask developers to add additional code to their programs just to swallow all errors of this type. That's not a good coding experience...

**Comment by posva** [comment]
See https://github.com/vuejs/vue-router/issues/2881
Changing this would be a breaking change and changed on v4
