### ISSUE TITLE
v-link-active is always there when map to '/'

### ISSUE THREAD

**Issue by panteng** [vuejs/vue-router#336]
Hello Evan,
Please see this [jsfiddle][1]. The class 'v-link-active' is always on the menu item 'home'.
The menu item 'home' is mapped to '/'.
Is this a bug or I just did something wrong somewhere else?

[1]:https://jsfiddle.net/Kamato/a1ft1k6a/8/

**Comment by rpkilby** [comment]
@panteng Use the `exact` option on v-link. ex:
```html
<li><a v-link="{ path: '/', exact: true }">Home</a></li>
```

**Comment by panteng** [comment]
@rpkilby oh my word. It seems that I should read the doc more carefully :laughing:. Thanks dude.

**Comment by rpkilby** [comment]
no problem!
