### ISSUE TITLE
Before Hook guard and currentRoute fullPath

### ISSUE THREAD

**Issue by beit46** [vuejs/vue-router#3361]
### Version
3.4.8

### Reproduction link
[https://jsfiddle.net/9oxdastu/](https://jsfiddle.net/9oxdastu/)

### Steps to reproduce
- Implement a beforeEach hook on the router
- On the beforeHook use a next({ name: 'PageNotFound' })
- Call a router.push() and expect that it use the previous line next()
- Using a catch on the router.push that should be redirected, does not updates router.currentRoute.fullPath to match the PageNotFound URL
- After the block execute router.push().then.catch, even if I sleep(500), the router.currentRoute.fullPath is not updated correctly. 
- When I use the afterHook on the router, I Can correctly see my router updated

### What is expected?
I expect the "router.currentRoute.fullPath" to match the route I redirect to in the beforeEach hook next() 

### What is actually happening?
The router.currentRoute.fullPath doesn't get updated, it reflects the endpoint prior to the redirected router.push()

**Comment by LinusBorg** [comment]
The reproduction seems incomplete, it's not runnable. Please fix the reproduction to it shows the actual problem when running it.

**Comment by posva** [comment]
Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions! If you manage to boil down the reproduction open a new issue
