### ISSUE TITLE
createRouter, createWebHistory is undefined

### ISSUE THREAD

**Issue by abhion** [vuejs/vue-router#3364]
### Version
3.3.4

### Reproduction link
[https://codesandbox.io/s/vue-dynamic-components-forked-xij8q](https://codesandbox.io/s/vue-dynamic-components-forked-xij8q)

### Steps to reproduce
import createWebHistory from vue-router

### What is expected?
I am trying to test vue-router. It mentions in this link https://vue-test-utils.vuejs.org/v2/guide/vue-router.html#with-a-real-router the steps to follow

### What is actually happening?
When I run the test I get typeerror: (01,
createWebHistory
), is not a function. I printed createWebHistory and it is undefined

**Comment by LinusBorg** [comment]
Those instructions are for Vue Router 4, currently in RC stage, and Vue 3.

The project you linked to uses VueRouter 3 and Vue 2.

VueRouter 3: router.vuejs.org
VueRouter 4: next.router.vuejs.org

**Comment by abhion** [comment]
@LinusBorg can you please give me a link to read how to test VueRouter3?

**Comment by LinusBorg** [comment]
https://vue-test-utils.vuejs.org/guides/#using-with-vue-router
