### ISSUE TITLE
Conditionally Redirect

### ISSUE THREAD

**Issue by gsccheng** [vuejs/vue-router#3366]
### What problem does this feature solve?
Allow a developer to configure whether or not a redirect happens in the [redirect](https://new-issue.vuejs.org/?repo=vuejs/vue-router) function.

### What does the proposed API look like?
Something to the effect of if `false` is passed, a redirect does not happen. Otherwise redirect to returned path.

```
const router = new VueRouter({
  routes: [
    { path: '/a', redirect: () => {
      if (userIsLoggedIn) {
        return "path/to/somewhere/else";
      }  
      return false;
    }}
  ]
})
```

**Comment by posva** [comment]
Use a navigation guard instead to conditionally redirect
