### ISSUE TITLE
router.back Can't work when the popstate listener is removed

### ISSUE THREAD

**Issue by citrusjunoss** [vuejs/vue-router#3371]
### Version
3.4.9

### Reproduction link
[https://github.com/vuejs/vue-router/issues/2016](https://github.com/vuejs/vue-router/issues/2016)

### Steps to reproduce
It's a strange problem and it's hard to reproduce。

I found that the problem may lie in` hook:destroyed `C through breakpoint debugging

```
    app.$once('hook:destroyed', () => {
      // clean out app from this.apps array once destroyed
      const index = this.apps.indexOf(app)
      if (index > -1) this.apps.splice(index, 1)
      // ensure we still have a main app or null if no apps
      // we do not release the router so it can be reused
      if (this.app === app) this.app = this.apps[0] || null

      if (!this.app) this.history.teardown()
    })
```

` this.app `Is set to null, when the app is destroyed for some reason

### What is expected?
router.back ()  works

### What is actually happening?
the page is normal, just router.back () or router.go (- 1) not working, which is strange

---
The code fragment cannot be provided because it is not required

The secondary routing component uses the `keepAlive`

```
    <transition name="fade" mode="out-in">
      <keep-alive :max="2" :exclude="excludeViews" :include="includeViews">
        <router-view :key="key"></router-view>
      </keep-alive>
    </transition>
```

**Comment by citrusjunoss** [comment]
![image](https://user-images.githubusercontent.com/18432488/98534452-757a9d80-22bf-11eb-84be-8d5f03c687bc.gif)

**Comment by posva** [comment]
`router.back` calls `history.go(-1)`
If your app is destroyed, the router cleans up and no longer listen to popstate changes, this is intended.

Feel free to open a new issue with a boiled down reproduction but don't open issue without reproduction, thank you

**Comment by citrusjunoss** [comment]
> `router.back` calls `history.go(-1)`
> If your app is destroyed, the router cleans up and no longer listen to popstate changes, this is intended.
> 
> Feel free to open a new issue with a boiled down reproduction but don't open issue without reproduction, thank you

However, the program does not have any errors, any function is normal, only router can not work properly

**Comment by cy920820** [comment]
> > `router.back` calls `history.go(-1)`
> > If your app is destroyed, the router cleans up and no longer listen to popstate changes, this is intended.
> > Feel free to open a new issue with a boiled down reproduction but don't open issue without reproduction, thank you
> 
> However, the program does not have any errors, any function is normal, only router can not work properly

What is the final solution? Is there any result?

**Comment by citrusjunoss** [comment]
> > > `router.back` calls `history.go(-1)`
> > > If your app is destroyed, the router cleans up and no longer listen to popstate changes, this is intended.
> > > Feel free to open a new issue with a boiled down reproduction but don't open issue without reproduction, thank you
> > 
> > 
> > However, the program does not have any errors, any function is normal, only router can not work properly
> 
> What is the final solution? Is there any result?


根本原因没有定位到，引发这个问题的原因是登录失效后，跳转login 页面，使用的是router的跳转（猜测是这次跳转引起了监听history事件解绑），导致后续的所有后退事件都不处理了，使用location.href 跳转让应用重新初始化，解决了后退不了的问题。

**Comment by Popxie** [comment]
> > > > `router.back` calls `history.go(-1)`
> > > > If your app is destroyed, the router cleans up and no longer listen to popstate changes, this is intended.
> > > > Feel free to open a new issue with a boiled down reproduction but don't open issue without reproduction, thank you
> > > 
> > > 
> > > However, the program does not have any errors, any function is normal, only router can not work properly
> > 
> > 
> > What is the final solution? Is there any result?
> 
> 根本原因没有定位到，引发这个问题的原因是登录失效后，跳转login 页面，使用的是router的跳转（猜测是这次跳转引起了监听history事件解绑），导致后续的所有后退事件都不处理了，使用location.href 跳转让应用重新初始化，解决了后退不了的问题。

所以现在解决了嘛？ 我这边 经常偶发，一直找不到具体原因，老被提bug

**Comment by 307590317** [comment]
> > > > `router.back` calls `history.go(-1)`
> > > > If your app is destroyed, the router cleans up and no longer listen to popstate changes, this is intended.
> > > > Feel free to open a new issue with a boiled down reproduction but don't open issue without reproduction, thank you
> > > 
> > > 
> > > However, the program does not have any errors, any function is normal, only router can not work properly
> > 
> > 
> > What is the final solution? Is there any result?
> 
> 根本原因没有定位到，引发这个问题的原因是登录失效后，跳转login 页面，使用的是router的跳转（猜测是这次跳转引起了监听history事件解绑），导致后续的所有后退事件都不处理了，使用location.href 跳转让应用重新初始化，解决了后退不了的问题。

我也遇到了这个问题，不过不是你的这种场景，你可以试试在登录失效后不使用router.push来跳转，而是使用router.replace方法来进行跳转，包括退出的时候也是使用replace方法

**Comment by Elias-cug** [comment]
> app.$once('hook:destroyed', () => {
>       // clean out app from this.apps array once destroyed
>       const index = this.apps.indexOf(app)
>       if (index > -1) this.apps.splice(index, 1)
>       // ensure we still have a main app or null if no apps
>       // we do not release the router so it can be reused
>       if (this.app === app) this.app = this.apps[0] || null
> 
>       if (!this.app) this.history.teardown()
>     })

可以看下路由守卫里是不是用了router.push跳转，改成next()跳转，是一种解决方式
