### ISSUE TITLE
Docs: portuguese translation

### ISSUE THREAD

**Issue by nazarepiedady** [vuejs/vue-router#3373]
I have translated the Vue Router documentation to portuguese, but it's 80 percent. Is it possible do a pull request or it's better to complete the translation and finally do a pull request once for all?

**Comment by posva** [comment]
Thanks for working on the translation! Better to do it once it's complete

It's also important to make sure there is an active team to keep the documentation up to date. There is no need for vue-router to host the documentation on all the other languages, we can simply point to your domain
