### ISSUE TITLE
Redirect with query string doest't work and removes query from URL : router.push({ redirect: '/path?query=value' })

### ISSUE THREAD

**Issue by darkylmnx** [vuejs/vue-router#3374]
### Version
3.4.7

### Reproduction link
[https://jsfiddle.net/darkylmnx/yrosh76j/](https://jsfiddle.net/darkylmnx/yrosh76j/)

### Steps to reproduce
- Go to `/a`
- Call `router.push({ redirect: '/b?query=value' })`

### What is expected?
URL to be: /b?query=value

### What is actually happening?
URL is: /b

---
Your question may be, why using a redirect when pushing a location object, the answer is that's what is done in a plugin I use, and I have no hand on the code.
Despite that, it's a weird behaviour that:
- `router.push('/b?query=value' )` works
- and `router.push({ redirect: '/b?query=value' })` doesn't and removes the query from the URL

**Comment by posva** [comment]
`redirect` is supposed to be used in route records, it's not meant to be passed to `push`: https://router.vuejs.org/guide/essentials/redirect-and-alias.html#redirect

**Comment by darkylmnx** [comment]
@posva this may be closed a bit too fast, for 2 reasons:
- if it should be used in the location object with `.push` why is it taken in account then?
- since it's taken in account, the behaviour is inconsistent as said before

Either it should not be taken in account at all or should be taken in account correctly, are am I missing something here?

PS: in the docs AFAIK, there isn't any page fully detailing the **location** object either which makes it hard to even know this redirect option isn't present on it or not.
