### ISSUE TITLE
Router link lose class name

### ISSUE THREAD

**Issue by dxvladislavvolkov** [vuejs/vue-router#3375]
### Version
3.4.9

### Reproduction link
[https://jsfiddle.net/1j4p3ewm/2/](https://jsfiddle.net/1j4p3ewm/2/)

### Steps to reproduce
1. Open a jsfiddle example
2. Click on the second link

Class disappears from the first link

### What is expected?
I have a component where slots are router-links. I need to get an element of router-link and add a class on it (not using binding)
So, I get children on the mounted hook and add class to the element
Styles of the class applied and don't disappear after some actions on a page

### What is actually happening?
Styles of the class applied but after clicking on another link the class disappears

**Comment by posva** [comment]
This is expected behavior in Vue: any manually added class (instead of using `v-bind`) are removed when a component re renders because Vue is not aware of those classes. It's an anti pattern to add classes to elements that are controlled by Vue.
