### ISSUE TITLE
Normalize URL before parse || add beforeParse navigation guard

### ISSUE THREAD

**Issue by olegbaturin** [vuejs/vue-router#3382]
### What problem does this feature solve?
Normilize URL before parse it to Route object.
URLs like "https://example.com//page//" became "https://example.com/page/" or "https://example.com/page" (trailing slash is removed) and run window.location.replace() with normalized URL. Removing repeated/trailing slashes can be optional.
||OR||
Add a beforeParse() navigation guard to allow custom normilization of URLs.

### What does the proposed API look like?
beforeParse(rawUrl: string) {
 return rawUrl.replace(/([^:]\/)\/ /g, "$1");
}

**Comment by posva** [comment]
Use a navigation guard to reformat urls. Trailing slashes can be controlled with the strict option for pathToRegexpOptions

**Comment by olegbaturin** [comment]
Looks like a bug in the /src/util/scroll.js

In the line 20
`const absolutePath = window.location.href.replace(protocolAndPath, '')`
If URL is 'https://example.com//page', absolutePath became '//page'.

Next in 25
`window.history.replaceState(stateCopy, '', absolutePath)`
Here we trying to exec replaceState() with absolutePath='//page'. Resulting URL will be interpreted as 'https://page/'.
And we get an exception: _DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'https://page/' cannot be created in a document with origin 'https://example.com' and URL 'https://example.com//sites'._

This is my case. Its reproduced in development mode. In production mode works as expected - URL will be normilized.

So, we must normilize _absolutePath_ before use it in the window.history.replaceState().

**Comment by JinPengGeng** [comment]
> 
> 
> Looks like a bug in the /src/util/scroll.js
> 
> In the line 20
> `const absolutePath = window.location.href.replace(protocolAndPath, '')`
> If URL is 'https://example.com//page', absolutePath became '//page'.
> 
> Next in 25
> `window.history.replaceState(stateCopy, '', absolutePath)`
> Here we trying to exec replaceState() with absolutePath='//page'. Resulting URL will be interpreted as 'https://page/'.
> And we get an exception: _DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'https://page/' cannot be created in a document with origin 'https://example.com' and URL 'https://example.com//sites'._
> 
> This is my case. Its reproduced in development mode. In production mode works as expected - URL will be normilized.
> 
> So, we must normilize _absolutePath_ before use it in the window.history.replaceState().

@olegbaturin i have the same problem, how can i fix this ??
