### ISSUE TITLE
Custom stringifyQuery/parseQuery overrides the default

### ISSUE THREAD

**Issue by WANZARGEN** [vuejs/vue-router#3383]
### What problem does this feature solve?
In my web application, the format of the search information is very complex. 
And users share search information with uri. 
The search format is the same on any page, so we need to parse the the query in the same way for search data on every page. 
It is the same to make it a query string again. 
So when I tried to create a custom stringifyQuery/parseQuery function for this, there are a lot of things the default function does. 
It's terrible to have to write that logic hassle twice. 

Looking at the internal logic, it seems very easy to let the default function be reused. 
If the default function is reusable, we can put only the logic we need to stringifyQuery or parseQuery function, excluding logic such as encoding or decoding it. 
I think there will be many developers who use it usefully compared to the effort that goes into it.

### routerOptions must be changed as follow: 

```typescript
export interface RouterOptions {
  ...
  parseQuery?: (query: string, defaultFunction: (query: string) => Object) => Object
  stringifyQuery?: (query: Object, defaultFunction: (query: Object) => string) => string
  ...
}
```

### getFullPath in vue-router.js must be changed as follow:

```javascript
function getFullPath (
    ref,
    _stringifyQuery
  ) {
    var path = ref.path;
    var query = ref.query; if ( query === void 0 ) query = {};
    var hash = ref.hash; if ( hash === void 0 ) hash = '';

    return _stringifyQuery ? (path || '/') +  _stringifyQuery(query, stringifyQuery) +  hash :  (path || '/') +  stringifyQuery(query) +  hash
  }
```

### resolveQuery in vue-router.js must be changed as follow:

```javascript
function resolveQuery (
    query,
    extraQuery,
    _parseQuery
  ) {
    if ( extraQuery === void 0 ) extraQuery = {};

    var parsedQuery;
    try {
      parsedQuery = _parseQuery ? _parseQuery(query || ''), parseQuery) : parseQuery(query || '');
    } catch (e) {
       warn(false, e.message);
      parsedQuery = {};
    }
    for (var key in extraQuery) {
      var value = extraQuery[key];
      parsedQuery[key] = Array.isArray(value)
        ? value.map(castQueryParamValue)
        : castQueryParamValue(value);
    }
    return parsedQuery
  }
```

**Comment by posva** [comment]
Our internal version of stringily and parse query will be kept internal but you are free to copy them and adapt them. In v4 you can import them (because of named imports) but they are internal too and should not be used

**Comment by wparad** [comment]
Just because you can use `vue-router` to convert to/from a query/string, doesn't mean you should. As a matter of fact these should be different things. For instance you are much better off using `querystring` package for converting back and forth. And further, it's just a coincidence that you can use the ones in `vue-router` to do this. For us we can't because we have our own convention on passing this data around. Specifically we base64url the data so a nice string, as well as add error checking to it. Neither of these things are vue related. Grab a standard library specifically to do this and don't rely on how the router treats these values.
