### ISSUE TITLE
Destroyed hook not called.

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [vuejs/vue-router#339]
Hello,

I have a component (fragment) and the beforeDestroy hook is called but not the destroyed one. Is it normal or is it a bug ?

Here is a repro: http://jsfiddle.net/xyu276sa/208/

I look at the source code and it seems [this part of the code](https://github.com/vuejs/vue-router/blob/5fbaffe91d91061abe0aa63b060f55e77a1463f2/src/override.js#L34) has not been updated for vue 1.0. (it works fine with vue 0.12)
 
Thank you

**Comment by smartpierre** [comment]
I got the same problem here, can someone check on this ?

**Comment by yyx990803** [comment]
Ran the repro but it seems to be working: http://jsfiddle.net/xyu276sa/217/

**Comment by GuillaumeLeclerc** [comment]
Did you checked/unchecked  the checkbox multiple times while looking at the console ?. On my computed I only see 'bb' on the console instead of 'bb' (beforeDestroy) and then 'dd' (destroyed).

@smartpierre Can you check my repro and see if it is working on your computer. 

@yyx990803 What browser are you running, If you don't see the problem must be browser related.

**Comment by yyx990803** [comment]
@GuillaumeLeclerc I did check the checkbox and tested in Chrome, Firefox and Safari, all working as intended.

**Comment by GuillaumeLeclerc** [comment]
![bug vue](https://cloud.githubusercontent.com/assets/2017051/12454142/83e3c9fa-bf96-11e5-820a-82d43cbb6c7e.png)

This is what I get when i run the jsfiddle.

I'll try on chrome

**Comment by smartpierre** [comment]
I have the same thing as @GuillaumeLeclerc , it never shows 'dd'

**Comment by GuillaumeLeclerc** [comment]
I thought my computer was going crazy. I'm glad I'm not alone having this strange problem.

**Comment by GuillaumeLeclerc** [comment]
I had the chance to test it on a Windows 7. (IE 11 and Firefox 43) and I get the exact same result. I really don't understand how you can get a different result.

I think the bug comes from the differences in the moment when `_isBeingDestroyed` is set to true.

In vue 1. _isBeingDestroyed is set [here](https://github.com/vuejs/vue/blob/bbf5e59ca625b50da5e7627bef51e6b7ff459b0b/src/instance/internal/lifecycle.js#L183), i.e. before the call to `_destroye`

In vue 0.12 as far as I remember _isBeingDestroyed is set in the _destroy method itself. (I can't point out where it is I'm on my phone and I can't search on github for other branches than master (it seems).

If you can tell me how I can tell which version of vue it is I should be able to make a fix and unit tests for this.

**Comment by yyx990803** [comment]
Hmm this is indeed weird. I ran the repro in IE11 & Chrome on Windows 8.1, and IE9 on Windows 7, they are all calling it correctly. Is your Vue version a bit behind? Are you using the latest 1.0.15?

**Comment by GuillaumeLeclerc** [comment]
I'm using the one in the jsfiddle. Are you running the js fiddle as is ?

**Comment by yyx990803** [comment]
Yes. I'm using this one though because your original one is not working due to rawgithub issues: http://jsfiddle.net/xyu276sa/217/

**Comment by smartpierre** [comment]
I tried this one http://jsfiddle.net/xyu276sa/217/ on : 

Firefox 43.0.4
Chromium 47.0.2526.73 Ubuntu 14.04 (64-bit)
Chrome Version 47.0.2526.111 (64-bit)

And it only shows 'bb' in the console.

I'm on Ubuntu 14.04

This is actually mind-blowing that on the same jsfiddle we have different results...

**Comment by GuillaumeLeclerc** [comment]
Same here but on archlinux windows 7 and Ubuntu 14.04. I tested ie 11, chrome and Firefox

**Comment by Gomah** [comment]
Same here, it's very weird.

If you click on "Go to Foo", check the checkbox & uncheck it, only the 'beforeDestroy' hook is called. ('bb)
But if you check the checkbox & click on "Go to Bar", 'beforeDestroy' & 'destroyed' hooks are called.

**Comment by yyx990803** [comment]
@Gomah Ohhhh I think I may have misunderstood what @GuillaumeLeclerc described. Toggling the checkbox does reproduces the issue. Looking into this.

**Comment by GuillaumeLeclerc** [comment]
I thought this was clear enough : `Did you checked/unchecked the checkbox multiple times while looking at the console ?` but I'm sorry you couldn't understand me, I'm not a native speaker.

**Comment by GuillaumeLeclerc** [comment]
Thank you !
