### ISSUE TITLE
Navigation Resolution Flow - AfterRouteLeave

### ISSUE THREAD

**Issue by lgmf-daitan** [vuejs/vue-router#3398]
### What problem does this feature solve?
I have a Vue mixin that is used to register/unregister Vuex's store modules that is intimately connected to the navigation flow.

```javascript

import store from '@/store';

export default ({ modulePath, module }) => ({
  beforeRouteEnter(to, from, next) {
    if (!store.hasModule(modulePath)) {
      store.registerModule(modulePath, module);
    }
    next();
  },
  beforeRouteLeave(to, from, next) {
    if (store.hasModule(modulePath)) {
      store.unregisterModule(modulePath);
    }
    next();
  },
});
```

I need to do that because we have a HUGE app and I want to decrease the size of our Store is in memory, its the same purpose as lazy loading components

The problem is that the "beforeRouteLeave" is being executed before the "beforeDestroy" lifecycle and because of that I'm facing a memory leak problem because in a particular case we use a WebSocket connect that was supposed to be disconnected when the page component was about to be destroyed.

### What does the proposed API look like?
My suggestion would be to add another navigation lifecycle that would guarantee that the component was already destroyed.
Add a navigation guard that would guarantee that the activated component was already destroyed.

```javascript
const Foo = {
  template: `...`,
  beforeRouteEnter (to, from, next) {
    // called before the route that renders this component is confirmed.
    // does NOT have access to `this` component instance,
    // because it has not been created yet when this guard is called!
  },
  beforeRouteUpdate (to, from, next) {
    // called when the route that renders this component has changed.
    // This component being reused (by using an explicit `key`) in the new route or not doesn't change anything.
    // For example, for a route with dynamic params `/foo/:id`, when we
    // navigate between `/foo/1` and `/foo/2`, the same `Foo` component instance
    // will be reused (unless you provided a `key` to `<router-view>`), and this hook will be called when that happens.
    // has access to `this` component instance.
  },
  beforeRouteLeave (to, from, next) {
    // called when the route that renders this component is about to
    // be navigated away from.
    // has access to `this` component instance.
  },
  afterRouteLeave(to, from, next) {
    // called after the destroy the route activated component 
  }
}
```

**Comment by lgmf-daitan** [comment]
I created a callback function called `beforeUnregister`

```javascript
// mixin builder file

export default ({ modulePath, module, beforeUnregister = () => Promise.resolve() }) => ({
  beforeRouteEnter(to, from, next) {
    if (!store.hasModule(modulePath)) {
      store.registerModule(modulePath, module);
    }
    next();
  },
  async beforeRouteLeave(to, from, next) {
    if (store.hasModule(modulePath)) {
      await beforeUnregister(store);
      store.unregisterModule(modulePath);
    }
    next();
  },
});

```

and then I'm using like this

```javascript
// page-component.js

import SomeModule from './store';

const storeModuleRegistrationMixin = storeModuleRegistrationMixinBuilder({
  modulePath,
  module: SomeModule,
  async beforeUnregister(store) {
    await store.dispatch('some-namespace/disconnect-webscoket');
  },
});

export default {
  mixins: [storeModuleRegistrationMixin]
}
```

This has solved my problem, but I still believe that this feature request would be interesting

**Comment by posva** [comment]
The best for this kind of scenario is to add a [meta property](https://router.vuejs.org/guide/advanced/meta.html) to routes to list the store modules they depend on. Then add a `beforeEach` and `afterEach` (global navigation guards) to register and unregister them.
In your case, it might be even simpler to add that handling to the `destroyed` component hook instead of coupling it with the navigation

**Comment by lgmf-daitan** [comment]
Thank you @posva!
