### ISSUE TITLE
Replace true on main router node

### ISSUE THREAD

**Issue by swannknani** [vuejs/vue-router#34]
Hi,

Just figured out after 3 hours of headache that having the ```<router-view></router-view>``` inside the application template and this application setup with the option ```replace``` set to ```true```(which is the default behaviour now) leads to child components not working properly (only ```created``` hook is called).
So maybe think to add this warning into your upcoming documentation.

Cheers

**Comment by yyx990803** [comment]
Is it because your main template is simply `<router-view></router-view`? If so that will be fixed with Vue core's next release.

**Comment by yyx990803** [comment]
Should now work properly in 0.12.5
