### ISSUE TITLE
A callback to next() of beforeRouteEnter executed before mounted()

### ISSUE THREAD

**Issue by huajianreno** [vuejs/vue-router#3402]
### Version
3.4.6

### Reproduction link
no reproduction link
must compile more than once

### Steps to reproduce
1. have beforeRouteEnter and mounted hooks in a component
2. have next() with callback in beforeRouteEnter
3. use different version of vue-router before(3.4.5 or other) and after 3.4.6

### What is expected?
the order of the executions of callback in next() of beforeRouteEnter and mounted are same in different version of view-router

### What is actually happening?
the order of the executions of callback in next() of beforeRouteEnter and mounted are different in different version of view-router

**Comment by posva** [comment]
Please read https://new-issue.vuejs.org/?repo=vuejs/vue-router-next#why-repro

the callback passed to next is always executed ~~after mounted~~ after one render but there is no guarantee between component lifecycle and navigation guards as they are not correlated and completely dependant on the features you use, meaning that if you rely on them in one scenario, your code could break if you add another feature like a keep-alive or transition.

For reference: https://router.vuejs.org/guide/advanced/navigation-guards.html#the-full-navigation-resolution-flow

**Comment by huajianreno** [comment]
> https://new-issue.vuejs.org/?repo=vuejs/vue-router-next#why-repro
> 
> the callback passed to next is always executed after mounted: https://router.vuejs.org/guide/advanced/navigation-guards.html#the-full-navigation-resolution-flow

I know, maybe it's more clearly in this way:
In version 3.4.6+, the callback passed to next is executed before mounted.

**Comment by MaciejJanyska** [comment]
I can confirm this behavior as @huajianreno described.
