### ISSUE TITLE
The callback passed to next is executed before mounted

### ISSUE THREAD

**Issue by huajianreno** [vuejs/vue-router#3403]
### Version
3.4.6

### Reproduction link
no link

### Steps to reproduce
1. have beforeRouteEnter and mounted hooks in a component
2. have next() with callback in beforeRouteEnter
3. use different version of vue-router before(3.4.5 or other) and after 3.4.6

### What is expected?
The callback passed to next in beforeRouteEnter is executed after mounted.

### What is actually happening?
The callback passed to next in beforeRouteEnter is executed before mounted.

**Comment by posva** [comment]
Please read the link about reproductions I sent you. Don't open issues without a reproduction
