### ISSUE TITLE
exports is not defined

### ISSUE THREAD

**Issue by ivanushkaPr** [vuejs/vue-router#3404]
### Version
4.0.0-0

### Reproduction link
[https://codesandbox.io/s/vue-router-nodod?file=/src/App.vue](https://codesandbox.io/s/vue-router-nodod?file=/src/App.vue)

### Steps to reproduce
I have this file structure and files on my local computer - https://codesandbox.io/s/vue-router-nodod?file=/src/App.vue
Unfortunately, this files work only in codesanbox. If start dev build via npm run serve on local computer, i get a following error in browser console:

Uncaught ReferenceError: exports is not defined
    at Module.eval (vue-router.esm-bundler.js?6c02:2306)
    at eval (vue-router.esm-bundler.js:3375)
    at Module../node_modules/vue-router/dist/vue-router.esm-bundler.js (chunk-vendors.js:1247)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at eval (main.js:11)
    at Module../src/main.js (app.js:1513)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at Object.1 (app.js:1526)

### What is expected?
expecting the program to run correctly

### What is actually happening?
vue router doesnt work correctly

---
Can it be because i have old version of webpack or typescript installed globally on local machine? 
If yes, why vue cli working correctly, but not vue-router.
This is my repository with all the files https://github.com/ivanushkaPr/vueRouting

**Comment by posva** [comment]
fixed in 4.0.1

**Comment by ivanushkaPr** [comment]
Thank you very much, switching to 4.0.1 resolved the problem)

**Comment by lujialiu844-cyber** [comment]
> fixed in 4.0.1

thank you very very very very much!!!!!!
