### ISSUE TITLE
Feature Proposal: export onError hook

### ISSUE THREAD

**Issue by lepture** [vuejs/vue-router#341]
Export an `onError` hook in transition, so that we can send errors in promise to sentry.

**Comment by yyx990803** [comment]
Where do you expect to use this hook? Sounds like it would be more useful if it's global?

**Comment by lepture** [comment]
@yyx990803 Yeah. It should be global.

**Comment by kxxoling** [comment]
How this works now?

**Comment by lepture** [comment]
Close via https://github.com/vuejs/vue-router/pull/393
