### ISSUE TITLE
chrome-headless(chromeDriver) mode，Abnormal performance

### ISSUE THREAD

**Issue by dingshaohua-com** [vuejs/vue-router#3415]
### Version
3.2.0

### Reproduction link
[https://router.vuejs.org/zh/](https://router.vuejs.org/zh/)

### Steps to reproduce
无头浏览器模式下，官方demo的history模式路由，会被重定向，并且自动添加“#”
In chrome-headless(chromeDriver) mode, 
the history mode route of the official demo-- will be redirected, --and the "#" will be automatically added
![history-model](https://user-images.githubusercontent.com/18003391/102161354-25948500-3ec2-11eb-9280-c6fcef7c152f.gif)

### What is expected?
normal using

### What is actually happening?
 will be redirected, --and the "#" will be automatically added

**Comment by posva** [comment]
Use the history mode if you don't want the hash. Otherwise this is expected

**Comment by dingshaohua-com** [comment]
> Use the history mode if you don't want the hash. Otherwise this is expected

i  am used history ,but not ok. plese look detail-  using in  chromeheadless！normal using is ok
