### ISSUE TITLE
IE9 compatibility with history mode

### ISSUE THREAD

**Issue by tikiatua** [vuejs/vue-router#342]
Hi there,

Just recently we deployed an online training course using vue and vue-router for the frontend code and just loved how simple it is to put even a complex interface together. So - a big thank to everyone involved with these projects.

We did however run into an issue with internet explorer 9 and html5 history mode. 

When using html5 history mode – i.e. new Router({history:true}) – the hash does not appear in the url and thus the server has to be configured to support deep linking. 
I.e. if your domain is _www.vueisawesome.org_ the link to the route _/login_ would be _www.vueisawesome.org/login_

In IE9, however, html5 history mode is not supported and hashes still need to be placed inside the url. 
I.e. the link to the route would be _www.vueisawesome.org/#!/login

This works perfectly fine, if the users selects a link on the page that has been generated by v-link. However, if the user is accessing the link without hash directly (www.vueisawesome.org/login) and the server is automatically serving the base page template, the router will not recognize www.vueisawesome.org/login as the login-route.

So if html5 history mode is turned on and the browser is IE9, it would be great, if vue-router could check if the url would match one of its routes and load the corresponding view accordingly.

Thanks for considering. I will try to take a look at the vue-router code myself and see if I can find a way to implement this.

**Comment by tikiatua** [comment]
P.S. we are currently checking if the browser is IE9 on the server and inject the hashes into the url on the server side. It would however be nice, if it would work correctly without the need of a server-fix.

**Comment by yyx990803** [comment]
Yes, this should be handled by the router. It seems what we need to do is recognize we are in IE9 fallback mode and interpret the initial path as hash instead.

**Comment by tikiatua** [comment]
Awesome. Many thanks. Will test it first thing tomorrow..

**Comment by zhancheng** [comment]
@tikiatua  did new version solve your problem， i find it useless for me by the new version，still not work well.

**Comment by tikiatua** [comment]
Hmm.. We actually went with the server fallback for now. I did however quickly test it in january and it seemed to work fine at the time.
