### ISSUE TITLE
When the scroll bar appears in the first page, the window scroll event is automatically triggered after the route jump. vue 3.0

### ISSUE THREAD

**Issue by wall-git** [vuejs/vue-router#3424]
### Version
3.4.9

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
When the scroll bar appears in the first page, the window scroll event is automatically triggered after the route jump.
first:（This problem occurs only when the scroll bar appears on the first page）----------
~~~vue
<template>
  <img src="../assets/images/jzsq.png" @click="topage({ url: 'ClassSign' })" />
</template>

<script lang="ts">
import router from '@/router';
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'Home',
  components: {},
  setup() {
    const topage = (params: any) => {
      router.push({
        path: params.url
      });
    }
    return {
      topage
    };
  }
});
</script>
<style lang="scss" scoped>
</style>

~~~
~~~vue
push page-------------

<template></template>

<script lang="ts">
import { defineComponent, onMounted, reactive, ref } from 'vue';
export default defineComponent({
  name: 'ClassSign',
  components: {},
  setup() {
    window.addEventListener(
      'scroll',
      function () {
        console.log('why do this ???');
      },
      { capture: false, passive: false }
    );
    return {};
  }
});
</script>

<style lang="scss" scoped>
</style>
~~~
router
~~~ts--------------
const routes: Array<RouteRecordRaw> = [
  {
    path: '/home',
    name: 'Home',
    component: Home
  },
  {
    path: '/ClassSign',
    name: 'ClassSign',
    component: () => import('@/views/ClassSign.vue')
  }
];
const router = createRouter({
  history: createWebHistory(process.env.VUE_APP_BASE_DIR),
  routes 
});

~~~

### What is expected?
don't call the scroll event

### What is actually happening?
When the scroll bar appears in the first page, the window scroll event is automatically triggered after the route jump.vue 3.0

**Comment by posva** [comment]
Read and follow https://new-issue.vuejs.org/?repo=vuejs/vue-router-next#why-repro (also the right repository) when opening issues.
The router will keep the scroll if reloading a page, that's intended to mimic native behavior

**Comment by wall-git** [comment]
> Read and follow https://new-issue.vuejs.org/?repo=vuejs/vue-router-next#why-repro (also the right repository) when opening issues.
> The router will keep the scroll if reloading a page, that's intended to mimic native behavior

thanks , but How  stop that?Because some components need to listen for this event, This will cause a misunderstanding on the first call

^_^

**Comment by posva** [comment]
Checking the `from` is equal to https://next.router.vuejs.org/api/#start-location to know if it's the initial navigation should do. 
Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
