### ISSUE TITLE
iOS safari causing browser to refresh and fails to load

### ISSUE THREAD

**Issue by adamprocter** [vuejs/vue-router#3428]
### Version
3.4.9

### Reproduction link
[https://alpha.nodenogg.in](https://alpha.nodenogg.in)

### Steps to reproduce
This issue has come back to me this week and only happens on the real devices, I had managed to a work around I believe before however this may have just been a fluke and perhaps an updated vuex actually fixed something not sure if vuex had updated again between my last testing. Trying to use mobile safari plugged into mac to debug.

visit https://alpha.nodenogg.in - type in a device name and then a microcosm name on iOS device, page will then get stuck refreshing and crash, no issues on android or desktop browsers

### What is expected?
page should load the correct data

### What is actually happening?
page just refreshes until it crashes

**Comment by posva** [comment]
I can't check without a boiled down reproduction like said in https://github.com/vuejs/vue-router/issues/3346#issuecomment-709920365

About reproductions: https://new-issue.vuejs.org/?repo=vuejs/vue-router#why-repro
