### ISSUE TITLE
ForceUpdate or forceRerender cause iOS to page refresh with History mode

### ISSUE THREAD

**Issue by adamprocter** [vuejs/vue-router#3431]
### Version
3.4.9

### Reproduction link
[https://alpha.nodenogg.in](https://alpha.nodenogg.in)

### Steps to reproduce
I think have tracked the issue down as to when you use ForceUpdate or force rerendner to get updated data then the page will keep refreshing on iOS and fail with the error a problem repeatably occured. Will try to make a better MVP

### What is expected?
Page should load with updated data

### What is actually happening?
page crashed on iOS

**Comment by posva** [comment]
Read what I said: https://github.com/vuejs/vue-router/issues/3428#issuecomment-750921139
This is the last notice, if you don't respect the issue-reporting guidelines, we will have to block you

**Comment by adamprocter** [comment]
I was hoping to try and put together a codepen but was struggling. It’s unlikely I’ll find the time / approach to do one so hopefully I’ll work around this issue. 

Apologies I have just caught your other comment I don’t think I justify being blocked at all. I raised two related issues and was hoping to update with a boiler plate ASAP but clearly this will not be looked at until I do.  

If I manage to reproduce and have time to isolate this issue in a separate location I’ll raise a issue then. 

Thanks
Adam
