### ISSUE TITLE
Cannot access router query from App.vue on mounted when route is lazy loaded

### ISSUE THREAD

**Issue by AustinGil** [vuejs/vue-router#3439]
### Version
3.4.9

### Reproduction link
[https://codesandbox.io/s/jolly-monad-ou69k?file=/src/App.vue](https://codesandbox.io/s/jolly-monad-ou69k?file=/src/App.vue)

### Steps to reproduce
* Create a Vue project with vue-router
* Add a console.log to App.vue that reads query params on created/mounted
* Create a lazy loaded route (lets say /example)
* Go to that lazy loaded route and add query params to URL (/example?q=1)
* Refresh browser

When the App.vue component loads on the lazy route (/example), the console.log returns an empty object even if there are query params. If the router view component is not lazy loaded, the console.log in App.vue will show the query params as expected.

Minimal example:
https://codesandbox.io/s/jolly-monad-ou69k?file=/src/App.vue

### What is expected?
I expect App.vue to have access to the query params on mounted

### What is actually happening?
The query params object is empty when App.vue mounts.

**Comment by posva** [comment]
This is expected because the navigation is asynchronous. You have to wait for `onReady` https://router.vuejs.org/api/#router-onready

**Comment by AustinGil** [comment]
Thanks @posva. I wasn't even sure this was a bug or working correctly. Glad it's not a bug, and thanks for the info :)

**Comment by doing-cr7** [comment]
i also appear this questions ,when ctrl+r currnt page ,my $route.query on monuted  not work, so i can close current page ,repeat a new page ,$route.auery become good; 
so i want it what's happen?

**Comment by zaptree** [comment]
For anyone else coming from an online search. If you need to wait for the routes to be ready use `$router.isReady()` like this:

```javascript
  import { onMounted } from 'vue';
  import { useRoute, useRouter } from 'vue-router';

  const $route = useRoute();
  const $router = useRouter();

  onMounted(async () => {
    await $router.isReady();
    const query = $route.query;
  });
```
