### ISSUE TITLE
addRoutes 的使用请教

### ISSUE THREAD

**Issue by furylee** [vuejs/vue-router#3441]
### Version
3.4.9

### Reproduction link
[https://new-issue.vuejs.org/?repo=vuejs/vue-router](https://new-issue.vuejs.org/?repo=vuejs/vue-router)

### Steps to reproduce
```
   router.addRoutes([{
    path: '/',
    name: 'index',
    component: BasicLayout,
    meta: { title: '首页' },
    redirect: '/home',
    children: [
      {
        path: '/home',
        name: 'home',
        meta: { title: '欢迎' },
        hidden: true,
        component: () => import('@/views/home')
      },
     {
  meta: {
    title: '404',
  },
  name: '404',
  hidden: true,
  path: '/404',
  component: constantRouterComponents['404'],
},
...
]}])
```

async addRoutes success,push('/'),to 404, why???

addRoutes成功后,跳转根目录重定向到404,为什么?能解答下吗,还是不能搞根目录的路由?

### What is expected?
to home
去首页

### What is actually happening?
redirect 404
重定向到了404

**Comment by posva** [comment]
Read https://new-issue.vuejs.org/?repo=vuejs/vue-router#why-repro. Also open issues in English, thanks!
