### ISSUE TITLE
The data in positionStore is never cleared

### ISSUE THREAD

**Issue by hezedu** [vuejs/vue-router#3444]
### Version
3.4.9

### Reproduction link
[https://github.com/vuejs/vue-router/blob/6d030f5c54dbb482d22a147b5a154f082b71e0a0/dist/vue-router.js#L1810](https://github.com/vuejs/vue-router/blob/6d030f5c54dbb482d22a147b5a154f082b71e0a0/dist/vue-router.js#L1810)

### Steps to reproduce
I read the source code and found that positionStore has only set, not deleted.

### What is expected?
The data in positionStore should be cleared on history.back().

### What is actually happening?
The memory haspmap:positionStore will continue to grow.

**Comment by posva** [comment]
This is client only. If you found a bug please provide a repro: https://new-issue.vuejs.org/?repo=vuejs/vue#why-repro
