### ISSUE TITLE
Call this.$route.path causes this.$route to get undefined.

### ISSUE THREAD

**Issue by phlegx** [vuejs/vue-router#3450]
### Version
3.4.9

### Reproduction link
no reproduction link.

### Steps to reproduce
I have the following method in a child component:

```
export default {
  name: 'my-child-comp',
  methods: {
    checkPath() {
      console.log(this.$route)
      return true //this.$route.path === '/test'
    },
  },
}
```

If I output `console.log(this.$route)` in `checkPath` method, the object is present with all route data. If I output `console.log(this.$route.path)` I get the error `TypeError: Cannot read property 'path' of undefined`

### What is expected?
Access `this.$route.path` should return the current route path.

### What is actually happening?
Access `path` from `this.$route` object, clears `this.$route` object to undefined.

**Comment by posva** [comment]
Please read https://new-issue.vuejs.org/?repo=vuejs/vue#why-repro and open a new bug report if you manage to boil it down
