### ISSUE TITLE
vue router doesn't scroll to top

### ISSUE THREAD

**Issue by Manubi** [vuejs/vue-router#3451]
Hi,
If I am correct, the following code should make the router to scroll to the top on every component change - right?

```
const router = new VueRouter({
  mode: 'history',
  base: process.env.BASE_URL,
  routes,
  scrollBehavior: (to, from, savedPosition) => {
    return { x: 0, y: 0 }
  }
})
```
But unfortunately it still keeps the same scroll position if I change the component. It's not scrolling to 0,0.

Thanks!

**Comment by megasanjay** [comment]
Can I just say that I was having this issue with regards to the Vue router not scrolling to the top. I managed to solve this by using `window.scrollTo(0, 0);` instead of `return { x: 0, y: 0 };`
Weird behavior but this comment might help someone else in the future (since this was the first link I got on Google). 

My final function was: 
```javascript
scrollBehavior: function (to, _from, savedPosition) {
    if (savedPosition) {
      return savedPosition;
    }
    if (to.hash) {
      return { el: to.hash, behavior: "smooth" };
    } else {
      console.log("moving to top of the page");
      window.scrollTo(0, 0);
    }
 }
```

**Comment by andreyrd** [comment]
scrollBehavior seems to just do absolutely nothing when you use it like the documentation specifies, and you can see reports of it all over the internet

**Comment by megasanjay** [comment]
It works for me. What issue are you having?

**Comment by nolros** [comment]
First, thanks a million for an awesome product!  I know you guys sacrifice a huge amount of time to build and maintain these code bases. Seriously, thank you.  

I've run into a similar problem and have managed to come up with a workaround (below), but although I can replicate the problem I cannot identify the source issue. 


**Clients Website (production)**
https://guttersandlights.com

**Router Version**
 "vue-router": "^4.0.8",

**Vue Version**
"vue": "^3.0.5"

**Dev Platform:**
Pure Laravel 8 backend and vue 3 frontend using Webpack and "@babel/core": "^7.15.8"

**Server Platform**
Recently provisioned AWS Ubuntu 2CPU hvm Server 
Cloudflare caching

**Steps to reproduce**
Replace the `window.scrollTo({top: 0, left: 0, behavior: 'smooth'})` in _routes/index.js_ below with recommended `return { x: 0, y: 0 } `or `return { left: 0, top: 0 }` and it will **not** scroll to top of page

**What is expected?**
When routing to a new page and DOM load is complete that it will scroll to the top of the page if not saved position or hash 

**What is actually happening?**
It will not scroll to the top or make any attempt. It acts as if saved position

**Other Steps taken:**

1. 1000ms delay using setTimeout to ensure DOM is fully loaded
2. setInternal (per example) to ensure DOM is loaded
3. window.addEventListener('DOMContentLoaded', (event) … with delay
4. I have a throttled scroll directive for header navigation (code below) but removing all directives made no difference

**NOTES:**
The site loads in around 1 second with 100% Google page speed score so it is not a performance issue

**app.js**

```
         import { createApp, h } from 'vue';
	import router from './router'
	import VueSocialSharing from 'vue-social-sharing'
	import DefaultLayout from 'layout@/DefaultLayout.vue'
	import Page404 from "pages@/Page404";

	require('./config/bootstrap');

	createApp({
	    render: () =>
	        h(DefaultLayout),
	    })
	    .use(router)
	    .use(VueSocialSharing)
	    .component(Page404, {})
	    .mount('#app');

```

**DefaultLayout.vue**

```
       <template>
	    <AppHeader/>
	    <div class="fbox-rel-col w-full center top mx-auto z-10">
	        <router-view :key="$route.params.slug || 'default'" v-slot="{ Component, route }">
	                <component :is="Component"/>
	        </router-view>
	    </div>
	    <FooterSection/>
	</template>

	<script>
	import FooterSection from "components@/footers/FooterSection";
	import AppHeader from "components@/headers/AppHeader";


	export default {
	    name: 'DefaultLayout',
	    components: {
	        AppHeader,
	        FooterSection
	    },
	}

```

**routes/index.js**

Note: 

1. I have used setInterval only to ensure the DOM loaded completely and as mentioned attempted a number of other tests. I also tested with DOMLoad event, but outcome was the same. I don't see anything that leads me to believe it is a DOM related issue
2. As mentioned above, this is the only solution that seems to work, replacing `window.scrollTo({top: 0, left: 0, behavior: 'smooth'});` with vue router options found in the documentation doesn't.  


```
         import { createRouter, createWebHistory } from 'vue-router'
	import { routes } from './routes'

	const timer = 100, threshold = 2000, _STATE = "complete";
	let interval = null;

	const router = createRouter({
	    linkActiveClass: 'is-active',
	    history: createWebHistory(),
	    routes,
	    scrollBehavior(to, from, savedPosition) {
	        if (to.hash) {
	            return {el: to.hash, behavior: "smooth"};
	        } else if (savedPosition) {
	            return savedPosition;
	        } else {
	            const isLoaded = () => (document.readyState === _STATE) && clearInterval(interval);
	            const scrollTo = () => window.scrollTo({top: 0, left: 0, behavior: 'smooth'});

	            interval = setInterval(() => hasLoaded() && scrollTo(), timer);
	        }
	    }
	})
	export default router

```

routes/routes.js (very basic async loads)


```
     
import {DOMAIN_TITLE} from '../.env'

	export const routes = [
	    {
	        path: "/",
	        name: "home",
	        component: () => import(/* webpackChunkName: "homePage" */ "pages@/HomePage"),
	        meta: {title: `${DOMAIN_TITLE} | home`}
	    },
	    {
	        path: '/services/gutters',
	        name: 'gutterServices',
	        slug: 'lighting-services',
	        component: () => import(/* webpackChunkName: "guttersPage" */ "pages@/GutterServices"),
	        meta: {title: `${DOMAIN_TITLE} | Gutter Services`}
	    },
	    {
	        path: '/services/lighting',
	        name: 'lightingServices',
	        slug: 'lighting-services',
	        component: () => import(/* webpackChunkName: "lightingPage" */ "pages@/LightingServices"),
	        meta: {title: `${DOMAIN_TITLE} | Lighting Gutter Services`}
	    },
	    {
	        path: '/about',
	        name: 'about',
	        slug: 'about',
	        component: () => import(/* webpackChunkName: "aboutPage" */ "pages@/AboutPage"),
	        meta: {title: `${DOMAIN_TITLE} | about`}
	    },
	    {
	        path: '/blog',
	        name: 'blog',
	        slug: 'blog',
	        component: () => import(/* webpackChunkName: "blogPage" */ "pages@/BlogPage"),
	        meta: {title: `${DOMAIN_TITLE} | blog`}
	    },

          // removed the rest for brevity sake

      ]

```

**AppHeader scroll directive** (basic throttled directive)

```
    directives: {
        scroll: {
            created: (el, binding, vnode) => {
                const makeScrollableEvent = (key, el, binding, vnode) => {
                    const callback = (evt) => (binding.value(evt, el)) ? window.removeEventListener(key, f) : null;
                    window.addEventListener(key, throttle(callback, 100), {capture: false, passive: true});
                }
                makeScrollableEvent('scroll', el, binding, vnode);
            }
        },
    },
```

**Comment by klivak** [comment]
After spending a few hours to find a solution I realize, that I have an inner layout, so scrolling to top by #app - didn't work for me. I add id for my layout, and in _scrollBehavior_ section add that code and it works well.

```
const layoutId = document.getElementById('layout-scroll-container');

if (layoutId) {
    layoutId.scrollTop = 0;
}
```

Hope it could be useful for someone. (maybe, for @nolros too)

**Comment by ICAZ117** [comment]
@klivak You are officially a chad.

**Comment by drfcozapata** [comment]
This work for me (based on the solution given by @megasanjay):
```
	scrollBehavior: function (to, _from, savedPosition) {
            if (savedPosition) {
                return savedPosition;
            }
            if (to.hash) {
	        return { el: to.hash, behavior: 'smooth' };
            } else {
	        setTimeout(() => {
		    window.scrollTo(0, 0);
	        }, 500);
            }
	},
```
The 'setTimeout' because you could see how it went to the top of the page before going to the clicked page. I'm using transitions between one page and another, and it was very obvious.

**Comment by drfcozapata** [comment]
This work for me (based on the solution given by @megasanjay):
```javascript
	scrollBehavior: function (to, _from, savedPosition) {
            if (savedPosition) {
                return savedPosition;
            }
            if (to.hash) {
	        return { el: to.hash, behavior: 'smooth' };
            } else {
	        setTimeout(() => {
		    window.scrollTo(0, 0);
	        }, 500);
            }
	},
```
The 'setTimeout' because you could see how it went to the top of the page before going to the clicked page. I'm using transitions between one page and another, and it was very obvious.
