### ISSUE TITLE
New feature: Data Store(before PR)

### ISSUE THREAD

**Issue by hezedu** [vuejs/vue-router#3452]
### What problem does this feature solve?
 [#3445: vue-router positionStore memory leak](https://github.com/vuejs/vue-router/issues/3445)
####  reconstruct `util/state-key`
used `window.performance.now()` as the state key will reset when localtion reload, It may conflict with other hisotories

### router.setData(key, data)
  - `key` ___string___
  - `data` ___any___
### router.getData(key)
  - `key` ___string___ 
  - Returns: ___any___
### router.removeData(key)
  - `key` ___string___

### Online Demo:
https://hezedu.github.io/SomethingBoring/vue-router-positionstore-memory-leak/pr-demo.html#/

## Why adding these new features?

Unlike [window.history](https://developer.mozilla.org/en-US/docs/Web/API/History), vue-router has no API to change history.state.

But sometimes we need it to store some unique keys, like the `positionStore`. <br>
So I replaced `positionStore` with `dataStore`. This way you can store more things. <br>
And there is no need to develop `state` related APIs in the future.

**Comment by posva** [comment]
That's a cool demo! Unfortunately, the router won't have an api to hold state like `history.state`, it has been discussed many times in different issues and in different routers.

The thing you are trying to improve in v3 is already improved in v4 by using `history.state` for both HTML5 history and hash history but that won't be possible in v3

The `isPop` is something that I plan on introducing through an RFC for Vue Router 4. It might be backported to v3 after that

**Comment by hezedu** [comment]
`isPop` I have already cut off. Because I can distinguish `back` , `forword`, `repalce` or `push` in more detail. 
This will be another PR (if this PR passes)

**Comment by posva** [comment]
Closing in favor of https://github.com/vuejs/vue-router/issues/3453 although it still needs to go through an RFC
