### ISSUE TITLE
Warning vue-router@3.5.0: [vue-router] <router-link>'s tag prop is deprecated and has been removed in Vue Router 4

### ISSUE THREAD

**Issue by tachibana-shin** [vuejs/vue-router#3459]
Hello I am using vue-router@3.5.0 together with vue@2.5 but I got a warning moving to vue-router 4. what happened?

**Comment by posva** [comment]
already fixed and released

**Comment by tachibana-shin** [comment]
> already fixed and released

Ok, thank you 😍

**Comment by strixy** [comment]
It appears that this issue persists with v3.5.1.

**Comment by Fadeoc** [comment]
@posva It appears that this issue persists with v3.5.3.
src/index.js :264
