### ISSUE TITLE
Feature: passing props to nested routers on per subroute basis

### ISSUE THREAD

**Issue by sztrzask** [vuejs/vue-router#346]
Allow passing props to nested components on per subroute basis, e.g.

```
router.map(
{

    '/a':
    {
        subRoutes:
        {
            '/b/':
            {
                component: someComponent,
                props: 'somePropsFromA'
            },
            '/c':
           {
                component: someOtherComponent,
                props: 'some.Other.PropsFromA'
            },

        }

    }

})
```

It would be awesome if .sync and .once were supported too.

**Comment by amirrustam** [comment]
:+1:

**Comment by koi8-r** [comment]
:+1:

**Comment by zackcote** [comment]
This is a good point -- how is passing different props to individual nested subroutes supposed to be handled?

**Comment by ianwalter** [comment]
@zackcote I'm passing props through `this.$route`, i.e.

``` js
'/profile': {
  name: 'Profile',
  component: ProfileView,
  subRoutes: {
    '/edit-name': {
      component: ProfileView,
      isEditingName: true
    }
  }

// In ProfileView component...

data() {
  return { isEditingName: this.$route.isEditingName || false };
}
```

If the prop is dynamic, why couldn't you just make the subroute take the param i.e.

``` js
'/profile': {
  name: 'Profile',
  component: ProfileView,
  subRoutes: {
    '/action/:action': {
      component: ProfileView
    }
  }

// In ProfileView component...

data() {
  return { action: this.$route.params.action };
}
```

**Comment by andrisi** [comment]
Is this possible on non-nested routes? Defining "props" for each route in the routes object. I am having a hard time passing specific props to specific routes, even without nesting involved. I am missing the point?

**Comment by jipengzhu** [comment]
i wonder to know when will this feature to be completed

**Comment by posva** [comment]
this already works on vue-router, it's an issue for the old version

**Comment by jipengzhu** [comment]
@posva , thanks for your reply

in my test , `props` for nested routers  

can work when it is in router config

but it doesn't work when use `this.$router.push` api or `router-link` tag
