### ISSUE TITLE
Vue Route 4 can’t read the Arabic link when refresh browser

### ISSUE THREAD

**Issue by ockba-a** [vuejs/vue-router#3464]
### What problem does this feature solve?
Vue Route can’t read the link when Refresh Browser in hexadecimal

The route is Arabic language in alias and route

Ex:
[jmbz0.csb.app/تواصل](https://jmbz0.csb.app/%D8%AA%D9%88%D8%A7%D8%B5%D9%84)

Dependecy
Vue 3
Vue Route 4.0.3

You can visit sandbox
[Vue Route](https://codesandbox.io/s/intelligent-feynman-jmbz0?file=/src/main.js)

I Open The Issue In:

[StackOverFlow](https://stackoverflow.com/questions/65942595/vue-route-4-can-t-read-the-link-when-refresh-browser-in-vue-3)

And

[Vuejs Forum](https://forum.vuejs.org/t/vue-route-4-cant-read-the-link-when-refresh-browser/110703)

regard

**Comment by posva** [comment]
You need to provide valid URLs in their encoded form, for example: 

```js
{ path: "/about", alias: encodeURI("/عنا"), component: About },
  { path: encodeURI("/تواصل"), component: Contact },
```

Also, make sure to provide the correct values when using string locations (`<router-link to="/español">` should be encoded properly): https://next.router.vuejs.org/guide/migration/index.html#named-children-routes-with-an-empty-path-no-longer-appends-a-slash

In your code:

```vue
<router-link :to="encodeURI('/عنا')">About</router-link> |
  <router-link :to="encodeURI('/تواصل')">Contact</router-link>
```

To make things easier, use [named routes](https://next.router.vuejs.org/guide/essentials/named-routes.html)

I thought I documented this but I couldn't find it so I will open a new issue to track it

**Comment by posva** [comment]
BTW the repository for vue router 4 is https://github.com/vuejs/vue-router-next
