### ISSUE TITLE
android webview中使用loadDataWithBaseURL打开首页，打开页面后，不能回退到首页。同样的代码，浏览器中正常

### ISSUE THREAD

**Issue by flyinmind** [vuejs/vue-router#3471]
### Version
3.5.1

### Reproduction link
[http://jsfiddle/无](http://jsfiddle/无)

### Steps to reproduce
1、android webview中使用loadDataWithBaseURL打开首页index.html，router采用hash模式；
2、在首页index.html的created函数中，使用router.push打开一个页面A，OK；
3、在A中，点击按钮后，使用router.push打开一个页面B，在B中点击按钮，调用router.back或go(-1)，无法返回，提示Not allowed to navigate top frame to data URL: data:text/html;charset=utf-8;charset=utf-8;base64,#/；
4、如果使用history模式，返回后呈现空白页。
试过再加一重跳转，index.html->A->B->C，都无法返回，日志提示是一样的。
### What is expected?
返回页面A

### What is actually happening?
页面无变化，日志中提示Not allowed to navigate top frame to data URL: data:text/html;charset=utf-8;charset=utf-8;base64,#/；
source: http://app.njhx.com/assets/builtin/vue-router-src_3.5.1.js (1994)
应该是这一行，window.location[replace ? 'replace' : 'assign'](url);

---
我猜测可能因为loadDataWithBaseURL，index.html是data url，所以不能返回，
但是进入index.html后，就立刻router.push(A)了，按理在B中调用router.back()时，应该回到A才对。

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by flyinmind** [comment]
Thanks for your reply! and thanks for your efforts.
I think this is a feature request.

setAllowFileAccessFromFileURLs is deprecated in webview. loadDataWithBaseURL is  a better way.
I tried so many ways, all were failed when called go(-1) with router 3.5.1 at line 1994.
Call stack trace is:
        at pushState (http://app.njhx.com/assets/builtin/vue-router-src_3.5.1.js:1994:74)
        at replaceState (http://app.njhx.com/assets/builtin/vue-router-src_3.5.1.js:1999:5)
        at replaceHash (http://app.njhx.com/assets/builtin/vue-router-src_3.5.1.js:2802:7)
        at ensureSlash (http://app.njhx.com/assets/builtin/vue-router-src_3.5.1.js:2768:5)
        at handleRoutingEvent (http://app.njhx.com/assets/builtin/vue-router-src_3.5.1.js:2683:14)

**Comment by flyinmind** [comment]
A good news is that 'abstract' mode can work!
const router = new VueRouter({routes, mode:"abstract"});

But I still think that it is great if 'hash' or 'history' mode can work!
Thanks!
