### ISSUE TITLE
Caveat for catchall 404 not described appropriately in docs

### ISSUE THREAD

**Issue by 1beb** [vuejs/vue-router#3476]
### Version
3.5.1

### Reproduction link
[https://router.vuejs.org/guide/essentials/history-mode.html#caveat](https://router.vuejs.org/guide/essentials/history-mode.html#caveat)

### Steps to reproduce
Navigate to: https://router.vuejs.org/guide/essentials/history-mode.html#caveat

### What is expected?
It should show an example using `"/:catchAll(.*)"` as described here: https://stackoverflow.com/a/63544929/170352

### What is actually happening?
It shows an outdated example using a catchall as `path: "*"`

**Comment by Blakelist7** [comment]
@posva is someone working on this issue?

**Comment by posva** [comment]
I didn't realise but you are on the wrong docs for Vue Router 4: https://next.router.vuejs.org
