### ISSUE TITLE
Doc Guide-Javascript Section in Module System, Must run in vue runtimeCompiler: true

### ISSUE THREAD

**Issue by xiote** [vuejs/vue-router#3478]
### Version
3.5.1

### Reproduction link
[https://router.vuejs.org/guide/#javascript](https://router.vuejs.org/guide/#javascript)

### Steps to reproduce
https://router.vuejs.org/guide/#javascript

### What is expected?
Ok

### What is actually happening?
Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

**Comment by posva** [comment]
The example shows an html page with the correct script tags
