### ISSUE TITLE
$router is undefined in RouterLink component in Google WebCache pages

### ISSUE THREAD

**Issue by VsevolodChumachenko** [vuejs/vue-router#3482]
### Version
3.4.9

### Reproduction link
[https://webcache.googleusercontent.com/search?q=cache:-AlwFLsePq8J:https://strahovka.ru/e-osago &cd=1&hl=ru&ct=clnk&gl=ru](https://webcache.googleusercontent.com/search?q=cache:-AlwFLsePq8J:https://strahovka.ru/e-osago &cd=1&hl=ru&ct=clnk&gl=ru)

### Steps to reproduce
visit https://webcache.googleusercontent.com/search?q=cache:-AlwFLsePq8J:https://strahovka.ru/e-osago &cd=1&hl=ru&ct=clnk&gl=ru

### What is expected?
$router isn't undefined and error doesn't fall

### What is actually happening?
$router in RouterLink component is undefined and the error falls
<img width="717" alt="Снимок экрана 2021-03-04 в 16 59 37" src="https://user-images.githubusercontent.com/53918248/109975075-4a530880-7d0b-11eb-83ea-86faec36ae5c.png">
<img width="691" alt="Снимок экрана 2021-03-04 в 17 02 23" src="https://user-images.githubusercontent.com/53918248/109975187-6e164e80-7d0b-11eb-9f48-22715523c713.png">
<img width="386" alt="Снимок экрана 2021-03-04 в 17 03 00" src="https://user-images.githubusercontent.com/53918248/109975231-7c646a80-7d0b-11eb-9604-8edd73663f3e.png">

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Maybe the router plugin isn't installed or something but I can't do anything with that as a repro. There is https://github.com/vuejs/vue-router/issues/2042 related to cache

**Comment by VsevolodChumachenko** [comment]
@posva I tried to understand what is the problem. I debug the process and noticed the problem. I think the problem is that when we open page in google web cache it has route like this `https://webcache.googleusercontent.com/search?q=cache%3A-AlwFLsePq8J%3Ahttps%3A%2F%2Fstrahovka.ru%2Fe-osago%20&cd=1&hl=ru&ct=clnk&gl=ru` and like you see it has `/search` route, that is current, so `$route` is `undefined`, because it doesn't matched that route in route list, because we don't have that route on our site. You can see it in this part of code. It is `match()` method in `matcher`. You can see it in `vue-router.js`:

```js
...
} else if (location.path) {
  location.params = {};
  for (var i = 0; i < pathList.length; i++) {
    var path = pathList[i];
    var record$1 = pathMap[path];
    if (matchRoute(record$1.regex, location.path, location.params)) {
      return _createRoute(record$1, location, redirectedFrom)
    }
  }
}
// no match
return _createRoute(null, location)
```

But links in web page, that represents by `RouterLink` component are exist and they have valid route, so in function `isSameRoute()`, that is used in render function of `RouterLink`

```js 
classes[exactActiveClass] = isSameRoute(current, compareTarget); // current is undefined but compareTarget not
```

the process is crushed because it only checks `compareTarget` (argument `b` in `isSameRoute()`):

```js
function isSameRoute (a, b) {
  if (b === START) {
    return a === b
  } else if (!b) {
    return false
  } else if (a.path && b.path) {
    return (
      a.path.replace(trailingSlashRE, '') === b.path.replace(trailingSlashRE, '') &&
      a.hash === b.hash &&
      isObjectEqual(a.query, b.query)
    )
  } else if (a.name && b.name) {
    return (
      a.name === b.name &&
      a.hash === b.hash &&
      isObjectEqual(a.query, b.query) &&
      isObjectEqual(a.params, b.params)
    )
  } else {
    return false
  }
}
```

So I think that you should also check `current` argument, because it may be `undefined` like in my example

**Comment by cihangull** [comment]
> @posva I tried to understand what is the problem. I debug the process and noticed the problem. I think the problem is that when we open page in google web cache it has route like this `https://webcache.googleusercontent.com/search?q=cache%3A-AlwFLsePq8J%3Ahttps%3A%2F%2Fstrahovka.ru%2Fe-osago%20&cd=1&hl=ru&ct=clnk&gl=ru` and like you see it has `/search` route, that is current, so `$route` is `undefined`, because it doesn't matched that route in route list, because we don't have that route on our site. You can see it in this part of code. It is `match()` method in `matcher`. You can see it in `vue-router.js`:
> 
> ```js
> ...
> } else if (location.path) {
>   location.params = {};
>   for (var i = 0; i < pathList.length; i++) {
>     var path = pathList[i];
>     var record$1 = pathMap[path];
>     if (matchRoute(record$1.regex, location.path, location.params)) {
>       return _createRoute(record$1, location, redirectedFrom)
>     }
>   }
> }
> // no match
> return _createRoute(null, location)
> ```
> 
> But links in web page, that represents by `RouterLink` component are exist and they have valid route, so in function `isSameRoute()`, that is used in render function of `RouterLink`
> 
> ```js
> classes[exactActiveClass] = isSameRoute(current, compareTarget); // current is undefined but compareTarget not
> ```
> 
> the process is crushed because it only checks `compareTarget` (argument `b` in `isSameRoute()`):
> 
> ```js
> function isSameRoute (a, b) {
>   if (b === START) {
>     return a === b
>   } else if (!b) {
>     return false
>   } else if (a.path && b.path) {
>     return (
>       a.path.replace(trailingSlashRE, '') === b.path.replace(trailingSlashRE, '') &&
>       a.hash === b.hash &&
>       isObjectEqual(a.query, b.query)
>     )
>   } else if (a.name && b.name) {
>     return (
>       a.name === b.name &&
>       a.hash === b.hash &&
>       isObjectEqual(a.query, b.query) &&
>       isObjectEqual(a.params, b.params)
>     )
>   } else {
>     return false
>   }
> }
> ```
> 
> So I think that you should also check `current` argument, because it may be `undefined` like in my example

We are having the same problem. Did you find a solution?

**Comment by cihangull** [comment]
> ### Version
> 3.4.9
> 
> ### Reproduction link
> [https://webcache.googleusercontent.com/search?q=cache:-AlwFLsePq8J:https://strahovka.ru/e-osago &cd=1&hl=ru&ct=clnk&gl=ru](https://webcache.googleusercontent.com/search?q=cache:-AlwFLsePq8J:https://strahovka.ru/e-osago &cd=1&hl=ru&ct=clnk&gl=ru)
> 
> ### Steps to reproduce
> visit https://webcache.googleusercontent.com/search?q=cache:-AlwFLsePq8J:https://strahovka.ru/e-osago &cd=1&hl=ru&ct=clnk&gl=ru
> 
> ### What is expected?
> $router isn't undefined and error doesn't fall
> 
> ### What is actually happening?
> $router in RouterLink component is undefined and the error falls
> <img alt="Снимок экрана 2021-03-04 в 16 59 37" width="717" src="https://user-images.githubusercontent.com/53918248/109975075-4a530880-7d0b-11eb-83ea-86faec36ae5c.png">
> <img alt="Снимок экрана 2021-03-04 в 17 02 23" width="691" src="https://user-images.githubusercontent.com/53918248/109975187-6e164e80-7d0b-11eb-9f48-22715523c713.png">
> <img alt="Снимок экрана 2021-03-04 в 17 03 00" width="386" src="https://user-images.githubusercontent.com/53918248/109975231-7c646a80-7d0b-11eb-9604-8edd73663f3e.png">

We are having the same problem. Did you find a solution?

**Comment by VsevolodChumachenko** [comment]
> > ### Version
> > 3.4.9
> > ### Reproduction link
> > [https://webcache.googleusercontent.com/search?q=cache:-AlwFLsePq8J:https://strahovka.ru/e-osago &cd=1&hl=ru&ct=clnk&gl=ru](https://webcache.googleusercontent.com/search?q=cache:-AlwFLsePq8J:https://strahovka.ru/e-osago &cd=1&hl=ru&ct=clnk&gl=ru)
> > ### Steps to reproduce
> > visit https://webcache.googleusercontent.com/search?q=cache:-AlwFLsePq8J:https://strahovka.ru/e-osago &cd=1&hl=ru&ct=clnk&gl=ru
> > ### What is expected?
> > $router isn't undefined and error doesn't fall
> > ### What is actually happening?
> > $router in RouterLink component is undefined and the error falls
> > <img alt="Снимок экрана 2021-03-04 в 16 59 37" width="717" src="https://user-images.githubusercontent.com/53918248/109975075-4a530880-7d0b-11eb-83ea-86faec36ae5c.png">
> > <img alt="Снимок экрана 2021-03-04 в 17 02 23" width="691" src="https://user-images.githubusercontent.com/53918248/109975187-6e164e80-7d0b-11eb-9f48-22715523c713.png">
> > <img alt="Снимок экрана 2021-03-04 в 17 03 00" width="386" src="https://user-images.githubusercontent.com/53918248/109975231-7c646a80-7d0b-11eb-9604-8edd73663f3e.png">
> 
> We are having the same problem. Did you find a solution?

We made component, that checks if the `$router` is and after renders:

```js
export default {
  render() {
    if (!this.$route) {
      return <a href={this.$attrs.to}>{this.$slots.default}</a>;
    }

    return (
      <nuxt-link {...{ attrs: this.$attrs, on: this.$listeners }}>
        {this.$slots.default}
      </nuxt-link>
    );
  },
};
```

**Comment by abyss-soft** [comment]
Solution supplement: [Link](https://www.reddit.com/user/AlexaderPanov/comments/oe9hy5/nuxtjs_and_search_engines_solving_seo_problems/ )
