### ISSUE TITLE
How to get the props value after route update (beforeRouteUpdate)

### ISSUE THREAD

**Issue by excing** [vuejs/vue-router#3493]
### Version
3.5.1

### Reproduction link
[https://jsfiddle.net/os5znjd4/1/](https://jsfiddle.net/os5znjd4/1/)

### Steps to reproduce
1. After clicking 1 and then 2 and viewing the console print, the output of `this.id` is still 1, but 2 is displayed on the page. 

2. Click 3 again to view the console print, `this.id` is output as 2 and the page is displayed as 3.

### What is expected?
The value of `this.id` is the same as the value displayed on the page

### What is actually happening?
The two are not the same, `this.id` is not refreshed immediately after next()

**Comment by posva** [comment]
> The two are not the same, this.id is not refreshed immediately after next()

This is expected, as any prop, it takes a tick to be updated

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by excing** [comment]
Thank you. When can I get the updated props?
