### ISSUE TITLE
Document Error Class

### ISSUE THREAD

**Issue by bkuster** [vuejs/vue-router#3495]
### What problem does this feature solve?
When using programmatic navigation, redirecting using a router guard (e.g. for some login etc.), I need to handle some Errors. This Error holds more information then `Error` would. Could you document this augementation? Maybe even create Error classes? Would make error handling easier. I can see a `type` for instance, this could be `instanceof RedirectError` or what have you.

Additionally, you could update the documentation to hold these Errors

### What does the proposed API look like?
```typescript
// error.d.ts
enum ErrorType { 
  REDIRECT,
 // other types I havent come accross yet
}
class RedirectError extends Error {
  type: ErrorType;
  to: Location;
  from: Location;
}
```

### Update
This is _present_ within the code and exported as `NavigationFailureType`. The only thing I'm missing is documentation in the API Reference.

**Comment by posva** [comment]
https://router.vuejs.org/guide/advanced/navigation-failures.html#detecting-navigation-failures

**Comment by bkuster** [comment]
@posva thanks for the link. None the less: dont see why this is not part of the API reference and only the guide. So every time your API changes I need to re-read the guide?
