### ISSUE TITLE
Route information not shown correctly at App level

### ISSUE THREAD

**Issue by ericuldall** [vuejs/vue-router#3496]
### Version
3.5.1

### Reproduction link
[https://codesandbox.io/s/vue-router-demo-forked-ptgsn?file=/router/index.js](https://codesandbox.io/s/vue-router-demo-forked-ptgsn?file=/router/index.js)

### Steps to reproduce
Browse to https://ptgsn.csb.app/sign-in and open the console. Check the logs for APP: {$route}, LAYOUT: {$route} and PAGE: {$route}
---------------------
APP: 
```
{name: null, meta: Object, path: "/", hash: "", query: Object…}
```

PAGE: 
```
{name: "sign-in", meta: Object, path: "/sign-in", hash: "", query: Object…}
```

LAYOUT: 
```
{name: "sign-in", meta: Object, path: "/sign-in", hash: "", query: Object…}
```

### What is expected?
APP, LAYOUT and PAGE should return the same $route information.

### What is actually happening?
APP returns a null $route

**Comment by posva** [comment]
This is normal, you need to call `router.onReady()` to know when the initial navigation is finished and `$route` is set (which is when your page and layout are rendered and therefore show the right `$route`)

**Comment by ericuldall** [comment]
Fair enough. Thanks for the clarification.
