### ISSUE TITLE
Passing props callbacks

### ISSUE THREAD

**Issue by jishcem** [vuejs/vue-router#35]
hi, 

How do I pass a prop callback to the parent in this context ?

Is it something like <router-view on-register="onAuthenticated"> in the template of the component. 

And in the child component. 

props: ['on-register'],

register: function(e){
    var self = this,
    self.onRegister(someData);
}

Can I do it like this ?

**Comment by azamat-sharapov** [comment]
I think your question is appropriate for the [Vue.js Gitter chat room](http://gitter.im/yyx990803/vue) or vuejs/Discussion repo, not vuejs/vue-router for sure ;)
