### ISSUE TITLE
Shim state support for hash history

### ISSUE THREAD

**Issue by callmez** [vuejs/vue-router#350]
see [react-router:What is that ?_k=ckuvup junk in the URL?](https://github.com/rackt/react-router/blob/b9b21cbb32e6fbbf0e703360d0c7eaea2db41770/docs/guides/basics/Histories.md#what-is-that-_kckuvup-junk-in-the-url)

**Comment by posva** [comment]
Related to #2243

**Comment by posva** [comment]
Given that IE 9 is the only browser that would require a shim for this, there is no chance this gets implemented in vue router core anymore. A user land plugin is still possible but it looks like this is a thing people are requesting anymore
