### ISSUE TITLE
baidu browser: The title of HTML has '小' and route lazy loading, route switch error

### ISSUE THREAD

**Issue by PingTouG** [vuejs/vue-router#3502]
### Version
3.2.0

### Reproduction link
[https://github.com/PingTouG/baidu-demo](https://github.com/PingTouG/baidu-demo)

### Steps to reproduce
Set the title of the website to "小中文". It will fail to open the site switch route by using Baidu browser on Android phone.

### What is expected?
switch route

### What is actually happening?
switch route error

**Comment by posva** [comment]
> Set the title of the website to "小中文". It will fail to open the site switch route by using Baidu browser on Android phone.

That failing is unrelated to Vue and Vue Router. Your repro doesn't have the code and I cannot even test this. Also, Baidu browser is discontinued: https://en.wikipedia.org/wiki/Baidu_Browser

**Comment by PingTouG** [comment]
> > Set the title of the website to "小中文". It will fail to open the site switch route by using Baidu browser on Android phone.
> 
> That failing is unrelated to Vue and Vue Router. Your repro doesn't have the code and I cannot even test this. Also, Baidu browser is discontinued: https://en.wikipedia.org/wiki/Baidu_Browser

Android mobile is work, that is pc. Can you try to run demo in Baidu browser of Android phone?
