### ISSUE TITLE
Failed to resolve async component dfault: ChunkLoadError: Loading chunk about failed.

### ISSUE THREAD

**Issue by PingTouG** [vuejs/vue-router#3504]
### Version
3.2.0

### Reproduction link
[https://github.com/PingTouG/baidu-demo](https://github.com/PingTouG/baidu-demo)

### Steps to reproduce
Set the title of the website to "小中文". Other browsers and platforms are normal, only Baidu browser on Android phone will appear, and only the word "小" is set.

### What is expected?
Load page normally

### What is actually happening?
Unable to load page

Baidu browser APK download address: http://mo.baidu.com.

- download repro
- npm install
- npm run serve
- open the link in Baidu browser of Android phone

@posva

**Comment by posva** [comment]
The error ChunkLoadeError is unrelated to Vue, it's about the js chunk (created with webpack by using a dynamic import in your routes) not being served successfully. The title failing is also unrelated to Vue. You should contact baidu's support. There shouldn't be anything to do on Vue Router's end to fix this.

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by PingTouG** [comment]
> The error ChunkLoadeError is unrelated to Vue, it's about the js chunk (created with webpack by using a dynamic import in your routes) not being served successfully. The title failing is also unrelated to Vue. You should contact baidu's support. There shouldn't be anything to do on Vue Router's end to fix this.
> 
> Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

ok.Thanks

**Comment by XzyZachary** [comment]
Do you know this solution? I also encountered the same problem。
