### ISSUE TITLE
The AddRoute(parent, routeConfig) function does not update the order of child fallbacks

### ISSUE THREAD

**Issue by Marcoru97** [vuejs/vue-router#3511]
### Version
3.5.1

### Reproduction link
[https://codesandbox.io/s/blissful-fermi-mht16?file=/src/router.js](https://codesandbox.io/s/blissful-fermi-mht16?file=/src/router.js)

### Steps to reproduce
The console in the reproduction link prints the route order.
Click on "Test 4 (Fallback Issue)" navigates to the fallback route instead of the test-4 route.

### What is expected?
The fallback route should always be the last array entry, to prioritize the other routes.

### What is actually happening?
The fallback route is not at the end of the array, and if I want to navigate to a newly added route, the fallback route matches.

---
Maybe this is the cause:
https://github.com/vuejs/vue-router/blob/v3.5.1/src/create-route-map.js#L29
After some debugging, I found this for loop checking if the route is a wildcard, but it only checks the full string and misses something like this: /test/*

**Comment by posva** [comment]
The `addRoute` API was added to mimic as much as possible Vue Router 4 dynamic API but since routes are flattened, the loop you are referring to cannot be applied in this scenario. This is one of the cases where the API for Vue Router 3 falls behind since it doesn't support proper dynamic routing.

**Comment by posva** [comment]
This is one of the parts where the incomplete dynamic routing api of vue router 3 falls behind since vue router 3 doesn't support proper dynamic routing, only Vue Router 4 does.
