### ISSUE TITLE
Change route path with no slash in hash mode，the corresponding component is not rendered

### ISSUE THREAD

**Issue by ZacharyL2** [vuejs/vue-router#3512]
### Version
3.5.1

### Reproduction link
[https://codesandbox.io/s/vue-router-issue-example-u8xv5](https://codesandbox.io/s/vue-router-issue-example-u8xv5)

### Steps to reproduce
1. Create hash mode router，assuming that you currently have index path and login path，like this `http://localhost:8080/#/index` and `http://localhost:8080/#/login`

2. When i modify the index path to the login path in the browser address bar，like this `http://localhost:8080/#/index` 
 =>  `http://localhost:8080/#login`，**note：no slash after the `#`**

3. The corresponding component is not rendered

### What is expected?
Render the corresponding component

### What is actually happening?
The corresponding component is not rendered

**Comment by posva** [comment]
Thank you but they are different URLs and `#login` becoming `#/login` only on load is okay. You are not supposed to manually change the URL from the address bar as it behaves differently on some browsers and if you do, you should change it to `#/login` and not `#login` as the initial slash should always be there.

**Comment by wparad** [comment]
What's the problem with supporting this though? Is there a reason why vue-router couldn't also handle the route when there is no slash?

**Comment by ZacharyL2** [comment]
When I use react-router, it can support it. What is the difference in behavior when manually changing the URL in other browsers? Can you elaborate?
