### ISSUE TITLE
Redirect route triggered simply by having a router-link reference it.

### ISSUE THREAD

**Issue by philiprenich** [vuejs/vue-router#3514]
### Version
3.5.1

### Reproduction link
[https://github.com/philiprenich/vue-router-redirect-bug](https://github.com/philiprenich/vue-router-redirect-bug)

### Steps to reproduce
* `npm run serve` the repo
* navigate to localhost:8080/spa/about (/spa is the router base)
* browser will be redirected to `/` infinitely because of the `router-link` referencing a redirect route

### What is expected?
The route redirect function will only be run on link click

### What is actually happening?
The route redirect function is being run on load

---
I have a project where `domain.com/` is a static site. The Vue SPA is being served on `domain.com/base`. However, there is no content directly on `/base`, but only on `/base/something` Therefore, if someone tries to access `/base` the best user experience is to redirect them out of the SPA ecosystem back to `domain.com/`. To do this, the `/` route is set to redirect with `location.href = '/'`, but that is being triggered immediately when a `router-link` references that route, even if the user doesn't click it.

I have created a workaround by setting the route like this instead

```
  {
    path: "/",
    beforeEnter() {
      window.location.href = "/";
    }
  }
```

**Comment by posva** [comment]
This is inherent to how router-link work on Vue Router 3 but because you shouldn't have any side effects in a `redirect` option, it is a won'tfix. However, this works as expected in v4.

Your workaround is the proper way to do it for a side effect

**Comment by philiprenich** [comment]
@posva Thanks for the response! I understand side effects aren't really desirable so the wontfix makes sense. I dug through the code to see why / how router-link is doing that, but couldn't figure it out. If it isn't a hassle, would you mind showing me what is causing it?

**Comment by posva** [comment]
it's the `resolve` method on the `router` that is following the redirect. There should be other issues about this matter btw
