### ISSUE TITLE
Spanish translate 

### ISSUE THREAD

**Issue by jovicon** [vuejs/vue-router#3515]
### What problem does this feature solve?
Hi, hope you are well. My name is José Contreras.
I want to request Spanish translation for vue-router.
Some of my developers partners have problems to read docs in English.
This will help a lot of developers to improve their Vue.js skills and improve develop times.

### What does the proposed API look like?
Translate vue-router docs files from english to spanish

**Comment by jovicon** [comment]
I create this PR https://github.com/vuejs/vue-router/pull/3516 to work on this issue.
hope you approved.

**Comment by posva** [comment]
Thank you. Spanish translations were not kept up to date and were removed: https://github.com/vuejs/vue-router/pulls?q=is%3Apr+sort%3Aupdated-desc+spanish+is%3Aclosed

The general idea is to keep translations outside of the main repo. It seems like the place where people were the most active is at https://github.com/es-vuejs. You should contact the people there and try helping them.
