### ISSUE TITLE
$route is not computed correctly until after app is mounted with async components

### ISSUE THREAD

**Issue by Tofandel** [vuejs/vue-router#3518]
### Version
3.5.1

### Reproduction link
[https://codesandbox.io/s/happy-tdd-qh8vk?file=/src/App.vue:273-317](https://codesandbox.io/s/happy-tdd-qh8vk?file=/src/App.vue:273-317)

### Steps to reproduce
Create a router with async components, log the content of the route on mount
Load the page, notice the `$route` property is not correct on the mounted hook, it will be after the route component has loaded though, it is also correct if the route component is not async

### What is expected?
The `$route` property to be correctly reflecting the current route

### What is actually happening?
The `$route` property doesn't contain anything related to the current route

---
Since the route is still being matched properly before the router is ready it should contain the correct info even though the component it contains has still not loaded, currently it waits for the component to be fetched to trigger the "ready" event and set the correct `$route`, the route should be set before the "ready" event fires to avoid this problem

PS: I'm running into major troubles with server side rendering and v-if because of this bug

**Comment by posva** [comment]
This is expected: the route object is set once the navigation is validated. Please search existing issues before opening one

**Comment by Tofandel** [comment]
I did search but this creates a problem with server side rendering

With SSR if you use a computed property with `this.$route.meta` it will be correct, but on the front it will not, creating an invalid node state that throws an error

Edit: removed as the error is solved on the page

I cannot wait for the router to be ready in the computed property or then the component is not prerendered which defeats the point, we should be able to use the current route meta before it's component is loaded


Edit:

It seems I can delay the app mount until the router is ready

**Comment by Tofandel** [comment]
Okay so I did solve the problem by doing

```js
const v = new Vue({
  router,
  //...
});

router.onReady(() => {
  v.$mount('#app');
});
```

Effectively delaying the app mount until the first component is loaded, but it does delay the mounting time by a while and it's slightly noticeable (the page looks like it's jittering on load), surely there must a more efficient way of doing this without getting an error. But for now this is enough for me

**Comment by NielsJorck** [comment]
> Okay so I did solve the problem by doing
> 
> ```js
> const v = new Vue({
>   router,
>   //...
> });
> 
> router.onReady(() => {
>   v.$mount('#app');
> });
> ```
> 
> Effectively delaying the app mount until the first component is loaded, but it does delay the mounting time by a while and it's slightly noticeable (the page looks like it's jittering on load), surely there must a more efficient way of doing this without getting an error. But for now this is enough for me

Hi @Tofandel I had a very similar issue as you and after some fiddling I found a different solution and wanted to share.

```js
const router = useRouter();
const route = useRoute();

router.isReady().then(() => {
   ...
});
```

https://router.vuejs.org/api/#isready

(method) Router.isReady(): Promise<void>
Returns a Promise that resolves when the router has completed the initial navigation, which means it has resolved all async enter hooks and async components that are associated with the initial route. If the initial navigation already happened, the promise resolves immediately.

This is useful in server-side rendering to ensure consistent output on both the server and the client. Note that on server side, you need to manually push the initial location while on client side, the router automatically picks it up from the URL.
