### ISSUE TITLE
Wrong Vue instance used

### ISSUE THREAD

**Issue by stickeegreg** [vuejs/vue-router#3524]
### What problem does this feature solve?
I'm writing a Web Component that will be included in pages that may have their own copy of Vue loaded.
This causes errors (at least in dev mode) like "$attrs is readonly" - I'm not sure what the effect of these errors is.

The problem is caused by the following code at the end of src/index.js

```
if (inBrowser && window.Vue) {
  window.Vue.use(VueRouter)
}
```

### What does the proposed API look like?
I'm not sure what the best way to fix this would be - perhaps provide a separate .js file that doesn't have the auto registration?
```
import Vue from 'vue';
import VueRouter from 'vue-router/no-auto-registration';

Vue.use(VueRouter);
```

As a workaround, I have changed my code from

```
import Vue from 'vue';
import VueRouter from 'vue-router';

Vue.use(VueRouter);
```

to

```
import Vue from 'vue';

const VueRouter = (function () {
    let windowVue = null;

    if (typeof window !== 'undefined') {
        windowVue = window.Vue;
        delete window.Vue;
    }

    const VueRouter = require('vue-router').default;

    if (windowVue) {
        window.Vue = windowVue;
    }

    return VueRouter;
})();

Vue.use(VueRouter);
```

which is a very ugly hack...

**Comment by wparad** [comment]
Out of curiosity, why does your web component make use of the vue router?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

When reporting a bug, please follow https://new-issue.vuejs.org/?repo=vuejs/vue-router#why-repro

**Comment by stickeegreg** [comment]
@posva please re-open - this is clearly a bug or feature request, however you want to categorise it.
`import VueRouter from 'vue-router';` has global side-effects which are breaking my use case.

@wparad it's a whole vue app that users can embed on their own websites. Works fine if they don't already use Vue.

**Comment by posva** [comment]
Please respect our time and read the link I posted above. Thanks.
