### ISSUE TITLE
Wrong Vue instance used

### ISSUE THREAD

**Issue by stickeegreg** [vuejs/vue-router#3525]
### Version
3.5.1

### Reproduction link
[https://github.com/stickeegreg/vue-router](https://github.com/stickeegreg/vue-router)

### Steps to reproduce
Use a bundled (webpack) copy of Vue, but also have a non-bundled version (window.Vue)

Clicking a router link will give errors such as `[Vue warn]: $attrs is readonly.`

### What is expected?
Vue-router should use the bundled Vue instance, when `Vue.use(VueRouter)` is called.

### What is actually happening?
Vue-router is [automatically registering itself](https://github.com/vuejs/vue-router/blob/670e5c09918169bded57b84f1aa238e895a27e2e/src/index.js#L290) using `window.Vue.use(VueRouter)` before `Vue.use(VueRouter)` is called

---
Apologies for not including a reproduce case before - I had submitted it as a feature request so the form didn't ask me for one.

I realise this is an unusual use-case, and your initial reaction is likely to be "just don't use 2 copies of Vue" but what I'm doing is valid and is something other libraries support (e.g. jQuery's noConflict mode). I'm creating a web component that others will be able to embed in their own websites, therefore I have no control over whether there will be a global version of Vue loaded or not. I need to use the bundled one, because even if there is a global one, it may not be the correct version.

My initial idea would be to create a no-conflict.js and then change index.js to export everything from no-conflict and do the auto-registration.

I can create a PR if you'd like but maybe there's a better way to do it?

**Comment by wparad** [comment]
It actually doesn't make any sense for VueRouter to depend on `window.Vue` being set. Is there a reason that the auto-registration even exists in this library?

**Comment by stickeegreg** [comment]
It's in the documentation [here](https://router.vuejs.org/installation.html):

```
When used with a module system, you must explicitly install the router via Vue.use():
<snip code>
You don't need to do this when using global script tags.
```

I'd guess it's a convenience for when you're loading Vue from a CDN for example. Removing it would break a ton of stuff, so keeping it as the default but allowing a way to not do it would make sense to me.

**Comment by posva** [comment]
> Apologies for not including a reproduce case before - I had submitted it as a feature request so the form didn't ask me for one.

No worries, the code sample and the description are very clear now.

> I realise this is an unusual use-case, and your initial reaction is likely to be "just don't use 2 copies of Vue" but what I'm doing is valid and is something other libraries support (e.g. jQuery's noConflict mode)

You should indeed not be using 2 copies of Vue. You can expose the one you import in your `main.js` to window instead of also including it from a CDN:

```js
import Vue from 'vue'

window.Vue = Vue
```

The existing behaviour was very convenient when it was introduced and it is followed by other libraries like Vuex. It's no longer like that in Vue 3 but given the legacy nature of the unusual use-case and the fact that **there shouldn't be two copies of Vue in an application**, this won't change.

**Comment by stickeegreg** [comment]
OK thanks for taking a look. Just to clarify though, I don't have 2 copies of Vue in an application, I have 2 separate, independent Vue applications on one page. If this is too much of an edge-case, maybe it's something you could keep in mind for vue-router 4 :)

If anyone else has the same problem and is looking for a workaround, please see #3524
