### ISSUE TITLE
different behavior when import different router js with same code

### ISSUE THREAD

**Issue by Cumbermiao** [vuejs/vue-router#3526]
### Version
3.5.1

### Reproduction link
[https://github.com/Cumbermiao/vue-template](https://github.com/Cumbermiao/vue-template)

### Steps to reproduce
i am trying to refactor the code in router/index_back.js ,and i copy the code to the router/indexNew.js;
In indexNew.js , I export an function addRoute which is used to add dynamic route;
```js
const basicRoute = [
{
    path: '/login',
    name: 'Login',
    component: Login,
    meta: {
      title: '登录',
      asideHidden: true
    }
  },
  {
    path: '/404',
    name: '404',
    component: Page1,
    meta: {
      title: '404',
      asideHidden: true
    }
  }
]

const router = new VueRouter({
  routes
})

export default router

export const addRoute = list => {
  var addHome = [{
    path: '/',
    name: 'Home',
    component: Layout,
    redirect: '/404'
  }]
  router.addRoutes(addHome)
  console.log(router.getRoutes()) // Home has add successfully
  return Promise.resolve(addHome)

// ...
}
```
when I use addRoute in indexNew.js ,  Home was successfully added, but page not redirect to /404;
when I use addRoute in index_back.js, it worked;

### What is expected?
when I use addRoute in indexNew.js ,  Home was successfully added and page can redirect to /404;

### What is actually happening?
when I use addRoute in indexNew.js ,  Home was successfully added, but page not redirect to /404;

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

We expect boiled down reproductions like described at https://new-issue.vuejs.org/?repo=vuejs/vue#why-repro when reporting a bug
