### ISSUE TITLE
调用$router.push方法 我想将url地址栏中的空格 转义 “%20” 变为加号“+” ，我应该怎么做

### ISSUE THREAD

**Issue by zzzheli** [vuejs/vue-router#3529]
### What problem does this feature solve?
如下调用
this.$router.push({
path: '/catalogserach/result',
query: {q: "1 2"}
})

期望显示为加号 "+"
/catalogserach/result?q=1+2

实际地址栏显示为 "%20"
/catalogserach/result?q=1%202

### What does the proposed API look like?
暂无

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
