### ISSUE TITLE
UC移动端浏览器返回不受控

### ISSUE THREAD

**Issue by Statfine** [vuejs/vue-router#3532]
### Version
3.5.1

### Reproduction link
[https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aDE e3sgbXNnIH19PC9oMT5cbjwvdGVtcGxhdGU XG5cbjxzY3JpcHQgc2V0dXA XG5yb3V0ZXIucHVzaCh7XG4gICAgICBwYXRoOiAnJyxcbiAgICB9KTtcbjwvc2NyaXB0PiJ9](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aDE e3sgbXNnIH19PC9oMT5cbjwvdGVtcGxhdGU XG5cbjxzY3JpcHQgc2V0dXA XG5yb3V0ZXIucHVzaCh7XG4gICAgICBwYXRoOiAnJyxcbiAgICB9KTtcbjwvc2NyaXB0PiJ9)

### Steps to reproduce
uc移动端浏览器点击浏览器返回按钮不受控制(可能返回上一个页面，可能返回上几次的页面)，其他浏览器正常，pc端正常

### What is expected?
正常按照路径返回上一页面

### What is actually happening?
不受控制

**Comment by posva** [comment]
Open issues in English, thank you
