### ISSUE TITLE
mode "abstract" and router onReady

### ISSUE THREAD

**Issue by MatteoGabriele** [vuejs/vue-router#3533]
### Version
3.5.1

### Reproduction link
[https://codesandbox.io/s/brave-agnesi-lv8dy?file=/__tests__/router.spec.js](https://codesandbox.io/s/brave-agnesi-lv8dy?file=/__tests__/router.spec.js)

### Steps to reproduce
while in abstract mode, simply add any functionalities inside the router.onReady method and watch tests failing when trying to expect code inside of it to be called.

### What is expected?
code written inside the `onReady` method should be called in abstract mode just like in history or hash mode

### What is actually happening?
nothing inside `onReady` is called when in abstract mode

---
the abstract mode seems to be the preferred method to be used when performing testing with vue-router because is the only one that it's cleared on each iteration, but then it doesn't give the same results as the other modes.

as shown in the simple tests I wrote in codesandbox, the console.log is not called in abstract mode

**Comment by posva** [comment]
On abstract mode you need to manually push the initial location: https://jsfiddle.net/posva/cqs2851L/

**Comment by MatteoGabriele** [comment]
@posva ah perfect. thanks for your quick response!
cheers
