### ISSUE TITLE
No global handler for aborted navigation

### ISSUE THREAD

**Issue by e-cloud** [vuejs/vue-router#3535]
### What problem does this feature solve?
As a developer, I need to capture all navigation failure globally, not for one single navigation.

so, `$router.push('xxx').catch(...)` is not a solution.

For now, I have to hack to prototype to archive it.

```
const originalPush = VueRouter.prototype.push;
VueRouter.prototype.push = function (location: any) {
  return originalPush.bind(this)(location).catch((err) => {
    NProgress.done();
    return err;
  });
};
```

### What does the proposed API look like?
```
VueRouter.prototype.onAbort = function() {
...
}
```

BTW, there was a similar issue, which was closed casually.
https://github.com/vuejs/vue-router/issues/3286

**Comment by wparad** [comment]
> As a developer, I need to capture all navigation failure globally, not for one single navigation.

But why?

I can see the value in never throwing an error, often the unnecessary `.catch(() => {})` has to be added.

I wourd be more interested in never throwing, or logging an `Vue` message using the `Vue` global message handlers.

**Comment by posva** [comment]
See https://github.com/vuejs/vue-router/issues/2881#issuecomment-520554378 on how to replicate the existing behavior on Vue Router 4. This can be added as it would be a breaking change
