### ISSUE TITLE
Example server configurations only work for single page apps

### ISSUE THREAD

**Issue by korggy** [vuejs/vue-router#3537]
### Version
3.5.1

### Reproduction link
[https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations](https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations)

### Steps to reproduce
The [example server configurations](https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations) in the Vue Router documentation only work for single page apps, not [multipage apps](https://cli.vuejs.org/guide/html-and-static-assets.html#building-a-multi-page-app).

### What is expected?
The server should return the correct html content for the specific page requested from a multipage app.

### What is actually happening?
The server returns unexpected and incorrect content when the user tries to navigate to other pages in a multipage app.

---
I recommend adding a note to the documentation warning that multipage apps may require more sophisticated server configuration. An example would be helpful, but not necessary.

**Comment by posva** [comment]
This kind of issues would require directly a pull request, an issue doesn't seem to bring any guidance to anybody trying to contribute. I'm closing this in favour of a pull request with a suggestion that includes an example instead of saying _things are come complicated_ and maybe some external links. But I'm not sure this kind of documentation has its place in the router docs in the first place

**Comment by wparad** [comment]
> This kind of issues would require directly a pull request, an issue doesn't seem to bring any guidance to anybody trying to contribute. I'm closing this in favour of a pull request with a suggestion that includes an example instead of saying _things are come complicated_ and maybe some external links. But I'm not sure this kind of documentation has its place in the router docs in the first place

I think the question we should be asking ourselves is: **Is an example configuration for a multi-page app sufficiently complex, relevant, or interesting**. If it is one of those then we should think about creating it. What's wrong with having an open issue to suggest that work?
