### ISSUE TITLE
请说明 router-view 中使用动态组件的效果

### ISSUE THREAD

**Issue by XSun771** [vuejs/vue-router#3542]
### What problem does this feature solve?
在官方文档（ https://next.router.vuejs.org/zh/api/#router-view-的-v-slot ）中给出了

<router-view v-slot="{ Component, route }">
  <component :is="Component" />
</router-view>

这样使用动态组件例子。同时，在其它 Vue 项目中这种形式也算常见。但为什么要这样使用？带来什么好处和副作用却没有明确说明。希望文档能补充这方面的内容。

### What does the proposed API look like?
添加在 https://next.router.vuejs.org/zh/api/#router-view-的-v-slot 章节。

**Comment by posva** [comment]
Open issues in English. Thank you
