### ISSUE TITLE
Please explain the effect of using dynamic components in <router-view>

### ISSUE THREAD

**Issue by XSun771** [vuejs/vue-router#3543]
### What problem does this feature solve?
It is given in the official document (https://next.router.vuejs.org/zh/api/#router-view-的-v-slot):

```
<router-view v-slot="{ Component, route }">
  <component :is="Component" />
</router-view>
```

Use the dynamic component example like this. At the same time, this form is also common in other Vue projects. But why use it like this? The benefits and side effects are not clearly stated. Hope the document can supplement this content.

### What does the proposed API look like?
supplement explanation in https://next.router.vuejs.org/zh/api/#router-view-的-v-slot

**Comment by posva** [comment]
That is the API. The v-slot is used in transition and keep alive examples. I will update the code sample to use them.
