### ISSUE TITLE
Router.push() on Wheel Event doesn't trigger History State on Chrome

### ISSUE THREAD

**Issue by trinketmage** [vuejs/vue-router#3546]
### Version
3.5.1

### Reproduction link
[https://jsfiddle.net/Nephelococcygia/drzv2s9t/9/](https://jsfiddle.net/Nephelococcygia/drzv2s9t/9/)

### Steps to reproduce
- You open the demo link on Chrome;
- You bind Router.push() on a wheel Event;
- You use wheel and trigger any number of wheel event;
- The route is changing but the history is not saved and so the back button of the browser does not work.

### What is expected?
The history state should be pushed.

### What is actually happening?
The history state doesn't seem to be pushed.

---
If you triggers any numbers of wheel, and then navigate with a click on a router link, all the history state are pushed even the "wheel" originated ones.
If you click on a router link and then "wheel", history state works fine.
It might be a Chrome related problem, a kind of "Lock", "Unlock" with a click history state situation ?

**Comment by posva** [comment]
This is not clear, can you post a clear video to reproduce?

**Comment by Maxim-Mazurok** [comment]
Yes, I confirm the issue.
Steps:
1. Open repro link in Incognito/Private window (just opening in a new tab also seems to work).
2. Don't click anywhere, just scroll when hovering over the results frame
3. You will see home/foo/bar cycling
4. But the back button in Chrome won't be active (nothing pushed to the history)
5. As soon as you click anywhere (even empty blank space, don't have to click links) - everything gets pushed to the history

I think this is indeed Chrome's security measure, so probably nothing can be done on vue-router side.
