### ISSUE TITLE
Feature request: alias as a v-link property

### ISSUE THREAD

**Issue by ghost** [vuejs/vue-router#355]
# Feature request: alias as a v-link option

I will first describe what I have, what I am trying to accomplish and then how I tried to tackle the issue.
## What I have

I am developing a multilingual site. I have a homescreen, index of items page and item's description page.

The mappings are as following:

```
'/' maps to the homescreen/ homescreen component
'/:lang/index' maps to index of items page/component
'/:lang/item/:id' maps to the item's description
```

Each page has a **:lang** parameter and also has a named route attached. I can retireve the url with v-link by adding **name** and **params** .

I also provide **aliases** for the links so they are nicer.

```
'/en/bicycle/6' equals '/bicycle/6' - the route to the English page of a bicycle with id of 6
'/es/bicycle/6' equals '/bicicleta/6' - the route to the Spanish page of a bicycle with id of 6

* bicicleta is bicycle in spanish
```

The issue arises when I want to retrieve the **aliased** version of a link, meaning

```
v-link={ name: 'bicycle', params : { lang: 'es', id: '6'}}
```

returns **/es/bicycle/6** but it would be nicer if it would return **/bicicleta/6** .
## Exploration

I've delved into the code and I found it quite cryptic. Observations are based on code v0.7.10, as of 27.01.2016 .
- method **router.alias(aliasMap)** is defined in vue-router.js on L2164
- after looping thru the object's properties one ends in 
- alias -> _addAlias -> _addGuard -> (new RouteRecognizer()).add -> [now in RouteRecognizer (/lib/route-recognizer.js) ]
-  add: is defined on L336 - here is where I get lost
- it seems that **router.redirect(redirectMap)** -> _addRedirects ends up in the same file - route-recognizer.js

As it turns out RouteReconginzer.add() method is beyond my comprehension as it is quite a complex piece of code.
## Hacking

I created a **window.aliases** which I put into **router.alias();** . I also made **router** a **global** variable. In a global mixin I defined a method which returns an alias when given a v-link-understandable object.

```
Vue.mixin({
  methods: {
    pathToAlias: function (path) {
        var aliases = window.aliases || {};
        path = router._stringifyPath(path); // relies on 'GLOBAL' existence of VueRouter instance router

        for (var alias in aliases){
            if (typeof aliases[alias] !== 'function') {
              var value = aliases[alias];
              console.log('Value', value);
              console.log('Path', path);

              if(value == path) {
                return '#!' + alias; // #!/hashbang is harcoded TODO
              }
            }
        }

        return '#!' + path; // #!/hashbang is harcoded TODO
      }
  },
}:
```

I managed to find the **private** method _stringifyPath (vue-router.js L2559) which turn a v-link object into a string/link . Then I scan my **global** aliases object to find a match.
## My proposal

It would be nice if there was an **alias** preperty in v-link.
It would return the alias if it exists or just a regular link if it doesn't.
## To summ up

Since I identified this as a potentially useful feature I hope someone with a more exstensive knowledge of vue-router will able to make it a reality.

I was thinking of creating a private _aliases object in a Router() closure which would then function as my **hacked up** code but I don't know which other features vue-router provides and how this could be implemented in a better way.

I hope it gets implemented. Bye :+1:

**Comment by yyx990803** [comment]
One issue I see is that a path could have more than one aliases - so the path to alias conversion may not be always reliable.

But your mixin is imo a proper work around - note that you can access `this.$router` inside methods, it doesn't need to be a global.

**Comment by vizo** [comment]
:+1: 
I also looking for that solution in every framework, but nobody take care of multilingual routes :(

Can i ask why aliases are not defined directly in router.map? Then you don't need to repeat original path to define alias... For example:

```javascript
router.map({
  '/bicycle/:id': {
    name: 'bicycle', // give the route a name
    aliases: {
        bicycle_en: '/en/bicycle/:id', // give alias_name: alias value
        bicycle_es: '/es/bicicleta/:id',
        bicycle_sl: '/sl/kolo/:id
    }
    component: { ... }
  }
})
```
Alias object should also hold original route object, so you could easily find original route name or list of aliases, switching between aliases... This could give huge flexibility.
