### ISSUE TITLE
关于addRoute之后路由输出问题

### ISSUE THREAD

**Issue by zhoufanglu** [vuejs/vue-router#3550]
### Version
3.2.0

### Reproduction link
[https://github.com/zhoufanglu](https://github.com/zhoufanglu)

### Steps to reproduce
```js
//原始路由函数
const routes = [
  {
    path: '/home',
    name: 'home',
    component: Home
  },
  {
    path: '/',
    redirect: '/login'
  },
  {
    path: '/login',
    name: 'login',
    component: login
  }
]
//添加
router.addRoute('home', {
{
    path: '/allSeePage',
    name: '所有人可见',
    component: allSeePage
  },
})

```

### What is expected?
输出正确的路由列表

### What is actually happening?
列表不符合预期，平级了,效果如图
实际我输出的路由是平级的，难道不应该在home的children下吗？

![4I@5R0{$5HV34SUOCJ$W1YD](https://user-images.githubusercontent.com/24451091/118246303-5d851000-b4d4-11eb-9b7c-61970b9b1a98.png)

**Comment by posva** [comment]
That's not a valid reproduction. Also, open issues in English

**Comment by zhoufanglu** [comment]
> That's not a valid reproduction. Also, open issues in English

My English is a little poor, why close my question？
