### ISSUE TITLE
about router.addRoute(), list display issues

### ISSUE THREAD

**Issue by zhoufanglu** [vuejs/vue-router#3551]
### Version
3.2.0

### Reproduction link
[https://github.com/zhoufanglu](https://github.com/zhoufanglu)

### Steps to reproduce
```js
//routes list
const routes = [
  {
    path: '/home',
    name: 'home',
    component: Home
  },
  {
    path: '/',
    redirect: '/login'
  },
  {
    path: '/login',
    name: 'login',
    component: login
  }
]
// add route
router.addRoute('home', {
{
    path: '/allSeePage',
    name: '所有人可见',
    component: allSeePage
  },
})

```

### What is expected?
The list doesn't meet expectations. It only has one level

### What is actually happening?
The list doesn't meet expectations. It only has one level
```js
router.getRoutes()
```
![4I@5R0{$5HV34SUOCJ$W1YD](https://user-images.githubusercontent.com/24451091/118247191-7b06a980-b4d5-11eb-89f6-0301c6861a3a.png)

**Comment by posva** [comment]
Still not a valid repro. Read https://new-issue.vuejs.org/?repo=vuejs/vue-router#why-repro.
Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
