### ISSUE TITLE
missing param for named route "default": Expected "0" to be defined

### ISSUE THREAD

**Issue by Maxim-Mazurok** [vuejs/vue-router#3553]
### Version
3.5.1

### Reproduction link
[https://codesandbox.io/s/happy-sea-88cbr?file=/src/main.js](https://codesandbox.io/s/happy-sea-88cbr?file=/src/main.js)

### Steps to reproduce
1. Open repro link
1. Open the console
1. Observe `[vue-router] missing param for named route "default": Expected "0" to be defined ` warning

### What is expected?
No warning

### What is actually happening?
Warning shown

---
This seems to appear when creating a named catch-all `*` route and including a `router-link` to it, using the name.

**Comment by Maxim-Mazurok** [comment]
A dirty workaround that seems to hide this warning is to add params:
```
to={{ name: "default", params: { 0: 0 } }}
```

**Comment by posva** [comment]
This is expected, you need to pass a param pathMatch (https://router.vuejs.org/guide/essentials/dynamic-matching.html#catch-all-404-not-found-route). We could add a note to the docs noting it is necessary when using a named location. A PR would be welcome!

**Comment by Maxim-Mazurok** [comment]
@posva so, you suggest using this syntax?
```<router-link :to="{ name: 'default', params: { pathMatch: '' } }"```

**Comment by Maxim-Mazurok** [comment]
@posva any update? I'd be happy to open PR, but need to know which approach to recommend.
