### ISSUE TITLE
查询参数在hash前面就获取不到参数

### ISSUE THREAD

**Issue by mcck** [vuejs/vue-router#3557]
### Version
4.0.6

### Reproduction link
[http://localhost:8090/?code=Pr41zg#/dashboard](http://localhost:8090/?code=Pr41zg#/dashboard)

### Steps to reproduce
使用spring oauth2 授权后返回地址为：
http://localhost:8090/?code=Pr41zg#/dashboard
可以看到这个地址的查询参数在前，hash在后，访问后通过 route.query 属性获取不到查询参数，只有查询参数在hash后面才能获取到

### What is expected?
不区分查询参数在前和在后

### What is actually happening?
查询参数在前就不能获取到参数

**Comment by posva** [comment]
Use the chat or forum for questions

**Comment by 123jiacheng123** [comment]
楼主这个问题解决了吗？#/会自动跑到url路径最后

**Comment by mcck** [comment]
在路由创建之前修改？和#的顺序
```
let queryIndex = location.href.indexOf('?')
let hashIndex = location.href.indexOf('#')
if(queryIndex < hashIndex){
    location.href = location.origin + location.pathname + location.hash + location.search
}
```

**Comment by 123jiacheng123** [comment]
是在这里的之前添加你发的那段代码？
const router = new VueRouter({
    routes
});
我试验了下，如果添加了的话，那么页面在跳转新页面后比如localhost:8080/#/?city=烟台&type=guide&topic=必玩。在新页面刷新浏览器，页面会一直重定向耶，好气奥

**Comment by mcck** [comment]
是的，因为查看router源码，初始化的时候会从location取数据

**Comment by 123jiacheng123** [comment]
那简直了，恐怕这个无解啊

**Comment by mcck** [comment]
可以自定义createWebHashHistory

**Comment by 123jiacheng123** [comment]
那就GG了，那就复杂度陡然提高了 哈哈哈哈哈 自我安慰
