### ISSUE TITLE
Can't navigate to href="#"

### ISSUE THREAD

**Issue by peter31990** [vuejs/vue-router#3559]
### Version
3.5.1

### Reproduction link
[https://codepen.io/pen/](https://codepen.io/pen/)

### Steps to reproduce
`<router-link to="#">` should be `<a href="#">` but is `<a href="/current/path/something#">`

### What is expected?
href="#"

### What is actually happening?
href="/current/path/something#"

**Comment by posva** [comment]
This is expected, like a regular a tag
