### ISSUE TITLE
安卓机路由问题

### ISSUE THREAD

**Issue by shinygang** [vuejs/vue-router#356]
在使用安卓手机浏览器的时候，
1、路由地址会慢一步，比如我访问了/new,实际地址没变，当我访问/detail的时候，浏览器地址才是/new。这个问题qq浏览器很容易复现。
2、当我触发安卓的返回按钮返回页面的时候，浏览器的地址没变化。

备注：history:false的时候就正常，启用history就不正常了。

**Comment by fnlctrl** [comment]
如果要兼容qq浏览器的话用hash路由呗，别用history
~~你指望qq浏览器这种玩意完美支持HTML5 History API么..~~

**Comment by shinygang** [comment]
@fnlctrl 
很多安卓机子自带浏览器都不行，不用html5 History的话，又只能hash了，但是不符合我们的需求。

**Comment by fnlctrl** [comment]
http://caniuse.com/#search=history
History API是安卓4.3+的

**Comment by shinygang** [comment]
@fnlctrl 
我上不说是vue-router的issue,我是想寻求解决方案，我们使用的安卓版本肯定是大于4.3的。

**Comment by fnlctrl** [comment]
安卓浏览器兼容算老大难问题了，系统自带的各种浏览器、垃圾浏览器（qq、uc）、微信浏览器（有可能调用系统，有可能调用qq内核）....，这么多兼容不过来的，除了换hash路由没别的办法。

**Comment by yyx990803** [comment]
既然不是 vue-router 的 issue...

**Comment by henryxie2093** [comment]
vue 项目 使用 vue-router的时候用history模式会导致 低版本Android机子无法打开webview，
解决办法是 用nginx起vue 项目npm run build 后的dist文件中的项目

具体nginx配置大概是
```
server {
    listen 0.0.0.0:80;

    location / {
        root    /home/my-project/dist;
        try_files $uri $uri/ /index.html =404;
    }

    error_page 404 /index.html
}
```
