### ISSUE TITLE
"Before Each" guard for children routes

### ISSUE THREAD

**Issue by edumudu** [vuejs/vue-router#3562]
### What problem does this feature solve?
When access control is needed and executed when enter routes that are children of another and all needs share the same condition to be able to the user enter is needed to put a `beforeEnter` in every child to works and this is kinda tedious, hard to maintain, and not have the same behavior that global `beforeEach`.

The solution with 'meta' and the global `beforeEach` looks polluted and separates the logic many times. In addition to adding several additional checks on route navigation that have nothing to do with it.

### What does the proposed API look like?
This can be called before route `beforeEnter`.

```js
[
  {
    path: '/dashboard'
    compoenent: LayoutDashboard,
    // This guards should be executed before every child navigation
    beforeEach: isAuthendicated
    children: [
       {
          path: 'admin'
          compoenent: LayoutAdmin,
          // This guards should be executed before every child navigation
          beforeEach: isAdmin
          children: []
       },
    ]
  },

  {
        path: '/'
        compoenent: LayoutDefault,
        children: [
            // Routes that don't need checks
        ]
     },
]
```

**Comment by posva** [comment]
> The solution with 'meta' and the global beforeEach looks polluted and separates the logic many times

Using `meta` + `beforeEach()` is the recommended approach to write a factorized version and has proven to be more flexible and powerful. We don't want to have another way to do it.
