### ISSUE TITLE
this.$route in computed runs twice

### ISSUE THREAD

**Issue by jd-solanki** [vuejs/vue-router#3570]
### Version
3.5.1

### Reproduction link
[https://codesandbox.io/s/amazing-architecture-zwque](https://codesandbox.io/s/amazing-architecture-zwque)

### Steps to reproduce
1. Visit about route
2. Reload the web view
3. Check console

### What is expected?
There shall be only one console log of about route

### What is actually happening?
We are also getting root route get logged in. Hence, two routes are getting computed

---
Because of this, I am getting the wrong layout rendering because of root route gets unexpected computation.

**Comment by posva** [comment]
This is normal, it's because of the initial navigation being async, try logging `this.$route.name` and you will see the _START_LOCATION_ and then your About page.

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
