### ISSUE TITLE
是否有让路由临时失效（disable ）（不再监听浏览器地址栏的变化）的方案

### ISSUE THREAD

**Issue by troyzhxu** [vuejs/vue-router#3575]
### What problem does this feature solve?
在微前端架构中，当父应用把页面 从 子应用A 切换到 子应用B 时，希望 子应用 A 保留原有的状态（不要销毁，以便后续切回）但也不希望 A 影响 B 的路由。

所以希望 路由可以有一个 类似 disable 与 enable 的方法

### What does the proposed API look like?
1、使路由失效（失效后不再监听浏览器地址栏的变化）

router.disable() 

2、重新启用路由

router.enable()

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

BTW issues are in English only

**Comment by troyzhxu** [comment]
好吧
