### ISSUE TITLE
$router.resolve解析结果不正确

### ISSUE THREAD

**Issue by chenguzhen87** [vuejs/vue-router#3583]
### Version
3.3.2

### Reproduction link
[https://github.com/vuejs/vue-router/issues/3580](https://github.com/vuejs/vue-router/issues/3580)

### Steps to reproduce
具体见：
https://github.com/vuejs/vue-router/issues/3580

### What is expected?
$router.resolve能解析正确地址editVideo/341

### What is actually happening?
editVideo/341解析成“/”

**Comment by posva** [comment]
Read and follow https://new-issue.vuejs.org/?repo=vuejs/vue-router to provide a boiled down repro in English
