### ISSUE TITLE
Custom parse/stringifyQuery may cause URL query and route query to get out of sync

### ISSUE THREAD

**Issue by backbone87** [vuejs/vue-router#3586]
### Version
3.5.2

### Reproduction link
[https://codesandbox.io/s/thirsty-wilbur-63o96?file=/src/main.js](https://codesandbox.io/s/thirsty-wilbur-63o96?file=/src/main.js)

### Steps to reproduce
In the sandbox use the buttons at the top to navigate between different query strings. Compare `foo: null` vs `foo: undefined`.
The sandbox uses custom parse/stringifyQuery to handle null values the same as undefined (= remove from query).

### What is expected?
`foo: null` will remove the query parameter from URL **and** ~~the route query object~~ *set it to `undefined` in the route query object*.

### What is actually happening?
`foo: null` removes the query parameter from the URL, ~~but **not** from the query object~~ *but does **not** set it to `undefined` in the query object*. if the page is reloaded then the parameter is not present in the route query anymore.

---
I think a solution would be to reparse the query after it was stringified to be appended to the URL

**Comment by posva** [comment]
both null and undefined will keep the property in the object but this is intended. In practice, this won't matter though as the only possible empty case missing is `query.foo == ''`

**Comment by backbone87** [comment]
`$route.query` is a representation of the query string, it should not map an absent parameter to undefined in one case (after page reload) and to null in another (after $router.push/replace). yes there **can** be a separate representation of null inside the query string, but since we have the possibility to define custom parse/stringifyQuery this may also not be the case and then `$route.query` should adhere to these custom serializers.

> both null and undefined will keep the property in the object

this is not the point of this issue. nevertheless I do not think that this is the most accurate behavior, since what you "see" in the URL query string should map to exactly one $route.query and not depend on previous route mutations.

edit: I have edited the OP to better reflect the intentions of this issue

**Comment by backbone87** [comment]
@posva are you interested in reconsidering this with the clarifications i made? because with the current behavior the custom query string serializer feature is not that useful.

**Comment by posva** [comment]
My point is: if you treat both null and undefined as not having the query parameter, it doesn't matter if reloading yields undefined instead of null since you were already considering them the same so at the end it doesn't matter
