### ISSUE TITLE
Redirect With Query Issue

### ISSUE THREAD

**Issue by sell** [vuejs/vue-router#3588]
### Version
3.5.2

### Reproduction link
[https://codesandbox.io/s/interesting-wave-xpvn7?file=/src/router/index.js](https://codesandbox.io/s/interesting-wave-xpvn7?file=/src/router/index.js)

### Steps to reproduce
One way to reproduce, is by adding a query to your redirect path, ex:
```js
{
    path: '/bot/:id/vote',
    redirect: {
      path: '/bot/:id/?vote=true'
    },
},
```

### What is expected?
It should load the component.

### What is actually happening?
It's leading to a 404 page, but when I refresh the page it works.

---
Here is a video, of showing what happens:

https://user-images.githubusercontent.com/34258275/125176695-7e4fa600-e1a3-11eb-87de-235a7f75ffa9.mov

**Comment by sell** [comment]
The only fix I was able to do was by using the `beforeEnter` method, but this temporarily shows a blank white screen which is not really nice. 

```js
{
    path: '/bot/:id/vote',
    beforeEnter: (to, from, next) => {
      next(`/bot/${to.params.id}?vote=true`);
    },
},
  ```

**Comment by posva** [comment]
Your reproduction is lacking the mentioned code and you should build a proper path in the redirect:

```js
{
    path: '/bot/:id/vote',
    redirect: to => `/bot/:id/?vote=true`
},
```

**The query cannot be in `path`**, it must go in `query`.

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by sell** [comment]
I gave a similar replication use a param and query, the issue seem to be with a component being lazy loaded and using the methos i used prior:
```js
{
    path: '/bot/:id/vote',
    redirect: {
      path: '/bot/:id/?vote=true'
    },
},
```
The working code is:
```js
{
    path: '/bot/:id/vote',
    redirect: {
      path: '/bot/:id',
      query: {
        vote: true,
      },
    },
  },
  ```

Would like to thank you for your contribution, help and maintaining of vue-router!
