### ISSUE TITLE
Passing Options API data object in route params not working

### ISSUE THREAD

**Issue by Lalrinfela** [vuejs/vue-router#3589]
Sometimes we need to pass object data with many properties in route params. It was working till version 3 but in the latest version it's not working. It just output [object] [object].

This works:
```this.$router.push({name: 'home', params: {rollNo: user.rollNo, class: user.class}})```

This Does not:
```
this.$router.push({name: 'home', {params: {user}})
<script>
export default {
  name: "ContactUs",
  data() {
   return {
     user: {rollNo: 'A123', class: 'Grade 9'}
   }
  }
}
</script>
```

**Comment by wcldyx** [comment]
I'm wondering why it prevents "params" from sending "object", don't you need to consider backward compatibility?
