### ISSUE TITLE
$router.replace behaves differently from window.history.replaceState when there is no diff between params and the current URL

### ISSUE THREAD

**Issue by teruhiky** [vuejs/vue-router#3595]
|  | the current URL !== params | the current URL === params |
----|----|---- 
| window.history.replaceState | replaced | no impact |
| this.$nuxt.$router.replace | replaced | NavigationDuplicated Error |

This is error-prone for engineers when using it. At least, it would be great if we clearly mention there is the difference of the behavior even though window.history.replaceState is similar to router.replace.

**Comment by LinusBorg** [comment]
https://next.router.vuejs.org/guide/advanced/navigation-failures.html#detecting-navigation-failures

**Comment by posva** [comment]
and for v3 docs: https://router.vuejs.org/guide/advanced/navigation-failures.html

**Comment by teruhiky** [comment]
understood, thank you vm
