### ISSUE TITLE
Adding route to beforeEach failed

### ISSUE THREAD

**Issue by c-Clithe** [vuejs/vue-router#3597]
### Version
3.5.2

### Reproduction link
[https://github.com/c-Clithe/vite2-vue3-vue-router4](https://github.com/c-Clithe/vite2-vue3-vue-router4)

### Steps to reproduce
router.beforeEach((to, from, next) => {
	loading = ElLoading.service({
		lock: true,
		text: '加载中...',
		spinner: 'el-icon-loading',
		background: 'rgba(0, 0, 0, 0)'
	})
	
	if (to.path === '/') {
		next()
		loading.close()
	} else {
		const routerList = filterAsyncRoutes(store.state.routers)
		routerList.forEach(item=>{
			router.addRoute(item)
		})
		next()
	}
})

### What is expected?
Route normal jump

### What is actually happening?
[Vue Router warn]: No match found for location with path "/information"

**Comment by posva** [comment]
This is explained in the docs dynamic routing
