### ISSUE TITLE
package isn't available in npm

### ISSUE THREAD

**Issue by nmabhinandan** [vuejs/vue-router#36]
https://www.npmjs.com/search?q=vue-router

**Comment by yyx990803** [comment]
This is released yet.

**Comment by michaeljcalkins** [comment]
Maybe you could just put it up in the meantime so that it can more easily be tested by the public.

**Comment by yyx990803** [comment]
@michaeljcalkins you can install from raw github repos with `npm install vuejs/vue-router`. I'll only publish a release when we have decent test coverage.
