### ISSUE TITLE
allow optional segments for optional parameters

### ISSUE THREAD

**Issue by Anubarak** [vuejs/vue-router#3602]
### What problem does this feature solve?
I'm trying to add optional segments in my single route (not parameters).
My current path might look like
```JS
{
    path: 'project/:projectId/variant/:variantId?/tab/:tabId?/group/:groupId?'
}
```
And should match these routes
```
project/5/
project/5/variant/3
project/5/variant/3/tab/8
project/5/variant/3/tab/8/group/4
```
I want to create a single route and not multiple different because all these are basically the same and they route to the very same component just with different states (tabs/groups/dialogs with toggle).

The problem is:
When I route to the above via `<router-link :to={name: 'route-name', params: {}}` my routes look instead like
```
project/5/variant/tab/group
project/5/variant/3/tab/group
project/5/variant/3/tab/8/group
project/5/variant/3/tab/8/group/4
```
and I would like to get rid of the wordings before the optional parameters.
I know I could actually make these optional as well but creating routes with
```js
router.push({
    params: {
        projectId: 5,
        variant: 'variant',
        variantId: 3,
        tab: 'tab',
        tabId: 8,
        group: '',
        groupId: ''
    }
});
```
seems like over the top. In PHP it's a common use case to include optional segments to existing routes so it would be awesome to have this feature as well in Vue Router.

After searching for hours I found no solution. 

### What does the proposed API look like?
The path could then look like
```JS
{
    path: 'project/:projectId/(variant)?/:variantId?/(tab)?/:tabId?/(group)?/:groupId?'
}
```

**Comment by posva** [comment]
In Vue Router 3, you should be able to do groups (https://router.vuejs.org/guide/essentials/dynamic-matching.html#advanced-matching-patterns), it should be something like `/(project/:projectId)?`.
In Vue Router 4, you can use a custom regexp: https://paths.esm.dev/?p=AAMeJbiAwAEenFbAMAWAMQlcEyBQAIYfUARc3NYBasAEcr-lAygQcAHWWCzLDg09t2NldNco0qgWOowAFHAkkzp1oAwwBxVAHNobwmrjIVYogAAg&t=/project/2/variant/3#. You will need to manually build the URL yourself because it contains `/` which are encoded in params.

The syntax of groups you are proposing cannot be adapted because it cannot be ranked and will impede dynamic routing

**Comment by PayteR** [comment]
> In Vue Router 3, you should be able to do groups (https://router.vuejs.org/guide/essentials/dynamic-matching.html#advanced-matching-patterns), it should be something like `/(project/:projectId)?`. In Vue Router 4, you can use a custom regexp: https://paths.esm.dev/?p=AAMeJbiAwAEenFbAMAWAMQlcEyBQAIYfUARc3NYBasAEcr-lAygQcAHWWCzLDg09t2NldNco0qgWOowAFHAkkzp1oAwwBxVAHNobwmrjIVYogAAg&t=/project/2/variant/3#. You will need to manually build the URL yourself because it contains `/` which are encoded in params.
> 
> The syntax of groups you are proposing cannot be adapted because it cannot be ranked and will impede dynamic routing

Hi @posva, i couldn't make groups working on vue-router 3.5.3. When i have path like `path: '/category/:path/page/:page/'` it works but  `path: '/category/:path/(page/:page/)?'` is not working.. where can i even find documentation about this? Thx
