### ISSUE TITLE
NAVIGATION TO SAME ROUTE WITH DIFFERENT PARAMS

### ISSUE THREAD

**Issue by maki1997** [vuejs/vue-router#3604]
### Version
3.5.2

### Reproduction link
[https://jsfiddle.net/rdc7pkzb/](https://jsfiddle.net/rdc7pkzb/)

### Steps to reproduce
Call $router.replace or $router.push twice with the same path and different params

### What is expected?
The route should stay the same, but route params should be changed.

### What is actually happening?
NavigationDuplicatedError is thrown.

---
Solution: Add additional check to function isSameRoute and check if the params from the old route are the same as the params from the new route.

Path to file: src/util/route.js

https://prnt.sc/1es0il3

**Comment by posva** [comment]
Params must be part of the path. They cannot be used to pass arbitrary state
