### ISSUE TITLE
建议route跳转后创建components时根据fullpath给components覆盖一个name以解决keep-alive问题

### ISSUE THREAD

**Issue by yuntian001** [vuejs/vue-router#3606]
### What problem does this feature solve?
当vue-route 和  keep-alive结合使用时通常的方案为：
```
<keep-alive :include="cachedViews" >
          <router-view :key="key" />
      </keep-alive>
```
但是include是通过组件名判断的，如果两个route 共用同一个组件就会出现问题，例如详情页 detail/1 detail/2共用同一个组件。
在cachedViews清楚缓存后  detail/1的缓存也会失效

### What does the proposed API look like?
建议路由跳转后创建component组件时，对组件设置一个对应路由fullPtah的唯一name 、并且放入当前路由的$route中。这样即可解决组件name判断问题，现在大部分还是用的vue2、强烈建议vue2版本加上此更新。

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
