### ISSUE TITLE
this.$route.name  is "undefined" in computed()

### ISSUE THREAD

**Issue by GeniusWiki** [vuejs/vue-router#3612]
### Version
3.5.2

### Reproduction link
[https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzcmM9XCJodHRwczovL3VucGtnLmNvbS92dWVAM1wiPjwvc2NyaXB0PlxuPHNjcmlwdCBzcmM9XCJodHRwczovL3VucGtnLmNvbS92dWUtcm91dGVyQDRcIj48L3NjcmlwdD5cblxuPGRpdiBpZD1cImFwcFwiPlxuICA8aDE SGVsbG8gQXBwITwvaDE XG4gIDxwPlxuICAgIDwhLS0gdXNlIHRoZSByb3V0ZXItbGluayBjb21wb25lbnQgZm9yIG5hdmlnYXRpb24uIC0tPlxuICAgIDwhLS0gc3BlY2lmeSB0aGUgbGluayBieSBwYXNzaW5nIHRoZSBgdG9gIHByb3AuIC0tPlxuICAgIDwhLS0gYDxyb3V0ZXItbGluaz5gIHdpbGwgcmVuZGVyIGFuIGA8YT5gIHRhZyB3aXRoIHRoZSBjb3JyZWN0IGBocmVmYCBhdHRyaWJ1dGUgLS0 XG4gICAgPHJvdXRlci1saW5rIHRvPVwiL1wiPkdvIHRvIEhvbWU8L3JvdXRlci1saW5rPlxuICAgIDxyb3V0ZXItbGluayB0bz1cIi9hYm91dFwiPkdvIHRvIEFib3V0PC9yb3V0ZXItbGluaz5cbiAgICB1c2VyIDxkaXYgdi10ZXh0PVwidXNlcm5hbWVcIj48L2Rpdj5cbiAgPC9wPlxuICA8IS0tIHJvdXRlIG91dGxldCAtLT5cbiAgPCEtLSBjb21wb25lbnQgbWF0Y2hlZCBieSB0aGUgcm91dGUgd2lsbCByZW5kZXIgaGVyZSAtLT5cbiAgPHJvdXRlci12aWV3Pjwvcm91dGVyLXZpZXc XG48L2Rpdj5cblxuXG48c2NyaXB0PlxuICAgIC8vIFRoZXNlIGNhbiBiZSBpbXBvcnRlZCBmcm9tIG90aGVyIGZpbGVzXG5jb25zdCBIb21lID0geyB0ZW1wbGF0ZTogJzxkaXY SG9tZTwvZGl2PicgfVxuY29uc3QgQWJvdXQgPSB7IHRlbXBsYXRlOiAnPGRpdj5BYm91dDwvZGl2PicgfVxuXG4vLyAyLiBEZWZpbmUgc29tZSByb3V0ZXNcbi8vIEVhY2ggcm91dGUgc2hvdWxkIG1hcCB0byBhIGNvbXBvbmVudC5cbi8vIFdlJ2xsIHRhbGsgYWJvdXQgbmVzdGVkIHJvdXRlcyBsYXRlci5cbmNvbnN0IHJvdXRlcyA9IFtcbiAgeyBwYXRoOiAnLycsIGNvbXBvbmVudDogSG9tZSwgbmFtZTogXCJob21lXCIgfSxcbiAgeyBwYXRoOiAnL2Fib3V0JywgY29tcG9uZW50OiBBYm91dCwgbmFtZTogXCJhYm91dFwiIH0sXG5dXG5cbi8vIDMuIENyZWF0ZSB0aGUgcm91dGVyIGluc3RhbmNlIGFuZCBwYXNzIHRoZSBgcm91dGVzYCBvcHRpb25cbi8vIFlvdSBjYW4gcGFzcyBpbiBhZGRpdGlvbmFsIG9wdGlvbnMgaGVyZSwgYnV0IGxldCdzXG4vLyBrZWVwIGl0IHNpbXBsZSBmb3Igbm93LlxuY29uc3Qgcm91dGVyID0gVnVlUm91dGVyLmNyZWF0ZVJvdXRlcih7XG4gIC8vIDQuIFByb3ZpZGUgdGhlIGhpc3RvcnkgaW1wbGVtZW50YXRpb24gdG8gdXNlLiBXZSBhcmUgdXNpbmcgdGhlIGhhc2ggaGlzdG9yeSBmb3Igc2ltcGxpY2l0eSBoZXJlLlxuICBoaXN0b3J5OiBWdWVSb3V0ZXIuY3JlYXRlV2ViSGFzaEhpc3RvcnkoKSxcbiAgcm91dGVzLCAvLyBzaG9ydCBmb3IgYHJvdXRlczogcm91dGVzYFxufSlcblxuLy8gNS4gQ3JlYXRlIGFuZCBtb3VudCB0aGUgcm9vdCBpbnN0YW5jZS5cbmNvbnN0IGFwcCA9IFZ1ZS5jcmVhdGVBcHAoe1xuICAgIGNvbXB1dGVkOiB7XG4gICAgICAgIHVzZXJuYW1lKCkge1xuICAgICAgICAvLyBXZSB3aWxsIHNlZSB3aGF0IGBwYXJhbXNgIGlzIHNob3J0bHlcbiAgICAgICAgICAgIGNvbnNvbGUubG9nKCduYW1lJywgdGhpcy4kcm91dGUubmFtZSk7XG4gICAgICAgICAgICByZXR1cm4gdGhpcy4kcm91dGUubmFtZVxuICAgICAgICB9LFxuICAgIH1cbn0pXG4vLyBNYWtlIHN1cmUgdG8gX3VzZV8gdGhlIHJvdXRlciBpbnN0YW5jZSB0byBtYWtlIHRoZVxuLy8gd2hvbGUgYXBwIHJvdXRlci1hd2FyZS5cbmFwcC51c2Uocm91dGVyKVxuXG5hcHAubW91bnQoJyNhcHAnKVxuPC9zY3JpcHQ In0=](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzcmM9XCJodHRwczovL3VucGtnLmNvbS92dWVAM1wiPjwvc2NyaXB0PlxuPHNjcmlwdCBzcmM9XCJodHRwczovL3VucGtnLmNvbS92dWUtcm91dGVyQDRcIj48L3NjcmlwdD5cblxuPGRpdiBpZD1cImFwcFwiPlxuICA8aDE SGVsbG8gQXBwITwvaDE XG4gIDxwPlxuICAgIDwhLS0gdXNlIHRoZSByb3V0ZXItbGluayBjb21wb25lbnQgZm9yIG5hdmlnYXRpb24uIC0tPlxuICAgIDwhLS0gc3BlY2lmeSB0aGUgbGluayBieSBwYXNzaW5nIHRoZSBgdG9gIHByb3AuIC0tPlxuICAgIDwhLS0gYDxyb3V0ZXItbGluaz5gIHdpbGwgcmVuZGVyIGFuIGA8YT5gIHRhZyB3aXRoIHRoZSBjb3JyZWN0IGBocmVmYCBhdHRyaWJ1dGUgLS0 XG4gICAgPHJvdXRlci1saW5rIHRvPVwiL1wiPkdvIHRvIEhvbWU8L3JvdXRlci1saW5rPlxuICAgIDxyb3V0ZXItbGluayB0bz1cIi9hYm91dFwiPkdvIHRvIEFib3V0PC9yb3V0ZXItbGluaz5cbiAgICB1c2VyIDxkaXYgdi10ZXh0PVwidXNlcm5hbWVcIj48L2Rpdj5cbiAgPC9wPlxuICA8IS0tIHJvdXRlIG91dGxldCAtLT5cbiAgPCEtLSBjb21wb25lbnQgbWF0Y2hlZCBieSB0aGUgcm91dGUgd2lsbCByZW5kZXIgaGVyZSAtLT5cbiAgPHJvdXRlci12aWV3Pjwvcm91dGVyLXZpZXc XG48L2Rpdj5cblxuXG48c2NyaXB0PlxuICAgIC8vIFRoZXNlIGNhbiBiZSBpbXBvcnRlZCBmcm9tIG90aGVyIGZpbGVzXG5jb25zdCBIb21lID0geyB0ZW1wbGF0ZTogJzxkaXY SG9tZTwvZGl2PicgfVxuY29uc3QgQWJvdXQgPSB7IHRlbXBsYXRlOiAnPGRpdj5BYm91dDwvZGl2PicgfVxuXG4vLyAyLiBEZWZpbmUgc29tZSByb3V0ZXNcbi8vIEVhY2ggcm91dGUgc2hvdWxkIG1hcCB0byBhIGNvbXBvbmVudC5cbi8vIFdlJ2xsIHRhbGsgYWJvdXQgbmVzdGVkIHJvdXRlcyBsYXRlci5cbmNvbnN0IHJvdXRlcyA9IFtcbiAgeyBwYXRoOiAnLycsIGNvbXBvbmVudDogSG9tZSwgbmFtZTogXCJob21lXCIgfSxcbiAgeyBwYXRoOiAnL2Fib3V0JywgY29tcG9uZW50OiBBYm91dCwgbmFtZTogXCJhYm91dFwiIH0sXG5dXG5cbi8vIDMuIENyZWF0ZSB0aGUgcm91dGVyIGluc3RhbmNlIGFuZCBwYXNzIHRoZSBgcm91dGVzYCBvcHRpb25cbi8vIFlvdSBjYW4gcGFzcyBpbiBhZGRpdGlvbmFsIG9wdGlvbnMgaGVyZSwgYnV0IGxldCdzXG4vLyBrZWVwIGl0IHNpbXBsZSBmb3Igbm93LlxuY29uc3Qgcm91dGVyID0gVnVlUm91dGVyLmNyZWF0ZVJvdXRlcih7XG4gIC8vIDQuIFByb3ZpZGUgdGhlIGhpc3RvcnkgaW1wbGVtZW50YXRpb24gdG8gdXNlLiBXZSBhcmUgdXNpbmcgdGhlIGhhc2ggaGlzdG9yeSBmb3Igc2ltcGxpY2l0eSBoZXJlLlxuICBoaXN0b3J5OiBWdWVSb3V0ZXIuY3JlYXRlV2ViSGFzaEhpc3RvcnkoKSxcbiAgcm91dGVzLCAvLyBzaG9ydCBmb3IgYHJvdXRlczogcm91dGVzYFxufSlcblxuLy8gNS4gQ3JlYXRlIGFuZCBtb3VudCB0aGUgcm9vdCBpbnN0YW5jZS5cbmNvbnN0IGFwcCA9IFZ1ZS5jcmVhdGVBcHAoe1xuICAgIGNvbXB1dGVkOiB7XG4gICAgICAgIHVzZXJuYW1lKCkge1xuICAgICAgICAvLyBXZSB3aWxsIHNlZSB3aGF0IGBwYXJhbXNgIGlzIHNob3J0bHlcbiAgICAgICAgICAgIGNvbnNvbGUubG9nKCduYW1lJywgdGhpcy4kcm91dGUubmFtZSk7XG4gICAgICAgICAgICByZXR1cm4gdGhpcy4kcm91dGUubmFtZVxuICAgICAgICB9LFxuICAgIH1cbn0pXG4vLyBNYWtlIHN1cmUgdG8gX3VzZV8gdGhlIHJvdXRlciBpbnN0YW5jZSB0byBtYWtlIHRoZVxuLy8gd2hvbGUgYXBwIHJvdXRlci1hd2FyZS5cbmFwcC51c2Uocm91dGVyKVxuXG5hcHAubW91bnQoJyNhcHAnKVxuPC9zY3JpcHQ In0=)

### Steps to reproduce
"vue": "^3.1.5",
 "vue-router": "^4.0.10",

For initial launch,  the name is undefined.
... Route:
const routes = [
  { path: '/', component: Home, name: "home" },
  { path: '/about', component: About, name: "about" },
]
... Vue

const app = Vue.createApp({
    computed: {
        username() {
            console.log('name', this.$route.name);
            return this.$route.name
        },
    }
})

### What is expected?
It should be always return route name, not undefined 

### What is actually happening?
The compute method is trigger twice,  the first time this.$route.name is undefined, second time is the expected name.

**Comment by posva** [comment]
This is expected and had been explained in other issues in Vue router best repo
