### ISSUE TITLE
Add state to route

### ISSUE THREAD

**Issue by xlaussel** [vuejs/vue-router#3620]
### What problem does this feature solve?
When using client-side routing I would like to preserve the display state of history entries. For example for a table with filter and/or order functionnality, it would allow to restore the applied filter and/or order when displaying the table again.
The scrollBehavior using savedPosition already permits to do it for the scroll position.

### What does the proposed API look like?
Implement any feature similar to the scrollBehavior
or
add a mutable state attribute to the route object

**Comment by posva** [comment]
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏
