### ISSUE TITLE
addRoute 动态添加添加异常

### ISSUE THREAD

**Issue by seechangan** [vuejs/vue-router#3623]
### Version
3.5.2

### Reproduction link
[codepen.io](https://codepen.io/code-show/pen/qBjObbo)

### Steps to reproduce
1.在main.js中 ， vue实例化之前调用router.beforeEach
2.在router.beforeEach钩子中调用 getAsyncRouter addRouter函数 完成动态路由添加
3.执行router.beforeEach中的next()

### What is expected?
希望能正常显示我动态添加的路由页面 例如:aa.vue页面

### What is actually happening?
停在当前动态路由页面刷新之后页面显示空白，无任何内容

**Comment by posva** [comment]
That is not a valid repro. Also open issues in English, thank you
