### ISSUE TITLE
Router link is bugged while rendering child component when the :to prop is given with the name of the route

### ISSUE THREAD

**Issue by ahmetyaziciDEFY** [vuejs/vue-router#3630]
### Version
3.5.2

### Reproduction link
[stackoverflow.com](https://stackoverflow.com/questions/69138337/vue-router-link-does-not-render-the-children-routes)

### Steps to reproduce
- Click on the router link from the Home page

### What is expected?
Expected to see the MainLayout and under that the InventoryManager page.

### What is actually happening?
After clicking router link, only MainLayout is rendered and InventoryManager is not rendered.

---
PS: When I refresh the page while at /inventory-manager, InventoryManager is rendered, but when I click to router-link InventoryManager is not rendered.
When I changed the 'to' prop from {name: 'InventoryManager'} to '/inventory-manager', it started to work

**Comment by posva** [comment]
That's not a valid repro
