### ISSUE TITLE
router.beforeEach doesn't work in safari

### ISSUE THREAD

**Issue by vinocturne** [vuejs/vue-router#3631]
### Version
3.5.2

### Reproduction link
[codepen.io](https://codepen.io/hago617/pen/wveqQem)

### Steps to reproduce
I'm trying to use 'router.beforeEach' for checking token. chrome can enter in beforeEach, but safari couldn't.

is there anything I have to know before use 'beforeEach' in safari? I'm so confused and this problem makes me crazy.

here is code. there are meta : {authRequired: true} every components except login component.

```javascript
router.beforeEach(function (to, from, next) {
console.log("I'm in!!!")
let token = VueCookies.get('jwtToken');
let isAuthenticated = token !== null;

if (to.matched.some(function(routerInfo) {
  return routerInfo.meta.authRequired;
})) {
  if(!isAuthenticated) {
    if(to.name != 'login') {
      next({name: 'login'});
    }
  }else {
    next();
  }
}else {
  next();
}
})
```

### What is expected?
When the token expires, I want to go through beforeEach and go to the login page if the conditions is right

### What is actually happening?
google chrome work fine. I can see console.log, 'i'm in!' and works very well.

but safari doesn't show console.log('i'm in!!'), and even can't get in beforeEach.

**Comment by posva** [comment]
That's not a valid reproduction
