### ISSUE TITLE
文档写错了

### ISSUE THREAD

**Issue by CarlKong** [vuejs/vue-router#3634]
### Version
3.5.2

### Reproduction link
[router.vuejs.org/zh/guide/](https://router.vuejs.org/zh/guide/#javascript)

### Steps to reproduce
链接页面的最后一个代码块中的代码写错了$route, 正确的应该是$router, 很影响理解

### What is expected?
期望修改成$router

### What is actually happening?
写错单词，会导致无法理解router的注入

**Comment by posva** [comment]
Use the chat or forum for questions, thanks.
