### ISSUE TITLE
[Feature] router.go support object-style query string

### ISSUE THREAD

**Issue by gouflv** [vuejs/vue-router#365]
object-style query string maybe a good idea on store some object to query without merge then,
just like jquery.param() do:
`
obj = {
  a: {
    one: 1,
    two: 2,
    three: 3
  }
}
`==> `a[one]=1&a[two]=2&a[three]=3`

**Comment by paulohp** [comment]
@yyx990803 is there someone implementing this? How can I help?

**Comment by agonbina** [comment]
@paulohp the [qs](https://github.com/ljharb/qs#parsing-objects) library supports this, maybe see how it's implemented there and submit a PR? :)

**Comment by cve** [comment]
I'm working on advanced data-table component and this functionality is "must have", cause I want to implement saving state of filters and pagination in query strings

**Comment by seaneagan** [comment]
vue-resource [does this](https://github.com/pagekit/vue-resource/blob/develop/src/url/index.js#L115).  Perhaps vue-resource and vue-router should shared a common vue-url module or similar?

**Comment by yyx990803** [comment]
@seaneagan this issue is for 0.7 and is outdated. 2.x already supports this.

**Comment by seaneagan** [comment]
It looks like the [latest code](https://github.com/vuejs/vue-router/blob/3f91065e5165d0457ee6295980086b86e107d034/src/util/query.js#L67) does support Arrays, but with `?foo=1&foo=2` rather than `?foo[]=1&foo[]=2` (like vue-resource), and it doesn't support objects e.g. `?foo[a]=1&foo[b]=2&foo[c]=3` (like vue-resource), you will instead get e.g. `?foo=[object Object]`

**Comment by Danita** [comment]
Why is this closed? Is this a "wontfix"? As of vue-router@3.0.1 is still unsolved:

`{ "filter": { "title": "bla", "actions": 1 } }` 

returns

`?filter=%5Bobject%20Object%5D`

Are there any official workarounds?

**Comment by posva** [comment]
in vue-router 3 you have to provide a custom and more powerful query parser (like https://github.com/ljharb/qs) to vue-router: https://router.vuejs.org/api/#parsequery-stringifyquery

**Comment by Danita** [comment]
Thanks, I just found #1259 with the explanation :)
