### ISSUE TITLE
Why is '+' replaced by ' '?

### ISSUE THREAD

**Issue by silverbulletlee** [vuejs/vue-router#3651]
### Version
3.5.2

### Reproduction link
[github.com](https://github.com/silverbulletlee/issue4vue-router)

### Steps to reproduce
1.clone repo
2.npm install
3.npm run serve
4.click 'bar: click show A+B'
5.look parma

### What is expected?
param should be 'A+B'

### What is actually happening?
it's 'A B' now

**Comment by posva** [comment]
As shown in other issues, it's for better cross-site interoperability.

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by silverbulletlee** [comment]
> As shown in other issues, it's for better cross-site interoperability.
> 
> Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

thank you～
