### ISSUE TITLE
[vue js] request

### ISSUE THREAD

**Issue by pipiscrew** [vuejs/vue-router#3655]
### What problem does this feature solve?
Apart from the fabulous online doc, is any possibility for a matrix between vue2 with npm vs vue2. ASAP a complete example
vue2 with routing.

A dozen of information can be found on net with many differences between versions.

the sample 
https://router.vuejs.org/guide/#javascript

```js
const routes = [
  { path: '/foo', component: Foo },
  { path: '/bar', component: Bar }
]
```

how to declare the router, so after can say
```js
router.push({ name: 'Foo' })
```

found the 
https://github.com/FranckFreiburger/vue3-sfc-loader

but has **2mb** dependency  :grinning:

### What does the proposed API look like?

%

**Comment by posva** [comment]
Pushing by name is already in the docs 🤔 
If you have a formal proposal, the best would be to open a PR.

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by pipiscrew** [comment]
@posva 

this is what was looking for
https://github.com/pipiscrew/vue3_small_prjs/tree/main/vue2vanilla_retain_PHPSessionCookie
