### ISSUE TITLE
Redirect error message needs more clarity

### ISSUE THREAD

**Issue by ffxsam** [vuejs/vue-router#3658]
### What problem does this feature solve?
Regarding this:
https://github.com/vuejs/vue-router/blob/677f3c1f714fb61cc495345e535409b1cbb90429/src/util/errors.js#L14-L16

This error message is unclear. Why is redirection an issue, exactly? What really happened here to raise an exception, and how should the developer address it?

### What does the proposed API look like?
N/A

**Comment by posva** [comment]
The thing is it's not an error, it's a navigation failure. It happened when you do next('/other-location'). This is documented.

Remember to use the discord chat to ask questions 🙂
