### ISSUE TITLE
How can I use `vue-router`subRoutes along with async components for lazy loading? 

### ISSUE THREAD

**Issue by alexisgaillard** [vuejs/vue-router#366]
Hi,

I'm trying to use async components with subRoutes, but doesn't work. For ex:

```js
import Vue from 'vue';
import VueRouter from 'vue-router';

Vue.use(VueRouter)

const router = new VueRouter({history: true});

router.map({

  '/':  {
  	name: 'root',
        component: function (resolve) {
            require(['./components/root'], resolve)
        },  
    subRoutes: {
      '/sub': {
        name: 'rootSub',
        component: function (resolve) {
          require(['./components/rootSub'], resolve)
        }
      }
    }
  }

})

export default router;
```

**Comment by repsac-by** [comment]
Path to the components must have extension

**Comment by tejitak** [comment]
I think we can close this issue.

**Comment by transtone** [comment]
@repsac-by  @tejitak 
https://github.com/vuejs/vue-router/blob/dev/example/advanced/route-config.js#L39
when replace this line from 
```component: require('./components/inbox/index.vue'),``` 
to
```component: (resolve) => require(['./components/inbox/index.vue'], resolve),```
it does not work. 

but change this line works fine:
https://github.com/vuejs/vue-router/blob/dev/example/advanced/route-config.js#L10
