### ISSUE TITLE
next in beforeEach is useless when we call addRoute in beforeEach

### ISSUE THREAD

**Issue by xialvjun** [vuejs/vue-router#3660]
### Version
3.5.3

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/eloquent-elgamal-zdwdq?file=/src/router/index.js)

### Steps to reproduce
At the first, you are in `/route1`, you can click 'home', '/route2', '/route1', that's all ok. 
But the first time you click '/route3', you can not see it. You must click '/route3' the second time, it will show.

### What is expected?
The first time we click `/route3`, it will show.

### What is actually happening?
route3 didn't show at the first time it been clicked.

---
Why do we transitionTo START after we addRoute? https://github.com/vuejs/vue-router/blob/dev/src/index.js#L257-L259

It seems there is a bug. When we call addRoute in beforeEach, next will be useless.

When we navigation to a route, router.history.pending = route (https://github.com/vuejs/vue-router/blob/dev/src/history/base.js#L139) . Then we call addRoute, and addRoute calls trnasitionTo, it will change the pending to currentLocation, so we call next will be ignored (https://github.com/vuejs/vue-router/blob/dev/src/history/base.js#L192-L194).

**Comment by posva** [comment]
You need to trigger a redirect to resolve again so it includes the newly added route:

```js
let hasAdded = false;
router.beforeEach((to, from, next) => {
  if (!hasAdded && to.path === "/route3") {
    router.addRoute(
      {
        path: "/route3",
        name: "route3",
        component: () => import("@/views/Route3.vue")
      }
    );
    hasAdded = true;
    next('/route3');
    return;
  }
  next();
});
```

**Comment by xialvjun** [comment]
https://github.com/vuejs/vue-router/issues/1926 this issue is in fact the same as mine.

If `addRoute` need we call next with specilize arguments, can you write it on the doc? @posva
