### ISSUE TITLE
vue-router命名路由 /detail/:id 打包后部署刷新不能加载?

### ISSUE THREAD

**Issue by ghost** [vuejs/vue-router#3663]
### What problem does this feature solve?
vue-router命名路由 /detail/:id 打包后部署刷新不能加载?

### What does the proposed API look like?
vue-router命名路由 https://next.router.vuejs.org/zh/guide/essentials/named-routes.html

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
