### ISSUE TITLE
Delayed start for fetching routes data

### ISSUE THREAD

**Issue by iBobik** [vuejs/vue-router#3668]
### What problem does this feature solve?
Some apps does not know routes structure in a compile time, but have to fetch some data in a run time. My use-case is content app which have to download content from CMS and then generate routes.

But currently in a meantime it reports "[Vue Router warn]: No match found for location with path". After routes loaded I have to call this.$router.replace(this.$route.fullPath).

### What does the proposed API look like?
Option like start: false in createRouter.
Method like router.start().

Or just document how to solve it by current API. There are [some workarounds](https://github.com/vuejs/vue-router/issues/1377#issuecomment-368498552), but they feels like a hacking.

**Comment by posva** [comment]
The warning is okay, it helps people figure out typos too. This is documented in v4: https://next.router.vuejs.org/guide/advanced/dynamic-routing.html. It's similar to v3
