### ISSUE TITLE
Scroll to top not working in fire

### ISSUE THREAD

**Issue by wontone18** [vuejs/vue-router#3669]
Hi

I am using vue router in my laravel application. I am facing a issue that when any body moving down from the home page and redirecting to any inner page then its not scrolling top of that selected page. But scroll behaviour working very smoothly in chrome, edge etc. But in firefox i have to use a alternative method to scroll top.

My route code is

```
const router = new VueRouter({
//  mode: 'history',
scrollBehavior (to, from, savedPosition) {
  if (savedPosition) {
    return savedPosition
  } else {
    return { x: 0, y: 0 }
  }
},
  routes: routes
});
```

My alternative method is mention below. But i dont want to go with this method. 

```
 mounted() {
            setTimeout(() => {
            document.body.scrollTop = document.documentElement.scrollTop = 0;
            }, 500);
            }
```

**Comment by cervonwong** [comment]
Yes, can confirm that it doesn't work in Firefox and your alternative method works. Interestingly, it doesn't work only when routing to a screen which is shorter than the current scroll position. Also if the scroll-behavior css property is not smooth, it works fine.
