### ISSUE TITLE
strange behavior router.go() or component ready() function

### ISSUE THREAD

**Issue by LuckyBlade** [vuejs/vue-router#367]
I have 2 components. Component A on route '/a' and component B on route '/b'. In comp B I have the code :
```
ready(){
   this.$route.router.go('/a') ;
}
```
Now in browser If I try to go from route '/a' to route '/b' I see both components A and B but in address line there is '/a'.
If code will be : 
```
ready(){
   sleepTimeout(()=>{this.$route.router.go('/a') ;},0);
}
```
Everything will be ok and if I try to go from route '/a' to route '/b' I see only component A again on route '/a'.

**Comment by jabyrd3** [comment]
I'm experiencing this in a component for catching an auth token from an OAUTH 2 redirect. the timeout solution works for now, but I'd rather not rely on window.setTimeout hacks all over.

**Comment by yyx990803** [comment]
This should work, but before it's fixed, the more proper way to do redirects is calling `transition.redirect` inside route hooks instead of `ready`.

**Comment by jabyrd3** [comment]
Thanks for the quick response and the pointer!

**Comment by tejitak** [comment]
@LuckyBlade Is this issue occurred when the url '/b' is directly accessed (not clicking v-link)?

I found the `router._rendered` flag here https://github.com/vuejs/vue-router/blob/dev/src/pipeline.js#L186 is still false at an initial route redirection in `ready` by default.

The `transitionOnLoad` would be nice option when you want to make transition successfully before all renderings are done.

```js
const router = new VueRouter({
  history: true,
  saveScrollPosition: true,
  transitionOnLoad: true
})
```

**Comment by LuckyBlade** [comment]
@tejitak  Yes, it's occurred when directly accessed.
After setting "transitionOnLoad: true" in config everything works fine. Thank you.
