### ISSUE TITLE
router.currentRoute.value is reset to homepage when saving with Vite HMR activated

### ISSUE THREAD

**Issue by GueganVictor** [vuejs/vue-router#3671]
### Version
4.0.12

### Reproduction link
[stackblitz.com](https://stackblitz.com/edit/vite-82dmj6?devtoolsheight=33&file=src/App.vue)

### Steps to reproduce
Create vue router add a route to it
Add it to Vue 
Navigate to said page, the value of the currentRoute is correctly set
Make any change to the componenet where currentRoute.value is called, save
The page will reload with Vite HMR
Value of the currentRoute is set to the homepage

### What is expected?
The currentRoute should still be equal to the route we are currently on

### What is actually happening?
The currentRoute value isn't properly set

---
Thought it had to do with params at first since it was the only time i was using currentRoute.value.params.xxx but it seems to affect every page.

I made a gif showing to situation for clarification : 

![Animation](https://user-images.githubusercontent.com/26070848/143688237-5d116194-dd32-43ec-a98e-9cb992ad516c.gif)

**Comment by posva** [comment]
This is because you are importing the router so the HMR also refreshes that part. Call `useRouter()` instead.

BTW this is vue router 3 repository, not 4, which is at vue-router-next

**Comment by GueganVictor** [comment]
Okey thanks a lot, sorry about that 😬
