### ISSUE TITLE
Safari scrollBehavior key is undefined but exists

### ISSUE THREAD

**Issue by archieDeveloper** [vuejs/vue-router#3674]
### Version
3.5.3

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/safari-scrollbehavior-gh2fx)

### Steps to reproduce
Click on the router-link in safari.

### What is expected?
Smooth scrolling

### What is actually happening?
Scroll quickly to an element

---
https://github.com/vuejs/vue-router/blob/cb4c16398bf25aaa2c5d755faa480ad1e81cd756/src/util/scroll.js#L164

This line returns `false`. I'm using a safari [polyfill](https://github.com/iamdustan/smoothscroll) that enables smooth scrolling with `window.scrollTo`, but smooth scrolling doesn't work because `vue-router` uses a different interface with two arguments.

`window.scrollTo(x, y)` instead of `window.scrollTo({ top, left })`

An even more interesting situation arises when you execute code in the browser console: `Object.keys(document.documentElement.style).includes('scrollBehavior')`

This code will return `true`, because the `scrollBehavior` key is present in the object.

**Comment by posva** [comment]
> This line returns false

That's something the polyfill needs to fix. It's the recommended way to check for the availability of the feature.

> window.scrollTo(x, y) instead of window.scrollTo({ top, left })

That is also something the polyfill needs to support because older browsers only have that method
