### ISSUE TITLE
In Named Views, When using a name, other name's BeforeRouteEnter will be triggered 

### ISSUE THREAD

**Issue by ppp122** [vuejs/vue-router#3682]
### What problem does this feature solve?
I don’t want one naming to affect another naming in Named View.
For Example, 
routes.js:

```
export const routers = [
    {path: '', name:'home', components: {
            default: Home,
            'ppptest': UserDetail,
        }
    }
]
```

UserDetail.vue:

```
<script>
  export default {
    beforeRouteEnter(to, from, next) {
      console.log('before router enter');
      next(false);
    }
  }
</script>

```
then when I go to "{path: '/'}" , UserDetail's beforeRouteEnter will be triggered causing the jump to fail.

### What does the proposed API look like?
When I don’t use a name in Named View, I don’t want it to affect my program

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
