### ISSUE TITLE
Route's query should be frozen

### ISSUE THREAD

**Issue by zuoez02** [vuejs/vue-router#3684]
### Version
3.5.3

### Reproduction link
[github.com](https://github.com/zuoez02/vrouter-deeply-shallow)

### Steps to reproduce
1. `yarn serve` and access `http://localhost:8080/?value=123&value=456`
2. Click `click` button. It will do following steps:
```javascript
      this.value = this.$route.query.value;
      console.log(this.value);
      await this.$nextTick();
      this.value.splice(0, this.value.length);
      this.$router.replace({
        name: this.$route.name,
        query: {
          value: [],
        },
      });
      await this.$nextTick();
      console.log(this.$route.query);
```
3. The URL not changed to `http://localhost:8080/`

### What is expected?
The url should be `http://localhost:8080/`.

### What is actually happening?
URL not changed.

---
Debugged in Edge devtool, found that the `query` in `current` in HTML5History is changed to `[]`, and it seems like same when compare `route` and `current`. I think the `route` object should be deeply frozen, not shallowed, or user can change the route.query and the router will run mistake.

Actually, I found the problem when I try to use `stringifyQuery` and `parseQuery` API when create router instance. I want to use add object to route.query but I don't like `JSON.stringify`, it's too long. I try to use `rison` to stringify and parse query. The `rison` is using in Elastic Kibana, which URL is funny.

**Comment by posva** [comment]
This is expected and documented, you need to create a copy:

```js
this.value = [...this.$route.query.value];
```

**Comment by zuoez02** [comment]
@posva Where is it documented? Sorry but I can't find it in `https://router.vuejs.org/`
