### ISSUE TITLE
about getRoutes(), how to know router's parent?

### ISSUE THREAD

**Issue by zhoufanglu** [vuejs/vue-router#3685]
### Version
4.0.0

### Steps to reproduce
I added a child route to a route called Home,
`router.addRoute("home", childRouter)`
below is the add childRouter.
How do I know childRouter parent route is?
![image](https://user-images.githubusercontent.com/24451091/146730549-43d43e94-f9d9-4660-95a2-5e8d68cd691b.png)
### but in "vue-router": "^3.5.2"
![image](https://user-images.githubusercontent.com/24451091/146731052-9ef4a9fa-b662-4c1f-be66-06ea83c147b5.png)

---

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by zhoufanglu** [comment]
> Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
Sorry, I only know how to use Github at present. Can you open the question? Can someone else solve this problem?
