### ISSUE TITLE
$router.push() with the query including number query, the number query will change to string query after reload page.

### ISSUE THREAD

**Issue by ElvisUpUp** [vuejs/vue-router#3687]
### Version
3.5.3

### Reproduction link
[codepen.io/E1vis/pen/LYzemaV](https://codepen.io/E1vis/pen/LYzemaV?editors=1111)

### Steps to reproduce
1. run the reproduction code.
2. click "to pageA" and can console the type of query "test" is "number".
3. click "reload" reload the page.
4. see console the type of query "test" is "string".

### What is expected?
The type of query don't change.

### What is actually happening?
The type of query will change after reload page.

**Comment by posva** [comment]
This is intended as anything coming from the URL (a string) will always be a string.
