### ISSUE TITLE
use useRouter() outside setup()

### ISSUE THREAD

**Issue by 467057463** [vuejs/vue-router#3690]
### What problem does this feature solve?
use useRouter() outside setup()

### What does the proposed API look like?
``` jsx
import { ref } from "vue"
import { useRouter } from 'vue-router'

const num = ref(0)
const router = useRouter();
export const Test = (props, ctx) => {
  return (
    <div onClick={() => router.push('/login') }>
      test {num.value}
    </div>
  )
}
```

**Comment by 467057463** [comment]
i konw now called `useRouter()` msut be inside of `setup()`.

when i try use vue function component with JSX, is every flexable, but this code pattern can't use useRouter(), a little regret 😶.

hope next version can consider function component pattern 😁

thanks all, thanks vue-router team.

**Comment by posva** [comment]
It can only be used where `inject()` can be called, this is by design. You can still directly import the router instance when not doing SSR
