### ISSUE TITLE
The routing home page in abstract mode cannot display content

### ISSUE THREAD

**Issue by yangdan8** [vuejs/vue-router#3697]
### Version
3.5.3

### Reproduction link
[github.com](https://github.com/yangdan8/vue2-router-abstract-error.git)

### Steps to reproduce
git clone https://github.com/yangdan8/vue2-router-abstract-error.git
npm i
npm run serve

### What is expected?
display home content

### What is actually happening?
cannot display home content

---
This demo is only an official demo Change the routing mode to abstract

**Comment by posva** [comment]
In memory mod eyou need to trigger the initial navigation.

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
