### ISSUE TITLE
bower 里没有么？

### ISSUE THREAD

**Issue by Dreampie** [vuejs/vue-router#37]

**Comment by yyx990803** [comment]
vue-router 还没有正式发布，目前只能直接用 github 地址安装。

**Comment by Dreampie** [comment]
对前端不是很了解，能不能像maven一样，提供一个snapshot版和一个release版，snapshot可以快速发布和更新

**Comment by yyx990803** [comment]
你可以直接 `bower install vuejs/vue-router#master`

**Comment by Dreampie** [comment]
bower.json  这么用的，vue-bootstrap  还是空的

```
{
  "name": "acfun-mobile-cms",
  "dependencies": {
    "bootstrap": "~3.3.5",
    "vue": "~0.12.4",
    "vue-resource": "~0.1.3",
    "vue-validator": "~1.1.1",
    "vue-router": "git@github.com:vuejs/vue-router.git"
  }
}
```

**Comment by Dreampie** [comment]
webpack  vue-router 加载不了.... 
![image](https://cloud.githubusercontent.com/assets/3667080/8498582/359f7b1e-21bb-11e5-8ece-5e200efcbffa.png)
