### ISSUE TITLE
router-view is functional component which should not be used with keep-alive

### ISSUE THREAD

**Issue by yuwu9145** [vuejs/vue-router#3701]
### Version
3.5.3

### Reproduction link
[github.com](https://github.com/vuejs/core/issues/5207)

### Steps to reproduce
According to [keepAlive official doc](https://v3.vuejs.org/api/built-in-components.html#keep-alive)

> keep-alive does not work with functional components because they do not have instances to be cached.

However, according to [router-view doc](https://router.vuejs.org/api/#router-view), `RounterView` is a functional component.

this results in issue which can be reproduced in https://github.com/vuejs/core/issues/5207

### What is expected?
RounterView should work correctly with keep-alive

### What is actually happening?
RounterView  does not work correctly with keep-alive and two official documents are contradictive.

**Comment by LinusBorg** [comment]
1. You are in the wrong repository. VueRouter 4 lives art https://github/vuejs/router
2. You have read the wrong docs, which until very soon still live at next.router.vuejs.org
3. The quote from the docs talks about KeepAlive wrapping a functional component *directly*. It does not mean *any nested child*

Please open a new issue in https://github.com/vuejs/router if you still think this needs to be adressed in the router.
