### ISSUE TITLE
firefox navigation bug

### ISSUE THREAD

**Issue by 332lfgb6** [vuejs/vue-router#3703]
### Version
3.5.3

### Reproduction link
[github.com](https://github.com/332lfgb6/vue-router-bug)

### Steps to reproduce
View the readme file in the repository

### What is expected?
Firefox desktop doesn't have a back button in the upper left corner; Firefox mobile exits the desktop by pressing the Back button once.

### What is actually happening?
In the desktop version of Firefox, there will be an extra back button. In the mobile version of Firefox, you need to press the back button twice to exit the desktop.

---
Copied to the firefox mobile tests, using http://xxx.xxx.xxx.xxx:8080/, not http://xxx.xxx.xxx.xxx:8080/about

**Comment by posva** [comment]
This is just different browsers behaviors, it's not related to how vue router handles things.
