### ISSUE TITLE
[...] is not assignable to type 'NavigationGuardReturn | Promise<NavigationGuardReturn>'

### ISSUE THREAD

**Issue by huzaifahj** [vuejs/vue-router#3704]
### Version
3.5.3

### Reproduction link
[sfc.vuejs.org/](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxpbnB1dCB2LW1vZGVsPVwibXNnXCI+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vc2ZjLnZ1ZWpzLm9yZy92dWUucnVudGltZS5lc20tYnJvd3Nlci5qc1wiXG4gIH1cbn0iLCJtYWluLnRzIjoiaW1wb3J0IHsgY3JlYXRlUm91dGVyLCBjcmVhdGVXZWJIaXN0b3J5IH0gZnJvbSBcInZ1ZS1yb3V0ZXJcIlxuaW1wb3J0IHsgdXNlQXV0aFN0b3JlIH0gZnJvbSBcIkAvc3RvcmVzL2F1dGhcIlxuXG5jb25zdCByb3V0ZXIgPSBjcmVhdGVSb3V0ZXIoe1xuICAgIGhpc3Rvcnk6IGNyZWF0ZVdlYkhpc3RvcnkoaW1wb3J0Lm1ldGEuZW52LkJBU0VfVVJMKSxcbiAgICByb3V0ZXM6IFtcbiAgICAgICAge1xuICAgICAgICAgICAgcGF0aDogXCIvXCIsXG4gICAgICAgICAgICBuYW1lOiBcIkRhc2hib2FyZFwiLFxuICAgICAgICAgICAgY29tcG9uZW50OiBpbXBvcnQoXCIuLi92aWV3cy9EYXNoYm9hcmQudnVlXCIpLFxuICAgICAgICB9LFxuICAgICAgICB7XG4gICAgICAgICAgICBwYXRoOiBcIi9sb2dpblwiLFxuICAgICAgICAgICAgbmFtZTogXCJMb2dpblwiLFxuICAgICAgICAgICAgY29tcG9uZW50OiAoKSA9PiBpbXBvcnQoXCIuLi92aWV3cy9Mb2dpbi52dWVcIiksXG4gICAgICAgICAgICBtZXRhOiB7XG4gICAgICAgICAgICAgICAgbG9naW46IHRydWUsXG4gICAgICAgICAgICB9LFxuICAgICAgICB9LFxuICAgIF0sXG59KVxuXG5yb3V0ZXIuYmVmb3JlRWFjaCgodG8sIGZyb20pID0+IHtcbiAgICBjb25zdCBhdXRoID0gdXNlQXV0aFN0b3JlKClcblxuICAgIGlmICh0by5tYXRjaGVkLnNvbWUoKHJlY29yZCkgPT4gcmVjb3JkLm1ldGEucHVibGljKSkge1xuICAgICAgICAvLyBQdWJsaWMgcGFnZXNcbiAgICAgICAgcmV0dXJuIHRydWVcbiAgICB9IGVsc2UgaWYgKHRvLm1hdGNoZWQuc29tZSgocmVjb3JkKSA9PiByZWNvcmQubWV0YS5sb2dpbikpIHtcbiAgICAgICAgLy8gTG9naW4gcGFnZVxuICAgICAgICByZXR1cm4gYXV0aC5pc0xvZ2dlZEluID8geyBuYW1lOiBcIkRhc2hib2FyZFwiIH0gOiB0cnVlXG4gICAgfSBlbHNlIHtcbiAgICAgICAgLy8gUHJpdmF0ZSBwYWdlc1xuICAgICAgICByZXR1cm4gYXV0aC5pc0xvZ2dlZEluXG4gICAgICAgICAgICA/IHRydWVcbiAgICAgICAgICAgIDoge1xuICAgICAgICAgICAgICAgICAgbmFtZTogXCJMb2dpblwiLFxuICAgICAgICAgICAgICAgICAgcXVlcnk6IHtcbiAgICAgICAgICAgICAgICAgICAgICByZWRpcmVjdDogZnJvbS5wYXRoLFxuICAgICAgICAgICAgICAgICAgICAgIHJlZGlyZWN0UXVlcnk6IGZyb20ucXVlcnlcbiAgICAgICAgICAgICAgICAgIH0sXG4gICAgICAgICAgICAgIH1cbiAgICB9XG59KVxuXG5leHBvcnQgZGVmYXVsdCByb3V0ZXJcbiJ9)

### Steps to reproduce
```
router.beforeEach((to, from) => {
    const auth = useAuthStore()

    if (to.matched.some((record) => record.meta.public)) {
        // Public pages
        return true
    } else if (to.matched.some((record) => record.meta.login)) {
        // Login page
        return auth.isLoggedIn ? { name: "Dashboard" } : true
    } else {
        // Private pages
        return auth.isLoggedIn
            ? true
            : {
                  name: "Login",
                  query: {
                      redirect: from.path,
                      redirectQuery: from.query
                  },
              }
    }
})
```

### What is expected?
No Typescript errors

### What is actually happening?
```
Argument of type '(this: undefined, to: RouteLocationNormalized, from: RouteLocationNormalized) => true | { name: string; query?: undefined; } | { ...; }' is not assignable to parameter of type 'NavigationGuardWithThis<undefined>'.
  Type 'true | { name: string; query?: undefined; } | { name: string; query: { redirect: string; redirectQuery: LocationQuery; }; }' is not assignable to type 'NavigationGuardReturn | Promise<NavigationGuardReturn>'.ts(2345)
```

**Comment by posva** [comment]
The error is correct:

```ts
                      redirectQuery: from.query
```

stringify `from.Query`, or rather pass the `fullPath` to `redirect`.

----

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
Note this is the repository for vue-router 3 for vue 2, not vue router 4 for vue 3 (which is the one you are using)
