### ISSUE TITLE
Add ability to edit routes

### ISSUE THREAD

**Issue by dospunk** [vuejs/vue-router#3706]
### What problem does this feature solve?
Right now we can edit a route by using `addRoute` with the same name as a currently existing route. This gets very difficult though if you want to edit a route that has children. Because the route's `children` property does not update when `addRoute` and `removeRoute` are used, to make a truly robust "edit route" function we would have to construct a new children array by searching through `router.getRoutes()` for the children's names to make sure that they still exist and are up to date. This gets even more complicated if a route's children have children. 

My use case is that I and trying to dynamically disable routes based on the capabilities of an API server, and I've run into a problem where a parent route needs to be unnavigable but its dynamic routes still need to be navigable. I would like to do this by simply setting the parent route to redirect to a 404 page rather than one of its children. 

### What does the proposed API look like?
I would propose a router function named `editRoute` that takes an existing route name and an object of changes to make to that route

```ts
router.editRoute(routeName: string | symbol, changes: Partial<RouteRecordRaw>): () => void
```

**Comment by posva** [comment]
This is too much of an app-specific feature to be added to the router. It can and should be implemented on the userland as we don't want to add the complexity and size to every user.
