### ISSUE TITLE
tag prop warning showing when its not used

### ISSUE THREAD

**Issue by hisuwh** [vuejs/vue-router#3716]
### Version
3.5.3

### Reproduction link
Not sure how to configure this thing to work properly

[sfc.vuejs.org/](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBWdWUsIHsgcmVmIH0gZnJvbSAndnVlJztcbmltcG9ydCBSb3V0ZXIgZnJvbSBcInZ1ZS1yb3V0ZXJcIjtcbiAgXG5WdWUudXNlKFJvdXRlcik7XG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8aW5wdXQgdi1tb2RlbD1cIm1zZ1wiPlxuICA8cm91dGVyLWxpbmsgdG89XCIvXCI+SG9tZTwvcm91dGVyLWxpbms+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vc2ZjLnZ1ZWpzLm9yZy92dWUucnVudGltZS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwidnVlLXJvdXRlclwiOiBcImh0dHBzOi8vdW5wa2cuY29tL3Z1ZS1yb3V0ZXIvZGlzdC92dWUtcm91dGVyLmpzXCJcbiAgfVxufSJ9)

### Steps to reproduce
Use vue-router

### What is expected?
Not to receive warning in the console if not using deprecated prop.

### What is actually happening?
Receiving warning in console:

`[vue-router] <router-link>'s tag prop is deprecated and has been removed in Vue Router 4. Use the v-slot API to remove this warning`

Despite no usages of the `tag` prop anywhere.

**Comment by posva** [comment]
Hello, make sure to always provide a reproduction that follows the instructions at https://new-issue.vuejs.org/?repo=vuejs/vue-next#why-repro.

Open a new issue with a reproduction that follows those instructions if you manage to create a boiled down reproduction.

**Comment by hisuwh** [comment]
If you want a reproduction why don't you do what other library authors do and provide a code sandbox already set up for your library.  The linked tool you provided is very hard to work with
