### ISSUE TITLE
Please create TypeScript definition file for VueRouter

### ISSUE THREAD

**Issue by dmitrijs** [vuejs/vue-router#372]
At the moment, only "vue" is available at http://definitelytyped.org/tsd/.

**Comment by NicolasParada** [comment]
+1

**Comment by yyx990803** [comment]
It's in the repo but for some reason not showing up in search. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/41f8573534b0fff88707d0a4cb870456b50cd43b/vue-router/vue-router.d.ts

**Comment by druppy** [comment]
Sorry to ask, but will it be included in the npm like vue and vue-class-component ?

It is so nice to be able to write vue code without typings :-)

**Comment by yyx990803** [comment]
@druppy yeah, we will likely do that in the future.

**Comment by meyerzinn** [comment]
For whatever reason, @yyx990803, the one in DefinitelyTyped doesn't have a router.map() function. Am I following outdated docs or is this an issue?

EDIT: My bad, it does have one, but WebStorm is freaking out about letting me use it.

**Comment by jeffcj** [comment]
@20zinnm If you're moving to Vue 2.x, router.map() has been deprecated in vue-router@next (VueJS 2.x) It has been replaced by the routes option.

**Comment by meyerzinn** [comment]
Oh. Thanks :). Never would've guessed there was a new router.
