### ISSUE TITLE
regexp is not applied when name is specified

### ISSUE THREAD

**Issue by fumifumitaro** [vuejs/vue-router#3724]
### Version
3.5.3

### Reproduction link
[github.com](https://github.com/fumifumitaro/bag-vue-router)

### Steps to reproduce
```
{
  path: "/user/:user_id(\\d+)",
  name: "User",
  component: "UserComponent"
}
```

I defined route like this.

```
router.push('/user/abc')
```

This successfully returns a 404 error.

```
router.push({
  name: 'User',
  params: {
    user_id: 'abc' // similarly when null
  }
})
```

regexp do not apply in this case, and UserComponent is displayed.

### What is expected?
regexp should be applied

### What is actually happening?
regexp is not applied when name is specified

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
