### ISSUE TITLE
Dynamic route has nested children routes, route-links generated 'a' tags with unexpected href

### ISSUE THREAD

**Issue by elderdog** [vuejs/vue-router#3725]
### Version
3.5.3

### Reproduction link
[codepen.io](https://codepen.io/elderdog/pen/bGYMmbM)

### Steps to reproduce
1.click 'GO to me'
2.inspect these 3 children to check the href
3.you will see these 3 'a' tags have different href which is expected to be the same

### What is expected?
3 links have same href

### What is actually happening?
3 links have different href

**Comment by posva** [comment]
This is how a relative link works. You can try with the URL object in the console to play around.

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
