### ISSUE TITLE
Add ability to goBackTo (pathname) 

### ISSUE THREAD

**Issue by tigohenryschultz** [vuejs/vue-router#3730]
### What problem does this feature solve?
Our app has pages that require a bluetooth connection, we need the ability to send the user back to a neutral page if they lose connection/disconnect.

 Something like router.goBackTo(pathname) would solve this problem.

### What does the proposed API look like?
new goBackTo method that finds the delta to invoke router.go with for navigating back

**Comment by posva** [comment]
Use a `router.push(pathname)`

**Comment by tigohenryschultz** [comment]
Yes but if the user clicks back then they would access invalid pages that require bluetooth connection.

Why would you just close this ticket?  @posva 

Theres no way to go back to a specific named page and always going forward is not a valid option.
