### ISSUE TITLE
vue router component object watch not working in firefox

### ISSUE THREAD

**Issue by fm-19** [vuejs/vue-router#3732]
### Version
3.5.1

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/sad-snow-dij6ot?file=/src/App.vue)

### Steps to reproduce
first：operating environment
   firefox： 46

two：run demo 

### What is expected?
watch data normal

### What is actually happening?
watch data is not working

**Comment by posva** [comment]
Can't reproduce but this also looks completely unrelated to router.

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
