### ISSUE TITLE
$route.matched returns the empty path when the path is /

### ISSUE THREAD

**Issue by Hill-98** [vuejs/vue-router#3734]
### Version
3.5.3

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/small-voice-m42vwr)

### Steps to reproduce
1. Open the reproduction link
2. View console output

### What is expected?
$route.matched[0].path = "/"

### What is actually happening?
$route.matched[0].path = ""

**Comment by posva** [comment]
This is a kinda internal behavior. `matched` is an array of the matched normalized records, so they are different from when they are added.

**Comment by Hill-98** [comment]
But isn't the empty path strange?
The problem I see is with the `normalizePath` function, which removes the trailing `/` when the `strict` parameter is `false`, which is not good for `/` paths.

**Comment by Hill-98** [comment]
VueRouter 4.x does not return the empty path but `/` on the `/` path, and I think VueRouter 3.x should do the same.
