### ISSUE TITLE
Cannot use 'in' operator to search for 'path' in undefined

### ISSUE THREAD

**Issue by gongzhx1998** [vuejs/vue-router#3735]
Cannot use 'in' operator to search for 'path' in undefined
![image](https://user-images.githubusercontent.com/51268072/160636305-dd0b7613-3887-4203-803b-f51c1ffe3d5b.png)
![image](https://user-images.githubusercontent.com/51268072/160636335-9160cece-1fbf-4ff9-98c3-7d6bd8d88418.png)
![image](https://user-images.githubusercontent.com/51268072/160636361-88edb262-749b-49f1-8aba-2c4509958fee.png)

**Comment by mohamed-alired** [comment]
i have the same setup and error

**Comment by extrem7** [comment]
@gongzhx1998 what was the solution of the problem?

**Comment by maisasb** [comment]
+1

**Comment by Muhamed-M** [comment]
Why is this closed ? What is causing the issue ?
