### ISSUE TITLE
Problem with default path ( / )

### ISSUE THREAD

**Issue by rascada** [vuejs/vue-router#374]
## error
`Uncaught TypeError: Cannot read property 'childNodes' of undefined`

## reproduction
- open app on `/` route
- then navigate to `/wykresy` 
- then again go to `/` 

also interesting  is when I open app with `/wykresy` route, everything work good. ( never throw that error )

## router config
```js
router.map({
  '/': {
    component(resolve) {
      require(['./views/weather'], resolve);
    },
  },
  '/wykresy': {
    component(resolve) {
      require(['./views/charts'], resolve);
    },
  },
});
```

## source code
https://github.com/rascada/Pogoda/tree/charts

### ps
1 component (without rest) have other behavior
##### on first load (`/` route)
![image](https://cloud.githubusercontent.com/assets/10521222/13030050/8cbc93f8-d29d-11e5-9824-5ed05b655189.png)
##### then go to `/wykresy` and back to `/` and now:
![image](https://cloud.githubusercontent.com/assets/10521222/13030057/e1f93236-d29d-11e5-847b-5d0399aa0b4b.png)

**Comment by rascada** [comment]
I think it has problem with web-components ( or polymer ), when I remove paper-material from all elements except cloud component now app work

after remove all paper-material (except clouds) paper-spinner, and paper-progress seems work good, but paper-tooltip crash after reproduction
## before reproduction
![image](https://cloud.githubusercontent.com/assets/10521222/13030214/b7001ac2-d2a2-11e5-9e94-983ef853340f.png)

## after reproduction
![image](https://cloud.githubusercontent.com/assets/10521222/13030217/c7a16fa2-d2a2-11e5-9c30-3cb52eb47cf6.png)

**Comment by rascada** [comment]
I temporary removed paper-material, so source code is here https://github.com/rascada/Pogoda/tree/374922c60ebd4815e77fa2f44f452cb0a6d9705f

**Comment by tejitak** [comment]
@rascada I checked your site https://pogoda.skalagi.pl/ But it looks working now.
The example code looks bit large to investigate an original issue. Also, I',m not sure it is vue.js bug or not from your description.
Can you provide a more clear code example or demo?

**Comment by rascada** [comment]
Web-components (paper elements for sure) don't work with router

pogoda-skalagi.pl always work because I don't publish broken app :P
and charts works because I remove web-components

**Comment by yyx990803** [comment]
I don't think it's specifically a `vue-router` issue, but rather a vue + polymer compatibility issue, so I'm closing this for now. It's a bit hard to identify the issue in a real app, if you can provide a minimal reproduction where Vue + Polymer is not working correctly, please open that in the main Vue.js repo. Thanks.
