### ISSUE TITLE
Select component by routes query

### ISSUE THREAD

**Issue by ItsPierre** [vuejs/vue-router#3740]
### What problem does this feature solve?
At the moment, it is not possible to show a different component by the query.

It should be possible to use the `?` as part of the route instead of just to make parts optional, possibly by escaping it.

### What does the proposed API look like?
```
{
  path: "/app/user\?userId=:userId",
  name: "user",
  component: UserView,
},
{
  path: "/app/user\?action=delete&userId=:userId",
  name: "user",
  component: DeleteUserView,
},
```

**Comment by posva** [comment]
This is intentional. You can still define custom query behavior within a navigation guard or directly use a query properly and named views together to build the behavior you want.
