### ISSUE TITLE
URL with line breaks are not properly managed

### ISSUE THREAD

**Issue by Frenchcooc** [vuejs/vue-router#3743]
### Version
3.5.3

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/vue-router-issue-with-history-mode-and-multiline-url-n4wd79)

### Steps to reproduce
From Codesandbox reproduction link:
1. Open Codesandbox
2. Click on "Click me"
3. The browser opens `example.org`

Locally:
1. Create a blank Vue app with vue-router
2. Add a link as follow: <router-link :to="url">Click me</router-link>
3. Specify a url with a line break such as :
```js
/
/example.com
```
4. Click the link, your browser will open `/example.com`

### What is expected?
It should trigger an error. Whether not a valid URL or not the same origin or redirect to `/`.
Or it should redirects to `//example.com` (removing line breaks)

### What is actually happening?
The browser opens `http://example.com`

---
The bug was reported to us by a bug hunter. 

One of our URL `https://dashboard.mailmeteor.com/login?redirect=%2F` was affected by the bug. If you share a URL to Mailmeteor having a line break in it, such as `https://dashboard.mailmeteor.com/login?redirect=%2F%0D%0A%2Fexample.com`, our application was redirecting to the distant domain. This has been fixed on our application by preventing redirection to URLs with multiple lines.

While looking at the source of this issue, turns out that vue-router codebase defaults to `window.location.replace` in case the `history.replaceState` methods triggers an error. See here: https://github.com/vuejs/vue-router/blob/677f3c1f714fb61cc495345e535409b1cbb90429/src/util/push-state.js#L40

And `window.location.replace(url)` has a "bug" that when you provide a url with a line break, it redirects to the last line:

```
var url = `/
/example.org`
window.location.replace(url) // opens "example.org"
```

**Comment by Frenchcooc** [comment]
First bug report on this repo. Feel free to change the title of the issue and let me know if you need more details :)

**Comment by posva** [comment]
I pushed a fix for this particular case because it is so easy to get wrong in userland but note that redirecting to a user-provided URL can always present a security risk. The app is responsible for sanitizing it if it wants to display it somewhere
