### ISSUE TITLE
addRouter execution sequence exception in beforEach

### ISSUE THREAD

**Issue by AIDeepx** [vuejs/vue-router#3745]
### Version
3.5.3

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/ecstatic-tharp-vm0buv?file=/src/router/index.js)

### Steps to reproduce

1. access url https://vm0buv.sse.codesandbox.io/#/collaborationoa/reimbursement/einvoicing/list
2. access url https://vm0buv.sse.codesandbox.io/#/collaborationoa/dissertation-review/project-list (history push or replace)

### What is expected?
I want to register the route once in the second step

### What is actually happening?
beforeEach is triggered every time addRouter is executed

**Comment by posva** [comment]
Always provide a minimal reproduction, it shouldn't contain +100 lines of custom logic. If you manage to reproduce it in a minimal environment open a new issue. BTW, you might not need to use `replace` when adding routes within a guard. This could also help: https://router.vuejs.org/guide/advanced/dynamic-routing.html#adding-routes-inside-navigation-guards

**Comment by surge-squirrel** [comment]
解决了这个问题吗？我也出现了同样的问题

**Comment by AIDeepx** [comment]
> 解决了这个问题吗？我也出现了同样的问题

我是用其他的方案处理掉的，因为这个方法在我的代码里是异步的，我是通过多次重定向直到获取到新的路由时放行

**Comment by surge-squirrel** [comment]
> > 解决了这个问题吗？我也出现了同样的问题
> 
> 我是用其他的方案处理掉的，因为这个方法在我的代码里是异步的，我是多次通过直到重定向获取到新的路由时放行
完全想不明白为什么会出现这个问题

**Comment by codeDevStory** [comment]
> > 解决了这个问题吗？我也出现了同样的问题
> 
> 我是用其他的方案处理掉的，因为这个方法在我里是异步的，我是多次通过直到重定向获取到新的路由时放行
我是在addRoute之前先`router.matcher = createRouter().matcher`这样，然后什么async  await根本不起作用，只要addRoute，他就会触发跳转

**Comment by surge-squirrel** [comment]
> > 解决了这个问题吗？我也出现了同样的问题
> 
> 我是用其他的方案处理掉的，因为这个方法在我里是异步的，我是多次通过直到重定向获取到新的路由时放行
我是用其他的方案处理掉的，因为这个方法在我里是异步的，我是多次通过直到重定向获取到新的路由时放行
我是在addRoute之前先`router.matcher = createRouter().matcher`，然后什么async  await都没用，只要addRoute，他就会触发跳转

**Comment by surge-squirrel** [comment]
> > 解决了这个问题吗？我也出现了同样的问题
> 
> 我是用其他的方案处理掉的，因为这个方法在我的代码里是异步的，我是通过多次重定向直到获取到新的路由时放行

你的vue-router是什么版本？

**Comment by codeDevStory** [comment]
I'm crazy

**Comment by AIDeepx** [comment]
> I'm crazy

 我的版本是3.5.4你是在业务上出现什么问题了吗？

**Comment by AIDeepx** [comment]
> 我是在addRoute之前先`router.matcher = createRouter().matcher`，然后什么async  await都没用，只要addRoute，他就会触发跳转

这行代码可以解决你的这个疑问，这是它的源码部分
![微信图片_20231023141205](https://github.com/vuejs/vue-router/assets/20198428/454cefae-a587-49a4-a6ae-946274a71e8d)

**Comment by surge-squirrel** [comment]
> > 我是在addRoute之前先`router.matcher = createRouter().matcher`，然后什么async  await都没用，只要addRoute，他就会触发跳转
> 
> 这行代码可以解决你的这个疑问，这是它的源码部分 ![微信图片_20231023141205](https://user-images.githubusercontent.com/20198428/277244332-454cefae-a587-49a4-a6ae-946274a71e8d.png)

唉，怎么说，反正跟你一样只要一addRoute就触发路由跳转，虽然也不是不能用，但是相比明白为啥啊

这段源码我看到了，但是addRoutes里面同样有这段源码，但是addRoutes没啥问题
