### ISSUE TITLE
`$route.query = { xxx: undefined }` affects `router-link-exact-active`

### ISSUE THREAD

**Issue by sws797** [vuejs/vue-router#3748]
### Version
3.5.3

### Reproduction link
https://codepen.io/sws797/pen/NWyraYK?editors=1111

### Steps to reproduce
click `<router-link to="/register">`  
-> browser's address bar: `http://localhost:8080/#/register`  
-> `<router-link to="/register">Register</router-link>` has `router-link-exact-active` and `router-link-active`  

click `<router-link :to="{ name: 'Register' }">`  
-> browser's address bar: `http://localhost:8080/#/register`  
-> `<router-link to="/register">Register</router-link>` has `router-link-exact-active` and `router-link-active`  

click `<router-link :to="{ name: 'Register', query = {} }">`  
-> browser's address bar: `http://localhost:8080/#/register`  
-> `<router-link to="/register">Register</router-link>` has `router-link-exact-active` and `router-link-active`  

BUT click  `<router-link :to="{ name: 'Register', query = { redirect: undefined } }">`  
-> browser's address bar: `http://localhost:8080/#/register`  
-> BUT `<router-link to="/register">Register</router-link>` only has `router-link-active`  

### What is expected?
The same browser's address bar get same router-link-exact-active

### What is actually happening?
Although the address bar is `/register`, different access methods have different effects

---
Do you have a more detailed description of `router-link-exact-active`? [https://v3.router.vuejs.org/zh/api/#exact-active-class](https://v3.router.vuejs.org/zh/api/#exact-active-class) has few descriptions

**Comment by posva** [comment]
You need https://v3.router.vuejs.org/api/#exact-path
