### ISSUE TITLE
vue-router not work with express

### ISSUE THREAD

**Issue by dolphineor** [vuejs/vue-router#375]
@yyx990803 Hi, I'm getting started with `vue-router`. Using `express` as server, but I found router don't work. The default page is 
![qq 20160218103211](https://cloud.githubusercontent.com/assets/9883493/13132148/62ac4338-d62b-11e5-87c0-86b6131eeefb.png), 
when I change the view, it just show the orginal view, like this 
![qq 20160218103511](https://cloud.githubusercontent.com/assets/9883493/13132174/9bec8a04-d62b-11e5-9771-7bfb33c33156.png). 
if I restart the server, the view is work, 
![qq 20160218103356](https://cloud.githubusercontent.com/assets/9883493/13132204/dd26f95a-d62b-11e5-91d9-6477d259dcbe.png), 
but I can't get default page. This my project's address: [modern-java-web-scaffold](https://github.com/dolphineor/modern-java-web-scaffold/tree/master/frontend). Is there something wrong with me? Thanks in advance.

**Comment by fnlctrl** [comment]
You probably need this:
https://ninja.sg/spa-router-fallback/

**Comment by dolphineor** [comment]
It doesn't work, I must reload page through browser url, instead of vue-router. Other solution?

**Comment by dolphineor** [comment]
@fnlctrl Thanks. I figured out, it's my fault, I provide an error value for transition property in ``` <router-view></router-view> ```
