### ISSUE TITLE
Can I uninstall @vue/cli-plugin-router?

### ISSUE THREAD

**Issue by m-demydiuk** [vuejs/vue-router#3756]
### What problem does this feature solve?
I added vue router to vue 2 project with @vue/cli-plugin-router(4.5.17).
According to documentation plugin only generates some code and do not add anything in runtime.
So the question is - can I uninstall @vue/cli-plugin-router after installation?

### What does the proposed API look like?
?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
