### ISSUE TITLE
Handlebars, Vue and typeahead enter in a bar...  

### ISSUE THREAD

**Issue by odranoelBR** [vuejs/vue-router#376]
Hello ppl. Im new here, vue is awesome tks for all work.

I have an input whit typeahead who brings me a list of  a href links.
Now im using vue router and tryng to put v-link in this links.
Dont work...

Code: 
```javascript

 suggestion: 
       Handlebars.compile(
                                    '<a v-link="' +
                                    '{ path: "/membro/editar/2}"' +
                                    '">{{nome}}</a>'
                            )
```

**Comment by yyx990803** [comment]
Why are you using Handlebars with Vue?...

**Comment by odranoelBR** [comment]
=)
Very good question sir!
Was tryng this all day , maybe this blur me.

Tks for help and vue.
When works i post here.

**Comment by odranoelBR** [comment]
Still in trouble ...

```javascript
 suggestion: function (data){
    var vLink = '<a v-link="{ path: ' + "'/configuracao/funcao'" + '} ">' + data.nome + '</a>';

    return vLink
}
```
and gives me :
```javascript

<a v-link="{ path: '/configuracao/funcao'} " class="tt-suggestion tt-selectable"></a>

I read your comment about dinamically elements in http://forum.vuejs.org/topic/151/vue-js-not-listening-to-dynamically-created-elements/2 but dont figure out how use v-if on this.

**Comment by odranoelBR** [comment]
I moved post to : http://forum.vuejs.org/topic/2309/creating-dinamic-element-list-of-typeahead-js-whit-vue-rounter-v-link-list

Close this one. Tks
