### ISSUE TITLE
addRoutes源码

### ISSUE THREAD

**Issue by zyz2019** [vuejs/vue-router#3761]
### Version
3.4.3

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/patient-tdd-94yzho?file=/src/router/index.js)

### Steps to reproduce
只要先进入hello路由，再点击回退，此时addRoutes就会无限进入路由钩子，根本走不到下一步的window.routerFlag++; 最终导致爆栈，具体原因也有描述，补充说明中有自己的文章解释，但是不太明白源码中的设计意图。

### What is expected?
在vue-router源码中
VueRouter.prototype.addRoutes = function addRoutes (routes) {
  this.matcher.addRoutes(routes);
  // 这里的判断意义在哪里
  if (this.history.current !== START) {
    this.history.transitionTo(this.history.getCurrentLocation());
  }
};

### What is actually happening?
经测试，自己的删除以下代码，仍然能正确添加路由，所以这里使用这段逻辑的原本目的什么。
  if (this.history.current !== START) {
    this.history.transitionTo(this.history.getCurrentLocation());
  }

---
整个问题的来源已经清晰了，但是不太清楚设计者添加上述逻辑的意义，这里有自己记录的文章链接
https://www.yuque.com/docs/share/22679b12-aaae-478a-a8a6-266d0543f104
还希望得到解答，谢谢~

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

——
Everything seems to be working fine in the reproduction
