### ISSUE TITLE
Link to vue-router 3 documentation in description of repository details

### ISSUE THREAD

**Issue by dpschen** [vuejs/vue-router#3768]
### Version
3.5.4

### Reproduction link
[github.com/vuejs/vue-router/](https://github.com/vuejs/vue-router/)

### Steps to reproduce
Open [vue-router v3 repository](https://github.com/vuejs/vue-router) on GitHub

### What is expected?
It should link to the archived v3 documentation [https://v3.router.vuejs.org](https://v3.router.vuejs.org)

### What is actually happening?
The description of the repository details is linking to the documentation of vue-router v4 instead.

---
See image:

![image](https://user-images.githubusercontent.com/6173598/184096801-cf3abe1a-ce97-4f37-980a-ef24919cb355.png)

**Comment by posva** [comment]
done
