### ISSUE TITLE
New release 3.6.0

### ISSUE THREAD

**Issue by Tofandel** [vuejs/vue-router#3771]
### Version
3.6.0

### Reproduction link
[www.npmjs.com](https://www.npmjs.com/package/vue-router/v/3.6.0)

### Steps to reproduce
Why is there a new minor release of vue router v3 but no change in the git history?

### What is expected?
The version to be released on github

### What is actually happening?
The release is not appearing on github and no commit where added to the branch https://github.com/vuejs/router/tree/vue2

---
If there was no change, why was it released? Should we be concerned?

**Comment by Tofandel** [comment]
My bad, npm points to the wrong repo, the branch there is not updated, but there may have been an issue somewhere as renovate when updating pointed the update history to https://github.com/vuejs/router/compare/9365e5b7ee362b4bed067709ca74f48cdbb69800...c0be82bd5cf29f42950ef8da793e2df72e3e5806

**Comment by posva** [comment]
Yep, npm only shows the latest
