### ISSUE TITLE
VueRouter 3.6.0 cannot be used via CDN

### ISSUE THREAD

**Issue by fimion** [vuejs/vue-router#3772]
### Version
3.6.0

### Reproduction link
[codepen.io/fimion/pen/VwXRxgM](https://codepen.io/fimion/pen/VwXRxgM)

### Steps to reproduce
Attempt to use VueRouter 3.6.0 via CDN

It will error before your code can run.

### What is expected?
to not error

### What is actually happening?
something is going wrong in the Vue.use statement that is causing it to error out as best as I can tell

---
I have created a codepen showing the same app working with 3.5.4: https://codepen.io/fimion/pen/WNzmyvq

**Comment by kotslee** [comment]
I have the same error when running as a webpack bundle. Error on line 2 of the following code:

import Vue from 'vue'
import VueRouter from 'vue-router'

Vue.use(VueRouter)

**Comment by MrJxy** [comment]
I meet the same error.
vue: 2.7.9 (from CDN)
vue-router: 3.6.0

Error will disappear when I downgrade to vue-router@3.5.4.

**Comment by imloama** [comment]
I got an error after deploy our system.
Downgrade to vue-router@3.5.4 and works.
Our system use nuxtjs framework.
![image](https://user-images.githubusercontent.com/3024323/186078121-7ec4f4be-7c09-4948-9334-a08f04cdaa29.png)
![image](https://user-images.githubusercontent.com/3024323/186078340-59ea71e8-b5b5-47da-83af-9200f6779fc2.png)
