### ISSUE TITLE
v3.6.0 cannot be used with vitest

### ISSUE THREAD

**Issue by kingyue737** [vuejs/vue-router#3775]
### Version
3.6.0

### Reproduction link
https://stackblitz.com/edit/vitest-router-x7aswn

### Steps to reproduce
Open the link to reproduction. Test will be run automatically and fail

### What is expected?
Test should pass

### What is actually happening?
Import `vue-router` v3.6.0 will result into error in unit testing thrown by `vite`:

```
Error: Failed to resolve entry for package "vue-router". The package may have incorrect main/module/exports specified in its package.json.
```

---
Temporary workaround:

```ts
// vite.config.ts
export default defineConfig({
  test: {
    alias: {
      'vue-router/composables': 'vue-router/dist/composables.mjs',
      'vue-router': 'vue-router/dist/vue-router.esm.js',
    },
})
```
I've reported this bug in `vitest` https://github.com/vitest-dev/vitest/issues/1898 and maintainer thinks that this is probably an error on `vue-router` part.

**Comment by posva** [comment]
Fixed in the latest release
