### ISSUE TITLE
no Ref and ComputedRef defined in vue2.x, but you use in vue-router2.6.1

### ISSUE THREAD

**Issue by lakalakaka** [vuejs/vue-router#3779]
see the capture

![image](https://user-images.githubusercontent.com/8756639/186297168-7b167d12-de2c-4568-8945-c15173204fb7.png)

**Comment by wal0x** [comment]
vue-router ^2.6.0 tries to import types ComputedRef and Ref from vue. This two type exists in vue ^2.7.X.

In the change log they claim that 2.6.0 will not affect vue 2.6 user. It's true only if you activate SkipLibCheck in your tsconfig.json
https://github.com/vuejs/vue-router/blob/dev/CHANGELOG.md#360-2022-08-22

Updating to vue 2.7 if possible should solve the issue too.
