### ISSUE TITLE
URL query parameters getting encoded twice

### ISSUE THREAD

**Issue by decademoon** [vuejs/vue-router#378]
If I perform this:

```
this.$router.go({ name: 'a', query: { b: '/c' } })
```

then the URL in the address bar becomes `/a?b=%252Fc` instead of `/a?b=%2Fc`.

`this.$route.query.b` will be `'%2Fc'` instead of `'/c'`.

---

It seems that each query parameter is being `encodeURIComponent`-ed, combined into the full path, then the full path is `encodeURI`-ed. Shouldn't the URL be `encodeURI`-ed before the query string is appended?

**Comment by GuillaumeLeclerc** [comment]
Do you have any idea when it will be integrated on the npm registry ?
