### ISSUE TITLE
Update version of path-to-regexp dependency

### ISSUE THREAD

**Issue by suleymangezsat** [vuejs/vue-router#3787]
### What problem does this feature solve?
I would like to add optional prefixes to my route params. Currently it's not possible since vue-router uses an old version of path-to-regexp library.

### What does the proposed API look like?
Adding custom prefix and suffix and many more features added in new versions will be added to vue-router.
Here is the link that shows how it works : https://github.com/pillarjs/path-to-regexp#custom-prefix-and-suffix

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/vue-router/issues/3256
