### ISSUE TITLE
Push new entry into vue-router stack silently.

### ISSUE THREAD

**Issue by Wadhah-Sky** [vuejs/vue-router#3788]
### What problem does this feature solve?
Hi, I am trying to update the data that are been showing in the view using the management state (**Pinia**) for that and in the same time update the URL with no need to push/replace the current view, I can do this with:

`history.pushState(null, '', newURL);`

But this method will not update the stack of the router which causing an issue with the pagination, and if I use the formal way as shown below will lead to push to that route: 

`useRouter.push(updatedRouteObj)` 

### What does the proposed API look like?
If we can have something like the shown suggested code, will be great:

```javaScript

useRouter.push(updatedRouteObj, {silently : true});

```

Or directly using <router-link> :

```html

<router-link 
  :to="{ 
      path: useRoute.path,
      params: { ...useRoute.params},
      query: { ...useRoute.query}
  }" 
  @click.capture.silently="updateData(pageNumber)"
>
  <span> {{pageNumber}} </span>
</router-link>

```

**Comment by posva** [comment]
the router doesn’t keep a stack of the history but you cannot change the URL through history and expect the router to update the location (or even react in any way to that).

You can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://chat.vuejs.org/) to ask questions 🙂
