### ISSUE TITLE
Setting root to '/' throws an "Invalid regular expression" error

### ISSUE THREAD

**Issue by agonbina** [vuejs/vue-router#379]
I want to set the root to `/` so that the activeClassName is set properly for nested routes within the root(because currently if you have a route definition for `/`, and then other routes starting with `/`, ex: `/cats` and you navigate to `/cats`, both anchors to `/` and `/cats` will have the active class), but I get this exception thrown: 
```
Invalid regular expression: /^\/: \ at end of pattern
```
being thrown by this line: https://github.com/vuejs/vue-router/blob/dev/src/history/html5.js#L14

**Comment by jsiebach** [comment]
Have a look at the `exact` option of `v-link`:  http://vuejs.github.io/vue-router/en/link.html

usage: `<a v-link="{ path: '/', exact: true }"></a>`

This way the link will only be active if the route path is matched exactly, and won't be highlighted when the user is at `/cats`
