### ISSUE TITLE
jsfiddle linked from documentation loads wrong versions of vue and vue-router

### ISSUE THREAD

**Issue by ig3** [vuejs/vue-router#3793]
### Version
3.6.5

### Reproduction link
[jsfiddle.net](https://jsfiddle.net/yyx990803/xgrjzsup/)

### Steps to reproduce
Browse to https://v3.router.vuejs.org/guide/#javascript and the Getting Started page. Near the bottom of the page is the link:

You can also check out this example live (opens new window).

This is a link to: https://jsfiddle.net/yyx990803/xgrjzsup/

The jsfiddle appears to load current versions of vue and vue-router, rather than 2.x and 3.x respectively. As a result, the example doesn't work.

I edited the links to:

```
<script src="https://unpkg.com/vue@2.7.12/dist/vue.js"></script>
<script src="https://unpkg.com/vue-router@3.6.5/dist/vue-router.js"></script>
```
After which the example worked as I expected it to, however I am very new to vue so my expectations may not be valid.

### What is expected?
The example in the linked jsfiddle should load and run without errors.

### What is actually happening?
The console of the jsfiddle displays the error:

"<a class='gotoLine' href='#69:14'>69:14</a> ReferenceError: VueRouter is not defined"

---
It is a very minor issue but troublesome because I don't know vue or vue-router, thus I am reading the getting started docs, trying to understand an existing app, and finding it difficult to recognize a faulty jsfiddle Vs my invalid expectations / understanding of what should happen. Of course, I should have noticed the error in the console sooner, but my attention was focused on the code and results that I was trying to understand.

I wouldn't be looking at the old versions except that I am unfamiliar with vue and vue-router and trying to understand an existing app that uses these old versions. Maybe there are others like me, who would have a better experience and introduction to vue if the examples just worked.

**Comment by posva** [comment]
BTW, you should really try the latest version https://router.vuejs.org/ 🙂
