### ISSUE TITLE
I'm trying to implement SPA on Laravel route. The route has a base route with a main vue component and on top of that I'm trying to load other components. The router link is changing the url parameters but the page isn't loading the ArticleVue component.  Current Installation: Laravel 9.x Vue3.x and Vue Router 4.x

### ISSUE THREAD

**Issue by cosmoarunn** [vuejs/vue-router#3794]
### Version
3.6.5

### Reproduction link
[stackoverflow.com](https://stackoverflow.com/questions/74131903/router-link-not-working-warning-component-default-in-record-with-path-fgb)

### Steps to reproduce
Laravel Routes

```
    Route::get('/fgbs.blog', function () { 
        return view('blog');
    });
    Route::any('/fgbs.blog/{any}', function () {
        return view('blog');
    })->where('any', '.*');
```

```
//router.js
export const  router = createRouter({
    history: createWebHistory(),
    //base:  '/fgbs.blog',
    routes: [
        { path: '/fgbs.blog',  name: 'blog.home', component: () => BlogVue },
        { path: '/fgbs.blog/articles/:slug', name: 'articles.show', component: ()=> ArticleVue },
    ]
})   

```

router link on BlogVue.vue component,

```
<router-link
  class="inline-block truncate text-theme-25 dark:text-theme-22"
   :to="{name: 'articles.show', params: {slug: article.slug} }"
 >
```
       
ArticleVue component is the display of the article that is expected to load after clicking the router-link

This warning appears on page reload, and also when I click the article's <router-link ..

> 
**[Vue Router warn]: Component "default" in record with path "/fgbs.blog/articles/:slug" is a function that does not return a Promise. If you were passing a functional component, make sure to add a "displayName" to the component. This will break in production if not fixed.**

How do I solve this issue?

### What is expected?
ArticleVue is expected to load the content using the slug provided on the same page.

### What is actually happening?
Url changing correctly for the slug but page isnt loading the component, it's still the same page

---
Since, it involved Laravel, I couldn't use the SFC playground for minimal reproduction

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
