### ISSUE TITLE
enhancement/change request: add keep-alive option on routes

### ISSUE THREAD

**Issue by tomcon** [vuejs/vue-router#380]
(1) http://vuejs.github.io/vue-router/en/view.html 
   "keep-alive now has experimental support in 0.7.2+."
(2) http://vuejs.org/guide/components.html#keep-alive
    <component :is="currentView" keep-alive>

See above, re. "keep-alive" option on router-view (and component) currently. if I understand correctly, this setting on router-view becomes effectively an all-or-nothing attribute (so not so useful). 

In other words, if keep-alive is specified then *all* routes are effectively cached and reloaded when that route is revisited. I'd like to be able to specify a keep-alive option on individual routes.  With 30+ routes and only 5 that need to be kept alive means the current router-view "keep-alive" option is unusable and leads to much manual code to work around this instead.

e.g. see below - the /find and /todolist routes are not re-used and currently have to be manually save and loaded to/from localstorage within the ready() & beforedestroy() methods. if we could specify "keep-alive" in the options object (as shown below in /find & /todolist) of the route it would be very good.

router.map({   
    '/': { component: c_home, canReuse: false },
   '/settings': { component: c_settings, canReuse: false, name:'settings' },
   '/supervisor': { component: c_supervisor, canReuse: false, name:'supervisor' },
   '/todolist': { component: c_todolist, canReuse: false, name:'todolist', keep-alive:true },
   '/find': { component: c_find, canReuse: false, name:'find', keep-alive:true },
   '/lists': { component: c_lists, canReuse: false, name:'lists' },
   '/reports': { component: c_reports, canReuse: false, name:'reports' },

**Comment by tomcon** [comment]
maybe instead of using:
`
'/find': { component: c_find, canReuse: false, name:'find', keep-alive:true },
`

use **"keep-route-alive"** to distinguish it from the `<component>` and `<router-view>` **"keep-alive"** attribute
`
'/find': { component: c_find, canReuse: false, name:'find', keep-route-alive:true },
`

**Comment by fnlctrl** [comment]
@tomcon  I think this is already possible with 2.0:
https://jsfiddle.net/fnlCtrl/cn5cnsw9/

**Comment by fnlctrl** [comment]
Closed due to inactivity.

**Comment by tracid** [comment]
@fnlctrl how to make proper transitions with your method?

**Comment by fnlctrl** [comment]
@tracid You can wrap each element with a `<transition>`:

``` html
<transition name="foo">
  <keep-alive>
    <router-view  v-if="$route.meta.keepAlive"></router-view>
  </keep-alive>
</transition>
<transition name="foo">
    <router-view v-if="!$route.meta.keepAlive"></router-view>
</transition>
```

Though it seems ugly.. and may also have transition synchronization problems...
Sorry I couldn't come up with a better idea.

**Comment by tracid** [comment]
with "proper" i meant transitions without synchronization problems - functioning as they meant to be. yes it seems like a ugly hack and i would like to know the perfomance implications with two router-views.
is there a solution for selective keep-alive in router-view in vuejs 2.0,  @yyx990803?

**Comment by fnlctrl** [comment]
@tracid There shouldn't be performance overhead, because no extra instance is created, and only the ones you wanted to be kept-alive are cached.

**Comment by tracid** [comment]
thank you for your answers! i figured a way out, my problem had nothing to do with caching the component. but the selective keepalive would still be interesting!

**Comment by yoyo837** [comment]
> thank you for your answers! i figured a way out, my problem had nothing to do with caching the component. but the selective keepalive would still be interesting!

Hello, how did you solve that?
