### ISSUE TITLE
next(false) clears path on global Navigation Guards

### ISSUE THREAD

**Issue by daniil4udo** [vuejs/vue-router#3807]
@posva, sorry my bad in the example, but I found the reason behind my "path flashes", it's `ensureURL` method in the `HTML5History` class.

```
// next(false) -> abort navigation, ensure current URL
this.ensureURL(true)
```
If we take a look at this method

```
ensureURL (push?: boolean) {
  if (getLocation(this.base) !== this.current.fullPath) {
    const current = cleanPath(this.base + this.current.fullPath)
    push ? pushState(current) : replaceState(current)
  }
}
```

if I try to go straight to the restricted path, at some point, in my app I have `next(false)`, that causes half-second absolutely clear URL.

When I logged vars in this method I noticed that it pushes to `to` url WITH aborting navigation.

<img width="312" alt="image" src="https://user-images.githubusercontent.com/34333374/201911818-b123d461-58d2-452d-a1a9-70094fc1576c.png">

When I commented that `ensureURL(true)` app worked as expected without annoying flashes.

Could you plz explain why do we need it?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). And please do not ping directly maintainers just to ask questions 🙏
