### ISSUE TITLE
setupListeners not invoke if user customer route guard not invoke next parameter function

### ISSUE THREAD

**Issue by workkk98** [vuejs/vue-router#3810]
### Version
3.6.5

### Reproduction link
[stackblitz.com](https://stackblitz.com/edit/vitejs-vite-qxv7ke?file=src%2FApp.vue,src%2Fmain.js,src%2Fviews%2FAbout.vue)

### Steps to reproduce
1. location bar enter "xxx/about" url.
2. click root link
3. click foo link
3. click browser navigation back button.

### What is expected?
"root" page should be render.
vue-router handleRoutingEvent function should be invoked, but not. 

### What is actually happening?
page content not changed.

---
I know this case because "/abount" beforeEnter guard isn't correct. But I think vue-router listen popstate Should not be affected by user code

**Comment by LinusBorg** [comment]
It's documented that next() needs to be called to validate a navigation. That's just how it works.
