### ISSUE TITLE
Office-js breaks vue app

### ISSUE THREAD

**Issue by warenix** [vuejs/vue-router#3814]
### Version
3.6.5

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/nameless-cookies-kl6z6r?from-embed=&file=/public/index.html)

### Steps to reproduce
In index.html, loading the office-js will breaks entire vue app.

### What is expected?
Vue should run 

### What is actually happening?
The browser keeps reloading

---
Perhaps related issue: https://github.com/vuejs/vue-router/issues/3154

**Comment by LinusBorg** [comment]
This reproduction:

1. Does not involve vue-router
2. does not break as described
3. uses a Vue 3 template, but the issue was raised in the repo for VueRouter 3.6.5, which is for Vue 2.

**Comment by posva** [comment]
Please open a new issue at vuejs/router if you manage to reproduce it
