### ISSUE TITLE
[Feature Request] Add navigator outside component

### ISSUE THREAD

**Issue by joojaewoo** [vuejs/vue-router#3816]
### What problem does this feature solve?
I recently converted to vue2.7 and vite.
I imported the existing router object and used it outside the component, but I can't use it anymore because of the circular reference problem. It would be nice to create a function that can be routed outside the component. like react-router

### What does the proposed API look like?
```javascript
// axios
import { navigate } from 'vue-router'

axios.interceptors.response.use((res) => {
    navigate(path);
})
```

**Comment by posva** [comment]
You need to solve your circular reference. It's simply not possible to create such API because it depends on the router instance created with `new VueRouter()`.
