### ISSUE TITLE
Sub Directory Wild Card Redirects - Feature Request

### ISSUE THREAD

**Issue by EHackettTriCore** [vuejs/vue-router#382]
As mentioned over on the [vue forum](http://forum.vuejs.org/topic/1744/how-do-i-define-vue-router-subroute-wildcard-404s/2) it would be nice to have built in ability to add directory specific wildcard redirect to specific pages.

**Use case:**
/\* => Redirects to global 404 page
/dashboard/\* => Redirects missing dashboard pages to dashboard specific 404 page.
/product-category/\* => Redirects missing product to category specific 404 page etc...

**Comment by Saymon-biz** [comment]
In [this example](https://github.com/vuejs/vue-router/blob/dev/example/advanced/route-config.js) there is root-level wildcard redirect     
```
    // not found handler
    '*': {
      component: require('./components/not-found.vue')
    },
```
Isn't it reasonable to implements same approach for nested routs?

E.g.

```
    '/': {
      component: SiteIndex,
      subRoutes: {
        '*': {
          // custom 404 page for public section
          component: Site404
        },
        ... // other routes for public section of a site
    },
    '/admin': {
        '*': {
          // custom 404 page for administrative section
          component: Admin404
        },
        *** // other routes for administrative section
      }
    },
```

**Comment by znck** [comment]
:+1:

**Comment by divmgl** [comment]
Need this pretty badly. Does anyone know of an alternative to perform a catch all?

**Comment by nickspiel** [comment]
Also looking for this. +1

**Comment by smadey** [comment]
+1

**Comment by enesemini** [comment]
Run into this as well.

+1 for implementation

**Comment by webbur** [comment]
+1

**Comment by deulos** [comment]
+1

**Comment by EmmanuelBeziat** [comment]
+1 Too.

**Comment by posva** [comment]
@znck @nickspiel @smadey @enesemini @webbur @deulos Can you please use the reaction feature to add a 👍 to the issue and then delete your comments so we can cleanup a bit? Thanks!
@divmgl You can already use the `'*'` wildcard when defining route paths

**Comment by EmmanuelBeziat** [comment]
@posva Any update on this? :) thanks

**Comment by fnlctrl** [comment]
@EmmanuelBeziat This is already in 2.0, you can try it out.
As for 0.7, there is no plans of back porting as for now since the team is working on improving 2.0, and a in fact back port is unlikely to happen as the majority of the people will probably have just upgraded to 2.0 by then.

**Comment by EmmanuelBeziat** [comment]
Thanks for the answer. So I won‘t use it for now, as the project is using Vue 1.0… I‘ll have it for the next. :)

**Comment by fnlctrl** [comment]
Don't forget to checkout this awesome migration helper, https://github.com/vuejs/vue-migration-helper/, should help you seamlessly upgrade from 1.0 to 2.0, though a certain amount of refactor is unavoidable.

**Comment by EmmanuelBeziat** [comment]
Thanks for your help!

**Comment by posva** [comment]
@fnlctrl I'm unsure we want to let this go. It may not be that difficult to add the `*` pattern for subRoutes

**Comment by fnlctrl** [comment]
@posva I didn't mean letting this go 😂 It's just that we don't have a plan for back ports yet as of now... And I honestly don't know if we're really going to have one in the future months...

**Comment by posva** [comment]
@fnlctrl Oh, my bad. That's right, this is not the priority right now and may not be worth in the near future 😄

**Comment by EmmanuelBeziat** [comment]
@posva well, let‘s fork v1 and add this feature by ourselves! 😛 

(I'm not good enough to achieve this, but if by any chance I do it, i‘ll surely make a pull request).
