### ISSUE TITLE
Routes' Matching Syntax ,the request address reset?

### ISSUE THREAD

**Issue by CeerDecy** [vuejs/vue-router#3820]
router.ts
<img width="693" alt="image" src="https://user-images.githubusercontent.com/79098669/210191025-454b6299-5d31-4ed5-b40d-fa92da7303b5.png">

request.ts
<img width="370" alt="image" src="https://user-images.githubusercontent.com/79098669/210191003-bfcf7613-b119-42b5-a52b-0392828b9db7.png">

vite.config.ts
<img width="784" alt="image" src="https://user-images.githubusercontent.com/79098669/210191096-fe44b8bb-58ae-424e-a04f-56d69c987bde.png">

error
<img width="476" alt="image" src="https://user-images.githubusercontent.com/79098669/210191076-ad97f680-fb3e-42da-bb98-3be8da67b633.png">

other router path is no problem, only this path `/editBlocG/:id`

**Comment by posva** [comment]
Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
