### ISSUE TITLE
Bug with transition + keep-alive + nested router-view

### ISSUE THREAD

**Issue by TheTrigger** [vuejs/vue-router#3829]
### Version
3.6.5

### Reproduction link
[github.com](https://github.com/TheTrigger/vuejs2-nested-router-bug)

### Steps to reproduce
1. Start the page to / (Home)
2. Click on User Edit
3. Click on Home
4. Click on User Dashboard

### What is expected?
Expecting to see the User Dashboard page

### What is actually happening?
The main router-view shows the latest sub-routing: User Edit.

---
The relevant thing I tried is to put the attribute `:key` to the main router-view

```HTML
<router-view :key="`app_${$route.fullPath}}`"></router-view>
```
alto tried to combine with

```HTML
<router-view :key="`user_${$route.fullPath}}`"></router-view>
```

but by doing this you mysteriously lose the animation on the child routing-view maybe because the parent-routing-view is being reloaded.

If you remove the node `<transition>` or `<keep-alive>` it start to work as expected.

I tried many things but haven't found a way to make it work with transition, keep-alive and nested routing

thanks

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for boiled down bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
