### ISSUE TITLE
`v-link-active` does not work when `v-link` is on a component

### ISSUE THREAD

**Issue by simplesmiler** [vuejs/vue-router#383]
Repro: http://jsfiddle.net/simplesmiler/g61g06gr/

I found this while playing around with the [idea of BEM directive](https://jsfiddle.net/simplesmiler/bgrh5chc/). I needed a way to look up the local DOM tree for the directive that defined a block, and I decided to follow the example of `v-link`/`v-link-active` of setting a custom flag on the element. But apparently this does not work when `v-link` is put on the component, because component node is compiled before the rest of the template.

Is there any other way for two vertically separated directives to talk?

**Comment by simplesmiler** [comment]
I guess I could try to signal the intention to the parent vm (assuming one component equals one block), and then execute things in correct order in the `compiled` hook.

**Comment by yyx990803** [comment]
Fixed in 3d12e95
