### ISSUE TITLE
vue-router v3 dynamic segments can't support content with period in vite dev server.

### ISSUE THREAD

**Issue by Shimada666** [vuejs/vue-router#3834]
### Version
3.6.5

### Reproduction link
[github.com](https://github.com/Shimada666/vite-vue2-router)

### Steps to reproduce
1. Accessing http://localhost:5173/foo/bar displays the page normally.
 
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/33391300/226619258-d069dd67-e843-4d91-8867-d8539f624e31.png">

2. Accessing http://localhost:5173/foo/bar.asd displays an error page with a 404 status code.

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/33391300/226619427-31052324-7e52-4f70-b98e-60cd1dd0be5a.png">

This is my router config.

```javascript
import Vue from 'vue'
import VueRouter from 'vue-router'
import HomeView from '../views/HomeView.vue'

Vue.use(VueRouter)

const router = new VueRouter({
  mode: 'history',
  base: import.meta.env.BASE_URL,
  routes: [
    {
      path: '/',
      name: 'home',
      component: HomeView
    },
    {
      path: '/about',
      name: 'about',
      // route level code-splitting
      // this generates a separate chunk (About.[hash].js) for this route
      // which is lazy-loaded when the route is visited.
      component: () => import('../views/AboutView.vue')
    },
    {
      path: '/foo/:bar',
      name: 'foobar',
      component: () => import('../views/FooBar.vue')
    }
  ]
})

export default router

```

### What is expected?
access normal

### What is actually happening?
access error, and got 404 status code

---
Furthermore, I noticed that the issue only occurs in vite, as it seems to work fine when using Vue CLI.

**Comment by luy19** [comment]
Yes, it's an expected behavior. When the requested path contains `.`(dot) characters, Vite treats it as a direct file request, so you get a 404 error.
Maybe you can change the vue-router to hash mode.
