### ISSUE TITLE
Redirected when going from path to path via a navigation guard

### ISSUE THREAD

**Issue by targetlucked69** [vuejs/vue-router#3835]
I am getting flooded by these errors in Sentry due to `vue-router` v3 unable to handle `next` errors.

The example error I got in sentry:

```
Redirected when going from "/login?redirect=%2Fprofile" to "/profile" via a navigation guard.
```

This is on purpose as I want to check if the user is authenticated and redirect back to the page he tried to access before it.

I saw this in stackoverflow but seems like this will break a lot of things - https://stackoverflow.com/a/63819014/4698790

Is there a way to handle these errors in v3?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
