### ISSUE TITLE
Cant debug with vue-router

### ISSUE THREAD

**Issue by hezhongfeng** [vuejs/vue-router#3843]
### Vue version

3.3.4

### Link to minimal reproduction

https://github.com/hezhongfeng/core/tree/report-branch

### Steps to reproduce

1. install and build vue
2. cd packages/vite and install
3. pnpm dev

### What is expected?

can use vue-router to display signal page

### What is actually happening?

Noting show

### System Info

```shell
macOs 13.3.1
```

**Comment by posva** [comment]
Open an issue on Vuejs/router using one of the bug report starters rather than a package within core and I will take a look 🙂
