### ISSUE TITLE
后面异步append加入的script没有插入iframe的head

### ISSUE THREAD

**Issue by yongdong1997** [vuejs/vue-router#3850]
![image](https://github.com/vuejs/vue-router/assets/54296372/47340e5d-e844-463c-9d79-b390087efe6d)
记得上两周的时候domcument.body.appendChild追加的脚本是插入在iframe的head上的，现在也无法显示了，获取不到之前假如的jquery环境，是不是脚本插入的位置发生更改导致的？

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
