### ISSUE TITLE
Suggestion about router send Object data 

### ISSUE THREAD

**Issue by For-me** [vuejs/vue-router#386]
HI, all.
I want to send a Object data to other compoents.But params like params:{id:1,name:'xxx'} is not need.
If i want to send more data to others ,The wording does not look elegant, it is difficult to maintain。
So, Did you provide some method like this: 
`route.map({'/user':{
           name:'user', 
           params:{
                  paramsData:{}
        },}})`

**Comment by nblackburn** [comment]
Did you mean like this: #398?

**Comment by For-me** [comment]
@nblackburn yeah! amost like this

**Comment by cendekia** [comment]
this.$router.app._route.params
