### ISSUE TITLE
两层iframe嵌套，在hash模式下，第二层iframe不渲染

### ISSUE THREAD

**Issue by IdealZXL** [vuejs/vue-router#3863]
由于项目的特殊性，要涉及到iframe的多级嵌套使用，我在home页面使用iframe加载detail页面，在detail页面使用iframe加载detail2页面,hash模式，detail2页面根本不加载，而history模式就可以，这个是vue-router本身限制，还是浏览器问题？

- 路由
![image](https://github.com/vuejs/vue-router/assets/23547355/887559b0-705c-4d03-8c20-cb41f7665df3)

- home.vue
![image](https://github.com/vuejs/vue-router/assets/23547355/d8affbf6-f7c4-414d-9c71-967f5bf517ba)

- detail.vue
![image](https://github.com/vuejs/vue-router/assets/23547355/13d25a85-ee07-4a60-a71c-9c302ff0ac70)

- detail2.vue
![image](https://github.com/vuejs/vue-router/assets/23547355/ac50675f-c239-4b27-947a-e643681c9a38)

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by edison1105** [comment]
是浏览器限制

> Infinite recursion is prevented. Any frame that attempts to assign as its SRC a URL used by any of its ancestors is treated as if it has no SRC URL at all (basically a blank frame). This doesn't prevent all malicious documents, but it eliminates a troublesome class of them.

see [w3.org/TR/WD-frames-970331](https://www.w3.org/TR/WD-frames-970331)
