### ISSUE TITLE
Page refreshing after replacing the current route ( Component getting unmounted and mounted again)

### ISSUE THREAD

**Issue by adithya-beo** [vuejs/vue-router#3865]
I have been using router.replace method to add the params in my exusting url. But the page is getting refreshed and my settings ( setting a value in the dropdown) getting reset. Any solution for this?

**Comment by posva** [comment]
This could be the result of having a `key` attribute that is too strict. Don't ignore the issue instructions please.

**Comment by adithya-beo** [comment]
Could you please provide me the code to avoid the issue?
