### ISSUE TITLE
watch router or router.currentRoute.path question

### ISSUE THREAD

**Issue by Miofly** [vuejs/vue-router#3867]
in App.vue

route change watch not trgger

```
watch(()=> router.currentRoute.path, (val) => {\
	console.log('router.currentRoute.path not trigger', val);
}, {
  immediate: true
});
```

why oldValue  === val

```
watch(()=> route, (val, oldValue) => {
	console.log('route.path not trigger', val, oldValue);
  console.log('why is true', JSON.stringify(val) === JSON.stringify(oldValue));
}, {
  immediate: true,
  deep: true
});
```
home.vue 

```
onDeactivated(() => {
  console.log('onDeactivated why after onBeforeRouteLeave');
})

onBeforeRouteLeave((_, from, next) => {
  console.log('onBeforeRouteLeave');
  next()
})
```
why onDeactivated after onBeforeRouteLeave

repo link: https://github.com/Miofly/demo-issue-template/tree/vue2-template

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by Miofly** [comment]
> watch(()=> route, (val, oldValue) => {
> 	console.log('route.path not trigger', val, oldValue);
>   console.log('why is true', JSON.stringify(val) === JSON.stringify(oldValue));
> }, {
>   immediate: true,
>   deep: true
> });

i think this question is bug, watch route old and new is equal?
Because the above issue is no problem in vue-route4
