### ISSUE TITLE
enhancement request: modify existing routes

### ISSUE THREAD

**Issue by andreixk** [vuejs/vue-router#387]
It would be nice to be able to add/remove/replace routes after they've been created with router.map().
e.g. if a user logs in and now has more privileges or access to more pages, this will need to be added. If he logs out, he should not be able to keep clicking on existing links/routes.

i.e.:
``` javascript

//initial setup
var basicPermissions = {
 '/home':{ 
     component : {  template : '#home-component'  }
  }
}

router.map(basicPermissions);

//...
// login, credentials processing, etc.
// inside some ajax request:
var myPermissions = data.permssions; //may contain a bunch more paths with sub-paths, etc. in json format
//add new routes that are available to the user
router.addMap(myPermissions);

//...
// user logged out
//remove all routes and reset his permissions
router.resetMap();
router.map(basicPermissions);

```

**Comment by bfic** [comment]
I agree. It would be significant and very important enhancement during building large apps.

**Comment by znck** [comment]
+1

**Comment by blake-newman** [comment]
Could you give a use case on where this may be usable.  Routes in my opinion should stay static,  when dynamic that could introduce bugs to your application.

**Comment by znck** [comment]
A very large application can be divided into modules and each module can register its routes when it is loaded.

**Comment by yyx990803** [comment]
I think you are approaching the problem in the wrong mindset - in `vue-router` route privileges are handled by aborting transitions in route hooks rather than removing routes. For lazy loading, just use async components.
