### ISSUE TITLE
check path 404

### ISSUE THREAD

**Issue by zhuchaoling** [vuejs/vue-router#3874]
Is there a feature to detect a 404 error in an API? For example, if the path is 404, return true and redirect to the homepage.

const isNotFoundPath = router.checkNotFound('/test/404') // true

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
