### ISSUE TITLE
In Vue vite, router.push() does not render page although it does navigate to a new URL

### ISSUE THREAD

**Issue by techsellingman** [vuejs/vue-router#3876]
### I want to navigate to homepage after login. It goes to a new url, but does not render the page. It was still loading login page although it was navigated.

This is the code snippet.

	async userSignin({ commit }, data) {
		const signinData = {
			email: data.email,
			password: data.password,
		};

		const response = await APIs.USER_SIGNIN(signinData);
		const { email, token } = response;

		if (token) {
			commit("SIGNIN_SUCCESS", response);
			router.push("/");
			console.log(1)
		} else {
			return Toast.fire({
				icon: "error",
				title: "Incorrect email or password.",
			});
		}
	}

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
