### ISSUE TITLE
有参数的路由，页面就没有切换动画了

### ISSUE THREAD

**Issue by redhat** [vuejs/vue-router#388]
如题，有参数的路由，页面就没有切换动画了
`subRoutes: {
                '/:userId': {
                    name: 'detail',
                    component: controller('foo/detail')
                }
            }`
假设我路由是这样的，这样页面的切换就没有动画了

**Comment by yyx990803** [comment]
http://router.vuejs.org/en/pipeline/can-reuse.html

**Comment by redhat** [comment]
Oh! It's working, Thank you for your help!
