### ISSUE TITLE
多路由复用同一个vue 组件，页面无法独立互不影响

### ISSUE THREAD

**Issue by movaddrx** [vuejs/vue-router#3899]
有两个 路由比如 
/testA , /testB 都使用相同组件 TestView，访问/testA 时输入框修改了值， 切换到/testB 时输入框的值也改变了。这是什么傻X 的设计啊， 明明是两个路由，为啥实际上是一个页面

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
