### ISSUE TITLE
Sub-route component lifecycle hooks aren't called when directly navigating to route

### ISSUE THREAD

**Issue by cheapsteak** [vuejs/vue-router#39]
e.g. given route `/aaa/bbb`

Starting at `/`, navigating to `/aaa` via `v-link` triggers lifecycle hooks (mainly looking for `ready` and `attached`), but refreshing the page or directly inputing the url does not trigger the lifecycle hooks.  

Same for when going from `/aaa` to `/aaa/bbb`

**Comment by yyx990803** [comment]
Can't reproduce in latest `master`, can you confirm or provide a repro?

**Comment by cheapsteak** [comment]
Still not working, private repo unfortunately :(  
I'll work on a sample file. I neglected to mention that these were all nested routes, might be relevant

**Comment by cheapsteak** [comment]
Arg, sorry, it is working. I made a really dumb mistake :dizzy_face: had duplicate `ready` keys.
Turning on strict mode now
