### ISSUE TITLE
Feature: use v-on:click with v-link 

### ISSUE THREAD

**Issue by weotch** [vuejs/vue-router#390]
This doesn't appear to work:

```html
<a v-link='{name: "home"}' v-on:click='onClick'>Home</a>
```

I think it's [this `e.preventDefault()`](https://github.com/vuejs/vue-router/blob/dev/src/directives/link.js#L84).  I get why that's there, but can you think of some way we can also handle these clicks from the Component?  Maybe a callback could be specified in v-link, like:

```html
<a v-link='{name: "home"}, onClick'>Home</a>
<a v-link='{name: "home", click: onClick}'>Home</a>
```

**Comment by weotch** [comment]
Another option might be to give `v-on` a higher priority.  I'm currently looking into whether I can adjust the priority of an internal directive...

**Comment by weotch** [comment]
FYI, this approach to reducing the `v-link` priority is working for me so far:

```js
onPriority = Vue.directive('on').priority
Vue.directive('link').priority = onPriority - 1
Vue.directive('link-active').priority = onPriority - 2
```

Glad you included a way to access directives!

**Comment by perkola** [comment]
An idea is that the object passed to `v-link` could have some kind of callback property where you could specify a function on the component to execute.

**Comment by repsac-by** [comment]
I think it is better to use
[Transition Hooks](http://vuejs.github.io/vue-router/en/pipeline/hooks.html)
```javascript
route: {
  canDeactivate() {
    transition.abort()
  }
}
```

**Comment by rpkilby** [comment]
> I think it is better to use Transition Hooks

That doesn't seem like the correct responsibility. The transition hook is there to determine whether or not you can deactivate the current route. I would not want to shove my event handling code inside that. eg,

```html
<a v-link='{name: "home"}'>Cancel</a>
<a v-link='{name: "home"}' v-on:click='saveTheThing'>Save</a>
```

In both cases I'm navigating back to the main page, but canceling and saving are two distinct actions.

**Comment by perkola** [comment]
I agree with @rpkilby. A use case is a hamburger menu component with `v-link` to some route. When a link is clicked the menu should collapse (preferably with something like `v-on:click.prevent='closeMenu()'`) before transitioning into the new route.

This _can_ be achieved with transition hooks that collapses the menu on each `activate` but that results in code duplication since every route has to invoke the `closeMenu()` function on the hamburger menu component.

**Comment by Gomah** [comment]
```In HTML5 history mode, v-link will intercept the click event so that the browser doesn't try to reload the page.```

I don't really see the problem here, it makes sense that [v-link](http://vuejs.github.io/vue-router/en/link.html) prevents the default behaviour, you can use a simple method to improve it :)
```html
<a @click.prevent="navigateTo('home')">Home</a>
```

Use a method instead:

```javascript
navigateTo: function (nav) {
	// Do what you want here.
	// this.saveTheThing()
	this.$router.go({
		path: nav
	})
}
```

**Comment by weotch** [comment]
@Gomah with that approach you lose both `v-link` creating an `href` (which I want for SEO) and the setting of the `v-link-active` class.

**Comment by Gomah** [comment]
You can still specify an `href` as the `@click.prevent` will prevent it anyway.
For the `v-link-active` class, you can specify it in your method but indeed, it would be easier then to have a higher priority on `v-on` so you don't have to rewrite the `v-link` behaviour yourself.

**Comment by paulpflug** [comment]
the problem isn't the `e.preventDefault()` but the next line: `this.router.go(target)`
This will navigate the browser and stop the event bubbling.

a nice solution would be:
```html
<a v-link='{name: "home"}' v-on:click.capture='onClick'>Home</a>
```
just make sure you don't use `event.stopPropagation()` within your onClick

besides that it would make sense to lower the priority of `v-link` as a click on it normally is terminal.
