### ISSUE TITLE
vue3+ts项目打包后，我用 VS code的 Live Server 插件运行不加载RouterView组件

### ISSUE THREAD

**Issue by czmCWH** [vuejs/vue-router#3903]
![30691724917900_ pic](https://github.com/user-attachments/assets/6ae02e06-731b-442a-b04e-eb2408f4b300)
2中的RouterView组件不会自动加载根路由显示；必须通过1中的 RouterLink 标签切换才能显示路由的页面。
有啥办法让它直接显示RouterView 吗？

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
