### ISSUE TITLE
Memory leak when using functional components with Vue router in Vue 2.7.14

### ISSUE THREAD

**Issue by diegoexplicatis** [vuejs/vue-router#3907]
### Reproduction

https://github.com/diegoexplicatis/vue-2-functional-component-memory-leak

### Steps to reproduce the bug

See README.md of reproduction link

##### Project setup
```
npm install
```

##### Run project
```
npm run serve
```

#### How to reproduce memory leak

1. Open base url of project (printed in console)
2. Click on "Go to Test Component"
3. Click on Home
4. Open developer tools and take a heap snapshot
![take_heapsnaphot](https://github.com/user-attachments/assets/e85d8d20-7f53-4cb2-97a0-21a51a0f1504)

5. Filter for "Objects retained by detached DOM nodes"
![filter](https://github.com/user-attachments/assets/23088ce1-ec71-471f-bd7c-46c6b82868dd)

6. See there are detached elements, e.g. a paragraph element with id = testParagraph.
![detached](https://github.com/user-attachments/assets/6b589065-f330-4a9a-aab7-84459b9d6d6f)

7. Manually trigger garbage collection
![garbage_collection](https://github.com/user-attachments/assets/032a2bae-bd9b-44f8-8ae0-2975b257dca7)

8. Take another heap snapshot and filter for "Object retained by detached DOM nodes" again
9. See that e.g. the paragrpah is still being retained => paragraph element has leaked (it is detached from the DOM but is not being garbage collected)
![not_collected](https://github.com/user-attachments/assets/be59ae12-f1b5-441a-9a4f-e9363168dd3e)

10. Go to FunctionalComponent.vue to line 4 and change the parameter for functional to "false"
11. Redo steps 1 - 8
12. See that there are not detached elements (even without manually garbage collecting) => all elements have been properly garbage collected
![no_detached](https://github.com/user-attachments/assets/6600139d-43b2-46d5-b955-6d92a2b2393e)

### Expected behavior

I would expect that after executing steps 1-8,  e.g. the paragraph element is not being retained anymore and has been garbage collected independent of the value for the functional parameter in FunctionComponent.vue

### Actual behavior

Instead the paragraph element is being retained when using `functional: true` and does not get garbage collected.

### Additional information

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 6.27 GB / 23.86 GB
Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
Browsers:
    Edge: Chromium (128.0.2739.79)
    Internet Explorer: 11.0.19041.4355
npmPackages:
    vue: ^2.7.14 => 2.7.16
```

**Comment by posva** [comment]
As noted in other issues in Vue-router repo (v3, not this repo), some dynamic component usage might increase memory usage once. Only if the memory continually increases, that’s a leak

**Comment by diegoexplicatis** [comment]
@posva The memory usage does continually increase! When repeating steps 2. and 3. five times I get five detached paragraph elements that do not get garbage collected!
![Screenshot 2024-09-19 121649](https://github.com/user-attachments/assets/007c2c86-df2d-4abe-976d-da1d24275ff5)

**Comment by diegoexplicatis** [comment]
@posva Can you please reopen this issue? As I have pointed out in my last comment there is a continual increase of memory! If you don't plan to reopen this issue can you at least point me to some other resource where I can get help for this...

**Comment by posva** [comment]
You already opened https://github.com/vuejs/vue/issues/13212
If this is important to you, try coming up with a PR or upgrade to Vue 3
Herodevs can help you out with Vue 2 support
