### ISSUE TITLE
router-view在IE9下的时候，会把原先写在上面的class删除掉

### ISSUE THREAD

**Issue by redhat** [vuejs/vue-router#394]
outer-view在IE9下的时候，会把原先写在上面的class删除掉;
代码:
`<router-view class="view fade" v-bind:class="{'loading':loading}" transition="fade" transition-mode="out-in" keep-alive></router-view>`
IE9渲染之后
`<div class="fade-transition"></div>`
原来的view fade被删除了

**Comment by yyx990803** [comment]
Fixed in Vue.js core.
