### ISSUE TITLE
当手动修改了$el下的HTML元素后router无法正常工作

### ISSUE THREAD

**Issue by 7upcat** [vuejs/vue-router#396]
@yyx990803 应用中局部使用Vue改造为了兼容原本架构中的backbone，两个构架共同使用#app作为view展现的根结点，但是，当backbone改变了#app下的元素后，发现vue报错。

之前验证使用react 时有遇到类似的问题，不知是否vue也有这方面的限制。

### Vue.js & vue-router.js version
1.0.16, 0.7.11
 
### Steps to reproduce
（1）App 挂载在 #app下
（2） /index    页面
（3） /new    (未配置路由)  显示为空白
（4） 手工在 #app元素下增加一个element 比如 h1

### What is Expected?

正常返回/index页面

### What is actually happening?

```
[vue-router] transition.next() should be called only once.
vue-router.js?e71f:728 [vue-router] Uncaught error during transition: 
vue-router.js?e71f:1539 Uncaught TypeError: Cannot read property 'insertBefore' of null
```

**Comment by yyx990803** [comment]
通常情况下，第三方修改 DOM 以后无法保证正常工作，应该尽量避免。如果还是有问题，请做成可以直接看的重现开新的 issue，最好是 jsfiddle。

**Comment by danielsdeboer** [comment]
I was getting that same group of errors, turns out I was embedding my script twice on the same page. Hope that helps someone in the future.
