### ISSUE TITLE
如何在hash没发生变化的情况下刷新视图呢

### ISSUE THREAD

**Issue by hnlinzhi19** [vuejs/vue-router#397]
目前有个需求是页面中有刷新功能，只能刷新视图，不能触发整个网页刷新，此需求没有触发hashchange 这个有参数可以处理吗？

**Comment by KyLeoHC** [comment]
我也有过类似的需求，不过我是额外加一个参数t，顾名思义，就是一个时间戳参数而已，改变了hash，不过要是路由本身支持这个功能就更好了，比如$route.router.refresh()

**Comment by fnlctrl** [comment]
这个问题在这里提过..https://github.com/vuejs/vue-router/issues/296/

**Comment by horizon0514** [comment]
yyx的建议是重新fetchData，然后触发数据更新。
