### ISSUE TITLE
Router middleware

### ISSUE THREAD

**Issue by nblackburn** [vuejs/vue-router#399]
I was wondering if it would be better to depreciate `router.beforeEach` and `router.afterEach` in favor of route middleware like what is possible in recent versions of vuex.

```javascript
import auth from 'router/middleware';

middleware: [
    auth()
]
```

```javascript
export default {
    handle(request, next) {
        // before middleware
        let response = next();
        // after middleware
    },
};
```

To me this feels more graceful but i could well be wrong.

**Comment by yyx990803** [comment]
You can think of `beforeEach` as adding a middleware (which is a function that receives the `transition` object) - it's just an imperative API.

On the other hand, the `beforeEach` and `afterEach` hooks in `vue-router` is mostly just for analytics etc. - there's no "response" to speak of like in a server routing context. Actual logic is usually handled inside components' route hooks.

I'm not sure what would changing the API achieve (except for subjectively more graceful).

**Comment by nblackburn** [comment]
Your right that it doesn't really achieve much and it's purely subjective as are most things, i was just thinking it would be consistent with vuex to have the same means of declaring middleware (which i am quite fond of).
