### ISSUE TITLE
Data resolved from route doesn't trigger updates in component when route changes

### ISSUE THREAD

**Issue by cheapsteak** [vuejs/vue-router#40]
When resolving data from the route to a component, whatever value the component gets the first time doesn't get updated when the route changes. The newly resolved data from the route change seems to be ignored by the component

Given route:
```js
'/steps/:stepNumber': {
  component: 'foo',
  data: function (route, resolve, reject) {
    resolve({stepNumber: route.params.stepNumber});
  }
}
```

Component: 
```js
{
  data: function () {
    return {stepNumber: 0}
  }
}
```

In the template: 
```html
{{stepNumber}}
<a v-link="/steps/99">go to 99</a>
```

When initially at `/steps/1`, `{{stepNumber}}` in the template correctly displays `1`.
After clicking on the v-link, the url changes to 99, the component's `this.route.params.stepNumber` is "99", but the component's `this.stepNumber` remains 1 (whatever was first resolved by the router)

**Comment by yyx990803** [comment]
Should be working now after eed21c2731c96bfd738b4e00f63c8f087b9e78be

**Comment by cheapsteak** [comment]
Confirmed. Thank you!
