### ISSUE TITLE
export Route class

### ISSUE THREAD

**Issue by lepture** [vuejs/vue-router#401]
Can we export `Route` class? I need to re-use it.

**Comment by tejitak** [comment]
Can you provide a more specific use case?

If you mention a router instance, you can access by `$route.router` from components
http://vuejs.github.io/vue-router/en/route.html

**Comment by rpkilby** [comment]
The package is distributed with the `src` directory on npm, so you should be able to import the Route class from the route module.

eg, we're using jspm and can simply
```js
import Route from 'vue-router/src/route'
```
