### ISSUE TITLE
canReuse is ignored, view always destroyed on transition

### ISSUE THREAD

**Issue by AVGP** [vuejs/vue-router#404]
### Vue.js & vue-router.js version
1.0.17, 0.7.11

### Reproduction Link
https://jsfiddle.net/avgp/bfe4tc92/

### Steps to reproduce

1. Go to one of the routes (say "/foo")
2. Transition to another route (say "/bar")
3. Go back to the first route

### What is Expected?

The following things should happen upon transition between routes:

* `canReuse` should be called on the `transition.from` component
* `deactivate` should be called on the `transition.from` component
* `destroy` should *not* be called on the component, if `canReuse` returned true

### What is actually happening?

* `canReuse` is not called
* `deactivate` is called
* `destroy` is called, no matter what

This might be somewhat related to #403

**Comment by AVGP** [comment]
Nevermind, re-reading the docs carefully shows I'm wrong about how canReuse works, sorry!

**Comment by roblav96** [comment]
Where you able to use <router-view keep-alive>? I'm trying to figure out how I can make specific routes keep-alive and others not.

**Comment by AVGP** [comment]
Your issue in #403 is not resolved, I can't get *some* routes to keep-alive vs. others to not keep-alive, because there's nothing to hook into... so your last comment with toggling the router behaviour seems the way to go.

**Comment by roblav96** [comment]
Ye it's definitely not though... lol Totally broke everything.

### Here's how I achieved it:
```javascript
		'/map': {
			component: require( './routes/map/map-comp.vue' ),
			name: 'map.index',
			map: true
		},

		'/contacts-index': {
			component: require( './routes/contacts/contacts/contacts.vue' ),
			name: 'contacts.index'
		},

		'/activities': {
			component: require( './routes/activities/activities-comp.vue' ),
			name: 'activities.index'
		},

		'/static': {
			component: require( './routes/static/static-comp.vue' ),
			subRoutes: {

				'/public': {
					component: require( './routes/public/public-comp.vue' ),
					subRoutes: {
						'/login': {
							component: require( './routes/public/login/login.vue' ),
							name: 'public.login'
						},
						'/about': {
							component: require( './routes/public/about/about.vue' ),
							name: 'public.about'
						},
						'/register': {
							component: require( './routes/public/register/register.vue' ),
							name: 'public.register'
						},
						'/recovery': {
							component: require( './routes/public/recovery/recovery.vue' ),
							name: 'public.recovery'
						}
					}
				},
```
The root router-view has keep-alive and the static-comp.vue does not.
