### ISSUE TITLE
ajax请求走了路由

### ISSUE THREAD

**Issue by liucc1986** [vuejs/vue-router#408]
我用jquery的$.ajax 请求'/someUrl' 页面自动跳转至‘/’对应的路由了。‘/someUrl' 没有设置路由。
 但是如果用vue-resource发请求就不会有此问题。
我尝试访问/inexistence 不存在的网址，仍然都跳转至‘/’l了
求解

**Comment by yyx990803** [comment]
这应该是你服务器设置的问题...

**Comment by liucc1986** [comment]
能具体点吗？web服务我用的是vue-cli带的那个webpack的模板。存在什么问题呢？
