### ISSUE TITLE
Route aliases please!

### ISSUE THREAD

**Issue by cheapsteak** [vuejs/vue-router#41]
It would be great to be able to alias routes, since sometimes it makes sense to nest routes based on which layout they use, but I don't want to show that in the URL

`/basic/home`, `/basic/article/` and `/minimal/some-other-thing`

I want to just be able to use `/home` and `/article` but still use the nested views.

Can *almost* do this using route.redirect, but the route changes in that case

**Comment by cheapsteak** [comment]
I [tried implementing this](https://github.com/cheapsteak/vue-router/tree/alias) by copying a few chunks of code from `router.redirect`, and turns out that doesn't work for nested routes with multiple route-variables. I wonder if it's related to #44 and would be fixed if that's fixed

E.g. `router.alias({'/c/a/:foo/b/:bar': '/a/:foo/b/:bar'})` blank page

**Comment by yyx990803** [comment]
Thanks, fixed the test case.

**Comment by cheapsteak** [comment]
Yup that works! 
Here's what I have: https://github.com/vuejs/vue-router/compare/master...cheapsteak:alias?expand=1

I'm not really happy with the amount of code duplication I have though, pretty much copied everything related to redirect so lots of dupe code.
Also not sure if there needs to be a separate recognizer for redirects and aliases

Let me know if you'd prefer to write your own implementation or if I should make a PR.

**Comment by yyx990803** [comment]
I've merged your implementation and reduced the code duplication in https://github.com/vuejs/vue-router/commit/94159f51aa6788faf4f75432f76696a35b3aa6d3 :)

**Comment by cheapsteak** [comment]
Thanks so much :D
