### ISSUE TITLE
[feature] External url

### ISSUE THREAD

**Issue by blake-newman** [vuejs/vue-router#411]
Having the option to use the router.go API to allow going to external links would be nice. 

However this can be simply achieved in vanilla JS,  I had one scenario where a button linked to an external site under one condition and internal routing under another.  Putting a href and v-link is not possible as href get replaced.

This is a nice to have feature,  but I can see some relevant use cases.

**Comment by tejitak** [comment]
Doesn't the following example cover the your use case?
```
<template>
<div>
  <a @cilck="onClickButton">Button</a>
</div>
</template>

<script>
export default {
  methods: {
    onClickButton () {
      if (/*check some conditions*/) {
        location.href = 'https://external.com/'
      } else {
        this.$router.go({....})
      }
    }
  }
}
</script>
```

**Comment by blake-newman** [comment]
Yes it can be achieved this way,  however usage with v-link is limited.  Have to add a custom method to handle it. 

If v-link could be like `v-link="{ external:}

**Comment by webmasterslava** [comment]
This example doesn't work if you want to open the external link in the new tab. Using window.open() could be restricted by browser popup blocking.

**Comment by pxwee5** [comment]
@tejitak Is that the proper way to use vue router so that links will support both absolute and relative url ? 

Did some research and this is the simplest solution I can come up with. I still can't find a reason why `router-link` doesn't support external urls. 

```
<template v-for="(link, i) in links">
  <a v-if="RegExp('^https?://|^//').test(link.path)" :key="i" :href="link.path" class="c-nav__link" :title="link.name">{{ link.name }}</a>
  <router-link v-else :key="i" :to="link.path" class="c-nav__link" :title="link.name">{{ link.name }}</router-link>
</template>
```

**Comment by johncade** [comment]
👍
