### ISSUE TITLE
为什么 saveScrollPosition 不生效呢？

### ISSUE THREAD

**Issue by hq5544** [vuejs/vue-router#416]
vue-router 0.7.11, vue 1.0.17
主页面是一个 v-for 生成的列表，外层是 router-view 加载的包裹元素。
当点击列表元素跳转以后，返回主页面，直接返回到了顶部，为什么 saveScrollPosition 不生效呢？

```js
import VueRouter from 'vue-router'
import RouterMap from './map'
const router = new VueRouter({
    history: true,
    saveScrollPosition: true
})

router.map(RouterMap.map)
router.alias(RouterMap.alias)

export default router
```

**Comment by goofcc** [comment]
Do have this problem, I also encountered this problem, but also did not find a solution

**Comment by yyx990803** [comment]
`saveScrollPosition` 只有在 HTML5 history 模式下才生效。

**Comment by hq5544** [comment]
请问 history: true 是不是就是已经开启 HTML5 history 模式了呢？

**Comment by angerlover2** [comment]
你主页的v-for是不是请求的数据，可能是每次到这个页面就会重新请求一次，所以数据重新渲染了
