### ISSUE TITLE
Anchors are not working when set history=false

### ISSUE THREAD

**Issue by jingsam** [vuejs/vue-router#420]
### Vue.js & vue-router.js version
1.0.18, 0.7.11

### Reproduction Link
http://jsfiddle.net/jingsam/wn8duy2m/2/

### Steps to reproduce
Click the link at the bottom 

### What is Expected?
The page should scroll to the top

### What is actually happening?
The page does not scroll to the top, becames blank

**Comment by tejitak** [comment]
This is because a `hashchange` event occurs and the component is removed by router when the link '#top' is clicked.
When we can keep the component by the hashchange, it would work as work-around.
For the example, 
```
router.map({
  '/': {
    component: Foo
  },
  '/top': {
    component: Foo
  }
})
```
Or, 
```
router.map({
  '/': {
    component: Foo
  },
  '*': {
    component: Foo
  }
})
```
Another solution is implementing `onclick` to move a scroll to the element.

**Comment by yyx990803** [comment]
This doesn't work for an obvious reason: you are already using the hash as your routing state. If you want client side routing AND hash anchors, you should be using history mode.
