### ISSUE TITLE
access the v-link-active element on beforeEach and afterEach

### ISSUE THREAD

**Issue by jedierikb** [vuejs/vue-router#423]
Would be helpful to access the ```a``` elements which fired a route event.  Currently trying to do this with 

```
  router.afterEach(function (transition) {
    console.log( "after", transition );
    var $vlink = document.querySelector('.v-link-active');
    console.log( "$vlink", $vlink );
  });
```
returns the _last_ ```a``` element, not the current one.

I want this so I can trigger javascript animations on the a element.

**Comment by jedierikb** [comment]
overall goal, perhaps more elegantly solved another way, is to perform JS animations on the `v-link-active` elements

**Comment by fnlctrl** [comment]
Try
```javascript
router.afterEach(function (transition) {
    console.log( "after", transition );
    // The DOM is not updated

    this.$nextTick(() => { 
        // The DOM is updated now
        var $vlink = document.querySelector('.v-link-active');
        console.log( "$vlink", $vlink );
    })
});
```

**Comment by yyx990803** [comment]
@jedierikb I think @fnlctrl 's suggestion should work.

Obviously it's much easier to use CSS animations for `v-link-active` elements - if you do want to use JS animations, another way to achieve that is writing a custom directive that watches `vm.$route` and applies animations accordingly:

``` js
bind () {
  this.vm.$watch('$route', route => {
    if (route.path === this.path) {
      // ...
    } else {
      // ...
    }
  })
},
update (path) {
  this.path = path
}
```
