### ISSUE TITLE
vue-router的组件问题

### ISSUE THREAD

**Issue by tcstory** [vuejs/vue-router#428]
我发现,教程给出的vue-router的使用方法,都需要把组件注册成为全局的,但是,有没有办法让路由和根实例的内部的组件配合使用呢?
例如

```
new Vue({
    el: 'body',
    components: {
        'mission-pane': require('./components/mission-pane.vue')
    }
});
```

例如,在这种情况下,我怎么使用mission-pane 这个组件呢?

**Comment by fnlctrl** [comment]
路由组件是路由组件，根组件是根组件。
路由组件是用于替换根实例(App)的模板里的<router-view>的
根组件是写在根实例的模板里的

你的例子应该这么用
```html
<body>
    <mission-pane></mission-pane>
</body>
```

建议先仔细读一下vue的文档

**Comment by tcstory** [comment]
谢谢 @fnlctrl
