### ISSUE TITLE
微信浏览器里面计算签名的问题

### ISSUE THREAD

**Issue by sandysong** [vuejs/vue-router#429]
微信jssdk在wx.config计算签名的时候，不论我用hashbang还是h5的pushstate模式都无法得到正确的结果，只有刷新页面才行。而根据我多次测试，感觉微信是以上一次发起真正的http请求的地址作为当前URL的，这就导致：
- 在计算signature的时候，我无法知道微信当前用哪个URL来计算signature。
- 在微信支付的时候，我无法知道用户上一次刷新页面是在什么地方，而微信支付后台只能配置3个目录。

为解决这个问题，我现在只能在访问到需要调用微信jssdk或者需要微信支付的页面时直接href连接过去而不使用v-link，这样给用户的体验上比较难受。

也许是微信的问题，不过我看另一个ironic写的应用“每日优鲜”貌似没这个问题，我不知道问题是不是出在hash上。

**Comment by yyx990803** [comment]
你在页面加载/刷新的时候就把最初的那个 URL 存下来不就行了？在 vue-router 启动之前做这个事情。

**Comment by ghost** [comment]
我用的是这个方法，在启动vue之前就wx.config配置，然后在另一个页面里调用地理位置时，苹果没问题，安卓报签名失败

**Comment by yyxx9988** [comment]
这个方法仅对IOS有效，安卓需要使用当前的URL进行签名
