### ISSUE TITLE
Multiple routes having same component

### ISSUE THREAD

**Issue by znck** [vuejs/vue-router#430]
If same component is attached to multiple routes. Then if it navigates from one route to other (Both routes having same component), `attached` hook is not called. Same for history back.

**Comment by fnlctrl** [comment]
It's expected behavior since the component is reused in-place, and not destroyed and created and attached again.
Checkout router's `data`, `activate` hooks, they should be what you need.
If you do want it to be called, use 
```javascript
route: {canReuse: false}
```
