### ISSUE TITLE
Router should not match extensions

### ISSUE THREAD

**Issue by egoist** [vuejs/vue-router#431]
### Vue.js & vue-router.js version
1.0.17, 0.7.11

### Steps to reproduce
Use `vue-router` with such routes mapping:

```js
{
  '/:id.html': {
    component: require('./id')
  }
}
```

Is there a way to prevent matching `.html` extension?

### What is Expected?
```js
{
  params: {id: 'xxx'}
}
```

### What is actually happening?
```js
{
  params: {'id.html': 'xxx'}
}
```

**Comment by yyx990803** [comment]
Why do you want the `.html` extension at the end? Most people want to prevent it...

**Comment by egoist** [comment]
Yes, it's a rare use case, but maybe we should only allow `a-zA-Z0-9_` in param name? Or only do this in `strictName` mode 😂  Just a random thought.

**Comment by yyx990803** [comment]
Params are delimited by `/`. I don't think we will support this... unless you can submit a PR to implement it.
