### ISSUE TITLE
canActivate hook returns null context

### ISSUE THREAD

**Issue by sqal** [vuejs/vue-router#432]
### Vue.js & vue-router.js version
1.0.20, 0.7.11

### Steps to reproduce

```
export default {
  route: {
    activate() {
      console.log('hook activate', this);
    },
    deactivate() {
      console.log('hook deactivate', this);
    },
    canActivate() {
      // this === null
      console.log('hook canActivate', this)
    },
    canDeactivate() {
      console.log('hook canDeactivate', this)
    },
    canReuse() {
      console.log('hook canReuse', this);
    },
  },
};
```
### What is Expected?

canActivate hook should have component's context, not null

### What is actually happening?

canActivate hook context is null, other hooks works correctly

```
canActivate() {
  // this === null
  console.log('hook canActivate', this)
}
```

**Comment by blake-newman** [comment]
This is intended,  this is because at this point the component has not yet been initialised.  

Upon the `activate` hook the component becomes initialised.  The `canActivate` hook should be used to determine if the component can become initialised.

**Comment by sqal** [comment]
Ohh ok. Sorry for false alarm then. So if i may ask you a question, how should i handle this situation: I have profile component that can only be viewed if user has logged in. I use vuex action isLoggedIn which is a promise. And since i can't access component context, how can i check my vuex state in canActivate hook? Should i just use activate hook only?

```
  import { isLoggedIn } from 'vuex/actions';

  export default {
    name: 'Profile',
    vuex: {
      actions: {
        isLoggedIn,
      },
    },
    route: {
      activate() {
        return this.isLoggedIn();
      },
      canActivate() {
       return this.isLoggedIn();
      },
    },
  };
```

**Comment by blake-newman** [comment]
There is many ways to do this.  Depending on what the action does,  it can return which you can use to follow on from the action.  

However as the purpose of Vuex is the maintain state and help with the control flow you could pass in the transition object to the action call.  If the transition object is passed then you can call the correct method based on the result of the action. 

It may also be that the action could return a promise. I'd advise to try centralise as much logic Vuex, to keep functionality similar across the application. If the action returns something then it should remain centralised to that component to help reduce complexity.  

It's an open debate how to do this,  but go with the solution that reduces complexity and helps maintainability.
