### ISSUE TITLE
router如何配合vue后缀的文件使用？怎么引用都是失败！

### ISSUE THREAD

**Issue by VinceXie** [vuejs/vue-router#433]
看了官方教程。用的是官方例子更改。
router.map里面匹配的是vue.extend的组件构造器就可以用。但如果我写成vue后缀的文件如a.vue，然后import进来，无论怎么写都不能成功地路由到那个组件。

求解！

**Comment by jingsam** [comment]
用vue-cli把你的项目脚手架搭好

**Comment by mlyknown** [comment]
vue-cli  妥妥的
