### ISSUE TITLE
文档中写到的route.go()方法有两个可选的参数params和query，可是实际却没有实现

### ISSUE THREAD

**Issue by renjian93** [vuejs/vue-router#435]
### Vue.js & vue-router.js version
1.0.16, 0.7.11

文档中写到的route.go()方法有两个可选的参数params和query，可是实际却没有实现。
```javascript
    {
      name: '...',
      // params 和 query 可选
      params: { ... },
      query: { ... }
    }
```

**Comment by liujb** [comment]
有效果的啊，this.$router.go({name: 'routerName', query: { name: '123' }}); 你留意一下URL的变化。

**Comment by renjian93** [comment]
@liujb 是我用法错误了。 多谢了。
