### ISSUE TITLE
this.$router.go without specified name or path

### ISSUE THREAD

**Issue by simplesmiler** [vuejs/vue-router#437]
It would be useful to have `this.$router.go({ ... })` and `v-link="{ ... }"` assume the current state to be the target if `name` or `path` are not specified, thus updating params and query string on the current state and triggering `data` hook.

This can be achieved with `this.$router.go({ name: this.$route.name, ... })` and `v-link="{ name: $route.name, ... }"`, but only for named states.

**Comment by azamat-sharapov** [comment]
> triggering `data` hook
> This can be achieved with `this.$router.go({ name: this.$route.name })`

I doubt it works.. I'm waiting for #296 for this.

**Comment by simplesmiler** [comment]
@azamat-sharapov it works when params or query do change, which is what I'm after :wink:
I've edited the details in.

**Comment by azamat-sharapov** [comment]
Well.. that isn't ideal in some cases, because leaves history dirty. Let's see what Evan thinks about #442

**Comment by simplesmiler** [comment]
What I'm trying to say is that this feature request (default to current state when none specified) is orthogonal to the #296 (option to force reload the current state).

Regarding the dirty history, this can already be solved with `replace: true`.

**Comment by simplesmiler** [comment]
Closed in favor of https://github.com/vuejs/vue-router/issues/461#issuecomment-209551099
