### ISSUE TITLE
Error after build vue code

### ISSUE THREAD

**Issue by erguotou520** [vuejs/vue-router#438]
### Description
When I run with the source code using `vue` and `vue-router`(called src mode), everything goes ok. But after I built the project(build with coolie, called build mode), some thing went wrong. I debugged the two codes, but had no idea about where is wrong.

### Demo Link
[src mode](http://vue-demo.erguotou.me/)
[build mode](http://vue-demo-uglify.erguotou.me/)

### Steps to reproduce
A(src mode):
1. click `go to edit`
2. click `go to add`
3. click `go to edit`
4. click `go to add`
Everything goes OK

B(build mode):
1. click `go to edit`
2. click `go to add`
3. click `go to edit`
4. click `go to add`
The add page contains the edit data.

### What is Expected?
Build code runs the same with the source code.

### What is actually happening?
In build mode, the add page contains the edit data.

### Repository
The repository is `https://github.com/erguotou520/vue-coolie-demo`, the `src` directory links to `http://vue-demo.erguotou.me/` and the `dest` links to `http://vue-demo-uglify.erguotou.me/`.

### Build command
```shell
npm install -g coolie
coolie build -d src
```

### Vue.js version
v1.0.13

### VueRouter.js version
v0.7.11

**Comment by tejitak** [comment]
@erguotou520 
I quickly checked your code. The code built by Coolie looks returning a cached module when duplicated paths are specified.

So the component for 'new' references exactly same instance created for 'edit'. Try the following code to work same with the src code though I'm not sure that is best solution.

```
    '/demo': {
      component: function(resolve) {
        require.async('./app/demo/demo.js', function(module) { resolve(Object.assign({}, module)) });
      },
      auth: false
    },
    '/demo/:id': {
      component: function(resolve) {
        require.async('./app/demo/demo.js', function(module) { resolve(Object.assign({}, module)) });
      },
      auth: false
    }
```

**Comment by cloudcome** [comment]
# 1、现象分析
在构建之前看似表现正确，其实是 coolie.js 的 bug，相同的模块没有被缓存下来，导致 vue 组件在进入 `demo/:id` 或者 `demo` 路由时不停的实例化出新的组件。

期望的表现是：构建前后都应该是与构建之后一致。

该 bug 已经在 coolie.js@1.3.4 修正。修正后：

![](http://s.ydr.me/@/res/20160401213835315817233352)

# 2、如何写

```
// index.js

// ...
'/demo': {
      component: function (resolve) {
        require.async('./app/demo/demo.js', function (exports) {
          resolve(exports());
        });
      },
      auth: false
    },
    '/demo/:id': {
      component: function (resolve) {
        require.async('./app/demo/demo.js', function (exports) {
          resolve(exports());
        });
      },
      auth: false
    }

// ...
```

同样的 `demo.js` 模块导出一个 function 用于生成动态不同的实例。

```
// demo.js

define(function (require, exports, module) {
  'use strict';
  var testData = {
    email: 'test@test.com',
    password: 'test'
  };
  module.exports = function () {
    return {
      template: require('./demo.html', 'html'),
      data: function () {
// ...
```
