### ISSUE TITLE
网址链接里的#!如何消除？ how to delete '#!' in url?

### ISSUE THREAD

**Issue by VinceXie** [vuejs/vue-router#439]
用了router后地址栏显示网址都带有#!，如http://localhost:8080/#!/hello。有方法消除里面的#!吗？

**Comment by yyx990803** [comment]
请仔细看文档... history: true

**Comment by mlyknown** [comment]
。。。。  还以不能消除。。

**Comment by yyx990803** [comment]
http://router.vuejs.org/zh-cn/options.html

**Comment by jingsam** [comment]
我发现消除后不能正确识别主目录，比如在浏览器中直接输入www.a.com/b/c会将www.a.com/b识别为主目录导致不能正确地显示页面

**Comment by yyx990803** [comment]
再说一遍，仔细看文档。

**Comment by jingsam** [comment]
尤大大息怒，又看了一遍文档，发现有root这个属性。实话说，我确实仔细看了文档很多遍，但是我记性不太好，如果没有use case的话很难记住每个属性的作用。
我碰到这个问题是缘于我之前用vue开发的一个SPA，发现锚点跳转始终出错，切换为history模式后发现锚点又可以正确跳转了，但是history模式下存在不能正确识别root的问题。由于注意力集中在锚点的问题上，就没注意有root这个属性。
由于页面托管到Github Pages，而Pages不支持history模式，导致我只能用hashbang模式。在hashbang模式的锚点跳转问题，我在很多地方都提问了，没有人回答，可能也是这个问题太幼稚了，也可能是我没仔细看文档。总之，锚点的问题一直没有解决。
最后感谢尤大大创造了vue，vue让我规避了很多前端工程化难题，以组件化的思想开发，这对从后端转前端的我来说，真是太幸福了。

**Comment by yisibl** [comment]
http://router.vuejs.org/zh-cn/essentials/history-mode.html
