### ISSUE TITLE
About the back page

### ISSUE THREAD

**Issue by mlyknown** [vuejs/vue-router#440]
After entering the page, how can't make it back? Clear historical record should be ok, but don't know how to do it.

**Comment by tejitak** [comment]
How about `history.back()`?

**Comment by mlyknown** [comment]
I don't want to page can back.So I can clear the browser's history.Do you understand?My English is not good.Ha ha 0.0

**Comment by tejitak** [comment]
I see.
Try to Use `router.replace` (or v-link replace option).
http://vuejs.github.io/vue-router/en/api/replace.html

**Comment by mlyknown** [comment]
ok.thanks!!!

**Comment by mlyknown** [comment]
I know this way before. In fact,I want to kown how is there a way to can directly to clear browser history. And Another problem is that I can return to specify the page without clear  historical record,for example,there are theree historical records are respectively  'pageA'  'pageB'  'pageC'. Now is 'pageC', I want to go 'pageA' when I return.Maybe I can listen to history.popstate, and then router.go('pageA'), but the page has the effect of beating,I Don't know is there a better way to resove this problem .
Ha ha.

**Comment by liupei2012** [comment]
```
route: {
      activate: function (transition) {
        this.sourceView = transition.from.name  // here you can get the source page where you are from
        console.info('xxx activate!')
        transition.next()
      },
      deactivate: function (transition) {
        console.info('xxx deactivated!')
        transition.next()
      }
    }

```
