### ISSUE TITLE
[FEATURE] Add "onRouteError" Hook

### ISSUE THREAD

**Issue by roblav96** [vuejs/vue-router#441]
I'm using vue heavily in my project [My Convoy](https://myconvoy.org/) with the cordova native page transitions plugins.

Now when a route error happens, the screenshot to my intended transition stays on the screen thus freezing my app.

It would be nice if we could incorporate something like:

``` javascript
Router.onError( function ( trans, error ) {
    console.error( error )
    window.plugins.nativepagetransitions.cancelPendingTransition()
} )
```

Is this possible?

Currently I'm doing this:

``` javascript
window.onerror = function ( msg, url, line, column, err ) {
    window.plugins.spinnerDialog.hide()
    window.plugins.nativepagetransitions.cancelPendingTransition()
}
```

but it would be nice to have the Router method in case an error never occurred.

**Comment by yyx990803** [comment]
There's an open PR for this: https://github.com/vuejs/vue-router/pull/393
Will probably land in next minor release.

**Comment by roblav96** [comment]
Awesome! That would be perfect! Thank you

**Comment by nblackburn** [comment]
This is exactly what i am looking for, looking forward to seeing this added.

**Comment by fnlctrl** [comment]
@roblav96 @nblackburn 
You can actually use beforeEach as onError hook for now:

``` javascript
// vue-router 0.7
router.beforeEach(({next}) => {
   try {
     next()
   } catch (e) {
     // onError hook
     ...

     // After processing error, don't forget to throw it back
     throw e
   }
})
```

**Comment by posva** [comment]
Closing as this has been implemented as `router.onError`
