### ISSUE TITLE
Add a section explaining history mode

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vue-router#445]

**Comment by posva** [comment]
@yyx990803 What should be explained about history mode?
This is something to include in both versions docs, isn't it?

**Comment by yyx990803** [comment]
@posva explaining what the `history.pushState` API does, and how to configure servers to work with history mode (redirecting to the same HTML file). Some users seem to be confused about the hash because they don't know what history mode is. Yes, this should be in both versions.
