### ISSUE TITLE
Vue app inside Java War

### ISSUE THREAD

**Issue by odranoelBR** [vuejs/vue-router#446]
Hello all
Im starting an app using this boilderplate : https://github.com/vuejs-templates/webpack
And need to pack this inside an .war java to run inside WebLogic server.
On develop everything works fine, but on npm run build, copyng the static / index.html to my java project the routes dont work. If i redirect '*' to /any-route, works.

I did a test on apache server and droped static/ index.html on WWW, but same problem 404 on routes

**Comment by yyx990803** [comment]
The dev server is pre-configured to work with HTML5 history routing. You need to configure your production server accordingly. http://router.vuejs.org/en/options.html#history

**Comment by odranoelBR** [comment]
Tks a lot !

**Comment by odranoelBR** [comment]
It worked, but now my components dont show... Any Idea ?
