### ISSUE TITLE
query params encoded multiple times

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [vuejs/vue-router#449]
### Vue.js & vue-router.js version
1.0.17, 0.7.11

### Reproduction Link
https://jsfiddle.net/ayLph0mw/

### Steps to reproduce
Click on the Bar link and look at the path

### What is Expected?
having a query only encoded once

### What is actually happening?
the params are encoded two times in this example. In my codebase they are encoded 3 times (I was not able to reproduce it in a fiddle). The problem is they are only decoded 2 times. So in my case not only it makes url uglier when I retrieve the `$route.query` a get an urlEncoded string.

**Comment by tejitak** [comment]
Hi, it's duplicated issue with https://github.com/vuejs/vue-router/issues/378
The fix will be included in the next release
Please close this issue.
