### ISSUE TITLE
Support get route by route.name

### ISSUE THREAD

**Issue by fundon** [vuejs/vue-router#450]
Sometimes, I want to get the route data by name, but I can not find the API. So please support it.

**Comment by azamat-sharapov** [comment]
Can you show example?

**Comment by OEvgeny** [comment]
For example I need to switch query for current route.
```js
this.$router.go({query})
```
is not working at all.
```js
this.$router.go({path: this.$route.path, query})
```
Will also not work correctly, because `path` already contains query string.

**Comment by fundon** [comment]
@azamat-sharapov 

Example: 

```js
router.map({
  '/login': {
    name: 'login',
    component: Login,
    title: '登录'
  },
  '/join': {
    name: 'join',
    component: Join,
    title: '注册'
  },

  '/settings': {
      name: 'settings',
      component: Settings,
      title: '我的'
    },
      '/settings/profile': {
        name: 'settings-profile',
        component: SettingsProfile,
        title: '设置',
        parentName: 'settings'
      },

      '/settings/interface-style': {
        name: 'settings-interface-style',
        component: SettingsInterfaceStyle,
        title: '风格',
        parentName: 'settings-profile'
      },
      '/settings/interface-style-theme': {
        name: 'settings-interface-style-theme',
        component: SettingsInterfaceStyleTheme,
        title: '主题',
        parentName: 'settings-interface-style'
      },
      '/settings/interface-style/background': {
        name: 'settings-interface-style-background',
        component: SettingsInterfaceStyleBackground,
        title: '背景',
        parentName: 'settings-interface-style'
      },
      '/settings/interface-style/background-music': {
        name: 'settings-interface-style-background-music',
        component: SettingsInterfaceStyleBackgroundMusic,
        title: '背景音乐',
        parentName: 'settings-interface-style'
      }
})
```

When the current route is `/settings/interface-style/background`, i want to use current `route#parentName` to get the route `/settings/interface-style`.

Why? Sometimes I don't just show the `Back` on navbar, want to show the `parent route`'s title.

**Comment by azamat-sharapov** [comment]
@OEvgeny that's more related to https://github.com/vuejs/vue-router/issues/437#issuecomment-204083654.

@fundon makes sense. But what I personally do in this case is store all map object in separate module and then create helper function to get map object. Something like this:
```
// ./stores/router.js

export const map = {
    '/settings/profile': {
        name: 'settings-profile',
        component: SettingsProfile,
        title: '设置',
        parentName: 'settings'
    },
}

export const getRouteByName = (name) => {
  let route = null
  Object.keys(map).some(path => {
    if (map[path].name === name) {
      route = map[path]
      return true
    }
  })
  return route
}
```

It's quick demo and could be improved, but you get the idea.

**Comment by fundon** [comment]
@azamat-sharapov Nice example.

**Comment by mxmaxime** [comment]
Use the `resolve` method, on `Router` object:
```
$router.resolve({name: 'landing'})
```
https://router.vuejs.org/en/api/router-instance.html#methods

**Comment by Exotelis** [comment]
> Use the `resolve` method, on `Router` object:
> 
> ```
> $router.resolve({name: 'landing'})
> ```
> 
> https://router.vuejs.org/en/api/router-instance.html#methods

I would not recommend using resolve over a map. The get() operation is 15 times faster. I ran 100.000 'find' operations and here is the result:
```
Map.get(): 402.09499999764375 ms.
$router.resolve(): 6512.219999996887 ms.
```

**Comment by mxmaxime** [comment]
Thank you @Exotelis 
Could you provide an example of `Map.get`? How can we use it? I didn't found any reference of it in the documentation.

**Comment by Exotelis** [comment]
> Thank you @Exotelis
> Could you provide an example of `Map.get`? How can we use it? I didn't found any reference of it in the documentation.

Hi. 
I am using it like this

```
function flattenRoutes (routes: Array<object>, parentPath: string = ''): Array<any> {
  let flatRoutes: Array<any> = [];
  for (let i in routes) {
    const route: any = routes[i];
    const path: string = parentPath !== '' && (route.path).charAt(0) !== '/' ? parentPath + '/' + route.path : parentPath + route.path;

    flatRoutes.push([ path, route ]);
    if (typeof route.children !== 'undefined' && route.children.length > 0) {
      flatRoutes = [ ...flatRoutes, ...flattenRoutes(route.children, path) ];
    }
  }

  return flatRoutes;
}
```
flattenRoutes walks recursively through all of your routes and creates an array that looks like:

```
[
 ['/', { path: '/' ... }],
 ['/dashboard', { path: '/dashboard' ... }],
 ['/dashboard/children', { path: '/children' ... }]
]
```
you can use this array to create a new map and use all of the map functions documented [here](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Map)
```
const routesMap = new Map(flattenRoutes(routes));
```
Note that this example sets all paths as the map key. If you want to look up routes by its name, you have to change the implementation slightly
```
flatRoutes.push([ route.name, route ]); // for example
```
but then you should make sure that the key 'name' does exist in your route definitions. I decided to use the path as key, because this is the only required setting of a route as you can see [here](https://router.vuejs.org/api/#routes).
