### ISSUE TITLE
Vue router 路由管理

### ISSUE THREAD

**Issue by DebugIsFalse** [vuejs/vue-router#456]
用webpack打包
router.map({
    '/index' : {
        component : function( resolve ){
            require( ['../webcomponent/index/index.vue'],resolve );
        }
    }
})
这样的格式编译出来的文件一直是数字文件比如3.3.js都是数字类型的文件
有没有方式编译出来直接是当前index.vue文件名作为JS文件名
我理解的是这样生成的规则是根据webpack模块化管理生成的对应回调方法的参数名

**Comment by fnlctrl** [comment]
这是webpack的分包行为 跟vue没有关系

**Comment by DebugIsFalse** [comment]
我测试过也觉得是webpack的问题。你有现成的解决方案么

**Comment by fnlctrl** [comment]
请阅读webpack文档 [Code Splitting](http://webpack.github.io/docs/code-splitting.html)

**Comment by DebugIsFalse** [comment]
其实我就是想目录文件看着美观一些，哈哈，谢谢。在你说之前我看了ensure这个东西。调试其实有source_map还好。其实紧紧为了编译之后文件的美观程度

**Comment by yyx990803** [comment]
这个不属于 vue-router 的问题。
