### ISSUE TITLE
v-link name and parameters format issue.

### ISSUE THREAD

**Issue by teledirigido** [vuejs/vue-router#457]
I have the following route:

```
'/news/:term/:slug': {
	name: 'news-category',
	component: require('./vue/layouts/page-news.vue')
},
'/news/:id/:slug': {
	name: 'news-single',
	component: require('./vue/layouts/single-news.vue')	
},
```
I also have the following link:
`
<a v-link="{ name: item.name, params: item.params }">{{item.title}}</a>
`

And my Item object has the following data:
```
{ "name": news-category", 
  "title": Category 1", 
  "params": { 
     "term": "n-cat", 
     "slug": "category-1" 
  }
}
```

My problem is that when I click on my v-link vue-router is taking me to news-single component. 

However If I change my `news-category` url from `'/news/:term/:slug'` to `'/news/cat/:term/:slug'` it works without problems. 

I'm using:
vue-router: 0.7.13
vue: 1.0.21

Is this a bug?

**Comment by yyx990803** [comment]
Please provide a reproduction.

**Comment by teledirigido** [comment]
@yyx990803 Thank you so much for your quick answer. I have a deployed version in here:
http://pnairport.blacksheep.design/news

If you see the console I've added a log under:

```
route: {
   activate(transition){
      console.log( transition.to )
   }
}
```

on `page-news.vue` and `single-news.vue`. Should I also share the source code files or repo?

**Comment by fnlctrl** [comment]
Your routes are self-contradictory.
```javascript
'/news/:term/:slug': {
    ...
},
'/news/:id/:slug': {
    ...
},
```

Now, how on earth would `vue-router` know `/news/foo/bar` belongs to which route?

**Comment by teledirigido** [comment]
@fnlctrl with named routes? http://vuejs.github.io/vue-router/en/named.html

**Comment by azamat-sharapov** [comment]
@fnlctrl how about moving `vue-router` to Mars?
```
'/news/:{term:[A-Za-z]}/:slug': {
    ...
},
'/news/:{id:[0-9]}/:slug': {
    ...
},
```

Complicated though :confused:

**Comment by fnlctrl** [comment]
@teledirigido Names are states. States are not passable in urls.
Now, without clicking anything in your page, the user comes from another website by the url '/news/foo/bar', what page should vue-router show?

**Comment by teledirigido** [comment]
Got it @fnlctrl, thank you for explaining this. you're right.
