### ISSUE TITLE
replace在部分android机型下无效

### ISSUE THREAD

**Issue by lzhwWeb** [vuejs/vue-router#460]
使用router时在返回时需要跳过当前页面，使用replace后在android的部分机型，改功能无效

**Comment by yyx990803** [comment]
什么机型你好歹得说下吧？...

**Comment by lzhwWeb** [comment]
opop x909 系统版本4.1.1
华为荣耀3 系统版本4.2.2

**Comment by fnlctrl** [comment]
@lzhwWeb  请使用jsfiddle, codepen之类的工具提供重现

**Comment by fnlctrl** [comment]
Closed due to inactivity.

**Comment by ckken** [comment]
same issue for HUAWEI MT7-TL10  android 6.0, emui system 4.0

**Comment by ckken** [comment]
http://shinygang.coding.me/#/list  for example

**Comment by ghost** [comment]
同样的问题， 三星G9300 和vivo x21上，使用的是nuxt/core@2.12.0   vue-router@3.1.6
