### ISSUE TITLE
关于fullPath，快速获取当前路径

### ISSUE THREAD

**Issue by Astray-git** [vuejs/vue-router#468]
之前可以获取当前路径（有多个路由共享一个视图组件时），改变query来刷新当前页面数据：
```js
// modify query
newQuery.page = 2
this.$router.go({
  path: this.$route.fullPath,
  query: newQuery
})
```
现在`this.$route.fullPath` 在 772d5d0fcfef15dc40123ca0ce9422e2eb4dc3a5 里被去掉了，`fullPath`只能通过遍历`matched`获取了。
这里去掉`fullPath`暴露是出于什么考虑呢？
或者有没有其他获取当前路径的方法？
谢谢。

**Comment by scottsut** [comment]
现在Route对象里貌似用path代替了原来fullPath的作用

**Comment by Astray-git** [comment]
path和以前一样，是有query部分的。

**Comment by yyx990803** [comment]
以后会支持直接 `router.go({ query: ... })`，也就不需要自己获取 fullPath 了。

**Comment by Jokcy** [comment]
@yyx990803 fullPath是有用的，有时候我们需要对比当前是否处于某个路由上，现在没有什么好的办法去进行比较了

**Comment by geekx63** [comment]
@yyx990803 fullPath的确有用的，有时候我们菜单高亮需要匹配这个字段。
如：
路由是：/path/:type
真正路径：/path/list （此时path为/path/list，而fullPath为/path/:type）
这样匹配路由时比较费力。
希望打开fullPath.

谢谢

**Comment by PLQin** [comment]
window.location.href

---

let routeData = this.$router.resolve({name: 'routeName', query: {data: "someData"}});
window.open(routeData.href, '_blank');
