### ISSUE TITLE
Path with anchor

### ISSUE THREAD

**Issue by azamat-sharapov** [vuejs/vue-router#47]
How can I get HTML `id` links like this: `https://github.com/vuejs/vue-router#basic-example` work with router? 

I have route `/page` mapped to a component, but additionally I have different sections on that page. So I want to access different sections with hash links like: `/page#section1`. But router is trying to recognize those URLs with hash and taking it as 404, because I have `*` mapping for 404. If I add `/page#section1` mapping to router, it doesn't show 404, but anchors don't work, like you would expect from standard HTML.

**Comment by manudurgoni** [comment]
Same issue for me.

**Comment by yyx990803** [comment]
Should now work via 1b6f3c9
Note the scrolling to anchor would not work if the view switch has a transition that delays the anchor element from entering the DOM for more than 1 tick.

**Comment by azamat-sharapov** [comment]
Thanks Evan.
