### ISSUE TITLE
active class is not added when using literal string inside v-link

### ISSUE THREAD

**Issue by sqal** [vuejs/vue-router#478]
### Vue.js & vue-router.js version
1.0.18-(up probably), 0.7.13

### Reproduction Link
http://www.webpackbin.com/41X8PQDlW

### What is Expected?
Active class should be added to the link when passing route name to the v-link directive as literal string.

### What is actually happening?
Class is not added at all .

**Comment by fnlctrl** [comment]
Prefixing the links with '/' solves this problem, and it's actually the proper way to do it. :smile: 

``` html
<a v-link="'/foo'">Go to Foo</a>
<a v-link="'/bar'">Go to Bar</a>
```
