### ISSUE TITLE
Routes not working with app component

### ISSUE THREAD

**Issue by anthony-pinskey** [vuejs/vue-router#479]
Hi There!

I am using the vue-webpack-boilerplate and I was testing the vue-router today and noticed that when I try to use the component tag (  <app></app> ) such as:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>VueJS Starter</title>
  </head>
  <body>
     <app></app>
  </body>
</html>
```

I get the following errors:
`[vue-router] <router-view> can only be used inside a router-enabled app.`
`[vue-router] v-link can only be used inside a router-enabled app.`

But if I use a regular element with an id of the component  <div id="app"></div> on my index.html in the body element it works just fine.

Is it possible to use component tags with the router? I'd like to because without the component tags it appears that vue-devtools in Chrome will not work properly without them.

thanks!

**Comment by sqal** [comment]
Sure you can. I am doing it this way:

{ 
import App from 'components/App'
 
...

router.start({
  components: { App },
  store,
}, 'body');
```

**Comment by anthony-pinskey** [comment]
@sqal are you having the v-links and router-view inside the body element then and not the <app> component?

**Comment by sqal** [comment]
No no, all my template is inside `App` component and my html looks just like yours ;)

**Comment by anthony-pinskey** [comment]
@sqal Gotcha! For some reason i still get the following errors:

`[vue-router] <router-view> can only be used inside a router-enabled app.`
`[vue-router] v-link can only be used inside a router-enabled app.`

Here is my setup:

main.js
```
    import Vue from 'vue'
    import App from './App'
    import VueRouter from 'vue-router'
    import VueResource from 'vue-resource'
    Vue.use(VueResource)
    Vue.use(VueRouter)

    /* eslint-disable no-new */
    new Vue({
      el: 'body',
      components: { App }
    })

    var router = new VueRouter({
      hashbang: false,
      history: true,
      linkActiveClass: 'active-class'
    })

    // Define some components
    var Foo = Vue.extend({
      template: '<p>This is foo!</p>'
    })

    var Bar = Vue.extend({
      template: '<p>This is bar!</p>'
    })

    /* Route Map */
    router.map({
      '/home': {
        component: Foo
      },
      'about': {
        component: Bar
      }
    })

    /* Route Redirects */
    router.redirect({
      '*': '/home'
    })

    /* Bootstrap routes to the main component */
    router.start({
      components: { App }
    }, 'body')

```

index.html
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>VueJS Starter</title>
  </head>
  <body>
    <app></app>
  </body>
</html>
```

App.vue

<template>
  <div id="app">
    <img class="logo" src="./assets/logo.png">
    <hello></hello>
    <a v-link="{ path: '/home' }">Go to Foo</a>
    <a v-link="{ path: '/about' }">Go to Bar</a>
    <p>
      Welcome to your Vue.js app!
    </p>
    <router-view></router-view>
  </div>
</template>

<script>
import Hello from './components/Hello'

export default {
  data: function () {
    return {
      name: 'VueJs'
    }
  },
  ready () {
    // Run when component is initialized and ready
  },
  components: {
    Hello
  }
}
</script>

**Comment by sqal** [comment]
```
    new Vue({
      el: 'body',
      components: { App }
    })
```

You don't need to initialize Vue instance here (and you shouldn't) becouse you vue-router creates it for you in `router.start`. So just get rid of this part and all should work fine.

**Comment by anthony-pinskey** [comment]
@sqal Understood! That worked perfectly. Thank you so much!

**Comment by xwjgo** [comment]
@sqal I have got following errors:
_[Vue warn]: Cannot find element: #app_
here is my code:

### main.js

```
import Vue from 'vue'
import VueResource from 'vue-resource'
import VueRouter from 'vue-router'

import App from './App'
import Register from './components/Register'
import Login from './components/Login'

Vue.use(VueResource)
Vue.use(VueRouter)

const router = new VueRouter()

router.map({
  '/register': {
    component: Register
  },
  '/login': {
    component: Login
  }
})

router.start(App, '#app')
```

### App.vue

```
<template>
  <div>
    <a v-link="{path: '/register'}">REGISTER</a>
    <a v-link="{path: '/login'}">LOGIN</a>
    <router-view></router-view>
  </div>
</template>

<script>
import Register from './components/Register'
import Login from './components/Login'

export default {
  components: {
    Register,
    Login
  }
}
</script>

```

**Comment by fnlctrl** [comment]
@xwjgo Please use our forum to ask questions.
