### ISSUE TITLE
params中包含encodeURIComponent后的字符的问题

### ISSUE THREAD

**Issue by airwin** [vuejs/vue-router#480]
### Vue.js & vue-router.js version
1.0.21, 0.7.13

类似这样的路由配置
`/account/invite/:account`
匹配到
`/account/invite/pony%40qq.com`
时，`this.$route.params.account == 'pony%40qq.com'`

需要业务中自己再进行decodeURIComponent
我看了一下源码，需要在 `findHandler` [中对match到的captures解码](https://github.com/vuejs/vue-router/blob/dev/lib/route-recognizer.js#L318-L320) ，不晓得有无副作用 
我的理解，这一步的解码是不是应该由路由内部完成呢？

**Comment by fnlctrl** [comment]
这可以按需自己实现呀，也不麻烦。如果在路由内部做了，却有人希望在路由里传带'%40'之类的字符串，不就被坑了吗。
