### ISSUE TITLE
abstract 下的 history.back()

### ISSUE THREAD

**Issue by yozman** [vuejs/vue-router#482]
在结合 hbuilder 制作 app，
遇到个问题就是可能没有对 `vue-router` 做优化，
在正常的 `hash` 模式下切换路由较慢，换到了 `abstract` 模式，
结果没找到 `history.back()` 的替代品，
不知 `vue-router` 能否在 `abstruct` 模式下
添加类似 `history.back()` 的返回上一渲染的功能？

**Comment by yyx990803** [comment]
恩，这个有计划会加

**Comment by yozman** [comment]
@yyx990803 
awesome :+1:

**Comment by aguegu** [comment]
同求哈～

**Comment by royJang** [comment]
同求,现阶段有方案可以实现back吗

**Comment by jaylinwang** [comment]
尤大,这个功能在近期会实现吗 😄   @yyx990803

**Comment by fnlctrl** [comment]
@jaylinwang abstract模式下可以使用`router.go(-1)`, 等价于back

**Comment by jaylinwang** [comment]
@fnlctrl router.go(-1)是会重新加载页面数据的呢

**Comment by fnlctrl** [comment]
浏览器里用abstract mode是不可能导致页面刷新的，你指的重新加载页面数据是什么？
