### ISSUE TITLE
从0.7.11升级到0.7.13后，vm.$route.fullPath 获取不到值

### ISSUE THREAD

**Issue by flftfqwxf** [vuejs/vue-router#483]
如题，
在0.7.11时
如下格式 url: 
**http://localhost:9083/mvvm/2?page=2**

    通过**vm.$route.fullPath** 可以获取到【/mvvm/2?page=2】
    **升级0.7.13后**  **vm.$route.fullPath**获取为 【undefined】

**Comment by fnlctrl** [comment]
这个属性被移除了，把$route对象console.log出来看一下，可以用别的属性替代

**Comment by flftfqwxf** [comment]
@fnlctrl 只看到还有一个path，不明白移除的目的是什么，我看源代码里依然有这个变量

**Comment by fnlctrl** [comment]
移除了反正也不是啥大问题，也许作者觉得这样更优雅呢。

**Comment by fnlctrl** [comment]
Closed due to inactivity.
