### ISSUE TITLE
[Request] Allow passing a component name to route config object

### ISSUE THREAD

**Issue by Eiskis** [vuejs/vue-router#484]
In [the docs](http://vuejs.github.io/vue-router/en/api/map.html#route-config-object) it is specified that when declaring routes, I have to point them either to an existing component *constructor* or a plain options object that will then be turned into a Vue object.

However, when integrating the routing to an app where I have already registered all my components with `Vue.component('foo', { .. })`, I have to make some changes to meet these requirements. As a user I don't really understand why I couldn't just point routes to components by name, especially since I have explicitly registered them with the same Vue object that the router points to. To me, that would be the natural thing to do.

If you were able to do this, it would also be much easier to load the routes from a JSON configuration file that can only deal with strings.

Below is a quick code sample of what I mean.

```
Vue.component('feed-page' {
...
});

Vue.component('profile-page' {
...
});

Vue.component('settings-page' {
...
});

router.map({
  '/feed': {
    component: 'feed-page'
  },
  '/me': {
    component: 'profile-page'
    subRoutes: {
      '/me/settings': 'settings-page'
    }
  }
})
```

If there's a reason this would not make sense or be a bad practice, I think the docs could make it clearer. As a new user I stumbled upon this quite quickly when trying to migrate an existing (simple) app to Vue.

**Comment by fnlctrl** [comment]
@Eiskis `Vue.component()` registers a `global` component, which should be as rarely used as possible. I recall reading this somewhere in the guide, but I couldn't remember the exact location.

In your example, you can just ditch the `Vue.component` lines, and use the simplified version below.

```
router.map({
  '/feed': {
    component: { 
        // the 'feed-page' component object
    }
  },
  '/me': {
    component: {
      // the 'profile-page' component object
    }
    subRoutes: {
      '/me/settings':  {
        // the 'settings-page' component object
      }
    }
  }
})
```

As for generating router map with json files, it's very easy to use `nodejs` to require it and replace the component name strings with an actual `require('component-name')`, then export the whole thing.
