### ISSUE TITLE
跳转到外部链接后再跳转回来页面显示异常

### ISSUE THREAD

**Issue by dp199313** [vuejs/vue-router#485]
第三方鉴权需要跳转到外部链接,我在beforeEach里判断用户有没有登录,没有登录就用 window.location.href 跳转到第三方授权页面,第三方页面跳转回来时再切换到别的路径就会出现旧的页面和新的页面同时存在的情况

**Comment by fnlctrl** [comment]
看控制台给的报错，这种情况通常是你的view抛了异常，或者transition的css没写好，导致vue-router取消/未完成跳转，所以两个页面会同时存在。
不是bug的问题，请发到[论坛](http://forum.vuejs.org/category/10/%E4%B8%AD%E6%96%87)
