### ISSUE TITLE
keep-alive breaks v-ref on <router-view>

### ISSUE THREAD

**Issue by te1** [vuejs/vue-router#486]
### Vue.js & vue-router.js version
1.0.18, 0.7.13

### Reproduction Link
http://www.webpackbin.com/VJUv0eAl-

### Steps to reproduce
Click on the "page 2" link and then click on the "page 1" link.

### What is Expected?
It should say "current page is page 1". The text is bound to `{{ $refs.page.name }}` with `<router-view v-ref:page keep-alive="true"></router-view>` and `name` is part of the `data` for the `page1` and `page2` components.

### What is actually happening?
The text disappears after switching back to page 1 because the `v-ref` on `<router-view>` is no longer respected. If you remove `keep-alive` it works as expected.

**Comment by fnlctrl** [comment]
$refs is designed only for programmatic access,  and usage inside templates should be avoided.
As of now, for vue 2.0 and above `$refs` is completely not reactive (to avoid cases like this), so this is a won't-fix for 0.7.

**Comment by 9mm** [comment]
Is this the same for Vue 3? I'm trying to cache a page and call `$refs.userForm.submitUserEdit()` inside a `@click` however once I navigate away and come back, it says `$refs.userForm` is undefined.
