### ISSUE TITLE
Action of route with nested routes

### ISSUE THREAD

**Issue by pespantelis** [vuejs/vue-router#491]
### Vue.js & vue-router.js version
1.0.22, 0.7.13

### Example (from docs)
```js
router.map({
  '/foo': {
    component: Foo,
    subRoutes: {
      '/bar': {
        component: Bar
      },
      '/baz': {
        component: Baz
      }
    }
  }
})
```

### What is actually happening and what is Expected?
When I hit the `http://example.com/foo` I get a blank page. Wouldn't it be better to act as if there was not a route?

**Comment by yyx990803** [comment]
Well in this case `Foo` is rendered with an empty `<router-view>`, what do you expect otherwise?

Note you can specify a default child view with `subRoutes: { '/': Bar }`.

**Comment by pespantelis** [comment]
I'm trying to figure something out, in order to avoid this:
```js
router.map({
  '/foo': {
    component: Foo,
    subRoutes: {
      '/bar': {
        component: Bar
      },
      '/': {
        component: {
          ready () {
            this.$router.go('/not-found')
          }
        }
      }
    }
  }
})
```

If it checks the url? For example:

- if the url is `/foo/bar`: renders the `Foo` component and then the `Bar`
- if the url is `/foo` and the `/` subRoute didn't specified: redirects

**Comment by fnlctrl** [comment]
For `not-found` redirection, use router.beforeEach.
```javascript
router.beforeEach(({redirect, to, next}) => {
        if (!to.matched) {
            redirect(....)
        } else {
            next();
        }
    })
```

**Comment by pespantelis** [comment]
@fnlctrl in my case, the `to.matched` does not be empty.

This could be achieved with `router.beforeEach` like below, but I've made a proposal for an out of the box solution.
```js
router.map({
  '/foo': {
    component: Foo,
    subRoutes: {
      '/bar': {
        component: Bar
      },
      '/': {
        component: {},
        notFound: true
      }
    }
  }
})

router.beforeEach(({ from, next, redirect }) => {
  if (from.notFound) {
      redirect('/not-found')
  } else {
      next()
  }
})
```

**Comment by fnlctrl** [comment]
@pespantelis As far as I know, during transition there is no way to tell whether a route has subRoutes or not.
So I think your code above is already the most succinct and explicit way to achieve what you want.
If you have multiple routes that need this behavior, then it can be written like:
```javascript
var redirectComponent = {
  route: {
      activate: ({redirect}) => redirect('not-found') // This is better I think
  }
}
router.map({
  '/foo': {
    component: Foo,
    subRoutes: {
      '/bar': {
        component: Bar
      },
      '/': {
        component: redirectComponent
      }
    }
  }
})
```

Other ways I can think of is like this
```javascript
router.map({
  '/foo/:name‘ {
    component: {
      template: `
         <component :is="$route.params.name"><component>
      `,
      route: {
        activate({to: {params: {name}}, next, redirect}) {
            if (!name) redirect ('/not-fount')
            else next()
        }
      }
    }
  }
})
```

**Comment by pespantelis** [comment]
Finally, I'm using this approach:
```js
var DoNotRender = {
  component: {},
  notFound: true,
}

router.map({
  '/foo': {
    component: Foo,
    subRoutes: {
      '/': DoNotRender,
      '/bar': {
        component: Bar
      }
    }
  }
})

router.beforeEach(({ to, next, redirect }) => {
  if (to.notFound) {
    redirect('/not-found')
  } else {
    next()
  }
})
```

**Comment by LinusBorg** [comment]
Since this does not seem to be a bug, and a solution to your problem was found, this issue will be closed.
