### ISSUE TITLE
hashbang能支持html5的popstate和pushstate么

### ISSUE THREAD

**Issue by sandysong** [vuejs/vue-router#492]
我们在微信底下开发，因为微信的一些坑，只能用hashbang形式的URL，但是开启了hashbang就无法用到html5模式的history、saveScrollPosition功能，我不知道这两部分是不是冲突，如果不冲突的话希望能同时支持。
我试过配置了html5模式后把root配置成
`/?#!`
但是无法正常跳转（拼出的rootRE有问题）

**Comment by amowu** [comment]
@sandysong 我也有這個問題，因為我的 SPA 是放在 S3 hosting。

我目前的解法是在 index.html 加段 js 去 rewrite。

```html
<script>
    history.pushState({}, "index.html", location.hash.substring(2));
</script>
```

**Comment by fnlctrl** [comment]
是冲突的，所以不能。
