### ISSUE TITLE
`route.data`的`transition.next`渲染页面以后有什么钩子函数可以做后续操作?

### ISSUE THREAD

**Issue by xjchenhao** [vuejs/vue-router#494]
你好, 请问`route.data`的回调函数以后有没有没有其他接口?

我想在` transition.next(data.resultData)`渲染了页面以后做其它操作.

**Comment by yyx990803** [comment]
你好，issue 是用来报 bug 的，不是用来提问的。报 bug 时，请确保有完整的重现步骤。不符合要求的 issue 会被直接关闭。
