### ISSUE TITLE
Videos with the autoplay attribute are played twice.

### ISSUE THREAD

**Issue by manudurgoni** [vuejs/vue-router#495]
Hello,

this is a really strange bug. 

When I have a video with the autoplay attribute in a template :

```
var Foo = Vue.extend({
    template: '<video autoplay controls src="http://vjs.zencdn.net/v/oceans.mp4"></video>'
})
```
There is one video tag in the dom, but it looks like two videos play simultaneously. 

Let me explain, if you try to pause the video, it works for the video in the dom. But there's another (invisible) video that is still playing.

If I do that :

```
var Foo = Vue.extend({
    template: "<video autoplay controls :src=\"'http://vjs.zencdn.net/v/oceans.mp4'\"></video>"
})
```

No problems.

Any ideas of what happens ?

### Reproduction Link

https://jsfiddle.net/cLc0s9aj/8/

### Vue.js & vue-router.js version
1.0.22, 0.7.13

PS: sorry for my poor English!

**Comment by yyx990803** [comment]
This is indeed a bug, please file it to the main repo (vuejs/vue)
