### ISSUE TITLE
vue-router异步加载js文件

### ISSUE THREAD

**Issue by wangchenhao** [vuejs/vue-router#496]
使用webpack构建vue-router异步加载js文件的时候出现问题，改回vue格式的时候路由可以正常显示，在加载js格式的时候无法显示。将加载后的对象对比后发现不一样。

**Comment by liujb** [comment]
@wangchenhao 问题描述得不知道该如何去判断哪里出错，可以贴代码，再描述清楚些。

**Comment by wangchenhao** [comment]
也不是哪里错误了，我重新描述下。
在异步加载router的时候，我开始加载的是vue格式的文件，异步加载时没有问题。
后面我感觉vue格式把HTML css js写一起有点繁重，所以分开写了，router就加载的是js格式的文件。
就是这个时候出现了问题，router加载Vue格式文件的时候是正常的，但是加载了js格式文件就无法显示，但是路由匹配是成功的，文件也异步加载过来了。这个问题只在异步加载的时候出现。

**Comment by yyx990803** [comment]
你好，issue 是用来报 bug 的，不是用来提问的。报 bug 时，请确保有完整的重现步骤。不符合要求的 issue 会被直接关闭。
