### ISSUE TITLE
vue-router如何设置默认访问路径

### ISSUE THREAD

**Issue by xiaoyunchen** [vuejs/vue-router#497]
假设有三个组件：
/a  --> 组件A
/b --> 组件B
/c --> 组件C
我希望页面打开时默认打开组件A，应该如何设置呢。
现在我是把 / 根目录配置给了A，
`router.map({
	'/':{
		component: A
	}
});`

HTML：
`<a v-link="{ path: '/', exact: true }" >Home</a>`

请问有没有更好的配置方式呢？

**Comment by stackOverMind** [comment]
同问

**Comment by multics** [comment]
router.alias({'*':'/a'})

**Comment by zhuqiuyang** [comment]
did it have default router?

**Comment by yyx990803** [comment]
你好，issue 是用来报 bug 的，不是用来提问的。报 bug 时，请确保有完整的重现步骤。不符合要求的 issue 会被直接关闭。
