### ISSUE TITLE
Parameter prefix/suffix

### ISSUE THREAD

**Issue by pespantelis** [vuejs/vue-router#499]
Is it possible to extend the functionality of the parameters, to support **prefix** and/or **suffix**?

For example:

``` js
router.map({
  '/prefix{param}suffix': {
    component: Foo
  }
})
```

**Comment by chrisvfritz** [comment]
What's the use case for this? Why not just:

``` js
router.map({
  '/prefix/:param/suffix': {
    component: Foo
  }
})
```

**Comment by NicolasParada** [comment]
For example, in medium.com they have the user profiles like `medium.com/@johndoe`.
Now, you can't do the same...
```js
router.map({
  '/@{username}': {
    component: Profile
  }
}
```
The reason to prefix with an `@` is to not match all the routes, because you will never end with 404 routes...

**Comment by pespantelis** [comment]
I want something like that as described by @NicolasParada.

Currently, I'm using that:
```js
router.map({

  ...

  '/:username': {
    component (resolve) {
      require(['pages/Profile'], resolve)
    },
    before ({ to, next, redirect }) {
      if (to.params.username.startsWith('~')) {
        next()
      } else {
        redirect('/not-found')
      }
    }
  }
})

router.beforeEach((transition) => {
  if (transition.to.before) {
    transition.to.before(transition)
  } else {
    transition.next()
  }
})
```
> Note that the `/:username` constitutes the last route, to match all paths with 1 segment.

However, I believe that other users need this functionality, which is why I raised this issue. :)

**Comment by chrisvfritz** [comment]
Ahh, I see how that makes sense - and does sound useful! If either of you feel like tackling it, I don't believe introducing this feature should be too hard. We'd just need an additional [matcher for dynamic segments](https://github.com/vuejs/vue-router/blob/c5dfe9958245f0c5988b52548a832234cae0996f/lib/route-recognizer.js#L138-L141).

**Comment by JivanRoquet** [comment]
What about something like this?

```javascript
if (match = segment.match(/^\{(?:[^\/:]?[^\/:a-zA-Z]{1})\}:([^\/:]+)$/)) {
  results.push(new DynamicSegment(match[1]))
  names.push(match[1])
  specificity.val += '3'
}
```

[See gist](https://gist.github.com/JivanRoquet/c4f7f0d5b8e1b6cc25d241657d634ee7) - [See regex](https://www.debuggex.com/r/ruD4X2pNz7nFenpD)

This would enable route constructs such as:

```javascript
router.map({
  '/{@}:username': {
    // example.com/@johnDoe
    component: Profile
  },
  '/{_}:username': {
    // example.com/_johnDoe
    component: Profile
  },
  '/{myPrefix_}:username': {
    // example.com/myPrefix_johnDoe
    component: Profile
  },
  '/{56}:username': {
    // example.com/56johnDoe
    component: Profile
  }
}
```

The proposed regex only allows prefixes with no `/` and `:`, and not ending by any letter. Without those limitations, it seems to me that matching an url to a route path would be difficult/expensive (think of a `abc` prefix and trying to match `example.com/abcjohnDoe` with the correct path, and try not to have nightmares tonight).

**Comment by JivanRoquet** [comment]
@chrisvfritz in addition to parsing route paths, where should go the code to match a given `url` to a path?

The code I suggested above just makes `{prefix_}:param` a valid route path, but I don't think it automagically makes `example.com/prefix_johnDoe` point to this path, does it?

**Comment by LinusBorg** [comment]
@JivanRoquet Thank you for your proposal, that would certainly do the job I think. the syntax with the curly braces feels a bit hackish to me though, we can think of something more readable?

About your question concering the code the code for matching an url to a path: I think you were already in the right place.

The Route class (`/src/route.js`) uses the recognizer to [match the current URL to a route](https://github.com/vuejs/vue-router/blob/dev/src/route.js#L13) and deconstruct params etc from the matched result. Those are used in the transition to the component etc.

**Comment by JivanRoquet** [comment]
@LinusBorg thanks for the follow-up. Would something like this be more readable?

```javascript
router.map({
  '/@:username': {
    // example.com/@johnDoe
    component: Profile
  },
  '/_:username': {
    // example.com/_johnDoe
    component: Profile
  },
  '/myPrefix_:username': {
    // example.com/myPrefix_johnDoe
    component: Profile
  },
  '/56:username': {
    // example.com/56johnDoe
    component: Profile
  }
}
```

The associated regex being `^(?:[^\/:]?[^\/:a-zA-Z]{1}):([^\/:]+)$`

Right now I don't think of any side-effect that would potentially trump the matching algorithm but there might be, and this would have to be thoroughly tested.

**Comment by leocflam** [comment]
Yes, this feature is important!

I hope to have something like /@{username} in Laravel.

**Comment by yyx990803** [comment]
FYI this can be done in 2.0 as `/(@):username`

**Comment by philBrown** [comment]
> FYI this can be done in 2.0 as `/(@):username`

Does this also apply to suffixes? Ie, can we use `/:username(@)`?

**Comment by posva** [comment]
This thread is quite outdated now. Here are the up to date ways to do it

- prefix: `/@:username`
- suffix with slash `/:something/suffix` (`/hello/suffix` -> `{ something: 'hello' }`)
- suffix with two params `/:something:suffix(suffix)` the param suffix only matches against `suffix`
- suffix with custom regex: `/:something([^/]+@suffix)` (`/hello@suffix` -> `{ something: 'hello@suffix' }`). Then clear it out with the `props` option on route records https://router.vuejs.org/guide/essentials/passing-props.html
