### ISSUE TITLE
a路由跳转到b路由后如何销毁a路由中的数据

### ISSUE THREAD

**Issue by libertyAlone** [vuejs/vue-router#501]
现在遇到一个问题，在a路由中有一个控制弹窗的变量，弹窗出现后路由跳转到b，然而b再跳转到a后，弹窗仍然显示，请问vue-router中是否有相应的配置或方法能够使在路由跳转后原组件的数据被销毁？

**Comment by yyx990803** [comment]
不用 keep-alive，或者在 deactivate 钩子里面重置。

**Comment by lihuangshuaige** [comment]
如果没有用到keep-alive呢？我也是遇见上一个路由的弹窗出现在当前路由的情况，但是我并没有用keep-alive
