### ISSUE TITLE
小菜鸟刚入门，使用vue-router插件路由不生效，求指教

### ISSUE THREAD

**Issue by Leungkingman** [vuejs/vue-router#502]
```
< ! --首先这个是主页面 -- ! >
`<body>
	<!-- 主体内容开始 -->
	<div>
		<!-- 表格顶部搜索区域开始 -->
		<div class="search-area">
			<div id="btnArry"></div>
		</div>
		<!-- 表格顶部搜索区域结束 -->

		<!-- 表格 -->
		<div id="list"></div>
		<!-- 表格结束 -->
	</div>
	<!-- 主体内容结束 -->
<script type="text/javascript" src="../../../js/main.js" data-module="node" data-path="node" id="entrance"></script>
</body>`
```

注入这个页面的js模块（以下就是这个js模块的代码）

define(function(require, exports, module){
	
	// 列表组件
	var list = new Vue({
		el: '#list',
		template: _g.getTemplate('node/list'),
		data: {
			nodes:[],
			checkedIds:[]
		},
		methods: {
			folderNode:function(id){
				for(var i=0;i<this.nodes.length;i++){
					if(this.nodes[i].fid == id || this.nodes[i].gfid == id){
						if(this.nodes[i].show){
							this.nodes[i].show = false;
						}else{
							this.nodes[i].show = true;
						}
					}
				}
			},
		},
		ready:function(){
			var self = this;
			var array = [];
			_g.goAjax('get','','AuthConfig/node_list',function(ret){
				var data = ret.retData;
				//console.log('ret ='+_g.j2s(data));
				var temp = {};
				$.each(data,function(k,v){
					temp.id = v.id;
					temp.construct = v.title;
					temp.name = v.name;
					temp.title = v.title;
					temp.level = v.level;
					temp.show = true;
					array.push(temp);
					temp = {};
					$.each(v.child,function(k,sv){
						temp.id = sv.id;
						temp.fid = v.id;
						temp.construct = '    ├ '+sv.title;
						temp.name = sv.name;
						temp.title = sv.title;
						temp.level = sv.level;
						temp.show = true;
						array.push(temp);
						temp = {};
						$.each(sv.child,function(k,tv){
							temp.id = tv.id;
							temp.gfid = v.id;
							temp.fid = sv.id;
							temp.construct = '    │    ├ '+tv.title;
							temp.name = tv.name;
							temp.title = tv.title;
							temp.level = tv.level;
							temp.show = true;
							array.push(temp);
							temp = {};
						})
					})
				});
				self.nodes = array;
				console.log('nodes ='+_g.j2s(self.nodes));
			});
		},
		events: {
			'outputData': function(arr){
				this.nodes = arr;
				console.log(_g.j2s(this.nodes));
			}
		}
	});

	
	/* 以下开始都是复制demo */
	var Foo = Vue.extend({
		template: '<p>This is foo!</p>'
	})

	var Bar = Vue.extend({
		template: '<p>This is bar!</p>'
	})

	var App = Vue.extend({})

	var router = new VueRouter()

	router.map({
		'/foo': {
			component: Foo
		},
		'/bar': {
			component: Bar
		}
	})

	router.start(App, '#app')
	
	module.exports = {};
	
});

`然后就是#list的模板`
```
<div class="table-container" id="app">
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>复选</th>
				<th>节点ID</th>
				<th>节点结构</th>
				<th>名称</th>
				<th>显示名</th>
				<th>类型</th>
				<th>操作</th>
			</tr>
		</thead>
		<tbody>
			<tr v-for="node in nodes" v-show="node.show">
				<td><input type="checkbox" value="{{node.id}}" v-model="checkedIds"/></td>
				<td>{{node.id}}</td>
				<td class="title" v-on:click="folderNode(node.id)">{{node.construct}}</td>
				<td>{{node.name}}</td>
				<td>{{node.title}}</td>
				<td>{{node.level}}</td>
				<td><a v-link="{ path: '/foo' }">编辑</a></td>
			</tr>
		</tbody>
	</table>
</div>
```

但是在运行的时候浏览器报了这样的错误：
[vue-router] v-link can only be used inside a router-enabled app.warn$1 @ vue-router.js:745
vue-router.js:1997 Uncaught TypeError: Cannot read property 'stringifyPath' of undefined

到底是哪里出错了呢？谢谢大家

**Comment by multics** [comment]
Vue.use(VueRouter)没写

**Comment by yyx990803** [comment]
你好，issue 是用来报 bug 的，不是用来提问的。报 bug 时，请确保有完整的重现步骤。不符合要求的 issue 会被直接关闭。
