### ISSUE TITLE
具名路径多个参数问题

### ISSUE THREAD

**Issue by dengjianan** [vuejs/vue-router#503]
`router.map({
    '/life': {
      name: 'life',
      component: require('../components/articleList.vue')
    },
    '/life/:year': {
      name: 'life',
      component: require('../components/detailList.vue')
    },
    '/life/:year/:month': {
      name: 'life',
      component: require('../components/detailList.vue')
    },
    '/life/:year/:month/:id': {
      name: 'life',
      component: require('../components/articleItem.vue')
    }
})
`
当跳转到/life/2016/5时候提示
`[VueResource warn]: The `:id` parameter syntax has been deprecated. Use the `{id}` syntax instead.`
这个错误。
是我哪里写错了吗

**Comment by yyx990803** [comment]
你好，issue 是用来报 bug 的，不是用来提问的。报 bug 时，请确保有完整的重现步骤。不符合要求的 issue 会被直接关闭。
