### ISSUE TITLE
Aborting transition runs `deactivate` hook twice

### ISSUE THREAD

**Issue by simplesmiler** [vuejs/vue-router#508]
### Vue.js & vue-router.js version

1.0.24, 0.7.13
### Reproduction Link

https://jsfiddle.net/simplesmiler/xto1h4k4/9/
### Steps to reproduce
1. Open developer console
2. Click "Go Home"
### What is Expected?

> activating root
> deactivating root
> aborting transition in home
> activating root
### What is actually happening?

> activating root
> deactivating root
> aborting transition in home
> deactivating root
> activating root

**Comment by fnlctrl** [comment]
Don't know if it is a bug or a dirty fix (by calling `deactivate` before calling `activate` to ensure something...)
Using `canActivate` instead of `activate` gives expected result though.
https://jsfiddle.net/fnlCtrl/23c4xdqf/
