### ISSUE TITLE
[Feature Request] v-link activeParent property

### ISSUE THREAD

**Issue by KingMario** [vuejs/vue-router#511]
In some cases, when the activeClass is set for *v-link*, upon path match, one might want to apply the class to the parent or an ancestor element of the *v-link*-ed element.

For example, in Bootstrap navbar, when the *v-link* is applied to an &lt;a&gt; element, the active class is wanted to be applied to the &lt;li&gt; element.

```html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a v-link="{path: '/', exact: true}"><img class="logo" src="./assets/logo.png"></a>

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-items" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="navbar-items">
      <ul class="nav navbar-nav">
        <li v-link="{path: '/jobs', activeClass: 'active'}" @click="getJobs"><a href="javascript:void(0)">Jobs</a></li>
        <!--the link will appear somewhere else in the app, so a reusable component is better-->
        <li><jobs-link>Jobs</jobs-link></li>
      </ul>
    </div>
  </div>
</nav>
```

The template part of JobsLink.vue

```vue
<a href="javascript:void(0)" v-link="{path: '/jobs', activeClass: 'active'}" @click="getJobs">
  <slot></slot>
</a>
```

The first &lt;li&gt; element has a *v-link* property directly set in itself and the activeClass will be applied to it.
The second &lt;li&gt; element has a reusable component with a *v-link* property set. Obviously, the activeClass will be applied to the &lt;a&gt; element if there is no activeParent property for *v-link*.

If an *activeParent* property for v-link is avaliable and set to a boolean value or an integer, upon path match, the activeClass will be applied instead to the parent element or *n*-th parent element with high flexibility.

```html
<li><jobs-link :active-parent="true">热招岗位</jobs-link></li>
```

Modified template for JobsLink.vue
```vue
<a href="javascript:void(0)" v-link="{path: '/jobs', activeClass: 'active', activeParent: activeParent}" @click="getJobs">
  <slot></slot>
</a>
```

Hope I'm clearly expressed.

**Comment by chrisvfritz** [comment]
I think [the `v-link-active` directive](http://router.vuejs.org/en/link.html#active-link-class#applying-active-classes-to-another-element) is what you're looking for.
