### ISSUE TITLE
v-link on button

### ISSUE THREAD

**Issue by Humeira** [vuejs/vue-router#513]
I don't know if it's the right way of using `v-link`. I am trying to wrap my head around it. 

But earlier I used something like this `<button class="btn btn-primary" v-link{path : '/'}>Previous</button>` and it works. 

Can I use v-link on buttons or only in an anchor tag?

**Comment by chrisvfritz** [comment]
Since this is neither a bug nor a feature request, I recommend posting your question on either [the forum](http://forum.vuejs.org/) or [the Gitter chat](https://gitter.im/vuejs/vue).
