### ISSUE TITLE
Query params change detection

### ISSUE THREAD

**Issue by organic-scholar** [vuejs/vue-router#514]
when i update hash from items/search?q=19 to items/search?q=20 the router didn't detect the change

**Comment by simplesmiler** [comment]
When you transfer from `items/search?q=19` to `items/search?q=20` the component is reused, so only [`route:data`](http://router.vuejs.org/en/pipeline/data.html) hook gets triggered. This hook is where you should fetch the data that depends on URL.

**Comment by organic-scholar** [comment]
Ah great this seems reasonable. appreciated for quick help

**Comment by texelate** [comment]
Or add this to your component:

``` javascript
route: {

    canReuse: false

}
```
