### ISSUE TITLE
动态载入的时候，如果组件中引用组件的样式会丢失

### ISSUE THREAD

**Issue by fengxiaotx** [vuejs/vue-router#520]
在使用异步路由的时候。如果，路由页面中，引用了组件，组件的样式写在改组件的<style>里面。组件中的样式全部丢失。
请问下，这个问题有没有解决办法呢？

**Comment by yyx990803** [comment]
这是涉及你的 webpack 配置的问题，和 vue-router 无关。

**Comment by evolutionjay** [comment]
遇到同样的问题, 求解
