### ISSUE TITLE
zh-cn 文档不恰当地使用了 lang=zh-tw

### ISSUE THREAD

**Issue by qgy18** [vuejs/vue-router#522]
这会导致在部分系统 / 浏览器下，页面 fallback 到日文字体，从而使得部分字形很奇怪。

例如下图中的「径」字：

<img width="710" alt="pasted_image_8_6_2016__4_51_pm" src="https://cloud.githubusercontent.com/assets/285369/15888885/55c42218-2d9b-11e6-9c95-1d5a4d1c7677.png">

文档地址：http://router.vuejs.org/zh-cn/named.html

**Comment by yyx990803** [comment]
这个是 gitbook 的问题，去那边开 bug 吧
