### ISSUE TITLE
设置了history为false还能使用锚点么？

### ISSUE THREAD

**Issue by YeomanYang** [vuejs/vue-router#525]
vue-route将history配置成false之后，url会带上#！，这时候如果在localhost:3000/#!/user使用锚点,#后面的路径就会被覆盖掉。但是为了某些要求，我必须设置history为false。有没有方法解决这个问题呢？
还是说设置了history为false的话就不能用锚点了？

**Comment by yuluhuang** [comment]
我也想知道

**Comment by jingsam** [comment]
不行。参见 https://github.com/vuejs/vue-router/issues/420

**Comment by yyx990803** [comment]
使用 hash 模式意味着 hash 被用来代表你的应用路由状态，里面不能再包含锚点。
