### ISSUE TITLE
Should route components be automatically patched with `replace: false` unless explicitly set?

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue-router#527]
Compiling routed apps to static sites, for example with `prerender-spa-plugin`, will only work when `replace: false` is set for page-level components. As static site generation is becoming more popular, should this just be the default or are there edge cases where it would be undesirable?

**Comment by fnlctrl** [comment]
`replace: false` is deprecated in 2.0, and I guess 2.0's server-side-rendering can make prerendering much easier.

**Comment by fnlctrl** [comment]
@chrisvfritz May I close this issue :smile: ?
