### ISSUE TITLE
vuejs v2 support

### ISSUE THREAD

**Issue by Bekt** [vuejs/vue-router#528]
vuejs v2.0.0-alpha.1 has been released, but vue-router (v0.7.13) is not compatible with it.

```js
  let router = new VueRouter({
      hashbang: false,
      history: true,
      root: '/app/'
  });
  router.map({
      '/': {
          name: 'foo',
          component: Foo
      }
  });

  router.start(App, '#app');
```

```
vue-router.js:1800

Uncaught TypeError: Cannot read property 'component' of undefined

View @ vue-router.js:1800
Router.install @ vue-router.js:2695
Te.e.use @ vue.min.js:6(anonymous function)
```

```
  function View (Vue) {

    var _ = Vue.util;
    var componentDef =
    // 0.12
    Vue.directive('_component') ||
    // 1.0
    Vue.internalDirectives.component; //1800
```

**Comment by yyx990803** [comment]
Current version of `vue-router` is not compatible with 2.0. Please wait for official announcement on updates.

**Comment by Bekt** [comment]
Good to know. Maybe modify the `Compatibility Note` section in readme until then?

**Comment by prpr2012** [comment]
hello! I use vue 2.5.1. but I found a quesion. 'Vue.internalDirectives.component;' how can i slove this quesion?

**Comment by sharynsl** [comment]
what does this mean“Cannot read property ‘component’ of undefined”?  How can I solve it ?  I have done "npm install vue-router@next",but it doesn't work.

**Comment by posva** [comment]
@sharynsl There's no need of `next` tag now. More help at https://router.vuejs.org/
