### ISSUE TITLE
some problem for subRoutes

### ISSUE THREAD

**Issue by yozman** [vuejs/vue-router#534]
there is a bug for subRoutes,

it's not working when subRoutes is function like this
```javascript
'/': {
  component: { template: '<h1>test</h1><router-view></router-view>' },
  subRoutes: function () {
    return {
      '/a': { component: { template: '<h2>pageA</h2>' } },
      '/b': { component: { template: '<h2>pageB</h2>' } }
    }
  }
}
```

I think it's the reason why subRoutes lazy load is not work,
could you please fix it?

**Comment by ifaouibadi** [comment]
that should fix it
`'/': {
  component: { template: '<h1>test</h1><router-view></router-view>' },
  subRoutes: {
      '/a': { component: { template: '<h2>pageA</h2>' } },
      '/b': { component: { template: '<h2>pageB</h2>' } }
    }
  
}`

**Comment by yyx990803** [comment]
This is not a bug. It is never designed to work like that.
