### ISSUE TITLE
Aborting activate on subRoutes when using history

### ISSUE THREAD

**Issue by steveneaston** [vuejs/vue-router#535]
I'm having trouble using the `activate` hook to redirect on a subRoute when `history: true` is set.

The example below has three routes: `/foo`, `/foo/bar` and `/foo/baz`. I want to redirect users away from `/foo/baz`, for example they may not be authorised or it may be a segment route and the requested entity doesn't exist.

When visiting `/foo/baz` via `v-link`, the user is redirected and the default sub view (`/foo`) renders correctly. When attempting to visit the page fresh, i.e. using `href` or coming in directly, the page redirects but the sub view **does not** render and an error `TypeError: Cannot read property 'filter' of null` is thrown.

The issue can be replicated like so:

``` js
var Foo = Vue.extend({
  template:
    '<div class="foo">' +
      '<h2>This is Foo!</h2>' +
      '<router-view></router-view>' +
    '</div>'
})

var Bar = Vue.extend({
    template: '<p>This is bar!</p>'
})

var Baz = Vue.extend({
    template: '<p>This is baz!</p>',
    route: {
        activate: function(transition) {
            // We wish to abort this route and redirect to /foo
            transition.redirect({path: '/foo'});
      }
    }
})


// configure router
var router = new VueRouter({
    history: true
});

router.map({
    '/foo': {
        component: Foo,
        subRoutes: {
            '/': {
                component: {
                    template: '<p>Default sub view for Foo</p>'
                }
            },
            '/bar': {
                component: Bar
            },
            '/baz': {
                component: Baz
            }
        }
    }
});

router.redirect({
    '*': '/foo'
});

// start app
var App = Vue.extend({})
router.start(App, '#app')
```

I've created a simple page here to demonstrate the issue: http://tmp.seaston.com/dev/vue/foo

**Comment by simplesmiler** [comment]
You should not be calling both `transition.redirect` and `transition.abort`.

**Comment by steveneaston** [comment]
@simplesmiler thanks. Even so, the problem still occurs. I've edited the original code to reflect.

**Comment by simplesmiler** [comment]
Sound like a bug to me, thanks for reporting.
