### ISSUE TITLE
stop from auto-appending trailing slash at root of app

### ISSUE THREAD

**Issue by jaredreich** [vuejs/vue-router#537]
For example, if the root is "/app", and you visit "website.com/app", vue-router will auto append a trailing slash, making it "website.com/app/", but any other routes will not have a trailing slash auto-appended (ex. "website.com/app/users"

### Vue.js & vue-router.js version
1.0.16, 0.7.11

### Reproduction Link

Any vuejs app

### Steps to reproduce
visit the root of your app with vue-router enabled

### What is Expected?
no trailing slash

### What is actually happening?
trailing slash auto-appending

**Comment by yyx990803** [comment]
Because it's the root, hence the `/`. This is necessary for the matching to work properly.

**Comment by jaredreich** [comment]
Thanks for the quick response, though I'm not sure if it is necessary... Because it works perfectly if no root is defined. (e.g. "website.com" <---> "website.com/users", it does not auto-append the trailing slash on the first route). If your root is "/app" it should be able to match "/app", not "/app/".

Ultimately this is very non-critical and I know you have more important Vue things to work on, so I will probably do a PR.

Thanks Evan, great work.

**Comment by LinusBorg** [comment]
You are free to submit a pull request if you think it can work without it.
