### ISSUE TITLE
maybe a bug with subroutes in hot-reload

### ISSUE THREAD

**Issue by zheeeng** [vuejs/vue-router#544]
With nested routers, modify the component which contains the subroute's outlet — `<router-view>`, the hot-reloaded page will reproduce the content of `<router-view>`. If I refresh this page, the behaviour is correct.

I found some others encountered the same problem. Check the second issue have a look at the screen talk.
https://github.com/vuejs/vue/issues/2550
https://github.com/vuejs/vue-loader/issues/217

**Comment by juukie** [comment]
Same problem here :/

**Comment by LinusBorg** [comment]
Closing this in favour of #662
