### ISSUE TITLE
ie9下用history：true  去掉锚点时，并不生效

### ISSUE THREAD

**Issue by shinlyli** [vuejs/vue-router#547]
### Vue.js & vue-router.js version

1.0.16, 0.7.11

**Comment by yyx990803** [comment]
IE9 本来就不支持 history API.......

**Comment by wjhcc2018** [comment]
@yyx990803  尤大，IE9不支持history不是自动变为hash模式吗？我用的history在IE9下，变为hash模式的时候，就是错误的，但是直接用hash就没问题，是什么原因呢？
例如：history模式下：https://e.qianfan578.com/wxm/toLogin这个网址，在IE9下就自动变为https://e.qianfan578.com/#/wxm/toLogin（结果就访问失败了）
但是hash模式下：就会变成https://e.qianfan578.com/wxm/toLogin/#/wxm/toLogin（能访问成功）
