### ISSUE TITLE
如何监听异步加载组件失败的情况？

### ISSUE THREAD

**Issue by terranc** [vuejs/vue-router#549]
比如：

```
'/articles': {
      name: 'articles',
      component: (resolve) => {
        require(['./pages/Articles'], resolve);
      },
    }
```

如果`/pages/Articles`加载失败或者超时，能捕获到这个事件吗？

**Comment by yyx990803** [comment]
异步加载是 webpack 的功能，和 vue-router 无关。

**Comment by panezhang** [comment]
实际上我觉得应该提供一个钩子，在切换路由失败的时候触发。现在只有beforeEach和afterEach，但在路由中途报错的时候，无法处理，就像上面 @ terranc 提到的那种情况，加载异步组件失败。

```
router.onError((err) => {
    // handle err
});
```

**Comment by devinRex** [comment]
webpack2 有reject回调

                 require(['./views/common/success'], resolve, networkError)

webpack1,可以用这个插件: require-error-handler-webpack-plugin.

**Comment by devinRex** [comment]
不过超时依然没找到解决办法，初步考虑只能去看看能不能改到webpack的超时时间
