### ISSUE TITLE
Keep the url while aborting a transition

### ISSUE THREAD

**Issue by Makio64** [vuejs/vue-router#553]
Is it possible the abort a transition but keeping the url ?

Basically I just want change the url for the deeplinking : gallery/01 => gallery/02 , keep the deeplinking but not really "change" the page, when I use go and then transition.abort() it give back to the previous url, is it another way to do it ?

thanks!

**Comment by yyx990803** [comment]
I'm not sure why you want to do that... just use `transition.next()`?

`transition.abort()` needs to have consistent behavior.

**Comment by LinusBorg** [comment]
I think `router.replace()` should do what you want (not having a new entry in browser history, and therefore, a back button)

http://router.vuejs.org/en/api/replace.html
