### ISSUE TITLE
关于路由转换规则的问题！

### ISSUE THREAD

**Issue by HenryHyt** [vuejs/vue-router#555]
我的意图是这样的，当访问
http://127.0.0.1/page/pay_confirm.html?order_no=123
我期望是最终转换的路由是变成
http://127.0.0.1/page/pay_confirm.html?order_no=123#!/order_no/123

//以下一些关键代码片段

```
router.map({
    '/order_no/:order_no' : {
        component : PayConfirmPage
    }
});
router.beforeEach(function(ts){
    console.log(ts.to.path); //这里显示将要跳转的路由是"/?order_no=123"
    ts.next(); //但其实最终跳转的路由却变成了"/"
});
```

了解上面的转换规则，我打算手动对修改最终跳转的路由

```
router.beforeEach(function(ts){
    var params = urlParam(ts.to.path); //这里将路由"/?order_no=123"转换成对象 {order_no:123}
    console.log(ts.to.path);
    console.log(params);
    if(params.order_no){
        ts.redirect('/order_no/' + params.order_no);
        return;
    }
    ts.next(); 
});
```

当将beforeEach的回调修改成上面的代码，然后再次访问
http://127.0.0.1/page/pay_confirm.html?order_no=123
结果beforeEach的回调执行了两次
第1次: ts.to.path为`"/?order_no=121"`，然后当然是执行重定向 `ts.redirect('/order_no/' + params.order_no);`
第2次: ts.to.path为`"/order_no/121?order_no=121"` ，这里的路由后面为什么会多出"?order_no=121"?

请问为什么会多出"?order_no=121"? 这里的路由转换规则是怎样的？

**Comment by fnlctrl** [comment]
0.7的行为是，从外部带进来的query参数会一直保留，在hash模式下会被自动移到尾部。
如果需要移除query的话，beforeEach中传入的redirect函数没法做到，只能调用实例方法router.replace()才行。
