### ISSUE TITLE
<router-view> doesn't support jquery-ui

### ISSUE THREAD

**Issue by xinshouke** [vuejs/vue-router#557]
I npm install jquery and jquery-ui into my vue project,  while I just use  vue components  with jquery-ui,it work well.
But I plan to use vue-router in my project, then I used `<router-view>`  instead of div tag from component  name . I found many jquery-ui components did not work normally ... ...
Such as jquery-ui draggable, the error was thrown:  `safe-active-element.js?ae4a:33 Uncaught TypeError: Cannot read property 'nodeName' of null` and the  jquery-ui  datepicker was unable to popup selection dialog without error, but it may show date of today.

**Comment by LinusBorg** [comment]
Hello ...,

thank you for your filing this issue.

Please provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem.

Thank you.

**Comment by xinshouke** [comment]
@LinusBorg I was unable to use jsfiddle since network speed ,would you like use my sample project please?

**Comment by LinusBorg** [comment]
If you can provide a link and instructions where in the source the relevant code is, sure.

**Comment by xinshouke** [comment]
I used a office network far from my home, I had still not registered  jsfiddle account successfully. Maybe there was some unknown reason. Actually, I created my sample project using vue-cli,there were my steps as below: (I had to upload my project to cloud disk this night because of network limitation)
1. vue init webpack my-project.
2.cd my-project
3. npm install
4. npm install --save jquery jquery-ui vue-router (my testing wasys)
5. upload or replace  the below files into folder src
[route-config.js.TXT](https://github.com/vuejs/vue-router/files/362917/route-config.js.TXT)
[App.vue.TXT](https://github.com/vuejs/vue-router/files/362922/App.vue.TXT)
[main.js.TXT](https://github.com/vuejs/vue-router/files/362923/main.js.TXT)
6.replace  the below files into folder src\components
[Hello.vue.TXT](https://github.com/vuejs/vue-router/files/362924/Hello.vue.TXT)
7.create a jquery folder under of src,upload these files into this folder

[style.css.TXT](https://github.com/vuejs/vue-router/files/362927/style.css.TXT)
8.replace the webpack base file under of build folder
[webpack.base.conf.js.TXT](https://github.com/vuejs/vue-router/files/362929/webpack.base.conf.js.TXT)
9.npm run dev, you may find the jquery UI didn't performance not normally.
10. If remove the vue-router configuration, and use the simple vue project .you will find the jquery ui run well.

**Comment by xinshouke** [comment]
@LinusBorg this is my sample project  [http://pan.baidu.com/s/1hsptBhi](http://pan.baidu.com/s/1hsptBhi) unzip the file and cd the folder, then npm install and npm run dev, you may find jquery-ui behave not normally, but remove the vue-router configuartion and `<router-view>`, it work well.

**Comment by LinusBorg** [comment]
Provided links dont work, reproduction not possible. Likely using $nextTick() would solve the issue.

**Comment by xinshouke** [comment]
@LinusBorg I add the below code into my vue source-code, I get the same error:
`import Hello from './components/Hello';
import $ from 'jquery';
require("jquery-ui");
require("jquery-ui/ui/widgets/draggable");
require("jquery-ui/ui/widgets/datepicker");
export default {
  components: {
    Hello
  }, 
  ready:function(){
    this.$nextTick(function(){
      $("#draggable").draggable();
      $("#datepicker").datepicker();
    });                   
  }  
}
</script>`

I re-upload my sample project ,it should be download by clicking the above url

**Comment by xinshouke** [comment]
@LinusBorg  I found the root cause is that I used `body` as el... So this is not a bug.
