### ISSUE TITLE
Default route when a custom root path is used

### ISSUE THREAD

**Issue by clooudch** [vuejs/vue-router#558]
The default route '/' does not display when i go the the url '/app'.

I have defined a custom root path '/app' and i have defined a route for '/'.

But accessing the path '/app' displays my error page that i bound to the route '*' and not the default route '/'. I can access the route '/' over the path '/app/'. That works like a charm.

When i accessed the route '/app'. The $router.path property is defined as an empty string. But i can not define a route for an empty string.

Is it possible to route '/app' or is this just how the vue-router works. Is there some kind of workaround for that kind of behavior?

**Comment by LinusBorg** [comment]
Hi clooudch,

thanks for filing this issue.

I hope I understand you correctly: When you directly go to the URL `/app`, then you get an error page, but you expect to go to `/` - is that what you mean?

Well, in that case, this cannot be solved by vue-router, or any code on the client-side for that matter.

The backend-server has to redirect requests for such routers back to `index.html`.

**Comment by clooudch** [comment]
I get the error page from the vue-router that i defined. This has nothing to do with the server.

**Comment by clooudch** [comment]
I already found a workaround.

I removed the custom root path from the router configuration and created a route to '/app' instead to '/'. The route now works for both '/app' and '/app/'.

**Comment by clooudch** [comment]
To explain the issue a little bit more:

I have created a html page that gets delivered when you request the page '/app' or any of the pages '/app/*'.

In that page i then created a vue-router with a root-path '/app' configured. 

Then i created a route '/' for the default route and a route '*' for the error page.

Now when i go to '/app' i get the html page from the server and the vue-router displays the error route defined as '*'.  **This is not what i want! I want to get the component for the route '/' instead**

When you are on the page and print out the $router object in the console you can then see that the 'path' property is an empty string.

**Comment by LinusBorg** [comment]
Ah, this is the same issue as #455 
Evan fixed this with [this commit](https://github.com/vuejs/vue-router/commit/f20af7d14785b344ff0adcb46f8e7fce1828dfb2)  but the new version containing this fix has not been released yet.

**Comment by LinusBorg** [comment]
Closing this issue in favour of #455.

**Comment by clooudch** [comment]
Ah sorry. I didnt see the issue.

Thank you for your help.

I am not using the custom root configuration anymore. I am creating the desired behavior with nested routes now.

**Comment by LinusBorg** [comment]
Great you found a workaround for the time being. We will try and release a new version with this fix asap.

**Comment by samturrell** [comment]
@yyx990803 - Is there any way we can get this fix versioned?

**Comment by deiucanta** [comment]
@samturrell here is a quick & dirty fix I did for my app

``` js
router.beforeEach(transition => {
    if (transition.to.path == '') {
        transition.replace('/');
    } else {
        transition.next();
    }
});
```
