### ISSUE TITLE
Document how named subroute should be referenced

### ISSUE THREAD

**Issue by imaia** [vuejs/vue-router#560]
When you have a route like so:

```
router = new VueRouter()
router.map
  '/':
    name: 'home'
    component: HomePage
```

You can access it with:

`<a v-link="home">click</a>`

Now, what with I have a named nested route?

```
router = new VueRouter()
router.map
  '/':
    name: 'home'
    component: HomePage
    subRoutes: HomePage.subRoutes

# HomePage.coffee
module.exports =
  subRoutes:
    '/':
      name: 'something'
      component: Component
```

How would the v-link for HomePage.Component look like? That should be documented.

**Comment by LinusBorg** [comment]
Hi @imaia,

Thanks for filing this issue.

But as I explained in the [forum thread](http://forum.vuejs.org/topic/4599/how-can-i-link-to-a-named-nested-route), there's no difference to document.

```
<a v-link="{name: 'something'}">Go to the subcomponent</a>
```

Sidenote: your example code does not make much sense. `//` is not a valid path.

**Comment by imaia** [comment]
Hi @LinusBorg thanks for your time,

Ok, bad example. The thing is, for some frameworks, like django, the name of the "father" route would get the subroute named appended to it. Let's try a decent example:

```
router = new VueRouter()
router.map
  '/':
    name: 'amazon'
    component: Amazon
    subRoutes: Amazon.subRoutes

# HomePage.coffee
module.exports =
  subRoutes:
    '/dashboard':
      name: 'dashboard'
      component: Dashboard
```

If one could reference the shop component like this:

`<a v-link="{name: 'amazon:dashboard'}">click</a>`

It would be very intuitive. Right now, the only way to get the path to dashboard would be like this:

`<a v-link="{name: 'dashboard'}">click</a>`

right?

What if I have multiple dashboards?

**Comment by LinusBorg** [comment]
Then you have to namepace them yourself.

```
# HomePage.coffee
module.exports =
  subRoutes:
    '/dashboard':
      name: 'home:dashboard'
      component: Dashboard
```

**Comment by imaia** [comment]
Understood. Thanks.
