### ISSUE TITLE
Auto-add namespace to subroutes

### ISSUE THREAD

**Issue by imaia** [vuejs/vue-router#561]
One nice thing about vue-router is that it allows subRoutes. As routing gets more complex, one would find itself forced to namespace subroutes manually. What I propose here is that vue-router auto-add namespace to subroutes in order to avoid name collisions for named nested routes.

See https://github.com/vuejs/vue-router/issues/560

**Comment by yyx990803** [comment]
The problem with auto namespacing subroutes is that when you change the name of a parent route, all your links to that route need to be changed as well. I actually think manually namespacing is better because it doesn't have this problem.

**Comment by imaia** [comment]
Well, the big picture here is that you should not change the name of the parent route. Anyhow...

**Comment by Wirzi** [comment]
have a look how django makes the name-spacing for urls: https://docs.djangoproject.com/es/1.10/topics/http/urls/#url-namespaces
