### ISSUE TITLE
Add class name for `router-view` not work as other components.

### ISSUE THREAD

**Issue by kxxoling** [vuejs/vue-router#567]
Is this a bug or designed as it is? We can add class name to custom components in it's container, but this does not work on `vouter-view` component.

**Comment by LinusBorg** [comment]
It does work, e.g. here: https://jsfiddle.net/Linusborg/k5gswo8g/2/

But it won't work if the component used for the route is a fragment instance.

Can you provide a reproduction example?

**Comment by kxxoling** [comment]
I debugged a lot time, only find out that I mistaken the wrong dom node. These two structure looks too similar, I think it's better to rename one of them.
