### ISSUE TITLE
请问下 vue 2.0路由是否支持 动态加载 按需加载 

### ISSUE THREAD

**Issue by ckken** [vuejs/vue-router#568]
目前使用ng 的路由风格是 module / controller /action 所有路由都是按需加载 想咨询下 vue 是否支持这种加载方案 如何实现

**Comment by fnlctrl** [comment]
用webpack可以轻松实现。ng这种自带包管理的全家桶模式，vue是不会支持的。

**Comment by ckken** [comment]
我的意思是 /:module/:controller/:action 然后通过 require(/:m/:c/:a)的方法动态实现 而不需要配置路由 这样协同开发高效很多

**Comment by ckken** [comment]
like this https://github.com/ckken/ngSea

**Comment by fnlctrl** [comment]
vue-router 1.0是不支持动态更改路由map的，router.start(map)以后路由就确定了。同时路由component的懒加载函数是不接受其他参数的(http://router.vuejs.org/en/lazy.html) ，所以不可能实现根据路由参数加载路由组件。
2.0还没有开发计划的样子。

**Comment by fnlctrl** [comment]
（多嘴说一句，这种方式（动态路由）组织SPA，简直是无底坑。。。

**Comment by DotCoyote** [comment]
Could you write in english, please? 👎

**Comment by LinusBorg** [comment]
@CinKon Vue's Author, Evan, is a chinese speaker and Vue has a huge userbase in the chinese developer community.

And just like you don'T speak chinese, many of them don't speak english at lest not well enough to ariculate their issues properly). It's bound to happen that people articulate their problems here in chinese.

So we have no "english only" rule - though we encourage it.

**Comment by fnlctrl** [comment]
It's rather a question, not an issue though, so I guess you can close it :D
@LinusBorg

**Comment by LinusBorg** [comment]
you can ask questions on the decicated forums, there's also subforums for different asian languages:

forum.vuejs.org
