### ISSUE TITLE
v-link doesn't work in custom child component, forced to use href and history: true

### ISSUE THREAD

**Issue by jacobgreen25** [vuejs/vue-router#570]
The following v-links work fine, but I get an error if I try to use v-links in my custom navbar component. Would be great to be able to use v-links in my navbar component as well.

```
<template>
   <div id="app">

    <navbar></navbar>

    <a v-link="{ path: '/cart' }">Go to Cart</a>
    <a v-link="{ path: '/background' }">Background</a>
    <router-view></router-view>

  </div>
</template>
```

**Comment by zllovesuki** [comment]
What's the error you are getting?

Please refer to https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines for issue guideline.

**Comment by EdouardNaze** [comment]
Same problem here.
I just can't use v-link on my sidebar menu.
Just one question : Do you have any bootstrap template ? I'm actually thinking that my template can produce an error. I use gentelella bootstrap boilerplate.

**Comment by fnlctrl** [comment]
@jacobgreen25 @EdouardNaze Please provide a live example on jsfiddle, codepen, etc.  :smile:

**Comment by fnlctrl** [comment]
Closed due to inactivity.
