### ISSUE TITLE
Dot (.) in URL

### ISSUE THREAD

**Issue by saman** [vuejs/vue-router#576]
I've used Vue Router; I was trying to use a domain name in the path, and I've got a problem.

When I use dot (.) for example `http://mywebsite.com/domains/xyz.com` in the path, Vue could not find the path and did not go to the component.

**Comment by saman** [comment]
I've checked twice. The problem was for middleware of the webpack. The routing is fine and it depends on your web server.

**Comment by ChristianSiegert** [comment]
@saman How did you solve this? I have the same issue (dot in URL path). When I click on a \<router-link to="/foo.bar"> I can access the URL, but when I refresh the page in the browser, I get a “Cannot GET /foo.bar” message. So the internal routing with vue-router works but a direct access does not.

Edit: I’m running in dev mode (npm run dev).

**Comment by saman** [comment]
@ChristianSiegert I wrote a rewrite in `dev-server.js`
```javascript
// handle fallback for HTML5 history API
// app.use(require('connect-history-api-fallback')())
var historyApiFallback = require('connect-history-api-fallback')({
    // disableDotRule: true,
    // verbose: true,
    rewrites: [
        {
            from: /^\/cdn\/.*$/,
            to: '/'
        }
    ]
})
```

`folder` is an initial path for my app.
