### ISSUE TITLE
Multiple routes with the same name, but different parameters

### ISSUE THREAD

**Issue by danielsamuels** [vuejs/vue-router#577]
I would like to propose a new feature / enhancement for Vue Router which takes inspiration from other routing systems - such as that found in the Django framework.  Vue router already supports named routes, and that's very useful for keeping static URLs in a singular location, but what it doesn't support is having two routes with the same name, but with different parameters.

Here's a few examples of where this would be useful:

```
router.map({
  // List of exhibits.
  '/exhibits': {
    name: 'exhibits:listing',
    component: Exhibits,
  },

  // Exhibit detail page.
  '/exhibits/:exhibitSlug': {
    name: 'exhibits:detail',
    component: Exhibit,
  },

  // Exhibit within an exhibition.
  '/exhibition/:exhibitionSlug/:exhibitSlug': {
    name: 'exhibits:detail',
    component: Exhibit,
  },
})
```

```
router.map({
  '/news/': {
    name: 'news:listing',
    component: NewsListing
  },

  '/news/:year/:month/:day/': {
    name: 'news:listing',
    component: NewsListing
  },

  '/news/category/:categorySlug/': {
    name: 'news:listing',
    component: NewsListing
  },

  '/news/author/:authorSlug/': {
    name: 'news:listing',
    component: NewsListing
  },
})
```

I've tried to give examples where just having optional parameters isn't enough and where re-using the same name would actually be useful.  Primarily these situations would be ones in which you're using the same view / templates but with different contexts or filters.

**Comment by simplesmiler** [comment]
Why do you want them have the same name? What is the benefit?
When you do `router.go({ name: 'exhibits:detail' })` it becomes unclear, at which route you would end up.

**Comment by danielsamuels** [comment]
It's not unclear at all, that particular route wouldn't exist (assuming all parameters are required).  In the first example, your code would look like this:

```
router.go({ name: 'exhibits:detail', params: { exhibitSlug: 'foo' } })
 -> /exhibits/foo/

router.go({ name: 'exhibits:detail', params: { exhibitionSlug: 'bar', exhibitSlug: 'foo' } })
 -> /exhibits/bar/foo/
```

**Comment by rpkilby** [comment]
The implementation changes should be straightforward too - router matches against a list of routes instead of a single route. 

> What is the benefit?

@danielsamuels - I'm curious too - have used django for several years but haven't taken advantage of this feature. Is there any other benefit to this aside from stylistic preferences?

**Comment by danielsamuels** [comment]
In a recent case for a project I worked on (from which I took and tweaked for the exhibit example above) I had to have a router map which looked like this:

```
router.map({
  '/exhibits': {
    name: 'exhibits:listing',
    component: Exhibits,
  },
  '/exhibits/:exhibitSlug': {
    name: 'exhibits:detail',
    component: Exhibit,
  },
  '/exhibition/:exhibitionSlug/:exhibitSlug': {
    name: 'exhibitions:exhibit_detail',
    component: Exhibit,
  },
})
```

Having the proposed feature would have mean I could just use `exhibits:detail` for both names, and just pass in the `exhibitionSlug` if I want the Exhibit within the context of an Exhibition, or without if I just wanted it as a singular item.

**Comment by fnlctrl** [comment]
@danielsamuels Why not:
```
router.map({
  '/exhibits': {
    name: 'exhibits:listing',
    component: Exhibits,
  },
  '/exhibits/:exhibitSlug': {
    name: 'exhibits:detail',
    component: Exhibit,
  },
  '/exhibition/:exhibitionSlug/:exhibitSlug': {
    name: 'exhibitions:exhibit_detail',
    component: Exhibit,
  },
})
```

**Comment by posva** [comment]
In current version of vue router it's possible to achieve this behaviour with optional parameters.
names are intentionally unique and a part of the codebase is build around that

**Comment by mekramy** [comment]
i wrote a utility function to resolve route by parameters name, to work you must define name and meta -> name for each route:

```javascript
import Router from 'vue-router';
/**
 * Find route based on parameter count
 * @param {String} name
 * @param {Object} params
 */
Router.prototype.$resolve = function(name, params, replace = true){
	const route = getAllRoutes(this.options.routes);
	function getAllRoutes(routes){
		if(Array.isArray(routes)){
			for(let index in routes){
				let route = routes[index];
				if(route.children){
					const res = getAllRoutes(route.children);
					if(res){
						return res;
					}
				}else{
					if(route && route.name && route.meta && route.meta.name && route.meta.name == name){
						let unproceed = 0;
						if((route.path.match(/:/g) || []).length == Object.keys(params).length){
							for (const param in params) {
								if (params.hasOwnProperty(param)) {
									var rx = new RegExp(`(:${param}\\/)|(:${param}\\/?$)`,"g");
									if(!`${route.path}`.match(rx)){
										unproceed++;
									}
								}
							}
						}else{
							unproceed = 1;
						}

						if(unproceed == 0){
							return route.name;
						}
					}
				}
			}
		}
		return false;
	}

	if(!!route){
		if(replace){
			this.replace({name: route, params});
		}else{
			this.push({name: route, params});
		}
		return true;
	}else{
		return false;
	}
}
```

sample route:
```javascript
[
{
   name: 'route-a',
   path: '/:a',
   meta: {
      name: 'test-route'
   }
},
{
   name: 'route-b',
   path: '/:a/:b',
   meta: {
      name: 'test-route'
   }
}
]
```

usage in component:
```
this.$router.$resolve('test-route', { a: 1 }); // redirect to route-a
this.$router.$resolve('test-route', { a: 1, b: 2 }); // redirect to route-b
this.$router.$resolve('test-route', { a: 1, c: 3 }); // return false no route found
