### ISSUE TITLE
ERR_TO_MANY_REDIRECTS after livereload in Electron

### ISSUE THREAD

**Issue by dspangenberg** [vuejs/vue-router#58]
Output in the developer tools console:
`GET file:/// net::ERR_TOO_MANY_REDIRECTS`
`Navigated to data:text/html,chromewebdata`

Page source after livereload (elements tab):
` <html><body></body></html>`

**Comment by dspangenberg** [comment]
With ´history: false´ it works.

**Comment by yyx990803** [comment]
This should no longer be an issue if the router is created with `abstract: true`.
