### ISSUE TITLE
jump to anchor tag

### ISSUE THREAD

**Issue by vonKristoff** [vuejs/vue-router#580]
I have looked at the docs, but cannot find how to work jumping to a named anchor, classic HTML style. I do not wish to change my route view - just jump from one part of the body text to the other via an anchor tag.

`<a href="#about">About</a>`
Further down the body will be .. 
`<span name="about">business as usual</span>`

This is simple stuff, but obviously if this is not being mapped by my router it will cancel it from being appended and jumping to the relevant section.

**Comment by chrisvfritz** [comment]
This doesn't have anything to do with vue-router. The `name` attribute only works when jumping to a named _anchor_. If you wish to jump to a `span`, you'll have to use `id`, which is preferred anyway in HTML5. See [this](http://stackoverflow.com/questions/484719/html-anchors-with-name-or-id).
