### ISSUE TITLE
[v2.0.0-beta.2] doesn't work with async component ?

### ISSUE THREAD

**Issue by dhcmrlchtdj** [vuejs/vue-router#585]
### Vue.js & vue-router.js version

2.0.0-beta.5, 2.0.0-beta.2
### Reproduction Link

http://jsbin.com/cenutet/edit?js,console,output
### Steps to reproduce

click `/page2`
### What is Expected?

goto page 2
### What is actually happening?

`Uncaught TypeError: Cannot read property 'beforeRouteLeave' of undefined` thrown

---

https://github.com/vuejs/vue-router/blob/v2.0.0-beta.2/src/history/base.js#L131

What is `component.options` for async component?

**Comment by JounQin** [comment]
+1

But you js bin file gets error: `"Script error. (line 0)"`.

How about this one: https://jsfiddle.net/JounQin/qyd624yk/

#586

**Comment by yyx990803** [comment]
Fixed in beta.3
