### ISSUE TITLE
[2.0.0-beta.3]not redirect to root router automatically now?

### ISSUE THREAD

**Issue by JounQin** [vuejs/vue-router#587]
### Vue.js & vue-router.js version

2.0.0-beta.5, 2.0.0-beta.3
### Reproduction Link

https://jsfiddle.net/JounQin/4f6g94ut/
https://jsfiddle.net/JounQin/7fsmc4fp/
### Steps to reproduce

Just look at the above.
### What is Expected?

In the first jsfiddle file, I didn't add:

``` javascript
{
    path: '*',
    redirect: '/'
}
```

and it could not redirect to the root router automatically.
### What is actually happening?

What I'm saying is that, when I try to open `localhost:8080` it doesn't redirect to `localhost:8080/#/`.

Is that an issue or a feature that we should handle initialization by ourselves?

**Comment by yyx990803** [comment]
Fixed in beta.4
