### ISSUE TITLE
Dynamic change router view with function/condition

### ISSUE THREAD

**Issue by remoe** [vuejs/vue-router#59]
I want to change the view after a condition match (function):

base route -> /home

In "/home" i want to select a view after a condition. This is currently not possible, right?

It's only possible to define a view component for a route. Or should one solve this differently?

**Comment by JosephSilber** [comment]
You should either redirect from your home route, or put a dynamic component in your home route's view.

**Comment by remoe** [comment]
Thanks. I don't know what you exactly mean. The "router.redirect" is static. The route's view is already dynamic. Or do you mean a dynamic view in a dynamic view?

**Comment by JosephSilber** [comment]
Correct. A dynamic component in the dynamic view.

As for redirecting: I meant to use the `router.go()` method to send the user to a different route.

**Comment by remoe** [comment]
Ok, but when I had defined a route I can't call router.go(). It only switch the component:

```javascript
router.map({
    '/r1': {
      component: 'view1'
    },
```

Where you mean can one insert the go() method? With click-event? I don't want do use it.

**Comment by remoe** [comment]
I'm not sure this is a part of it:
https://github.com/vuejs/vue-router/blob/master/example/routes.js#L64

It should be possible to hook a route to make a decision with application state?

**Comment by remoe** [comment]
I restructed my code and solved it differently. @JosephSilber thanks anyway.
