### ISSUE TITLE
name not working

### ISSUE THREAD

**Issue by DotCoyote** [vuejs/vue-router#592]
I set up my router like this:

``` javascript
Vue.use(VueRouter)

router.map({
  '*': {
    component: notFound,
    breadcrumb: '404',
    name: '404'
  },
  '/': {
    component: Home,
    breadcrumb: '/',
    name: 'home'
  },
  '/referenzen': {
    docTitle: 'Referenzen',
    name: 'referenzen',
    component: References,
    breadcrumb: 'Referenzen'
  }
})

router.alias({
  '/references' : '/referenzen'
})
```

But the name is not available:

![VueConsole](https://storage.jumpshare.com/preview/EmMuMEWlw-yu1XZC8Bsk8OuilfD1NvnkEqaWT-7_N9O-D8w8qUDJJYHP2bRUq7nRNdQY8ZUHDxhSg8jqWYQ5690Iq-_ZMIwlJNqsu6s4bO0F1kR3dMUjedqC16uBUu85)
### Versions

Vuejs: 1.0.26
Vue-Router: 0.7.13

**Comment by jingman** [comment]
Your image link didn't work - can you update it?

**Comment by DotCoyote** [comment]
I'm sorry, my bad...
I expected to see $router.name in the Vue-Console, but it works anyway.
