### ISSUE TITLE
The client-side rendered virtual DOM tree is not matching server-rendered content

### ISSUE THREAD

**Issue by doabit** [vuejs/vue-router#593]
### Vue.js & vue-router.js version

2.0.0-beta.6, 2.0.0-rc.1
### Reproduction Link

https://github.com/doabit/vue-ssr-demo
### Steps to reproduce

After run `npm build` and `npm start`, when visit `http://localhost:3000`,  it works well, when click `about` to visit `http://localhost:3000/about` and refresh
### What is Expected?

Browser console show errors:

``` javascript
vue.common.js:2246[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. Bailing hydration and performing full client-side render. 
Uncaught TypeError: Cannot read property 'data' of null
```

**Comment by yyx990803** [comment]
You need to set `router.setInitialLocation(context.url)` in your `server-entry.js`. Otherwise the server-side router doesn't know what initial route to render.

**Comment by doabit** [comment]
Works well, thanks.

**Comment by simplesmiler** [comment]
Note: in [2.0.0-rc.2](https://github.com/vuejs/vue-router/releases/tag/v2.0.0-rc.2) `router.setInitialLocation` was removed in favour of `router.push` just after creating the router.
