### ISSUE TITLE
Global v-link activeClass setting?

### ISSUE THREAD

**Issue by elithrar** [vuejs/vue-router#594]
Looking through the docs and current/closed issues didn't surface anything, so:
- Allow a global configuration to override the default active class for all `v-link` params
- This removes boilerplate in Components, although does potentially increase coupling.
- Suggested approach:

``` js
router.options({
  "activeClass": "active"
})
```

An alternative approach would be to override on a per-component basis.

**Comment by yyx990803** [comment]
http://router.vuejs.org/en/options.html look for "linkActiveClass"
