### ISSUE TITLE
Default to parent route's component if a component isn't specified on a sub-route

### ISSUE THREAD

**Issue by ianwalter** [vuejs/vue-router#597]
This feature request would make it more convenient for those developing applications which are keeping component state in sub-routes. i.e. 

``` js
'/profile': {
  component: ProfileView,
  subRoutes: {
    '/edit-name': {
      component: ProfileView,
      isEditingName: true
    }
  }
}
```

In my opinion, the 'edit-name' sub-route shouldn't have to specify a component. It should just default to the main route's component. Thoughts?

**Comment by yyx990803** [comment]
If it's not corresponding to a component then it should be a dynamic segment in the parent route instead of a subroute.

**Comment by ianwalter** [comment]
@yyx990803 If I were to add a dynamic segment to the route above, for example, `'/profile/:action'`, then it would no longer match the base `'/profile'` path and I would get a 404. I could create separate routes, but I don't think it wouldn't be as concise and organized as using subroutes.

**Comment by yyx990803** [comment]
@ianwalter the point is that nested routes are designed for nested components, not for state, while params and queries are designed for state.

In router 2.0 though you can use `/profile/:action?` to make the dynamic segment optional.

**Comment by ianwalter** [comment]
@yyx990803 Yes, bad assumption on my part, thank you.
