### ISSUE TITLE
canDeactivate not working right

### ISSUE THREAD

**Issue by Jokcy** [vuejs/vue-router#599]
### Vue.js & vue-router.js version

1.0.16, 0.7.10
### Reproduction Link

example is here: http://output.jsbin.com/voqivayuso
code here: http://jsbin.com/voqivayuso/edit?html,js,output
### Steps to reproduce

click go, then click back, confirm comes out, if I click 'cancel', then back will never work again
### What is Expected?

back is ok after I abort the transition
### What is actually happening?

back is not working

**Comment by hubinforjs** [comment]
vue2？ ok I think, u need react

**Comment by posva** [comment]
Closing in favour of #666
