### ISSUE TITLE
Getting route params outside of router view components

### ISSUE THREAD

**Issue by holic** [vuejs/vue-router#6]
In my use case, I have an app with a template that sets up the page container. The container includes a navigation component on the left and a `<router-view>` on the right. I'd like to highlight the current active page in the navigation, but I'm not able to access any of the route params from outside the `router-view` components.

Is there any disadvantage to exposing the route params on the Vue instance used in `router.start`? Or exposed throughout all VMs? Should I pass this up to the root via an event or `v-ref`?

**Comment by yyx990803** [comment]
This is a part that I have overlooked! `react-router` deals with this using a React feature called `context`, which is essentially some data that is implicitly shared among the entire tree of components. I'm not entirely sure if it's necessary to introduce something similar to Vue yet, but for now you should be able to just do `this.$root.route.params` to access the params.

**Comment by holic** [comment]
OK. Traversing using `this.$root` makes me feel a little dirty. For now, I'm just passing the `route.params` through a prop on the component.

**Comment by yyx990803** [comment]
Now all descendants of a router-enabled app gets the `route` property automatically.

**Comment by ajcastro** [comment]
Hello @yyx990803 !

Is it possible to get the `$route` params in a simple js files. Because I have service js class that needs to access the query params. 

For example:
```js
import $route from 'from-somewhere?'

function getQueryParamsPlusOne(){
  return $route.query.some_count + 1
}
```

Currently I need to pass the `$route` variable from the component to this function everytime I use it: 
```js
function getQueryParamsPlusOne($route){
  return $route.query.some_count + 1
}
```

**Comment by posva** [comment]
The best thing to do will be passing the params that are used as arguments to your service so it doesn't rely on vue router at all.

This is a 4y old thread, please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by ajcastro** [comment]
@posva ok thank you!
so it means that it not possible to import $route/$router. 
thanks for the tips, I will just pass it in my service for now.
btw my service is really dependent on $route so I will pass the $route instance.

**Comment by posva** [comment]
You can import the router anywhere from the router.js file where you create a router instenace. But again, doing that in a service look like a bad idea because a service doesn't need to manipulate the router

Eduardo San Martin Morote

**Comment by ajcastro** [comment]
@posva I am following Domain-driven Design, and object-oriented approach, wherein, I have a Table class, and when users add filters on the table, I need to update the url with query params of filters. 
Although it is possible not to pass $router as dependency, but using this approach makes my code in component cleaner and concise, making it easier to read/understand as normal person. 

User-story: When the user add filters, it updates the url with query params of filters, and send request to api server.

So my class looks something like this. 
```js
class Table 
updateUrl(tableFilters, $router){}
request() {}
```
Usage in components:
```js
data() {
  return {
    table: new Table
  }
}, 
method: {
  onChangeTableFilters(tableFilters) {
    this.table.updateUrl(tableFilters, this.$router).request();
  }
}
```
That way, we can explicitly see that the the table is responsible for updating the url as well.
