### ISSUE TITLE
Specifying a root URL

### ISSUE THREAD

**Issue by remoe** [vuejs/vue-router#60]
It should be possible to specify a root url. For example this is the base URL of an app:

www.example.com/app

When one go to root with "router.go('/')" it should go to:

www.example.com/app

The root folder should not a part of a route. Like: http://guides.emberjs.com/v1.12.0/routing/#toc_specifying-a-root-url

Does this make sense?

**Comment by JosephSilber** [comment]
This is already possible. Set the root config option to whatever you want.

**Comment by remoe** [comment]
Thanks!

**Comment by enomado** [comment]
https://router.vuejs.org/en/api/options.html#base

**Comment by trajano** [comment]
@enomado link no longer works.

**Comment by Lege19** [comment]
parse the root to createWebHistory and vue router will handle the roots correctly. If you are using vite for development (which you probably are) you also need to add base: `'/<ROOT>/'` to vite.config.ts so that vite will serve it correctly
