### ISSUE TITLE
2.0-rc.2 Initial route does not have it's name set

### ISSUE THREAD

**Issue by wprater** [vuejs/vue-router#603]
The initial route is matched on initial render, but the `name` property is not set.

If I push another route and then the `play` route, it will have the `name` set.

Using the latest vue and vue-router.

![image](https://cloud.githubusercontent.com/assets/10452/17573921/7a4dbb28-5f12-11e6-8815-0e84806cc415.png)

**Comment by yyx990803** [comment]
Hmm, can't reproduce this. It's working for me.

**Comment by wprater** [comment]
OK. let me try and build a small test case.  fiddles work with router?

**Comment by yyx990803** [comment]
yeah, you can use https://npmcdn.com/vue-router@2.0.0-rc.2

**Comment by wprater** [comment]
I seem to have had a conflict with `vue-template-compiler` and `vue beta-8`.  Im not sure if they were related, but after updating my deps, the `name` prop is now being set on the initial render.
