### ISSUE TITLE
subRoutes vs. subroutes

### ISSUE THREAD

**Issue by didimitrie** [vuejs/vue-router#606]
This is really a formal little feel-free-to-ignore-and-close suggestion :) 
### The hidden problem

I've spent an hour debugging the following, not knowing why it doesn't work (but it works when i copy paste the example from the doc!):

``` javascript
router.map({
    '/': {
      component: Root,
      subroutes: {
        '/': {
          component: Home
        },
        '/about': {
          component: About
        }
      }
    },
[...]
```
### The big reveal:

**subroutes** is not the same as **subRoutes**! Note the capital _R_ :) 
To be fair, it makes sense the way it is. Just thought that maybe, just maybe, both could work concurrently. 

As said, really minor, ignorable, feature request from a spoiled kid that loves vue and was just annoyed he didn't get enough icing on the cake.

**Comment by LinusBorg** [comment]
Hi @didimitrie,

Thanks for failing this issue. 

However we try to keep the API clear of duplicates.
