### ISSUE TITLE
HTML5 History build up

### ISSUE THREAD

**Issue by tkjaergaard** [vuejs/vue-router#607]
I'm curious to the flow of vue-router.

I'm experiencing a, from my point of view, unexpected behaviour when aborting a transition from a `beforeEach` each hook.

The current flow (from my reverse-engineering):
1. `router.go({name: 'route'});`
2. triggers `this.history.go('/route', false, false);`
3. triggers `window.history.pushState({}, '', '/route');`
4. triggers `.onChange('/route', null, false)`
5. triggers `._match('/route', null, false)`
6. triggers `transition.runQueue`
7. triggers `BeforeEach` hook
8. hook invokes `transition.abort()`
9. calls `this.router.replace(this.from.path || '/')`

Why are the pushState invoked before the transition actually have determined if it should continue or abort?

If you're a `home`-route and, let's say, you click a logo which has a `v-link="home"` then the whole tree will be invoked pushing another entry onto the history, resulting in build up of the browser history.

The intention of the user might just be to "refresh" the current page (which he achieves). But now the user has to click twice on the "back-button" to get back to the previous page.

The default browser behaviour with regular HTTP calls would not add another entry to the history, so why does the router force another entry onto the history tree.

There might be an obvious reason for this 🙂 

I would expect to either be able to hook into the router earlier in the process or have the the pushState moved to the end of the chain?

**Comment by LinusBorg** [comment]
Hi @tkjaergaard 

Thanks for filing this issue.

The point is that the whole architecture of the router rests on the premise that the URL shoult decide where to transition to 

In other words,  `router.go()` does not start the transition - it only changes the URL. The transition starts when the router detects the changed URL (e.g. by listening to the history push event).

This mechanism is nessessary to make external/direct links to vue-router URLs work.

Changing this behaviour in cases where the route transition is triggered from your app would be thinkable, but a huge change.

I doubt that we will attempt this anytime soon, and if we will, then we will do it for version 2.0
