### ISSUE TITLE
Access to app instance from router methods

### ISSUE THREAD

**Issue by dwightjack** [vuejs/vue-router#61]
Hi,

I'm trying to change a data property of a vue app managed by a vue-router instance.
I tried using `router.afterEach` method but I can't find a way to get the app instance, something like:

```
router.afterEach(function () {
  //this is  the app instance reference
   this.$set('foo', true);
});
```

Is this the right path or there's a better option?

Thanx in advance!

**Comment by yyx990803** [comment]
It's probably better to watch the route inside the component you want to manage:

``` js
// inside the app component
{
  watch: {
    route: function (route) {
      this.$set('foo', true)
    }
  }
}
```

**Comment by dwightjack** [comment]
Ah cool,

 Didn't know such event existed! That's way better thanks!

**Comment by remoe** [comment]
I also try to update data after transition in a component. Like so:

```
    activate: function (transition) {

      var s = transition.to.path.match(/\/([a-z]*)$/);
      this.tab = s[1];
      
      transition.next()
    }
```

But this is null. So this is not allowed? But route-watch doesn't work with a child component?

Is there's a better way?
