### ISSUE TITLE
The parameter 'query' is not replaced

### ISSUE THREAD

**Issue by stranger-ru** [vuejs/vue-router#611]
Hello.

```
this.$router.go({
    path: this.$route.path,
    query: {
        a: 'a'
    }
})

// or

this.$router.replace({
    path: this.$route.path,
    query: {
        a: 'a'
    }
})
```

result: `path?a=a`

Recall function:

```
this.$router.go({
    path: this.$route.path,
    query: {
        a: 'a'
    }
})

// or

this.$router.replace({
    path: this.$route.path,
    query: {
        a: 'a'
    }
})
```

leads to: `path?a=a&a=a`.

Parameter is not replaced , and added again and again.

**Comment by LinusBorg** [comment]
This is to be expected as the router doesn't manipulate the path you provide it with.

A Workaround would be this:

``` js
 path: this.$route.path.split('?')[0],
// or:
path: window.location.pathname
```

Changing this behaviour (make the router itself apply `.split('?')[0]` to the path would technically be a breaking change.

@yyx990803 would you think this is worth it?

**Comment by stranger-ru** [comment]
**@LinusBorg** Thank you. 
But why in the url can be need two of the same parameter with different values?
Why not replace the value of the parameter if it is already in the url?

**Comment by LinusBorg** [comment]
I just told you what happens right now and how to fix it for the moment. 

We will think about how to best tackle this. The issue is still open for this reason.
