### ISSUE TITLE
[2.0] router-link to default route always applies activeClass, even with exact

### ISSUE THREAD

**Issue by fnlctrl** [vuejs/vue-router#614]
### Vue.js & vue-router.js version

2.0.0-rc.2, 2.0.0-rc.3
### Reproduction Link

https://jsfiddle.net/fnlCtrl/qepmvyLf/
### Steps to reproduce

Click on any of the router-links
### What is Expected?

The `router-link` whose `to` is default route, its `activeClass` should only apply if the router is on default route.
### What is actually happening?

`activeClass` is always applied to `router-link` whose `to` is default route.

**Comment by LinusBorg** [comment]
You should link to `'/'`, not `''`.

**Comment by yyx990803** [comment]
You should always be using `to="/"` for the root. `to=""` is considered an "empty relative", so it basically links to the current active route.

**Comment by fnlctrl** [comment]
Well, I've updated the fiddle to reflect my actual use case:
https://jsfiddle.net/qepmvyLf/3/

In this example, when the parent route is not '/', router-link to default will always get activeClass, with or without trailing slash...

**Comment by fnlctrl** [comment]
Nevermind, I forgot to set `exact`. It's working properly now https://jsfiddle.net/qepmvyLf/4/
