### ISSUE TITLE
t.$el.getBoundingClientRect is not a function [v2.0.0-rc.3] [BUG]

### ISSUE THREAD

**Issue by lukepolo** [vuejs/vue-router#617]
### Vue.js & vue-router.js version

v2.0.0-rc.2 , v2.0.0-rc.3
### Reproduction Link

Vue Component 
https://jsfiddle.net/hvzcm89n/

Vue Pile Store
https://jsfiddle.net/2405e9Ln/

Vue UserTeam Store
https://jsfiddle.net/0pj8ogn8/
### Steps to reproduce

Click on route : sometimes it triggers error. Not always. No request fails from the API. Not easy to replicate. 
### What is Expected?

Should go to page and show view / data
### What is actually happening?

![image](https://cloud.githubusercontent.com/assets/2066668/17838270/596b4122-6797-11e6-9b6b-4df0e7328acd.png)

Probably cant be solved from what I've given, which happens once in 10-15 requests.

**Comment by fnlctrl** [comment]
I've encountered this before, it's not a vue bug, but a vue-devtools bug
(you can see the error is coming from backend.js), when vue-devtools try to
call getClientBoundingRect on a component's $el which doesn't exist. Forgot
to file an issue on devtools repo, though. So perhaps you can close this
and file an issue there instead : )

A quick workaround is to replace some `v-if`s with `v-show`.

**Comment by lukepolo** [comment]
Thanks for that, ill go ahead and do that.
