### ISSUE TITLE
Nested routes throwing error in vue router

### ISSUE THREAD

**Issue by liuhedong** [vuejs/vue-router#619]
Html file

```
<div id="app">
        <h1>Just demo for router</h1>
        <p>
            <a v-link="{ path: '/foo' }">Go to foo</a>
            <a v-link="{ path: '/bar' }">Go to bar</a>
            <a v-link="{ path: '/foo/bar' }">Go to foobar</a>
        </p>
        <router-view></router-view>
    </div>
```

Vue file

```
    var Foo = Vue.extend({
        template: '' +
        '<div>This is foo</div>' +
        '<router-view></router-view>'
    });

    var Bar = Vue.extend({
        template: '<div>This is bar</div>'
    });

    var App = Vue.extend({});

    var router = new VueRouter({
        hashbang: false,
    history:true,
        root: '/', 
        saveScrollPosition: true
    });

    router.map({
        '/foo' : {
            component: Foo,
            subRoutes: {
                '/bar': {
                    component: Bar
                }
            },
        },

        '/bar': {
            component:Bar,
        }

    });

    router.start(App, '#app');
```

apache .htaccess

```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.html [L]
```

Normally clicking on the links it is working.

/foo/bar link is working perfect when i click on the url. When i directly copy the url and paste it on other browser it is displaying the error in the console as

Uncaught SyntaxError: Unexpected token <
Can anyone please tell me where i have did  wrong.

**Comment by fnlctrl** [comment]
Unfortunately this is related to apache instead of vue-router so there's nothing we can do to help.

`Uncaught SyntaxError: Unexpected token <` usually happens when server sends wrong content-type header: https://www.google.com/#newwindow=1&q=Uncaught+SyntaxError%3A+Unexpected+token+%3C

**Comment by n4nirmal09** [comment]
Its not a vue issue. its related  with how the server handles the request.
Add a leading '/' for all the external resources like css,js,images etc. It will work fine.
https://stackoverflow.com/questions/10865480/mod-rewrite-to-index-html-breaks-relative-paths-for-deep-urls

**Comment by GreggOD** [comment]
In my vue.config.js file I had modified the webpack config - either I did it manually or through the Vue UI.

The `publicPath` was set to `./`

A simple change to `/` without the `.` fixed the issue.

Dont forget to restart your run.

**Comment by MegaBadCoder** [comment]
> In my vue.config.js file I had modified the webpack config - either I did it manually or through the Vue UI.
> 
> The `publicPath` was set to `./`
> 
> A simple change to `/` without the `.` fixed the issue.
> 
> Dont forget to restart your run.

Thank you!
