### ISSUE TITLE
v-link-active in a scope of parent component

### ISSUE THREAD

**Issue by cybertino** [vuejs/vue-router#620]
### Vue.js & vue-router.js version

1.0.26, 0.7.13
### Expected

https://jsfiddle.net/93v8pffd/

This example does not work correctly due to #583. There is a workaround:

https://jsfiddle.net/east1987/90Lpnbgj/4/
### What is actually happening?

**v-link-active** is not applied if **v-link** is actually in nested component though it is applied when components are not used. Check out the examples.
### Reproduction Link

https://jsfiddle.net/90Lpnbgj/1/
### Bug?

This might not be a bug but it would be a good feature which possibly covers a common case.
### Other notes

This duplicates issue #596 which was closed unresolved and was not reopened.

**Comment by fnlctrl** [comment]
In my opinion this usage case of `v-link-active` is just too complex and hard to reason with. So I'd suggest writing your own active link check method, or use vue-router 2.0 and its <router-link> component, which was designed to solve this problem.

**Comment by cybertino** [comment]
@fnlctrl I agree that it might be not that simple but I believe that it could be commonly used at least because it reduces redundant code. I haven't tried vue-router 2.0 though - it could be a solution.

**Comment by fnlctrl** [comment]
You can add your commonly used methods to Vue.prototype if you'd like, but I don't think there will be any more new features for vue-router 0.7.

**Comment by fnlctrl** [comment]
@softomatix  Closing now as it's solved in 2.0, and will be a won't fix for 0.7
