### ISSUE TITLE
<router-link> with `exact` doesn't seem to apply active class for named routes correctly (2.0)

### ISSUE THREAD

**Issue by jwahdatehagh** [vuejs/vue-router#622]
### Vue.js & vue-router.js version

`2.0.0-rc.3`, `2.0.0-rc.3`
### Steps to reproduce

`<router-link to="/" exact>Start</router-link>` applies the active class but

`<router-link :to="{ name: 'start' }" exact>Start</router-link>` doesn't.
### Problem

Should be the `isSameRoute` function in [`/src/util/route`](https://github.com/vuejs/vue-router/blob/next/src/util/route.js), but i cant find the error.
### Link to reproduce

Here is a jsfiddle with that shows the behaviour: http://jsfiddle.net/jwahdatehagh/feowLxqm/1/ 
(thanks to @posva)

**Comment by posva** [comment]
here's a fresh repro: http://jsfiddle.net/posva/wtpuevc6/ 😄

**Comment by jwahdatehagh** [comment]
Thanks @posva, i've updated the link. It illustrates the problem...
