### ISSUE TITLE
[Suggestion/Enhancement] Simpler way to set current route without alter history?

### ISSUE THREAD

**Issue by ghost** [vuejs/vue-router#626]
There are scenarios when i need to update current route without change the URL, like this:

``` js
this.$router.history.updateRoute(this.$router.match('/some/path'))
```

Sort of hairy. A better way would be:

``` js
this.$router.updateRoute({path: '/some/path'})
this.$router.updateRoute({name: 'SomeName'})
```

I could submit a PR if that's something useful for anyone else.

**Comment by LinusBorg** [comment]
Hi @sleewoo,

thanks for your suggestion.

So I hope I understand your proposal correctly:  You want an API method that allows you to change the current route, but not change the URL? 

So when someone goes to `/some/path`, it will render `componentA`, then you will change the route, the URL will still be `/some/path`, but now the $route object contains different content etc.? 

What is the usecase for this? I don't see one, can you provide an example.

To be honest, I guess this will not happen. The whole philisophy of `vue-router` is that the URL is the only source of truth, it determines which routes are matched.

If you want to sidestep that, feel free to do so, but I'm pretty sure we won't encourage that by supporting it as a feature.

**Comment by ghost** [comment]
Hi @LinusBorg 
thanks for quick reply.

Let's suppose such a scenario:
4 components:
`Index`
`Pages`
`Profile`
`Signup`

While each component is served from own url, they should also be rendered from root path, e.g. from `Index` component.

If no params given, `Index` should render `Signup`.
If a single params given and it's not a page, render `Profile`.
Else render `Pages`.

`Index` is a `render` function that can render each component but there is a issue - components depends on `$router.currentRoute` to function properly and when rendering from `Index` the current route is obviously `Index`.

Suggestions?

**Comment by ghost** [comment]
thinking about passing a custom router instance to rendered components:

``` js
h(Pages, {router: a_router_instance_tailored_for_pages})
```

please advise how to cleanly build a custom router for each component.
it's a far better way than to update root router.
thank you.

**Comment by LinusBorg** [comment]
Wow, this sounds complicated for something that shouldn't be.
1. Why do you want to render all these components under "index"? Why not use `redirect()` or `replace()`?
2. If you do really want to do that, Make the components themselves independent of the router (so you can ender them from `Index`), and create small wrapper components for each to be used in their respective routes (these can depend on the router and simply pass down the router params as props).

**Comment by yyx990803** [comment]
I think you are basically trying to work against how the router is designed.

If you want the UI to change without changing the URL, then that change should be driven by your component private state, not the router history. So you can have a index component which renders some children based on its own `data`.

**Comment by ghost** [comment]
@LinusBorg, yeah, looks awkward but it's a business requirement coming from a priority customer.

Makes sense @yyx990803 
Thank you

Updating components to not depend on router is the sanest solution here.
Wondering why i hesitated doing so from the very beginning :)
