### ISSUE TITLE
[2.0]Router hooks are not work

### ISSUE THREAD

**Issue by sarik93** [vuejs/vue-router#631]
### Vue.js & vue-router.js version

2.0.0-rc.4, 2.0.0-rc.4
### Reproduction Link

http://codepen.io/Sarik/pen/BLBdNp
### Steps to reproduce

Click to any router links.
### What is Expected?

Expected log message in console before change route
### What is actually happening?

Watch is work but hook no.
In example all router hooks not work, in the new document states that this works.

What a way to get the data to change the routing now?

**Comment by LinusBorg** [comment]
What documentation are you referring to? There is no documentation for vue-router 2.0.0 yet.

And the hooks you use in your example don't exist anymore in 2.0.0. Please read the [release notes](https://github.com/vuejs/vue-router/releases) from 2.0.0-beta.1 onwards to get a picture of how the new version works.

Also look at the examples in the `next` branch: 

https://github.com/vuejs/vue-router/tree/next/examples
