### ISSUE TITLE
[next]Asynchronous components in the first time request to display, subsequent request does not display

### ISSUE THREAD

**Issue by wengang** [vuejs/vue-router#639]
### Reproduction Link

git@github.com:wengang/vue-router-async-components.git
### Steps to reproduce

twice request Foo and Bar
### What is Expected?

the components should display
### What is actually happening?

last time,Foo and Bar components does not display
### Founded Issue function:

src/history/base.js
function resolveAsyncComponents
### Fixed Code

var resolve = function (resolvedDef) {
  //there may be have a bug,In webpack - Simple template generated by the project,
 // The resolve  function is called twice, at the time of the last call  the value of the resolvedDef    parameter is undefined,
  // Lead to subsequent requests for the same component was terminated
  if (resolvedDef) {
      match.components[key] = resolvedDef
  }
next()
}

**Comment by fnlctrl** [comment]
Cannot reproduce. Please provide a reproduction on webpackbin

**Comment by wengang** [comment]
@fnlctrl  already add reproduction repository

**Comment by fnlctrl** [comment]
You are using webpack 2.0, so use System.import instead of require:
Use

``` js
const Foo = () => System.import('./Foo.vue')
const Bar = () => System.import('./Bar.vue')
```

instead of 

``` js
const Foo = resolve => require(['./Foo.vue'], resolve)
const Bar = resolve => require(['./Bar.vue'], resolve)
```

Please refer to the webpack docs.

**Comment by JounQin** [comment]
@fnlctrl As I know, since `vue-loader ^9.3`, it has been supported.

https://github.com/vuejs/vue-loader/releases/tag/v9.3.0

**Comment by JounQin** [comment]
@wengang So, just use the latest version of `vue-loader`.

**Comment by wengang** [comment]
```
   dynamic setup component map also can not work normally
```

only hard code component map can work normally,why?
Reporduction Link also is: git@github.com:wengang/vue-router-async-components.git
can you help me

---

发件人: JounQin notifications@github.com
发送时间: 2016年9月4日 10:19
收件人: vuejs/vue-router
抄送: wengang; Author
主题: Re: [vuejs/vue-router] [next]Asynchronous components in the first time request to display, subsequent request does not display (#639)

@fnlctrlhttps://github.com/fnlctrl As I know, since vue-loader ^9.3, it has been supported.

https://github.com/vuejs/vue-loader/releases/tag/v9.3.0

―

**Comment by fnlctrl** [comment]
@wengang Please ask questions on our [forum](http://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue), thanks!
