### ISSUE TITLE
abstract out history management

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vue-router#64]
Currently the logic for handling the difference between html5 history mode and hash mode is scattered across the codebase. It's a good idea to abstract them behind a single interface.

**Comment by cheapsteak** [comment]
Perhaps also do a check for whether the url starts with `file:///` (phonegap, electron) and forcibly not use html5 with a logged warning?

**Comment by holic** [comment]
This came across my radar the other day: https://github.com/rackt/history
