### ISSUE TITLE
lazy-loading异常

### ISSUE THREAD

**Issue by JerroldLee** [vuejs/vue-router#642]
vue-router的lazy-loading写法，router-view第一次可以正常渲染，第二次访问就为空了，"vue": "^2.0.0-rc.4", "vue-router": "^2.0.0-rc.4"（如果改成import同步的方式则会正常渲染）

**Comment by fnlctrl** [comment]
同https://github.com/vuejs/vue-router/issues/639

请
1.使用System.import()
2.或者更新vue-loader
