### ISSUE TITLE
[2.0] 页面跳转时，url改变是在afterHooks之后

### ISSUE THREAD

**Issue by lmllml** [vuejs/vue-router#653]
### 现象
- 在vue-router的v2.0中，当调用this.$router.push时，页面发生跳转行为，但是url的变化发生在afterHooks之后
- 在vue-router的v1.0中，当调用this.$router.go时，页面发生跳转行为，但是url的变化发生在beforeHooks之前
### 情景

假设B页面的加载方式是异步加载

**在v1.0中**
- 从A页面跳转B页面
- 当前网络环境差，下面B页面对应的component时间较长，所以页面会出现loading，此时url已经改变成了B页面的url。
- 由于loading时间较长，用户等不及了，所以选择点击浏览器的返回按钮，想要返回到上一页。
- url自然就变成了A页面的url，只需在A页面中cancel掉loading即可

**在v2.0中**
- 从A页面跳转B页面
- 当前网络环境差，下面B页面对应的component时间较长，所以页面会出现loading，但是此时url没有改变，仍然是A页面URL。
- 由于loading时间较长，用户等不及了，所以选择点击浏览器的返回按钮，想要返回到上一页。
- 由于当前url还是A页面的URL，所以返回的实际上是A页面的前一页面
### 问题

那么在vue-router2.0中，如何实现一个页面跳转的Loading以应付网络环境差的情况呢？

**Comment by fnlctrl** [comment]
请使用[论坛](http://forum.vuejs.org/category/10/%E4%B8%AD%E6%96%87)提问。
