### ISSUE TITLE
Issue with beforeHooks in v2.0.0-rc.5 ?

### ISSUE THREAD

**Issue by websanova** [vuejs/vue-router#659]
I'm trying to set a hook using `beforeEach`.

```
router.beforeEach(function () {});
```

It throws an error:

```
Uncaught TypeError: this.beforeHooks.push is not a function
```

If we echo it out `console.log(router.beforeEach)`.

```
beforeEach(fn) {
    this.beforeHooks.push(fn)
}
```

We can indeed see it's just pushing it on some array. However, when we console it out it just shows an empty object.

```
 console.log(router.beforeHooks); // {}
```

I guess it just needs to be an array?

**Comment by fnlctrl** [comment]
Hi! Thanks for filling this issue. 
Please provide a repro on jsfiddle/codepen etc.

**Comment by websanova** [comment]
Nevermind, discovered it was something else of my own causing it.
