### ISSUE TITLE
keep-alived subroute component disappears prematurely during a transition

### ISSUE THREAD

**Issue by Centaur** [vuejs/vue-router#660]
### Vue.js & vue-router.js version

2.0.0-rc.6 & 2.0.0-rc.5
### Reproduction Link

https://jsfiddle.net/oldpig/wtvbck7v/5/
### Steps to reproduce

Click '/p2' link
### What is Expected?

The content of subroute component `Subpage` should stay on screen until covered by `Page2`. 
### What is actually happening?

`Subpage` disappears immediately

It works as expected if not using `keep-alive` on the top-level `router-view`, as demonstrated [here](https://jsfiddle.net/oldpig/wtvbck7v/7/)

**Comment by yyx990803** [comment]
This is because kept-alive components are still fully reactive. The inner router-view no longer has a matched segment and thus destroyed its content.

This is something the `keep-alive` component can improve on, however it's not a bug in vue-router.
