### ISSUE TITLE
Duplicate content after hot reload

### ISSUE THREAD

**Issue by Christilut** [vuejs/vue-router#662]
I've seen this bug reported in multiple places and read this is most likely a vue-router bug. Removing the router all-together also removes this bug.

My project structure is the following:

```
src/
    components/
        Sidebar/
            index.vue
```

So I can import like this: `import Sidebar from './components/Sidebar'

Apparently this causes the bug that when a .vue file is edited (I added an empty <div> as test) and the webpage is hot reloaded then the sidebar is duplicated.

When I change my project structure so that `index.vue` is renamed to `Sidebar.vue` and import changed to `'./components/Sidebar/Sidebar'` the bug disappears.

Hopefully this helps tracking this bug down.

**Comment by posva** [comment]
Thanks for reporting it.
Although the reproduction is different, this may be related to #544

**Comment by sqal** [comment]
@Christilut 

> So I can import like this: `import Sidebar from './components/Sidebar'

so what's the point of `index.vue` if you want to import component this way?

**Comment by Christilut** [comment]
It makes for a slightly nicer syntax `./components/Sidebar` instead of `./components/Sidebar/Sidebar`

**Comment by sqal** [comment]
Ok i get it. I checked this out in my app and can't reproduce this bug. I am using vue@2.0.0.rc6, vue-router@2.0.0-rc.5, HMR enabled everything works fine.

**Comment by Christilut** [comment]
I'll try and reproduce it this week. It's pretty elusive though, for what I've noticed so far.

**Comment by fnlctrl** [comment]
I can confirm a duplicate `<router-view>` bug with HMR (all latest version, vue, vue-router, vue-loader, webpack 2.0, etc..), but it only happens when it's used with `<keep-alive>`.
![1111](https://cloud.githubusercontent.com/assets/5557143/18635334/3a080d9c-7eb7-11e6-9606-361ad2e1ec2c.png)

Though I think I don't really need a fix because I'd just refresh the page 😂

**Comment by yyx990803** [comment]
Cannot reproduce this in with latest versions. Please re-open if a reproduction can be provided.
