### ISSUE TITLE
Router rendering twice instead (on enter, on leave)

### ISSUE THREAD

**Issue by mutumarieru** [vuejs/vue-router#663]
### Vue.js & vue-router.js version

"vue-router": "^0.7.13" ( so i guess latest via npm)
### Reproduction Link

check the console
http://jsfiddle.net/xyu276sa/1077/
### Steps to reproduce

just switch to one rout to another with the links
### What is Expected?

you're suppose to see a console log of each component's "created" hook, once when its rendered
### What is actually happening?

it appears the hook is fired even when leaving, i guess it's because there are two "router-view" tag, but they are in a conditionnal template so i don't understand the behavior, i think there's a bug somewhere or something i didn't understand with conditionnal rendering

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. It's actually not a bug because you are defining two `router-view`s and applying `v-if` and `v-else` on them. The rendering of `v-if` and `v-else` and `router-view` happens asynchronously, so both `router-views` are rendered (causing hooks to be called twice), and one of them is removed from dom.

If you want to bind different classes, you can simply use `v-bind:class`:

``` html
<div :class="logged ? 'style-1' : 'style-2'">
    <router-view></router-view>
</div>
```

**Comment by mutumarieru** [comment]
hi,
well i'm sorry let me edit the fiddle for it to be more accurate to my current project because just putting a condition on the class doesn't solve my problem. If the router outlet is in the `v-if` or `v-else` isn't it suppos to be normal that it tries to render after the `v-if` async ? else it would be quite weird to try to get an unexisting element right ?

therefore, if it waits the end of the async condition before rendering, the bug shouldn't occure.

http://jsfiddle.net/xyu276sa/1080/

could you elaborate aboute how the router tries to render the outlet when a change of route occures (on angular i had this working without problem so i'm quite curious)

**Comment by fnlctrl** [comment]
After a close examination, I was actually wrong about the explanation and sync or async doesn't matter here. The root cause is that you're changing `toggled`, which is the v-if condition, when route changes.

So, there are two factors affecting `router-view`'s rendering:
1. Route change, that creates new `router-view` and destroys the old one.
2. `toggled`, which also creates a new `router-view` and destroys the old one.

Since the two cannot happen simultaneously, (you cannot change two states at one time, synchronously or asynchronously, either one must happen first), the hooks will get called twice.

**Comment by mutumarieru** [comment]
well i changed the fiddle to show again more how i do it. In few words, i have an auth system, when the user logs in i want one kind of layout (independently of what route by the time a logged in user can access those routes) and when user logs out he can only see other kind of routes with a different layout.

I now understand why it doesn't work, thought it's kind of tricky, the router shouldn't be able to re-render a component he's already on (as if i could rerender by going twice to the same url, thus, not possible via a browser to go from one hash to the same hash except by reloading the page)

http://jsfiddle.net/xyu276sa/1081/

any idea how i could acheive that, i already tried to change the design of the app but i can't see any other way than conditional rendering, the other wya would be to duplicate my layout in each component where user needs to be logged in but it would be not maintainable

**Comment by fnlctrl** [comment]
Sorry but I don't quite understand your use case...
You can just define v-ifs in each router-view component to show different content depending on the login status

If you want to do it globally (without changing every router-view component), you can just define it inside your root template, without using two `router-views`:

``` html
<div v-if="logged">
  <router-view></router-view>
</div>
<div v-else>
  ....the content you show when user logged out, independent of routes
</div>
```

**Comment by mutumarieru** [comment]
Ok let me simplify what i said. Let's say I have 10 pages, login, landing
and 2 other pages which are static pages (for logged out users only) so I
need four routes and components here.

Now I also have 6 other pages for logged in users only, so I need 6 routes
and components.

Here's the problem, each of these two groups need a totally different
layout (like on most websites, static pages and app pages don't have the
same layout)

Now either I do what you say and just duplicate layout in each component
which would not be DRY, either I create two parent routes which would be
overkill just to create sub layouts.

Do you get it ?

**Comment by LinusBorg** [comment]
> Now either I do what you say and just duplicate layout in each component

You can do this in a DRY way.
- Put the two layouts in two components.
- in each layout, define a `<slot>` element where the route components should go
- now in each of the 10 components, wrap its template in the required layout:

``` html
<template>
<layout-a>
  <-- rest of the template here -->
</layout-a>
</template>
```

Additionally, if you think about switching to Vue 2.0 and vue.-router 2.0, you can have named `<route-view name="Sidebar">` elements, so fill multiple route-views from one route:

https://github.com/vuejs/vue-router/tree/next/examples/named-views

**Comment by mutumarieru** [comment]
I guess the named route would be the perfect solution bit the component way
with a slot can be a good solution too. Thanks

Le 16 sept. 2016 13:55, "Thorsten Lünborg" notifications@github.com a
écrit :
