### ISSUE TITLE
keep-alive causes functional route component not rendered

### ISSUE THREAD

**Issue by Centaur** [vuejs/vue-router#664]
### Vue.js & vue-router.js version

2.0.0-rc.6 & 2.0.0-rc.5
### Reproduction Link

https://jsfiddle.net/oldpig/qos7px6j/6/
### Steps to reproduce

run 
### What is Expected?

content of functional component `Page1` should be rendered
### What is actually happening?

Not rendered.

Observations:
If keep 'keep-alive' and remove `functional : true`, works as expected. 
If remove `keep-alive` and keep `functional: true`,  it gets rendered but class 'view' defined in `router-view` is not merged. I guess this can be reasoned from technical point of view, but it can still be very surprising at the first sight. So I think it may at least deserve a special treatment in the documentation. 
If remove both, works as expected.

All these observations apply to jsx as well.

**Comment by yyx990803** [comment]
Functional components are instance-less and thus do not work with `keep-alive` (how do you cache something without an instance?). Short answer is do not use functional component as route components.
