### ISSUE TITLE
Disable go back browser button

### ISSUE THREAD

**Issue by gary149** [vuejs/vue-router#670]
I have a form at "localhost/form" the user comes in from this route "localhost/intro"
I want to disable the going back button on the browser when the user reach "localhost/form".
Is there a way to do this with the router ? like kill the history or hack the browser behavior ?

Thanks

**Comment by nicolasparada** [comment]
> A link with replace: true will call router.replace() instead of router.go() when clicked, so the navigation will not leave a history record.
> 
> ``` html
> <a v-link="{ path: '/abc', replace: true }"></a>
> ```

**Comment by gary149** [comment]
Ok but when ? the user uses the browser button

**Comment by LinusBorg** [comment]
What browser button? There are usually a few ...

Also:  your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).
