### ISSUE TITLE
Cannot read property 'matched' of undefined && Unknown element <router-link> && Unknown element <router-view>

### ISSUE THREAD

**Issue by MartianGreed** [vuejs/vue-router#672]
Hey,

i got those weird issues with this setup:
- "vue": "^2.0.0-rc.6",
-  "vue-router": "^2.0.0-rc.5"
- main.js
  
  > import Vue from 'vue/dist/vue'
  > import App from './App.vue'
  > 
  > import router from './router/index'
  > 
  > new Vue({
  >    router,
  >    ...App
  > }).$mount('#root')
- router.js
  
  > import VueRouter from 'vue-router'
  > import Vue from 'vue/dist/vue'
  > 
  > Vue.use(VueRouter)
  > 
  > import App from '../App'
  > import LoginApp from '../components/login/LoginApp'
  > 
  > const routes = [
  >   {
  >       path: '',
  >       component: App
  >    },
  >    {
  >        path: '/login',
  >        component: LoginApp
  >    }
  > ]
  > 
  > export default new VueRouter({
  >    mode: 'history',
  >    base: '/',
  >    scrollBehavior: () => ({ y: 0 }),
  >    routes: routes
  > 
  > })`
- App.vue
  
  > <template>
  > 
  > <div id="app">
  >      <router-link to="/">Home</router-link>
  >      <router-link to="/login">Login</router-link>
  >      <router-view></router-view>
  >  </div>
  > 
  > </template>`

I just can't figure out what's wrong... Tried to find examples, googled the errors but i just found nothing...
I inspired myself of this : [Vue Hackernews 2.0](https://github.com/vuejs/vue-hackernews-2.0)

The "Vue Warn" for router-view and router-links can be resolved by writing them in template instanciation of Vue in main.js. I wonder why is there the warn outside this file.

And I got  the error cannot read 'matched' of undefined that i just don't understand...

Did you guys know what's wrong ??
Cheers

**Comment by yyx990803** [comment]
http://rc.vuejs.org/guide/installation.html#Note-on-NPM-Builds

**Comment by MartianGreed** [comment]
My bad... Just missed it...

**Comment by ChromoX** [comment]
I'm having this same issue, but the link above is no longer valid. I have the exact same setup inspired from vue-hackernews-2.0.

**Comment by xgvargas** [comment]
Hello @MartianGreed, I'm having the same error message in here. Did you solved by using that alias sugested by @yyx990803 ?

This is not working to me. Any way, I don't understand why I need to use the standard lib if I'm using webpack to pre-compile my templates... this part of documents is TOO vague.

**Comment by MartianGreed** [comment]
I really can't tell you because i'm no expert of VueJs... The solution @yyx990803 proposed worked well for me!

**Comment by xgvargas** [comment]
Ok, thanks for your reply any way.... I'll keep trying in here!

**Comment by cpury** [comment]
For my and future people's sake: What did @yyx990803 's link refer to? It seems like it's not on the page anymore...

**Comment by fnlctrl** [comment]
The link is now at
https://vuejs.org/v2/guide/installation.html#Standalone-vs-Runtime-only-Build

**Comment by ralyodio** [comment]
I'm having the exact same issue with routes failing on 'matched' error. But I used the `vue-cli webpack` which already has this resolver in place.

**Comment by cyberdude** [comment]
I'm having the same issue here. Resolver is in place.

**Comment by keyboSlice** [comment]
Same here, but using browserify with 
```  
"browser": {
    "vue": "vue/dist/vue.common"
  },
```

in my package.json

**Comment by cyberdude** [comment]
I gave up on vue router and went  with page.  So complicated for what it is.

**Comment by yyx990803** [comment]
@cyberdude the official webpack template has vue-router working out of the box...

**Comment by cyberdude** [comment]
I'll check it out. The issue for me is vue-loader and vue-router playing nice together. I wanna use .vue files and not hard coded html templates. They hate each other at the time.

**Comment by zzzgit** [comment]
![image](https://cloud.githubusercontent.com/assets/1060733/23585084/1043f4c8-01af-11e7-8e3b-72831a5e6254.png)


![image](https://cloud.githubusercontent.com/assets/1060733/23585090/26297114-01af-11e7-8379-d905e59a3d03.png)


No such a file in `node_modules`.
I have got the same problem.the official demos use in-line `template` and `$mount`,but I use `.vue` file,and this error I got.

**Comment by posva** [comment]
@zzzgit Please, use the forums to ask questions
