### ISSUE TITLE
[2.0] Docs error in page "Navigation Guards"

### ISSUE THREAD

**Issue by jiangfengming** [vuejs/vue-router#680]
![eb9637da-a074-4553-991b-37e04b312f5f](https://cloud.githubusercontent.com/assets/11750532/18783178/fa97475a-81bc-11e6-98a2-e20c13208ca4.png)

**Comment by LinusBorg** [comment]
Edit: There's indeed something off. This is neither normal-function nor arrow-function syntax.

And the second one cannot be an arrow function because it has to be bound to the vm instance.

Thanks, we will fix it.
