### ISSUE TITLE
router-view failed to switch with CSS transform

### ISSUE THREAD

**Issue by midahai** [vuejs/vue-router#683]
In template:
`<router-view transition="changelist"></router-view>`
In style:
`.changelist-transition {
    transform: scale(1);
    transition: .2s;
  }`

it appears to append components in router-view instead of shifting.
when i use `transform: translateX(100px)`, router-view stayed still when v-link works and path changes correctly.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.

> it appears to append components in router-view instead of shifting.

You need to give `router-view` a `position: absolute`, or they will not overlay on each other.

>  transition: .2s;

You're not specifying a transition-property, so the css transition won't work properly.
Please read more about css transition here: https://developer.mozilla.org/en-US/docs/Web/CSS/transition
