### ISSUE TITLE
Lazy load routes params

### ISSUE THREAD

**Issue by kyoukhana** [vuejs/vue-router#686]
In Vue Router 1.0 If I do a route  like this  the params value doesn't work in Lazy Loading.   Even the edit.vue can't read userid when calling.

```
console.log($route.params.userid);
```

```
Vue.router.map({
  '/user/edit:userid': {
  component: (resolve) => { require(['./components/views/edit.vue'], resolve); }
}

});
```

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. Please provide a repro on jsfiddle, codepen etc if you believe there is a bug.

It seems your `path` is wrong:
`'/user/edit:userid'`
It should be `'/user/edit/:userid'`. Dynamic segment requires a slash before it.

And also:
`Vue.router.map`
Did you bind `router` to `Vue`? If so, you needn't have to because you can access the router in components simply by `this.$router`

**Comment by kyoukhana** [comment]
Its within a sub route.  I don't think i can include a fiddle for this .  Here is my complete main.js file. When I add a parm to the route i get the following error.

main.js:1292 [Vue warn]: Invalid expression. Generated function body:  {path:'/dashboard/users/edit', params:{scope.user.uerid}}

```
import Vue from 'vue'
import VueResource from 'vue-resource'
import VueRouter from 'vue-router'
import auth from 'vue-jwt-auth'
import * as App from './components/app.vue'
import mdl from 'material-design-lite'
import VueMdl from 'vue-mdl'
import VueX from 'vuex'


Vue.use(VueRouter);
Vue.use(VueResource);
Vue.use(VueMdl);
Vue.use(VueX);


Vue.router = new VueRouter; /*Must be declared before using vue auth */

/*vue-jwt-auth options */
var options = {
  fetchUrl:'api/account',
  tokenUrl:'api/auth',
  loginUrl:'api/auth',
  loginRedirect:'/dashboard/home'
};

/*init vue with auth options */
Vue.use(auth,options);


/*CRFC TOKEN For form validations */
Vue.http.headers.common['X-CSRF-TOKEN'] = document.querySelector('#token').getAttribute('content');


Vue.router.map({
  '/auth/login': {
  component: (resolve) => { require(['./components/views/login.vue'], resolve); }
},

  '/dashboard/': {
    auth:true,
    component: (resolve) => { require(['./components/views/dashboard.vue'], resolve); },


    subRoutes: {
      '/':{
        component: (resolve) => { require(['./components/views/dashboardHome.vue'], resolve); }
      },

      '/users':{
        component: (resolve) => { require(['./components/views/users/users.vue'], resolve); },

        subRoutes: {

          '/':{
            component: (resolve) => { require(['./components/views/users/usersHome.vue'], resolve); }
          },

          'add':{
            auth:true,
            component: (resolve) => { require(['./components/views/users/add.vue'], resolve); }
          },


          '/users/edit/:userid/':{
            name:'edit',
            component: (resolve) => { require(['./components/views/users/edit.vue'], resolve); }
          },

          'list':{
            auth:true,
            component: (resolve) => { require(['./components/views/users/list.vue'], resolve); }
          }

        }


      },


      '/tracks':{
        component: (resolve) => { require(['./components/views/tracks/tracks.vue'], resolve); },

        subRoutes: {

          '/':{
            component: (resolve) => { require(['./components/views/tracks/tracksHome.vue'], resolve); }
          },

          'add':{
            auth:true,
            component: (resolve) => { require(['./components/views/tracks/add.vue'], resolve); }
          },

          'list':{
            auth:true,
            component: (resolve) => { require(['./components/views/tracks/list.vue'], resolve); }
          }

        }


      }

    }

  },

  '/about/': {
    auth:true,
    component: (resolve) => { require(['./components/views/about.vue'], resolve); }
  }

});


Vue.router.start(Vue.extend(App), 'body');

//Vue.router.start(App, 'body');

```

**Comment by fnlctrl** [comment]
A repro means an isolated example of the least code required to reproduce a bug, so you needn't include all your files in your project. And jsfiddle/codepen is capable of giving a repro with vue-router.

> [Vue warn]: Invalid expression. Generated function body: {path:'/dashboard/users/edit', params:{scope.user.uerid}}

This error is generally caused by something wrong in a component's tempalte, as it's thrown by vue's runtime compiler.

**Comment by kyoukhana** [comment]
Here is a link to the repo.  This repo just outlines the issue. 

[https://github.com/kyoukhana/vuerouterparam](url)

**Comment by kyoukhana** [comment]
Here is a link to the repo.  This repo outlines the basics of the issue.  

https://github.com/kyoukhana/vuerouterparam

**Comment by crswll** [comment]
I think the issue is `/edit:foo`. It does not work at all. I made a repo to show the situation very simply here if it helps: https://github.com/crswll/vue-router-bug (it does not matter if it's async or not).

**Comment by LinusBorg** [comment]
as @fnlctrl explained in the first reply: 

You cannot have prefix-text for params. it has to be  `edit/:userid`, not `edit:userid`

**Comment by crswll** [comment]
Duh, totally missed that part of the reply. I must have been looking for it with different wording.
