### ISSUE TITLE
Navigation guards are not called when navigating to route with other params

### ISSUE THREAD

**Issue by robinvdvleuten** [vuejs/vue-router#687]
Hi there,

I noticed that the navigation guards of components and routes are not called when the route is the same but the params changes (I have a year/month/date url structure). Is this expected behaviour?

Best regards,
Robin

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.

Yes it is expected. Navigation guards only guard entering a route, since you've already entered that route, and changing params doesn't mean leaving then entering the route, navigation guards won't be called.

**Comment by robinvdvleuten** [comment]
@fnlctrl thanks for the quick response! How do I prevent the actual navigation until the data is loaded then?

**Comment by fnlctrl** [comment]
That's a different topic then, please use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions. Thanks!

---

http://router.vuejs.org/en/advanced/data-fetching.html#fetching-before-navigation
