### ISSUE TITLE
Uncought error with data transition when the api server is down

### ISSUE THREAD

**Issue by mahdisyazdani** [vuejs/vue-router#688]
this is my code, that it works when the api server is running but it throws some errors when the sever is not responding 

``` js
route: {
      waitForData: true,
      data() {
        return Users.get({ id: 1 })
          .then((response) => ({
            user: response.body
          }))
      }
    },
```

the errors:

> vue-router.js?e71f:745 [vue-router] Uncaught error during transition:
> warn$1 @ vue-router.js?e71f:745
> onError @ vue-router.js?e71f:1552
> onPromiseError @ vue-router.js?e71f:1561  
> vue-router.js?e71f:1553 Uncaught Error: [object Object]
> onError @ vue-router.js?e71f:1553
> onPromiseError @ vue-router.js?e71f:1561

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only, so please use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions. Thanks!

---

You need to handle that error yourself, the router can't help you with it.

``` js
return Users.get({ id: 1 })
          .then((response) => ({
            user: response.body
          }))
          .catch(e => /* handle the error */)
```

**Comment by mahdisyazdani** [comment]
@fnlctrl Hi, thanks for the quick response. I have already tested the `.catch()` but I am afraid it is not the case. The router throws those errors anyways. Any thoughts?

**Comment by fnlctrl** [comment]
What did you pass into the `.catch()` method? Would you please provide more information, or a repro?
