### ISSUE TITLE
Can't get it to work with "vue init webpack-simple"

### ISSUE THREAD

**Issue by sean-hill** [vuejs/vue-router#689]
Hey there,

I created a brand new project using the vue cli with `vue init webpack-simple`. I've tried many different ways to get the router to work, so either I'm stupid or the docs for `vue-router` are just confusing and not clear. Could we get an example of how to incorporate `vue-router` with a simple component based project such as `vue init webpack-simple`? Thanks.

This what I have so far:
### main.js

``` js
import Vue from 'vue'
import VueRouter from 'vue-router'

Vue.use(VueRouter)

const Foo = { template: '<div>foo</div>' }
const Bar = { template: '<div>bar</div>' }

const routes = [
  { path: '/foo', component: Foo },
  { path: '/bar', component: Bar }
]

const router = new VueRouter({
  routes
})

const app = new Vue({
  router
}).$mount('#app')
```
### index.html

``` html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>vue-simple</title>
  </head>
  <body>
    <div id="app">
      <h1>Hello App!</h1>
      <p>
        <!-- use router-link component for navigation. -->
        <!-- specify the link by passing the `to` prop. -->
        <!-- <router-link> will be rendered as an `<a>` tag by default -->
        <router-link to="/foo">Go to Foo</router-link>
        <router-link to="/bar">Go to Bar</router-link>
      </p>
      <!-- route outlet -->
      <!-- component matched by the route will render here -->
      <router-view></router-view>
    </div>
    <script src="dist/build.js"></script>
  </body>
</html>
```

But I get the error in my console:

`[Vue warn]: Failed to mount component: template or render function not defined. (found in root instance)`

**Comment by posva** [comment]
In the webpack-simple repo, you have:

``` js
new Vue({
  el: '#app',
  render: h => h(App)
})
```

You shouldn't have replaced that.
Next time, please use the forums or gitter to ask questions

**Comment by sean-hill** [comment]
So something like:

``` js
const app = new Vue({
  router,
  el: '#app',
  render: h => h(App)
});
```

❓

**Comment by posva** [comment]
Yes

**Comment by sean-hill** [comment]
Awesome thanks! I think that'd be helpful to know in the `vue-router` docs.

**Comment by sean-hill** [comment]
Hey I tried it now with the `webpack` template, not the `webpack-simple` template, and the same code there doesn't work. It just displays a blank page with no errors. Should I hop over to the forums and continue there?

**Comment by posva** [comment]
That's because it's still Vue 1. Install  `webpack#2.0` instead 😉

**Comment by sean-hill** [comment]
You're a genius 👍
