### ISSUE TITLE
异步加载可以么？貌似有点问题

### ISSUE THREAD

**Issue by 285858315** [vuejs/vue-router#69]
源码
![qq 20150801133848](https://cloud.githubusercontent.com/assets/2813953/9020792/f6c1f7f6-3852-11e5-9ace-44c746f3a254.png)
运行后
![qq 20150801133754](https://cloud.githubusercontent.com/assets/2813953/9020793/fd25ea12-3852-11e5-803b-bcbc99a9f725.png)

**Comment by 285858315** [comment]
![Uploading QQ截图20150801134233.png…]()

**Comment by 285858315** [comment]
![Uploading QQ截图20150801134233.png…]()

**Comment by 285858315** [comment]
加个字符就正常了。

![qq 20150801134233](https://cloud.githubusercontent.com/assets/2813953/9020810/77b1d12e-3853-11e5-8bdb-b9149d04fad0.png)

**Comment by yyx990803** [comment]
0.12.9 已经修复此问题。
