### ISSUE TITLE
[2.0] redirect() not changing hash / abort() equivalent

### ISSUE THREAD

**Issue by fergaldoyle** [vuejs/vue-router#692]
Example: http://run.plnkr.co/O8drrKqdru329Cf4/#/a
Source: http://plnkr.co/edit/fjHGwqUnUTzq2eDpKVTa?p=preview
Standalone source in case plunker is down: http://pastebin.com/bN2vMGY4

Steps in the above example:
- Click "Go to B"
- Click "OK" in the prompt
- Press back button in the browser
- Press forward button in the browser
- Click "Cancel" in the prompt

Result: 
- Component A is correctly shown in the router outlet
- Page hash is incorrect, still shows `#/b`

In the previous version of vue-router, using `abort()` would revert the hash back to the correct path.

On a site note, how do we handle the removal of `abort()`?  `redirect()` needs you to know the previous path, where as `abort()` automatically reverted back to the previous path.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.

`Abort` is no longer needed since you can just do nothing inside guard hooks to abort the navigation.
http://plnkr.co/edit/NuiJlxJV4IkhnXOwfgqr

Please read more about navigation guards here:
http://router.vuejs.org/en/advanced/navigation-guards.html

> If neither redirect nor next is called, the navigation will be cancelled.

**Comment by fergaldoyle** [comment]
> If neither redirect nor next is called, the navigation will be cancelled.

While navigation is cancelled (i.e. the correct component is displayed in the router outlet), the hash change is not canceled.  Previously `abort()` restored the correct hash / path.

If hash is changed outside of using `<router-link />`, i.e. browser forward / back or using `<a href="#/b" />`  
1. browser hash changes (to `#/b` for example)
2. `beforeEach` fires
3. `redirect` or `next` not called
4.  navigation is canceled
5. hash remains  `#/b`

**Comment by fnlctrl** [comment]
> If hash is changed outside of using <router-link />, i.e. browser forward / back or using `<a href="#/b" />`
> 1. browser hash changes (to #/b for example)
> 2. beforeEach fires
> 3. redirect or next not called
> 4. navigation is canceled
> 5. hash remains #/b

I see.. It may indeed be a bug. @yyx990803

**Comment by yyx990803** [comment]
See https://github.com/vuejs/vue-router/releases/tag/v2.0.0-rc.6
