### ISSUE TITLE
You are using the runtime-only build of Vue where the template option is not available.

### ISSUE THREAD

**Issue by liniu** [vuejs/vue-router#699]
使用 webpack@2.1.0-beta.22 ,vue@2.0.0-rc.8,vue-router@2.0.0-rc.6 会出现warn：You are using the runtime-only build of Vue where the template option is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

**Comment by posva** [comment]
Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

the compiler included build is in `dist/vue.js`
