### ISSUE TITLE
Make `history` mode the default mode in browser

### ISSUE THREAD

**Issue by segfaultmedaddy** [vuejs/vue-router#702]
Maybe switch default mode for routing from `hash` to `history` it seems that 91% of browsers support it according to caniuse.com (http://caniuse.com/#feat=history). Or there are another points to make `hash` mode the default mode for router?

**Comment by erguotou520** [comment]
`history` mode needs the server support, not necessary I think.

**Comment by segfaultmedaddy** [comment]
While Vue is multiplatform starting from version 2, the primary platform still is browser. So it necessary to switch to more appropriated mode for browsers, while other can switch back to hash mode if they need it

**Comment by simplesmiler** [comment]
Default settings should work everywhere. History mode requires properly configured server.

**Comment by segfaultmedaddy** [comment]
Ok. Just trying to help ;)
