### ISSUE TITLE
Get the parent meta

### ISSUE THREAD

**Issue by gil0mendes** [vuejs/vue-router#704]
On the previous version of vue-router I was able to apply the session validation directly in the parent, but this not work on the new version?!  I have to repeat the meta every route?

The code below shows a simplified version of the code who I'm using:

``` javascript
export const routes = [
  {
    path: '/platform',
    meta: { auth: true },
    component: require('./components/Base.vue'),

    children: [
      // users
      {
        path: '/users',
        name: 'users',
        component: require('./components/Users.vue')
      }
    ]
  }
]

export const startSecurity = router => {
  // get login token from the localStorage
  const token = localStorage.getItem('token')

  // before each transition we check if the route need authentication
  router.beforeEach((route, redirect, next) => {
    // check if the user needs to be authenticated. If the yes, redirect to the
    // login page if the token is null
    if (route.meta.auth && token === null) {
      return redirect({ name: 'login' })
    }

    // check if a logged user should see this page
    if (route.meta.guest && token !== null) {
      return redirect({ name: 'dashboard' })
    }

    // authorize transition
    next()
  })
}
```

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.
In vue-router 2.0 parent and child route records are no longer merged into $route, so in order to access the parent's meta field, you need to iterate through `route.matched`:

``` js
// change this 
if (route.meta.auth && token === null)

// to this
if (to.matched.some(m => m.meta.auth) && token === null)
```

We'll make sure this is covered in the migration guide, thanks!

**Comment by gil0mendes** [comment]
Ok... Thanks for the quick response 👍

**Comment by adamreisnz** [comment]
It's worth noting that this also works when using `router.currentRoute`:

```js
//change this
if (router.currentRoute.meta.auth)

//to this
if (router.currentRoute.matched.some(route => route.meta.auth))
```

**Comment by NaturalDevCR** [comment]
This doesn't makes any sense to me, child routes should inherit by logic parent meta unless a child route has it's own meta params.

Just saying.

**Comment by MajedMuhammad** [comment]
Should it be a tree-like data structure? If so, every node should have, a reference to its parent if it's a child, and a reference to each of its children, if any.

**Comment by MajedMuhammad** [comment]
Heads-up, last comment.
@fnlctrl.

Do you require a separate issue? I would love to go with an RFC process for this. I see the RFC project is only for `core`.
