### ISSUE TITLE
elements inside router-link do not get updated on hot-reload

### ISSUE THREAD

**Issue by boogerlad** [vuejs/vue-router#705]
create a new project in the terminal

```
vue init vuejs-templates/webpack-simple project
```

add `"vue-router": "2.0.0-rc.7"` to `package.json`'s `devdependencies`
in App.vue, add the router-link and the router-view
https://www.diffchecker.com/lWrDzuyu
in main.js, add the router
https://www.diffchecker.com/tEpOSXbq
create a simple component for the router to use

```
<template>
  <div>
    blah
  </div>
</template>
```

Start the dev server `npm run dev` in the terminal. Edit any of the attributes or the value of the `<span>`s. Notice that they do not update. However, adding or removing a span inside `<router-link>` seems to work.

Tested on chrome and firefox.

**Comment by boogerlad** [comment]
actually, this seems to be a problem with vuejs itself and slots. retesting....

**Comment by yyx990803** [comment]
This has been fixed in latest versions of Vue and vue-router.
