### ISSUE TITLE
Where do I put things that used to go into the `data` hook? `activate` hook only happening once

### ISSUE THREAD

**Issue by cheapsteak** [vuejs/vue-router#71]
This might be a sort of regression of #40 
Activate is not getting triggered when route changes  

`/foo/:page`

When `:page` changes, the activate hook is not called again  

Am I using the right hook?

**Comment by yyx990803** [comment]
I'm in the process of nailing down the new route lifecycle.

The first thing to check is whether to reuse an existing component when the route has changed but matching the same component. It's possible to make `activate` be called in the reuse case, but that would make activate different from other lifecycle hooks.

The new design can be explained as follows:

1. Component by default will be reused if possible, but can also provide a `canReuse` boolean / function in its route config to mandate its reusability.
2. All lifecycle hooks ('canDeactivate`, `canActivate`, `deactivate`, `activate`) will only be called if the component is being replaced (i.e. switching to a different component, or `canReuse` resolves to false).
3. Separately we will have a `data` hook inside route config, which is called **every time** the route changes and the current component is matched, regardless of reuse or not.

**Comment by JosephSilber** [comment]
This whole lifecycle will have to be thoroughly documented. It's VERY hard to get all the details right by just reading the source.

**Comment by yyx990803** [comment]
@JosephSilber obviously... that's why the readme says "use at your own risk" :) It just seems premature to work on docs before the API stabilizes with proper test coverage.

**Comment by cheapsteak** [comment]
Should the new lifecycle hooks be moved out of the route's config object?
It seems like they refer to the component and not the route (i.e. it's not the route activating and deactivating, it's the component)

Maybe canDeactivate should be able to bubble up from child components?
If there's an arbitrary number of textboxes on a page (e.g. reddit comments) , and any of them are filled but not saved
