### ISSUE TITLE
2.0router实例的push 方法用不了

### ISSUE THREAD

**Issue by shmy** [vuejs/vue-router#710]
你好，
我正在开始使用vue2.0.1和vue-router2.0.0
出现了一个意外的问题

```
<div id="app">
    <router-view></router-view>
`</div>
```

```
var router = new VueRouter({});
console.info(router.push);
console.info(router.push('/h'));
```

第一个能打印
第二个就报错
`Uncaught TypeError: Cannot read property 'push' of undefined`
我试了 go replace 等等都不行

**Comment by fnlctrl** [comment]
请确保router已经被注入到vue根实例中。

```
new Vue({
  router,
  ...
})
```

否则在那之前调用这些方法是会报错的。

**Comment by todayeeee** [comment]
var router = new VueRouter({routes:routerMap});//初始化一个vue路由实例
global.router=router;

需要注册成全局变量
