### ISSUE TITLE
vue-router npm package for vuejs 1.0 is gonne?

### ISSUE THREAD

**Issue by alexsandro-xpt** [vuejs/vue-router#711]
I cant add

**Comment by egoist** [comment]
I think it's still there https://unpkg.com/vue-router@0.7.13/

**Comment by alexsandro-xpt** [comment]
Thank you so mutch, but how can I add this via `npm install` ?

**Comment by egoist** [comment]
npm install --save vue-router@0.7

**Comment by alexsandro-xpt** [comment]
Thank you mutch, you save my life today.
