### ISSUE TITLE
v-link don't work in vue-google-maps

### ISSUE THREAD

**Issue by mxshdev** [vuejs/vue-router#712]
Vue 0.7, v-link in info-window in vue-gmail-map not working. This generated simple href and reload page. Please help..

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only, so please use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions. Thanks!
