### ISSUE TITLE
router-link is not transformed to a link

### ISSUE THREAD

**Issue by darth30joker** [vuejs/vue-router#716]
I followed http://router.vuejs.org/en/essentials/getting-started.html#, but got unexpected result. Router-link tag is not transformed to a tag.

`vue` version is `^2.0.1`, and `vue-router` is `^2.0.0`.

**Comment by fnlctrl** [comment]
Please make sure `Vue.use(VueRouter)` is called and the router instance is given to the root vue instance. `(new Vue({ router, ... }))` If the problem persists, please provide a repro on jsfiddle/codepen etc. Thanks!

**Comment by darth30joker** [comment]
@fnlctrl https://jsfiddle.net/1dmtv3f0/

**Comment by VincentGarreau** [comment]
Hi @david30xie ,
Apparently vue and vue-router are not linked in your repro, I linked the missing libraries and it seems to work: https://jsfiddle.net/VincentGarreau/1dmtv3f0/3/

**Comment by fnlctrl** [comment]
↑ As above, @david30xie thanks for the explanation.

**Comment by darth30joker** [comment]
@VincentGarreau @fnlctrl 
You guys misunderstood here.

I used `vue-cli` to create this project, and then I used `npm` to install `vue-router`. After copying code from http://router.vuejs.org/en/essentials/getting-started.html#, `router-link` are not transformed to `a`, that's the problem I got.

Commands I used:

```
vue init browserify-simple vue-temp
cd vue-temp
npm install vue-router --save
npm install
npm run dev
```

**Comment by fnlctrl** [comment]
@david30xie 
The example is using in-dom templates, which cannot be compiled by `vue`'s runtime-only build (what you get by `require('vue')`, by default)
Therefore, you need to use the standalone build, check out the section here: https://vuejs.org/guide/installation.html#Standalone-vs-Runtime-only-Build

I'm sorry for any confusion caused by the docs, and we'll definitely improve it afterwards.

**Comment by darth30joker** [comment]
@fnlctrl Thank you for the explanation, it makes more sense.

Now I still have 2 questions:
1. if I should use `aliasify` for standalone build, is there any example though?
2. I saw errors for below code, which only happened on vuejs 2.0, any idea why?

```
const app = new Vue({
  router
}).$mount('#app')
```

**Comment by fnlctrl** [comment]
1. No, but maybe it would be nicer if there were... /cc @chrisvfritz 
2. For the same reason I explained before, runtime-only build cannot compile templates.

**Comment by darth30joker** [comment]
For 2, is below command a standalone build?
`cross-env NODE_ENV=production browserify -g envify src/main.js | uglifyjs -c warnings=false -m > dist/build.js`

**Comment by fnlctrl** [comment]
`standalone build` is one of vue's two builds (standalone, runtime-only), it's not related to your own code.
https://vuejs.org/guide/installation.html#Standalone-vs-Runtime-only-Build

**Comment by darth30joker** [comment]
I understand there are 2 kinds of builds for vuejs, but I don't know how to tell which one I am using, and how to switch to another one, especially when I am using `browserify`.

I think I am gonna just give up here, because I tried so many ways, and none of them worked. Also I couldn't find anything helpful in your docs, this is so frustrating for beginners. But anyway, thank you for your help!

**Comment by nlvraghavendra** [comment]
Sorry to reopen this thread. I'm having the same issue. I referred vue and vue-router in the above jsfiddle and it is still not working.

https://jsfiddle.net/1dmtv3f0/7/

**Comment by chrisvfritz** [comment]
I'm not sure why this thread only appeared in my notifications now, 😬  but for the future reference of anyone looking at this thread, check out:

- [These installation docs](https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only) for explanations and examples of how to use each build.
- [This Browserify template](https://github.com/vuejs-templates/browserify/blob/master/template/package.json) for a more complete example of how to use the various builds with Browserify.
