### ISSUE TITLE
Redirect unmatched routes to 404

### ISSUE THREAD

**Issue by RaduCl** [vuejs/vue-router#717]
In v "^2.0.0-rc.7" i can't do redirect based on wildcards.
In v 1.\* you could redirect all unmatched routes to 404. Ex 

```
router.redirect({
  '*': '/home',
});
```

**Comment by fnlctrl** [comment]
Yes you can.
http://router.vuejs.org/en/essentials/redirect-and-alias.html
https://github.com/vuejs/vue-router/blob/dev/examples/redirect/app.js#L54

**Comment by RaduCl** [comment]
ok it works, i just needed to put catch all redirect as last route in the routes array (mine was first in the array)
