### ISSUE TITLE
[2.0] Opening link in new tab does not working

### ISSUE THREAD

**Issue by xelia** [vuejs/vue-router#718]
Version 
2.0.0

Reproduction Link
http://jsfiddle.net/yyx990803/xgrjzsup/show/

Steps to reproduce
Try opening links in new tab 

What is Expected?
Link opens in new tab like in 0.7 router example http://jsfiddle.net/yyx990803/xyu276sa/show/

What is actually happening?
404

**Comment by egoist** [comment]
I can confirm this, no `#/` was prepended to the href.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.
In 2.0 router-link no longer supports opening external links / opening links in new tab, please use `<a>` tags instead.
