### ISSUE TITLE
Anchor offset is wrong when parent has a relative position

### ISSUE THREAD

**Issue by jm-david** [vuejs/vue-router#719]
When loading a page with an anchor in the path, the offset calculation of the target element `el.offsetTop` is returning the wrong value when it has a parent with relative positioning. My specific scenario is due to Bootstrap applying `position: relative` to all columns. The easy fix (I assume) would be to loop through the `el.offsetParent` property, but I thought I better start the conversation here first in case there are some problems with this approach that I haven't considered.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.
This behavior is already customizable with 2.0's [scroll behavior hook](http://router.vuejs.org/en/advanced/scroll-behavior.html)
(I assume you're talking about vue-router@0.7)

Example: 

> If you want to simulate the "scroll to anchor" behavior:
> 
> ``` js
> scrollBehavior (to, from, savedPosition) {
>   if (to.hash) {
>     return {
>       selector: to.hash
>     }
>   }
> }
> ```

And it uses `getBoundingClientRect` by default to get element positions, so no more `offsetTop` issues, but you can still customize it any way you want. ;)
