### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property '_aborted' of #<Route>

### ISSUE THREAD

**Issue by ben-joostens** [vuejs/vue-router#72]
The error is thrown when I click a link. It is "fixed" by making the following change in https://github.com/vuejs/vue-router/blob/master/src/directives/view/index.js#L49

```
previousRoute._aborted = true
```
To
```
previousRoute.$set('_aborted', true)
```

I'm not sure whether it's an actual fix though, as removing that line has the same effect.

**Comment by yyx990803** [comment]
Closing all pre-0.4.0 issues. Please open new ones if you are experiencing the same issue with the released version.
