### ISSUE TITLE
npm run build failed

### ISSUE THREAD

**Issue by ladieman217** [vuejs/vue-router#727]
Condition always false [dist/vue-router.js:957,8]
 Dropping unreachable code [dist/vue-router.js:957,39]

**Comment by LinusBorg** [comment]
Please provide additional information: 
- which branch, which version ? 
- which node & npm version?
- what did you do exactly? What is the full error message?

**Comment by fnlctrl** [comment]
The OP seems to be building vue-router by himself, but these errors:

> Condition always false [dist/vue-router.js:957,8]
> Dropping unreachable code [dist/vue-router.js:957,39]

are actually just warnings by uglifyjs, which doesn't mean the build process failed.
