### ISSUE TITLE
router.go() doesn't render correct view

### ISSUE THREAD

**Issue by adriandmitroca** [vuejs/vue-router#728]
Hello guys,

I just found out that `go()` method doesn't work in one - probably one of the most generic - case. Everything works fine when you navigate between different routes:

```
this.$router.go('/test');
this.$router.go('/test2');
```

But everything blows away when you try to navigate between one named route with different parameter. URL in the browser changes correctly, but no action in the layout is being triggered - which causes that data remains the same.

```
// Lets assume user with ID of 1:
this.$router.go({ name: 'user', params: { id: user.id } }) // everything works fine, we moved to user(1) view
// Lets assume user with ID of 2:
this.$router.go({ name: 'user', params: { id: user.id } }) // only URL has been updated, in the view we still have outdated user's of ID 1 data.
```

I am currently using Vue 1.0.28 and Vue-Router 0.7.13 which are the most recent versions for today.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.
The component is reused because `/user/1` and `/user/2` is on the same route, so its life cycle hooks are not called again. Please use a watcher on `$route` inside the component to react to route params changes.
