### ISSUE TITLE
Consider adding tags for the repo.

### ISSUE THREAD

**Issue by Piicksarn** [vuejs/vue-router#73]
Hi~
Adding tags for repo could specify points in history and mark release points.
It's helpful for user to know the version and status of repository, and would enable wider distribution of the library, for example on [CDNJS](https://github.com/cdnjs/cdnjs)
Would you please consider on using tags?

Thanks for your great work!!
Piicksarn

**Comment by azamat-sharapov** [comment]
:smile: there was [no release yet](https://github.com/vuejs/vue-router#work-in-progress---use-at-your-own-risk)

**Comment by Piicksarn** [comment]
@azamat-sharapov, thank you!
