### ISSUE TITLE
A navigation guard on a subroute?

### ISSUE THREAD

**Issue by NathanWailes** [vuejs/vue-router#731]
I have a small question about this. The nice thing about beforeRouteLeave is that you can prevent navigating away under certain conditions.

I have a setup that uses a subroute to render part of the page. I would like a navigation guard on the subroute to prevent switching to another one if the data is not saved.

```
        {
            path: '/customers/view',
            component: ViewCustomerShell,
            children: [
                {path: ':id', name: 'ViewCustomer', component: ViewCustomer}
            ]
        },
```

So when I visit /customers/view/12 and make a change, if they try to load /customers/view/13, I want to pop up the usual confirmation and potentially stop navigation. Since beforeRouteLeave is not called in this situation, what is the recommended approach for preventing navigation? It seems that watching $route would be too late, because then the navigation has already occurred.

**Comment by posva** [comment]
Please make sure to ask questions on the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Watching `$route` should work

**Comment by NathanWailes** [comment]
But a trigger on a $route watch occurs after the route has changed, so how do you prevent navigation if you don't know until after it has happened?

**Comment by LinusBorg** [comment]
> Please make sure to ask questions on the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by zppro** [comment]
i have a route like below:
```
{
    name: 'TA',
    path: '/ta/:id',
    components: {
      head: TANav,
      body: TA
    },
    children: [
      {
        name: 'TA的发布',
        path: 'tweeted',
        alias: 'details',
        components: {
          info: TAInfo,
          tweeted: TAExperience
        }
      },
      {
        name: 'TA的收藏',
        path: 'stared',
        components: {
          info: TAInfo,
          stared: TAExperience
        }
      },
      {
        name: 'TA的关注',
        path: 'following',
        components: {
          info: TAInfo,
          following: TAFollowingFollowerList
        }
      },
      {
        name: 'TA的粉丝',
        path: 'follower',
        components: {
          info: TAInfo,
          follower: TAFollowingFollowerList
        }
      }
    ]
  }
```
and my TA.vue 
```
<template lang="jade">
  .TA
    router-view(name="info", :ta="taInfo")
    router-view(name="tweeted", :is-list-tweeted="true" keep-alive)
    router-view(name="stared", :is-list-tweeted="false" keep-alive)
    router-view(name="following", :is-list-following="true" keep-alive)
    router-view(name="follower", :is-list-following="false" keep-alive)
</template>
```
the route-view  `tweeted` and `stared` are share the same component `TAExperience` and 
`following` and `follower` are share the `TAFollowingFollowerList`
the problem is when i change the route from `/ta/{id}/tweeted` or `/ta/{id}/stared` to  `/ta/{id}/following` or  `/ta/{id}/follower` and the render result is ok and vice versa,but when change the route from  `/ta/{id}/tweeted` to `/ta/{id}/stared` or   `/ta/{id}/following` to `/ta/{id}/follower`  , nothing is happen 
is the share component cause??
