### ISSUE TITLE
uri encoding with plus sign

### ISSUE THREAD

**Issue by lukpep** [vuejs/vue-router#732]
vue-router 0.7.13
vue 1.0.28

`this.$router.go('/production?tab=1&recipe='+recname);`

spaces in recname gets correctly encoded to %20 but plus sign stays untouched (should be %2B)

so recname 

> DM USZCZ

 becomes 

> DM%20USZCZ

but 

> DM + USZCZ

 becomes

>  DM%20+%20USZCZ

 instead of 

> DM%20%2B%20USZCZ

**Comment by posva** [comment]
It seems this is a bug on path-to-regexp end. As you can imagine, it is simply fixed by replacing `encodeURI` to `encodeURIComponent`.
I cannot check right now but, can you try replacing those in your vue-router dist files to check if that's what fixes the bug, please?

**Comment by lukpep** [comment]
@posva unfortunately not.
changes in `dist/vue-router.js` to encodeURIComponent breaks normal navigation - without params.

`generateQueryString`(line 600) uses `encodeURIComponent`
`stringifyPath`(line 2371) uses `encodeURI`and changing it to `encodeURIComponent`results in:

_http://localhost:8080/#!/home_ becomes _http://localhost:8080/#!/%2Fhome_ and nawigation stops working

**Comment by posva** [comment]
Ok, thanks for checking. I'll give it a deeper look. After all is something we only need for query params

**Comment by acidjazz** [comment]
@posva @lukpep any update on this? any workaround?

**Comment by posva** [comment]
Unfortunately no. Note this is a version 1 issue, though
