### ISSUE TITLE
[Vue warn]: Missing required prop: to (found in component: <router-link>)

### ISSUE THREAD

**Issue by fagray** [vuejs/vue-router#733]

**Comment by Samuell1** [comment]
Hi, do you have attribute `to="/somepath"` on router-link element ?

**Comment by posva** [comment]
As @Samuell1, add a `to` prop. Next time, please use the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) when you have a questions. [Docs](router.vuejs.org) are also quite extensive 😄 . Thanks.

**Comment by fagray** [comment]
hi sorry for my mistake. I already solved it  thank you.
