### ISSUE TITLE
SSR Vue Router: The client-side rendered virtual DOM tree is not matching server-rendered content.

### ISSUE THREAD

**Issue by nickewansmith** [vuejs/vue-router#740]
I receive "bundle.js:2662 [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside "p", or missing "tbody". Bailing hydration and performing full client-side render." when adding the <router-view> element to my application while using Vue.js Server Side Rendering.  When I remove the <router-view> element I get no errors.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.

>  This is likely caused by incorrect HTML markup, for example nesting block-level elements inside "p", or missing "tbody".

The error message has already explained the cause of the problem, please check if your template is valid html.
