### ISSUE TITLE
router-link exact not working

### ISSUE THREAD

**Issue by terrylow** [vuejs/vue-router#741]
im following the migration guide to migrate from vuejs1+vuerouter 0.7 to vuejs2+ vuerouter 2
but it seem the router-link do not perform an exact match on link,

Kindly references to the jsfiddles

[VueRouter 2.0.0](https://jsfiddle.net/ginlong_low/rcc0caqy/4/) , this will also highlight the first link when i click the second
[VueRouter 0.7.13](https://jsfiddle.net/ginlong_low/q0c6ozrk/6/) this is working prefectly

**Comment by Samuell1** [comment]
Its working but you need to use it as separate attribute

```
  <router-link :to="{path: '/edit/1'}" tag="li" exact>
    <a>Slide info</a>
  </router-link>
```
