### ISSUE TITLE
Additional CSS classes for active paths

### ISSUE THREAD

**Issue by rightaway** [vuejs/vue-router#742]
A `router-link-active` CSS class is applied to links that point to the current path, as well as links that point to parent paths of the current path (unless those parent links are specified as `exact`).

It would be useful for cases like better breadcrumb styling to be able to differentiate between parent active links and exact active links. Currently we can only differentiate between non-active links and active (exact or parent, depending on `exact` attribute) links.

So if you had links to `/1`, `/1/2`, and `/1/2/3` and you were on `/1/2/3`, then all 3 links would have a class of `router-link-active`. But `/1/2/3` could also be given a class named by default `router-link-active-exact`, and `/1` and `/1/2` could also be given a class named by default `router-link-active-parent`.

Doing this could optionally remove the need for specifying `exact` attributes on individual links because anyone could then target any type of link they want.

There could be `linkActiveClassParent` and `linkActiveClassExact` config parameters on the router that are null by default, so that the classes are not output (so no different markup is generated for existing pages). And people who want to distinguish between parent and exact active links could set these parameters to a string.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.

> Doing this could optionally remove the need for specifying exact attributes on individual links

May I ask what kept you from using `exact` attributes?

In your example of breadcrumbs, simply using exact on every `router-link`, and using `.router-link-active:nth-child(...)` to style them is a better solution than styling `router-link-active-exact`, `router-link-active-parent` or whatever classes you may want to apply to `router-link`s.

Therefore, I don't think this is worth complicating the API for, so I'm closing this.

**Comment by rightaway** [comment]
How about if there were a global setting to make router-link default to `exact`, so that it doesn't need to be specified everywhere?

Could you give an example of how `.router-link-active:nth-child(...)` could be used to achieve the effect I'd like to get (where the active exact link can be targeted differently from the active parent link)?

**Comment by fnlctrl** [comment]
> How about if there were a global setting to make router-link default to exact, so that it doesn't need to be specified everywhere?

Then after the default settings you'd be applying `:exact="false"` to every other links that you don't want exact match on, so I don't see it as a convenience over just applying `exact` (yes, you don't need `:exact="true"`, it's just five letters plus a space) on some of the links.

> Could you give an example of how .router-link-active:nth-child(...) could be used to achieve the effect I'd like to get (where the active exact link can be targeted differently from the active parent link)?

Please ask questions on the [forums](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue), thanks!
