### ISSUE TITLE
router-link 的 tag 移除了上层所有的class

### ISSUE THREAD

**Issue by one-leaf** [vuejs/vue-router#746]
不能移除全部的class，应该仅仅增加或移除  router-link-active

```
<li class="treeview">
      <router-link tag="li" to="/">/</router-link>
 </li>
```

**Comment by fnlctrl** [comment]
`<li>`不能包含`<li>`，请写正确的html。如果修改后还有问题，请给重现。

**Comment by one-leaf** [comment]
我明白了，router-link 会自动建立 li ，但原来是这样写的: 

```
<li class="treeview" v-link-active>
        <a v-link="/">/</a>
</li>
```

现在迁移到新版本该如何写？

**Comment by fnlctrl** [comment]
http://router.vuejs.org/zh-cn/api/router-link.html

> 将"激活时的CSS类名"应用在外层元素

**Comment by one-leaf** [comment]
注意 li 需要自带 `class="treeview"`， 新提供的 

```
<router-link tag="li" to="/">
  <a>/</a>
</router-link>
```

无法给 li 增加 treeview class

**Comment by fnlctrl** [comment]
可以的。如果你觉得有bug，请在jsfiddle/codepen之类的网站上给重现

**Comment by saint3347** [comment]
![image](https://cloud.githubusercontent.com/assets/7347133/19301269/2f374e96-9091-11e6-8569-4e6d434fcd77.png)
2个a同时高亮? how?
