### ISSUE TITLE
Router undefined

### ISSUE THREAD

**Issue by hlawuleka** [vuejs/vue-router#749]
Hi, 

I keep getting an error that says Router.(start/map) is undefined, what could I be doing wrong ?:
I manually included vue.min.js and vue-route.js(installed via bower).

 Vue.use(VueRouter);

```
        var App = Vue.extend({});

        var Router = new VueRouter();

        // Router.map({
        //     '/' : {
        //         component : {
        //             template : '<p>Vue routing rocking bro!!</p>'
        //         }
        //     }
        // });


        Router.start(App, "#v-app");
```

Thanks!

**Comment by LinusBorg** [comment]
You have vue-router 2.0 installed while using vue-router 0.7 syntax.

**Comment by LinusBorg** [comment]
You probably have the latest version installed which is 2.0, and has different syntax from previous versions - you try to use old syntax, please read the docs.

**Comment by hlawuleka** [comment]
Just note that https://vuejs.org/guide/routing.html and http://router.vuejs.org/en/essentials/getting-started.html are totally different! yet they are both about vue 2.0, not sure why, it does not make sense to me. The one that works is : http://router.vuejs.org/en/essentials/getting-started.html

**Comment by LinusBorg** [comment]
The first link is not about `vue-router`. It only demonstrates how you can build a small, simple routing system yourself with Vue, _without_ using vue-router. That's why the section is titled "Simple Routing from scratch", and not "Routing with vue-router" or something.
