### ISSUE TITLE
beforeRouteLeave is never called when component is reused (even with a key)

### ISSUE THREAD

**Issue by francoisromain** [vuejs/vue-router#751]
The beforeRouteLeave hook is not called when a component is reused, and has a specific key. I guess it should. 

see example here: 
http://stackoverflow.com/questions/39939256/vue-router-how-to-trigger-a-transition-on-a-nested-component

thanks

**Comment by dyu** [comment]
I can confirm this bug.
@francoisromain Hopefully that S.O. post is enough.  Otherwise a "repro" will be asked from you.

**Comment by LinusBorg** [comment]
Please provide an actual running reproduction on jsfiddle or something instead of forcing us to copy-paste code around.  That would be helpful.

Thanks :)

**Comment by francoisromain** [comment]
Here we go: https://jsfiddle.net/francoisromain/97sot78h/

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. It's actually not a bug as you didn't leave the route.
Keying the component only affects its life cycle (whether reused or not), but doesn't affect router hooks.

**Comment by francoisromain** [comment]
@fnlctrl so how can I solve the problem on stackoverflow please?

**Comment by fnlctrl** [comment]
@francoisromain Try using the [forum](http://forum.vuejs.org/) or the [gitter](https://gitter.im/vuejs/vue) ;)

**Comment by francoisromain** [comment]
@fnlctrl I tried to, but with no success: http://forum.vuejs.org/t/vue-router-how-to-trigger-a-transition-on-a-nested-component/1094/3. same on gitter and SO…

**Comment by LinusBorg** [comment]
The team reading these issues is also reading the forum. Discussing this here as well will not bring new information into the situation.

**Comment by existe-deja** [comment]
I am very interested on this problem, I asked stackoverflow here for the same thing > http://stackoverflow.com/questions/40137100/vue-js-2-0-transition-on-dynamic-route-not-firing

**Comment by mani04** [comment]
@LinusBorg I actually answered the above stackoverflow question, with a jsFiddle example. Can you please check if it is a proper solution?

Here is that jsFiddle: https://jsfiddle.net/mani04/dLnz4rbL/

As explained in my answer on stackoverflow, I am using the same method for "Transitioning between Elements". I hope it is ok to use in this context.
