### ISSUE TITLE
The route which redirect unmatched path must locate in the last of routes Arrays

### ISSUE THREAD

**Issue by wang2lang** [vuejs/vue-router#754]
route such as `{ path: '*', redirect: '/'}` now must locate in the last of routes arrays, otherwise it will replace the match after itself. It is unreasonable and stupid！

**Comment by LinusBorg** [comment]
No it's not. An URL can possibly match multiple routes. Theorder of routes definitions is used to decide priority. It's explained in the docs.

Locking this because of name-calling.
