### ISSUE TITLE
Let middle click be handled by browser

### ISSUE THREAD

**Issue by rashfael** [vuejs/vue-router#756]
A middle click on a router-link does not open a new tab (normal behaviour for `<a>`) but instead navigates in the current tab in v2.

This worked in v1, handled by this code:
https://github.com/vuejs/vue-router/blob/1.0/src/directives/link.js#L100

Right-clicking and selecting "Open link in new tab" does work, only adding to user confusion.

**Comment by nicolasparada** [comment]
I can do middle click to open a new tab...

**Comment by rashfael** [comment]
Using the code from v1 works ([fork here](https://github.com/rashfael/vue-router)) but for testing I cannot seem to trigger a middle click correctly with nightwatch. Ctrl+click does work though.
