### ISSUE TITLE
Dead link in documentation

### ISSUE THREAD

**Issue by ScreamZ** [vuejs/vue-router#757]
https://github.com/vuejs/vue-router/blob/v2.0.0/docs/en/essentials/named-views.md

JS Fiddle link is dead, can you update please ?

Thanks

N.B. : Edit this page link also dead, redirect to https://github.com/vuejs/vue-router/tree/master/docs/en/essentials/named-views.md

**Comment by LinusBorg** [comment]
@posva this was your fiddle, where did it go? :D

**Comment by posva** [comment]
My bad, I accidentally deleted it 😅
It was a copy paste from the example, so it can be recreated in 1m.i won't be able to do it until 2pm Paris time. If you can fix it before that, please do it 🙏
