### ISSUE TITLE
router-link-active的class会出现两次！

### ISSUE THREAD

**Issue by saint3347** [vuejs/vue-router#759]
![image](https://cloud.githubusercontent.com/assets/7347133/19296722/7d849c1e-9070-11e6-913e-62ab201c56df.png)

![image](https://cloud.githubusercontent.com/assets/7347133/19296648/c6a0e7b4-906f-11e6-9b31-c3f38a421f9b.png)

如果指定了一个默认的a高亮，这个a会一直高亮，因为有一个router-link-active的class常驻在那。。

所以会出现两个a同时高亮

**Comment by yyx990803** [comment]
这个是静态和动态混合 class 的更新机制导致的。也没什么问题吧，不影响渲染。

**Comment by saint3347** [comment]
![image](https://cloud.githubusercontent.com/assets/7347133/19299307/333f008e-9086-11e6-9e6f-1af9ac291d48.png)
渲染时不影响，但是实际应用的时候会有两个a链接同时高亮 orz... 
how?

**Comment by saint3347** [comment]
![routerlink](https://cloud.githubusercontent.com/assets/7347133/19300134/1d6d4914-908b-11e6-8d66-fd5ad133ec9b.gif)
