### ISSUE TITLE
conditional component on route

### ISSUE THREAD

**Issue by alioygur** [vuejs/vue-router#76]
how can i set route component conditional. such as when the `isLoggedIn` data `true` the "/" route wil be dashboard.

```
module.exports = function (router) {
  router.map({
    '/': {
      // if isLogged in is true require "dashboard" componen else load home
      component: require('./components/home.vue')
    }})
  })
```

how can i do it ?

**Comment by yyx990803** [comment]
You can only have one component for one route, but you can do the conditional check and display other components inside that component. Or - you can do a conditional redirect inside the global before hook or in the `canActivate` hook.

**Comment by awitherow** [comment]
@yyx990803 first of all, super thanks for vuejs. it is awesome :)

Second, is this comment above still valid with vue 2.0?

**Comment by fnlctrl** [comment]
@awitherow Generally yes. But the router hooks have changed, please refer to the docs.

**Comment by awitherow** [comment]
@fnlctrl been looking through the docs and cannot pinpoint exactly what I am looking for...

Considering the docs have changed drastically as it seems, a link would be nice not only for me, but for future people that stumble across this issue :) Thanks!

**Comment by alxmagro** [comment]
Conditional routes could not be a new feature? It would be very useful since most applications have a dynamic root, switching between Landing Page and a first page if the user is logged in.

**Comment by dkushner** [comment]
It seems like this feature could be as simple as accepting a function for the value of the `component` property of the route definition.

**Comment by LinusBorg** [comment]
I don't see a necessity for this. A simple functional component as a wrapper can easily solve this.
```javascript
import store from './store' // or wherever you get login status from
export default {
  functional: true,
  render(h) {
    return store.user.loggedIn 
    ? h('dasboard')
    : h('LandingPage')
  }
}
```

You can even define this small wrapper  inline in the routes config, if you wanted to. That would be pretty much the same as the suggested passing of a function.

**Comment by alxmagro** [comment]
In my opinion, this is a "routing problem", this approach seems to me a workaround. This component has no semantic reason to exist, it only there to make a switch between two different purposes components.

**Comment by alxmagro** [comment]
This is how I imagine how it could be: https://gist.github.com/alexandremagro/e9a83f5b926f13ca9b6cb224ae809ca9.

**Comment by LinusBorg** [comment]
> it only there to make a switch between two different purposes components.

That's a pretty valid usecase for a functional component - we use a similar example in the guide to explain possible use cases for functional components.

**Comment by alxmagro** [comment]
But this approach is more complicated, not simpler.

1. The true components are hidden from the routes;
2. Hides and spreads the routing logic across multiple components;

**Comment by fnlctrl** [comment]
@alexandremagro  Actually you don't need to show different component on each route.

It's far simpler and easier to reason to just do:
1. Make routes static: one route to always render one component
2. Use router.beforeEach to make redirections

e.g. 
```js
if (user.isLoggedIn) next()
else next({ path: '/login', replace: true})
```

**Comment by alxmagro** [comment]
@fnlctrl Yes, this is correct approach today. But is a limitation of Vue Router not being able to use root path (/) for Landing Page and Logged Home Page (ex. Facebook and Instagram), without create a "switch component".

**Comment by blocka** [comment]
You _can_ pass a function a long as a component. It just has to return a promise with a component

**Comment by alexandremagro** [comment]
Since my last comment, I had to develop based on the @LinusBorg example, but now I have a problem: When the user is logged in to my Home, and then exits, I can not redirect the user to the same route (and same component) because data is not initialized again: https://github.com/vuejs/vue-router/issues/1490.

What would be the solution this time?

**Comment by coopertim13** [comment]
Has a solution been found for this issue yet? I agree that while LinusBorg's approach may work, it feels like a workaround. Is there any way to do this strictly using vue-router?

**Comment by andredewaard** [comment]
Is there a way to do something like this:

```
const allowed = ref(false)

export const useAuthState = () => {
  const setAllowed = () => {
    allowed.value = !allowed.value
  }
  return {
    allowed,
    setAllowed
  }
}

const routes = [
  {
    path: '',
    name: 'Home',
    component: () => { 
      const { allowed } = useAuthState()
      if (allowed.value) {
        return import('../views/dashboard/benchmarks/Highlights.vue')
      } else {
        return import('../views/dashboard/partials/NotAllowed.vue')
      }
    },
    meta: { requiresAuth: true }
  }
]
```
