### ISSUE TITLE
just not render , no error shows

### ISSUE THREAD

**Issue by joe-lz** [vuejs/vue-router#761]
main.js

```
// The Vue build version to load with the `import` command
// (runtime-only or standalone) has been set in webpack.base.conf with an alias.
import Vue from 'vue'

// 路由VueRouter
import VueRouter from 'vue-router'
Vue.use(VueRouter)
// 1. 定义（路由）组件。
// 可以从其他文件 import 进来
import indexComponent from './pages/App'
import projectsComponent from './pages/projects'

const index = indexComponent
const projects = projectsComponent
// 2. 定义路由
// 每个路由应该映射一个组件。 其中"component" 可以是
// 通过 Vue.extend() 创建的组件构造器，
// 或者，只是一个组件配置对象。
// 我们晚点在讨论嵌套路由。
const routes = [
  { path: '/', component: index },
  { path: '/projects', component: projects }
]
// 3. 创建 router 实例，然后传 `routes` 配置
// 你还可以传别的配置参数, 不过先这么简单着吧。
const router = new VueRouter({
  routes // （缩写）相当于 routes: routes
})
// 4. 创建和挂载根实例。
// 记得要通过 router 配置参数注入路由，
// 从而让整个应用都有路由功能
/* eslint-disable no-new */
new Vue({
  router
}).$mount('#app')



```

**Comment by LinusBorg** [comment]
Hi  

Thanks for filing this issue! Could you please provide a small reporduction on jsfiddle.net so we can debug this without trying to replicate this ourselves?`

That would be very helpful, thanks!

**Comment by ragnarlotus** [comment]
Hello, it happened to me too. In the documentation just says to add the Vue.use(VueRouter) if using module system, but it is not enough. You will also have to do the following.

Replace:
`new Vue({
  router
}).$mount('#app')`
With:
`new Vue(Vue.util.extend({ router }, App)).$mount('#app');`

**Comment by posva** [comment]
@deulos Why would you extend the App instance?
It's much easier to do

``` js
new Vue({
  el: '#app',
  router,
  render: h => h(App)
})
```

**Comment by ragnarlotus** [comment]
Because it was the way I found to solve it. Yours works too and I like it more.

Would be great to include it in router docs, will happen to more people for sure.

Thank you for the correction!

**Comment by posva** [comment]
@deulos I'll check it tomorrow

**Comment by posva** [comment]
@jeodiong any news?

**Comment by joe-lz** [comment]
solved the problem by use app.vue as a root component, I thought app.vue could be a index  page

**Comment by HeyShinner** [comment]
@posva Thanks for you answer. I solved my problem. But I have a question about 'h'. What is it point for? Looking forward your reply...

**Comment by posva** [comment]
It's create element. Lookup the render section on the guide for more info

**Comment by coderunner-xinxin** [comment]
Got it...Thanks

**Comment by HeyShinner** [comment]
@posva Got it...Thanks

**Comment by renielsalvador** [comment]
Hi! I'm having same problem. 
My vue-router doesn't seem to work. 

the  <router-view></router-view> is just turning to 

Need help.

**Comment by posva** [comment]
You're probably going to a route that is not defined 🙂 
Please, use the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions
