### ISSUE TITLE
home link always stays active

### ISSUE THREAD

**Issue by Lahori-Jawan** [vuejs/vue-router#762]
I was using `**router-link-active**` class to highlight the active link in menu but even when other links are clicked, the home link with newly clicked menu link ,both, show active state. So i just hurried to [official example](http://jsfiddle.net/yyx990803/xgrjzsup/) and **[updated](http://jsfiddle.net/xgrjzsup/139/)** the `path: '/foo'`  to `path: '/'` and noticed the same problem. Active state works fine with other route paths i.e. '/home', '/foo', '/user' but always remains active for path: '/' even when it is inactive

![bug](https://cloud.githubusercontent.com/assets/7579344/19308135/7f14f5f2-9097-11e6-87cd-4f866d7cc396.PNG)

**Comment by LinusBorg** [comment]
http://router.vuejs.org/en/api/router-link.html

Read about the `exact` option.

**Comment by KoMiToRaY** [comment]
this fix it
```
<!-- this link will only be active at / -->
<router-link to="/" exact>
```
