### ISSUE TITLE
  beforeRouteLeave not trigged when used in a sub-component

### ISSUE THREAD

**Issue by psi-4ward** [vuejs/vue-router#764]
Hi,
I have 

```
<component-with-route>
  <sub-component>
```

The `beforeRouteLeave` guard in the SubComponent never fires. 
Bug? Or do I anything wrong? Or simply missing feature?

Thanks!

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a live example on jsfiddle, codepen etc. Thanks!

**Comment by psi-4ward** [comment]
Of course, sorry :)

http://jsfiddle.net/uy9a8bg9/1/

So you see in SubComponent:

```
  beforeRouteLeave(to, from, next) {
     alert('prevent route change');
     next(false);
  }
```

But you can navigate away

**Comment by fnlctrl** [comment]
`beforeRouteLeave` must be defined on the component that is mapped to a path (inside `routes` option). So, in your case, just define it on `Foo`.

**Comment by psi-4ward** [comment]
Ah, that was my Question/Problem.
Should I prepare a pull to the docs with note for that?

**Comment by fnlctrl** [comment]
Thanks, but it's not really necessary since the docs didn't directly note nor imply such usage, besides, it did state

`Finally, you can directly define route navigation guards inside **route components** with beforeRouteEnter and beforeRouteLeave:` 
where `route components` refers to those you put inside `routes`.

So I thinks we can just keep the docs that way.

**Comment by psi-4ward** [comment]
Okay I agree, a close enough look clears it.

Thanks!

**Comment by icehazard** [comment]
Try :key="$route.fullPath" on the parent <router-view> and on the child <router-view>

**Comment by AwaisSikander** [comment]
I want to add something 
In routes.js 
For routes hooks to work component should not be imported as lazyLoadView
BAD for router hooks
{
        path: 'salary-notifications',
        name: 'salary-notifications',
        component: () =>
            lazyLoadView(
                import('@views/settings/notifications-settings/salaryNotifications.vue'),
            ),
},
Good For Router hooks

 {
        path: 'theme-settings',
        name: 'theme-settings',
        component: () => import('@views/settings/theme-settings/theme-settings.vue'),
},

**Comment by Elrinth** [comment]
I can confirm in sub-component the beforeRouteLeave does indeed NEVER fire.

my setup is like this:
App.Vue -> /layouts/default.vue -> pages/admin/Create.vue -> components/admin/Create.vue

From pages the function is INDEED called.
From components the function is NEVER called.

**Comment by c0c4i** [comment]
Why is this issue closed? I have the same problem of @Elrinth 
Is there new updates?

**Comment by Valigion** [comment]
the way i got beforeRouteLeave working is when i navigated from /Page/id <- id as a parameter to /Home.
it fired and was able to pass the parameter that way.

**Comment by negartarh** [comment]
I have the same problem of @Elrinth
