### ISSUE TITLE
open link in new tab?

### ISSUE THREAD

**Issue by TangJiong** [vuejs/vue-router#768]

**Comment by TangJiong** [comment]
can vue-router open link in new tab progammaticaly

**Comment by robinlambert** [comment]
I don't know if I should create a new issue for that, but with vue-router 2.0.1, when you right click on a link and click "Open in a new tab", the url is missing the "#" and so it leads to a 404. Same when you do a CMD+Click on a link.

**Comment by LinusBorg** [comment]
@TangJiong 

> can vue-router open link in new tab progammaticaly

No. use a normal link.

@robinlambert Yes, please open a new issue, and include a reproduction so we can test exactly what you did.

**Comment by propardhu** [comment]
> can vue-router open link in new tab progammaticaly

Same issue,
If it is Done,Can you please Help me

**Comment by posva** [comment]
Use target=_blank
