### ISSUE TITLE
Using a component name in a route definition

### ISSUE THREAD

**Issue by JosephSilber** [vuejs/vue-router#77]
Up until very recently, you were to be able to use the name of a global component as a route:

```js
router.on('/path', { component: 'some-global-component' });
```

But it's now been broken. [`guardComponent`](https://github.com/vuejs/vue-router/blob/dev/src/router/internal.js#L245) just sets it to `null`. It [used to check for a string first](https://github.com/vuejs/vue-router/blob/5257f5d31d8f975ba5886297c0d9c84a400d1149/src/router/internal.js#L243).

I now get this error:

> [vue-router] invalid component for route "undefined"

**Comment by yyx990803** [comment]
I've decided to remove that functionality. You now always need to pass in the actual component (options or constructor).

For global ones you can just do `{ component: Vue.component('some-global-component') }`

**Comment by JosephSilber** [comment]
That did the trick. Thanks. Sorry for bugging you :heart:

**Comment by SalathielGenese** [comment]
Getting `undefined` on Repl.it
I had to use `var` in global scope :(
