### ISSUE TITLE
Clicking link of already active route does not trigger anything

### ISSUE THREAD

**Issue by rightaway** [vuejs/vue-router#770]
If I'm in a route '/login' and click a `router-link` corresponding to /login, nothing happens. Some behavior in the apps (clearing flash messages, etc), depend on it working like this, similar to how clicking links in regular non-JS pages works, where it reloads everything. I'd like it to trigger all transitions (as asked in https://github.com/vuejs/vue-router/issues/723#issuecomment-251678829) and hooks.

In that issue, `canReuse` is mentioned, but it was deprecated in 2.0. I also saw something about using watch (https://github.com/vuejs/vue-router/blob/next/examples/data-fetching/Post.vue#L31-L36), but this doesn't work for me. Probably because `$route` isn't actually changing, so maybe it wouldn't trigger the watch.

**Comment by fnlctrl** [comment]
>  similar to how clicking links in regular non-JS pages works, where it reloads everything.

Since you're using vue + vue-router (instead of just vue),

> Some behavior in the apps (clearing flash messages, etc), depend on it working like this

You can no longer depend on such behavior. 

Simply use a on-click handler to call functions/trigger transitions etc.
