### ISSUE TITLE
get active state of router-link using javascript

### ISSUE THREAD

**Issue by aplr** [vuejs/vue-router#774]
Hello,

I need to know if a `<router-link>`-component is active using javascript to programmatically trigger animations on sub-elements. As I have seen in the code of the component there's currently no way to get access to this value (or I missed it).

Is it possible to implement an `@activechange`-event or something else, which will make this possible, so one does not need to copy/implement the whole matching-logic himself again?

Regards,
Andreas

**Comment by fnlctrl** [comment]
http://router.vuejs.org/en/api/router-instance.html

> router.currentRoute
