### ISSUE TITLE
How can i parse GET parameter ?

### ISSUE THREAD

**Issue by CihanAksoy** [vuejs/vue-router#775]
For example link : test.com/news?id=19

How can i parse id parameter in Vuejs ?

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only, so please use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions. Thanks!

http://router.vuejs.org/en/essentials/dynamic-matching.html
