### ISSUE TITLE
[2.0] Waring about named route with default child route not showing in non-minified build

### ISSUE THREAD

**Issue by Jesseyx** [vuejs/vue-router#777]
When i use `<router-link :to="{ name: 'home' }">/home</router-link>`, i can't get the correct results. [See](https://jsfiddle.net/Jesseyx/1hxmbbL2/).

But  `<router-link to="/home">/home</router-link>` is right. [See](https://jsfiddle.net/Jesseyx/46aphe1h/)

When use router.push, the result is same as the first case.

Please help me, thanks.

**Comment by LinusBorg** [comment]
You _should_ be seeing a warning about this, but appearntly there's a problem with that. I will check that out.

The warning _does_ appear when you use e.g. the vue-cli webpack template and have run `npm run dev`

The warning would read:

```
Named Route 'home' has a default child route.
When navigating to this named route (:to="{name: 'home'"), the default child route will not be rendered.
Remove the name from this route and use the name of the default child route for named links instead.`
```

Which esseantially means your route config should look like this:

``` js
const router = new VueRouter({
  routes: [
    { path: '/home', component: resolve => resolve(Home),
      children: [
        { path: '', name: 'home', component: resolve => resolve(Welcome) },
        { path: 'welcome', name: 'welcome', component: resolve => resolve(Welcome) },
      ]
    }
  ]
})
```

Sorry for the inconvenience, will see how to fix that the non-minified release does show the warning in the future, but it apüpears that warnings in this build are not shown generally.

**Comment by Jesseyx** [comment]
Ok, i get it, thanks.

**Comment by coderabsolute** [comment]
Am getting this error appeared on my app. Am using vue-router `2.6.0`, is this fixed?

**Comment by LinusBorg** [comment]
The error is telling you what to do, just follow the instructions.

**Comment by roger-russel** [comment]
Someone should put it into docs https://router.vuejs.org/en/essentials/nested-routes.html

**Comment by rublev** [comment]
I got this working:

```
routes: [
		{
			path: '/',
			redirect: '/dashboard',
			meta: { requiresAuth: true }
		},
		{
			path: '/dashboard',
			component: () => import(/* webpackChunkName: "DashboardContainer" */ './containers/DashboardContainer/DashboardContainer.vue'),
			meta: { requiresAuth: true },
			children: [
				{
					path: 'data',
					component: () => import(/* webpackChunkName: "Data" */ './views/Data/Data.vue'),
					children: [
						{
							path: 'sources',
							component: () => import(/* webpackChunkName: "Sources" */ './views/Data/Sources/Sources.vue'),
							meta: { pageTitle: 'Sources' },
						},
						{
							path: 'new-source',
							component: () => import(/* webpackChunkName: "NewSource" */ './views/Data/NewSource/NewSource.vue'),
							meta: { pageTitle: 'New Source' },
						},
						{
							path: 'new-offer',
							component: () => import(/* webpackChunkName: "NewOffer" */ './views/Data/NewOffer/NewOffer.vue'),
							meta: { pageTitle: 'New Offer' },
						},
						{
							path: '',
							redirect: '/dashboard/data/sources',
						},
						{
							path: '*',
							redirect: '/dashboard/data/sources',
						},
					]
				},
				{
					path: '/',
					redirect: '/dashboard/data/sources',
				},
				{
					path: '*',
					redirect: '/dashboard/data/sources',
				},
			]
		},
]
```

**Comment by tonilam** [comment]
Just remove the name attribute from the parent route fixed the warning. What the warning telling you is that you got the parent with a named-route, if you route to somewhere by name, and the destination is the parent route, as we don't know the name of the child, the child will not be rendered. Simple.
