### ISSUE TITLE
Navigate link on custom events

### ISSUE THREAD

**Issue by AdamNiederer** [vuejs/vue-router#785]
Hi there,

I'd love to have my `router-link` components be activated on a `mousedown` event, but it looks like the component is hard-coded to only navigate on a `click` event. Adding a property to activate the link on a custom event would be awesome.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.
That's a relatively rare use case, so I don't know if people really need it.
But for now, you can simply do:

``` html
<router-link @mousedown.prevent.native="$router.push(...the path...)"></router-link>
```
