### ISSUE TITLE
Bower+Webpack support

### ISSUE THREAD

**Issue by holmescn** [vuejs/vue-router#79]
Please remove the ignore of **src** and **examples** from bower.json, because we need the **src** to pack using webpack, the dist file is already packed which is not convenient for webpack to analyze. The **example** is the docs which is lack now.

**Comment by yyx990803** [comment]
I can include the src folder, but if you are using webpack, you should prefer [installing via npm](http://webpack.github.io/docs/usage-with-bower.html#prefer-modules-from-npm-over-bower).

Example should not be included in the package, you have to run it by cloning the repo and installing all the dependencies anyway.
