### ISSUE TITLE
router-link when i change data the view link is not change

### ISSUE THREAD

**Issue by JJL-SH** [vuejs/vue-router#792]
Data is array repeat 10
v-for="item in datas"
`<router-link :to="{name: 'userRegisterInfo', params:{id: item.id}}" tag="li"><a>用户详情</a></router-link>`

when i change data like this
`[{id:1},{id:2},{id:3}]  => [{id:11},{id:22},{id:33}]`
the view page link is not change!
why?（my english is not very better! sorry~~）

**Comment by JJL-SH** [comment]
I find a method~
when i change data
set data is a empty array and create setTimeout to set new data！
it is success working

**Comment by fnlctrl** [comment]
> when i change data like this
> [{id:1},{id:2},{id:3}] => [{id:11},{id:22},{id:33}]
> the view page link is not change!

It should have. If not, please provide a repro on jsfiddle/codepen etc. and open a new issue, thanks!
