### ISSUE TITLE
Official "Getting Started" does not work in "runtime-only" build

### ISSUE THREAD

**Issue by nivekz** [vuejs/vue-router#794]
- `vue-cli` version: 2.4.0
- `vue-router` version: 2.0.1
- `vue version` version: 2.0.3

I created a project through `vue init webpack` and chose `runtime` for question `Vue comes in two build versions, which do you want to use?`. The example at http://router.vuejs.org/en/essentials/getting-started.html does not work but gives the following warning at console:

```
[Vue warn]: Failed to mount component: template or render function not defined. 
(found in root instance)
```

Choosing `standalone` build version seems to fix the problem.

**Comment by nivekz** [comment]
This may be related: http://vuejs.org/guide/installation.html#Standalone-vs-Runtime-only-Build

**Comment by posva** [comment]
Thanks for your interest! This is working as intended.
The runtime build cannot parse templates outside of `vue` files
We're making this clearer in the cli and making the standalone version the default

Edit: here's the PR: https://github.com/vuejs-templates/webpack/pull/321
