### ISSUE TITLE
Runtime build support

### ISSUE THREAD

**Issue by dabowheel** [vuejs/vue-router#796]
There are two types of Vue builds. One is the standalone and the other is the runtime.  Unless I'm mistake vue-router doesn't support the runtime build.

As far as I can tell, none of the examples use the runtime render function.

I tried using vue-router with the runtime build and [the DOM was blank](http://forum.vuejs.org/t/vue-router-all-i-get-is-an-empty-comment-in-dom-where-the-router-view-tag-was/1568) where the page was suppose to be rendered.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.
Vue-router supports runtime-build, it's using in-dom template that's not supported by runtime-build. We're sorry for any misleading information in the docs or examples, and we're currently fixing them. Thank you for you patience.
