### ISSUE TITLE
Deferred long-running timer task(s) to improve scrolling smoothness. See crbug.com/574343.

### ISSUE THREAD

**Issue by sssaaa123** [vuejs/vue-router#799]
vue@2.0.3
vue-router@2.0.1
it mostly only occur when run in chrome's **device mode** .
using `router.beforeEach` will more frequently.

related: [https://segmentfault.com/a/1190000006053354](https://segmentfault.com/a/1190000006053354)

![image](https://cloud.githubusercontent.com/assets/3761867/19461722/beba6918-9519-11e6-91a3-087b2a96ed21.png) 

![image](https://cloud.githubusercontent.com/assets/3761867/19461764/162bedac-951a-11e6-947e-d76dffd2952e.png) 

![image](https://cloud.githubusercontent.com/assets/3761867/19461780/2996bc78-951a-11e6-9b12-1649bb7fe181.png)

**Comment by posva** [comment]
Can you explain what is the issue, please?

**Comment by sssaaa123** [comment]
actually everything is work, but the console print this message when switch hash:
Deferred long-running timer task(s) to improve scrolling smoothness. See crbug.com/574343.

**Comment by posva** [comment]
It looks to me nothing can de done by vue-router to improve this. Please tell me if there's something we can do and tell me what 😅 
Closing until then
