### ISSUE TITLE
Uncaught TypeError: Cannot read property 'entry**deep**' of null

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vue-router#8]
Moved from yyx990803/vue#864

> https://github.com/yyx990803/vue/blob/dev/src/api/data.js#L74

> I'll attempt to reproduce this in a JSFiddle, but this happens when navigation (with vue-router) before I'm able to load external data (entry) into the VM. The same component had a deep watcher set up on entry, then entry is unset before trying to load a new entry (caused by navigation).

**Comment by holic** [comment]
This should be resolved by the implementation of a `data` option to load async data on route changes.

**Comment by yyx990803** [comment]
Closing as part of #7
