### ISSUE TITLE
[2.0]change params can't reload component

### ISSUE THREAD

**Issue by zjlzlr** [vuejs/vue-router#801]
http://localhost:8080/#/person_census/1/78
http://localhost:8080/#/person_census/1/7
when I change router like this,use  the same component, then the url changed but the component can't reload again and can't load the new data

code below:
`this.$router.push({name: router, params:{timetype:this.timeType, userid:this.userid}});`

router:

```
{   path: '/person_census/:timetype/:userid',
   name: 'person_census', 
  component: require('./views/person_census.vue'),
}
```

**Comment by fnlctrl** [comment]
http://router.vuejs.org/en/essentials/dynamic-matching.html#reacting-to-params-changes
