### ISSUE TITLE
[2.0]transition didn't work between same component change

### ISSUE THREAD

**Issue by Elric-pp** [vuejs/vue-router#802]
Vue.js version

2.0.2

Reproduction Link

https://jsfiddle.net/elrichxu/5b5mhzpb/

Steps to reproduce

click router-link between root a b can not see transitions, but click c will see the transition
What is Expected?

when route change, transition will fire

**Comment by LinusBorg** [comment]
Use the [key attribute](http://vuejs.org/api/#key)

https://jsfiddle.net/5b5mhzpb/7/

They key can be anything, you don'T have to use a meta prop or anything from $route, it just has to be different for each route.
