### ISSUE TITLE
Alias on nested routes

### ISSUE THREAD

**Issue by nicolas-t** [vuejs/vue-router#803]
Hi,

How can I use an empty alias on a nested route?
I think it'll be clearer with an example : 
https://jsfiddle.net/p7uk1pbv/1/

when I click `/user/foo` I want to display the profile (`UserProfile` component)

also, is there a way not to add `.router-link-active` to parent route links ?

Thanks

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only, so please use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions. Thanks!
