### ISSUE TITLE
[2.0] <router-view> does not support v-for and dynamic name

### ISSUE THREAD

**Issue by niceue** [vuejs/vue-router#804]
``` html
<template>
<div>
    <router-view v-for="name in views" :name="name"></router-view>
</div>
</template>

<script>
export default {
    data () {
        return {
            views: ['default', 'page1', 'page2', 'page3']
        }
    }
}
</script>
```

New example is here:
https://jsfiddle.net/6n7jtnr3/3/

**Comment by LinusBorg** [comment]
What exactly do you expect to happen in this fiddle that is not happening?
1. there are no errors
2. clicking on the links renders the right components.
3. as you only defined one default comonent per route, there's no use for multiple router-view element anyway.

If you actually define more than one component per route, the expected result is: more than one component is rendered:

https://jsfiddle.net/Linusborg/6n7jtnr3/1/

**Comment by niceue** [comment]
@LinusBorg @yyx990803 
Thanks for the answer, the new example is here:  https://jsfiddle.net/6n7jtnr3/3/

Here are my needs:  
1. I want to keep multiple views on a single page.
2. The views can be switched and closed.
3. Clicking a link will create a new view if it does not exist.

**Comment by fnlctrl** [comment]
> 1. Clicking a link will create a new view if it does not exist. 

This is not possible.
