### ISSUE TITLE
can't add  alias: '' to s child route (to make it behave like a default route.

### ISSUE THREAD

**Issue by LinusBorg** [vuejs/vue-router#805]
Repro: https://jsfiddle.net/p7uk1pbv/1/

The other way around works: https://jsfiddle.net/p7uk1pbv/2/

Cause: https://github.com/vuejs/vue-router/blob/dev/src/create-route-map.js#L62

**Comment by nicolas-t** [comment]
initial message https://github.com/vuejs/vue-router/issues/803

**Comment by LinusBorg** [comment]
PR submitted.
