### ISSUE TITLE
[2.0]History model，refresh browser Nested Routes has error

### ISSUE THREAD

**Issue by oooowl** [vuejs/vue-router#808]
vue-router 2.0
in History model，
Nested Routes like 'www.demo.com/id/info'
`path: '/id',
            component: component1,
            children: [
                {
                    path: 'info',
                    component: component2 ,
                }
            ]`
refresh browser cannot worked
but set alias use 'www.demo.com/info' can work
`path: '/id',
            component: component1,
            children: [
                {
                    path: 'info',
                    component: component2 ,
                },
                    alias: '/info'
            ]`

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a live reproduction on jsfiddle, codepen etc. Thanks!

**Comment by yiling-e0** [comment]
http://jsfiddle.net/L7hscd8h/92/
but need to open in new window because router is  history model
at ‘user/info’ and refresh will throw error
‘/info’ and refresh will be normal

**Comment by LinusBorg** [comment]
Hm, a jsfiddle does not help here as we can't open a new widow from links in there.

**Comment by erbing** [comment]
@yiling-e0 I have the same problem, do you solve?

**Comment by erbing** [comment]
`{
        path: '/use',
        component: Use
    },
    {
        path: '/use/start',
        component: UseStart,
        children: [
            { path: '', component: Index },
            { path: 'install', component: UseBase }
        ]
    }`

My primary route is effective, but my secondary routing or tertiary routing is invalid

**Comment by oooowl** [comment]
im forget , remember is edited '.htaccess' file.

**Comment by erbing** [comment]
@yiling-e0  Ok, I has been solved . because vue-router 1.x and  2.x are very different.
