### ISSUE TITLE
path error 

### ISSUE THREAD

**Issue by wormen** [vuejs/vue-router#81]
Information on the screenshot
https://yadi.sk/i/BTHZiFgniX4te

**Comment by yyx990803** [comment]
Did you see the warning? It means you are using `v-link` but the app does not have an associated router.

**Comment by wormen** [comment]
yes seen
there the code looks exactly the same as in this example, but here there is no warning

```
<div id="app">
  <h1>Hello App!</h1>
  <p>
    <!-- use v-link directive for navigation. -->
    <a v-link="/foo">Go to Foo</a>
    <a v-link="/bar">Go to Bar</a>
  </p>
  <!-- route outlet -->
  <router-view></router-view>
</div>
```

**Comment by yyx990803** [comment]
Did you start your app via the router? `router.start(App, el)`

**Comment by wormen** [comment]
yes

**Comment by wormen** [comment]
Here is my code

```
Vue.use(VueRouter);

var router = new VueRouter({
    history: true
});

var App = Vue.extend();

router.redirect({
    '/': '/main'
});

router.map({
    '*': {
        component: notFound
    },
    '/main': {
        component: {
            template: 'main page'
        }
    },
    '/domains': {
        component: {
            template: 'domains page'
        }
    },
    '/setting': {
        component: {
            template: 'setting page'
        }
    }
});

router.start(App, '#app');
```

**Comment by yyx990803** [comment]
Hmm, not sure what exactly is wrong. You'll have to reproduce this for me, maybe in a jsfiddle: http://jsfiddle.net/yyx990803/xyu276sa/

**Comment by wormen** [comment]
structure code are all exactly the same

**Comment by yyx990803** [comment]
Then make sure you are using the latest files?

**Comment by wormen** [comment]
I took an example from your site, all that has changed, it routes and links, the rest is left

**Comment by wormen** [comment]
Yes, I have just updated all, before the advent of the error

**Comment by yyx990803** [comment]
I can't help you if you don't provide a reproduction.

**Comment by wormen** [comment]
you can see here on the prepared project, I think this will be enough
http://srv.x-sells.com:8098/

**Comment by yyx990803** [comment]
But it's not throwing the error you original posted?

**Comment by yyx990803** [comment]
Also you shouldn't be overwriting `Vue.config`.

**Comment by wormen** [comment]
... Not all the code was unloaded earlier ....
now everything as it should be, with an error

**Comment by yyx990803** [comment]
You are using `Vue.component` wrong. Make sure to read http://vuejs.org/guide/components.html - `Vue.component` only registers the component but returns Vue itself. If you want to return the created component you should use `Vue.extend`.

**Comment by wormen** [comment]
@yyx990803 Set an example, which is more detailed than
http://vuejs.github.io/vue-router/basic.html
