### ISSUE TITLE
在hybrid app中，单页应用需要的一些功能。

### ISSUE THREAD

**Issue by nothinggift** [vuejs/vue-router#812]
其实并不只是在hybrid app里，即使web app也常常会需要这些功能。
1. 保存在应用中所有的跳转历史。因为在app中常常需要关闭其中的一些特定页面，而原生的history对象，无法做到这一点。本人尝试在**beforeEach**钩子中记录下这些信息，然后发现在钩子里无法区分新页面是replace还是push。
2. keep alive 的路由组件，在页面回退时，清除掉缓存。

为了解决这两个问题，我重写了vue cli的基础模版，来支持多页面应用，最终使用原生的web view解决了。

vue真的很好用，我们新的前端项目都在使用，希望能够支持这两点，谢谢。

**Comment by fnlctrl** [comment]
1. 我不知道你为什么需要区分replace和push，这不是一个常见的需求，否则手动用beforeEach记录或者用vuex-router-sync就足够了。如果你一定需要区分replace和push的话，建议自己fork一份vue-router在replace/push方法上加钩子。
2. 清除keep-alive的缓存目前可以通过这个方法:

```
<keep-alive v-if="foo">
  <router-view></router-view>
</keep-alive>
```

在keep-alive上加v-if。平时恒为true，需要清缓存的时候改成false，再在nextTick再改回true。这样会清除所有的缓存。

未来的计划里keep-alive会支持更细粒度的操作。(https://github.com/vuejs/vue/projects/3#card-487045)

**Comment by nothinggift** [comment]
1. 举个例子，在web app中回到首页，往往是一个指向首页的链接。在hybrid app中回到首页，则是将首页之外打开的webview都关闭。在单页应用里要实现相同的效果，例如：返回首页，就需要找到首页在 history中的位置，这就需要维护一个已打开页面的列表，而push和replace自然就需要区分。
2. 这种粒度的操作着实意义不大，希望有动态的清除特定组件缓存的方法。

**Comment by fnlctrl** [comment]
> 在hybrid app中回到首页，则是将首页之外打开的webview都关闭。在单页应用里要实现相同的效果，例如：返回首页

为什么不直接replace回首页？这和你需要实现的效果有什么区别？

> 这就需要维护一个已打开页面的列表，而push和replace自然就需要区分

为什么自然需要区分？

> 希望有动态的清除特定组件缓存的方法

细粒度的操作指的就是这一类操作。

**Comment by nothinggift** [comment]
> 为什么不直接replace回首页？这和你需要实现的效果有什么区别？

在后退按钮的表现上存在不同。

> 为什么自然需要区分？

因为push和replace对history的影响不同

> 细粒度的操作指的就是这一类操作。

了解

**Comment by fnlctrl** [comment]
如果只是需要回到首页的话，你可以在第一次进入首页的时候记录`let n = history.length`。然后之后任何时刻需要回到首页，就`history.go(n - history.length)`，不需要自己记录history栈的。

**Comment by nothinggift** [comment]
首页只是举个容易理解的例子，实际情况可能是这样的：
A->....->G->H->I**->G**

ps：如一开始所说，这并不是hybrid app独有的问题，在web app中，应用的history也往往是非常混乱的，这导致后退这个操作非常不可靠，常常违反我们的使用直觉。

**Comment by fnlctrl** [comment]
这个问题没有办法解决的，因为浏览器不允许你从原生histroy栈中删除，就一定会有重复的项目。没有一个框架的路由能帮你解决这个问题。最简单的做法就是能用replace的地方都用replace。

**Comment by nothinggift** [comment]
至少有两种方式可以实现类似效果，两种方法都需要维护history记录：
1. 在页面跳转时，从history中查询是目标页面是否已打开，如果是，查询目标页面距当前页的步数，然后后退到目标页。
2. 所有页面跳转均使用replace，然后监听后退键，在后退按键点击时，从history中查询上一页地址并跳转。

第一种方法适用性好些，目前项目中采用该方式，第二种方法仅适用于手机设备上，因为在浏览器里，后退按钮可能显示为不可用状态。

**Comment by fnlctrl** [comment]
> 1. 在页面跳转时，从history中查询是目标页面是否已打开，如果是，查询目标页面距当前页的步数，然后后退到目标页。

那只需要维护一个下标为历史记录序数，值为path的数组就可以了，不需要区分push和replace。

简陋实现：

``` js
const historyPaths = []
router.beforeEach(to, from, next) {
  let i = historyPaths.indexOf(to.path);
  if (i > -1) {
    router.go(i - window.history.length)    
  } else {
   historyPaths[window.history.length] = to.path
   next()
  }
}
```

**Comment by nothinggift** [comment]
> 那只需要维护一个下标为历史记录序数，值为path的数组就可以了，不需要区分push和replace。
1. **window.history.length**在页面后退时，不会自减
2. 要判断页面是否存在，需要同时判断**path**和**params**

**Comment by fnlctrl** [comment]
> window.history.length在页面后退时，不会自减

浏览器本来就没有提供history的删除操作，这跟你区分不区分push/replace没有关系

> 要判断页面是否存在，需要同时判断path和params

我的例子里用的是to.path不是to.fullPath，是不带params/hash的。
要处理params/hash也很简单

``` js
router.beforeEach((to, from, next) {
  let i = historyPaths.indexOf(to.path);
  if (i > -1) {
    router.go(i - window.history.length)
    // apply params/hash
    router.replace(to)
  } else {
   historyPaths[window.history.length] = to.path
   next()
  }
})
```

**Comment by nothinggift** [comment]
事实上，这里有两个我尚未完全验证的错误
1. `<router-link replace></router-link>`仍然会使window.history.length++
2. hash模式，安卓4.3以下，A-(push)->B-(replace)->C-(push)->B,最后一个push仍会被当作replace处理

**Comment by yeomanyang** [comment]
@fnlctrl 请问现在有办法支持更细粒度的操作keep-alive缓存么？比如可以手动把A组件的缓存先清掉，但是A还是要继续在keep-alive状态。
