### ISSUE TITLE
Using the same route name and/or path multiple times should throw an error

### ISSUE THREAD

**Issue by wszgxa** [vuejs/vue-router#828]
i find that the same route name and path don't throw an error when compile them.
just like：

``` js
'/test': {
    name: 'test',
    component: testa
  },
  '/test-2': {
    name: 'test',
    component: testb
  },
```

if  preson a write a name same as b, and a don't find anything wrong,then a push to server.And then b's page will not work.

it's find in 0.7.13.

**Comment by posva** [comment]
I edited your code and changed test by test-2 so it's valid js.
This is something that should be enabled on non-production mode only
