### ISSUE TITLE
several components in the route

### ISSUE THREAD

**Issue by wormen** [vuejs/vue-router#83]
tell me how best to specify multiple components in a certain route, for example

```
'/main': {
        components: {
            block1: blockComponent1,
            block2: blockComponent2,
            block3: blockComponent3
        }
    },
```

or is there any alternatives?

**Comment by yyx990803** [comment]
Just nest the child components inside that main component.

**Comment by mahmoudHosny** [comment]
Can I use named <router-view> and inject component at named view
EX:
<router-view name="a"></router-view>
<router-view name="b"></router-view>
