### ISSUE TITLE
Reverse URL resolving should be public method

### ISSUE THREAD

**Issue by hogart** [vuejs/vue-router#831]
"Reverse URL resolving" means "converting name and params to URL string".

Right now there's only `VueRouter#match` method, which is great, but it's not documented, doesn't take `base` and `mode` into account, and doesn't normalize relative urls, so it's not really an equivalent of what's going inside `<router-link>` `render` method. 

Rationale for making reverse URL resolving public is following:
- In isomorphic apps we may need to send some link via email, so we should be able to get this link as  text
- Several kind of apps, (e.g. google drive, bit.ly) require to provide link which can be copied by user
- Issues like #827 where `<router-link>` doesn't support some attribute will have simple work-arounds

**Comment by yyx990803** [comment]
resolved via merging #918
