### ISSUE TITLE
use the transition errors 

### ISSUE THREAD

**Issue by xierenyuan** [vuejs/vue-router#832]
hi,I met a problem when doing the router transition, can appear the following error when I routing switch.
![image](https://cloud.githubusercontent.com/assets/7599351/19682839/0aacb81c-9ae2-11e6-8227-7f5d57359693.png)
![image](https://cloud.githubusercontent.com/assets/7599351/19682852/193c6954-9ae2-11e6-95ef-935d07229ef8.png)
# vue version

vue 2.0 && vue-router 2.0 
# code

``` javascript
<style lang="scss">
    @import './scss/index.scss';
</style>
<template>
    <div>
        <rc-header></rc-header>
        <rc-nav></rc-nav>
        <div class="rc-content" v-setHeight>
            <transition name="fade" mode="out-in">
                <router-view></router-view>
            </transition>
        </div>
    </div>
</template>
<script>
    import rcHeader from './components/header.vue';
    import rcNav from './components/nav.vue';
    export default {
        name: 'app',
        components: {
            rcHeader,
            rcNav
        }
    };
</script>
```

  0.0 I try to? A number of ways or in error.I hope you can help me.please tell me if I didn't describe clearly, please forgive my English is not good. =￣ω￣=

**Comment by fnlctrl** [comment]
Do not manually remove dom nodes that are created by vue, they'll be be destroyed by vue after `beforeDestroy`.
