### ISSUE TITLE
求帮助：Failed to mount component: template or render function not defined. 

### ISSUE THREAD

**Issue by qdafeng** [vuejs/vue-router#833]
vue2.0+vue-router2建项目，根据官网改动 alias: { 'vue$': 'vue/dist/vue.js'}，报错：Failed to mount component: template or render function not defined. vue-loader用的是9.7.0，求大神们帮忙下，如何才能解决模板注册失败问题

**Comment by fnlctrl** [comment]
你好，请使用[论坛](http://forum.vuejs.org/)或[gitter](https://gitter.im/vuejs/vue)提问，issue列表只用于提交bug和feature request，谢谢！
