### ISSUE TITLE
Mode HTML5 history and Cordova

### ISSUE THREAD

**Issue by AnthonySendra** [vuejs/vue-router#836]
Hello,

I'm trying to build an app with Vue 2 and Vue Router 2 with the mode `history`. My application was init with [vue cli webpack](https://github.com/vuejs-templates/webpack) and in the browser everything works fine with `npm run dev`.

The problem is when I'm trying to build with `npm run build` and put the dist folder inside Cordova, the application is empty, with an empty body but CSS and JS are loaded correctly.
Plus, everything is ok when I configure the router mode to `hash`.

Any clue ? Thanks !

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only, so please use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions or for discussion. Thanks!
