### ISSUE TITLE
Vue router and named slot

### ISSUE THREAD

**Issue by stephanedemotte** [vuejs/vue-router#837]
Hi !

I can't have different slot in `router-view`

See [here](https://jsfiddle.net/de6zLctj/13/) for the reproduction.

If we remove line 6, the view router doesn't render the named slot.
I have missed something ? I have try to read the Vue & Vue-router doc, but nothing...

Thanks !

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. 
`<router-view>` doesn't support named slots, only default slot is available.
If you need named slots, you can try [named views](http://router.vuejs.org/en/essentials/named-views.html) instead.
