### ISSUE TITLE
route hooks

### ISSUE THREAD

**Issue by peterSa** [vuejs/vue-router#839]
I'm sure I'm doing something wrong, but I copied this from the docs and it just aint working.

```
export default{
    data(){
        return{
            msg:'hello vue'
        }
    },
    route: {
        // three options:
        // 1. return a boolean
        // 2. return a promise that resolves to a boolean
        // 3. explicitly call transition.next() or abort()
        canActivate(transition) {
            console.log('inbox canActivate?')
            if(!this.$store.state.user.id){
                this.$router.push('/login')
            }
            transition.next()
        }
    }
```

}

Can someone tell me what must I do to get canActivate to work?
I'm using vue 2.0.0 and vue-router 2.0.1

**Comment by fnlctrl** [comment]
These hooks are deprecated in 2.0. Please refer to the [migration guide](http://vuejs.org/guide/migration-vue-router.html) and [2.0 docs](router.vuejs.org/en/index.html).
