### ISSUE TITLE
Preserving state between route changes

### ISSUE THREAD

**Issue by holic** [vuejs/vue-router#84]
There are some cases where I'd like to preserve data between route changes so that hitting the back button restores the component with some/all of it's original state/data. How would I go about doing this?

**Comment by yyx990803** [comment]
Currently, `keep-alive` is not supported for router-views. However, you can store the state that you want to preserve into a store in a component's `deactivate` hook, and retrieve it in its `activate` hook.

**Comment by holic** [comment]
Resolved by https://github.com/vuejs/vue-router/commit/4fdbb703e56cdb8e9441fb7e320a0a97bdd88f1d?
