### ISSUE TITLE
it`s not work

### ISSUE THREAD

**Issue by calmchang** [vuejs/vue-router#840]
it`s report:   Error: Uncaught ReferenceError: age is not defined.

【html】  

<div id="viewApp">
  <router-view></router-view>
</div>

【js】
var routes = [
{ path: '/form1', component: {template:"<div>{{name}}</div>"}} ,
{ path: '/form2', component: {template:"<div>{{age}}</div>"}}
];
var router = new VueRouter({ routes});
var app = new Vue({
    el:'#viewApp',
    data:{
        name:'cx',
        age:12,
    },
    router,
});

**Comment by posva** [comment]
Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

The `age` variable is referring to the inline component. Take a look at the docs: https://vuejs.org/guide/ 😉
