### ISSUE TITLE
Inactive component can't switch to active

### ISSUE THREAD

**Issue by leaves4j** [vuejs/vue-router#841]
open `pageA`(lazy load pageA, it is active) => open `pageB`(lazy load PageB, pageB: active, pageA: inactive) =>reopen `PageA`(pageA: inactive, pageB: inactive);

There is no global guards, but if I push a function which throw an exception into after guards, it work well:

``` js
router.afterEach(route => {
  throw new Error('this is a funny issue');
});
```

it's doesn't work since I update vue-loader from 8.x to 9.x and vue-router from 2.0.0 to 2.0.1.

**Comment by fnlctrl** [comment]
Repro please

**Comment by leaves4j** [comment]
the same with #673

**Comment by fnlctrl** [comment]
That issue is only about webpack's lazy loading. Throwing an error inside application code may have triggered a reload a the module, but it has nothing to do with vue-router.
