### ISSUE TITLE
IE9 compatibility with #!

### ISSUE THREAD

**Issue by cheneyang** [vuejs/vue-router#844]
I use apache to drive all sources
path /opt/app/ is my root path
here are my two apps called dashboard (/opt/app/dashboard) and home(/opt/app/home) which all built by Vue
I get some error when browsering on IE9
localhost/home  will redirect to localhost/#!/home and show the apache directory page, so could anybody help me to disable the redirect or solve this problem?

**Comment by fnlctrl** [comment]
http://caniuse.com/#search=history
IE9 doesn't support history API and will force vue-router into using hash mode. There's no way around that.

**Comment by cheneyang** [comment]
that's to say Vue-router can not support IE9 ?

**Comment by posva** [comment]
@SeanCode No, you need to use the hash mode

**Comment by posva** [comment]
Vue-router does support IE9, you cannot use the history mode though, you have to use the hash mode

**Comment by cheneyang** [comment]
ok, thank you guys
