### ISSUE TITLE
 Unknown custom element: <router-view>

### ISSUE THREAD

**Issue by timaschew** [vuejs/vue-router#845]
I've migrated a project to vue 2, veux 2 and vue-router 2.
I read the docs before and also the migration guide, but I can't fix the erorr/warning: Actually the app is not rendered at all.

```
[Vue warn]: Unknown custom element: <router-view> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in component <App> at /Users/awilhelm/dev/CoPilot/src/components/App.vue)
```

I tried to set a name, but it didn't help. I also checked other solutions for this error in the web, but none helped me.

Here is my basic setup:

**main.js**

``` javascript
import Vue from 'vue'
import VueRouter from 'vue-router'
import routes from './routes'
import store from './store'
import AppView from './components/App.vue'

var router = new VueRouter({
  routes: routes,
  mode: 'history'
})

new Vue({
  el: '#root',
  router: router,
  store: store,
  render: h => h(AppView)
})
```

**store.js**

``` javascript
import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

const state = {/* */}
const mutations = {/* */}

export default new Vuex.Store({
  state,
  mutations
})
```

**routes.js**

``` javascript
const routes = [
  { path: '/login', component: LoginView}, 
  { path: '/', component: DashView, auth: true,
    children: [
      { path: '', component: DashboardView, name: 'Dashboard' }, 
      { path: '/tables', component: TablesView, name: 'Tables',
    ]
  }, 
  { path: '*', component: NotFoundView }
]

export default routes
```

**components/App.vue**

``` html
<template>
  <div>
    <router-view></router-view>
    <div id="app"></div>
  </div>
</template>

/* <script> omitted */
```

**components/Dash.vue**

``` html
<template>
  <div class="wrapper">
  <!-- stuff -->
    <!-- some where in the nested stuff  -->
      <router-view></router-view> <!-- only ONE occurrence  -->
  </div>
</template>

/* <script> omitted */
```

The whole code is public on github: https://github.com/timaschew/CoPilot
You can see [here my commit](https://github.com/timaschew/CoPilot/commit/93e95a2fbb9d14b145ab48c2a7a22a0cd4b6915c) where I tried to upgrade all the stuff

Here is the original code with vue 1: https://github.com/misterGF/CoPilot 
and a working demo: http://copilot.mistergf.io/

**Comment by fnlctrl** [comment]
You didn't call `Vue.use(VueRouter)`.
http://router.vuejs.org/en/installation.html

**Comment by timaschew** [comment]
Damn.
Thank you!

**Comment by ghost** [comment]
@fnlctrl Thanks, that also fixed my issue.

Do you know why the demo JSFiddle (http://jsfiddle.net/yyx990803/xgrjzsup/) gets away with not making that call?

**Comment by fnlctrl** [comment]
@ThePadawan 

> When used with a module system, you must explicitly install the router via Vue.use():
> ```js
> import Vue from 'vue'
> import VueRouter from 'vue-router'
>
> Vue.use(VueRouter)
> ```
> You don't need to do this when using global script tags.

http://router.vuejs.org/en/installation.html

When using global script tags (in browser), vue-router will automatically install itself, so as long as router's `<script>` is after vue's, you don't have to call `Vue.use(VueRouter)`

**Comment by ghost** [comment]
@fnlctrl Thanks, did not know that!

**Comment by milimetric** [comment]
I suggest making that a little clearer in the documentation, I think that's why this is tripping everybody up (small thing though)

**Comment by posva** [comment]
It's already there: https://router.vuejs.org/en/installation.html#npm

**Comment by tpraxl** [comment]
After falling into that pit, I noticed that it's also here: http://router.vuejs.org/en/essentials/getting-started.html

As a comment in source code

```
// 0. If using a module system (e.g. via vue-cli), import Vue and VueRouter and then call Vue.use(VueRouter).
```
I just didn't notice it. It would be helpful to make this more visible by placing it above the source snippet with a `<blockquote>`, just like the other tips ("We will be using ES2015", etc).

**Comment by TerryZ** [comment]
thx, fix my issues too

**Comment by dasDaniel** [comment]
also, though less likely to be the issue, watch the case of vue import

```js
import Vue from 'Vue'  // bad
import Vue from 'vue'  // good
```
This can result in the same error

**Comment by alexvkcr** [comment]
I get this same error but only with my first Jest tests.

import { shallowMount } from '@vue/test-utils'
import App from '@/App.vue'

describe('App.vue', () => {
  it('has the proper id', () => {
    const id = 'app'
    const wrapper = shallowMount(App)
    expect(wrapper.attributes().id).toContain(id)
  })
})


Anyone any idea?
This is the error
● Console

    console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
      [Vue warn]: Unknown custom element: <router-view> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
      
      found in
      
      ---> <App>
             <Root>

**Comment by Daniel-Gherard** [comment]
@alexvkcr, I've fixed that on my project by adding this:

import router from '@/router'

Vue.use(router)

to the test file.

**Comment by thiagobrunodev** [comment]
@alexvkcr 
> I get this same error but only with my first Jest tests.
> 
> import { shallowMount } from '@vue/test-utils'
> import App from '@/App.vue'
> 
> describe('App.vue', () => {
> it('has the proper id', () => {
> const id = 'app'
> const wrapper = shallowMount(App)
> expect(wrapper.attributes().id).toContain(id)
> })
> })
> 
> Anyone any idea?
> This is the error
> ● Console
> 
> ```
> console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
>   [Vue warn]: Unknown custom element: <router-view> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
>   
>   found in
>   
>   ---> <App>
>          <Root>
> ```

### [This guide](https://vue-test-utils.vuejs.org/guides/using-with-vue-router.html) shows how to use Jest with VueRouter.
```js
import { shallowMount, createLocalVue } from '@vue/test-utils'
import VueRouter from 'vue-router'

const localVue = createLocalVue()
localVue.use(VueRouter)
const router = new VueRouter()

shallowMount(Component, {
  localVue,
  router
})
```

**Comment by Korak-997** [comment]
I was having that Error also !
Thanks @fnlctrl , that also fixed my issue. :)
