### ISSUE TITLE
issues ????

### ISSUE THREAD

**Issue by matisha001** [vuejs/vue-router#846]
https://github.com/vuejs/vue-router/blob/1.0/docs/en/api/stop.md
when a router is in stopped state, router.app is not destroyed.However ,if you use router.go(path),as you can see,the navigate has changed,but the router can't work.

**Comment by fnlctrl** [comment]
Hi, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Thanks!
