### ISSUE TITLE
router-link-active class not assigned correctly

### ISSUE THREAD

**Issue by mineralwassermedium** [vuejs/vue-router#847]
### Vue.js version

2.0.3
### Vue-Router version

2.0.1
### Reproduction Link

https://jsfiddle.net/pr4suw3e/1/
### Steps to reproduce

Click on the link 'One Hundred' or 'Two Hundred'
### What is expected

Only the link 'One Hundred' or 'Two Hundred' has the class router-active-link 
### What is actually happening?

Also the link 'One' or 'Two' has the class router-active-link

**Comment by fnlctrl** [comment]
In your case please use `exact` mode for `router-link`.
https://jsfiddle.net/fnlCtrl/kt1cngjg/

http://router.vuejs.org/en/api/router-link.html

> The default active class matching behavior is inclusive match. For example, <router-link to="/a"> will get this class applied as long as the current path starts with /a.
