### ISSUE TITLE
vue-router多次切换组件后，样式冲突，感觉这样设计不合理

### ISSUE THREAD

**Issue by h330894169** [vuejs/vue-router#848]
我觉得这种点击一次就添加一个style这样的设计不太合理，如果点的多了，style越来越多，样式冲突的概率越来越大。虽然有scoped来控制，但是如果在.vue文件里面import和require的样式文件无法控制，依然会污染整个样式，如body...等。。
1.建议组件切换的时候，将style也删掉，
2.还有现在一个问题，.vue文件里面import和require的样式文件无法合并到一个css文件里面。

**Comment by fnlctrl** [comment]
这跟vue-router没有关系。请检查你自己的实现和配置。

**Comment by h330894169** [comment]
https://github.com/vuejs/vue-router/issues/529   @fnlctrl 
和这个问题是一样的。 请问怎么设置才能让之前组件的样式消失？而不冲突

**Comment by fnlctrl** [comment]
请检查webpack的extract-text-plugin配置和vue-loader配置，并更新到最新版。如果还有问题可以去[论坛](http://forum.vuejs.org/c/chinese)提问。
