### ISSUE TITLE
TypeError: redirect is not a function. Error in examples...

### ISSUE THREAD

**Issue by murbanowicz** [vuejs/vue-router#849]
Hi,

I am just building my own auth module based on vue-router examples.
https://github.com/vuejs/vue-router/blob/next/examples/auth-flow/app.js

I have router in separate file, so it is like that:

```
Vue.use(VueRouter)

function reqAuth (route, redirect, next) {
  if (!auth.authenticated()) {
    redirect({
      path: '/login'
    })
  }
  else {
    next()
  }
}

var router = new VueRouter({
  hashbang: false,
  mode: 'history',
  routes: [
    {
      path: '/',
      component: login
    },
```

and it does not work and throwing error: `TypeError: redirect is not a function`
What is wrong with that? Can't figure it out.

EDIT:
Throwing also error `next() is not a function`

**Comment by fnlctrl** [comment]
You're reading outdated examples. `next` branch is outdated, and the current branch is dev: https://github.com/vuejs/vue-router/blob/dev/examples/auth-flow/app.js

Please refer to the docs here: http://router.vuejs.org/en/advanced/navigation-guards.html
