### ISSUE TITLE
component rendering not waiting for data in beforeRouteEnter

### ISSUE THREAD

**Issue by lbineau** [vuejs/vue-router#855]
'beforeRouteEnter' seems to be the new 'activate' equivalent method but the component is rendered before data accessible.
Normally it should wait for next() call to render it ?
Look at the console there is an error and then the component is rerendered with data in the following example http://codepen.io/lbineau/pen/gwNqMa?editors=1010#0
I know it could be easily fixes with a v-if but the component should be rendered once next() is called, so it is a bug right ?

Thank you

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.
In order to be passed as `vm` inside the `next(vm => ....)`'s callback, the component must be created before calling `next()`, but it's rendering will be delayed until `next()` is called. So everything is working as intended.

**Comment by lbineau** [comment]
Thanks for the anwser but I still don't understand why I have the following error:

``` javascript
vue.min.js:6 Uncaught TypeError: Cannot read property 'title' of null(…)
```

It seems that the data are evaluated in the template (so rendered ?!) before the next() call if I understand the error message well.

**Comment by fnlctrl** [comment]
Since the vm is created before router renders it, it will try to access `content.title`, but `content` is null as you defined. 
You need to properly initialize it: 

```
data() {
    return {
      content: {title: ''}
    }
  },
```
