### ISSUE TITLE
在beforeEach中使用next(path)后，手动改变url中的hash或点击<a href="#/p1">这种形式的链接无法跳转

### ISSUE THREAD

**Issue by x531tanxl** [vuejs/vue-router#856]
重现url：https://jsfiddle.net/3ja5Lvb9/Lmf9yy0u/2/ ，点击 p1-hash 不生效，但url上的hash已经改变了。

通过调试源代码发现没有绑定hashchange事件。

vue版本：2.0.3，vue-router版本：2.0.1。

---

这种情况下这里绑定事件的回调未执行：
```javascript
this.transitionTo(getHash(), function () {
  window.addEventListener('hashchange', function () {
    this$1.onHashChange()
  })
})
```

**Comment by cycold** [comment]
这边也出现了同样的问题

**Comment by MrRoshan** [comment]
碰到了同样的问题，使用hash mode的时候，如果在beforeEach中next(path)优先于next()执行，导致页面回退、跳转无法正常执行，原因是window注册hashchange代码未执行

**Comment by yyx990803** [comment]
This is fixed as a side effect of merging #797 ;)
