### ISSUE TITLE
Bootstrap mobile navbar not collapsing

### ISSUE THREAD

**Issue by Zwaen91** [vuejs/vue-router#859]
When using the bootstrap collapsible menu for mobile sites the menu stays open when you go to another site. I'm sure the code should work.
    
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <router-link v-if="!user" to="/login" tag="li">
                        <a><i class="fa fa-login" aria-hidden="true"></i>Login</a>
                    </router-link>
                    <router-link v-if="!user" to="/register" tag="li">
                        <a><i class="fa fa-login" aria-hidden="true"></i>Register</a>
                    </router-link>
                </ul>
            </div>
        </div>
    </nav>

**Comment by fnlctrl** [comment]
Hi, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Thanks!

**Comment by Diferno** [comment]
Hi! I wonder why this has been closed. I have the same issue with Vuejs 2 and Bootstrap 3.3.6

**Comment by znck** [comment]
Provide minimal reproduction code using JSFiddle/JSBin/Codepen to demonstrate your issue. You could start with this [template](http://jsfiddle.net/df4Lnuw6/) that already includes the latest version of Vue.

Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. **The issue list only accepts bug reports and feature requests.** If you want to ask such question, please use our [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue).

Thanks.

**Comment by posva** [comment]
@Diferno It was closed because it wasn't following the Issue Reporting Guidelines. It's a question and should be posted on the Forum on SO

**Comment by dapobelieve** [comment]
so we dont get any answer to it??

**Comment by znck** [comment]
@dapobelieve You do get answer to it but Github issues is not the correct channel. Questions should be posted on the [forum](https://forum.vuejs.org).
