### ISSUE TITLE
Update docs basic usage section

### ISSUE THREAD

**Issue by ridewn** [vuejs/vue-router#86]
It'd be nice to have, in the 'Basic Usage' section of the docs, in the comments right before the routes are defined, something like:
```javascript
// Route component property's must receive an object.
```
Or something like that, so people know not to pass something like:
```javascript
'/foo': {
    component: 'foo'
}
```
into the property.

I noticed in this issue: https://github.com/vuejs/vue-router/issues/77 you said you deleted that functionality, but I don't know if you explicitly stated it anywhere aside from the ticket (unless I missed it somewhere).

Thanks!

**Comment by yyx990803** [comment]
Added. Yes, the string id functionality has been deleted.
