### ISSUE TITLE
keep-alive的路由组件在去除过渡效果后，点击会同样作用于目标页面

### ISSUE THREAD

**Issue by nothinggift** [vuejs/vue-router#860]
`<keep-alive>
          <router-view></router-view>
        </keep-alive>`
在第一个页面点击链接后，跳转到第二个页面，此时无异常
退回第一个页面后，再次点击同一链接，跳转到第三个页面，第三个页面的链接在第二个页面点击的同一位置

**Comment by fnlctrl** [comment]
请用jsfiddle/jsbin之类的工具给重现

**Comment by nothinggift** [comment]
请关闭这个问题，已经确认该问题的原因是一个插件将click模拟为tap动作时导致的
