### ISSUE TITLE
Doc TOC is broken

### ISSUE THREAD

**Issue by sfermigier** [vuejs/vue-router#861]
The TOC (left-hand navigation) on the doc seems incomplete:

<img width="1001" alt="screen shot 2016-11-02 at 13 21 24" src="https://cloud.githubusercontent.com/assets/271079/19928606/6a2190ec-a0ff-11e6-8782-202e055ee891.png">

**Comment by rpkilby** [comment]
You've entered 'html5' into the search, which is filtering the TOC.

**Comment by sfermigier** [comment]
:) 

Actually I didn't "enter" html5, I'm pretty sure I got there directly from Google, and it's a bit confusing that the search is persistent, and the search box doesn't look like a box at all.

Anyway, it's a bug for Getbook then. Closing.
