### ISSUE TITLE
problem with html5 history mode upon reload

### ISSUE THREAD

**Issue by snshn** [vuejs/vue-router#864]
### Vue.js version

vue@^2.0.1:
version "2.0.3"

vue-router@^2.0.0:
version "2.0.1"

### Reproduction Link

https://lyrics.github.io

### Steps to reproduce

Click on any letter on the top

Refresh the page

### What is Expected?

The items rendered with v-for should have text content

### What is actually happening?

Both the letters and the items on the top are empty (yet the DOM nodes are being created)

### How to fix

Go to the website's root, reload the page, then navigate the website using the same tab session without reloading it

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a reproduction repo on github. Thanks!

**Comment by snshn** [comment]
I think you can close this one, it was my mistake.
Github pages somehow removes the contents of `<router-link></router-link>` within the source on the server. Not a bug.
