### ISSUE TITLE
[Feature request] Auxiliary routes (i.e. many routes in a single url)

### ISSUE THREAD

**Issue by d-ph** [vuejs/vue-router#865]
Hello,

Would it be possible to add support for routing, that resembles Angular 2 auxiliary routes, please?

In short, auxiliary routes work like this. The following route: `www.lorem.com/#user/profile(aux1:tab1/point3//aux2:accordion3/foo/bar)` would route the `default`, `aux1` and `aux2` <router-view> to the following routes:

`<router-view></router-view>`: `user/profile`
`<router-view name="aux1"></router-view>`: `tab1/point3`
`<router-view name="aux2"></router-view>`: `accordion3/foo/bar`

This way those 3 `<router-view>`s can be navigated independently.

Vue-router already has a feature called "named views". The difference is, that those "named views" are navigated at the same time, whereas the auxiliary routes would be navigated independently.

More info about Angular 2 auxiliary routes here: https://yakovfain.com/2016/08/16/angular-2-working-with-auxiliary-routes/ 

Thanks.

**Comment by alexstanbury** [comment]
+1 This would certainly be a great feature to have.

**Comment by yyx990803** [comment]
I'm interested in a convincing use case for this feature. To me this feels like a feature that is quite complex yet only cater to a very niche use case.

**Comment by d-ph** [comment]
Hello Evan.

I can't come up with better use cases than the ones mentioned in the linked article.

I agree, that this feature is not of major importance. If you feel, that it'd introduce too much complexity compared to the benefits, then I'm ok with us closing this ticket and waiting for more people to express a need for this feature. In the meantime, I might do some research on my own to see how this could be implemented.

Thanks.

**Comment by dinfer** [comment]
How it's going?

named router-view maybe the most confusing feature in vue-router, in my opinion.
If there are two or more vue-router in a page, a disaster happens

```
<router-view></router-view>
<router-view name="aux"></router-view>

// routes:
...
..., components: { default: A, aux: X } // A & X
..., components: { default: B, aux: X } // B & X
..., components: { default: A, aux: Y } // A & Y
..., components: { default: B, aux: Y } // A & Y
...

// lines for maintain the current aux route and so on
```

If the router-view can only be nested, why do i need the named router-view? Why not use component directly? use `v-if` to make it behave like a router?

Please remove the named router-view feature. if you want to make vue-router clean and tidy. Or provide Auxiliary routes if you think named router-view is important.

**Comment by posva** [comment]
This hasn't received much attention and I don't find this feature necessary given named and nested routes in Vue Router. If someone thinks this idea is worth pursuing, please go through [the RFC process](https://github.com/vuejs/rfcs)
