### ISSUE TITLE
Go the same router with different params

### ISSUE THREAD

**Issue by petrelselina** [vuejs/vue-router#868]
If I use "router.push" to go to the same router view but with different params, it will trigger the global guard "router.beforeEach", but won't trigger the "beforeRouteEnter" guard of the vue component(the router view).
I try to migrate from 1.x, it work in old router-view with router guard, but didn't work with new guard event in 2.x.

**Comment by petrelselina** [comment]
by the way, I use keep-alive so I cannot do what I need in the created event, so i just have the "beforeRouteEnter" event to use.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. When you've entered a route, changing the params doesn't mean leaving it then re-entering it. It simply means staying on the route, but change some params.
The proper way to react to params change is to set a watcher on `$route`, please refer to the section here:
http://router.vuejs.org/en/advanced/data-fetching.html
