### ISSUE TITLE
v-link:name

### ISSUE THREAD

**Issue by guojianlan** [vuejs/vue-router#870]
v-link="{name:'index'}"
router.map({
'/index': {
        showNav: false,
        name:'index2',
        component: function (resolve) {
            require(['xxx'], resolve)

        }
    },
})
没找到相同name会报错，能不能在找不到的时候
generate: function generate(name, params) {
      var route = this.names[name],
          output = "";
      if (!route) {
        route = this.names[noFoundName]
        //throw new Error("There is no route named " + name);
      }

      var segments = route.segments;

      for (var i = 0, l = segments.length; i < l; i++) {
        var segment = segments[i];

        if (segment instanceof EpsilonSegment) {
          continue;
        }

        output += "/";
        output += segment.generate(params);
      }

      if (output.charAt(0) !== '/') {
        output = '/' + output;
      }

      if (params && params.queryParams) {
        output += this.generateQueryString(params.queryParams);
      }

      return output;
    },
使用配置的name

**Comment by fnlctrl** [comment]
找不到name的时候需要报错的，否则容易出现name写错，链接失效而找不到原因的情况。

**Comment by guojianlan** [comment]
不能先出个配置？然后找不到name,而且没有配置name再报错么？

**Comment by fnlctrl** [comment]
这太琐碎了，没有必要为此增加配置。
