### ISSUE TITLE
Unknown custom element <router-view>

### ISSUE THREAD

**Issue by ChromoX** [vuejs/vue-router#872]
Using webpack template.

I'm getting the following error message:

```
[Vue warn]: Unknown custom element: <rounter-view> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in root instance)
```

I've taken a look at all other closed issues about this topic and can't find a solution.

main.js:

```js
import Vue from 'vue'
import App from './App'
import router from './router'
// import { sync } from 'vuex-router-sync'

Vue.config.debug = true

/* eslint-disable no-new */
const app = new Vue({
  router,
  ...App
})

app.$mount('#app')
```

./router/index.js

```js
import Vue from 'vue'
import Router from 'vue-router'

Vue.use(Router)

import Home from '../components/Home'
import Pag from '../components/Pag'

const routes = [
  {path: '/home', component: Home},
  {path: '/pag/:id', component: Pag}
]

export default new Router({
  mode: 'history',
  scrollBehavior: () => ({ y: 0 }),
  routes: routes
})
```

App.vue
```js
<template lang="pug">
  div(id="app")
    div(class="header pure-g")
      form(class="search pure-u-2-5 pure-form")
        input(type="text" placeholder="Search...")
      nav(class="pure-u-5-5 pure-menu pure-menu-horizontal")
        ul(class="pure-menu-list")
          li(class="pure-menu-item")
            router-link(class="pure-menu-link" to="/home") Home
          li(class="pure-menu-item")
            router-link(class="pure-menu-link" to="/pag") Pag
    rounter-view
</template>
```

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

You're missing the plugin installation `Vue.use(VueRouter)`

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

You mistyped rounter-view --> router-view
