### ISSUE TITLE
$route.query can't use in vue-resource params.

### ISSUE THREAD

**Issue by alphatr** [vuejs/vue-router#873]
I use $route.query in vue-resource like this:

```
Vue.http.get('/someUrl', {query: $route.query});
```

and receive a `obj.hasOwnProperty is not a function` error;

I find in vue-route create query by using `Object.create(null)` and this is completely blank object, no inherit hasOwnProperty method.

however in vue-resource, it can use `obj.hasOwnProperty` in `each` function to transform the params query.

**Comment by posva** [comment]
As a workaround until this is fixed, you can use the assign syntax: `query: {...$route.query}`

**Comment by yusank** [comment]
```
http://example.com?a=1&b=2&c=3
```
I want to change one of the param value and still use it like
```
query: {
...$route.query
}
```
any ideas?

**Comment by posva** [comment]
you just do

```js
query: {
  ...$route.query,
  myOverridenValue: 'hi'
}
```

Remember you can use the [forum](http://forum.vuejs.org/) or the [Discord server](https://vue-land.js.org/) to ask quick questions 🙂

**Comment by yusank** [comment]
OK ,  thank you . I just start learning Vue ,so I didn't know those websites before you told me . 👀

**Comment by JounQin** [comment]
It's nothing related to Vue, it is just `js` (or `es`?).
