### ISSUE TITLE
Reference Error - _m is not defined 

### ISSUE THREAD

**Issue by ThisThatBC** [vuejs/vue-router#875]
I have the following routes, defined in a module. All routes work except for Apps and Emails. I get the error `Reference Error - _m is not defined`. I am using webpack and it seems to be an error due to that. Does anyone have experience with this error. The Apps and Emails vues are new. Don't know if I missed something or the WebPack Vue Loader is playing up. 

``` javascript
import Vue from 'vue';
import Router from 'vue-router';
import Login from '../components/Login.vue';
import SignUp from '../components/SignUp.vue';
import Profile from '../components/Profile.vue';
import Settings from '../components/Settings.vue';
import Dashboard from '../components/Dashboard.vue';
import Apps from '../components/Apps.vue';
import CreateApp from '../components/CreateApp.vue';
import Emails from '../components/Emails.vue';
import NotFound from '../components/NotFound.vue';

Vue.use(Router);

export default new Router({
    mode: 'history',
    base: __dirname,
    routes: [
        { path: '/', component: Dashboard },
        { path: '/login', component: Login },
        { path: '/signup', component: SignUp },
        { path: '/profile', component: Profile },
        { path: '/settings', component: Settings },
        { path: '/apps', components: Apps },
        { path: '/emails', components: Emails },
        { path: '/app/create', component: CreateApp },
        { path: '/notfound', component: NotFound },
        { path: '*', redirect: 'notfound' }
    ]
});
```

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only, and we encourage you to use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions or for discussion. Thanks!

**Comment by ThisThatBC** [comment]
All good. The error was due to me working on a Friday evening and typing in `components` instead of `component`.
