### ISSUE TITLE
Router configuration "base" don't support "?#"

### ISSUE THREAD

**Issue by chooin** [vuejs/vue-router#878]
```
const router = new VueRouter({

    mode: 'history',

    base: '?#',

    ...
})
```
first enter the page http://localhost:8080/?#/home/index，
refresh  http://localhost:8080/?#/home/index#/home/index，
refresh again http://localhost:8080/?#/home/index#/home/index#/home/index

**Comment by posva** [comment]
`base` is supposed to be a valid base URI, It's `/` by default and can contain strings like `/admin/`. `#` and `?` have both special meanings for URL and therefore cannot be used as basepaths. More info here: http://router.vuejs.org/en/api/options.html#base
