### ISSUE TITLE
Should router-link to a number work like router.go?

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue-router#880]
For example, to go back:

``` html
<router-link :to="-1">
```

**Comment by simplesmiler** [comment]
The most common use case is `-1`, so maybe `<router-link back>` will be better?

**Comment by chrisvfritz** [comment]
But why limit the API? In some cases, people may want to go back if there's history, or else go to a default location. For native-like mobile interfaces, I can also see use cases for forward.

**Comment by DaAwesomeP** [comment]
@chrisvfritz will you accept pulls for this?

**Comment by DaAwesomeP** [comment]
@chrisvfritz nevermind, this isn't as simple as I thought. I would need to resolve the location, route, and href of the next page, not just go to it.

**Comment by isometriq** [comment]
I've created a simple functional component, here:
```
<script>
    export default {
        render(createElement) {

            const $root = this.$root;

            return createElement(

                // Tag
                this.tag,

                // Attributes
                {
                    attrs: Object.assign({
                        href: this.tag=='a' ? 'javascript:' : null,
                        type: this.tag=='button' ? 'button' : null
                    }, this.$attrs),
                    on: {
                        click() {
                            $root.$router.back();
                        }
                    }
                },

                // Children
                this.$slots.default
            );
        },

        props: {
            'tag': {
                type: String,
                default: 'a'
            }
        }
    }
</script>
```

You can use it like this
```
// Most basic is a link with href="javascript:"
<router-back>Go Back!</router-back>

// You can specify the tag and normal html tags
<router-back tag="button" class="btn btn-sm btn-danger"><i class="fa fa-close"></i> Cancel</router-back>
```

I was thinking of wrapping the same logic  with something like `<router-history go="-5">Go back a lot</router-history`, but I guess I'm too lazy and 99% of the time, it would be used to go back. These other special cases can go in a click event.

**Comment by pcornier** [comment]
I'm new to vuejs but is it strictly forbidden to access the router instance like this?
```
<div @click="$router.go(-2)">back</div>
```

**Comment by posva** [comment]
@pcornier that's absolutely ok, but please use the [forum](http://forum.vuejs.org/) or the [Discord server](https://vue-land.js.org/) for questions 🙂

**Comment by pcornier** [comment]
@posva OK thank you, but the idea behind my comment was to close this feature request as we can access the router instance directly.

**Comment by FossPrime** [comment]
Vue-Material users: 
```
<md-button class="md-fab md-mini md-primary" @click="$router.go(-1)">
  <md-icon>arrow_back</md-icon>
</md-button>
```

**Comment by leoyli** [comment]
I don't like the `vm.$router` approach, I was trying to limit the use of `vm.$router` in general, especially in the `template`, then I don't need to mock this object in my tests...  IMO, we should have something imperative, and at least supports `<router-link back>` to make thing complete.

Otherwise, we just have to put `@click="$router.push(to)"` right?  NO.

**Comment by Ashyoo** [comment]
changed it? Why is it now warning that "to" is a necessary String or Object, but gets the number.

**Comment by posva** [comment]
Given that the utility of RouterLink is to display the correct URL as the href and other things related to the generated URL, we wouldn't be able to do any of these in the case of `-1`  (since we don't have access to the history entries), this would be equivalent to just doing `@click="$router.go(-1)"`, so I don't think it's worth adding

**Comment by joallard** [comment]
I see this has been moved to Done, is that right?

**Comment by joallard** [comment]
So I've just wrestled with this a bit, changing the usual `<router-link>` to a custom invocation for the sake of the back link:

- `<div @click="$router.push(-1)"> and <button>` don't reuse the css selector for links `a` and needs a workaround to work
- `<a @click="$router.push(-1)" href="#">` will insert extra `#` at random moments in the history, breaking the back function (I've just been debugging this for half an hour)

I'm now trying `<a @click.prevent="$router.push(-1)" href="#">`, crossed fingers I won't get another random bug.

Overall, this use case has amassed 59 votes over 4 years, seems like there is a clear need. I am not sure why we would require people writing more code to do the same task, not to mention that copy-pasting and extra code often leads to more bugs and requests.

If the API seems contorted/inelegant under the current proposal, I could understand. Would the following work?

```
<router-link :go="-1">
```

To make the implementation "boring", seeing `to` gets passed internally to `router.push`, `go` could simply get passed to `router.go`, no parsing or special treatment required. I'm not familiar with the vue-router internals, but if it makes the implementation more straightforward, seems like a winner to me. (There's always a way to include syntactic sugar such as `back` in the future, but first steps first.)

Would that be simple enough?
