### ISSUE TITLE
v-link param not escape

### ISSUE THREAD

**Issue by craynic** [vuejs/vue-router#881]
vue 1.0.27
vue-router 0.7.13
my html:
```
<input type="text" name="seat" v-model="seat">
<a v-link="{name: 'search-list', params: {type: 'seat', pattern: seat}}">查询</a>
```
js:
```
router.map({
    '/search/:type/:pattern': {
        name: 'search-list',
        component: SearchList,
    }
});
```
I type `2#3f123` in the input, and the address becomes `/search/seat/2#3f123`, and `$route.params.pattern` returns `2`, which is surely not expected. I do not think that it's a feature.

Is there a way to escape the value passed to v-link as a param? Or, if it is supported in v2? I'm glad to move to v2.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. Escaping isn't automatically done by vue-router, you need to manually escape them with [`encodeURIComponent`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent), and get the real value with `decodeURIComponent`.

**Comment by craynic** [comment]
thanks, this works for me:

```
<a v-link="{name: 'search-list', params: {type: 'seat', pattern: encodeURIComponent(seat)}}">查询</a>
```
