### ISSUE TITLE
hashbang backwards compatibility?

### ISSUE THREAD

**Issue by pehbehbeh** [vuejs/vue-router#885]
Is it somehow possible to use the old hashbang behaviour with vue-router 2.x?

For our application we need the URLs to be with `#!` instead of just `#` in hash mode.

**Comment by posva** [comment]
I don't see why you need to use a [deprecated](https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html) practice but you can use history mode and set a base of `/#!/` as a workaround. I doubt we add back support for it.

**Comment by pehbehbeh** [comment]
I didn't know about this workaround. Seems to work just fine. Thanks for your help!

**Comment by Mr-Hero** [comment]
Now I am updating Vue-rouer1.x to Vue-router2, and I have the same problem, I wanna urls has #!/ in hash mode, but cannot find the  config option

**Comment by posva** [comment]
The doc is here: https://router.vuejs.org/en/api/options.html#base

**Comment by aftdotleo** [comment]
**history mode** with **/#!/** seems not to be worked properly when served in sub path web app,
such as **/appA/#!/** or **/appB/#!/**.

I found a easy way to compat v1 & v2 route path in hash mode.

Just write a inline script before vue-router loaded,

```javascript
      var hash = location.hash;
      if (hash && hash.indexOf('#!') === 0) {
        location.hash = hash.slice(2);
      }
```

The old v1 route path will work fine in v2.
