### ISSUE TITLE
vue-router 刷新后页面变404

### ISSUE THREAD

**Issue by yanlee26** [vuejs/vue-router#889]
这个问题怎么破，谢谢大师指教

**Comment by vvenv** [comment]
#886 又发一遍？

**Comment by posva** [comment]
http://router.vuejs.org/zh-cn/essentials/history-mode.html#后端配置例子
Or ask for help on the [forums ](https://forum.vuejs.org/). Github Issues are for feature request and bug reports only

**Comment by zhx0311** [comment]
另一种情况，你配置的服务器请求代理proxyTable中配置的url名称是不是和vue-router中routes设置的路由切换名重复了，才导致的刷新就出现了404；
