### ISSUE TITLE
Better compatibility between ScrollBehavior and transitions

### ISSUE THREAD

**Issue by francoislevesque** [vuejs/vue-router#892]
I'm trying to create smooth animations between router using <transition> on <router-view>. To achieve this, it's important to scroll on each transition. The provider attribute "ScrollBehavior" can handle this like that: 

```
scrollBehavior (to, from, savedPosition) {
  return { x: 0, y: 0 }
}
```

Using this, the scrolling occurs before the animation is finished, which is not "smooth". I'm currently doing a smoother scrolling to the top like this:

```
// Template
<transition name="scale" mode="out-in" 
	v-on:before-enter="beforeEnter">	
	<router-view></router-view>
</transition>

// Script
methods: {
	beforeEnter() {
		window.scrollTo(0,0)
	}
}
```

Is it possible, using scrollBehavior, to scroll in the middle of the animation to hide the scrolling?

**Comment by posva** [comment]
Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You're probably looking for this: https://vuejs.org/v2/guide/transitions.html#JavaScript-Hooks

Edit: Sorry, I went a bit too fast without noticing that was what you're already doing. No, it's not possible, using transition hooks is the way to go
