### ISSUE TITLE
can't get app instance properties or methods

### ISSUE THREAD

**Issue by MillerRen** [vuejs/vue-router#893]
```
if (to.matched.some(record => record.meta.requiresAuth)) {
    // this route requires auth, check if logged in
    // if not, redirect to login page.
    if (!router.app.isLoggedIn) {
      next({
        path: '/login',
        query: { redirect: to.fullPath }
      })
    } else {
      next()
    }
  } else {
    next() // make sure to always call next()!
  }
```
router.app.isLoggedIn is undefined first run. `isLoggedIn ` defined in vuex.

**Comment by posva** [comment]
Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) 🙂 

---

You need to make `isLoggedIn` accessible in the root instance if you want to do that
