### ISSUE TITLE
<div @click="onClick"><router-link :to="{ query: { q: val}}">{{val}}</router-link></div>  to  <router-link :to="{ query: { q: val}}" onClick>{{val}}</router-link>

### ISSUE THREAD

**Issue by suptwo** [vuejs/vue-router#896]
how to  add click  for router-link 

&lt;li @click="onClick"&gt;<router-link :to="{ query: { q: val}}">{{val}}</router-link>&lt;/li&gt;

  to  

<router-link :to="{ query: { q: val}}" @click="onClick">{{val}}</router-link>

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only, and we encourage you to use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions or for discussion. Thanks!

---

https://vuejs.org/v2/guide/components.html#Using-v-on-with-Custom-Events
`<router-link :to="{ query: { q: val}}" @click.native="onClick">{{val}}</router-link>`

**Comment by suptwo** [comment]
Hello.  how to add (-webkit-tap-highlight-color: rgba(0,0,0,0.05)) for router-link / a

the  forum is ' New registrations are not allowed from your IP address (maximum limit reached). Contact a staff member.'
