### ISSUE TITLE
浏览器上正常，微信上有问题，搞不定

### ISSUE THREAD

**Issue by 285858315** [vuejs/vue-router#90]
http://182.92.213.103/test/a/22
浏览器上这个路由上正常显示，但微信上没有匹配到路由。

**Comment by 285858315** [comment]
该死的微信。

**Comment by yyx990803** [comment]
试试用 abstract mode

**Comment by 285858315** [comment]
试了，好像还是匹配不到，

**Comment by 285858315** [comment]
试了，好像还是匹配不到，

**Comment by 285858315** [comment]
算了，我还是先用以前的老办法吧。

**Comment by honghuamin** [comment]
我遇上同样问题。在iphone上正常，而android里的微信，第一次打开，不匹配路由，需要重新进入页面后才正常
