### ISSUE TITLE
什么时候vue2.0+meteor开发个例子出来

### ISSUE THREAD

**Issue by shijunti19** [vuejs/vue-router#904]
什么时候vue2.0+meteor开发个例子出来？
webpack在meteor几乎不能用啊！
可不可以提供一套完整程序！

**Comment by fnlctrl** [comment]
你好，请使用[论坛](http://forum.vuejs.org/)或[gitter](https://gitter.im/vuejs/vue)提问，issue列表只用于提交bug和feature request，谢谢！
