### ISSUE TITLE
how to add (-webkit-tap-highlight-color: rgba(0,0,0,0.05)) for router-link / a

### ISSUE THREAD

**Issue by suptwo** [vuejs/vue-router#907]
Hello.  how to add (-webkit-tap-highlight-color: rgba(0,0,0,0.05)) for router-link / a

to  forum is ' New registrations are not allowed from your IP address (maximum limit reached). Contact a staff member.'

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only. You can also use [gitter](https://gitter.im/vuejs/vue) or [Stackoverflow](http://stackoverflow.com/) to ask questions. Thanks!
