### ISSUE TITLE
Router-link warnings

### ISSUE THREAD

**Issue by rlambertsen** [vuejs/vue-router#909]
I have two ares where I use router-link inside v-for. One of them throws a vue-warn in the console log saying that the required prop TO is not found and then also the property NAME is undefined. Though the code is the same minus some structure of inner html.

example of working no warnings code:
```
<div class="col-lg-3 col-xs-6 form-group" v-for="(object, index) in interests">
          <router-link :to="{name: 'community', params: {id: object.id, name: object.name}}">
            <div class="commuinity-box text-center">
              <img src="../assets/gaming.jpeg" alt="gaming" class="img-responsive community-box__image">
              <div class="community-box__icon white-text">
                  <i class="fa fa-gamepad" aria-hidden="true"></i>
              </div>
              <p class="community-box__title">{{object.name}}</p>
            </div>
          </router-link>
        </div>
```
example of code that throws error:
```
<ul class="list-unstyled list-group my-communities__ul text-center white-text">
            <li class="list-group-item my-communities__li" v-for="(objects, index) in community" draggable>
              <router-link :to="{name: 'community', params: {id: objects.id, name: objects.name}}">{{objects.name}}<router-link>
              <i class="fa fa-times pull-right"></i>
              <i class="fa fa-arrows-v pull-right"></i>
            </li>
            <li class="list-group-item my-communities__li"><a href="javascript:void">Discover More</a></li>
          </ul>
```
Also to note that when rendered the font awesome icons are not in the HTML. That is also casing some real head scratching. The router-link works as expected but makes me think WTF where are the font awesome icons and why are there errors here and no tthere!! Any help on why this issue is present would help, thanks!

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a live reproduction on jsfiddle, codepen etc. Thanks!
