### ISSUE TITLE
path 不变, 参数变化的情况下,有没有可能重绘 router-view 里面的元素呢?

### ISSUE THREAD

**Issue by spacedragon** [vuejs/vue-router#91]
例如:
  /user/: id  这样的route

如果地址从 /user/a   换到 /user/b , router view 并不会重绘.    设计是这样的么?

**Comment by 285858315** [comment]
http://vuejs.github.io/vue-router/view.html
keep-alive is not supported as of now.

**Comment by yyx990803** [comment]
看文档：http://router.vuejs.org/pipeline/data.html

**Comment by santinoDu** [comment]
这个文档404了，还有别的地方可以看到吗？

**Comment by jingsam** [comment]
http://router.vuejs.org/zh-cn/pipeline/data.html

**Comment by shaqueoneal** [comment]
文档都是404，如果想要把 /user/a   /user/b 都缓存起来需要怎么做？@yyx990803
