### ISSUE TITLE
Could i use 'append' in router.go() ?

### ISSUE THREAD

**Issue by yinjun1991** [vuejs/vue-router#911]
use vue-router 1.x, I can write like this:
```
this.$router.go({
  path: 'upload',
  append: true,
});
```

but i have try in vue-router 2.x, It seems like can`t work

how can i use 'append' in router.go() ? thanks

**Comment by LinusBorg** [comment]
`path: this.$route.path + 'upload'` maybe?

**Comment by xuchao008** [comment]
遇见这个问题了，貌似没人回答
