### ISSUE TITLE
[Regression] Using router methods without Vue instance causes error

### ISSUE THREAD

**Issue by blake-newman** [vuejs/vue-router#922]
```bash
  TypeError: null is not an object (evaluating 'this$1.router.app.$nextTick')
  at webpack:///~/vue-router/dist/vue-router.js:1321:0 <- /Users/blake/work/vue-creating-scalable-apps-workshop/final/test/unit/index.js:8738
```

[Source location](https://github.com/vuejs/vue-router/blob/dev/src/history/base.js#L95)

Git Bisect points at [83418bc](https://github.com/vuejs/vue-router/commit/83418bce4b66b0320047a0f7cbd50a3a2d2b4d1f)

Using router methods without Vue instance causes the above error. This affects unit tests with PhantomJS due to a `popstate` event after tests are finished. This also breaks when using the feature as intended.

Note: The line that causes the error is to ensure that asynchronous components are resolved before callbacks are executed. We can not rely on the `router.app` as this may not be available.

**Comment by blake-newman** [comment]
A further investigation reveals that PhantomJS causes a 'popstate' event upon finishing tests. Which invokes the error to happen. 

This could potentially be an issue for applications that use other librarys/tooling. If a `popstate` or `hashchange` event occurs without an instantiation of Vue then this will be an issue.

**Comment by ealves-pt** [comment]
Same problem here, only working if I use `v2.0.1`.

**Comment by sam-b-rose** [comment]
I think this should be reopened. I am still getting the same error as @blake-newman when using `v2.2.1`. Like @ealves-pt I do not get the error if using `v2.0.1`

```
TypeError: undefined is not an object (evaluating '_Vue.extend')
at webpack:///~/vue-router/dist/vue-router.common.js:1737:0 <- index.js:36394
```

**Comment by posva** [comment]
@samrose3 If that the case, can you open a new issue with a minimal repro, please?
