### ISSUE TITLE
Is there a way to exclude routes from vue router and send them as a GET http request?

### ISSUE THREAD

**Issue by scottgrayson** [vuejs/vue-router#927]
For example:
I want these to use vue router
```
'/'
'/news'
'/blog'
```
but theses to be sent as get requests and ignored by vue router
```
'/admin'
'admin/users'
```

**Comment by fnlctrl** [comment]
No. Front-end routing never sends GET requests.

**Comment by motanelu** [comment]
I think what he means is can the router ignore some routes and let them pass through to the server? Which is something I'm interested in achieving now.

**Comment by posva** [comment]
Use a regular link 🙂

**Comment by motanelu** [comment]
That's one way of doing it, although in my case is a bit more complicated, as it would need to fallback to a different HTML5 router. Think an widget that you can drop in. Routes that start with `/my-widget/*` should be handled by the vue router and others should be allowed to pass.

**Comment by dschreij** [comment]
I'm also struggling with this one. I want all calls to /api/* to be forwarded to the server, but let vue-router catch all other unspecified paths and show a 404. Currently I don't see a way to specify in the route config to let vue-router ignore calls to /api. What would be nice to have is:

~~~javascript
const routes = [
    { path: '/', component: Home },
    /* other routes */
    { path: '/api', // Ignore or pass on to server },
    { path: '*', component: NotFound }
];
~~~

The problem now is that other apps who want to peform a GET request to the api endpoints of the server get intercepted by the vue-router.

**Comment by posva** [comment]
Just use a regular link without declaring it in `routes` (or axios/fetch if you just want to fetch data)

**Comment by dschreij** [comment]
@posva thanks for your suggestion, but doesn't the `{ path: '*', component: NotFound }` entry intercept it anyway if I don't declare it in the routes?

**Comment by posva** [comment]
only if you use a `router-link`

**Comment by koliyo** [comment]
What if you enter the URL manually in the browser address bar? Eg `https://my.service/graphiql`

Edit: I realize I can just catch this on the server side before routing to the SPA client.

**Comment by mirajp** [comment]
What version of vue-router are you all using? I'm using v3.0.1 and I can just add the paths I want ignored without designating a component and it allows me to visit my backend RESTful (GET) endpoints and see the JSON without the router redirecting to my catch-all/default route.
(Vue: v2.5.16)
`
const routes = [
    { path: '/', component: Home },
    /* other routes with components*/
    { path: '/apia' },
    { path: '/apib' },
    { path: '/apic' },
    { path: '*', redirect: '/' }
];

...

var router = new VueRouter({
    routes: routes,
    mode: "history"
});
`

Maybe this is no longer an issue?

**Comment by mirajp** [comment]
What version of vue-router are you all using? I'm using v3.0.1 and I can just add the paths I want ignored without designating a component and vue-router will allow me to visit my backend RESTful (GET) endpoints to see the JSON as axios would; the router is not redirecting to my catch-all/default route:
(Vue: v2.5.16)
```javascript
const routes = [
    { path: '/', component: Home },
    /* other routes with components*/
    { path: '/apia' },
    { path: '/apib' },
    { path: '/apic' },
    { path: '*', redirect: '/' }
];

...

var router = new VueRouter({
    routes: routes,
    mode: "history"
});
```

Maybe this is no longer an issue?

**Comment by tecnical** [comment]
Hi guys,

I installed vuepress as mentioned in the docs  (https://vuepress.vuejs.org/guide/getting-started.html#inside-an-existing-project). I used the same directory anyway.

I want to integrate the build of vuepress in the build of my project (im using quasar, with vue-router, but could be anything with vue-router)

Is there anyway to vou-router ignore the /docs?

if put the dist content in /src/statics/docs, vou-router sends me a 404 response.

**Comment by tcamde** [comment]
I had the problem that my GET requests to my node servers API were intercepted by vue router.
As it turns out the solution is just to create your api routes **before** serving the SPA on you node backend. I know it's obvious but it took me 30 min. So letting everybody else know.

This works for me (server.js):

```
const express = require('express')
const history = require('connect-history-api-fallback')
const bodyParser = require('body-parser')
const config = require('./server/config/config.js')
const sequelize = require('./server/models/database-connection')

const app = express()

// attach all server routes
require('./server/routes')(app)  <------------------------------- before app.use(history())

app.use(history()) // routes all unkown get requests back to index
app.use(express.static(__dirname + '/client/dist')) // serves the SPA
app.use(bodyParser.json()) // makes payload of post request available under req.body
```

**Comment by joaomelo** [comment]
I was having a challenge related to this issue. 

I want some routes to be caught by vue-router and others to be addressed by Node. But I want the vue-router eligible routes to be addressed in all situations, including when the user typed them in the address bar. That is, not be limited to cases coming from a router-link as explained by @posva.

If someone reached this page researching the same problem as me, I'm sharing that the solution was found in the official docs. The html5 history mode [page](https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations), although addressing a different problem, offers an equally valid solution to this.

By the way, Vue and Vue-router are awesome :)

**Comment by mitar** [comment]
I also came to this issue searching for a way to register server-die routes with vue router. I want this so that I could use programmatic route resolving by name while keeping the usual structure (and use of router-link). I think that ideally, if `component` would not be defined, vue router should just make a regular http get request. This would allow me to have a single place to register routes and their behavior while users of routes (using name and router-link) would not have to care if the link is frontend or backend one.

**Comment by mitar** [comment]
I think I figured a workaround. For routes I want to use GET requests, one can add `beforeRoute` guard:

```js
      beforeEnter: (to, from) => {
        if (isServerRoute(to)) {
          window.location = to.fullPath
          return false
        }
        return true
      },
```

**Comment by posva** [comment]
You can also put it in one single beforeEach. You can just not return anything instead of true btw (vue router 4)

**Comment by derunva** [comment]
Just add an option for this! Something like:

{ path: "/assets/3dmodels/", mode: "ignore" }

Or how I cant do it?

I don't need to configure or manage another server just for development. I want to serve static files from the public folder and get a real 404 status when a file doesn't exist. Because I need to get it by axios or etc. 

This is a really frustrating issue because SPA fallback makes it impossible to distinguish between an actual application route and a missing static resource.

At this point, I'm removing `vue-router` from my project because I've already spent too much time looking for a legitimate solution to this problem.
