### ISSUE TITLE
[JSPM] router-link: unknown custom element warning when used inside child component 

### ISSUE THREAD

**Issue by ghost** [vuejs/vue-router#928]
Getting the known warning:
_Unknown custom element: <router-link> - did you register the component correctly?_
when using the router-link component inside a child component. 

I am using JSPM / System.js and ES6 to import modules. 
I use the full version of VueJS (with the compile), importing it:
`import Vue from 'vue/dist/vue.js';`

I realise the solution to Webpack or Browserify is to not include Vue  like this, but define an alias to the full version. I have done so in SystemJS config, yet still receiving the same warning. 
Checked and Vue is being loaded only once, as is VueRouter.

Any help would be greatly appreciated.

**Comment by yyx990803** [comment]
Did you call `Vue.use(VueRouter)`?

**Comment by ghost** [comment]
@yyx990803 yes, Vue.use(VueRouter) is called.
The router-link components seems to work normally, until it is used in a child component.

This is a general representation of the app structure:
```
[App] - Uses router-view.
    
    [MainControllerComponent] - Uses router-view
        
        [SectionControllerComponent] - Extended MainControllerComponent. Uses router-view.

            [SectionPageControllerComponent] - Extended SectionControllerComponent. Uses router-view. Router-link works here.
            
                [ListComponent] - Locally registered component of SectionPageControllerComponent. Router-link stops working here.
                
                    [ListItemComponent] - Router-link doesn't work.
```

**Comment by ghost** [comment]
@yyx990803 
It does seem that JSPM reloads the Vue library when it is imported in a different file, though that is not seen in the network tab of devtools. 

I was able to reproduce and resolve the behaviour:

```
// === main.js ===

import Vue from 'vue-full';
import VueRouter from 'vue-router';

import LocalComponent from './local-comp.js';

Vue.use(VueRouter);

const app = new Vue({...});

let View1 = Vue.extend({
    components: {
        'local-comp': LocalComponent
    }
});

// === local-comp.js ==

import Vue from 'vue-full';

export Vue.extend({...});
```

This will cause the warning if _router-link_ is used in the _LocalComp_ component. Interestingly the _LocalComp component_ does have the $route and $router properties available in its instance.
In order to fix this the VueRouter needs to be reapplied whenever Vue is imported in a different file:

```
// === main.js ===

import Vue from 'vue-full';
import VueRouter from 'vue-router';

import LocalComponent from './local-comp.js';

Vue.use(VueRouter);

const app = new Vue({...});

let View1 = Vue.extend({
    components: {
        'local-comp': LocalComponent
    }
});

// === local-comp.js ==

import Vue from 'vue-full';
import VueRouter from 'vue-router';

Vue.use(VueRouter);

export Vue.extend({...});
```
See the **Vue.use(VueRouter);** in the _LocalComp_ file.

To work around this, I made a sort of decorator for vue in a separate file:

```
// === vue-decorator.js ===

import Vue from 'vue-full';
import VueRouter from 'vue-router';

Vue.use(VueRouter);

export default Vue;

// === other file(s) ===
import Vue from 'vue-decorator.js';
```

I'm not sure if this is good practice or not, but solves the issue with JSPM.

**Sidenote:**
If you're using a vue instance as an event hub, you will have to import the default vue library and use the constructor.

**Comment by fnlctrl** [comment]
@beno-dlabs You should never use `Vue.extend` (or `Vue.component`) when exporting components, simply export a plain object instead.
```js
// === local-comp.js ==
export {...}
```

**Comment by ghost** [comment]
@fnlctrl Thank you for the information. Can I ask why this shouldn't be used?

**Comment by fnlctrl** [comment]
When you use `Vue.extend()` you get a fresh new Vue constructor, you can think of it as a fork of the global Vue. In the future, not all modifications to the global Vue by plugins will be applied to it.
By the way, there is no practical benefit of doing it in the first place - duplicating `import Vue` and `Vue.extend()` in every component.

**Comment by ghost** [comment]
@fnlctrl Ok, understood. Thank you for the extra explanation!
