### ISSUE TITLE
Hooks function can not execute when used Dynamic Segments.

### ISSUE THREAD

**Issue by liboemc** [vuejs/vue-router#929]
路由设置如下：

_router.map({
			'/help': {
				component: helpView
			},
			'/help/:index': {
				component: helpDetailView
			},
		});
	
	
1.浏览器触发 http://xxx.xxx/#!/help 变更为 http://xxx.xxx/#!/help1 时，钩子函数activate是正常执行的。
2.浏览器触发 http://xxx.xxx/#!/help/1 变更为 http://xxx.xxx/#!/help/2 ,钩子函数并没有执行。
观察源码，第二种情况发生时候，canReuse函数返回这个view是可以复用的，所以钩子函数没有执行。
我的疑问是，第二种情况钩子函数没有执行，具体是什么原因呢？

Vue.js v1.0.10   
vue-router v0.7.13

**Comment by fnlctrl** [comment]
activated只会在进入新路由的时候被触发，参数改变的时候不会触发。
需要响应参数改变的话，请给$route加一个watcher:
```js
{
  watch: {
    $route(route) {
        console.log(route.params)
    }
  }
}
```

**Comment by liboemc** [comment]
找到另外一种方式，加入钩子函数canReuse:function(transition){return false;}
   参数改变也会触发activated。

看到源码：
	return typeof canReuseFn === 'boolean' ? canReuseFn : canReuseFn ? canReuseFn.call(component, {
      to: transition.to,
      from: transition.from
    }) : true; // defaults to true

这里defaults to true基于什么考虑呢？是否可以换成false?
