### ISSUE TITLE
关于路由参数自动排序的特性

### ISSUE THREAD

**Issue by NadokaCiel** [vuejs/vue-router#932]
尤大大您好，最近在项目中使用vue-router时发现了页面的请求参数自动调用stringifyQuery，按照字母顺序排序的情况，可以请教一下为什么要对参数排序吗？
这个特性导致在使用vue进行微信公众号开发的时候，参数自动变换位置导致wx,config在配置时的url请求与最终的url不一致。由于微信会自动向url添加form参数，ios系统则会自动向url添加isapp参数，因此vue-router对参数自动排序的特性会导致类似的验证失效，可否麻烦您提供 是否自动对参数排序 的配置，O(∩_∩)O谢谢！

**Comment by fnlctrl** [comment]
见https://github.com/vuejs/vue-router/issues/926
