### ISSUE TITLE
Prefixed argument in path does't work

### ISSUE THREAD

**Issue by ianberdin** [vuejs/vue-router#935]
I tried make route path like this:
```
 site.com/5
 site.com/5/prefix6
```
with path:  
```JavaScript
{ path: '/:arg1(/prefix)?:arg2?', name: 'home' }
```
And it work. But url resolver in Router not. Problem:
```JavaScript
this.$router.push( { name: 'home', params: { arg1: 5, arg2: 6 } } )
// going to:
site.com/56
// not to:
site.com/5/prefix6
```

Additional I tried like this:
```JavaScript
{ path: '/:arg1/:arg2(prefix\\d+)?', name: 'home' }
// and it's work, but... I need pass prefixed argument
his.$router.push( { name: 'home', params: { arg1: 5, arg2: "prefix6" } } )
```

Any ideas, how implement this?
Ofc, I can use like this: push( { path: '/5/prefix6' } ). But...

**Comment by posva** [comment]
Your path isn't good, it should be: `path: '/:arg1/(prefix/)?:arg2?'`
However, it will go to `5/6`. Since your prefix is optional, vue-router will omit it by default

**Comment by ianberdin** [comment]
Thank you for answer.
>it will go to 5/6

Isn't normal. I need: /5/prefix6

**Comment by posva** [comment]
Then do `path: '/:arg1/(prefix)?:arg2?'`. But you have to manually specify the prefix because it is optional. You can also use a redirect or an alias http://router.vuejs.org/en/essentials/redirect-and-alias.html

**Comment by ianberdin** [comment]
Doesn't work :(
go to:
/5/
/5/6

not:

/5
/5/prefix6

**Comment by ianberdin** [comment]
Redirect and Alias not for this case, it's simple.
It's good work with 2 different url:
```JavaScript
{ path: '/:arg1', name: 'home' }
{ path: '/:arg1/prefix:arg2', name: 'homePrefixed' }
```
