### ISSUE TITLE
How to make each href with a domain name?

### ISSUE THREAD

**Issue by bs32g1038** [vuejs/vue-router#937]
### for example:
`<router-link  to="/category/news">news</router-link>`

### I want it to be like this.
After vue compiled,  the "a tag of href" can with domain name.
such as: `<a` `href="http://127.0.0.1/category/news">news</a>`

How should I go to realize it?

**Comment by posva** [comment]
Maybe using the [`base` option](http://router.vuejs.org/en/api/options.html#base) will work.
Why do you need that?
