### ISSUE TITLE
Using class extends syntax with router component

### ISSUE THREAD

**Issue by mcfarljw** [vuejs/vue-router#940]
Should we be able to use the es6 class extends syntax when extending the vue for router components? For the following examples assume the VueRouter is doing something like this: `VueRouter({routes: [{ path: '/', component: Home }]});`

```
const Home = Vue.extend({

  template: '<h1>hello world</h1>'

});
```

This works and properly renders the extended view component to the page.

```
class Home extends Vue {

  constructor () {
    super({
      template: '<h1>hello world</h1>'
    });
  }

}
```

This doesn't work and returns the following errors:

- [Vue warn]: Error when rendering root instance
- vue.js:2902TypeError: Cannot call a class as a function

```
babel-preset-latest: 6.16.0
vue: 2.1.3
vue-router: 2.0.3
```

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. There's `vue-class-component` for this: https://github.com/vuejs/vue-class-component
