### ISSUE TITLE
按需加载路由及子路由

### ISSUE THREAD

**Issue by yinjun1991** [vuejs/vue-router#941]
您好，我的项目里面有一个功能模块，允许用户上传头像，裁剪，还有一个loading 页面。
由于这个功能用户很可能只用到一次，所以采用按需加载的方式。
router 如下所示：

```
'/upload': {
  name: 'upload',
  component: resolve => require(['./views/upload/index.vue'], resolve),
  subRoutes: {
    '/clip/:face': {
      name: 'clip',
      component: resolve => require(['./views/upload/clip/index.vue'], resolve),
    },
    '/loading': {
      component: resolve => require(['./views/upload/loading/index.vue'], resolve),
    },
    '/': {
      component: resolve => require(['./views/upload/index/index.vue'], resolve),
    },
  },
},
```

但是上面的方法导致每个模块都被分割出来了，打包后有 4 个 js 文件
我想实现的效果是把 upload 这个模块打包成一个 js 文件。那么route 应该怎么写才合适呢？

vue-router 是 1.0 版本

感激不尽。

**Comment by fnlctrl** [comment]
请使用[论坛](http://forum.vuejs.org/)或[gitter](https://gitter.im/vuejs/vue)提问。

----------------------

这是webpack的配置，跟vue没有关系，见https://webpack.github.io/docs/code-splitting.html。
