### ISSUE TITLE
同一路由，参数变化问题

### ISSUE THREAD

**Issue by baixiaosh** [vuejs/vue-router#943]
您好：
我在开发过程中遇到一个路由跳转的问题：
比如路由配置为path:'a/:id' 
在这个组件内有<router-link :to="a/2">test</router-link>
访问路由 'a/1' 页面渲染（假设组建渲染后页面很长）
然后滚动到一定距离，点击组件内的 ‘a/2’ 这时候数据更新了（假设组建渲染后页面也很长），但是页面还在原来滚动的位置

https://jsfiddle.net/wj4fxedx/

最后：怎么处理才能让这个组建刷新，就像是新链接进去的呢

**Comment by posva** [comment]
Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

`scrollBehaviour` is what you're looking for: http://router.vuejs.org/en/advanced/scroll-behavior.html

**Comment by baixiaosh** [comment]
scrollBehaviour is don't work

**Comment by baixiaosh** [comment]
https://jsfiddle.net/wj4fxedx/

**Comment by baixiaosh** [comment]
Note: this feature only works in HTML5 history mode.
