### ISSUE TITLE
不使用HTML5 history 模式，怎么实现scrollBehavior功能

### ISSUE THREAD

**Issue by baixiaosh** [vuejs/vue-router#948]
您好：
我需要在url中保留#，并且能使用scrollBehavior功能，怎么实现呢？
https://jsfiddle.net/wj4fxedx/1/

**Comment by fnlctrl** [comment]
你好，请使用[论坛](http://forum.vuejs.org/)或[gitter](https://gitter.im/vuejs/vue)提问，issue列表只用于提交bug和feature request，谢谢！

-------------
可以参考https://github.com/vuejs/vue-router/blob/dev/src/util/scroll-position.js 记录滚动位置，然后在组件的生命周期钩子/beforeEach钩子里用window.scrollTo()设置滚动高度

**Comment by baixiaosh** [comment]
谢谢

**Comment by baixiaosh** [comment]
最后采用的watch->$route里匹配路由 window.scrollTo()设置的
