### ISSUE TITLE
vue-router单独配置router.js，在主js中引用，路由不起作用

### ISSUE THREAD

**Issue by jiangchengshi** [vuejs/vue-router#952]
- main.js

import Routers from "./router.admin";
Vue.use(VueRouter);
const router = new VueRouter({});
Routers(router);

- router.admin.js

import Main from '../components/admin/main.vue';
import User from '../components/admin/user/user.vue';
import UserRole from '../components/admin/user/user_role.vue';
import RoleAuthority from '../components/admin/user/role_authority.vue';

export default function (router) {
    const routes = [
        {
            name: 'main',
            path: '/',
            component: Main
        },
        {
            name: 'user',
            path: '/user',
            component: User
        },
        {
            name: 'user_role',
            path: '/user_role',
            component: UserRole
        },
        {
            name: 'role_authority',
            path: '/role_authority',
            component: RoleAuthority
        }
    ];
    router.options.routes = routes;
    router.beforeEach((to, from, next) => {
        console.info('next...');
        console.info(to);
        console.info(from);
        console.info('next..');
        next();
    });
}

**Comment by yyx990803** [comment]
用法不当。router.options 是只读的，routes 在创建实例时就被注册了。
