### ISSUE TITLE
Is it possible to destroy the router and create a new one ?

### ISSUE THREAD

**Issue by nkostadinov** [vuejs/vue-router#954]
Since we cannot modify the routes at runtime I have the following issue.  A php/ajax application - I load content from ajax containing a Vue app inside with router - its working fine. But when I click a link from the navigation I want to load another page with other router + app inside. Is it possible to destroy the router so I can build a new one and/or whats the best way to achieve this ?

**Comment by LinusBorg** [comment]
No, that's not possible. How should that work in your case, exactly? I don't really understand the usecase.

**Comment by nkostadinov** [comment]
It's a php ajax application with some modules loaded via ajax. I want after I load a module, which is actually a vue component and it has its own internal navigation, to be able to navigate inside the module with vue router. 
When the user clicks on a link in the main menu, I want to destoy this app+router and load another one which has its own routes and components.

**Comment by posva** [comment]
Closed in favour of #888 which was the original request

**Comment by limoli** [comment]
I don't understand. Is it possible to do it or not?

**Comment by posva** [comment]
no, it's not. What is possible is to add new routes
