### ISSUE TITLE
[doc] a link is broken

### ISSUE THREAD

**Issue by esmeetu** [vuejs/vue-router#955]
zh-cn: [docs/zh-cn/api/router-link.md](https://github.com/vuejs/vue-router/blob/dev/docs/zh-cn/api/router-link.md)
行：查看更多关于激活链接类名的例子 [可运行](http://jsfiddle.net/fnlCtrl/dokbyypq/).

en: [router-link](http://router.vuejs.org/en/api/router-link.html)
line: Checkout more examples explaining active link class [live](http://jsfiddle.net/fnlCtrl/dokbyypq/).

**Comment by fnlctrl** [comment]
Thanks! It's fixed now.
