### ISSUE TITLE
Name, params and query as props

### ISSUE THREAD

**Issue by damianstasik** [vuejs/vue-router#956]
It would be awesome if instead of writing this:
```vue
<router-link :to="{ name: 'foo' }">bar</router-link>
```
... we could write something like that:
```vue
<router-link name="foo">bar</router-link>
```
The same rule would apply for the `params` object:
```vue
<router-link name="foo" :params="{ bar: 123 }">bar</router-link>
```

It's cleaner, shorter and more understandable. What do you think? If you want to reject this idea, could you provide an easy way to extend the `router-link` so these changes could be made?

**Comment by yyx990803** [comment]
I feel this is somewhat subjective - personally I like the object format `to` because it is consistent with the argument format for `router.push()`. The props format introduces a different way of doing things but imo not significant value.

As requested, this is how you can extend `router-link` to achieve what you want:

``` js
Vue.use(VueRouter)

// retrive router-link
const Link = Vue.component('router-link')

// overwrite it with your wrapper component
Vue.component('router-link', {
  props: Object.assign({}, Link.props, {
    // your extra props
    path: String,
    name: String,
    params: Object,
    query: Object,
    hash: String
  }),
  render (h) {
    const to = this.to || {
      path: this.path,
      name: this.name,
      params: this.params,
      query: this.query,
      hash: this.hash
    }

    return h(Link, {
      props: Object.assign({}, this.$options.propsData, { to })
    }, this.$slots.default)
  }
})
```
