### ISSUE TITLE
vue-router version 2.1.0 throws ReferenceError

### ISSUE THREAD

**Issue by tmgnpp** [vuejs/vue-router#957]
Hi,

my application is loading vue and the router through two script tags:

```
<script src="https://unpkg.com/vue@next/dist/vue.js"></script>
<script src="https://unpkg.com/vue-router"></script>
```

Since today it throws the following errors:

```
ReferenceError: module is not defined  vue-router:2057:1
ReferenceError: process is not defined   vue-router:521:1
```

Surely some problems with the today's commit.

**Comment by simplesmiler** [comment]
You should src the dist file: `https://unpkg.com/vue-router/dist/vue-router.js`.
Reference: [2.1.0 release notes](https://github.com/vuejs/vue-router/releases/tag/v2.1.0).

---

I would also advise to pin the version (exact or semver) instead of relying on latest or `next`.
