### ISSUE TITLE
Page refresh after params data mixed

### ISSUE THREAD

**Issue by ruofeng086** [vuejs/vue-router#959]
![image](https://cloud.githubusercontent.com/assets/14192308/20737638/ee73abc4-b6e8-11e6-86c7-1fa45feb2da4.png)

This is why?
Where did I go wrong? 
How to solve this problem?

**Comment by fnlctrl** [comment]
Hi, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Thanks!

**Comment by ruofeng086** [comment]
A bit depressed, should not focus on solving this problem?

**Comment by vinicius73** [comment]
If you do not follow the guidelines when creating issues, it is impossible to identify the problem and the solution.
