### ISSUE TITLE
Prevent re-using the same component

### ISSUE THREAD

**Issue by theGC** [vuejs/vue-router#961]
Since `canReuse` was removed (https://github.com/vuejs/vue-router/releases/tag/v2.0.0-beta.1) from vue-router is there a way to force it to create a fresh instance of a component when navigating to a page that uses the same component? Essentially we wildcard CMS pages and use the same component for the entire site (it loads a grid system based on JSON the page receives from an ajax request). In vue-router 0.7.x we could set `canReuse: false` and 2 separate pages from the CMS - which used the same component - could utilise Vues transition system, allowing us to use modes such as 'in-out'. Without `canReuse` I'm not sure Vue has a way of doing this anymore?

**Comment by simplesmiler** [comment]
I think `:key` on `<router-view>` can do that.

**Comment by theGC** [comment]
sorry, what do you mean? what are you binding key to so that Vue will create a new instance of the component?

**Comment by theGC** [comment]
@simplesmiler thank you. Setting the :key to `$route.path` essentially acts exactly as the previous method using `canReuse`. Put together an example fiddle if others need it:

https://jsfiddle.net/thebigsurf/ho9t809w/
