### ISSUE TITLE
Redirects do not work if a redirect has the same path as a child component in history mode

### ISSUE THREAD

**Issue by ghost** [vuejs/vue-router#963]
### Vue.js version
2.0+

### Vue-router version
2.0+

### Reproduction Link
https://jsfiddle.net/2b4f2pxd/2

### Steps to reproduce
1. Go to the page.

### What is Expected?
It redirects twice. Once to parent, once to child.

### What is actually happening?
It does not redirect at all.

### Workaround

A temporary workaround is to add an alias to the child route.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. You should directly put `redirect` inside parent definition:
https://jsfiddle.net/9u8fzcwv/

Side note: You'll see duplicate path warnings if you're using a node environment (webpack/browserify etc)
