### ISSUE TITLE
Suggestion: router.beforeRoute

### ISSUE THREAD

**Issue by vinicius73** [vuejs/vue-router#964]
Currently we need to create rules of the type in each group of routes

```javascript
routes: [{
  path: 'panel/accounts',
  component: AccountsComponent,
  children: [...],
  // access rules
  meta: { rules: ['admin'] },
  // or
  beforeEnter (to, from, next) {
    //...
  },
}] 
```

Initially this approach is efficient, cut in more complex systems can easily become complex, because it is very fragmented.

`router.afterEach` helps a lot, however it is very easy to have a lot of code to keep, with many rules.
`router.beforeRoute` will be a more modular solution

```javascript
router.beforeRoute('panel/*', (to, from, next) =>  {...})
router.beforeRoute('panel/accounts/*', (to, from, next) =>  {...})
router.beforeRoute('accounts/:id', (to, from, next) =>  {...})
```

I believe this is much simpler to maintain and componetize the routes, maybe even helping with integrations with vuex
Issues that may be helped with this: #938 #958

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. If you need a modular solution, you can  simply use [in-component guards](http://router.vuejs.org/en/advanced/navigation-guards.html), and define `beforeRouteEnter` inside components.

**Comment by VladimirCores** [comment]
In component hook `beforeRouteEnter` called before any properties of the component initialized thus VUEX mapActions throw an error.
