### ISSUE TITLE
关于next replace参数的建议

### ISSUE THREAD

**Issue by shusiwei** [vuejs/vue-router#965]
我觉得vue-router 2.1中的next方法中的replace参数应该默认为true，我在项目中所有的beforeRouteEnter发生异常，都要转向到一个替换页面，404或是其它

**Comment by fnlctrl** [comment]
不同场景下的需求不一样，默认参数没有办法满足所有人的需求。

**Comment by shusiwei** [comment]
默认参数不是不能有参数
