### ISSUE TITLE
[bug] `beforeEach` hooks runs twice

### ISSUE THREAD

**Issue by lmk123** [vuejs/vue-router#966]
### Vue.js version

2.1.3

### vue-router version

2.1.0

### Reproduction Link

https://jsfiddle.net/lmk123/qoj2sfb2/

### What is Expected?

Alert should only shown once.

### What is actually happening?

It shown twice.

**Comment by damianstasik** [comment]
The first hook execution is done in `VueRouter.init`:  
https://github.com/vuejs/vue-router/blob/0e319d44102a8ebc07c8a41c437530d86c4b0a73/src/index.js#L75

The second execution is here:  
https://github.com/vuejs/vue-router/blob/a95795c1c59361ab7cc23009ff2e2aecd46827a1/src/history/hash.js#L37

When the url doesn't contain [the hash character](https://github.com/vuejs/vue-router/blob/a95795c1c59361ab7cc23009ff2e2aecd46827a1/src/history/hash.js#L79-L80), it will append `#/` to the url and that will trigger the `hashchange` event which will run `onHashChange` and the second execution.

**Comment by lmk123** [comment]
@visualfanatic Thanks, just now I found this issue is duplicate (#725) and fixed in #735, sorry for my carelessness :joy:
