### ISSUE TITLE
Introduction section is missing in docs.

### ISSUE THREAD

**Issue by potato4d** [vuejs/vue-router#971]
"Introduction" section content is only written filename "SUMARRY.md";

Is there something wrong with the setting of GitBook?

<img width="1440" alt="2016-12-02 12 32 16" src="https://cloud.githubusercontent.com/assets/6993514/20822169/dcb7d762-b88b-11e6-8c29-af74c555985c.png">

**Comment by kazupon** [comment]
Thank you for your feedback!

I guess that introduction section is broken with this https://github.com/vuejs/vue-router/commit/3cefd559fd9d80f2dfa7b4d82a0a8237885471e0

the following this issue file:
https://github.com/vuejs/vue-router/commit/3cefd559fd9d80f2dfa7b4d82a0a8237885471e0#diff-27f563ae0dc0308043bf87e1805ac098R478

**Comment by fnlctrl** [comment]
Hmm that's strange... I was just re-deploying it after fixing a dead jsfiddle link. I'm looking into it..

**Comment by fnlctrl** [comment]
Fixed now.

It seems that on windows, referencing other files by only including their names (in this case, "SUMMARY.md" inside "README.md") doesn't work... And I couldn't find any gitbook documents about this usage, so I don't know how it worked on other systems (and also in vuex's repo) 😢. Fortunately there is a documented way to do that: http://toolchain.gitbook.com/templating/conrefs.html

@kazupon Maybe we should also update vuex's docs to use the above method for importing files? That seems the proper way of doing it..

**Comment by kazupon** [comment]
@fnlctrl 
As far as I checked, vuex's repo don't need to change.
In vuex's repo, `READEME.md` is not symbolic link.

However, In vue-router repo,  `README.md` Still use the symbolic link.
I fixed and pushed the PR.

https://github.com/vuejs/vue-router/pull/982
