### ISSUE TITLE
lazy-load and data-fetch can't be used concurrently

### ISSUE THREAD

**Issue by NadokaCiel** [vuejs/vue-router#972]
when **lazy-load** route components:
```
const Board = resolve => require(['../components/Board.vue'], resolve)

{ path: '/board/:boardType',name:'boardList', component: Board}
```
and **data-fetch:**
```
watch: {
    // call again the method if the route changes
    '$route': 'getBoard'
  },
```
then change url only with params,such as:
board/1
board/2

and it failed to **watch** the change,
does't call method **getBoard**
and I've tried to use hook **beforeRouteEnter**，still not working
switch back to：
`import Board from '../components/Board.vue'`
it's alright again

maybe it's caused by lazy-load?
thanks for your attentionO(∩_∩)O

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a repo on github for reproduction. Thanks!

**Comment by NadokaCiel** [comment]
Please see：
[vue-router-data-fetch-issue](https://github.com/NadokaCiel/vue-router-data-fetch-issue)
when using lazy load to pack component separately，it will stop rending and show no error message
or I just do it wrong……？
Thanks for your time~

**Comment by fnlctrl** [comment]
That's a known webpack 2.0 lazy load issue: the return value of `require` becomes undefined after the first call. As a workaround, you'll have to use webpack 2.0's `System.import()`instead of `require`
Detailed explanation: https://github.com/vuejs/vue-router/pull/862
Webpack docs: https://gist.github.com/sokra/27b24881210b56bbaff7#code-splitting-with-es6

**Comment by NadokaCiel** [comment]
So it's caused by webpack,I see……
Thanks a lotO(∩_∩)O!
