### ISSUE TITLE
Why can't a component be referenced by string id?

### ISSUE THREAD

**Issue by akoumjian** [vuejs/vue-router#975]
A recent change to router asserts that the component argument of a path object cannot be a string id. Does this mean it's not possible to use global components created via `Vue.component()` as a router view?

Here is the new assertion in question: https://github.com/vuejs/vue-router/blame/dev/dist/vue-router.js#L528

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. It's actually a fixed bug:

Quote from Evan:

> FYI using string ID for component was never intended to be supported - it worked in some cases by accident. The documentation also had a misleading comment. In the future it will be explicitly warned against.

https://github.com/vuejs/vue-router/issues/930

**Comment by simplesmiler** [comment]
Global components can still be used as router views, via `{ ..., component: Vue.component(name) }`.

**Comment by akoumjian** [comment]
I see, thank you @simplesmiler . I guess the idea is that you want to pass in a specific instance of a Vue, and since I'm new I didn't realize that was how you could instantiate them.
