### ISSUE TITLE
直接克隆的项目初始化之后不能正常运行？

### ISSUE THREAD

**Issue by Jiiiiiin** [vuejs/vue-router#980]
jiiiiiin@ZhaoJins-MBP:~/Develop/WebstormProjects/vue-router|dev⚡
⇒  cnpm install
✔ All packages installed (use 49ms, speed 0B/s, json 0(0B), tarball 0B)
jiiiiiin@ZhaoJins-MBP:~/Develop/WebstormProjects/vue-router|dev⚡
⇒  npm run dev

> vue-router@2.1.1 dev /Users/jiiiiiin/Develop/WebstormProjects/vue-router
> node examples/server.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1376:9)
    at Function.listen (/Users/jiiiiiin/Develop/WebstormProjects/vue-router/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/Users/jiiiiiin/Develop/WebstormProjects/vue-router/examples/server.js:29:22)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.1.0/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! vue-router@2.1.1 dev: `node examples/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-router@2.1.1 dev script 'node examples/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-router package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node examples/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-router
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-router
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jiiiiiin/Develop/WebstormProjects/vue-router/npm-debug.log
jiiiiiin@ZhaoJins-MBP:~/Develop/WebstormProjects/vue-router|dev⚡

@wprater 为啥？

**Comment by fnlctrl** [comment]
> Error: listen EADDRINUSE :::8080

端口被占用
