### ISSUE TITLE
Can't access subroutes as entry point/HR not working when in subroute

### ISSUE THREAD

**Issue by murbanowicz** [vuejs/vue-router#981]
Vue & Vue-router all up to date (2+)

I have my routes:
```
{
      path: '/panel',
      component: panel,
      beforeEnter: reqAuth,
      children: [
        { path: '', component: epPanelHome },
        { path: 'events', component: epPanelEvents },
        { path: 'groups', component: epPanelGroups }
      ]
    },
```

I can't run app from link: `localhost:8080/panel/events` or `groups` 

I can access `localhost:8080` or `localhost:8080/panel` but not any subroute... 
I can run subroutes with links  and it's working  ok (almost)

The issue is somehow about config or something? 
`GET http://localhost:8080/panel/js/app.js ` when I think it should not add `/panel`

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. You'll need a HTML5 History API compatible server, checkout the section here:
http://router.vuejs.org/en/essentials/history-mode.html#example-server-configurations

**Comment by murbanowicz** [comment]
Ah ok. Thank you.
IS it possible to get history mode working with webpack dev server or for dev I have to use hashmode ?

**Comment by fnlctrl** [comment]
Yeah, just add this to your webpack config:
```
{
   ...
    devServer: {
        historyApiFallback: true,
    },
}
```

More info: https://webpack.github.io/docs/webpack-dev-server.html#the-historyapifallback-option
