### ISSUE TITLE
Navigating to fragment identifier

### ISSUE THREAD

**Issue by callumacrae** [vuejs/vue-router#985]
Hey!

I'm trying to add a "skip to main content" link to my site for screenreaders, but it isn't working with vue-router. I'm not using HTML5 history mode, so any links with hashes in are being intercepted by the router, and a 404 page is being displayed.

Is it impossible to link to sections of a page when not using the html5 history mode?

vue-router 2.

Callum

**Comment by fnlctrl** [comment]
Sorry, using hash as anchor is only supported in html5 history mode, since in hash mode the router cannot differentiate routes from anchors.
