### ISSUE TITLE
Alias does not support nested routes

### ISSUE THREAD

**Issue by lifeforfun** [vuejs/vue-router#987]
Demo is here: [codepen](http://codepen.io/HugeWorld/pen/gLeKoN)
Component **/a/add** has an alias **/a/edit** but its children does not inherit its alias like **/a/edit/campaign** 、 **/a/edit/ad_group**、**/a/edit/keyword** . They only has their default path **/a/add/campaign**、**/a/add/ad_group**、**/a/add/keyword**

My english doesn't well, so I translate it into Chinese in case of viewer can not understand.
**中文版(如果上面的没看明白请看下面的解释)**
组件指定了别名后其子组件并没有继承这个别名，比如路由**/a/**下的子路由**add** 指定了别名为**edit**, 然后**add**路由下又有子路由**campaign**、**ad_group**、**keyword**. 这三个路由并没有继承路由**add**添加的这个别名,即**/a/edit/campaign**、**/a/edit/ad_group**、**/a/edit/keyword**

**Comment by LinusBorg** [comment]
I just tried this, seems to be a bug indeed.
