### ISSUE TITLE
sorry, I am english is not good

### ISSUE THREAD

**Issue by SPACEX-2022** [vuejs/vue-router#993]
我就想问问官网的[http://router.vuejs.org/zh-cn/advanced/data-fetching.html#](url)
其中  进阶->数据获取  里面有段话是不是写错了

> 当你使用这种方式时，我们会马上导航和渲染组件，然后在组件的 create 钩子中获取数据。这让我们有机会在数据获取期间展示一个 loading 状态，还可以在不同视图间展示不同的 loading 状态。
这里的create钩子应该是created钩子吧?

**Comment by fnlctrl** [comment]
Thanks, fixed.
