### ISSUE TITLE
Using router-link "events" property for a double click event doesn't work.

### ISSUE THREAD

**Issue by dschissler** [vuejs/vue-router#994]
Based upon the 2.1 documentation I would expect : <router-link :to="to" events="dblclick" exact> to only trigger on the dblclick event instead of click, but this doesn't change the default behavior to fire on double click. If this is not the intention of the events property then this has not been made clear in the documentation.

I'm currently enjoying being able to wrap around router-link instead of needing to handle anchor events and to then call e.preventDefault(). However, without either better documentation of this feature or a patch to provide it then it will be a large dead end for me.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a live reproduction on jsfiddle, codepen etc. Thanks!

**Comment by dschissler** [comment]
I'm closing this issue until I can create a reproduction and then I will reopen it.
