### ISSUE TITLE
Bootstrap theme dont work with vue-router

### ISSUE THREAD

**Issue by pascencio** [vuejs/vue-router#999]
Hi guys!

I'm using this components on my project:

- Gentellela Bootstrap 3 Theme
- Vue.js
- Vue Router
- Material Desing for Bootstrap 3

When I follow the getting started example from the vue-route [page](https://router.vuejs.org/en/essentials/getting-started.html) getting some issues with some anchors on the **Gentellela Theme**.
If I use the app id on the root div in the page, all anchors seems to be "blocked", but if I use the app id inside a div located in the page content section on the them works.

**I'm neebie using Vue and Vue Router, please I need help!**

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only, and we encourage you to use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions or for discussion. Thanks!

**Comment by pascencio** [comment]
Thanks @fnlctrl I will try gitter.

Bye!
